### ISSUE TITLE
Upgrade OpenSSL bundled with windows to 1.1.1s

### ISSUE THREAD

**Issue by mattip** [python/cpython#100180]
# Enhancement

The version of OpenSSL used in [get_externals.bat](https://github.com/python/cpython/blob/c0859743d9ad3bbd4c021200f4162cfeadc0c17a/PCbuild/get_externals.bat#L80) is 1.1.1q, where 1.1.1s has been released. This in turn pulls from https://github.com/python/cpython-bin-deps/tree/openssl-bin, which was last updated by @zooba to 1.1.1q

# Pitch

It would be nice to get the latest updates. Looking at the [changelog](https://www.openssl.org/news/cl111.txt) I don't see anything critial for windows, so maybe 1.1.1q is still OK, in which csae feel free to close the issue.

# Previous discussion

### Linked PRs
* gh-100901
* gh-100902
* gh-100903
* gh-100904
* gh-100908
* gh-100909
* gh-100910
* gh-101258
* gh-101259

**Comment by zooba** [comment]
Agreed that there's nothing critical in there, but since you've created the issue, let's keep this open so we remember to update before the next round of releases.

We just released every version last week, so I'll mark this as a blocker before the next release (apart from the next 3.12 alpha), as there's a pretty good chance we'll get 1.1.1t before then.

**Comment by Yhg1s** [comment]
Since 3.12.0a4 is scheduled for today, do you want to get this done before I cut the release, @zooba?

**Comment by zooba** [comment]
@Yhg1s I'll get on it now

**Comment by ned-deily** [comment]
We should also update the macOS installer as well. I'll do that and test it before tomorrow's release.

**Comment by mattip** [comment]
Closing as complete. Please reopen if I am mistaken.
