### ISSUE TITLE
Remove `yield from` usage from asyncio tests

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#100113]
Support for `yield from` was deprecated and removed so it should be removed. 

See https://github.com/python/cpython/blob/cd67c1bb30eccd0c6fd1386405df225aed4c91a9/Lib/test/test_asyncio/test_tasks.py#L2093-L2100

### Linked PRs
* gh-100114

**Comment by vstinner** [comment]
There are a few ``yield from`` in asyncio tests (Lib/test/test_asyncio/):

```
test_futures.py:296:            x = yield from f
test_futures.py:298:            y = yield from f
test_futures.py:303:        self.assertEqual(next(g), f)  # First yield from f.
test_futures.py:306:        # The second "yield from f" does not yield f.
test_futures.py:408:            yield from fut
test_pep492.py:152:            yield from ()
test_sslproto.py:99:        # yield from waiter hang if lost_connection was called.
test_tasks.py:2096:                return (yield from fut)
utils.py:271:            yield from _run_test_server(address=path, use_ssl=use_ssl,
utils.py:278:    yield from _run_test_server(address=(host, port), use_ssl=use_ssl,
```

**Comment by kumaraditya303** [comment]
> There are a few yield from in asyncio tests (Lib/test/test_asyncio/):

I think those are testing the internal implementation of futures and they are not used with asyncio APIs. I don't think they should be changed to await.

**Comment by gvanrossum** [comment]
There's a comment referencing `yield from` on line 66 of asyncio/futures.py that probably should be updated, if indeed we are dropping (or have dropped) `yield from` support. Similar on line 292 (seems to refer to the same thing).

Next, in asyncio/tasks.py, line 316 there's an error message complaining about `yield` instead of `yield from`. Should that be `await` too? Again on line 327. The same error messages also occur in _asynciomodule.c.

Then there's `_wrap_awaitable()`, also in tasks.py, which on line 687 has a `yield from`.

But maybe I'm not understanding how `yield from` is used here???

**Comment by kumaraditya303** [comment]
> Then there's _wrap_awaitable(), also in tasks.py, which on line 687 has a yield from.

This has been removed now. 

> Next, in asyncio/tasks.py, line 316 there's an error message complaining about yield instead of yield from. Should that be await too? Again on line 327. The same error messages also occur in _asynciomodule.c.

That's debugging aid for people who are writing their own awaitables with custom `__await__` method.

**Comment by kumaraditya303** [comment]
Closing this, anythig left can be handled in https://github.com/python/cpython/issues/102748
