### ISSUE TITLE
Dynamic lambda expressions get shared reference when built during loop.

### ISSUE THREAD

**Issue by jarekwg** [python/cpython#100170]
Minimal reproducible case:
```python
funcs = []
for i in [1, 2]:
    funcs.append(lambda: i)

print([f() for f in funcs])
```
result:
```python
[2, 2]
```
expected result:
```python
[1, 2]
```

Something is getting a shared reference...
The `id`s of the two functions are distinct, so it's not that.

A way around this is to "build" the lambda outside of the loop, like this:
```python
def build_lambda(i):
    return lambda: i

funcs = []
for i in [1, 2]:
    funcs.append(build_lambda(i))

print([f() for f in funcs])
```

I assume this is rare, as lambdas are generally consumed immediately, rather than getting stored like this. However it's still very much unexpected behaviour.

Reproduced on *Python 3.10.7*, *Python 3.11.0*

**Comment by TeamSpen210** [comment]
This is intentional behaviour. For loops don't create their own scope, so there's only one `i` variable in the first example, which both lambdas will share. It's more obvious if you unroll the loop:
```py
funcs = []
i = 1 
funcs.append(lambda: i)
i = 2
funcs.append(lambda: i)
```
In the second case, calling the function produces a new local scope and therefore a new distinct `i`, so this isn't an issue. Another workaround is to use default variables: `lambda i=i: i`, or to use `functools.partial`. Both do early binding, so the value is fixed and won't change.

There's a further explanation in [the Python FAQ](https://docs.python.org/3.11/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result).
