### ISSUE TITLE
struct.pack() unexpected extra bytes

### ISSUE THREAD

**Issue by ryi3r** [python/cpython#100285]
```
>>> import struct
>>> struct.pack("HL",0xFF,0xFF)
b'\xff\x00\x00\x00\xff\x00\x00\x00'
```
It should return `b'\xff\x00\xff\x00\x00\x00'`, but instead it doesn't.

**Comment by pochmann** [comment]
> It should return `b'\xff\x00\xff\x00\x00\x00'`

Says who? [The documentation](https://docs.python.org/3/library/struct.html#format-characters) says it's platform-dependent.

**Comment by ZorroMundoYT** [comment]
If I do `struct.pack("H",0xFF)+struct.pack("L",0xFF)` it actually returns me the right value.

**Comment by ericvsmith** [comment]
The difference between `struct.pack("HL",0xFF,0xFF)` and `struct.pack("H",0xFF)+struct.pack("L",0xFF)` is due to alignment issues on your platform and C compiler (neither of which you have mentioned). Padding bytes are added to align the second field to the platform's expected alignment.

From the docs, there are these notes "Native size and alignment are determined using the C compiler’s sizeof expression. This is always combined with native byte order." and "Padding is only automatically added between successive structure members. No padding is added at the beginning or the end of the encoded struct."

You can test this by writing a C program and checking sizeof on a struct with an unsigned short and a unsigned long. It should show 8 bytes. Be sure to use the same C compiler that python is using.

So I don't see a bug here and I'll close this. If your test C shows something different, please post here and we can revisit it.
