### ISSUE TITLE
[Quickstart tutorial]: typo in section on strings?

### ISSUE THREAD

**Issue by 011-X** [python/cpython#100245]
# Documentation

Seems to be a typo in the quick start tutorial under the strings section. 
Current code:
```python 
print("""\
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to
""")
```
I may be wrong but I feel it should be:
```python
print("""
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to\
""")
```

**Comment by rhettinger** [comment]
Thanks for the suggestion, but the example is correct.  The backslash causes the initial newline to be skipped.  This is a common practice.

**Comment by busywhitespace** [comment]
Hi @rhettinger , I agree with you, but @011-X also has a point.

The documentation says that the output of the aforementioned **print** is

<pre>Usage: thingy [OPTIONS]
 -h                        Display this usage message
 -H hostname               Hostname to connect to</pre>

But when the last newline is not escaped, the real output of **print** has two newlines at the end, because by default the **print** adds '\n' at the end. So that could've confused @011-X , but it is just my guess.

If I'm mistaken, I'm sorry for bothering you.
