### ISSUE TITLE
Silent grab external dependency from libuuid during build without possibility to disable it

### ISSUE THREAD

**Issue by VVD** [python/cpython#100369]
# Bug report

During build process of the python it silent grab external (not in base system, but installed from ports) dependency from `libuuid` (`misc/e2fsprogs-libuuid`):
```
checking uuid.h usability... yes
checking uuid.h presence... yes
checking for uuid.h... yes
checking for uuid_generate_time_safe... no
checking for uuid_generate_time in -luuid... yes
checking for uuid_create... yes
checking for uuid_enc_be... yes
```
Without `libuuid` (`misc/e2fsprogs-libuuid`) installed:
```
checking uuid.h usability... yes
checking uuid.h presence... yes
checking for uuid.h... yes
checking for uuid_generate_time_safe... no
checking for uuid_generate_time in -luuid... no
checking for uuid_create... yes
checking for uuid_enc_be... yes
```

And it's impossible to disable this behavior without additional patches to configure script.

# Your environment

- CPython versions tested on: 3.10.9
- Operating system and architecture: FreeBSD 13.1-p5 amd64

IMHO, best solution is to add an options to configure script, for example: `--disable-libuuid` and `--enable-libuuid`.
Additionally: base system have `uuid.h` and `misc/e2fsprogs-libuuid` have `uuid/uuid.h` - better check for `uuid.h` if `--disable-libuuid` used and for `uuid/uuid.h` if `--enable-libuuid`.

P.S. Sorry for my poor english.

**Comment by eli-schwartz** [comment]
Reading the code for configure.ac, I am pretty sure this is not an issue anymore since GH-29741, which cleaned up the uuid module in a couple ways including refactoring the configure checks to use pkg-config.

A side effect of this is that it actually checks properly for different providers of uuid -- and if it finds the FreeBSD base system version of uuid.h, it marks it as found and doesn't attempt to either probe it with pkg-config, or fall back on AC_CHECK_LIB. Therefore it won't ever find it in ports.

**Comment by eli-schwartz** [comment]
Dunno if that's worth backporting from 3.11 to 3.10, at the very least that commit would need to be reduced and only part of it applied.

**Comment by VVD** [comment]
> Dunno if that's worth backporting from 3.11 to 3.10, at the very least that commit would need to be reduced and only part of it applied.

Look like not backported yet.

**Comment by VVD** [comment]
ping
