### ISSUE TITLE
pathlib.PurePath.as_uri() and __bytes__() are impure

### ISSUE THREAD

**Issue by barneygale** [python/cpython#100415]
`pathlib.PurePath.as_uri()` and `__bytes__()` use `os.fsencode()` to encode paths, which makes their results vary from system to system. In pathlib parlance these methods are "impure", and so they rightfully belong to the `Path` class, not the `PurePath` class.

Furthermore, the `as_uri()` method may confuse users if we add an `AbstractPath` class that sits between `PurePath` and `Path`, as the default implementation would provide a `file://` URI in a naive user subclass such as `S3Path` or `FTPPath`. I think this helps demonstrate that `file://` URIs really are a _local_ filesystem feature, and so should not be implemented in `PurePath`.

Proposal: emit deprecation warnings from `as_uri()` and `__bytes__()` unless `isinstance(self, Path)`. In a future version of Python, move the implementations into `Path`.

**Comment by brettcannon** [comment]
I'm not sure if it's worth the disruption to change this as that method has been like that for 5.5 years and no one has filed a bug due to the fact that it is in any way platform-dependent; "practicality beats purity". I am totally fine with adding a note to the docs, though, pointing out the fact that `__bytes__()` is platform-dependent.

Personally, I have always viewed `PurePath` as not interacting with the file system, not being isolated from the system itself.

**Comment by barneygale** [comment]
Fair. I suspect this might become more pressing if/when we add `AbstractPath`, but until then it's very minor.
