### ISSUE TITLE
inspect.getattr_static vs getattr returns different result

### ISSUE THREAD

**Issue by yanboliang** [python/cpython#100418]
# Bug report

Repro:
```
class MyClass(object):
    def __init__(self, x):
        self.x = x

    def add(self, y):
        return self.x + y

a = MyClass(2)

print(inspect.getattr_static(a, "add"))
print(getattr(a, "add"))
```
Result:
```
<function MyClass.add at 0x7fec4ebe9310>
<bound method MyClass.add of <__main__.MyClass object at 0x7fec4fca3490>>
```

I'm not sure if this is a bug, but I'd like to understand the reason behind the difference. Since ```function``` and ```bound method``` are different type in Python, I think it should be a ```bound method``` in my case, but why ```inspect.getattr_static``` return ```function``` type?

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by AlexWaygood** [comment]
This isn't a bug. This is because functions in Python are descriptors (they define the `__get__` method). Because of this, the call `getattr(a, "add")` is translated into something like the following:

```python
type(type(a).__dict__["add"]).__get__(type(a).__dict__["add"], a, type(a))
```

`inspect.getattr_static()`, by contrast, bypasses the normal hook for `__get__` that's used by `getattr()` and any normal dotted lookup. That's deliberately part of the design of `inspect.getattr_static()`.

If you'd like to learn more about descriptors in Python, I recommend the [Descriptors HOWTO doc](https://docs.python.org/3/howto/descriptor.html#id1). If you still have questions after that, I'd recommend asking them over at https://discuss.python.org/c/users/7.
