### ISSUE TITLE
Float documentation doesn't allow int-like strings as valid arguments for float

### ISSUE THREAD

**Issue by stevendaprano** [python/cpython#100428]
[The documentation for `float`](https://docs.python.org/3/library/functions.html#float) doesn't explicitly allow int-like strings, although it does give one as an example. E.g. although `float('10')` works and returns a float, the documentation implies that it shouldn't.

See [discussion on Discuss](https://discuss.python.org/t/is-it-legal-valid-to-use-float-to-convert-a-string-containing-integer-to-float/22114).

### Linked PRs
* gh-100436
* gh-100437
* gh-100510
* gh-100511
* gh-100674
* gh-100675

**Comment by mdickinson** [comment]
Maybe remove the indirection (the reference to floating-point literals) from the current documentation and give a direct description of what's permitted instead? That way the information is all in one place. The current documentation feels as though it was a shortcut taken for ease of documentation _writing_ rather than ease of documentation reading.

On the other hand, it's definitely useful for users to know that any string that's acceptable as a floating-point literal is _also_ acceptable as a string argument to `float`.

**Comment by hauntsaninja** [comment]
There are inaccuracies in the `int` documentation too, for instance, the handling of leading zeros isn't really described. Also the following isn't correct:
>  Base 0 means to interpret exactly as a code literal

```
>>> s = "२३४५६७८९"
>>> int(s, 0)
23456789
>>> eval(s)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    २३४५६७८९
    ^
SyntaxError: invalid character '२' (U+0968)
```
