### ISSUE TITLE
eval() documentation is wrong about keyword arguments

### ISSUE THREAD

**Issue by wjandrea** [python/cpython#100546]
# Documentation

[The docs for `eval()`](https://docs.python.org/3/library/functions.html#eval) say it takes keyword arguments, which is incorrect:
```
eval(expression, /, globals=None, locals=None)
```

For example:
```
>>> eval('a', locals={'a': 0})
  ...
TypeError: eval() takes no keyword arguments
```

Meanwhile, `help(eval)` has the correct signature:
```
eval(source, globals=None, locals=None, /)
```

I found a previous, similar issue, #69996, which was resolved in #15173 (which shipped in 3.7) but then the syntax was changed in #96579 and [the same sort of mistake was added back](https://github.com/python/cpython/commit/3c4cbd177f36777a04e78eb07ce20367560a66d3#diff-6a7a07ac473fdd76734669b1b70626ad2176011129902f6add017810f54d0439R515) (which shipped in 3.11).

This issue is also similar:
- #67926

### Linked PRs
* gh-100547
* gh-100654

**Comment by hauntsaninja** [comment]
Thanks for the report!

cc @JulienPalard the history here is confusing, would you mind posting on https://github.com/python/cpython/issues/98340 what the current state of using positional-only (and keyword-only) markers in docs is? I still see four positional-only markers in functions.rst (only eval's seems to be in the wrong place)

**Comment by slateny** [comment]
There are some comments by Raymond on https://github.com/python/cpython/pull/100444, so one possible guideline for markers is the same for spelling/stylistic rules, where it just needs to be consistent per module instead of for all modules.

That said, I think it'd nonetheless be useful to have a deeper discussion on this for consistency and properly documenting default values, whether it be via markers, or `[]`, or otherwise.
