### ISSUE TITLE
[Bug] An error occurred in the installation file

### ISSUE THREAD

**Issue by CoolPlayLin** [python/cpython#100597]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

![image](https://user-images.githubusercontent.com/96709586/209895348-e896c8f0-c9fd-4848-abf0-35b2ae15684d.png)

When I use the Python 3.11.1 installer to upgrade Python 3.11.0 in my computer, I start Python and it says that I can't find the Python 311 .dll, so I look through the Python installation directory.

**The installer for Python 3.11.1 seems to be wrong**

![image](https://user-images.githubusercontent.com/96709586/209895109-56b768ef-3fb9-49d1-983b-2091b3197f91.png)

**Comment by CoolPlayLin** [comment]
I tried reinstalling, but:
![image](https://user-images.githubusercontent.com/96709586/209895517-fd1418be-8333-41b8-8d91-87209ce7ca71.png)
![image](https://user-images.githubusercontent.com/96709586/209895587-cde1f9f0-88d0-4d5c-b2fe-a17027166483.png)
![image](https://user-images.githubusercontent.com/96709586/209895603-bcb6d03b-f806-42d6-b030-27c93ef3036e.png)

**Comment by CoolPlayLin** [comment]
@hauntsaninja Are you there?

**Comment by hauntsaninja** [comment]
Here in what sense? I can't read Chinese and I don't have access to a Windows system, so I'm not really able to do much.

If you're just looking for help, discuss.python.org or StackOverflow are the best places to get help.

**Comment by CoolPlayLin** [comment]
@hauntsaninja Error window prompt: [Python.exe - System error] Unable to continue executing code due to Python 311.dll not found, reinstalling the program may resolve this issue.

**Comment by CoolPlayLin** [comment]
You can also look at the installation directory behind, there is no dll file in it, this is the screenshot after the installation is successful, I did not make any modifications.

**Comment by CoolPlayLin** [comment]
@hauntsaninja 
You can also look at the installation directory behind, which is missing many dll files compared to Python 3.10, this is the screenshot after the installation is successful, I did not make any modifications.

**Comment by CoolPlayLin** [comment]
@hauntsaninja I feel like you can find an expert who has access to Windows to solve the problem.

**Comment by CoolPlayLin** [comment]
@AlexWaygood May you help me?

**Comment by CoolPlayLin** [comment]
https://user-images.githubusercontent.com/96709586/210125161-47fb2c80-7cb9-4348-b70a-13d0c82d566a.mp4

**Comment by AlexWaygood** [comment]
> @AlexWaygood May you help me?

No. Unlike Shantanu, I have access to a Windows machine, but I'm neither a Windows expert nor an installation expert.

We have added the appropriate labels so that people who know how to fix this issue will see the issue.

**Comment by CoolPlayLin** [comment]
@vstinner May you help me?

**Comment by CoolPlayLin** [comment]
@rhettinger Could you help me?

**Comment by CoolPlayLin** [comment]
Any update?

**Comment by zooba** [comment]
To investigate this, we need you to start on a clean machine (make sure all old Python installs are removed, all registry keys cleaned up, etc.), and then explain the sequence of installs/uninstalls/repairs you are following. It will be easiest if you replicate it and upload all of the Python install logs from your `%TEMP%` directory.

Without the logs, we have to guess what's going on. Since this isn't happening to anyone else, instructions likely aren't going to help, because there must be something unusual on your machine. So if you can get the logs, we can help.

Pinging random contributors will not get you help. If anything, you've been ignored on purpose because of doing it. Please don't do it anymore. I will help, as long as you can run the installs yourself and upload all your logs to this issue (put them in a zip file and drag-drop into the text box when writing your next reply).
