### ISSUE TITLE
Bypassing data between classes containing array elements

### ISSUE THREAD

**Issue by amaciasmedri** [python/cpython#100558]
# Is this a Bug? or does exist any documentation about it?

The following code was implemented on an Arch Linux distribution and Python v3.10.

```python
class Array:
    def __init__(self, A: list = []):
        self.A: list = A


Temp = Array()
Temp.A.append(123)
BUG = Array()
print(BUG.A)  # Output: [123]
BUG.A[0] = -654
print(Temp.A)  # Output: [-654]
```

From my point of view, the pointer of element `A` was copied from `Temp` to `BUG` when the `__init__` method was executed.
The initialization process with the default value `A=[]` in the constructor was omitted for the `BUG` object, instead, it was copied the previous pointer catched by the constructor. Some privileges between objects could be bypassed with this drawback.

#bypassing #class #array

**Comment by AlexWaygood** [comment]
Not a bug https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument

If you have further questions after reading the above, the better place to ask them is https://discuss.python.org/c/users/7. The GitHub issue tracker is for discussing bugs in CPython.

**Comment by stevendaprano** [comment]
Further to what @AlexWaygood says, this feature of Python has been around literally since the first version of the language. There is a [FAQ about it](https://docs.python.org/3/faq/programming.html#why-are-default-values-shared-between-objects), and it was recently discussed [in this ticket](https://github.com/python/cpython/issues/99142#issuecomment-1304669043).
