### ISSUE TITLE
Double Tk events

### ISSUE THREAD

**Issue by mrJean1** [python/cpython#100588]
# Bug report

Python/Tk generates double events for menu items with certain shortcut keys defined with the Shift modifier in the Tk bind call.  

For example, a shortcut key `Command-Shift-plus` generates a Menu event _PLUS_ a KeyPress event when that key combination is pressed.

# Your environment

The problem occurs only with recent Python releases, only on (recent) macOS versions and both on Intel and Apple Silicon.  

Attached is a script `tkShift.py` to reproduce the problem.  It includes details about the Python, macOS and Windows versions used for testing.

[tkShift.py.zip](https://github.com/python/cpython/files/10315512/tkShift.py.zip)

**Comment by mrJean1** [comment]
Following the suggestion from issue #67317 to eliminate Python and `tkinter`, below is a Tcl/Tk script (named `tkShift.tcl`) exhibiting double events for Shift shortcuts.  However, double events only occur with the `bind .win <...> Key` line.   _Not_ when using the `bind . <...> Key` line.
```
# run this Tcl/Tk script from python as

# >>> import tkinter
# >>> r = tkinter.Tk()
# >>> r.tk.eval('source tkShift.tcl')

# then click the menu item and enter the shortcut.

toplevel .win
menu .win.menubar
.win configure -menu .win.menubar

set mb .win.menubar
menu $mb.file
$mb add cascade -menu $mb.file -label Test

$mb.file add command -label "Item" -command "Item"
$mb.file entryconfig "Item" -accelerator "Command+Shift++"

# bind .  <Command-Shift-plus> Key  # single event
bind .win <Command-Shift-plus> Key  # double events

proc Item {} {puts "Menu"}
proc Key {} {puts "Key"}
```

**Comment by ronaldoussoren** [comment]
What's the version of Tk used by the Python installations with and without the issue? This version is reported by ``python -m test.pythoninfo`` (Tk versions are near the end).

**Comment by mrJean1** [comment]
Attached is the `tkShift.py` script updated with the `Tcl/Tk` and `tkinter` versions from
```
%  python -m test.pythoninfo | grep tkinter
```
at the Python releases used.  All are
```
tkinter.TCL_VERSION: 8.6
tkinter.TK_VERSION: 8.6
tkinter.info_patchlevel: 8.6.8, 8.8.11 or 8.6.12.
```

[tkShift.zip](https://github.com/python/cpython/files/10327577/tkShift.zip)

**Comment by ronaldoussoren** [comment]
When using Python 3.12 with Tcl/Tk 8.6.13
With tkShift.py:
- "-A":  only a keypress event when using the shortcut, no menu event
- "-B": likewise
- "-C": no reaction on using the shortcut
- 
With Python 3.10 and Tcl/Tk 8.6.12 I do get both events in the "-A" and "-B" cases and once again no reaction in the "-C" case.

With tkShift.tcl script and Python 3.12:
- as included I get "Menu" when explicitly selecting the menu, and "Key" when using the keyboard shortcut
- commenting out the "bind .win" results in no output when using the keyboard shortcut, although the system clearly detects that a menu shortcut is used because the "Test" menu gets highlighted. This happens both with and without uncommenting the "bind . " line. 

With 3.10 I get duplicated events in the first case.


This likely is an issue with Tk on macOS, or maybe "was an issue" as I'm not familiar enough with Tkinter to say if the behaviour I'm seeing with Python 3.12 is correct or not.

**Comment by serhiy-storchaka** [comment]
Tkinter doesn't add anything fancy here. This must be a Tk issue.
