### ISSUE TITLE
reduce documentation argument signature is incorrect.  

### ISSUE THREAD

**Issue by anirban-s** [python/cpython#100548]
# Documentation
reduce(function, iterable[, initial]) -> value 

This signature is right and very confusing in my opinion. Can I make pull request to rectify the code to reduce(function, iterable, initial) -> value

**Comment by sobolevn** [comment]
`[, initial]` is used in many places where some argument is optional. But, when it does not have explicit python default value. In this case it is `PyObject *result = NULL;`

So, using `reduce(function, iterable, initial) -> value` is not correct here. Because it implies that `reduce` has three arguments, while it can be called with just two.

**Comment by rhettinger** [comment]
I concur with Nikita.  The docs are correct as-is.
