### ISSUE TITLE
comparing class `__main__.Class is Class` is False

### ISSUE THREAD

**Issue by nmnsnv** [python/cpython#100672]
# Bug report

When comparing a class (A, defined in __main__) with itself imported through import we receive `False` 

```python
# File name: "main.py"
import main

class A:
    pass

if __name__ == "__main__":
    # prints False
    print(A is main.A)
```
Reproduce:
```bash
> python3 ./main.py
False
```

# Your environment

- CPython versions tested on: 3.8.10
- Operating system and architecture: Linux Mint x64

**Comment by FrozenBob** [comment]
This is not a bug. Your circular import has created two versions of your `A` class, and `A` is indeed not `main.A`. `A` is `__main__.A`, because your file is running as `__main__` when you run it directly.

I'd prefer if Python used a different way of distinguishing the main script that didn't create these "evil twin" modules on circular import, but this is the design.
