### ISSUE TITLE
[tutorial/classes.html] Is it appropriate to put dataclasses in `Odds and Ends` section?

### ISSUE THREAD

**Issue by peterjpxie** [python/cpython#100651]
# Documentation

A recent [PR #100498](https://github.com/python/cpython/pull/100498/files) has replaced the 'odd' empty class sample with a dataclass sample to represent the C “struct” alike data type in tutorial/classes.html#odds-and-ends section.

I was wondering if it is still appropriate to keep this part under 'Odds and Ends'. It is not 'odd' like the empty class, IMHO. Maybe dataclasses deserves a separate section like iterators, and leave other odds there?

Before change, e.g. v3.9: 
https://docs.python.org/3.9/tutorial/classes.html#odds-and-ends
![image](https://user-images.githubusercontent.com/12903395/210157650-a5dcc849-a62f-46a7-ba40-6e6142b2218b.png)

After the change, i.e. latest:
https://docs.python.org/3.12/tutorial/classes.html#odds-and-ends
![image](https://user-images.githubusercontent.com/12903395/210157643-2da59ec1-8088-4afc-95c9-8fcbd5e8c96a.png)

**Comment by JosephSBoyle** [comment]
Hi, I authored the PR to change the example from an empty class to a dataclass. My rationale was that the previous example was simply not idiomatic modern Python.

I think you raise a valid point as to whether or not such an example belongs in an 'odds and ends' section of the docs.

The section is composed of:
- the dataclass example
- a description of using duck typing
- examples of two of the magic attrs that methods have

I think there are perhaps better ways to organize this section. Let's discuss here and when we reach a consensus I'm happy to open a PR with the changes:)

**Comment by JosephSBoyle** [comment]
cc: @gpshead @AlexWaygood

**Comment by AlexWaygood** [comment]
"Odds and ends" here means "various useful tips that didn't fit anywhere else in the tutorial", rather than "things that are odd". This complies with the [dictionary definition](https://www.merriam-webster.com/dictionary/odds%20and%20ends) of the phrase "odds and ends":

> miscellaneous remnants or leftovers

As such, I think it's perfectly appropriate for this example to use `dataclasses`. As @JosephSBoyle says, the previous code was outdated and no longer represented idiomatic Python.

Whether the tutorial should be more thoroughly restructured is a different issue. But it's hard to claim that the example is out of place in this section, in my opinion, given that the section title means "a collection of items that didn't really fit anywhere else in this tutorial".
