### ISSUE TITLE
set.add() behavior when adding equal element is not documented

### ISSUE THREAD

**Issue by ipilcher** [python/cpython#100629]
The[ `set.add()` documentation](https://docs.python.org/3/library/stdtypes.html#frozenset.add) does not mention the behavior of the method if an equal element is already present in the set.

The behavior should be documented.  (The set is not modified.  I.e. the existing element is **not** replaced.)

### Linked PRs
* gh-100657

**Comment by rhettinger** [comment]
This may be considered an implementation detail and not a guaranteed behavior. The underlying set theory is predicated on a notion of an equivalences classes rather than on object identity. The implementation takes full advantage of that fact in its operations.  For example, set intersection make an implementation dependent choice between these two equivalent zeros:

```
{0, 1}.intersection({0.0})
{0.0}
{0.0, 1}.intersection({0})
{0}
```

 I think the situation is similar for dicts where `d[k] = v` for an existing key guarantees that `k` keeps its insertion order and that `v` is always replaced, but no assurance is given about where `k` is replaced. Python currently does not replace `k` but a case could be made that it should be replaced so that the final `k` and `v` correspond.

**Comment by stevendaprano** [comment]
I would support a note that the behaviour is implementation-defined, not specified by the language, and users should not make any assumptions about which element is kept.

Given that CPython is the reference implementation, I think that it is fair to document which parts of the behaviour are not considered part of the language and so (1) do not need to be emulated by other implementations and (2) should not be relied on.

**Comment by ipilcher** [comment]
FWIW, both comments make sense to me.  (It's become clear to me since I wrote that relied on a particular behavior that I was abusing the notion of equality.)

IMO, it does still make sense to document the fact that the behavior is not defined, so that people don't (foolishly) rely on it.

**Comment by ramvikrams** [comment]
I'll add a note then
