### ISSUE TITLE
mailbox.Message fails to initialize from email.message.Message created from a file

### ISSUE THREAD

**Issue by HoffmannJM** [python/cpython#100789]
# Bug report

    import mailbox
    from email.message import Message

    with open("example.mail", mode='rb') as f:
        msg = Message(f)
        mailbox.Message(msg)

    -- example.mail --
    Subject: Test

    Hello, BUG!

Running this results in a

    TypeError: cannot pickle '_io.BufferedReader' object

I expect this to work regardless of the email.message.Message residing fully in memory or partially on disk.
I understand the copy semantics of the mailbox.Message initializer makes this situation difficult because of the underlying file descriptor.
Directly reading the file with mailbox.Message works fine though.
What I want would be a move so that I in essence upgrade the email.message.Message instance to a mailbox.Message.

The underlying issue is that I have a custom Policy that I require but a mailbox.Message does not allow setting it.
The upgrade would be a way of bypassing the lack of constructor argument pass through.

# Your environment

- CPython versions tested on: 3.10.8
- Operating system and architecture: Arch, Linux Kernel 6.0.15

**Comment by sobolevn** [comment]
Looks like these lines produce this result: https://github.com/python/cpython/blob/2f2fa03ff3d566b675020787e23de8fb4ca78e99/Lib/mailbox.py#L1494-L1497

However, there are couple of questions I have for the piece of code you've shared:
1. Why do you use `Message` instead of `EmailMessage`? It is documented to be deprecated: https://docs.python.org/3/library/email.compat32-message.html
2. Secondly, `email.message.Message` is documented to receive `Policy` class as the first argument, not file instance. 
   > If policy is specified (it must be an instance of a [policy](https://docs.python.org/3/library/email.policy.html#module-email.policy) class) use the rules it specifies to update and serialize the representation of the message. If policy is not set, use the [compat32](https://docs.python.org/3/library/email.policy.html#email.policy.Compat32) [policy](https://docs.python.org/3/library/email.policy.html#module-email.policy), which maintains backward compatibility with the Python 3.2 version of the email package. For more information see the policy documentation.

   Link: https://docs.python.org/3/library/email.compat32-message.html#email.message.Message

3. We provide a special API to create `email.message.Message` objects from files: `email.message_from_file`. This works:
   
   ```python
   >>> with open('Lib/test/test_email/data/msg_01.txt') as f:
   ...   m = email.message_from_file(f)
   ... 
   >>> m
   <email.message.Message object at 0x1068b0970>
   >>> import copy
   >>> copy.deepcopy(m)
   <email.message.Message object at 0x1068a3c60>
   ```

Is there anything I am missing? :)

**Comment by D1CED** [comment]
Apparently I got confused by the initializer arguments of the two types and didn't read the doc for the email.parser module.

Using `email.message_from_binary_file` was what I needed just a little confusing that it is not mentioned at all in email.message.
