### ISSUE TITLE
`Doc/whatsnew/3.{9,10,11}.rst` are out of sync on various branches

### ISSUE THREAD

**Issue by zware** [python/cpython#100734]
# Documentation

There are various inconsistencies between the whatsnew documents for 3.9, 3.10, and 3.11 on the `3.9`, `3.10`, `3.11`, and `main` branches.  Most of the inconsistencies are trivial, but some will require some research to determine which version is the canonical text that should be synced across branches.

### Linked PRs
* gh-114657
* gh-114688
* gh-114689
* gh-115526
* gh-115527

**Comment by ned-deily** [comment]
This is an on-going problem due to the unnecessary duplication of data across release branches; it is also an issue with the generated changelog.html files for each branch. Rather than trying to patch over the problem again, we should fix it permanently by removing the duplication. One way that I believe would work is to change the whatsnew and changelog "templates" for each release branch to only contain the data for its branch and to include links at the bottom to the on-line version of the previous branch's whatsnew or changelog. There would also likely need to be some release manage actions added to PEP 101 and release scripts to delete the previous branch's whatsnew when creating a new release branch, i.e. at beta 1 time. One minor downside to this is that any off-line version of the docs would now have a link to the on-line whatsnew and changelog for previous releases rather but that's probably better than having incomplete and/or incorrect information as we do today. @python/python-release-managers

**Comment by hugovk** [comment]
See also https://github.com/python/docsbuild-scripts/issues/138.

**Comment by JelleZijlstra** [comment]
If I understand @ned-deily correctly, his proposal would be that the main branch contain only the 3.12 What's New, the 3.11 branch only the 3.11 What's New, etc.

One problem with that approach is that we fairly regularly have PRs updating an old branch's What's New in addition to docs changes (e.g. python/cpython#100009, python/cpython#100179. Currently, such PRs can be made against main, then backported into 3.11. But with Ned's proposal, that won't work any more, and you might need a separate PR against the 3.11 branch.

**Comment by ned-deily** [comment]
While I think it would be best to really have one and only one copy of each branch's What's New, I suppose we *could* come up with some kludge to ease merging like not removing the old branches's whatsnew file in the newer branches but have the old files removed when producing each release's source files (tarballs, et al) while still using the suggested links in the generated html files. OTOH, I don't think that this comes up *that* often that it is an undue burden. But that's just my opinion.
