### ISSUE TITLE
"What's New In Python X.YZ" Pages Show Incorrect Release Information

### ISSUE THREAD

**Issue by ronaldpetty** [python/cpython#100700]
# Documentation

From this page https://docs.python.org/release/3.11.1/whatsnew/index.html, if you click on 3.11 or 3.10, you see the release information. It appears incorrect on 3.10, 3.9. Earlier releases are inconsistent (missing that same header information section).

On page https://docs.python.org/release/3.11.1/whatsnew/3.11.html

```
Release 3.11.1
Date December 06, 2022
Editor Pablo Galindo Salgado
```

On page https://docs.python.org/release/3.11.1/whatsnew/3.10.html

```
Release 3.11.1
Date December 06, 2022
Editor Pablo Galindo Salgado
```

For example, the 3.10 release should say:

```
Release 3.10
Date October 04, 2021
Editor X Y Z
```

### Linked PRs
* gh-100728
* gh-100729
* gh-100730
* gh-106999

**Comment by FloofyReal** [comment]
For me, it always shows the current date.

Since version [3.9](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.9.rst), they all ([3.10](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.10.rst), [3.11](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.11.rst), [3.12](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.12.rst)) contain a `today` field, which is definitely confusing, mainly because the previous version of Python mentioned the release date in the text.

**Comment by zware** [comment]
Thanks for the report!  This is actually a reappearance of #73905; the attached PRs will resolve this for the currently-relevant branches (though we'll have to wait for a rebuild of each branch to see the fix).  I've opened python/release-tools#34 to hopefully address this once and for all.
