### ISSUE TITLE
ctypes `PYFUNCTYPE` assignment on a `Structure` mutates saved references outside

### ISSUE THREAD

**Issue by ionite34** [python/cpython#100861]
# Bug report

As shown in this example, setting the attribute `tp_repr` on this `Structure` mutates the original saved `orig = st.tp_repr` There doesn't seem to be any documented reason for this behavior.
```python
from ctypes import *

reprfunc = PYFUNCTYPE(py_object, py_object)

class PyTypeObject(Structure):
    _fields_ = [("tp_repr", reprfunc)]

st = PyTypeObject.from_address(id(int)+88)
orig = st.tp_repr

@reprfunc
def __repr__(self):
    return "hi"

st.tp_repr = __repr__

print(repr(40))
>> 40
print(orig(40))
>> 40
```

The `PYFUNCTYPE`s are still unique objects, they just happen to now point to the same function in memory?
```py
print(tp.tp_repr)
>> <CFunctionType object at 0x7ff57cf10870>
print(orig)
>> <CFunctionType object at 0x7ff57cf106d0>
```

If defining the field as a `c_void_p`, and then casting manually between assignments, this no longer has the behavior of mutating an outside reference.
```py
from ctypes import *

reprfunc = PYFUNCTYPE(py_object, py_object)

class PyTypeObject(Structure):
    _fields_ = [("tp_repr", c_void_p)]

st = PyTypeObject.from_address(id(int)+88)
orig = cast(st.tp_repr, reprfunc)

@reprfunc
def __repr__(self):
    return "hi"

st.tp_repr = cast(__repr__, c_void_p)

print(repr(40))
>> hi
print(orig(40))
>> 40
```

# Your environment
- CPython versions tested on: 3.11.1 and main 3.12 bc0a686f820d7d298a0b1450b155a717972de0fc
- Operating system and architectures tested: macOS M1, Ubuntu x64

**Comment by eryksun** [comment]
This is the correct, expected behavior. `st.tp_repr` resides in the struct. 

```pycon
>>> addressof(st.tp_repr) == addressof(orig) == id(int) + 88
True
```

Setting the value of `st.tp_repr` modifies the value in the struct.

We can know that `st.tp_repr` references a pointer that resides in an aggregate by examining its `_b_base_` attribute. For example:

```pycon
>>> st.tp_repr._b_base_ is st
True
```

Depending on the context, the base reference may instead be in the `_objects` dict. For example:

```pycon
>>> orig = reprfunc.from_buffer(st.tp_repr)
>>> addressof(orig) == addressof(st.tp_repr)
True
>>> orig._objects
{'ffffffff': <memory at 0x7f67926d37d0>}
>>> orig._objects['ffffffff'].obj._b_base_ is st
True
```

---

A new function pointer can be initialized from the target function address, but we don't know this address without first casting to `c_void_p`. If we have to cast anyway, we may as well create a copy by casting directly to `reprfunc`. For example:

```pycon
>>> orig = cast(st.tp_repr, reprfunc)
>>> addressof(orig) == addressof(st.tp_repr)
False
>>> st.tp_repr = __repr__
>>> repr(40)
'hi'
>>> orig(40)
'40'
```

Alternatively, the target address can be copied to a new function pointer by way of a temporary pointer to the function pointer. For example:

```pycon
>>> orig = reprfunc()
>>> pointer(orig)[0] = st.tp_repr
>>> addressof(orig) == addressof(st.tp_repr)
False
>>> st.tp_repr = __repr__
>>> repr(40)
'hi'
>>> orig(40)
'40'
```

Finally, restore the original repr function:

```pycon
>>> st.tp_repr = orig
>>> repr(40)
'40'
```

**Comment by ionite34** [comment]
Thanks for the detailed explanation. I think I understand what's going on but not really why.

> We can know that `st.tp_repr` references a pointer that resides in an aggregate by examining its `_b_base_` attribute.

Is there any other `Structure` field that behaves like this? Being "bound" to the struct itself and modifications to the struct also affecting the field?

And is there a reason PYFUNCTYPE fields has to be bound to the struct like that? Instead of just being the function pointer as casted from if the field was a c_void_p?

**Comment by eryksun** [comment]
> Is there any other `Structure` field that behaves like this? Being "bound" to the struct itself and modifications to the struct also affecting the field?

Most of them, unless it's a simple type that gets automatically converted to a native Python object. A subclass of a simple type is never automatically converted, however. For example:

```python
from ctypes import *

class my_int(c_int):
    pass

class S(Structure):
    _fields_ = ('i', my_int),

```
```pycon
>>> s = S()
>>> i = s.i
>>> i
<my_int object at 0x7fc6696547e0>
>>> i._b_base_ is s
True
>>> i.value = 0x04030201
>>> bytes(s)
b'\x01\x02\x03\x04'
```

Here's an example with an array aggregate:

```pycon
>>> a = (my_int * 1)()
>>> i = a[0]
>>> i
<my_int object at 0x7fc669654ba0>
>>> i._b_base_ is a
True
>>> i.value = 0x04030201
>>> bytes(a)
b'\x01\x02\x03\x04'
```

I suppose that sharing the base storage instead of creating a deep copy is faster and simpler to implement, particularly for a deeply nested case.

**Comment by ionite34** [comment]
That makes sense 👍 I guess it might be good to expand on ctypes documentation a bit but I'm closing this issue for now.
