### ISSUE TITLE
Bizarre behavior adding floats

### ISSUE THREAD

**Issue by ScriptJunky** [python/cpython#100862]
# Bug report

floats do not add correctly. When adding 0.1 to 1.0, 9 times, this is the expectation;

```
1.1
1.2
1.3
1.4
1.5
1.6
1.7
1.8
1.9
```

Instead, we see this;

```
1.0
1.1
1.2000000000000002
1.3000000000000003
1.4000000000000004
1.5000000000000004
1.6000000000000005
1.7000000000000006
1.8000000000000007
1.9000000000000008
```

# Your environment

Python 3.9.6
MacOS Ventura 13.1

Code used to generate output;

```
def walkforward(start, end, step):
	values = []
	val = int(((end-start)/step))
	for x in range(0, val):
		values.append(start)
		start += step
	return print(*values, sep='\n')
```

I see similar behavior with numpy.arange. 

I may be limited in my understanding of why this is happening, and would love to understand better why the bizarre output.

**Comment by AlexWaygood** [comment]
I'm afraid that this is expected behaviour, and that you would get  similar results using most programming languages. Please see https://docs.python.org/3/tutorial/floatingpoint.html for more information. If you have further questions after reading the documentation there, please ask them over at https://discuss.python.org/c/users/7 rather than on the GitHub issue tracker.
