### ISSUE TITLE
ctypes Stucture._fields_ cannot be set when Structure has been subclassed

### ISSUE THREAD

**Issue by ionite34** [python/cpython#100980]
# Bug report

Currently the method for defining Structure fields that cannot be defined within the class, is to define the class with `pass` and then set `_fields_` outside. But `ctypes.Structure` incorrectly raises `AttributeError`, even when no class has ever set a `_fields_`.
```py
from ctypes import *

class PyObject(Structure):
    pass

class PyVarObject(PyObject):
    pass

class PyTypeObject(PyVarObject):
    pass

PyObject._fields_ = [
    ("ob_refcnt", c_long),
    ("ob_type", POINTER(PyTypeObject)),
]
```
```py
    PyObject._fields_ = [
    ^^^^^^^^^^^^^^^^^
AttributeError: _fields_ is final
```

Strangely, suppressing this Attribute error reveals the `_fields_` attribute *does* actually get set?
```py
with suppress(AttributeError):
    PyObject._fields_ = [
        ("ob_refcnt", c_long),
        ("ob_type", POINTER(PyTypeObject)),
    ]

print(PyObject._fields_)
>> [('ob_refcnt', <class 'ctypes.c_long'>), ('ob_type', <class '__main__.LP_PyTypeObject'>)]
```

# Your environment
- CPython versions tested on: 3.11.1, main
- Operating system and architecture: macOS ARM, ubuntu x64

### Linked PRs
* gh-124292

**Comment by encukou** [comment]
Subclassing a Structure finalizes it, which prevents setting `_fields_`. That is the intended behaviour: the superclass's fields are “inherited” (included in the subclass), so they must be known rather early, and they can't change when a new subclass is made. (AFAIK we *could* delay the finalization a bit more, but that would add hard-to-test edge cases, so let's not.)
The docs could be clearer here.

The bug here is that the `_fields_` attribute is set despite `AttributeError`. This should not happen. (However, the setattr is just “cosmetic”: the internals aren't updated, in fact the attribute is never consulted again after finalization.)

It's confusing that it's possible can finalize a class that doesn't have `_fields_` set. However, this feature is useful for superclasses that don't add/affect C fields -- like `Structure` itself.
