### ISSUE TITLE
Generate separate pages for every individual free function and class

### ISSUE THREAD

**Issue by adamncasey** [python/cpython#100921]
## The problem

One issue I come across quite frequently when searching for python documentation is that I can find the page the function docs exist on quite quickly. But getting to the actual function on that page isn't obvious or (often) easy.

For example, searching for `python os.pipe` gives me a first result of https://docs.python.org/3/library/os.html but it drops me at the top of a fairly long page with no easy way to jump to what I'm actually looking for.

I've learned I can typically ctrl+f for the function name I'm looking for. In the example above the actual function would be the third result, although I could have clicked the second result to jump there. 

![image](https://user-images.githubusercontent.com/720498/175517258-34315d81-135d-440a-ba71-9a0c5a02deeb.png)

It's certainly not unusable, but it does make the official python docs one of the hardest results to navigate - which is a shame because the quality (and authenticity) of the information here is excellent.

The above example is not so bad, but the length of pages such as https://docs.python.org/3/library/stdtypes.html is surprisingly daunting when you want to check what the official docs say about a pretty 'core' behaviour such as `dict.get()`

![image](https://user-images.githubusercontent.com/720498/175517521-505b01db-eadb-4329-83c4-b48ca620c54b.png)

I think pages such as https://docs.python.org/3/library/functions.html which add a table of contents to the top are a slight improvement, but they don't really solve the problem that if I search for `python open function` I would like to immediately see information relevant for my search - `abs()` / `all()` don't fit that bill.

## Solutions in other doc sites/languages

Looking at other programming languages, this problem is solved by having a hierarchy of pages such as:

- top level: module documentation
    - [C++ <unordered_map> header file](https://en.cppreference.com/w/cpp/header/unordered_map)
    - [Rust std::collections](https://doc.rust-lang.org/stable/std/collections/)
    - [C# System.Collections.Generic](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic?view=net-6.0)
- next level: free function / class documentation
    - [C++ unordered_map class](https://en.cppreference.com/w/cpp/container/unordered_map)
    - [Rust HashMap class](https://doc.rust-lang.org/stable/std/collections/struct.HashMap.html)
    - [C# Dictionary](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2?view=net-6.0)
- next level: class member documentation
    - [C++ unordered_map::at](https://en.cppreference.com/w/cpp/container/unordered_map/at)
    - Rust doesn't have separate pages at this level, but the class/module documentation is much more targetted. Finding `get` from the class docs is significantly easier because these methods are listed above the fold on the left hand table of contents.
    - [C# Dictionary.TryGetValue](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.trygetvalue?view=net-6.0)

## Suggestion

I think adding more structure into the docs.python.org pages, even if it means some information gets duplicated, would be a bit improvement for search -> find workflows for function documentation.

I think there should be a page specifically for the `dict` class, if not to a page specifically for every method. This should eventually improve the search -> result experience but it will also makes it much easier for the user to discover other relevant functions/info - such as `dict[key]`, or `dict.update`

It may also give the official python docs a boost in search engine ratings for searches like `python dict update` - at the moment (at least in my google results) I need to hop over a lot of [advert](https://www.programiz.com/python-programming/methods/dictionary/update) [filled](https://www.w3schools.com/python/ref_dictionary_update.asp) or [specifically python2.7 only](https://python-reference.readthedocs.io/en/latest/intro.html) tutorial/reference pages - and I don't blame google

This issue was originally opened at https://github.com/python/docsbuild-scripts/issues/130 but was directed here.

Thanks for reading & I hope this is the now right place to put this issue

**Comment by rhettinger** [comment]
I am opposed to breaking the documentation apart like this.

*  For one, it would break every existing link into our documentation from external sources (blog posts, lesson plans, stackoverflow answer, etc).  It would also break all the links in from old BPO and new GH issues pages (this one for example).

* We already have a solution though perhaps not used as much as it should be.   Docs for builtin functions and itertools have a summary of function and hotlinks at the top of the page.  This makes navigation easy.

* We also have a search bar in our docs which is usually but not always effective at taking you directly to docs for a specific function. It could be improved by giving builtin functions a higher ranking, but is mostly good at its task

* For some modules, the functions have logical groupings that shouldn't be split up.  Likewise some docs are intended to be read as an aggregate and would suffer if split-up (the [heapq](https://docs.python.org/3/library/heapq.html#module-heapq) functions for example).

* Some projects like numpy have a separate page per function; however, their needs are different.  Those functions typically have many possible arguments and flags. In contrast, Python functions typically have a much simpler design.

* The problem being solved (inability to use Cntl+F in a browser) is insufficient motivation for a major reorganization that would require enormous effort to be done in a thoughtful way (i.e. cross-references to functions that are currently side by side, and repeated text that is currently unnecessary because they only need to be stated for one variant of the function).  The current text was written in a context where the current presentation is the norm; changing that assumption would require that every split-out function would need a thorough review to make sure that it continues to make sense in a standalone context.

* Currently, it is easily possible to study one module at a time it its entirety just by reading top to bottom.  Fragmenting the docs (breaking the molecules into atoms) makes that task more daunting, less obvious, less likely to have a cohesive result. For comparison, try using wikipedias topics maps as a basis for studying a group of topics.  See for example, the "Group homomorpishsms" topic list under the [Abelian Groups](https://en.wikipedia.org/wiki/Abelian_group); I don't think someone can learn the topic area by clicking on the individual topics.   In contrast, a person can on their own read the [bisect documentation](https://docs.python.org/3/library/bisect.html#module-bisect) from top to bottom and thoroughly learn the topic.

**Comment by zware** [comment]
> We already have a solution though perhaps not used as much as it should be. Docs for builtin functions and itertools have a summary of function and hotlinks at the top of the page. This makes navigation easy.

It might be interesting to see the results of a change to automatically generate this kind of table[^1] for each module, or at least those that opt in with some directive so that the location of the table can be chosen more carefully.  I *don't* want to see someone go to the effort of manually creating such a table for every module; those are bound to drift out of date.

[^1]: Existing example: https://github.com/python/cpython/blob/7b14c2ef194b6eed79670aa9d7e29ab8e2256a56/Doc/library/functions.rst?plain=1#L10-L41

**Comment by rhettinger** [comment]
I someone wants to submit individual PRs to improve some module's documentation, please do so.   Not all modules need this or they already have some other reasonable approach to combining readability with searchability.  These should be considered one at a time rather that applying a blanket sweep through the docs.

If someone wants to build a table making tool in the Tools directory, that would be okay. The need is not high though.  Most of the current tables were already made maintained with some third-party tooling (for example, Emacs has builtin support for creating and editing reStructured text tables.

**Comment by adamncasey** [comment]
Thank you for taking the time to read through & reply.

I feel like we're considering different workflows when considering this problem: it sounds like you're already on the docs.python.org website when you search for documentation, whereas I'm trying to find what I'm looking for from google / any other search engine. Although I write a reasonable amount of python, it's certainly not an everyday thing, and I would guess google hasn't especially adjusted my search results to prefer the docs.python.org website. I'm assuming my search results are somewhat typical here.

For me, these two searches highlight the issue.

![image](https://user-images.githubusercontent.com/720498/215748780-ee9725f3-1179-4f47-89ac-40ce870af0d4.png)
![image](https://user-images.githubusercontent.com/720498/215750254-ad927e03-c3c0-4789-ad61-dc49a2e962de.png)

and it seems to me that this is solvable by providing information on more targeted pages.

I've got a couple of comments on some of your points above too - I'll add these inline.

> * For one, it would break every existing link into our documentation from external sources (blog posts, lesson plans, stackoverflow answer, etc).  It would also break all the links in from old BPO and new GH issues pages (this one for example).

I like this point. I think it would be possible to keep existing links functional while providing more specific results where appropriate.

> * For some modules, the functions have logical groupings that shouldn't be split up.  Likewise some docs are intended to be read as an aggregate and would suffer if split-up (the [heapq](https://docs.python.org/3/library/heapq.html#module-heapq) functions for example).
This module is a good counter point. It's methods are all tightly related and fit on one screen. I wouldn't feel bad linking someone new to this page if they need a method on it.

My counter-counter-point though has to be these two pages:
https://docs.python.org/3/library/functions.html
https://docs.python.org/3/library/stdtypes.html

I'd be happy to reduce the scope of this issue to just addressing discoverability on these two pages. Starting small is probably the right thing to do regardless

> * Some projects like numpy have a separate page per function; however, their needs are different.  Those functions typically have many possible arguments and flags. In contrast, Python functions typically have a much simpler design.

Many built in things like subprocess are highly complex too. I don't think this argument applies across the board. https://docs.python.org/3/library/subprocess.html

> * Currently, it is easily possible to study one module at a time it its entirety just by reading top to bottom.  Fragmenting the docs (breaking the molecules into atoms) makes that task more daunting, less obvious, less likely to have a cohesive result. For comparison, try using wikipedias topics maps as a basis for studying a group of topics.  See for example, the "Group homomorpishsms" topic list under the [Abelian Groups](https://en.wikipedia.org/wiki/Abelian_group); I don't think someone can learn the topic area by clicking on the individual topics.   In contrast, a person can on their own read the [bisect documentation](https://docs.python.org/3/library/bisect.html#module-bisect) from top to bottom and thoroughly learn the topic.

For some modules this is true, I think examples I listed above show that that isn't universally a a useful workflow.
