### ISSUE TITLE
Inconsistency in TypeError messages

### ISSUE THREAD

**Issue by jahrules** [python/cpython#101099]
The best way I can describe this is with example:

```python
import random
random.choice(1,2,3,4)
```

This gives an error message:
"TypeError: Random.choice ..."

But

```python
import datetime
datetime.datetime.strptime(1,2,3,4)
```

This gives an error message:
"TypeError: strptime ..."

Two nitpicks: 
Why is Random being capitalized? I called random, not Random. strptime doesn't get capitalized.
Why does the Type Error for random get prepended with the library and strptime does not?

Consistency would be nice here.

**Comment by stevendaprano** [comment]
Random gets capitalised because the `random.choice` function is actually a method of `random.Random`. Its a big confusing because we have the `random` module containing the `Random` class, which is then instantiated into a private object, and the methods made visible as public functions.

```
>>> import random
>>> print(random.choice)
<bound method Random.choice of <random.Random object at 0xb86120>>
```

> Why does the Type Error for random get prepended with the library and strptime does not?

Its not the library, its the class, and no particular reason.

We're unlikely to get consistency across the entire language and stdlib.
