### ISSUE TITLE
Subprocess stdin does not allow tempfile.SpooledTemporaryFile

### ISSUE THREAD

**Issue by zackees** [python/cpython#101136]
# Bug report

It appears that `subprocess.Popen` does not accept a stdin stream of type `SpooledTemporaryFile` and just fails. I've gone ahead and created a public unit test showing this in action. It fails on all MacOS/Windows10/Ubuntu. However, switching from `SpooledTemporaryFile` to an actual named file or a `tempfile.TemporaryFile` works just fine.

See bug repro case here:
https://github.com/zackees/python-subprocess-bug-spooled-temp-file

I'm not sure if this is a bug or intended behavior. Feel free to close if this is intended behavior.

# Your environment

The test for SpooledTemporaryFile fails on Windows10, MacOS and Ubuntu using python 3.11

**Comment by ronaldoussoren** [comment]
Please add reproducers to the the issue when they are as small as this. Also describe what "just fails" means.

Your reproducer does something like this:

```python3

import tempfile
import subprocess

stream = tempfile.SpooledTemporaryFile()
stream.write(b"hello world\n")

p = subprocess.Popen(["some-command"], stdin=stream)
p.wait()
```

This fails in the sense that ``some-command`` sees an empty stdin. That's expected because the current file offset of ``stream`` is at the end of the file.

The command will see the correct input when you reset the current file offset before the call to ``Popen`` by calling ``stream.seek(0)``.

**Comment by zackees** [comment]
> Please add reproducers to the the issue when they are as small as this. Also describe what "just fails" means.

I literally created a github repo that does nothing but reproduce this error with platform tests for Win/Linux/MacOS

But here you go:

```
/Users/runner/work/python-subprocess-bug-spooled-temp-file/python-subprocess-bug-spooled-temp-file/tests/test_fail.py:[22](https://github.com/zackees/python-subprocess-bug-spooled-temp-file/actions/runs/3951471594/jobs/6765363924#step:6:23): ResourceWarning: Unclosed file <tempfile.SpooledTemporaryFile object at 0x101e436d0>
  p = subprocess.Popen(
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "/Users/runner/work/python-subprocess-bug-spooled-temp-file/python-subprocess-bug-spooled-temp-file/tests/accept_input.py", line 2, in <module>
    answer = input("Accept [y/n]?: ")
             ^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line
F/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/unittest/case.py:622: ResourceWarning: unclosed file <_io.TextIOWrapper name=4 encoding='UTF-8'>
  with outcome.testPartExecutor(self):
ResourceWarning: Enable tracemalloc to get the object allocation traceback

======================================================================
FAIL: test_fail (__main__.Tester.test_fail)
Should this test pass?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/python-subprocess-bug-spooled-temp-file/python-subprocess-bug-spooled-temp-file/tests/test_fail.py", line 32, in test_fail
    self.assertIn("OK", stdout)
AssertionError: 'OK' not found in 'Accept [y/n]?: '
```

**Comment by ronaldoussoren** [comment]
> > Please add reproducers to the the issue when they are as small as this. Also describe what "just fails" means.
> 
> I literally created a github repo that does nothing but reproduce this error with platform tests for Win/Linux/MacOS

My phrasing was unfortunate. Let me expand a little: The GitHub repo did help and is appreciated. But in general we prefer reproducers in the issue itself because that makes it easier for us to look at the issue.  My request was meant as a request for future reports.

As mentioned in my previous message your example fails because it doesn't reset the file offset before passing the open file to subprocess.
