### ISSUE TITLE
Undocumented risky behaviour in subprocess module

### ISSUE THREAD

**Issue by mauricelambert** [python/cpython#101283]
# Bug report - Undocumented risky behaviour in subprocess module

When using `subprocess.Popen` with `shell=True` on Windows and without a `COMSPEC` environment variable, a `cmd.exe` is launched. The problem is the `cmd.exe` full path is not written, Windows will search the executable in the current directory and in the PATH. If an arbitrary executable file is written to the current directory or to a directory in the PATH, it can be run instead of the real cmd.exe.

See the code [here](https://github.com/python/cpython/blob/38cc24f119346e2947e316478b58e58f0dde307c/Lib/subprocess.py#L1480) and a POC [here](https://github.com/mauricelambert/PythonSubprocessVulnerabilityPOC).

 - This risky behaviour can be patched by replacing `cmd.exe` string by `C:\WINDOWS\system32\cmd.exe`.
 - If the behavior was chosen by python developers, it should be documented.

### Linked PRs
* gh-101286
* gh-101708
* gh-101709
* gh-101710
* gh-101711
* gh-101712
* gh-101713
* gh-101719
* gh-101721
* gh-101728

**Comment by eryksun** [comment]
FYI, `subprocess.Popen` should never find "cmd.exe" in `PATH`. We call `CreateProcessW()`, which always searches the application directory and system directories before it seraches `PATH`.

`CreateProcessW()` may also check the current directory immediately after the application directory and before the system directories. This unsafe behavior can be prevented by defining the environment variable [`NoDefaultCurrentDirectoryInExePath`](https://learn.microsoft.com/en-us/windows/win32/api/processenv/nf-processenv-needcurrentdirectoryforexepathw). This environment variable has been supported for over 15 years now, since Windows Vista. Our implementation of `shutil.which()` should honor this security feature by calling `NeedCurrentDirectoryForExePathW()`.

Note that if `NoDefaultCurrentDirectoryInExePath` is defined, the current directory is still included in the search path if the name is a relative path that includes backslashes (e.g. "Scripts\\eggs.exe"), but not if it only includes forward slashes (e.g. "Scripts/eggs.exe"). Note also that the application directory takes precedence over the current directory in this case (e.g. if the application directory is "C:\\Program Files\\Python311", then "Scripts\\eggs.exe" will resolve to "C:\\Program Files\\Python311\\Scripts\\eggs.exe" if it exists).

If you define `NoDefaultCurrentDirectoryInExePath`, the current directory can be added explicitly as a "." entry at the end of either the system or user `PATH`. I add "." to the end of the user `PATH` because some apps and scripts still depend on finding binaries and scripts in the current directory, but I won't cater to a bad actor that expects the current directory to be searched before system directories.

**Comment by gpshead** [comment]
FYI - this originally came in as a security report to PSRT. I redirected the reporter here (thanks for reporting this!) as this didn't seem serious enough to be embargoed. I'm still tagging it as such and aiming for a full set of backports as it feels like a good idea.

**Comment by gpshead** [comment]
The versionchanged markers in several of the PRs are inaccurate.

**Comment by zooba** [comment]
The backports are not merged yet - do you want to just fix it there?

**Comment by zooba** [comment]
Ah I see, it's only the versions in `main` and `3.11` branches.

**Comment by zooba** [comment]
Fully merged, and all the fixes should be in (I hope). Thanks all!
