### ISSUE TITLE
I don't know what to call this bug, Mathemitical error?

### ISSUE THREAD

**Issue by kdschlosser** [python/cpython#101314]
# Your environment

- CPython versions tested on:
3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]

- Operating system and architecture:
Windows 11 build 22621

Easier to look at the code example below to explain it.

```python
new_delta_t = 1.2

delta_change_time = 24678
delta_change = -0.8

change = delta_change_time * ((delta_change - new_delta_t) ** new_delta_t)

print(change)
```

outputs the following

```
(-45867.34471020895-33324.57657864852j)
```

it's not even a number!!
I get no tracebacks of any kind, the script terminates normally

**Comment by ericvsmith** [comment]
You're raising a negative number to a fractional power and getting a complex number as a result.

Here's a simpler case:
```pycon
>>> (-3) ** 0.5
(1.0605752387249068e-16+1.7320508075688772j)
```
From `help('**')`: Raising a negative number to a fractional power results in a "complex" number.

**Comment by stevendaprano** [comment]
https://en.wikipedia.org/wiki/Complex_number

Python uses "j" instead of "i", but otherwise these are the same.

I don't see any reason to keep this ticket Pending, the behaviour is as documented and is mathematically correct to the accuracy of floating point arithmetic, so I'm going to close it. @kdschlosser if you think it should be reopened, please answer here with the reason you still think this is a bug.
