### ISSUE TITLE
IntEnum access is slower in 3.11 vs 3.10

### ISSUE THREAD

**Issue by a-temnikov** [python/cpython#101370]
I checked performance with this script:

```python
import time
from enum import IntEnum


class BitAvailability(IntEnum):
    BUSY: int = 0
    FREE: int = 1


tb = time.time_ns()
for i in range(100000000):
     if i == BitAvailability.BUSY:
         pass

ta = time.time_ns()
print(f'{(ta - tb) / 10**9}')
```

The results were like:
```
$ python3.10 ~/test_enum.py
14.056523

$ python3.11 ~/test_enum.py
15.676774
```

Checked with Python 3.10.9 and Python 3.11.1 on MacOS 10.15.7, x86_64

**Comment by Eclips4** [comment]
I cannot reproduce it on Windows 10 and on Ubuntu 20.04

Windows:
```
python3.10 test.py
15.8870493

python3.11 test.py
14.7179961
```
Ubuntu:
```
python3.10 test.py
12.571745074

python3.11 test.py
11.71601287
```

**Comment by yusancky** [comment]
I tested on three Ubuntu 22.04s, and all showed that Python 3.10 was faster. 

| 3.10.6 | 3.11.1 |
| :----: | :----: |
| 20.152185739 | 24.841406463 |
| 14.939108898 | 17.297398998 |
| 17.25897922 | 21.345257179 |

**Comment by ethanfurman** [comment]
On my system the 3.10 vs 3.11 performance is nearly identical.

**Comment by neomachiney** [comment]
```
root@v2311:~# python3.12 test.py
0.450826113
root@v2311:~# python3.11 test.py
0.270465216
root@v2311:~# python3.12 test.py
0.854911641
root@v2311:~# python3.11 test.py
0.271121652
root@v2311:~# python3.12 test.py
0.391541296
root@v2311:~# python3.11 test.py
0.388706446
root@v2311:~# python3.12 test.py
0.466933656
root@v2311:~# python3.11 test.py
0.294551369
root@v2311:~# python3.12 test.py
0.384226765
root@v2311:~# python3.11 test.py
0.374963949
root@v2311:~# python3.12 test.py
0.399923255
root@v2311:~# python3.11 test.py
0.271317335
root@v2311:~# python3.12 test.py
0.383908077
root@v2311:~# python3.11 test.py
0.317050526
```

**Comment by DmitriyL02** [comment]
Python 3.10 was faster

```
~ python3.10 enum_test.py

22.023389315989334

~ python3.11 enum_test.py
23.951147317013238

```

**Comment by cat0d** [comment]
3.10 is also faster on Intel Core i5 Mac-Book Pro and MacOS Catalina 10.15.7:

python3.11 test_enum.py 
14.628569
python3.10 test_enum.py
13.357837

**Comment by SimpleArt** [comment]
This looks to me like really bad benchmarking, for the following reasons:

- Practical use cases probably only check the values covered by the enum.
- There's a lot more than what should be tested being timed here: there's a loop and a cast of the equality result to a `bool` for the `if` block.
- If you're going to time multiple iterations like this, it's probably a good idea to measure the mean and standard deviation rather than the total so that it's clear what the time per iteration is and roughly how much noise we're seeing.
- Better benchmarking usually only looks for the minimum time taken. Any additional time is more often caused by your system doing other things, not your program.
