### ISSUE TITLE
Unexpected behaviors with `collections.abc.Set` for binary operators

### ISSUE THREAD

**Issue by SimpleArt** [python/cpython#101568]
# Bug report

`collections.abc.Set` allows any `Iterable` to be used with binary operators:

```python
from collections.abc import Set as AbstractSet


class Set(AbstractSet):

    def __init__(self, iterable):
        self._set = frozenset(iterable)

    def __contains__(self, x):
        return x in self._set

    def __iter__(self):
        return iter(self._set)

    def __len__(self):
        return len(self._set)

    def __repr__(self):
        return f"{type(self).__name__}({self._set})"


S = Set([1, 2, 3])
print(S & [2, 3])  # Set(frozenset({2, 3}))
```

However, this behavior is not respected by the builtin sets:

```python
assert issubclass(frozenset, AbstractSet)
assert issubclass(set, AbstractSet)

S = {1, 2, 3}
print(S & [2, 3])
"""
Traceback (most recent call last):
  ...
TypeError: unsupported operand type(s) for &: 'set' and 'list'
"""
```

This is the expected behavior from `mypy`, especially to allow for consistent and easily understood operations. Allowing any `Iterable` opens up confusion as to which type the end result is.

### Linked PRs
* gh-101569

**Comment by arhadthedev** [comment]
Can confirm the bug on Python 3.12.0a4.

@rhettinger as the collections expert.

**Comment by rhettinger** [comment]
Sorry, but this is a breaking change. The ABC for Sets was intentionally designed to support iterable inputs, likely because it does not have non-operator methods like union, intersection, and difference. Contrariwise, concrete sets intentionally prohibit iterable inputs because the likelihood of user error `s |= "abc"`.

The two design decisions are inconsistent, but practicality beats purity.  With concrete sets, you have access to the non-operator methods.  That is why issues aren't arising in practice.  With abstract sets, the operators allow inputs which is also pragmatic because the non-operator methods are not guaranteed to be available.  Guido personally made this decision a long time ago when creating the collections ABCs.  In practice, this decision has worked out just fine.  The only real issue is that it seems to really bug people who wish for more purity.

**Comment by SimpleArt** [comment]
@rhettinger
Hm, I see. I can't help but think the practical solution would've been to simply add those methods, but that's a bigger breaking change. Out of curiosity, do you have a link for the discussion you're referencing?

And in the case that one has a generic case involving both cases, I suppose the fix would be to:

- Only use sets throughout, since sets are still iterable and will satisfy both cases.
- Forego both approaches and construct a concrete set using comprehension for most cases.
