### ISSUE TITLE
It appears that I can only write one line of code at a time. It may be me,,

### ISSUE THREAD

**Issue by rreece72** [python/cpython#101510]
Hello Team

It appears that I can only write one line of code at a time. I cannot go from line 1 to line 2 without running line one. I
hope I am explaining my issue in a way that is understandable. It may be me - I am a newb and am looking to follow along
with the trainer. Please Help

I am on a MacOS

My Name is Ronald and I can be reached at rreece72@gmail.com

Thank you
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by ericvsmith** [comment]
You have not given any indication this is a bug in Python. You should ask your question at https://discuss.python.org/c/users/7. You should provide information on what you’re trying to do, what program you’re running, what operating system you’re using, what you tried, and what error you got. I’m closing this because it doesn’t appear to be a bug. If, after asking for help at the above link, you still think you’ve discovered a bug in Python, please re-open this bug report.
