### ISSUE TITLE
Add threading support based on wasi-threads

### ISSUE THREAD

**Issue by yamt** [python/cpython#101538]
# Feature or enhancement

use [wasi-threads](https://github.com/WebAssembly/wasi-threads) via [wasi-sdk](https://github.com/WebAssembly/wasi-sdk)

# Pitch

# Previous discussion

### Linked PRs
* gh-101537
* gh-106834

**Comment by brettcannon** [comment]
My concerns about supporting this is that wasi-threads is only at phase 1 of (I believe) 4, so this is not close to being available publicly as part of WASI itself.

The WASI SDK support is also not released yet (although I see the OP is the author of the support that's in their `main` branch 😉). I also don't know how many WASI runtimes support this proposal (e.g. wasmtime doesn't, but does wasmer, wasmedge, iwasm/WAMR, etc.?). Basically this seems very experimental and I would prefer we were not providing direct support and thus the ones that will get the bug reports on the feature.

As such, I'm unfortunately going to need to reject this feature request. Maybe Singlestore Labs or VMWare via their builds would be up for taking this on? Otherwise I would suggest keeping a fork going with your changes and release your own build if you're trying to get testing for wasi-threads specifically.

**Comment by yamt** [comment]
> My concerns about supporting this is that wasi-threads is only at phase 1 of (I believe) 4, so this is not close to being available publicly as part of WASI itself.
> 
> The WASI SDK support is also not released yet (although I see the OP is the author of the support that's in their `main` branch 😉). I also don't know how many WASI runtimes support this proposal (e.g. wasmtime doesn't, but does wasmer, wasmedge, iwasm/WAMR, etc.?). Basically this seems very experimental and I would prefer we were not providing direct support and thus the ones that will get the bug reports on the feature.

wasmtime support has been landed in the meantime.
wamr has a support on a dev branch.

> 
> As such, I'm unfortunately going to need to reject this feature request. Maybe Singlestore Labs or VMWare via their builds would be up for taking this on? Otherwise I would suggest keeping a fork going with your changes and release your own build if you're trying to get testing for wasi-threads specifically.

**Comment by brettcannon** [comment]
We can re-evaluate once wasi-sdk has support in a release.

**Comment by yamt** [comment]
a prerelease of wasi-sdk with wasi-threads support: https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-20%2Bthreads

**Comment by yamt** [comment]
> We can re-evaluate once wasi-sdk has support in a release.

now a wasi-sdk release with wasi-threads is available: https://github.com/WebAssembly/wasi-sdk/releases/tag/wasi-sdk-20
