### ISSUE TITLE
Improve `list_repeat`

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#101619]
[Current implementation](https://github.com/python/cpython/blob/main/Objects/listobject.c#L552) of `list_repeat` doesn't took into consideretion case when `n` is equals to 1.
(Implementation of `list_inplace_repeat` has this check)
We can add this block of code to function
```c

    const Py_ssize_t input_size = Py_SIZE(a);
    if (n == 1 && input_size != 0){
        PyListObject *np = (PyListObject *) list_new_prealloc(input_size);
        PyObject **src = a->ob_item;
        PyObject **src_end = src + input_size;
        PyObject **dest = np->ob_item;
        while (src < src_end) {
            _Py_RefcntAdd(*src, n);
            *dest++ = *src++;
        }
        Py_SET_SIZE(np, input_size);
        return (PyObject *) np;
    }
```
This prevent us from calculating output size (because output size is equals to input size) and other checks.

### Linked PRs
* gh-101695

**Comment by pochmann** [comment]
How much does that improve this special case and how much does it harm every other case?

**Comment by peendebak** [comment]
For `list_inplace_repeat` we avoid a call to `list_resize` with the fast path for `n==1`. For `list_repeat` the computation of the output_size is very cheap, I doubt if will make a large performance difference.

For the corresponding `tuple_repeat` there is a fast path for `n==1`, because we can return a reference to the input tuple and avoid copying data altogether.

**Comment by Eclips4** [comment]
I got such results:

old `list_repeat`
```
> pyperf timeit "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 100"
Mean +- std dev: 616 ns +- 13 ns
> pyperf timeit "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 1"
Mean +- std dev: 98.4 ns +- 3.0 ns
```
new `list_repeat`
```
> pyperf timeit "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 100"
Mean +- std dev: 621 ns +- 15 ns
> pyperf timeit "[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] * 1"
Mean +- std dev: 87.9 ns +- 1.3 ns
```

**Comment by peendebak** [comment]
That is indeed a little bit faster, but I am not sure it matters enough to make a special code path for it. If you are interested, you could make PR with some more performance results for various cases. (but a core developer would have to approve)

*  Where exactly in the `list_repeat` did you place your check? I suspect before
```
...
if (input_size == 0 || n <= 0)
        return PyList_New(0);
...
```
(otherwise you could skip the `input_size != 0` part in your code). That could make the case `[] * n` a bit slower. 

* After `PyListObject *np = (PyListObject *) list_new_prealloc(input_size);` you need to check for `np==NULL` as the allocation can fail. 
* Since `n==1` you can replace `Py_RefcntAdd(*src, n);` with `Py_INCREF(*src)`.
* Do we need the check `(input_size > PY_SSIZE_T_MAX / n)` for `n==1`?
