### ISSUE TITLE
Add a top() functionality in PriorityQueue() 

### ISSUE THREAD

**Issue by vasisthasinghal** [python/cpython#101772]
# Feature or enhancement

(A clear and concise description of your proposal.) 
Add a top() function to get without removing the element from the queue. 

# Pitch

(Explain why this feature or enhancement should be implemented and how it would be used.
 Add examples, if applicable.)
This feature would enable accessing the top element of the queue without removing it. 

# Previous discussion

**Comment by sweeneyde** [comment]
The analogous issue for `queue.Queue` was here: https://github.com/python/cpython/issues/98097

All the same reasoning applies: The `queue` module is designed with synchronization semantics in mind, so that multiple threads of consumers or producers can share the same queue. If you do not need the extra condition variables, you can use a list `h = []` as a heap, and then you can `heapq.heappush(h, x)`, `heapq.heappop(h)`, and access the root as `h[0]`.

**Comment by rhettinger** [comment]
Thanks for the suggestion, but we will decline for the reasons mentioned by Dennis.  Also, we have an aspiration to keep this API as minimal as possible and fully synced with the APIs for the other queue types.

**Comment by vasisthasinghal** [comment]
Understood! Thanks for the quick response. I'll close the thread now.
