### ISSUE TITLE
Option to not call `shutdown_default_executor`  after `asyncio.run`

### ISSUE THREAD

**Issue by Conchylicultor** [python/cpython#101796]
# Feature or enhancement

It would be nice to have a kwarg to not call `shutdown_default_executor` when `asyncio.run` is called. Something like:

```python
asyncio.run(future, shutdown_default_executor=False)
```

# Pitch

Currently, the following code will fail:

```python
import asyncio


x = asyncio.Future()  # Work

asyncio.run(asyncio.sleep(1))  # Silently call shutdown_default_executor()

y = asyncio.Future()  # Raise: RuntimeError: There is no current event loop in thread 'MainThread'.
```

Currently the workaround is to use the low-level boilerplate event loop:

```python
loop = asyncio.new_event_loop()
loop.run_until_complete(asyncio.sleep(1))
loop.close()
```

I understand mixing multiple even loop is not a good practice, but forcing to use the low level API feels too restrictive.

I encountered this while using https://github.com/deepmind/xmanager. They are using the global event loop and return some future. The only way to access those futures in the global scope (which is required for more complex reason), is to create an event loop (like `asyncio.run(future)`. But doing so makes xmanager API fail afterward with `RuntimeError: There is no current event loop in thread 'MainThread'.`.

**Comment by gvanrossum** [comment]
I can reproduce this too, but I don't think it has anything to do with the default executor. Here's a simpler repro:
```
>>> import asyncio
>>> asyncio.set_event_loop(None)
>>> asyncio.Future()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/guido/cpython/Lib/asyncio/events.py", line 698, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
>>> 
```
This makes me think that the root cause is simply that the default Future constructor (which is written in C) calls `asyncio.get_event_loop()`. Note that you will get a deprecation warning when creating a Future before calling run() -- this is because in some future Python release (3.14?), the initial Future() call will fail too, unless an explicit event loop was set before calling it.

So that's the solution: set an event loop explicitly (e.g asyncio.set_event_loop(asyncio.new_event_loop()) and hold on to that loop. Mixing low-level APIs like calling Future() when there's no running loop and high-level APIs like run() is asking for problems anyway, since run() overwrites the event loop set in the policy.
