### ISSUE TITLE
os: support blocking functions on Windows

### ISSUE THREAD

**Issue by RayyanAnsari** [python/cpython#101881]
The os.get_blocking and os.set_blocking functions are only currently supported on Unix.

### Linked PRs
* gh-101882

**Comment by eryksun** [comment]
When WinAPI `ReadFile()` is called to read from an empty pipe that's in non-blocking mode, the call fails with `ERROR_NO_DATA` (232). The C runtime's `read()` function maps this error code to the `errno` value `EINVAL` (invalid argument). We would have to update all code that calls `_read()` to clarify this case by checking `_doserrno`. This is the Windows error code that was mapped to the C `errno` value. We can manually map `ERROR_NO_DATA` to `EAGAIN` (resource temporarily unavailable) in the `read()` context[^1] and possibly raise `BlockingIOError`, unless `EAGAIN` should be ignored.

When WinAPI `WriteFile()` is called to write to a pipe that's in non-blocking mode, if the size of the write exceeds the available space, then the call succeeds with 0 bytes written[^2]. The C runtime's `write()` function usually handles a 'successful' write with nothing written by failing with `ENOSPC` (no space left on device), except it's not considered an error when writing a string that starts with Ctrl+Z to a character device[^3]. For POSIX compatibility, the error code that we want in this case is `EAGAIN`.

[^1]: The error mapping depends on context. When writing to a pipe, if the read end is closed, this also fails with `ERROR_NO_DATA`, which we need to map to `EPIPE` and raise `BrokenPipeError`. These cases are distinct at the lower level of the NT API. When `NtReadFile()` is called to read from an empty pipe in non-blocking mode, the call fails with `STATUS_PIPE_EMPTY`. When `NtWriteFile()` is called to Write to a pipe for which the read end is closed, the call fails with `STATUS_PIPE_CLOSING`. Unfortunately the Windows API maps both of these status codes to `ERROR_NO_DATA`.

[^2]: It's documented that as much as possible will be written if a byte-type pipe (as opposed to a message-type pipe) is in non-blocking mode. However, in my testing back to Windows NT 4.0 (1996), no data is written to a pipe in non-blocking mode if the write size exceeds the available space. It's all or nothing. This is really for the best since it matches the behavior on Linux.

[^3]: This is bizarre because nothing nowadays implements special behavior for writing Ctrl+Z to a character device. *Reading* from console input via `ReadFile()` is special cased to return 0 bytes read if the line read from the console begins with Ctrl+Z.

**Comment by RayyanAnsari** [comment]
@eryksun thanks for the detailed information about the Win32 API, I've implemented your suggestions in #101882. Though I'm not sure why test_nonblock_pipe_write_bigbuf is failing when test_nonblock_pipe_write_smallbuf is not.

**Comment by eryksun** [comment]
Usage in the io module and test cases will have to be examined for assumptions that partial writes are supported up to the available space in the pipe. On Windows, it's all or nothing in non-blocking mode. If the pipe has 1024 bytes available, then trying to write 2048 bytes will write nothing at all and fail.

**Comment by eryksun** [comment]
Here's an idea to get around the annoying behavior in non-blocking mode. Modify `_Py_write_impl()` to check for this case. If so, cap the write to the size of the pipe, from `GetNamedPipeInfo()`. Eventually the reader will empty the pipe, and a write of the full pipe size will succeed. This allows `test_nonblock_pipe_write_bigbuf()` to succeed.

For example, append the following code to the first `MS_WINDOWS` section in `_Py_write_impl()`.

```c
    // A write that exceeds the available size of a pipe never succeeds in
    // non-blocking mode. Limiting writes to the pipe size in this case allows
    // a buffered write to succeed eventually, as the pipe is read.
    DWORD mode, pipe_size;
    HANDLE hfile = _Py_get_osfhandle(fd);
    if (hfile == INVALID_HANDLE_VALUE) {
        return -1;
    }
    if (gil_held) {
        Py_BEGIN_ALLOW_THREADS
        if (GetFileType(hfile) == FILE_TYPE_PIPE &&
            GetNamedPipeHandleStateW(hfile, &mode,
              NULL, NULL, NULL, NULL, 0) &&
            mode & PIPE_NOWAIT)
        {
            // GetNamedPipeInfo() requires FILE_READ_ATTRIBUTES access.
            // CreatePipe() includes this access for the write handle.
            if (!GetNamedPipeInfo(hfile, NULL, &pipe_size, NULL, NULL)) {
                pipe_size = 4096;
            }
            if (count > pipe_size) {
                count = pipe_size;
            }
        }
        Py_END_ALLOW_THREADS
    }
    else {
        if (GetFileType(hfile) == FILE_TYPE_PIPE &&
            GetNamedPipeHandleStateW(hfile, &mode,
              NULL, NULL, NULL, NULL, 0) &&
            mode & PIPE_NOWAIT)
        {
            if (!GetNamedPipeInfo(hfile, NULL, &pipe_size, NULL, NULL)) {
                pipe_size = 4096;
            }
            if (count > pipe_size) {
                count = pipe_size;
            }
        }
    }
```

**Comment by eryksun** [comment]
The documentation in "Doc/library/os.rst" needs to be updated to indicate the new Windows support in 3.12, `.. availability::` and `.. versionchanged::`, plus a brief description that Windows support is limited to pipes. 

For example:

```text
.. function:: get_blocking(fd, /)

   Get the blocking mode of the file descriptor: ``False`` if the
   :data:`O_NONBLOCK` flag is set, ``True`` if the flag is cleared.

   See also :func:`set_blocking` and :meth:`socket.socket.setblocking`.

   .. availability:: Unix, Windows.

      The function is limited on Emscripten and WASI, see
      :ref:`wasm-availability` for more information.

      On Windows, this function is limited to pipe files.

   .. versionadded:: 3.5
   
   .. versionchanged:: 3.12
      Added support for Windows
```

```text
.. function:: set_blocking(fd, blocking, /)

   Set the blocking mode of the specified file descriptor. Set the
   :data:`O_NONBLOCK` flag if blocking is ``False``, clear the flag otherwise.

   See also :func:`get_blocking` and :meth:`socket.socket.setblocking`.

   .. availability:: Unix, Windows.

      The function is limited on Emscripten and WASI, see
      :ref:`wasm-availability` for more information.

      On Windows, this function is limited to pipe files.

   .. versionadded:: 3.5

   .. versionchanged:: 3.12
      Added support for Windows
```

**Comment by RayyanAnsari** [comment]
done, anything else needed?
