### ISSUE TITLE
Add `__name__` to property

### ISSUE THREAD

**Issue by eltoder** [python/cpython#101860]
```python
class C:
    @property
    def foo(self):
        return 1

assert C.foo.__name__ == "foo"
```
It would be very handy if this worked, so properties can be introspected the same way as functions, classmethods, etc. Name can be simply taken from `fget` the same way this is done for `__isabstractmethod__`.

### Linked PRs
* gh-101876
* gh-123399
* gh-123428

**Comment by sobolevn** [comment]
What about this case?

```python
>>> def getter(o):
...     return 42
... 
>>> class Some:
...    number = property(getter)
... 
>>> Some().number
42
```

Should it be `'getter'`?

**Comment by TeamSpen210** [comment]
Actually, `property` already [defines `__set_name__()`](https://github.com/python/cpython/blob/6ef6915d3530e844243893f91bf4bd702dfef570/Objects/descrobject.c#L1545-L1564), storing the name internally for use in formatting `AttributeError`s. That's called during class creation, so it'll be accurate regardless where the callable comes from. All that's needed is for that to be exposed. This was added in #71981, but it was [kept private](https://github.com/python/cpython/issues/71981#issuecomment-1093723025) to avoid expanding the API since a need wasn't specified.

**Comment by eltoder** [comment]
@TeamSpen210 Nice find! I think the API expansion comments were about adding `name` as an argument to `property` constructor. Adding `__name__` as a read-only attribute for introspection seems very much in the spirit of python.

**Comment by JelleZijlstra** [comment]
This is a change to a builtin and likely has an impact on some introspection tools, so it should be mentioned in the What's New for 3.13.

**Comment by picnixz** [comment]
Closing since the feature is now documented in 3.13 and 3.14.
