### ISSUE TITLE
Argparse is ignoring the double quotes

### ISSUE THREAD

**Issue by Nriver** [python/cpython#101984]
Argparse is ignoring the double quotes

- CPython versions tested on: 3.10.9
- Operating system and architecture: Manjaro x64

Sample code

```python
import argparse
ap = argparse.ArgumentParser()
ap.add_argument('-c', '--conf', required=False, default='conf.ini')
ap.add_argument('--params', required=False, default='')
args = vars(ap.parse_args())
print(args)
```

`-c` is for config file. `--params` is some param for some external programs. They are both optional args.
Something unexpected happened when I test it with this comamnd.

```console
❯ python 1.py --params "-c 12"
usage: 1.py [-h] [-c CONF] [--params PARAMS]
1.py: error: argument --params: expected one argument
```

I am not passing anything to `-c`, while a string which happens to contain a substring `-c` to `--params`. After little debug, it seems that argparse ignored the double quotes and assgined `12` for param `-c`, and left nothing for `--params`.

**Comment by ericvsmith** [comment]
There are two things going on here. First, your shell is "eating" the double quotes, so what argparse is seeing is:

```pycon
>>> ap.parse_args(["--params", "-c 12"])
usage: [-h] [-c CONF] [--params PARAMS]
: error: argument --params: expected one argument
```

The other is that argparse pre-scans the args to see what it thinks are params and finds the "-c". While it doesn't always work, in this case you can get around it by passing "--params=-c 12" as a single (quoted) value on the command line, which gives you:

```pycon
>>> ap.parse_args(["--params=-c 12"])
Namespace(conf='conf.ini', params='-c 12')
```

See https://github.com/python/cpython/issues/53580 for a very long discussion which ended with "we're not going to change this".

Since this is a known problem with argparse that's not going to change, I'm going to close this.

**Comment by Nriver** [comment]
@ericvsmith  Thanks for the reply. Do you have a suggestion for any alternative module that can work for my problem?

**Comment by ericvsmith** [comment]
I’ve moved all of my code to click. None of the stdlib options are awesome, but that’s okay.
