### ISSUE TITLE
zip() docstring should comment on the difference in handling ordered and unordered interables

### ISSUE THREAD

**Issue by doolio** [python/cpython#101939]
# Documentation

The `zip()` docstring does not mention how the grouping of items into n-tuples differs when passing iterables that are unordered as opposed to ordered. I think it would be an improvement to include that detail.

Example:
```pycon
>>> numbers = [1, 2, 3]
>>> letters = ['a', 'b', 'c']
>>> list(zip(numbers, letters))  # [(1, 'a'), (2, 'b'), (3, 'c')]
>>> s1 = {2, 3, 1}
>>> s2 = {'b', 'a', 'c'}
>>> list(zip(s1, s2))  # [(1, 'a'), (2, 'c'), (3, 'b')] or something else
```

**Comment by AlexWaygood** [comment]
Thanks for the suggestion, but I don't think this should be included in the `zip()` docstring. This isn't anything specific to how `zip()` works; it's just due to the fact that sets are unordered collections, which is stated clearly in the [documentation for `set` objects](https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset). You'll find similar behaviour with `map()`, `filter()`, `itertools.filterfalse()`, etc etc — we'd have to update a lot of docstrings if we wanted to note in every iterator class or function's docstring that iterating over an unordered container could lead to any arbitrary order in the output :)

**Comment by terryjreedy** [comment]
Agreed.

**Comment by doolio** [comment]
Firstly, thanks for the quick response.

> we'd have to update a lot of docstrings if we wanted to note in every iterator class or function's docstring that iterating over an unordered container could lead to any arbitrary order in the output :)

Ah, I didn't appreciate that point. That's fair and thanks for considering my suggestion in any case.

> You'll find similar behaviour with `map()`, `filter()`, `itertools.filterfalse()`, etc

Thanks, good to know. I'm still very early on my journey to learn programming and was learning  about `zip()` yesterday.

**Comment by AlexWaygood** [comment]
Good luck on your journey learning Python!
