### ISSUE TITLE
CI: intermittent macOS failures for make checksharedmods

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#101981]
I've seen a couple of these on `main` and on various PRs. Example failure:

https://github.com/python/cpython/actions/runs/4199421484/jobs/7284276265

### Linked PRs
* gh-101991
* gh-102070
* gh-102072
* gh-102073
* gh-102074
* gh-102076
* gh-102081
* gh-102082
* gh-102094
* gh-102095
* gh-102131
* gh-102177
* gh-102178
* gh-102186
* gh-102187

**Comment by erlend-aasland** [comment]
FYI, this target runs `/Tools/build/check_extension_modules.py` using `PYTHON_FOR_BUILD`.

**Comment by erlend-aasland** [comment]
`main` has been failing regularly since a5024a261a75dafa4fb6613298dcb64a9603d9c7

**Comment by sblondon** [comment]
I wonder if this error is linked to https://github.com/actions/runner-images/issues/7128

**Comment by pradyunsg** [comment]
Not sure if it's totally related to this, but a PR upgrading pip's wheel on 3.8 (which shouldn't really affect the test_mkfifo_dir_fd) triggered a segfault on the macOS test run.

https://github.com/python/cpython/actions/runs/4269978257/jobs/7433511913#step:6:651

Looking through the issue tracker, I don't see that failure mode reported as is and I'm noting it here mostly since I'm not sure if it's in any way related to this ongoing thing or if it should be a separate issue. It doesn't seem like it is, but I've not followed the failure discussions here closely to know for sure. 😅

**Comment by pradyunsg** [comment]
Filed https://github.com/python/cpython/issues/102306 as a tracking issue for the test_mkfifo_dir_fd segfaults.

**Comment by erlend-aasland** [comment]
Reopening: there are still backports waiting to be merged or closed.

**Comment by corona10** [comment]
@erlend-aasland Now we can close this issue, WDYT?

**Comment by erlend-aasland** [comment]
Yes, let's close this.
