### ISSUE TITLE
error: externally-managed-environment

### ISSUE THREAD

**Issue by krishnaTORQUE** [python/cpython#102134]
# Crash & Error
```bash
krishna@torque:~$ python3 -m pip install pip
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

# Your environment

- CPython versions tested on: Python 3.11.2
- Operating system and architecture: Debian 11, Gnome 42, x86_64

It was working until today its howing this error. sell & setuptools are installed.
I am just trying to install or update python module & for every module, its showing this error.

**Comment by JelleZijlstra** [comment]
This looks like Debian patched something (either pip or CPython itself) to nudge you towards using virtual environments. If that doesn't work for you, please report it to Debian.

**Comment by kkl90** [comment]
I have same thing after I installed some packages on kali. I guess that python, and so on pip got updated. The virtual env. does work, and I can install modules, but, the python scripts does not detect any module, and gives the: "error: no module named [module]".

**Comment by Ghost1292** [comment]
this works for me , it says at the end of the error message  --break-system-package.

**Comment by jesorian** [comment]
I got the same thing on my kali box.

**Comment by jetsup** [comment]
I did a full system upgrade in my Kali machine, ```python3 --version``` now became ```3.11.2``` and in turn all the modules I had installed though *pip3* cannot be found and, on top, I am getting the error ```errror: externally-managed-environment```.

**Comment by Yukifar** [comment]
@jetsup Literally that's what happened to me as well

**Comment by ArifNL** [comment]
how to fix this?

**Comment by davidcohain** [comment]
I have the same problem, Is there something wrong with the last update !
any Ideas how to fix this 🙏

**Comment by fsocietyxzy** [comment]
yes same here it give me "error: externally-managed-environment" what's happening python say smth i got this error after i upgrade my kali

**Comment by cyb3rsec1990** [comment]
does alreadt anyone fix this ?

**Comment by Feliperdg** [comment]
Can anyone help to fix this problem? please

**Comment by 0xMrR0b0t** [comment]
hello everyone i fixed this problem using kali documentation

**Comment by Feliperdg** [comment]
tell us how you did it

**Comment by 0xMrR0b0t** [comment]
i'm sending you full command list

**Comment by 0xMrR0b0t** [comment]
1.sudo apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git
2. curl https://pyenv.run | bash
3. echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc
4. echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc
5. echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init --path)"\nfi' >> ~/.zshrc
6. exec $SHELL
7. pyenv
8. pyenv install 3.11.2
9. pyenv global 3.11.2
10. pyenv versions

**Comment by 0xMrR0b0t** [comment]
@everone need to run this all command to fix your error

**Comment by Feliperdg** [comment]
@jetsup

**Comment by 0xMrR0b0t** [comment]
> @jetsup

fixed man??

**Comment by Feliperdg** [comment]
even running the commands, PyRoxy problem remains now

**Comment by Feliperdg** [comment]
continuous with the same problem too, it was just updating apt upgrade that happened

**Comment by 0xMrR0b0t** [comment]
> even running the commands, PyRoxy problem remains now

can you sand screen shot

**Comment by Feliperdg** [comment]
![image](https://user-images.githubusercontent.com/111777688/221379491-c32eb3bb-86ad-41c1-af27-6e136b1ba3a6.png)

**Comment by 0xMrR0b0t** [comment]
> 

check pyroxy pip virsion

**Comment by 0xMrR0b0t** [comment]
https://discord.gg/xhGYKYFv
join our discord i will help you in discord channel and vc

**Comment by Feliperdg** [comment]
I'm there

**Comment by sp1d3o** [comment]
> https://discord.gg/xhGYKYFv join our discord i will help you in discord channel and vc

May I please also ask for help?

**Comment by richplaya** [comment]
> https://discord.gg/xhGYKYFv
> join our discord i will help you in discord channel and vc

I'm having the same problem. Please help me.![Screenshot_20230226-120231_Facebook.png](https://user-images.githubusercontent.com/118781200/221399212-011529e4-7bab-40ca-b2d5-6b9e8cddb569.png)

**Comment by Samsc126** [comment]
> this works for me

Thanks

**Comment by Samsc126** [comment]
> 1.sudo apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git 2. curl https://pyenv.run | bash 3. echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc 4. echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc 5. echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init --path)"\nfi' >> ~/.zshrc 6. exec $SHELL 7. pyenv 8. pyenv install 3.11.2 9. pyenv global 3.11.2 10. pyenv versions

This works - - - Thanks

**Comment by brandongillett** [comment]
Seems like this is due to the new release of pip 23.0.1, just downgrade to the last known working version using the command:
python -m pip install pip==22.2.2 --upgrade --break-system-packages
Hope this helps!

**Comment by 0xMrR0b0t** [comment]
> > 1.sudo apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git 2. curl https://pyenv.run | bash 3. echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc 4. echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc 5. echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init --path)"\nfi' >> ~/.zshrc 6. exec $SHELL 7. pyenv 8. pyenv install 3.11.2 9. pyenv global 3.11.2 10. pyenv versions
> 
> This works - - - Thanks

welcome man

**Comment by Surfwhale** [comment]
> 1.sudo apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git 2. curl https://pyenv.run | bash 3. echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc 4. echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc 5. echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init --path)"\nfi' >> ~/.zshrc 6. exec $SHELL 7. pyenv 8. pyenv install 3.11.2 9. pyenv global 3.11.2 10. pyenv versions

It works for me too..TQ

**Comment by Zenius07** [comment]
> 1.sudo apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git 2. curl https://pyenv.run | bash 3. echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc 4. echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc 5. echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init --path)"\nfi' >> ~/.zshrc 6. exec $SHELL 7. pyenv 8. pyenv install 3.11.2 9. pyenv global 3.11.2 10. pyenv versions

Я это сделал и ошибка пропала, но у меня появилась другая ошибка.
![image](https://user-images.githubusercontent.com/94601067/221419514-6dfbc1fe-ac7a-476f-9d12-bc9726523fb7.png)

**Comment by osman876** [comment]
> 



> https://discord.gg/xhGYKYFv join our discord i will help you in discord channel and vc



> > 1.sudo apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git 2. curl https://pyenv.run | bash 3. echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc 4. echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc 5. echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init --path)"\nfi' >> ~/.zshrc 6. exec $SHELL 7. pyenv 8. pyenv install 3.11.2 9. pyenv global 3.11.2 10. pyenv versions
> 
> It works for me too..TQ

i am getting still same error

**Comment by osman876** [comment]
> > > 1.sudo apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git 2. curl https://pyenv.run | bash 3. echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc 4. echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc 5. echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init --path)"\nfi' >> ~/.zshrc 6. exec $SHELL 7. pyenv 8. pyenv install 3.11.2 9. pyenv global 3.11.2 10. pyenv versions
> > 
> > 
> > This works - - - Thanks
> 
> welcome man

i am getting same error now also

**Comment by blopax3** [comment]
try 
1. python3 -m venv venv
2. source venv/bin/activate

**Comment by osman876** [comment]
> try
> 
> 1. python3 -m venv venv
> 2. source venv/bin/activate

for sudo i am getting error for virtualenv it is fine

**Comment by 0xMrR0b0t** [comment]
> > > > 1.sudo apt install -y build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git 2. curl https://pyenv.run | bash 3. echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.zshrc 4. echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshrc 5. echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n eval "$(pyenv init --path)"\nfi' >> ~/.zshrc 6. exec $SHELL 7. pyenv 8. pyenv install 3.11.2 9. pyenv global 3.11.2 10. pyenv versions
> > > 
> > > 
> > > This works - - - Thanks
> > 
> > welcome man
> 
> i am getting same error now also

Restart your linux

**Comment by CAM-Gerlach** [comment]
# What Is this?

As the message you're getting explains, ***this is actually not any issue with Python itself***, but rather your Linux distribution (Kali, Debian, etc.) implementing a deliberate policy to ensure you don't break your operating system and system packages by using ``pip`` (or another non-OS package manager, like Poetry, Hatch or PDM) outside the protection of a [virtual environment](https://docs.python.org/3/library/venv.html).

This has been a long-standing recommendation from both the Python team and Linux distros, due to the severe problems that frequently occur for people as a result of using `pip` or other package managers directly with your system Python.

# What should I do about it?

As the error message tells you, [create and activate a virtual environment](https://packaging.python.org/en/latest/tutorials/installing-packages/#creating-virtual-environments) for your project, and then use pip (or another non-system package manager, like Poetry, Hatch or PDM) to install the packages you need.

Alternatively, for command-line applications and tools you want to be available system-wide, install and run them with a tool like [pipx](https://pypa.github.io/pipx/).

Finally, if the packages provided by your distribution meet your needs, install the software you want with your system package manager (`apt`, `dnf`/`yum`, `pacman`, etc) instead. See your distro's documentation for more information.

<details>

<summary>Here be dragons...read this part at your own risk!</summary>

If you're really, really, really sure you want to use `pip` or another non-system package manager directly on the packages installed by your Linux distribution, you can pass the [`--break-system-packages`](https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-break-system-packages) flag to `pip`. However, it will do exactly what it says if you aren't _extremely_ careful, so if you aren't 120% sure you're an expert who knows _exactly_ what you're doing, **don't** use it. And if you do, don't say I didn't warn you! :) 

</details>

# Where can I get more information?

The message you get should explain where you can find more information specific to your distro, and for those curious [PEP 668: Marking Python environments as externally managed](https://peps.python.org/pep-0668/) has the full technical details.

# What about the other workarounds proposed in this thread? Why is it closed?

We appreciate folks trying to help other users! However, the other approaches that users had come across were all temporary workarounds that were likely to break down the line rather than truly solving the real problem, and unfortunately made it much harder for users to find the actual solution, and much easier to get confused as to which was the right one. Since we wanted to make sure that you can all find the accurate answer to your questions, and since there's nothing else we can do on CPython's end (since this is controlled by your Linux distro), we've closed/lock the issue with this as the final comment, and collapsed duplicate and outdated comments by default to make it easier for viewers to navigate. Thanks for your understanding, and hope this is helpful!
