### ISSUE TITLE
Windows embeddable python: In Version 3.11 import site does not work anymore in python311._pth

### ISSUE THREAD

**Issue by Wissperwind** [python/cpython#102169]
Hi,

I use a windows 64bit embeddable python. It contains a python311._pth file, where you can specify the python path.
It also contains:
```
# Uncomment to run site.main() automatically
#import site
```
The idea is that you can uncomment the import and then python executes tha main() from the site script in the python311.zip.
In python 3.10 this works fine. But in python 3.11 I think it does not work anymore.

The background:
I want my embeddable python to have the empty string in pythonpath. So that if you execute a script in a specific folder, all other scripts in that folder are in python path and can be imported. I achieved this in python 3.10 by replacing the compiled site script in the zip with an uncompiled version. And then I added a line to add "" to the pythonpath to the script. It was executed on every python launch. But in python 3.11 the site script is not executed. I added prints. But the site script is just not executed. I can even delete the site script from python311.zip and it is not missing...

**Comment by eryksun** [comment]
The `site` module is frozen in "python311.dll". You can disable using frozen modules by passing the command-line argument `-X frozen_modules=off`. 

However, I'd avoid patching the standard library unless it were the only option. There's an alternative in this case. Create a "sitecustomize.py" module beside "python311.\_pth" (assuming the latter contains a "." entry). The final step in `site.main()` is to try to import `sitecustomize` and `usercustomize`.

> I want my embeddable python to have the empty string in pythonpath. So that if you execute a script in a specific folder, all other scripts in that folder are in python path and can be imported.

An empty string in `sys.path` is the current working directory, not the script directory. When a script is executed, the working directory is whatever was set by the parent process. In general, this is not the script directory. Also, the working directory can change, e.g. via `os.chdir()`.

Here's an example "sitecustomize.py" that prepends the script directory to `sys.path`.

```python
import os
import sys

if len(sys.argv) > 0 and sys.argv[0] and sys.argv[0] not in ('-c', '-m'):
    path = [os.path.dirname(os.path.abspath(sys.argv[0]))]
    norm_script_dir = os.path.normcase(path[0])
    for p in sys.path:
        if os.path.normcase(p) != norm_script_dir:
            path.append(p)
    sys.path[:] = path
```

---

Personally, I'd avoid adding `import site` to the ".\_pth" file in an embedding context. It adds the user site packages directory to `sys.path`, and it processes user ".pth" files and imports `usercustomize`, if it exists. I'd rather build my own executable that customizes `sys.path` instead of relying on `site` extension mechanisms that aren't controlled by the application.

**Comment by Wissperwind** [comment]
Hi eryksun,
Thanks! I discovered the possibility of sitecustomize a few hours ago. It provides exactly what I need. I will not import site anymore. I will write a sitecustomize.py which assembles my pythonpath excatly how I need it.
I just did not know that site is a frozen module now. Never heard of drozen modules bevore.
So you can remove the site.pyc from python311.zip?
The issue can be closed now from my side.

**Comment by eryksun** [comment]
> I will not import site anymore. 

You still need to include `import site` in "python311._pth". `site.main()` is what imports `sitecustomize` and `usercustomize` at startup.

> So you can remove the site.pyc from python311.zip?

It's required when running with `-X frozen_modules=off`.

**Comment by Wissperwind** [comment]
ok
