### ISSUE TITLE
I can't upload my library to PyPI

### ISSUE THREAD

**Issue by Eduardo372-ai** [python/cpython#102132]
# Bug report
I can't upload my library to PyPI with Twine
Invalid or non-existent authentication information

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment
Python 3.11.1
Twine

- CPython versions tested on:
- Operating system and architecture:
  Windows 10 Pro x64

**Comment by terryjreedy** [comment]
You left out the "clear and concise description of what the bug is" and the MRE.  What did you actually do?  How is this a cpython issue?  Especially given the note about bad authentication information?

This is most likely a problem with your code or upload procedure.  If you don't have definite cpython bug evidence, close this and ask for help on discuss.python.org or stackoverflow.com.
