### ISSUE TITLE
replace use of getpid on Windows with GetCurrentProcessId

### ISSUE THREAD

**Issue by maxbachmann** [python/cpython#102141]
# Feature or enhancement

Windows provides `getpid`, `_getpid` and `GetCurrentProcessId` to retrieve the process identifier. `getpid` is deprecated in favor of `_getpid`. In addition both `getpid` and `_getpid` cannot be used by application that execute in the Windows Runtime.

### Linked PRs
* gh-102142

**Comment by maxbachmann** [comment]
> Is this a relevant concern? Python also uses _wenviron, _wgetenv(), _wputenv(), _wspawnv(), _wspawnve(), and _wsystem(), all of which are documented as being unavailable when building a UWP app.

I am currently porting CPython to the XBox. So yes these are an issue as well ;)
It would be great to reduce the amount of local patching I need to get this to work.

**Comment by zooba** [comment]
Some of those are going to be harder to deal with, and possibly require a build option. It might be better to start with detecting a UWP build (I believe there are preprocessor variables for it, but also a header file that calculates the app family) rather than trying to replace UCRT functions.

I don't believe the UCRT was ever different on UWP, other than it would fail on functions that used Win32 APIs that were missing. So if the function is there but not used, it shouldn't matter. And if the underlying API is there (and the underlying APIs have been growing quickly) it should be fine.

My point is, replacing UCRT calls with direct Win32 calls shouldn't make a difference here. There are probably some rare cases (most likely due to miscommunications), but I'd expect we have to omit or fully replace functions.

**Comment by maxbachmann** [comment]
Yes this one is certainly not the norm. I mainly did this first, since it did not appear to require detecting an UWP build. `GetCurrentProcessId` is already used in the socketmodule: https://github.com/python/cpython/blob/928752ce4c23f47d3175dd47ecacf08d86a99c9d/Modules/socketmodule.c#L6174.

At least right now I use the following detection for detection for desktop apps:
```cpp
#if !defined(WINAPI_FAMILY) || (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP)
#define MS_WIN_DESKTOP_APP
#endif
```
This should be required for most other changes.

**Comment by zooba** [comment]
I'm less concerned about precedents using Win32 API elsewhere in our sources, and more concerned about within posixmodule. It comes down to _is the UCRT our POSIX emulation layer? Or are we going to implement it ourselves?_ Right now, it's UCRT, and the only exceptions are things that are broken in UCRT where we need more correct behaviour.

If we start taking PRs that make it look like we want to replace innocuous UCRT functions with Win32 APIs, we'll get more of those PRs, and will have to justify refusing those while accepting the past ones.

Since the limited UWP API set is our special case right now, I'd rather have a define that encapsulates "definitely a Windows UWP not-full trust app". The detection you posted would require testing for `#if defined(MS_WINDOWS) && !defined(MS_WIN_DESKTOP_APP)` to choose when to apply workarounds. I'd rather it be `#ifdef MS_WINDOWS_UWP` for the case where we need to avoid certain APIs.

**Comment by maxbachmann** [comment]
Thanks for the explanation. I will update the PR to perform the workarounds only on UWP.

**Comment by zooba** [comment]
Now the variable is in there, feel free to bundle other workarounds in the same PR (new issue). If it gets too complex all together, that's probably a sign that a different approach may be needed, but if they're all basically like this one then there's nothing to be gained by doing them all individually.
