### ISSUE TITLE
Confusion in regular expression syntax example.

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#102259]
In the 3.11 documentation, the regular expression syntax section reads, in part:

> To match a literal ']' inside a set, precede it with a backslash, or place it at the beginning of the set. For example, both `[()[\]{}]` and `[]()[{}]` will both match a parenthesis.

The discussion centers on matching a right square bracket, but the end phrase reads, "... will both match a parenthesis." I suspect the author meant something like "... will both match left or right braces, parentheses or square brackets."

The same wording exists in 2.7 and 3.5 through 3.12. I doubt it's worth backporting beyond whatever is still being actively bugfixed.

### Linked PRs
* gh-102264
* gh-102270
* gh-102271

**Comment by terryjreedy** [comment]
Thank you Skip.  I have seen this anomaly but never stopped to open an issue.  I propose to replace 'a parenthesis' with 'a right bracket, as well as left bracket, braces, and parentheses'.  What do you think?  If OK, can you make a PR and ask me to review?

 Doc changes are usually backported to bugfix releases when applicable and easily done.  Thank you for the note that both are true. They are almost never backported to security releases and then only by the release manager.  (Prior releases are frozen ;-)

Use a single `>` to blockquote text.  This results in proper wrapping instead of a horizontal scroll bar.  The examples needed backticks to display properly.

**Comment by smontanaro** [comment]
Sure, I'll whip something up. Thanks for the Markdown suggestion. I seem to always choose incorrectly between "code" and "quote".
