### ISSUE TITLE
Hash collision of simple tuple

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [python/cpython#102352]
# Bug report

When I do:
```python
>>> hash((501, -1))
2671086736621881696
>>> hash((501, -2))
2671086736621881696
```

The equality of the hash does not seem right.

# Your environment

- CPython versions tested on: 3.11.0
- Operating system and architecture: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

**Comment by pochmann** [comment]
Can you find a third tuple with that same hash?

**Comment by TeamSpen210** [comment]
This is because of the value `-1`. For whole numbers, the hash value is simply that as an integer (wrapping if outside the limit). But `-1` is a reserved return value from the function to indicate an exception was raised, so `hash(-1)` instead returns `-2`. Tuples simply combine the hashes of their elements, so you get the same hash. This isn't actually an issue `hash()` isn't meant to be particularly collision resistant, unpredictable, etc. They're unnecessary for insertion into a dict, and would just slow it down.

**Comment by stevendaprano** [comment]
There is no bug here. Hashes are not unique, and there are many hash collisions. It is just that -1 and -2 happen to be easy to find, but there are many others:

```
>>> hash(1) == hash(2**61) == hash(2**122)
True
```

@TeamSpen210 I think you are incorrect to say that hashes are not meant to be collision resistant. If that were true, we could simplify the hash function to just always return 1 for every object. Good hash functions should be collision resistant. But collision resistant doesn't mean that there are no collisions at all.
