### ISSUE TITLE
ipaddress._BaseAddress has no attribute _string_from_ip_int

### ISSUE THREAD

**Issue by narel** [python/cpython#102366]
# Bug report

ipaddress._BaseAddress class has no `_string_from_ip_int` attribute, but it is used in `__str__` method:

```
>>> from ipaddress import _BaseAddress
>>> _BaseAddress()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/narel/.pyenv/versions/3.10.9/lib/python3.10/ipaddress.py", line 607, in __repr__
    return '%s(%r)' % (self.__class__.__name__, str(self))
  File "/home/narel/.pyenv/versions/3.10.9/lib/python3.10/ipaddress.py", line 610, in __str__
    return str(self._string_from_ip_int(self._ip))
AttributeError: '_BaseAddress' object has no attribute '_string_from_ip_int'. Did you mean: '_prefix_from_ip_int'?
```

# Your environment

- CPython versions tested on: 3.10.9
- Operating system and architecture: Ubuntu 22.04 x86_64

**Comment by terryjreedy** [comment]
Confirmed in 3.12.0a5.  This is a subtle bug and the naive fix of accepting the suggestion would be wrong.  `_BaseAddress` inherits from `_IPAddressBase`.  Neither have `__new__` or  `__init__` methods, which is why no argument was needed.  It is a mixin used in IPv4Address and IPv6Address, which also inherit from the `_BaseV4` and `_BaseV6` mixins.  The latter two *do* have `_string_from_ip_int` methods.  These return dotted decimal strings. So when _BaseAddress is used as intended, as a mixin, there is no bug.  And it would be wrong to change `_BaseAddress.__str__` to use anything else when used properly.  "_BaseAddress " does not appear in test_ipaddress, so it is not tested as a standalone class.

One possible solution would be to prevent efforts to instantiate it directly, but I don't know if this is possible, and I think one should be able to instantiate to test, assuming that this makes sense.

Another is to catch AttributeError and substitute another string, perhaps '0.0.0.0' (legal?) or just '_BaseAddress instance''?

There may be other methods that fail without the other mixin, or other (Interface) mixins with a similar dependency.

**Comment by iritkatriel** [comment]
Why is this a bug? It’s not intended to be used standalone, and it doesn’t.

**Comment by sobolevn** [comment]
I agree that this is not a bug, it is a protected not-documented (implicitly) abstract base class. It should not be used alone. It is intended to be used with `_BaseV4` and `_BaseV6` mixing classes.
