### ISSUE TITLE
`_osx_support.get_platform_osx()` does not always return the minor release number

### ISSUE THREAD

**Issue by keleftheriou** [python/cpython#102362]
`_osx_support.get_platform_osx()`, particularly when called from `sysconfig.get_platform()`, might not return the minor release number. This seems to be because the `MACOSX_DEPLOYMENT_TARGET` environment variable will be used instead (if present), which may or may not include a minor version number.

E.g. on macOS 12.6 with `MACOSX_DEPLOYMENT_TARGET=12`:
```
>>> _osx_support.get_platform_osx({}, "", "", "")
('macosx', '12.6', '')
>>> _osx_support.get_platform_osx(sysconfig.get_config_vars(), "", "", "")
('macosx', '12', '')
```

Perhaps `release = macver` could be switched to `release = macrelease` [here](https://github.com/python/cpython/blob/2f62a5da949cd368a9498e6a03e700f4629fa97f/Lib/_osx_support.py#L514) so that the internal `_get_system_version()` will be used instead?

### Linked PRs
* gh-112942
* gh-113264
* gh-113265

**Comment by terryjreedy** [comment]
It seems to me that TARGET without minor release suggests that minor release no. is not relevant.  I have no thought on the other case.

**Comment by keleftheriou** [comment]
Agreed, it shouldn't be relevant. The reason I looked into this is because a wheel file I'm generating is producing this error: `[REDACTED]_macosx_12_arm64.whl is not a supported wheel on this platform.`, and the filename is derived from `sysconfig.get_platform()`. 

If I manually rename it the file to add e.g. `_0` after `macosx_12` it works fine, and I was looking to identify the root cause of the issue. Perhaps always including a zero for the minor version returned from `get_platform_osx()` would be more consistent.

**Comment by keleftheriou** [comment]
May be related: https://github.com/pypa/wheel/issues/385#issuecomment-738224783

**Comment by ronaldoussoren** [comment]
I've added a PR that will add '.0' to the version when MACOSX_DEPLOYMENT_TARGET is set to just a major version.

The PR is labelled for back port to 3.11 and 3.12, but I'm not sure if this is a change that is suitable for back ports.

* [+/-]: This doesn't affect our installers at all as those get build with 10.9 as the deployment target
* [+]: This fixes an inconsistency in the result from ``sysconfig.get_platform()`` w.r.t. expectations from pip/platform
* [-]: The fix likely isn't necessary for build tooling because, in particular, the wheel project already contains a workaround for this
* It is hard to gauge whether or not this negatively impact existing code (e.g. code that expects that the version exactly matches the deployment target).

**Comment by ronaldoussoren** [comment]
@ned-deily, what's your opionion on this (both the change to make sure that the platform version includes at least a major and minor version and back porting this change)?

**Comment by ned-deily** [comment]
I think this is a long-standing bug, ever since Apple changed the semantics of macOS release numbers with macOS 11, and this should be the least-disruptive fix for it. The only gotcha I can think of is if the standard lib `_osx_support` isn't being called, perhaps by a distutils replacement. We *could* consider in addition changing `configure.ac` to do something similar if MACOSX_DEPLOYMENT_TARGET defaults to only a major version, but not if explicitly set by a variable. Again, as far as backporting, perhaps just to 3.12 to start?

**Comment by ronaldoussoren** [comment]
> I think this is a long-standing bug, ever since Apple changed the semantics of macOS release numbers with macOS 11, and this should be the least-disruptive fix for it. The only gotcha I can think of is if the standard lib `_osx_support` isn't being called, perhaps by a distutils replacement. We _could_ consider in addition changing `configure.ac` to do something similar if MACOSX_DEPLOYMENT_TARGET defaults to only a major version, but not if explicitly set by a variable. Again, as far as backporting, perhaps just to 3.12 to start?

The public interface for this is ``sysconfig.get_platform()``, anyone that calculates the platform on their own can adjust the version manually.  

I'll merge the back port to 3.11 as well. The most because this fixes a bug: the result of ``sysconfig.get_platform()`` currently is not valid according to ``packaging`` when MACOSX_DEPLOYMENT_TARGET is set to a value with just a major version.
