### ISSUE TITLE
Blue Screen Error with Python 3.11.2

### ISSUE THREAD

**Issue by Laraib9** [python/cpython#102311]
On the 21st of February, 24 of my students [downloaded and installed Python Idle version 3.11.2](https://www.python.org/downloads/) on their laptops. About 10 of them complained about their systems crashing and restarting (Blue Screen Error) after having installed Python Idle. Can someone please let me know if you've received similar feedback from other users about this specific version? 

We have asked the students to uninstall it from their systems for now. Please note that my students have both Mac and Windows systems.

**Comment by arhadthedev** [comment]
Could you list Mac and Windows versions (and, if possible, hardware configuration), please? It's highly untypical to be able to crash an OS kernel from an application so some strange iteraction should take place and we need to reproduce this.

**Comment by terryjreedy** [comment]
This is first report of a problem with IDLE on 3.11.2.  In fact, I believe IDLE is unchanged since 3.11.1 and unchanged or mostly unchanged from 3.11.0.  So I wonder if IDLE is reallly the problem.  Your students are installing Python and optionally the IDLE app that runs on Python and the tkinter gui.  Please test Python by itself and tkinter without IDLE.  Assuming py launcher was installed (*highly* recommended), open CommandPrompt and run `py -3.11` and if that runs, `py -m tkinter` (a basic tkinter test), and if that runs, `py -m test` (tests everything, about 20 minutes).

**Comment by pochmann** [comment]
What unusual thing do they have in common? Are the laptops provided by the school, with special software or configuration?

**Comment by arhadthedev** [comment]
To fix a bug we need to reproduce it and use a debugger to find the crashing system call and its arguments. Otherwise, this issue will stay unresolved forever.
