### ISSUE TITLE
`isinstance` on `runtime_checkable` `Protocol` has side-effects for `@property` methods

### ISSUE THREAD

**Issue by chrisjsewell** [python/cpython#102433]
For example:

```python
from typing import Protocol, runtime_checkable

@runtime_checkable
class X(Protocol):
   @property
   def myproperty(self): ...

class Y:
   @property
   def myproperty(self):
      raise RuntimeError("hallo")

isinstance(Y(), X)
```

will raise the `RuntimeError`

This is an issue, for example, if `myproperty` is an expensive call, has unwanted side effects, or excepts outside of a context manager

### Linked PRs
* gh-102449
* gh-102592
* gh-102593
* gh-103034

**Comment by chrisjsewell** [comment]
Apologies, if this is a duplicate, or the wrong place to raise this, but I couldn't find anything much on this issue outside of https://stackoverflow.com/questions/66641191/rationale-of-instancecheck-on-protocols

**Comment by JosephSBoyle** [comment]
Hi @chrisjsewell. I've traced the problem to the 'hasattr` call in the `_ProtocolMeta` class referencd in that S.O question you linked.

`hasattr` calls `getattr`, which in your test case succeeds, thus executing the code in `myproperty`, which then errors. It's quite trivial to solve (we just replace the getattr with checking the existence of `attr` in `dir(cls)`).

I can't think of any particular downside to making this change so will open a PR shortly:)

**Comment by chrisjsewell** [comment]
Brilliant thanks

**Comment by AlexWaygood** [comment]
@JosephSBoyle, a better solution would probably be to use [`inspect.getattr_static`](https://docs.python.org/3/library/inspect.html#fetching-attributes-statically), which is specifically designed for solving this kind of problem.

Looking in an object's `dir()` is problematic, because objects can define custom `__dir__` methods:

```pycon
>>> class Foo:
...     def __init__(self):
...         self.x = 5
...     def __dir__(self):
...         return []
...
>>> "x" in dir(Foo())
False
```

A better solution is to look in an object's `__dict__`, but there are complications here as well.

```pycon
>>> class Foo:
...     a = 1
...     def __init__(self):
...         self.b = 2
...
>>> obj = Foo()
>>> "a" in obj.__dict__
False
>>> "b" in obj.__dict__
True
>>> "a" in obj.__class__.__dict__
True
>>> "b" in obj.__class__.__dict__
False
```

(It gets even more complicated if the attribute is defined on the parent class, or if the class defines `__slots__`.)

`inspect.getattr_static` already tackles all of these complications, so it would provide a better solution than reinventing the wheel here :)

Having said that, importing `inspect` in `typing.py` might slow down importing `typing` at runtime, so we should be careful to check that.

**Comment by JosephSBoyle** [comment]
Thanks @AlexWaygood, I wasn't aware of `getattr_static`.

The docs suggest that using this might result in changing some other existing  result in a change in behaviour

**Comment by JosephSBoyle** [comment]
Thanks @AlexWaygood, I wasn't aware of `getattr_static`.

The docs suggest that using this might result in changing some other existing  result in a change in behaviour, for instance "not being able to fetch dynamically created attributes". I'm not sure if this is wrong, or if I'm misunderstanding what is stated.

Change:
```python
# typing.py
        if cls._is_protocol:
            # Check if attr is defined on the instance using `inspect.getattr_static`
            # to avoid triggering possible side-effects in function style properties
            # (i.e those with @property decorators) that would occur if `hasattr`
            # were used.
            import inspect
            
            def hasattr_static(instance, attr):
                try:
                    inspect.getattr_static(instance, attr)
                    return True
                except AttributeError:
                    return False
            
            if all(hasattr_static(instance, attr) and
                    # All *methods* can be blocked by setting them to None.
                    (not callable(getattr(cls, attr, None)) or
                     getattr(instance, attr) is not None)
                    for attr in _get_protocol_attrs(cls)):
                return True
        return super().__instancecheck__(instance)
```
Test for dynamic attribute checking with `getattr_static`:
```python

    def test_dynamically_added_attribute(self):
        """Test a class dynamically becoming adherent to a Protocol."""
        @runtime_checkable
        class P(Protocol):
            @property
            def foo(self):
                pass
                
        class X:
            pass

        x = X()
        self.assertFalse(isinstance(x, P))
        x.foo = "baz"
        self.assertTrue(isinstance(x, P))

        x2 = X()
        x2.foo = property(lambda self: "baz")
        self.assertTrue(isinstance(x2, P))
```
The above test passes, suggesting getattr static _can_ in fact find dynamically added attributes.

**Comment by AlexWaygood** [comment]
> I'm not sure if this is wrong, or if I'm misunderstanding what is stated.

I _think_ you're misunderstanding, but the `inspect` docs could probably be clearer on this point :) I believe the `inspect` docs are talking about situations with fancy descriptors where attributes are dynamically added in `__get__` methods — I'm struggling to think of an example, but the whole point of `getattr_static` is that it doesn't call `__get__` methods, so that is indeed something it would struggle with.

This isn't exactly what the inspect docs are talking about, but here's a situation where using `inspect.getattr_static` instead of `hasattr` would lead to a bad regression that we should try to avoid:

```pycon
>>> from typing import ClassVar, Protocol
>>> class HasBar(Protocol):
...     @property
...     def bar(self) -> int: ...
...     
>>> class Foo:
...     x: ClassVar[bool] = False
...     @property
...     def bar(self) -> int:
...         if self.x:
...             return 42
...         raise AttributeError
...         
>>> import inspect
>>> f = Foo()
>>> inspect.getattr_static(f, "bar")
<property object at 0x11f7b0f48>
>>> hasattr(f, 'bar')
False
>>> if isinstance(f, HasBar):  # False with current implementation, True with getattr_static implementation
...     y = f.bar  # type checkers will assume this is a safe attribute access, but if we used getattr_static, this would be unsafe
...
```

**Comment by AlexWaygood** [comment]
The best solution here may actually be to just add a warning to the docs for `runtime_checkable` stating that calling `isinstance()` against runtime-checkable protocols will result in (possibly expensive) properties being accessed. I don't think there's a way of doing it so that we avoid accessing properties on the object but maintain type-safe behaviour.

**Comment by chrisjsewell** [comment]
😢  personally I would say this kind of makes `Protocol` and `@runtime_checkable` unusable in many practical applications, and I will just switch back to using `ABC` classes

**Comment by AlexWaygood** [comment]
> 😢 personally I would say this kind of makes `Protocol` and `@runtime_checkable` unusable in many practical applications, and I will just switch back to using `ABC` classes

I'm open to suggestions, if anybody can think of a way of improving the implementation here while maintaining type safety! 🙂

**Comment by JosephSBoyle** [comment]
Thanks for the example, @AlexWaygood.

I agree it seems like we're unfortunately unable to support both use cases and so should stick with the one we've supported thus far and provide a warning w.r.t the second use case as you suggest.

I'm sorry to hear this makes Protocol unusable for the cases you had in mind @chrisjsewell, if you have a concrete case in mind feel free to open a S.O issue and link it here, I'd be happy to take a look.

**Comment by chrisjsewell** [comment]
> if you have a concrete case in mind fee

```python
class X:
    def __init__(self):
        self._is_open = False
    def __enter__(self):
        # open some resource
        self._is_open = True
    def __exit__(self, *args):
        # open the resource
        self._is_open = False
    @property
    def x(self):
        if not self._is_open:
            raise RuntimeError("cannot access x unless in a context")
       # fetch x ...
```

**Comment by chrisjsewell** [comment]
It just feels very unexpected that `@property` is essentially incompatible with `@runtime_checkable`, since presumably one is are using `@property` over `self.x = ...` for a good reason

**Comment by AlexWaygood** [comment]
> ```python
> class X:
>     def __init__(self):
>         self._is_open = False
>     def __enter__(self):
>         # open some resource
>         self._is_open = True
>     def __exit__(self, *args):
>         # close the resource
>         self._is_open = False
>     @property
>     def x(self):
>         if not self._is_open:
>             raise RuntimeError("cannot access x unless in a context")
>        # fetch x ...
> ```

It would be much more idiomatic in this case to raise `AttributeError` rather than `RuntimeError` from the `x` property, since you are, after all, trying to fetch an attribute if you're accessing the property. If you change your code to raise AttributeError, then the `isinstance()` check will (correctly) return `False`, and no exception will be raised.

**Comment by chrisjsewell** [comment]
Plus the fact you really have no idea what `instance` could be in `isintance(instance, X)`, so it essentially poses a "security risk" I guess that you are could be running code that you did not expect to run

**Comment by chrisjsewell** [comment]
> It would be much more idiomatic in this case to raise AttributeError ...

Thinking out loud, perhaps you have to have a separate Protocol for an "open" instance vs a "closed" one,
although this is not what e.g. `IO` does: https://github.com/python/cpython/blob/7894bbe94ba319eb650f383cb5196424c77b2cfd/Lib/typing.py#L3164

**Comment by JosephSBoyle** [comment]
I agree that perhaps it's unintuitive that the code in a property would be run but it's not any more of a security risk than if it didn't run the contents of the property method, since by even importing a class in the first place you're allowing it to run with whatever permissions you have set anyways.

To add to Alex's suggestion of raising an `AttributeError` I would suggest maybe using a second object, which is returned by your `__enter__` method. That way x can only be accessed when the resource is available and you remove the erroneous path from your code (thus simplifying it!).

**Comment by chrisjsewell** [comment]
I certainly take the suggestions onboard thanks 🙏 , but still...

I feel the point of using `isinstance` is that you don't know what `instance` is, and now you kind of do need to know. Because, depending on what `instance` is, it's going to effect the behaviour of `isinstance`; how long it takes to run, whether it will except, etc .... It's no longer a "trivial" call
It just feels like `@runtime_checkable`, in its current form, is not worth the hassle, as opposed to not using `Protocol` or using a custom `isinstance` function

**Comment by AlexWaygood** [comment]
> It just feels like `@runtime_checkable`, in its current form, is not worth the hassle, as opposed to not using `Protocol` or using a custom `isinstance` function

I don't necessarily disagree; I personally would be pretty wary about using `@runtime_checkable` in my own code. But that's unfortunately not relevant to the question of "Is it possible to solve this issue without breaking type safety?", and I think the answer (unless you have any suggestions!) remains "No".

**Comment by chrisjsewell** [comment]
Yeh no worries, I certainly don't want to moan about the good work you guys are doing 😅 

I just want to feedback that `@runtime_checkable` is probably not as "benign" as it suggests in the documentation, and msybe goes a little too far in the direction of type safety at the expense of usability (? after all this is not code that's actually being used by static type checkers)

**Comment by AlexWaygood** [comment]
> after all this is not code that's actually being used by static type checkers

As I demonstrated above in https://github.com/python/cpython/issues/102433#issuecomment-1455103900, the runtime implementation here is very relevant to static type checkers. If we change the implementation of `_ProtocolMeta.__instancecheck__` so that it doesn't access and evaluate properties, then the following snippet will raise `AttributeError` at runtime but will not be flagged by static type checkers. Static type checkers will assume that the `isinstance()` guard will ensure that accessing `f.bar` is safe, but if we change the implementation of `_ProtocolMeta.__instancecheck__` so that it doesn't evaluate the `bar` property, this assumption will be entirely erroneous:

```python
from typing import ClassVar, Protocol

class HasBar(Protocol):
    @property
    def bar(self) -> int: ...
    
class Foo:
    x: ClassVar[bool] = False
    @property
    def bar(self) -> int:
        if self.x:
            return 42
        raise AttributeError

f = Foo()
if isinstance(f, HasBar):  # False with the current implementation, but True if we change _ProtocolMeta.__instancecheck__ so that it doesn't evaluate the `bar` property
    y = f.bar
```

**Comment by AlexWaygood** [comment]
> I just want to feedback that `@runtime_checkable` is probably not as "benign" as it suggests in the documentation

Yeah, that's why I suggested adding a note to the docs in https://github.com/python/cpython/issues/102433#issuecomment-1455106070 :)

**Comment by chrisjsewell** [comment]
> so that it doesn't access and evaluate properties, then the following snippet will raise AttributeError at runtime but will not be flagged by static type checkers

It feels a bit "off" suggesting that attributes can "claim" they are not attributes, via `AttributeError` 😬 

For example, from what I can see, this passes `mypy --strict`

```python
from typing import Protocol

class P(Protocol):
    @property
    def x(self) -> None:
        ...

class X(P):
    @property
    def x(self) -> None:
        raise AttributeError("I'm not really an attribute!")
```

should it not?

**Comment by AlexWaygood** [comment]
> For example, from what I can see, this passes `mypy --strict`
> 
> ```python
> from typing import Protocol
> 
> class P(Protocol):
>     @property
>     def x(self) -> None:
>         ...
> 
> class X(P):
>     @property
>     def x(self) -> None:
>         raise AttributeError("I'm not really an attribute!")
> ```
> 
> should it not?

That's not a _great_ example because the `x` properties are annotated as returning `None`, but yeah, mypy's behaviour isn't necessarily ideal with respect to properties. Arguably it _should_ complain about there being no `return` statement in the `X.x` property in the following snippet -- it should aguably either have a `return` statement or be explicitly decorated with `@abstractmethod` to indicate that class `X` is still abstract:

```python
from typing import Protocol

class P(Protocol):
    @property
    def x(self) -> int:
        return 5

class X(P):
    @property
    def x(self) -> int:
        raise AttributeError("I'm not really an attribute!")
```

Anyway, that's more of a discussion to be had on the mypy issue tracker. The _whole point_ of the `runtime_checkable` decorator is so that you can use `isinstance()` checks at runtime to do structural type-narrowing operations that a type checker will also understand. I'm very unwilling to compromise on that.

**Comment by chrisjsewell** [comment]
> The whole point of the runtime_checkable decorator is so that you can use isinstance() checks at runtime to do structural type-narrowing operations that a type checker will also understand. I'm very unwilling to compromise on that.

That's fair, it's a difference of opinion.
Just personally I won't be using this feature, and I wouldn't advise anyone else to

**Comment by hmc-cs-mdrissi** [comment]
> ```python
> from typing import ClassVar, Protocol, runtime_checkable
> 
> @runtime_checkable
> class HasBar(Protocol):
>     @property
>     def bar(self) -> int: ...
>     
> class Foo:
>     x: ClassVar[bool] = False
>     @property
>     def bar(self) -> int:
>         if self.x:
>             return 42
>         raise AttributeError
> 
> f = Foo()
> if isinstance(f, HasBar):  # False with the current implementation, but True if we change _ProtocolMeta.__instancecheck__ so that it doesn't evaluate the `bar` property
>     y = f.bar
> ```

I find this example messy as the behavior for type checkers depends on type checker. pyright disagrees with mypy here and pyright thinks that Foo is compatible with HasBar and behaves like if check is True. pyright even gives an error in strict mode of isinstance(f, HasBar) is always true.

I also don't think even mypy interprets that code as you stated. If I adjust code a little to have,

```python
f: HasBar = Foo()
```

so mypy also believes that Foo matches HasBar protocol. I did a check with other main type checkers and pyright/pyre/pytype all are happy allowing HasBar annotation on that line.

This issue feels like it fits better to discuss in typing repository. I think requiring runtime evaluation though of properties is awkward enough behavior that I'd just avoid any code I work with mixing both runtime checkable and properties. I do sometimes use runtime checkable and it's behaviors make more sense with methods only.

**Comment by AlexWaygood** [comment]
> I also don't think even mypy interprets that code as you stated. If I adjust code a little to have,
> 
> ```python
> f: HasBar = Foo()
> ```
> 
> mypy gives 0 errors so mypy also believes that Foo matches HasBar protocol. I did a check with other main type checkers and pyright/pyre/pytype all are happy allowing HasBar annotation on that line.

I didn't mean to imply that mypy had different behaviour. What I'm concerned about is situations like the following:

```python
def print_attr(obj: object) -> None:
    if isinstance(obj, HasBar):
        print(obj.attr)
```

Type checkers will assume that the `isinstance()` guard makes the `obj.attr` attribute access safe inside the guard. But in this case, it won't be.

Anyway, @JelleZijlstra also expressed reservations in https://github.com/python/cpython/pull/102449#discussion_r1125763043, so this is evidently more controversial than I realised :) I'll start a discussion on python/typing to see what others think.

**Comment by chrisjsewell** [comment]
> Type checkers will assume that the isinstance() guard makes the obj.attr attribute access safe inside the guard. 

Does it though?
what about:

```python
class A:
    @property
    def a(self): ...

class B(A):
    @property
    def a(self):
        raise AttributeError

isinstance(B(), A)
```

that passes, then raises
is there any difference?

For me, trying to account for `AttributeError` inside of `@property` seems very niche, but thats just my viewpoint

**Comment by AlexWaygood** [comment]
I've opened an issue here, attempting to summarise the discussion, and seeking thoughts from the typing community more broadly:

- https://github.com/python/typing/issues/1363

**Comment by AlexWaygood** [comment]
https://github.com/python/cpython/pull/103034 has been merged, meaning that descriptors, properties and `__getattr__` methods will no longer be called during `isinstance()` checks on runtime-checkable protocols in Python 3.12+. The change introduces some minor backwards incompatibilities, however, so can't be backported to 3.11 and 3.10.

It _might_ be possible to backport the change to `typing_extensions`, but that should be discussed in the `typing_extensions` repo, not here :)

Thanks for changing my mind on this one!
