### ISSUE TITLE
Drop support for python3.6 in `Parser` and `test_type_comments`

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#102692]
Since python3.6 no longer supported, we can drop these lines:

https://github.com/python/cpython/blob/a703f743dbf2675948e59c44fa9d7112f7825100/Parser/string_parser.c#L213-L218

https://github.com/python/cpython/blob/a703f743dbf2675948e59c44fa9d7112f7825100/Parser/pegen.c#L633-L637

https://github.com/python/cpython/blob/a703f743dbf2675948e59c44fa9d7112f7825100/Lib/test/test_type_comments.py#L262-L285

Do these lines makes any sense on current moment?

**Comment by sobolevn** [comment]
Current parser supports multiple target versions, including even 3.5: https://github.com/python/cpython/blob/a703f743dbf2675948e59c44fa9d7112f7825100/Grammar/python.gram#L275-L281 
See https://docs.python.org/3/library/ast.html#ast.parse

I don't think that dropping the support of older versions is required here.
So, I am -1 on this proposal. Because it does not solve a problem, but just removes some existing features that are quite easy to maintain.

**Comment by Eclips4** [comment]
Yeah, you're right, this features really easy to main. But, what is main purpose of why parser supports even python3.5?

**Comment by sobolevn** [comment]
Static analysis tools use this feature, for example: mypy supported old versions of python `>= 3.6` until recently. 

I think there might be others.

**Comment by Eclips4** [comment]
Python ecosystem is really important thing. Mypy included into this ecosystem, so we really should care about this features.
But there's another question raised, why mypy supports old versions of python?
However, this question isn't related to CPython, if there no more opinions, i'll close this issue.
Thanks for the answers, Nikita!
