### ISSUE TITLE
Better `splitext` function.

### ISSUE THREAD

**Issue by 0xAndrewBlack** [python/cpython#102672]
# Feature or enhancement

I wanted to help and change the inner workings of the `splitext` function to work with multiple file extensions.
In most cases when working with archives it tend to have `archive.tar.gz` and the extensions are left untouched leading to not as intended consequences.

# Pitch

It helps with files that has multiple extensions. ex.: `archive.tar.gz`

#### First example
input: `alma.tar.gz`
output: `('alma.tar', '.gz')`
expected: `('alma', '.tar.gz')`

#### Second example
input: `szilvasbukta.2.tar.gz.zip`
output: `('szilvasbukta.2.tar.gz', '.zip')`
expected: `('szilvasbukta', '.2.tar.gz.zip')`

#### First example
input: `alma.tar.gz`
output: `('alma', '.tar.gz')`

#### Second example
input: `szilvasbukta.2.tar.gz.zip`
output: `('szilvasbukta', '.2.tar.gz.zip')`

#### First example
input: `alma.tar.gz`
output: `(b'alma', b'.tar.gz')`

#### Second example
input: `szilvasbukta.2.tar.gz.zip`
output: `(b'szilvasbukta', b'.2.tar.gz.zip')`

# Previous discussion

Did not find any related issues to this function but its quite trivial when used with files that has multiple extensions such as archives in most cases.

### Linked PRs
* gh-102673

**Comment by stevendaprano** [comment]
Changing the behaviour will break existing code that expects the current behaviour.

I don't think that this is better. What are you going to do with joined up multiple extensions? Especially since they aren't just limited to .tar.gz. How do you process the joined up extension .txt.zip.backup.blob.crypt?

Quote:

```
expected: ('alma', '.tar.gz')
```

That's not what I expect. I expect `('alma.tar', '.gz')`, because alma.tar.gz is a gzipped file. You can always call `splitext` a second time to get `('alma', '.tar')`.

It might be worth considering a `split_extensions` function that splits into a list of `[root, zero or more extensions]`.

This is why we ask people to discuss new feature elsewhere first. What seems better to you may not seem better to others.

If you are serious about this change, please discuss it on [Discuss](https://discuss.python.org/c/ideas/6) or [Python-ideas](https://mail.python.org/mailman3/lists/python-ideas.python.org/) to get community feedback.

**Comment by kwsp** [comment]
The behaviour you want (aka split the filename from all extensions) can trivially be achieved by calling `str.split(".", 1)`. It's so trivial (given how powerful string methods are in Python) that I don't think we need another standard library function for it. 

Example:

```
"archive.tar.gz".split(".", 1)  # ['archive', 'tar.gz']
"alma.tar.gz".split(".", 1)  # ['alma', 'tar.gz']
"szilvasbukta.2.tar.gz.zip".split(".", 1)  # ['szilvasbukta', '2.tar.gz.zip']
```

**Comment by stevendaprano** [comment]
`str.split` is not the correct solution. Not even for paths with a single file extension.

```
>>> path = "/home/user/something.things/file.txt"
>>> os.path.splitext(path)
('/home/user/something.things/file', '.txt')
>>> path.split('.', 1)
['/home/user/something', 'things/file.txt']
```


And likewise for files with a leading dot, or no dot at all:

```
>>> os.path.splitext('.bashrc')
('.bashrc', '')
>>> '.bashrc'.split('.', 1)
['', 'bashrc']
>>> os.path.splitext('filename')
('filename', '')
>>> 'filename'.split('.', 1)
['filename']
```

**Comment by barneygale** [comment]
Period can appear anywhere in filenames, e.g. here's a random file from my "Downloads" folder: `ubuntu-20.04.5-desktop-amd64.iso`. It's not very useful to split that as `('ubuntu-20', '.04.5-desktop-amd64.iso')`!
