### ISSUE TITLE
tkinter [Windows] [Python 3.10] changing labelframe bg  color causes whole window to be redrawn

### ISSUE THREAD

**Issue by ckelloug4** [python/cpython#102762]
On Windows 10 (x86-64), python 3.10.0 ,changing the bg color of a labelframe when the labelframe has width and height set and has a child label causes all widgets in the window to resize and redraw.  This only happens on windows and not macOS and linux.

```py
from tkinter import *
from tkinter import ttk
lf=[]
win=""
def change_color():
    for i in range(0,14):
        lf[i].config(bg="green")
    win.after(1000,change_color)

def print_hi(name):
    # Use a breakpoint in the code line below to debug your script.
    global win
    win=Tk()
    global lf
    for i in range(0,14):
        lf.append(LabelFrame(win,text=f"frame {i}", width=100,height=100 ))
        Label(lf[i],text="foo").grid()
        lf[i].grid()

    win.after(1000,change_color)
    win.mainloop()

if __name__ == '__main__':
    print_hi('PyCharm')
```

**Comment by terryjreedy** [comment]
Verified with 3.12.0a6.  I agree that is visually obnoxious.  Only reconfigured LableFrames get redrawn (after reducing change_color range).  They are nearly always redrawn wider and shrunk, sometimes also redrawn higher and shrunk (random, perhaps 1/4 the time).  Same if packed instead of gridded.  Same with 'white' background.  (Will continue experiments later.)

I suspect problem is in tk, not _tkinter, but someone with tk wish would have to test.
@serhiy-storchaka Is there any way widget misbehavior as described could be our fault?

**Comment by gvanrossum** [comment]
How sure are you this is a Python (tkinter) issue and not a Tcl/Tk issue? IIUC a lot of Tk behavior is platform-specific/dependent.

**Comment by ckelloug4** [comment]
I've further investigated.  This appears to be a tcl/tk bug, not a tkinter bug.  I probably should have done this before reporting here.  I guess I'll report this as a tcl/tk bug.

```
#/usr/bin/wish

proc update_color {} {
	for {set i 0} {$i<14} {incr i} {
	.mylabelframe$i configure -background green
	}
	after 1000 update_color
}

for {set i 0} { $i<14} {incr i} {
labelframe .mylabelframe$i -text $i  -width 50 -height 50
label .mylabelframe$i.mylabel$i -text $i
grid .mylabelframe$i.mylabel$i
grid .mylabelframe$i
}

after 1000 update_color
```

**Comment by gvanrossum** [comment]
Thanks for looking into it.
