### ISSUE TITLE
dict.get(key, val) function for dictionaries has a wrong evaluation order

### ISSUE THREAD

**Issue by jabatrox** [python/cpython#102884]
# Bug report

The dict.get(key, val) function, according to the docs, "returns the value for key if key is in the dictionary, else default. If default is not given, it defaults to None, so that this method never raises a KeyError".

However, the value of "val" is evaluated before checking if "key" exists in dict, so that it is not really a "default" value, as it needs to exist even before knowing if "key" is in dict (and therefore making it pointless to know the value of "val").

## Example

If I have two dictionaries, dict1 and dict2, and I have the following:
```
for key in (xxxx):
     if dict2 and (key in dict2 or key in dict1):
          dict1.get(key, dict2[key])
```
This gives a KeyError if key is not in dict2, before even checking if it's in dict1 (which would make pointless the check for dict2[key]). Of course, I could do something like this:

```
for key in (xxxx):
     if dict2 and (key in dict2 or key in dict1):
          dict1.get(key, dict2.get(key))
```

as I know, given the if before, that key is either in dict1 or in dict2 necessarily... but I find it a bit "illogical" to check the value of a default value before checking if the value to look for exists.
Maybe I'm wrong and it makes no sense what I'm saying, I don't know, but I went through this today and it was pretty unexpected.

**Comment by carljm** [comment]
This is expected behavior, not a bug. Python evaluation order is consistent: arguments are always evaluated before function calls, there is no lazy evaluation.

For a case like yours, where you don't want to even look up / calculate the "real" default value unless you need it, the typical idiom is to use an "inert" sentinel like `None` as the default in calling `get`, and then check for the sentinel value and replace it with the real default:

```
val = dict1.get(key, None)
if val is None:
    val = dict2[key]
```

If `None` is a valid value in `dict1`, you can make your own custom sentinel instead, e.g. `MISSING = object()` and use that instead of `None` in the above idiom.

**Comment by pochmann** [comment]
You find it "unexpected" that a function call evaluates the arguments before the call? The doc for [calls](https://docs.python.org/3/reference/expressions.html#calls) says:

> All argument expressions are evaluated before the call is attempted.

**Comment by pochmann** [comment]
@carljm `None` *is* the default, no need to write it explicitly. Or is that what makes it an idiom?

**Comment by carljm** [comment]
> @carljm `None` _is_ the default, no need to write it explicitly. Or is that what makes it an idiom?

You're right, it's not needed. I think it makes things a bit more obvious to include it explicitly (and it made the follow-up about custom sentinel clearer in this example), but it doesn't matter.
