### ISSUE TITLE
LoggerAdapter lacks `.addFilter()` and `.removeFilter()` methods

### ISSUE THREAD

**Issue by jonathan-scholbach** [python/cpython#102868]
# Bug report

`logging.LoggerAdapter` doesn't have the `addFilter()` and `removeFilter()` methods, which `logging.Logger` does expose. That way, `LoggerAdapter` is not a fully functional drop in replacement  for `Logger`:

## Minimal Example

```python
>>> from logging import getLogger, LoggerAdapter
>>> logger = getLogger('some_module')
>>> adapter = LoggerAdapter(logger)
>>> adapter.addFilter(lambda _: True)

AttributeError: 'LoggerAdapter' object has no attribute 'addFilter'
```

The filter could be added on the logger itself, of course. But that holds true for all the other methods which `LoggerAdapter()` instances are already delegating to their underlying `Logger` instance.

**Comment by Kundanagrawalofficial** [comment]
The reason you are getting the AttributeError: 'LoggerAdapter' object has no attribute 'addFilter' error is because the LoggerAdapter class in the logging module does not have an addFilter method.

The addFilter method is a method of the Logger class in the logging module, not the LoggerAdapter class. This method allows you to add a filter to the logger to selectively discard log records based on their properties.

If you want to add a filter to your logger, you should modify your code to use the addFilter method of the Logger object, like this:

**Comment by jonathan-scholbach** [comment]
I am aware that `LoggerAdapter` does not have the attribute. I just think, it _should_ have it. `LoggerAdapter` should be a drop-in for `Logger`. It is delegating most of its attributes and methods to the underlying logger instance. I think, `addFilter` should be amongst those. While I know how to work around it, I find the current behavior unexpected.

**Comment by vsajip** [comment]
Well, `LoggerAdapter` overrides those methods where you might want to pass in specific contextual information. It's _not_ intended to be a drop-in for `Logger` in all respects - it's there to facilitate passing contextual information to logging calls.
