### ISSUE TITLE
Enum._generate_next_value_ should be static

### ISSUE THREAD

**Issue by RomanSteinberg** [python/cpython#103056]
# Bug report

[Here](https://github.com/python/cpython/blob/2cdc5189a6bc3157fddd814662bde99ecfd77529/Lib/enum.py#L1149) and in two more places in the same file function `_generate_next_value_` supposed to be called for instance. But it will not work properly in that case, because it behaves like static method. Consider `staticmethod` decorator.

As far as I understand there is no problem right now and all calls are correct. But in future it will be more robust if it would be static.

### Linked PRs
* gh-103062
* gh-103231

**Comment by ethanfurman** [comment]
`_generate_next_value_` is not a static method, and should never be called on an instance.  It is a plain function, called by the enum type machinery during value creation.  If a user does use the `staticmethod` decorator, it will be stripped and the decorated function used instead during value creation.

Hmm, I see that the final function stored on the completed class is either a plain function or a static method depending on how it was written in the class -- it should probably always be one or the other; I think `staticmethod` since that's what I thought it was doing.  ;-)

The check and possible staticmethod conversion should be at [line 531](https://github.com/python/cpython/blob/2cdc5189a6bc3157fddd814662bde99ecfd77529/Lib/enum.py#L531).

**Comment by ethanfurman** [comment]
Okay, so it will be a `staticmethod`, but specifying that when writing a class is optional.

**Comment by RomanSteinberg** [comment]
@ethanfurman could you, please, explain the following phrase:  
>  If a user does use the staticmethod decorator, it will be stripped and the decorated function used instead during value creation.

**Comment by ethanfurman** [comment]
If the function was decorated with `staticmethod`, [this line](https://github.com/python/cpython/blob/2cdc5189a6bc3157fddd814662bde99ecfd77529/Lib/enum.py#L396): `_gnv = value.__func__ if isinstance(value, staticmethod) else value` retrieves the function.  When `auto()` is used, the actual enum doesn't yet exist and the members don't yet exist, so a static method doesn't work -- we need the plain function in order to generate the values.

The change implented by this patch is to wrap the `_generate_next_value_` with `staticmethod` (if not already done) before storing it in the final enum class.

**Comment by RomanSteinberg** [comment]
@ethanfurman thank you!
As far as I understand, the main reason not to make `_generate_next_value_` static is not related to the code I linked, but to the code you linked, i.e. method around [this line](https://github.com/python/cpython/blob/2cdc5189a6bc3157fddd814662bde99ecfd77529/Lib/enum.py#L396).

Ok, If I understood you correctly then I have one more question. Why not to decorate the definition of the `_generate_next_value_` function with `@staticmethod`? The line you linked removes decorator for machinery purposes and it will still work fine, but the code becomes more clear for future developers and IDE will not complain.

**Comment by ethanfurman** [comment]
@RomanSteinberg You make a good point.  I have added the `staticmethod` decorator to the code and the docs.

Thank you for your input!
