### ISSUE TITLE
OrderedDict.sort

### ISSUE THREAD

**Issue by Gouvernathor** [python/cpython#103202]
# Feature or enhancement

Add an OrderedDict.sort method

# Pitch

Enables to sort an (ordered)dict in-place, offering both better performance and single-object security when accessing the values in the sorted order - though the sorting is done key-wise.

# Previous discussion

https://discuss.python.org/t/sorting-ordered-dicts/25336

### Linked PRs
* gh-103203

**Comment by rhettinger** [comment]
-1 for this change.   

This is a permanent API change just to optimize the idiom `OrderedDict(sorted(od.items()))`.  AFAICT people rarely use that idiom and when they do it is never speed critical; otherwise, they would be using a regular dict which already has much better performance than `collections.OrderedDict`.

Also, `collections.OrderedDict` is close to being a dead part of the collections module.  Mostly It is only useful for being backwards compatible to versions before Python 3.6 and for creating LRU cache variants.

Lastly, it isn't desirable to have API to diverge further from the regular dict.

**Comment by sunmy2019** [comment]
Python 3.7+ dicts uses a new implementation. From then on, `dicts` are guaranteed to be ordered.

If you want to be performant, try to replace all your `OrderedDict` with `dict`.

Then `dic(sorted(dic.items(), key=...))` will be much faster than acting on `OrderedDict`, because "creating a dict from a list" is implemented in C.

----

Besides that, as you can see this part of the code:

https://github.com/python/cpython/blob/33c8adf2be68e42c262920b9a3a31c083e5a189f/Lib/collections/__init__.py#L354-L358

It will try import native implementation after define python version `OrderedDict`.

Your change won't apply for most cases (you can add a test case). You need to modify `Objects/odictobject.c` as well.

**Comment by Gouvernathor** [comment]
I answered the point of this in the discourse thread, I suggest going there to avoid repeating the same points over too many different places.

@erlend-aasland
> I'm puzzled why an issue and a PR was opened, given the very lukewarm response.

There are often backlashes against ideas of changes complaining that there is no implementation for them. I had a viable implementation, so to show the diff I opened a PR. The PR rules ask that an issue be opened about them except for very minor changes, which this is not since it adds a feature and a new method.
So, this issue is the result of the rules.

I also added this to trigger the tests, forgetting that I had not modified any code outside of the new method so no test would effectively check it. But still.

@sunmy2019 
> If you want to be performant, try to replace all your OrderedDict with dict.

Great, but I doubt dict.__map and dict.move_to_end will work quite well.

> It will try to import native implementation after it define python version OrderedDict.

I know that, I said so in the Discourse thread, to time things, you have to comment-out that part so that the pure-python version is used.

**Comment by rhettinger** [comment]
Thanks for the suggestion, but I am going to decline for the reasons mentioned above.
