### ISSUE TITLE
Redundant `if` statement in `EnumType._find_data_type_()` in `enum.py`

### ISSUE THREAD

**Issue by sadra-barikbin** [python/cpython#103215]
This statement is redundant:
https://github.com/python/cpython/blob/823622212eb258fcec467db56f6e726d841297b3/Lib/enum.py#L996-L997

in 

https://github.com/python/cpython/blob/823622212eb258fcec467db56f6e726d841297b3/Lib/enum.py#L990-L997

### Linked PRs
* gh-103222

**Comment by sobolevn** [comment]
Yes, looks like it is! Line https://github.com/python/cpython/blob/823622212eb258fcec467db56f6e726d841297b3/Lib/enum.py#L996 cannot be reached, because it is covered by https://github.com/python/cpython/blob/823622212eb258fcec467db56f6e726d841297b3/Lib/enum.py#L991

Would you like to submit a PR? :)
