### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by ankit31365** [python/cpython#103330]
```pytb
Traceback (most recent call last):
  File "dbsetup\bin\runFlyway.py", line
    sys.exit(Util.runDbCommand(cmdList, dbContext.schemaPasswd, debug))
  File "dbsetup\lib\Util.py", line 65,
    return subprocess.call(cmdList)
  File "C:\python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
++ exit_report FAILED
++ echo 'specdbMigrate.sh - FAILED'
specdbMigrate.sh - FAILED
++ echo
```

using python 3.10
Windows 11 
executing python file through shell script 
using git bash to execute to shell script
perl verison is 5.32
flyway 9.16

**Comment by ericvsmith** [comment]
You have not provided enough information. It looks like the code is trying to run some executable which is not installed, but with what you’ve shown it’s not possible to say what it is. In any event, this isn’t a bug in Python. I suggest you ask this question on StackOverflow, as suggested on https://flywaydb.org/community

**Comment by ankit31365** [comment]
> You have not provided enough information. It looks like the code is trying to run some executable which is not installed, but with what you’ve shown it’s not possible to say what it is. In any event, this isn’t a bug in Python. I suggest you ask this question on StackOverflow, as suggested on https://flywaydb.org/community

flyway is installed . this is python error. somehow same setup is working in linux but i am trying to install in windows and this error comes ,

**Comment by eryksun** [comment]
> flyway is installed . this is python error. somehow same setup is working in linux but i am trying to install in windows and this error comes ,


I don't know what program your script is trying to run because you haven't provided a minimal example. All I can tell you is that if `subprocess.Popen` is instantiated without an explicit `executable`, then WinAPI `CreateProcessW()` uses the first command-line argument as the executable to run. It searches for it in the application directory (e.g. where "python.exe" is located); possibly the current working directory (if the environment variable `NoDefaultCurrentDirectoryInExePath` isn't defined); the system directories (e.g. "C:\\Windows\\System32", "C:\\Windows\\System", "C:\\Windows"); and the directories in the `PATH` environment variable. You'll need to find whatever it's trying to run, if it's even installed, and add the containing directory to the `PATH` environment variable.
