### ISSUE TITLE
Triple quoted literal definition and  7 in row

### ISSUE THREAD

**Issue by VasylKolomiiets** [python/cpython#103594]
# Documentation
[Here ](https://docs.python.org/3/reference/lexical_analysis.html#strings)
we can read that 

- longstringchar  ::=  <any source character except "\">................................... (for example  ")
- longstringitem  ::=  [longstringchar]........................................................................(again " is valid)
-    longstring      ::=  "'''" longstringitem* "'''" | '"""' longstringitem* '"""' ..("""""""  is valid)

But   """"""" gives syntax error      
So we need rewrite interpretator or point something in documentation, isn`t it?

**Comment by VasilijKolomiets** [comment]
[Here](https://stackoverflow.com/questions/76036574/why-does-the-literal-string-seven-quotes-give-an-error) was discussion. But it seams nobody understand what I say....
https://stackoverflow.com/questions/76036574/why-does-the-literal-string-seven-quotes-give-an-error

**Comment by terryjreedy** [comment]
As should be expected, 7 quotes are interpreted as triple quote, triple quote, unmatch single quote, and the last is an error.
```
>>> '''''''
  File "<stdin>", line 1
    '''''''
          ^
SyntaxError: unterminated string literal (detected at line 1)
```
The quoted lexical analysis section says:
`shortstringchar ::=  <any source character except "\" or newline or the quote>`
`longstringchar  ::=  <any source character except "\">`
As I also said on the SO answer, the grammar in the docs is only partly 'formal'. These 2 productions are partly informal. The doc grammar is not and can not be the grammar used to define the parser. It is a human readable version that must be read along with the text explanation that follows.  This explanation starts with `One syntactic restriction not indicated by these productions... .`  Another is given by `In triple-quoted literals, unescaped newlines and quotes are allowed (and are retained), except that three unescaped quotes in a row terminate the literal.`  The informal “a quote” in the productions and in the sentence just quoted is then explained as `the character used to open the literal, i.e. either ' or ".`

The `longstringchar` definition could be extended with ` or quote part of a triple quote`.  But I am not sure that this really adds anything to the sentence given later and might possibly be a bit confusing.

I am inclined to close this as 'not planned', but will wait for opinions others than ours.

**Comment by VasilijKolomiets** [comment]
First of all - sorry for my English... )

Ok. May be I am a bit tooo formal. But indeed the docummrntation has no real definition the term  ` triple-quoted literal`.  First when it appears they say 'see below' but below again is no any formal-like definition. So it is wroten like I have to know what is ` triple-quoted literal` is BEFORE reading this text.       

So I propose reformat the docs for adding explanation of this term a bit early and the text   `In triple-quoted literals, unescaped newlines and quotes are allowed (and are retained), except that three unescaped quotes in a row terminate the literal. `   have to be transformed. BC  iread the `triple-quoted literals` as "literal inside triple quote frame"  or   " set of symbols between opening triple quoter and closing triple quoter".  So in fact 7 in row is not like  having  `" three unescaped quotes in a row terminate the literal"`. Because literal is the thing that was `triple quaoted` i.e. at least  9 total symbols `"` in a row are causing this situation.

Account this if it  is possible.

**Comment by VasilijKolomiets** [comment]
> The doc grammar is not and can not be the grammar used to define the parser.

What is th problem to place here the real gramma wich define the parser?
Or may be it is not exist?   ;-)
How to understand that parser works properly if I can not see formal gramma?

**Comment by terryjreedy** [comment]
The doc grammar is for people to read and can have informalities.  The formal grammar is for a program to read.  One benefit of  separating the two was that we cound switch from a formal context-free grammar to a formal program expression grammar (PEG) in 3.10 without changing the docs.  You are free to read the [PEG](https://github.com/python/cpython/blob/main/Grammar/python.gram).  Literal identification is part of the tokenizer in the [Parser directory](https://github.com/python/cpython/tree/main/Parser).  As far as I could tell, this is done with hand-crafted C rather than generated from a grammar.

**Comment by VasilijKolomiets** [comment]
Thanks a lot. 
I am satisfied.  May be if PEG links was near the Bacus-Nour description I do not ask anything. 
But the last try to be free from traditional view.

Why   `""""` accounts as "" + ""  but not as wrong variant """ + "  ?        
So i am for homogenous logic in parcing ))

Thanks for being human for such strange people like me.
