### ISSUE TITLE
tempfile.TemporaryDirectory() returns a directory that does not exist

### ISSUE THREAD

**Issue by andrewschalk** [python/cpython#103619]
# Bug report

When I run tempfile.TemporaryDirectory(), the returned string is a directory that does not exist. For my system, it returns "<TemporaryDirectory 'C:\\Users\\ANDREW\~1\\AppData\\Local\\Temp\\tmp6lyqjcuq'>" When I would expect "Andrew Schalk"(my user name) instead of "ANDREW~1". I assume this has something to do with the space in the user name, as on my computer where the user is "Andrew", it returns "Andrew" for this folder(and works fine). Apologies if I'm missing something here, I looked through the docs and source code and found nothing that obviously indicated the reason behind this behavior.

### Minimum reproducible example
```
import tempfile
print(tempfile.TemporaryDirectory())
```

### This is causing FileNotFoundError: [WinError 2] The system cannot find the file specified
I encounter this error using the [PDFLaTeX module](https://pypi.org/project/pdflatex/) when calling the following create_pdf() method. The error occurs on `with open(os.path.join(td, 'file.pdf'), 'rb') as f:`
```
def create_pdf(self, keep_pdf_file: bool = False, keep_log_file: bool = False, env: dict = None):
        if self.interaction_mode is not None:
            self.add_args({'-interaction-mode': self.interaction_mode})
        
        dir = self.params.get('-output-directory')
        filename = self.params.get('-jobname')
        
        if filename is None:
            filename = self.job_name
        if dir is None:
            dir = ""
        
        with tempfile.TemporaryDirectory() as td:
            self.set_output_directory(td)
            self.set_jobname('file')

            args = self.get_run_args()
            fp = subprocess.run(args, input=self.latex, env=env, timeout=15, stdout=PIPE, stderr=PIPE)
            with open(os.path.join(td, 'file.pdf'), 'rb') as f:
                self.pdf = f.read()
            with open(os.path.join(td, 'file.log'), 'rb') as f:
                self.log = f.read()
            if keep_log_file:
                shutil.move(os.path.join(td, 'file.log'), os.path.join(dir, filename + '.log'))
            if keep_pdf_file:
                shutil.move(os.path.join(td, 'file.pdf'), os.path.join(dir, filename + '.pdf'))
        
        return self.pdf, self.log, fp

```
# Your environment

- Windows 11 x64
- VS code 1.77.3
- Python 3.11.3

**Comment by gaogaotiantian** [comment]
The path with the tilde(`~`) is the short path, which should work on Windows. You can try to open `C:\Users\ANDREW~1` in your file explorer and see if it works. You can also do a `os.listdir()` on the tilde paths. So my guess would be the problem was something different.

**Comment by gaogaotiantian** [comment]
I noticed that the line your error occured was to read data. Did you confirm that the file was written? Was is supposed to be created by the subprocess? I can't tell what's your subprocess doing from your code. But if you can do `os.listdir(td)` before the erroreous line, then it's not a Python bug :)

**Comment by eryksun** [comment]
When Windows assigns the `TEMP` environment variable, it calls [`GetShortPathNameW()`](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getshortpathnamew) on the path. By default, NTFS generates a short name for every file and directory name that contains non-ASCII characters, spaces, or is longer than a legacy DOS 8.3 filename (e.g. "filename.ext")[^1]. You can verify that `os.path.isdir(r'C:\Users\ANDREW~1\AppData\Local\Temp')` returns true.

Note that the exception is for "WinError 2". That's `ERROR_FILE_NOT_FOUND` (2). If the temporary directory `td` didn't exist, it would be "WinError 3", i.e. `ERROR_PATH_NOT_FOUND` (3). So the problem lies elsewhere. My guess would be that whatever you're running via `subprocess.run()` creates the file in its current working directory. By default a process inherits the current working directory of its parent. You can override this by passing the `cwd=td` to `subprocess.run()`.


[^1]: This legacy feature of NTFS can be disabled via "fsutil.exe", and existing short names can be purged. Doing so can speed up disk access a bit. Also, disabling and purging short names avoids surprises when calling `FindFirstFileW()` with wildcard characters, which can sometimes unexpectedly match a short name even if the wildcard pattern does not match the normal name.

**Comment by andrewschalk** [comment]
Thanks for the quick and helpful responses. I searched earlier to find if this was a legal way to short a path but didn't find anything, must've missed it. Sorry for the issue, I'll close it with this.
