### ISSUE TITLE
File not found, then key error accured

### ISSUE THREAD

**Issue by Crafterluck** [python/cpython#103654]
When I want to read a specific config file, if this file does not exist it only returns a KeyError not an OS error.
Because of this error it is not hard to troubleshoot errors of this library.

https://github.com/python/cpython/blob/2b5dbd1f237a013defdaf0799e0a1a3cbd0b13cc/Lib/configparser.py#L714

Have this a specific reason why there is a continue used?

**Comment by zware** [comment]
See just above the line you quoted for the reasoning:

https://github.com/python/cpython/blob/2b5dbd1f237a013defdaf0799e0a1a3cbd0b13cc/Lib/configparser.py#L697-L702

`read()` returns the list of files it was able to open so that you can check whether any files were read, or you can open the file yourself and use `read_file()` instead of `read()`.

**Comment by Crafterluck** [comment]
Okay, thank you, i misunderstand this method.
