### ISSUE TITLE
Documentation: dark theme & images

### ISSUE THREAD

**Issue by denballakh** [python/cpython#103960]
# Documentation

Starting from version 3.12, the Docs now have a dark theme. However, this feature does not affect the images. As an example, please visit https://docs.python.org/3.12/library/pathlib.html.
The page contains an image of an inheritance tree. In the dark theme, the rectangles remain white, which is not visually appealing: ![image](https://user-images.githubusercontent.com/47365157/235004488-9d2b0c45-adae-4ca1-9ccb-03383a97019c.png)

To address this issue, I propose making these images compatible with the dark theme: 
![example of image with dark theme](https://user-images.githubusercontent.com/47365157/235004449-a907305d-248b-4380-ac23-e29632882238.png)

Although I'm not an expert in HTML/CSS, a quick search suggests that adding `style="filter:invert(1)"` to `<img>` element can help achieve this.

### Linked PRs
* gh-103983
* gh-104358

**Comment by denballakh** [comment]
I think this issue is also relevant to https://github.com/python/python-docs-theme

Also `filter: hue-rotate(180deg) invert(1)` instead of `filter: invert(1)` works a bit better.
Without hue rotation:
![image](https://user-images.githubusercontent.com/47365157/235034055-957a7c4b-e79c-466f-82fd-067d9d5de7f1.png)
With hue rotation:
![image](https://user-images.githubusercontent.com/47365157/235034031-7c3a7c42-1906-4ef6-99a4-4b973ca42362.png)

**Comment by hugovk** [comment]
Thanks for the report.

Images/pages to review:

# howto/logging.rst - logging_flow.png

https://docs.python.org/3.12/howto/logging.html#logging-flow
Image has white background and no transparency, but `filter:invert(1)` would help

<img width="828" alt="image" src="https://user-images.githubusercontent.com/1324225/235049422-4a28ad43-5ae8-4ea6-9cb8-5a3dc6c77b98.png">

<img width="821" alt="image" src="https://user-images.githubusercontent.com/1324225/235049485-c474f372-d32a-4427-b4b8-a57a2fb6e1ad.png">

# using/windows.rst - win_installer.png
https://docs.python.org/3.12/using/windows.html#installation-steps
The installer image [above](https://github.com/python/cpython/issues/103960#issuecomment-1526862117). We might need to leave this one because it's a screenshot and might not want to modify the logo colours:

<img width="711" alt="image" src="https://user-images.githubusercontent.com/1324225/235049537-254ebd75-ee9a-4291-a1b9-8d6fd7fa5bbb.png">

Or, the actual installer dialog now also supports dark mode, perhaps we could create new screenshots and show the relevant one?

# library/pathlib.rst - pathlib-inheritance.png
https://docs.python.org/3.12/library/pathlib.html
The inheritance tree [above](https://github.com/python/cpython/issues/103960#issue-1687638867). Needs fixing, e.g. `filter:invert(1)`

# library/tkinter.messagebox.rst - tk_msg.png
https://docs.python.org/3.12/library/tkinter.messagebox.html
Image has white background and no transparency:

<img width="826" alt="image" src="https://user-images.githubusercontent.com/1324225/235049756-32855692-5b62-486f-822b-6de4b46f131c.png">

`filter:invert(1)` might work, but it's a screenshot so maybe we don't want to show a dark mode version if it doesn't have one in reality (I've not checked).

<img width="829" alt="image" src="https://user-images.githubusercontent.com/1324225/235049836-ad02eb7d-c796-4871-86a2-377480c814a6.png">

# library/hashlib.rst - hashlib-blake2-tree.png
https://docs.python.org/3.12/library/hashlib.html#creating-hash-objects
White background, no transparency, can be inverted:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/1324225/235050010-f2f10edd-c4fe-4196-ae9f-4554b1a491f0.png">

<img width="761" alt="image" src="https://user-images.githubusercontent.com/1324225/235050056-b67b34c0-a80a-4693-b952-edd9af5ff269.png">

**Comment by hugovk** [comment]
See also https://github.com/python/peps/pull/2409 and https://github.com/python/peps/pull/2949 for how we dealt with some images for dark mode on the PEPs site.

**Comment by hugovk** [comment]
Please see PR https://github.com/python/python-docs-theme/pull/128 to add the class to the theme.

**Comment by hugovk** [comment]
And please see PR https://github.com/python/cpython/pull/103983 to add the class to the three diagrams.

I didn't invert the installer or tkinter.messagebox screenshots shown in https://github.com/python/cpython/issues/103960#issuecomment-1526948099 because they're screenshots of real dialogs and inverting would be misleading and potentially confusing. It's okay to have some lighter screenshots in dark mode.

**Comment by barneygale** [comment]
Inverting the hashlib image makes the shaded areas almost invisible!

**Comment by hugovk** [comment]
In contrast (no pun intended) to the above, here's how PR https://github.com/python/cpython/pull/103983 renders it with inverted brightness, but not inverted contrast:

![image](https://user-images.githubusercontent.com/1324225/235325015-9ce61ef5-b96d-4567-b52c-16bd5609fd6e.png)

It's not so visible in the original:

<img width="772" alt="image" src="https://user-images.githubusercontent.com/1324225/235325101-110d5fa7-24e6-4359-9eb3-1d24b86e5f21.png">

What does the shading actually signify here?

**Comment by hauntsaninja** [comment]
Thanks for fixing!
