### ISSUE TITLE
Defaultdict default value bindings issue

### ISSUE THREAD

**Issue by daryakoval** [python/cpython#103989]
# Bug report

Hi, 
I am trying to create a default dictionary, using the following code:
```
from collections import defaultdict

d = dict()
for i in range(1, 4):
    d[i] = defaultdict(lambda: i)

print(d[1][1])      # getting here 3 instead 1
```

I expect that `d` will be the following dict: 
```
d = { 1: defaultdict(lambda: 1),
         2: defaultdict(lambda: 2),
         3: defaultdict(lambda: 3),
}
```
But unfortunately, all default dict default values are now `3`. 
I think it is related to the lazy evaluation of `lambda: i` and the bindings between `i` and its value. 

# Your environment

Python 3.10.11 (main, Apr 23 2023, 23:41:14) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Mac Ventura 13.3.1 Intel

Python 3.11.3 (main, Apr 29 2023, 15:46:44) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Mac M1

**Comment by sobolevn** [comment]
Hi @daryakoval! 

This is a common pitfall, called "late binding" :)
See https://docs.python-guide.org/writing/gotchas/#late-binding-closures

Solution:

```python
>>> from collections import defaultdict
>>> 
>>> d = dict()
>>> for i in range(1, 4):
...     d[i] = defaultdict(lambda i=i: i)
... 
>>> d[1][1]
1
```

I am going to close this issue, because it works as expected (but it is confusing indeed!)

If you have aany other questions, you can always ask them on Discuss: https://discuss.python.org/c/users/7

👍
