### ISSUE TITLE
PyType_FromSpec refuses to create classes with tp_new

### ISSUE THREAD

**Issue by encukou** [python/cpython#103968]
As reported in #60074, since `PyType_FromMetaclass` was added, other functions from the `PyType_FromSpec` family refuse to create classes whose metaclass has a non-default `tp_new`. IMO this is the correct default behaviour -- we don't have the arguments to call `tp_new` with, and skipping it may be dangerous.
Nevertheless, it's a backwards-incompatible change. It should only be made after a deprecation period.

I'm working on a fix.

### Linked PRs
* gh-103972
* gh-105386
* gh-105697
* gh-105698
* gh-106619

**Comment by encukou** [comment]
Deprecation period started.

**Comment by gpshead** [comment]
The 3.12 docs now say "The tp_new of the metaclass is ignored. which may result in incomplete initialization." statements, but it isn't clear if this is a part of the versionchanged in 3.12 behavior, or if this was always the case.

Basically, we need **explicit instructions** on what code finding itself in the situation that protobuf https://github.com/protocolbuffers/protobuf/issues/12186 finds itself in is supposed to do to reconcile the situation.  

3.12's "What's New" does not directly address this today. It just talks about tp_new being ignored as if that is a behavior change rather than if it was always ignored without being documented as such or what should be done to get the previous behavior.

**Comment by gpshead** [comment]
Late discussion on #60074 which created the TypeError that this issue properly made into a DeprecationWarning has suggestions for a workaround but they definitely qualify as hacks. Deeper understanding of why that tp_new was set and what it's goal was and when it was ever called or not in the past is likely required.

**Comment by gpshead** [comment]
(marking deferred-blocker as we should at least address the documentation on this during the 3.12 beta phase before release)

**Comment by encukou** [comment]
It would be safe, and useful in some cases, to allow ``tp_new=NULL`` (i.e. the metaclass can't be instantiated from Python). I'll try to get that in before the What's New PR.

For What's New, here's the text I have now:

---

  Since ``tp_new`` overrides almost everything ``PyType_From*`` functions do,
  the two are incompatible with each other.
  The existing behavior -- ignoring the metaclass for several steps
  of type creation -- is unsafe in general, since (meta)classes assume that
  ``tp_new`` was called.
  There is no simple general workaround. One of the following may work for you:

  - If you control the metaclass, avoid using ``tp_new`` in it:

    - If initialization can be skipped, it can be done in
      :c:member:`~PyTypeObject.tp_init` instead.
    - If the metaclass doesn't need to be instantiated from Python,
      set its ``tp_new`` to ``NULL`` using
      the :const:`Py_TPFLAGS_DISALLOW_INSTANTIATION` flag.
      This makes it acceptable for ``PyType_From*`` functions.

  - Avoid ``PyType_From*`` functions: if you don't need C-specific features
    (slots or setting the instance size), create types by :ref:`calling <call>`
    the metaclass.

  - If you *know* the ``tp_new`` can be skipped safely, filter the deprecation
    warning out using :func:`warnings.catch_warnings` from Python.

**Comment by haberman** [comment]
> protobuf uses PyType_FromSpecWithBases to create [ScalarMapContainer](https://github.com/protocolbuffers/protobuf/blob/242771ad159927cf731f30c1379aaef1913d7b1e/python/google/protobuf/pyext/map_container.cc#L919) and [MessageMapContainer](https://github.com/protocolbuffers/protobuf/blob/242771ad159927cf731f30c1379aaef1913d7b1e/python/google/protobuf/pyext/map_container.cc#L926), which derive from collections.abc.MutableMapping, so their metaclass is abc.ABCMeta.

Protobuf is using MutableMapping as a mixin. The goal is that we can define only a core set of methods (`__getitem__`, `__setitem__`, etc.) and get correct implementations of all other `MutableMapping` methods "for free" (`__contains__`, `keys`, etc.).

> abc.ABCMeta [defines __new__](https://github.com/python/cpython/issues/103968), meaning it overrides how ABC types should be constructed.
This __new__ is not called on protobuf's container types, which is, IMO, a bug.

It looks like the primary purpose of `abc.ABCMeta` is to add a `register()` method to the class, so that you can call `MutableMapping.register(Foo)`, which will cause `isinstance(Foo(), MutableMapping)` to return true.

We do not want that functionality in this case. We do not want people to be able to call `ScalarMapContainer.register(Foo)`, because `ScalarMapContainer` is a concrete class, not an abstract class.

I suspect that anyone who uses `MutableMapping` as a mixin is in the same boat as us. I would consider it a bug if a class becomes an ABC merely because it mixed in an ABC.

But this seems to be what happens if you mix in an ABC in pure Python:

```python
from collections.abc import MutableMapping

class MyMapping(MutableMapping):
    pass

class OtherMapping:
    pass

# This works -- MyMapping has become an ABC!
MyMapping.register(OtherMapping)
assert isinstance(OtherMapping(), MyMapping)
```

The simplest fix would be to stop inheriting from `MutableMapping`.  Maybe we could "manually" mix in the other methods without using inheritance:

```python
from collections.abc import MutableMapping

class ScalarMapContainer:
    # ...

MutableMapping.register(ScalarMapContainer)

# Mixin the methods manually.
ScalarMapContainer.__contains__ = MutableMapping.__contains__
ScalarMapContainer.keys = MutableMapping.keys
ScalarMapContainer.items = MutableMapping.items
ScalarMapContainer.values = MutableMapping.values
# ...
```

**Comment by encukou** [comment]
No, short of reverting the warning.

**Comment by cdce8p** [comment]
Just saw the warning while testing `3.12.0b4`. Is `stack_level=1` correct for the `DeprecationWarning`
This is my test output
```
<frozen importlib._bootstrap>:400
<frozen importlib._bootstrap>:400
  <frozen importlib._bootstrap>:400: DeprecationWarning: Using PyType_Spec with metaclasses that have custom tp_new is deprecated and will no longer be allowed in Python 3.14.
```

After reading the discussion here, it could probably be Protobuf but no way to tell for the warning alone.

_Happy to open a new issue if this isn't the right place._

**Comment by osandov** [comment]
Leaving a note here for others that may run into this issue with `collections.abc`. Another workaround is to define your desired extension class as a mixin type and then create the final type by inheriting from both your mixin type and the abstract base class. CPython's own `decimal` module does this: https://github.com/python/cpython/blob/3c9996909402fadc98e6ca2a64e75a71a7427352/Modules/_decimal/_decimal.c#L6008-L6013.

**Comment by haberman** [comment]
I can report that for Protobuf we ended up doing what I proposed above in https://github.com/python/cpython/issues/103968#issuecomment-1589928055, which is to mix in the ABC without using inheritance. We explicitly register our class as a virtual subclass: https://github.com/protocolbuffers/protobuf/pull/15999
