### ISSUE TITLE
python on Windows closes additional file descriptors on launch

### ISSUE THREAD

**Issue by dnschneid** [python/cpython#104099]
# Bug report
If you launch python with additional fds open (e.g., 3 and 4 for a pipe), python on Windows seems to close the pipes on launch, but on Linux you can use them just fine.  I ran into this when debugging a python integration with a third-party tool; the integration worked on Linux but not on Windows, but after digging I could not find any way to launch python with the additional fds preserved on Windows.

test.py:
```python
import os
os.write(3, b'ok\n')
```

Run:
```bash
python3 test.py 3>&1
```

On linux, if you run the command above, you'll get "ok" written out on stdout.  On Windows, it'll be as if you didn't do the redirection, and you'll get
```OSError: [Errno 9] Bad file descriptor```

As a sanity-check, I did try launching other processes that can use the additional file descriptors, such as

test_notpy.sh:
```bash
echo ok >&3
```

Run:
```
bash test_notpy.sh 3>&1
```
and file descriptor passing does seem like it should work on Windows.

The third-party integration is also advertised to work just fine on Windows, so that's another data point that it's not my test cases doing lots of cartwheels behind the scenes to make it look like it's working.  So I'm probably not crazy, although I wouldn't be surprised if I'm missing something since this seems like it should be pretty basic behavior...

# Your environment
Tested on Windows 10, x86_64, with the 3.11 python in the windows store as well as with the Python 3.10.11 on the python.org download page.

**Comment by eryksun** [comment]
Natively, Windows uses handles that reference objects in the kernel, such as a handle for a file, job, process, thread, section (file mapping), event, semaphore, mutex, etc. For programs that use C standard I/O and low-level 'Unix' I/O (e.g. `open`, `close`, `read`, `write`), the Windows C runtime library also implements Unix-like file descriptors, which index records that include the actual kernel file handle and the type and state of the open file.

The kernel is not aware of C runtime file descriptors in any way. However, there's basic support to smuggle file descriptors into a child process using the `cbReserved2` and `lpReserved2` fields of the process `STARTUPINFO` record. When a child process is spawned via C `_[w]spawn*()`, the C runtime packs the records for all inheritable file descriptors in a buffer that's referenced by `lpReserved2`, with the buffer size set in `cbReserved2`. If the spawned process links with the Windows C runtime, at startup the CRT calls `GetStartupInfo()` and initializes its set of file descriptors using these two `STARTUPINFO` fields.

Internally, the `STARTUPINFO` record corresponds to the PEB `ProcessParameters`, and the C runtime data is the `RuntimeData` field. Let's use a debugger to look at what MSYS2 bash actually passes as the runtime data when we spawn the Windows build of Python via `python 3>&1`:

```text
2:008> ?? @$peb->ProcessParameters->RuntimeData
struct _UNICODE_STRING
 ""
   +0x000 Length           : 0xa8
   +0x002 MaximumLength    : 0xa8
   +0x008 Buffer           : 0x00000263`50be7c6a  ""
2:008> db @@(@$peb->ProcessParameters->RuntimeData.Buffer)
00000263`50be7c6a  00 00 00 00 a8 00 00 00-64 fa 00 af fc 94 92 ac  ........d.......
00000263`50be7c7a  01 00 00 00 00 00 00 00-08 14 35 10 02 00 00 00  ..........5.....
00000263`50be7c8a  f8 87 37 10 02 00 00 00-00 00 00 00 00 00 00 00  ..7.............
00000263`50be7c9a  00 00 00 00 00 00 00 00-e0 02 00 00 00 00 00 00  ................
00000263`50be7caa  00 00 00 00 00 00 00 00-1c 01 00 00 00 00 00 00  ................
00000263`50be7cba  44 03 00 00 00 00 00 00-78 12 00 00 00 00 00 00  D.......x.......
00000263`50be7cca  88 02 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
00000263`50be7cda  00 00 00 00 00 00 00 00-00 00 00 00 00 00 00 00  ................
```

This is apparently data for the MSYS2/Cygwin runtime library. It's definitely not the format of the file-descriptor data that the Windows C runtime expects. The latter should start with the number of file descriptors in the buffer as a C `int` (i.e. a 4-byte integer). The number of file descriptors should be at least 64. Following that, it should have an array of bytes, each of which describes the type of file (disk, pipe, character device) and state of each file descriptor as a bit mapping (bits 0 through 7: `FOPEN`, `FEOFLAG`, `FCRLF`, `FPIPE`, `FNOINHERIT`, `FAPPEND`, `FDEV`, `FTEXT`). Finally, the buffer should end with the corresponding array of native OS file handles.

I'm pretty sure the above MSYS2 runtime data starts with a 0 valued `int` in order to ensure that the Windows C runtime ignores it. Thus it is not possible for the Windows build of Python to inherit file descriptors from MSYS2 bash. It should work with an MSYS2 build of Python.

**Comment by dnschneid** [comment]
Thanks for the detailed response!  The MSYS2/Cygwin behavior is probably a red herring then; I'll have to look into what convention the third-party tool is actually using that originally got me on this path.  It is proprietary and their example C code just includes stdio and reads/writes to the extra fds...but they don't say what libc they've used.

Is it safe to assume that Python is supposed to be receiving and exposing those fds via the process you describe above, or is it possible that the versions built for Windows do not support it for some reason?

If it's quick for you to write a test program that can spawn Python with extra fds in the expected way to confirm it works, that would be very helpful.  Regardless, I'll look into figuring out what the third-party tool is doing.

**Comment by eryksun** [comment]
Here's a quick and dirty test program that spawns Python with an inherited fd for the write end of a pipe. The Python command writes "spam" to the pipe and exits.

```c
#include <io.h>
#include <fcntl.h>
#include <stdio.h>
#include <process.h>

int main()
{
    int fds[2];
    wchar_t script[100];
 
    _pipe(fds, 4096, _O_BINARY | _O_NOINHERIT);
    int fd_child = _dup(fds[1]);
    swprintf(script, 100, 
             L"\"import os; os.write(%d, b'spam'); os._exit(0)\"",
             fd_child);
    if (!_wspawnl(_P_WAIT, L"C:\\Program Files\\Python311\\python.exe",
                  L"python", L"-c", script)) {
        char buf[100];
        _read(fds[0], buf, 4);
        buf[4] = '\0';
        printf("data read: %s\n", buf);
        return 0;
    }
    return 1;
}
```
```text
>.\test_fd_inherit.exe
data read: spam
```

**Comment by dnschneid** [comment]
Awesome, thank you so much for testing that!
Now to dive into what terrible things the proprietary tool is doing...

**Comment by NeedsMoar** [comment]
The problem with what you're trying to do there (among other weirdness) is that file handles other than STDIN, STDOUT, and STDERR aren't inherited by sub-processes by default on Windows, as you know from your C code that's duplicating the pipe you opened into an inheritable one so it'll actually work, and stuff launched by cmd counts as a sub-process when it has to call out to externals like the python interpreter.  Even if it worked, which it likely won't with anything but builtin commands, 
If you do manage to get something on the 3rd FD it probably won't be writable the way you're wanting or will be killed when the python interpreter terminates.  All 1>&3 is doing is saying that both STDOUT and whatever is on 3 should go to the same place...  that place will end up being wherever you redirect them, and they'll all be in STDIN as far as whatever receives them is concerned.  You should be able to get it to print by throwing an echo command on there but the syntax gets incredibly silly when you start using multiple redirection operators and I'm not sure what you're trying to do or whether you want to input to or read output from the third party software.  

Either should probably just be done with |, that's the standard method of doing so.  File handle 3 was MS-DOS legacy STDAUX (com port) and if you check my link below it's suspected that there's some internal meaning to it in the interpreter or access has just been blocked off entirely since NT kernel came about and crufty things like that which would have needed kernel calls to perform direct IN / OUT ring0 commands with arbitrary data as input would be immediately removed from userland if not admin mode shell too, but it won't work with other numbers even with the correct syntax either. 
For example, 
`5>"C:\Programs\Shark\qua.txt" (echo I ATE THE PROM 1>&5)`
works and writes the text of the echo command to the file mapped onto 5, but with a modified version of your program it just gives this (ignore the old python, it doesn't work in newer versions either but that one was quicker to type the path to):
```
5>"C:\Programs\Shark\qua.txt" (C:\Python27\python.exe bla.py 1>&5)
Traceback (most recent call last):
  File "bla.py", line 6, in <module>
    os.fdopen(5);   #same with os.write or os.dup followed by os.write to the duplicated handle, which fails on the os.dup call
OSError: [Errno 9] Bad file descriptor
```

[SS64](https://ss64.com/nt/syntax-redirection.html ) has lots of info on this command as well as a link to the nightmare somebody got into trying to use file descriptor 3 in particular for anything;  a link on the stackoverflow post has a batch file that will determine which of the descriptors are actually free.  Nobody has come up with any good theory on why that one is special other than the STDAUX thing, really.  Microsoft would likely answer if you asked them but they'd just tell you to pipe everything because they're in the midst of modernizing cmd.exe into Terminal.   My system only had two of them available in the first place and they don't match between systems so hardcoding any of them isn't a good option.  

Your echo example in the bash script works because a) echo is an internal command b) all it's doing is mixing together the output of STDOUT with 3 and since 3 isn't mapped anywhere it just ends up all going to STDOUT, and possibly would work in more complicated ways because c) bash on windows in the godawful hack that is msys2 may be remapping everything in an only partially linux compatible way because of the underlying differences they just ignored when they built it, but normal semantics require you to map an output stream to a file before you do anything with it anyway

**Comment by eryksun** [comment]
Let's paint a more detailed picture here, starting with a description of native system handles for kernel objects, which are not to be confused with emulated POSIX file descriptors provided by runtime libraries such as the C runtime (ucrtbase), MSYS2, or Cygwin. 

Every process has a handle table. An entry in the table maps a handle value (e.g. 0x4, 0x8, 0xC; modulo 4 because the lower 2 bits of a handle value are reserved as tag bits) to the address of an executive object in the kernel (e.g. Session, WindowStation, Desktop, Job, Process, Thread, Section, File, Event, Semaphore), a 32-bit mask of granted access rights to the object (e.g. synchronize, read control, write DAC, write owner, delete), and handle attributes (e.g. inherit, protect-from-close).

In general, all handles that are marked as inheritable will be inherited by a child process if `CreateProcessW()` is called with handle inheritance enabled, i.e. if the `bInheritHandles` argument is true. The subset of inheritable handles can be constrained using a `PROC_THREAD_ATTRIBUTE_HANDLE_LIST` creation attribute, but the handles still have to be marked as inheritable.

The Process Environment Block (PEB) of a process contains a `ProcessParameters` record that, among other things, includes four handle values for use by console I/O and standard I/O: `ConsoleHandle`, `StandardInput`, `StandardOutput`, and `StandardError`. At startup the `ConsoleHandle` value is a reference file for a console session, which the system uses to open a connection file for a console session. The latter handle is used implicitly by the console API (e.g. by `GetConsoleProcessList()`).

Applications look up the current standard handle values by calling `GetStdHandle()` with either `STD_INPUT_HANDLE`, `STD_OUTPUT_HANDLE`, or `STD_ERROR_HANDLE`. Note that the current standard handle values of a process are not constants, in contrast to POSIX, which always uses file descriptors 0, 1, and 2 respectively for `STDIN`, `STDOUT`, and `STDERR`. 

If handle inheritance is enabled (i.e. the `close_fds` argument of `subprocess.Popen` is false), and all of the standard handles are inheritable, and none is redirected, then the standard handle values of a child process are the same as its parent. For example (with a user-mode debugger attached to Python and its child process):

```text
>>> subprocess.call('python', close_fds=False)
Breakpoint 0 hit
KERNELBASE!CreateProcessW:
00007ffc`19a7fe80 4c8bdc          mov     r11,rsp
```
Here are the handle values for the console connection (i.e. a handle for "\\Device\\ConDrv\\Connect") and the standard handles in the parent process:

```text
0:000> ?? @$peb->ProcessParameters->ConsoleHandle
void * 0x00000000`00000058
0:000> ?? @$peb->ProcessParameters->StandardInput
void * 0x00000000`00000064
0:000> ?? @$peb->ProcessParameters->StandardOutput
void * 0x00000000`000001cc
0:000> ?? @$peb->ProcessParameters->StandardError
void * 0x00000000`000001c4
0:000> g
```
The following is the debugger output for the child process, just after it loads the system DLL (i.e. ntdll.dll).

```text
************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is:
ModLoad: 00007ff7`c0900000 00007ff7`c091a000   python.exe
ModLoad: 00007ffc`1c190000 00007ffc`1c3a4000   ntdll.dll
ntdll!RtlUserThreadStart:
00007ffc`1c1ea9d0 4883ec78        sub     rsp,78h
```
The child inherited 4 handles, which in this case all refer to kernel File objects. There's a console handle that references an inherited console session (i.e. an open File for "\\Device\\ConDrv\\Reference") and the three standard handles. These all have the same handle values as in the parent (e.g. 0x4, 0x64, 0x1cc, 0x1c4). The handle for the file that references the inherited console session (e.g. handle 0x4) is used to open a new connection file at startup (i.e. an open file for "\\Device\\ConDrv\\Connect"), which replaces the initial value of `ConsoleHandle` in `ProcessParameters`.

```text
1:003> !handle 0 3
Handle 4
  Type          File
  Attributes    0
  GrantedAccess 0x12019f:
         ReadControl,Synch
         Read/List,Write/Add,Append/SubDir/CreatePipe,ReadEA,WriteEA,ReadAttr,WriteAttr
  HandleCount   5
  PointerCount  131073
Handle 64
  Type          File
  Attributes    0
  GrantedAccess 0x12019f:
         ReadControl,Synch
         Read/List,Write/Add,Append/SubDir/CreatePipe,ReadEA,WriteEA,ReadAttr,WriteAttr
  HandleCount   5
  PointerCount  129889
Handle 1c4
  Type          File
  Attributes    0
  GrantedAccess 0x12019f:
         ReadControl,Synch
         Read/List,Write/Add,Append/SubDir/CreatePipe,ReadEA,WriteEA,ReadAttr,WriteAttr
  HandleCount   9
  PointerCount  196450
Handle 1cc
  Type          File
  Attributes    0
  GrantedAccess 0x12019f:
         ReadControl,Synch
         Read/List,Write/Add,Append/SubDir/CreatePipe,ReadEA,WriteEA,ReadAttr,WriteAttr
  HandleCount   9
  PointerCount  196450
4 Handles
Type            Count
File            4
```
```text
1:003> ?? @$peb->ProcessParameters->ConsoleHandle
void * 0x00000000`00000004
1:003> ?? @$peb->ProcessParameters->StandardInput
void * 0x00000000`00000064
1:003> ?? @$peb->ProcessParameters->StandardOutput
void * 0x00000000`000001cc
1:003> ?? @$peb->ProcessParameters->StandardError
void * 0x00000000`000001c4
```

OTOH, if handle inheritance is disabled when spawning a console application, then the standard handles of the parent process get *duplicated* to the child process instead of inherited, i.e. the child handle values will be different but still reference the same kernel File object(s). For example:

```text
>>> subprocess.call('python', close_fds=True)
Breakpoint 0 hit
KERNELBASE!CreateProcessW:
00007ffc`19a7fe80 4c8bdc          mov     r11,rsp
0:000> ?? @$peb->ProcessParameters->StandardInput
void * 0x00000000`00000064
0:000> ?? @$peb->ProcessParameters->StandardOutput
void * 0x00000000`000001cc
0:000> ?? @$peb->ProcessParameters->StandardError
void * 0x00000000`000001c4
0:000> g
```

In the child process, the console handle and standard handles are duplicated into an empty handle table instead of inherited, so the values increment modulo 4 as expected.

```text
************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is:
ModLoad: 00007ff7`c0900000 00007ff7`c091a000   python.exe
ModLoad: 00007ffc`1c190000 00007ffc`1c3a4000   ntdll.dll
ntdll!RtlUserThreadStart:
00007ffc`1c1ea9d0 4883ec78        sub     rsp,78h
1:003> ?? @$peb->ProcessParameters->ConsoleHandle
void * 0x00000000`00000004
1:003> ?? @$peb->ProcessParameters->StandardInput
void * 0x00000000`00000008
1:003> ?? @$peb->ProcessParameters->StandardOutput
void * 0x00000000`0000000c
1:003> ?? @$peb->ProcessParameters->StandardError
void * 0x00000000`00000010
```

Finally, here's an example in which the standard error file is overridden to a pipe. `subprocess.Popen` sets up the standard handles in the `STARTUPINFO` by overriding all 3 with duplicate, inheritable handles.

```text
>>> subprocess.call('python', stderr=PIPE)
Breakpoint 0 hit
KERNELBASE!CreateProcessW:
00007ffc`19a7fe80 4c8bdc          mov     r11,rsp
0:000> ?? @$peb->ProcessParameters->StandardInput
void * 0x00000000`00000064
0:000> ?? @$peb->ProcessParameters->StandardOutput
void * 0x00000000`000001cc
0:000> ?? @$peb->ProcessParameters->StandardError
void * 0x00000000`000001c4
0:000> g
```
Child process:

```text
************* Path validation summary **************
Response                         Time (ms)     Location
Deferred                                       srv*
Symbol search path is: srv*
Executable search path is:
ModLoad: 00007ff7`c0900000 00007ff7`c091a000   python.exe
ModLoad: 00007ffc`1c190000 00007ffc`1c3a4000   ntdll.dll
ntdll!RtlUserThreadStart:
00007ffc`1c1ea9d0 4883ec78        sub     rsp,78h
1:003> ?? @$peb->ProcessParameters->StandardInput
void * 0x00000000`00000134
1:003> ?? @$peb->ProcessParameters->StandardOutput
void * 0x00000000`00000144
1:003> ?? @$peb->ProcessParameters->StandardError
void * 0x00000000`00000158
```
In a kernel debugger, we can see that the child's `StandardError` handle (i.e. handle 0x158) refers to a File object in a named-pipe filesystem (NPFS).

```text
lkd> !handle 158 1

PROCESS ffff8009017350c0
    SessionId: 1  Cid: 0f34    Peb: 985b8cc000  ParentCid: 0368
FreezeCount 1
    DirBase: 16d7c002  ObjectTable: ffffc2093125b7c0  HandleCount:   4.
    Image: python.exe

Handle table at ffffc2093125b7c0 with 4 entries in use

0158: Object: ffff80090301e250  GrantedAccess: 00120196 (Inherit)
```
```text
lkd> !fileobj ffff80090301e250

Related File Object: 0xffff80090301d2b0

Device Object: 0xffff8008f9a3ab70   \FileSystem\Npfs
Vpb is NULL
Event signalled

Flags:  0x40482
        Synchronous IO
        Named Pipe
        Queue Irps to Thread
        Handle Created

FsContext: 0xffffc2092bfbe9b0   FsContext2: 0xffffc20932875511
Private Cache Map: 0x00000001
CurrentByteOffset: 0
```

---

As I discussed previously, the C runtime on Windows emulates POSIX-like file descriptors for the sake of cross-platform C code. This hides the differences between POSIX file descriptors and native Windows File handles. For example, file descriptors only refer to files (whereas handles can reference any type of kernel object); a newly opened file descriptor is assigned the first available, unit-incremented value (whereas handle values are modulo 4, and File handles aren't opened in a reliable sequence); and a file descriptor can be duped onto another file descriptor via `dup2()` (whereas a handle cannot be duplicated onto a specific handle value). A valid C file descriptor is associated with an OS File handle and a set of flags that describe the file type and whether the file descriptor is inheritable via `_[w]spawn*()`.

The C runtime `_[w]spawn*()` family of functions store the data for inheritable file descriptors in the `STARTUPINFO` record's `cbReserved2` and `lpReserved2` fields. In the child process, this data is available in the `RuntimeData` field of the PEB `ProcessParameters`, and it can be accessed by calling `GetStartupInfoW()` to convert the internal NT `ProcessParameters` back to a WinAPI `STARTUPINFO` record.

Note that the CMD shell has no support for inheriting file descriptors to child processes. It does not use the C `_[w]spawn*()` functions, and it has no manual support for using the `cbReserved2` and `lpReserved2` fields of the `STARTUPINFO` in order to pass C runtime file-descriptor data. For example, with a debugger attached to CMD, we see that the `cbReserved2` and `lpReserved` values are both 0 in the `STARTUPINFO` record (argument 9 on the stack) that it passes to `CreateProcessW()`:

```text
C:\Temp>python 3>&1
Breakpoint 0 hit
KERNELBASE!CreateProcessW:
00007ffc`19a7fe80 4c8bdc          mov     r11,rsp
0:000> ?? ((short *)&((char ***)@rsp)[9][8])[1]; * STARTUPIONFO.cbReserved2
short 0n0
0:000> ?? ((void ***)@rsp)[9][9]; * STARTUPINFO.lpReserved2
void * 0x00000000`00000000
```

CMD is a single-threaded shell that implements standard I/O redirection by temporarily modifying its standard handles before calling `CreateProcessW()`. When it calls the latter directly, it always enables handle inheritance. OTOH, if it calls `ShellExecuteExW()` to execute a file by association, the shell API's internal `CreateProcessW()` call disables handle inheritance. If it's a console application, however, as explained above, the system will still duplicate the standard handles to the child process. For example:

```text
C:\Temp>type test.py
#!/usr/bin/python3
print('standard input:', input())

C:\Temp>echo spam | test.py 2>&1 | more
standard input: spam

C:\Temp>ren test.py test.pyw
C:\Temp>echo spam | test.pyw 2>&1 | more
C:\Temp>

C:\Temp>echo spam | pyw test.pyw 2>&1 | more
standard input: spam

C:\Temp>echo spam | pythonw test.pyw 2>&1 | more
standard input: spam

```
In the first example, based on the ".py" file association, "py.exe" or "python.exe" gets executed without inheriting any handles, but since it's a console app, the system at least duplicates the standard handles to the child. In the second example, based on the ".pyw" file association, "pyw.exe" or "pythonw.exe" gets executed without inheriting any handles, and since it's a GUI app, the system does not duplicate the standard handles to the child, and the script silently fails. The third and fourth examples show that it works fine when "pyw.exe" or "pythonw.exe" is executed directly, in which case CMD calls `CreateProcessW()` directly instead of via `ShellExecuteExW()`.

---

The examples from the initial bug report in this issue used MSYS2 bash. That's a different environment, which has nothing to do with the C runtime's file descriptor emulation and `_[w]spawn*()` functions. If you install the MSYS2/Cygwin build of Python via `pacman -S python`, then you'll find that file descriptors work as expected for bash, Python, and other applications that are built for the MSYS2/Cygwin environment. For example:

```text
$ python3 3>&1
Python 3.11.3 (main, May 20 2023, 12:14:18) [GCC 11.3.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.write(3, b'ok\n')
ok
3
```

The Windows build of Python, on the other hand, has no use for the MSYS2 runtime data. It uses Microsoft's C runtime for file-descriptor emulation, and it thus requires the specific runtime data format that's used by the C runtime's `_[w]spawn*()` functions. 

 
> [SS64](https://ss64.com/nt/syntax-redirection.html) has lots of info on this command as well as a link to the nightmare somebody got into trying to use file descriptor 3 in particular for anything; a link on the stackoverflow post has a batch file that will determine which of the descriptors are actually free. Nobody has come up with any good theory on why that one is special other than the STDAUX thing, really.

There's nothing special about file descriptor 3 in CMD, but there are bugs in CMD's implementation of saving and restoring a file-descriptor reference, as pointed out by [this answer](https://stackoverflow.com/a/9880156). For example:

```text
C:\>echo spam 1>&3
```

First save the current fd 1 reference by duping it to the first available fd, which happens to be 3 in this case.

```text
Breakpoint 0 hit
ucrtbase!dup:
00007ffc`19993200 4053            push    rbx
0:000> r rcx
rcx=0000000000000001
0:000> pt
ucrtbase!dup+0x35:
00007ffc`19993235 c3              ret
0:000> r rax
rax=0000000000000003
0:000> g
```

Now redirect fd 1 to the current reference of fd 3 (i.e. `dup2(3, 1)`), which happens to be the file reference that was just saved.

```text
Breakpoint 1 hit
ucrtbase!dup2:
00007ffc`19993240 4053            push    rbx
0:000> r rcx, rdx
rcx=0000000000000003 rdx=0000000000000001
0:000> g
spam
```

Finally, restore the saved reference in fd 3 back to fd 1:

```text
Breakpoint 1 hit
ucrtbase!dup2:
00007ffc`19993240 4053            push    rbx
0:000> r rcx, rdx
rcx=0000000000000003 rdx=0000000000000001
0:000> g
```

It's really a silly bug because the developer didn't check that `dup(1)` returned fd 3, which means that fd 3 wasn't a valid fd to begin with.

> they're in the midst of modernizing cmd.exe into Terminal. My system only had two of them available in the first place and they don't match between systems so hardcoding any of them isn't a good option.

CMD is a shell that uses standard I/O, not a console or terminal that provides console I/O. Windows applications such as "cmd.exe", "pwsh.exe", and "python.exe" attach to a console session via inheritance, `AllocConsole()`, or `AttachConsole()`.

The system's builtin host for a console session is "conhost.exe", which also implements the classic system terminal window. "conhost.exe" was updated in Windows 10+ to support virtual-terminal escape sequences as an alternative to the classic console API, and also to support ConPTY pseudoconsole sessions.

Windows Terminal is a bit more complex. The terminal UI is implemented by "WindowsTerminal.exe", which has a tab for each console session, which is hosted by an instance of "OpenConsole.exe" (an open-source build of "conhost.exe"). If Windows Terminal is set as the default terminal, then currently in Windows 11, "conhost.exe" is actually responsible for spawning Windows Terminal via the latter's registered COM interface, and subsequently the background instance of "conhost.exe" waits for the terminal to exit.
