### ISSUE TITLE
PowerShell support

### ISSUE THREAD

**Issue by R-LIBIN** [python/cpython#104459]
Hi Team, 

We see the Powershell and bash most popular in the Systems side. We need the support similar to os.system package for the making of things simpler. Kindly help out and add the support. Pls Add packages with in the python in the future.

**Comment by gaogaotiantian** [comment]
Could you be more specific about what you are looking for? What's the equivalent package for bash? What kind of features are you suggesting? `os.system()` works with powershell now.

**Comment by R-LIBIN** [comment]
As we are aware of os.system() function for cmd. Similar, Looking for the
inbuilt support for the Powershell os.powershell() kind of like that. Now,
it's too much hassle to connect, currently.

**Comment by ericvsmith** [comment]
Just as there is no `os.bash()` function, there shouldn't be an `os.powershell` function. Not that I recommend `os.system` unless you know what you're doing, but you can easily write your own `powershell` function:
```python
def powershell(cmd):
  os.system("powershell " + cmd)

powershell("dir")
```
You say it's too much hassle. Could you elaborate on this?

**Comment by R-LIBIN** [comment]
Hi Team,

During , the sys operations we need complex queries to be inbuilt into the
system and invoke scripts and get the output, then processing the output.
And, this goes on.

Support for formatting output if at all through some around the neck works
is too complicated.

Thank you.

Regards,
Libin

**Comment by gaogaotiantian** [comment]
`os.system()` can bring up `powershell` instead of `cmd`. If you look at the [docs](https://g.dianping.com/ssr/biz-product-detail/play-theme-detail.html?shopid=k13Cot7FQT1RiFnq&productid=698890306), on Windows, it'll read `COMSPEC` enviroment variable to determine which program to use. Normally `COMSPEC` points to CMD, but you can set the env var to powershell and `os.system()` will use powershell - again, not that we recommend it.

In powershell:

```powershell
> $Env:Comspec = "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe"
> python
```

Then

```python
import os
# This will work!
os.system("ls")
```

**Comment by ericvsmith** [comment]
> Support for formatting output if at all through some around the neck works is too complicated.

It sounds like you want something like https://pypi.org/project/windows-tools.powershell/

I'm going to close this issue, because I don't think we'll add any specific powershell support to the stdlib. If you'd like to discuss it further, I suggest opening a discussion on https://discuss.python.org/c/ideas/6
