### ISSUE TITLE
Ctrl+C doesn't work on Windows Powershell

### ISSUE THREAD

**Issue by Polda18** [python/cpython#104566]
# Bug report
When I run the `python3 -m http.server` command in Powershell, I cannot stop the process by simple Ctrl+C keyboard shortcut, it does nothing. As far as I have found, it has been reported in numerous packages, so it is not actually unique to this module, however the behaviour varies from package to package. Some packages managed to fix this issue by adding some additional code, but I didn't verify the source codes. That however implies that this issue is fixable inside a Python code. So

# My environment
- CPython versions tested on: Windows Powershell (specifically `http.server`)
- Operating system and architecture: Windows 11, 64bit
- Powershell version: 5.1.25336.1000

My projects don't actually rely on this functionality, and I can actually stop the child process by killing the parent Powershell window, so I'm not really stuck with a running webserver until I shut down the computer. But it is inconvenience, because then I'll have to open Powershell again when I want to do something else or launch the webserver again. Windows Command Line doesn't have this issue, but what I care about is convenience, and Powershell actually gives me tools to create Powershell commands of my own, which I did, using my own module.

**Comment by eryksun** [comment]
Console applications such as "cmd.exe", "powershell.exe", and "python.exe" either inherit a console/terminal or allocate a new one. The commonly used terminals on Windows are the builtin console host "conhost.exe", "WindowsTerminal.exe", and "mintty.exe" (Cygwin/MSYS2). I can use Ctrl+C to kill `py -m http.server` when it's running in any of these common terminals. 

In which terminal environment are you running PowerShell and Python? Is it "powershell_ise.exe" (integrated scriping environment)?

**Comment by Polda18** [comment]
I am running Powershell in Windows Terminal (which is the default application that launches when I launch Powershell, except for Administrator permissions, admin evelation launches conhost instead as it seems, but that's not what I'm using in this case). It cannot be in the terminal application, because cmd uses the very same terminal, and there it works. However I cannot use Powershell cmdlets in cmd (unless I specifically invoke Powershell in cmd).

**Comment by eryksun** [comment]
I cannot reproduce a problem with Ctrl+C when I execute Python from PowerShell in Windows Terminal. For example:

```text
PS C:\> &"C:\Program Files\Python311\python.exe" -m http.server
Serving HTTP on :: port 8000 (http://[::]:8000/) ...

Keyboard interrupt received, exiting.
```

A command-line interface shell such as "cmd.exe" or "powershell.exe" just waits for an executed child process to exit. The child has a direct connection to the console session for its keyboard input, output, and console control events (i.e. Ctrl+C, Ctrl+Break, close, logoff, shutdown).

When a console session is inherited or attached to instead of allocated, the session may be in a state that doesn't generate Ctrl+C events. In this case, Ctrl+C processing can be restored by calling WinAPI `GetConsoleMode(hConsoleInput, &mode);` `SetConsoleMode(hConsoleInput, mode | ENABLE_PROCESSED_INPUT)`.

An app can ignore Ctrl+C events by calling WinAPI `SetConsoleCtrlHandler(NULL, TRUE)`. It may also inherit this state from its parent process or get spawned in this state via the creation flag `CREATE_NEW_PROCESS_GROUP`. Normal Ctrl+C handling can be restored by calling WinAPI `SetConsoleCtrlHandler(NULL, FALSE)`.

Unlike Ctrl+C, there's no API to ignore Ctrl+Break events at a low level. However, it's not always obvious how to type Ctrl+Break if you don't have a standard desktop keyboard. It's usually possible to type Ctrl+Break on a laptop using the Fn key (e.g. Ctrl+Fn+B), but it depends on the manufacturer and model number. By default, Python uses the default handler for Ctrl+Break, which exits via WinAPI `ExitProcess()`.

> I am running Powershell in Windows Terminal (which is the default application that launches when I launch Powershell, except for Administrator permissions, admin evelation launches conhost instead as it seems, but that's not what I'm using in this case)

Starting with Windows 11, Windows Terminal can be configured as the default terminal. Each tab in Windows Terminal is a separate console session that's hosted by an instance of "OpenConsole.exe".

Since Explorer is a graphical shell that has no console session for a child process to inherit, if you run a console app from Explorer, the app allocates a new console session, which is hosted by an instance of the system console host, "conhost.exe". If this "conhost.exe" process isn't elevated, and the allocating app isn't started with certain flags (e.g. `CREATE_NO_WINDOW`), then it checks the registry key "HKCU\\Console\\%%Startup" to see whether the user wants to use an alternate console session host and alternate terminal. If no alternate terminal is configured, then "conhost.exe" simply connects to the allocating app, and, if requested, it creates and shows the classic console window. Otherwise "conhost.exe" spawns the alternate console session host (e.g. "OpenConsole.exe"), which spawns the alternate terminal frontend (e.g. "WindowsTerminal.exe").

**Comment by Polda18** [comment]
That's interesting. Well, what I can do, once I get back home from work is to check the version of my Windows Terminal. I didn't do any changes to it, no changes in it's behaviour, so I'm not sure if it is a bug of the terminal or if it is a bug of Powershell. Windows Terminal is by default preferred on Windows 11 (being it preinstalled as well), on Windows 10, it is possible to install Windows Terminal from MS Store, and installing it will automatically change the preferred console application to Windows Terminal.

**Comment by Polda18** [comment]
Wouldn't you believe it? I installed Windows Updates and the bug was fixed. So it seems like whatever caused the Ctrl+C to glitch out, is gone now.

**Comment by jcheng5** [comment]
Exactly the symptoms @Polda18 just happened to me. Windows 11, Windows Terminal, PowerShell. Ctrl+C did nothing. I created multiple new PowerShell tabs within Windows Terminal, they all behaved the same. I created multiple new cmd tabs within Windows Terminal, they all worked fine. And Windows console host running PowerShell also worked fine.

Closed and restarted the Windows Terminal app, the problem went away. 🤷‍♂️
