### ISSUE TITLE
[BUG] heapq.merge seems not correct

### ISSUE THREAD

**Issue by hccyril** [python/cpython#104790]
I found this bug when solving the Leetcode problem: [23. Merge k Sorted Lists](https://leetcode.com/problems/merge-k-sorted-lists/description/)

i'm trying to use heapq.merge to merge multiple sorted linked list into one, in order to do so, i've prepare the wrapper class IterListNode so that the linked list node can be iterated.

the code was relatively simple, and the result is not correct, it will output the correct sorted list, but with some extra numbers appended in the tail.

so i suspect it's a bug from heapq

here's the complete code to regenerate the bug:

```Python
import heapq
from typing import List, Optional

# Definition for singly-linked list.
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

# my Iterator for ListNode
class IterListNode:
    def __init__(self, head: ListNode | None) -> None:
        self.head = head
        self.cur = head
    def __next__(self):
        if self.cur:
            a = self.cur.val
            self.cur = self.cur.next
            return a
        else:
            raise StopIteration
    def __iter__(self):
        self.cur = self.head
        return self

def toListNode(a) -> ListNode:
    head, tail = None, None
    for val in a:
        if not head:
            head = tail = ListNode(val)
        else:
            tail.next = ListNode(val)
            tail = tail.next
    return head

class Solution_P0023:
    def mergeKLists(self, lists: List[Optional[ListNode]]) -> Optional[ListNode]:
        if not lists or all(not li for li in lists):
            return None
        iterList = [IterListNode(nodeHead) for nodeHead in lists]
        li = heapq.merge(*iterList)
        print('merge=', *li)
        return toListNode(li)

sln = Solution_P0023()    

# both WA
# test case #1
# answer:   1 1 3 4 4 5 1 4 5
# expected: 1 1 3 4 4 5
lists = [toListNode([1,4,5]), toListNode([1,3,4])]

# test case #2
# answer:   1 1 2 3 4 4 5 6 2 6
# expected: 1 1 2 3 4 4 5 6
# lists = [toListNode([1,4,5]), toListNode([1,3,4]), toListNode([2,6])]

ansNode = sln.mergeKLists(lists)
print(*IterListNode(ansNode))

```

the output and expected output i have typed in the comment of the code.
i'm using Python 3.11.1 of Windows 11. the test was run on Visual Studio Code.

**Comment by gaogaotiantian** [comment]
In my experience, it's almost always the users' code that has a bug when they are trying to solve a difficult problem with complex data structures, but happen to use a standard library.

In your case, it's `IterListNode` - you should not do `self.cur = self.head` in ``__iter__``. You can't reset the iterator when a function asks for its iterator(which is itself). Removing that line and you're good to go.

That's why we suggest having a "minimum reproducing example" - a real bug with the standard library should be easy to reproduce without complex unrelated code. If there's a bug in `heapq.merge`, you should be able to reproduce it with simple data, not a leetcode question.
