### ISSUE TITLE
Global state affected by inspecting frames and causing weakrefs to fail

### ISSUE THREAD

**Issue by stur86** [python/cpython#104748]
# Bug report

I am using `weakref` to create weak proxies to a function. If I then delete the function and force a garbage collection, this unbinds the proxy, as it should. However, if _before_ the deletion I call `inspect.stack()` and then inspect the locals of its individual frames, this seems to affect the global state of the application and store a reference to the function somewhere, which means the weakref keeps living:

```py
import gc
import weakref
import inspect


def test_weakref():
    
    def test():
        return 1
    
    p1 = weakref.proxy(test)
    
    assert p1() == 1
    
    # Now try deleting the function
    del test
    gc.collect()
    
    failed = False
    try:
        p1()
    except ReferenceError:
        failed = True
    finally:
        assert failed
    
    def test():
        return 2
    
    p1 = weakref.proxy(test)

    assert p1() == 2
    
    stack = inspect.stack()
    for s in stack:
        s.frame.f_locals
            
    # Now try deleting the function
    del test
    gc.collect()
    
    failed = False
    try:
        p1()
    except ReferenceError:
        failed = True
    finally:
        assert failed
        
if __name__ == "__main__":
    test_weakref()

```

This happens if the code is put in a test function, but not if it's in the `__main__` clause.

# Your environment

Tested on Python 3.8 and 3.10. Happens in both.

Tested on Windows 11 Home 22H2, build 22621.1702.

**Comment by carljm** [comment]
Frame objects hold a reference to a dictionary of the frame locals, which (for function frames) is created lazily when `f_locals` is accessed, based on the current values in the frame's "fast locals" array. This dictionary won't be updated again from fast locals until/unless `f_locals` is accessed again. So accessing `f_locals` once creates and caches a locals dictionary that includes the `test` function, and the deletion of the `test` function isn't reflected in that locals dict, because you don't access `f_locals` on the frame object again.

I think that this caching of the locals dict could be removed, but it would make introspection of `f_locals` on function frames even slower, since a new dictionary would have to be created each time.

I don't think there is any guarantee made by CPython about the timing of weakref invalidation, and in particular I don't think it's reasonable to expect frame stack introspection to have no effect on the lifetime of locals within the currently-executing frame. So I don't think this is a bug (it doesn't contradict any behavior guaranteed by the documentation.) I will mark it as `pending` and wait to see if others have thoughts.

**Comment by stur86** [comment]
Thanks for the explanation, that makes sense. For my specific use case in which I found this problem I guess I'd be happy with knowing if there's a way to force clearing that cache. Performance is not an issue.

**Comment by carljm** [comment]
> I'd be happy with knowing if there's a way to force clearing that cache

I don't think there's a way to clear it, but you can access `f_locals` on the frame again after making changes to the locals, to force updating the cache to reflect currently live locals.

E.g. adding a second `for s in stack: s.frame.f_locals` loop after the deletion of `test` "fixes" your repro.

**Comment by stur86** [comment]
Ah, sadly that doesn't work in my actual use case, I just want to do an inspection but then make sure that the weak reference will expire whenever that might naturally happen.
