### ISSUE TITLE
Bytes conversion in the basic type can swallow binary bytes.

### ISSUE THREAD

**Issue by LedbetterBlog** [python/cpython#104914]
# Bug report

"When converting bytes, there is a possibility of losing binary data. Here is a very reproducible example: print(bytes(b'\x08\x01\x10\xb6\x93\x9d\xf3\x84\x31\x1a\x10\x64\x61\x39\x38\x36\x33\x38\x61\x30\x38\x31\x64\x31\x36\x63\x66')). The printed result is b'\x08\x01\x10\xb6\x93\x9d\xf3\x841\x1a\x10da98638a081d16cf', but the actual result should be b'\x08\x01\x10\xb6\x93\x9d\xf3\x84\x31\x1a\x10da98638a081d16cf'. The bytes '\x84' and '\x31' have merged together. How can I solve this problem? I can't avoid this issue whenever I use bytes."

# Your environment

python3.8.10
windows64

**Comment by hauntsaninja** [comment]
Your bytes are unchanged:
```
>>> b"\x31\x32"
b'12'
>>> b"\x31\x32" == b"12"
True
>>> b"\x31\x32"[0]
49
>>> b"\x31\x32"[1]
50
>>> b"12"[0]
49
>>> b"12"[1]
50
```

By default, `bytes.__repr__` will represent any individual byte in the ASCII range as the corresponding ASCII value instead of escaping it. If you want a custom representation of your bytes, you're better off doing it yourself, for instance, by converting each byte to hex yourself.

For more help, discuss.python.org is a better forum than this.
