### ISSUE TITLE
Unexpected behaviour when sorting with zipped 2-dimensional arrays and two of values are identical

### ISSUE THREAD

**Issue by costabm** [python/cpython#104977]
Unexpected behaviour when sorting a zipped list with a 2-dimensional array and two of the values of the list are identical:
sorted(zip(np.array([1,1]),np.array([[1,2],[3,4]])))  # ValueError (ambiguity)

However, if using lists, no error occurs:
sorted(zip([1,1],[[1,2],[3,4]]))  # OK !

**Comment by pochmann** [comment]
Please note this place is for bugs in CPython, not for help with *your* bugs. See the issue template text that you used for information about where to get help.

**Comment by chgnrdv** [comment]
This behaviour is expected and is probably based on how numpy defines comparison (`__lt__`, `__eq__` etc) and `__bool__` operations on arrays.

`sorted`, when applied to `zip` object, firstly creates a `list` object from it:
```python
>>> x = np.array([1, 1])
>>> y = np.array([[1, 2], [3, 4]])
>>> l = list(zip(x, y))
>>> l
[(1, array([1, 2])), (1, array([3, 4]))]
```
Then `.sort` method is called on that list, comparing its elements and trying to convert comparison result to boolean type. For elements of `tuple` type it means that if length of both tuples is equal, the first elements are compared; if they are equal, the second ones are taken and so on. In our case, because the first two elements are equal, second ones, which are numpy arrays, will be compared:
```python
>>> l[0][0] == l[1][0]
True
>>> l[0][1]
array([1, 2])
>>> l[1][1]
array([3, 4])
>>> r = l[0][1] < l[1][1]
>>> r
array([ True,  True])
```
But attempt to convert a result to boolean type fails:
```
>>> bool(r)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The second example works because comparison operations on `list` objects are clearly defined to return a boolean value:
```python
>>> [1, 2] < [3, 4]
True
```

**Comment by terryjreedy** [comment]
@chgnrdv Thank you for the explanation.  I suspected 'not a bug' but am not familiar enough with np to be sure without confirmation.

**Comment by Yhg1s** [comment]
Yes, this is not a bug in Python, and it's intentional behaviour in numpy.
