### ISSUE TITLE
pathlib: Where does "self._flavour" comes from? (3.11 to 3.12 migration)

### ISSUE THREAD

**Issue by buhtz** [python/cpython#104921]
This question is related to Python 3.12.

https://github.com/python/cpython/blob/278030a17d6889731d91a55e9f70cbec0b07dee8/Lib/pathlib.py#L319

This is the first occurrence of `self._flavour` in `pathlib.py`. I don't see where this object is set. I can't find the string `self._flavour =` somewhere in the repo. I'm confused.

Background:
I try to figuring out why `pathlib._Flavour.parse_parts()` (and the whole class) was removed from Python 3.11 to 3.12. I can not see this in the CHANGELOG. And I'm not skilled enough with git to find the related commit.

**Comment by hugovk** [comment]
Thank you for testing the beta!

`pathlib._Flavour` was removed in https://github.com/python/cpython/pull/31691.

The linked issues are gh-68320, gh-88302. From the latter:

> Following [bpo-39899](https://bugs.python.org/issue?@action=redirect&bpo=39899), [bpo-43757](https://bugs.python.org/issue?@action=redirect&bpo=43757) and [bpo-43012](https://bugs.python.org/issue?@action=redirect&bpo=43012), `pathlib._Flavour` and its subclasses are looking a bit pointless.
> 
> The implementations of `is_reserved()` and `make_uri()` (~`as_uri()`) can be readily moved to into `PurePosixPath` and `PureWindowsPath`, which removes some indirection. This follows the pattern of OS-specific stuff in `PosixPath` and `WindowsPath`.
> 
> The remaining methods, such as `splitroot()`, can be pulled into `Pure*Path` with an underscore prefix.
> 
> I'm generally a believer in composition over inheritance, but in this case `_Flavour` seems too small and too similar to `PurePath` to separate out into 3 extra classes.
> 
> There should be no impact on public APIs or performance.

I expect there was no CHANGELOG entry because the undescores indicate these are private and not part of the public API, and pyfakefs will need refactoring to use something else.

cc @barneygale 

---

PS I did `git log -S _Flavour Lib/pathlib.py` to find the most recent commit mentioning the class, including deletes.

**Comment by CAM-Gerlach** [comment]
Also, just to note, `_parse_parts` itself (likewise still a private method) was replaced with `_parse_path` in PR #102789 , to address issues #76846 and #85281 . Presumably, the intention is to properly subclass `Path` rather than relying on private internal-only members, though @barneygale is the expert and can likely advise you what's best for your use case much more specifically.

**Comment by buhtz** [comment]
Awesome! Great!
Thanks a lot for helping and explaining. I learned a lot.

From my point of view this Issue can be closed.

**Comment by barneygale** [comment]
For posterity, the motivation/explanation for the removal of the flavour classes can be found here: https://discuss.python.org/t/make-pathlib-extensible/3428/42
