### ISSUE TITLE
edge case when parsing complex numbers

### ISSUE THREAD

**Issue by mattip** [python/cpython#105027]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

Parsing `-1.0j` with no real part will assume the real part is `-0`, not +0. This is a change from Python2. Is it intentional? PyPy3 will assume `+0`. This is the root cause of [this PyPy issue](https://foss.heptapod.net/pypy/pypy/-/issues/3944)

```
$ python3.11
Python 3.11.3 (main, Apr  5 2023, 14:14:37) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> -1.0j
(-0-1j)
>>> 0-1.0j
-1j
>>> 
```

# Your environment
Debian-provided python3 all do this (python3.9, python3.10, python3.11).

- CPython versions tested on:
- Operating system and architecture:
Debian, CPython 3.9, 3.10, 3.11

**Comment by arigo** [comment]
Note that the CPython3 behavior almost makes sense: the expression `-1j` really means `-(1j)`, and if you do `a=1j; -a` then you get `-0-1j`.  This is different from doing the subtraction `0-1j`, which gives a result with a positive-zero real part.  It's the same difference that also occurs without complex number, between `-0.0` and `0-0.0`.

It only "almost" makes sense, because the detail that confuses matter is that the result of the expression `0-1j` is printed as `-1j`; but the result of the expression `-1j` is printed as `(-0-1j)`... (also, the result of the expression `(-0-1j)` is printed as `-1j`, because need the expression `(-0.0-1j)` to print `(-0-1j)`).

**Comment by mdickinson** [comment]
Yes, the Python 3 behaviour, and the change w.r.t. Python 2, is intentional.

`1j` is a complex number with real part `+0.0` and imaginary part `1.0`. The unary `-` negates both the real and imaginary part. In Python 2, there was a peculiar AST "optimization" that effectively absorbed the `-` into the literal.

@arigo: In `0 - 1j` we're subtracting the complex number `(0.0, 1.0)` from the complex number (after coercing the `int`) `(0.0, 0.0)`. The real part is therefore `0.0 - 0.0`, which under the usual IEEE 754 round-ties-to-even mode is `0.0`. So it's valid to drop the real part from the repr. In contrast, the real part of `-1j` is `-0.0`.

**Comment by mdickinson** [comment]
@arigo: Ah, sorry; I think I'm just repeating what you already said.

Yes indeed, `eval`-ing the repr `"-1j"` of the result of `0-1j` doesn't give back precisely the same result. That's pretty much unavoidable, I'm afraid, and has been discussed in multiple other tracker issues.

For some history on the Python 2 to Python 3 change, see https://github.com/python/cpython/issues/53257.

For issues related to @arigo's comments, see #70026, #61538, #66738 (almost certainly an incomplete list).

**Comment by mdickinson** [comment]
Also FTR: #84450, and @serhiy-storchaka's PR #19593.
