### ISSUE TITLE
Unexpected: `shutil.copyfile` tapping into previously opened file pointer

### ISSUE THREAD

**Issue by jamesbraza** [python/cpython#105001]
# Bug report

```python
import pathlib
import shutil
import tempfile

THIS_DIRECTORY = pathlib.PurePath(__file__).parent


with tempfile.NamedTemporaryFile(mode="w") as f:
    f.write("green eggs")

    # Now, let's copy the temp file's contents into a non-temp file

    # Unexpected: this file is empty
    shutil.copyfile(f.name, THIS_DIRECTORY / "copied_into1.txt")

    # This file is not empty after we reset the temp file's pointer,
    # despite not being related to shutil.copyfile
    f.seek(0)
    shutil.copyfile(f.name, THIS_DIRECTORY / "copied_into2.txt")
```

The bug took me a while to figure out.  Basically, `shutil.copyfile` is tapping into the open file pointer of the temp file, even though `shutil.copyfile` is not connected to this file pointer.

I would consider this unexpected behavior, as there's no connection within my Python script.  I believe the connection is being made at the OS level, but I am not sure this claim is correct.

# Your environment

- CPython versions tested on: 3.10.10
- Operating system and architecture: macOS Monterey v12.6

**Comment by ronaldoussoren** [comment]
This is not bug, what you're seeing it the result of the file buffer.  That is, after ``f.write(...)`` the data is not yet written to the file, but is the buffer associated with ``f``.  Data is flushed to the file when the buffer is full (by default the buffer is ``io.DEFAULT_BUFFER_SIZE`` bytes), when you call ``f.flush()``, or when you change the file position using ``f.seek``.

Adding ``f.flush()`` after the call to ``f.write()`` results in two complete copies of the file.

**Comment by jamesbraza** [comment]
Oh wow, that's interesting.  I didn't know that `f.write` used a buffer.  I can see what you're talking about with buffering is documented in [`open`](https://docs.python.org/3/library/functions.html?highlight=open#open).  Thank you for the great explanation and redux!

---

Thinking about this, the fact that `f`'s buffering/file pointer is also implicitly being used by `shutil.copyfile` is surprising/unexpected to me.

Do you think there's something Python can do for this bug to make it less surprising/unexpected?

**Comment by ronaldoussoren** [comment]
The buffering is not implicitly used by ``shutil.copyfile``. That function copies the bits that are in the file system, and until you flush the buffer not all data you wrote made it to the file system.

I/O buffering is needed both for performance because the overhead from system calls is significant when you'd perform a system call for every read or write unless you write in larger chunks.  That's something all commonly used I/O libraries do, not just in Python. 

BTW. Is the code pattern in your report something you use in your scripts?  If so, what it the use case for this pattern?  This combination of a ``NamedTemporaryFile`` and ``shutil.copyfile`` is something I'd have questions about in a code review.

**Comment by jamesbraza** [comment]
You've provided me even deeper insight, thank you!  I understand the first `shutil.copyfile` in the OP's repro was copying an empty file, because the buffer was not yet flushed. ✅

I guess then the code makes sense now (no longer surprising behavior).  Feel free to close this out then, I guess the resolution is user error on my part.

---

My pattern of using a tempfile paired with `shutil.copyfile` was to provide the semblance of in-place cleaning of a data file.  Basically: 1. read in data file line, 2. clean line, 3. write line to temp file, 4. after all lines, use `shutil.copyfile` to overwrite the original data file from the temp file.  I found that approach easier than actually dealing actual real in-place cleaning.

**Comment by ronaldoussoren** [comment]
For updating files I mostly use ``os.rename`` instead of ``shutil.copyfile`` (mostly using a custom contextmanager that creates the temporary file and cleans it up on errors).  The ``atomicfile`` package on PyPI claims to do something similar, although I've never used that package.  The advantage of renaming instead of copying it that this guarantees atomic updates (e.g, the file is completely replaced on success and untouched when an exception is raised).
