### ISSUE TITLE
Documentation of `base64.b64decode(s, altchars=None, validate=False)` should mention ValueError if non-ascii characters are present in input

### ISSUE THREAD

**Issue by sauc-odoo** [python/cpython#105193]
# Documentation

At the moment, it is as follows.

https://github.com/python/cpython/blob/c67121ac6bf8ee36d79de92ef68fc3fde178d2a3/Lib/base64.py#L65-L82

If we give non-ascii character as input in `base64decode` function it will raise a ValueError from - https://github.com/python/cpython/blob/c67121ac6bf8ee36d79de92ef68fc3fde178d2a3/Lib/base64.py#L39

So either the documentation should be updated to note that it may raise ValueError for non-ascii content, or `_bytes_from_decode_data` should be fixed to raise `binascii.Error`.

**Comment by gaogaotiantian** [comment]
Hmm, the docs stated that

> Decode the Base64 encoded [bytes-like object](https://docs.python.org/3/glossary.html#term-bytes-like-object) or ASCII string s and return the decoded [bytes](https://docs.python.org/3/library/stdtypes.html#bytes)

Raising `ValueError` when the input is not valid is very common in Python and is normally not documented. The `validate == False` part is for characters that are ASCII but not in Base64 alphabet, not for non-ASCII encoding.

**Comment by sauc-odoo** [comment]
In the docs, it is stated that
>May assert or raise a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) if the length of altchars is not 2.

and also
>A [binascii.Error](https://docs.python.org/3/library/binascii.html#binascii.Error) exception is raised if s is incorrectly padded.

So when s consist of non-ASCII characters, is it possible to mention the ValueError in documentation so that whenever a python developer encounters with `raise ValueError('string argument should contain only ASCII characters')` error from `b64decode` method it is easy for him to track whats going wrong.

In the docs, it is given that
>If validate is True, these non-alphabet characters in the input result in a binascii.Error.

So either ValueError can be converted into binascii.Error if it is possible or the ValueError can be stated in documentation.

**Comment by sauc-odoo** [comment]
> In the docs, it is stated that
> 
> > May assert or raise a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) if the length of altchars is not 2.
> 
> and also
> 
> > A [binascii.Error](https://docs.python.org/3/library/binascii.html#binascii.Error) exception is raised if s is incorrectly padded.
> 
> So when s consist of non-ASCII characters, is it possible to mention the ValueError in documentation so that whenever a python developer encounters with `raise ValueError('string argument should contain only ASCII characters')` error from `b64decode` method it is easy for him to track whats going wrong.
> 
> In the docs, it is given that
> 
> > If validate is True, these non-alphabet characters in the input result in a binascii.Error.
> 
> So either ValueError can be converted into binascii.Error if it is possible or the ValueError can be stated in documentation.

@gaogaotiantian Please reply to this comment.

**Comment by gaogaotiantian** [comment]
I probably accidentally deleted my reply.

Like I said, not all the potential exceptions that can be raised are documented for a function. In my opinion, there are two cases where the documentation for the exception helps:

1. It helps the users to better prepare for an unexpected exception. Either user does not think about the cases, or the exception itself is special. The `binascii.Error` for padding issue falls into this category.
2. It helps the users to understand the problem when an exception is raised - when the exception itself is not clear enough to explain what happened.

I don't think this case falls into these two categories. The docs already stated clearly that the input string should be ASCII - you should expect exceptions (`ValueError` is the most common one) if you do not follow the rule. The explanation for the exception is very clear (`string argument should contain only ASCII characters`).

I strongly disagree with the idea of using `binascii.Error` for this, because in this function, that has a very specific meaning - non base64 alphabets (this is different than non ascii encoding).

I don't believe the documentation you proposed is necessary, TBH I don't think the `ValueError` explanation for `altchars` is necessary either.

You can still pursue the doc change and get a second opinion from core devs, but from my point of view, I don't think this change is making the docs better. And if this is accepted, there would be a lot of the docs that need to be changed for expected exceptions.

**Comment by sauc-odoo** [comment]
Thank you @gaogaotiantian  for your input. I appreciate your perspective on the matter. I understand that you believe the current documentation is sufficient and provides clear instructions and explanations for the potential exceptions. You also express concern about the use of `binascii.Error` for non-ASCII characters and question the necessity of the proposed changes. I will take your feedback into consideration.
