### ISSUE TITLE
New Tokenizer API raise SyntaxError on 3.12 where it emits tokens on 3.11

### ISSUE THREAD

**Issue by Carreau** [python/cpython#105238]
It looks like the new 3.12 tokenizer is quite more strict in raising SyntaxError where in 3.11 and before it would return tokens and ENDMARKER. 

This is a bit problematic as it can be common to try to at least tokenize unfinished or non valid Python, for example in IPython. Typically see the errors in https://github.com/ipython/ipython/pull/14091. 

We use incomplete tokenizing for a bunch of things:

In the REPL:

- is what the user incomplete but valid ? 
   - Yes, we insert a new line and have the user keep typing. 
   - No, continue with compile() and show user the error. 
- Is the tokenisation valid, but does not compile ?
   - Yes, 
   - Could it be bash like `ls something` -> Yes, detect it and do the right things.
- Detect invalid unicode better.

Most of those are now SyntaxError in the new tokenizer. I'm actually not even sure the old tokenizer used to raise SyntaxError at all, it seem it was only raise `tokenize.TokenError` before.

```
fails_in312 = [
    "a = [1,\n2,",
    "1 \n\n1 \ ",
    "x =(1+",
    "import os, \\",
    'a="""',
    "\xc3\xa9\n",
]


for f in fails_in312:
    from tokenize import generate_tokens

    list(generate_tokens(iter(f).__next__)) # ok on 3.11 raises SyntaxError on 3.12
...
```

(a bit hand waved as I was not yet able to get 3.12 on my local machine, but all above example should be from IPython failing CI on 3.12).

I'm assuming those changes are on purpose, due to the new parser for f-strings. I was just noting on social media that I don't know if/how I'm going to handle those breakage, and even wether it's possible to do it only on IPython side. I was still advised to open an issue anyway as it is a change of API that breaks downstream, so here is it.

Still it would be great for the tokenizer to only tokenize, and the parser the SyntaxError as there are valid reasons to tokenize incomplete/invalid python.

# Your environment

- CPython versions tested on: 3.12-dev from GitHub action.
- Operating system and architecture: linux.

Thanks

**Comment by ambv** [comment]
### Why the tokenizer had to change
The change in behavior results from the removal of the custom Python-based tokenizer that Python used to ship with. This custom tokenizer used to parse valid Python code closely enough to what the interpreter itself was doing in C, but it differed when it came to error handling. We even had a third Python-based tokenizer in lib2to3.

Now we're down to a single tokenizer, which is a big win for compatibility, as the differences between them were a source of issues.

The consolidation of tokenizers was planned for a while and was finally triggered by the needs of PEP 701. The Python-based tokenizer was built with regular expressions, making support for the new f-string syntax like nested quotes very tricky to get right. In all likelihood, we would end up with tokenizers that don't behave the same. Using the one that the interpreter itself uses solves those problems, while being faster at the same time.

Note that none of the documented and tested behavior of `tokenize.py` changed. You were relying on undefined behavior around invalid input, therefore no backward compatibility considerations apply here. We do acknowledge that this is a breaking change for you and that's unfortunate, but we cannot treat every observable behavior as a future compatibility contract.

### Can we make `tokenize.py` work like it did before?
In short, no. 

Changes to the C tokenizer to account for invalid input would slow down parsing of valid Python code and are therefore a controversial proposition. More importantly, "invalid Python code" is a vast superset of what the tokenizer is meant to support, so we're afraid that agreeing to some concessions here would lead to expectations of more concessions in the future. As none of the tokenizers in Python were ever meant to be error-recoverable, this is not a change we are able to make now.

Let's be explicit about the kind of behavior you would like the tokenizer to preserve.

```python
>>> import tokenize, pprint, io
>>> def tokens(s): return pprint.pprint(list(tokenize.generate_tokens(iter(s).__next__)))
```

Python 3.11:
```
>>> tokens("a = [1,\n2,")
[TokenInfo(type=1 (NAME), string='a', start=(1, 0), end=(1, 1), line='a'),
 TokenInfo(type=4 (NEWLINE), string='', start=(1, 1), end=(1, 2), line=''),
 TokenInfo(type=0 (ENDMARKER), string='', start=(2, 0), end=(2, 0), line='')]
```

Look at this result. It is bizarre. It doesn't follow any documented logic. It doesn't even acknowledge the assignment, let alone the unmatched square bracket.

Better yet, if you didn't pass the tokens to the generator character by character but rather line by line, as is more often the case, you'd get an exception anyway:

Python 3.11:
```
>>> def tokens_by_line(s): return pprint.pprint(list(tokenize.generate_tokens(io.StringIO(s).readline)))
...
>>> tokens_by_line("a = [1,\n2,")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in tokens_by_line
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tokenize.py", line 525, in _tokenize
    raise TokenError("EOF in multi-line statement", (lnum, 0))
tokenize.TokenError: ('EOF in multi-line statement', (3, 0))
```

Documenting and preserving this behavior seems like a really bad idea. It's not a result of conscious design, but rather of implementational coincidence. 

### What you can do now
There are two levels of support that IPython needs to think about:
1. Does IPython run on Python 3.12?
2. Does IPython support 3.12+ syntax?

Long-term of course you want both (1.) and (2.). To get there, you will probably want to adopt a third-party tokenizer like the one shipping with [libcst](https://http://pypi.org/p/libcst). I admit it will be some work and taking on a new dependency is never to be taken lightly.

However, in the short term what you really need is (1.) as most users won't be writing 3.12-only code from Day 1 when Python 3.12.0 is available, and even if they do only care about Python 3.12, they can easily avoid the new syntax temporarily until it is supported by their tools.

To get (1.), the simplest solution would be to vendor-in Python 3.11's `tokenize.py` and use that. This is a much smaller change that will unblock users to launch IPython on Python 3.12.

**Comment by Carreau** [comment]
I've open the issue as several people asked me to do so on twitter. Thanks for taking the time to respond. 

I as thought it is too complex of a change, and I don't expect CPython to do it. Thus closing to now keep the discussion too long, at least this will be a reference point for reference. 

Thanks for all your hard work on 3.12, I'm looking forward to try it !

**Comment by asmeurer** [comment]
Note that this also breaks SymPy's use of `tokenize` in my tests. 

For context, I maintain three separate projects that make use of `tokenize` (including SymPy), and this change would break all three of them. This sort of thing has happened in the past as well. I would appreciate if the tokenizer were treated as public API (because it is), and not broken so casually.

**Comment by CAM-Gerlach** [comment]
Thanks @Carreau for fully documenting this here—it's really helpful to at least have a complete and easy to follow description of the problem and the explanation all in one linkable place. And it's definitely something I'll be pointing my fellow Spyder core devs and other downstream maintainers to as a heads up, as we'll want to stay on top of and potentially try to help with if possible, since it will be a major blocker to 3.12 adoption for the scientific Python ecosystem. 

And for the record, at least one CPython core dev heavily uses Python interactively (via Spyder, and sometimes the interpreter/IPython/QtConsole directly) :wink:  Unfortunately, I also have some of the least subject matter expertise in this particular area, so I'm not sure I can be of much help in this case.

**Comment by CAM-Gerlach** [comment]
Thanks @Carreau for fully documenting this here—it's really helpful to at least have a complete and easy to follow description of the problem and the explanation all in one linkable place. And it's definitely something I'll be pointing my fellow Spyder core devs and other downstream maintainers to as a heads up, as we'll want to stay on top of and potentially try to help with if possible, since it will be a major blocker to 3.12 adoption for the scientific Python ecosystem. 

And for the record, at least one CPython core dev heavily uses Python interactively (via Spyder, and sometimes the interpreter/IPython/QtConsole directly) :wink:  Unfortunately, I also have some of the least subject matter expertise in this particular area, so I'm not sure I can be of much help in this case.

(Also, setting the correct close state)

**Comment by jni** [comment]
> I've open the issue as several people asked me to do so on twitter.

I stand by my proposal, as the discussion above is fascinating to read and provides (to my naive eyeballs) several useful avenues for exploration. 😃 Thanks @ambv, @pablogsal, and @CAM-Gerlach for your responses!
