### ISSUE TITLE
Remove superinstructions

### ISSUE THREAD

**Issue by markshannon** [python/cpython#105229]
Superinstructions offer a small speedup, but their existence complicates things; mainly instrumentation, and specialization.
The tier2 optimizer is likely to be simpler without superinstructions.

[This experiment](https://github.com/faster-cpython/benchmarking-public/tree/main/results/bm-20230526-3.13.0a0-0087a08) shows that combining the most common superinstructions into single instructions can outperform superinstructions, rendering superinstructions pointless.

We have already removed almost all superinstructions in specialization. We should remove them altogether.

### Linked PRs
* gh-105230
* gh-105326
* gh-105703

**Comment by markshannon** [comment]
https://github.com/faster-cpython/ideas/issues/585

**Comment by corona10** [comment]
Question: One good thing of super instruction is that we can hide the optimization detail to end user.
But from this change, if we need to optmizing opcodes with concatnation. Do we have to introduce the new opcode or still prefer to experiment it as the super instruction?

**Comment by markshannon** [comment]
What do you mean by the "end user"? 
Python programmers really shouldn't be concerned about bytecode, except in a "I wonder how this works" kind of way.

`LOAD_FAST_LOAD_FAST` is lot easier to understand than instructions like `RETURN_GENERATOR` or `CLEANUP_THROW`

**Comment by corona10** [comment]
> What do you mean by the "end user"?

Ah I meant Python programmers. Thanks.

> Python programmers really shouldn't be concerned about bytecode, except in a "I wonder how this works" kind of way.

Okay, Looks like it was just my thought. I loved super instruction from the view of hidden optimization implementation detail.

So still questions left if we decide to remove the current super-instruction mechanism.

1. What are the criteria of the new opcode that can be added? Can we add any super instructions that can be faster than the current instruction since it doesn't require runtime overhead?
2. What if the super instruction interferes with general bytecode reordering optimization?
(I am not sure which case will be)

Thank you for answering for all :)

**Comment by corona10** [comment]
> What if the super instruction interferes with general bytecode reordering optimization?
(I am not sure which case will be)

While I am reading the [code](https://github.com/python/cpython/pull/105230), it looks like happening at the last moment of optimization. So it will not happen?

**Comment by markshannon** [comment]
Forming superinstructions should done after all other optimizations, so won't interfere those.
It could be done in the assembler.

**Comment by corona10** [comment]
> For the reasons given above, I want to remove all superinstructions.

I am asking about the new single opcodes(in #105230,  LOAD_FAST_LOAD_FAST / STORE_FAST_LOAD_FAST  / STORE_FAST_LOAD_FAST ) that will alter the existing super instruction. :)
Sorry to make you confused!
I am asking about a situation when someone needs to add a new single opcode concatenated by multiple opcodes.
Because it doesn't require a runtime cost, so the execution of frequency is less important than before.

**Comment by terryjreedy** [comment]
> [This experiment](https://github.com/faster-cpython/benchmarking/tree/main/results/bm-20230526-3.13.0a0-0087a08) shows

Link goes nowhere for me.

**Comment by markshannon** [comment]
Fixed the link

**Comment by gvanrossum** [comment]
@markshannon Should I just remove the super-instruction support from the cases generator? That would simplify a lot of things! (There are a bunch of things that are factored somewhat awkwardly to share common code between super and macro while also honoring their differences.)

**Comment by gvanrossum** [comment]
@carljm FYI. I forgot that Cinder now uses the generator to override some opcodes and add others. Hopefully you're not using super-instructions, or we'd have to roll back gh-105703.

**Comment by carljm** [comment]
> @carljm FYI. I forgot that Cinder now uses the generator to override some opcodes and add others. Hopefully you're not using super-instructions, or we'd have to roll back [gh-105703](https://github.com/python/cpython/pull/105703).

Nope, we don't need the super-instruction support. Thanks for thinking of us! I am generally watching changes in these areas and will pipe up if I see anything happening that would be a problem for us.
