### ISSUE TITLE
Unpack `.args` for Structural Pattern Matching against Exceptions

### ISSUE THREAD

**Issue by mgdotdev** [python/cpython#105393]
# Feature or enhancement

`match_class` in `ceval.c` should default to match the positional arguments in the `.args` attribute for Exceptions

# Pitch

By default, the BaseException object in Python defines an args attribute which is assigned the tuple of the arguments given to Exception objects at instantiation. 

```python
>>> err = ValueError("error msg")
>>> err.args
('error msg', )
```

Matching this object in structural pattern matching (SPM) requires knowledge of this implementation detail and results in the match statement being overly verbose for developers who prefer `return`-ing errors instead of `raise`-ing them.

```python
def fn(x: int) -> int|ValueError:
    if not x:
        return ValueError("x is falsy", 1)
    return x

match fn(0):
    case ValueError(args=(str(msg), int(code))):
        print(f"Error {code}: {msg}")
```

the `match_class` function in `ceval.c` allows for passing positional arguments to the match for classes. The function uses a `__match_args__` class attribute to compare positional values against attributes of the instance. These attributes are packed into a `PyList` object, and the values are then compared against for SPM.

The proposal here is to, for Exception objects, unpack the `.args` attribute by default into the list of values used for SPM. The result would be a cleaner syntax more aligned with how exception objects are constructed.

```python
match fn(0):
    case ValueError(str(msg), int(code)):
        print(f"Error {code}: {msg}")
```

A proof-of-concept implementation can be found here:
https://github.com/1mikegrn/cpython

# Previous discussion

https://discuss.python.org/t/add-structural-pattern-matching-to-exception-objects/27389/22
https://www.reddit.com/r/Python/comments/13zq790/add_match_args_to_baseexception/

Originally this idea was framed as adding a `__match_args__ = ("args", )` class attribute to the BaseException class. The downside there is that you are then required to pass a tuple of args to the `case`. After further investigation and discussion, changing `match_class` to unpack the `args` attribute for Exception objects seems the better approach.

The purpose of this change is to better support the notion of errors as values in Python. Keeping errors out of the global error state and in the local stack provides for more granular control flow and explicitness in error handling. Static type checkers like mypy can validate type safety more effectively for errors that are returned instead of raised. It's an approach that has been seen in multiple other languages as a first-class citizen, and major projects in languages with `try/catch` functionality have been known to emulate the approach so as to derive its benefits.

**Comment by 1mikegrn** [comment]
Presumably static type checkers would need a corresponding update to similarly check by default the types of the `.args` attr on exception objects, since there would be no `__match_args__` to read

**Comment by sobolevn** [comment]
But, `ValueError` accepts `*args`, so we can do something like this:

```python
>>> raise ValueError('you', 'can', 'put', 'here whatever', object())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: ('you', 'can', 'put', 'here whatever', <object object at 0x100f48600>)
```

**Comment by 1mikegrn** [comment]
presumably you'd also want corresponding type support (not unprecedented, basically treat it to be the same as `tuple[str, int]`)

```python
def fn(x: int) -> int|ValueError[str, int]:
    if not x:
        return ValueError("ValueError", 30)
    return x

match fn(0):
    case ValueError(str(msg), int(code)):
        print(f"Error {code}: {msg}")
```

**Comment by brandtbucher** [comment]
Thanks for taking the time to research and implement this!

While this does seem sort of "cool", I'm not sure this is an idea worth pursuing right now. To me, it feels too much like a special case (one that will probably slow down *all* class matches by a tiny bit). Plus, as you note, it's already possible to match on the value of `args` using the class pattern syntax.

We also haven't pushed pattern matching on exceptions in general, since that's completely different from the built-in exception handling model and encourages people to use the payload of an exception for error handling rather than the class hierarchy. I'm pretty sure that as soon as we introduce this feature, people will use it to start matching on the exact text of error strings, which is not at all what we want.

However, a more general solution for "view patterns" was discussed at the [Language Summit](https://pyfound.blogspot.com/2023/05/the-python-language-summit-2023-pattern.html) this year. If that idea moves forward, it *may* make sense to add `__match__` method to classes (like `BaseException`) that collect their constructor arguments into a single attribute. But we can cross that bridge when we get there.
