### ISSUE TITLE
configparser doesn't support multiple entries with the same name

### ISSUE THREAD

**Issue by Die4Ever** [python/cpython#105307]
# Feature or enhancement

configparser doesn't support multiple entries with the same name (acting like an array), which meant I had to use regex instead.

# Pitch

For example, the game Deus Ex uses ini files like this

```
[Core.System]
Suppress=DevLoad
Suppress=DevSave
Suppress=DevNetTraffic
Suppress=DevGarbage
Suppress=DevKill
Suppress=DevReplace
Suppress=DevSound
Suppress=DevCompile
Suppress=DevBind
Suppress=DevBsp
Paths=..\DXRando\System\*.u
Paths=..\DXRando\Maps\*.dx
Paths=..\Music\*.umx
Paths=..\Sounds\*.uax
Paths=..\Textures\*.utx
Paths=..\Maps\*.dx
Paths=..\System\*.u
```

https://github.com/Die4Ever/deus-ex-randomizer/blob/develop/installer/Configs/DXRandoDefault.ini#L42-L58

**Comment by terryjreedy** [comment]
Closing because : 
1. No prior discussion.  The new feature template suggests: " New features to Python should first be discussed elsewhere before creating issues on GitHub,  for example in the "ideas" category (https://discuss.python.org/c/ideas/6) of discuss.python.org.
2. No specification.  There is a statement, but no specific proposal to implement.
3. I believe the implied proposal is outside the current scope of the module, to provide "a basic configuration language which provides a structure similar to what’s found in Microsoft Windows INI files. "  https://docs.python.org/3/library/configparser.html#module-configparser  The doc goes on to note that the extended syntax used in Windows Registry is not supported and to list alternatives that support structured data.
