### ISSUE TITLE
__getitem__ of AsyncMock returns MagicMock instead of AsyncMock

### ISSUE THREAD

**Issue by darrikonn** [python/cpython#105317]
## Actual
`info.context.data_loader["organization"]` yields `MagicMock`

## Expected
`info.context.data_loader["organization"]` yields `AsyncMock`

## Test case

```ipython
ipdb> info
<AsyncMock id='4411944080'>

ipdb> info.context
<AsyncMock name='mock.context' id='4593499664'>

ipdb> info.context.data_loader
<AsyncMock name='mock.context.data_loader' id='4591705360'>

ipdb> info.context.data_loader["organization"]
<MagicMock name='mock.context.data_loader.__getitem__()' id='4588173008'>
```

**Comment by tirkarthi** [comment]
This is an intentional behavior where child mock is MagicMock/Mock if the method accessed is synchronous in this case `__getitem__`

Relevant commit : 3667e1ee6c90e6d3b6a745cd590ece87118f81ad

https://github.com/python/cpython/blob/d3af83b9342457d8b24476baeb799f7506ff04f3/Lib/unittest/mock.py#L1074-L1080

**Comment by darrikonn** [comment]
Mmm interesting, thanks for clarifying.
I'll need to use a custom AsyncMock class for my use-case.

**Comment by tfglasswing** [comment]
Same issue/confusion here. Is there a recursive AsyncMock?
