### ISSUE TITLE
Calling function with lru_cache passing args as dict creates different entries in cache

### ISSUE THREAD

**Issue by george-gca** [python/cpython#105618]
# Bug report

When creating a function with `lru_cache`, calling it passing the params with the same values as `**params` creates different cache entries.

```python3
from functools import lru_cache
@lru_cache
def fn(a, b):
    return a + b

print(fn(1, 1))
# 2
print(fn.cache_info())
# CacheInfo(hits=0, misses=1, maxsize=128, currsize=1)

params = {'b': 1}
print(fn(1, **params))
# 2
print(fn.cache_info())
# CacheInfo(hits=0, misses=2, maxsize=128, currsize=2)

params = {'a': 1, 'b': 1}
print(fn(**params))
# 2
print(fn.cache_info())
# CacheInfo(hits=0, misses=3, maxsize=128, currsize=3)
```

But it works fine when passing params as `*params`:

```python3
from functools import lru_cache
@lru_cache
def fn(a, b):
    return a + b

print(fn(1, 1))
# 2
print(fn.cache_info())
# CacheInfo(hits=2, misses=1, maxsize=128, currsize=1)

params = (1,)
print(fn(1, *params))
# 2
print(fn.cache_info())
# CacheInfo(hits=2, misses=1, maxsize=128, currsize=1)

params = (1, 1)
print(fn(*params))
# 2
print(fn.cache_info())
# CacheInfo(hits=2, misses=1, maxsize=128, currsize=1)
```

# Your environment

Python 3.11.2
Ubuntu Desktop 23.04

**Comment by sobolevn** [comment]
Hi, @george-gca!

This works as intended, because `1, 1` and `1, b=1` are generally different sets of arguments in CPython.
`lru_cache` does not inrospect the signature to be sure that `1, 1` and `1, b=1` are compatible.

Docs say:

>  It can save time when an expensive or I/O bound function is periodically called with the **same arguments**.

Moreover, we also cover this use-case in the docs:

> Distinct argument patterns may be considered to be distinct calls with separate cache entries. For example, f(a=1, b=2) and f(b=2, a=1) differ in their keyword argument order and may have two separate cache entries.

So, if you want to have a working cache, use the same set of arguments.

If you have further support questions, please, open them here: https://discuss.python.org/c/users/7

Cheers!
