### ISSUE TITLE
Allowing non ASCIIs in HTTP headers

### ISSUE THREAD

**Issue by ghost** [python/cpython#105981]
I ran into a bug while using OpenCV, Flask, and Japanese fonts through Pillow. Here's the pertinent section of the traceback:

```plain
\AppData\Local\Programs\Python\Python311\Lib\http\server.py", line 513, in send_response_only
    (self.protocol_version, code, message)).encode(
                                            ^^^^^^^
UnicodeEncodeError: 'latin-1' codec can't encode character '\u3007' in position 120: ordinal not in range(256)
```

The problem can be solved by changing `latin-1` in two spots to `utf-8`.

### Linked PRs
* gh-105956

**Comment by sunmy2019** [comment]
Why should HTTP headers use `utf-8` encoding? Are there reliable sources?

Is it a common practice to send non-ASCII in HTTP headers?

**Comment by fkkjohn** [comment]
I can happily accept that simply making the error go away is not always the best course of action. If things suddenly start breaking all over the internet, that'd be bad. So I'm going to argue in a progressive manner since maintaining a status-quo which no longer serves a good purpose is a very conservative mindset, and that's not me.

All of the standards I've seen quoted on this topic are about 30 years old. They come from a time before open source software, before a world wide internet, and are essentially the vestiges of English language hegemony on the internet.

First of all, UTF-8 is identical to ASCII as far as the ASCII character set goes. UTF-8 simply invites everyone else to the party -- it's more inclusive. From the wikipedia entry on UTF-8, "It was designed for backward compatibility with ASCII: the first 128 characters of Unicode, which correspond one-to-one with ASCII, are encoded using a single byte with the same binary value as ASCII, so that valid ASCII text is valid UTF-8-encoded Unicode as well." Using ASCII or UTF-8 would be indistinguishable until you try to read something outside of ASCII, at which point you get UnicodeEncodingErrors or working UTF-8 Unicode.

HTML bodies all use UTF-8 as the default encoding, as seen on line 485 of the same http/server.py file being discussed now. What is the purpose of limiting the headers to ASCII? If it's byte size, UTF-8 uses the same number and exact bytes as ASCII for all of the ASCII characters. Where will the problem arise? Could someone design an exploit using non-ASCII characters that are now available to them due to the UTF-8 character set? Perhaps, but that will only affect systems that refuse to modernize. Just like every other exploit.

Let me make this shorter, I could go for longer than I have. 

I don't have any great reasons why it needs to be UTF-8 other than it works for me while I'm running a local webserver and dealing with Japanese character encodings. Latin-1 caused me problems because it is an ethnocentric system made only to suit the purposes of English speakers. I've moved beyond that, and the internet has as well. Let me share some links I found that are on the subject, and you can decide what you want to do, but I vote for moving forward and changing the standard. Most of the standards we're considering right now were written descriptively concerning common practices. For once I suggest prescriptive yet forward thinking action. Let's switch to UTF-8 for everything. Anyway, here are the links that seem relevant. They may not necessarily agree with me, and that's fine. One day, everything will be UTF-8. I just wish it would be a little sooner than later.

I found a stackoverflow discussion about this just now:
https://stackoverflow.com/questions/4400678/what-character-encoding-should-i-use-for-a-http-header
There are a few conflicting opinions and interpretations of standards. From my understanding, most of python and it's libraries default to utf-8, and for good reason. It's better than latin-1/US-ASCII/ISO- 8859-1.


Here's another person fixing problems by using utf-8 instead of being flummoxed by encodings from the 90's.
https://support.mozilla.org/de/questions/1239476 

More confusion as people attempt to use UTF-8 but run into backward standards:
https://stackoverflow.com/questions/5788088/getting-latin1-instead-of-utf-8-with-cgiapplication

Have a great day folks. My program is working because I changed my local file, so I'm happy either way, but I hope my effort to help has been helpful in some way.

**Comment by kwsp** [comment]
Relevant discussion: https://github.com/python/cpython/issues/105505

**Comment by davidism** [comment]
This isn't correct. HTTP headers should not contain UTF-8 encoded bytes, they must only contain Latin-1, with other characters encoded using whatever scheme the particular header specifies. For example, dict-like headers typically use a format like `Header: key1*=UTF-8''%ab...`, where the `*=` indicates that the value is encoded, and only `UTF-8''` prefix is allowed. Preferably, headers should only contain ASCII, with the same encoding scheme applied for Latin-1 characters as well. HTTP servers and clients will not behave correctly if UTF-8 bytes are sent directly.

**Comment by fkkjohn** [comment]
Which part isn't correct? It has already been accepted that HTTP headers by standard definition should not contain non-latin-1 characters. The conversation is moving towards considering a new standard. Your claim that clients will not behave correctly if UTF-8 bytes are sent directly doesn't seem to be backed up by evidence. At least in my experience doing so and then using the code with Firefox and your own Flask, shows otherwise. Neither piece of software had trouble with UTF-8 headers, and that includes both server and client. Does this mean everything will work without breaking? Of course not. There are a lot of clients and servers out there (some better than others), and even Y2K broke a couple of programs, but making the claim doesn't make it true (thus the Y2K reference).

Isn't it nice when repositories don't close down issues and block issue submitters within 5 minutes and these things can be discussed?

**Comment by davidism** [comment]
> The conversation is moving towards considering a new standard.

Which standard? I don't see anything in https://httpwg.org/specs/, or the WSGI or ASGI specs that would support this.

**Comment by fkkjohn** [comment]
Are you stalking me because I called out your repository yesterday for removing issues as a method of improving the image of your software? I didn't have anything to report you guys for yesterday as burying issues isn't against any github rules, but internet stalking IS against the github rules. Contribute in a specific manner or kindly move along.

**Comment by fkkjohn** [comment]
While browsing internet standards from your link, I came across one you might be able to use for Flask. https://datatracker.ietf.org/doc/rfc7234/

It's all about caching. Since Flask has a bug that causes it to cache when everything is telling it not to, maybe you should consider looking at the issues being reported, and when people invite you to fix it, take them up on the offer of help.
https://github.com/pallets/flask/issues/4874 (you ghosted the guy and closed his issue when he asked for guidance on how to fix your bugs that you refuse to admit exist)

**Comment by methane** [comment]
WSGI spec uses latin-1 for encoding/decoding fields.
https://peps.python.org/pep-0333/#unicode-issues

Changing this server may affects some WSGI servers based on this HTTP server.

**Comment by fkkjohn** [comment]
> WSGI spec uses latin-1 for encoding/decoding fields. https://peps.python.org/pep-0333/#unicode-issues
> 
> Changing this server may affects some WSGI servers based on this HTTP server.

That's a valid point, but ultimately just another example of code that needs to be updated, in my opinion. Producing undefined results is a result of bad coding. This could result in exploits. All anyone has to do is send some unicode to disrupt the operations of servers? Sounds like that needs to be handled better... perhaps by properly supporting unicode to begin with?

**Comment by methane** [comment]
> Producing undefined results is a result of bad coding.

What is undefined here?

> This could result in exploits. All anyone has to do is send some unicode to disrupt the operations of servers?

As far as my understanding, this UnicodeError is occurred by sending *response*, not receiving request.
If we use UTF-8 for decode/encode fields, anyone can cause UnicodeDecodeError by sending invalid UTF-8.
On the other hand, latin-1 is byte transparent. Decode always success. And you can send UTF-8 response field even in server uses latin1 to encode fields:

```py
>>> 'こんにちは'.encode('utf-8').decode('latin1')
'ã\x81\x93ã\x82\x93ã\x81«ã\x81¡ã\x81¯'
>>> _.encode('latin1').decode('utf8')
'こんにちは'
```

> Sounds like that needs to be handled better... perhaps by properly supporting unicode to begin with?

UTF-8 with surrogateescape is what we use in filesystem encoding. It may be better than latin1.
But transition is very hard.

Personally, I prefer using just bytes, rather than latin-1 or UTF-8/surrogateescape.

**Comment by fkkjohn** [comment]
> > Producing undefined results is a result of bad coding.
> 
> What is undefined here?

The very first paragraph of the link you posted says, 

"HTTP does not directly support Unicode, and neither does this interface. All encoding/decoding must be handled by the application; _all strings passed **to** or **from** the server_ must be standard Python byte strings, not Unicode objects. **The result of using a Unicode object where a string object is required, is undefined**."


> 
> > This could result in exploits. All anyone has to do is send some unicode to disrupt the operations of servers?

Undefined behaviors can result in a variety of overflows and unexpected behavior. There are plenty of exploits that use undefined behavior to run arbitrary code. Personally I do not think this is a reason to avoid unicode, rather it is a very good reason to support it, or at the very very least, handle it.

> 
> As far as my understanding, this UnicodeError is occurred by sending _response_, not receiving request. If we use UTF-8 for decode/encode fields, anyone can cause UnicodeDecodeError by sending invalid UTF-8. On the other hand, latin-1 is byte transparent. Decode always success. And you can send UTF-8 response field even in server uses latin1 to encode fields:
> 
> ```python
> >>> 'こんにちは'.encode('utf-8').decode('latin1')
> 'ã\x81\x93ã\x82\x93ã\x81«ã\x81¡ã\x81¯'
> >>> _.encode('latin1').decode('utf8')
> 'こんにちは'
> ```

The error in the inital bug report is a UnicodeEncodeError. Currently, anyone can cause a UnicodeEncodeError even by sending _properly formatted_ UTF-8. Forget about improperly formatted UTF-8, HTTP doesn't support unicode at all. That's my proposed change. I understand it would require a change of standard and the standard libraries, but that's what progress requires. No one has offered a good reason why unicode would be impossible or worse. The only real argument is essentially "That's not what this 30 year old document says to do." (in reference to the established standards.)

> 
> > Sounds like that needs to be handled better... perhaps by properly supporting unicode to begin with?
> 
> UTF-8 with surrogateescape is what we use in filesystem encoding. It may be better than latin1. But transition is very hard.
> 
> Personally, I prefer using just bytes, rather than latin-1 or UTF-8/surrogateescape.

I agree that bytes are better. That's also why I feel UTF-8 would be a fine system to improve this latin-1 only system. It is byte for byte identical with latin-1 for the length of the latin-1 character set. Then it expands as you move beyond the single byte codes. That's my understanding.

Anyway, I don't expect anyone to do anything at this point, and I don't have time to teach myself everything I'd need to know to do it alone. For now I'm hoping the discussion gets people used to the idea, so that when we can't kick the can down the road any more, people won't be as resistant to the changes that need to be made. As I've said, I simply made the change in the file, and my code started working with no unexpected side effects. I have since abandoned Flask because its garbage maintained by people who refuse to fix bugs, so even my fix no longer affects me, and I seriously doubt I'll be running a local HTTP server again any time soon.

**Comment by fkkjohn** [comment]
You're absolutely right. We should not update those old standards, we should blindly adhere to them until the heat death of the universe.

**Comment by ericvsmith** [comment]
I don't think anyone is opposed to updating the standards. But Python isn't the relevant standards body, which is who you can work with to modernize things. I'm not sure if it's IETF or another organization, as I'm not heavily involved in that area.
