### ISSUE TITLE
pathlib.Path: Truncate file extension if Path is PosixPath

### ISSUE THREAD

**Issue by PedanticHacker** [python/cpython#106020]
# Feature or enhancement

For `pathlib.Path`, make it truncate the file extension if `Path` is a `PosixPath`.

# Pitch

Say we create this path on Windows:

```py
from pathlib import Path
my_path = Path("some/path/file.exe")
```

On a Windows CLI, we get this:

```
>>> my_path
WindowsPath('some/path/file.exe')
>>> str(my_path)
'some\\path\\file.exe'
```

But if the OS, on which you execute this same code, is not Windows, then `my_path` is of type `PosixPath`. The issue is that `PosixPath` does not truncate the `.exe` in our example path. As we know, POSIX-compliant OSes do not use file extensions to determine the file type (with the small exception of archive files, like `*.tar.gz`, `*.zip`, `*.rar`, etc., for which a POSIX-compliant OS does rely on the file extension to successfully distinguish between the different archive file types).

I think it would be a huge boon if `PosixPath` is more proactive in this regard.

**Comment by eryksun** [comment]
"file.exe" is a valid filename, so there is nothing at all that `pathlib.PosixPath` could do to be "more proactive in this regard".

In regard to Windows, if the path of an executable in a command line has no extension, WinAPI `CreateProcessW()` looks for the exact name and also the name plus ".exe". For example:

```pycon
>>> p = pathlib.Path(sys.executable).with_suffix('')
>>> p
WindowsPath('C:/Program Files/Python311/python')
>>> p.exists()
False
>>> subprocess.call([p, '-V'])
Python 3.11.2
0
```

In principle, you should also be able to resolve the extension using [`shutil.which()`](https://docs.python.org/3.12/library/shutil.html#shutil.which), which tries appending extensions from the `PATHEXT` environment variable. Unfortunately it's not implemented properly prior to 3.12, and the new behavior in 3.12 won't be backported to previous versions.

Python 3.12:

```pycon
>>> p = pathlib.Path(sys.executable).with_suffix('')
>>> shutil.which(p)
'C:\\Program Files\\Python312\\python.EXE'
```

Python 3.11:

```pycon
>>> p = pathlib.Path(sys.executable).with_suffix('')
>>> shutil.which(p) is None
True
```

**Comment by barneygale** [comment]
If POSIX should ignore file extensions, what business does `PosixPath` have handling file extensions specially on POSIX, much less truncating them?

**Comment by ferdnyc** [comment]
> As we know, POSIX-compliant OSes do not use file extensions to determine the file type (with the small exception of archive files, like `*.tar.gz`, `*.zip`, `*.rar`, etc., for which a POSIX-compliant OS does rely on the file extension to successfully distinguish between the different archive file types).

This request seems to be confusing "does not use file extensions to determine file type" with "does not consider the file extension part of the filename". The former is _somewhat_ true. (Though not **entirely** true, in more ways than just the compressed-archive case mentioned.) The latter could not be farther from the truth.

While it's possible to save a shell script as either `myscript.sh` or `myscript`, and execute it as a shell command either way by simply adding the execute bit (`chmod a+x myscript.sh` or `chmod a+x myscript`) due to the `#!/bin/sh` (or equivalent) shebang on the first line of the file, it is _**not**_ possible to save the script as `myscript.sh` and execute it as `myscript`. If the file is named `myscript.sh`, you have to **call** it `myscript.sh`. No other name will work.

The file extension is still very much _part of_ the filename on POSIX filesystems, and cannot be ignored if you still want to be able to access your files. As @eryksun demonstrated, the extension is actually _less_ of a requirement on Windows (which will attempt to resolve some extensions automatically) than on POSIX systems (which will not).

While all three OSes offer GUI features to _hide_ file extensions, they are just that — merely _hidden_. The underlying code still uses the full file/directory name, including extension. (Even Apple's Finder knows to do the equivalent of the macOS shell command `open /path/to/Applications/SomeApplication.app`, when you double click on the application icon labeled `SomeApplication`.)

**Comment by ronaldoussoren** [comment]
@barneygale, I propose closing this issue.

As @eryksun notes "file.exe" is a valid file name on a unix-y system. Furthermore, file name extensions are commonly used on unix-y systems ("script.py", "image.png", ...). The only thing that's not commonly used on unix-y systems are file extensions for binary executables, but using an extension for those is still valid and I have seen ".exe" files on Linux systems (mostly in not very good ports of Windows software).

**Comment by barneygale** [comment]
@PedanticHacker I hope you found the discussion of your idea interesting, but as it hasn't found support I'm going to close this as "not planned". In future please could you discuss ideas in the [ideas forum](https://discuss.python.org/c/ideas/6) before posting them here - you'll attract a wider audience and get a better idea of whether your idea has wide support. Thanks all the same :)
