### ISSUE TITLE
shutil.copyfile does not throw an exception for a Windows invalid file containing a colon.

### ISSUE THREAD

**Issue by leouvarov** [python/cpython#106251]
# Bug report

shutil.copyfile does not throw an exception when trying to copy src file to a file with an invalid name containing a colon. An empty file is created.  

Example:
```
import shutil

file_src = 'tst.txt'
file_dst = 'invalid:name.txt'

with open(file_src, 'w') as f:
    f.write('test file content')

shutil.copyfile(file_src, file_dst)
```
As a result an empty file with "invalid" name will be created (the part after colon is ommited). Also, I found that  pathlib.Path.is_file(file_dst) will return True.
I tried other forbidden characters
chars = ('<', '>', '"', '/', '\\', '|', '?', '*')
all of them throw an exception (OSError or FileNotFoundError).

# Your environment

Python 3.11.4 on Windows10

**Comment by ronaldoussoren** [comment]
The name "somepath:name" on Windows refers to the (alternate) stream "name" in a file "somepath", see <https://learn.microsoft.com/en-us/windows/win32/fileio/file-streams> for more information on those. 

This explains the behaviour you're seeing: the copy is performed, but the data is in an alternate data stream instead of the regular one.

**Comment by eryksun** [comment]
As mentioned above, the name "invalid:name.txt" is actually valid in general on Windows, though it's invalid on some filesystems such as FAT32 or exFAT, which do not support [file streams](https://learn.microsoft.com/en-us/windows/win32/fileio/file-streams) of the form "filename:streamname:streamtype". Note that colon (":") is the delimiter character in the full stream name, and it's not a valid character in the filename, stream name, or stream type components of the full stream name.

An NTFS file contains an anonymous data stream, which can be accessed explicitly as "filename::$DATA". Alternate data streams can be created and opened, of the form "filename:streamname" or "filename:streamname:$DATA". The default stream type is "$DATA", which is why "$DATA" can be omitted from the name. An NTFS directory contains a name index stream that's called "$I30". It can be accessed explicitly as either "dirname:$I30:$INDEX_ALLOCATION" or "dirname::$INDEX_ALLOCATION". The index stream cannot be accessed as "dirname:$I30" since even directories can contain data streams, and "$DATA" is still the default stream type. Thus "dirname:$I30" resolves as the full stream name "dirname:$I30:$DATA". Note that regular files cannot contain index streams, in contrast to directories being able to contain data streams.
