### ISSUE TITLE
Remove restriction on the wild card form of import (from module import *) only being allowed at the module level

### ISSUE THREAD

**Issue by arterrey** [python/cpython#106499]
# Feature or enhancement

Remove the restriction that requires the wild card form of import `from module import *`only being allowed at the module level.

# Pitch

The wild card form of import is often used to break apart a module into multiple files. The wild card import allows a developer to draw all those seperate module files into a single final module without needing to re-list all the symbols of each of the modules in the final module.

The same patten should be available to classes, thus allowing a class to be split across multiple files. For example,

**myclass.py**
```python
class MyClass:
    from .foo_behavior import *
```

**foo_behavior.py**
```python
from . import myclass

__all__ = ["foo"]

def foo(self: "myclass.MyClass", a: in) -> int:
    return a + 1
```

```python
>>> from .myclass import MyClass
>>> MyClass().foo(1)
2
```

To be sure this does work currently, just not with the wildcard syntax. E.g.:

```python
class MyClass:
    from .foo_behavior import foo
```

Nevertheless, there doesn't seem to be a good reason to restrict the wild card import syntax in the way that it is currently.

**Comment by sunmy2019** [comment]
Note this restriction also applies to the function level.
```py
>>> def foo():
...   from types import *
... 
  File "<stdin>", line 2
SyntaxError: import * only allowed at module level
```

It's a major behavioral change. I think we should discuss it first at https://discuss.python.org/c/ideas/6

I am also wondering why it is restricted in the first place.

**Comment by sobolevn** [comment]
In my opinion `import *` is one of the most hazardous things in Python. It makes code harder to read, complicates things for linters, type-checkers, and IDEs. Please, let's not allow it in classes / functions scopes.

**Comment by ronaldoussoren** [comment]
"from module import *" was restricted to module scope only in Python 3.0 (mentioned in the what's new for 3.0). 

IIRC removal from function level was done because using star imports in function scope is bad for performance due to disabling fast locals lookup as the byte code compiler cannot know which names are valid in that function scope. Furthermore this affects features like "nonlocal" and accessing locals from an outer function in a nested function, e.g.:

```python3

def outer():
    from foo import *

    def inner():
        print(x)
```

Is "x" a reference to a global or a reference to a local from "outer" that happens to be imported.


But anyway... This is a request for a new language feature and as such this requires discussion on discuss.python.org (ideas category) and a PEP.
