### ISSUE TITLE
Initializing a super class

### ISSUE THREAD

**Issue by iloabachie** [python/cpython#106481]
# Bug report

The code below does not intialize the B superclass.  It appears to do nothing with the superclass  when run in this manner.
```py
class A:
    def __init__(self):
        print("Initializing A")

class B:
    def __init__(self):
        print("Initializing B")

class C(A, B):
    def __init__(self):
        super(B, self).__init__()  # should initialize the B superclass
        print("Initializing C")

c = C()
```
The output shows that it only initializes the C subclass.

# Your environment

- CPython versions tested on:  namespace(name='cpython', cache_tag='cpython-311', version=sys.version_info(major=3, minor=11, micro=1, releaselevel='final', serial=0), hexversion=51053040)
- Operating system and architecture:  sys.getwindowsversion(major=10, minor=0, build=22000, platform=2, service_pack='')

**Comment by carljm** [comment]
There is no bug here, this is `super` working exactly as designed and as documented: https://docs.python.org/3/library/functions.html#super

In order to get `__init__` of all classes called, `C.__init__` should be calling `super(C, self).__init__()` (not `super(B, self).__init__()`), or simply `super().__init__()`, and you also would need to add a `super().__init__()` call in `A.__init__` method. (This seems counter-intuitive but is required for super to work correctly in multiple inheritance cases, since it operates on the linearized MRO.

Please take further `super()` usage questions to a help forum such as https://discuss.python.org/c/users/7, not the bug tracker.
