### ISSUE TITLE
[Enum] add __deepcopy__ method to Enum

### ISSUE THREAD

**Issue by ethanfurman** [python/cpython#106602]
### Linked PRs
* gh-106666
* gh-106694
* gh-106695

**Comment by Agent-Hellboy** [comment]
Hi @ethanfurman, I thought of implementing this.

did you mean we should be able to make a deep copy of the whole enum like adding `is` check in here 
https://github.com/python/cpython/blob/1f2921b72c369b19c2e32aaedb9f8c63e0cb8b48/Lib/test/test_enum.py#L803C1-L808C35

if yes, then we need to make changes in copy module I guess because Enums are getting created using a custom metaclass 
and deep copy returns the object as it is because the class is a subclass of a type 
https://github.com/python/cpython/blob/1f2921b72c369b19c2e32aaedb9f8c63e0cb8b48/Lib/copy.py#L137C1-L139C42

Where did the bug get reported? Do you know if I can see the StackOverflow link?

if it's about copying a member (adding __deepcopy__ in Enum) then I will explore more 
```
    def __deepcopy__(self, memo):
        new_enum = self.__class__(self.value)
```
currently, it is taking the same object for new_enum as well as self

**Comment by ethanfurman** [comment]
> [question about `is` check]

Yes, those should both be `is` checks -- enum members are singletons, so a copy of any kind should return the exact same object.


> [copy module questions]

An enum class, such as `Color`, is processed by that branch; a member, such as `Color.RED`, falls through to the `else` branch where a `__deepcopy__` is looked for.

`Enum.__copy__` and `Enum.__deepcopy__` just need to return `self`.


> [bug report question]

This issue is where the bug was reported.

**Comment by ethanfurman** [comment]
The current `test_copy` is testing an enum *class* -- we need to add a test for enum *members*.  All those copy tests should be using `is`.

**Comment by Agent-Hellboy** [comment]
> This issue is where the bug was reported.
Ohh, I tough this one also got reported on StackOverflow just like a calendar module feature I once picked.

I have added a PR 
Btw, I learned a lot about Enum's internal design because of the wrong assumption that deep-copy(Enum or it's member) will return a new Enum

**Comment by ethanfurman** [comment]
Thanks, @Agent-Hellboy, for the help!

**Comment by Agent-Hellboy** [comment]
Thanks @ethanfurman, looking forward to contributions like these.
