### ISSUE TITLE
Sorting Lists Using Sets

### ISSUE THREAD

**Issue by BAbdulBaki** [python/cpython#106866]
# Bug report

```py
def switch_numbers(list_of_lists, num1, num2):
	for sublist in list_of_lists:
		print(sublist)
		for i in range(len(sublist)):
			if sublist[i] == num1:
				sublist[i] = num2
			elif sublist[i] == num2:
				sublist[i] = num1
		sublist = [list(set(sublist))]
		print(sublist)
#	list_of_lists = list(set(list_of_lists))
```

# Example usage

```py
numbers = [[4, 5, 6], [1, 2, 3], [7, 8, 9]]
print("Before switching:")
print(numbers)

switch_numbers(numbers, 2, 5)
print("After switching:")
print(numbers)
```

# Output

```
Before switching:
[[4, 5, 6], [1, 2, 3], [7, 8, 9]]
[4, 5, 6]
[[2, 4, 6]]
[1, 2, 3]
[[1, 3, 5]]
[7, 8, 9]
[[8, 9, 7]]    # BUG: This should not change.
After switching:
[[4, 2, 6], [1, 5, 3], [7, 8, 9]]
```

# Your environment

- Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
- Processor	Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz   2.11 GHz
- Installed RAM	16.0 GB (15.8 GB usable)
- System type	64-bit operating system, x64-based processor
- Edition	Windows 10 Pro
- Version	21H2
- Installed on	‎6/‎20/‎2022
- OS build	19044.1766
- Experience	Windows Feature Experience Pack 120.2212.4180.0

**Comment by ericvsmith** [comment]
Please describe what you expect the output to be, and why.

A simpler example would also help.

But I think your concern comes down to sets being unordered. If so, that's not going to change.

**Comment by tim-one** [comment]
It _appears_ that most of the code here is irrelevant, and that the entire complaint is that

```python
>>> list(set([7, 8, 9]))
[8, 9, 7]
```
doesn't preserve the order of the input list. If that's not the complaint, please be more explicit about what the problem is.

But if that is "the problem", then as @ericvsmith said, it's not a bug and won't be changed. By design, sets don't care - and guarantee nothing - about order. Any of the six permutations of the input list in that example _could_ be the result.
