### ISSUE TITLE
Date is confusing on What's New page

### ISSUE THREAD

**Issue by kmulka-bloomberg** [python/cpython#106967]
# Documentation

On this page, the Date is confusing. What does it represent? Doesn't seem to be the date the version was released. Is it the last date the documentation was updated? 
https://github.com/python/cpython/blob/3.11/Doc/whatsnew/3.11.rst?plain=1#L6

### Linked PRs
* gh-107000
* gh-109648

**Comment by hugovk** [comment]
Status:

* Fixed in `main` by https://github.com/python/cpython/pull/107000, 
* will be fixed in `3.12` by https://github.com/python/cpython/pull/109648, 
* was fixed in `3.11` by https://github.com/python/cpython/pull/106999, 
* and will be fixed for future branches by https://github.com/python/release-tools/issues/34 and https://github.com/python/release-tools/pull/52.

**Comment by hugovk** [comment]
Let's close this now, the changes to this repo have been merged and we have https://github.com/python/release-tools/issues/34 to track the script changes. Thanks!
