### ISSUE TITLE
argparse: optimizing internal string formatting

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [python/cpython#107146]
# Enhancement

Replace non-public facing %-style string formatting in `argparse` with f-strings.

# Pitch

The replacement of %-style formatting with f-strings where possible is a small optimization.

We wouldn't change the public API – so the user still can/still has to use %-style formatting to further customize help/usage messages.
Furthermore, we wouldn't change the internal strings that are translated to prevent breaking translation tools elsewhere.

# Previous discussion

Informal discussion between me and Lukasz happened at the EuroPython 2023 sprint.

### Linked PRs
* gh-107152

**Comment by hpaulj** [comment]
When I first start following argparse issues, it was being used with Python2 as well as 3.  It was convenient to have code that could run on both.  That's part of why there's not been any rush to replace the old '%' style of formatting.

**Comment by doraeric** [comment]
I encounter this [formatting issue](https://bugs.python.org/issue41289) and I believe this issue should be corrected.

 If there is a `%` in help text, it will cause `ValueError: unsupported format character` and you have to escape this character. Look into the implementation, the error comes from

```python
self._get_help_string(action) % params
```

which may expand to
```python
help = 'help text with %'
help % params
```

but I think the user input should be an argument for format string instead of the format string. For example:
```python
'''usage: {}

{}'''.format(prog, help)
```

**Comment by serhiy-storchaka** [comment]
Sorry, but we usually do not accept pure cosmetic changes.

**Comment by JvD-Acknowledge** [comment]
Since the `%` is ran on user inputted data, this causes hard-to-track bugs, making this change not purely cosmetic.

I ran into this issue with the help string `Checks whether there are any "broken" tasks in [redacted URL]. Broken tasks are defined as being Stopped/Interrupted while at 100% completion.` for a subcommand. 

As a fix I had to duplicate %'s in all strings, but it's very much non-obvious. Maybe because I've always used .format() and f-strings, and aren't familiar with C.
