### ISSUE TITLE
Setting two lists equal to each other and then modifying one also modifies the other

### ISSUE THREAD

**Issue by Pikuhana42** [python/cpython#107363]
# Bug report

Setting List1 to equal List2 and then making changes to either list causes both lists to change

List1 = [1,2,3]
List2 = [4,5,6]
List1 = List2
print(List1)
print(List2)
List1[0] = 1
print(List1)
print(List2)

# Your environment

- CPython versions tested on: 3.11.4
- Operating system and architecture: Windows 10 Pro x64

**Comment by Pikuhana42** [comment]
This is my first bug report so patience and constructive criticism is appreciated

**Comment by hmc-cs-mdrissi** [comment]
This is expected behavior in python. In C++ = may mean assignment operator and list1/list2 are separate. In python variables are bound by object and when you assign list1 to list2 they refer to same object and changing one will change other. Different languages have different views on how assignment behaves. If you want list1 to be separate from list2 you need to copy it like,

```python
from copy import deepcopy
list1 = deepcopy(list2) # In this simple case list1 = list(list2) also works.
```

**Comment by Pikuhana42** [comment]
> This is expected behavior in python. In C++ = may mean assignment operator and list1/list2 are separate. In python variables are bound by object and when you assign list1 to list2 they refer to same object and changing one will change other. Different languages have different views on how assignment behaves. If you want list1 to be separate from list2 you need to copy it like,
> 
> ```python
> from copy import deepcopy
> list1 = deepcopy(list2) # In this simple case list1 = list(list2) also works.
> ```

ah ok, my bad. Thanks for the input

**Comment by terryjreedy** [comment]
Please post questions like this to, for instance, discuss.python.org, help channel.
