### ISSUE TITLE
Spelling errors in Dutch month names

### ISSUE THREAD

**Issue by bitkat** [python/cpython#107372]
# Documentation

The example given in https://docs.python.org/3/reference/lexical_analysis.html#implicit-line-joining is incorrect. The month names are capitalized. However, in Dutch, month names (as well as the days of the week) are all lowercase.

**Comment by hugovk** [comment]
Out of interest, I did some archaeology to find out who added this.

The earliest addition I found was in https://github.com/python/cpython/commit/f666917ab76a483447d5da33ebacf57ab385cb10 which added `.tex` files of "The Python Reference Manual", committed by Fred Drake in 1998.

Searching for this title, I find Version 1.2 (10 April 1995) https://ir.cwi.nl/pub/5008 written by Guido for Centrum voor Wiskunde en Informatica whilst in the Netherlands, so it's likely intentional?

<img width="655" alt="image" src="https://github.com/python/cpython/assets/1324225/5fbb7ff6-53ac-4c7d-ad61-46ae34d168f5">

(But "Januari" etc. are not in Release 1.0.2 from 4 May 1994: https://www2.informatik.hu-berlin.de/Themen/manuals/python/python-ref/ref.html)

**Comment by bitkat** [comment]
Nice find!! However, this certainly would not have been intentional. It's actually a rather common mistake among programmers, probably because of the influence from the English language.

**Comment by eendebakpt** [comment]
As a native Dutch speaker I can confirm that in Dutch the months in normal text are indeed written without a capital. However, in the example the months appear at the beginning of a sentence (of only one word, but still), where they would be written with a capital letter. Also, the example is more a list of strings then a full Dutch text.

I have no idea whether the capitalization was intentional or not, but the current example looks fine to me.

**Comment by hugovk** [comment]
Agreed, they are standalone strings and not part of a sentence, so I think it's fine in this case.

But thank you nevertheless for reporting.
