### ISSUE TITLE
Add `pathlib.Path.from_uri()` classmethod

### ISSUE THREAD

**Issue by barneygale** [python/cpython#107465]
# Feature or enhancement

Add `pathlib.Path.from_uri()` classmethod that creates a path objects from a 'file' URI, like `file:///c:/windows`. This method should accept [RFC 8089](https://datatracker.ietf.org/doc/html/rfc8089) `file:` URIs, including variant forms.

# Pitch

The proposed method is the counterpart of `pathlib.Path.as_uri()`. As we continue to open up pathlib for subclassing, user subclasses of path classes will begin to appear with their own `as_uri()` methods returning URIs like `s3://`, `ftp://`. These subclasses will likely also support parsing URIs to create paths. However, there is currently no defined interface for doing this in pathlib, and users will be tempted to accept URIs in initialisers, which produces a confusing interface. If pathlib instead defines a `from_uri()` classmethod, there is one clear and obvious method that subclasses may override.

# Previous discussion

See https://discuss.python.org/t/make-pathlib-extensible/3428/136 and subsequent posts

### Linked PRs
* gh-107640

**Comment by rdrf2838** [comment]
Hello, I'd like to give this a shot!

Before I begin, could I check if the proposed ```from_uri()``` method should be added to the ```PurePath``` base class instead of the ```Path``` class? My current understanding is that this method will not make any system calls (though I may be wrong as I have not given this function much thought yet). Additionally, the ```as_uri()``` method belongs to the ```PurePath``` base class. Thanks in advance!

**Comment by barneygale** [comment]
Implemented in 3.13 / [15de493](https://github.com/python/cpython/commit/15de493395c3251b8b82063bbe22a379792b9404) / #107640
