### ISSUE TITLE
`abc.ABC` incorrectly raise `Can't instantiate abstract` if attribute has `__getattr__`

### ISSUE THREAD

**Issue by Conchylicultor** [python/cpython#107580]
# Bug report

## Reproduction

```python
import abc

class A:

  def __getattr__(self, name: str):
    return A()


class B(abc.ABC):
  a: A = A()


B()  # TypeError: Can't instantiate abstract class B with abstract method a
```

`a = A()` is not a `@abc.abstractmethod`. I think `abc` just have some check `if hasattr(B.a, '__is_abstractmethod__')`, but this raise an error because `A.__getattr__` dynamically create `__is_abstractmethod__` on the fly

# Your environment

- CPython versions tested on: 3.11.1

**Comment by Conchylicultor** [comment]
One workaround is to raise AttributeError inside `__getattr__`:

```python

class A:

  def __getattr__(self, name: str):
    if name == '__isabstractmethod__':
      super().__getattribute__('__isabstractmethod__')  # Raise `AttributeError`
    return A()
```

But still, I feel this should not happen in the first place

**Comment by sunmy2019** [comment]
@AlexWaygood What do you think? Should this be statically checked?

**Comment by AlexWaygood** [comment]
Yes, the way the `abc` module determines whether a class has any abstract methods or attributes is via `_abc_init` here:

https://github.com/python/cpython/blob/a6675b1a597c67be972598ac8562883fabe48099/Lib/abc.py#L105-L108

`_abc_init` is imported from the `_abc` C extension module. If you look in `Modules/_abc.c`, you'll find that `_abc_init` just uses `_PyObject_IsAbstract` to check whether any values in the class dictionary have a truthy `__isabstractmethod__` attribute, and `_PyObject_IsAbstract` basically just does the C equivalent of `getattr(obj, "__isabstractmethod__", False)`:

https://github.com/python/cpython/blob/a6675b1a597c67be972598ac8562883fabe48099/Objects/object.c#L950-L965

I think the behaviour here should be kept as-is. It would break a lot of existing code if we tried to determine statically whether an object has an `__isabstractmethod__` attribute without resolving any `__getattr__` methods or descriptor lookups. (We can treat the two as being ~the same, since they both involve arbitrary code execution during `getattr()` calls -- it would be pretty unprincipled to say that the `abc` module will resolve descriptor lookups but won't call custom `__getattr__` methods, for example.) There are several classes in the standard library that define `__isabstractmethod__` properties; these would all be broken if we tried to statically determine whether objects have `__isabstractmethod__` attributes without "calling" these properties:

https://github.com/python/cpython/blob/a6675b1a597c67be972598ac8562883fabe48099/Lib/functools.py#L412-L414

https://github.com/python/cpython/blob/a6675b1a597c67be972598ac8562883fabe48099/Lib/functools.py#L971-L973

There are also tests in the `abc` module that assert the current behaviour:

https://github.com/python/cpython/blob/a6675b1a597c67be972598ac8562883fabe48099/Lib/test/test_abc.py#L239-L242

A secondary question is how we would achieve this change, if we went ahead with it? If it were Python code, we'd use `inspect.getattr_static()` to avoid arbitrary descriptor lookups and `__getattr__` calls, and that would slow the code down a _lot_, as `inspect.getattr_static()` is much slower than `getattr()`. There's probably a much faster way of doing what `inspect.getattr_static()` does in C; I can't really speak to that (I'm not exactly the world's greatest C programmer). Regardless, it would involve digging around in some C code that's been pretty stable for a while; doing so would have a very high risk of breaking some people.

Creating an object with a `__getattr__` method so that it claims to have literally every possible attribute is _going_ to break assumptions made in a fair few libraries. I think it's your code that needs to change here, @Conchylicultor, not the `abc` module :)
