### ISSUE TITLE
ConfigParser AttributeError: 'NoneType' object has no attribute 'append'

### ISSUE THREAD

**Issue by mpf82** [python/cpython#107625]
# Bug report

## Checklist

- [x] I am confident this is a bug in CPython, not a bug in a third-party project
- [x] I have searched the CPython issue tracker, and am confident this bug has not been reported before

## A clear and concise description of the bug

When trying to parse an INI with an indented key that follows a no-value key, an AttributeError is raised

  ```py
import configparser
lines = [
    '[SECT]\n',
    'KEY1\n',
    ' KEY2 = VAL2\n', # note the Space before the key!
]
conf = configparser.ConfigParser(
    comment_prefixes ="",
    allow_no_value   =True,
    strict           =False,
    delimiters       =( '=', ),
    interpolation    =None,
)
conf.read_file( lines, "test" )
print( conf.__dict__[ '_sections' ] )
  ```

```
File "C:\Python311\Lib\configparser.py", line 1076, in _read      
    cursect[optname].append(value)
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'append'
```

The reason is that ConfigParser assumes the second key is a continuation line and therefore further assumes that ``cursect[optname]`` is initialized in the following check:

```py
            if (cursect is not None and optname and
                cur_indent_level > indent_level):
                cursect[optname].append(value)
```

Suggested fix: add a check for ``cursect[optname] is not None``:

```py
            if (cursect is not None and optname and
                cursect[optname] is not None and
                cur_indent_level > indent_level):
                cursect[optname].append(value)
```

With this check added, the print will output:

```py
{'SECT': {'key1': None, 'key2': 'VAL2'}}
```

If the suggested fix is not acceptable, please consider to add a check and maybe raise a ``ParsingError``, but making an assumption about ``cursect[optname]`` and let it raise an AttributeError is just not a good thing, IMHO.

# Your environment

- CPython versions tested on: 3.7, 3.9, 3.11.2 (Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32)
- Operating system and architecture: Windows 10 Pro, 64 bit

### Linked PRs
* gh-107651

**Comment by terryjreedy** [comment]
Behavior verified with 3.12.0b4 on Win10.  I agree that configparser has a bug.  I also think that a continuation line for a no-value option is a user bug.  So I would a line to the [structure section](https://docs.python.org/3/library/configparser.html#supported-ini-file-structure) saying so and raise a ParsingError with a message something like "No-value option {opname} cannot be continued".

Line 1084, `cursect[optname] = None` executes when `optval is not None` (line 1079) is false.  Since this appears to be the only such setting, I think `cursect[optname].append(value)` can be replaced with `if...else raise...`.

Adding `=` to the KEY1 line results in KEY1 initially getting a blank value `""` that *is* continued, resulting in value '\nKEY2 = VAL2'

**Comment by Agent-Hellboy** [comment]
I have added a PR as you suggested @terryjreedy
