### ISSUE TITLE
Argparse incorrectly parses positional arguments containing spaces

### ISSUE THREAD

**Issue by finn-cz** [python/cpython#107829]
# Bug description
Let's suppose the following piece of code:

  ```py
""" Argparse bug demonstration """

import argparse
import pprint
import sys

# parsing arguments
parser = argparse.ArgumentParser(description='Argparse bug demonstration')
parser.add_argument('--output', required=True, type=str, help='some output argument')
parser.add_argument('args', nargs='*', help='arguments')
args, remaining_args = parser.parse_known_args()

pprint.pprint(sys.argv[1:])
pprint.pprint(args.output)
pprint.pprint(args.args)
pprint.pprint(remaining_args)
  ```
and run it like this:
```
python argparse_bug.py --output stdout -DHello -DCruel "-DWorld" -DI'm "-Dleaving you" -Dtoday
```
The output will be:
```
['--output',
 'stdout',
 '-DHello',
 '-DCruel',
 '-DWorld',
 "-DI'm",
 '-Dleaving you',
 '-Dtoday']
'stdout'
['-Dleaving you']
['-DHello', '-DCruel', '-DWorld', "-DI'm", '-Dtoday']
```

I'think all positional arguments should be stored in `args.args` or at worst all in `remaining_args`, but this behaviour, when some arguments are placed in `remaining_args` and those with spaces in `args.args` is strange and unexpected.

# Environment

MS Windows 10 Enterprise, 22H2, build 19045.3208
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

**Comment by terryjreedy** [comment]
I verified the behavior on 3.12.0rc1, but it is not a bug.  You define 'args' as the first sequence of otherwise unmatched positional arguments, if any, and a string with a space is seen as a positional argument.  A no-space string with leading '-' is unknown, not positional.  Remove the leading '-' from strings on either side of the space string, so that they become positional, and they are added to args.  Remove the leading '-' from, say, '-Dhello', and that is put in args, but the space string is not because it does not follow 'Dhello'.

Experimenting with argparse, as suggested above, is *much* easier if one passes a list of strings to parse[-known]-args and runs the file directly from an editor.  Edit the list, run, look at result; repeat.  Another experiment: pass `['a', '--output', 'stdout', 'b']` and args is ['a'] and remaining_args is ['b'].

Although parse-known-args allows for some interspersing of known and unknown args, as shown by the example in the [doc](https://docs.python.org/3/library/argparse.html#partial-parsing), it is probably best used for cases where the unknown args are all at the end, such as (on Windows) `py -3.12 -m idlelib -n file.py`, where `['-n', 'file.py']` is passed on to IDLE.
