### ISSUE TITLE
@cached_property is not checked for doctests

### ISSUE THREAD

**Issue by tjsmart** [python/cpython#107995]
### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.10, CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.13.0a0 (heads/main:607f18c894, Aug 15 2023, 08:58:26) [GCC 11.4.0]

### A clear and concise description of the bug:

Doctests belonging to a `functools.cached_property` are not ran by doctest.

Here is a minimal example (saved in a file `t.py`):
```python
from functools import cached_property


class Foo:
    @cached_property
    def my_cached_property(self):
        """
        >>> assert False
        """
        return 1
```

If I then invoke doctest with this file, I'd expect to see an assertion error. Instead, this doctest is skipped:
```console
$ python -m doctest t.py  # no failing output due to assertion error
$ echo $?  # zero exit code
0
```

Note, this issue was originally reported here: https://github.com/pytest-dev/pytest/issues/11237.

### Linked PRs
* gh-107996

**Comment by AlexWaygood** [comment]
Thanks for the bug report, and for the fix, @tjsmart!

Although the fix is very simple, and although I can't think of ways in which it might break people's code, it's the kind of thing that _could_ have unexpected consequences. For that reason, I think we won't be backporting this fix, unfortunately -- you'll have to wait for Python 3.13 to see the fix. As such, I'm closing this issue out.

Thanks again for the PR!
