### ISSUE TITLE
Drop the "Distributing Python Modules" section of the docs

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#107987]
# Documentation

https://docs.python.org/3/distributing/index.html is woefully outdated and the packaging ecosystem is managed externally to the core dev team. It would probably be better to have a link pointing at packaging.python.org than it is to try and maintain this part of the docs.

### Linked PRs
* gh-108016
* gh-108081
* gh-108091

**Comment by BrenBarn** [comment]
Does the same apply to the section on [installing](https://docs.python.org/3/installing/index.html)?

**Comment by BrenBarn** [comment]
> > Does the same apply to the section on [installing](https://docs.python.org/3/installing/index.html)?
> 
> I don't think so. That page is still relatively accurate for how most people will do things and with what Python typically ships with.

Well, yes, for the moment.  :-)  But it looks to me like it's still mostly documenting how to use pip, right?  And pip isn't in the stdlib.  So might it be prudent to keep it under packaging docs so that it will remain accurate?  (For instance, even the `--user` part there may now be in danger of getting stale/confusing since the introduction of externally-managed environments.)

**Comment by brettcannon** [comment]
> But it looks to me like it's still mostly documenting how to use pip, right? And pip isn't in the stdlib.

Pip is effectively shipped with Python (Debian withstanding), so it's as close as one can get to being included with Python short of being in the stdlib.

If you would like to propose removing the installation docs then please open a separate issue for that idea.

**Comment by hugovk** [comment]
Thanks @AA-Turner for the PRs!
