### ISSUE TITLE
`TypeAliasType.__value__` might raise `NameError`, should we test it?

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#107905]
```python
>>> type Invalid = dict[X, Y]

>>> Invalid[str, int]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Only generic type aliases are subscriptable

>>> Invalid.__value__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in Invalid
NameError: name 'X' is not defined
```

This seems correct to me. 

However, this case is not covered right now with existing tests.

But, before adding a test case for this error (that in my opinion will be quite common among devs: when you forget to add `[X, Y]` to type alias definition), I want to double check this with @JelleZijlstra 

### Linked PRs
* gh-107997
* gh-108217

**Comment by JelleZijlstra** [comment]
Good catch, there is no test in `test_type_aliases.py` where evaluating the value raises.

**Comment by brandonardenwalli** [comment]
I am also try to follow this example, and I get a different error when I run example:

`type Invalid = dict[X, Y]
  File "<stdin>", line 1
    type Invalid = dict[X, Y]
         ^^^^^^^
SyntaxError: invalid syntax`

And all code in `>>>` after does not work for me since this above error seems to be causing problem.

is this also a bug, or is there more I need to do? (I am doing something wrong?)

**Comment by JelleZijlstra** [comment]
@brandonardenwalli these issues refer to new syntax that is being added in Python 3.12. Please use a recent Python 3.12 build to test.
