### ISSUE TITLE
[C API] PEP 741: Add PyInitConfig C API to customize the Python initialization

### ISSUE THREAD

**Issue by vstinner** [python/cpython#107954]
### Links to previous discussion of this feature:

https://discuss.python.org/t/fr-allow-private-runtime-config-to-enable-extending-without-breaking-the-pyconfig-abi/18004

### Summary of proposal:

Add a text-based configuration to Python initialization

### Pitch:

An API should be added to the limited C API customize the Python initialization (PyConfig API, PEP 587).

The problem is that the PyConfig C API is excluded from the limited C API, whereas the legacy initialization API is deprecated (ex: Py_VerboseFlag in Python 3.12) and being removed in Python 3.13 (ex: PySys_SetPath()).

### Linked PRs
* gh-110145
* gh-110146
* gh-110176
* gh-112609
* gh-116359
* gh-123472
* gh-123502
* gh-123663
* gh-123668
* gh-124636
* gh-127056
* gh-132954
* gh-132958

**Comment by LostTime76** [comment]
As discussed in discourse, I do not think the text file is the best option for embedding. Depending on the embedding scenario, I think we will run into issues of finding the file due to how python is currently resolving paths. I have a very specific scenario that may be solved in easier ways. Even if you by chance get python to find the file in my particular scenario, I don't want the user of my embedded python exe to have to specify package paths that my exe should always be able to set itself. 

Its not as easy as putting the file in the same directory as the embedded exe or the main script. Take the scenario that the embedding exe is using the global python install or the embedding exe is launched as a child process from an external process where the process path is not the path of the embedded exe.

I think there may be much easier ways to solve my specific scenario. I would like to use as few APIs as possible and not duplicate how python is already parsing the options from the command line.

What about adding additional command line options that can be set from argv? If we could set additional package paths from argv, it would allow us to direct point to where we need to without hassle.

Environment variables do not work nicely in the embedded scenario, even though we have PYTHONPATH, because there is no way to cleanly set an environment variable from  an already running process to be accessible from a loaded python dll.

**Comment by vstinner** [comment]
I'm thinking about a function taking a string, not a file.

**Comment by vstinner** [comment]
I wrote PR #112609 to read configuration options such as ``"verbose"`` or ``"argv"`` as a C int or as a Python object.

**Comment by vstinner** [comment]
I close the issue: https://github.com/python/cpython/pull/110176#issuecomment-1864287927

**Comment by milianw** [comment]
Hey @vstinner - IIUC then there's still no non-deprecated API in the limited C API to customize the initialization, right? Can you then please reopen this task to indicate that this? Or should I report a separate issue to track this?

Thank you

**Comment by vstinner** [comment]
> Can you then please reopen this task to indicate that this?

Ok, I reopen the issue.

**Comment by vstinner** [comment]
> Hey @vstinner - IIUC then there's still no non-deprecated API in the limited C API to customize the initialization, right? Can you then please reopen this task to indicate that this? Or should I report a separate issue to track this?

I wrote [PEP 741 – Python Configuration C API](https://discuss.python.org/t/pep-741-python-configuration-c-api/43637). Can you please elaborate your use case to motivate the usage of the limited C API to customize the Python initialization, rather than using the non-limited PyConfig C API? I was [asked for such rationale](https://discuss.python.org/t/pep-741-python-configuration-c-api/43637/9).

**Comment by milianw** [comment]
We have a large old code base with an embedded python/jupyter console in a graphical application.

We call `Py_SetProgramName` and `Py_SetPythonHome` - though to be frank our test suite seems to pass even without calls to these two functions, but maybe not in a packaged environment without any system python available, I have to double check that - but I believe this was the initial idea - to tell python where to look for its bundled libraries in a subfolder of our application directory.

**Comment by vstinner** [comment]
See also https://github.com/python/cpython/issues/99872 "Allow efficient read access to PyConfig options".

**Comment by vstinner** [comment]
PEP 741 is now fully implemented, I close the issue.
