### ISSUE TITLE
asyncio.StreamReaderProtocol doesn't appear to call connection_lost

### ISSUE THREAD

**Issue by robertsdotpm** [python/cpython#108129]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

Windows

### A clear and concise description of the bug:

I'm trying to subclass StreamReaderProtocol so its main methods can be used like a protocol class. Currently this works well except for the behavior of connection_lost which doesn't seem to be getting called when a socket is closed. Here is the following code I use to produce this bug:

```python3
asyncio.set_event_loop_policy(SelectorEventPolicy())
class TestDaemon(unittest.IsolatedAsyncioTestCase):
    async def test_connection_close(self):
        reader = asyncio.StreamReader(limit=10000)
        class MinReader(asyncio.StreamReaderProtocol):
            def __init__(self, reader):
                self.close_set = False
                super().__init__(reader)

            def connection_made(self, transport):
                self.transport = transport
                super().connection_made(transport)

            def data_received(self, data):
                print("Received:", data.decode())
                super().data_received(data)

            def connection_lost(self, exc):
                # The socket has been closed
                self.close_set = True

        # Make server to test close handler works.
        loop = asyncio.get_event_loop()
        lsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        lsock.bind(('127.0.0.1', 0))
        print(lsock)
        mr = MinReader(reader)
        server = await loop.create_server(
            lambda: mr,
            sock=lsock
        )

        # Connect to server and close pipe.
        dest = ("127.0.0.1", lsock.getsockname()[1])
        cs = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        cs.connect(dest)
        print(cs)
        cs.close()
        await asyncio.sleep(3)
        print(mr.close_set)
        server.close()

```

The output I get is False. But switching the class to use the Protocol class (with minor changes) sets it to True. Though this does not support reader / writer streams. It just shows what I would expect a close to do... Let me know if I'm using this wrong?

**Comment by robertsdotpm** [comment]
Hello, I've looked at the issue again and narrowed it down to this function 

https://github.com/python/cpython/blob/main/Lib/asyncio/streams.py#L275

```python3
    def eof_received(self):
        reader = self._stream_reader
        if reader is not None:
            reader.feed_eof()
        if self._over_ssl:
            # Prevent a warning in SSLProtocol.eof_received:
            # "returning true from eof_received()
            # has no effect when using ssl"
            return False
        return True
```
		
So here: if the function returns False then the connection_lost callback is called as expected. But at the moment it's only returning False if the transport is using SSL. If this class is just used with a simple TCP socket (which I think was the purpose) then False is never returned. So the connections aren't cleaned up. Maybe there's some other reason why you would want to keep this open but to be it seems like unexpected behavior.

To anyone who wants a fix define this method in your subclass:

```python3
class Something(StreamReaderProtocol):
    def eof_received(self):
        reader = self._stream_reader
        if reader is not None:
            reader.feed_eof()

		return False
```

**Comment by thegamecracks** [comment]
Correct me if I'm wrong, but to my understanding StreamReader normally comes with a StreamWriter, and StreamWriter is what handles closing the underlying transport, leading to `connection_lost()` being called. In other words, the transport not closing by itself is intentional.

<details>
<summary>Script calling <code>StreamWriter.close()</code></summary>

```py
import asyncio
import socket
import unittest


class MyStreamReaderProtocol(asyncio.StreamReaderProtocol):
    writer: asyncio.StreamWriter

    def __init__(self, reader: asyncio.StreamReader):
        super().__init__(reader, self.client_connected_cb)
        self.closed = False

    def client_connected_cb(self, reader, writer):
        self.writer = writer

    def connection_made(self, transport):
        print("protocol: connection made")
        super().connection_made(transport)

    def data_received(self, data):
        print("protocol: received", data)
        super().data_received(data)

    def connection_lost(self, exc):
        print(f"protocol: connection lost")
        super().connection_lost(exc)
        self.closed = True


class TestDaemon(unittest.IsolatedAsyncioTestCase):
    async def test_connection_close(self):
        loop = asyncio.get_running_loop()
        print(loop)

        lsock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        lsock.bind(("127.0.0.1", 0))

        reader = asyncio.StreamReader()
        protocol = MyStreamReaderProtocol(reader)

        server = await loop.create_server(lambda: protocol, sock=lsock)

        async with server:
            port = lsock.getsockname()[1]
            dest = ("127.0.0.1", port)
            with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as cs:
                cs.connect(dest)
                cs.send(b"data\n")

            # Yield until connection is made, writer will be created afterwards
            print("test: received", await reader.readline())

            print("test: closing writer")
            protocol.writer.close()

            # If an error occurs before this, e.g. writing+draining after
            # the connection has closed, wait_closed() will re-raise it here
            print("test: waiting for writer to close")
            await protocol.writer.wait_closed()

        self.assertTrue(protocol.closed)
```

</details>

Result:
```py
<ProactorEventLoop running=True closed=False debug=True>
protocol: connection made
protocol: received bytearray(b'data\n')
test: received b'data\n'
test: closing writer
test: waiting for writer to close
protocol: connection lost
```

**Comment by robertsdotpm** [comment]
@thegamecracks

Your example works fine for cleaning up the server socket but what I'm interested in is a listen socket that serves other clients. The protocol class will be created for each client connection. In which case -- when a client closes their connection the server ought to be able to run the connection_lost function. Currently this isn't happening which makes it hard to manage connections for servers that use this class.

**Comment by thegamecracks** [comment]
As a sidenote, it seems weird to use StreamReaderProtocol for flow control rather than the StreamReader/StreamWriter provided by that protocol or a custom protocol altogether.
Regardless based on what I could figure out, the transport can either call `connection_lost()` first in the case of a read/write error, or call `eof_received()` first. EOF doesn't imply the client's connection is closed, only that the client has no more data to send. Maybe the client did close their connection, but they could have also shutdown the write half of their connection, expecting you to send something back. Python cannot assume what you'll do in this case, so the protocol lets you decide whether your side of the connection should be closed. Note that this is the case for any stream protocol, not StreamReaderProtocol in particular.

Here's an example using just high-level interfaces to demonstrate what a server might do:
```py
async def handle_client(reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
    # connection_made()
    try:
        while True:
            # data_received() or eof_received() (buffered data comes before EOF)
            data = await reader.read(1024)
            if not data:
                print("Server received EOF")
                writer.write(b"Goodbye!\n")
                await writer.drain()
                break

            print("Server received", data)
            writer.write(data)
            await writer.drain()
    except ConnectionError as e:
        # connection_lost()
        print(f"Connection closed due to {type(e).__name__}")
    finally:
        # If the connection wasn't already lost, we'll close the connection ourselves
        # (eventually leading to connection_lost(None))
        print("Server finalizing connection")
        writer.close()

server = await asyncio.start_server(handle_client, ...)
async with server:
    await server.serve_forever()
```

**Comment by Hels15** [comment]
@robertsdotpm might as well close it if you got the answer.

**Comment by robertsdotpm** [comment]
> @robertsdotpm might as well close it if you got the answer.

I appreciate the responses but so far I don't think these replies are relevant to the issue. People use the protocol classes because code is fired automatically when an event occurs. The previous examples are based on having to poll for events yourself as the server which defeats the purpose of using the protocol classes. Every other related class of this kind has a method called connection_lost that is correctly run by the event loop if a client disconnects and I do think that for server code that uses these classes to not be able to handle this event asynchronously is a bug to me. Going around it to avoid using the protocol classes or having the server manually call close like in HTTP is not really a solution to the issue.

**Comment by thegamecracks** [comment]
I don't mean to suggest that the way to solve `connection_lost()` not being called was to use the Stream classes rather than a protocol. Rather, `connection_lost()` only happens after you close your side of the connection or you get a read/write error which implicitly closes the connection. `eof_received()` is there to detect the client attempting to gracefully shutdown the connection, so your code *should* consider this as the client wanting to disconnect.

> Maybe there's some other reason why you would want to keep this open but to be it seems like unexpected behavior.
https://github.com/python/cpython/issues/108129#issuecomment-1685162636

In [TCP](https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Protocol_operation), a typical connection termination can be broken down to four steps:
1. The client sends a `FIN` to the server
2. The server `ACK`s their response
3. The server sends a `FIN` to the client
4. The client `ACK`s their response

Once step 2 is reached, the server knows that the client won't send any more data and socket will receive EOF. Between step 2 and 3, the server might want to send data back, which is why it stays open by default. In your case you don't have anything to send back, so shutting down your connection is what you want to do, and returning False from `eof_received()` as your workaround showed is the same as explicitly calling `transport.close()` or `writer.close()`. The example I gave with streams was to show the same decision being made at a higher level.

**Comment by robertsdotpm** [comment]
Hello @thegamecracks you really know your stuff. I am impressed with your knowledge. I've double checked in wireshark that both the 'graceful' FIN sequence and the error RST sequence can be handled by the changes to eol_received. So I will mark this issue as solved for now. If there's any people in future who come across this in Python they should have more than enough information here to know what's going on. I appreciate everyone who looked at this issue and walked through the TCP stack with me. You're smart people, thank you.
