### ISSUE TITLE
Assigning to a class variable with name equal to annotation corrupts the annotations

### ISSUE THREAD

**Issue by davidhewitt** [python/cpython#108437]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

Linux

### A clear and concise description of the bug:

The following snippet demonstrates a divergence in the evaluation of `F.__annotations__` for its two attributes `A` and `B` even though they are annotated in the same way.

```python
A = int
B = int

class F:
   A: Optional[A]
   B: Optional[B] = None

print(F.__annotations__)
#> {'A': typing.Optional[int], 'B': <class 'NoneType'>}
```

The annotation for `A` looks completely as expected. For `B` the type `None` is a potential surprise to users.

I've reproduced this through from 3.7 to 3.12. With 3.10 union syntax we get a `TypeError` thrown:

```python
B = int

class F:
    B: B | None = None  # TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'
```

----

It looks to me like scoping rules are at play here, and the difference is that `A` without the assignment doesn't actually define the name in the class scope. It's reasonable to make the argument that because of this `Optional[B]` is completely expected to evaluate to `Optional[None]` (which then reduces to `None`), in which case please close this as not a bug.

I couldn't find the exact scoping rules for class attribute annotations in [PEP 484](https://peps.python.org/pep-0484), so it seemed prudent to at least file a bug report to prompt discussion.

Originally reported downstream as a Pydantic bug in https://github.com/pydantic/pydantic/issues/7222

**Comment by davidhewitt** [comment]
Right, agreed. Reading PEP 526 I only see one potentially interesting point in the specification: https://peps.python.org/pep-0526/#specification

> This syntax does not introduce any new semantics beyond [PEP 484](https://peps.python.org/pep-0484), so that the following three statements are equivalent:
> 
> ```python
> var = value # type: annotation
> var: annotation; var = value
> var: annotation = value
> ```

It seems to me that the implementation doesn't match this specification. The annotation is being evaluated _after_ the assignment. The second form of the spec above implies that the evaluation would be evaluated before.

Indeed a workaround is to split into two statements as per the "equivalent" form of the specification:

```python
A = int
B = int

class F:
   A: Optional[A]
   B: Optional[B]; B = None

print(F.__annotations__)
#> {'A': typing.Optional[int], 'B': typing.Optional[int]}
```

Similarly no blowup in the case of union syntax:

```python
B = int

class F:
   B: B | None; B = None

print(F.__annotations__)
#> {'B': int | None}
```

I suppose there is also a complication here related to delayed evaluation of annotations / forward references. Probably changing anything can break a lot. Unless you think there's something which could be done here, please close this. I'll go suggest the workaround in the original pydantic issue.

**Comment by terryjreedy** [comment]
In general, expressions are evaluated left to right.  Does the typing doc, which supercedes the PEP, mention this exception for annotation expressions?  (I think It should.)

I presume the same does not matter for function definitions because the annotation expression is evaluated in global (or outer) scope while the parameter name is local and not even bound until the function is called.

**Comment by davidhewitt** [comment]
Just noticed that the language reference describes this order of operations as assignment first, then evaluate annotation: https://docs.python.org/3/reference/simple_stmts.html#annassign

So according to the reference, this behaviour is expected. I suppose we should infer the PEP is out of date and there is no bug here.

**Comment by AlexWaygood** [comment]
@davidhewitt

> I suppose we should infer the PEP is out of date

Yes, PEPs represent the consensus of the community at a fixed point in time; the living documentation is the language reference.

@terryjreedy

> Does the typing doc, which supercedes the PEP, mention this exception for annotation expressions? (I think It should.)

I wouldn't expect this to be noted in the `typing` documentation, since it doesn't relate to any objects exposed by the `typing` module's public API. Annotations are mostly used for typing these days, but they predate typing, and can still be used for things other than typing. This is a fundamental aspect of how the language works; I think the proper place for this to be noted is indeed the language reference (where, according to David, it is already noted) rather than the documentation for the `typing` module.

**Comment by AlexWaygood** [comment]
As David says, this appears to be already well documented in the language reference, so I don't think there's a bug here
