### ISSUE TITLE
dataclasses field named like an import whose type is in the import with a default value

### ISSUE THREAD

**Issue by avieli** [python/cpython#108905]
# Bug report

### Bug description:
When creating a field in a dataclass whose name is the same as the module in which its type is and giving it a default value, it raises an attribute-error.
The name of the field is probably used as is and overrides the imported module.

```python
import dataclasses

@dataclasses.dataclass
class C:
    dataclasses: dataclasses.dataclass = None
```

Or maybe an example someone might use:
```python
import dataclasses
import typing

@dataclasses.dataclass
class C:
    typing: typing.Optional[int] = None
```

will throw an attribute-error:
`AttributeError: 'NoneType' object has no attribute 'dataclass'`
or:
`AttributeError: 'NoneType' object has no attribute 'Optional'`

Also happens if using `field` to create the default value.
Also happens with user-created modules.

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by sobolevn** [comment]
This is not specific to `dataclasses`, this is just how name resolution works:

```python
>>> class A:
...    typing: typing.List = None
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in A
AttributeError: 'NoneType' object has no attribute 'List'
```

Annotations are processed after `typing = None` is set in `A`'s body.
Since inside `A`'s class-scope `typing` will be redefined, python correctly raise an error.

To fix this:
1. Rename import `import typing as t` and use `typing: t.Optional[str] = None`
2. Import individual names: `from typing import Optional`
3. Rename your field

I hope this helps! 👍

**Comment by avieli** [comment]
Interesting!
I would still call it a bug, and not correct behavior though...
