### ISSUE TITLE
Unexpected syntax for str.format

### ISSUE THREAD

**Issue by invisibleroads** [python/cpython#109018]
# Bug report

### Bug description:

It seems like `str.format` does not require quotes when referencing keys from a dictionary. This looks like a bug.

```python
In [1]: "{d['a']}".format(d={'a': 1})
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 1
----> 1 "{d['a']}".format(d={'a': 1})
KeyError: "'a'"

In [2]: "{d[a]}".format(d={'a': 1})
Out[2]: '1'

In [3]: "{d['a']}".format(d={"'a'": 1})
Out[3]: '1'
```

Python 3.11.4

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by chgnrdv** [comment]
As I can see, it is a documented behaviour.
https://docs.python.org/3/tutorial/inputoutput.html#the-string-format-method

`If you have a really long format string that you don’t want to split up,
it would be nice if you could reference the variables to be formatted by name
instead of by position. This can be done by simply passing the dict
and using square brackets '[]' to access the keys.`

```python
>>> table = {'Sjoerd': 4127, 'Jack': 4098, 'Dcab': 8637678}
>>> print('Jack: {0[Jack]:d}; Sjoerd: {0[Sjoerd]:d}; '
      'Dcab: {0[Dcab]:d}'.format(table))
Jack: 4098; Sjoerd: 4127; Dcab: 8637678
```

**Comment by sunmy2019** [comment]
Closed as it is documented behavior.

If you have the intention to change the current behavior, raise it at https://discuss.python.org/c/ideas/6
