### ISSUE TITLE
The pydoc3 command uses the incorrect interpreter in virtual environments and fails to bring documentation for installed packages.

### ISSUE THREAD

**Issue by CarvellScott** [python/cpython#109115]
# Bug report

### Bug description:

Problem: On python 3.10, `/usr/bin/pydoc3` uses a shebang line of `#!/usr/bin/python3.10`. Because this doesn't get symlinked or copied into a virtual environment on creation (at least when done through `python3 -m venv`), it uses a different version of python and correspondingly different set of modules when presenting documentation.

Reproduction Instructions:
```bash
python3 -m venv venv
source venv/bin/activate
echo '"This module is documented"' > venv/lib/python3.13/site-packages/documented_module.py
pydoc3 documented_module
```

Expected Result: Documentation for "documented_module" shows up.
Actual Result: A message saying "No Python documentation found for 'documented_module'" shows instead.

### CPython versions tested on:

3.10, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-109116

**Comment by vsajip** [comment]
Is this problem distro-specific? If it's not, then why not address it in `pydoc` rather than `venv`?

**Comment by CarvellScott** [comment]
It might be distro-specific. I'm not as familiar as I should be with different varieties of linux if that's what you mean. Is there a specific command I should run to help narrow that down? I've seen this occur in:
- WSL running Ubuntu 22.04.3 LTS
- Mac OS Monterey 12.6.7
- ChromeOS 115.0.5790.182

Even so, it can't be addressed it in the pydoc module because the issue is with the shebang lines used in some of the files that import pydoc. The module itself is working fine.

**Comment by vsajip** [comment]
Sorry, I should have been clearer. I meant to say, whatever it is that installs `pydoc3` as a running script. As far as I know, `python -m venv` doesn't install `pydoc` as a runnable script (I just checked on Ubuntu, and on Windows).

**Comment by CarvellScott** [comment]
Looks like Makefile.pre.in overwrites the shebang line with a different value. I don't immediately seeing the reason in the commit of the `git blame`, and idle looks like it may suffer a similar issue, but I'll keep my change to just pydoc.

**Comment by vsajip** [comment]
As I said, `python -m venv` doesn't appear to install `pydoc` as an executable script, at least on my systems. Are you saying it does on yours? (I don't have access to any of the systems you mentioned.)

**Comment by CarvellScott** [comment]
On WSL, Makefile uses sed to copy `Tools/scripts/pydoc3` to `/usr/bin/pydoc3` while simultaneously changing the shebang line.
My first approach to fixing this was to have `python -m venv` create an equivalent script in `$VIRTUAL_ENVIRONMENT/bin/`, but my new approach modifies the Makefile to keep the proper shebang line.

**Comment by vsajip** [comment]
I'm not sure either is the correct approach. I would say that if you need `pydoc` in the venv, you need to create a modified script or class inheriting from `venv.EnvBuilder` which installsit in venvs you create after doing the other setup. I don't believe there should be any change in core Python for this. Feel free to open a discussion on `discuss.python.org` about this, and see what other core developers think.

**Comment by merwok** [comment]
pydoc inside venvs was removed here: https://github.com/python/cpython/issues/62424#issuecomment-1093619138

I thought it was a mistaken decision.  I do understand the recommendation for people to use `python3.x -m pip`, the general appeal of `-m` scripts, but regret that we lost perfectly fine functioning scripts for other operating systems (and non-beginner users who are not confused about their python installations and PATH).

I still find myself regularly trying `pydoc thing` or `pydoc3 thing` in an activated venv, then having to correct to the longer, less convenient command.  (`python3 -m venv` is fine since I rarely run it directly.)  It would be great to see pydoc in $venv/bin, next to python and pip.

To stop rewriting the shebang in the main pydoc script would be a way to solve this, but I am not sure of all implications.
I was also going to say that redistributors would probably continue to rewrite shebangs, but was surprised to see (on debian) that the `pdb`, `pdb3.11` and `pdb3.12` scripts do use `/usr/bin/env python3` (incorrectly for the versioned scripts, but that’s another issue).  So maybe there is hope!

**Comment by vsajip** [comment]
Based on the linked discussion, I'm minded to close this issue and PR as "not planned". I didn't see any objections to using an alias and/or `pydoc.cmd` to get access to `pydoc` uniformly across venvs and installed "system" Pythons.
