### ISSUE TITLE
Replace `mktemp` usage with `mkstemp` 

### ISSUE THREAD

**Issue by nydelzaf** [python/cpython#109317]
# Bug report

### Overview
As of Sep 12, 2023 - there's three existing uses of `mktemp` method of `tempfile` module. Since it's not safe to use, it's recommended to use `mkstemp` instead.

In file: [windows_utils.py](https://github.com/python/cpython/blob/main/Lib/asyncio/windows_utils.py#L34) and [connection.py](https://github.com/python/cpython/blob/main/Lib/multiprocessing/connection.py#L78), there are several methods that creates a temporary file using an unsafe API `mktemp`. The use of this method is discouraged in the Python documentation. iCR suggested that a temporary file should be created using `NamedTemporaryFile` or `mkstemp` which is a safe API. iCR replaced the usage of `mktemp` with `mkstemp`. Read more about tempfile's deprecated functions [here](https://docs.python.org/3/library/tempfile.html#deprecated-functions-and-variables).

### Proposed Fix
Replace the `mktemp` method with a safe one- `mkstemp`

### Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation (OpenSSF)](https://openssf.org/): [Project Alpha-Omega](https://alpha-omega.dev/). Alpha-Omega is a project partnering with open source software project maintainers to systematically find new, as-yet-undiscovered vulnerabilities in open source code - and get them fixed – to improve global software supply chain security.

The bug is found by running the Intelligent Code Repair (iCR) tool by OpenRefactory and then manually triaging the results.

> **Comments:**
> I wasn't sure which label to choose. Since it's related to deprecation according to Python's documentation, I opted for `type-bug`

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-109318

**Comment by serhiy-storchaka** [comment]
`mkstemp()` is more safe than `mktemp()` only if you use it properly. I.e. when you perform operations with file descriptor which cannot be replaced outside of your program.

If you simple drops the file descriptor and continue to use file name, you not only do not make the code more safer, you introduce a file descriptor leak.

I do not see how `mkstemp()` can improve the code that still use `mktemp()`, because it needs a path, and cannot fork a file descriptor. I am not even sure that there are real bugs there. The OS should prevent replacing such files. Do you have an example of the attack that utilizes the supposed vulnerability?
