### ISSUE TITLE
Iterating over `enum.Flag` types ignores zero-valued in Python 3.11

### ISSUE THREAD

**Issue by gmgunter** [python/cpython#109633]
# Bug report

### Bug description:

In Python 3.10, you can iterate over `enum.Enum` and `enum.Flag` types to yield their values.

```python
>>> import sys; print(sys.version)
3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]

>>> import enum
>>> class MyEnum(enum.Enum):
...     A = 0
...     B = 1
...     C = 2
...
>>> list(MyEnum)
[<MyEnum.A: 0>, <MyEnum.B: 1>, <MyEnum.C: 2>]

>>> class MyFlag(enum.Flag):
...     A = 0
...     B = 1
...     C = 2
...
>>> list(MyFlag)
[<MyFlag.A: 0>, <MyFlag.B: 1>, <MyFlag.C: 2>]
```

In Python 3.11, the same is true for `enum.Enum` types, but the behavior seems to have changed for `enum.Flag` types. Now, iterating over the type only yields its nonzero values.

```python
>>> import sys; print(sys.version)
3.11.5 | packaged by conda-forge | (main, Aug 27 2023, 03:34:09) [GCC 12.3.0]

>>> import enum
>>> class MyEnum(enum.Enum):
...     A = 0
...     B = 1
...     C = 2
...
>>> list(MyEnum)
[<MyEnum.A: 0>, <MyEnum.B: 1>, <MyEnum.C: 2>]

>>> class MyFlag(enum.Flag):
...     A = 0
...     B = 1
...     C = 2
...
>>> list(MyFlag)
[<MyFlag.B: 1>, <MyFlag.C: 2>]  # Missing <MyFlag.A: 0> (!)
```

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

Linux

**Comment by CharlieZhao95** [comment]
I bisected to here:
> commit 7aaeb2a3d682ecba125c33511e4b4796021d2f82
> Author: Ethan Furman <ethan@stoneleaf.us>
> Date:   Mon Jan 25 14:26:19 2021 -0800
> bpo-38250: [Enum] single-bit flags are canonical (GH-24215)

**Comment by sobolevn** [comment]
From the docs, I can say that now `0` is treated as more like a special value:
https://docs.python.org/3/library/enum.html#enum.Flag

Check how `<Color: 0>` is used all over the place.

The technical reason behind this is that now `0` does not get into `_member_names_` here: https://github.com/python/cpython/blob/712cb173f8e1d02c625a40ae03bba57b0c1c032a/Lib/enum.py#L313-L319

Because `0` is not a `_is_single_bit` member (it is explicit): https://github.com/python/cpython/blob/712cb173f8e1d02c625a40ae03bba57b0c1c032a/Lib/enum.py#L93-L98

So, when we use `__iter__` over `_member_names_` zero-value is not there: https://github.com/python/cpython/blob/712cb173f8e1d02c625a40ae03bba57b0c1c032a/Lib/enum.py#L790-L794

We need @ethanfurman :)

**Comment by ethanfurman** [comment]
It is more accurate to say that `Enum` and `Flag` iterate over the *canonical* values.  For example:

    class Color(Enum):
        RED = 1
        GREEN = 2
        BLUE = 3
        ROJO = 1
        VERDE = 2
        AZUL = 3

    list(Color)
    # RED, GREEN, BLUE
 
    class BlendColor(Flag):
        BLACK = 0
        RED = 1
        GREEN = 2
        BLUE = 4
        WHITE = RED | GREEN | BLUE

    list(BlendColor)
    # RED, GREEN, BLUE

Aliases have always been omitted from iteration, and flag values with no, or more than one, bit(s) set are considered aliases since Python 3.11 -- this was considered a bug-fix.

**Comment by gmgunter** [comment]
Oh I see. Thanks for the clarification, @ethanfurman.

Looking back over [the docs](https://docs.python.org/3/library/enum.html) now, they do pretty much convey everything that you've explained here, although some of the details are subtle. The only thing that I think isn't explicitly explained there is that zero-valued flags are considered aliases.

**Comment by ethanfurman** [comment]
Because `f` is not a flag, it is a name for the absence of flags.

**Comment by wimglenn** [comment]
It shows up in `F.__members__`, but not in `dir(f)`. Is that intended?

**Comment by ethanfurman** [comment]
Yes.  `dir(F)` doesn't list aliases, but `__members__` does (which also prevents aliases from being overridden -- i.e. `F.f = 99` raises an `AttributeError`).

**Comment by ClundXIII** [comment]
Hi,

I do have a use case where I need both alias and elements of a flag. Is there a way to explicitly iterate over either only elements and only aliases that works in both old AND new version?

**Comment by Leo1690** [comment]
@ClundXIII  You can do this
```
from enum import IntFlag

class Bla(IntFlag):
    X = 0

list(Bla.__members__.values())
```
