### ISSUE TITLE
Python "zipfile" can't detect "quoted-overlap" zipbomb that can be used as a DoS attack

### ISSUE THREAD

**Issue by dyingc** [python/cpython#109858]
# Bug report

### Bug description:

Just found this vulnerability in the latest Python 3.11.5 (and previous 3.10.10).

If we craft a zipbomb using the "quoted-overlap" way (as mentioned [https://www.bamsoftware.com/hacks/zipbomb/](https://urldefense.com/v3/__https://www.bamsoftware.com/hacks/zipbomb/__;!!ACWV5N9M2RV99hQ!NeHC7dlBypbGhcmQALXGCNyt3gJ-N86F3rJ3GczFSLYbl0kR34I67_YZCxbseU0GGIxRGc4gcPu4Sw$)), this can't be detected by Python's zip file and the zip will be extracted and thus potentially cause a DoS attack by consuming all the storage.

This issue is related to CVE-2019-9674 but not the same. CVE-2019-9674 is talking about the "normal" overlap-zipbomb which is a "full" overlap. This can already be detected by Python's new version of zipfile. However, when we craft a "quoted-overlap" zip, as indicated by [https://www.bamsoftware.com/hacks/zipbomb/](https://urldefense.com/v3/__https://www.bamsoftware.com/hacks/zipbomb/__;!!ACWV5N9M2RV99hQ!NeHC7dlBypbGhcmQALXGCNyt3gJ-N86F3rJ3GczFSLYbl0kR34I67_YZCxbseU0GGIxRGc4gcPu4Sw$), python can't detect and happily starts to extract.

For example, the following is the python to extract a zip file, 116 KB before extraction, goes to as large as 17GB after extraction. The size after extraction can be easily increased to multi TBs or even PBs by adjusting the zip-creation.

```python
import zipfile
import sys
import os

def extract_zip(zip_path):
    """
    Extracts the contents of a ZIP file to the current directory.

    :param zip_path: Path to the ZIP file
    """
    if not os.path.exists(zip_path):
        print(f"Error: {zip_path} does not exist.")
        return

    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall()
        print(f"Extracted contents of {zip_path} to the current directory.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python extract_zip.py <path_to_zip_file>")
        sys.exit(1)

    zip_file_path = sys.argv[1]
    extract_zip(zip_file_path)
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-110016
* gh-113912
* gh-113913
* gh-113914
* gh-113915
* gh-113916
* gh-113918

**Comment by gpshead** [comment]
While we do _at least_ have an existing [warning on ZipFile.extractall() in our docs](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.extractall) _"Warning: Never extract archives from untrusted sources without prior inspection."_ - that text goes on to focus on other reasons. We expect that there are people who don't actually understand the full implications of handling untrusted compressed complex-referential data like zips and just call an API like `.extractall()` without sufficient checks regardless.

@SethMichaelLarson & @di looked into [PyPI's warehouse](https://github.com/pypi/warehouse) to check how PyPI handles this situation with regards to uploaded packages. It already has a decent seeming zip file checking loop in place that rejects zip files who's extracted size would be huge compared to the input as seen in https://github.com/pypi/warehouse/pull/13877 - that seems to reject the example zipbombs already. @pradyunsg later confirmed that while `pip` itself doesn't do such checks (it probably should) _"we do benefit from PyPI's checks in the default configuration and those benefits transfer to mirrored PyPI indexes as well."_ - so in effect we don't currently believe PyPI can host zipbomb wheels - ameliorating this for the community's `pip install` invocations by default.

## Workarounds & Recommendations

### Document the workaround

We should centralize our guidance for Python users on how to avoid the problem when processing untrusted zip files, perhaps with a code snippet such as [the overall extraction size checking loop from Warehouse](https://github.com/pypi/warehouse/pull/13877) as an example of the kinds of protection users of `zipfile` today should employ. Having applications and libraries do that is good defense in depth and doesn't require a patched Python runtime.

We also recommend that code handling untrusted zip files always run in a resource constrained container regardless.

### Fixing

Improving our `zipfile` internals to do consistency checks to raise an exception when processing zip files with overlapping sections or inconsistent metadata or whatnot (all of the kinds of things that enable this form of malicious structured file).

How feasible it'll be to backport that is unknown. But as this is only a DoS, for something that _most_ code isn't doing (processing untrusted zips), and it can be worked around, I don't think focusing on designing this backporting this all the way back to 3.8 is worth spending extra time on if it requires any.

Reaching out to specific applications that process arbitrary zip files to make sure they're aware of this issue is a good idea.

**Comment by serhiy-storchaka** [comment]
As a workaround, the following check can be used before extracting a ZIP file.

```python
# zipf is an open ZipFile
end_offset = zipf.start_dir
for zinfo in sorted(zipf.filelist,
                    key=lambda zinfo: zinfo.header_offset,
                    reverse=True):
    if zinfo.header_offset + zinfo.compress_size > end_offset:
        raise zipfile.BadZipFile('Overlapped entries')
    end_offset = zinfo.header_offset
```
You can even use simple `reversed(zipf.filelist)` instead of `sorted(...)`, because most normal files add files to the central directory in the same order as write them. But if the ZIP file was modified in-place after creation, the order can be changed, so it is up to you whether you want to support such corner case.

**Comment by gpshead** [comment]
> But if the ZIP file was modified in-place after creation, the order can be changed, so it is up to you whether you want to support such corner case.

Applications wanting to do that seem rare & overcomplicated enough that I'd just call that an application design issue corner case that we don't need to spend extra effort to worry about ourselves.

**Comment by serhiy-storchaka** [comment]
Backports already include the #113918 fix, so they can just be merged.

**Comment by pablogsal** [comment]
This is marked as a release blocker including the 3.11 tag but the issue is still open. It's there anything left here?

**Comment by serhiy-storchaka** [comment]
No. All necessary backports were merged. Thank you for the reminder.

**Comment by sparrowt** [comment]
Does anyone here have any contacts in GitHub who know about GHSA?

Their entry for this (CVE-2024-0450) https://github.com/advisories/GHSA-jm46-725r-hh9v says that 3.12.2 and 3.11.8 are vulnerable, but AFAICS those 2 versions contain the fix. I've attempted to open an improvement PR [here](https://github.com/github/advisory-database/pull/4204) but I'm not sure if it will be accepted - and the "suggest improvements" button (via which I did it) forced me to select "Affected products" where [c]python was not an option 😢

AFAICS this GHSA data feeds through into tools like Grype which currently say "Fixed?"=unknown and have no "Fixed in" so it would be good to know how to correct the record on which python versions are vulnerable/fixed.

**Comment by sethmlarson** [comment]
Thanks for reporting this @sparrowt, I'll take a look and update the CVE records accordingly. In theory this will trickle down into GitHub Security Advisories as well since they source a lot of their information from that database.

**Comment by sparrowt** [comment]
Amazing thank you! I'm not sure how the affected versions / patched versions thing is going to work given GHSA seems to only support packages within certain 'ecosystems' but seemingly not the ecosystem runtime (e.g. python) itself:
![image](https://github.com/python/cpython/assets/793763/975b4d98-eb2a-43e4-ae4e-65d87eb915f0)

**Comment by sethmlarson** [comment]
I've fixed the metadata for the CVE. I believe the "syncing" process will happen outside of the manual update process but could be wrong? The GHSA team is aware of the whole ecosystem issue for updating GHSA records.

**Comment by sparrowt** [comment]
Thanks! Sadly it's still wrong on https://github.com/advisories/GHSA-jm46-725r-hh9v
