### ISSUE TITLE
Behaviour of Counter.most_common when argument greater than len

### ISSUE THREAD

**Issue by ByteEater-pl** [python/cpython#109996]
Please document that if `Counter.most_common` is called with a number greater than there are elements in the container, the result is the same as if the number of elements were passed. Now it's completely unspecified, may even raise an exception, format the disk or launch missiles (UB).

**Comment by rhettinger** [comment]
No one seems to have ever had an issue with this.  Likely this is because It pretty much works the same as other operations such as slicing where `s[:n]` returns up to *n* items but doesn't raise for shorter inputs.

Now, if we were doing something surprising like "format the disk or launch missiles", THAT would be worth calling out.

**Comment by ByteEater-pl** [comment]
It's very easily corrected from the current underspecified status, e.g. by adding "(or all elements if there are fewer than n)" after "Return a list of the n most common elements".

If it's left as is, programmers are supposed to (lest implementations are allowed to do anything when executing their code) write `C.most_common(min(n, len(C)))` (incurring performance penalty and assuming `len` and `min` behave in the standard way) instead of `C.most_common(n)` whenever `n` may be greater.
