### ISSUE TITLE
fstring_middle and fstring_format_spec grammar rules almost the same

### ISSUE THREAD

**Issue by RobEin** [python/cpython#110173]
# Bug report

### Bug description:

The next two grammar rules are almost the same **grammatically**:
```
fstring_middle[expr_ty]:
    | fstring_replacement_field
    | t=FSTRING_MIDDLE { _PyPegen_constant_from_token(p, t) }
```

```
fstring_format_spec[expr_ty]:
    | t=FSTRING_MIDDLE { _PyPegen_decoded_constant_from_token(p, t) }
    | fstring_replacement_field
```

Only the ordered choice differs **grammatically**.
I don't know if it's a bug, but it's suspicious.

### CPython versions tested on:

3.12

**Comment by sunmy2019** [comment]
ping @pablogsal @isidentical @lysnikolaou 


```diff
diff --git a/Grammar/python.gram b/Grammar/python.gram
index 73aaa796b0..db451ba529 100644
--- a/Grammar/python.gram
+++ b/Grammar/python.gram
@@ -920,8 +920,8 @@ fstring_conversion[ResultTokenWithMetadata*]:
 fstring_full_format_spec[ResultTokenWithMetadata*]:
     | colon=':' spec=fstring_format_spec* { _PyPegen_setup_full_format_spec(p, colon, (asdl_expr_seq *) spec, EXTRA) }
 fstring_format_spec[expr_ty]:
-    | t=FSTRING_MIDDLE { _PyPegen_decoded_constant_from_token(p, t) }
     | fstring_replacement_field
+    | t=FSTRING_MIDDLE { _PyPegen_decoded_constant_from_token(p, t) }
 fstring[expr_ty]:
     | a=FSTRING_START b=fstring_middle* c=FSTRING_END { _PyPegen_joined_str(p, a, (asdl_expr_seq*)b, c) }
```

I changed it and it passed all grammar-related regression tests. So I think the order actually may not matter.

But I also think it's not worth changing it if there are no bugs, i.e. no code is affected by this.

**Comment by RobEin** [comment]
If the order doesn't matter, then I think one grammar rule is redundant.
I think some optimization would make it clearer when which rule is executed.

**Comment by lysnikolaou** [comment]
@pablogsal and @isidentical may remember this better, but I think I recall this being necessary in the early stages of development of the fstring grammar, when the work on the tokenizer was still ongoing.

It seems to me that, indeed, the order does not matter anymore, but the rule is still not redundant, cause of the decoding that happens in the action for `fstring_format_spec`. Since this has been the status quo for some months now without any bug reports and since my guess is that `FSTRING_MIDDLE` is the most prevalent token in this position resulting in a very very minor performance gain when parsing format specs, I'd say let's leave it as is.

**Comment by RobEin** [comment]
OK, on closer inspection, it really is not redundant.

**Comment by pablogsal** [comment]
Yeah is not redundant because the action is different so we need to use an entire different rule. Also we don't want to reuse pieces because we don't want to cache different ast pieces
