### ISSUE TITLE
Add support of PyStructSequence in copy.replace()

### ISSUE THREAD

**Issue by XuehaiPan** [python/cpython#110222]
# Feature or enhancement

### Proposal:

This issue is to make the concept of ["named tuple"](https://docs.python.org/3/glossary.html#term-named-tuple) support the `__replace__` protocol.

`collections.namedtuple` and `typing.NamedTuple` already support the `__replace__` protocol in:

- #108752

[`PyStructSequence`](https://docs.python.org/3/c-api/tuple.html#struct-sequence-objects)s are also [named tuples](https://docs.python.org/3/glossary.html#term-named-tuple) but they do not support the `__replace__` protocol yet.

It would be convenient if `PyStructSequence` be supported in `copy.replace()`.

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

- #108751
- https://discuss.python.org/t/generalize-replace-function/28511
- #109956
- #109174
- #109175

### Linked PRs
* gh-110223

**Comment by AlexWaygood** [comment]
@serhiy-storchaka

**Comment by XuehaiPan** [comment]
I created a PR to resolve this.

**Comment by serhiy-storchaka** [comment]
PyStructSequence with unnamed fields is a special case. Currently the only such structure is `os.stat_result`. Accessible by name fields `st_atime`, `st_mtime` and `st_ctime` are float values. Corresponding unnamed fields 7-9 are integer values. It is an old trick for compatibility. `__replace__()` can replace named fields, but unnamed fields will keep the old value. Integer and float value will be de-synchronized, and the code that reads unnamed fields will work incorrectly.

The simplest solution is to disable `__replace__()` for PyStructSequence with unnamed fields. Such structures can even be deprecated, but this is a different issue.

There may be a special implementation of `__replace__()` for `os.stat_result`, which derives values for unnamed fields from corresponding values for named fields. But float value can be less precise than integer value, because it has limited precision. So it needs to take into account `*_ns` fields. It is separate very complex issue.

**Comment by XuehaiPan** [comment]
> PyStructSequence with unnamed fields is a special case. Currently the only such structure is `os.stat_result`. Accessible by name fields `st_atime`, `st_mtime` and `st_ctime` are float values. Corresponding unnamed fields 7-9 are integer values. It is an old trick for compatibility. `__replace__()` can replace named fields, but unnamed fields will keep the old value. Integer and float value will be de-synchronized, and the code that reads unnamed fields will work incorrectly.

I can confirm this is a bug for PyStructSequence with unnamed fields if we rely on `__reduce__()`. But I'm not sure why `pickle.loads(pickle.dumps(stat))` works fine for `os.stat_result`.

> The simplest solution is to disable `__replace__()` for PyStructSequence with unnamed fields. Such structures can even be deprecated, but this is a different issue.

I agree to raise an error for this (e.g., `TypeError`) since `os.stat_result` is the only case to have unnamed fields.

> There may be a special implementation of `__replace__()` for `os.stat_result`, which derives values for unnamed fields from corresponding values for named fields. But float value can be less precise than integer value, because it has limited precision. So it needs to take into account `*_ns` fields. It is separate very complex issue.

I think it's better to disable `__replace__()` for PyStructSequence with unnamed fields.
