### ISSUE TITLE
`_pyio.IOBase.__del__` call twice

### ISSUE THREAD

**Issue by F-park** [python/cpython#110287]
# Bug report

### Bug description:
```python
import _pyio


def hook_del(__del__):
    def wrapper(self):
        __del__(self)
        print("call __del__")

    return wrapper


_pyio.IOBase.__del__ = hook_del(_pyio.IOBase.__del__)

strip_lines = (line.strip() for line in _pyio.StringIO("hello\nworld!"))
print(list(strip_lines))
```

```
call __del__
call __del__
['hello', 'world!']
```
### Affected functions:
- _pyio.StringIO
- _pyio.open

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

Windows

**Comment by sobolevn** [comment]
Hi!

```python
>>> import _pyio
>>> _pyio.IOBase.__del__ = lambda *args: print(args)
>>> 
>>> x = _pyio.StringIO("hello\nworld!")
>>> del x
(<_pyio.StringIO object at 0x105196f40>,)
(<_pyio.BytesIO object at 0x105045690>,)
```

It calls `BytesIO.__del__` the second time.
This happens because `IOBase` is a base class for both `StringIO` and `BytesIO`.
`BytesIO` is created here: https://github.com/python/cpython/blob/77e9aae3837d9f0cf87461d023896f2c4aeb282f/Lib/_pyio.py#L2643-L2646

Do you have any exact problems with that?

**Comment by F-park** [comment]
Thanks for this, it is my mistake that do not pay attention to the docstring
https://github.com/python/cpython/blob/77e9aae3837d9f0cf87461d023896f2c4aeb282f/Lib/_pyio.py#L1960-L1962
