### ISSUE TITLE
Python 3.11.5 to 3.11.6 upgrade fails: vcruntime140.dll not found

### ISSUE THREAD

**Issue by dconnet** [python/cpython#110437]
# Bug report

### Bug description:

While updating 3.11.5 to 3.11.6 using python-3.11.6-amd64.exe, installation fails multiple time while precompiling. This is on a fairly clean up-to-date Win10 system with no Visual Studio. On a system with Visual Studio, the upgrade works.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

### Linked PRs
* gh-110470
* gh-110555
* gh-110556

**Comment by zooba** [comment]
You should have a set of log files in your `%TEMP%` directory. Could you zip them up and attach them to this issue?

**Comment by dconnet** [comment]
These are all the logs (started the upgrade with a clean temp)

[InstallLogs.zip](https://github.com/python/cpython/files/12824153/InstallLogs.zip)

**Comment by dconnet** [comment]
I did forget to note: downloading vc_redist.x64.exe from MS and installing that resolves the issue. (This also affected Windows11 - I have a couple VMs for testing)

**Comment by zooba** [comment]
Hmm, it seems like somehow we ended up with an earlier version of vcruntime140.dll in the 3.11.6 release than was in the 3.11.5.

<img width="550" alt="image" src="https://github.com/python/cpython/assets/1693688/3a55cdc1-c6ee-47ed-bbe1-b81ee37f26c7">

Usually this shouldn't matter, because it's the key file and the latest version should be kept, but for some reason it was removed but not reinstalled here.

I haven't got time right now to dig any further, but I'll try and look closer at it tomorrow. Out of interest, if you uninstall 3.11.5 and then install 3.11.6 (i.e. don't do an upgrade), does it install the file?

**Comment by dconnet** [comment]
Another note: Out of curiosity, I tried the 3.12 installer - that worked.

**Comment by dconnet** [comment]
Actually, I had to uninstall 3.11.6 since the install worked - the precompile failure didn't rollback the install.
After uninstalling that and reinstalling, it did work.

**Comment by zooba** [comment]
Looks like repairing 3.11.6 will add the file back, but it definitely gets lost in the upgrade process for some reason.

**Comment by zooba** [comment]
This blog covers the reasons: https://learn.microsoft.com/en-us/archive/blogs/astebner/why-windows-installer-removes-files-during-a-major-upgrade-if-they-go-backwards-in-version-numbers

It seems that [the image used for 3.11.6](https://github.com/actions/runner-images/blob/releases/win22/20230924/images/win/Windows2022-Readme.md) replaced toolset v14.36 with v14.37, but our build used v14.35 instead. The [image for 3.11.5](https://github.com/actions/runner-images/blob/releases/win22/20230820/images/win/Windows2022-Readme.md) had both v14.35 and v14.36, but the build chose the latter. It's always supposed to choose the latest, but apparently it didn't in this case. Most likely an issue on the image.

I think the best option is going to be to manually manage the redistributable files rather than picking them up from the build machine. Now that our build machines are subject to the whims of cloud CI, we clearly can't assume we won't go backwards in version.

**Comment by zooba** [comment]
@pablogsal It's not super urgent, but it would be nice to get a 3.11.7 release out with this fix. I don't think there's a need to trigger a release just for this, but please don't delay the next one.

Also, it'd be great to get a note on the download page, something like:
> Due to an installer issue, updating from Python 3.11.5 to 3.11.6 may inadvertently remove some files. If you experience issues, run the 3.11.6 installer again and choose "Repair", or else you can manually install the [latest VCRedist](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) from Microsoft.
