### ISSUE TITLE
Python 3.12 and library aiogram

### ISSUE THREAD

**Issue by nicelight** [python/cpython#110557]
# Bug report

### Bug description:

with python 3.12 impossible to install aiogram lib through pip
getting
```
ERROR: Could not build wheels for *many packages* 
```

how i fixed: 
uninstall 3.12, install 3.11 
pip install aiogram 
Success. 
sorry for weak report

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Windows

**Comment by AlexWaygood** [comment]
It's likely that this is caused by third-party packages not yet being compatible with Python 3.12, which isn't an issue we can help with -- you'll have to file issues with those third-party projects. But without being able to see the error messages pip gave you, it's impossible to be tell exactly what the problem is. Please copy and paste the entire output pip printed to your terminal.

**Comment by neomachiney** [comment]
Likely an aiohttp issue

**Comment by dtrodrigues** [comment]
The next release will support Python 3.12: https://github.com/aio-libs/aiohttp/issues/7675

**Comment by codermilioner** [comment]
bruh
