### ISSUE TITLE
Python pip broken out of the box - issue raised in 2021 still present

### ISSUE THREAD

**Issue by LeavingAtSix** [python/cpython#110518]
# Bug report

### Bug description:

Pip not running successfully after Microsoft Store install. Python 3.11.6

High level issue raised many times and at least since 2021.  Kindly push to board level and ask if Python pip should work out of the box after Windows App Store install. The documentation says it does.

This is a flavour:
```
 pip install tartan
 Collecting tartan
   Using cached tartan-0.1.3-py2.py3-none-any.whl (6.1 kB)
 Collecting pillow==7.0.0 (from tartan)
   Using cached Pillow-7.0.0.tar.gz (38.2 MB)
   Installing build dependencies ... done
   Getting requirements to build wheel ... done
   Preparing metadata (pyproject.toml) ... done
 Building wheels for collected packages: pillow
   Building wheel for pillow (pyproject.toml) ... error
   error: subprocess-exited-with-error
 
   × Building wheel for pillow (pyproject.toml) did not run successfully.
   │ exit code: 1
   ╰─> [197 lines of output]
       <string>:42: RuntimeWarning: Pillow 7.0.0 does not support Python 3.11 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
       running bdist_wheel
       running build
       running build_py
       creating build
 
 .....
 
 
       The headers or library files could not be found for zlib,
       a required dependency when compiling Pillow from source.
 
       Please see the install instructions at:
          https://pillow.readthedocs.io/en/latest/installation.html
 
 
       [end of output]
 
   note: This error originates from a subprocess, and is likely not a problem with pip.
   ERROR: Failed building wheel for pillow
 Failed to build pillow
 ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects
```

This is a high level installation issue.  As recommended by Microsoft only install apps from  Microsoft Store, or I can also use pip.  This issue is so common it will be wasting tens of thousands of hours a year. Kindly push to board level and ask if Python including pip should work out of the box from the Microsoft Store.

If you're not going to fix, there documentation is wrong and needs an update, as it implies Python, including pip, works out of the box.

[ https://docs.python.org/3/using/windows.html#the-microsoft-store-package](https://docs.python.org/3/using/windows.html#the-microsoft-store-package
)
4.2. The Microsoft Store package
New in version 3.7.2.

The Microsoft Store package is an easily installable Python interpreter that is intended mainly for interactive use, for example, by students.

To install the package, ensure you have the latest Windows 10 updates and search the Microsoft Store app for “Python 3.12”. Ensure that the app you select is published by the Python Software Foundation, and install it.

Warning Python will always be available for free on the Microsoft Store. If you are asked to pay for it, you have not selected the correct package.
After installation, Python may be launched by finding it in Start. Alternatively, it will be available from any Command Prompt or PowerShell session by typing python. **Further, pip and IDLE may be used by typing pip or idle.** IDLE can also be found in Start.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
This is not the issue tracker for pip or the MS Store build of Python, but both appear to have run as best possible in the reported episode. 

The only thing obviously broken is that you tried to install on 3.11 a package [tartan](https://pypi.org/project/tartan/) that was last upgraded to work on 3.8.  You should have looked at that page yourself before trying to install or at least after the failure, rather than reporting and ranting here.

As pip informed you, the 3.8 tartan requires an old 3.8 version of `pillow`, 7.0.0.  The latter does not provide a 3.11 build (wheel) as it was uploaded to pypi years before 3.11.  (The current [pillow version](https://pypi.org/project/Pillow/) is 11.0.0.)  Pip could have stopped there, but tried to do more just in case.  It did not work.

If you want to run tartan, you could install 3.8, ask the tartan developer to release an update (and wait), or try to make it work on 3.11 yourself.  If you need more help, try elsewhere, such as stackoverflow.com or [python discourse](https://discuss.python.org/c/users/7).   If you do, please be polite and drop the rant.

**Comment by LeavingAtSix** [comment]
Thank you for promptly confirming you don't care about supporting legacy code, even is if it 3.8 and not really that old. I only expect breaks with a major release change e.g. from Python 2.x to 3.x.

**Comment by LeavingAtSix** [comment]
Thanks again for your recommendation to use 3.8.  It is now working.

**Comment by zooba** [comment]
> This is not the issue tracker for pip or the MS Store build of Python

@terryjreedy This is, in fact, the issue tracker for the Windows Store build of Python. It's exactly the same build as released on python.org, published via the PSF, and has no formal links to Microsoft.

The `python.exe` built into Windows that opens to our Store page, however, is not covered by this repo. Issues with that should be reported directly to Microsoft via the Windows Feedback tool.
