### ISSUE TITLE
Pip install results in ERROR: Could not build wheels for aiohttp

### ISSUE THREAD

**Issue by tedhudek** [python/cpython#110846]
# Bug report

### Bug description:

Install Python 3.12 for Windows (64 bit).

```python
py -3.12 -m venv venv
.\venv\Scripts\activate
py -3.12 -m pip install openai
```

Result:

(at end of output)
ERROR: Failed building wheel for aiohttp
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp, which is required to install pyproject.toml-based projects

Works fine on 3.11.6.  A related thread describes the same problem on 3.11 but working fine on 3.10.6:

https://stackoverflow.com/questions/74550830/error-could-not-build-wheels-for-aiohttp-which-is-required-to-install-pyprojec.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by gaogaotiantian** [comment]
This is because aiohttp has not supported 3.12 (they do not have wheels for 3.12 so you need all the build pre-requirements to build it from source). This is not a CPython issue - also I think it's reported before. Please ask aiohttp to build 3.12 wheels :)

**Comment by AlexWaygood** [comment]
This is an issue with aiohttp, which needs to be reported at the aiohttp bug tracker, not the CPython bug tracker.

Having said that, the solution to your problem is probably to install `aiohttp==3.9.0b0`, which is the first release to support Python 3.12. Please see https://github.com/aio-libs/aiohttp/issues/7675

**Comment by tedhudek** [comment]
Thanks, do you know if the same is true of tiktoken?  Was getting the same error there.  Also curious why the same problem happened (the stackoverflow link I included) where it didn't work with Python 3.11 but was ok with 3.10.6.  Is it that each module has to come out with a new release to support each new Python release?

**Comment by AlexWaygood** [comment]
aiohttp uses a C extension, and packages that have C extensions often need to make changes in order to become compatible with new versions of Python.

For more information, please start a thread at discuss.python.org, which is a better place to ask these kinds of questions — this bug tracker is meant to be for bugs in CPython, and this isn't a bug in CPython :)

**Comment by tedhudek** [comment]
Thanks Alex, appreciate the help.
