### ISSUE TITLE
unittest.TestResult.testsRun no longer counts skipped tests.

### ISSUE THREAD

**Issue by felixxm** [python/cpython#110890]
# Bug report

### Bug description:

`unittest.TestResult.testsRun` no longer counts skipped tests in Python 3.13.0a1. I couldn't not find anything in the release notes, so maybe it's not an intended change :thinking: If it was changed on purpose I can adjust [our test](https://github.com/django/django/blob/73b2c63127297e214d3bfdc8d9a96837691fc2a0/tests/test_utils/tests.py#L159-L186). Thanks!

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
Which module are we talking about here?

**Comment by felixxm** [comment]
> Which module are we talking about here?

`unittest`

**Comment by terryjreedy** [comment]
Intentional change viewed as a bugfix.

The 3.13 [changelog](https://docs.python.org/3.13/whatsnew/changelog.html#changelog) lists this bugfix issue:
[gh-106584](https://github.com/python/cpython/issues/106584): Fix exit code for unittest if all tests are skipped.
The corresponding [PR 106588](https://github.com/python/cpython/pull/106588) starts "Increase the number of running tests only if a test hasn't been skipped."  This was merged into 3.13 a week before 3.12.0 was released and the backport was deferred until after that release to appear in 3.12.1.  In the [diff](https://github.com/python/cpython/pull/106588/files), the call to result.startTest, which increments `testsRun`, in moved below the skip return with comment "# Increase the number of tests only if it hasn't been skipped".

**Comment by felixxm** [comment]
> Intentional change viewed as a bugfix. In the 3.13 [changelog](https://docs.python.org/3.13/whatsnew/changelog.html#changelog) changelog: [gh-106584](https://github.com/python/cpython/issues/106584): Fix exit code for unittest if all tests are skipped. The corresponding [PR 106588](https://github.com/python/cpython/pull/106588) starts "Increase the number of running tests only if a test hasn't been skipped." This was merged into 3.13 a week before 3.12.0 was released and the backport was deferred until after that release to appear in 3.12.1. In the [diff](https://github.com/python/cpython/pull/106588/files), the call to result.startTest, which increments `testsRun`, is moved below the skip return with comment "# Increase the number of tests only if it hasn't been skipped".

@terryjreedy Many thanks for the detailed explanation :star2:
