### ISSUE TITLE
asyncio.Timeout raises AttributeError when not used in loop

### ISSUE THREAD

**Issue by Gobot1234** [python/cpython#111085]
# Bug report

### Bug description:

```py
    async def __aenter__(self) -> "Timeout":
        self._state = _State.ENTERED
        self._task = tasks.current_task()
        self._cancelling = self._task.cancelling()  # AttributeError
        if self._task is None:
            raise RuntimeError("Timeout should be used inside a task")
        self.reschedule(self._when)
        return self
```
Honestly I don't know how to get this to error but it's possible according to the types

### CPython versions tested on:

3.13, CPython main branch

### Linked PRs
* gh-110910
* gh-111111
* gh-111171
* gh-111172

**Comment by Gobot1234** [comment]
It accesses self._task while it could still be None before the is None check

**Comment by gvanrossum** [comment]
Got it. Do you want to send a PR?

**Comment by Gobot1234** [comment]
The PR is already sent :)

**Comment by gvanrossum** [comment]
Oh wait. You started with the PR. A bit unconventional. :-)

I don’t think I am needed here.

**Comment by serhiy-storchaka** [comment]
The problem is larger and more complex than it looked. It applies as well to `TaskGroup`.

* The valid state is not always checked.
* If it is checked, sometimes `assert` is used for this, even if the condition can be false.
* If an exception is raised, it can left the object in inconsistent state which breaks checks in the following operations.

It was also not trivial to write tests for this. So I created a new PR #111111.
