### ISSUE TITLE
`datetime` module should provide timezone awareness checks

### ISSUE THREAD

**Issue by jakob-keller** [python/cpython#111177]
# Feature or enhancement

### Situation
[Documentation of the `datetime` module](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects) states that:

> Date and time objects may be categorized as “aware” or “naive” depending on whether or not they include timezone information.

Documentation of the `datetime` module also defines how to [determine if an object is aware or naive](https://docs.python.org/3/library/datetime.html#determining-if-an-object-is-aware-or-naive).

This check needs to be performed frequently in application code, e.g. as part of input validation and/or normalization.

Multiple third-party packages implement awareness checks and helpers:
* `Django`: https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.timezone.is_aware
* `peprock`: https://github.com/Ponte-Energy-Partners/peprock/blob/main/peprock/datetime/awareness.py (disclaimer: I'm the author of `peprock`)
* ...

As of now, no such checks are offered by the Python standard library.

### Problem
Any Python user that needs to check for timezone awareness needs to either implement the checks herself or rely on third-party libraries. This is more cumbersome than it needs to be.

### Solution
The Python standard library should offer timezone awareness checks as part of the `datetime` module.

There are several implementation options available, including:
1. `is_naive(__obj)` and/or `is_aware(__obj)` helper functions
2. `is_naive` and/or `is_aware` properties on the level of "date and time objects"

While 1.) is typically followed by third-party packages, IMO Python should implement 2.) as part of the `datetime` module.

Proposed API: 

```python
import datetime

# `datetime.date` objects
d = datetime.date.today()
assert d.is_naive is True
assert d.is_aware is False

# `datetime.datetime` objects
naive_dt = datetime.datetime.now()
assert naive_dt.is_naive is True
assert naive_dt.is_aware is False

aware_dt = datetime.datetime.now(tz=datetime.timezone.utc)
assert aware_dt.is_naive is False
assert aware_dt.is_aware is True

# `datetime.time` objects
naive_t = naive_dt.time()
assert naive_t.is_naive is True
assert naive_t.is_aware is False

aware_t = aware_dt.timetz()
assert aware_t.is_naive is False
assert aware_t.is_aware is True
```

The signature of these proposed `is_naive` and `is_aware` properties may optionally be specified as a `typing.Protocol`.

I could try to prepare a PR, if there is sufficient interest.

What do you think?

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-111193

**Comment by jakob-keller** [comment]
I prepared a draft PR #111193 that covers the Python implementation, but without the required C changes. Anyone able to collaborate on this?

**Comment by pganssle** [comment]
On first blush, this seems like a reasonable feature to add, the only thing that worries me here is that I'm finding it hard to come up with reasonable use cases for figuring out whether a datetime is aware or naive (other than possibly to throw errors — maybe I think of static typing too automatically since it feels like you could use `DateType` to specify your interface and then not incur the runtime cost of checking for awareness on input). Both the examples here are helper functions, so they're not directly using it, just making it available for other people to use. This reminds me a bit of the `dst()` method, which exposes information that is (sort of) in the time zone database, but is also effectively _never_ useful. The only time I use it or see anyone using it correctly is when they are implementing interfaces trying to be compatible with other interfaces that also expose this information.

I think there are basically three interfaces that would accept `datetime`:

1. Requires `datetime` to be aware and considers naive datetimes to be ill-defined. You could use this method to error out early rather than somehow documenting the contract (either with static types or in documentation) and letting the program error out naturally when it hits something it can't handle.
2. Accepts both naïve and aware `datetime`s and interprets naïve datetimes to be [local times](https://blog.ganssle.io/articles/2022/04/naive-local-datetimes.html). In this case, it would mostly be just an optimization to care about whether or not it's naïve because you can almost always do something like call `dt.astimezone()` or `dt.timestamp()` or `dt.astimezone(datetime.utc)` unconditionally and use that for operations that require an absolute time.
3. Accepts both naïve and aware `datetime`s and interprets the naïve ones in some other way, like considering them to be UTC times. This is probably dangerous (see [Stop using `utcnow` and `utcfromtimestamp`](https://blog.ganssle.io/articles/2019/11/utcnow.html)), and having methods like this may in fact be [an attractive nuisance](https://blog.ganssle.io/articles/2023/01/attractive-nuisances.html) if it encourages more of this kind of thing.

I think it mostly comes down to whether the majority of people who might find this method would be in one of the situations where the use would be appropriate, or whether it's basically going to create a whole bunch of new interfaces where naïve `datetime`s are considered to be UTC. All that said, my guess is that people who are going to create new interfaces where naïve times are considered UTC are just going to do `if dt.tzinfo is None: dt = dt.replace(tzinfo=UTC)`, which is both easy enough that it's not deterring anyone from writing bad code and also subtly wrong, so this feature is probably net positive. I'd say I'm +0.5 on it.

A few details that I am discussing here rather than on the PR, since they are about the general feature design and not necessarily the specifics of that PR:

1. I don't think we need separate `is_naive` and `is_aware` methods, since `dt.is_aware == not dt.is_naive`. I would probably say `is_aware` is the right one to choose.
5. I am not sure how I feel about them being properties. I think it hides the fact that the calculation may be expensive. I would say this should be a method to make it clear what's happening.
6. `date` doesn't need an implementation for this, since the concept of awareness does not currently apply to `dates` (though TBH if either `date` or `time` is going to have one, it should probably be `date`). I suppose the main reason you would want this is if you want some interface that can take either `date` or `datetime` and you want to do something like convert the time zone if the thing is aware and otherwise do nothing, so you want to avoid things like `if isinstance(d_or_dt, datetime) and d_or_dt.is_aware()`? Not sure if this is a strong motivation (and also see my note below about another potential option).
7.  Since `datetime`s are immutable, I'm also inclined to cache the value somewhere, but I am aware that there is somewhat limited space in the `datetime` struct before we hit another alignment boundary and people start seeing the actual size of these things increase in memory, which probably wouldn't be great. Probably 1 bit won't make much difference. This should be a backwards-compatible change if we want to make it in the future, so we can put off a decision about that until later versions unless everyone strongly agrees in one direction or the other.
8. As always with this sort of thing, bikeshedding about the name. Over time I've learned that many people don't know the "aware/naive" terminology with regards to `datetime`s, and won't realize that it refers to time zones. To be clearer, we might want a method named `is_timezone_aware` or `is_tz_aware` instead of `is_aware`.

I also recall that for lack of higher-kinded types, we decided that [`DateType`](https://pypi.org/project/datetype/) probably can't currently live in `typeshed` or the standard library, but I wonder if this might be a reasonable use case for importing a limited version of the date types that can be used in `isinstance` checks. It might be more expensive than a method call (and certainly more expensive than a cached one), but if we had `NaiveDateTime` and `AwareDateTime` in the standard library, that would encapsulate the same information (and work well with `DateType` and/or a future world where the standard library just has the equivalent of `DateType` in it). It would also sort of sidestep the problem of whether or not `date` should have this method. If you have some function that can take either a `date` or a `datetime`, you can check `isinstance(d_or_dt, NaiveDateTime)` to know whether its both a `datetime` and naïve. I am not really a big pattern-matching user, but I can also imagine it playing nicely with that, for example:

```
def is_after_random_epoch(d: date | datetime | time) -> bool:
    match d:
        case date(x):
            return x > RANDOM_EPOCH.date()
         case NaiveDateTime(x):
            return x.astimezone() > RANDOM_EPOCH
         case AwareDateTime(x):
            return x > RANDOM_EPOCH
        case time(x):
            return datetime.combine(datetime.now().date(), x).astimezone() > RANDOM_EPOCH
````

Obviously that's not a terribly compelling example since you can just call `.astimezone(...)` on *any* `datetime` if that is what you are worried about, but as I said I rarely find places where the `match` statement is a particularly compelling choice. Plus as I mentioned above I am not sure how often one actually really needs / wants this information, but presumably there are people who like match statements and would appreciate this kind of thing?

**Comment by jakob-keller** [comment]
@pganssle: Thank you for taking the time to thoroughly evaluate my proposal. Much appreciated!

> I'm finding it hard to come up with reasonable use cases for figuring out whether a datetime is aware or naive (other than possibly to throw errors...).

*Throwing errors* is an obvious use case that comes to mind. When working with `datetime` objects in library-type codebases, I prefer timezone-aware objects, as is encouraged. In the absence of static typing support, I resort to timezone-awareness checks for argument validation. The `datetime` module documentation provides clear and simple definitions, but:
* having to reimplement these checks over and over again feels like a violation of the DRY principle to me
* providing a definitive implementation avoids subtle issues stemming from different implementations (e.g. Django performs a simplified check that does not match the documentation)
* I would expect the C implementation that @sobolevn provided as part of #111193 to be more performant

> 1. I don't think we need separate `is_naive` and `is_aware` methods, since `dt.is_aware == not dt.is_naive`. I would probably say `is_aware` is the right one to choose.

Makes sense to me. I will update the PR, if there's consensus to go ahead.

> 2. I am not sure how I feel about them being properties. I think it hides the fact that the calculation may be expensive. I would say this should be a method to make it clear what's happening.

Makes sense to me. I will update the PR (hopefully with the help of @sobolevn), if there's consensus to go ahead.

> 3. `date` doesn't need an implementation for this, since the concept of awareness does not currently apply to `dates` (though TBH if either `date` or `time` is going to have one, it should probably be `date`).

I cannot think of a good use case either. My reason for proposing an implementation for `date` objects was that the [`datetime` module documentation](https://docs.python.org/3/library/datetime.html#determining-if-an-object-is-aware-or-naive) explicitly states:

> Objects of the [date](https://docs.python.org/3/library/datetime.html#datetime.date) type are always naive.

Is this sensible and helpful? Otherwise, it might warrant a documentation update instead of the implementation.

The same goes for `time` objects.

> 4. Since `datetime`s are immutable, I'm also inclined to cache the value somewhere.

I had initially considered a `functools.cached_property` decorator for the Python implementation, but the check is rather light-weight IMO. The C implementation should already be faster than the status quo. 

> 5. As always with this sort of thing, bikeshedding about the name. Over time I've learned that many people don't know the "aware/naive" terminology with regards to `datetime`s, and won't realize that it refers to time zones. To be clearer, we might want a method named `is_timezone_aware` or `is_tz_aware` instead of `is_aware`.

Makes sense to me. This also touches upon the concept of abstract and concrete datetimes that you [discussed on your blog](https://blog.ganssle.io/articles/2019/11/utcnow.html). If one updates the documentation accordingly, the name could also be `datetime.is_abstract()` (not to be confused with the `abc` module) or `datetime.is_concrete()`.

👍🏻 I'm pro implementation, but won't be sad if we decide against it.

**Comment by glyph** [comment]
> CC @glyph Any thoughts on the idea of a potentially backwards / third-party compatible version of `DateType` without the full power of `DateType` being added here?

It's going to take me a few days to digest this and write a response, but I just wanted to say that I saw it :)

**Comment by glyph** [comment]
`datetype` somewhat sidesteps the issue of naive timezones which *do* have a non-`None` `tzinfo` but that `tzinfo`'s `utcoffset` returns `None`.  Given that `ZoneInfo` objects return `utcoffset`s from the year 1 to the year 5000, I'd not anticipated a case where I'd need to care about that.  What exactly is the *purpose* of allowing `utcoffset` to return `None` sometimes, rather than simply raise an exception?  I've never seen this happen and I don't know what it would mean if I did.

Personally, what my experience with `datetype` points to is that "aware"  and "naive" are insufficient distinctions, because what I've actually wanted to know in the few cases I've used it thus far are not just "do you have a timezone" but "what exact type can I rely on from your timezone" since different types of timezones have different features.  And by turning `datetime` into a `Generic`, you can easily establish the "`utcoffset` can never return `None`".

Making `is_aware` (and/or `is_naive`) a run-time feature rather than trying to embed it in the type system seems like a step in the wrong direction.  So I'd be much more in favor of stealing `datetype`'s `__instancecheck__`, and asking this question in terms of dedicated `isinstance` checks, so that a type guard is established both by the actual logic in mypy, but also by existing convention so that neither other type-checking implementations nor the user's brain needs to learn something new.

The protocol with this custom `__instancecheck__` could be more sophisticated than `datetype`'s, and actually runtime-check the result of `utcoffset` to make sure that it's *properly* not-naive, but that will also give you a `Protocol` that usefully constrains the expectations on the `tzinfo` as well; no need for `None`-checking `utcoffset` once you've done this.

So I'd be -1 on adding a literal method, but at least +0 on adding a type that can be used in the same way as that method would be.

The amount of actual code from `datetype` useful to this is literally 5 or 6 lines, and as I said it'd need to be modified anyway, so I don't know if "including it" would really help solve the problem here.  But let me know if I've missed something, I'm happy to relinquish copyrights or do whatever paperwork would be required to move this forward.

**Comment by jakob-keller** [comment]
@glyph Thanks a lot for your insights!

To summarize, my proposal to add `is_aware` and/or `is_naive` properties to date and time objects does not pose an elegant solution to their inherent ambiguity. I will turn #111193 into a draft for the time being, with the expectation for it to be closed in the future.

Who would be interested in advancing the `Generic` / `Protocol` approach? I don't feel well enough versed in this codebase to contribute much further, especially since the `datetime` module is (also) implemented in C.

**Comment by glyph** [comment]
> Who would be interested in advancing the `Generic` / `Protocol` approach? I don't feel well enough versed in this codebase to contribute much further, especially since the `datetime` module is (also) implemented in C.

I am not quite sure, structurally, how to add this, but if someone more familiar with the process would like to pair with me to get me started, i could give it a shot

**Comment by ariebovenberg** [comment]
> Personally, what my experience with `datetype` points to is that "aware" and "naive" are insufficient distinctions, because what I've actually wanted to know in the few cases I've used it thus far are not just "do you have a timezone" but "what exact type can I rely on from your timezone" since different types of timezones have different features.

This also jibes with my experience. `tzinfo=datetime.UTC`and `tzinfo=ZoneInfo(...)` are very different beasts, even though they are both 'aware'. For example, ZoneInfo is messy and ambiguous, while `UTC` is super clear and fast.

Drawing inspiration from other languages and @pganssle's [post](https://blog.ganssle.io/articles/2022/04/naive-local-datetimes.html), I'd contend for these distinct cases:

- UTC
- Fixed offsets
- IANA timezones
- system local
- naive 

(If you're interested I did a [detailed exploration](https://github.com/ariebovenberg/whenever#quickstart) to see what this would look like.)

---

> Who would be interested in advancing the Generic / Protocol approach? I don't feel well enough versed in this codebase to contribute much further, especially since the datetime module is (also) implemented in C.

Regarding `Generic`: do you mean something like `DateTime[ZoneInfo]`, `DateTime[UTC]`, and `DateTime[datetime.timezone]`? The disadvantage with this approach is that type-checkers running in strict mode won't allow you to omit the generic parameter, even while this is perfectly valid in some cases:

```python
def is_thursday_afternoon(
    d: DateTime  # no generic parameter, since the function works on all types of datetime
) -> bool:
    return d.weekday() == 3 and d.hour >= 12
```

**Comment by jakob-keller** [comment]
Thank you for all the feedback! I feel that it is time to close this issue, but maybe the discussion will help inform others in the future.

**Comment by glyph** [comment]
> ```python
> def is_thursday_afternoon(
>     d: DateTime  # no generic parameter, since the function works on all types of datetime
> ) -> bool:
>     return d.weekday() == 3 and d.hour >= 12
> ```

This is more of a feature request from the type checkers, since one way for a "strict" mode to work would be to interpret this as `DateType[bound]` where `bound` is `object` (or as close to it as you can get, given the TypeVar's specified bound, so, in this case, `None | datetime.tzinfo`).

It's true that it's a little annoying to have to spell it out, but quite often you need the generic to propagate anyway, so you can do `def thunk(d: DateTime[T]) -> Time[T]` or whatever.

**Comment by glyph** [comment]
> Regarding `Generic`: do you mean something like `DateTime[ZoneInfo]`, `DateTime[UTC]`, and `DateTime[datetime.timezone]`?

Yes: https://github.com/glyph/DateType/blob/0ff07493bc2a13d6fafdba400e52ee919beeb093/src/datetype/__init__.py#L361

**Comment by ariebovenberg** [comment]
> Yes: https://github.com/glyph/DateType/blob/0ff07493bc2a13d6fafdba400e52ee919beeb093/src/datetype/__init__.py#L361

Interesting! Was there any advantage to using generics instead of simple subclasses like `ZoneInfoDateTime`, `UTCDateTime` and `TimezoneDateTime` (all with a common base `AwareDateTime`)?

**Comment by glyph** [comment]
> > Yes: https://github.com/glyph/DateType/blob/0ff07493bc2a13d6fafdba400e52ee919beeb093/src/datetype/__init__.py#L361
> 
> Interesting! Was there any advantage to using generics instead of simple subclasses like `ZoneInfoDateTime`, `UTCDateTime` and `TimezoneDateTime` (all with a common base `AwareDateTime`)?

Yes. Specifically, I need it for this:

https://github.com/glyph/Fritter/blob/e01a35f792d38f7861fde901b3912568851be654/src/fritter/persistent/json.py#L691-L712

https://github.com/glyph/Fritter/blob/e01a35f792d38f7861fde901b3912568851be654/src/fritter/persistent/json.py#L792-L808

I suppose `ZoneInfoDateTIme` could have had the same annotation of `tzinfo: ZoneInfo`, but that is just a generic by a different name, with a bunch of `type:ignore`'s about illegal overrides in place of a clean `TypeVar`.
