### ISSUE TITLE
Update Windows builds to use latest zlib

### ISSUE THREAD

**Issue by SharpMan** [python/cpython#111239]
# Bug report

### Bug description:

A new version of zlib is out: 1.3 - https://zlib.net/

zlib 1.2.13 has [CVE-2023-45853](https://nvd.nist.gov/vuln/detail/CVE-2023-45853)
https://www.openwall.com/lists/oss-security/2023/10/20/9

minizip is part of the contrib directory in zlib, but we do not appear to use this API. The CVSS v3 score is 9.8.

We would rather patch Python to use the latest library because people will ask us about that CVE.

### CPython versions tested on:

3.11, 3.12, 3.13

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-111242
* gh-114877
* gh-115076
* gh-115079
* gh-115080
* gh-115086
* gh-115087

**Comment by zware** [comment]
There is not a release with a fix for CVE-2023-45853 yet, and we aren't using the affected API anyway.  We should probably update 3.13 to 1.3.1 when it becomes available, and probably update 3.11-3.12 to 1.2.14 if it appears.  But until there's a release, there's nothing for us to do here.  As such, I'm going to go ahead and close the current PR but leave this issue open.

Thanks for bringing this to our attention!

**Comment by zware** [comment]
I'm going to mark this as a 'deferred-blocker': we don't want to forget about it before final releases, but it's also not a release blocker.

**Comment by zware** [comment]
@python/release-managers-in-development-maintenance-and-security-mode: `main` is now updated to use 1.3.1.  Given the following:

- We were never vulnerable to the CVE that started this issue
- The CVE-2023-45853 link on GitHub now shows the vulnerability to be against the `pyminizip` package on PyPI rather than `zlib` itself, so there's arguably not even a link back to CPython from it anymore anyway
- There doesn't appear to be a zlib 1.2.14 expected
- It's not clear how SemVer-y `zlib` is anyway

How far do we want to backport the update?  I can see arguments for backporting to 3.8-3.12, 3.11-3.12, or not at all, so I'll leave it up to you all to set the backport labels you want on #114877 or close this issue :)

**Comment by zware** [comment]
Upgrading to `release-blocker` for <=3.12.

**Comment by Yhg1s** [comment]
Has this been backported to 3.12 yet? (3.12.2 is scheduled for today.)

**Comment by zooba** [comment]
Since there's a CVE attached, I vote for backporting all the way. Even if it doesn't affect us, users regularly fail to recognise that, and we'll get called out for not shipping security fixes in our security releases (all builds on Windows will default to the version we have in the repo - overriding is possible, but it's not automatic).

Plus if another actual security issue comes up, we'll potentially have had some experience with any other changes by then.

**Comment by zware** [comment]
> I thought [#111239 (comment)](https://github.com/python/cpython/issues/111239#issuecomment-1925484971) meant it was decided.

Sorry for the confusion, was just trying to raise visibility before impending releases.

**Comment by lanzkron** [comment]
Am I missing something? I just installed Python 3.12.7 and got zlib1.dll v 1.2.13.0.

**Comment by zware** [comment]
It looks like `zlib1.dll` is just for Tcl/Tk, and probably is actually v1.2.13.  I believe the `zlib` used by Python itself is statically linked, and is actually v1.3.1 (see `zlib.ZLIB_VERSION`).
