### ISSUE TITLE
Complementary re patterns such as [\s\S] or [\w\W] are much slower than . with DOTALL 

### ISSUE THREAD

**Issue by pan324** [python/cpython#111259]
# Bug report

### Bug description:

```python
import re
from time import perf_counter as time

p1 = re.compile(r"[\s\S]*")
p2 = re.compile(".*", re.DOTALL)

s = "a"*10000
for p in (p1,p2):
    t0 = time()
    for i in range(10000): _=p.match(s)
    print(time()-t0)
```
Runtimes are 0.44 s vs 0.0016 s on my system. Instead of simplification, the [\s\S] is stepped through one after another. \s does not match so then \S is checked (the order [\S\s] is twice as fast for the string here). This is not solely an issue for larger matches. A 40 char string is processed half as fast when using [\s\S]. Even 10 chars take about 25% longer to process. I'm not completely sure whether this qualifies as a bug or an issue with documentation. Other languages don't have the DOTALL option and always rely on the first option. Plenty of posts on SO and elsewhere will thus advocate using [\s\S] as an all-matching regex pattern. Unsuspecting Python programmers such as @barneygale may expect [\s\S] to be identical to using a dot with DOTALL as seen below.

@serhiy-storchaka

https://github.com/python/cpython/blob/9bb202a1a90ef0edce20c495c9426d9766df11bb/Lib/pathlib.py#L126-L133

### CPython versions tested on:

3.11, 3.13

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-111303
* gh-120742
* gh-120745
* gh-120813
* gh-120814

**Comment by pan324** [comment]
Is there a document of slow and fast patterns for the Python regex engine? I just stumbled across this pattern here by chance.

If it does work as expected then I think it cannot qualify as a bug in `pathlib`.

Feel free to set different labels that match the issue more closely.

**Comment by serhiy-storchaka** [comment]
- [ ] Use more efficient pattern `(?s:.)` instead of `[\s\S]` in `pathlib`.
- [ ] Explicitly document `(?s:.)` (and maybe other idiomatic patterns).
- [ ] (?) Compile `[\s\S]` in the same opcode as `(?s:.)`.

I see that `[\s\S]` is used in third-party code, for example in `pyparsing` and `pygments`. I am not even sure that `[\s\S]` and `[\w\W]` are always equivalent to `(?s:.)`. Currently it is true, but it is because the support of the Unicode standard (https://www.unicode.org/reports/tr18/) in the `re` module is so loose. After resolving #44795 it may no longer be true, at least for `[\w\W]`. So I am not sure about making such optimization automatically.
