### ISSUE TITLE
os.close()ing a file descriptor can cause variable assignments to be skipped

### ISSUE THREAD

**Issue by keller-tophat** [python/cpython#111287]
# Bug report

### Bug description:

Simplest recreating example is:

```python
import os

x = open(__file__)
os.close(x.fileno())
x = open(__file__)
x.read()
```
```
Traceback (most recent call last):
  File "/Users/keller/Downloads/test.py", line 6, in <module>
    x.read()
OSError: [Errno 9] Bad file descriptor
```

This also works when the files are completely different:

```bash
touch foo bar
```

```python
import os

x = open("foo")
os.close(x.fileno())
x = open("bar")
x.read()
```

It also works on other file like objects that aren't `_io.TextIOWrapper` objects:

```python
import os, select

x = select.epoll()
os.close(x.fileno())
x = select.epoll()
x.poll(0, 1)
```

I first found the problem around asyncio where it uses either epoll or kqueue depending on the system. Example of it in action with asyncio:

```python
import asyncio, os

async def foo():
    pass

async def main():
    await foo()

    if not os.fork():
        exit()

    await foo()

asyncio.run(main())
```

I've tested this against versions dating back as far as Python 2.7 all the way to 3.13.0a1. I've tested this on Linux, MacOS, and OpenBSD.

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13

### Operating systems tested on:

Linux, macOS, Other

**Comment by JelleZijlstra** [comment]
I guess what happens here is:

- We open a file, producing file descriptor (fd) N, and get a file object wrapping it
- We `os.close` that fd, but don't tell the file object about it
- We open the file again, and the OS gives us the same fd again (because the previous one was closed), and get a file object wrapping it
- Now we assign that file to the name `x`. That means that the old file object is no longer referenced and gets garbage collected. In its destructor, it closes its file descriptor, because it doesn't know that we already closed it. But that fd is now valid again, as we opened a new file that happened to reuse the same fd.
- And now we try to read from that fd, but we can't, because the destructor of the first file closed it.

I don't see a bug here. Directly manipulating the file descriptor underlying a file object is inherently tricky, and can cause weird issues like the one you see here.

**Comment by keller-tophat** [comment]
That's fair. I've been hunting down an issues around asyncio that had somewhat mysterious bad file descriptor issues when trying to run functions on the event loop. I'd happened across this which explains much of the behaviour I found where a system that executes something in the default loop before the program forks can end up with a broken event loop because the descriptor is closed implicitly in the fork but can't open it again because of the overload. That's more the actual issue I'm having, the simplified `os.close()` is what a suspect is most at issue as opposed to the asyncio and select modules.
