### ISSUE TITLE
Update design FAQ 'switch' entry mention of `match-case`.

### ISSUE THREAD

**Issue by dascritch** [python/cpython#111307]
# Documentation

**Describe the bug**
I did a search to remember what was the `switch` keyword in Python, and the very first link I got is a not up-to-date page from Python 3.11 documentation, explaining that `elif` is great.

**To Reproduce**
1. Go to <https://docs.python.org/3.12/faq/design.html>
2. Click on [Why isn’t there a switch or case statement in Python?](https://docs.python.org/3.12/faq/design.html?highlight=switch#why-isn-t-there-a-switch-or-case-statement-in-python)
4. `match case` isn't cited, but the catastrophic `elif` cascade is still the “reference”

**Expected behavior**
Correct it and explain why `match case` is a really better coding practice instead of cascaded `elif` (unreadable, unmaintainable, confuse)

Sidenote : 
[Found here](https://datagy.io/python-switch-case/) what I was looking at.

Even [on this not related page](https://skonik.me/python-alternatives-to-if-elif-statements-before-python-3-10/#whenifelsemightbegood) the author use `return`, and didn't think to replace `elif` with simplier `if` !

### Linked PRs
* gh-111312
* gh-115899
* gh-116703
* gh-116704

**Comment by hugovk** [comment]
Sounds like a good idea to recommend `match` at https://docs.python.org/3/faq/design.html?highlight=switch#why-isn-t-there-a-switch-or-case-statement-in-python, mentioning it's new in 3.10.

Would you like to propose something in a PR?

**Comment by dascritch** [comment]
I suppose it is in <https://github.com/python/cpython/blob/main/Doc/faq/design.rst> ? I try

**Comment by mdboom** [comment]
Cc @brandtbucher

**Comment by pochmann** [comment]
> `match case` isn't cited

I do see it there. The second sentence is all about it.

**Comment by terryjreedy** [comment]
The diatribe against if-elif-else is wrong-headed.  Match-case statements are executed as if case matches, do action, elif next case matches, do action, .... else _, do last action.  People must understand this to read and write such properly.  If-else is better for value range matching, which is quite common, since one otherwise has to add an if-clause to case statements anyway.

I write if-elif-else with return rather than if-if-if return since it is clearer at a glance that case-analysis is being done and exactly one condition will match and one suite executed.  In simple cases, such can be reduced to `return true_val if condition else false_val`.

**Comment by terryjreedy** [comment]
The existing doc, at the time of the PR, does not say the 'elif is great'.  I does say that that one "can do this easily enough", which I consider true.  Contrary to  "`match case` isn't cited", the entry says in the 2nd sentence, "For literal values, or constants within a namespace, you can also use a ``match ... case`` statement."  So I do not see any urgent need for revision, but I do see room for improvement. PR #115899 mentions match-case first as Python's new switch-case statement and de-emphasizes if-else.
