### ISSUE TITLE
Link to bpython's website is broken

### ISSUE THREAD

**Issue by zmc** [python/cpython#111406]
# Documentation

I noticed a broken link on this page: https://docs.python.org/3/tutorial/interactive.html

It links to https://www.bpython-interpreter.org/, which does not exist:
```bash
$ rh HEAD https://www.bpython-interpreter.org/ -s
Error: error sending request for url (https://www.bpython-interpreter.org/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```

https://bpython-interpreter.org/ does, though:
```bash
$ rh HEAD https://bpython-interpreter.org/ -s
HTTP/2.0 200 OK
```

### Linked PRs
* gh-111407
* gh-111408
* gh-111409

**Comment by hugovk** [comment]
It looks like it used to work as recently as 12th October. 

https://web.archive.org/web/20231012034120/https://www.bpython-interpreter.org/ 

We can fix the docs, but the root problem is likely some misconfiguration of the bpython website. 

The bpython project should fix their site so the www version redirects, otherwise countless other inbound links from other websites (and old Python docs we no longer update) will remain broken.

Please could you also report it to bpython?

**Comment by AlexWaygood** [comment]
This is fixed on CPython's side now, anyhow, so I'll close this issue!
