### ISSUE TITLE
type hint(set hint error)

### ISSUE THREAD

**Issue by zoulee24** [python/cpython#111492]
# Bug report

### Bug description:

```python
# -*- coding: utf-8 -*-
# @Time    : 2021/8/31 10:58 上午
# @Author  : zoulee24


class MyClass:
    """
    自定义类
    """
    def __init__(self, value: int):
        self.value: int = value

    def __repr__(self):
        return f"<MyClass: {self.value}>"

    def __hash__(self) -> int:
        return hash(self.value)

    def __eq__(self, other) -> bool:
        if isinstance(other, int):
            return self.value == other
        elif isinstance(other, MyClass):
            return self.value == other.value
        raise NotImplemented


# init data
my_class_set: set[MyClass] = set()
inner_type_set: set[int] = set()

for i in range(10):
    my_class_set.add(MyClass(i))
    inner_type_set.add(i + 8)

# get data by union
# expect hint: set[MyClass] but hit set[int]
out_1: set[MyClass] = inner_type_set & my_class_set
out_2: set[int] = inner_type_set & my_class_set
print(out_1, type(out_1.pop()).__name__)
print(out_2, type(out_2.pop()).__name__)

# expect hint: set[int] but hit set[MyClass]
out_3: set[int] = my_class_set & inner_type_set
out_4: set[MyClass] = my_class_set & inner_type_set
print(out_3, type(out_3.pop()).__name__)
print(out_4, type(out_3.pop()).__name__)

```

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by sobolevn** [comment]
Translating from Chineese: 

> I want to customize a class to implement the set operations supported by the int class.
When writing type hints, the opposite logic occurs. I performed the AND operation between set[MyClass] and set[int], and what I actually got was set[int], but the type prompt I got was set[MyClass], which is wrong.

I also saw these two lines:

```python
out_1: set[MyClass] = inner_type_set & my_class_set
out_2: set[int] = inner_type_set & my_class_set
```

They are indentical, because annotations do not have any runtime effect.

Runtime outputs (with all typos fixed):

```
{<MyClass: 9>} MyClass
{<MyClass: 9>} MyClass
{9} int
{9} int
```

which seems correct to me.

MyPy output: https://mypy-play.net/?mypy=latest&python=3.11&gist=8a316e51ce3f5ce3dc88c59bcf61b494

So, from runtime's point of view, everything is correct. 
This place is only for runtime bugs. If you want to open an issue about typing, please refer to typeshed / mypy / pyright / whatever tool you use. 

And please, respect our time and use English next time :)

**Comment by zoulee24** [comment]
I know they are indentical, also the result will not follow by type hint. But in pycharm when i write
```python
out_1: set[MyClass] = inner_type_set & my_class_set
```
it will warn me the code `inner_type_set & my_class_set` will return `set[int]`. It is obvious that the hint is incorrect.

**Comment by zoulee24** [comment]
the bug belong to pycharm
