### ISSUE TITLE
Path for scripts folder missing in new install Python 3.12 (pip and other libraries can't be used)

### ISSUE THREAD

**Issue by tencerjo** [python/cpython#111434]
# Bug report

### Bug description:

The title. The path name for the launcher was there but not the path name for the scripts folder so pip and others wouldn't work.

Environment variables under PATH had:
C:\Users\[user]\AppData\Local\Programs\Python\Launcher

but also needs this added for pip and other libraries.
C:\Users\[user]\AppData\Local\Programs\Python\Python312\Scripts

On Microsoft Windows 11 Home  Version 10.0.22621 Build 22621

Thanks.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Lounnaci-gi** [comment]
same problem

**Comment by zooba** [comment]
You need to select the "Add Python to PATH" option when installing.

Alternatively, use `py -m <tool>` to launch, instead of just using the name directly. e.g. `py -m pip install ...`. Most tools should support this.

_Alternatively_, most people create a virtual environment to work from and activate that, which has the benefit of not corrupting your system by injecting executables/DLLs into the system path. So `py -m venv .venv` followed by `.venv\Scripts\activate` and then `pip install ...` should be just fine.
