### ISSUE TITLE
Python 3.8 + Windows 11

### ISSUE THREAD

**Issue by kazuser** [python/cpython#111649]
# Bug report

### Bug description:

![image](https://github.com/python/cpython/assets/3335273/f797ca43-373d-4161-93ac-8c0d2dbc7b95)

Are you sure about that? 🥲

### CPython versions tested on:

3.8

### Operating systems tested on:

Windows

**Comment by zooba** [comment]
I don't understand the issue. Can you clarify?

**Comment by terryjreedy** [comment]
The OP has opened issues on various projects asking sometimes cryptic questions without supplying any reason or information or claim behind the question.  I presume kazuser (Kazakstan user, from another project's post) questions whether MS store Python starts working on exactly Win10 version 17763.  Even if the correct 'first version' should be something else, is this an issue for this repository?

**Comment by zooba** [comment]
It's in the right repository - these packages are published by us as part of the normal release processes, and the minimum version is a property in [a file in this repository](https://github.com/python/cpython/blob/edf701c4d83f399bff8612c34fef95da7663945e/PC/layout/support/appxmanifest.py#L112).

I'm not sure what the question is though. Should it start working earlier? Later? Presumably when we updated that minimum version it was due to some feature in the packaging format that was previously unavailable (potentially global app aliases, which seem to be the latest feature in use in that file), and so yeah, the Store package simply does not work on earlier Windows releases, even if the regular installer would.

Without a question, there's no answer anyone can give. We can reopen the issue when a question is formed.

**Comment by kazuser** [comment]
![image](https://github.com/python/cpython/assets/3335273/bb251809-937c-4f79-afbe-bba1e82b1428)

So... does Python 3.9 work on Windows 7+ or not? 😶

**Comment by ericvsmith** [comment]
It seems pretty clear: it can't be used on Windows 7, but can be used on versions after that.

**Comment by kazuser** [comment]
Seems pretty obvious to whom exactly? To you, lol? 🥲

Because others don’t think so, and when asked to “find it in the store and download Python 3” people download the first version they come across instead of the 100% compatible one.

**Comment by zooba** [comment]
If they're finding it in the Store, they already have Windows 10 or later, so it doesn't matter whether Windows 7 or earlier are supported or not.

Could you perhaps suggest the change you would like to see made? That may help us understand what problem you're encountering.
