### ISSUE TITLE
What’s New In Python 3.12: bad highlighting for Py_NewInterpreterFromConfig() example

### ISSUE THREAD

**Issue by jwilk** [python/cpython#111700]
In the "[PEP 684: A Per-Interpreter GIL](https://docs.python.org/3/whatsnew/3.12.html#pep-684-a-per-interpreter-gil)" section of "What’s New In Python 3.12", the C code snippet is highlighted as if it was Python.

### Linked PRs
* gh-113609
* gh-113610

**Comment by hugovk** [comment]
Thanks for the report!

This can be fixed by replacing the `::` with `:` at the end of the paragraph preceding the paragraph, and adding `.. code-block:: c` between the paragraph and the snippet. 

Would you like to create a PR and check if there are any other C snippets with Python formatting on the page?

**Comment by hugovk** [comment]
Fair enough, let's add the https://github.com/python/cpython/labels/easy label for someone else.

**Comment by parthsdoshi** [comment]
Hopefully fixed above, lmk!

**Comment by hugovk** [comment]
Thank you!
