### ISSUE TITLE
Discrepancy in Python 3.11 code between the 3.11 branch of the repository and the 3.11.6 release.

### ISSUE THREAD

**Issue by ForceFledgling** [python/cpython#111793]
# Bug report

### Bug description:

The Python 3.11 code provided through Homebrew corresponds to the Python 3.11.6 code available on python.org (https://www.python.org/ftp/python/3.11.6/Python-3.11.6.tgz). However, this archive, as well as the release (https://github.com/python/cpython/releases/tag/v3.11.6), does not match the latest code in the 3.11 branch of the repository (https://github.com/python/cpython/tree/3.11).

An example of a file with discrepancies that lead to the error below:
```python
Exception ignored in: <function _SelectorTransport.__del__ at 0x104f44ea0>
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 865, in __del__
    self._sock.close()
    ^^^^^^^^^^^^^^^^
AttributeError: 'TransportSocket' object has no attribute 'close'
```

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by JelleZijlstra** [comment]
Python 3.11.6 was released about a month ago and a lot of changes have gone into the 3.11 branch since then, including some in asyncio. I don't know if those are related to the issue you're seeing, but you may have to just wait for 3.11.7.

**Comment by hugovk** [comment]
I'm not sure what the problem you're seeing is exactly, but you're correct that the https://github.com/python/cpython/tree/3.11 branch isn't the same as the https://github.com/python/cpython/releases/tag/v3.11.6 tag, because there have been some 172 commits to the branch since that release:

* https://github.com/python/cpython/compare/v3.11.6...3.11

This is intended, and isn't a bug.

The next 3.11.7 release is due in a month, on 2023-12-04:

* https://peps.python.org/pep-0664/

If you have a concrete bug report, please open a new issue with a code snippet.
