### ISSUE TITLE
`ZipFile().namelist()` returns POSIX filepaths on Windows

### ISSUE THREAD

**Issue by tusharsadhwani** [python/cpython#111875]
# Bug report

### Bug description:

When using the `zipfile` module on windows, `namelist()` returns POSIX paths even on windows:

```pycon
>>> import zipfile
>>> file = zipfile.ZipFile('foo.zip')
>>> print(file.namelist())
['foo/', 'foo/bar/', 'foo/bar/baz.txt']
```

I was expecting `\\` separated paths here. Is this intentional?

### CPython versions tested on:

3.11, CPython main branch

### Operating systems tested on:

Windows

**Comment by serhiy-storchaka** [comment]
Yes, it is intentional. They are not paths in the file system.

**Comment by tusharsadhwani** [comment]
What's the benefit of returning `/` separated filepaths on windows? Is it to mimic CLI behaviour?

**Comment by serhiy-storchaka** [comment]
According to the ZIP file specification (https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT), all slashes in the path stored in a ZIP file must be forward slashes.

If you ask why not translate slashes to the platform-specific path component separator when read a ZIP file, there is no reason to do this. And since it would be a breaking change, you should have very good reasons to justify it.
