### ISSUE TITLE
Make weakref thread-safe without the GIL

### ISSUE THREAD

**Issue by colesbury** [python/cpython#111926]
# Feature or enhancement

The current weakref implementation relies on the GIL for thread-safety.

The `nogil-3.12` fork substantially modifies the weakref implementation. I think we can implement a simpler change in CPython 3.13 (main) now that all PyObject's have their own mutex (in `--disable-gil` builds).

### Basic idea
Protect access to the weakrefs linked list using the mutex in the weakly referenced object. Use the critical section API.

Prior implementation: https://github.com/colesbury/nogil-3.12/commit/0dddcb6f9d

### Linked PRs
* gh-112189
* gh-112267
* gh-113621
* gh-116825
* gh-116843
* gh-116844
* gh-117168
* gh-117275

**Comment by corona10** [comment]
Maybe we should check the performance impact the default build first

**Comment by colesbury** [comment]
The critical section APIs are no-ops on the default build:
https://github.com/python/cpython/blob/289af8612283508b67d7969d7182070381b4349b/Include/internal/pycore_critical_section.h#L107-L113

**Comment by corona10** [comment]
I know that there is no op for the default build but the commit you suggested modify some internal structure, I just want to know ovehead from the structure changed. (I didn't look at deeply now please let me know if I miss something)

**Comment by colesbury** [comment]
@corona10 the commit I linked to (in nogil-3.12) is **not** how I intend to make weakref thread-safe in CPython 3.13. I wouldn't spend too much time investigating it because it's not going to make it's way into 3.13. I linked to it because it's sometimes helpful for me to look back at the nogil-3.12 implementation.

**Comment by corona10** [comment]
By the way, I am working on it :)

**Comment by erlend-aasland** [comment]
Is there more work to be done here? If yes, could you add a list of actionable items?

**Comment by corona10** [comment]
> Is there more work to be done here? If yes, could you add a list of actionable items?

I am still checking :)

**Comment by corona10** [comment]
Okay from this week, I process this issue as my 1st priority issue that I should take a look :)

**Comment by colesbury** [comment]
I think @mpage started looking at this

**Comment by corona10** [comment]
> I think @mpage started looking at this

Well, it looks like I was a blocker(?) in this issue, is there any progress from Matt's side?
(I 've target this issue for 2 weeks :))

**Comment by mpage** [comment]
> is there any progress from Matt's side?
I just started looking at this on Friday afternoon, so not much progress :) I have a couple of ideas for how to implement this without having to substantially modify the weakref implementation like we did in the earlier nogil forks.

**Comment by mpage** [comment]
I have a design that I think will work, but would appreciate a sanity check in case I've missed something. I'm intentionally not pursuing what was done in the nogil-3.12 fork and am instead opting for a simpler solution using per-object locks.

We need to protect the following:

* The weakly-referenced object.
* The weakrefs.
* The linked-list of weakrefs.

To do so, we'll use per-object locks that are locked using critical sections according to the following rules:

* The weakly-referenced object and the linked-list are protected by the mutex in the weakly-referenced object.
* Weakrefs are protected by their per-object mutexes.
* The weakly-referenced object's mutex is always acquired first if both mutexes need to be held.

The main operations that we'll need to make thread-safe are outlined below.

### Creating a weakref

Creating a new weakref needs to maintain the invariant that the first two items in the linked-list are "canonical" objects for callback-less weakref and proxy objects, respectively. That is, only a single callback-less weakref or proxy should exist for any weakly-referenced object. I'll use weakref in place of both in the description below.

We'll maintain this invariant, along with enforcing thread-safety of the referenced object and the linked-list, by doing roughly the following:

1. Lock the referenced object's mutex.
2. If no callback was provided, try to return a reference to a "canonical" weakref, if one exists:
    1. Attempt to incref the "canonical" reference (using `_Py_TryIncref`). This will fail if the existing weakref is being destroyed (but hasn't been unlinked from the linked-list yet because we hold the lock).
    2. If the previous step was successful, unlock the mutex and return the new reference.
4. Create a new weakref (this may release the critical section).
5. If no callback was provided, retry returning a reference to a "canonical" weakref, if one exists. One may have been created and inserted into the list while the critical section was released.
6. Insert the weakref into the list.
7. Unlock the mutex.
8. Mark the weakref with the `weakrefs` shared refcount state.
9. Mark the referenced object with the `weakrefs` shared refcount state.
10. Return the weakref.

### Retrieving the referenced object from a weakref

This is already implemented in 3.13.

### Destroying a weakref

Destroying a weakref needs to unlink it from the linked-list. Doing this in a thread-safe manner using the correct lock ordering is tricky because we can't be sure that the referenced object is alive until we've already taken the weakref lock. To work around this, we add a `is_unlinking` field to weakrefs and use the following steps to unlink a weakref from the linked-list:

1. Lock the weakref's mutex.
2. Unlink the weakref from the linked-list if its `wr_object` is not `Py_None`:
  1. Set the `is_unlinking` flag.
  2. Unlock the weakref's mutex.
  3. Lock the referenced object's mutex. We can be sure that the object, and its mutex, will remain alive once the `is_unlinking` flag is set because its destructor will not make forward progress until all weakrefs with the `is_unlinking` flag have been removed from the list. See the description of how we destroy the referenced object for more details.
  4. Lock the weakref's mutex.
  5. Unlink from the linked-list.
  6. Unlock the weakref's mutex.
  7. Unlock the referenced object's mutex.

### Destroying a weakly-referenced object

Destroying a weakly-referenced object requires destroying the linked list. In the presence of the GIL, the list pointers in each node are rendered meaningless, rather than being unlinked, by setting `wr_object` to `Py_None` for each node in the list. Note that since the GIL is held this happens atomically for all nodes in the list. In free-threaded builds we'll also need to unlink the nodes from the list to prevent weakrefs that are being destroyed concurrently from attempting to modify already freed memory:

1. Lock the referenced object's mutex.
2. For each weakref in the list:
   1. Lock its mutex.
   2. If `is_unlinking` is set:
      1. Unlock the weakref's mutex.
      2. Unlock the referenced object's mutex.
      3. Goto (1)
   3. Set `wr_object` to `Py_None`
   4. Unlink the node from the list.
   5. Unlock the weakref's mutex.
3. Unlock the referenced object's mutex.

### Third-party extension code that manually clears the list

We'd like to support third-party [extensions](https://github.com/pytorch/pytorch/blob/f43b9c56c598b3a0f4d8e1d85f1e67b8f273d235/torch/csrc/Storage.cpp#L251-L257) that manually clear the list without requiring code changes. The best idea I can come up with is to stop the world in `_PyWeakref_ClearRef()`.

**Comment by colesbury** [comment]
Overall, this looks like a good approach. A few comments:

- Are you planning to use critical sections or directly lock and unlock mutexes?
- You write: "Create a new weakref (this may release the critical section)". Creating an object doesn't release critical sections any more. Previously, allocating a GC object could immediately trigger a GC, but that's not the case since 3.12. I don't know if there were other considerations that would make creating a new weakref release the active critical section.
- Regarding extension calls to `_PyWeakref_ClearRef()`: we do not need to make this thread-safe with the GIL disabled. We just need to ensure that it continues to work correctly when the GIL is on. We can propose a thread-safe, public API to clear an object's weakrefs later.

**Comment by mpage** [comment]
> Are you planning to use critical sections or directly lock and unlock mutexes?

Given that the locking protocol is a little tricky I think it might be easier to do correctly by directly locking/unlocking the mutexes (only in free-threaded builds).

**Comment by mpage** [comment]
> I think it's not safe to lock the PyObject.ob_mutex mutex without using the critical section API because some code higher up the stack may be holding it.

Ah, of course. Ok, well I think this approach will still work, I'll just need to be mindful of places where the CS might be released and be sure to use the two lock CS variant when both locks need to be held.

**Comment by mpage** [comment]
It turns out this is a little tricky to do as described using critical sections. When destroying a weakly-referenced object the plan is to:

1. Lock the referenced object.
2. For each weakref:
   1. Lock the weakref.
   2. ...

Translating this into critical sections, we'd need to:

1. Acquire a CS for the referenced object.
2. For each weakref:
   1. Acquire a CS2 with the referenced object and the weakref. Unfortunately, I think this requires temporarily releasing the referenced object's lock and once its re-acquired the weakref may be destroyed.
  
I think there's actually a simple solution to this problem that would also allow us to get rid of the `is_unlinking` flag, provided `_Py_TryIncref` only fails when the object its trying to incref has a refcount of 0. When destroying a weakly-referenced object, we first do the following:

1. Acquire a CS on the weakly-referenced object.
2. For each weakref:
   1. if `!_Py_TryIncref(weakref)`:
      1. Release the CS.
      2. Restart at (1) from the last weakref that was successfully increfed.
3. Release the CS.

This waits for any weakrefs that are destructing concurrently to finish and ensures that the remaining weakrefs are live for the rest of the process. We also don't have to worry about making forward progress because no new weakrefs to the object can be created.

**Comment by mpage** [comment]
> Previously, allocating a GC object could immediately trigger a GC, but that's not the case since 3.12. I don't know if there were other considerations that would make creating a new weakref release the active critical section.

Oh, ok, I think that simplifies things then. There's a [comment](https://github.com/python/cpython/blob/main/Objects/weakrefobject.c#L804-L808) that it can trigger cyclic GC, but it's probably just outdated. [`new_weakref`](https://github.com/python/cpython/blob/main/Objects/weakrefobject.c#L28-L48) only allocates a GC object and does some basic initialization.
