### ISSUE TITLE
Make `http.cookiejar.CookieJar` picklable

### ISSUE THREAD

**Issue by XuehaiPan** [python/cpython#112144]
# Bug report

### Bug description:

I am developing a program that employs multiprocessing to enhance efficiency through parallel execution. Python relies on the `pickle` module for object serialization and inter-process communication. However, I've encountered an issue where the `CookieJar` object cannot be pickled due to its inclusion of an RLock object, which is causing problems in my application.

Here is the membership hierarchy:

```text
openai.OpenAI -> httpx.Client -> httpx.Cookies -> http.cookiejar.CookieJar
```

Reproduce snippet:

```python
# Add a code block here, if required

import pickle
from http.cookiejar import CookieJar


jar = CookieJar()
pickle.dumps(jar)  # TypeError: cannot pickle '_thread.RLock' object
```

We could implement a `__reduce__` method for the `CookieJar` class to let it support serialization.

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

### Linked PRs
* gh-112178

**Comment by terryjreedy** [comment]
@XuehaiPan Does 'We could' mean that you have actually done so?  At least well enough for the purpose?  Can you submit a PR?

**Comment by XuehaiPan** [comment]
I created a PR to resolve this issue.

**Comment by Eclips4** [comment]
Terry, seems you accidentally closed issue :)

**Comment by terryjreedy** [comment]
Definitely accidental, as I verified the behavior and support improving it.

**Comment by serhiy-storchaka** [comment]
I am not sure that it is correct. The lock was in CookieJar from the beginning, from 2a6ba9097ee3942ae328befaf074ce9722b93ca0 (bpo-963318/gh-40311). It allows to share CookieJar between HTTP clients used in different threads. The lock makes the changes to CookieJar are atomic and keeps its state in consistent state. Also changes in one client are available in other client that uses the same CookieJar, so you can use several clients in the same session. But when you clone it for multiprocessing, the new instance no longer shares the lock and the state, so changes in one client are no longer available in other clients. And why then not simply create a new CookieJar, and maybe a new HTTP client in a new process?

The `http.cookiejar` module docstring refers to third-party subclasses of CookieJar that save the state in the external DB. In the best case they are not pickleable, if they contains non-pickleable attributes like a reference to a DB, but in the worst case they can be pickleable, but the unpickled copy makes it unsafe, because changes are no longer atomic. We should estimate such risk.

**Comment by XuehaiPan** [comment]
> The `http.cookiejar` module docstring refers to third-party subclasses of CookieJar that save the state in the external DB. In the best case they are not pickleable, if they contains non-pickleable attributes like a reference to a DB, but in the worst case they can be pickleable, but the unpickled copy makes it unsafe, because changes are no longer atomic.

That makes sense. I think we'd better raise an error for this. Closing this now.
