### ISSUE TITLE
An opcode optimize error in Python 3.12.0

### ISSUE THREAD

**Issue by tiwb** [python/cpython#112356]
# Bug report

### Bug description:

```python
import dis

def _f(a):
	print(a)

dis.dis(_f)
```
Here is a test in Python 3.12 test_dis.py BytecodeTests.test_disassembled, It outputs:
```
  3           0 RESUME                   0

  4           2 LOAD_GLOBAL              1 (NULL + print)
             12 LOAD_FAST                0 (a)
             14 CALL                     1
             22 POP_TOP
             24 RETURN_CONST             0 (None)
```
source code for this optimization is at: https://github.com/python/cpython/blob/3.12/Python/flowgraph.c#L1556-L1560
```C
            case PUSH_NULL:
                if (nextop == LOAD_GLOBAL && (inst[1].i_opcode & 1) == 0) {
                    INSTR_SET_OP0(inst, NOP);
                    inst[1].i_oparg |= 1;
                }
                break;
```

I feel the correct check should be:
```C
if (nextop == LOAD_GLOBAL && (inst[1].i_oparg & 1) == 0)
```

I'm unable to write a unit test for this code to make some real error, but if opcode for LOAD_GLOBAL is changed to some odd number, test_dis will fail.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-112566

**Comment by sweeneyde** [comment]
This line dates back to https://github.com/python/cpython/commit/3011a097bd9500c007bd8b8d005edeea895f6b44. It was fixed in main by a9caf9cf9041d6d0b69f8be0fd778dd1f9b50e74, but the `inst[1].i_opcode & 1` still exists in [3.11](https://github.com/python/cpython/blob/03ac9e6ee1aacb1ab42788c40e8465a6e5c46532/Python/compile.c#L9035) and [3.12](https://github.com/python/cpython/blob/4c9da4c964a62c2972fa40b30ab11f19f89178f4/Python/flowgraph.c#L1557).

> I feel the correct check should be: `if (nextop == LOAD_GLOBAL && (inst[1].i_oparg & 1) == 0)`

I agree--this is likely the mistake.

> I'm unable to write a unit test for this code to make some real error, but if opcode for LOAD_GLOBAL is changed to some odd number, test_dis will fail.

https://github.com/python/cpython/pull/112566 uses `test_peepholer.DirectCfgOptimizerTests`
