### ISSUE TITLE
teach dis how to interpret the oparg of ENTER_EXECUTOR 

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#112383]
The oparg of `ENTER_EXECUTOR` is not consistent with that of `JUMP_BACKWARD`. See https://github.com/python/cpython/pull/112377/files#r1404568464

### Linked PRs
* gh-113153
* gh-117171

**Comment by gvanrossum** [comment]
Hm... I think it's not that simple. The oparg of `ENTER_EXECUTOR` is unrelated to the oparg of the `JUMP_BACKWARD` it overwrites. It is an index in the table of executors associated (optionally) with the code object. The executor saves the origin opcode (currently always `JUMP_BACKWARD`, but that may change) and oparg (low byte only) in its `vmdata` field. Note that if there are `EXTENDED_ARG` prefixes those are unchanged and unaffected -- the executor index must fit in one byte and only the low byte of the full oparg is saved.

I expect that in order to handle `ENTER_EXECUTOR` correctly in `dis` and other things that inspect the "adaptive" (read: specialized) bytecode, we need an API on the code object to retrieve the executors, or at least the original vmdata for the executors.

**Comment by iritkatriel** [comment]
I don't think we know what to do here.

**Comment by gvanrossum** [comment]
If you can import `_testinternalcapi`, you can get a hold of the executor (`ex = _testinternalcapi.get_executor(co, offset)`) and the executor object now has methods `get_opcode()` and `get_oparg()` that return those fields (only the lower byte of `oparg`).

```
>>> def f():
...     for i in range(20):
...         i += 1
...     return i
... 
>>> f()
20
>>> f()
20
>>> f()
20
>>> c = f.__code__
>>> import dis
>>> import _testinternalcapi as t
>>> dis.dis(c, adaptive=1, show_offsets=1)
  1          0       RESUME_CHECK             0

  2          2       LOAD_GLOBAL_BUILTIN      1 (range + NULL)
            12       LOAD_CONST               1 (20)
            14       CALL_BUILTIN_CLASS       1
            22       GET_ITER
      L1:   24       FOR_ITER_RANGE           8 (to L2)
            28       STORE_FAST               0 (i)

  3         30       LOAD_FAST                0 (i)
            32       LOAD_CONST               2 (1)
            34       BINARY_OP_ADD_INT       13 (+=)
            38       STORE_FAST               0 (i)
            40       ENTER_EXECUTOR          10

  2   L2:   44       END_FOR
            46       POP_TOP

  4         48       LOAD_FAST_CHECK          0 (i)
            50       RETURN_VALUE
>>> e = t.get_executor(c, 40)
>>> e
<uop_executor object at 0x1037a3b40>
>>> e.get_oparg()
10
>>> e.get_opcode()
77
>>> 
```
