### ISSUE TITLE
Misleading error message when lambda misspelt in map expression

### ISSUE THREAD

**Issue by kdwyer** [python/cpython#112384]
# Bug report

### Bug description:

When `lambda` is misspelt within a `map` expression or similar, the interpreter suggests the user has omitted a comma, whereas the problem is in fact a misspelt keyword.

```python
Python 3.12.0 (main, Oct  2 2023, 19:12:54) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> map(lamda x: 1, [1])
  File "<stdin>", line 1
    map(lamda x: 1, [1])
        ^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

### CPython versions tested on:

3.10, 3.11, 3.12

### Operating systems tested on:

Linux

**Comment by terryjreedy** [comment]
The current checks for possible correction suggestions are triggered by runtime NameErrors.  At parse time, "id1 id2", where id1 and id2 are non-keyword identifiers,  is, I believe, always a SyntaxError.  This is, of course, not specific to misspellings of 'lambda', but is also possible with misspellings of 'if', 'elif', 'while', 'for', 'def', 'class', 'with', 'async', and others.  In at least some situations where "id1, id2" *is* legal, the comma insertion suggestion is issued.

The effective suggestion above is that in situations where an illegal "id1 id2" pair is possibly the result of a keyword misspelling, id1 or id2 be checked as a misspelling of any of the keywords that would be legal in that place.  At the beginning of a line, id1 could be many things.  In some places, id2 could be 'if', 'else', or 'for'.  In the situation above, after '(', 'lambda' is the only thing I can think of now.  But note that many near-keyword spellings are intentional, so that the comma suggestion would still be needed.  Leaving out commas is probably as common as unintentionally misspelling a keyword, it can be harder to see, even with 'SyntaxError'.

**Comment by pablogsal** [comment]
Unfortunate we cannot easily fix this as it's near impossible to detect this case from the one it's suggesting. That's why we say "perhaps" in the message. Unfortunately there is nothing we can do other than trying to suggest common keyword misspellings but that's a different and more complicated problem.
