### ISSUE TITLE
Update outdated unicodestring.encode in the document of :mod:`array`

### ISSUE THREAD

**Issue by wanglc02** [python/cpython#112437]
# Documentation

```rst
.. method:: fromunicode(s)

   Extends this array with data from the given unicode string.
   The array must have type code ``'u'`` or ``'w'``; otherwise a :exc:`ValueError` is raised.
   Use ``array.frombytes(unicodestring.encode(enc))`` to append Unicode data to an
   array of some other type.
```

https://docs.python.org/3/library/array.html#array.array.fromunicode

**It seems that `unicodestring.encode` is not supported anymore.**

**Comment by terryjreedy** [comment]
Encode very much still works for strings, which are unicode in 3.x.  Perhaps the redundancy in 3.x of 'unicode string confused you.
```
>>> 'a'.encode()
b'a'
>>> '\u2222'.encode()
b'\xe2\x88\xa2'
```
The compound `unicode string` is a bit obsolete in 3.x, where strings *are* (always) unicode.  Perhaps
"fromunicode(s)
Extend this array with data from string *s*. The array must be a type 'u' array; otherwise a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) is raised. Use array.frombytes(s.encode(enc)) to append Unicode data to an array of some other type."

I looked at `tounicode` and think its entry can be left alone.

**Comment by wanglc02** [comment]
Thank you! I realize that `unicodestring` is actually a `str` instance.
