### ISSUE TITLE
default function parameters self variable

### ISSUE THREAD

**Issue by ERIPECH** [python/cpython#112573]
# Feature or enhancement

### Proposal:

class YourClass {
    constructor() {
        this.currentColor = 'red';
    }

    removePreviousLines(color = this.currentColor) {
        // Your function logic using color...
    }
}

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

https://groups.google.com/g/comp.lang.python/c/eAFPoYwdOTQ/m/t80hyl2EAgAJ

**Comment by gaogaotiantian** [comment]
So you want Python to be JavaScript :)

**Comment by Eclips4** [comment]
Hello!
Currently this is impossible because `self` is passing  into the methods, it's isn't available at the scope of a class, so you cant write something like that:
```python
class Foo:
    def __init__(self, color):
        self.color = color
    def paint_color(self, color=self.color): # self is unavailable here
        ...
```
This will be a major change in class scoping rules, so this requires a more wider discussion, here you can creat a topic for it: https://discuss.python.org/c/ideas/6
Now I'm closing this, we can reopen it later if the idea "takes root".
