### ISSUE TITLE
gc.collect() docs are wrong

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#112502]
https://docs.python.org/3/library/gc.html#gc.collect says "The number of unreachable objects found is returned."

In fact, it returns (https://github.com/python/cpython/blob/48dfd74a9db9d4aa9c6f23b4a67b461e5d977173/Modules/gcmodule.c#L1378) the sum of two numbers: the number of objects collected plus the number of uncollectable objects. The docs should be changed.

(What makes an object uncollectable? I didn't read too closely but it seems to have something to do with finalizers.)

### Linked PRs
* gh-112562

**Comment by olutra** [comment]
To be fair, "The sum of collected objects and uncollectable objects" is exactly "The number of unreachable objects found", so docs weren't wrong. It was confusing, because there is no definition of the `unreachable` objects on the page, but new wording isn't necessarily less confusing. Two numbers are summed and returned as one, and it becomes impossible to deduce each number from the sum. To me it seems to be an internal implementation detail that should not be propagated to higher levels. 

I think a better way would be to put a definition of unreachable objects somewhere on the page, because `unreachable` is also used in a couple of other places on the page.
Previous wording "The number of unreachable objects found is returned." didn't indicate that objects weren't only found but also processed. Current wording indicates that collectable objects were collected, but doesn't say that uncollectable objects are also processed (moved to `garbage`) and won't be included in the next collection.
