### ISSUE TITLE
zipfile decompress bug

### ISSUE THREAD

**Issue by FireJohnny** [python/cpython#112739]
# Bug report

### Bug description:

if there is a zip file named "test.zip" with "test.csv".
i dont know the encoding with test.csv. so i will write code like this:
```python
from zipfile import Zipfile
import pandas as pd
with Zipfile("test.zip") as zip_f:
    for file_name in zip_f.namelist():
        try:
            df = pd.read_csv(f)
        except:
            df =pd.read_csv(f,encoding="gbk")
```
now i will get the woring dataframe.
cause the real encoding is "gbk".but the `pd.read_csv` will decode some info. so `pd.read_csv(f,encoding)`cant decode all info.

now the solution is ,
1> extract the csv file to local disk
2> read csv file 
3> delete csv file

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by ronaldoussoren** [comment]
It is not clear to me what the issue in CPython is you're trying to tell us about. The CSV parsing is done by Pandas in your example, and that's something you'll have to ask them about.

BTW:

1. The example is incomplete, you're passing and ``f`` variable to ``pd.read_csv`` but never define that variable
2. It is best practice to never use ``except:``, but always catch specific exceptions because ``except:`` will also catch exceptions you generally don't want to catch such as ``KeyboardInterrupt`` and ``MemoryError`.

**Comment by ronaldoussoren** [comment]
I'm closing the issue because of the reasons in mention in my previous message.
