### ISSUE TITLE
3.12.1 Windows installer not writing standard libraries to disk

### ISSUE THREAD

**Issue by CY-Pan** [python/cpython#113005]
# Bug report

### Bug description:

I downloaded 3.12.1 windows 64-bit installer from the official site, and ran it successfully. But a lot of files are missing in the installation directory. As the screenshot shows, `python3.dll`, `python312.dll`, `include/`, `Lib/` are all missing. I cannot run `python` for lacking python312.dll.
![image](https://github.com/python/cpython/assets/59761962/2ffc17e3-01ee-49a0-8318-d89816a3f277)

I also tried installing 3.12.0 first, and upgraded to 3.12.1. The wired thing is, `python -V` still gives '3.12.0'. I believe the reason is the installer didn't replace python312.dll.

I tried multiple times of reboot, uninstallation, reinstallation, but its behavior remains same. 3.12.0 installer always works fine, but 3.12.1 installer never. I used python for years and I never came across such an issue before.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
You are missing several things, depending on the install options you chose.  I have no idea why.  A few days ago, I successfully installed python-3.12.1-amd64.exe, 25,967 KB.  Does your install file have the same name and size?  Could your hard disk be full?

**Comment by zooba** [comment]
Can you look in your `%TEMP%` directory and collect all the Python log files you find there, put them in a ZIP file, and attach to a post on this issue? That ought to tell us exactly what is going wrong here. (Note that it may disclose some personal information, such as your username.)

**Comment by CY-Pan** [comment]
> You are missing several things, depending on the install options you chose. I have no idea why. A few days ago, I successfully installed python-3.12.1-amd64.exe, 25,967 KB. Does your install file have the same name and size? Could your hard disk be full?

These are the install options. I don't set $PATH$ here because I set it myself. I used these options for a long time on different versions, nothing ever went wrong.
![image](https://github.com/python/cpython/assets/59761962/7bc6c4aa-4dec-488c-8a3a-4661d5e94aa2)
![image](https://github.com/python/cpython/assets/59761962/f4d8a005-34ca-4fe4-94ec-d71b560e40ac)

I compared the md5 hash and file size, they are correct. I did redownload installer and install again for several times, it still didn't work.

My disk is far from full, and has no functional issues.

**Comment by CY-Pan** [comment]
> Can you look in your `%TEMP%` directory and collect all the Python log files you find there, put them in a ZIP file, and attach to a post on this issue? That ought to tell us exactly what is going wrong here. (Note that it may disclose some personal information, such as your username.)

Here are my installer logs for all installation and reinstallation yesterday.
[Python logs.zip](https://github.com/python/cpython/files/13655240/Python.logs.zip)

**Comment by zooba** [comment]
It seems to have gotten wedged for some reason. Windows Installer _thinks_ the stdlib files are installed, but they're not, and without them we can't do the pip uninstall so neither a repair nor an uninstall will work.

You may be able to clean everything up with these PowerShell commands and then try installing again:

```
$> Get-Package "Python 3.12*" # just to review the packages
$> Uninstall-Package (Get-Package "Python 3.12*")
```

Unfortunately the earliest logs in the file appear to be an attempt to repair the already broken install. So I can't see how it broke in the first place. The usual problem is installing pip, so you might want to disable that option and run `python -m ensurepip` yourself.

**Comment by CY-Pan** [comment]
`Get-Package` returns 2 packages. `Uninstall-package` only removes the Executables. Then I uninstall the Program in settings and ensure `Get-Package` finds no matching packages.
![Snipaste_2023-12-14_09-45-14](https://github.com/python/cpython/assets/59761962/be9c5b8b-a2a9-41f7-95a9-6562765f500d)

After reboot, I rerun the installer, uncheck every option, and install to a brand new directory. It still doesn't write the libraries.

I deleted all old logs before the installation, and got 3 new logs after. I attach them here.
[python logs.zip](https://github.com/python/cpython/files/13667528/python.logs.zip)

**Comment by zooba** [comment]
Thanks! From the newest logs, it seems to think the stdlib is already installed:

```
[3430:12AC][2023-12-14T09:58:27]i201: Planned package: lib_JustForMe, state: Present, default requested: Present, ba requested: Present, execute: None, rollback: None, cache: No, uncache: No, dependency: Register
```

It's possible that running a repair now will fill everything else in, but honestly I'm guessing. Something has gone weird in your installer registration database that I've not seen before.

I _think_ what you'll need to do is a bit of manual registry cleanup. It would be great if you could capture the keys before you delete anything (screenshot is fine), as that may give more hints as to what's wrong, but I don't think we're solving this any other way.

First uninstall everything Python 3.12 related that you can. We're about to wipe out _part_ of its own understanding of what is installed, so if anything is actually left behind it'll be just as confused. Delete any installed files from disk as well.

Find `HKEY_CURRENT_USER\Software\Classes\Installer\Dependencies` in Registry Editor. It's got a whole lot of GUIDs listed, and each of those will have its own list of GUIDs saying which bundles added them. It's these last GUIDs that might show what went  wrong, so expand everything out and screenshot it before deleting anything.

The entries to delete (if they're there) will be:[^1]
* `{AC82C1A3-9597-40F2-893D-F02F778FBA4D}`
* `{44BC9F9C-15C2-46C1-B88D-3135A9DA555F}`
* `{8C53CBDD-4DAF-426F-9478-6C7C2920CDDA}`
* `{47957EE3-0E23-4075-B825-F202E913670F}`
* `{1662F43B-2337-4FD8-8CE6-BEA38FC94DD4}`
* `CPython-3.12`

Once they're gone, try installing again and capture the logs in case it doesn't work. But I think without those keys it'll decide to install everything instead of just skipping them.

[^1]: These are the product codes of each MSI in the bundle. I found them from the main installer log, where it has a list of dependencies that it registers, but it should also be visible in the build logs where they are generated.

**Comment by CY-Pan** [comment]
Thanks for the guide! The issue is solved with registry keys removed, just not in `HKEY_CURRENT_USER\Software\Classes\Installer\Dependencies` in my case.

My very first installation of 3.12.1 did meet some serious trouble, and that uninstallation left some registry keys unclean.
When I tried reinstalling 3.12.0, it always prompted "a newer version is installed". This error resulted from keys in `HKEY_CURRENT_USER\Software\Classes\Installer\Dependencies`. I cleaned up there following solutions on StackOverflow. (All before committing this issue here) 
So my `HKEY_CURRENT_USER\Software\Classes\Installer\Dependencies` is already clean. The only item of 3.12.0 should in no way forbid installation of 3.12.1.
![Snipaste_2023-12-15_10-26-55](https://github.com/python/cpython/assets/59761962/b5eb9203-8253-4b72-bf04-b47a0264a90f)

Then I tried searching the given UUID above, Some items were found and seemed really like the problem cause--`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Installer\UserData\S-XXXX\Products`. After a thorough search of other UUID, it seemed to be the only registry that may confuse the installer. I deleted them, and the installer worked!
![Snipaste_2023-12-15_10-37-42](https://github.com/python/cpython/assets/59761962/99619098-fd71-42c7-8022-0dbfa1e248d8)

When trying to solve the issue in the first place, I thought about registry. Yet I cannot find a detailed list of registry positions the installer writes. It would really help a lot if such information could be provided in documentations.

**Comment by zooba** [comment]
> Yet I cannot find a detailed list of registry positions the installer writes. It would really help a lot if such information could be provided in documentations.

I agree, but it's not ours to document. When Microsoft decide to make this public information (as opposed to internal implementation details), then it's up to them to document it. Some parts may also be Wix internal implementation, rather than MSI - I'm not totally sure where the divide is.

I wouldn't expect any of it to be documented anytime soon 😄
