### ISSUE TITLE
File opened with `'r+'` faulty write after read without prior flush

### ISSUE THREAD

**Issue by Grismar** [python/cpython#113242]
# Bug report

### Bug description:

Consider this:
```python
with open('test1.txt', 'w') as f:
    f.write('x' * 100000)

with open('test1.txt', 'r+') as f:
    s1 = f.read(5)    # 5. read first 5 bytes, expected to be 'xxxxx'
    f.seek(0)         # 6. seek back to beginning of file
    f.write('y' * 5)  # 7. write 5 bytes of 'yyyyy'
    f.read(5)         # 8. then read another 5 bytes (discarded, but would be 'xxxxx')
    f.flush()         # 9. flush the buffer, if any
    f.seek(0)         # 10. seek the beginning of the file once more
    s2 = f.read(5)    # 11. read 5 characters, expected to be 'yyyyy', but in fact 'xxxxx' (Win 10, Python 3.11.6)

print(s1, s2)

# without line 8:
with open('test2.txt', 'w') as f:
    f.write('x' * 100000)

with open('test2.txt', 'r+') as f:
    s1 = f.read(5)
    f.seek(0)
    f.write('y' * 5)
    # f.read(5)
    f.flush()
    f.seek(0)
    s2 = f.read(5)

print(s1, s2)         # the expected result
```
After running this code, `test1.txt` will contain `yyyyy` at position 8193, after 'read buffer size' bytes. `test2.txt` will contain `yyyyy` at position 0, which is what would be the expected behaviour without knowing the exact inner workings of `_io`.

If a `.flush()` is a requirement before following a `.write()` with a `.read()`, shouldn't Python either perform this flushing automatically, or throw an error if this is not done?

The data getting written to a seemingly arbitrary position (though it is most likely the size of the read buffer, and the read operation repositions the file pointer) seems to be the most undesirable (and what's worse, unexpected) outcome here.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by mattprodani** [comment]
Similar discussion in https://github.com/python/cpython/issues/93101 .
From the [docs](https://github.com/python/cpython/blob/f428c4dafbfa2425ea056e7f2ed2ea45fa90be87/Doc/library/io.rst#L912-L921), the behavior of `seek` as used in your example is undefined.
```
seek(offset, whence=SEEK_SET, /)
Change the stream position to the given offset. Behaviour depends on the whence parameter. 
The default value for whence is SEEK_SET.

SEEK_SET or 0: seek from the start of the stream (the default); 
offset must either be a number returned by [TextIOBase.tell()](https://docs.python.org/3/library/io.html#io.TextIOBase.tell), or zero. 
Any other offset value produces undefined behaviour.
```


Currently the `TextIOBase` implementation uses an internal "cookie" parameter as opposed to a raw offset. This design comes due to having to encode and decode bytes in a stream (where a character may be encoded in multiple bytes). (If offset were to refer to characters, for example, in a 16-bit encoding, the first two bytes of a stream define the endianness, and the first true character starts at byte 2. It would be unclear what `seek(0)` means) For this reason, only values returned by `tell()` should be used in `seek` calls, additionally, outputs from `tell()` are opaque and should not be assumed to be have any meaning in their value to the user.

The `seek()` method on bytes-based IO does not have this limitation though, so after dealing with encoding, your example would work as expected.

**Comment by ericvsmith** [comment]
Can this issue be closed?

**Comment by ericvsmith** [comment]
I'm going to close this, it can always be re-opened if needed.
