### ISSUE TITLE
Occasionally `multiprocessing.test.*.test_threads` can take 10 minutes

### ISSUE THREAD

**Issue by gpshead** [python/cpython#113205]
# Bug report

### Bug description:

See the logs in https://buildbot.python.org/all/#/builders/1138/builds/498

```
10 slowest tests:
- test.test_multiprocessing_spawn.test_threads: 10 min 14 sec
- test.test_multiprocessing_fork.test_threads: 10 min 13 sec
- test_imaplib: 1 min 31 sec
- test_signal: 1 min 18 sec
- test.test_multiprocessing_spawn.test_processes: 52.6 sec
- test.test_concurrent_futures.test_wait: 48.6 sec
- test_socket: 40.7 sec
- test.test_multiprocessing_forkserver.test_processes: 40.1 sec
- test_io: 37.4 sec
- test_codecs: 37.3 sec
```

Normally those two `.test_threads` sub-suites in `test_multiprocessing` do not make the top 10 slowest at all.

Something odd is going on and occasionally making them sit around for a very long time before apparently succeeding anyways.  I've seen it multiple time in the rpi buildbot logs.  I expect it'll show up on some other bots as well but I haven't gone hunting.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-114186
* gh-114222
* gh-114223
* gh-114249
* gh-114516
* gh-114517

**Comment by gpshead** [comment]
Notably I'm not seeing this on the `main` 3.x branch builds, only 3.12 and 3.11.  https://buildbot.python.org/all/#/workers/25

**Comment by encukou** [comment]
It appears on Windows too, and there the refleak buildbot sometimes fails with a timeout.

I will investigate.

**Comment by encukou** [comment]
`WithThreadsTestPool.test_terminate` takes `LONG_TIMEOUT` (5 minutes) in about 1.5% cases (on my machine).

It happens when the first task starts executing before termination. Unlike processes, threads can't be safely forcefully stopped, so the expected behaviour of `ThreadPool.terminate` is to wait for in-progress tasks to finish.
But the test is designed for process pools, and it uses very long tasks.

On main, the test is now [skipped for threads entirely](https://github.com/python/cpython/commit/0e9c364f4ac18a2237bdbac702b96bcf8ef9cb09#diff-c3db62f7c1928499afd71830c22c8bb8f56843a4533cecf69137973d73c489fc). We can do better: for threads, use a shorter task, but still make sure the API *works*.

**Comment by gpshead** [comment]
The merged PR in `main` has a few buildbot failures.  is this perhaps related: https://buildbot.python.org/all/#/builders/345/builds/6859/steps/5/logs/stdio

**Comment by encukou** [comment]
The PR changed one specific case, so it's unrelated.
But I'll look at those failures anyway, with higher priority than backporting this fix.

**Comment by encukou** [comment]
It was https://github.com/python/cpython/issues/104522#issuecomment-1897942493.

**Comment by encukou** [comment]
I don't see a good way to verify that this fixed *all* occasional hangs, so I'll close the issue now. Please ping me if you see something like it again, though.

**Comment by serhiy-storchaka** [comment]
It is disturbing that it only happens in 1.5% cases. It means that in majority of cases `terminate()` is called when no tasks was even started. It is perhaps not for what this test was purposed (by running slow tasks which take "forever" to complete).

**Comment by encukou** [comment]
We could also go all the way and let the worker signal its start using a event or queue, but `sleep` is good enough.
