### ISSUE TITLE
Unordered UnitTest Methods When Using unittest.defaultTestLoader.sortTestMethodsUsing = None

### ISSUE THREAD

**Issue by iihsan** [python/cpython#113247]
# Bug report

### Problem
The setting `unittest.defaultTestLoader.sortTestMethodsUsing = None` is not effectively maintaining the order of UnitTest methods, causing them to run out of sequence.

### Description
When utilizing the `unittest` module in Python to create test cases, the order of execution for UnitTest methods is not guaranteed, even when attempting to set `unittest.defaultTestLoader.sortTestMethodsUsing = None`. This lack of sequential execution can lead to issues during component testing, where specific configurations, such as database connections, may not be loaded in the expected order, resulting in test failures.

### Root Cause
The problem arises from the use of `dir(TestCaseClass)` to obtain all methods, which does not maintain the order. The `getTestCaseNames()` method in loader.py attempts to filter the methods but does not prevent sorting, leading to unpredictable execution order.

### Why is it Happening
The default behavior of `dir()` is to return attributes and methods in lexical order. When the sorting of test cases is disabled (`unittest.defaultTestLoader.sortTestMethodsUsing = None`), the actual order of the methods in the class is not preserved.

### Example
Here's the sample test class:
```
import unittest
unittest.defaultTestLoader.sortTestMethodsUsing = None

class TestCaseClass(unittest.TestCase):
    def test_get_record_from_db_when_no_record_exists():
        pass
    def test_insert_some_record_in_db():
        pass
    def test_get_record_from_db_when_1_record_exists():
        pass
```
When attempting to run the test cases, those are executed in incorrect order because of `dir()` behaviour. So, when the following line or code executes:
```
testFnNames = list(filter(shouldIncludeMethod, dir(testCaseClass)))
```
It executes in the following sequence:
**Actual Execution:**
```
1. test_get_record_from_db_when_1_record_exists
2. test_get_record_from_db_when_no_record_exists
3. test_insert_some_record_in_db
```
**Expected Execution:**
```
1. test_get_record_from_db_when_no_record_exists
2. test_insert_some_record_in_db
3. test_get_record_from_db_when_1_record_exists
```

### Solution
To address this issue, a modification to the `getTestCaseNames()` method in `loader.py` is proposed. Instead of using `dir(testCaseClass)`, 
```
testFnNames = list(filter(shouldIncludeMethod, dir(testCaseClass)))
```
the method should obtain attributes and methods directly from the class without pre-sorting:

```
attributes_and_methods = list(testCaseClass.__dict__.keys())
testFnNames = list(filter(shouldIncludeMethod, attributes_and_methods))
```

### Note
While the sequence is maintained when using the **pytest** module, the historical behavior in earlier releases of the **unittest** module is mentioned for reference [StackOverflow Reference](https://stackoverflow.com/questions/4095319/unittest-tests-order).

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
The [attribute doc](https://docs.python.org/3/library/unittest.html#unittest.TestLoader.sortTestMethodsUsing) says "Function to be used to compare method names when sorting them in getTestCaseNames() and all the loadTestsFrom* methods.and all the loadTestsFrom* methods." It does not document the acceptibility or effect of passing None.  Just based on this, I don't see the behavior as being a bug.  Maybe someone else has additional info otherwise, but the unittest docs do not contain 'sequential' or 'order depend', so I am pretty sure there is no guarantee of what you expected.  This should likely be closed.

There is no evidence that the person who suggested None actually tested this, and a commenter says "sortTestMethodsUsing = None appears to not work in Python 3.9.5, and indeed the documentation no longer mentions this."  You could use git blame to try to find out when and why the entry was changed, if that is were there once was a mention.

When you have dependent operations and tests, and you do not want to repeat test setup, put the operations and assertions in one test method.  This is what the SO answer called a 'component' test. You can find multiple examples of this in stdlib tests.

A trivial alternative is to name dependent test methods so that alphabetical is the right order 'test_1_whatever', test_2_something', 'test_3_finished'.

**Comment by serhiy-storchaka** [comment]
Agree with everything Terry said. I would like to add that dependence on the order of tests is generally considered a defect of tests. Each test should be self-contained.

**Comment by picnixz** [comment]
Closing as `wont fix`. To configure a consistent order, this would likely be a feature request that should be discussed on DPO first: https://discuss.python.org/c/ideas/6.
