### ISSUE TITLE
Better lambda syntax

### ISSUE THREAD

**Issue by kevinhellos** [python/cpython#113545]
# Feature or enhancement

### Proposal:

```python
# Create a feature to allow lambda syntax much easier.

# Current syntax example:
add = lambda x, y: x + y
print(add(2, 3))  # Outputs: 5

# Proposed new syntax example:
add = (x,y) => x+y
print(add(2, 3))  # Outputs: 5
```

### Has this already been discussed elsewhere?

No response given

**Comment by AlexWaygood** [comment]
As our "feature proposal" issue form states, significant features (which includes any features that involve the introduction of new syntax) require substantial discussion and consensus-building before a GitHub issue can be opened. If you're interested in developing your idea here, I recommend you start a thread at https://discuss.python.org/c/ideas/6.

**Comment by terryjreedy** [comment]
[PEP 8](https://peps.python.org/pep-0008/#programming-recommendations) explicitly recommends against `add = lambda x, y: x + y` in favor of `def add(x, y): return x+y`.  The result is exactly the same except that for the latter, `f.__name__` is `add` instead of `<lambda>` and we consider the specific name to be superior to the generic name.  For other lambda uses, various alternatives have been proposed and rejected.  I am pretty sure that the one given here is included among them.
