### ISSUE TITLE
Python uses two different methods for Tilde operator.

### ISSUE THREAD

**Issue by mohamadiarch** [python/cpython#113617]
# Bug report

### Bug description:

I think there is a small bug in Python.
```python
print(~60)
```
How does it work? I think we can break it down into three steps:
First step: Convert `60` to binary:  `00111100`. 
Second step: it converts zeros to ones and vice versa. so we would have `11000011`.
Finally, it should convert binary to decimal and Python will print `-61`, but that's wrong. Because Python thinks it's a two's complement number, but it's not, Python has forgotten that it's a one's complement number, we just convert ones and zeros to each other and nothing else, and that's a one's complement number. This means that Python uses the one's complement method in the second step and uses another method (the two's complement method) for converting to decimal number in the final step. And I think this is wrong, we should use one method for both steps. And if we use the one's complement to decimal method, the answer should be `-60` and not `-61`.
![2024-01-01_142812](https://github.com/python/cpython/assets/46373929/36807a62-ab14-4e31-bcc2-e762c5dfca28)

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
That's not a bug, this works as intended. For your case you should use `operator.neg`:
```python
>>> import operator
>>> operator.neg(60)
-60
```
Changing it would be break backward compatibility with a lot of python code.

**Comment by WolframAlph** [comment]
Hi, I think you confuse couple of things:

> we just convert ones and zeros to each other and nothing else, and that's a one's complement number.

Under the hood, negative integers are represented in 2’s complement format. When you perform `~`, you don’t change negative integer representation from 2’s to 1’s complement. You just flip the bits. Maybe the fact that `~` is also called ‘complement’ confused you. But anyway, here is further explanation:

Negation of integer `x` is defined as:
&emsp;  $`-x = flipbits(x) + 1`$
Since `~` operator flips the bits (makes complement) of the integer we can express it as:
&emsp;  $`-x = \sim x + 1`$
Which means that:
&emsp;  $`\sim x = -x - 1`$

This is why `~60 == -61`, which is correct.

**Comment by mohamadiarch** [comment]
@WolframAlph Can you break it down with an example 60? I think if we use `flipbits(x) + 1` for "00111100" (60 in decimal) we should have "11000100" and is this means "-61"?

**Comment by WolframAlph** [comment]
@mohamadiarch, `11000100` is `-60` in 2’s complement. `flipbits(x) + 1` negates `x`, remember? 
So `flipbits(60) + 1 == -60`

**Comment by mohamadiarch** [comment]
@WolframAlph  I have understood your formula. But what I can't figure out is the method of going from binary to decimal. You use the formula for the final answer and get `-61`, but I want to read it without it.  You said: `You just flip the bits' and I think this is an introduction to one's complement. If I flip all the bits of `00111100` I get `11000011`. Now if I want to read this number I have two choices. Reading from 1's complement or reading from 2's complement. For the first one, I get `-60` and for the second one, I get `-61`. But if we use the formula we get `-61`.

**Comment by WolframAlph** [comment]
@mohamadiarch 
>Now if I want to read this number I have two choices

Correct.
>Reading from 1's complement or reading from 2's complement

Wrong. Have you read what I wrote earlier?
>Under the hood, signed integers are represented in 2’s complement format.

So yes, you can interpret `11000011` binary number in 2 ways. But those are:
1. Interpret as 8bit signed integer - `-61`
2. Interpret as 8bit unsigned integer - `195`

Interpretation depends on context. In this scenario context is that `x = 60` is positive and  therefore `~x` will produce negative number, because if `x >= 0` then `~x = -x - 1` produces negative result. This is why Python tells you it is `-61` instead of `195`. In summary: computer sees signed integers in 2’s complement and you cannot expect to get correct results by interpreting as 1’s complement.

**Comment by terryjreedy** [comment]
[invert operator ~](https://docs.python.org/3/reference/expressions.html#unary-arithmetic-and-bitwise-operations): "The bitwise inversion of x is defined as -(x+1). "  @mohamadiarch In the future, please consult the docs. A place to discuss such details is https://discuss.python.org/c/users/7.

**Comment by mohamadiarch** [comment]
@WolframAlph I made a mistake. I'm sorry, I shouldn't have said that in this place. Thank you for your explanation. Your explanation was perfect.
