### ISSUE TITLE
DOC: add_done_callback - callback is called with Future as the LAST non-keyword argument, rather than the first/only argument

### ISSUE THREAD

**Issue by Ennovate-com** [python/cpython#113635]
# Documentation

In (A) [Future Object add_done_callback(callback, *, context=None)](https://github.com/python/cpython/blob/8e4ff5c7885abb04a66d079499335c4d46106aff/Doc/library/asyncio-future.rst?plain=1#L161) it says _The callback is called with the Future object as its only argument._ It also says _[functools.partial()](https://docs.python.org/3/library/functools.html#functools.partial) can be used to pass parameters to the callback_.

However, (B) [functools.partial(func, /, *args, **keywords)](https://docs.python.org/3/library/functools.html#functools.partial) says _If more_ [non-keyword] _arguments are supplied to the call, they are appended to args._

When I call `add_done_callback(functools.partial(done_callback, *args, **kwargs))`, what appears to be happening is what is described by (B) rather than (A). In other words:

[functools.partial()](https://docs.python.org/3/library/functools.html#functools.partial) can be used to pass **additional** parameters to the callback. The callback is called with the Future object as the **last (possibly only)** non-keyword argument (rather than its first/"only" argument).

**Comment by gvanrossum** [comment]
Hi @Ennovate-com, thanks for submitting an issue. I think the docs are actually correct though: in (A), "the callback" is whatever you pass to `add_done_callback()`, which if you are using `functools.partial()` is the "partial" object returned by that, not the "original" callback you are passing to `partial()`. So the "partial" object is indeed called with the future as its first argument -- and whatever `partial()` does with that argument is beyond control of `add_done_callback()`. (If it was me, I'd have used `lambda` instead of `partial()`, but that's irrelevant here. :-)

There is even an example that shows exactly what you are seeing. So I don't feel there's a need to update the docs here.

**Comment by Ennovate-com** [comment]
@gvanrossum Makes sense.

```
partial = functools.partial(callback, *args, **kwargs)
future.add_done_callback(partial)

would result in the done callback, with the first/only paramter being the future:

```
partial(future)
```

resulting in
 
```
callback(*args, future, **kwargs)
```
 
per the [functools.partial(func, /, *args, **keywords)](https://docs.python.org/3/library/functools.html#functools.partial) documentation regarding the future being appended to the partial non-keyword args.

Thanks. Apologies for the confusion on my part. In using the name `callback` as above, I was incorrectly thinking of "callback" being the parameter being passed to the partial, rather than the partial itself. And thanks for the suggestion to use `lambda` as an alternative to `functools.partial`.
