### ISSUE TITLE
CSV reader should support QUOTE_NOTNULL and QUOTE_STRINGS

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#113732]
# Feature or enhancement

New quoting rules QUOTE_NOTNULL and QUOTE_STRINGS were introduced in #67230. But they only affect CSV writer, not CSV reader. I think that they should affect CSV reader in the same way as QUOTE_NONNUMERIC does.

* QUOTE_NOTNULL -- unquoted empty strings are returned as None.
* QUOTE_STRINGS -- unquoted empty strings are returned as None and unquoted  numeric strings are returned as float.

It is perhaps too late to change this in 3.12, so it can be considered as a new feature in 3.13.

### Linked PRs
* gh-113738

**Comment by serhiy-storchaka** [comment]
On other hand, it is the documented behavior. So this can be considered as a bugfix.

* It is a bug fix in 3.12.2.
* It is a new feature in 3.13. 3.12.2 needs a documentation fix, and the change between 3.12 and 3.13 is breaking.

**Comment by merwok** [comment]
This change feels needed but probably disruptive, as people who tried using the parameters probably saw that it doesn’t work as expected, and either are fine with it or already working around it. So I think this is a bug fix for 3.13.

**Comment by serhiy-storchaka** [comment]
I think that it is less disruptive than alternatives. For now, not much people use 3.12, and even less use new quoting options. But the mass adaptation of 3.12 will start before releasing 3.13, and at that time more code can be broken by 3.13 changes.

1. Fix this in 3.12.2. It is only disruptive for these who use new quoting options in 3.12.0 and 3.12.1.
2. Change the behavior in 3.13 without warning. It is disruptive for all users of 3.12, and also for users of 3.13 who occasionally run their code on the contemporary supported 3.12.
3. Emit a FutureWarning in 3.13 and 3.14 and change the behavior in 3.15. It is how such changes should be done, but it increases the number of affected people and delay the proper solution.
4. Emit a FutureWarning in 3.12.2+ and 3.13 and change the behavior in 3.14.
5. Emit a FutureWarning in 3.12.2+ and change the behavior in 3.13.

It was better to do this before 3.12.0, but it was not done, and now we have no good options. The longer we delay the solution, the worse options we have. cc @Yhg1s

**Comment by merwok** [comment]
Ah, I missed that the options were introduced in 3.12! Option 1 to fix in 3.12.2 seems great then. Great that you tagged the release manager to confirm.

**Comment by Yhg1s** [comment]
We should consider observable behaviour, rather than documentation, to be leading. Changing the behaviour in 3.12.2 is too disruptive. Patch releases also should not add new warnings. Given that it was documented to behave this way, I don't think it's necessary to add a new warning for this. That it doesn't work as documented is a bug we can't fix in 3.12, but we can in 3.13.

**Comment by merwok** [comment]
> That it doesn't work as documented is a bug we can't fix in 3.12, but we can in 3.13.

Would it be useful to add a note in the 3.12 docs?

**Comment by oct15demo** [comment]
I have been following this issue for a while. Could you please fix the documentation in https://docs.python.org/3/library/csv.html which currently says under  csv.QUOTE_NOTNULL:

"Instructs [reader](https://docs.python.org/3/library/csv.html#csv.reader) objects to interpret an empty (unquoted) field as None and to otherwise behave as [QUOTE_ALL](https://docs.python.org/3/library/csv.html#csv.QUOTE_ALL)."

If you bug fix 3.12 you could then change the documentation back again to reflect the fix. If the reader implementation of QUOTE_NOTNULL isn't pushed until 3.13, there is still no reason not to delete the notice of the unimplemented feature in 3.12. An alternative is some note to the documentation referencing this issue.

In either case, I would argue it would also be helpful aside from deleting a description of the unimplemented feature, to note that QUOTE_NOTNULL is not implemented in the reader currently. 

I've been working with PostgreSQL, and have need for treating empty strings and nulls differently. For now, Java's opencsv does have the feature, but I look forward to the python version, and being able to round trip csv files wholly in python.

**Comment by Prometheus3375** [comment]
Adding a note to the documentation will be useful indeed. Was just writing some .csv involved code and because of the documentation of new quoting constants increased python version. Then I realized that these constants does not work for reading as documentation suggests. Hopefully I found this issue.

Actually, instead of the note of bugged behavior maybe it will be better to simply remove reader instruction in 3.12 documentation and then add in 3.13 as an addition.

Also, one of the `None` is not properly formatted.
![image](https://github.com/python/cpython/assets/35541026/69539b85-d433-44d1-903f-68aa22166c25)

**Comment by merwok** [comment]
> instead of the note of bugged behavior maybe it will be better to simply remove reader instruction in 3.12 documentation

I don’t think so: it is common to read a newer version of the docs than the Python version you’re using. It’s best to be clear about the behaviour and the change here.

Does someone want to open a pull request for this?
If not, we should open a doc ticket to make sure this doesn’t get forgotten.
