### ISSUE TITLE
pathlib: clarify difference between pathlib and os.path

### ISSUE THREAD

**Issue by SubaruArai** [python/cpython#113838]
# Documentation

Currently, in [pathlib's doc page](https://docs.python.org/3/library/pathlib.html) the reason to use `os.path` instead is only stated as below:
> For low-level path manipulation on strings, you can also use the [os.path](https://docs.python.org/3/library/os.path.html#module-os.path) module.

This doesn't explain when one might want to use `os.path` instead of `pathlib`.
I propose to add several examples where one might want to use `os.path` at the same place where the aforementioned sentence was (i.e. near the top) to let users choose the appropriate tool for their job.

## Example of difference against `os.path` (i.e. `str`)

Since `pathlib` is a library to handle filesystem paths, design decisions were made to format when creating an instance. Here are some examples:

| input | converting to `pathlib` |
| --- | --- |
| path with trailing slash (`a/b/`) | strips (`a/b`) |
| path with single leading dot (`./a/b`) | strips (`a/b`) |
| path with single dot inside (`a/./b`) | strips (`a/b`) |

As stated below, some type of stripping can change the meaning of the input. (trailing slash & leading dot)

## What are the impact if we aren't aware of this?

1. A quick google search for "python pathlib vs os.path" doesn't give any reason to choose `os.path` over `pathlib` on the 1st page. Even [a stack overflow question](https://stackoverflow.com/questions/70259852/) doesn't have an answer.
2. As discussed in the python discourse [topic: leading dot](https://discuss.python.org/t/suggestion-for-pathlib-differentiate-explicit-and-implicit-local-paths-pathlib-strictpath/31235) [topic: trailing slash](https://discuss.python.org/t/pathlib-preserve-trailing-slash/33389), there are cases where preserving seemingly meaningless dots and slashes.
3. With the wide-spread adoption of libraries that automatically parses inputs into specific classes (`argparse`, `fastapi`/`pydantic`, `marshmallow`, etc.), it is more intuitive to directly cast the input to `pathlib`. As stated on (2.), there needs to be documentation to point when *not* to use `pathlib`.

### Linked PRs
* gh-115926

**Comment by tovrstra** [comment]
It would be helpful to also document third-party alternatives to `os.path` and `pathlib`.

A comparison of just the two built-in options gives the impression that some people has to choose between two suboptimal solutions: 

- `os.path`: good because it preserves dots and slashes that are sometimes useful, but bad because it results in poorly readable code.
- `pathlib`: good because it makes code more readable code, but bad because it has a too strong opinion on what a path is (not).

There are other options out there, such as [`path`](https://github.com/jaraco/path) for those who like the convenience of `pathlib` but cannot use it because its compulsory path normalization is discarding information relevant to their use case.

**Comment by barneygale** [comment]
PR up: https://github.com/python/cpython/pull/115926
