### ISSUE TITLE
Make queue.SimpleQueue thread-safe in `--disable-gil` builds

### ISSUE THREAD

**Issue by mpage** [python/cpython#113884]
# Feature or enhancement

### Proposal:

Instances of `queue.SimpleQueue` have mutable state that is not safe to mutate without the GIL. The previous implementation (in 3.12) was https://github.com/colesbury/nogil-3.12/commit/7e60a01aee. 

@colesbury - You mentioned in chat that porting the 3.12 approach wouldn't be straightforward. Can you say more?

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-114161
* gh-114259

**Comment by colesbury** [comment]
@mpage, after looking it over again, I think the nogil-3.12 approach is mostly the right direction with a few modifications:

1) Replace the manual `_PyMutex_lock()/unlock()` calls with critical sections and remove the `_PyMutex mutex` field. Since, the code already uses Argument Clinic (AC), this is mostly just a matter of adding the `@critical_section` to the AC input. This will avoid the extra lock operations in the default build, which can rely on the GIL.
2) The parking lot API changed slightly; it's not a huge difference. For example, the unpark operation now takes a callback

This means we will go from a SimpleQueue implementation built around `list` to run that more explicitly manages a buffer. I think that's worthwhile here; otherwise I think handling the synchronization across both the `list` operations and the containing `SimpleQueue` will be too messy.

**Comment by erlend-aasland** [comment]
Thank you, @mpage and @colesbury 🙏
