### ISSUE TITLE
test_idle fails on Devuan 5 Linux

### ISSUE THREAD

**Issue by LeamHall** [python/cpython#113903]
# Bug report

### Bug description:

On Devuan 5, with this command in a build script:

```
./python -m test -uall -j0 > $test_file 2>&1
```

the following is logged:

```
0:10:21 load avg: 3.54 [229/469/2] test_idle failed (1 error)
test test_idle failed -- Traceback (most recent call last):
  File "/usr/local/src/forks/cpython/Lib/idlelib/idle_test/test_configdialog.py", line 452, in test_highlight_target_text_mouse
    click_it(start_index)
    ~~~~~~~~^^^^^^^^^^^^^
  File "/usr/local/src/forks/cpython/Lib/idlelib/idle_test/test_configdialog.py", line 436, in click_it
    x, y, dx, dy = hs.bbox(start)
    ^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

But this passes:
```
./python -m test -uall -j0 test_idle
Using random seed: 2055385424
0:00:00 load avg: 0.00 Run 1 test in parallel using 1 worker process
0:00:01 load avg: 0.00 [1/1] test_idle passed

== Tests result: SUCCESS ==

1 test OK.

Total duration: 1.8 sec
Total tests: run=283 skipped=81
Total test files: run=1/1
Result: SUCCESS
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-113973
* gh-113974
* gh-113975

**Comment by terryjreedy** [comment]
test_idle is passing because gui tests are not run.  Same command in repository on my older Windows PC, current main:
```
Total duration: 19.7 sec
Total tests: run=619 skipped=4
```
If I omit `-uall`, I get what you did.

In any case, `hs.bbox(start)` returns None only if the 'start' char is not visible, so I  believe the font being used on your system must be such that the last line is not visible.  You could immediately test this by moving copying lines 428-9 to above 436 and indenting to match and changing `1.0` to `start'.  I will add a PR with this later.

**Comment by LeamHall** [comment]
@terryjreedy, thanks! I just compiled 3.13 and it's fine, and am testing 3.12 now. Again, thank you!
