### ISSUE TITLE
Deprecation warning during text completion in REPL

### ISSUE THREAD

**Issue by WolframAlph** [python/cpython#113978]
# Bug report

### Bug description:

Define function inside REPL session:

```pycon
>>> def f():pass
```

then try to hit TAB to get suggestions for `f.__code__.` and you will be left with this ugly output without suggestions:

```pycon
>>> f.__code__./root/Desktop/cpython-main/Lib/rlcompleter.py:191: DeprecationWarning: co_lnotab is deprecated, use co_lines instead.
  if (value := getattr(thisobject, word, None)) is not None:
```
then try to access `co_lnotab` and you will get this warning again:
```pycon
>>> f.__code__.co_lnotab
<stdin>-1:1: DeprecationWarning: co_lnotab is deprecated, use co_lines instead.
```

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-113979
* gh-119429

**Comment by terryjreedy** [comment]
IDLE's completer uses 'dir(ob)' to get the list of (22) attribute names, including 'co_lnotab'.  `dir` does not access the objects themselves, hence no DeprecationWarning.  This issue arises because rlcompleter accesses objects in order to add suffixes such as '(' or '()'.  I added a note to the IDLE issue #113978 proposing to copy rlcompleter.

**Comment by gaogaotiantian** [comment]
Are you on debug build? DeprecationWarning should be turned off on release build unless it's directly from `__main__`, so you should not be able to reproduce this on release build - let me know if you can.

If you can't do that, this is a much smaller issue. Personally, I don't hate warnings on debug mode. I am a bit hesitated to turn off all the warnings during text completion in REPL though.
