### ISSUE TITLE
pathlib.PosixPath doesn't handle double slashes properly

### ISSUE THREAD

**Issue by LeGEC** [python/cpython#113985]
# Bug report

### Bug description:

seen in python version 3.11.4 :

```python
import pathlib

p = pathlib.PosixPath('//some/path/to/file')
p.relative_to('/some/path')

# Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "/usr/lib/python3.11/pathlib.py", line 731, in relative_to
#    raise ValueError("{!r} is not in the subpath of {!r}"
#ValueError: '//some/path/to/file' is not in the subpath of '/some/path' OR one path is relative and the other is absolute.
```

is this a known issue ?

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
Pathlib follows the POSIX/IEEE 1003.1 specification w.r.t. path names, and this specification says that double slashes at the start of the path name are special: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_271

In particular the [section on path name resoution](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_13) mentions that paths starting with two slashes may be interpreted in a implementation defined manner:

> A pathname consisting of a single <slash> shall resolve to the root directory of the process. A null pathname shall not be successfully resolved. If a pathname begins with two successive <slash> characters, the first component following the leading <slash> characters may be interpreted in an implementation-defined manner, although more than two leading <slash> characters shall be treated as a single <slash> character.

I know of no currently used large platform that actually does this though.

For `pathlib.PosixPath` "//some/path" and "/some/path" are _not_ the same path because of this detail of the POSIX specification.

**Comment by barneygale** [comment]
This is intentional behaviour as Ronald explains! Thanks all the same for reporting it, @LeGEC.
