### ISSUE TITLE
Tier 2 optimizer's abstract interpreter

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#114058]
### Linked PRs
* gh-114059
* gh-115085
* gh-115423
* gh-115779
* gh-115817
* gh-115848

**Comment by markshannon** [comment]
We need a lattice of values that embodies type information, `NULL`ness, `None`ness, constant values, version numbers, at the least.

The lattice should look something like this:

```mermaid
graph BT;
    t("True");
    f("False");
    bl("bool");
    nnull(not NULL);
    nnone(not None);
    ot(other types);
    oc(other constants);
    b("bottom(unknown)");
    b-->NULL;
    b-->nnull;
    nnull-->nnone;
    nnull-->None;
    nnone-->ot;
    nnone-->bl;
    ot-->oc;
    oc-->top;
    None-->top;
    NULL-->top;
    bl-->t;
    bl-->f;
    t-->top;
    f-->top;
```

**Comment by markshannon** [comment]
There should be edges from all the nodes (except `bottom`) to `top`, but I've omitted those to avoid the diagram becoming a mess

**Comment by gvanrossum** [comment]
> There should be edges from all the nodes (except `bottom`) to `top`, but I've omitted those to avoid the diagram becoming a mess

Maybe `top` needn't be part of the diagram at all? It ought to be unreachable (IIUC it represents an impossible condition). Might as well simplify the diagram a bit further.

**Comment by gvanrossum** [comment]
According to Wikipedia, in type theory, [Bottom](https://en.wikipedia.org/wiki/Bottom_type) is the type that has no values, whereas [Top](https://en.wikipedia.org/wiki/Top_type) is the type that encompasses all values. Maybe we should switch to this terminology, and swap `top` and `bottom` in the [diagram](https://github.com/python/cpython/issues/114058#issuecomment-1934416412) above, so that "unknown" is named "top" and there is an arrow from every other nod to "bottom"? (Possibly also just flipping the diagram upside down so that "top" is drawn at the top and "bottom" at the bottom?)

**Comment by gvanrossum** [comment]
```mermaid
graph TB;
    t("True");
    f("False");
    bl("bool");
    nnull(not NULL);
    nnone(not None);
    ot(other types);
    oc(other constants);
    top("top(unknown)");
    top-->NULL;
    top-->nnull;
    nnull-->nnone;
    nnull-->None;
    nnone-->ot;
    nnone-->bl;
    ot-->oc;
    oc-->bottom;
    None-->bottom;
    NULL-->bottom;
    bl-->t;
    bl-->f;
    t-->bottom;
    f-->bottom;
```

**Comment by gvanrossum** [comment]
Offline we agreed that Top is the universal type and Bottom is the empty type, like in my latest diagram. I will update diagrams and text where these terms are used.

**Comment by Tuahm** [comment]
Ok

Pada Sel, 27 Feb 2024 01.56, Guido van Rossum ***@***.***>
menulis:
