### ISSUE TITLE
reversing dataclasses.asdict

### ISSUE THREAD

**Issue by lczyk** [python/cpython#114125]
# Documentation

Documentation of `dataclasses.asdict` does not mention anything about reversing the conversion. I suggest adding a paragraph on keyword argument unpacking as a possibility.

### Linked PRs
* gh-114126

**Comment by ericvsmith** [comment]
Is it really worth mentioning this? It's the same as every other class.

**Comment by MarcinKonowalczyk** [comment]
sure, but like that it highlights that this would work only for shallow dataclasses.

**Comment by MarcinKonowalczyk** [comment]
more context on my side:

i've made the suggestion based on my own experience of going form _"how do i do this?"_ to _"lets do the right thing and search the python docs as opposed to \<some-other-python-reference\>?"_ and then not finding the answer to what i'd consider part of basic usage. i guess since `asdict` came from the dataclasses module i was expecting there to be `fromdict`, realised that would be stupid/impossible and then just failed to make the (admittedly tiny) mental jump to the fact that its just a class. maybe its because i try to avoid the ** syntax in my normal python dev.

the specific use case for me was handling both ends of an api in a flask app and sending `dataclasses.asdict`s on one end and receiving them on the other.

**Comment by MarcinKonowalczyk** [comment]
but yeah, no strong feelings if the consensus is that this should not be in the docs

**Comment by brianschubert** [comment]
Even "shallow" dataclasses don't necessarily round-trip with `asdict`. Using any of `@dataclass(init=False)`, `InitVar`, `field(init=False)`, or  defining `__init__` or `__post_init__` would likely break round tripping with `asdict`.

Consider one of the examples given elsewhere in the docs:
```python
@dataclass
class C:
    a: float
    b: float
    c: float = field(init=False)

    def __post_init__(self):
        self.c = self.a + self.b
```
This dataclasses doesn't round-trip with `asdict`:
```pycon
>>> c = C(1, 2)
>>> C(**asdict(c))
Traceback (most recent call last):
...
TypeError: C.__init__() got an unexpected keyword argument 'c'
```

**Comment by MarcinKonowalczyk** [comment]
yup. fair. missed that. the doc as proposed would therefore just be confusing so withdrawing the PR. thanks for the feedback! :))

**Comment by ryanleecode** [comment]
Python is a failed language

**Comment by voiceusa01** [comment]
How is it a failed language?
________________________________
