### ISSUE TITLE
ftplib CLI fails to retrieve files

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#114241]
# Bug report

The `ftplib` module has undocumented feature -- a CLI that implements a simple FTP client. It allows listing directories and retrieving files. But retrieving files does not work in Python 3, because it writes binary data to sys.stdout.

It's help is also incomplete and unclear.

Documenting, testing and extending this CLI to a more complete FTP client is a matter of other issues. Here I only want to fix small functionality that it currently has.

### Linked PRs
* gh-114242
* gh-114404
* gh-114405

**Comment by tom93** [comment]
A couple more small bugs if anyone wants to look into this:
 - There are two calls to `sys.stderr.write` where a trailing `\n` should be inserted
 - The [line](https://github.com/python/cpython/blob/6f4b242a03e521a55f0b9e440703b424ed18ce2f/Lib/ftplib.py#L937) `userid, acct, passwd = netrcobj.authenticators(host)` fails with "TypeError: cannot unpack non-iterable NoneType object" if the netrc file exists but doesn't contain a host/default entry. Per the [docs](https://docs.python.org/3/library/netrc.html#netrc.netrc.authenticators) (and source) it returns `None` if there is no entry, so ftplib should check for `None` instead of using `except KeyError:`.

**Comment by erlend-aasland** [comment]
> Documenting, testing and extending this CLI to a more complete FTP client is a matter of other issues.

I'm looking into improving the docs.
