### ISSUE TITLE
Misleading exception for empty enum.Flag

### ISSUE THREAD

**Issue by jobh** [python/cpython#114474]
# Bug report

### Bug description:

Instantiating a zero-value flag from an empty `enum.Flag` became an error sometime around CPython 3.11/3.12. In 3.12, a workaround text was added to the exception message, but this text is incorrect:

```python
Python 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 08:03:24) [GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import enum
>>> E = enum.Flag("E", names=())
>>> E(0)
Traceback (most recent call last):
  [...]
TypeError: <flag 'E'> has no members; specify `names=()` if you meant to create a new, empty, enum
```

As you can see, `names=()` was part of the enum definition as recommended; but it still fails.

I don't know if the exception itself is unintended, or if it's just the explanatory text that is wrong.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by sunmy2019** [comment]
In some senses, this hint is not wrong either. `<flag 'E'>` can be used to create a new enum. for example

```py
>>> import enum
>>> E = enum.Flag("E", names=())
>>> E1 = E("E1", names=())
>>> E1
<flag 'E1'>
>>> E
<flag 'E'>
>>> E2 = E1("E1", names=(("a",1),("b",2)))
>>> E2
<flag 'E1'>
>>> E2.__members__
mappingproxy({'a': <E1.a: 1>, 'b': <E1.b: 2>})
```

**Comment by ethanfurman** [comment]
The exception is correct.  There is probably room for improvement in the error text.

**Comment by jobh** [comment]
@sunmy2019 It can perhaps be used for other purposes, but it's impossible to access its only valid state (0). This may be for good reasons — maybe it's a common user error? I don't know. But the advice given does not give a solution.

**Comment by ethanfurman** [comment]
An flag with no members has no valid state.  If `0` is valid, specify it:

```python
E = enum.Flag("E", [('zero',0)])
E(0)
# <E.zero: 0>
```

**Comment by jobh** [comment]
@ethanfurman IMO that's an inconsistency with all other flags which has a valid zero state even if not named. But I'm fine with that, only that the error text advice is wrong in that case - which I think we agree on.

**Comment by ethanfurman** [comment]
@jobh Any enum or flag with no members is merely a template to be used to create other enums/flags.  Following that logic, an "empty" flag (i.e. template), does not have a state of "nothing set" since it has nothing to set -- therefore `0` is not valid.

Your own example shows using `names=()` to create your `E` flag, and as @sunmy2019 also showed, `E` can then be used to create other flags, either empty or with members -- so the error message is correct: either you asked for a member when none exist, or you were trying to make a new flag (e.g. `E1` above) in which case `names=()` is needed.
