### ISSUE TITLE
posixpath.commonpath: Check for empty iterables broken

### ISSUE THREAD

**Issue by srittau** [python/cpython#114709]
# Bug report

### Bug description:

This came up in python/typeshed#11310: When passing an empty sequence to `commonpath()`, a `ValueError` is raised with an appropriate error message. When an "empty" iterable is passed, an `IndexError` is raised instead, although iterables otherwise work fine:

```python
from posixpath import commonpath

commonpath([])  # -> ValueError: commonpath() arg is an empty sequence
commonpath(iter([]))  # -> IndexError: tuple index out of range
```

The fix is trivial, I'll send a PR. Technically this is an API change, though, although the old API is unexpected.

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-114710
* gh-115639

**Comment by serhiy-storchaka** [comment]
It did not supported arbitrary iterables initially, it only worked with sequences. Then in 3.6 it started working with non-empty iterables by accident, but it was not intentional change, it was an implementation detail.

Accepting an arbitrary iterable is a new feature. This change can only go in future 3.13.

**Comment by serhiy-storchaka** [comment]
Please revert the change in `versionchanged:: 3.6` and add `versionchanged:: 3.13`.

**Comment by hauntsaninja** [comment]
Done in https://github.com/python/cpython/pull/115639
