### ISSUE TITLE
Microsoft Store does not include Arm64 version

### ISSUE THREAD

**Issue by reflectronic** [python/cpython#114845]
# Bug report

### Bug description:

Downloading Python from the Microsoft Store on an Arm64 computer appears to install an x64 version. 

![image](https://github.com/python/cpython/assets/27514983/6e028828-5a52-4e42-9ad2-fc7b0bb050ff)
![image](https://github.com/python/cpython/assets/27514983/8540de47-83d4-49ea-8464-680dc82def5a)

Upon inspection using a service like http://store.rg-adguard.net, it seems that only an x64 package has been uploaded to the Microsoft Store. 

This would suggest that Python cannot be installed from the Microsoft Store on an Arm64 computer running Windows 10 (or a computer running 32-bit Windows, for that matter).

To support this, a multi-architecture bundle ([`msixbundle`](https://learn.microsoft.com/en-us/windows/msix/package/bundling-overview)) would need to be generated and uploaded to the Microsoft Store. It's not clear to me that the build setup you have is generating these. Is there interest in supporting this? If support was added, would further releases to the Microsoft Store use these msixbundles for multi-architecture support?

### CPython versions tested on:

3.10, 3.11, 3.12

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
Our Windows installers are .exe files, no longer .msi files.  Our main installer support for Windows is on [python.org](https://www.python.org/downloads/release/python-3121/), with 3 for normal installs and 3 embeddable.  Please get your ARM installer there. I believe the store gives a simplified default for users who don't want so many choices.  I expect a Windows expert will close this request.

**Comment by zooba** [comment]
Because ARM64 is still experimental, we don't want to inadvertently lead users into getting it and then having no package ecosystem to use it with. The [alpha releases of 3.13](https://www.microsoft.com/store/apps/9PNRBTZXMB4Z) on the Store have ARM64 builds, as did the prereleases of 3.12. But since there's no option for users to select the x64 build, our only choice is to leave them off for now. This is our standard practice for experimental releases - the experimental free-threaded builds will not be available through the Store either when they release.

If you want to help increase adoption of ARM64 throughout the ecosystem, you can help various packages add builds and publishing steps to put wheels on PyPI, as that's essentially what is blocking us. They will likely need help testing, as that's the biggest gap right now. Unfortunately, the core team isn't in a position to provide test infrastructure for everyone either, so we can't do much from here apart from make the binaries available.

And as Terry noted, the ARM64 installers are available from python.org. You can also get [Nuget-installable packages](https://www.nuget.org/packages/pythonarm64) of the ARM64 builds. We just can't yet put them in the Store.
