### ISSUE TITLE
pathlib read_text intermittently reads empty string from write_text

### ISSUE THREAD

**Issue by davetapley** [python/cpython#115113]
# Bug report

### Bug description:

Have a thread attempting to `read_text` from a random path (printing its contents on first non-`FileNotFoundError`),
then `write_text` to the same random path on the main thread:

```python
import tempfile
import threading
import uuid
from pathlib import Path


def print_file(path: Path):
    while True:
        try:
            print(path.read_text())
            return
        except FileNotFoundError:
            ...


def test():
    path = Path(tempfile.gettempdir()) / str(uuid.uuid4())
    thread = threading.Thread(target=print_file, args=(path,))
    thread.start()

    path.write_text("Lorem ipsum dolor sit amet")


for _ in range(10):
    test()
```

You will see output like this:
```

Lorem ipsum dolor sit amet


Lorem ipsum dolor sit amet
Lorem ipsum dolor sit amet
Lorem ipsum dolor sit amet

Lorem ipsum dolor sit amet
Lorem ipsum dolor sit amet
```

Sometimes the string has been written when `read_text` occurs, but sometimes it has not.

I ran in to this during testing where I'm using [tenacity](https://github.com/jd/tenacity) to retry until a worker thread is done.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by serhiy-storchaka** [comment]
It is an expected behavior. `Path.write_text()` is not an atomic operation. First it open a file for writing (creating a new file if it did not exist and truncating and existing file), then write an encoded string (perhaps in several chunks if it is large enough, the closes the file). If you read a file between its opening and writing into it, you can see an empty file or a partial content.

If you want an atomic operation, write into another file (preferable in the same directory), and then replace the target file with it (using `os.replace()`). The success is platform and filesystem depending, but it should work on Posix platform in common cases.
