### ISSUE TITLE
typing.Annotated fails for functions returning UUIDs

### ISSUE THREAD

**Issue by dave-shawley** [python/cpython#115165]
# Bug report

### Bug description:

`typing.Annotated` tries to set an attribute on the _return value_ of calling an annotated callable. This fails when the returned object is immutable. I believe that adding `TypeError` to the `except` clause in `typing. _BaseGenericAlias.__call__` will fix the problem. I'm not sure if there are more cases of the same pattern or not.

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/typing.py#L1128-L1131

### Example

```python
import typing
import uuid

class MyAnnotation:
    def __init__(self, **properties) -> None:
        self.properties = properties

def uuid_from_str(s: str) -> uuid.UUID:
    return uuid.UUID(f'urn:uuid:{s}')

coercion = typing.Annotated[uuid_from_str, MyAnnotation(type='str', format='uuid')]
coercion('00000000-0000-0000-0000-000000000000')
```

### Result

```pythoncon
Traceback (most recent call last):
  File "/Users/.../foo.py", line 12, in <module>
    coercion('00000000-0000-0000-0000-000000000000')
  File "/Users/.../lib/python3.12/typing.py", line 1142, in __call__
    result.__orig_class__ = self
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../lib/python3.12/uuid.py", line 278, in __setattr__
    raise TypeError('UUID objects are immutable')
TypeError: UUID objects are immutable
```

### CPython versions tested on:

3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-115213
* gh-115227
* gh-115228

**Comment by AlexWaygood** [comment]
Arguably there are two bugs here:

1. Why is the uuid module raising `TypeError` from a `__setattr__` method? That seems like an antipattern; it should probably be raising `AttributeError`. We probably can't change that now, though, for backwards-compatibility reasons
2. Yes, the `typing` module should indeed be more careful here. Feel free to send a PR — I think `except Exception` might actually be better here than just adding `TypeError` to the `except` clause. Otherwise we'll just get this bug reported again when somebody tries to use `Annotated` with a class that raises e.g. `RuntimeError` (or whatever) from its `__setattr__` method

**Comment by AlexWaygood** [comment]
Thanks for the report, and the fix!
