### ISSUE TITLE
cProfile doesn't attribute await time to its async function

### ISSUE THREAD

**Issue by gh-andre** [python/cpython#115218]
# Bug report

### Bug description:

Profiling an app with `async` functions makes it hard to identify slow `async` code because cProfile handles `async` calls as multiple calls and not as wait operations. 

This example is for `async.sleep`, but the attached source allows testing against `async` I/O, typical for REST API calls, with the same result, making it hard to attribute time spent in specific `async` functions.

```python
async def sleeper(howlong: float) -> None:
    await asyncio.sleep(howlong)

task1: asyncio.Task[None] = asyncio.create_task(sleeper(5.0))
task2: asyncio.Task[None] = asyncio.create_task(sleeper(10.0))

await asyncio.gather(task1, task2)
```
Run the attached source like this:
```
python -m cProfile -o asyncio-sleeper.cprofile asyncio_sleeper_test.py asyncio.sleep
python -m pstats asyncio-sleeper.cprofile
```
On the `pstats` prompt run this:
```
strip
sort cumulative
callers sleeper
```
This output will be returned:
```
   Ordered by: cumulative time
   List reduced from 753 to 1 due to restriction <'sleeper'>

Function                     was called by...
                                 ncalls  tottime  cumtime
asyncio_sleep.py:4(sleeper)  <-       4    0.000    0.002  {method 'run' of '_contextvars.Context' objects}
```
The 4 calls are for 2 `sleeper` tasks and 2 for `awaits`, when the event loop callback returns control to `sleeper`. However, the cumulative time does not reflect the fact that the function waited for the operation to complete.

Dumping module stats shows the same:
```
stats asyncio_sleep.py
Fri Feb  9 08:51:32 2024    asyncio_sleep.cprofile

         43690 function calls (42971 primitive calls) in 10.093 seconds

   Ordered by: cumulative time
   List reduced from 753 to 2 due to restriction <'asyncio_sleep.py'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        4    0.000    0.000    0.002    0.001 asyncio_sleep.py:4(sleeper)
        1    0.000    0.000    0.000    0.000 asyncio_sleep.py:1(<module>)
```
Only the main module reflects the time spent somewhere in the event loop.
```
stats asyncio_sleep_test.py
Fri Feb  9 08:51:32 2024    asyncio_sleep.cprofile

         43690 function calls (42971 primitive calls) in 10.093 seconds

   Ordered by: cumulative time
   List reduced from 753 to 2 due to restriction <'asyncio_sleep_test.py'>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000   10.093   10.093 asyncio_sleep_test.py:1(<module>)
        2    0.000    0.000    0.001    0.001 asyncio_sleep_test.py:7(main)
```
The attached source also contains basic code that does `async` I/O. Start the HTTP server in another terminal window like this:
```
python http_server.py
```
, and then run the profiling session like this:
```
python -m cProfile -o asyncio-sleeper.cprofile asyncio_sleeper_test.py http_request
```
The outcome is the same as with `asyncio.sleep`.

The time between `await` callbacks should be attributed to the `async` function with those `await` keywords. Otherwise it is very hard, sometimes impossible, to break down wait times between various components, such as REST API, `async` database access, etc.

This archive contains 2 test files, which are sufficient to run both sleep tests. For the I/O test, start the HTTP server in the 3rd file, as described above.

[asyncio-sleep-test.zip](https://github.com/python/cpython/files/14222735/asyncio-sleep-test.zip)

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by gaogaotiantian** [comment]
This is not a bug, this just truthfully represents how the code works. It's like throughput vs latency, cProfile measures the actual time async tasks take, not how long it takes from the start of the task to the end of it, because during that "wait time", other tasks are running and it'll be a "double count". Actually, cProfile is not even aware of async stuff, because under the hood they are just generators.

The actual execution is like this (I had to shrink your `5s` wait to `5ms` so it's easier to read):
![image](https://github.com/python/cpython/assets/13121107/b14d6f8a-95a3-4bc0-8b5c-ea90bb5d5836)

Task-2 and Task-3 is your real `sleeper` task and as you can tell, they do not take much time at all. They are just scheduled to be brought up later. It would be unfair to blame them for CPU cost.

Metaphor:
Someone goes to a doctor, takes a blood test and the doctor asks him to come back next week for the test result. The doctor is not responsible for whole week time cost. The patient can do whatever he wants to do during the week.

And that's how the profilers should understand the code as well.

**Comment by gh-andre** [comment]
@gaogaotiantian I realize how it works - I did mention that cProfile measures actual callback time. 

What I'm highlighting is that currently there is no way to figure out the wait time for `async` functions. What cProfile shows is the function time, not the cumulative time, which should include all of its child calls, and `await` is just an implementation detail for those child calls that simply run in background, so `await` time should be included into cumulative time.

**Comment by gaogaotiantian** [comment]
> What cProfile shows is the function time, not the cumulative time, which should include all of its child calls, and `await` is just an implementation detail for those child calls that simply run in background, so `await` time should be included into cumulative time.

That's inaccurate.

There's no "child call". The `sleep` function returned and the scheduler started another function (or polling until an available one). No other async task is the "child" of the `sleep` task - so there's no cumulative time. Each task is of their own and has no relationship with others. They are all managed by the scheduler, or the event loop. The time spent on other tasks, or in the event loop, is not and should not be recorded, in any form, to the individual task.

**Comment by gaogaotiantian** [comment]
I'm not saying it's unreasonable to get the "duration" of the task, or how long it takes from the beginning of the task, to the end of the task. It is definitely a useful measurement in many cases. However, that's not what cProfile does - cProfile generates information about how long each part of the program "executed", or the actual CPU time it used. It would be confusing to users if it generates data that's against what it claims to generate.

At very least, this is not a bug. cProfile does what it claims to do. This could be a feature request, which we could have further discussion about. I will stand on my side though - I don't believe this is something cProfile should do.

However, there might be other profilers in the market that gives such information, and we always encourage Python users to look for what they need on the library market because they are a huge part of Python.

**Comment by gh-andre** [comment]
@gaogaotiantian Well, what's a bug or not is certainly defined by the owners of this repository, so no argument there. I will leave it to you guys to decide whether you want to track this as a feature or just close it. I like cProfile for speed and flexibility of the stats viewer, so I think this would be a good addition, but if there's no consensus here, go ahead and close it.

**Comment by Jason-Y-Z** [comment]
+1 to @gaogaotiantian - we shouldn't mix runtime with wait-time here
But the use case from @gh-andre is certainly valid, some example discussion/package for this  - https://stackoverflow.com/questions/54292461/how-to-profile-benchmark-python-asyncio-code

**Comment by gh-andre** [comment]
@Jason-Y-Z In an `asyncio` app most work is supposed to be done outside of the event loop, so measuring only the active running time in coroutines will only highlight blunders that shouldn't be in `asyncio` code to begin with. So, what you are basically saying is that the always-available Python profiler is not intended and, never will be (since it's the intended behavior), for `asyncio` code. That's unfortunate, because it's a good profiler otherwise. Ok, I'll close this issue.
