### ISSUE TITLE
Performance regression in 3.12 with string joins

### ISSUE THREAD

**Issue by kartiksubbarao** [python/cpython#115487]
# Bug report

### Bug description:

I'm seeing a 15% slowdown from 3.11.8 to 3.12.1 with the following string join scenario on Fedora 39:

```
% python3.11 -m timeit "','.join(['X' for _ in range(500000000)])"
1 loop, best of 5: 6.33 sec per loop
% python3.12 -m timeit "','.join(['X' for _ in range(500000000)])"
1 loop, best of 5: 7.27 sec per loop
```

At the same time though, there's no difference with a very similar scenario:
```
% python3.11 -m timeit "','.join(['X'] * 500000000)"
1 loop, best of 5: 2.6 sec per loop
% python3.12 -m timeit "','.join(['X'] * 500000000)"
1 loop, best of 5: 2.6 sec per loop
```

The actual issue that I'm seeing is a 50% slowdown in a pandas script (reported at https://github.com/pandas-dev/pandas/issues/57423) where the only difference is Python 3.11 vs 3.12. I'm not sure how much of this is pandas and how much is python. Any help in troubleshooting either of these issues would be greatly appreciated.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
> I'm seeing a 15% slowdown from 3.11.8 to 3.12.

Have you tried 3.12.2? Do you see the same thing?

**Comment by tomasr8** [comment]
The difference seems to be coming mostly from creating the list itself rather than the string joining.
With this simple script:

```python
import time                           
                                      
t = time.time()                       
x = ['X' for _ in range(500000000)]
print('List', time.time()-t)                  

t = time.time()                       
','.join(x)                           
print('Join', time.time()-t)
```

I get:

| | 3.11.8  | 3.12.1  |
|---|---|---|
| List  | 11.2s  | 14.2s |
| Join | 3.4s    | 3.2s |

So the string joining is almost identical while the list allocation is much slower in 3.12.1.

As for the second scenario, it is also about equal for me with about 1 second to allocate the list and 3 seconds again to join it. I suppose the second scenario is faster because it does one allocation (`BUILD_LIST` in the disassembly) while the first one uses `LIST_APPEND`. No idea why the speed is different between versions though..

**Comment by kartiksubbarao** [comment]
@AlexWaygood Wow, 3.12.2 smokes them both, on both tests!

```
/opt/python-3.12.2/bin/python3 -m timeit "','.join(['X' for _ in range(500000000)])"
1 loop, best of 5: 5.68 sec per loop
% /opt/python-3.12.2/bin/python3 -m timeit "','.join(['X'] * 500000000)"
1 loop, best of 5: 2.02 sec per loop
```

I tested my pandas scripts and 3.12.2 is much closer to or even better than 3.11. Thanks for the tip!

Thanks @tomasr8 for taking a look as well.

Given that 3.12.2 has resolved things for me, I'll close out this issue.

**Comment by AlexWaygood** [comment]
Good :) I had a vague memory of previous issues along these lines, so I thought there was a good chance the performance regression had already been fixed. Glad it was!
