### ISSUE TITLE
Odd space

### ISSUE THREAD

**Issue by AV-86** [python/cpython#115629]
https://github.com/python/cpython/blob/9d34f60783b726de5bb0352d0efb1cbd23a4ac89/Lib/xml/etree/ElementTree.py#L896

Is this space at closing XML tags is necesary?

**Comment by terryjreedy** [comment]
Whether or not the space is strictly necessary for self-closing tags (I am not sure), it is allowed and appears to be at least customary, as (nearly) all examples in the following have it.
https://www.tutorialstonight.com/self-closing-tags-in-html
https://stackoverflow.com/questions/3558119/are-non-void-self-closing-tags-valid-in-html5

I found these with a fairly quick web search.  Otherwise, this question should have been asked on a QA forum, such as https://discuss.python.org/c/users/7 or stackoverflow.com.
