### ISSUE TITLE
Fix building CPython with -DWIN32_LEAN_AND_MEAN on Windows

### ISSUE THREAD

**Issue by georgthegreat** [python/cpython#115882]
# Feature or enhancement

### Proposal:

We use customized build of CPython which compiles all the sources with `-WIN32_LEAN_AND_MEAN`, thus limiting the amount of transitive `#include` from `Windows.h` header.

I would like to propose a series of enhancements to make CPython buildable in this configuration.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-115350

**Comment by georgthegreat** [comment]
@zooba, it looks like it was the only patch regarding WIN32_LEAN_AND_MEAN build.

As for your question, having this CFLAG defined allows to reduce negative impact of tranisitive Windows SDK headers which tend to define various keywords as a macros (see [protobuf solution](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/port_undef.inc#L114) for the case).

As we are using our own build system to compile both python sources and our own code, we have simply defined this CFLAG universally.

As for the guarantees from Microsoft — they do neither recommend nor discommend using this define (see [here](https://learn.microsoft.com/en-us/windows/win32/winprog/using-the-windows-headers#faster-builds-with-smaller-header-files)). Yet their documentation [explicitly recommends](https://learn.microsoft.com/en-us/windows/win32/api/unknwn/nn-unknwn-iunknown) including particular header instead of expecting `windows.h` to include it transitively.

**Comment by zooba** [comment]
> Yet their documentation [explicitly recommends](https://learn.microsoft.com/en-us/windows/win32/api/unknwn/nn-unknwn-iunknown) including particular header instead of expecting `windows.h`

To be clear, this is not an explicit recommendation, but an acknowledgement that this is the header file that contains the definition. In many such cases, an explicit recommendation is made to include `windows.h` instead of the one listed, but that appears to be at the discretion of the documentation author.

Avoiding certain macros being defined is a perfectly good reason though. If this is the only one you need, glad to have been able to help.
