### ISSUE TITLE
Documentation: PyDictKeysObjects layout diagram in the comments section of Objects/dictobjects.c file

### ISSUE THREAD

**Issue by Humbulani1234** [python/cpython#115941]
# Documentation

The `PyDictKeysObjects` layout diagram in the file `Objects/dictobjects.c` comments section, shown below:
```
layout:

+---------------------+
| dk_refcnt           |
| dk_log2_size        |
| dk_log2_index_bytes |
| dk_kind             |
| dk_usable           |
| dk_nentries         |
+---------------------+
| dk_indices[]        |
|                     |
+---------------------+
| dk_entries[]        |
|                     |
+---------------------+
```
seems not to correspond with the actual definition of `PyDictKeysObjects` which is a typedef of `_dictkeysobject`, where `_dictkeysobject` is located in the file ```Include/internal/pycore_dict.h```, and its structure is reproduced below:

```c
/* See dictobject.c for actual layout of DictKeysObject */
struct _dictkeysobject {
    Py_ssize_t dk_refcnt;

    /* Size of the hash table (dk_indices). It must be a power of 2. */
    uint8_t dk_log2_size;

    /* Size of the hash table (dk_indices) by bytes. */
    uint8_t dk_log2_index_bytes;

    /* Kind of keys */
    uint8_t dk_kind;

    /* Version number -- Reset to 0 by any modification to keys */
    uint32_t dk_version;

    /* Number of usable entries in dk_entries. */
    Py_ssize_t dk_usable;

    /* Number of used entries in dk_entries. */
    Py_ssize_t dk_nentries;

    /* Actual hash table of dk_size entries. It holds indices in dk_entries,
       or DKIX_EMPTY(-1) or DKIX_DUMMY(-2).

       Indices must be: 0 <= indice < USABLE_FRACTION(dk_size).

       The size in bytes of an indice depends on dk_size:

       - 1 byte if dk_size <= 0xff (char*)
       - 2 bytes if dk_size <= 0xffff (int16_t*)
       - 4 bytes if dk_size <= 0xffffffff (int32_t*)
       - 8 bytes otherwise (int64_t*)

       Dynamically sized, SIZEOF_VOID_P is minimum. */
    char dk_indices[];  /* char is required to avoid strict aliasing. */

    /* "PyDictKeyEntry or PyDictUnicodeEntry dk_entries[USABLE_FRACTION(DK_SIZE(dk))];" array follows:
       see the DK_ENTRIES() macro */
};
```

The struct ```_dictkeysobject``` has a ```dk_version``` field and it doesn't contain a ```dk_entries``` field, whereas the layout diagram in the code comments' section shows such fields. 

End.

### Linked PRs
* gh-116196

**Comment by carljm** [comment]
The inclusion of `dk_entries[]` in the doc block I think is correct, even if such a member is not named in the struct (because you can't have two variable-sized arrays in the same struct). In actual fact the memory layout of the `PyDictKeysObject` includes both the indices array and the dk_entries array, as clarified in the final comment in the `_dictkeysobject` struct definition.

The omission of `dk_version` does look like an oversight; a PR to add it in the doc block would be useful.

If someone makes a PR for this, I noticed another typo in that doc block that could be fixed at the same time: a few lines later it says "Values are stored in the me_value field of the PyDictKeysObject." This is wrong, it should say "Values are stored in the me_value field of the PyDictKeyEntry."

**Comment by Humbulani1234** [comment]
PR #116196 has been created and it aims to address the proposed changes.
