### ISSUE TITLE
pprint does not keep the order of dict keys

### ISSUE THREAD

**Issue by mattermat** [python/cpython#115985]
# Bug report

### Bug description:

As in the title:

```python
from pprint import pprint

a = {
    "a": [1, 2, 3],
    "b": [1, 2, 3],
    "c": [1, 2, 3],
}

b = {
    "b": [1, 2, 3],
    "c": [1, 2, 3],
    "a": [1, 2, 3],
}

pprint(a)
pprint(b)
```
gives the following:
```
{'a': [1, 2, 3], 'b': [1, 2, 3], 'c': [1, 2, 3]}
{'a': [1, 2, 3], 'b': [1, 2, 3], 'c': [1, 2, 3]}
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by kotnen** [comment]
This is the expected behaviour, and is not a bug.


From [the documentation](https://docs.python.org/3.13/library/pprint.html),

> If `sort_dicts` is true (the default), dictionaries will be formatted with their keys sorted, otherwise they will display in insertion order.

**Comment by AlexWaygood** [comment]
Thanks for the report! As @kotnen says, this is longstanding and intentional behaviour that we wouldn't be able to easily change without breaking backwards compatibility. However, I think there's a number of documentation improvements we could make here to call out the default behaviour of `pprint.pprint()` so that users are more aware of it. I've opened #115986 to track that.

**Comment by mattermat** [comment]
Hi @kotnen ,

I should have checked the documentation before opening the issue...
Given that dict keeps the order of the keys I didn't expect pprint not doing the same.

Thanks for you feedback!

**Comment by terryjreedy** [comment]
pprint predate ordered keys by at least a decade.  Sorting keys was then part of the expectation of 'pretty'.  It also enabled a *predictable* output string for doctests.
