### ISSUE TITLE
Add default behaviour to `pprint.pprint`

### ISSUE THREAD

**Issue by Privat33r-dev** [python/cpython#116041]
### Proposal:

[json.dumps](https://docs.python.org/3/library/json.html#json.dumps) contains `default` parameter which allows it to handle custom and unsupported internal objects. While `pprint` [module](https://docs.python.org/3/library/pprint.html)'s functions and objects are lacking this functionality. I suggest to add it so users can `pprint` even more diverse data. It might also reduce requests for different classes' support for `pprint` module.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by gaogaotiantian** [comment]
So for `json.dumps`, `default` is used when the object can't be serialized. When will the `default` argument for `pprint` work? Because all the objects can be printed. Also we already have `__str__` to customize the print of a specific object, what's the value added to the `default` argument? Is there an example where such usage is helpful?

**Comment by Privat33r-dev** [comment]
> So for `json.dumps`, `default` is used when the object can't be serialized. When will the `default` argument for `pprint` work? Because all the objects can be printed. Also we already have `__str__` to customize the print of a specific object, what's the value added to the `default` argument? Is there an example where such usage is helpful?

Thank you for pointing that out. By some reason I assumed that `pprint.pprint` follows the same behaviour as JSON, while in fact it attempts to stringify objects that it's unable to represent otherwise. `default` still might be useful in some cases like
```python
from pprint import pprint

class User(object):
    def __init__(self, name, occupation):
        self.name = name
        self.occupation = occupation

users_raw = [("Mr Bartlett", "court barrister"), ("Biggus Dickus", "Commander of a \"cwack legion\"")]
users = [User(name, occupation) for name, occupation in users_raw]
pprint(users, default=vars)
```

Frankly, that's a questionable feature after you pointed out that stringification is the default behavior of pprint.

**Comment by gaogaotiantian** [comment]
First of all, `pprint` is a print function - it prints stuff so yes it tries to stringify data. The difference between `pprint` and `print` is some special handlers for some known types (list, dict, etc.).

There is a critical matter to consider here, which I mentioned above and you did not respond: when do we start using `default`? All the objects have string representation, there will be no case when `pprint` failed to find one. How does `pprint` know that an arbitrary object, should use `default`, instead of their stringify method? Do we check it against `object.__str__`?

Is `default` applied to ALL objects? How would that work if we are printing a reasonably complicated data? Would it be feasible to pick one function to all types of data that we are printing? Is it easier for the users to just write a `__str__` method for the self-defined `User` class?

Overall I don't think the `default` argument helps in many real life cases, without considering the potential indentation issue. There are some library in the market that deals with arbitrary object printing though (https://github.com/gaogaotiantian/objprint for example). Not sure if `pprint` wants to march into that area.

**Comment by Privat33r-dev** [comment]
I think that it pretty much concludes the discussion. Default behavior was meant to be for the object that don't have __str__ method, but since it's uncommon need that is already covered by external library, the issue can be closed. Thank you for review.
