### ISSUE TITLE
Implement PEP 705 (TypedDict: Read-only items)

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#116127]
# Feature or enhancement

PEP-705 was just accepted. For the runtime implementation, we'll need:

- [ ] Add the new `ReadOnly` special form
- [ ] Adjust the implementation of `TypedDict`
- [ ] Update docs

The [typing-extensions implementation](https://github.com/python/typing_extensions/blob/main/src/typing_extensions.py) should provide a good baseline.

cc @alicederyn

### Linked PRs
* gh-116350

**Comment by sobolevn** [comment]
Is someone working on this already? :)
Or can I take this over?

**Comment by JelleZijlstra** [comment]
I am not working on it, feel free to take it. Thanks!

**Comment by sobolevn** [comment]
Basically, the implementation exists here: https://github.com/python/typing_extensions/commit/0b0166d649cebcb48e7e208ae5da36cfab5965fe

I just need to port it.

**Comment by JelleZijlstra** [comment]
@sobolevn any progress here? The beta freeze is approaching.

**Comment by JelleZijlstra** [comment]
Wait, it was done. Thank you!

**Comment by donbarbos** [comment]
Don’t you think that a runtime error shouldn’t occur if mutable key overrides a read-only one in a base class? Like in typing_extensions (python/typing_extensions/pull/333) implementation as mentioned [here](https://discuss.python.org/t/pep-705-read-only-typeddict-items/37867/10)

Maybe it was just missed because it was changed in another commit:
> Basically, the implementation exists here: python/typing_extensions@0b0166d

Actually I noticed this discrepancy while trying to run `test_typing`, importing `typing_extensions` instead of `typing`.

**Comment by JelleZijlstra** [comment]
At this point making this an error would be a backwards incompatibility in CPython. In general I prefer to avoid raising runtime errors in the typing implementation; they reduce flexibility for future changes or nonstandard usage of the module.

**Comment by alicederyn** [comment]
I think it would be best to open a new issue, with a reproduction, what version of Python you're using, what you see, and what you would expect to see. I don't fully understand what you're describing, unfortunately.
