### ISSUE TITLE
PCbuild\build.bat does not complete its work

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [python/cpython#116123]
# Bug report

### Bug description:

PCbuild\build.bat does not complete its work, which prevents its use (call) from a bat script. Subsequent actions wait for PCbuild\build.bat to complete, but this does not happen even when it says that the build completed successfully.

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by zooba** [comment]
I'm afraid there's not enough information to go on here. Are you able to share build logs? Can you tell what step it was trying to execute?

Also, have you tried restarting your computer? It's occasionally possible that MSVC stops being able to launch new processes, or simply hangs, and it tends to be due to extra processing hanging around when they should've closed. Rebooting ensures that they've gone away (you could also find and kill them, but they aren't always obvious).

**Comment by terryjreedy** [comment]
I have had no issue running pcbuild/build.bat from my own .bat for a decade, though I have not do so with 3.10 since it went to security status.

**Comment by Yrij-Zhavoronkov** [comment]
I just delete /b for exit. It work for me
