### ISSUE TITLE
Add a `operator.repeat` function 

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#116374]
# Feature or enhancement

### Proposal:

There's already an `operator.concat` for sequences, but there's no `operator.repeat` which could be useful for sequences.
Is there a good reason why this hasn't been implemented yet?

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by AlexWaygood** [comment]
Would this work like https://docs.python.org/3/library/itertools.html#itertools.repeat, like https://docs.python.org/3/library/itertools.html#itertools.cycle, or like something else?

**Comment by Eclips4** [comment]
> Would this work like https://docs.python.org/3/library/itertools.html#itertools.repeat, like https://docs.python.org/3/library/itertools.html#itertools.cycle, or like something else?

No, it would work like shorthand for that 
```
[1, 2, 3] * 3
> [1, 2, 3, 1, 2, 3, 1, 2, 3]

# Example:
operator.repeat([1, 2, 3], 3)
>[1, 2, 3, 1, 2, 3, 1, 2, 3]
```

**Comment by terryjreedy** [comment]
I guesss that it should implement n * [...].  The difference between operator.add and operator.concat is that the latter checks for a.__getitem__ first before doing a+b.  Operator.repeat should have the same check.

**Comment by terryjreedy** [comment]
Because of the restriction, operator.concat does not correspond to an actual operator, but without the restriction, it would be a pure duplicate.  I think operator.repeat should have been added at the same time as operator.add, or neither should exist.  Since I will not propose deletion of concat, I am inclined to support addition of repeat.  But I would look for the issue/pr that added concat to see if there were an explicit and plausible reason for omitting repeat.

There are also iconcat and __concat__ and __iconcat__.

**Comment by pochmann3** [comment]
> The difference between operator.add and operator.concat is that the latter checks for a.**getitem** first before doing a+b.

Are you talking about the Python version? That's not usually used, is it? And if I remember correctly, the C version is slightly faster than `add`, at least for builtin sequence types, due to using `PySequence_Concat` instead of `PyNumber_Add`.

**Comment by sobolevn** [comment]
Do you mean like this?

```python
>>> import operator
>>> operator.mul([1, 2], 2)
[1, 2, 1, 2]
```

**Comment by rhettinger** [comment]
I think the existing `operator.mul` will more than suffice.  No need to create an alias where the meaning isn't self-evident (as indicated by the above discussion).

**Comment by pochmann3** [comment]
> if I remember correctly, the C version of `concat` is slightly faster than `add`'s,

Little benchmark, reducing a million empty lists (like `reduce(concat, repeat([], 10**6))`):

```
 30.8 ± 0.1 ms  iconcat
 34.7 ± 0.2 ms  iadd
 37.6 ± 0.1 ms  concat
 39.7 ± 0.2 ms  add
```

And a million tuples:

```
 20.8 ± 0.1 ms  concat
 21.5 ± 0.2 ms  iconcat
 23.1 ± 0.1 ms  add
 25.2 ± 0.3 ms  iadd
```

<details><summary>Script</summary>

Python version used:
```
3.12.0 (main, Oct  7 2023, 10:42:35) [GCC 13.2.1 20230801]
```

```python
from timeit import timeit
from statistics import mean, stdev
import sys
import random
from operator import add, concat, iadd, iconcat
from functools import reduce
from itertools import repeat

funcs = [add, concat, iadd, iconcat]

times = {f: [] for f in funcs}
def stats(f):
    ts = [t * 1e3 for t in sorted(times[f])[:10]]
    return f' {mean(ts):4.1f} ± {stdev(ts):3.1f} ms '
for _ in range(100):
    random.shuffle(funcs)
    for f in funcs:
        t = timeit(lambda: reduce(f, repeat([], 10**6)), number=1) / 1
        times[f].append(t)
for f in sorted(funcs, key=stats):
    print(stats(f), f.__name__)

print('\nPython:', sys.version)
```

[Attempt This Online!](https://ato.pxeger.com/run?1=dVJBjtQwEJQ4-hV9G3tkwkSLEIo0f-AeosibtFmLsR3ZnZVGoz3yCi57gTtf4Bm8Bsd2FoFETu6u7urqSn_9vlzpwbvn528r6dfvf736ooO3QMaiITB28YFqxDISSZGJZKa4oxaVkyk_4yOrqXiN-zMoN3tbev2CQZEPe6eaZwmTd5MiCSZHpoSlXq9uIu8vL6MCzuuEBTSE4R9wwdTJtq4IZ-j_Tz8wtu20Vd10B_0AOqnSYFyeGZ_YjDqvGrkWHYP0UeYkOEKLd7metvqYRuPMM12vB9F37WkYckdAWkNiPMBt84hTFN3bptVP8PMH3LJhOXeXczbCgW2040abbPuEvD2d6vRiYxMfVq0vyLNKkZG_lZfqrDfJLT-OX5S9n1VX7eNaVq94P0hoT8fjOyEkuNXeYzi3At5A-4emLtaoZUGXFhXsZWLdPQ-W8Bmv52xZlbwE44jvJkrQzTg6ZXEcBWMFPHx0H_L9dQe5HU3ziCEa70S5xnqU-3H-Bg)

</details>

**Comment by terryjreedy** [comment]
pochmann3> Are you talking about the Python version?

I would expect the C and Python versions to act the same.

Me>  (Any) plausible reason for omitting repeat.

1. There is a PySequence_Concat, but I suspect that there is no 'PySequence_Repeat' and hence not the same reason to expect exposure (of what does not exist).
2. Confusion about the meaning, and the rest of Raymond's comment.
I now think this could be closed.

**Comment by Eclips4** [comment]
> pochmann3> Are you talking about the Python version?
> 
> I would expect the C and Python versions to act the same.
> 
> Me> (Any) plausible reason for omitting repeat.
> 
> 1. There is a PySequence_Concat, but I suspect that there is no 'PySequence_Repeat' and hence not the same reason to expect exposure (of what does not exist).

PySequence_Repeat is a part of public C API.

**Comment by serhiy-storchaka** [comment]
It was removed in Python 3.1 (89e12963ad7f0551b325b282267ad21011aa5fd7).

cc @rhettinger

**Comment by Eclips4** [comment]
At the moment for me it's not clear why `operator.repeat` has been removed, but `operator.concat` remains

**Comment by pochmann3** [comment]
No mention of `concat` in the [thread](https://mail.python.org/archives/list/python-dev@python.org/thread/72ZZ2GTBJZAHSQLJ6G6ZFCQMO3UHFKHY/) removing `repeat`.

**Comment by rhettinger** [comment]
I recommend that this feature request be rejected. It seems to be solely motivated by a weak symmetry argument (you have thing A so you must also have thing B) rather than a real world use case or need that can't easily be met with existing tools.

The `repeat` function was removed about about 15 years ago. No one complained and no one has requested it since. That is strong evidence that this isn't needed.

Keep in mind that`repeat` specialized for sequences is only a very slight optimization of `mul` which is the well known and obvious way to do it because it matches the `string * integer` example shown in the tutorial section 3.1.2.

Unlike `concat` which is unambiguous, the name `repeat` isn't obvious. Alex Waygood's post above provides evidence that this is easily misinterpreted.  Also, it doesn't fit in well with the known use cases for the `operator` module which mainly seems to be used with functional programming tools like `map()`.

When `repeat` was removed because of its weak foundations, `concat` was looked at as well.  The latter was left in because a code search revealed that it was actually being used and it wasn't worth breaking existing code.

In general, almost everything built on top of `PySequence_Check()` is skating on thin ice.  Even `concat` can be considered broken because it is supposed to reject non-sequences, but it cannot:

```
>>> import collections
>>> import operator

>>> class CMA(collections.ChainMap):
...     def __add__(self, other):
...         return self | other
...    
>>> operator.concat(CMA({'a': 1}), CMA({'b': 2}))
CMA({'a': 1, 'b': 2})

>>> class Bits(int):
...     def __getitem__(self, i):
...         return (self >> i) & 1
...    
>>> operator.concat(Bits(5), Bits(13))
18
```

**Comment by terryjreedy** [comment]
To be clear, after reading Raymond's extended explanation I agree with his conclusion that we should close and leave as is.

**Comment by Eclips4** [comment]
Thanks Raymond for an explanation!
I'm going to close this.

**Comment by JelleZijlstra** [comment]
Interesting, I always thought that the difference between `operator.concat` and `operator.add` was about whether the `nb_add` or the `sq_concat` slot was being used, but looking at the code it's more complicated: `operator.add` always checks both slots but tries `nb_add` first, and `operator.concat` checks `sq_concat` first, but also checks `nb_add` if the argument is a sequence, where "is a sequence" approximately means "has `__getitem__` but is not a dict".

In any case, I agree with the outcome in this issue. The fact that some dunders map to multiple slots in C is an ugly implementation detail that we should try to hide, not expose in the `operator` module.
