### ISSUE TITLE
logging.LogRecord.__repr__ contains not inerpolated message

### ISSUE THREAD

**Issue by gortibaldik** [python/cpython#116412]
# Bug report

### Bug description:

When testing log messages with `pytest` and `caplog` fixture, the `LogRecord.__repr__` is misleading.

```python
import logging

def test_logging(caplog):
   with caplog.at_level(logging.INFO):
       logging.info("Message (%s)", "interpolated")
   for record in caplog.records:
       print(record)
```

When I run pytest with capture of output: `pytest tests/ -s`

I see the following record:

```txt
<LogRecord: root, 20, <path>, <line_number>, "Message (%s)">
```

I think this record is misleading, as "Message (%s)" isn't the captured message. If I instead print `record.message`, I get the expected "Message (interpolated)".

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by serhiy-storchaka** [comment]
It looks rather as expected behavior to me. It helps you to identify what source line produced the record. If there are some problems with interpolating, it help you by showing an original format string. repr() usually includes the most important parts of the object's state. `message` is derived from `msg`.

If you want to see the interpolated message, just use the `message` attribute.
