### ISSUE TITLE
Confusing behaviour when using os.walk()

### ISSUE THREAD

**Issue by the-Chain-Warden-thresh** [python/cpython#116605]
# Bug report

### Bug description:

I write a Python program to get all of the folders under a specfic directory, except for those that start with `.`, such as `.git` and its subdirectory, as follows.
```python
def get_dirs(scan_dir):
    dir_list=[]
    dir_list.append(scan_dir)
    for root, dirs, files in os.walk(scan_dir):
        for dir1 in dirs:
            if dir1.startswith("."):
                dirs.remove(dir1)
                continue
            write_dir=os.path.join(root, dir1).replace('\\', '/')
            dir_list.append(write_dir)
    print(dir_list)
```
Something strange happens when `scan_dir` contains a folder named `engines`. It **will not** be added into `dir_list`. I think this might have some connection with the code that remove an element of a list while traversing it, i.e. `dirs.remove(dir1)` .
However, when the directory structure is as follows:
test
├─.git
├─a
└─xml
the output is `['test', 'test/xml', 'test/a']`

Meanwhile, when the directory structure is as follows:
test
├─.git
├─a
├─engines
└─xml
the output is still `['test', 'test/xml', 'test/a']`
If I change the name `engines` to `en`, the output will be `['test', 'test/xml', 'test/a', 'test/en']`
I'm confused and wonder whether this is a bug, or just because I don't have enough knowledge about Python.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by zware** [comment]
This is in fact a symptom of mutating the list that you're iterating.  I believe the difference you're seeing is due to the order of `dirs` returned by the `listdir()` (or equivalent) call within `os.walk()`; if you do a `dirs.sort()` before iterating, I think you'll see consistent (incorrect :)) behavior.

You have a few options to avoid the issue; the simplest is to copy `dirs` before iterating it by using `for dir1 in dirs[:]:` or `for dir1 in dirs.copy():`.

**Comment by terryjreedy** [comment]
I am pretty sure that there is  FAQ about mutating lists while iterating with solutions.
