### ISSUE TITLE
Regression in `urllib.parse.parse_qsl(None)` behavior

### ISSUE THREAD

**Issue by msullivan** [python/cpython#116764]
# Bug report

### Bug description:

https://github.com/python/cpython/pull/115771 introduced a change in some currently working behavior. Previously:
```python
import urllib.parse
>>> urllib.parse.parse_qsl(None)
[]
```
but now it raises `TypeError: cannot convert 'NoneType' object to bytes`.

(`parse_qs` also broke, since it calls `parse_qsl`)

I think it's obviously pretty debatable whether the old behavior was desirable but there *is* popular code in the wild that depends on it: https://github.com/encode/httpx/blob/7df47ce4d93a06f2c3310cd692b4c2336d7663ba/httpx/_urls.py#L431-L433. 

(I stumbled across this when one of my colleagues was accidentally using a current dev branch of 3.11 and started getting mysterious errors from inside the bowels of the httpx client.)

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-116801
* gh-116894
* gh-116895

**Comment by msullivan** [comment]
@serhiy-storchaka If there's agreement that the old behavior when passing `None` should be preserved, I can submit a patch.

**Comment by serhiy-storchaka** [comment]
Thank you for your report @msullivan. This looks as a serious reason to restore support of false values, even if it was not intentional behavior.

I already started to write a PR when I requested for creating this issue. The fix was trivial, but there was substantial lack of tests, and new tests exposed other flaws in this code, so the final code is more complicated.

**Comment by serhiy-storchaka** [comment]
Opened #116897 for deprecating support of generic false values.
