### ISSUE TITLE
`collections.deque` freelist blocks could be chained together

### ISSUE THREAD

**Issue by masklinn** [python/cpython#117098]
# Feature or enhancement

### Proposal:

Convert `freeblocks` to a single pointer, and chain the free blocks through the `rightlink` (or the `leftlink` for small-endian).

### Justification:

When the deque freelist was moved from global to per-instance, the freelist array was simply moved into the structure, adding `MAXFREEBLOCKS = 16` pointers (128 bytes) to the static overhead of the struct, bringing it from 104 bytes to 232 bytes.

But the blocks can be chained directly, so the freelist could be a linked list of blocks, reducing `freeblocks` to a single pointer and saving 120 bytes.

In the grand scheme of things this is not huge savings especially as deque preallocates a block (528 bytes) on creation, but it's still 15% less overhead on deques up to 64 elements.

As an aside, and probably pretty minor, as far as I can tell `deque_dealloc ` calls `deque_clear` which calls `freeblock`, this should shift up to `MAXFREEBLOCKS` into the freelist (freeing the rest), then actually free those during the second pass.

Couldn't `deque_dealloc` set `numfreeblocks` to `MAXFREEBLOCKS` to ensure all live blocks are freed immediately, to avoid the extra work of shifting them to the freelist?

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by rhettinger** [comment]
When this was designed, extensive efforts were made to compare the various ways to implement the freelist. The current approach was fastest, the generated assembly gave the best cache utilization and fewest unpredictable branches.  I look at this again when I get a chance but right now my strong preference is to leave this as-is.  The overall design strategy for the deque has consistently opted to pay for small speed gains with memory when needed.  This matches the typical use cases for deques where we have few instances but potentially many elements.

FYI this isn't a feature request because it has no user visible API impact. Instead, I've marked it with the performance label because it just revisits implementation choices and speed/space trade-offs.

**Comment by rhettinger** [comment]
After more thought and investigation, I would like to decline this suggestion.  The current choice was made on purpose with full knowledge of the speed/space trade-off.  Even if that balance has changed a bit, I don't see any possible user benefit worth churning the code and my having to spend a lot of effort again to running timings on different hardware and different compilers to prove or disprove the performance effect.

If you feel strongly about this, we can discuss it more.  Otherwise, we can wait for other more substantive issues.
