### ISSUE TITLE
Problems about importing libraries.

### ISSUE THREAD

**Issue by ChenDOS** [python/cpython#117188]
# Bug report

### Bug description:

I found an interesting bug where when a program import itself, it doesn't report an error and executes normally, even though vscode does give an error message
![bug](https://github.com/python/cpython/assets/123917956/3eb98bb4-4bf6-492f-ab8e-c9ca1a72f509)

### CPython versions tested on:

3.9

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
Why do you think that this is a bug, meaning, do the docs prohibit this?  If so, where?  Python allows many crazy things.

**Comment by ronaldoussoren** [comment]
There is no bug here, when you run the script there are effectively two modules using the same source:

1.  "python3 ccc.py" runs the code in "ccc.py" in the ``__main__`` module
2. "import ccc" creates the "ccc" module from the same file

In general it is better to avoid this pattern because this can be fairly confusing, especially when defining classes in such modules.
