### ISSUE TITLE
csv.reader ignoring quotechar

### ISSUE THREAD

**Issue by bmarcote** [python/cpython#117286]
# Bug report

### Bug description:

Given the following content inside a `afile.csv` file:

```
email1, name1, country1
email2, name2, country2
email3, name3, "country, 3"
email4, name4, country4
```

And called as:
```python
import csv
reader = csv.reader('afile.csv', delimiter=',', quotechar='"')
for row in reader:
    email, name, country = reader
```
I expected that the previous code would consider the quotes for "country, 3" (as provided in `quotechar`) and thus including such string as a single element in the outputting object. Therefore, I would expect:
```python
> print(reader)
['email3', 'name3', 'country, 3']
```

However, the resulting `reader` is:
```python
['email3', 'name3', '"country', '3"']
```

From what it is understood from the documentation, this should not be the case.

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by ericvsmith** [comment]
Your example code does not run as-is. Among other things, `csv.reader` takes an iterable of strings. Please correct the code and I'll take a look at it.

**Comment by ericvsmith** [comment]
Your example prints `<_csv.reader object at 0x0000018EF723CC40>`. While it would be easy to fix this, unfortunately I've run out of time to look at it. Sorry, and good luck.

**Comment by brianschubert** [comment]
This is the expected behavior for the default CSV dialect. Spaces are considered to part of the field and are not ignored.

You can set [`Dialect.skipinitialspace`](https://docs.python.org/3/library/csv.html#csv.Dialect.skipinitialspace) to `True` to change this behavior.

In the future, it's a good idea to ask about potential bugs on https://discuss.python.org/c/users/7 before opening an issue

**Comment by bmarcote** [comment]
Oh thank you. I thought this was the best place to put it. Apologies and I will do it properly next time.
