### ISSUE TITLE
Handle leading `//` for `posixpath.commonpath`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117201]
# Bug report

### Bug description:

```python
>>> import posixpath
>>> posixpath.commonpath(["//foo/bar", "//foo/baz"])
'/foo'
```

Expected: `//foo` with precisely two leading slashes, see: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_13

This can be quite easily solved using `posixpath.splitroot`, see the PR.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-117202
* gh-117334

**Comment by OscarSong2003** [comment]
Can I look into this issue potentially?

**Comment by serhiy-storchaka** [comment]
For reference, the original issue that introduced `commonpath()` is bpo-10395/gh-54604.
And its behavior was discussed at https://mail.python.org/archives/list/python-ideas@python.org/thread/VHQTSU4ERTH262OPVZ6SEO2EYCFQF56G/.

**Comment by erlend-aasland** [comment]
If anything, this looks to me like a `commonpath` documentation issue.

**Comment by nineteendo** [comment]
> If anything, this looks to me like a `commonpath` documentation issue.

If that's the case, that's fine by me, but that should be confirmed by @ronaldoussoren.

> Moreover, if I were to write such a test, I would normalise `tail1` before comparing it

The thing is: the paths are already normalised here, but that won't eliminate a leading `//` as intended.

**Comment by erlend-aasland** [comment]
> The thing is: the paths are already normalised here, but that won't eliminate a leading `//` as intended.

`splitdrive` does not normalise the paths, if that is what you imply.

**Comment by nineteendo** [comment]
No, the paths I'm passing to `splitdrive()` are already normalised (I added `abspath()` to make that clearer), but I would still need to apply `commonpath()` to the tail to make the comparison work. I shouldn't have to do that.

**Comment by erlend-aasland** [comment]
Well, it is still a backwards-incompatible change.

**Comment by nineteendo** [comment]
Anyway, whether this will be accepted depends on whether this is intentional behaviour or not:

- If it's intentional, we should document and test this.
- If it isn't, we should document the new behaviour like how [`os.path.isabs()`](https://docs.python.org/3.13/library/os.path.html#os.path.isabs) was changed to handle paths correctly starting with exactly one (back)slash on Windows.

**Comment by ronaldoussoren** [comment]
IMHO we should consider dropping special handling for '//' at the start of a path for our path manipulation APIs.  I cannot recall a Unix where '//foo' is different from '/foo', but it is an awfully long time that I've used anything other than Linux and macOS.

The Open Group documents that '//foo' may be special ("may be treated in an implementation defined way"), but AFAIK commonly used UNIX-y systems don't use this possibility. 

Because most systems don't treat '//foo' specially we shouldn't change the behaviour of `os.path.commonpath` as this will only lead to confusing users and might have a security impact for code that expects the current behaviour.

**Comment by ronaldoussoren** [comment]
To reply to myself: https://unix.stackexchange.com/questions/256497/on-what-systems-is-foo-bar-different-from-foo-bar

Appearently Cygwin uses '//share/path' to access UNC shares, as does UWIN. And finally zOS uses '//path' for something implementation defined as well.   The page also lists some no longer supported systems which used '//host/path' for networked file systems.

This complicates things...

**Comment by nineteendo** [comment]
Can we rediscuss the behaviour of `commonpath(['//foo', '/foo'])` then? As these paths would have a different meaning.
I would prefer to return the empty string in this case.

**Comment by ronaldoussoren** [comment]
As I wrote, it's complicated.   My gut feeling is that we shouldn't change the behaviour for all platforms because of most platforms the two paths do no have a different meaning.

The platforms with special treatment for double slashes at the start of a path are not on our list of supported platforms, and are not tested in CI. As such we generally don't complicate the code base for them, although Cygwin used to be somewhat popular (but I haven't used Windows or Cygwin in a long time).

Because of this I'm still of the opinion what we should consider dropping specific support for double slashes at the start of paths in `os.path`.  That's something that needs discussion outside of this issue though, and that might lead to keeping support for this on a specific list of platforms such as Cygwin.

**Comment by nineteendo** [comment]
OK, then I'll close this issue for the time being. Could you start a discussion about this?

**Comment by ronaldoussoren** [comment]
> How '//share/path/../../file' is resolved on Cygwin? Is it equal to `/file` or `//share/file`? The same question is for other platforms.

I have no idea.  On any platform where "//path/subpath" is special the behaviour is implementation defined, and hence not something we can implement generically in CPython.

> 
> Perhaps such platforms should have a separate `os.path` and `pathlib.Path` implementations. And have more complete support of `normpath()`, `split()`, `splitroot()`, `commonpath()` etc if `//share` is considered a different root.

Probably.  That's one more reason to just drop the limited support for this in the stdlib and reconsider when someone proposes to add support for such a platform to CPython.  On first glance the only support we have is that `normpath`  doesn't remove the extraneous slash when there are exactly 2 slashes at the start of the path (introduced in bf222c9f12c1078a5d41acf4f4ce77c1a976c67f).   Other path manipulation functions don't check for there double slashes at all.

**Comment by nineteendo** [comment]
> Other path manipulation functions don't check for there double slashes at all.

`posixpath.splitroot()`:

https://github.com/python/cpython/blob/4d4a6f1b6aea6dae131ac116f1735a38c3e32cd1/Lib/posixpath.py#L162-L164

The only function that doesn't handle it properly is `posixpath.commonpath()` (`posixpath.realpath()` works as intended: #117338).

**Comment by calestyo** [comment]
Just for the records:

> I have no idea. On any platform where "//path/subpath" is special the behaviour is implementation defined, and hence not something we can implement generically in CPython.

Is that really the case? POSIX probably (see my remarks in https://github.com/python/cpython/issues/138139#issue-3352125441) **does** define well how such pathnames are e.g. normalised, because it says only the first component is implementation defined.

At least to the point where Python just passes such pathnames on to some syscall or so, things should probably work, as then the OS would take care again of any interpretation of the first component.

The only thing which Python in fact cannot really do generically, would be when e.g. comparing/joining/etc. two such special pathnames (i.e. any pathname operations).<br>
Cause e.g. in some implementation `//foo/bar` could be considered identical to `//FOO/bar` where in others not.
