### ISSUE TITLE
Reduce syscalls for `posixpath.ismount`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117394]
# Feature or enhancement

### Proposal:

Currently `posixpath.ismount` uses `realpath(join(path, '..'))` to get the parent of the mount. This is absolutely overkill and should only be used when `join(path, '..')` isn't sufficient.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

- #117350

### Linked PRs
* gh-117395
* gh-117447

**Comment by barneygale** [comment]
Related to #96328

**Comment by serhiy-storchaka** [comment]
`abspath` is broken by design.

Let `/mnt/storage/link` be a link to `/mnt`, `/mnt/storage` is a mount point, and the original path is `/mnt/storage/link/../mnt/storage`. `abspath()` will return `/mnt/storage/mnt/storage`. `dirname()` will then return `/mnt/storage/mnt` which is on the same device as the original path, therefore `ismount()` will return False. But the real path is `/mnt/storage`, and it is a mount point.

**Comment by nineteendo** [comment]
Are you sure? `ntpath.realpath()` doesn't handle symlinks that way:

```python
>>> import ntpath
>>> ntpath.realpath(r"C:\Users\wanne\path-picker\link")
'C:\\Users\\wanne'
>>> ntpath.realpath(r"C:\Users\wanne\path-picker\link\..")
'C:\\Users\\wanne\\path-picker'
```

Does that work the same on Linux?

**Comment by barneygale** [comment]
It works differently on Linux - `..` entries point to the real parent of a directory.

**Comment by serhiy-storchaka** [comment]
#117447 is an alternate PR which achieves the same or better speed up.
