### ISSUE TITLE
Speed up `os.path`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117349]
# Feature or enhancement

### Proposal:

There are some minor optimisations possible in `os.path`, including some fast returns.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

- #117202

### Linked PRs
* gh-117350
* gh-117610

**Comment by nineteendo** [comment]
@barneygale, can you reopen this?

**Comment by AlexWaygood** [comment]
> If the same optimisation can be applied to several functions, can I make a single issue?

I think that would be fine. But I'd make sure to limit any PR so that it only changes functions where that optimisation actually makes a difference :-)

> Does that include further optimisations to the modified functions, besides the proposed one? Or do I need to make a separate issue?

It's hard to say in general. Sometimes we have one issues to track multiple changes to a function or an area of code. Sometimes we're more atomic, and have a different issue to track each specific change. But whatever the case, it's important to have each issue clearly define the work you're proposing to do, and why you think it will be beneficial for users of CPython. If you want to optimise `os.path`, then you need to clearly state which optimisations you're planning in the issue before filing a PR. If you later see the potential for followup PRs with different optimisations, then yes, it would probably be best to open a new issue detailing the new optimisation, rather than reusing the old issue.
