### ISSUE TITLE
`test_ssl.test_wrong_cert_tls13` should accept "Broken pipe" as valid error

### ISSUE THREAD

**Issue by colesbury** [python/cpython#117483]
The `test_wrong_cert_tls13` unit tests checks the behavior when the server rejects the client's ceritficate. On macOS, this can sometimes lead to a "Broken pipe" on the client instead of a "Connection reset by peer" when the connection is closed during the `s.write()` call.

This happens frequently in the free-threaded build, but can also be reproduced on the default (with GIL) build by adding a short `time.sleep(0.1)` immediately before the `s.write(b'data')`.

https://github.com/python/cpython/blob/8eda146e87d5531c9d2bc62fd1fea3bd3163f9b1/Lib/test/test_ssl.py#L3153-L3178

### Linked PRs
* gh-117484

**Comment by erlend-aasland** [comment]
Interesting. Could it be related to #26893?

**Comment by encukou** [comment]
IMO it's related to #115628. And the fact that SSL tests are too strict about the exact wording of the messages.

I checked that adding the `time.sleep(0.1)` doesn't break tests on 3.12, so it looks like a backport isn't needed.

**Comment by keepworking** [comment]
@encukou I am agreed with your opinion
Before the error was handled with `assertRaisesRegex`, it was being processed collectively as `except OSError as e:`.
You can refer to #26520.
As the types of errors that can occur again since #115628 are increasing, it may be necessary to consider a method of collectively dealing with `except OSError as e:`.
Or, I think it is necessary to investigate what is possible about OSError that may occur in that situation.
I'll look into it over the weekend.
