### ISSUE TITLE
Handle not executable directories for `os.listdir`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117402]
# Bug report

### Bug description:

I have a directory with "rw-" permisions with a file `inaccessible.txt`:

```python
>>> import os
>>> os.listdir("directory")
['inaccessible.txt']
>>> os.path.exists("directory/inaccessible.txt")
False
```

That's inconsistent behaviour: `os.listdir` says `directory/inaccessible.txt` exists, while `os.path.exists` says it does not.
This can be solved simply be raising a `PermissionError` (or a subclass) for `os.listdir` when the directory is not executable.
I can't think of any situation outside of a CTF where it would be useful to be able to list the files in such directories.

_Note that this is different from a directory with "-wx" permisions with a file `secret.txt`:_

```python
>>> import os
>>> os.listdir("directory")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 13] Permission denied: 'directory'
>>> os.path.exists("directory/secret.txt")
True
```

_In this case, files can still be accessed if you know the filename._

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by nineteendo** [comment]
@eryksun, what do you think?

**Comment by nineteendo** [comment]
@terryjreedy, this is technically not related to `pathlib`. Though it would change the behaviour of `pathlib.Path.iterdir()`.

**Comment by barneygale** [comment]
`os.stat()` and `os.listdir()` propagate errors from your operating system rather than raising `OSError` artificially or suppressing it. This is not a bug, and you'll need to gather support on the [ideas forum](https://discuss.python.org/c/ideas/6) first if you want to change it.

**Comment by nineteendo** [comment]
https://discuss.python.org/t/handle-not-executable-directories-for-os-listdir/49978

**Comment by eryksun** [comment]
It's expected on POSIX that read and search (execute) access are independent. Python should not, for example, call `access()` or `faccessat()` on a directory in order to pretend that `os.listdir()` failed if the caller lacks search access.

On Windows it's mostly a non-issue because users are almost always granted default-enabled "SeChangeNotifyPrivilege". When this privileged is enabled, a filesystem must bypass checking permissions when traversing directories. It only checks the permissions of the opened file or directory. Even without this privilege, `os.stat()` on Windows falls back on getting stat information from the directory listing. WinAPI `FindFirstFileW()` is able to return data for a specific file, including the normalized name, file attributes, reparse tag (i.e. the file type if it's a reparse point, such as a symlink or mountpoint), file size, and time stamps (creation/birth, modify, access).

**Comment by nineteendo** [comment]
I'm actually getting a permission error on macOS after listing the files with `ls`:

```none
ls 666
secret		secret.txt
ls: fts_read: Permission denied
```

But it's possible that listdir doesn't use "fts_read".
