### ISSUE TITLE
Add null pointer judgement

### ISSUE THREAD

**Issue by xk2013** [python/cpython#117563]
# Feature or enhancement

### Proposal:

I add null pointer judgement for Python.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-117564
* gh-117575

**Comment by serhiy-storchaka** [comment]
What problem are you trying to solve? Could you provide a sample Python code to demonstrate the issue?

**Comment by gaogaotiantian** [comment]
They added a NULL check for getters and setters for function object. I don't believe that's necessary because getters and setters have a guarantee that the object is not NULL. Otherwise we need to change a lot of code.

They might be new to open source contribution or this might be a result from a linter. Project wise, the change is not necessary and I think we should probably close it.

**Comment by serhiy-storchaka** [comment]
I had the same impression. Either the author is very inexperienced and does not know what they is doing (their code was not event compile), or it was all AI-generated.
