### ISSUE TITLE
Cancel built tests on first failure

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117580]
# Feature or enhancement

### Proposal:

Currently, when one built test fails, the others keep running, which is a waste of cpu time.
Would it be possible to cancel the other built tests in this case? A PR cannot then be merged anyway.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by AlexWaygood** [comment]
In general, it's very useful to be able to see exactly which platforms a test is failing on. For PRs that make changes to C code in particular, this can help a great deal in figuring out what the problem might be. If all tests are cancelled on all platforms as soon as they fail on one platform, it's much harder to do this.

**Comment by AlexWaygood** [comment]
That's just going to waste time, though: now I have to file the PR, wait until all the jobs start getting cancelled, then ping bedevere for a full re-rerun. Usually I know that the tests pass on at least one operating system, because I [run the tests locally beforehand](https://devguide.python.org/testing/run-write-tests/), so if they start failing in CI for some unexpected reason, usually the _only_ thing I'm interested in is exactly which platforms the tests are failing on

**Comment by nineteendo** [comment]
OK, if you think it's going to waste time, we should leave it as it is.
