### ISSUE TITLE
Automate positional arguments in clinic code

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117868]
# Feature or enhancement

### Problem:

It looks like we often forget to mark arguments as **positional only** in clinic input:

https://github.com/python/cpython/blob/8fc953f606cae5545a4d766dc3031316646b014a/Modules/posixmodule.c#L5470-L5476

This causes **a lot** of overhead with no practical benefit (this function is even private):

https://github.com/python/cpython/blob/8fc953f606cae5545a4d766dc3031316646b014a/Modules/clinic/posixmodule.c.h#L2257-L2304

If we wrote this instead:

```c
/*[clinic input]
os._path_normpath

    path: object
    /

Basic path normalization.
[clinic start generated code]*/
```

The overhead is gone:

```h
#define OS__PATH_NORMPATH_METHODDEF    \
    {"_path_normpath", (PyCFunction)os__path_normpath, METH_O, os__path_normpath__doc__},
```

*No, I didn't forget to include the rest of the code, **this is all the code!***

### Proposal:

Instead of **manually** updating all clinic input, we should modify `clinic.py` to do this **automatically** for functions **without keyword arguments**. If the old behaviour is desired, you should **explicitly** tell `clinic.py` that you want to support keyword arguments at the cost of performance:

```c
/*[clinic input]
os._path_normpath

    /
    path: object

Basic path normalization.
[clinic start generated code]*/
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by nineteendo** [comment]
@erlend-aasland, @eendebakpt

**Comment by nineteendo** [comment]
You should probably add performance too. :)

**Comment by AlexWaygood** [comment]
> Alex, you should probably also add the performance label, as this could greatly improve CPython's performance. :)

Unfortunately I don't think we'd see any immediate performance gains, as we'd have to undergo a deprecation period of at least two release cycles before making any parameters that are currently positional-or-keyword positional-only :/

**Comment by nineteendo** [comment]
Damn that's really unfortunate. ;( Could we do this deprecation as soon as possible with a list of all affected functions?

**Comment by erlend-aasland** [comment]
This would break a lot of code. I don't think this is a good idea.

**Comment by nineteendo** [comment]
Which code? All I can think of is usage with `functools.partial()` which wouldn't apply to functions with a single argument!

**Comment by AlexWaygood** [comment]
We'd need to approach such a deprecation extremely carefully. Each function changed would have to be evaluated separately to see if the tradeoff would be worth it for users of CPython. For each function, we'd have to consider:
- How common is it to pass a keyword argument to the parameter(s) we're considering changing? If it's common, and/or if it makes sense to be able to pass it by keyword, it may not be worth the disruption
- How much of a speedup are we talking for that function?
- How likely is it that that function would be used in performance-critical areas of a codebase, such that speeding up the function would offer a meaningful and noticeable improvement for users of CPython?

This isn't to say that we shouldn't make _any_ changes here, necessarily. If there are builtin functions where it really makes no sense to pass an argument by keyword, it would speed the function up a lot to make a parameter positional-only, and we can't really find any uses in the wild of people passing it by keyword — for those functions, I think we could definitely consider starting a deprecation cycle so that we can eventually make them positional-only. We definitely can't do them all at once, though, I'm afraid :-)

**Comment by nineteendo** [comment]
> We'd need to approach such a deprecation extremely carefully. Each function changed would have to be evaluated separately to see if the tradeoff would be worth it for users of CPython.

I agree, though we should use an approach that minimizes the required work (like only evaluating functions with 2 or more
required arguments).

> How common is it to pass a keyword argument to the parameter(s) we're considering changing? If it's common, and/or if it makes sense to be able to pass it by keyword, it may not be worth the disruption

Won't this be mostly used for functions with readability problems or an unintuitive order, and usage with something like `functools.partial()` (which doesn't apply to functions with a single argument)?

> We definitely can't do them all at once, though, I'm afraid

That's fine, but it's important that we discuss this.

**Comment by AlexWaygood** [comment]
> Won't this be mostly used for functions with readability problems or an unintuitive order, and usage with something like `functools.partial()`

It's pretty hard to say in the abstract, which is why we'd need to consider each function individually before making a decision on whether to start the deprecation cycle :-) but anything that would require people to change code that was previously working counts as a backwards-compatibility breakage, so is subject to the policy in PEP-387

**Comment by nineteendo** [comment]
Could we consider automatically updating all current clinic input to explicitely allow keyword arguments like in the proposal, and make arguments positional only by default if no keywords are provided?
Or would that lead to too many merge conflicts?

**Comment by nineteendo** [comment]
I also think we should start with the private functions (starting with an underscore).
For those functions we just need to check if they're not exported as public functions.

**Comment by AlexWaygood** [comment]
> Could we consider automatically updating all current clinic input to explicitely allow keyword arguments like in the proposal, and make arguments positional only by default if no keywords are provided? Or would that lead to too many merge conflicts?

I'm not sure I fully understand what you're proposing here, sorry

**Comment by nineteendo** [comment]
OK, so we simply convert this code:

```c
 /*[clinic input] 
 os._path_normpath 
  
     path: object 
  
 Basic path normalization. 
 [clinic start generated code]*/ 
```

To this:

```c
 /*[clinic input] 
 os._path_normpath 
  
     /
     path: object 
  
 Basic path normalization. 
 [clinic start generated code]*/ 
```

That's it. Oops, that's not supported:

```none
Error in file 'Modules/posixmodule.c' on line 5473:
Function '_path_normpath' has an unsupported group configuration. (Unexpected state 0.d)
```

**Comment by nineteendo** [comment]
Well, I guess this can be closed then for the time being.
