### ISSUE TITLE
Tutorial: An issue with 3.1.2. Text

### ISSUE THREAD

**Issue by PingPongSet** [python/cpython#117883]
# Documentation

https://docs.python.org/3/tutorial/introduction.html#text

The result below is wrong
```pycon
>>> '"Isn\'t," they said.'
'"Isn\'t," they said.'
```
it should be 

```
"Isn't," they said.
```

**Comment by hugovk** [comment]
I get the same results as the tutorial:

```pycon
Python 3.12.3 (v3.12.3:f6650f9ad7, Apr  9 2024, 08:18:47) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 'doesn\'t'  # use \' to escape the single quote...
"doesn't"
>>> "doesn't"  # ...or use double quotes instead
"doesn't"
>>> '"Yes," they said.'
'"Yes," they said.'
>>> "\"Yes,\" they said."
'"Yes," they said.'
>>> '"Isn\'t," they said.'
'"Isn\'t," they said.'
```

The the middle single quote is escaped in `'"Isn\'t," they said.'` because single quotes are also used for the whole string. If it wasn't escaped, it would signify the end of the string, and the remainder would be an error.

But if you `print` it, it shows up as expected:

```pycon
>>> print('"Isn\'t," they said.')
"Isn't," they said.
```
