### ISSUE TITLE
Make `posix.getcwd()` as fast as `nt.getcwd()`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117856]
# Feature or enhancement

### Proposal:

On Unix `os.getcwd()` is 33.85x as slow as on Windows!

```powershell
PS C:\Users\wanne> python -m timeit -s "import os" "os.getcwd()"
500000 loops, best of 5: 322 nsec per loop
```

```zsh
wannes@Stefans-iMac ~ % python -m timeit -s "import os" "os.getcwd()"
20000 loops, best of 5: 10.7 usec per loop
```

Is there anything we can do about this? Caching maybe?

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by zware** [comment]
I don't believe there's anything to do here, for several reasons:
- you're comparing apples to oranges, unless you're running both of those on bare metal on the same disk; my local result on Linux is around 400ns.
- `posix_getcwd` is already implemented in C as a quite thin wrapper around the `getwcd` syscall
- `os.getcwd()` really should not be performance critical anyway
- the value is trivially cacheable in application code.

**Comment by ericvsmith** [comment]
I agree with @zware.

**Comment by nineteendo** [comment]
Sorry, I was not running these on the same machine, but because this was such a big difference I thought there was something inefficient here. I'm getting slightly better results on Android:

```sh
/storage/emulated/12 $ python -m timeit -s "import os" "os.getcwd()"
100000 loops, best of 5: 2.32 usec per loop
```

**Comment by eryksun** [comment]
Here are my results on Linux and Windows 11. On Linux, the short path "/tmp" took 200-250 ns for both `os.getcwd()` and `os.getcwdb()`, while a 4058 character path took 3900-4050 ns for `os.getcwd()` and 3700-3750 ns for `os.getcwdb()`. For Windows 11 on the same machine, the short path "C:\\Temp" took 120-130 ns for both `os.getcwd()` and `os.getcwdb()`, while a 4047 character path took 2700-2800 ns for `os.getcwd()` and 3000-3300 ns for `os.getcwdb()`. 

Windows is faster here, but there's nothing that can be done about it on POSIX. Windows is simply doing less work. The system stores both a handle for the working directory and the normalized path of the working directory in the user-mode Process Environment Block (PEB), so fetching the path is cheap. However, it's not equivalent to POSIX because the working directory on Windows isn't a real path that's guaranteed to have no symlinks. It would be more expensive to meet that POSIX requirement on Windows. The implementation of `os.getcwd()` on Windows would have to open the path (cheap) and call `GetFinalPathNameByHandleW()` (expensive).
