### ISSUE TITLE
Overriding ft.cached_property does not work correctly when the return type is a generator, and the derived implementation uses parent implementation

### ISSUE THREAD

**Issue by marksandler2** [python/cpython#118015]
# Bug report

### Bug description:

Consider the following code:

```python
import functools as ft
from typing import Iterator
class Base:
  @ft.cached_property
  def foo(self) -> Iterator[str]:
    for each in ['a', 'b', 'c']:
      yield each

class Derived(Base):  # Example A
  @ft.cached_property
  def foo(self) -> Iterator[str]:
    elements = super().foo
    for each in zip(elements, ['c', 'd', 'e']):
      yield each
    

d = Derived()
print(next(d.foo))
print(next(d.foo))
```

You would expect it to print `('a', 'c') and ('b', 'd').`

Instead it prints `('a', 'c'), b`. 

What happens here? When d.foo is accessed first time, it updates `__dict__`, so far so good, but when `next` is  called, it calls `super().foo` which calls its `__get__()` implementation, and the parent cached_property's `__get__` function which unconditionally overrides the dict.  

The bug can be triggered even the result is not a generator but it is a little more convoluted, though it gets overridden again with the correct value after the derived property finishes: 

```python
class Derived(Base):  # Example B
  @ft.cached_property
  def foo(self) -> str:
    x =  super().foo + 'b'      # at this point self.__dict__ contains 'foo' populated by the parent's foo.
    return x
   # upon returning __dict__ will get updated with child's value, so most of the time this bug is 
   # invisible.
```

I think the solution here is to check in cached_property [implementation](https://github.com/pydanny/cached-property/blob/master/cached_property.py#L36)  if the cache has been updated and don't update it, and possibly introduce special sentinel value to indicate that it is about to be updated to deal with Example B , so to prevent parent from updating it even if temporarily. 

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux

**Comment by carljm** [comment]
Hi, thanks for the report!

I'm not able to reproduce the result you describe for the generator code you show. In all of Python 3.11.9, 3.12.2, and current main branch, I instead get `ValueError: generator already executing`. This is the result I would expect, because `foo` on the instance is the cached generator from the subclass override (starting from the first access of `d.foo`, before the generator code has ever been executed), and thus `super().foo` in the override body will return the same subclass generator that is currently executing.

I also don't think the behavior in the non-generator case is a bug. At the time of the `super().foo` call, there is no `foo` attribute on the instance yet, so the base class sets one. Then the subclass immediately resets it to the appropriate value for the subclass. This is all expected behavior, IMO, and not a problem. It is only detectable in a multi-threaded scenario, and `cached_property` is already documented as not thread-safe without user-provided locking.

The fix for the non-generator case would look something like this, I think:

```
diff --git a/Lib/functools.py b/Lib/functools.py
index a80e1a6c6a..a55e0843f8 100644
--- a/Lib/functools.py
+++ b/Lib/functools.py
@@ -993,6 +993,7 @@ def __isabstractmethod__(self):
 ################################################################################

 _NOT_FOUND = object()
+_UPDATING = object()

 class cached_property:
     def __init__(self, func):
@@ -1025,8 +1026,11 @@ def __get__(self, instance, owner=None):
             )
             raise TypeError(msg) from None
         val = cache.get(self.attrname, _NOT_FOUND)
-        if val is _NOT_FOUND:
+        if val in (_NOT_FOUND, _UPDATING):
+            cache[self.attrname] = _UPDATING
             val = self.func(instance)
+            if val is _UPDATING:
+                return val
             try:
                 cache[self.attrname] = val
             except TypeError:
```

This uses a sentinel, as you suggested. But this adds more complexity and reduces inefficiency, and I'm not sure what is gained. In any scenario where the temporary presence of the base-class value could previously have been detected, now instead the sentinel will be found instead. Both results are clearly wrong.

And this doesn't change anything about the generator case, because in that case there is never any temporary presence of a base-class value at all, because the subclass sets the cached value before the generator body ever runs.

As far as I can see, the most that is warranted here is a note in the `cached_property` documentation that it doesn't really make sense to cache a generator, and may result in unexpected behavior.

**Comment by marksandler2** [comment]
Hi Carl, 

Thanks for the response! You are absolutely correct, the behavior you describe is as expected, and i can't reproduce my observed behavior  on open source python.  I was running this on internal version of python where I still can reproduce it, but it probably has some patches applied, i will follow up on this elsewhere.
