### ISSUE TITLE
CPython requires stdatomic.h

### ISSUE THREAD

**Issue by encukou** [python/cpython#118034]
According to PEP-7:

> Python 3.11 and newer versions use C11 without [optional features](https://en.wikipedia.org/wiki/C11_%28C_standard_revision%29#Optional_features). The public C API should be compatible with C++.

However, CPython now requires `#include <stdatomic.h>` (an optional C11 feature) or MSVC. (Mimalloc can use C++ atomics, C11 atomics, or MSVC atomics. And pyatomic.h requires C11 atomics, MSVC atomics, or GCC atomics. The intersection is C11 or MSVC.)

This means CPython can't compile with GCC 4.8, as C11 atomics were [added in GCC 4.9](https://gcc.gnu.org/wiki/C11Status). See [this buildbot failure](https://buildbot.python.org/all/#/builders/15/builds/7501) for example. Granted, GCC 4.9 is very old and we can probably drop it, but I don't know how other compilers are affected.

**Comment by colesbury** [comment]
You can build CPython with GCC 4.8. Mimalloc is optional in the default build and is disabled by `configure` if `stdatomic.h` is not available.

I'm not sure what went wrong with the buildbot, but something is fishy. `configure` thought that `stdatomic.h` was present and that `gcc` does not need any options to enable C11 features, but GCC 4.8 needs `-std=gnu11` for C11 features. I wonder if the compiler used for `configure` and `make` are different.

I built main successfully with an Ubuntu 18.04 image and GCC 4.8. There is this warning after running `configure`, but otherwise it builds fine:

```
configure: Your compiler or platform does have a working C11 stdatomic.h. A future version of Python may require stdatomic.h.
```

**Comment by encukou** [comment]
Right. That buildbot run was misconfigured (configure had an up-to-date GCC `$PATH`, but the build apparently had a decade-old one O.o)

Sorry for the noise, and thank you for the info!
