### ISSUE TITLE
Add a command-line interface for the glob module

### ISSUE THREAD

**Issue by ZeroIntensity** [python/cpython#118133]
# Feature or enhancement

### Proposal:

The following command:
```console
python -m glob *.txt
```
would be more or less equivalent to
```py
print(" ".join(glob("*.txt")))
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by terryjreedy** [comment]
Closing for now because adding new command-line interfaces *should* be discussed ['elsewhere'.](https://discuss.python.org/c/ideas/6).
See for example the discussion of doing the same for [random](https://discuss.python.org/t/command-line-interface-for-the-random-module/51304/8), which after appropriate discussion in https://github.com/python/cpython/issues/118131.
