### ISSUE TITLE
Backslash char reported invalid usage inside single quoted string

### ISSUE THREAD

**Issue by lyallp** [python/cpython#118220]
### Bug description:

```python
# Add a code block here, if required
    script = 'tail -n 1000 /var/log/fail2ban.log | grep -E "fail2ban.filter.*\[[0-9]+\]:.*\[[^]]+\] Found ([0-9]{1,3}\.){3}[0-9]{1,3}" -o | sed -re "s/fail2ban.filter\s+\[[0-9]+\]:\sINFO\s+\[//; s/\]//; s/Found //;" | sort | uniq -c > ' + tmpf[1]
```
The above code generates a 'Syntax Warning: invalid escape sequence '\\[' (reverse quote left square bracket)
even if I put this code inside a if(false):, the message is generated, so it's during parsing, not execution.
To make it so the message is not generated, every occurrence of `\` has to be replaced with `\\`

This code worked just fine in 3.11
As such, I tried putting before and after inside an if, testing the running version of python and I still saw the message, even though execution used the \\ string.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by brianschubert** [comment]
Hi lyallp, this isn't a CPython bug. `\[` is an invalid escape sequence. Including that in a string literal emits a `DeprecationWarning` in Python 3.6+ and a `SyntaxWarning` warning in Python 3.12+. See this [StackOverflow question](https://stackoverflow.com/q/77531208/11082165) for more details on why you're seeing this warning and how to mitigate it. 

In the future, it's a good idea to ask about potential bugs on https://discuss.python.org/c/users/7 before opening an issue.

**Comment by terryjreedy** [comment]
This is the second item [here](https://docs.python.org/3/whatsnew/3.12.html#other-language-changes).  The alternative fix, recommended for a long time for regexes, is to prefix the string with 'r'.
```
>>> r'\['
'\\['
```
Note: '`' is the 'reverse quote' char.  '\\' is 'backslash'.

**Comment by lyallp** [comment]
The problem arises during a STRING assignment in which I build a bash command line that uses Grep and Sed, both of which have Regexp parameters, so the string is not a regexp and cannot be 'fixed' by prefixing with an 'r'

The error is generated during parsing, not execution, so even code that has no hope of executing, generates the message.

section 2.4.1.1 it is obvious that 3.11 did not conform by not generating a diagnostic, whereas 3.12 does.

My error with regard to 3.12 but an issue still stands with 3.11, it does not generate a diagnostic at all.

Still, it is not possible to write python code that is backward compatible by enclosing the code in an IF statement and executing the new code or the old code, depending on which version of python is being used as the diagnostic is not runtime but parsing time.
Feel free to close the bug, if appropriate.

**Comment by brianschubert** [comment]
Python is working as designed here. I'd recommend opening a thread on https://discuss.python.org/c/users/7 if you'd like to discuss how to work around this warning

**Comment by terryjreedy** [comment]
You can fix a string containing backslashes that are meant to be included in the string either by prefixing the string with 'r' or by doubling each backslash.  Your choice.  The latter solution is required if you want some backslashes to be interpreted as escapes and some as literal chars.  I mentioned 'regex' because regexes are the most common reason to want literal '\\'s and because your strings contains regex substrings.  The parser does not care why the literal backslashes are there.  A properly written string will work on older pythons.

Syntax warnings and errors are (nearly) always generated while parsing.  That is what the terms mean.  No need to repeatedly tell us.  3.11, and likely 3.10, emitted a DeprecationWarning, as designed, which you apparently do not see.
