### ISSUE TITLE
test_trashcan_16602 crashes on WASI in Debug build

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#118445]
# Bug report

See test failures in gh-118339, e.g. [this one](https://github.com/python/cpython/actions/runs/8896769195/job/24430337127).

Fow now I'm going to disable the `test_trashcan_16602` test if we detect both WASI and `Py_DEBUG`, but maybe someone should look into what's going on here. The `Py_C_RECURSION_LIMIT` variable is set to 500 for all debug builds; lowering it to 300 for WASI did not make any difference (and caused problems elsewhere). WASI without pydebug mode is fine.

**Comment by brettcannon** [comment]
In most instances tests had there recursion limit artificially low when hitting the limit is on purpose, e.g. https://github.com/python/cpython/commit/3c19ee0422e9b9f1582fb74931c174a84583bca0 . Otherwise skipping is fine as the stack depth under wasmtime in a debug build is very small.

So unless hitting the recursion limit is on purpose, you can just leave the test skip in IMO.

**Comment by brettcannon** [comment]
I'm going to close this, @gvanrossum , as it seems the test is not about testing what happens when the recursion limit is hit (obviously if this is wrong just let me know and I will tweak the recursion limit in the test).

**Comment by gvanrossum** [comment]
Agreed. We can do without this test on that particular combination of platform parameters. Thanks for following up!
