### ISSUE TITLE
Group definition of `os.remove()` & `os.unlink()`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#118954]
# Documentation

`os.remove()` & `os.unlink()` are semantically equivalent. Could we group their documentation?

### Linked PRs
* gh-118955

**Comment by rhettinger** [comment]
Sorry, this does not make any sense.  That two entries already cross-reference each other. It is best to keep the alphabetical order so that people who do not already know that they are aliases can find them.  This is similar to how there are different man pages for `unlink` and `remove`.

Thanks for the suggestion, but we will decline.
