### ISSUE TITLE
why 1 == 0.99..??

### ISSUE THREAD

**Issue by yassine-ennatiqi** [python/cpython#119047]
# Crash report

### What happened?

```python
print(1 == 0.99999999999999999)
```
True .
why??
![Capture d’écran 2024-05-14 182435](https://github.com/python/cpython/assets/154271510/e1fdaf7b-43c2-4588-b457-483c84c6df24)

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Windows

**Comment by sobolevn** [comment]
https://stackoverflow.com/questions/51170191/why-in-floating-point-arithmetic-0-9999999999999999-1-but-0-9999999999999999

This is how `float` works.

This is a bug tracker :)
Please, ask support questions on https://discuss.python.org/c/users/7

**Comment by yassine-ennatiqi** [comment]
But isn't this a mistake?

**Comment by terryjreedy** [comment]
No.  You used 17 9s instead of 16 as in the SO question.  The difference makes 1.0 the nearest representable float.
```
1 == 0.999_999_999_999_999_90
False
1 == 0.999_999_999_999_999_99
True
```
The discussion of float formats in the SO answers is otherwise relevant to your observation.  If you want the difference kept, use the decimal module with sufficient digits of accuracy.  In the future, ask on 'discuss' so answers are more available to other beginners.

**Comment by yassine-ennatiqi** [comment]
What about programs that require a lot of accuracy?

**Comment by yassine-ennatiqi** [comment]
But as long as one is beneficial to us, 2 == 1.99..

**Comment by mdickinson** [comment]
@yassine-ennatiqi Please take discussion to https://discuss.python.org/c/users/7 as already suggested. This tracker isn't the right place for such discussion.
