### ISSUE TITLE
Libmpec-dev not available on debian 12 when building Python

### ISSUE THREAD

**Issue by neochine** [python/cpython#119114]
# Feature or enhancement

### Proposal:

In this guide
https://devguide.python.org/getting-started/setup-building/#build-dependencies
it suggests lib-mpdec but its not available in debian 12? Perhaps its outdated package?
```
root@v18606:~/cpython# sudo apt-get install build-essential gdb lcov pkg-config \
      libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
      libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev \
      lzma lzma-dev tk-dev uuid-dev zlib1g-dev libmpdec-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libreadline-dev' instead of 'libreadline6-dev'
E: Unable to locate package libmpdec-dev
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by we-are-all-individuals** [comment]
I encountered the same issue. It looks like mpdecimal has been removed solely because dh-sphinxdoc was not happy with the pre-built HTML docs ...

https://groups.google.com/g/linux.debian.bugs.dist/c/IhDtdjrk7mE

The upstream mpdecimal changelog states that the Sphinx documentation is now in a separate package:

https://www.bytereef.org/mpdecimal/changelog.html

Debian should not have any reason not to reinstate the package, it should be trivial. I suggest to ask nicely on the Debian mailing lists and mention that mpdecimal will be assumed to be present in the CPython build process in the future.

**Comment by neochine** [comment]
Alright. Given I could build python3.12 even without installing that package, it looks not much necessary. I think issue can be closed

**Comment by aisk** [comment]
The devguide said that `mpdecimal` is just an optional package for building with optional packages, so it is not required for building Python.

But I think this is still an issue that needs to be fixed.

**Comment by devdanzin** [comment]
Here's the Debian bug report log for the removal: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1056785

**Comment by we-are-all-individuals** [comment]
> Here's the Debian bug report log for the removal: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1056785

Reading that issue, it looks like the Debian developers are not going to respond there. Perhaps opening an issue against the Debian CPython package will get more attention.

**Comment by erlend-aasland** [comment]
FTR, a fallback to the bundled version is added in #119196.
