### ISSUE TITLE
Support `pythonπ` in Python 3.14 venv's

### ISSUE THREAD

**Issue by hauntsaninja** [python/cpython#119535]
# Feature or enhancement

### Proposal:

```
λ env/bin/pythonπ
Python 3.14.0a0 (heads/main-dirty:de19694cfb, May 24 2024, 23:13:56) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

### Linked PRs
* gh-119536
* gh-125035
* gh-134037

**Comment by ronaldoussoren** [comment]
I guess I'm too boring, but I'm -1 on this.  This would a nice-ish easter  egg, but we'd have to revert for 3.15 and that opens up backward compatibility issues.

**Comment by nineteendo** [comment]
+1 It doesn't need to be reverted. We check specifically for 3.14.

**Comment by zitterbewegung** [comment]
I have seen cute things like this break systems . I believe racket-lang had some birthday code trigger but then it broke the system on that day. Who knows what this would break and it seems too hard to test.

**Comment by jbosboom** [comment]
Unlike most easter eggs, this will be directly presented to users because it will appear in tab completion, so you will get questions about it.  Users without Unicode fonts in their terminal will be extra confused.  I don't think it is worth the support burden.

**Comment by hauntsaninja** [comment]
> Still, someone might start using pythonπ in a shell script with 3.14

The same argument would apply to using "python3.14" in a shell script

Not wanting easter eggs is a valid personal difference, they are sometimes contentious (even if the CPython project has a history of a few). I think this one is quite predictable and harmless. I do concede that in 3.15 it would create two dead but harmless lines of code — to me that's a reasonable cost for a little bit of joy.

I've heard some FUD about the use of a Greek character. It's 2024, I'm genuinely curious, does anyone have an example of a platform/filesystem we support that this would cause a real issue on? Note also that PEP 11 has this to say https://peps.python.org/pep-0011/#legacy-c-locale

**Comment by skirpichev** [comment]
> But, I still advocate for using pi easter egg for 3.14 release somewhere else.

Minor releases 3.14.1, 3.14.15, 3.14.159, ... (or rather 3.14.2, 3.14.16, 3.14.159...)?  But ~~Simpsons~~TeX already did it!

**Comment by sobolevn** [comment]
Proof that easter eggs do create maintenance costs and bugs: https://github.com/python/cpython/issues/124960

**Comment by nineteendo** [comment]
> I do concede that in 3.15 it would create two dead lines of code

Technically we could wait with merging this until a 3.14 branch is created, right? Then there's no need to revert it.

> Minor releases 3.14.1, 3.14.15, 3.14.159, ...

How about displaying 3.14.2, 3.14.3, ... as 3.14.15, 3.14.159... in the REPL? Because I'm afraid `PY_VERSION_HEX` might make things difficult.

> easter eggs do create maintenance costs and bugs

The chance at bugs should be lower since it's just for one release (and not as complicated as `<>`).

**Comment by skirpichev** [comment]
> displaying ... in the REPL?

Well, with something like ~20 minor releases this will be
```pycon
>>> "3.14."+f"{gmpy2.const_pi():.22f}"[4:]
'3.14.15926535897932384626'
```
On another hand, current 1st line of the banner doesn't fit common default of 80 characters width anyway... ;)

> I'm afraid PY_VERSION_HEX might make things difficult.

Yeah, and rather impossible.  159 will be the last minor version, that increases monotonically and don't mess with major or minor version.

**Comment by rruuaanng** [comment]
Oh damn, turns out this was an easter egg. A while back, I was seriously telling the author that maybe ASCII characters should be used. Looks like I’m just old-fashioned.

**Comment by zitterbewegung** [comment]
Hypothetically someone uses python3.14 and either on accident (tab competition) or on purpose  writes a script that references λ env/bin/pythonπ and they are logging the call to pythonπ .  Wouldn't this cause confusion if more people are working on the project and don't understand what it is since they don't understand the joke?

**Comment by hugovk** [comment]
Merged.

Now, everyone: shhh!

**Comment by natewind** [comment]
`pyτhon` would be twice as good

**Comment by bennoapkudo** [comment]
> I have seen cute things like this break systems . I believe racket-lang had some birthday code trigger but then it broke the system on that day. Who knows what this would break and it seems too hard to test.

FWIW, it did break things for me. There are some (edge cases) where various tools don't like non-ASCII path names. This is arguably a bug in those tools ( https://github.com/ostreedev/ostree/issues/3431 ). Perhaps exposing these issues is a good thing.

**Comment by ArrayBolt3** [comment]
> FWIW, it did break things for me. There are some (edge cases) where various tools don't like non-ASCII path names. This is arguably a bug in those tools ( https://github.com/ostreedev/ostree/issues/3431 ). Perhaps exposing these issues is a good thing.

Note that some tools intentionally reject all non-ASCII characters because of the (sometimes severe) risks of dealing with them. Unicode parser vulnerabilities is an obvious case, but [Trojan Source](https://trojansource.codes/) attacks are also a thing, as are [mismatches between Unicode versions supported by various tools](https://engineering.atspotify.com/2013/06/creative-usernames). In particular, Kicksecure has a handler for the `org.freedesktop.FileManager1` D-Bus interface that will scream very loudly if it detects non-ASCII in filenames as a security precaution. (It also comes with lots of fancy tools for inspecting those characters without displaying them raw, since displaying them raw opens the Trojan Source hole and potentially other unknown Unicode what-you-see-is-not-what's-actually-there bugs.)

Also, some snaps in Ubuntu are struggling with this "feature" causing lovely directory listings like:

```
# ls -lh prime/bin/
....
-rwxr-xr-x 3 root root  225 Sep 17 00:08  pip
-rwxr-xr-x 3 root root  225 Sep 17 00:08  pip3
-rwxr-xr-x 3 root root  225 Sep 17 00:08  pip3.14
lrwxrwxrwx 1 root root    7 Sep 17 00:08  python -> python3
lrwxrwxrwx 1 root root   21 Sep 17 00:08  python3 -> ../usr/bin/python3.14
lrwxrwxrwx 1 root root    7 Sep 17 00:08  python3.14 -> python3
-rwxr-xr-x 3 root root  215 Sep 17 00:08  uvicorn
lrwxrwxrwx 1 root root    7 Sep 17 00:08  ''$'\360\235\234\213''thon' -> python3
```

Easter eggs that trigger during normal user interaction cause real-world problems virtually always. A program's behavior in response to certain input is essentially part of that program's API, and triggering an easter egg effectively changes the program's API in an unexpected and sometimes unpredictable way. The [gimme gimme gimme](https://unix.stackexchange.com/questions/405783/why-does-man-print-gimme-gimme-gimme-at-0030) easter egg in `man` is one particularly fun example. IMO such easter eggs do not belong in critical infrastructure like Python. If there are going to be any easter eggs in any program, but especially one of this scale, they should only be able to be triggered intentionally by a user who knows or suspects they are there, like the `aptitude [-vvvvvv] moo` series of jokes.

**Comment by hugovk** [comment]
Is `𝜋thon` actually causing you an issue here? 

If so, good news! Python 3.15 is out in 9 days which removes it! 🚀

Trojan Source is an "attack is to use control characters embedded in comments and strings to reorder source code characters in a way that changes its logic". It's an attack on code review, not file systems. This pi symbol is an ordinary display character, with no BIDI direction control. It's a hard-coded constant, not attacker-controlled source code, so Trojan Source doesn't apply here.

It looks like Kicksecure only [warns for non-ASCII directories](https://github.com/Kicksecure/security-misc#file-manager-d-bus-shim), and not files like this one:

> This shim displays a confirmation window for every request an application makes to open one or more directories, while also ensuring applications can only try to open directories (not files), and cannot try to open directories that the user cannot access. 

The file is only created in non-Windows venvs, and only when the file system encoding is UTF-8. For "broken" `ls`, this is cosmetic, I suggest setting a UTF-8 locale rather than plain `C`/`POSIX`.

**Comment by ArrayBolt3** [comment]
> The file is only created in non-Windows venvs, and only when the file system encoding is UTF-8. For "broken" ls, this is cosmetic, I suggest setting a UTF-8 locale rather than plain C/POSIX.

That's a good idea, will forward it to the person who originally showed me the dir listing issue.

On the Trojan Source point, filenames are a part of code review too. Unicode has more dangers than just Trojan Source attacks, and while it is possible and potentially reasonable to try to disallow / specially handle just the "bad" parts of Unicode, Unicode is so complex that some tools intentionally say "let's not even go there" for the sake of avoiding the security footguns of dealing with it. Those tools can choke on things like this. (I had forgotten that the shim mentioned only looks at directory names, which is a bit ironic because I wrote the shim, so I guess that wasn't the best example.)

> If so, good news! Python 3.15 is out in 9 days which removes it! 🚀

Unfortunately Ubuntu 26.04 LTS managed to snag Python 3.14, meaning that this easter egg will probably be floating around in the wild causing weird issues in strange edge cases for at least another 9 years and 9 months.
