### ISSUE TITLE
Windows Store Python 3.12 app execution aliases disabled by default

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#119653]
# Bug report

### Bug description:

After installing Python 3.12 from the Windows Store, the shell app execution aliases for `python`, `python3`, and `python3.12` were disabled by default.

I went looking for them after https://learn.microsoft.com/en-us/windows/python/beginners confirmed that the expected behaviour is for those commands to be available in any shell after installing Python from the Windows Store. Everything worked as expected once I turned the execution aliases on, so the only issue was with their default state.

Note that I had previously turned off the Python app installer aliases in the Windows settings, to avoid hiding other Python installs on `PATH` (originally a python.org Windows install, then MiniForge3 for a while). I removed all other Python installs before installing the Windows Store version (but the app installer aliases were left switched off).

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows 10

**Comment by ncoghlan** [comment]
Just noting that I confirmed with @zooba that this was an appropriate place to file this report before posting it.

**Comment by zooba** [comment]
It's a bit unfortunate given that people may look up a quick fix for a bad PATH, but this is by design. The assumption is that if someone has previously opened Manage App Execution Aliases, then they'll know/think to open it again, and that if they've specifically requested that a particular command be disabled then they don't want it enabled just because something (potentially an automatic update) was installed.
