### ISSUE TITLE
support bytes/bytearray in complex() constructor

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#119823]
# Feature or enhancement

### Proposal:

Not sure if this has much practical sense.  On another hand, other builtin numerical types (int, float) support at least bytes and bytearray (float - also other objects, supporting buffer protocol).

Filled as a feature request, but as it [was noted](https://github.com/python/cpython/pull/109642/#discussion_r1616789032) by @serhiy-storchaka - that might be treated as a regression (in py3).

I will work on a patch.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-119825

**Comment by mdickinson** [comment]
I'm not seeing that anything has changed much since #46735 and the related discussion. I'd vote -1 on this - I consider the fact that `int` and `float` support bytes to be a minor wart, but one that we can't remove for backwards compatibility reasons. I don't see a reason to make that wart bigger by extending it to complex. (Note that `fractions.Fraction` doesn't support `bytes` either, and this doesn't seem to have been a problem for anyone.)

**Comment by skirpichev** [comment]
Ok, this issue was born from somewhat random note in my pr; I would guess Serhiy wasn't aware about background story of this proposal.  Sorry for the noise.

**Comment by serhiy-storchaka** [comment]
Should #779 be revived? Support of bytes-like objects in `int()` and `float()` caused an issue. Since the buffer of the general bytes-like object is not necessary null-terminated, it requires copying it to a temporary null-terminated buffer.

**Comment by mdickinson** [comment]
> Should #779 be revived?

Maybe? I don't have a good sense of how many people are relying on applying `int` and `float` to bytes (e.g., as part of parsing some mixed text+binary format).
