### ISSUE TITLE
[C API] Add a public Py_nullptr macro (rename private _Py_NULL)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#119851]
On C23 and newer and on C++11 and newer, `nullptr` is preferred over `NULL` to specify a "null pointer". Python has a private `_Py_NULL` macro for that. Static inline functions should use Py_NULL rather than using directly NULL to prevent C++ compiler warnings.

```c
#if (defined (__STDC_VERSION__) && __STDC_VERSION__ > 201710L) \
        || (defined(__cplusplus) && __cplusplus >= 201103)
#  define _Py_NULL nullptr
#else
#  define _Py_NULL NULL
#endif
```

I propose to make the macro public to make it usable in more cases: rename `_Py_NULL` to `Py_NULL`.

### Linked PRs
* gh-119852

**Comment by serhiy-storchaka** [comment]
Why make it public? Users can use `nullptr` or `NULL`, what they prefer, we should not force them using `Py_nullptr`.

**Comment by vstinner** [comment]
You cannot use nullptr if you use C11 or older, or C++03 or older. Using NULL on C++11 can emit compiler warnings. So it's not convenient to use nullptr nowaday.

**Comment by serhiy-storchaka** [comment]
It is not our business what the _user_ uses. On C++ they can use `nullptr` and on C they can use `NULL`. The user knows what they do.

**Comment by encukou** [comment]
Yeah, this sounds like it should be internal. I'm not sure which users this would help.

Users that don't need to support both C and C++ can simply choose `nullptr` or `NULL`.
For the rest: non-library users are probably better off with `#define nullptr NULL` for older C/C++, rather than switching to a Python-specific name.
For the rest of the rest: It won't help users that don't include `Python.h` for *all* their C code -- those need to define their own thing anyway.

In the end, I don't think it's worth the overhead of documentation, support, and eventual deprecation.

> On C23 [...], nullptr is preferred over NULL to specify a "null pointer". 

Hm, I haven't yet heard that it's *preferred* on C23. Do you have any reference/reasoning for that?

AFAIK, the main benefit of `nullptr` is for use in `_Generic` (or C++ overloading). Note that in a `_Py_NULL`/`Py_nullptr` macro that can still expand to `NULL`, that benefit goes away.

**Comment by vstinner** [comment]
I failed to convince @serhiy-storchaka and @encukou, so I prefer to give up on making Py_nullptr public. I close the issue and its PR. Thanks anyway ;-)
