### ISSUE TITLE
Possible memory leak in pickle

### ISSUE THREAD

**Issue by mvhensbergen** [python/cpython#120095]
# Bug report

### Bug description:

```python
import gc
import os
import pickle
import psutil
import random

# Obtain memory usage of our process
def get_memory_usage():
    process = psutil.Process(os.getpid())
    mem_info = process.memory_info()
    return mem_info.rss

# Stub data that represents a lot of data
class LotsOfData:
    def __init__(self):
        self.a = "A" * 2**16
        self.mydict= {}
        self.mylist = []
        for i in range(0, 3):
            self.mydict[i] = "A" * 2**8
            self.mylist.append("A" * 2**8)

# The object we are going to pickle
storage = {}

N = 10000
# Initialize object to pickle
for i in range(0,N):
    storage[i] = random.Random()
    # storage[i] = LotsOfData()

# Determine memory use of process
before = get_memory_usage()
print(get_memory_usage())
input("Filled\n")

# Pickle the object to disk
with open("dump.pkl", "wb") as fh:
    pickle.dump(storage, fh)

# Display memory usage of process
print(get_memory_usage())
input("Dumped\n")

# Display memory usage after force garbabe collect
gc.collect()
after = get_memory_usage()
print(get_memory_usage())
print (round(after/before,2))
print("Collected")lock here, if required
```

In the above script, we create a dict with N=10000 random generators and use `pickle` to save this to disk. The implementation of `Random` has a function `getstate()` which is meant for serialization of the state of the random generator.

The script also measures the memory usage of the process before and after pickling to disk:
```
root@d9f64301400d:/src# python3 memdump2.py 
42991616
Filled

114040832
Dumped

76738560
1.78
Collected
```

When instead of pickling random generators but a regular class with quite some mem use (comment and uncomment de appropriate part in the script) we get:

```
root@d9f64301400d:/src# python3 memdump2.py 
674222080
Filled

674902016
Dumped

674902016
1.0
Collected
```

As expected, after pickling the process should not use more memory.

It appears pickling the random generator leaves global state of pickle.

This may also happen with other classes to pickle but this was the most obvious reproduction path.

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux

**Comment by serhiy-storchaka** [comment]
I do not think there is a leak. If you repeat the cycle of data initialization, pickling and cleaning up (`del storage`), you will see that memory usage does not significantly grow after the first iteration (it grow a little, but less with every iteration). The memory is not leaked, it stays in the memory pool, and used when more memory is necessary. Pickling of the random generator creates a lot of integer objects (624 per generator) and corresponding number of strings and bytes objects, this is why the peak memory usage is so high. Since the memory is fragmented, it cannot all be returned to the OS, but stays in the memory pool.
