### ISSUE TITLE
Example in docs for `configparser` wrong   

### ISSUE THREAD

**Issue by tegni** [python/cpython#120174]
# Documentation

In https://docs.python.org/3/library/configparser.html#quick-start the second code block ends on the following three lines: 
```python3
>>> with open('example.ini', 'w') as configfile:
...     config.write(configfile)
... 
```
I suggest the following change: 
```diff
[...]
  >>> with open('example.ini', 'w') as configfile:
- ...     config.write(configfile)
+ ...     configfile.write(config)
```
The variable `config` is defined as the config that is modified in the lines above and `configfile` as the opened file object, so I suspect that the way it is now is incorrect. If it is indeed correct that way I'd suggest adding a note giving a quick explanation why it's that way around.

**Comment by gaogaotiantian** [comment]
`config` is a `ConfigParser` object which has a method `write` that takes a file-like object (in this case, `configfile`).

**Comment by Lampe2020** [comment]
> `config` is a `ConfigParser` object which has a method `write` that takes a file-like object (in this case, `configfile`).

Maybe you should add such a note to the docs as it is pretty unusual to see the file object get passed as an argument to another object's `.write()` method instead of having its `.write()` method called with a stringified or binarized form of an object.

**Comment by gaogaotiantian** [comment]
It's not unusual to pass the file object to another object. Almost all standard libraries do that - `json`, `pickle`, `csv` ... you name it. `ConfigParser` has a method that happens to be `write` so that might be a bit confusing, but I don't see enough incentive to add extra comments here. I can't think of when `configfile.write(config)` would work if `config` is an arbitrary object.
