### ISSUE TITLE
``test_pydoc.test_pydoc`` fails with a ``-R 3:3`` option

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#120590]
# Bug report

### Bug description:

```
./python.exe -m test -R 3:3 test_pydoc.test_pydoc
```
The output of the tests is in the attached file.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

[output.txt](https://github.com/user-attachments/files/15858121/output.txt)

### Linked PRs
* gh-120615
* gh-120669
* gh-120670

**Comment by Eclips4** [comment]
cc @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
It fails because `sys.modules['pydoc']` and `pydoc` (imported at the top of `test_pydoc`) are not the same. Some `pydoc` functions reload the module and change `sys.modules`. The first pass is successful because tests with such side effect are run after tests that use `unittest.mock.patch`, but the second pass fails.

There are other tests that use `unittest.mock.patch`, they do not fail, but the second pass do not test what it was intended.

The PR restores `sys.modules['pydoc']` after it was modified and adds a check after every test to ensure that it was restored (because we may add new tests in future).
