### ISSUE TITLE
Bug when press arrow button in command processor

### ISSUE THREAD

**Issue by Usercyk** [python/cpython#120538]
# Bug report

### Bug description:

When using python in cmd, I found that I can press right arrow button at the end of one line, then it just automatically filled the blanks with the characters of the previous line. That's weird and won't happen in vanilla cmd. I'm not sure whether this is the python's design.

Minimal Example:
1. Open cmd, enter python
2. just type something into the command line, press enter
3. type something at the new line then using right arrow button (or just only press the button), it will automatically repeat the content of the previous line

Screenshot:
![image](https://github.com/python/cpython/assets/109349977/1d4415ec-1387-4e6b-903d-58413e59a2fd)

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by eryksun** [comment]
This isn't a bug, and it doesn't have anything to do with either Python or CMD. It's a feature of the Windows console that dates back to MS-DOS. A template buffer in the console input file always contains the last entered non-empty command line. Either F1 or the right-arrow key copies one character from the corresponding column in the template. F2 followed by a character copies up to but not including the first occurrence of the character from the template. F3 copies the remainder of the template starting at the current column.

Back in MS-DOS, a Doskey utility could be run to extend the system's basic command-line editing, as well as provide support for macros and command-line history. Doskey mapped additional function keys for command-line editing, such as the F7 key to display the command history, F8 key to cycle though the history, and F9 key to run a command based on its number in the history buffer. Doskey also mapped the up and down arrow keys to move forward and backward in the history buffer.

In Windows systems based on NT instead of MS-DOS (NT was first released in 1993, and used by all versions since Windows XP), the console host is implemented to emulate all of the basic MS-DOS and extended Doskey command-line editing. It also supports per-application macros and history, up to given number of history buffers configured in the property sheet for the current console-session profile (a session profile gets created based on the initial window title, and gets persisted either in the registry in a subkey of "HKCU\\Console" or in a .LNK shortcut file if the initial console 'title' in the spawning process parameters is flagged as being the path of a shortcut file). Microsoft provided a "doskey\.com" utility on NT systems to emulate the classic MS-DOS Doskey interface, but under the hood it was built into the console host itself. (The console host used to run in the Windows session server process, "csrss.exe", but nowadays it runs in an unprivileged instance of either "conhost.exe" or "openconsole.exe".)

If you dislike the Doskey command-line editing and history support that's built into the Windows console, you're in for a treat with the next release of Python. There's a new REPL that implements all of its own command-line editing and history support on Windows. I don't see any discussion about implementing a "Windows" mode to fit in with other command-line applications that use the console's builtin Doskey UI. Maybe an option for that will be added later.

**Comment by Usercyk** [comment]
Thank you very much. And sorry for taking up your time. My bad
