### ISSUE TITLE
Use `@file` for gcc commands

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#120677]
# Feature or enhancement

### Proposal:

When building Python 338 gcc commands are run with these options[^1]:

```none
-fno-strict-overflow -Wsign-compare -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -Og
-Wall -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes
-Werror=implicit-function-declaration -fvisibility=hidden -I../cpython-ro-srcdir/Include/internal
-I../cpython-ro-srcdir/Include/internal/mimalloc -IObjects -IInclude -IPython -I.
-I../cpython-ro-srcdir/Include
```

That's 400 characters, here's a screenshot to demonstrate how ridiculously long these commands are:
 
<img width="2048" alt="Screenshot 2024-06-18 at 12 43 55" src="https://github.com/python/cpython/assets/65588599/68438e97-d8dc-4c26-bd0b-29e00e2c1849">

Can we please use `@file` to read the options from a file instead? e.g.

```shell
$ gcc -c @file -DPy_BUILD_CORE -o Programs/python.o ../cpython-ro-srcdir/Programs/python.c
```

[^1]: See this file: [gcc.txt](https://github.com/user-attachments/files/15884692/gcc.txt)

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by eli-schwartz** [comment]
The same argument could be made about virtually any software project which uses a compiler. I don't find it compelling. You could simply ignore the command lines entirely and wait for it to finish.

More generally, the actual issue here isn't that the compiler is *invoked* with an argument list, it is that the build status *logs* the entire argument list, instead of perhaps doing this:

```
  CC (core)  Programs/python.o
  CC (core)  Parser/token.o
  CC (core)  Parser/pegen.o
[...]
```

Python uses autoconf to build, but not automake. Automake usually provides this for free, and makes it controlled via:

```
./configure --enable-silent-rules # be compact
./configure --disable-silent-rules # be very verbose


make V=0 # override --disable-silent-rules and be compact
make V=1 # override --enable-silent-rules and be very verbose
```

This is fully under control of the user, which many people like because it means they can guarantee "full debugging logs" are available by default in various contexts, e.g. CI / build servers.

**Comment by eli-schwartz** [comment]
Not all C11 compilers (are guaranteed to) support `@file`, but all Make implementations support silent rules.

**Comment by nineteendo** [comment]
```shell
$ g++ `cat compiler.args|xargs`
$ COMPILE_ARGS=`cat compiler.args|xargs` g++ ${COMPILE_ARGS}
```
You can also do this, but silent rules would be fine too.

**Comment by erlend-aasland** [comment]
Eli:

> This is fully under control of the user [...]

+1

**Comment by nineteendo** [comment]
OK, I can zoom out, but I had hoped we could make these commands a bit shorter. ;(
A bit ironic given the fact that PEP 7 & 8 mandate 79 characters for code.

**Comment by eli-schwartz** [comment]
@erlend-aasland,

for the sake of clarity: when I say "This is fully under control of the user" I am complimenting the rules that automake creates when processing a `Makefile.am`.

cpython doesn't use automake, so if it is desirable for cpython to do what automake does "OOTB", it would have to manually implement that.

The mechanism isn't too complicated, especially if you've read some of automake's source code. (This is partially a joke, and partially not a joke.)

**Comment by nineteendo** [comment]
Could you please re-open this? (You can always close it again if we decide this isn't desired)

**Comment by nineteendo** [comment]
@sobolevn, could you re-open this? erlend-aasland hasn't done that.

**Comment by erlend-aasland** [comment]
We're not going to manually reimplement automake features; we're not going to swotch to automake. @nineteendo, if you want to maintain your own CPython build system, you can do so on your own fork. There's a lot of alternative CPython build systems out there, if you are curious about other variants. I see no reason to reopen this; please stop pushing.

**Comment by eli-schwartz** [comment]
Yeah, this is something that I could implement and PR if it was decided to accept, but I'm... not particularly motivated to push for it since I would not actually use the option -- the status quo is fine for me.

I'm happy to clarify facts about the various options which exist throughout the wide world of technology, of course, even if there is a lack of enthusiasm about adopting any of them for CPython. Facts are interesting and often fun to know about.

**Comment by nineteendo** [comment]
> We're not going to manually reimplement automake features; we're not going to swotch to automake.

That's a satisfactory answer for me, the issue was simply closed without mentioning this.
