### ISSUE TITLE
Bug in smtplib example

### ISSUE THREAD

**Issue by MordechaiFast** [python/cpython#120662]
# Documentation

The example code is meant to demonstrate sending a multi-line message. It does not do that; the lines get contracted into one.

This can be fixed by adding a newline character to the end of the line when it is added to the message string:
```python
msg += line + '\n'
```

BTW, why not use PEP8 compliant names, f-strings, and context managers? Why make things complicated with a .strip() call? Why make it that blank lines in the message are like pressing send?

```python
import smtplib


from_addr = input("From: ")
to_addrs  = input("To: ").split()
print("Enter message, end with ^D (Unix) or ^Z (Windows):")

# Add the From: and To: headers at the start!
msg = f"From: {from_addr}\r\nTo: {', '.join(to_addrs)}\r\n\r\n"
while True:
    try:
        line = input()
    except EOFError:
        break
    msg += line + '\n'

print("Message length is", len(msg))

with smtplib.SMTP('localhost') as server:
    server.set_debuglevel(1)
    server.sendmail(from_addr, to_addrs, msg)
```

### Linked PRs
* gh-120668
* gh-120681
* gh-120682

**Comment by hugovk** [comment]
Please can you link to the relevant page?

**Comment by terryjreedy** [comment]
The proper idiom would be to make an initialized list of lines, append further lines, and join with '\r\n' when complete.
```
    lines = [f"From: {from_addr}", "To: {', '.join(to_addrs)}", ""]
...
        lines.append(line)
...
    msg = '\r\n'.join(lines)
```

**Comment by picnixz** [comment]
> BTW, why not use PEP8 compliant names, f-strings, and context managers?

Well... PEP 8 is a suggestion, not a requirement so it can't force people to follow it. For the rest, it's probably because at the time when it was written, f-strings and context managers did not exist and the code has not been updated since then.

> Why make things complicated with a .strip() call?

To ensure that you don't have whitespaces before and after in the list of mails to send to, just before the `split()` call (and to avoid having an empty address). 

> Why make it that blank lines in the message are like pressing send?

that's a good question; I think it was assumed that you only want to send a single paragraph (though I agree it's not really a good idea since you could just end the message with CTRL+D).

---

I'll make a PR to improve the example. @terryjreedy May I shamefully take your idiom?

**Comment by picnixz** [comment]
I think this one can now be closed @hugovk

**Comment by terryjreedy** [comment]
@picnixz (" May I shamefully take your idiom?") Yes! I am delighted to wake up and find my suggestion implemented and merged.
