### ISSUE TITLE
Optimize sort() and min()/max() by not calling keyfunc for size-1 inputs

### ISSUE THREAD

**Issue by jobh** [python/cpython#121292]
# Feature or enhancement

### Proposal:

Calling the `key=` argument to `sort()` and `min()`/`max()` is unnecessary when the input size is 1, as there are no comparisons. Motivation is from a binary-heap-like structure, where the key function is slightly expensive and the number of children to find the minimum of is at most 2. `max()` and `sort()` follow as low-hanging fruit.

This seems like a niche optimization, and it is, but the code change is small, and it avoids the temptation for contorted invocations like

```python
if children: 
    min_child = children[0] if len(children) == 1 else min(children, key=sort_key)
    ...
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-121294

**Comment by terryjreedy** [comment]
Call is also unnecessary with size 0, though that may be handled already.
This adds a cost to every min, max, and sort call, and will very rarely save anything, so average saving is unclear.

**Comment by jobh** [comment]
Yes, size-0 is already handled in the sense that there is no item to call the key function for.

The cost for sort() is a single size comparison; the cost for min()/max() is one `NULL` comparison per item. I believe both are insignificant overall, but I agree it is uncertain.

**Comment by jobh** [comment]
Hm, actually I can get rid of that extra `NULL` comparison per item, making it constant.

**Comment by gaogaotiantian** [comment]
It's a very interesting idea. I have a few concerns about this.

First of all - is it okay to skip the `keyfunc` when the list only has one value? This seems harmless, but `keyfunc` could have a potential side effect. I don't know if there is code out there that relies on it. Our docs says:

> The key corresponding to each item in the list is calculated once and then used for the entire sorting process.

Is it a violation to the documentation when the key is *not* calculated at all?

Let's say it's not and it's an implementation defined behavior - we have no obligation to keep that. What's the ROI on this?

I like the changes to `list.sort()` because that's super easy to follow. However, `min()` and `max()`, not so much. The code is definitely more difficult to read and understand. For example, the `keyfunc` part appears twice in the function. We now need to distinguish the *first* and *second* iteration. I was wondering, if it would make more sense to just optimize on certain builtin types - lists/sets etc. and check if the size of it is `1` and return when it is. I think that's a good tradeoff between a fast path for a more common case, vs extra code complexity and overhead in other cases.

**Comment by tim-one** [comment]
I would rather not go down this path. It won't end here. For example, various `bisect` module functions, and `heapq.merge()`, also have optional `key=` args.

I'd say that, yes, it's flatly backward-incompatible for `list.sort()` to ever skip calling a key function. In the absence of weasel words, the docs have to be taken as meaning what they plainly say. Python isn't, e.g., C, and "mental models" in the Python docs are intended to be the final word, not just hints subject to modification by other text 100 pages away. Like "left to right" means "left to right", period. Except when it doesn't :wink:.

We don't need elaborate "use cases" to justify this default. For example, it may be as boring as that a particular key function increments a global counter per call, as a cheap and automated way to generate statistics about how many list items in all were input to `.sort()`. Works fine today, would _appear_ to work after, but would silently overlook counting singleton lists.

If there were drop-dead great speed gains to be had in return, maybe it could be justified on "practicality beats purity" grounds. But it's hard to imagine a real app where improving the speed of sorting 1-element lists would make a lick of practical difference. If there is such a thing, the author would be well-advised to write their own tiny sort wrapper to skip calling `sort()` at all unless there are at least 2 elements.

**Comment by jobh** [comment]
Thank you all for your considered opinions! I'll retract this.

**Comment by tim-one** [comment]
Thanks for the good grace, @jobh. It was a reasonable proposal, and you did a good job of presenting it. I hope you stick around!
