### ISSUE TITLE
nested filter via for loop incorrect behavior

### ISSUE THREAD

**Issue by mvirts** [python/cpython#121274]
# Bug report

### Bug description:

I ran across an issue nesting filters within a loop. Iterating the final filter object to build a list generates elements that seem to ignore all preceding filters and only applies the last filter to the original iterable.

In contrast, writing out the nested filters literally provides the expected results

```python
print("Nested filters in loop")
f = list(range(10))
l = [3,2]
for v in l:
    f = filter(lambda x: x%v==0, f)
print(list(f)) # [0, 2, 4, 6, 8]
 
print("Literal nested filters")
f = list(range(10))
print(list(filter(lambda x: x%2==0,filter(lambda x: x%3==0, f)))) # [0, 6]
```

I've checked that the filter objects are unique and that the loop is running correctly. Materializing the filter into a list each iteration successfully works around the issue.

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux, Windows

**Comment by gaogaotiantian** [comment]
This is because your lambda function `lambda x: x%v==0`. Notice that variable `v` is not "local", and it's lazily evaluated, so the lambda function will read the variable `v` when it's being evaluated - it won't remember that in the first loop, `v == 3`. So when you evaluated `list(f)` after the loop, `v == 2` and both of your filters are filtering on the same condition. It's not a bug and lambda functions could be evil sometimes.

**Comment by mvirts** [comment]
And I thought I had checked everything! Thanks

**Comment by terryjreedy** [comment]
FYI: if you add `, v=v` to the lambda args, they work as expected.  This must be in the FAQs someplace.

**Comment by terryjreedy** [comment]
Use https://discuss.python.org/c/users/7 to ask about puzzling behaviors.
