### ISSUE TITLE
AttributeError: 'zipimporter' object has no attribute '_files'

### ISSUE THREAD

**Issue by catchyzheng** [python/cpython#121552]
# Bug report

### Bug description:

Hello, 

I encountered this error when running code on python 3.13.

```
for file_path in importer._files:
E       AttributeError: 'zipimporter' object has no attribute '_files'
```
I suspect sth is changed in Lib/zipimport.py, but i am not sure.

Hope someone can provide some guidance, thank you!

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux, macOS

**Comment by Eclips4** [comment]
Hello! Yes, the ``zipimporter.files`` attribute has been removed in version 3.13: #103208. Since this attribute is private and not documented anywhere else, it was removed without any deprecation process.
So, you need to update your code :)
Actually, maybe it would make sense to mention this removal in the changelog, but I'm not sure how many users are using it, since it's a private, undocumented attribute.

**Comment by ZeroIntensity** [comment]
FWIW, the new way to do it is through the new `_get_files()` method instead of `_files`. Note that this is a private API too, though.

**Comment by catchyzheng** [comment]
Thank you! Yes the `_get_files()` works.
