### ISSUE TITLE
Decimal().normalize() produces an incorrect result

### ISSUE THREAD

**Issue by swhare** [python/cpython#121564]
# Bug report

### Bug description:

```python
from decimal mport Decimal
x = 1/Decimal(9)
print((9*x).normalize())
# 0.9999999...
# 1 is expected
print((99*x).normalize())
# 11
# correct!
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
The ``normalize`` method of Decimal instances is used for producing canonical values of an equivalence class: https://docs.python.org/3/library/decimal.html#decimal.Decimal.normalize
It looks like you need a `round` built-in function.

**Comment by swhare** [comment]
My apologies Mr. Podoprigora,

    ... for falsely attributing this issue to the normalize() function.  It really has nothing to do with the normalize() function and everything to do with how the Decimal class is storing or calculating values.  It would not be possible for 99*x to correctly produce 11.000000... unless a either a few extra digits were bring either stored or presumed so that an internal rounding function was triggered to produce the correct result.  The similar case 9*x however, should be handled in the same way so that it produces 1.00000000....  The normalize() function is only knocking off all the trailing zeroes. 

I wish to remind you that you use the Decimal class only when you want to work with numbers in the same way a human would avoiding the errors that creep in from storing a number in base 2.  The way humans do math, 0.999999...=1. 000000...!  Further, I insist that if you have code that produces the correct result most of the time, but not all of the time, you have a bug.  If you have code that requires a round() function as a workaround to handle these weird edge cases, you indeed have a bug.

I continue to insist that this is a bug.  Thank-you nonetheless for taking the time to consider my claim.

Warm regards,

Sean Hare

________________________________

**Comment by mdickinson** [comment]
@swhare

> It would not be possible for 99*x to correctly produce 11.000000... unless a either a few extra digits were bring either stored or presumed [...]

It's entirely possible, and it's exactly what's happening. With `Decimal`, what you see is exactly what you get - there are no hidden or presumed digits.

Longer explanation: the `Decimal` type, by design, cannot store _any_ rational number: it can only store numbers expressible with a finite number of decimal places. `1/9` is not such a number, so when you compute `1/9` using the decimal module:

```python
Python 3.12.4 (main, Jun  8 2024, 04:58:03) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from decimal import Decimal
>>> x = 1 / Decimal(9)
>>> x
Decimal('0.1111111111111111111111111111')
```

then `x` has `exactly the value shown: not 1/9, but what you get after rounding 1/9 to 28 significant digits (the default precision for the `decimal` module). So there are exactly 28 `1`s following the `0.`:

```python
>>> str(x).count("1")
28
```

When you multiply `x` by `99`, the _exact_ result would be `10.9999999999999999999999999989`. However, that has `30` significant digits, so as with all `Decimal` arithmetic operations, the exact result is rounded to the current precision (28 significant digits) using the current rounding mode (round ties to even). The result of that rounding is exactly `11`:

```python
>>> x * 99
Decimal('11.00000000000000000000000000')
```

In contrast, when you multiply `x` by `9`, the exact result would be `0.9999999999999999999999999999`. That has only 28 significant digits, so there's no need to round, and that exact result is returned:

```python
>>> x * 9
Decimal('0.9999999999999999999999999999')
```

So all of the above is operating exactly as expected, as tested, and as specified in the standard that the `decimal` module follows. I'm happy to confirm that there's no bug here.

**Comment by swhare** [comment]
I understand now.  Thank you for explaining it to me.  I'm not entirely satisfied with the answer because I would think it's going to lull other coders into larger errors that they may not be able to easily detect as it did with me, and I don't see any practical purpose in relying on code that will return inconsistent results, but I at least now know why I have to specify some rounding myself.   Thanks again.

Warm regards,

Sean Hare
________________________________
