### ISSUE TITLE
[C API] Add PyBytes_Join() function

### ISSUE THREAD

**Issue by vstinner** [python/cpython#121645]
# Feature or enhancement

Python 3.13 alpha 1 removed the private `_PyBytes_Join(sep, iterable)` function which calls `sep.join(iterable)`.

mypyc uses it. Since we already have `PyUnicode_Join(sep, iterable)`, I propose to add a new `PyBytes_Join()` function.

In practice, it's just about renaming `_PyBytes_Join()` to `PyBytes_Join()`.

### Linked PRs
* gh-121646
* gh-123783

**Comment by vstinner** [comment]
> mypyc uses it.

A code search on PyPI top 7,500 projects found 6 projects using the private `_PyBytes_Join()` function:

* Cython (3.0.9)
* dbnd (1.0.22.9)
* dulwich (0.21.7)
* mod_wsgi (5.0.0)
* mpi4py (3.1.5)
* mypy (1.9.0)

**Comment by vstinner** [comment]
> mypyc uses it

Sorry, I forgot to add a reference to the mypy issue: issue gh-121489.

**Comment by ZeroIntensity** [comment]
Additionally, [many repositories](https://github.com/search?q=_PyBytes_Resize&type=code) use `_PyBytes_Resize` as well. Perhaps that's something that should go public?

**Comment by vstinner** [comment]
> Additionally, many repositories use _PyBytes_Resize as well. Perhaps that's something that should go public?

IMO _PyBytes_Resize() is a bad pattern, it uses a bytes object which is incomplete/inconsistent: see https://github.com/capi-workgroup/api-evolution/issues/36.

Instead, I created https://github.com/python/cpython/issues/121710: [C API] Add PyBytesWriter API.

**Comment by vstinner** [comment]
Implemented by the change https://github.com/python/cpython/commit/3d60dfbe1755e00ab20d0ee81281886be77ad5da.

**Comment by i-l-s-h-a-t** [comment]
Dear @vstinner,

I have an issue during my Python wheel generation on Linux, Python 3.13:
```
      ../numpy/_core/src/common/pythoncapi-compat/pythoncapi_compat.h: In function ‘PyObject* PyBytes_Join(PyObject*, PyObject*)’:
      ../numpy/_core/src/common/pythoncapi-compat/pythoncapi_compat.h:1607:12: error: ‘_PyBytes_Join’ was not declared in this scope; did you mean ‘PyBytes_Join’?
```

My code  has numpy dependency and it uses pybind11 C++ library. I would like then to generate a wheel for it.

Could it be due to [this](https://github.com/python/cpython/commit/3d60dfbe1755e00ab20d0ee81281886be77ad5da) renaming?
There is a check [here](https://github.com/python/pythoncapi-compat/blob/main/pythoncapi_compat.h#L1600) but it checks only Python 3.14, and not 3.13:

<img width="515" height="151" alt="Image" src="https://github.com/user-attachments/assets/f2d4f2b4-ca2a-4d6f-b759-8da5cbf8908f" />

I see there is a backward compatibility was [assumed](https://github.com/python/cpython/commit/3d60dfbe1755e00ab20d0ee81281886be77ad5da#diff-033df8a480e4319295ffc199e3d03e1f967effe19b844754f115a3289139f7a7R38)

<img width="381" height="52" alt="Image" src="https://github.com/user-attachments/assets/9028b3d4-2022-4026-8650-5415bc2d8da5" />

As you can see it doesn't work in my case.

The whole log is here https://pastebin.com/Am07UcZg 
I have this issue only for Python 3.13, only on Linux (docker image python:3.13). I tried to just install numpy and that works there. Looks like for my wheel creation, it does something else which fails. 
And there is no such an issue on other Python versions (3.12 or 3.14) and Windows (Python 3.10-3.14).

I will appreciate you help.

Best,
ilshat

**Comment by vstinner** [comment]
@i-l-s-h-a-t: Interesting bug. It's unrelated to Python, so can you please open an issue at https://github.com/python/pythoncapi-compat/issues? Please include commands on how to reproduce your issue.

**Comment by i-l-s-h-a-t** [comment]
> [@i-l-s-h-a-t](https://github.com/i-l-s-h-a-t): Interesting bug. It's unrelated to Python, so can you please open an issue at https://github.com/python/pythoncapi-compat/issues? Please include commands on how to reproduce your issue.

@vstinner Thank you for your reply. I created an [issue ](https://github.com/python/pythoncapi-compat/issues/163) there.
Although I could not reproduce the issue locally which appears in gitlab CI/CD.
