### ISSUE TITLE
IDLE: Path Browser vertical spacing is too small, causing the text to be cut off

### ISSUE THREAD

**Issue by Wulian233** [python/cpython#122392]
### Bug description:

Noise: @terryjreedy 

The vertical spacing is too small, causing the text to be cut off. I'm not sure if this issue exists on other systems as well. Currently, I may not create a PR to fix it because I haven't found where the related code is and what the cause of the bug is. IDLE is a program with a long history; the folder icons here are very "retro"~~old~~, and the code is quite heavy.

<img width="297" alt="2024-07-29 193916" src="https://github.com/user-attachments/assets/0a335bcf-6572-452e-89b1-ec9fc9285c38">

### Operating systems tested on:

Windows or all

### Linked PRs
* gh-124975
* gh-125061
* gh-125062

**Comment by terryjreedy** [comment]
There is a GH project page for `IDLE issues`.  Once an issue to added to the project on the right sidebar, one can click to open it. By default, IDLE issues is sorted by `Topic`.  These mostly refer a block of menu entries.  For instance,  `File - New File` to `File - Path Browser` constitute the topic `File open`.  There are 4 previous open browser issues.  The main one is #75733, converting the browsers to be based on ttk.Treeview instead of Canvas, as currently in tree.py.   At least some of the enhancements listed at the top of tree.py should be part of or easier with Treeview.

I temporarily fixed browser line spacing a decade ago in  #66818 by increasing tree.py line 202 (first after `def draw`) to `dy = 20`.  The issue reappeared 5 years ago in #81222 on hi-res monitors.  Is this your case?  I closed #81222 in favor of #75733, intending to fix line spacing as part of the conversion.  #81222 has some Treeview test code, though dynamically setting spacing to the monitor seems not trivial.

So browser line spacing is a duplicate issue.  However, since using Treeview is still in the future, I will consider patching tree.py to calculate the line spacing.  Such code might be reusable with Treeview.  Currently the browsers use the same system font as used for the menus, which is not changed by user font selections.  As long as this is true,  spacing could be calculated on startup rather than just for each browser.     My current idea is to write a line, say, 'sys.path' (with descending chars) in a text widget and get the height of the bounding box.  I will do some experiments next.

I would need help with code and review for these issues. How familiar are you with tkinter?  Any experience with ttk styles?

Removing unneeded icons is #69277.  That will definitely be easier with Treeview.  The browser icons are folder.git, minusnode.gif, openfolder.gif, and plusnode.gif in idlelib.Icons.  They fit within 16x16 pixels.  Such files could be replaced if someone 'paints' new ones from scratch, without directly copying from elsewhere, and contributes them.  Do you have anything in mind?  Adding new icons, possibly blank for files and functions might be an alternative to simply removing the python icon.

**Comment by terryjreedy** [comment]
Please copy the following into a file and run it.
```
from tkinter import *
r = Tk()
r.lift()
t = Text(r)
t.pack()
t.insert('1.0','Ãny')
r.update_idletasks()
r.lift()
print(t.bbox('1.0'), t.bbox('1.1'), t.bbox('1.2'))
def Ãnyf(): pass
class Ãnyc(): pass
```
I see (2, 2, 8, 16) (10, 2, 8, 16) (18, 2, 8, 16).  Although the font in the tk window is not the same as the module browser window, the height of Ãny is the same as far as I can tell, and the spacing of 16 + 4 = 20 pixels is more than adequate.  Change dy in your tree.py to the reported height plus a bit and then try module browser on this or other .py file.  I going to repeat with text written on a canvas.

**Comment by Wulian233** [comment]
I see (2, 2, 7, 13) (9, 2, 7, 13) (16, 2, 7, 13). dy=25 is fine for me
<img width="432" alt="2024-07-30 082932" src="https://github.com/user-attachments/assets/1c53dc7d-60b8-4041-b428-c9763737df6e">

> I would need help with code and review for these issues. How familiar are you with tkinter? Any experience with ttk styles?

I've used ttk to create some simple utility GUIs before. They were quite simple, so I didn't use many components. One example (ignore the non-English parts) is [this GitHub project](https://github.com/Wulian233/kubejs-translate). Although the appearance differs from the default tkinter style, that's because I used the sv-ttk module for styling, which is just a ttk/tcl theme. It's entirely written with ttk. 
<img width="386" alt="2024-07-30 084308" src="https://github.com/user-attachments/assets/dce49eb8-2bea-418c-9b59-155033ed3dfc">

I'm very willing to help!

**Comment by terryjreedy** [comment]
Since 13 is shorter than 16, it puzzles me that you need a greater height to avoid overlap.  I did a similar test as above with canvas.create_text and got a height of 17.  But this is only used for extra label text in stackviewer.  The browsers display object text as labels within windows on the canvas.  I believe this is to get event binding (but could be done with canvas texts).  Try this code.
```
from tkinter import *
r = Tk()
r.lift()
c = Canvas(r)
c.pack()
l = Label(c, text='Ãny', bd=0, padx=2, pady=2)
l2 = Label(c, text='Ãny', bd=0, padx=2, pady=2)
w = c.create_window(2, 2, anchor=NW, window=l)
c.create_window(2, 22, anchor=NW, window=l2)  # One widget can only be in one window.
r.update_idletasks()
r.lift()
print(c.bbox(w))
```
I get (2, 2, 27, 21).  I should really have dy = 21 = 17 + 4 padding, set to work on Windows.  The 1 pixel overlap is visible with careful observation of selection highlighting.  What is your OS, what is printed, and do you see overlap with this code with dy=20?

**Comment by Wulian233** [comment]
I get (2, 2, 27, 23). Win10 22H2 laptop: 1920x1080 150% Dpi
### 20
<img width="297" alt="20" src="https://github.com/user-attachments/assets/6d442653-952b-4d89-8396-d9b527cec607">
### 21
<img width="297" alt="21" src="https://github.com/user-attachments/assets/b25e47a0-e8ed-47c1-aa90-c511d133e778">
### 25
<img width="297" alt="25" src="https://github.com/user-attachments/assets/b5582f3d-f0d4-4ba7-aede-a08f96e0c144">

**Comment by terryjreedy** [comment]
This is making more sense.  How about with 23?

**Comment by Wulian233** [comment]
### 23
<img width="297" alt="23" src="https://github.com/user-attachments/assets/c128710a-381a-4961-a6fa-d476b934c7d3">

**Comment by terryjreedy** [comment]
Thanks.  The bounding box height looks like it will work.  I am thinking of the best way to get it.

**Comment by Xiaokang2022** [comment]
Based on the above discussion, after I looked at the source code and found that we can set the size of `dy` by calculating the height of the first line.

This value is not used in the first row, so we can set its initial value to `0` for later judgment. After the first line is drawn, taking this height and assigning it to `dy` will solve the problem.

I've created a [PR](https://github.com/python/cpython/pull/124975) to fix this, it should help.

**Comment by Xiaokang2022** [comment]
In the PR, I tested it with my Win10 laptop (1920x1080 150%), here I tested it with my Win11 laptop (2560x1600 150%), and it looks like this:

<img width="318" alt="2024-10-05-01-18-47" src="https://github.com/user-attachments/assets/35055926-e3c2-40ac-b3b9-7c189d1ee505">

**Comment by terryjreedy** [comment]
After my last comment, I did an experiment very similar to the PR, but was not satisfied.  I decided to try using ttk.Treeview and let ttk do the spacing.  I got as far as adding top-level items, with good result, before I needed to replace my system.  I now have a 4k monitor and see the problem this issue is about; hence I can test fixes.  Since I do not expect to have a complete replacement ready before the 3.14.0a1 release in, perhaps, 10 days, I will merge Xiaokang's first PR if requested changes are made and it then gets enough testing.  Not allowing spacing to be reduced below the current value should make it fairly safe.

**Comment by Xiaokang2022** [comment]
I've done revising it, but I'm not sure if this is what you meant.

**Comment by Xiaokang2022** [comment]
Because the results weren't perfect on my computer. There are still some very small overlaps.

<img width="318" alt="2024-10-05-03-27-46" src="https://github.com/user-attachments/assets/734c593e-0577-43d9-9018-e35fc531583e">

**Comment by Wulian233** [comment]
LGTM. 
![屏幕截图 2024-10-05 110714](https://github.com/user-attachments/assets/1eb972a2-9162-47c4-82c5-15b40021fe29)
Also I've found that: for example, `__init__.py` loses the `__ __`, showing `init`. Is this a bug or a feature? If it's a bug, we can create a new issue

**Comment by Xiaokang2022** [comment]
No, I think it's just that the underline isn't visible because of the occlusion.

**Comment by terryjreedy** [comment]
Underscores, as their name implies, are at least 2 pixels down from the main bottom line of the text.  They are visible for me with the patch.
