### ISSUE TITLE
Code to detect code errors

### ISSUE THREAD

**Issue by liuzhongyi2** [python/cpython#122382]
# Bug report

### Bug description:

Code to detect code errors
```python
import ast

def check_syntax(code):
    try:
        # 使用ast.parse尝试解析代码
        ast.parse(code)
        print("代码语法正确")
    except SyntaxError as e:
        print(f"语法错误: {e}")

# 示例代码
code_to_check = """
prin("hello")
"""

check_syntax(code_to_check)
```

It said there was no mistake.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by Wulian233** [comment]
English should be used here

His code comments are written in Chinese, let me translate them

```python
import ast

def check_syntax(code):
    try:
        # Use ast.parse to try parsing the code
        ast.parse(code)
        print("correct")
    except SyntaxError as e:
        print(f"Syntax error: {e}")

# example code
code_to_check = """
prin("hello")
"""

check_syntax(code_to_check)
```

**Comment by Wulian233** [comment]
Not a cpython bug, is your bug

Your code example contains a spelling mistake, but your code checker did not detect it. This is because `ast.parse` can only detect syntax errors, not spelling or runtime errors.

In your example code, `prin("hello")` is a spelling mistake, but syntactically it is correct, so `ast.parse` will not raise a `SyntaxError`. However, if you wrote code with a syntax error, like a missing parenthesis or other syntax issues, `ast.parse` would detect it and raise a `SyntaxError`.

If you need to detect runtime errors such as spelling mistakes, you need to execute the code and catch exceptions. Here is an example to demonstrate how to do that:

```python
import ast

def check_syntax(code):
    try:
        # Attempt to parse the code using ast.parse
        ast.parse(code)
        print("The code syntax is correct")
    except SyntaxError as e:
        print(f"Syntax error: {e}")

def execute_code(code):
    try:
        exec(code)
    except Exception as e:
        print(f"Runtime error: {e}")

# Example code
code_to_check = """
prin("hello")
"""

check_syntax(code_to_check)
execute_code(code_to_check)
```

In this example, the `check_syntax` function is still used to detect syntax errors, while the `execute_code` function is used to execute the code and catch runtime errors. Runtime errors will catch issues like spelling mistakes that occur when the code is executed.

**Comment by JelleZijlstra** [comment]
You can also use a linter (e.g., flake8, pylint, ruff) or a type checker (e.g., mypy, pyright) to find some categories of errors without running code.
