### ISSUE TITLE
[3.13.0b4] f-string with precision specifier has `format_spec` of `Constant`, not `JoinedStr`

### ISSUE THREAD

**Issue by jacobtylerwalls** [python/cpython#122300]
# Bug report

### Bug description:

```py
Python 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
>>> import ast
>>> ast.parse("f'{e:.3}'").body[0].value.values[0].format_spec
<ast.JoinedStr object at 0x1002aa050>
```
```py
Python 3.13.0b4 (v3.13.0b4:567c38b4eb, Jul 18 2024, 07:28:29) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
>>> import ast
>>> ast.parse("f'{e:.3}'").body[0].value.values[0].format_spec
<ast.Constant object at 0x104af45d0>
```

[Docs](https://docs.python.org/3/library/ast.html#ast.FormattedValue) say `FormattedValue.format_spec` is a `JoinedStr`.

Reported downstream in pylint-dev/astroid#2478

Not present in 3.13.0b3

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux, macOS

### Linked PRs
* gh-122308
* gh-122363
* gh-122364

**Comment by Eclips4** [comment]
Bisected to c46d64e0
cc @pablogsal

**Comment by jacobtylerwalls** [comment]
Thanks for the bisect. That PR updated the docs for `ast.JoinedStr` to show this as the new expected result, so maybe we just need a docs update for `ast.FormattedValue`?

**Comment by pablogsal** [comment]
> Thanks for the bisect. That PR updated the docs for `ast.JoinedStr` to show this as the new expected result, so maybe we just need a docs update for `ast.FormattedValue`?

Note that the docs are not prescriptive over what the shape of the AST will be, it's just an example. The actual shape of the AST can still change due to bug fixes and grammar extensions so I would not recommend looking at those docs as a prescription with any backwards compatibility guarantees.

Being said that I can try to investigate how difficult it's to preserve this because I understand how annoying this can be downstream if you don't have anything you can match against and was like that for several versions.

**Comment by pablogsal** [comment]
I think https://github.com/python/cpython/pull/122308 will do the trick

**Comment by penguinpee** [comment]
Yep. #122308 fixes the test regressions in `rope` and `astor` that I reported in #122307. Thanks!

**Comment by pablogsal** [comment]
Will backport this soon

**Comment by pablogsal** [comment]
All done!
