### ISSUE TITLE
`co_varnames` now incorrectly includes iteration variables

### ISSUE THREAD

**Issue by ybungalobill** [python/cpython#122532]
# Bug report

### Bug description:

As of python 3.12.3, `co_varnames` includes the iteration variables from within list comprehension expressions. This is a breaking change since earlier versions of python (e.g. 3.11.9), where `co_varnames` included local variables only (as per documentation):

```python
def f():
    [1 for i in range(2)]

# 3.12.3: ('i',)
# 3.11.9: ()
print(f.__code__.co_varnames)
```

To the best of my knowledge `i` here isn't a function-local variable in python 3x anymore. Which also suggests another oddity with the new behavior: under the new interpretation there can be two "local" variables with the same name, but only one will be reported:

```python
def f():
    i = 42
    [1 for i in range(2)]
    return i

print(f.__code__.co_varnames)  # ('i',)
print(f())  # 42
```

### CPython versions tested on:

3.9, 3.11, 3.12

### Operating systems tested on:

Linux

**Comment by sobolevn** [comment]
cc @carljm

**Comment by carljm** [comment]
Thanks for the repor

Since PEP 709 (comprehension inlining) the comprehension iteration variable now technically is again a local variable. This is an implementation detail, and I don't think there are backward-compatibility guarantees on the presence or absence of a name in `co_varnames`.

Technically it might be possible to remove this name from `co_varnames` (not sure, would have to look into the details), but I'm not sure if this would be a net positive change; at this level of introspection it may be best not to attempt to hide the actual implementation.

Perhaps you can say more about your use case where this is a problem?

**Comment by ybungalobill** [comment]
@carljm Our use-case is in a python static analyzer that piggy-backed on `co_varnames` to determine scoping of names in the AST. Without it we would need to re-implement python name resolution, it seems.

**Comment by carljm** [comment]
The more conventional tool for this would be the `symtable` module rather than code objects (if you have code objects handy, it calls into question the staticness of the "static analyzer"!). But you'll find the `symtable` module also now reflects the underlying implementation and shows the comprehension iteration variable as a local in the outer scope. I think it provides more additional metadata about each name that might make it easier to handle this as a special case, though.

It's already quite obvious in a number of ways from looking at code objects that comprehensions are inlined: there's no child code object with its own `co_varnames`, the bytecode doesn't create and call a function, etc. So it wouldn't make sense for `co_varnames` to be inconsistent with the rest of the code object.

I think "would need to re-implement Python name resolution" is an over-statement, but it is true that comprehension inlining will require _some_ special-cased handling in your tool, if you are using `symtable` or code objects to help your tool understand Python scoping rules. It seems like this special-case handling should be pretty feasible, though, given that your tool has access to the AST as well, and can see the presence of the comprehensions.

**Comment by JelleZijlstra** [comment]
Code objects are [documented](https://docs.python.org/3/reference/datamodel.html#internal-types) in a section that says "Their definitions may change with future versions of the interpreter". As such, we don't provide guarantees about the exact contents of code objects across versions.

As mentioned, the symtable is likely a better fit for your needs.
