### ISSUE TITLE
UnInstalling python launcher leading to windows crash

### ISSUE THREAD

**Issue by ghost** [python/cpython#122655]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```

Hey guys, I wanted to unInstall python launcher today and the moment I unInstalled it, and my screen went white, When I checked again it asked me to close windows, What I did is simple: Going to the control panel, choosing the unInstall tab, unInstalling python launcher and than it happens. to resolve it I pressed Ctrl + shift + esc it leads me to the task manager, from there is clicked on new task, typed: explorer.exe and everything went to normal

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by eryksun** [comment]
3.11 only gets security updates at this point. Can you try to replicate the issue with the launcher from 3.12? The launcher installs a shell extension that loads in Explorer in order to support drag and drop on a script. After installing the launcher, try dragging and dropping a file onto a Python script in Explorer, and then try to uninstall the launcher. For now, I'm marking this issue as pending while waiting for additional feedback or additional reports.

**Comment by TerseSmile10428** [comment]
Sure, I will try in a moment.

**Comment by TerseSmile10428** [comment]
Hey, is 3.12.3 good? If yes I would try it right now

**Comment by eryksun** [comment]
It would be, but the latest stable release is 3.12.4.

**Comment by encukou** [comment]
@TerseSmile10428, were you able to try this on 3.12?

**Comment by TerseSmile10428** [comment]
Hey, No. It only happened to me one time with python 3.11

בתאריך יום ב׳, 19 באוג׳ 2024, 15:00, מאת Petr Viktorin ‏<
***@***.***>:

**Comment by mmannin2** [comment]
How was this fixed? I am having the same issue and my entire screen is white.

**Comment by zooba** [comment]
It was not fixed, it was closed because there isn't enough information for us to do anything here. Installation in particular is mostly provided by Windows - all we really do is list the files - so we really do need logs and/or reproduction steps that work across multiple machines.
