### ISSUE TITLE
Inconsistent Results for **cmath.atan** and **numpy.arctan** with Specific Complex Inputs

### ISSUE THREAD

**Issue by HP-Li** [python/cpython#122615]
# Bug report

### Bug description:

**Description:**
I have encountered an issue with the cmath.atan function (and numpy.arctan which exhibits the same behavior) when calculating the inverse tangent of specific complex numbers. The results do not seem to be consistent with expectations. Below is a minimal example demonstrating the issue:
```python
import cmath as cma

def test(a):
    res = 10 / (a * 1j)
    return res

print(test(1.4))  # Output: -7.142857142857143j
print(cma.atan(test(1.4)))  # Output: (1.5707963267948966 - 0.14092557607049386j)
print(cma.atan(-7.142857142857143j))  # Output: (-1.5707963267948966 - 0.14092557607049386j)
```
**Actual Results:**

    The result of test(1.4) is -7.142857142857143j.
    The result of cmath.atan(test(1.4)) is (1.5707963267948966 - 0.14092557607049386j).
    The result of cmath.atan(-7.142857142857143j) is (-1.5707963267948966 - 0.14092557607049386j).

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by mdickinson** [comment]
Thanks for the report. This is expected behaviour. The input value that you're `atan` lies exactly on the branch cut, and the sign of the zero real part is used to determine which side of the branch cut the input lies on for computation purposes. The two inputs you're comparing have different signs on the real part, hence the difference in the output.

```python
>>> print(test(1.4))
-7.142857142857143j
>>> -7.142857142857143j
(-0-7.142857142857143j)
```
