### ISSUE TITLE
argparse can not work for path ending with slash on windows

### ISSUE THREAD

**Issue by NewUserHa** [python/cpython#122919]
# Bug report

### Bug description:

```python
import argparse
import sys


parser = argparse.ArgumentParser()
parser.add_argument("--model")
parser.add_argument("--temperature")
parser.add_argument("--temperature2")

args = parser.parse_args()
print('11',args)
print('22',args.model)
print(sys.argv)
input()
```
```cmd
"test.py" --model "E:\test\model-medium\" --temperature 1 --temperature2 1
11 Namespace(model='E:\\test\\model-medium" --temperature 1 --temperature2 1', temperature=None, temperature2=None)
22 E:\test\model-medium" --temperature 1 --temperature2 1
['E:\\Sandbox\\AI whisper\\New Python File.py', '--model', 'E:\\test\\model-medium" --temperature 1 --temperature2 1']
```

windows path can be able to end with slash

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by eryksun** [comment]
The `\"` in the command-line represents a literal double quote character. Thus, since there's no closing quote, the last argument in `sys.argv` is the rest of the command line: `'E:\\test\\model-medium" --temperature 1 --temperature2 1'`.

Issues about command-line parsing come up from time to time. Perhaps the documentation needs to prominently feature a link to the Windows C runtime library's page that details the rules user for [parsing C command-line arguments](https://learn.microsoft.com/en-us/cpp/c-language/parsing-c-command-line-arguments). The relevant rule in this case is '[a] double quote mark preceded by a backslash (\\") is interpreted as a literal double quote mark (")'.

**Comment by serhiy-storchaka** [comment]
This is not related to `argparse`, but to the way the command line is parsed by the C runtime. It is not even specific for Python, the behavior should be the same for most program.

I do not think we should do anything about this. This is a problem outside Python.

**Comment by ChrisDenton** [comment]
The issue is with the shell. This is fixed in [Powershell 7](https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4) but with earlier shells you'll need to workaround it (e.g. by doubling the trailing slash).

**Comment by NewUserHa** [comment]
the issue happens on cmd, not powershell

**Comment by ChrisDenton** [comment]
Yes, that a shell too. Only the latest version of Powershell fixes the issue. Which needs to be installed separately.

**Comment by NewUserHa** [comment]
tested, `flag` of golang also has this issue on cmd

**Comment by ChrisDenton** [comment]
Well it does work in Powershell 7 and the issue is consistent across most language runtimes (I tried C++, C#, Go, Python, Rust).

Python could indeed do parsing differently then the CRT but then it would be out of step with almost everything else, which I think would cause more issues than it would solve. E.g. it would be a pain when calling Python from other applications that would need to special case calling Python. As you note, this is already a problem with cmd which does have to be treated special.

**Comment by NewUserHa** [comment]
https://www.github.com/golang/go/issues/16131 on github/golang a related github issue found

**Comment by eryksun** [comment]
> Well it does work in Powershell 7 and the issue is consistent across most language runtimes (I tried C++, C#, Go, Python, Rust).

@ChrisDenton, that's true. PowerShell rewrites the command-line string from its own syntax to that of the C runtime, under the reasonable assumption that an application uses the C runtime's `argv` array or `CommandLineToArgvW()`. For example, in some cases it escapes backslashes (e.g. use `"C:\Program Files\\"` instead of `"C:\Program Files\"`), and in some cases it simply removes unnecessary quotes (e.g. use `C:\` instead of `"C:\\"`).

The CMD shell makes no attempt to rewrite the command-line like that, which is good in some ways but overall it's probably better to encourage applications to adopt uniform command-line parsing that matches the C runtime (e.g. Cygwin apps use POSIX shell rules, which can be annoying).

> Python could indeed do parsing differently then the CRT but then it would be out of step with almost everything else

I was only pointing at that the behavior is implemented within the Python process, not a shell, according to our (mostly default) decision to use the C runtime's `argv` array. I didn't suggest that we actually change anything about this, and I don't think that would be reasonable for many reasons.

In my initial post, I did suggest that we should consider adding a prominently-featured link to the relevant [C runtime doc](https://learn.microsoft.com/en-us/cpp/c-language/parsing-c-command-line-arguments) in the using Python on Windows section of our documentation, and, come to think of it, maybe also notes in the documentation of `sys.argv` and `argparse`. It's not the first time I've come across misunderstandings about how command-line arguments are handled on Windows. I'd wager that most users have no idea what the rules are, and Microsoft doesn't go out of its way to describe this anywhere that's friendly and accessible. It's buried in the documentation of the C runtime library.
