### ISSUE TITLE
Index value is always 0 when list in the values are same.

### ISSUE THREAD

**Issue by kumaranssekar21** [python/cpython#123218]
# Bug report

### Bug description:

```python
list_same = [1, 2, 3]
for i in list_same:
    print(list_same.index(i), i)
```
out: 
0 1
1 2
2 3

```python
list_same = [1, 1, 1]
for i in list_same:
    print(list_same.index(i), i)**
```
out:
0 1
0 1
0 1

### CPython versions tested on:

3.9

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
There's no bug because `.index` returns a index of first occurence of `x in s`: https://docs.python.org/3/library/stdtypes.html#common-sequence-operations

Additionally, this repository is intended as a CPython bug tracker. Please, ask python-related questions there: https://discuss.python.org/c/users/7
