### ISSUE TITLE
have you met confused result of round() or np.round() function ?

### ISSUE THREAD

**Issue by zywvvd** [python/cpython#123253]
# Bug report

### Bug description:

```python
# Add a code block here, if required
import numpy as np
import decimal
from decimal import Decimal


if __name__ == '__main__':
    for i in range(10):
        value_str = '5.' + str(i) + '55555'
        value = float(value_str)
        print(round(value, 5))

    print('------------------------')

    for i in range(10):
        value_str = '5.' + str(i) + '55555'
        value = float(value_str)
        print(np.round(value, 5))

    print('------------------------')

    decimal.getcontext().prec = 6
    quant = decimal.Decimal('0.00001')
    for i in range(10):
        value_str = '5.' + str(i) + '55555'
        value = Decimal(value_str)
        rounded_value = value.quantize(quant)
        print(rounded_value)
    pass
```

my python is in version 3.10.12
under ubuntu 22.04

the output in my terminal is :

```
5.05556
5.15555
5.25556
5.35555
5.45556
5.55556
5.65555
5.75556
5.85555
5.95556
------------------------
5.05556
5.15555
5.25556
5.35556
5.45556
5.55556
5.65556
5.75556
5.85556
5.95556
------------------------
5.05556
5.15556
5.25556
5.35556
5.45556
5.55556
5.65556
5.75556
5.85556
5.95556
```

is there any reasonable explanation for these results?

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
This is documented in https://numpy.org/doc/stable/reference/generated/numpy.round.html:

> Alternatively, Python’s builtin [round](https://numpy.org/doc/stable/reference/generated/numpy.round.html#numpy.round) function uses a more accurate but slower algorithm for 64-bit floating point values.

The decimal module uses by default ROUND_HALF_EVEN rounding mode, and exact representation since you asked for 5 fractional digits.

For the native `round`, this is because of float limitations: https://docs.python.org/3/tutorial/floatingpoint.html#tut-fp-issues.

For instance, `5.155555` is actually:

```pycon
>>> format(5.155555, '.17f')
'5.15555499999999967'
``` 

Thus, ``round(5.155555, 5)`` is actually `round(5.15555499999999967, 5) == 5.15555`. On the other hand, `Decimal(5.155555)` is really (mathematically) 5.155555, so when you round it up to 5 fractional digits, with ROUND_HALF_EVEN mode, you'll round the last "55" to "56", whence the result.

Closing as a `not an issue`.
