### ISSUE TITLE
Add datetimewalker function to the datetime module

### ISSUE THREAD

**Issue by DarjaGFX** [python/cpython#123537]
# Feature or enhancement

### Proposal:

The `datetimewalker` function (or any other name that might be more appropriate) would provide users with the ability to generate a sequence of datetime objects between a specified start and end date, using a given `timedelta` interval.

Example Usage:
```python
from datetime import datetime, timedelta, datetimewalker

start = datetime(2024, 8, 25)
end = datetime(2024, 8, 30)
delta = timedelta(days=1)

for i in datetimewalker(start, end, delta):
    print(i)
```
While similar functionality is available through third-party packages like `numpy`, `pandas`, and `more_itertools`, I believe this feature is simple and fundamental enough to warrant inclusion directly in the standard library. This would make it more accessible for users without requiring the installation of additional packages for such a basic task.

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

[Discourse](https://discuss.python.org/t/proposal-to-add-a-datetimewalker-function-to-the-datetime-module/62454)

**Comment by Wulian233** [comment]
I saw this function in the discussion, remember to add the module documentation for the function and whatsnew/3.14.rst :)

**Comment by nineteendo** [comment]
There's no consensus on Discourse. I suggest to close this for the time being.

**Comment by picnixz** [comment]
By reading the Discourse discussion, I agree that this proposal is still not yet ready. There are appear to be questions that need to be answered. I personally think that `more_itertools` is a sufficient "small" package to be included as a dependency and thus I'd like the OP to continue on Discourse for now. What you could however do to keep the issue opened is to suggest an implementation. Be aware that the implementation must be in Python **and** in C, so this could make the implementation not-that-simple at the end. Otherwise, I suggest closing the issue for now.

**Comment by ericvsmith** [comment]
I'm going to close this, pending a consensus on d.p.o. It can always be re-opened.
