### ISSUE TITLE
Hosted documentation has not been updated in a couple of days

### ISSUE THREAD

**Issue by aphedges** [python/cpython#123876]
# Documentation

I tried viewing the [Changelog](https://docs.python.org/3.12/whatsnew/changelog.html) to see what was included in the Python 3.12.6 release, and I noticed the page states "Last updated on Sep 07, 2024 (13:49 UTC)". I checked several other pages on the 3.12 documentation site, and they all have the same date. I checked the 3.8-3.10 docs, and they have all been built within the past day, but 3.12-3.14 have not been updated in a couple of days and are missing changelog updates. The 3.11 docs are also missing changelog updates, but they haven't been updated since April, even though there have been two releases since then.

This is similar to #122868, but it appears to be different enough that I have created a new issue.

**Comment by Eclips4** [comment]
cc @hugovk

**Comment by hugovk** [comment]
I was just looking into this.

The reason is we released six versions of Python on Friday:

https://discuss.python.org/t/python-3-13-0rc2-3-12-6-3-11-10-3-10-15-3-9-20-and-3-8-20-are-now-available/63161

The docs build server is now working through all of these and rebuilding docs for them all, plus up to 12 translations each. For many of these it includes building PDFs, which are very slow.

It's recently been taking about 40 hours to build 3.12-3.14 and their translations, so it will take much longer to do the whole batch of seven versions.

For example, recently built:

* https://docs.python.org/zh-cn/3.11/ - "最后更新于 Sep 09, 2024 (16:11 UTC)"
* https://docs.python.org/uk/3.11/ - "Востаннє оновлено Sep 09, 2024 (18:01 UTC)"

So let's check back in a few days!

PS See https://github.com/python/docsbuild-scripts/issues/190 for efforts to improve the docs build times.

**Comment by ned-deily** [comment]
Also the untranslated (English-only) versions of the documentation sets as they existed at the time of each release should always be available from the [Python Documentation by Version](https://www.python.org/doc/versions/) page on python.org.

**Comment by aphedges** [comment]
I can confirm that all of the documentation has been rebuilt, so I'm closing this issue. There isn't a bug, just slow builds.
