### ISSUE TITLE
Request for a set of function tool for debugging

### ISSUE THREAD

**Issue by dongrixinyu** [python/cpython#123993]
# Feature or enhancement

### Proposal:

I am using VSCode to debug CPython source codes. And I encountered with many cases where many `PyObject*` can not be viewed through the VARIABLES screen as below.

As this picture shows, the variable locals is a `PyDictObject*`, I still have no idea what specific object in this variable. So, how could I check the infomation inside the Python Objects like dict, list, set, int, etc. when debugging.

For example, I know that using `PyBytes_AsString` can check the bytes info. So what about others?

![image](https://github.com/user-attachments/assets/e14c75b7-1255-4b5a-99ac-914463aaa702)

Is it nessesary to designed a set of funtions to show infos inside Python Objects?

### Has this already been discussed elsewhere?

No response given

**Comment by TeamSpen210** [comment]
You'll need something specific to Visual Studio Code to show in your UI, I don't know which exact extensions you're using. Though it seems it's using gdb, and I do know CPython has [builtin integration](https://docs.python.org/3/howto/gdb_helpers.html) with that.

**Comment by gaogaotiantian** [comment]
I think this issue covers a lot of issues and I'm not sure if this should be discussed here, instead of [discuss.python.org](https://discuss.python.org). If you are asking if there's a function to list the objects in a `PyDictObject*`, there is - all the [C APIs](https://docs.python.org/3/c-api/dict.html) starting with `PyDict_`. If there's a generic function to list all objects inside a container? Well maps and sequenses are obviously different, I don't believe there could be a generic function to list everyting in an container (for all the builtin containers, you already have the tools).

However, it seems like you want the information in VSCode, that's a completely different issue. You need to ask whoever wrote the language server of VSCode to support this. Also, things are actually complicated here because from VSCode's perspective, you are just debugging a C program (CPython is just a C program), it won't know it's CPython so it can do some customizations on displays. It will just show what it understands from C aspects - that's all the pointers listed. So you probably need another plugin to customize your language server when you are debugging CPython - I don't think anyone in CPython team is working on that and it's difficult for me to imaging that would be something we will do in a foreseeable future.

**Comment by terryjreedy** [comment]
This python/cpython tracker is for discussing changes to the python/cpython repository.  We ask that non-trivial enhancements first be discussed and fleshed out on the Ideas channel of discuss.python.org.  Help using python, including with other software, should be asked on the help channel.
