### ISSUE TITLE
Document `Annotated.__origin__`

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#124120]
The `typing` module docs cover using `Annotated.__metadata__` to retrieve the annotations, but they do not currently cover the use of `Annotated.__origin__` to retrieve the underlying type hint that is being annotated.

```
>>> from typing import Annotated
>>> Annotated[int, ""].__metadata__
('',)
>>> Annotated[int, ""].__origin__
<class 'int'>
```

### Linked PRs
* gh-124125
* gh-124416
* gh-124417

**Comment by JelleZijlstra** [comment]
You should not use this directly, but use `typing.get_origin` instead. However, we could document this explicitly.

**Comment by JelleZijlstra** [comment]
Actually, looking at the code some more this is not true. For some reason there is a special case where `.__origin__` and `get_origin()` (as well as `__args__` and `get_args()`) are not aligned for Annotated.

```
>>> a = Annotated[int, "x"]
>>> a.__origin__
<class 'int'>
>>> a.__args__
(<class 'int'>,)
>>> typing.get_origin(a)
<class 'typing.Annotated'>
>>> typing.get_args(a)
(<class 'int'>, 'x')
```

This aligns with the documentation, which promises that for `X[Y, ...]`, `get_origin()` will return `X`. However, it is confusing that it does not also align with the `__origin_` attribute.

Since `__origin__` is otherwise undocumented, it's probably best to document it specifically for `Annotated` as @ncoghlan originally suggested.

**Comment by sobolevn** [comment]
I made this mistake in the first version of https://github.com/python/cpython/pull/124125

But, then I realized the same thing as in https://github.com/python/cpython/issues/124120#issuecomment-2352997878

Why? Because of these two lines: https://github.com/python/cpython/blob/9aa1f60e2dedd8a67c42fb4f4c56858b6ba5b947/Lib/typing.py#L2507-L2508

I think that it makes sense:
> Get the unsubscripted version of a type.

So, `Annotated` is the unsubscripted version of a type. And any `T` wrapped by it is just the first type arg.

**Comment by ncoghlan** [comment]
Backports have been merged, so marking this as complete. Thanks, folks!
