### ISSUE TITLE
About `compileall.py` error exit code

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#124333]
# Bug report

### Bug description:

This thread continues the discussion of https://github.com/python/cpython/issues/88621.

I went through the compileall source code, and it blew my mind, but not in a good way. The indentation is all over the place, and I'm not sure what the heck is going on with the `success` variable. I’m thinking about refactoring it. Maybe it's a bit much work, but please give me some time if you can.

You know, the confusion with the execution state is really just because of the mess with the success variable.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

**Comment by picnixz** [comment]
The indentation looks quite standard to me (but it's a personal matter I think). However, nothing seems to warrant a refactorization (and we don't accept cosmetic PRs). 

The `success` variable is a boolean indicating whether the main procedure succeeded or not, and it is only set to False when something went wrong. However, POSIX convention for program exit codes dictates that 0 is for success and anything else is for an error (you have only a single case of a success but many possibilities of having an error). So, `exit_status = int(not main())` simply converts `False` into `1` and `True` into `0`.

We could have directly returned the exit code by main(), but it's easier to return True/False at the Python level to indicate whether something went wrong or not rather than returning an integer representing a program exit code.

Closing as a `non-issue`.
