### ISSUE TITLE
How to convert annotations to `Format.SOURCE` in `__annotate__`?

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#124412]
# Feature or enhancement

Let's say you have a dict of some custom annotations like I have in https://github.com/python/cpython/pull/122262

How users are expected to convert say an annotation dict of `{'user': CustomUser[AuthToken], 'auth_callback': Callable[[CustomUser[T]], T]}` to string?

There are several ways right now:
1. `repr` for simple types, which might not work for complex ones
2. https://github.com/python/cpython/blob/536bc8a806008fff4880ad11ddc189e4847d0255/Lib/annotationlib.py#L466-L501 but, it requires complex `annotate` object
3. https://github.com/python/cpython/blob/536bc8a806008fff4880ad11ddc189e4847d0255/Lib/typing.py#L2955-L2956 but it is a private API

I propose adding a public and documented API for that.

### Linked PRs
* gh-124551

**Comment by JelleZijlstra** [comment]
The use cases for this would be cases where types get provided outside annotations (e.g., with the functional syntax for `NamedTuple` and `TypedDict`, and with `make_dataclass`), and you want the `__annotate__` method to support the SOURCE format.

The implementation is `repr()` for most cases, but for types we want the fully qualified name instead of `<type 'int'>`, and there are a few other special cases. Currently we have `typing._convert_to_source`, which takes an annotations dict and uses `typing._type_repr` to repr each annotation.

Since we already have use cases from two standard library modules (typing and dataclasses), I think it makes sense to add something to `annotationlib`. I would suggest:
- `annotationlib.repr_annotations(dict)`, similar to the current `typing._convert_source`
- `annotationlib.repr_type(type)`, which works like `typing._type_repr` but without the special case for tuples

**Comment by sobolevn** [comment]
I want to investigate on this feature, because I still have a limited understanding of `__annotate__` and all of it corner-cases. 

Will probably work on this tomorrow 👍

**Comment by JelleZijlstra** [comment]
Thanks! We'll also want to add the new functions to PEP 749.

**Comment by JelleZijlstra** [comment]
We also need this in annotationlib itself, for the edge case where a user-created object has `__annotations__` but not `__annotate__`. Currently, in that case SOURCE returns non-strings:

```
>>> class X:
...     @property
...     def __annotations__(self):
...         return {"x": int}
...         
>>> x = X()
>>> import annotationlib
>>> annotationlib.get_annotations(x, format=annotationlib.Format.SOURCE)
{'x': <class 'int'>}
```

I think the most reasonable behavior for this case is to return `{'x': 'int'}`.

**Comment by larryhastings** [comment]
My initial reaction is, this seems like _a_ least-worst option, and it may even be _the_ least-worst option.  I'd like to marinate on it further.  I won't mind too much if you go ahead and merge without my blessing--as long as you don't mind me retroactively pushing back if I (eventually) arrive at some other conclusion.

**Comment by larryhastings** [comment]
I will say, shenanigans like this are an argument against calling this format `SOURCE`.

**Comment by sobolevn** [comment]
@JelleZijlstra can this be closed now? Sorry, I was not quick enough to send a PR :( It was only partially ready yesterday, due to some other work.

**Comment by JelleZijlstra** [comment]
Let's leave it open for a while to allow Larry to ruminate.

**Comment by larryhastings** [comment]
Jelle has convinced himself that we should change the name away from `SOURCE`, I think he preferred `STRINGS` which is fine.

It's a day later and this approach seems like a good idea.  Ship it!  We can always regret it later.

**Comment by JelleZijlstra** [comment]
To be precise I propose `STRING`, since the other formats are also in the singular.

**Comment by larryhastings** [comment]
`STRING` is fine by me.  My only counter-proposal is `TEXT`, which is also sufficiently singular.  I don't have a strong opinion about it either way; I don't think `TEXT` does any better job of conveying the intended semantics of the format.
