### ISSUE TITLE
[CVE-2024-9287] `venv` activation scripts do not quote strings properly

### ISSUE THREAD

**Issue by y5c4l3** [python/cpython#124651]
# Bug report

### Bug description:

Crafted paths break the script templates:

```console
envname='";uname -a;"'
mkdir "$envname"
cd "$envname"
python3 -m venv .
. ./bin/activate
```

```
Linux archlinux 6.10.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Mon, 19 Aug 2024 17:02:39 +0000 x86_64 GNU/Linux
```

Like pypa/virtualenv#2768 the execution path itself is low-risk, but it enables many potential downstream attack vectors. Downstream projects that automatically initialize and activate `venv` at a controllable path (e.g. read from repo configuration file) could execute unexpected commands.

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-124712
* gh-125813
* gh-125947
* gh-126185
* gh-126269
* gh-126300
* gh-126301

**Comment by sethmlarson** [comment]
Hey @y5c4l3, thanks for reporting this. We're going to treat this as a low-risk security issue. You or anyone else can submit a fix normally. If you have questions about this, send an email to security@python.org.

**Comment by y5c4l3** [comment]
@sethmlarson Thanks for the reply! Could you please help me with a code review for this PR as well as #124155? The code owner for `venv` seems to be unavailable recently.

**Comment by gpshead** [comment]
can we keep this open until all of the security branch backports are done?

**Comment by vstinner** [comment]
I close the issue. The fix was applied to all branches.

**Comment by YigitElma** [comment]
Hello!

I am part of a team that uses Github's cache to store virtual environments for our CI. Our routine was working fine but for the last 2 days, I have noticed that sometimes actions that use Python `3.11` and `3.12` fail. I couldn't find any other major change that might affect it. Then, I found this change that is introduced in Python `3.11.11` and `3.12.8` recently.

My problem is, the workflow that creates the cached virtual environment and other workflows that use that cache sometimes operate with different Python versions e.g. `3.12.7` and `3.12.8` (this is probably due to some Github runner difference). When that is the case, I cannot activate the virtual environment and tests fail.

One of the solutions that I can think of is to enforce both workflows (the one that creates and the one that uses the venv) to use the exact same Python patch (for example 3.12.8), but I wanted to ask you if I am missing something? I would expect any venv created by the same minor Python version to be compatible with each other or I have never faced this issue before (I usually don't look at which Python patch I am using).

Thanks for any help!

**Comment by vstinner** [comment]
Sadly, the Python version used to create the venv should match the Python version used to run the venv. Both versions should be in sync.

**Comment by YigitElma** [comment]
> Sadly, the Python version used to create the venv should match the Python version used to run the venv. Both versions should be in sync.

@vstinner Thanks for the quick response!

Was this always the case? For example, venv with 3.12.7 and 3.12.6, aren't they compatible?

Because previously creating the venv with any 3.12 (whatever patch was chosen by Github runner) and activating it with any 3.12 was working.

**Comment by vstinner** [comment]
> Was this always the case? For example, venv with 3.12.7 and 3.12.6, aren't they compatible?

It's a new issue caused by the security fix.
