### ISSUE TITLE
remove_unreachable: Assertion `target->b_predecessors == 0 || target == b->b_next' failed

### ISSUE THREAD

**Issue by 15r10nk** [python/cpython#124871]
# Crash report

### What happened?

The following code causes an assertion in a cpython debug build

```python

name_3=5
name_2=2
name_1=0

while name_3 <= name_2 > name_1:
    try:
        raise
    except:
        pass
    finally:
        pass
```

output (Python 3.13.0a5+):
```python
python3: Python/flowgraph.c:994: remove_unreachable: Assertion `target->b_predecessors == 0 || target == b->b_next' failed.
```

The bug is in the current 3.13 branch.
I bisected the problem down to 04697bcfaf5dd34c9312f4f405083b6d33b3511f
@iritkatriel I think this is again one for you.

Little side note. I found this bug after fuzzing for ~3 days. I want to start to test the cpython main branch in the future and I hope to find bugs like this earlier.

### CPython versions tested on:

3.13

### Linked PRs
* gh-124952
* gh-124977

**Comment by iritkatriel** [comment]
This bug went away with fe23f8ed970425828de20fb48750fa89da914886.

**Comment by iritkatriel** [comment]
The issue here is that we have a small basicblock which has ``SETUP_FINALLY`` instructions and is reachable from two other blocks via jumps - one conditional and one unconditional. The `inline_small_or_no_lineno_blocks`` function inlines this block where it called unconditionally, but not where it's called conditionally. So the block remains, and is reachable, and when reachability calculation follows the ``SETUP_FINALLY`` target of the second time, this assertion trips.

I need to figure out whether the assertion is wrong it's or something else.

**Comment by iritkatriel** [comment]
> I need to figure out whether the assertion is wrong it's or something else.

The assertion is wrong. The reason it was added was because this function marks blocks as visited when they are processed, and not when they are inserted to the queue (as other traversals do). The assertion ensured that we don't enter the same block to the queue more than once. The PR changes it to mark blocks as visited as soon as they are inserted to the queue, and remove the assertion.

**Comment by 15r10nk** [comment]
awesome, thank you.
