### ISSUE TITLE
Emit slices as constants in the bytecode compiler

### ISSUE THREAD

**Issue by mdboom** [python/cpython#125063]
# Feature or enhancement

### Proposal:

Constant slices are currently emitted as multiple bytecodes by the Python bytecode compiler.

For example, `x[:-2, 1:-1]` generates:

```
              LOAD_CONST               4 (0)
              LOAD_CONST               5 (-2)
              BUILD_SLICE              2
              LOAD_CONST               1 (1)
              LOAD_CONST               2 (-1)
              BUILD_SLICE              2
              BUILD_TUPLE              2
```

Then tuples of slices are constant like this, this could instead be compiled down to a single `LOAD_CONST` instruction:

```
              LOAD_CONST                1 ((slice(0, -2, None), slice(1, -1, None))
```

According to @fberlakovich and [Stefan Brunthaler](https://drops.dagstuhl.de/search/documents?author=Brunthaler,%20Stefan)'s paper on [Cross module quickening](https://drops.dagstuhl.de/entities/document/10.4230/LIPIcs.ECOOP.2024.6), this can have a significant impact on Numpy benchmarks.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-125064
* gh-126804
* gh-126829
* gh-126830

**Comment by nineteendo** [comment]
Shouldn't this be closed now?

**Comment by mdboom** [comment]
> Shouldn't this be closed now?

Yep -- sorry, I forgot that step.

**Comment by encukou** [comment]
Hi @mdboom,
This is missing a documentation update, since [marshal docs](https://docs.python.org/3/library/marshal.html#module-marshal) have a list of the types that `pyc` can handle.

But, I wanted to ask: would it make sense to do the folding in AST, rather than in codegen? That seems like a more appropriate place, even though it probably won't help common code (e.g. folding `"abc"[:1]` to `"a"` isn't too relevant).

I tried moving it, and tests pass, but I don't know if I'm missing something: https://github.com/python/cpython/compare/main...encukou:cpython:const_slice

**Comment by mdboom** [comment]
> his is missing a documentation update, since [marshal docs](https://docs.python.org/3/library/marshal.html#module-marshal) have a list of the types that pyc can handle.

Thanks for pointing that out.  I'll handle that part.

> But, I wanted to ask: would it make sense to do the folding in AST, rather than in codegen?

I don't know if I have enough historical to say which is better, it does seem like doing it earlier makes sense.  I'd want a second opinion about whether it's the right thing to do, though (Cc: @iritkatriel?), and if so, you should submit your branch as a PR.

**Comment by iritkatriel** [comment]
> But, I wanted to ask: would it make sense to do the folding in AST, rather than in codegen?

Yes, I think this makes sense.
