### ISSUE TITLE
`importlib` documentation doesn't declare functions properly

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#125018]
https://docs.python.org/3/library/importlib.metadata.html#distribution-versions doesn't actually define a Sphinx function for `version`, so attempted references with `` `:func:`importlib.metadata.version` `` (including via the `intersphinx` extension) fail.

Edit: fixed the backticks thanks to @serhiy-storchaka's tip below (TIL that you can use repeated backticks with trailing and leading space for inline code markup, allowing inclusion of single backticks in the quoted code)

### Linked PRs
* gh-125027
* gh-125047
* gh-125048
* gh-125050
* gh-125055
* gh-125080

**Comment by serhiy-storchaka** [comment]
Use triple backticks ``` :func:`importlib.metadata.version` ```.

**Comment by webknjaz** [comment]
@serhiy-storchaka nope, @ncoghlan is right. For the full list of exposed objects, I have this little helper that updates every several hours: https://webknjaz.github.io/intersphinx-untangled/docs.python.org/.

And the terminal way to see what's exposed would be `python -Im sphinx.ext.intersphinx https://docs.python.org/en/3/objects.inv`.

These references don't come from Python runtime but from Sphinx. They must be properly declared in Sphinx in order to be linkable.

Single backticks work depending on Sphinx config. In that case, it's because of `default_role = 'any'` that Sphinx attempts finding any object of any role matching the name in intersphinx (and the site-local domain).

**Comment by serhiy-storchaka** [comment]
I meant that you can use triple quotes to quote text containing single or double backquotes in Markdown.

**Comment by ncoghlan** [comment]
I fixed the initial post to avoid requiring imagination of the actual reference syntax (thanks to @serhiy-storchaka's tip, I learned something new about Markdown today: https://meta.stackexchange.com/questions/82718/how-do-i-escape-a-backtick-within-in-line-code-in-markdown ).

**Comment by ncoghlan** [comment]
Posted a PR that adds the minimal text needed to define valid semantic cross-reference targets. The phrase "as described below" features heavily in their descriptive text, since I didn't want to embark on a wholesale rewrite of the module docs just to fix a cross-referencing issue.

**Comment by webknjaz** [comment]
> I fixed the initial post to avoid requiring imagination of the actual reference syntax (thanks to @serhiy-storchaka's tip, I learned something new about Markdown today: [meta.stackexchange.com/questions/82718/how-do-i-escape-a-backtick-within-in-line-code-in-markdown](https://meta.stackexchange.com/questions/82718/how-do-i-escape-a-backtick-within-in-line-code-in-markdown) ).

One stray backtick still renders for me, though..

**Comment by ncoghlan** [comment]
Thanks for the syntax cleanups @AA-Turner (I incorrectly assumed that Sphinx would error on the `!~` syntax if it didn't understand it, missing the possibility that it might just treat everything after the `!` as a plain text string to pass through to the rendered output, which is what actually happened).
