### ISSUE TITLE
Nested range Bug

### ISSUE THREAD

**Issue by chlovec** [python/cpython#125016]
# Bug report

### Bug description:

```python
def nested_range_bug(self, word: str) -> int:
        word_len: int = len(word)
        for left in range(len(word) - 1, - 1, -1):
            for index in range(1, min(10, word_len - left)):
                return left

    def test_my_word(self) -> None:
        actual_left = self.nested_range_bug("band")
        self.assertEqual(3, actual_left)
```
When using a nested range in two nested loops and the range in the inner loop is started at one, python skips processing of the the first iteration of the outer loop.
In the code example above, it's nested_range_bug is expected to return 3 but it returns 2 instead.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by tomasr8** [comment]
The first iteration of the outer loop is not skipped, it is actually the inner loop that is skipped because
`range(1, min(10, word_len - left))` evaluates to `range(1, min(10, 4 - 3))` which is `range(1, 1)` which is empty, so the inner loop does not run for the first iteration of the outer loop. It runs only on the second interation when `left` is `2` which is also the value that is returned from the function :)

**Comment by chlovec** [comment]
Thanks for the explanation.
