### ISSUE TITLE
Rounding Error

### ISSUE THREAD

**Issue by MrHamel** [python/cpython#125155]
# Bug report

### Bug description:

This made the rounds on [Twitter yesterday afternoon](https://twitter.com/0xTib3rius/status/1843430274094506285), and was able to verify this in Linux (x86_64) on versions 3.10 and 3.12.

```python
>>> round(2.5)
2
>>> round(3.5)
4
```

### CPython versions tested on:

3.10, 3.12

### Operating systems tested on:

Linux

**Comment by MrHamel** [comment]
I understand how the function [works](https://github.com/python/cpython/blob/eafd14fbe0fd464b9d700f6d00137415193aa143/Doc/library/functions.rst#id101), but it can trip many people up because that is not proper math. Anything > 4 is rounded up, everything below it is rounded down.

**Comment by zware** [comment]
This is [documented behavior](https://docs.python.org/3/library/functions.html#round):

> if two multiples are equally close, rounding is done toward the even choice (so, for example, both round(0.5) and round(-0.5) are 0, and round(1.5) is 2)

See also [this SO question](https://stackoverflow.com/q/10825926).

**Comment by MrHamel** [comment]
Can we have the option of switching between methods, and leave the current one as the default?

Also, don't you think it is rude to close someones issue immediately after response? It's like shutting the door in ones face, which I'm sure you would not like.

**Comment by MrHamel** [comment]
Is there a reason why this was done, other than "it's the standard" ?

**Comment by zware** [comment]
> Can we have the option of switching between methods, and leave the current one as the default?

If you would like to pursue that possibility, please post to the [Ideas](https://discuss.python.org/c/ideas/6) forum.  If it gains significant traction there, a new feature request issue can be opened.

My personal expectation is that it is not worth complicating the `round` builtin.

> Also, don't you think it is rude to close someones issue immediately after response? It's like shutting the door in ones face, which I'm sure you would not like.

Rudeness was not the intention, sorry about that. You are of course free to continue to post here, but this bug report will not be reopened because there is no bug to fix.  This is also not the first such issue; see for example gh-91981, gh-94672, gh-89878, gh-88069, etc.

> Is there a reason why this was done, other than "it's the standard" ?

Is following standards not enough? :)

When summing many rounded values, the primary school "round half up" algorithm produces a significant and noticeable bias towards larger numbers, artificially inflating the sum; "round half to even" corrects this.  If "round half up" semantics are *really* necessary, it can be implemented relatively easily in user code, or by making use of the `decimal` module's multiple rounding modes.

**Comment by MrHamel** [comment]
Would it be possible to meet the community half way, by adding that `decimal` method to the builtin.round's documentation to know how to get the original behavior? It's just that it's a wakeup call for those that are not ready to expect such a change, compared to JavaScript, PHP, etc.

Also, the [`decimal.round()` documentation](https://docs.python.org/3/library/decimal.html#decimal.Decimal.to_integral_value) does not have the hyperlink button to the right, like the `decimal.to_integral_value()` function.

**Comment by hugovk** [comment]
Opening a discussion on the ideas forum is the way forward:

https://discuss.python.org/c/ideas/6

This will involve many more from the community (who are subscribed to the forum) rather than the one or two who happen to see this in the firehose of issues :)  

Thank you!



> Also, the [`decimal.round()` documentation](https://docs.python.org/3/library/decimal.html#decimal.Decimal.to_integral_value) does not have the hyperlink button to the right, like the `decimal.to_integral_value()` function.

Please could you share screenshots to illustrate?

**Comment by skirpichev** [comment]
> Please could you share screenshots to illustrate?

@hugovk, I confirm that

![1](https://github.com/user-attachments/assets/ba4f20a0-4741-40c0-981c-1e3d01beb99b)

round() below has no such anchor.

> know how to get the original behavior?

I think that round-to-nearest mode (with ties to even) was in CPython from beginning.  It's default in IEEE 754, etc.

> Would it be possible to meet the community half way, by adding that decimal method to the builtin.round's documentation

I also think, that starting a d.p.o thread is a best way to go.

There is a relevant stale issue, however: https://github.com/python/cpython/issues/57269

**Comment by hugovk** [comment]
Thanks, it's because [`decimal.to_integral_value`](https://docs.python.org/3/library/decimal.html#decimal.Decimal.to_integral_value) is a regular `.. method::` but `round`  is `.. describe::`

https://github.com/python/cpython/blob/78406382c97207b985b5c1d24db244ec398b7e3f/Doc/library/decimal.rst#L894-L903

https://www.sphinx-doc.org/en/master/usage/domains/standard.html#directive-describe

`describe` is new to me, but looks appropriate here because `round` isn't part of `decimal`, it's a builtin and we're referring to how `round` applies to decimal. `meth` would incorrectly say there's a `decimal.round`.

One option would be to put it in a new section called "Rounding decimals"?

**Comment by skirpichev** [comment]
> One option would be to put it in a new section called "Rounding decimals"?

Or add round-like method ``round()`` on Decimal, with additional optional ``rounding`` argument.  In sphinx docs for this method we can mention builtin round() as a restricted version of this interface.
