### ISSUE TITLE
Behaviour of os.kill() on Windows may be misunderstood

### ISSUE THREAD

**Issue by honorasm** [python/cpython#125298]
The [latest os.kill() document](https://docs.python.org/3/library/os.html#os.kill) says “The Windows version of kill() additionally takes **process handles** to be killed,” but the `kill()` function actually does not accept process handles instead of process IDs. Runing the following code with `Python 3.12.6` on `Windows 10 Education Edition version 22H2 amd64` will result in an error.

Test code:
```
import os, signal
proc_handle = os.spawnl(os.P_NOWAIT, r'C:\Windows\notepad.exe', 'notepad.exe')
os.kill(proc_handle, signal.SIGTERM)
```

Error message:
```
Traceback (most recent call last):
  File "C:\Users\John\Documents\Python\os_kill_proc_handle.py", line 3, in <module>
    os.kill(proc_handle, signal.SIGTERM)
OSError: [WinError 87] The parameter is incorrect
```

### Linked PRs
* gh-125749
* gh-126587
* gh-126588

**Comment by picnixz** [comment]
I think this is a doc imprecision. What os.kill() does is:

https://github.com/python/cpython/blob/08f6bf717118963815d9a3e60578104470fdf3e1/Modules/posixmodule.c#L9528-L9559

So, it only expect PIDs but may try to use process handles instead in order to kill the desired PID. I am no Windows expert but that's how I understand it. Now, I think we could perhaps improve the wording though I don't have a good suggestion.

cc @zooba as a Windows expert

**Comment by csm10495** [comment]
It kind of seems like 

`The Windows version of kill() additionally takes process handles to be killed.`

Could be removed for clarity. If something must be stated about the implementation, maybe:

On Windows, the pid is mapped to a process handle which is then passed along with the signal to `TerminateProcess`.

**Comment by rruuaanng** [comment]
Actually this is a documentation issue, since `TerminateProcess` only receives a handle, it needs to get the pid, but the documentation doesn't really need to state this, since this is implementation-level and not user-facing. It could be removed, and there's no need to add extra documentation to describe this behavior.
