### ISSUE TITLE
Whitespace-only lines in PDB cause a line continuation when taken from history

### ISSUE THREAD

**Issue by treyhunner** [python/cpython#125378]
# Bug report

### Bug description:

The issue happens *only* when pulling a line from history.

Typing 4 spaces or a Tab and hitting Enter when at the PDB prompt is interpreted the same as hitting Enter without entering whitespace.
However, grabbing a whitespace-only line from history causes a prompt/line continuatin.

To reproduce:

1. Type `if True:` and hit Enter
2. Type 4 spaces and hit Enter
3. Type 4 spaces, `print("True")` and hit Enter twice
4. Hit the up arrow 2 times
5. Hit Enter again

After those 5 steps you will see:

![image](https://github.com/user-attachments/assets/e745f2bf-e7cf-49e6-80ce-e945b8d3baf6)

Repeatedly hitting Enter at that point shows the same continuation prompt:

![image](https://github.com/user-attachments/assets/668d26ca-d7eb-4840-9c78-cef66d36a02f)

The new REPL had a somewhat similar issue (#118911 was part of it).

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-125717
* gh-125736

**Comment by savannahostrowski** [comment]
cc: @gaogaotiantian

**Comment by gaogaotiantian** [comment]
It doesn't need a repro this complicated :) The repro could be:

1. type any multi-line statement and finish it
2. hit `<enter>`

Basically the issue is, an empty line means "repeat" in `pdb` (inherited from `cmd.Cmd`), but `pdb` did not remember the full multi-line statement, it only remembers the first line. So equivalently, when you read the empty line from the history, you just sent a "repeat" command, and it repeated the line of the `if` statement - that line did not end, so `pdb` is expecting more code, hence the `...`.

Fix was straight foward - just let `pdb` remember the full multi-line command as the last command.
