### ISSUE TITLE
CI is failing on current main: test_asyncio.test_taskgroups

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#125472]
# Bug report

### Bug description:

Example of failing CI:
* https://github.com/python/cpython/actions/runs/11331846505/job/31512771372?pr=125471
* https://github.com/python/cpython/actions/runs/11331026920/job/31510134859?pr=125469
* https://github.com/python/cpython/actions/runs/11331846505/job/31512771372?pr=125471

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-125476
* gh-125478
* gh-125486

**Comment by Eclips4** [comment]
Perhaps the bad commit is the d5dbbf4372cd3dbf3eead1cc70ddc4261c061fd9

**Comment by picnixz** [comment]
cc @graingert

**Comment by 1st1** [comment]
Yeah, OK to revert. Weird that it did pass the GH CI.

**Comment by zware** [comment]
Expectation is that it conflicts with a more recent change to `main`; the PR 124959 branch was not fully up to date before merge.

**Comment by terryjreedy** [comment]
We allow PRs to be merged (if merge-compatible) with a passing GH CI for an older version of main because A) requiring a fresh green CI for every code change would drastically slow down progress and b) we have buildbots retesting all recent merges together.   A coredev considering merging a PR with an 'old' green CI can trigger a retest by updating the patch, which is now easy right on the PR, and set automerge upon success.
