### ISSUE TITLE
Add total_seconds() method to datetime.time object

### ISSUE THREAD

**Issue by MirrorAzure** [python/cpython#125435]
# Feature or enhancement

### Proposal:

It often happens that when working with datetime.time objects, user has to write custom constructions to get the number of seconds from the time object, like that:
```python
>>> time_object = time(hour=5)
>>> total_seconds = time_object.hour * 3600 + time_object.minute * 60 + time_object.second
>>> print(total_seconds)
18000
```
It would be convenient to have a method that returns total number of seconds of time object
Example:
```python
>>> time_object = time(hour=5)
>>> total_seconds = time_object.total_seconds()
>>> print(total_seconds)
18000
```

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-125433

**Comment by erlend-aasland** [comment]
This functionality is present in the `timedelta` class:

```python
>>> import datetime
>>> t = datetime.timedelta(hours=5)
>>> t.total_seconds()
18000.0
```

**Comment by pganssle** [comment]
The `time` object does not represent an amount of time, it represents an instant on the clock. Like Erlend says, use `timedelta` if you want to represent an amount of time. 

Thank you for taking the time to write a well-formatted request with an accompanying PR! I hate to close issues and PRs like this because they clearly represent the kind of effort that I prefer to encourage, but unfortunately this one is based on a fundamental misunderstanding of the purpose of the `time` class, and if we were to implement it it would propagate this misunderstanding. Please do not let this discourage you from further reports and PRs in the future.

**Comment by MirrorAzure** [comment]
Thanks for the feedback.
In general, I understand why you are not going to implement this functionality. Perhaps I myself misunderstood the purpose of the `datetime.time` object.
I wanted to suggest my improvement, since I had a task to calculate the difference in seconds between two timestamps, for which I used `datetime.time` (it might have been more correct to use `datetime.datetime`, but the date was irrelevant in the context of the task).
