### ISSUE TITLE
Consider pinning runner image instead of using `ubuntu-latest` in JIT CI

### ISSUE THREAD

**Issue by savannahostrowski** [python/cpython#125560]
It looks like GitHub updated the default/latest Ubuntu runner to use Ubuntu 24.04 from 22.04, which is leading to [failed CI runs](https://github.com/python/cpython/actions/runs/11357684569/job/31591164216?pr=125499). We should  consider pinning the version here.

(GitHub's general guidance is to use `ubuntu-latest,` so if folks feel strongly against this, this could also be a temporary measure until the issue resolves.)

See also https://github.com/actions/runner-images/issues/10788

### Linked PRs
* gh-125564

**Comment by savannahostrowski** [comment]
cc: @brandtbucher in case you have additional thoughts here.

**Comment by ZeroIntensity** [comment]
We should consider this for all our runners, as long as we remember to bump them every once in a while. I've had [issues](https://github.com/actions/setup-python/issues/850) in the past with `latest` breaking things after an update.

**Comment by savannahostrowski** [comment]
That said, I'm actually not sure if the image is missing dependencies...it seems like maybe something else has gone awry given that the error is actually a 503 on the workflow run.

**Comment by hugovk** [comment]
The 503s look like temporary network errors. You can click the "Re-run jobs" button and "Re-run failed jobs". If the errors persist on ubuntu-latest aka ubuntu-24.04, we can pin (in the short-to-medium term) to ubuntu-22.04 if that fixes it.

In general, pinning is a good idea to avoid surprises like in https://github.com/python/cpython/pull/125236, then we can do a controlled upgrade.

See also https://github.com/python/cpython/issues/122544.

**Comment by savannahostrowski** [comment]
Yeah, that makes sense. Thanks for sharing those other issues!

Updating to pin to 22.04 did fix things last night. Judging by the noise on social media around this...it seems like a bunch of things broke (some of which were more ephemeral).

**Comment by hugovk** [comment]
Unfortunately, I don't think we can schedule them: we get Ubuntu releases every second year, and it will depend a lot on availability of the image on GitHub Actions, plus readiness of other dependencies.

For example, alpha0 was 8th May, and `ubuntu-24.04` was available on (checking...) [14th May](https://github.com/actions/runner-images/issues/9848). That's not so bad, actually :)  But it was a beta, the GA was last month, and when we checked upgrades in August, some things weren't ready, like Azure Pipelines (https://github.com/python/cpython/issues/122544).

And I wouldn't want it to be part of the release cycle (but it could be prompted by it) - there can be some non-trivial upgrades needed, and we wouldn't want to delay any part of the release because of it.
