### ISSUE TITLE
re documentation, the word 'captured' is unfortunate

### ISSUE THREAD

**Issue by epa** [python/cpython#125579]
# Documentation

In the docs for the `re` package, which can be seen for example at https://docs.python.org/3/library/re.html
there are some example code fragments with the string

`"He was carefully disguised but captured quickly by police."`

But to "capture" is a term used when talking about regular expressions.  If you search that page for "capture" or for the initial substring "captur" then you will hit this example text as well as, or instead of, the documentation about how to capture the matched text from a regexp or sub-regexp.

Obviously it's not a big problem, but equally it costs nothing to change the example string to something that doesn't contain that word.  I will send a pull request.

### Linked PRs
* gh-125580

**Comment by epa** [comment]
I have made a pull request, but the change is so trivial you might choose to ignore that and change it yourself.

**Comment by terryjreedy** [comment]
In the re doc, there are 11 matches for 'captur': 9 for 'capturing' and the 2 above for 'captured'.  Perhaps someone decided to consistently use 'capturing' rather than 'capture' as an adjective in expressions like 'captur__ group'.  I agree that it would be better if the match number dropped from 9 to 0 (instead of 11 to 2) when adding 'e', to suggest deleting the 'e' and looking to see what the 9 matches are.

I am not sure if we officially care about this and will ask others for opinions.

**Comment by nedbat** [comment]
This to me seems like too small a friction point to make a change for. When I search a page, I constantly find false matches, and I keep going.

**Comment by terryjreedy** [comment]
@epa Thank you for the clear issue and PR.  Several coredevs and triagers responded on our discord.  All agreed that this is a minor issue.  Opinion as to merge or not seems split, making this close to a coin flip for me.  The main concern against was that some people would see this as precedent to open numerous similar issues, which we do not really want.  If not for the CLA issue, I might have merged anyway after adding a note that doing was because of particular details of this case and that doing so should not be seen as a precedent for similar issues and PRs.  But this awkward and too likely to be ignored.  So rather than leave this open indefinitely, which is also a problem, I am closing.

**Comment by terryjreedy** [comment]
Yes, my mistake.
