### ISSUE TITLE
Move `jit_stencils.h` to the `Python/` directory

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#126087]
# Feature or enhancement

### Proposal:

I don't know if there is any reason to keep `jit_stencils.h` under the root directory, but I think it should also be placed in the Python directory, as other generated files are also placed there (`generated_cases.c.h`, `executor_cases.c.h`, `optimizer_cases.c.h`). 

If you agree, I will be happy to submit a PR :)

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by brandtbucher** [comment]
`jit_stencils.h` isn't placed in the *root* directory, it's placed in the *build* directory. This is important, since (like `pyconfig`, or compiled `.o` files) it contains binary code specific to *that particular build*. In particular, out-of-tree builds, especially parallel ones, would break.

So I think it makes sense for this to stay where it is, right next to `pyconfig.h`. Unlike the other files you mention, it's not tracked by version control.

**Comment by Eclips4** [comment]
> `jit_stencils.h` isn't placed in the _root_ directory, it's placed in the _build_ directory (basically, wherever `configure` is run from). This is important, since (like `pyconfig`, or compiled `.o` files) it contains code specific to _that particular build_. In particular, out-of-tree builds, especially parallel ones, would break.
> 
> So I think it makes sense for this to stay where it is, right next to `pyconfig.h`. Unlike the other files you mention, it's not tracked by version control.

Oh, yes, I somehow missed it. So, there's no issue. Sorry for making noise!
