### ISSUE TITLE
Incorrect use of OBJ_obj2txt

### ISSUE THREAD

**Issue by federicovalenso** [python/cpython#126125]
# Bug report

### Bug description:

OBJ_obj2txt [is used incorrectly](https://github.com/python/cpython/blob/faa3272fb8d63d481a136cc0467a0cba6ed7b264/Modules/_ssl.c#L1050). In *man* we can [see this at Bugs section](https://linux.die.net/man/3/obj_obj2txt):

> OBJ_obj2txt() is awkward and messy to use: it doesn't follow the convention of other OpenSSL functions where the buffer can be set to NULL to determine the amount of data that should be written. Instead buf must point to a valid buffer and buf_len should be set to a positive value. A buffer length of 80 should be more than enough to handle any OID encountered in practice.

### CPython versions tested on:

3.11

**Comment by encukou** [comment]
That's for an old OpenSSL version, [1.0](https://docs.openssl.org/1.0.2/man3/OBJ_nid2obj/#bugs).

[Since 3.10](https://peps.python.org/pep-0644/), CPython only supports OpenSSL 1.1.1 and above, and the [docs for that](https://docs.openssl.org/1.1.1/man3/OBJ_nid2obj/#description) say:

> Unless buf is NULL, the representation is written as a NUL-terminated string to buf, where at most buf_len bytes are written, truncating the result if necessary. In any case it returns the total string length, excluding the NUL character, required for non-truncated representation, or -1 on error.

3.9 can still be built with OpenSSL 1.0. But, it still uses an initial buffer of 256, so it should be OK in practice.

**Comment by federicovalenso** [comment]
@encukou, you're right about version 1.0, I think issue could be closed.
