### ISSUE TITLE
Cannot find installation file structure change in changelog

### ISSUE THREAD

**Issue by kapple19** [python/cpython#126226]
On Windows, I have a Python dependency that used to install the virtual Python environment in a `./Scripts/` directory (Python 3.11.0). Recently my automated Python installation started installing Python in a `./bin/` directory instead (Python 3.11.7).

Which Python versions does this change apply to?
I can't find it in the [changelogs](https://docs.python.org/release/3.11.7/whatsnew/changelog.html).

**Comment by kapple19** [comment]
My colleague who set it up says that the change was probably in the Python package `venv`.

**Comment by AA-Turner** [comment]
What's the output of python -VV? Which shell are you running this in?

**Comment by kapple19** [comment]
`.\python -VV` returns the following:

* "Working" version: `Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]`
* "Broken" version: `Python 3.11.7 (main, Dec  7 2023, 09:09:57)  [GCC UCRT 13.2.0 64 bit (AMD64)]`

My colleague just found [this issue](https://github.com/python/cpython/issues/58510)!

**Comment by ericvsmith** [comment]
That issue is 12 years old, and as near as I can tell was never implemented. Your problem is most likely due to the 3.11.7 version you're using being part of mingw or cygwin or similar. This is not a Python bug, so I'm going to close this issue. You should ask for help at https://discuss.python.org/c/help/7, or maybe StackOverflow.
