### ISSUE TITLE
`RecursionError` when comparing two dictionaries referenced to itself

### ISSUE THREAD

**Issue by vodkar** [python/cpython#126749]
# Bug report

### Bug description:

Is this expected behavior?

```python
d = {}
d["a"] = d
d2 = {}
d2["a"] = d2
d == d2
```
Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RecursionError: maximum recursion depth exceeded in comparison
```

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by nineteendo** [comment]
Also note that you can reference the other dictionary:

```python
d1 = {}
d2 = {}
d1["a"] = d2
d2["a"] = d1
print(d1 == d2)
```

**Comment by ZeroIntensity** [comment]
Well, if you play stupid games with circular references, you win stupid `RecursionError` prizes 😄

I guess if we *really* wanted to fix this, we could check the identity of the first when comparing. Does this have precedent (e.g. does the same thing happen with circular references on `list`)?

**Comment by nineteendo** [comment]
Peter, it already checks for identity:

```python
d1, d2 = {}, {}
d1["a"] = d2["a"] = d1
print(d1 == d2) # True
```

You could link back to an arbitrary ancestor making this somewhat difficult to fix.

**Comment by vodkar** [comment]
> Well, if you play stupid games with circular references, you win stupid `RecursionError` prizes 😄

Initially, I found this bug report at pydantic: https://github.com/pydantic/pydantic/issues/10630
There is a dict comparison in`__eq__`, so I made a similar construction in pure python with dictionaries, and I got this error 😄
I was trying to search this problem in issues, but no luck. So I want to check, is this proper behavior?

> I guess if we really wanted to fix this, we could check the identity first when comparing. Does this have precedent (e.g. does the same thing happen with circular references on list)?

I can't provide such precedents. 
I'm not sure about the following way to check correctness of current logic in Python but I check other programming languages, and this is what I got:

| Language    | Result |
| -------- | ------- |
| Java  | raises `StackOverflowError` |
| JavaScript | `false` |
| Golang    | `true`  |

So, I have no idea which logic is correct 🤷‍♂️

**Comment by terryjreedy** [comment]
In the first case, d1 == d2 if and only if d1 == d2.  So the answer is indeterminate (not determined).  In the C world, this means that any arbitrary answer is considered correct.  In Python, guessing is frowned upon, and refusing to answer, by raising, is considered  more correct.  (This is better than the alternative non-answer of looping forever.)  In the second case, d1 == d2 if and only if d2 == d1, which is the same thing.  In the particular case of 1 key k, d1 == d2 if and only if (d1 is d2 or d1[k] == d2[k]), where the latter is a condensed and partly checkable form of an infinite proposition d1[k] is d2[k] or d1[k][k] is d2[k][k] or d1[k][k][k] is d2[k][k][k] or ...). I think we can close.

**Comment by ZeroIntensity** [comment]
Since this did appear in a large library downstream, I want to wait for any extra input before brushing it off as a non-issue.

**Comment by terryjreedy** [comment]
Raising an exception for buggy code is not a brush-off.

**Comment by pochmann3** [comment]
Just some more thoughts...

@terryjreedy I'd say d1 and d2 clearly are equal, they were even created the exact same way. Just the simplistic recursive determination isn't capable of seeing it. 

Consider these two mazes:

![mazeA](https://github.com/user-attachments/assets/d88a8477-cf8b-47b2-b9ef-f31895417677)
![mazeB](https://github.com/user-attachments/assets/7b57c876-936e-4794-bbbf-3d92443f78d8)

Are they equal?

Let me make it easier: The second one is a copy of the first. So wouldn't you agree that they're equal?

You also could've found that they're equal by looking at those bird's-eye views for a while, or comparing the images pixel by pixel. But if you write a simplistic recursive checker and give it the two maze graphs, it would likewise get a RecursionError, as there's a loop in the maze. And you could apply your same infinite proposition reasoning to call it indeterminate. But that's just because that view and mechanism can't see it. Can't see that they're equal. But a more capable method could.

That said, I think making Python capable to see such hard-to-see equality would be too complicated/inefficient to be worth it. (And impossible in general, at least with user-defined classes.)

**Comment by zhangyx1998** [comment]
My first intuition solution was to use a "short circuit" logic to first check "a is b" and only check for "a == b" when "a is b == False".

However, this only works if an object does not overload equality operator. Otherwise it's possible that an object is not "equal to" itself. Short circuiting such comparison will make our result incorrect.

**Comment by nineteendo** [comment]
> first check "a is b"

That's already what happens:

```python
>>> from math import nan
>>> nan == nan
False
>>> [nan] == [nan]
True
```

**Comment by zhangyx1998** [comment]
Interesting. I found the logic [here](https://github.com/python/cpython/blob/612ac283b81907d328891b102f5bfafcf62bd833/Objects/object.c#L1077-L1084). (I should try to look it up earlier). The work has been done 15 years ago.

So for a subset of objects with endless recursion, the comparison would actually work.

I am wondering what if someone overloads the equality operator and expects a `False`. Will this be considered a bug?

**Comment by brianschubert** [comment]
I suggest opening a topic on https://discuss.python.org/ instead of continuing this discussion here. Keep in mind that every rely sends out notifications to all subscribed users.
