### ISSUE TITLE
Nested generator in dictionary view misbehaves after unpacking and parameter packing

### ISSUE THREAD

**Issue by WH-2099** [python/cpython#126875]
# Bug report

### Bug description:

```python
mapping = {
    1: [101, 102, 103],
    2: [201, 202, 203],
    3: [301, 302, 303],
}

def iterate_generator(gen):
    for pairs in gen:
        print(", ".join(str(x) for x in pairs))

def iterate_packing_unpacking(*args):
    for pairs in args:
        print(", ".join(str(x) for x in pairs))

iterate_generator(
    (((x, x_member) for x_member in x_members) for x, x_members in mapping.items())
)
# (1, 101), (1, 102), (1, 103)
# (2, 201), (2, 202), (2, 203)
# (3, 301), (3, 302), (3, 303)

iterate_packing_unpacking(
    *(((x, x_member) for x_member in x_members) for x, x_members in mapping.items())
)
# (3, 101), (3, 102), (3, 103)
# (3, 201), (3, 202), (3, 203)
# (3, 301), (3, 302), (3, 303)

```

### Expectation

The output of `iterate_packing_unpacking` should be the **same** as `iterate_generator`.

### CPython versions and Operating systems tested on:
- [x] 3.13
  - [x] Linux
  - [x] macOS
  - [x] Windows
- [x] 3.12
  - [x] Linux
  - [x] macOS
  - [x] Windows
- [ ] 3.11
  - [x] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] 3.10
  - [x] Linux
  - [ ] macOS
  - [ ] Windows
- [ ] 3.9
  - [ ] Linux
  - [ ] macOS
  - [ ] Windows

###  tested on:

Linux, macOS, Windows

**Comment by Zheaoli** [comment]
@Eclips4 I think this issue need an interpreter core label.

**Comment by WH-2099** [comment]
I am gradually adding to and refining the description.

**Comment by terryjreedy** [comment]
There is no bug; the problem is with the cell variable 'x'.  This issue is similar to the issue in this [lambda faq](https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result).  In the first case, each time the outer generator yields an inner generator, the inner generator is immediately run with the proper value of 'x'.  In the second case, the 3 inner generators are captured without running them.  Then all 3 are run with the fixed final value of 'x', which is 3.

As with lambda confusions, the problem can be easier to see in an equivalent def.
```
def outer():
    for x, x_members in mapping.items():
        yield ((x, x_member) for x_member in x_members)
```
The equivalent of your generator expression is `outer()`.  Passing `outer()` (and `*outer()`) gives the same results as above.

For each for loop iteration, the current value of x_members is captured ("the iterable expression in the leftmost for clause is immediately evaluated", [see](https://docs.python.org/3/reference/expressions.html#generator-expressions) but that of x is not, as it is not in your generator expression.  The only solution I see immediately is to also expand the inner genex into a def, using defaulted parameters to capture both current outer loop values.
```
def outer2():
    for x, x_members in mapping.items():
        def inner(x=x, x_members=x_members):  # Without 'x=x', outer2 is same as outer.
            for x_member in x_members:
                yield x, x_member
        yield inner()
```

**Comment by WH-2099** [comment]
Thank you very much for your patience.
