### ISSUE TITLE
import random

### ISSUE THREAD

**Issue by Abdullo-it** [python/cpython#126842]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
import random

# Schritt 1: Generiere eine Zufallszahl zwischen 1 und 100
zufallszahl = random.randint(1, 100)

# Schritt 2: Begrüßung und Anweisung
print("Willkommen zum Zufallszahl-Spiel!")
print("Ich habe eine Zahl zwischen 1 und 100 gewählt. Kannst du sie erraten?")

# Schritt 3: Wiederhole, bis der Benutzer die Zahl errät
while True:
    # Benutzereingabe
    ratezahl = int(input("Gib eine Zahl zwischen 1 und 100 ein: "))

    # Überprüfung und Feedback
    if ratezahl < zufallszahl:
        print("Zu niedrig!")
    elif ratezahl > zufallszahl:
        print("Zu hoch!")
    else:
        print("Richtig! Du hast die Zahl erraten!")
        break  # Beendet die Schleife

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by zware** [comment]
Hi @Abdullo-it.  A few things:

1) This is an English-language issue tracker.  If you are not comfortable using English, please use a translation service like translate.google.com and mention that you have done so.  That's what most of your audience here would have to do to understand your message anyway, so please save us the trouble :)

2) When reporting a bug, please include all of the details that you reasonably can, especially any error messages.  Also, use code blocks (see the `<>` button in the message editing toolbar) to format anything copied from a terminal to make sure it remains readable.

3) Consulting my crystal ball, rename your script from `random.py` to `myrandom.py`, or otherwise make sure that you don't have a file named `random.py` in the same directory as your script :)
