### ISSUE TITLE
Python 3.13 Threading issues

### ISSUE THREAD

**Issue by Apprisco** [python/cpython#126874]
# Bug report

### Bug description:

```
from threading import Thread
import time

def forward(a):
    while True:
        print(a)
        time.sleep(1.0)
# print(c.vk['mclick'])
thread=[Thread(target=forward,args=(i,),daemon=True) for i in range(10)]
for t in thread: t.start()
```
When daemon=True, thread runs for 1 round then immediately exits main thread without errors.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by JelleZijlstra** [comment]
Isn't that the purpose of daemon threads? They are killed when the main thread exits.

**Comment by ZeroIntensity** [comment]
I thought it was the opposite: daemon threads *aren't* killed when the main thread exits.

Anyways, @Apprisco, this is intentional. If you're interested in the technical side of what's going on, then know that finalizing Python prevents future re-acquisition of the GIL (*i.e.*, `PyEval_RestoreThread`, or I guess `_PyThreadState_Attach` as well, will never return), and since `time.sleep` releases the GIL while it sleeps (to allow other threads to run), then it will never be able to get the GIL and the loop doesn't proceed. So, that's why it works for one iteration, but then stops. If you don't want to do this and let your thread run, remove `daemon=True`.

**Comment by JelleZijlstra** [comment]
> I thought it was the opposite: daemon threads aren't killed when the main thread exits.

This is incorrect. The interpreter exits when only non-daemon threads are left. This is documented under https://docs.python.org/3.14/library/threading.html#thread-objects.

**Comment by ZeroIntensity** [comment]
Oh, I thought you meant the main thread exiting at the Python level (*i.e.,* thread state clearing and `Py_Finalize`), not the process itself. Sorry for the confusion there!

**Comment by Apprisco** [comment]
Interesting, I completely forgot that my main thread does not wait for any of the test threads. As such, it closes itself and kills all the other threads. That makes perfect sense, thank you.
I'm debugging pyarmor issues with python 3.13 haha
