### ISSUE TITLE
Overflow if `ast.AST.end_col_offset` is absurdly large

### ISSUE THREAD

**Issue by federicovalenso** [python/cpython#126860]
# Bug report

### Bug description:

```python
c = ast.parse('x = 1')
c.body[0].end_col_offset = 2**31-1
c.body[0].end_col_offset
2147483647
code = compile(c, "", "exec")
```

It leads to overflow in [_PyPegen_raise_error](https://github.com/python/cpython/blob/c0f045f7fd3bb7ccf9828f4bfad55347d097fd41/Parser/pegen_errors.c#L254C9-L254C48). This is also true for [col_offset](https://github.com/python/cpython/blob/c0f045f7fd3bb7ccf9828f4bfad55347d097fd41/Parser/pegen_errors.c#L250) (just replace `c.body[0].end_col_offset`)

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
Can you provide me an example where it could lead to invalid result?

**Comment by federicovalenso** [comment]
I tried, but failed... But that doesn't mean there won't be someone who can, and that could lead to unexpected problems. Or am I paranoid? :)))

**Comment by picnixz** [comment]
I would say that it depends on whether it's reachable or not and whether it will be used or not. Let's ask @pablogsal if this is worth fixing.

**Comment by skirpichev** [comment]
The source code size would be something like a quettabyte to trigger this.  Hardly it's a kind of practical limitation for text source.  Maybe after Mars colonization?  But even if so, hardly such program text will be readable for human kind.  Are you alien invader?!

If some generator of AST wrongly sets col_offset - it's another story.  But it will be a bug somewhere else, not in the CPython.

I think this may be closed.

**Comment by picnixz** [comment]
By looking at the code I don't think it's possible to trigger that code path with a very huge number, at least not unless the file is extremely huge. The reason is that it's because you're creating code objects using `ast.parse` in order to hack the offset value. But this assumes that you can parse the code so in order to get the AST node at the end, you cannot have a SyntaxError, a IndentationError or an IncompleteInputError which are the only errors that `_PyPegen_raise_error` uses internally.

So I don't think it's possible to craft such code that would badly compile (maybe you could instrumentalize it directly by changing the code object itself from bytes but I don't think we should do something for this one). Closing as `not planned`.
