### ISSUE TITLE
Pattern matching on Enum.name fails to distinguish between members with duplicate values

### ISSUE THREAD

**Issue by 1957-001B** [python/cpython#127375]
# Bug report

### Bug description:

```python
# How to reproduce

from enum import Enum

class Registers(Enum):
    SP = 31   # Stack pointer
    XZR = 31  # Zero register

# Example
for token in ["XZR"]:
    match token:
        case Registers.XZR._name_:
            print("Matched XZR")
        case Registers.SP._name_:
            print("Matched SP")
        case _:
            print("No match")

# Current behavior: Always matches SP case first because SP is defined first
# Expected behavior: Should match XZR case when checking against XZR._name_
```
The issue appears to be that when pattern matching against `_name_` of enum members with duplicate values, Python always matches the first enum member with that value, regardless of which `_name_` is being matched against. This makes it impossible to differentiate between enum members with the same value in pattern matching contexts.
This behavior is particularly problematic in cases like ARM assembly parsing where different registers (SP and XZR) share the same value (31) but have distinct semantic meanings and need to be handled differently.

much obliged,

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

**Comment by TeamSpen210** [comment]
This is because when you give members the same value, they actually get replaced by the same object. The extra name is just an alias - `Registers.ZSR is Registers.SP`. If you need to distinguish them, you could define the value as `("SP", 31)`, then define a `__new__` which copies the number to another attribute.

**Comment by TeamSpen210** [comment]
It's deliberate behaviour yes. You can call an enum class with a value to lookup the corresponding member - `Registers(18)`. If they weren't the same object it'd be ambiguous as to what was returned. Flag enum behaviour would also be very weird, since there you can do bitwise ops to combine/split values.

**Comment by 1957-001B** [comment]
Ah I see of course - a nice feature indeed. Thank you again.
