### ISSUE TITLE
Allow ast.NodeVisitor's generic_visit to return list of all returned values of calls to `visit_`

### ISSUE THREAD

**Issue by ahmedhus22** [python/cpython#128127]
# Feature or enhancement

### Proposal:

```python
class FindNames(ast.NodeVisitor):
    def visit_Name(self, node):
        return node.id

tree = ast.parse(src_code)
names = FindNames().visit(tree) # will return None for the tree, should return list of all names.
```
Currently ast.NodeVisitor iterates through all the nodes in tree calls the defined `visit_` methods but returns None.
## Proposal:
NodeVisitor's generic_visit should not return None when it has visited all the nodes, It will be more appropriate for it to return List of all return values of `visit_` calls.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-128128

**Comment by picnixz** [comment]
I've replied on the PR but I'll reply here instead to continue the discussion:

> This will blow-up memory footprint a lot, especially for static analysis tool so I'm not very sure it should be done. A visitor pattern is essentially used for traversing nodes, dynamically dispatching to the correct method efficiently, but it's not meant to remember what has been visited by default. If such behaviour is desired, a dedicated visitor class must be implemented instead.

I'm considering closing this one as `not planned`. cc @JelleZijlstra @Eclips4

**Comment by picnixz** [comment]
Thanks for the suggestion, but considering that both the OP and the relevant code owners have acknowledged the comment above, I will close this one as `not planned`. I would advise the OP to subclass `ast.NodeVisitor` for the latter to remember the nodes it encountered (but the object should carefully clear the nodes it visited once it has finished visting them in order to be re-used multiple times, see https://github.com/python/cpython/pull/128128#issuecomment-2557551611).
