### ISSUE TITLE
Strange regression between 3.13.0 and 3.13.1 with `socket.socket#setsockopt`

### ISSUE THREAD

**Issue by A5rocks** [python/cpython#128210]
# Bug report

### Bug description:

```python
def test_regular_socket() -> None:
    stdlib_sock = stdlib_socket.socket()
    with stdlib_sock as _:
        stdlib_sock.setsockopt(
            stdlib_socket.SOL_SOCKET,
            stdlib_socket.SO_BINDTODEVICE,
            None,
            0,
        )
```

This fails on 3.13.1 at least on MacOS GitHub Actions runners, and succeeds on 3.13.0. I don't have a MacOS machine to bisect with.

Looking at this more after the fact, `SO_BINDTODEVICE` is Linux-specific so it's not surprising that it fails. The only surprise is that this used to work and now does not. I couldn't find anything in the detailed changelog about this but I wasn't sure the right keywords to use.

Here's the error:

```
  _____________________________ test_regular_socket ______________________________
  
      def test_regular_socket() -> None:
          stdlib_sock = stdlib_socket.socket()
          with stdlib_sock as _:
  >           stdlib_sock.setsockopt(
                  stdlib_socket.SOL_SOCKET,
                  stdlib_socket.SO_BINDTODEVICE,
                  None,
                  0,
              )
  E           OSError: [Errno 42] Protocol not available
```

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

**Comment by A5rocks** [comment]
My hypothesis is that this is a build-time difference, but I don't have anything to prove or disprove that.

**Comment by ronaldoussoren** [comment]
FWIW, this code works for me on macOS 15.2 laptop using Python 3.13.1 (Python.org installer).

Note that ``socket.SO_BINDTODEVICE`` is available on macOS because the constant is available in the system headers (at least in the macOS 15.2 SDK, but not in the 14.5 SDK).  

Which macOS runner do you use? 

[Github's documentation](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) lists a number of runners using older versions of macOS (and it seems that macOS-latest is still macOS 14 at this point in time).

**Comment by A5rocks** [comment]
I believe we run macos 14 runners

**Comment by A5rocks** [comment]
Ok, so turns out the issue was that 3.13.1 has the symbol and 3.13.0 does not (presumably because 3.13.0 was built on macos 14?), so our tests try running this (which fails because at runtime it's macos 14).

I should have tested the minimized version against 3.13.0 instead of just confirming it still errored on 3.13.1. Sorry for the spurious bug report.
