### ISSUE TITLE
getopt not properly mentioned in the Library Reference index

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#128260]
# Documentation

`getopt` and `optparse` were recently saved from the trash heap. `optparse` is mentioned in the Library Reference Index section, "Command Line Interface Libraries." `getopt` is still only mentioned in the "Superseded Modules" section at the bottom of the index. The fix appears to be trivial. PR incoming in case the current ordering is not what is desired.

### Linked PRs
* gh-128261

**Comment by ncoghlan** [comment]
I had this link restoration in earlier iterations of the deprecation reversal PR, but eventually decided to keep `getopt` in the superseded category, as *functionally*, `optparse` does everything `getopt` does with less code and more user friendly results.

So the final outcome in the PR was an intentional choice, as `getopt` really *isn't* on the same tier as the other two CLI parsing modules. It's really the backwards compatibility concern that keeps it around (and undeprecated), moreso than the niche use case of directly replicating procedural CLI parsing code from C applications.

Thank you for the PR, but I'm going to decline both it and the issue.
