### ISSUE TITLE
Assignment to __bases__ of direct object subclasses

### ISSUE THREAD

**Issue by 26af53de-f307-4809-a4a7-9d50203b0a97** [python/cpython#37817]
BPO | [672115](https://bugs.python.org/issue672115)
--- | :---
Nosy | @mwhudson, @amauryfa, @benjaminp, @florentx, @ambv, @kynan, @maggyero
Files | <li>[typeobject.c.diff](https://bugs.python.org/file751/typeobject.c.diff "Uploaded as text/plain at 2003-02-05.02:39:14 by glchapman")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2003-01-21.22:45:40.000>
labels = ['interpreter-core', 'type-feature', '3.11']
title = 'Assignment to __bases__ of direct object subclasses'
updated_at = <Date 2022-03-23.00:08:37.846>
user = 'https://bugs.python.org/glchapman'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-23.00:08:37.846>
actor = 'maggyero'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2003-01-21.22:45:40.000>
creator = 'glchapman'
dependencies = []
files = ['751']
hgrepos = []
issue_num = 672115
keywords = []
message_count = 18.0
messages = ['14163', '14164', '14165', '14166', '14167', '14168', '14169', '14170', '14171', '70132', '70133', '86225', '88508', '88569', '106633', '154116', '189987', '270220']
nosy_count = 16.0
nosy_names = ['mwh', 'glchapman', 'amaury.forgeotdarc', 'lorph', 'benjamin.peterson', 'memeplex', 'farcat', 'flox', 'Hari.Krishna.Dara', 'lukasz.langa', 'kynan', 'eli.collins', 'aventurella', 'krzysiekj', 'borisompol', 'maggyero']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue672115'
versions = ['Python 3.11']
```

</p></details>

**Comment by erlend-aasland** [comment]
Heap type B[^1] based off of static type `object`[^2] tries to assign a heap type A[^1] as its new base. This generates, as expected, an error.

Changing decades long behaviour is not something we do lightly. If this behaviour should be changed, a discussion with a broader audience than the bug tracker would have to take place.

The issue author already suggested to close this as not-a-bug https://github.com/python/cpython/issues/37817#issuecomment-1093980502:

> Maybe it's best just to close this as "not a bug."

I'm closing this as not-planned. If someone wants to change fundamental behaviour, please open a discussion over [on Discourse](https://discuss.python.org) first.


[^1]: `tp_free = PyObject_GC_Del`
[^2]: `tp_free = PyObject_Free`

**Comment by erlend-aasland** [comment]
Opening as per request of @serhiy-storchaka

**Comment by Keniis0712** [comment]
I have the same problem when I do some meta-programming. Is there any plans to fix/change it?

**Comment by serhiy-storchaka** [comment]
There were several causes that prevented assignment.

* `tp_free` is different -- `PyObject_Free` and `PyObject_GC_Del`. But there is no need to check this  for `__bases__` assignment, because only `tp_free` of the original class is used, and it is not changed after assignment.
* The `Py_TPFLAGS_HAVE_GC` flag is different in old and new bases. For `__bases__` assignment, this was wrong check. The only forbidden case is if the flag is set in a new base but not set in the original (derived) class. The same is for other flags.

This fixes the case when class `A` has empty `__slots__`.

This is not enough to make the original example working, because `A` has `__dict__` and `__weakref__`, and therefore its base size differs from the size of `object`. But `B` has `__dict__` and `__weakref__` with the same offset and don't add new fields, so it may be possible make the assignment even more lenient.

**Comment by serhiy-storchaka** [comment]
Fixed also the original case.
