### ISSUE TITLE
fix one or two bugs in trace.py

### ISSUE THREAD

**Issue by 182980c4-e4f4-4e83-8e3e-662d412bbf71** [python/cpython#38807]
BPO | [766910](https://bugs.python.org/issue766910)
--- | :---
Nosy | @abalkin, @devdanzin
Files | <li>[makedir.patch](https://bugs.python.org/file5452/makedir.patch "Uploaded as text/plain at 2003-07-07.01:46:30 by zooko")</li><li>[trace-dir.patch.txt](https://bugs.python.org/file8480/trace-dir.patch.txt "Uploaded as text/plain at 2007-09-29.02:46:06 by zooko")</li><li>[trace_target.py](https://bugs.python.org/file19933/trace_target.py "Uploaded as text/plain at 2010-12-04.08:33:56 by eli.bendersky")</li><li>[traced_module.py](https://bugs.python.org/file19934/traced_module.py "Uploaded as text/plain at 2010-12-04.08:34:21 by eli.bendersky")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2003-07-07.01:46:30.000>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'fix one or two bugs in trace.py'
updated_at = <Date 2021-12-10.20:38:21.739>
user = 'https://bugs.python.org/zooko'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-10.20:38:21.739>
actor = 'ajaksu2'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2003-07-07.01:46:30.000>
creator = 'zooko'
dependencies = []
files = ['5452', '8480', '19933', '19934']
hgrepos = []
issue_num = 766910
keywords = ['patch']
message_count = 14.0
messages = ['44232', '55404', '56196', '56197', '58923', '65432', '114249', '123005', '123319', '126113', '126154', '126155', '190040', '190088']
nosy_count = 5.0
nosy_names = ['zooko', 'belopolsky', 'ajaksu2', 'ijmorlan', 'eli.bendersky']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue766910'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-110143
* gh-114206
* gh-114207

**Comment by hellozee** [comment]
Hoi, was poking around the codebase looking to learn something, if I follow the conversation correctly, is this the patch which is being talked about for this issue?
```diff
diff --git a/Lib/trace.py b/Lib/trace.py
index fb9a423ea0..0e20d3ab73 100755
--- a/Lib/trace.py
+++ b/Lib/trace.py
@@ -258,9 +258,8 @@ def write_results(self, show_missing=True, summary=False, coverdir=None):
                 modulename = _modname(filename)
             else:
                 dir = coverdir
-                if not os.path.exists(dir):
-                    os.makedirs(dir)
                 modulename = _fullmodname(filename)
+            os.makedirs(dir, exist_ok=True)

             # If desired, get a list of the line numbers which represent
             # executable content (returned as a dict for better lookup speed)
```

**Comment by buermarc** [comment]
TLDR at the bottom, some history at the top.

## Original Issues (2003) https://github.com/python/cpython/issues/38807:
 - Bug (as I understood it): Using `os.path.exists` to check if a file exists and if not creating it with `os.makedirs` could lead to a failure if it was created in between.
 - Maybe Bug: 
    > The maybe-bug is that it doesn't attempt to create the
    directory if it got the directory name from the name of
    the .py file (instead of getting the directory name
    from the --coverdir command line option).

    I am unsure if the maybe bug is really a bug, because even if we use a
    pickle file it seems to that we still would try to open the source file,
    therefore assuming it exists.
    As it might be opened two times, but definetly here:
    https://github.com/python/cpython/blob/c829975428253568d47ebfc3104fa7386b5e0b58/Lib/trace.py#L273
    So maybe the assumption that the source file must exist is okay, below a longer snippet from `Lib/trace.py`, with ` # <----` comments where we seem to open the file.

    ```python
    for filename, count in per_file.items():
    if self.is_ignored_filename(filename):
        continue

    if filename.endswith(".pyc"):
        filename = filename[:-1]

    if coverdir is None:
        dir = os.path.dirname(os.path.abspath(filename))
        modulename = _modname(filename)
    else:
        dir = coverdir
        if not os.path.exists(dir):
            os.makedirs(dir)
        modulename = _fullmodname(filename)

    # If desired, get a list of the line numbers which represent
    # executable content (returned as a dict for better lookup speed)
    if show_missing:
        lnotab = _find_executable_linenos(filename)
    else:
        lnotab = {}
    source = linecache.getlines(filename)  # <---- Maybe opening the file here
    coverpath = os.path.join(dir, modulename + ".cover")
    with open(filename, 'rb') as fp:   # <---- Opening the file here
        encoding, _ = tokenize.detect_encoding(fp.readline)
    n_hits, n_lines = self.write_results_file(coverpath, source,
                                              lnotab, count, encoding)
    ```

## Race Condition in os.makedirs (2007) https://github.com/python/cpython/issues/46016:
 - Addresses Race Condition but is superseeded by https://github.com/python/cpython/issues/53545

## Superseeder (2010) https://github.com/python/cpython/issues/53545:
 - Adds `exist_ok` kwarg but also introduces a security vulnerability, which is
   addressed in https://github.com/python/cpython/issues/65281

## Vulnerability fix (2014) https://github.com/python/cpython/issues/65281:
 - Some umask problem, I didn't read it all, but seems to be fixed, however the
   last comment (https://github.com/python/cpython/issues/65281#issuecomment-1093650697) was:

 benjaminp:
 > I've now removed the offending behavior. exist_ok is still racy because it
 > uses path.isdir() in the exceptional case, but fixing that can be an
 > enhancement elsewhere.

 So yeah there is still a problem lurking here, but I am not quite sure if it is
 relevant enough to be addressed in the case of this issue.

## Issue #25583: Avoid incorrect errors raised by `os.makedirs(..., exist_ok=True)`:

 - Changed some error handling but `os.path.isdir` is still used

```diff
tree 39ae79f83900575d6dba600ebec8deb3917508eb
parent 41f69f4cc7c977bd202545b8ada01b80a278d0e2
author Martin Panter <vadmium+py@gmail.com> Thu Nov 19 04:48:44 2015 +0000
committer Martin Panter <vadmium+py@gmail.com> Thu Nov 19 04:48:44 2015 +0000

Issue #25583: Avoid incorrect errors raised by os.makedirs(exist_ok=True)


diff --git a/Lib/os.py b/Lib/os.py
index a8f6a0b8db..27b241ae97 100644
--- a/Lib/os.py
+++ b/Lib/os.py
@@ -226,7 +226,7 @@ def makedirs(name, mode=0o777, exist_ok=False):
         try:
             makedirs(head, mode, exist_ok)
         except FileExistsError:
-            # be happy if someone already created the path
+            # Defeats race condition when another thread created the path
             pass
         cdir = curdir
         if isinstance(tail, bytes):
@@ -235,8 +235,10 @@ def makedirs(name, mode=0o777, exist_ok=False):
             return
     try:
         mkdir(name, mode)
-    except OSError as e:
-        if not exist_ok or e.errno != errno.EEXIST or not path.isdir(name):
+    except OSError:
+        # Cannot rely on checking for EEXIST, since the operating system
+        # could give priority to other errors like EACCES or EROFS
+        if not exist_ok or not path.isdir(name):
             raise
 ```

# TLDR: 
There is a possible race condition where after the `os.path.exists` an
`os.makedirs` call might fail if the directory is created in between. Using
`os.makedirs(..., exist_ok=True)` would somewhat solve this. However, there 
might still be a problem within `os.makedirs(..., exits_ok=True)`. At first glance it did not
seem to be that relevant to this issue. 

Moving the `os.makedirs` out of the if case might not be necessary, as it seems
to me that if the source directory is deleted we will fail as soon as we try to
retrieve the source via the `linecache` module given the source is not loaded.
Or as soon as we open the filename in order to retrieve the encoding.

@hellozee Does this somewhat match how you followed the issue?
