### ISSUE TITLE
On linux, numeric pad input is ignored when numlock off

### ISSUE THREAD

**Issue by 4d0431b7-1c16-4dc0-9659-d71b494e1d7b** [python/cpython#41237]
BPO | [1074333](https://bugs.python.org/issue1074333)
--- | :---
Nosy | @rhettinger, @terryjreedy

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2020-06-07.21:37:55.519>
created_at = <Date 2004-11-27.21:37:55.000>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'On linux, numeric pad input is ignored when numlock off'
updated_at = <Date 2020-06-07.21:37:55.514>
user = 'https://bugs.python.org/netvigator'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-07.21:37:55.514>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2020-06-07.21:37:55.519>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2004-11-27.21:37:55.000>
creator = 'netvigator'
dependencies = []
files = []
hgrepos = []
issue_num = 1074333
keywords = []
message_count = 13.0
messages = ['23350', '23351', '23352', '23353', '23354', '23355', '23356', '23357', '82122', '86363', '86364', '222771', '370912']
nosy_count = 2.0
nosy_names = ['rhettinger', 'terry.reedy']
pr_nums = []
priority = 'low'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1074333'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by hsantanna** [comment]
There is any way for making the Home key from keypad (KP_Home) to work just like the normal Home key with IDLE shell/editor?

And the same to KP_End, KP_Prior (PageUp) and KP_Next (PageDown).

The KP_Home, KP_End, KP_Prior and KP_Next keys doesn't work with IDLE on Linux (I didn't test it on MS Windows).

The expected behavior is the KP_Home to move the keyboard cursor to the begin of the line and the KP_End to move to the end of the line, just like Home and End keys.

Ctrl + KP_Home should move to the begin of the file and Ctrl + KP_End should move to the end of the file.

Shift modifier should be used to select text together with any of those keypad keys. But it depends on keyboard layout, for some (or most) keyboard layouts on Linux, Shift modifier will return a number when used together with keypad keys. For my keyboard layout Shift only modify the keypad keys if NumLock is active, so the expected behavior is that it triggers text selection.

Those expected behaviors works for almost any non TKinter applications on modern Linux desktops, ie, works on GTK or QT based software.

As already discussed for this bug, TK will not change it's own default behavior, since this is the desired behavior for some use cases.

That said, I ask, please, that this bug is re-opened
(or ask me and I will open a new bug for this).
