### ISSUE TITLE
provide a shlex.split alternative for Windows shell syntax

### ISSUE THREAD

**Issue by 2e8d23da-bac4-412b-8dc9-27a278f5f59e** [python/cpython#44990]
BPO | [1724822](https://bugs.python.org/issue1724822)
--- | :---
Nosy | @birkenfeld, @pfmoore, @ericvsmith, @pjenvey, @merwok, @bitdancer, @eli-schwartz

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2007-05-24.12:56:34.000>
labels = ['type-feature', 'OS-windows', 'docs']
title = 'provide a shlex.split alternative for Windows shell syntax'
updated_at = <Date 2019-10-08.17:47:27.613>
user = 'https://bugs.python.org/gjb1002'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-08.17:47:27.613>
actor = 'eschwartz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Windows']
creation = <Date 2007-05-24.12:56:34.000>
creator = 'gjb1002'
dependencies = []
files = []
hgrepos = []
issue_num = 1724822
keywords = []
message_count = 18.0
messages = ['55118', '55119', '55120', '55121', '55122', '55123', '55124', '55125', '55126', '55127', '55128', '93822', '116679', '116681', '116687', '116693', '130138', '141238']
nosy_count = 11.0
nosy_names = ['georg.brandl', 'paul.moore', 'ianbicking', 'titus', 'gjb1002', 'janssen', 'eric.smith', 'pjenvey', 'eric.araujo', 'r.david.murray', 'eschwartz']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'languishing'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1724822'
versions = ['Python 3.3']
```

</p></details>

**Comment by keelung-yang** [comment]
This issue is `opened on May 24, 2007`. Is there any update/response officially ?

**Comment by pfmoore** [comment]
The nearest you'll get to an official status is that no-one is currently working on this. And it'll stay like that until someone is interested enough in the problem to put together a proposal and an implementation that addresses the various questions and comments made here, and offers a genuinely useful cross-platform experience. One major issue that would need to be addressed, for example, is that on Windows, there isn't a single "shell syntax" to target - PowerShell and CMD have *very* different quoting rules, etc, and the fact that commands can do their own command line parsing (they get passed a command line string rather than an argument array) adds even *more* complexity.

On a purely personal note, I'm not convinced that it's even possible to write something that would be sufficiently general to be worth including in the stdlib (beyond what we currently have with the explicit limitation that it implements Unix-like semantics). I'd be happy to be proved wrong, but I'm not holding my breath ;-)

Having said all that, if you need something like this in the meantime, 3rd party solutions may well exist on PyPI, and even if there isn't anything that suits your constraints, you can write your own code that's tailored for your application.
