### ISSUE TITLE
abstract class instantiable when subclassing built-in types

### ISSUE THREAD

**Issue by e3c2cfe4-8fc4-40d8-9253-90242a0f2a80** [python/cpython#50246]
BPO | [5996](https://bugs.python.org/issue5996)
--- | :---
Nosy | @aleaxit, @rhettinger, @terryjreedy, @pitrou, @benjaminp, @jwilk, @merwok, @bitdancer, @thet, @durban, @eltoder, @ericsnowcurrently, @soltysh, @MojoVampire, @poleto, @zhangyangyu, @nathanielmanistaatgoogle, @DimitrisJim, @remilapeyre, @2xB
Files | <li>[abc.patch](https://bugs.python.org/file21600/abc.patch "Uploaded as text/plain at 2011-04-10.02:28:38 by @eltoder")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2009-05-11.14:06:01.619>
labels = ['3.8', 'type-bug', 'library', '3.9', '3.10']
title = 'abstract class instantiable when subclassing built-in types'
updated_at = <Date 2020-10-30.23:49:27.541>
user = 'https://github.com/thet'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-30.23:49:27.541>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2009-05-11.14:06:01.619>
creator = 'thet'
dependencies = []
files = ['21600']
hgrepos = []
issue_num = 5996
keywords = ['patch']
message_count = 16.0
messages = ['87574', '87576', '87854', '113698', '133440', '138411', '140108', '140114', '266704', '279479', '279481', '279483', '279484', '279499', '299815', '335337']
nosy_count = 24.0
nosy_names = ['aleax', 'rhettinger', 'terry.reedy', 'pitrou', 'nadeem.vawda', 'benjamin.peterson', 'jwilk', 'eric.araujo', 'r.david.murray', 'cvrebert', 'thet', 'daniel.urban', 'eltoder', 'eric.snow', 'maciej.szulik', 'josh.r', 'luiz.poleto', 'xiang.zhang', 'Kevin Shweh', 'Nathaniel Manista', 'Jim Fasarakis-Hilliard', 'remi.lapeyre', 'Jon McMahon', '2xB']
pr_nums = []
priority = 'low'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue5996'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by bitdancer** [comment]
Closed bpo-31127 as a duplicate of this one.

**Comment by Yc7521** [comment]
The reason for this bug is that the creation of the subclass avoids the invocation of the 'object_new' method (e.g. for built-in types or when `__new__` is overridden without calling `super().__new__`).
It seems that considering adding an abstract flag check in `tp_new_wrapper` could solve this issue.

some links:
[object_new](https://github.com/python/cpython/blob/aa0a73d1bc53dcb6348a869df1e775138991e561/Objects/typeobject.c#L4903)
[tp_new_wrapper](https://github.com/python/cpython/blob/aa0a73d1bc53dcb6348a869df1e775138991e561/Objects/typeobject.c#L7648)

A simple code for enforcing `ABC` check to correct the behavior. (only for fixing inheriting built-in types)
```python
class MyABC(ABC):
    def __new__(cls, *args, **kwargs):
        if len(cls.__abstractmethods__) > 0:
            raise TypeError("Can't instantiate abstract class MyABC with abstract methods test")
        return super().__new__(cls, *args, **kwargs)


ABC = MyABC
```

**Comment by gvanrossum** [comment]
I got as far as a repro, but this morning my Pooh brain doesn't follow the root cause. I'll come back to it.
```
import abc
class A(object, metaclass=abc.ABCMeta):
    @abc.abstractproperty
    def abstract(self): return True

class A2(dict, metaclass=abc.ABCMeta):
    @abc.abstractproperty
    def abstract(self): return True

a2 = A2()  # Passes
a = A()  # TypeError: Can't instantiate abstract class A with abstract methods abstract
```

**Comment by gvanrossum** [comment]
> The reason for this bug is that the creation of the subclass avoids the invocation of the 'object_new' method (e.g. for built-in types or when `__new__` is overridden without calling `super().__new__`).

You're right that it is because `object_new` isn't called when the base class is a builtin.

I'm skeptical of Python-level code whose `__new__` doesn't call `super().__new__`, because how would it come up with an object to return at all?

I'm also skeptical of putting anything in `tp_new_wrapper`, since that isn't called by e.g. `dict_new` nor by most other builtin types' `tp_new` callback.

One of the duplicates reported the same problem when inheriting from `Exception`, which doesn't even override `tp_new`, so there's something more going on there that I haven't tracked down yet.

My gut feeling still says that the exception you get for instantiating an abstract class is intended to be helpful,  but not a feature you can depend on, but that's at least in part because I don't know how to solve this yet without slowing down e.g. dict creation, which is pretty time sensitive.

**Comment by gvanrossum** [comment]
I'm tempted to close this as won't fix, unless there is further discussion. (A PR would also be helpful to focus the discussion; I'm not considering old patch files from bpo.)

**Comment by Yc7521** [comment]
Maybe someday someone will come up with a relatively good solution. At least this is indeed a bug.

**Comment by gvanrossum** [comment]
Thanks, it is indeed a bug, but we won't fix it (yet).
