### ISSUE TITLE
extend captured_output to simulate different stdout.encoding

### ISSUE THREAD

**Issue by eda57068-96ad-4b33-8431-9c528f59a6a6** [python/cpython#52230]
BPO | [7982](https://bugs.python.org/issue7982)
--- | :---
Nosy | @rhettinger, @ezio-melotti, @merwok, @florentx, @berkerpeksag, @adfrost
PRs | <li>python/cpython#15881</li>
Files | <li>[issue7982.diff](https://bugs.python.org/file35741/issue7982.diff "Uploaded as text/plain at 2014-06-23.16:36:33 by @berkerpeksag")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-02-22.13:09:16.348>
labels = ['easy', 'type-feature', 'tests']
title = 'extend captured_output to simulate different stdout.encoding'
updated_at = <Date 2019-12-04.00:48:48.735>
user = 'https://github.com/florentx'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-04.00:48:48.735>
actor = 'adfrost'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2010-02-22.13:09:16.348>
creator = 'flox'
dependencies = []
files = ['35741']
hgrepos = []
issue_num = 7982
keywords = ['patch', 'easy']
message_count = 6.0
messages = ['99730', '220756', '221366', '349927', '351743', '357772']
nosy_count = 7.0
nosy_names = ['rhettinger', 'ezio.melotti', 'eric.araujo', 'flox', 'berker.peksag', 'mike_hart', 'adfrost']
pr_nums = ['15881']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue7982'
versions = ['Python 3.5']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
It looks as the only difference is that you can specify encoding as the `captured_stdout()` instead of explicitly calling `encode()` for `getvalue()` result. It is too small benefit in comparison with the complicated implementation (+30 lines of new code, and I am not sure that it is enough). I does not even save a line of code.

Currently there are only 4 occurrences of `.getvalue().encode(` in the test code:
```
test/test_zipfile/test_core.py:3122:        expected = t.getvalue().encode('ascii', 'backslashreplace')
test/test_tarfile.py:2689:            expected = t.getvalue().encode('ascii', 'backslashreplace')
test/test_tarfile.py:2700:            expected = t.getvalue().encode('ascii', 'backslashreplace')
test/test_source_encoding.py:325:        out = stdout.getvalue().encode('latin1')
```
and I am not sure that they all are related to `captured_stdout()` or `captured_stderr()`. The example in https://github.com/python/cpython/issues/52230#issuecomment-1093493406 is the only one in which the proposed feature can be used. Other 3 examples require also the error handler. So for now it looks like complication without any benefit.

If you really need to simulate standard streams with different encodings, you need to add also support of `errors` and `newline` argument, and encode the written text immediately, so you can get encoding errors and partially written output. It will be a complex code if make it this way. The simplest way to do this is to use `contextlib.redirect_stdout()` with a `TextIOWrapper` that wraps a `BytesIO`. You do this if you need, and use simple `test.support.captured_stdout()` for common case.

**Comment by picnixz** [comment]
Closing as `not planned` since the benefits are too small and would be better suited for a utility function.
