### ISSUE TITLE
datetime naive and aware types should have a well-defined definition that can be cross-referenced

### ISSUE THREAD

**Issue by 9432cd65-9f88-4bc6-8ad6-72e5ab1c730d** [python/cpython#53068]
BPO | [8822](https://bugs.python.org/issue8822)
--- | :---
Nosy | @abalkin
Files | <li>[datetime_doc.patch](https://bugs.python.org/file23135/datetime_doc.patch "Uploaded as text/plain at 2011-09-12.20:30:50 by shaq"): Patch for datetime.rst</li><li>[datetime_doc_noreflow.patch](https://bugs.python.org/file23167/datetime_doc_noreflow.patch "Uploaded as text/plain at 2011-09-15.19:26:09 by shaq"): Patch for datetime.rst</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-05-26.12:07:26.281>
labels = ['3.10', 'docs']
title = 'datetime naive and aware types should have a well-defined definition that can be cross-referenced'
updated_at = <Date 2020-12-29.04:39:53.267>
user = 'https://bugs.python.org/techtonik'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-29.04:39:53.267>
actor = 'orsenthil'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2010-05-26.12:07:26.281>
creator = 'techtonik'
dependencies = []
files = ['23135', '23167']
hgrepos = []
issue_num = 8822
keywords = ['patch']
message_count = 13.0
messages = ['106524', '106614', '143930', '143936', '143937', '143938', '143939', '144091', '144094', '144096', '144099', '144101', '220773']
nosy_count = 5.0
nosy_names = ['belopolsky', 'techtonik', 'Alexander.Belopolsky', 'docs@python', 'shaq']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue8822'
versions = ['Python 3.10']
```

</p></details>

**Comment by slateny** [comment]
It looks to me that the [current document](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects) addresses the main concerns here: the wording regarding types is clarified, there is an anchor to the aware/naive objects, and aware/naive are marked bold for clarity. There's also a [pretty clear section](https://docs.python.org/3/library/datetime.html#determining-if-an-object-is-aware-or-naive) on determining when an object's aware/naive.

Since these sections are at the top of the document, imo they've got good enough visibility that not linking every instance of aware/naive is fine, so I think this can be considered resolved. If there are unaddressed issues though, feel free to comment/reopen.
