### ISSUE TITLE
platform.architecture() gives misleading results for OS X multi-architecture executables

### ISSUE THREAD

**Issue by ned-deily** [python/cpython#54944]
BPO | [10735](https://bugs.python.org/issue10735)
--- | :---
Nosy | @malemburg, @ronaldoussoren, @pitrou, @ned-deily
Files | <li>[issue10735-py3k.patch](https://bugs.python.org/file20108/issue10735-py3k.patch "Uploaded as text/plain at 2010-12-19.08:56:57 by @ned-deily"): Issue10735 py3k patch rev 1</li><li>[issue10735-27.patch](https://bugs.python.org/file20109/issue10735-27.patch "Uploaded as text/plain at 2010-12-19.08:57:27 by @ned-deily"): Issue10735 2.7 patch rev 1</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/malemburg'
closed_at = None
created_at = <Date 2010-12-19.06:28:26.329>
labels = ['OS-mac', 'type-bug', 'library', '3.7']
title = 'platform.architecture() gives misleading results for OS X multi-architecture executables'
updated_at = <Date 2017-02-20.19:21:51.899>
user = 'https://github.com/ned-deily'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-20.19:21:51.899>
actor = 'lemburg'
assignee = 'lemburg'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'macOS']
creation = <Date 2010-12-19.06:28:26.329>
creator = 'ned.deily'
dependencies = []
files = ['20108', '20109']
hgrepos = []
issue_num = 10735
keywords = ['patch']
message_count = 13.0
messages = ['124331', '124333', '124349', '124351', '124352', '124376', '124445', '124448', '130703', '130730', '130738', '288227', '288228']
nosy_count = 4.0
nosy_names = ['lemburg', 'ronaldoussoren', 'pitrou', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue10735'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by malemburg** [comment]
I think there's a misunderstanding in what platform.architecture() is meant for. The purpose is to find out more details about the executable you pass to it, e.g. whether it's a 32-bit or 64-bit binary, or whether it's an ELF or PE binary. And it's a best effort API, just as most other platform APIs - this is also the reason why most of them have parameters available to modify the default return values.

It doesn't work with multi-architecture executables. We'd need a new API for this.

Regarding returning multiple architectures in the linkage return value: I'm not sure whether that's a good idea. The architectures are not necessarily of different linkage types. In fact on Macs, the correct values is "Mach-O". The API should probably return this instead of the default empty string.

**Comment by malemburg** [comment]
The term "linkage" is probably a misnomer... "execformat" would be more correct:

 * https://en.wikipedia.org/wiki/Comparison_of_executable_file_formats

Too late to change, I guess.

**Comment by ronaldoussoren** [comment]
Let's close this issue, it is not relevant for current versions of macOS because macOS 10.15 and later no longer support 32-bit code (10.15 was released in 2019) and therefore ``platform.architecture`` will do the right thing on current releases.  It is IMHO not worthwhile to try to design a solution for this issue that's only useful on old versions of macOS.

**Comment by malemburg** [comment]
> Let's close this issue, it is not relevant for current versions of macOS because macOS 10.15 and later no longer support 32-bit code (10.15 was released in 2019) and therefore `platform.architecture` will do the right thing on current releases. It is IMHO not worthwhile to try to design a solution for this issue that's only useful on old versions of macOS.

Ok, makes sense.
