### ISSUE TITLE
Increase pickle compatibility

### ISSUE THREAD

**Issue by e26428b1-70cf-4e9f-ae3c-9ef0478633fb** [python/cpython#57775]
BPO | [13566](https://bugs.python.org/issue13566)
--- | :---
Nosy | @terryjreedy, @pitrou, @vstinner, @avassalotti, @serhiy-storchaka, @vajrasky, @MojoVampire
Files | <li>[pickle_old_strings.patch](https://bugs.python.org/file39348/pickle_old_strings.patch "Uploaded as text/plain at 2015-05-12.09:17:43 by @serhiy-storchaka")</li><li>[pickle-old-strings-2.patch](https://bugs.python.org/file46703/pickle-old-strings-2.patch "Uploaded as text/plain at 2017-03-06.07:41:31 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2011-12-09.13:25:03.645>
labels = ['3.7', 'type-feature', 'library']
title = 'Increase pickle compatibility'
updated_at = <Date 2017-03-06.16:02:42.072>
user = 'https://bugs.python.org/sbt'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-06.16:02:42.072>
actor = 'josh.r'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2011-12-09.13:25:03.645>
creator = 'sbt'
dependencies = []
files = ['39348', '46703']
hgrepos = []
issue_num = 13566
keywords = ['patch']
message_count = 16.0
messages = ['149092', '149101', '149104', '205445', '206504', '206532', '206536', '242949', '245048', '245049', '245050', '245051', '245056', '245057', '288158', '289119']
nosy_count = 9.0
nosy_names = ['terry.reedy', 'pitrou', 'vstinner', 'alexandre.vassalotti', 'sbt', 'Ramchandra Apte', 'serhiy.storchaka', 'vajrasky', 'josh.r']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue13566'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
This is a problem when pickle data in Python 3 for unpickling in Python 2.

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
Right, but Antoine's objection is that suddenly strs pickled in Py3 can end up as strs in Py2, rather than unicode. If the library enforces a Py3-like type separation on Py2 (text arguments are unicode only, binary data is str only), then you have the problem where pickling on Py3 produces a pickle that will unpickle as str on Py2, and suddenly the library explodes because the argument, that should be unicode on Py2 and str on Py3, is suddenly str on both.

This means that, to fix a problem with non-forward compatible libraries (that accept text only as Py2 str), a Py2 library that's (very) forward thinking would have problems.

Admittedly, I wouldn't expect there to be very many such libraries, and many of them would have their own custom pickle formats, but stuff like numpy is quite sensitive to argument type; numpy.array(u'123') and numpy.array(b'123') are different. In numpy's case, each of those produces a derived datatype that is explicitly pickled and (I believe) would prevent the error, but some other more heuristic library might not do so.

**Comment by serhiy-storchaka** [comment]
Since Python 2 has reached its EOL, this issue is no longer actual.
