### ISSUE TITLE
Support display of both __cause__ and __context__

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#59010]
BPO | [14805](https://bugs.python.org/issue14805)
--- | :---
Nosy | @ncoghlan, @pjenvey, @meadori, @serhiy-storchaka
Dependencies | <li>bpo-14133: improved PEP 409 implementation</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-05-14.12:00:38.996>
labels = ['interpreter-core', 'type-feature', 'library']
title = 'Support display of both __cause__ and __context__'
updated_at = <Date 2013-04-20.19:16:46.060>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2013-04-20.19:16:46.060>
actor = 'pjenvey'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'Library (Lib)']
creation = <Date 2012-05-14.12:00:38.996>
creator = 'ncoghlan'
dependencies = ['14133']
files = []
hgrepos = []
issue_num = 14805
keywords = []
message_count = 3.0
messages = ['160609', '187446', '187451']
nosy_count = 8.0
nosy_names = ['ncoghlan', 'pjenvey', 'Arfrever', 'cvrebert', 'poke', 'meador.inge', 'serhiy.storchaka', 'isoschiz']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue14805'
versions = ['Python 3.3']
```

</p></details>

**Comment by stevendaprano** [comment]
@ gvanrossum [says](https://discuss.python.org/t/proposal-close-old-feature-request-issues-language-summit-follow-up/15776/6) says that the current behaviour is by design, and this ticket should be closed.

I asked [why the design is intended](https://discuss.python.org/t/proposal-close-old-feature-request-issues-language-summit-follow-up/15776/7) (since neither the PEP nor the documentation explains) and Guido says I should ask it here.

**Comment by gvanrossum** [comment]
I suppose the reason is that if you take both cause and context into account, you end up with a tree -- each cause may itself have another cause *and* another context, and ditto for each context. Displaying such a tree (where each node is a traceback that could be many stack frames deep) would be complicated, and probably produce more confusion than understanding in most users. Plus, because cause is set explicitly while context is implicit, it stands to reason that when the failing code indicates a context, the cause is not important enough to display.
