### ISSUE TITLE
zipimport needs to support namespace packages when no 'directory' entry exists

### ISSUE THREAD

**Issue by ericvsmith** [python/cpython#59110]
BPO | [14905](https://bugs.python.org/issue14905)
--- | :---
Nosy | @warsaw, @gpshead, @pjeby, @ronaldoussoren, @ncoghlan, @ericvsmith, @ericsnowcurrently, @serhiy-storchaka, @phmc
Files | <li>[zipimport-issue14905.patch](https://bugs.python.org/file26302/zipimport-issue14905.patch "Uploaded as text/plain at 2012-07-07.14:47:49 by jerub")</li><li>[zipimport-issue14905-2.patch](https://bugs.python.org/file26894/zipimport-issue14905-2.patch "Uploaded as text/plain at 2012-08-19.12:59:23 by jerub")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-05-25.00:27:06.530>
labels = ['3.8', 'type-feature', 'library']
title = "zipimport needs to support namespace packages when no 'directory' entry exists"
updated_at = <Date 2020-08-13.13:47:03.805>
user = 'https://github.com/ericvsmith'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-13.13:47:03.805>
actor = 'pconnell'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-05-25.00:27:06.530>
creator = 'eric.smith'
dependencies = []
files = ['26302', '26894']
hgrepos = []
issue_num = 14905
keywords = ['patch']
message_count = 16.0
messages = ['161543', '161544', '161584', '164861', '168568', '182245', '182254', '182255', '182279', '182326', '185799', '185936', '186026', '325724', '325764', '375307']
nosy_count = 14.0
nosy_names = ['barry', 'gregory.p.smith', 'pje', 'ronaldoussoren', 'ncoghlan', 'jerub', 'eric.smith', 'Arfrever', 'eric.snow', 'serhiy.storchaka', 'jpaugh', 'pconnell', 'isoschiz', 'superluser']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue14905'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-121233
* gh-121375
* gh-121378

**Comment by jaraco** [comment]
I stumbled onto this issue while working on https://github.com/python/importlib_resources/issues/287. In https://github.com/python/importlib_resources/commit/496acc1a0d8018c830b30a3a28826c9b101975fa, I factored out the zip files that the tests use to dynamically generate the zip fixtures so that I could extend the tests to have namespace support. I then pointed it at the namespace fixtures (https://github.com/python/importlib_resources/commit/f0e9a45c96c74c7f9364b8e5bb7aa701a1fdb04c), but was surprised when `namespacedata01` wasn't importable.

I additionally encountered the issue previously in #80921.

When I was developing `zipfile.Path`, I found that zipfiles without explicit directory entries were common enough that I added support for them (https://github.com/jaraco/zipp/issues/4) and later developed [performance optimizations](https://github.com/python/cpython/blob/add16f1a5e4013f97d33cc677dc008e8199f5b11/Lib/zipfile/_path/__init__.py#L86-L167) to minimize the performance impacts.

Perhaps that work can be re-purposed to give the zip importer the CompleteDirs treatment and resolve this issue.

**Comment by serhiy-storchaka** [comment]
#121233 is slightly different from the patches proposed earlier, but the effect is the same. It may be faster for large archives with deep structure, although the difference may be insignificant. It also fixes `get_data()` and adds many new tests.
