### ISSUE TITLE
argparse: positional arguments containing - in name not handled well

### ISSUE THREAD

**Issue by a01efe54-0922-416c-a318-dff8f40521de** [python/cpython#59330]
BPO | [15125](https://bugs.python.org/issue15125)
--- | :---
Nosy | @merwok, @bitdancer, @florentx, @vadmium, @khughitt, @shihai1991
Files | <li>[argparse-argument-names.diff](https://bugs.python.org/file26286/argparse-argument-names.diff "Uploaded as text/plain at 2012-07-07.10:24:46 by mapleoin")</li><li>[15125-1.patch](https://bugs.python.org/file27860/15125-1.patch "Uploaded as text/plain at 2012-11-03.18:01:11 by sfllaw")</li><li>[15125-2.patch](https://bugs.python.org/file27863/15125-2.patch "Uploaded as text/plain at 2012-11-03.19:25:19 by sfllaw")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-06-21.15:34:07.013>
labels = ['3.11', 'type-bug', '3.9', '3.10', 'docs']
title = 'argparse: positional arguments containing - in name not handled well'
updated_at = <Date 2021-12-10.17:15:56.002>
user = 'https://bugs.python.org/nstiurca'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-10.17:15:56.002>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2012-06-21.15:34:07.013>
creator = 'nstiurca'
dependencies = []
files = ['26286', '27860', '27863']
hgrepos = []
issue_num = 15125
keywords = ['patch']
message_count = 22.0
messages = ['163340', '163383', '163456', '163457', '163461', '164789', '164792', '164808', '164968', '165060', '165067', '166181', '174655', '174656', '174660', '174677', '174725', '225527', '225628', '225744', '348622', '350811']
nosy_count = 14.0
nosy_names = ['bethard', 'sfllaw', 'eric.araujo', 'r.david.murray', 'flox', 'docs@python', 'tshepang', 'martin.panter', 'paul.j3', 'nstiurca', 'mapleoin', 'khughitt', 'Socob', 'shihai1991']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue15125'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-104092
* gh-125215

**Comment by stdedos** [comment]
As this looks like it's not getting handled anytime soon, will the upstream accept _at least_ a documentation update here https://docs.python.org/3/library/argparse.html#dest, explicitly mentioning that "positional arguments are **not** `s/-/_/g` converted"?

**Comment by merwok** [comment]
Yes, a doc PR would get reviewed.

**Comment by furkanonder** [comment]
The [PR](https://github.com/python/cpython/pull/104092) is ready for review.

**Comment by serhiy-storchaka** [comment]
There are issues with the proposed patches and #104092.

* It changes also the default value for metavar.
* It does not handle setattr and delattr.
* And, most importantly, `Namespace` is only the default class for namespace. The user can use arbitrary object as a namespace. This cannot be fixed.

So, if we still want to implement name mangling for positional parameters, I suggest the following 3-step plan:

* Update the documentation.
* Start emitting a FutureWarning for names containing `'-'`.
* After few releases remove the warning and make the code replacing `'-'` with `'_'`.

**Comment by serhiy-storchaka** [comment]
@sfllaw, is it your patches? Are you interesting in creating a PR based on [15125-1.patch](https://bugs.python.org/file27860/15125-1.patch)?

**Comment by sfllaw** [comment]
@serhiy-storchaka Sorry, but I no longer have good context for this patch. Please feel free to use it as a basis for your own PR, since you appear to have thought about this recently!

**Comment by serhiy-storchaka** [comment]
Created #125215 based on [15125-1.patch](https://bugs.python.org/file27860/15125-1.patch). Thank you for your contribution @sfllaw.

**Comment by mh-dm** [comment]
As a new user of argparse I've hit this issue and the experience was just bad and the workaround and documentation is far from optimal. Please reopen this issue!

1) Reading through this and #95100 there is agreement that that it would be nice if the behavior were normalized between positional and optional args.
2) The documentation and behavior is still confusing. Do you really want every single developer that adds a two or more words positional argument to have to learn the details and differences of specifying `'foo-bar'`, `dest='foo_bar'` and `'metavar='foo-bar'`?
3) The current behavior resists any future attempts at fixing it, even in a python 4 / with a long deprecation notice.

Let's go through the new developer experience that already has some args:
```python
    parser.add_argument('--input-file')
    parser.add_argument('file')
    args = parser.parse_args()
    # Using args.input_file, args.file is fine
```

Let's be more explicit about what 'file' is with `parser.add_argument('output-file')`. Using `args.output_file` we get:
```
AttributeError: 'Namespace' object has no attribute 'output_file'
```
Quick investigation with `print(args)`:
```Namespace(input_file=None, **{'output-file': 'foo'})```

Weird, but I there's this `dest` option for specifying where I want my output to go and which a quick read of the [documentation](https://docs.python.org/3/library/argparse.html) confirms: "The name of the attribute to be added to the object returned by parse_args()" and "The name of this attribute is determined by the dest keyword argument of add_argument(). For positional argument actions, dest is normally supplied as the first argument to add_argument()". So:

```python
    parser.add_argument('output-file', dest='output_file')
```
which results in
```
ValueError: dest supplied twice for positional argument
```
Excuse me, what? That's not what "normally supplied" means.

Or, after PR #125215 the error is:
`dest supplied twice for positional argument, did you mean metavar?`

NO, I don't mean metavar. `parser.add_argument('output-file', metavar='output_file')` is literally the opposite of what I wanted.

Then you read more and realize that you have to do this:
```python
    parser.add_argument('output_file', metavar='output-file')
    # OR
    parser.add_argument(metavar='output-file', dest='output_file')
```

Both versions are not intuitive and would be harder to automatically migrate in a future major release that fully fixes the issue.

## PROPOSAL
Please fix `parser.add_argument('output-file', dest='output_file')` to work as expected. This fix is backwards compatible because existing code that uses it is already 'broken' (currently raises the `dest supplied twice` error). It's also compatible with a future fix in say a python 4 that would process `parser.add_argument('output-file')` just like `parser.add_argument('--input-file')`.
It also provides an easy automated upgrade path from python 3 to 4: any existing `add_argument('foo-bar')` can be machine translated to `add_argument('foo-bar', dest='foo-bar')`.
