### ISSUE TITLE
PyType_FromSpec should take metaclass as an argument

### ISSUE THREAD

**Issue by abalkin** [python/cpython#60074]
BPO | [15870](https://bugs.python.org/issue15870)
--- | :---
Nosy | @loewis, @jcea, @amauryfa, @abalkin, @pitrou, @encukou, @lekma, @mattip, @zooba, @seberg, @ctismer
Files | <li>[typeobject.diff](https://bugs.python.org/file27137/typeobject.diff "Uploaded as text/plain at 2012-09-06.15:49:23 by @abalkin")</li><li>[typeobject.patch](https://bugs.python.org/file50285/typeobject.patch "Uploaded as text/plain at 2021-09-17.22:54:10 by @seberg")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/abalkin'
closed_at = None
created_at = <Date 2012-09-06.15:49:25.705>
labels = ['interpreter-core', 'type-feature', '3.11']
title = 'PyType_FromSpec should take metaclass as an argument'
updated_at = <Date 2021-10-12.13:28:38.470>
user = 'https://github.com/abalkin'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-12.13:28:38.470>
actor = 'petr.viktorin'
assignee = 'belopolsky'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2012-09-06.15:49:25.705>
creator = 'belopolsky'
dependencies = []
files = ['27137', '50285']
hgrepos = []
issue_num = 15870
keywords = ['patch', 'needs review']
message_count = 40.0
messages = ['169925', '169928', '169929', '169940', '169942', '169943', '169944', '169951', '169955', '169972', '169977', '398430', '398435', '398751', '398776', '401642', '401651', '401781', '402105', '402511', '402517', '402520', '402521', '402522', '402527', '402551', '402729', '402733', '402734', '402735', '402737', '402738', '402751', '402753', '402793', '402800', '402806', '403231', '403257', '403730']
nosy_count = 16.0
nosy_names = ['loewis', 'jcea', 'amaury.forgeotdarc', 'belopolsky', 'pitrou', 'Arfrever', 'petr.viktorin', 'lekma', 'Alexander.Belopolsky', 'mattip', 'Robin.Schreiber', 'steve.dower', 'seberg', 'Christian.Tismer', 'jhaberman', 'haberman2']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue15870'
versions = ['Python 3.11']
```

</p></details>

**Comment by wjakob** [comment]
Hi @seberg and @encukou,

I just stumbled across this issue along with https://github.com/python/cpython/issues/89546 and was wondering what the current status of these issues is?

My use case is  for a binding tool ([nanobind])(https://github.com/wjakob/nanobind)). I would like to allocate a type that is larger than a `PyHeapTypeObject` so that the binding library can stash some information about the associated C++ there.

The puzzle in my case is that

- `PyType_FromModuleAndSpec` doesn't accept a metaclass. This would have been a nice way to request more memory by specifying a larger `tp_basicsize` in the metaclass.

- Calling the metaclass constructor manually `PyObject_Call(callable, args, kwargs)` can create a correctly-sized heap object, but this doesn't allow setting many low-level type flags.

- In principle, those could be mixed as pointed out above This is a no-go for a binding tool since it will mess up the inheritance chain with classes that don't have a C++ counterpart.

**Comment by wjakob** [comment]
A side comment: the initial patch associated with this PR looked perfectly good to me (modulo, perhaps, the naming that was being discussed). Short and simple. What do you think about reviving this change and rebasing it on the latest Python version?

**Comment by seberg** [comment]
@wjakob I think you should look at gh-89546 where I think we managed to clarify a bit how this should develop.  I (and maybe also Petr) mean to come back to this at some point for NumPy (I need to make the new NumPy DTypes compatible with the "limited API"), but it has not managed to top my priority/interest list for a while.

**Comment by wjakob** [comment]
I commented here, because this other PR does not look like it would fix my issue: there might not be a base class with a suitable metaclass -- it should be possible to allocate a sufficiently large PyTypeObject even in such a case.

**Comment by wjakob** [comment]
I am also curious what was wrong with the solution proposed here? It seems that the discussion got hung up on a really minor technical issue (whether to pass in the metaclass as a function argument or as a slot member, and what's valid to pass as a `void*` pointer)

**Comment by seberg** [comment]
I cannot say why each of the proposals did not really follow up on.  Probably because it is tricky and nobody pushed much more.  I had a PR to just increase the allocation size, but never polished up the tests (plus I now think we it should be restricted it a bit more then I did).

However, I now think that we figured out some stuff in gh-89546 in that:
1. `PyType_FromSpec` should query the metaclass and allocate it.  But, we likely should reject creating the class if the metaclass has a custom `__new__`, because the class that comes out may be broken if its `__new__` is not called.  If all it has is a custom alloc/basicsize we are fine though (there is no custom `__new__`).
2. A new function `PyType_ApplySpec` seems likely like the better approach if you are looking into expanding the API (as you seem to require)?  This would give something like a `super().__new__()` for a metaclass `__new__` to use.


But I don't know, maybe the approach proposed here has its advantages, I can't say I reread the whole discussion here, things had just made a lot more sense to me after the discussion in gh-89546 so I thought it might be the more worthwhile path to persue.

**Comment by erlend-aasland** [comment]
I think we can close this. @encukou?

**Comment by encukou** [comment]
Yes, with a note that #89546 follows up on this.
Thanks for the ping!

**Comment by ctismer** [comment]
Hi @wjakob We got a big problem with this change.
Since I tried Python 3.12.0a4 today on PySide6, we cannot build any more.
Reason: The Message
> Metaclasses with custom tp_new are not supported

We use the feature heavily to use our own new function on a meta class.
Why is this no longer supported?
Is there an easy work-around possible?

All the best -- Chris

**Comment by mattip** [comment]
@ctismer I think you should be using [`PyType_FromMetaclass` on 3.12](https://docs.python.org/3.12/c-api/type.html?highlight=pytype_frommetaclass#creating-heap-allocated-types)

**Comment by mattip** [comment]
[here](https://github.com/wjakob/nanobind/blob/master/src/nb_type.cpp#L452) is the work-around in nanobind for versions before 3.12

**Comment by ctismer** [comment]
@mattip Versions before 3.12 are no problem. And whatever I do gets redirected to PyType_FromMetaclass in 3.12, which then forbids tp_new. 
I was never stuck, but now I am. Why is tp_new changing not allowed?

**Comment by seberg** [comment]
There was more discussion on the newer PR I think, but also here: gh-89546.  The issue is that the `super().__new__()` cannot be called and Petr at that time suggested a second function may be necessary, but I think later it was thought/hoped that just wouldn't be needed.

**Comment by ctismer** [comment]
@seberg Thanks a lot, now I understand the problem better. And as I read all the discussions, the tp_new problem was not solved in the end, although there was a plan. 

On first glance I was happy that this hackery around PyType_* would come to an end, but with the redirections leading always into PyType_FromMetaclass, there is effectively a new restriction that was not present before. 
I need to test if some hacking aftter the fact can work around that.

**Comment by encukou** [comment]
If there is a `tp_new`, what *should* `PyType_FromMetaclass` (or any type creation function that doesn't take `*args, **kwargs`) do?

**Comment by ctismer** [comment]
It should simply do nothing but accept it as-is. 

Before the new function existed, we supplied the metatype after type crestion. 
That should simply work as before. We do not supply the metatype to PyType_From*, but some helper function now grabs the likely metatype from the bases, adds it and then complains about our tp_ new. 
We don‘t have a chance to patch it ourselves any more. 
I don‘t complain about the new function, this may be ok for the use cases. But it should not be greedy and leave my patching alone. This is not an addition to the API but it removes functionality without replacement.

**Comment by seberg** [comment]
Before the new function existed PySide worked by pure luck because Python always allocated one slot extra which happened to be enough for its use-case.  (It worked for PySide, but not really anyone else, took me weeks to fully understand probably at the time.)

In NumPy I currently also have a tp_new, all it does is reject creation, though.  IIRC there was a point that it should be OK to do without/remove (I don't remember the actual point, but trusted it at the time).  (NumPy's hacks are deep enough they should keep working in 3.12 for the time being.)

So, I agree we need to find a solution.  But we should also ask the question if you actually need the `tp_new`, and whether the right approach is not to allow it but to add a way to write a "C new" function for metaclasses.

**Comment by encukou** [comment]
> It should simply do nothing but accept it as-is.

That means it would create an object without calling its C-level initialization function. That sounds pretty dangerous -- most `tp_new` set up some invariant you should then be able to rely on.
I don't understand the use case here. Why do you have a `tp_new` that should *not* be called at instance creation?

> add a way to write a "C new" function for metaclasses

But does that “C new” need to be a slot? It probably needs a custom signature -- if you can fit in `*args, **kwargs` you should be able to use `tp_new`, and call the metatype to create subclasses. And if that's the case, there's not much point in letting Python or other extensions know about it -- it can just be a C function you export.

**Comment by seberg** [comment]
> But does that “C new” need to be a slot?

No, of course not.  In the old issue you had brought up a `PyType_ApplySpec` as a raw interface to creating a new class instance.  Having such a function would then allow me in NumPy for example to have a C-API function:
```
DTypeMeta
PyArray_CreateNewDTypeFromSpec(DTypeMeta_Spec *spec)
{
    newtype = alloc_metatype();
    PyType_ApplySpec(newtype, some_spec);
    /* Do more initialization stuff */
    return newtype;
}
```

Now, I am not convinced we need this, because all I currently need in NumPy is rejecting creation in Python.  And if I would want more, I would just create a factory function anyway, probably:
```
@create_dtype
class SomeClass:
    ...
```
which is more than enough probably.

**Comment by encukou** [comment]
> all I currently need in NumPy is rejecting creation in Python

Is doing that in `tp_init` not enough?
I guess there is a way to bypass `tp_init` from Python, but 

>  In the old issue you had brought up a `PyType_ApplySpec` as a raw interface to creating a new class instance.

A good first step would be `PyType_SetSlot`, initially with a small subset of settable slots (for some slots, setting them after creation is tricky). (BTW, that would bring us closer to [Mark's sketch of a perfect API](https://github.com/markshannon/New-C-API-for-Python/issues/4), while keeping current C signatures.)

**Comment by ctismer** [comment]
> So, I agree we need to find a solution. But we should also ask the question if you actually need the `tp_new`, and whether the right approach is not to allow it but to add a way to write a "C new" function for metaclasses.

PySide has a meta type `Shiboken.ObjectType` which is used in all PySide classes.
When a wrapper type is initialized, its type is created this way.
This code existed long before my time in PySide1. When I moved to Qt5 (2015) and then limited API (2017), 
the trouble began. 😉 

Basically, we add some extra attributes to the meta type. But in 2021, supporting PyPy forced me to
put these extras into a shadow structure, anyway. So it might be possible to add them later when the type
creation is over. I'm currently investigating that.

**Comment by ctismer** [comment]
@seberg I have a crude fix:
Before calling `PyType_FromSpecWithBases` or `PyType_FromMetaclass`, I patch an eventually 
existing `tp_new` away and restore it right afterwards. This gives the same behavior as before.
It does not hurt (but the brain) , because only the type slot is temporarily changed, but the `__new__` 
function is still in the already initialized meta type.

As soon as a proper "C new" function is available, I will remove that hack. But it serves me well,
for heaven's sake. You could do the same BTW. to your NumPy tp_new.

Hoping for a wise decision on this weird issue 😄 

So long -- Chris

**Comment by encukou** [comment]
Sorry for dropping the ball here.

The behavior change is backwards incompatible. If refusing to create classes with `__new__` is better than silently skipping it (as I think it is), there should at least be a deprecation warning period, at least in the pre-existing functions.
I'll do that for 3.12.

I assume this won't really help you since PySide will want to avoid deprecation warnings, though...
As hacky as it is, patching `tp_new` away at least says *I don't want `tp_new` called and I know what I'm doing* explicitly.

**Comment by ctismer** [comment]
@encukou Whatever the outcome, it's fine with me. The most important thing is a stable status that will not change for the time being.
All the best -- Chris
