### ISSUE TITLE
ArgumentParser inconsistent with parse_known_args

### ISSUE THREAD

**Issue by 698a88e8-ff26-4994-9f86-79f7dc89f86c** [python/cpython#60346]
BPO | [16142](https://bugs.python.org/issue16142)
--- | :---
Nosy | @bitdancer, @osandov, @aeros, @benedwards14
Files | <li>[aparse.py](https://bugs.python.org/file27434/aparse.py "Uploaded as text/plain at 2012-10-05.14:53:20 by idank")</li><li>[dashku.patch](https://bugs.python.org/file29910/dashku.patch "Uploaded as text/plain at 2013-04-17.22:38:07 by paul.j3")</li><li>[dashku.patch](https://bugs.python.org/file30056/dashku.patch "Uploaded as text/plain at 2013-04-29.07:01:54 by paul.j3")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-10-05.14:53:21.479>
labels = ['easy', 'type-bug', 'library']
title = 'ArgumentParser inconsistent with parse_known_args'
updated_at = <Date 2019-11-12.21:46:41.296>
user = 'https://bugs.python.org/idank'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-12.21:46:41.296>
actor = 'LewisGaul'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-10-05.14:53:21.479>
creator = 'idank'
dependencies = []
files = ['27434', '29910', '30056']
hgrepos = []
issue_num = 16142
keywords = ['patch', 'easy']
message_count = 10.0
messages = ['172088', '172089', '172091', '172092', '173492', '173640', '181167', '187212', '188038', '355469']
nosy_count = 11.0
nosy_names = ['bethard', 'r.david.murray', 'idank', 'paul.j3', 'Sam.Breese', 'Radu.Ciorba', 'Andrei.Vereha', 'osandov', 'kynikos', 'aeros', 'benedwards14']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16142'
versions = ['Python 2.7', 'Python 3.3']
```

</p></details>

### Linked PRs
* gh-103197
* gh-114180
* gh-115674
* gh-115675

**Comment by furkanonder** [comment]
The [PR](https://github.com/python/cpython/pull/103197) is ready for review.

**Comment by serhiy-storchaka** [comment]
For `-k=unknown` it gives `(Namespace(known=True), ['-u', '-n', '-n', '-o', '-w', '-n'])`.

**Comment by serhiy-storchaka** [comment]
I tested different corner cases, and neither proposed patches, nor PR #103197 handle them correctly.

If `-k` and `-n` are known flags:

`-kunknown` should recognize `-k` and leave `-unknown`, because we do not know whether unknown option `-u` takes argument or not.
`-k=unknown` should be an error, because `-k` has an explicit argument here.
`-knew` should recognize `-k` and `-n` and leave `-ew`.
`-k-new` should be an error, because a single-dash option cannot be `--`, and it cannot leave a double-dash option `--new`.
`-kn-ew` should be an error, for same reason.
`-kn=ew` should be an error, because `-n` has an explicit argument here.
`-kne-w` should recognize `-k` and `-n` and leave `-e-w`.
`-kne=w` should recognize `-k` and `-n` and leave `-e=w`.

#114180 handles all these corner cases (and maybe more). It is much more complex than the original patch.
