### ISSUE TITLE
wrong type for wintypes.BYTE

### ISSUE THREAD

**Issue by 9432cd65-9f88-4bc6-8ad6-72e5ab1c730d** [python/cpython#60580]
BPO | [16376](https://bugs.python.org/issue16376)
--- | :---
Nosy | @amauryfa, @abalkin, @meadori
Files | <li>[Issue16376.diff](https://bugs.python.org/file35940/Issue16376.diff "Uploaded as text/plain at 2014-07-13.14:48:39 by BreamoreBoy"): Change BYTE definition fron c_byte to c_ubyte</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-10-31.17:02:55.557>
labels = ['ctypes', 'type-bug', '3.9', '3.10', '3.11']
title = 'wrong type for wintypes.BYTE'
updated_at = <Date 2021-06-17.10:29:15.374>
user = 'https://bugs.python.org/techtonik'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-17.10:29:15.374>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2012-10-31.17:02:55.557>
creator = 'techtonik'
dependencies = []
files = ['35940']
hgrepos = []
issue_num = 16376
keywords = ['patch']
message_count = 2.0
messages = ['174331', '222935']
nosy_count = 4.0
nosy_names = ['amaury.forgeotdarc', 'belopolsky', 'techtonik', 'meador.inge']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16376'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-97579

**Comment by elibroftw** [comment]
This bug can cause people to make grave mistakes when using WIndows APIs. I"m assuming this is a simple fix.
Just because "cbytes" tests pass does not mean practical tests will pass. Take for example
https://stackoverflow.com/a/6156606/7732434

Run this code as shown and then run the code with types `ctypes.c_ubyte` instead of `wintypes.BYTE`. You can see that the latter works as expected according to Microsofts own specs as seen in the link below.

https://learn.microsoft.com/en-us/windows/win32/api/winbase/ns-winbase-system_power_status

**Comment by arhadthedev** [comment]
Fixed by gh-97579; no backporting is planned.
