### ISSUE TITLE
The sqlite3 context manager does not work with isolation_level=None

### ISSUE THREAD

**Issue by bitdancer** [python/cpython#61162]
BPO | [16958](https://bugs.python.org/issue16958)
--- | :---
Nosy | @loewis, @bitdancer, @Kodiologist, @corona10, @coleifer, @erlend-aasland

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-01-14.00:46:44.408>
labels = ['extension-modules', 'type-bug', 'library']
title = 'The sqlite3 context manager does not work with isolation_level=None'
updated_at = <Date 2022-03-29.16:07:14.645>
user = 'https://github.com/bitdancer'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-29.16:07:14.645>
actor = 'corona10'
assignee = 'ghaering'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Library (Lib)']
creation = <Date 2013-01-14.00:46:44.408>
creator = 'r.david.murray'
dependencies = []
files = []
hgrepos = []
issue_num = 16958
keywords = []
message_count = 8.0
messages = ['179909', '179912', '179913', '219866', '248822', '348633', '349507', '415999']
nosy_count = 9.0
nosy_names = ['loewis', 'ghaering', 'r.david.murray', 'nagylzs', 'aymeric.augustin', 'Kodiologist', 'corona10', 'coleifer', 'erlendaasland']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16958'
versions = ['Python 2.7', 'Python 3.2', 'Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by erlend-aasland** [comment]
I'm not sure we should change the current context manager to emit BEGIN statements on enter. The _could_ be backwards incompatible.

I think the best solution may be to deprecate the current context manager, and possibly introduce a new SAVEPOINT based context manager, that allows nesting.

```py
cx = sqlite3.connect(":memory:")
with cx.savepoint("sp1"):
    with cx.savepoint("sp2"):
        pass

# alternatively, we could auto-generate savepoint names internally
with cx.savepoint():
    with cx.savepoint():
        pass
```

**Comment by erlend-aasland** [comment]
@Kodiologist:
> the docs should be clarified in the meantime.

See gh-93890

**Comment by erlend-aasland** [comment]
The docs are now updated in:

- main: #93890 
- 3.11: #94013
- 3.10: #94012

**Comment by erlend-aasland** [comment]
IMO, we can close this issue now.

I think the discussion of deprecating the current context manager and/or possibly replacing it with a new SAVEPOINT-based context manager should have a wider audience than this issue alone. I therefore suggest opening a topic on Discourse, to try and gain more attention to such changes. If there is sufficient interest in following up and implementing the deprecation and/or a new context manager, I suggest we create new issue on the bug tracker, with backlinks to this discussion for reference.

**Comment by phiresky** [comment]
I just hit the same issue as @Kodiologist 

Specifically what happens:

First, you use sqlite3 library like this:

```python
db = sqlite3.connect("x.db")
db.execute("create table foo(x);") # this auto-commits, as expected. `$ sqlite3 x.db .dump` shows the table as expected.
db.execute("insert into foo values (1);") # this implicitly creates a cursor and a transaction but doesn't commit it!!
db.close()
# $ sqlite3 x.db .dump # the table is empty! why?
```

After a while of thinking your code is buggy you find out that sqlite3 uses isolation_level=DEFERRED by default which starts a transaction "secretly" and is different than the default of the sqlite3 REPL (and pretty much every other database engine I've seen)

So you set isolation_level=None to get the behaviour you expected. But then some time later you write this code:

```python
db = sqlite3.connect("x.db", isolation_level=None)

db.execute("insert into foo values (1);") # this one autocommits as expected
with db:
    for i in range(1000):
        db.execute("insert into foo values (1);")
        # i would expect these all to happen in one transaction, but turns out it commits after every insert
        # (you probably won't even realize this until later just thinking sqlite itself is slow)
    db.execute("syntax error")
    # the table contains the value that you think was rolled back
    # but it turns out `with db` doesn't actually do anything when isolation_mode=None
```

I think this behaviour is really confusing for most people, at least those coming from SQLite in different programming langugaes as well as other db engines like PostgreSQL.

Here's my workaround:

```py
class ConnectionFixedCtxManager(sqlite3.Connection):
    def __enter__(self) -> ConnectionFixedCtxManager:
        raise Exception(
            "don't use contextmanager on sqlite3 connection, it's broken with isolation_level=None (which is the sane default). use .transaction() instead (see https://github.com/python/cpython/issues/61162)"
        )

    def transaction(self) -> CursorFixedCtxManager:
        return CursorFixedCtxManager(self)


class CursorFixedCtxManager(ContextManager[sqlite3.Cursor]):
    _cursor: sqlite3.Cursor | None = None

    def __init__(self, conn: ConnectionFixedCtxManager):
        self._conn = conn

    def __enter__(self) -> sqlite3.Cursor:
        self._cursor = self._conn.cursor()
        self._cursor.execute("BEGIN")
        return self._cursor

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        value: BaseException | None,
        traceback: TracebackType | None,
    ) -> None:
        assert self._cursor
        if exc_type is None:
            self._conn.commit()
        else:
            self._conn.rollback()
        self._cursor.close()
        self._cursor = None
```

Usage:

```py
db = sqlite3.connect(..., isolation_level=None, factory=ConnectionFixedCtxManager)

with db.transaction() as cursor:
    cursor.execute("insert into foo values (1);")

```

Pretty simiilar to the .savepoint() suggestion by @erlend-aasland above except I think the context manager should return a cursor to prevent mixing up the main db object with the cursor. My code doesn't do anything for nested transactions since I don't use those. The separation between connection and cursor is still not really clean, IMO all convenience methods like `db.execute()` should throw an error when .transaction() was called / `in_transaction == True`

**Comment by erlend-aasland** [comment]
> The separation between connection and cursor is still not really clean, IMO all convenience methods like db.execute() should throw an error when .transaction() was called / in_transaction == True

That would probably break existing code, so that is not an option.

The docs have been made more explicit in the last weeks. Hopefully that will reduce the confusion. Also, the upcoming autocommit attribute will introduce a cleaner API that should be easier to understand, imo.

**Comment by phiresky** [comment]
It wouldn't be a breaking change if it only happens with a new `.savepoint()` / `.transaction()` method right? My idea would be that while the context manager created from that function is open, the main `Connection` object would basically be disabled and not usable.

Otherwise the __enter__ method should probably return `None` and not `Connection` (as the current contextmanager does) or `Cursor` (as my suggestion). If it returns something I'd expect what it returns to be different and statements on the main connection object to be unaffected

**Comment by erlend-aasland** [comment]
Let's move this discussion to either Discourse or a new issue.
