### ISSUE TITLE
multiprocessing.connection challenge implicitly uses MD5

### ISSUE THREAD

**Issue by davidmalcolm** [python/cpython#61460]
BPO | [17258](https://bugs.python.org/issue17258)
--- | :---
Nosy | @warsaw, @doko42, @pitrou, @tiran, @davidmalcolm, @miss-islington
PRs | <li>python/cpython#16264</li><li>python/cpython#20380</li><li>python/cpython#20412</li><li>python/cpython#20626</li>
Files | <li>[avoid-implicit-usage-of-md5-in-multiprocessing.patch](https://bugs.python.org/file29134/avoid-implicit-usage-of-md5-in-multiprocessing.patch "Uploaded as text/plain at 2013-02-20.20:11:35 by @davidmalcolm"): Patch to multiprocessing.connection to specify which hash algorithm to use</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-02-20.20:11:36.540>
labels = ['3.7', 'library']
title = 'multiprocessing.connection challenge implicitly uses MD5'
updated_at = <Date 2020-06-04.17:22:43.520>
user = 'https://github.com/davidmalcolm'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-04.17:22:43.520>
actor = 'miss-islington'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-02-20.20:11:36.540>
creator = 'dmalcolm'
dependencies = []
files = ['29134']
hgrepos = []
issue_num = 17258
keywords = ['patch']
message_count = 7.0
messages = ['182547', '182550', '182553', '309103', '309134', '370705', '370717']
nosy_count = 7.0
nosy_names = ['barry', 'doko', 'pitrou', 'christian.heimes', 'dmalcolm', 'sbt', 'miss-islington']
pr_nums = ['16264', '20380', '20412', '20626']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue17258'
versions = ['Python 3.7']
```

</p></details>

* PR: gh-99425

* PR: gh-99623

**Comment by gpshead** [comment]
This isn't something to backport to a release as what we've got isn't broken. Changing this is a feature.

**Comment by gpshead** [comment]
So https://github.com/python/cpython/pull/20380 is a more complicated version of my draft PR above.  In other PRs and issues related to this in the past, I see one claim by @tiran in particular that bothers me - https://github.com/python/cpython/pull/16264#issuecomment-562200425 - _"The change breaks backward compatibility. multiprocessing supports distributed computing across multiple machines and works with multiple Python versions. With the change a controller with Python 3.N+1 would no longer be able to talk to a 3.N server or the other way around."_

What evidence is there that multi-python-version use of multiprocessing rather than use as a single Python process launching and controlling a bunch of children is a supported use case? People really should not be using multiprocessing that way. This isn't a distributed computing system.

**Comment by CAM-Gerlach** [comment]
Just to note, this came up again, in #100755 , an apparent duplicate of this issue

**Comment by gpshead** [comment]
3.12beta1 is going out using hmac-sha256 by default with the above PR merge.
