### ISSUE TITLE
tkinter.Image.__del__ can throw an exception if module globals are destroyed in the wrong order

### ISSUE THREAD

**Issue by 876014a4-52b5-4d09-bc43-64eb16d8ef36** [python/cpython#62341]
BPO | [18141](https://bugs.python.org/issue18141)
--- | :---
Nosy | @terryjreedy, @pitrou, @serhiy-storchaka
Files | <li>[3fdd418be9f8.diff](https://bugs.python.org/file30470/3fdd418be9f8.diff "Uploaded as text/plain at 2013-06-05.12:21:26 by JanKanis")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2014-06-08.12:42:34.851>
created_at = <Date 2013-06-05.12:09:36.598>
labels = ['type-bug', 'expert-tkinter']
title = 'tkinter.Image.__del__ can throw an exception if module globals are destroyed in the wrong order'
updated_at = <Date 2014-06-08.12:42:34.849>
user = 'https://bugs.python.org/JanKanis'
```

bugs.python.org fields:
```python
activity = <Date 2014-06-08.12:42:34.849>
actor = 'JanKanis'
assignee = 'none'
closed = True
closed_date = <Date 2014-06-08.12:42:34.851>
closer = 'JanKanis'
components = ['Tkinter']
creation = <Date 2013-06-05.12:09:36.598>
creator = 'JanKanis'
dependencies = []
files = ['30470']
hgrepos = ['196']
issue_num = 18141
keywords = ['patch']
message_count = 13.0
messages = ['190654', '190655', '190656', '219294', '219298', '219488', '219718', '219720', '219941', '219958', '219993', '220010', '220032']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'pitrou', 'JanKanis', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'patch review'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue18141'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by daver1691** [comment]
I'm using Ubuntu 23.10, using its system Python 3.11.6 which has Tkinter 8.6., and this problem has reappeared .

    import tkinter as tk
    root = tk.Tk()
    im = tk.PhotoImage(width=300,height=100)
    lab = tk.Label(root, image=im)
    lab.pack()
    root.mainloop()

On window close:

    Exception ignored in: <function Image.__del__ at 0x7f9e9520fe20>
    Traceback (most recent call last):
    File "/usr/lib/python3.11/tkinter/__init__.py", line 4081, in __del__
    TypeError: catching classes that do not inherit from BaseException is not allowed

**Comment by terryjreedy** [comment]
On Windows, 3.11.8 (latest bugfix) and 3.13.0a5, both installed, there is no problem.  OS should not affect tkinter code though.  
In 3.11.8 (with different line numbers), Image.__del__ is
```
    def __del__(self):
        if self.name:
            try:
                self.tk.call('image', 'delete', self.name)
            except TclError:
                # May happen if the root was destroyed
                pass
```
where line 39 has `TclError = _tkinter.TclError`.  @serhiy-storchaka  Could there be an issue in 3.11.6 with the base class of TclError?

**Comment by daver1691** [comment]
@terryjreedy  Thanks for your help.

OK, it does seem that this is a problem specific to the Python that's in the current version of Ubuntu, 23.10, and that the problem will go away with Ubuntu 24.04.

At the command line, I got the same result as yourself, TclError inherits from BaseException.

But I edited `__init__.py`, putting  `print(TclError.__mro__)` above `try:` in the `__del__` function, and got an error because `TclError` had no attribute `__mro__`. It turned out that the `TclError` there was of type `NoneType`. I've no idea why.

I installed the development version of Ubuntu 24.04 into a spare partition on my PC and repeated the test with its Python 3.12.2. This time, `TclError` *did* inherit from `BaseException`.

I've made the problem go away on my Ubuntu 23.10 installation by replacing `except TclError:` with `except Exception:`. OK, problem solved, I guess.
