### ISSUE TITLE
Use argparse in the profile/cProfile modules

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#63171]
BPO | [18971](https://bugs.python.org/issue18971)
--- | :---
Nosy | @birkenfeld, @vstinner, @ezio-melotti, @bitdancer, @serhiy-storchaka, @wm75, @yan12125, @mlouielu
Files | <li>[profile_argparse.patch](https://bugs.python.org/file31665/profile_argparse.patch "Uploaded as text/plain at 2013-09-08.14:48:54 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-09-08.14:48:55.312>
labels = ['type-feature', 'library']
title = 'Use argparse in the profile/cProfile modules'
updated_at = <Date 2018-07-11.17:43:50.223>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-11.17:43:50.223>
actor = 'yan12125'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-09-08.14:48:55.312>
creator = 'serhiy.storchaka'
dependencies = []
files = ['31665']
hgrepos = []
issue_num = 18971
keywords = ['patch']
message_count = 8.0
messages = ['197262', '197649', '197660', '282192', '291976', '291977', '291978', '291982']
nosy_count = 9.0
nosy_names = ['georg.brandl', 'bethard', 'vstinner', 'ezio.melotti', 'r.david.murray', 'serhiy.storchaka', 'wolma', 'yan12125', 'louielu']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue18971'
versions = ['Python 3.4']
```

</p></details>

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
bad news, somehow the output of std.err and std.out have different between optparse and argparse, even if the test is done, it still need to convert some testcase to argparse compatible.

**Comment by vstinner** [comment]
> bad news, somehow the output of std.err and std.out have different between optparse and argparse

Only test argparse. I don't think that it matters to test that the change doesn't change the behaviour.

You can also redirect stderr to stdout.

What do you want to test?

**Comment by bitdancer** [comment]
Well, part of the point of the tests is to make sure the module's behavior doesn't change when doing the conversion to argparse.  But "behavior changing" doesn't extend to the exact format of the output...that can change, as long as what the module \*does* given specific cli argument combinations stays the same.  Ideally, you write the tests so that it is not sensitive to the exact output, but realistically some tests may need to be different between the optparse case and the argparse case to get good coverage.

Note that even with good tests, you can still miss behavior changes.  We tried to do a good job on the tests for compileall, for example, and we still introduced a bug or two when we converted to argparse.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
haypo, murray, thanks for pointing this thing, I will let go about the bad message test, move to output file and sort test tomorrow, also add a new issue: bpo-30118

**Comment by serhiy-storchaka** [comment]
Well, for now there is no need to migrate from optparse to argparse.
