### ISSUE TITLE
Add pathlib.chown method

### ISSUE THREAD

**Issue by ce7d5904-2ae0-4bc9-8085-2279bf8114aa** [python/cpython#64978]
BPO | [20779](https://bugs.python.org/issue20779)
--- | :---
Nosy | @pitrou, @vajrasky, @sedrubal, @eamanu, @y0urself
PRs | <li>python/cpython#31212</li>
Files | <li>[add_chown_to_pathlib.patch](https://bugs.python.org/file34227/add_chown_to_pathlib.patch "Uploaded as text/plain at 2014-02-26.09:51:48 by @vajrasky")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-02-26.09:51:50.192>
labels = ['type-feature', 'library', '3.11']
title = 'Add pathlib.chown method'
updated_at = <Date 2022-02-08.11:17:25.947>
user = 'https://github.com/vajrasky'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-08.11:17:25.947>
actor = 'y0urself'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2014-02-26.09:51:50.192>
creator = 'vajrasky'
dependencies = []
files = ['34227']
hgrepos = []
issue_num = 20779
keywords = ['patch']
message_count = 7.0
messages = ['212245', '212378', '212411', '212425', '396629', '398695', '412787']
nosy_count = 8.0
nosy_names = ['pitrou', 'cvrebert', 'neologix', 'vajrasky', 'sedrubal', 'eamanu', 'Tom Cook', 'y0urself']
pr_nums = ['31212']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue20779'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-104183

**Comment by barneygale** [comment]
I'm -1 on this: I don't think pathlib should start accumulating further functionality from `os` unless its used to implement high-level path behaviour (like walking directory trees).

**Comment by CAM-Gerlach** [comment]
To note, I can't confirm myself since I'm on a Windows machine at the moment, but [os.chown is documented](https://docs.python.org/3/library/os.html#os.chown) as natively supporting `pathlib.Path`s since Python 3.6. There's also the higher level [`shutil.chown`](https://docs.python.org/3.12/library/shutil.html#shutil.chown) which has a nicer API with more Pythonic argument handling and accepts user/group names as well as IDs, unlike the `os` version. As it simply passes `path` through to the underlying `os.chown`, it in turn supports `pathlib.Path`s as well.

This seems to address the major concrete issue expressed by users here (e.g. "It's annoying to have to drop back to os.chown(str(path), ...)", "I would love to use chown for a pathlib Path, too."), as well as exposing a nicer higher-level interface.

(Sidenote: Perhaps, if there's interest, it's worth allowing passing through `dir_fd` or particularly `follow_symlinks` in `shutil.chown` to `os.chown` so the latter is a proper superset of the former, but that's an entirely separate issue of course and unrelated to `pathlib`.)

**Comment by AlexWaygood** [comment]
I agree with @barneygale, @CAM-Gerlach, and @brettcannon (Brett voiced his opinions on the PR here: https://github.com/python/cpython/pull/31212#issuecomment-1132298550). There seems to be little point adding this method, if it's just a thin wrapper around `os.chown()`.

**Comment by barneygale** [comment]
Re-opening the issue for the sake of discussion.

I'm ±0 on this idea.

On the one hand, I don't want pathlib to accumulate simple wrappers of `os` functions, because there's a large number of them and it's hard to draw the line. The Zen of Python says "There should be one-- and preferably only one --obvious way to do it."

On the other hand, the implementation of `chown()` in `shutil` (not `os`) feels high-level enough to belong in pathlib, as it deals with user and group *names* like pathlib's `owner()` and `group()`. I have a [vague plan to move shutil things into pathlib](https://discuss.python.org/t/incrementally-move-high-level-path-operations-from-shutil-to-pathlib/19208), so it fits reasonably well. In the very distant future we might consider deprecating the `shutil` version, which makes me feel better about the intervening duplication.

Would love to hear thoughts from others!

**Comment by CAM-Gerlach** [comment]
Personally, FWIW, I'm +0.5 so long as the idea fits with the long-term plan and the implementation does not add more than minimal additional maintenance burden. It's a little unfortunate there are two different `chown` functions with different APIs, but if this could eventually lead to deprecating one of them, leading to the same net number, while adding the convinence of calling methods directly on Paths rather than importing from `os`, then it seems reasonable to consider.

**Comment by barneygale** [comment]
Thanks both.

IMO we should move the implementation from `shutil` to `pathlib`. The version in `shutil` becomes a thin wrapper:

```python
# shutil.py

def chown(path, user=None, group=None):
    pathlib.Path(path).chown(user, group)
```

**However**, we'd need to add support for `bytes` paths to pathlib, as they're accepted by `shutil.chown()`. There's no feature request logged for that yet. It's not easy, but it's worth doing I think.

**Comment by brettcannon** [comment]
> we'd need to add support for `bytes` paths to pathlib, as they're accepted by `shutil.chown()`. There's no feature request logged for that yet. It's not easy, but it's worth doing I think.

FYI I disagree with that as we _want_ people to move towards string-based paths as they are much easier to work with (just like we want people to use UTF-8 more).

**Comment by AlexWaygood** [comment]
> Hm. I wouldn't want to encourage users to use `bytes` if they don't need to, or to put the thought in their minds. If we were to add it, it would only get a brief mention in the docs.

I view pathlib refusing to handle bytes as a _feature_. If I have a function that accepts an arbitrary `Path` object `x`, I know for sure that `x.parts[0]` will be a `str`. That's one of the things that makes the pathlib API easy to fit in my brain, and easy to reason about.

Even if we can add support for bytes paths without complicating the implementation or slowing things down, I think I'd still be against adding support  for bytes paths in pathlib 😕 it would raise backwards-compatibility concerns and increase the cognitive load associated with the module, and I'm unsure that there's a strong use case for it.

**Comment by barneygale** [comment]
I find that quite convincing! Thanks.

It sounds like we can't implement `shutil.chown()` using `pathlib.Path.chown()` then, as we'd be breaking support for bytes. It probably makes sense to do the opposite: call `shutil.chown()` from pathlib. This will make it slightly more complicated to move other `shutil` functionality to pathlib in future where `AbstractPath` is a thing, but that's a problem for another day.

**Comment by pitrou** [comment]
If users were allowed to pass `bytes` to pathlib, they would have to be converted to `str` internally anyway. I'd rather people do their own conversion if they need a special one.

**Comment by barneygale** [comment]
> If users were allowed to pass `bytes` to pathlib, they would have to be converted to `str` internally anyway. I'd rather people do their own conversion if they need a special one.

I don't follow, sorry - why would they have to be converted to `str`? AFAIK the only reason to use `bytes` paths is specifically to _avoid_ decoding to `str`, because the encoding can't be known with certainty on POSIX.

**Comment by AlexWaygood** [comment]
> Relevant SO: https://stackoverflow.com/questions/45724240/processing-non-utf-8-posix-filenames-using-python-pathlib

(I mainly use Windows so excuse my ignorance about bytes paths here!)

Are there any drawbacks to the solution given in the answer to that Stack Overflow question? It looks pretty "clean" to me — if there are no drawbacks, maybe we should just document in the pathlib docs that this is how you use pathlib if you have a bytes path?

**Comment by pitrou** [comment]
[PEP 383](https://peps.python.org/pep-0383/) is the fundamental reference here.

**Comment by pitrou** [comment]
> I don't follow, sorry - why would they have to be converted to `str`?

Because pathlib uses `str` internally.

**Comment by barneygale** [comment]
PR available:

- https://github.com/python/cpython/pull/104183

**Comment by nineteendo** [comment]
Barney, what's the status here?

**Comment by barneygale** [comment]
I'm still undecided as to whether this is a good idea.

IIUC we can't make `shutil` use `pathlib` because [pathlib strips trailing slashes](https://discuss.python.org/t/pathlib-preserve-trailing-slash/33389), and so `shutil.chown('not_a_dir/', ...)` would succeed where previously it failed with `NotADirectoryError`. This is fixable if we introduce a private superclass of `Path` that skips normalization, but there's little appetite for that right now.

Consequently we'd either need to make `pathlib` use `shutil`, which [feels wrong to some core devs](https://github.com/python/cpython/issues/73991#issuecomment-2111680201) and I'm trying to avoid if I can, or we'd just copy-paste the shutil implementation into pathlib, which I feel pretty "meh" about too.

**Comment by barneygale** [comment]
#73991 is the more important shutil/pathlib issue. I hope to solve that first, and by doing so, shed some light on whether _this_ request is worth doing or not.

**Comment by barneygale** [comment]
I'm going to close this as "won't do". It turns out that `Path.chown()` won't be helpful for copying file metadata in #73991, and I can see no other compelling reason to add it. Plus it's POSIX-only and usually needs root. Use `os.chown()` or `shutil.chown()` instead please! And feel free to leave a comment if you disagree and would like to see this re-opened.
