### ISSUE TITLE
Auto-generate exceptions.c from a Python file

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#65442]
BPO | [21243](https://bugs.python.org/issue21243)
--- | :---
Nosy | @brettcannon, @matrixise, @Vgr255

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-04-15.18:12:29.123>
labels = ['interpreter-core', 'type-feature', '3.9']
title = 'Auto-generate exceptions.c from a Python file'
updated_at = <Date 2020-03-18.18:28:41.984>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-18.18:28:41.984>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2014-04-15.18:12:29.123>
creator = 'brett.cannon'
dependencies = []
files = []
hgrepos = []
issue_num = 21243
keywords = []
message_count = 3.0
messages = ['216354', '242219', '242221']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'matrixise', 'abarry']
pr_nums = []
priority = 'low'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue21243'
versions = ['Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
I think this would increase maintenance burden rather than reduce it. The exceptions are currently defined in one place with one pattern. With this proposal there would be two patterns, with the additional burden of deciding which exception should be defined with each pattern (and maintaining this decision as thing may change in the future).

The C implementation of exceptions uses macros to avoid code duplication for the simple exceptions (those that could be auto generated from python). So even just for those exceptions I don’t think this will reduce maintenance burden.
