### ISSUE TITLE
freeze.py not working properly with OS X framework builds

### ISSUE THREAD

**Issue by 01981423-a583-401e-97ed-5aec83c79400** [python/cpython#65701]
BPO | [21502](https://bugs.python.org/issue21502)
--- | :---
Nosy | @ronaldoussoren, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = None
created_at = <Date 2014-05-14.00:11:32.240>
labels = ['OS-mac', 'type-feature']
title = 'freeze.py not working properly with OS X framework builds'
updated_at = <Date 2015-02-07.15:33:25.994>
user = 'https://bugs.python.org/yjiangnan'
```

bugs.python.org fields:
```python
activity = <Date 2015-02-07.15:33:25.994>
actor = 'ned.deily'
assignee = 'ned.deily'
closed = False
closed_date = None
closer = None
components = ['macOS']
creation = <Date 2014-05-14.00:11:32.240>
creator = 'yjiangnan'
dependencies = []
files = []
hgrepos = []
issue_num = 21502
keywords = []
message_count = 2.0
messages = ['218493', '235528']
nosy_count = 2.0
nosy_names = ['ronaldoussoren', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue21502'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

### Linked PRs
* gh-113352
* gh-113361
* gh-113362

**Comment by erlend-aasland** [comment]
Is this still relevant?

**Comment by FFY00** [comment]
@ned-deily would be able to see if this is still relevant?

**Comment by ned-deily** [comment]
> @ned-deily would be able to see if this is still relevant?

I'll take a look.

**Comment by ronaldoussoren** [comment]
> Ronald, do you have other thoughts on this?

Sorry, but I have never used freeze. But given the description in the readme I'd expect that freeze is not really useful with a framework (or shared library!) build because you'll end up with dependencies to the framework/shared library. This is worse on macOS than on other unix-y platforms because the load command for shared libraries contains an absolute path to the library (that is, a frozen script won't rely on ``libpython.so`` but on ``/path/to/libpython.so``).

IMHO it is better to document that freeze is not compatible with framework builds, unless someone is willing to put in the work to fix issues (with test cases!) and document the limitations.

**Comment by ronaldoussoren** [comment]
The attached PR documents that framework builds aren't supported in the README file, and also bails out in freeze.py when it detects a framework build.

I looked into adding a test, but ended up not doing this because the test machinery tries to do a separate install in a temporary directory and that's problematic with framework builds as well (alternate prefix doesn't work, and is not something we should try to support because it is incompatible with platform standards)
