### ISSUE TITLE
inspect documentation describes module type inaccurately

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#65959]
BPO | [21760](https://bugs.python.org/issue21760)
--- | :---
Nosy | @ncoghlan, @ericsnowcurrently, @miss-islington, @furkanonder
PRs | <li>python/cpython#19097</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-06-14.19:58:13.196>
labels = ['easy', '3.11', '3.9', '3.10', 'docs']
title = 'inspect documentation describes module type inaccurately'
updated_at = <Date 2021-06-21.15:17:15.619>
user = 'https://github.com/ericsnowcurrently'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-21.15:17:15.619>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2014-06-14.19:58:13.196>
creator = 'eric.snow'
dependencies = []
files = []
hgrepos = []
issue_num = 21760
keywords = ['easy']
message_count = 5.0
messages = ['220576', '364831', '366210', '395472', '395475']
nosy_count = 5.0
nosy_names = ['ncoghlan', 'docs@python', 'eric.snow', 'miss-islington', 'furkanonder']
pr_nums = ['19097']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue21760'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by tuukkamustonen** [comment]
@encukou I believe this ticket is no longer relevant.

There was a change in https://github.com/python/cpython/pull/98116/files where the module members were removed from https://docs.python.org/dev/library/inspect.html#types-and-members, that this ticket suggested to update.

There's no longer nothing to update, because we're simply referencing another docs location for the details. I _assume_ [that other location](https://docs.python.org/dev/reference/import.html#import-mod-attrs) is correct and covers all the fields. That was also the assumption in the original report in this ticket:

> The language reference[2] and importlib docs[3] both provide an accurate list of module attributes.

[2] https://docs.python.org/3/reference/import.html#import-related-module-attributes (it's now linked to this)
[3] https://docs.python.org/3/library/importlib.html#importlib.machinery.ModuleSpec

**Comment by ericsnowcurrently** [comment]
As https://github.com/python/cpython/issues/65959#issuecomment-1093657481 notes, there are also some missing attributes in the `types` module docs.  However, those can be addressed by gh-64019.
