### ISSUE TITLE
asyncio: nested event loop

### ISSUE THREAD

**Issue by c4c66b32-370b-4abf-b91a-4cf1c912e1ff** [python/cpython#66435]
BPO | [22239](https://bugs.python.org/issue22239)
--- | :---
Nosy | @jcea, @njsmith, @jab, @pmp-p, @vadmium, @1st1, @crusaderky, @douglas-raillard-arm, @davidbrochart, @kumaraditya303
Files | <li>[nested.py](https://bugs.python.org/file36422/nested.py "Uploaded as text/plain at 2014-08-20.18:03:50 by djarb"): Decorator allowing a coroutine to run in a nested event loop</li><li>[nested.patch](https://bugs.python.org/file36498/nested.patch "Uploaded as text/plain at 2014-08-28.19:10:41 by djarb")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2014-08-25.18:04:32.900>
created_at = <Date 2014-08-20.18:03:50.601>
labels = ['type-feature', 'expert-asyncio']
title = 'asyncio: nested event loop'
updated_at = <Date 2021-12-11.07:40:23.171>
user = 'https://bugs.python.org/djarb'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-11.07:40:23.171>
actor = 'kumaraditya'
assignee = 'none'
closed = True
closed_date = <Date 2014-08-25.18:04:32.900>
closer = 'gvanrossum'
components = ['asyncio']
creation = <Date 2014-08-20.18:03:50.601>
creator = 'djarb'
dependencies = []
files = ['36422', '36498']
hgrepos = []
issue_num = 22239
keywords = ['patch']
message_count = 23.0
messages = ['225578', '225883', '226037', '298388', '373145', '373177', '373183', '373186', '373192', '373240', '373241', '373244', '373245', '373247', '373249', '373270', '373273', '373280', '373307', '373311', '389487', '398257', '399920']
nosy_count = 14.0
nosy_names = ['jcea', 'djarb', 'zzzeek', 'njs', 'jab', 'pmpp', 'martin.panter', 'yselivanov', 'Rokas K. (rku)', 'crusaderky', 'douglas-raillard-arm', 'davidbrochart', 'kumaraditya', 'rob.moore']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = None
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue22239'
versions = []
```

</p></details>

### Linked PRs
* gh-93338

**Comment by 8bad483d-8030-4917-a382-788f55ce0a13** [comment]
I understand rationale for rejection of this issue but i beg to reconsider.

Unlike in traditional coroutines (windows fibers / setjmp|longjmp with stack switching) we can not yield from any point of execution. There must be full async-await chain preserved. This basically divides code into two islands - async and non-async. And there seems to be no way to schedule async call from non-async code and get a response. While suggestion to make custom `async def contains()` call is a valid one we can not always do that. Consider the case when we have to do some networking calls in a function that is invoked by non-async library. Naturally it would be simple non-awaited call from which we can not call a coroutine and get a response. And since it is a library calling into our code we can not easily change it. It might even be completely unsuitable change for library in question.

I see two solutions to this problem (if i am missing something please point it out):

1. Reentrant loops as suggested in this issue.
2. Allow awaited calls from non-coroutines provided execution is invoked from a coroutine somewhere up the call stack.

First one is certainly easier to implement.

**Comment by gvanrossum** [comment]
There are still people who desperately want this feature, and there is now a PyPI package [nestio](https://github.com/erdewit/nest_asyncio) that claims to solve the problem. (I recently found out about it from the announcement video for ChatGPT 4, where the AI suggested this for a problem with using `await` in a Jupyter Notebook.)

In PR GH-93338 there is some discussion that I'm trying to redirect here.

The key part of the example is this:
```py
async def main():
    t = asyncio.create_task(task("main"))  # not executed until foo() is done
    foo()  # Calls asyncio.run()
    await asyncio.sleep(1.1)  # t resumes execution

asyncio.run(main())
```
Here the tasks created on the first line of `main()` are not allowed to run until the `foo()` function returns -- and `foo()` itself runs some tasks in a different event loop using `asyncio.run()`. In current `asyncio` this isn't allowed (the recursive `asyncio.run()` call raises an exception) but the PR changes things to allow it.

There's another proposal that goes quite a bit further -- it runs both sets of tasks interleaved. I'm not sure I even want to know how that works. :-)

My continued resistance to allowing either semantics is that `asyncio` has a *guarantee* that no other tasks run unless `await` is used. This creates an implicit "critical section" between any two `await` calls. Interleaving the tasks in a recursive `asyncio.run()` definitely breaks this guarantee -- there is nothing in the call to `foo()` that warns the reader that it may run other tasks, and it fact the nested `asyncio.run()` call could be hidden deeply in the call tree.

The weaker form (where the nested loop blocks anything running in the outer loop, as proposed by the PR) violates a weaker principle of `asyncio`, i.e., that no blocking I/O should be performed (all I/O must be non-blocking and defer to the event loop using `await`). The reason for this requirement is that such blocking I/O calls would prevent the I/O parallelism promised by the `asyncio` architecture -- the blocking call (as demonstrated by `foo()` in the example) prevents all other asynchronous I/O from happening.

Now, my understanding is that the main reason people want this feature is that currently Jupyter (or the IPython kernel, I'm not sure about the boundary between the two) has an `asyncio` event loop running at all times, which means that anyone typing `asyncio.run(...)` at the Jupyter prompt gets an error. If that hypothesis is correct, maybe we should work together with the Jupyter project to improve this situation without breaking the guarantees and promises made by `asyncio` to its users. (@willingc Do you have a contact there who might be able to jump on this thread?)

Other thoughts?

**Comment by gvanrossum** [comment]
(Further thought: maybe it should be the *outer* loop that allows running nested inner loops, rather than telling the inner loop to ignore the outer loop?)

**Comment by davidbrochart** [comment]
> Here the tasks created on the first line of `main()` are not allowed to run until the `foo()` function returns -- and `foo()` itself runs some tasks in a different event loop using `asyncio.run()`.

Actually `foo()` runs some tasks in the same event loop, but all currently running tasks are suspended until the nested `asyncio.run()` returns.

> The weaker form (where the nested loop blocks anything running in the outer loop, as proposed by the PR) violates a weaker principle of `asyncio`, i.e., that no blocking I/O should be performed (all I/O must be non-blocking and defer to the event loop using `await`). The reason for this requirement is that such blocking I/O calls would prevent the I/O parallelism promised by the `asyncio` architecture -- the blocking call (as demonstrated by `foo()` in the example) prevents all other asynchronous I/O from happening.

Although that principle is rather left to the good will of the user, right? Nothing prevents them to run some blocking code that is "not cooperative", i.e. that runs for a long time, preventing other tasks to have a chance to run soon.
I really see a nested event loop as a blocking section of code that just happens to take advantage of `asyncio` internally, but that should suspend the outer loop. Yes, it can be a bad practice, just as having a too long blocking call, but that's left to the user.

> Now, my understanding is that the main reason people want this feature is that currently Jupyter (or the IPython kernel, I'm not sure about the boundary between the two) has an `asyncio` event loop running at all times, which means that anyone typing `asyncio.run(...)` at the Jupyter prompt gets an error. If that hypothesis is correct, maybe we should work together with the Jupyter project to improve this situation without breaking the guarantees and promises made by `asyncio` to its users. (@willingc Do you have a contact there who might be able to jump on this thread?)

Yes, [ipykernel](https://github.com/ipython/ipykernel) runs user code in an event loop, which prevents them from typing `asyncio.run(...)`. We have been recommending [nest-asyncio](https://github.com/erdewit/nest_asyncio), but it monkey-patches `asyncio`, which is not great, and there are issues where some tasks are launched before it does so. Another option is to run another event loop in another thread, but I've heard that some libraries want to be run in the main thread. Finally, [vaex](https://github.com/vaexio/vaex/blob/633970528cb5091ef376dbca2e4721cd42525419/packages/vaex-core/vaex/asyncio.py#L7) can swap the current event loop with a new one, but it uses the private `asyncio.events._set_running_loop`, and there can be issues with accessing objects (e.g. events) defined in the other loop.

> (Further thought: maybe it should be the _outer_ loop that allows running nested inner loops, rather than telling the inner loop to ignore the outer loop?)

Interesting idea, although often times it is the inner event loop which doesn't know in which environment it is used, and it would depend on the outer loop to allow nested loops.
Maybe both options should be allowed? The outer loop could allow nested loops, making inner calls to `asyncio.run` work by default. And the inner loop could call `asyncio.run(..., running_ok=True)` even though the outer loop didn't allow nested loops.

**Comment by willingc** [comment]
Thanks @davidbrochart for jumping in. @Carreau would likely have good context on this too from his earlier async work with IPython. Let's see if we can discuss at JupyterCon. Thanks!

**Comment by gvanrossum** [comment]
Do we have to allow people writing `asyncio.run(coro())`? If they can just as well write `await coro()` why not recommend that as the fix, instead of installing `nest_asyncio`?

The proposal to allow writing `with loop.subloop() as subloop: await subloop.create_task(coro())` is intriguing; it makes it clear that there is something funny with the event loop, but it fails to let people use `asyncio.run(coro())`, which they presumably copy-paste from one of the gazillion tutorials.

I'm not crazy about the "concurrent" subloop, that seems to be violating the strong guarantee. I can live with any of a number of ways of allowing users to violate the weak guarantee, but you'll have to let me know which you like best.

If my hunch is right about why people want to use `asyncio.run(coro())` which they copy-pasted from an example, then maybe having a flag on the parent loop (e.g. the Jupyter loop) to allow this might work -- `asyncio.run()` should be adjusted to save and restore the previous loop. If we want things more auditable, a flag on the `run()` call would be better, or the `with subloop()` idea.

Thoughts?

**Comment by davidbrochart** [comment]
> Do we have to allow people writing `asyncio.run(coro())`? If they can just as well write `await coro()` why not recommend that as the fix, instead of installing `nest_asyncio`?

They can only `await coro()` at the top-level, but if we recommend doing that in a function down the stack, now they have to convert pretty much all their code base to async. I think it would be nice to nest event loops not only in the Jupyter context, but for anyone willing to provide a blocking API from an async API.

**Comment by gvanrossum** [comment]
But providing a simple way to run an asynchronous API synchronously is exactly the antipattern I'm trying to avoid here. If an API exists in async and sync form (the latter using `asyncio.run()` or the former), we want to make sure that when the user is already in async code they don't call the sync form out of laziness.

The two cases where we *do* want to allow using the sync form are: (1) in legacy sync code, where no loop is running; or (2) in situations *like* Jupyter, where there is a "dormant" event loop that is safe to ignore with a recursive `asyncio.run()` call is made. I like the idea of making the "dormant" loop advertise that it is okay with recursive `asyncio.run()` calls, either using a context manager.

**Comment by Carreau** [comment]
> Do we have to allow people writing asyncio.run(coro())? If they can just as well write await coro() why not recommend that as the fix, instead of installing nest_asyncio?

I think @davidbrochart replied to this. We are rarely talking about top-level  `asyncio.run`, in which case, yes, top level await is the answer.

> The proposal to allow writing with loop.subloop() as subloop: await subloop.create_task(coro()) is intriguing; it makes it clear that there is something funny with the event loop, but it fails to let people use asyncio.run(coro()), which they presumably copy-paste from one of the gazillion tutorials

Oh, I was not suggesting the inner code would have access to subloop. I was suggesting:


```

foo() # indirectly call asyncio.run() fails.

with some_decorator():
    foo() # indirectly calling asyncio.run() works. 
```

We can just "isolate" the code that may run subloops. Typically in IPython/jupyter, the only place we would have this decorator is around whatever will call exec:

```python
async def handle_user_request(code):
   with some_contextmanager():
        self.IPython.exec_user_code(code)
```

With this `code` _could_ contain an `asyncio.run`, but we are _sure_ that anywhere else in Jupyter we do not nest eventloops.

`some_contextmanager` would likely set a contextvar that let the next (second) usage of asyncio.run to not fail (semantics of weak loop, or concurrent loop to be allowed TBD). This (second) nested asyncio.run create a new context, so a third nested asyncio.run would fail (unless itself in an unprotected section with another `some_contextmanager`). My proposal would be that `some_contextmanager()` be a method on the current loop so that only code that has access to the current loop can create an unprotected section. And in the same way that trio has nurseries, you _must_ pass this to your callee if you want _them_ to decide to create an unprotected section.

To your second message

> But providing a simple way to run an asynchronous [...]

I think you are basing your reflexion on case where the user/developper can be in control of most of the stack – and/or it's their job to understand and modify it – which is more common in businesses and applications, less in libraries and the Scientific ecosystem. There are many cases where this is untrue, and cases where you do not know wether the API is going to be async or sync down(or up) the line, or worse where you _know_ you have a sync call between two async. 

### Same code Sync and Async Sandwich with anyway Sync in the middle.

Say you are doing machine learning on images in Jupyter. 
You are likely using numpy array-like code.

```
import skimage
import sklearn
img = skimage.read('holy_grail.png')
sklean.detect_objects(img)
```

All good, your teacher is happy. `sklean.detect_objects(img)` is 100% Sync cause `img[...]` is sync, and you are a student on your laptop. 

Now you get an image from the [VLT](https://en.wikipedia.org/wiki/Very_Large_Telescope), damn now it's a petabyte. 

```
import skimage
import sklearn
img = skimage.read("s3://bucket/bucket/bucket.zarr")
sklean.detect_objects(img) # ???
```


Well now `img[...]` would like to do async stuff cause `img[0:100, ..]`, and `img[101:200,...]` are on different servers and I can get them concurrently it's automatically using [zarr](https://pypi.org/project/zarr/) (compressed, chunked, N-dimensional arrays) and compute concurently for independant chunks with [dask](https://pypi.org/project/dask/) (distributed computing) on your cluster cause your admin is awesome and enabled the Dask backend.

Great thing about Dask, and Zarr is they both handle one side of the numpy API, and both want async. Dask replace the computation, so calls get/setitem, zarr gets the data so implement get/setitem. Feel free to replace with with cupy if you want GPU, or ray for single machine parallelism. And here even if both _want_ async, they can't know the _other_  will be async. Well they are stuck. They don't know either exactly how they will interact with each other cause the algorithm is in sklearn/skimage, which itself tries not to care wether up/down is async, it just want to have array of pixel and do stuff with it in some order.

Sure I could make `await async_detect_objects(img)`... but anyway `img[...]` is `def` not `async def` it will be sync here anyway. Or the user pass a custom callback that is sync. Those algo have been written for decades, so even if the new ones are `async def` anyway and we now have `async def getitem`, I might still get called by (or with) old sync ones.

Even if we – as maintainer – would _like_ to use async all the way down, _in practice_ we hit so many layers and places where we can't use async, or don't know if we will get async we have to nest loops. Cause we'd like the user to keep the same code for both use case. (also "Although practicality beats purity"). 

### Jupyter (scientific users are not here to code).

Many of Jupyter Users are also not programers, their job is not to code, it's to produce science. They can't afford to learn about async, it's not their job. They are not lazy not learning about it, because often the tradeoff is not worth it anyway.

They are not going to serve 1M page. Most code is going to be ran _once_. I mean we are sometime talking about code that take you 15 second to write, and runs from 1-2 seconds and gets modified/deleted. Reaching for async everywhere means taking 30 second to write it, maybe more as it cause Errors the first 2 times, and googling on stack overflow. The result will now take _only_ 0.5 sec to display. But for that scientist that's ~95% worse.

Plus now they have to context switch between the "Mutations within a furin consensus sequence block proteolytic release of ectodysplasin-A", and "how do you properly reuse an httpx.AsyncClient". Now I personally find both question fascinating, but having seen some folks struggling with dicts, I don't think they are ready to tackle the details async/await. Though I  still they may help to cure cancer, and that Async/Await are not going to help with that for some of them.

For those interested in both above question, I'd like for them to be able to focus on the Furin cleavage site during the day, and do science, and httpx during the night, if they like to program, but not both at the same time.

For those scientist the metrics of "clean/fast" code is completely different and they love python because it's pseudo code, and it just works™. If it's too slow, they know where my office is.

### Maintainers for Science

I think the Scientific Python stack developers are doing their best to make things work out of the box as well as possible without having users to look under the hood, and we would be grateful for a way to at least locally enable a weaker concurrency form (zarr perfect example as it's a leaf and we just want getitem to have local concurency). 

Now what would be even greater, is that if all the ingredient of the sandwich were gluten free, to not have to package each individually and have them all running in the same loop. It will just take some reallllllly long time to get there.

We also do our best to put warnings when people do thing in non optimal way, and we love when a grad student reach to us and use the right API and suddenly have their code run in 12 min instead of 12days (true story), and do completely understand your POV. We just have a sometime a realllly different use case. 


Sorry for this long message, if you read me in full (whoever you are), I owe you a drink next we meet at a conference.

**Comment by gvanrossum** [comment]
FWIW for a different view on nesting event loops, see @fried's talk from PyCon 2022: https://youtu.be/XW7yv6HuWTE. (And yes, I'm slowly working through my backlog, and I will eventually get to this.)

**Comment by gvanrossum** [comment]
Anyway, you now definitely owe me a drink. :-)

I think I get your point about scientists, best they don't have to know about async at all. So maybe it's Jupyter's fault for having an event loop running already. If what you say is roughly true, top-level `await` is addictive candy for CS nerds, but rarely useful for scientists, and causes them pain (which `nest_asyncio` solves with a big hammer).

But if we accept that Jupyter wants to do it this way, your proposal of having a context manager that sets something like a context var to communicate to `asyncio.run()` that it should ignore the existing loop makes sense.

We very much have to debate whether it's better in that case for `asyncio.run()` to reuse the existing loop or whether it should create a new loop.

Creating a new loop is probably simpler to implement in `run()`, because it would (mostly) just mean that it can ignore the check for "is a loop already running" and everything else remains the same. A possible exception would be the `set_event_loop()` call and the logic around that -- it might have to save/restore the "current" event loop.

The semantics of creating a new loop are also simpler: the outer loop is just as blocked as when you call some CPU-consuming function. And no promises are broken except the "don't do blocking I/O without using `await`".

Reusing the loop would make the implementation slightly more complicated (I think), but the real downside is that it *does* break the promise I take most seriously -- in an `asyncio` world, other tasks and callbacks are guaranteed **only** to run at `await` points. OTOH it consumes fewer resources (there's only one event loop object), and tasks/callbacks in scenarios that don't care about the strong guarantee will not be blocked.

All in all I think I'd just approve a properly done PR that implements this idea if it creates a new loop, but I'd be wary of a version reusing the loop, so if you feel strongly that the latter is better, you'll have to show a very clear scenario here.

**Comment by tomkcook** [comment]
I beg you not to get hung up on Jupyter as the only use case prompting this requirement.  The scenario described by @zzzeek above is also important; an existing library written in blocking code which can load drivers to interact with network resources.  Naturally the writers of those drivers want to be able to use asyncio under the covers.  But the library developers don't want to have to rewrite their entire library to support that.  So you end up with red/blue delineation, not only at the function level but at the library level.

**Comment by gvanrossum** [comment]
So many words. Does anyone have any code to contribute that satisfies various requirements?

**Comment by CarliJoy** [comment]
I actually thought I needed this to prevent code duplication within decorators that wrap both async and sync code.

But inspired by [@njsmith](https://github.com/python/cpython/issues/66435#issuecomment-1093662826) I figured out a solution [which I documented in stackoverflow](https://stackoverflow.com/questions/78170266/python-decorator-for-async-and-sync-function-without-code-duplication/78170267#78170267).

**Comment by willingc** [comment]
Thank you @CarliJoy for sharing your solution.

@gvanrossum I would like to close this issue. IMHO, I don't see us adding nested event loops due to the added complexity and overhead. I think reasoning about event loops is difficult enough with one loop, and nested event loops would contribute to even more unpredictable behavior in a program.

**Comment by qci-amos** [comment]
I support a low level `asyncio` library which I must expose through a 3rd party sync-only library (maybe even multiple such layers), all of which needs to be executable from within Jupyter. I would welcome some official Python documentation/examples explaining what I'm supposed to do or I request some kind of endorsement of `nest_asyncio`.

As an aside, I just discovered that Ewald de Wit, the author and maintainer of `nest_asyncio`, [has just passed away](https://github.com/erdewit/ib_insync/commit/ef5ea29e44e0c40bbadbc16c2281b3ac58aa4a40). RIP.

**Comment by davidbrochart** [comment]
@qci-amos The latest library I learnt about that could help you is [greenback](https://github.com/oremanj/greenback).

**Comment by douglas-raillard-arm** [comment]
So 3 years after [my previous comment](https://github.com/python/cpython/issues/66435#issuecomment-1093662840), it's back to square one:
1. Running `nest_asyncio.apply()` under `gunicorn` gives an exception immediately:
```
  File "/lib/python3.12/site-packages/nest_asyncio.py", line 193, in _patch_loop
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'uvloop.Loop'>
```
This is not too surprising TBH, considered the implementation relies on pretty hacky monkey patching.

2. Unless the project gets forked/re-owned, this will not be fixed

3. The `greenback` alternative seems to provide a useful building block, but for how long and with what reliability ? From [greenback's own doc](https://greenback.readthedocs.io/en/latest/principle.html#greenlets-a-different-approach):
> The approach required deep architecture-specific magic and elicited a number of subtle bugs, but those have generally been worked out in the years since the first release in 2006, such that the package is now considered pretty stable.

Although I'm glad bugs got ironed out, it does not fill me with confidence, especially considered the general amount of change in recent CPython versions (JIT in 3.13 etc).

4. @CarliJoy 's SO post is interesting to remove duplication in decorator code, but brings nothing when it comes to the backward compat use case (my initial comment). Taking the place of the event loop and using `.send(None)` obviously fails pretty quickly on even a basic `await asyncio.sleep()`, which is not suprising as the asyncio event loop does a bit more than nothing at all :)

5. The only solution that does not rely on deep low-level hacks or monkey patching I found was to spin up a thread for every re-entrant call, and wait for the thread to finish. This is not satisfactory since the perf cost is very high and requires thread safety in the code. On top of that, the lib I'm working on uses thread local values, so running some code in another thread can trigger a re-connection over SSH, and using a thread pool means these extra connections become somewhat immortal.

So unless I missed anything the problem is still opened: there is no reasonable way to provide a sync API shim for backward compat on top of an async API using `asyncio`. 

@willingc Should I open a new issue specifically for that backward compat use case ? I'm not particularly attached to any implementation detail (nested event loop or otherwise) so it's fine to me that this specific thread got closed on those grounds:
> IMHO, I don't see us adding nested event loops due to the added complexity and overhead

However, the actual issue I'm facing is still very much unsolved, and closing the thread is unfortunately not going to change that, and it will not help discoverability for other people having the same problem. If `greenback` is the endorsed way to go then so be it, but I'll be hesitant until I see an official recommendation to use it.

**Comment by willingc** [comment]
@douglas-raillard-arm I think opening a new issue makes sense if you focus on the specific issue that you are facing. Please focus more on the issue and less on how to solve the issue. Including a small executable example would be helpful too. Thanks!
