### ISSUE TITLE
Direct sub-classing of pathlib.Path

### ISSUE THREAD

**Issue by 114124f8-a54e-4a8a-a5ba-52165f132225** [python/cpython#68320]
BPO | [24132](https://bugs.python.org/issue24132)
--- | :---
Nosy | @pfmoore, @pitrou, @keithy, @qb-cea, @miss-islington, @FFY00, @barneygale, @Xtrem532, @nyuszika7h, @kfollstad
PRs | <li>python/cpython#6248</li><li>python/cpython#25240</li><li>python/cpython#25271</li><li>python/cpython#25701</li><li>python/cpython#26141</li><li>python/cpython#26438</li><li>python/cpython#26708</li><li>python/cpython#26906</li><li>python/cpython#31085</li><li>python/cpython#31691</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-05-06.05:26:53.017>
labels = ['type-feature', 'library', '3.11']
title = 'Direct sub-classing of pathlib.Path'
updated_at = <Date 2022-03-09.23:54:09.299>
user = 'https://bugs.python.org/projetmbc'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-09.23:54:09.299>
actor = 'barneygale'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-05-06.05:26:53.017>
creator = 'projetmbc'
dependencies = []
files = []
hgrepos = []
issue_num = 24132
keywords = ['patch']
message_count = 28.0
messages = ['242643', '242651', '242656', '242657', '242689', '242696', '242699', '242700', '242701', '242702', '242703', '242705', '246007', '305799', '305811', '305827', '305830', '305918', '310634', '314561', '314582', '314625', '365277', '381321', '392695', '401946', '412354', '414821']
nosy_count = 15.0
nosy_names = ['paul.moore', 'pitrou', 'bronger', 'elguavas', 'piotr.dobrogost', 'Kevin.Norris', 'projetmbc', 'keithy', 'qb-cea', 'miss-islington', 'FFY00', 'barneygale', 'Xtrem532', 'nyuszika7h', 'kfollstad']
pr_nums = ['6248', '25240', '25271', '25701', '26141', '26438', '26708', '26906', '31085', '31691']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue24132'
versions = ['Python 3.11']
```

</p></details>

**Comment by 287a392c-1882-4f2f-bebc-78a5b678f680** [comment]
Using a set of paths with special properties and formats in a project, thought "the cleanest oop way to do this is try out python's oop paths in pathlib". Subclassed Path to implement my extra (non platfor specific) properties and fell at the first hurdle because of this issue... 

for me pathlib does not provide oop paths if i can't subclass Path, for whatever reason.

reverted to treating paths as strings and writing functions to handle my special path properties and formats.

i was also surprised when i found another bug report on this issue that said it was closed for 3.7, great i thought this has been solved, but no, the other report was closed because it was about the same issue as this ancient report.

**Comment by pfmoore** [comment]
@elguavas the problem is, no-one has proposed a patch. There's not likely to be much movement on this until someone provides one.

**Comment by 114124f8-a54e-4a8a-a5ba-52165f132225** [comment]
For the moment, you can take a look at this little script that acheives 
subclassing of Path : 
https://github.com/bc-python/mistool/blob/master/mistool/os_use.py 
(search for class Path).

Le 08/11/2017 à 09:55, Paul Moore a écrit :
> Paul Moore \<p.f.moore@gmail.com\> added the comment:
>
> @elguavas the problem is, no-one has proposed a patch. There's not likely to be much movement on this until someone provides one.
>
> \----------
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<https://bugs.python.org/issue24132\>
> _______________________________________

**Comment by 114124f8-a54e-4a8a-a5ba-52165f132225** [comment]
Mistyping : /search for class PPath/ with two P.

Le 08/11/2017 à 13:59, Christophe BAL a écrit :
> Christophe BAL \<projetmbc@gmail.com\> added the comment:
>
> For the moment, you can take a look at this little script that acheives
> subclassing of Path :
> https://github.com/bc-python/mistool/blob/master/mistool/os_use.py
> (search for class Path).
>
> Le 08/11/2017 à 09:55, Paul Moore a écrit :
>\> Paul Moore \<p.f.moore@gmail.com\> added the comment:
>\>
>\> @elguavas the problem is, no-one has proposed a patch. There's not likely to be much movement on this until someone provides one.
>\>
>\> \----------
>\>
>\> _______________________________________
>\> Python tracker \<report@bugs.python.org\>
>\> \<https://bugs.python.org/issue24132\>
>\> _______________________________________
> \----------
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<https://bugs.python.org/issue24132\>
> _______________________________________

**Comment by 287a392c-1882-4f2f-bebc-78a5b678f680** [comment]
@paul.moore is the original contributor mia? i seem to remember pathlib as once being marked 'provisional', i think it should have stayed that way until this problem was resolved. easy to say i know ;) when i don't have a patch.

@projetmbc yes i found various work-arounds on the web and decided to not use any of them. really i feel this should be fixed as it's a jarring inconsistency with naturally expected behaviour for a class in python.

so i added my report to this as a topic bump because i don't think this should be forgotten about and in case anyone might come up with an idea how to fix it.

**Comment by mzipay** [comment]
Sorry if I'm "late to the party," but ALL of the discussion from non-mannequins seems (to me) to miss the point **entirely**.

The `pathlib` module fails (**grossly**, IMO) to respect two key "Pythonic" principles:
#. If the implementation is hard to explain, it's a bad idea.
