### ISSUE TITLE
In argparse subparser's option goes to parent parser

### ISSUE THREAD

**Issue by 13bd9cc7-04b0-4774-9e07-8b0322e89dcc** [python/cpython#68665]
BPO | [24477](https://bugs.python.org/issue24477)
--- | :---
Nosy | @py-user

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-06-20.00:52:42.933>
labels = ['type-bug', 'library']
title = "In argparse subparser's option goes to parent parser"
updated_at = <Date 2015-06-20.00:52:42.933>
user = 'https://github.com/py-user'
```

bugs.python.org fields:
```python
activity = <Date 2015-06-20.00:52:42.933>
actor = 'py.user'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-06-20.00:52:42.933>
creator = 'py.user'
dependencies = []
files = []
hgrepos = []
issue_num = 24477
keywords = []
message_count = 1.0
messages = ['245536']
nosy_count = 1.0
nosy_names = ['py.user']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue24477'
versions = ['Python 3.6']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
I do not see anything wrong or controversial here. `argparse` allows to pass options after positional arguments, and in the third example it is passed after positional argument `arg` that belongs to the main parser. It cannot be passed to the subparser, because the subparser already finished its work, and the main parser parsed arguments that follow the subparser.
