### ISSUE TITLE
unittest assertEqual difference output foiled by newlines

### ISSUE THREAD

**Issue by cjerdonek** [python/cpython#68968]
BPO | [24780](https://bugs.python.org/issue24780)
--- | :---
Nosy | @tim-one, @loewis, @rbtcollins, @ezio-melotti, @bitdancer, @voidspace, @cjerdonek, @elenaoat, @AnishShah, @tirkarthi, @nanjekyejoannah
PRs | <li>python/cpython#11548</li><li>python/cpython#11548</li><li>python/cpython#11548</li>
Files | <li>[test.py](https://bugs.python.org/file41636/test.py "Uploaded as text/plain at 2016-01-17.01:22:50 by pynewbie"): Test case to reproduce the bug</li><li>[test2.py](https://bugs.python.org/file41639/test2.py "Uploaded as text/plain at 2016-01-17.13:42:39 by @elenaoat")</li><li>[issue24780.patch](https://bugs.python.org/file41782/issue24780.patch "Uploaded as text/plain at 2016-02-02.16:59:20 by @AnishShah")</li><li>[fix_24780.patch](https://bugs.python.org/file44679/fix_24780.patch "Uploaded as text/plain at 2016-09-15.22:29:38 by adchanw")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-08-02.16:49:29.240>
labels = ['3.7', '3.8', 'type-bug', 'library', 'easy']
title = 'unittest assertEqual difference output foiled by newlines'
updated_at = <Date 2019-01-14.15:30:04.394>
user = 'https://github.com/cjerdonek'
```

bugs.python.org fields:
```python
activity = <Date 2019-01-14.15:30:04.394>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-08-02.16:49:29.240>
creator = 'chris.jerdonek'
dependencies = []
files = ['41636', '41639', '41782', '44679']
hgrepos = []
issue_num = 24780
keywords = ['patch', 'easy']
message_count = 14.0
messages = ['247883', '247947', '258132', '258466', '259375', '259403', '261713', '275942', '276633', '333277', '333289', '333295', '333584', '333627']
nosy_count = 13.0
nosy_names = ['tim.peters', 'loewis', 'rbcollins', 'ezio.melotti', 'r.david.murray', 'michael.foord', 'chris.jerdonek', 'Elena.Oat', 'anish.shah', 'pynewbie', 'adchanw', 'xtreak', 'nanjekyejoannah']
pr_nums = ['11548', '11548', '11548']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue24780'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-103937

**Comment by mblahay** [comment]
The root cause of the issue is the way lines of text must be submitted to the difflib.ndiff function. The documentation states that ndiff is to receive two lists, each containing the lines to be compared. What is not stated, rather inferred from the example provided with the documentation, is that each line MUST end with a newline. For what we are doing here with assertEquals, the problem appears when comparing strings comprised of two or more lines, and the final line is not terminated by a newline.

Why doesn't this happen when comparing single lines? Surprisingly, in the case when there is one line and the newline is missing, a newline is added. The addition of the newline simply doesn't occur when there are more than one line; I don't know why. The fix will be a change the logic to check the final line of each group for the newline and add if necessary.

But why does the comparison of '\nabc' and '\nabd' result in the garbled output? I know it may be hard to believe, but each of those strings represent two lines. Lets take a closer look at '\nabc'; if your split the text using the str.splitlines function, and the keepends=True option, you will end up with '\n' and 'abc'. Because there are two lines, the missing newline is not appended to the 'abc', and garbling ensues.

I do hope this helps with the understanding of the issue.

**Comment by mblahay** [comment]
@adchanw, I took a look at your proposed fix. You are checking each line  ndiff output and adding a newline if missing. Since the root of the problem is the input into the ndiff function, it is better to handle the problem there.

**Comment by mblahay** [comment]
@AnishShah, Your proposed fix seems to be more in line with what the fix should be. I'm going to create a pull request to accomplish something similar. There are opportunities to optimize your changes.

**Comment by itamaro** [comment]
it seems gh-103937 fixes this issue.
closing, but please reopen if there's additional work to be done here!
