### ISSUE TITLE
argparse doc introduction is inappropriately targeted

### ISSUE THREAD

**Issue by 5cd21ea9-932d-4a19-96c8-75f23db9662e** [python/cpython#70789]
BPO | [26602](https://bugs.python.org/issue26602)
--- | :---
Nosy | @vadmium, @csabella
Files | <li>[bguo.patch](https://bugs.python.org/file42248/bguo.patch "Uploaded as text/plain at 2016-03-23.04:18:25 by BGuo1")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-03-21.12:11:34.755>
labels = ['3.7', 'docs']
title = 'argparse doc introduction is inappropriately targeted'
updated_at = <Date 2017-06-04.21:10:28.095>
user = 'https://bugs.python.org/DanielStone'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-04.21:10:28.095>
actor = 'cheryl.sabella'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2016-03-21.12:11:34.755>
creator = 'Daniel Stone'
dependencies = []
files = ['42248']
hgrepos = []
issue_num = 26602
keywords = ['patch']
message_count = 5.0
messages = ['262121', '262238', '262311', '289572', '295144']
nosy_count = 6.0
nosy_names = ['docs@python', 'martin.panter', 'paul.j3', 'BGuo1', 'Daniel Stone', 'cheryl.sabella']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue26602'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vadmium** [comment]
The patch looks unfinished. I left some narrow nit-picky review comments, but I haven’t really thought about the problem from a high level.

**Comment by csabella** [comment]
If it helps at all, I first learned about argparse a few weeks ago.  I first went to the doc page and then immediately went to the tutorial, as suggested.  I didn't find it difficult or off-putting at all.  In fact, I loved that there was a tutorial that it explained it perfectly for my level as a newbie.  I've referenced the doc page a few times since, but I haven't read it from beginning to end like I did to learn the str functions, for example.  I think the doc page should be more advanced for people who need to know it's full power (as it is now) and the tutorial can serve newbies (as it does now).

**Comment by savannahostrowski** [comment]
This issue is fairly old, and I think that the tutorial addresses the need for a more gentle intro.

That said, I am going to close this issue. If anyone has additional feedback about the current intro to the argparse docs and finds that they still fall short, please feel free to open a new issue and tag me. I am happy to discuss and address the feedback.
