### ISSUE TITLE
[doc] Questionable terminology ('free variables') for describing what locals() does

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#70870]
BPO | [26683](https://bugs.python.org/issue26683)
--- | :---
Nosy | @rhettinger, @terryjreedy, @vadmium, @marco-buttu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-04-01.01:31:32.772>
labels = ['3.11', '3.9', '3.10', 'docs']
title = "[doc] Questionable terminology ('free variables') for describing what locals() does"
updated_at = <Date 2021-11-27.00:24:37.261>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-27.00:24:37.261>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2016-04-01.01:31:32.772>
creator = 'rhettinger'
dependencies = []
files = []
hgrepos = []
issue_num = 26683
keywords = []
message_count = 6.0
messages = ['262713', '262718', '262722', '262753', '282284', '282989']
nosy_count = 5.0
nosy_names = ['rhettinger', 'terry.reedy', 'docs@python', 'martin.panter', 'marco.buttu']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue26683'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-122545

**Comment by ncoghlan** [comment]
In 3.13, the `locals()` docs now say:

> In an [optimized scope](https://docs.python.org/3.13/glossary.html#term-optimized-scope) (including functions, generators, and coroutines), each call to locals() instead returns a fresh dictionary containing the current bindings of the function’s local variables and any nonlocal cell references.

I also posted a separate PR after reviewing all the references to "free variable" in the documentation: https://github.com/python/cpython/pull/122545

While I left some of them alone, I changed several others to either "closure variable", "free closure variable", or specific references to `co_freevars`.

The PR makes the definitions of "co_freevars" and "__closure__" reference each other and defines both "free variable" and "closure variable" in the glossary. The definition of "free variable" notes that the term gets used in two different ways rather than attempting to exclusively reserve it for the formally correct meaning.
