### ISSUE TITLE
New assert method that checks an error message for a list of strings

### ISSUE THREAD

**Issue by soltysh** [python/cpython#71319]
BPO | [27132](https://bugs.python.org/issue27132)
--- | :---
Nosy | @rbtcollins, @ezio-melotti, @bitdancer, @voidspace, @berkerpeksag, @vadmium, @serhiy-storchaka, @soltysh, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-05-26.20:48:13.145>
labels = ['type-feature', 'tests']
title = 'New assert method that checks an error message for a list of strings'
updated_at = <Date 2022-03-22.21:42:01.387>
user = 'https://github.com/soltysh'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-22.21:42:01.387>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2016-05-26.20:48:13.145>
creator = 'maciej.szulik'
dependencies = []
files = []
hgrepos = []
issue_num = 27132
keywords = []
message_count = 9.0
messages = ['266454', '266456', '266457', '266461', '266472', '266558', '266564', '266567', '415820']
nosy_count = 9.0
nosy_names = ['rbcollins', 'ezio.melotti', 'r.david.murray', 'michael.foord', 'berker.peksag', 'martin.panter', 'serhiy.storchaka', 'maciej.szulik', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue27132'
versions = []
```

</p></details>

**Comment by bitdancer** [comment]
For the record, the approach I've adopted in my own code for this is regexes of the form `r'(?=.*thisdirdoesntexist)(?=.*no.*directory)'`, which achieves the 'match multiple substrings in any position' requirement.  But the result when the regex fails is less helpful than it could be, since you don't know which substring failed to match.  It is, however, straightforward and not too verbose.  I think it was @zware that suggested this to me, but I don't remember for sure :)
