### ISSUE TITLE
Unpickling Path objects

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#71362]
BPO | [27175](https://bugs.python.org/issue27175)
--- | :---
Nosy | @pitrou, @serhiy-storchaka, @anntzer
PRs | <li>python/cpython#28083</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-06-01.09:18:04.911>
labels = ['type-feature', 'library', '3.11']
title = 'Unpickling Path objects'
updated_at = <Date 2021-09-01.08:14:57.293>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-01.08:14:57.293>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-06-01.09:18:04.911>
creator = 'Antony.Lee'
dependencies = []
files = []
hgrepos = []
issue_num = 27175
keywords = ['patch']
message_count = 12.0
messages = ['266810', '400703', '400706', '400709', '400711', '400714', '400716', '400719', '400721', '400817', '400820', '400822']
nosy_count = 3.0
nosy_names = ['pitrou', 'serhiy.storchaka', 'Antony.Lee']
pr_nums = ['28083']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue27175'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-116523

**Comment by barneygale** [comment]
To me, it feels too magical to automatically downgrade the objects to pure paths when unpickling on a foreign OS. Are there other places in the standard library where something like this occurs?

**Comment by barneygale** [comment]
I've opened a PR that pickles `PosixPath` and `WindowsPath` paths as `Path`, which allows them to be unpickled on any OS. I'm not sure if it's a sensible approach as non-relative paths work differently. Perhaps we could apply it only to purely relative paths? (no drive nor anchor)

**Comment by barneygale** [comment]
I've tried a few approaches to addressing this, but nothing feels quite right.

Downgrading to `PurePath` or its flavour-specific variants, either at pickle or unpickle time, feels too surprising. Rather than a user program breaking during unpickling, it will break as soon as any `Path` API is used with the unpickled objects. If users are expected to avoid using `Path` APIs with unpickled objects, then they may as well work with `PurePath` to begin with.

Downgrading to `Path` risks silent data corruption in cases where POSIX and Windows parse paths differently, which is pretty common. If we downgrade only when we can ensure that paths are parsed the same on both OSs, we make pickling behaviour rather subtle and hard to predict for users, and hard to document for us.

I'll close this issue and the PRs. If anyone feels I've misjudged this, feel free to leave a comment and I can re-open.
