### ISSUE TITLE
argparse: successive parsing wipes out nargs=? values

### ISSUE THREAD

**Issue by dee71fb9-726a-4eb7-b129-76f645b61d71** [python/cpython#72920]
BPO | [28734](https://bugs.python.org/issue28734)
--- | :---
Nosy | @wm75, @adamjstewart

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-11-18.15:41:15.800>
labels = ['invalid', 'type-bug', 'library']
title = 'argparse: successive parsing wipes out nargs=? values'
updated_at = <Date 2017-07-29.00:02:53.657>
user = 'https://github.com/adamjstewart'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-29.00:02:53.657>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-11-18.15:41:15.800>
creator = 'ajstewart'
dependencies = []
files = []
hgrepos = []
issue_num = 28734
keywords = []
message_count = 4.0
messages = ['281128', '281137', '281138', '299354']
nosy_count = 4.0
nosy_names = ['bethard', 'paul.j3', 'wolma', 'ajstewart']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue28734'
versions = ['Python 3.5']
```

</p></details>

**Comment by 7a064fe6-c535-4d80-a11f-a04ed39056c5** [comment]
The problem described here is restricted to `?` and `*' positionals, and is caused by the subtle way in which 'empty' optional positionals are handled.

The regular handling of defaults at the start of `parse_known_args` works fine.  The default is only written to the namespace if something isn't there already.

```py
     if not hasattr(namespace, action.dest):
         if action.default is not SUPPRESS:
              setattr(namespace, action.dest, action.default)
```


But a positional with ? or * is always 'seen' because an empty list of strings satisfies the nargs pattern.  'get_values()' has special handling for this case:

```py
        if not arg_strings and action.nargs == OPTIONAL:
            ....
                value = action.default
```


That is, it replaces the empty list with the 'default'. 

But take_action(), which does the actual saving, is conditional:

```py
            # take the action if we didn't receive a SUPPRESS value
            # (e.g. from a default)
            if argument_values is not SUPPRESS:
                action(self, namespace, argument_values, option_string)
```


That explains why 'default=SUPPRESS' solves this issue.

It's enough to satisfy the OP's situation, but I don't think it's a robust fix.

I don't have a patch idea yet, but this probably should be reopened so there's a record of the potential problem.

More on the complications raised by these 'seen default actions' in 

http://bugs.python.org/issue18943
