### ISSUE TITLE
Document all "python -m" utilities

### ISSUE THREAD

**Issue by daf46b87-a9e9-4381-bf23-8c373c9135e6** [python/cpython#73158]
BPO | [28972](https://bugs.python.org/issue28972)
--- | :---
Nosy | @gvanrossum, @rhettinger, @tebeka, @aaronchall, @elafontaine, @GadgetSteve

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-12-14.13:00:03.262>
labels = ['type-feature', 'docs']
title = 'Document all "python -m" utilities'
updated_at = <Date 2017-09-09.22:26:23.101>
user = 'https://github.com/tebeka'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-09.22:26:23.101>
actor = 'Aaron Hall'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2016-12-14.13:00:03.262>
creator = 'tebeka'
dependencies = []
files = []
hgrepos = []
issue_num = 28972
keywords = []
message_count = 9.0
messages = ['283190', '283359', '283461', '283470', '283498', '283537', '286839', '300154', '301793']
nosy_count = 7.0
nosy_names = ['gvanrossum', 'rhettinger', 'tebeka', 'docs@python', 'Aaron Hall', 'Eric Lafontaine', 'Steve Barnes']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue28972'
versions = []
```

</p></details>

**Comment by 80c73838-aa1d-43ef-8f08-69c1afb3791f** [comment]
Having done some checks for the practicality of auto documenting library items with a -m command line usage I have to say that it will not be so simple. 

Many of the library items that provide useful functionality, including zipfile & tarfile, are implemented as single .py files, rather than as modules so have no \_\_main__.py to trigger the inclusion in auto-generated documentation. 

I also tried searching for standard library items that use \`if \_\_name__ == "\_\_main__":\` constructs but, of course, many files simply use that to expose tests rather than useful functionality - so that is out as well. I even thought of trying for a regex that would look for this followed, in the same scope by argparse but of course there is no obligation to use it.

And of course main() does not HAVE to be called main so that is out.

Sorry to scotch the idea Eric!

**Comment by affb16c2-6fdb-403f-b328-86b7e719c99e** [comment]
I like this idea too, but perhaps it should just be a multi-column bulleted list (under the -m flag at https://docs.python.org/3/using/cmdline.html#interface-options) with links to the respective Standard Library doc?

Then we just ensure the documentation for the module is complete with examples for the command line usage.

**Comment by slateny** [comment]
Per [comment](https://github.com/python/cpython/issues/59150#issuecomment-1180131644) and discussion in #93410, closing as the ability to be used as `-m` should be listed in the modules themselves over a complete list.

**Comment by vstinner** [comment]
Implemented in issue gh-109435 as new documentation page: https://docs.python.org/dev/library/cmdline.html
