### ISSUE TITLE
Problem with Checkbutton and  duplicate last name components

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#73588]
BPO | [29402](https://bugs.python.org/issue29402)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka
Files | <li>[tkinter-checkbutton-unique-variables.patch](https://bugs.python.org/file46696/tkinter-checkbutton-unique-variables.patch "Uploaded as text/plain at 2017-03-03.20:52:20 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2017-01-31.21:34:54.653>
labels = ['3.7', 'expert-tkinter', 'type-bug', 'library']
title = 'Problem with Checkbutton and  duplicate last name components'
updated_at = <Date 2017-03-03.20:52:20.440>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-03.20:52:20.440>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Tkinter']
creation = <Date 2017-01-31.21:34:54.653>
creator = 'terry.reedy'
dependencies = []
files = ['46696']
hgrepos = []
issue_num = 29402
keywords = ['patch', '3.6regression']
message_count = 3.0
messages = ['286552', '286611', '288926']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29402'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Here is a sample patch that makes implicit variables for checkbuttons unique. This is one of ways to solve this issue.

But I'm not sure that this issue needs to be solved at all. In real applications Checkbutton() is called with the variable argument, otherwise it would be not very useful. Only sample code can call Checkbutton() without the variable argument.

**Comment by serhiy-storchaka** [comment]
PR #97547 slightly differs from the initial patch. It makes the last element of the name unique by default instead of making the checkbutton variable. If you implicitly specify the same `name` argument for different checkbuttons, they will share the state.

`ttk.Checkbutton` does not have such problem, because it uses the full name as the variable name, it is always unique.
