### ISSUE TITLE
doc 17.2.1: basic Pool example is too basic

### ISSUE THREAD

**Issue by d5976d5e-c853-4096-affc-0ce4d81ac6f5** [python/cpython#73761]
BPO | [29575](https://bugs.python.org/issue29575)
--- | :---
Nosy | @methane, @berkerpeksag, @applio, @jwuttke
Files | <li>[smime.p7s](https://bugs.python.org/file46657/smime.p7s "Uploaded as application/pkcs7-signature at 2017-02-21.09:11:38 by @jwuttke")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-21.01:42:28.787>
created_at = <Date 2017-02-15.22:59:20.340>
labels = ['type-feature', '3.7', 'docs']
title = 'doc 17.2.1: basic Pool example is too basic'
updated_at = <Date 2017-02-21.09:11:39.092>
user = 'https://github.com/jwuttke'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-21.09:11:39.092>
actor = 'jwuttke'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-02-21.01:42:28.787>
closer = 'davin'
components = ['Documentation']
creation = <Date 2017-02-15.22:59:20.340>
creator = 'jwuttke'
dependencies = []
files = ['46657']
hgrepos = []
issue_num = 29575
keywords = []
message_count = 7.0
messages = ['287895', '288045', '288253', '288274', '288276', '288278', '288279']
nosy_count = 6.0
nosy_names = ['methane', 'docs@python', 'berker.peksag', 'davin', 'Winterflower', 'jwuttke']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29575'
versions = ['Python 3.7']
```

</p></details>

**Comment by d5976d5e-c853-4096-affc-0ce4d81ac6f5** [comment]
The »basic example of data parallelism using Pool« is too basic. It demonstrates the syntax, but otherwise makes no sense, and therefore is potentially confusing. It is blatant nonsense to run 5 processes when there are only 3 data to be treated. Let me suggest the following:


```py
from multiprocessing import Pool
import time

def f(x):
    time.sleep(1)
    return x*x

if __name__ == '__main__':
    start_time = time.time()
    with Pool(4) as p:
        print(p.map(f, range(20)))
    print("elapsed wall time: ", time.time()-start_time)
```


The sleep command makes f representative for a function that takes significant time to execute. Printing the elapsed time shows the user that the 20 calls of f have indeed taken place in parallel.

**Comment by 913479bb-37e6-4dd5-9d09-bfa0704c65f0** [comment]
Would you like to open a PR with a patch on GH? I think the docs could certainly do with another example for Pool.

**Comment by applio** [comment]
When passing judgement on what is "too basic", the initial example should be so basic as to be immediately digestible by as many people as possible.

Some background:
All too many examples mislead newcomers into believing that the number of processes should (a) match the number of processor cores, or (b) match the number of inputs to be processed.  This example currently attempts to dispel both notions.  In practice, and this depends upon what specific code is to be performed in parallel, it is not uncommon to find that slightly over-scheduling the number of processes versus the number of available cores can achieve superior throughput and performance.  In other cases, slightly under-scheduling may provide a win.  To help subtly encourage the newcomer, this example uses 5 processes as opposed to something which might be mistaken for a common number of cores available on current multi-core processors.  Likewise, the number of distinct inputs to be processed deliberately does not match the number of processes nor a multiple of the number of processes.  This hopefully encourages the newcomer to not feel obligated to only accept inputs of a particular size or multiple.  Granted, optimizing for performance motivates tuning such things but this is the first example / first glance at what functionality is available.

Considering the suggested change:
* range(20) will likely produce more output than can be comfortably accommodated and easily read in the available browser window where most will see this
* the addition of execution time measurement is an interesting choice here given how computationally trivial the f(x) function is, which is perhaps what motivated the introduction of a time.sleep(1) inside that function; a ThreadPool would be more appropriate for a sleepy function such as this

Ultimately these changes complicate the example while potentially undermining its value.  An interesting improvement to this example might be to introduce a computationally taxing function which more clearly demonstrates the benefit of using a process Pool but still achieving the ideal of being immediately digestible and understood by the largest reading audience.  Some of the topics/variations in the proposed change might be better introduced and addressed later in the documentation rather than unnecessarily complicating the first example.

**Comment by d5976d5e-c853-4096-affc-0ce4d81ac6f5** [comment]
Dear Davin,

since I am new to the Python bug tracker, I have to asked
a stupid question: are you the benevolent dictator of the
Python Standard Library?

Otherwise, how can it be that one and the same person in
one and the same intervention adds new arguments to the
debate, conclude that theses arguments are winning,
declares that the current state »works for me«, and closes
the issue, thereby cutting short any further debate?

I have several other issues with the current Python
documentation, but if defenders of the status quo are
acting that boldly, I would only waste my time to raise
them.

With best regards, Joachim

**Comment by methane** [comment]
I like current, minimum example to describe API.

No need to make it complex only for checking it's really executed in parallel.

Adding more and more "may be useful for someone" code in the doc make the document long, hard and tedious to read for everyone.

**Comment by berkerpeksag** [comment]
I agree with and Davin and Inada. Note that multiprocessing documentation is already too long and we'd like to be careful before adding another example.

If you could create a "multiprocessing cookbook" on wiki.python.org I'm pretty sure we'd be happy to consider adding a link to it in the documentation.

**Comment by d5976d5e-c853-4096-affc-0ce4d81ac6f5** [comment]
I never proposed to add a second example, but to make the one example more meaningful.

As a minimal solution, could we replace the numbers 3 (input data) and 5 (threads)
by a slightly more plausible choice? Davin explained why numbers should be
incommensurate. So what about 10 data, 3 threads?
