### ISSUE TITLE
Improve UnboundLocalError message for deleted names

### ISSUE THREAD

**Issue by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [python/cpython#73779]
BPO | [29593](https://bugs.python.org/issue29593)
--- | :---
Nosy | @warsaw, @rhettinger, @bitdancer, @vadmium, @serhiy-storchaka, @vedgar, @ilevkivskyi, @Carreau
PRs | <li>python/cpython#141</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-17.18:06:14.801>
created_at = <Date 2017-02-17.17:06:57.054>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Improve UnboundLocalError message for deleted names'
updated_at = <Date 2017-08-17.18:06:14.800>
user = 'https://github.com/Carreau'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-17.18:06:14.800>
actor = 'mbussonn'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-17.18:06:14.801>
closer = 'mbussonn'
components = ['Interpreter Core']
creation = <Date 2017-02-17.17:06:57.054>
creator = 'mbussonn'
dependencies = []
files = []
hgrepos = []
issue_num = 29593
keywords = []
message_count = 9.0
messages = ['288023', '288024', '288032', '288033', '288038', '288041', '289165', '300399', '300452']
nosy_count = 8.0
nosy_names = ['barry', 'rhettinger', 'r.david.murray', 'martin.panter', 'serhiy.storchaka', 'veky', 'levkivskyi', 'mbussonn']
pr_nums = ['141']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29593'
versions = ['Python 3.7']
```

</p></details>

**Comment by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [comment]
Raymond Hettinger reported during PyCon Canada 2016 Keynote (~20m30 sec)
that unbound local error message was inaccurate, it state that :

> local variable 'xxx' referenced before assignment

Though it can be assigned and deleted.

```py
    for a toy example:

       def foo():
          x = 1
          del x
          print(x)

       foo()
```


Do the same for free variable.

```py
    def multiplier(n):
	def multiply(x):
	    return x * n
	del n
	return multiply
```


The error message can be improved by adding "or got deleted".

**Comment by serhiy-storchaka** [comment]
Wouldn't be better to say just "local variable 'xxx' is not set"?

**Comment by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [comment]
> Wouldn't be better to say just "local variable 'xxx' is not set"?

Thank you for responding that fast and for your interest in this issue. 

While I think that "local variable 'xxx' is not set" is technically correct, I think it would be a step back.

The improvement of the error message is not really meant for the 99% of the developers hanging on b.p.o. I think for these just the fact that there is an UnboundLocalError is sufficient to know what's happening. 

The error message will mostly be useful for users that still don't have much clue about what's going on. For these kind of users UnboundLocalError("local variable 'xxx' is not set") is not much different from NameError("name 'xxx' is not defined")[*]

The current error message already does a good job at giving some extra hint as to why this is the case. In particular that it is (often) assigned but not in the right place. Changing to "local variable 'xxx' is not set" will likely make many novices check the spelling, and be more confused.

Note that "local variable 'xxx' referenced before assignment, or got deleted" would not be completely obvious for novices either, why would the following not trigger such an error ? 

In [1]: def foo():
   ...:     if False:
   ...:         print(n)
   ...:     n = 1

Well, for you and me it's (likely) obvious. 

I want to point out (just stealing rhettinger example) that it might not be obvious either the variable has been deleted:

In [5]: def foo():
   ...:     n = 1 
   ...:     def g(): # imagine a more complex g
   ...:         del n 
   ...:     g()
   ...:     print(n) #UnboundLocalError
   ...:

So I think expanding the error message to give hints as of \_why_ is better than just stating what is. 


[*] Source: The users I work with. Last question I got on wednesday: "Can you re-explain the difference between a string and a function". They meant "list" and "list comprehension".

**Comment by serhiy-storchaka** [comment]
Adding "or got deleted" makes the error message longer, and since "del" is rarely used for deleting local variables I afraid that it can add confusion in most cases.

The "del" statement is not the only way to unset the local variable.

```pycon
>>> def foo():
...     e = None
...     try:
...         1/0
...     except Exception as e:
...         pass
...     print(e)
... 
>>> foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 7, in foo
UnboundLocalError: local variable 'e' referenced before assignment
```

**Comment by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [comment]
> makes the error message longer

Out of curiosity is there a guide as to what is considered a too long error message ?

Or is there a technical reason like after a certain length strings are not cached and exception will be slower to construct ? I'm trying to understand why rhettinger would have proposed in his talk to make this specific error message longer and there is a push back now. 

> and since "del" is rarely used for deleting local variables I afraid that it can add confusion in most cases.

> The "del" statement is not the only way to unset the local variable.

Good point, would "or has been unset" be acceptable ?

**Comment by vadmium** [comment]
Matthias’s proposal sounds reasonable to me. There is a minor disadvantage that it will exceed the width of an 80-character terminal:

UnboundLocalError: local variable 'x' referenced before assignment, or got delet
ed

But I don’t think the wrapping is a big deal; it already happens with longer variable names anyway. I doubt using “unset” instead of “deleted” is any better. If you really wanted to make it clear, you would have to say “or got deleted, perhaps by an exception handler”, but that is probably going too far.

Another idea, which separates the hint from the technical error:

UnboundLocalError: local variable 'x' not set; perhaps it is not yet assigned

**Comment by serhiy-storchaka** [comment]
See also bpo-17792.

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
Re: http://bugs.python.org/msg288032

I don't know what example Raymond had, but your example

In [5]: def foo():
   ...:     n = 1 
   ...:     def g(): # imagine a more complex g
   ...:         del n 
   ...:     g()
   ...:     print(n) #UnboundLocalError

is completely wrong, at least in what you imply in the comments. It would be a horrible language where functions could just delete nonlocal names in the same way as local ones. (You can force it by adding `nonlocal n` inside g. But "nonlocal keyword is ugly for a good reason", to quote Guido.:)

It's interesting that in your example, you also get an ULE, but for a whole different reason: it is \_g_'s call that tries to \_delete_ (a kind of "referencing") a local (to \_it_) variable n, that hasn't yet been set \_in the scope of g_. You can see it easily in the traceback, and you'd probably see it if you didn't have preconceived notions about what happens. :-]

You can easily see it by removing print(n), it is a red herring, or even more simply, just define g globally:

```pycon
    >>> def g(): del n
    >>> g()
    UnboundLocalError: ...
```


You'll get the same phenomenon.

\---

About the error message: I agree with Serhiy. See http://www.drmaciver.com/2013/07/a-case-study-in-bad-error-messages/#comment-9095 (and the whole discussion if you miss the context). Trying to cover all the possible situations where an ULE might get raised is (a) futile, (b) worsening things, since experienced programmers already know that error messages are just approximations, and beginners are best helped with just the most common case.

May I ask why do you even teach "del on simple names" (as opposed to del on list items, which is kinda useful since it has a sideeffect) to beginners? It's very rarely needed, especially in a language with a powerful garbage collector.

**Comment by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [comment]
Thanks you all for your input, it seem like to much of electronic ink and time has been spend on this issue. For the sake of everyone and avoiding more to be spent, I'm going to close it.
