### ISSUE TITLE
Issue with spacing in argparse module while using help

### ISSUE THREAD

**Issue by daef3769-8373-4bce-8c94-c40aa3db9faf** [python/cpython#73812]
BPO | [29626](https://bugs.python.org/issue29626)
--- | :---
Nosy | @bitdancer, @serhiy-storchaka, @falu2010, @csabella
PRs | <li>python/cpython#1835</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-02-22.23:00:55.432>
labels = ['library']
title = 'Issue with spacing in argparse module while using help'
updated_at = <Date 2017-05-28.23:25:22.809>
user = 'https://github.com/falu2010'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-28.23:25:22.809>
actor = 'paul.j3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-02-22.23:00:55.432>
creator = 'falu2010'
dependencies = []
files = []
hgrepos = []
issue_num = 29626
keywords = []
message_count = 11.0
messages = ['288389', '288403', '288674', '288676', '288679', '288681', '288683', '294615', '294619', '294655', '294663']
nosy_count = 5.0
nosy_names = ['r.david.murray', 'paul.j3', 'serhiy.storchaka', 'falu2010', 'cheryl.sabella']
pr_nums = ['1835']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue29626'
versions = ['Python 2.7']
```

</p></details>

**Comment by 7a064fe6-c535-4d80-a11f-a04ed39056c5** [comment]
We need to see the parser setup as well.  I've never seen a bug like this before.  The `usage` line suggests that you are using subparsers.

It might be better if you asked this on StackOverFlow with a repeatable code example.  That's a better place to get debugging help of your own code.  Come back here if others think this is a problem with `argparse` itself rather than your own setup.

**Comment by daef3769-8373-4bce-8c94-c40aa3db9faf** [comment]
Sample code to repro this:

```py
import argparse

    parser = argparse.ArgumentParser(prog='cli')
    subparsers = parser.add_subparsers(dest="command")

    subparsers_user_delete = subparsers.add_parser("delete", help="Deletes a user in your organization.",
                                                        description="Deletes a user in your organization.")
    subparsers_user_delete.add_argument("userid", help="The userid of user.", default=None, type=int)
    subparsers_user_delete.add_argument("-p", "--projectid", metavar="",
                                        help="Specify the project ID of project from where you want to delete"
                                             " the user or else user will be deleted from organization.", type=int,
                                        default=None)

    parser_nodes = subparsers.add_parser('nodes')
    sp = parser_nodes.add_subparsers()
    p1 = sp.add_parser('list', description='Lists nodes in your current project')
    p1.add_argument('-p', '--projectid', action='store_true')
    p1.add_argument('-o', '--org', action='store_true', help=' (For administrators only) Lists all the nodes in')
    parser.parse_args()
```


Please run following command:
$issue.py delete -h

**Comment by serhiy-storchaka** [comment]
Does an empty metavar make sense? This makes the option with argument non-distinguising from the option without argument.

**Comment by csabella** [comment]
I submitted a PR for this based on paul.j3's suggested change:

```py
      def _format_action_invocation(self, action):
           ....
           for option_string in action.option_strings:
               if len(args_string)>0:
                    parts.append('%s %s' % (option_string, args_string))
               else:
                    parts.append('%s' % option_string)
           ....
```


I created a test that would have duplicated the original issue and, with the change, no longer prints the extra blank.

To Serhiy's point, I'm not sure if an empty metavar makes sense since it's intention is to give the parser a way to refer to the expected arguments within the help messages. 

However, with no metavar at all, the help output is:
  -f FOO, --foo FOO

With metavar = '' (and this change), the output is:
-f, --foo 

With metavar = '' (and without this change), the output is:
-f , --foo

**Comment by bitdancer** [comment]
If I'm interpreted what the OP wrote correctly, he wanted the help text to not show that the option takes an argument, but instead rely on the help text to show that.  That works for the option text, but it doesn't work for the synopsis (the synopsis is just wrong in that case).

Probably a blank metavar should just be rejected because of the issue with they synopsis.  That should only be done in 3.7 if we do it, though.

Perhaps the OP will respond to explain the blank-metavar use case in more detail.

**Comment by 7a064fe6-c535-4d80-a11f-a04ed39056c5** [comment]
I don't anticipate  any backward compatibility issues with the proposed patch.  But at the same time it feels almost too trivial of an issue to merit a patch.  

A short metavar such as `metavar="ID"' or even `metavar="_"' would be nearly as compact, and still leave an indicator of the required argument (in usage as well as the help).

I'm not even sure if disallowing a blank metavar is worth the change.

As indicated before I've only seen this extra space problem when I or others suggest the blank metavar as a way making a more compact help invocation.  That has come up frequently on SO, but I can't find a relevant bug/issue.  

https://stackoverflow.com/a/18280876/901925 - here I suggest suppressing the help line and putting custom info in the group's description.

https://stackoverflow.com/questions/9642692/argparse-help-without-duplicate-allcaps - suggests a help formatter subclass

So maybe the bigger issue is, can we make it easier to customize the the help invocation formatting?

Things to consider:

- metavar affects both the help line and usage

- setting help width and indentation is a messy part of the formatter

- there are unittests for long and long-long-longer option names to test these indentation issues.

As with some other help formatter issues, we are treading a fine line between making trivial patches, and substantive ones that make it cleaner and more robust.

**Comment by serhiy-storchaka** [comment]
Note that currently help produces more compact output: `-s, --long ARG    help`.

Closing this issue as supporting empty metavar looks like a bad idea.
