### ISSUE TITLE
IDLE - call tips show wrapper's argpsec instead of wrapped

### ISSUE THREAD

**Issue by df79943f-4aee-4531-a00d-c6b12816eb70** [python/cpython#73839]
BPO | [29653](https://bugs.python.org/issue29653)
--- | :---
Nosy | @terryjreedy, @mr-nfamous
Superseder | <li>bpo-19903: Idle: Use inspect.signature for calltips</li>
Files | <li>[calltips.py](https://bugs.python.org/file46669/calltips.py "Uploaded as text/plain at 2017-02-25.20:34:30 by @mr-nfamous")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-02-25.22:50:10.292>
created_at = <Date 2017-02-25.20:34:32.419>
labels = ['expert-IDLE', 'type-feature']
title = "IDLE - call tips show wrapper's argpsec instead of wrapped"
updated_at = <Date 2017-02-25.22:50:10.289>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-25.22:50:10.289>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-02-25.22:50:10.292>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-02-25.20:34:32.419>
creator = 'bup'
dependencies = []
files = ['46669']
hgrepos = []
issue_num = 29653
keywords = []
message_count = 2.0
messages = ['288580', '288584']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'bup']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '19903'
type = 'enhancement'
url = 'https://bugs.python.org/issue29653'
versions = ['Python 3.6']
```

</p></details>

**Comment by df79943f-4aee-4531-a00d-c6b12816eb70** [comment]
Many wrappers use the famous (*args, \*\*kwargs) argspec, which is less than helpful for a function that uses some positional arguments and maybe a few keyword only arguments, ie (x, y, z=10). Other IDEs have the capability of showing the wrapped functions argspec in a calltip, so why shouldn't IDLE?

**Comment by terryjreedy** [comment]
We usually prefer diffs rather than revised files, but I know not everyone can provide them.  Did you change anything other than add the following?
    elif hasattr(ob, '\_\_wrapped__') and callable(ob.\_\_wrapped__):
        fob = ob.\_\_wrapped__
 
I am all for accurate calltips.  However, your patch will not work for the stdlib wrapper functools.partial.  It does not add a \_\_wrapped__ attribute.  Instead it had args, func, and kwargs attributes.

I plan on switching calltips from using inspect.getfullargspec to inspect.signature (bpo-19903). The latter defaults to follow_wrapped=True, in which case, it should follow callable.\_\_wrapped__.  https://docs.python.org/3/library/inspect.html#inspect.signature.  It also is documented to work with partials and in my test, it indeed followed .func to get the original signature and remove the parameters set in the partial call.

So this request is a duplicate in that it will be fixed by the existing issue.
