### ISSUE TITLE
Use GCC __attribute__((alloc_size(x, y))) on PyMem_Malloc() functions

### ISSUE THREAD

**Issue by vstinner** [python/cpython#73860]
BPO | [29674](https://bugs.python.org/issue29674)
--- | :---
Nosy | @vstinner, @svelankar
PRs | <li>python/cpython#669</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-19.23:22:38.096>
created_at = <Date 2017-02-28.08:54:10.589>
labels = ['3.7']
title = 'Use GCC __attribute__((alloc_size(x, y))) on PyMem_Malloc() functions'
updated_at = <Date 2018-09-19.23:22:38.095>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-19.23:22:38.095>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-19.23:22:38.096>
closer = 'vstinner'
components = []
creation = <Date 2017-02-28.08:54:10.589>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 29674
keywords = []
message_count = 5.0
messages = ['288699', '289308', '289310', '289612', '289616']
nosy_count = 2.0
nosy_names = ['vstinner', 'svelankar']
pr_nums = ['669']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29674'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
GCC allows to get "size" parameters of functions allocating memory to emit better warning. For example, GCC 7 will detect implicit cast from signed to unsigned integer and emit a warning.

https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html

Example of Python functions that can benefit of this attribute:

* PyMem_RawMalloc(), PyMem_RawCalloc(), PyMem_RawRealloc()
* PyMem_Malloc(), PyMem_Calloc(), PyMem_Realloc()
* PyObject_Malloc(), PyObject_Calloc(), PyObject_Realloc()

**Comment by 6394ae25-ec38-4bb4-ae9f-c7fd49375561** [comment]
So once these functions are decorated with this attribute, what kind of testing/validation you have in mind, please let me know.

**Comment by vstinner** [comment]
> So once these functions are decorated with this attribute, what kind of testing/validation you have in mind, please let me know.

Call PyMem_Malloc(Py_ssize_t) for example: it must emit a warning on GCC 7, since casting negative values to size_t overflows.

Not sure how to test the attribute on GCC 6. Maybe some GCC related static analyzers are able to detect memory leaks like:

```c
void test(void)
{
   void *ptr = PyMem_Malloc(16);
   /* don't free ptr */
}
```

**Comment by 6394ae25-ec38-4bb4-ae9f-c7fd49375561** [comment]
Ok. 

As a side note, while compiling python source using gcc 7 [gcc (GCC) 7.0.1 20170314 (experimental)], few places in the code with case fallthrough (must be intentional) triggered this warning - -Wimplicit-fallthrough=.

We can either disable this warning altogether (downside being unintended fallthroughs will go unnoticed) OR  pass some flag [https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/] to -Wimplicit-fallthrough=. so that it does a regex match on the comments defined [something like  /* fall through code \*/] in that specific part of the code and suppresses the warning. The downside to this is that these comments might have to be inserted wherever they are missing and new code introduced in the future with intentional fallthroughs need to write those comments. Please let me know.

**Comment by vstinner** [comment]
Yeah, as for each GCC release, I expect new warnings. I noticed the
implicit fall through in GCC 7. I know that it's used on purpose in CPython.
