### ISSUE TITLE
Python 3 Module doc still sounds like __init__.py is required

### ISSUE THREAD

**Issue by 8e3a9b64-4338-4df6-8ead-c4463e72931d** [python/cpython#73902]
BPO | [29716](https://bugs.python.org/issue29716)
--- | :---
Nosy | @brettcannon, @methane, @marco-buttu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-06.18:44:11.006>
created_at = <Date 2017-03-03.21:26:26.801>
labels = ['invalid', 'type-feature', '3.7', 'docs']
title = 'Python 3 Module doc still sounds like __init__.py is required'
updated_at = <Date 2017-03-06.18:44:11.004>
user = 'https://bugs.python.org/JamesO'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-06.18:44:11.004>
actor = 'brett.cannon'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-03-06.18:44:11.006>
closer = 'brett.cannon'
components = ['Documentation']
creation = <Date 2017-03-03.21:26:26.801>
creator = 'James O'
dependencies = []
files = []
hgrepos = []
issue_num = 29716
keywords = []
message_count = 5.0
messages = ['288932', '288951', '288953', '288960', '289123']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'methane', 'docs@python', 'marco.buttu', 'James O']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29716'
versions = ['Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 8e3a9b64-4338-4df6-8ead-c4463e72931d** [comment]
PEP-420 says "Allowing implicit namespace packages means that the requirement to provide an \_\_init__.py file can be dropped completely..."
(as described here:  http://stackoverflow.com/questions/37139786/is-init-py-not-required-for-packages-in-python-3)

The documentation for modules \<https://docs.python.org/3/tutorial/modules.html\> doesn't seem to reflect this change. 

My "enhancement suggestion" is that a sentence (and perhaps an example) be added that explicitly states or shows an import from another directory.

(P.S. This is my first Python bug submission, so if it's silly, let me know. Thanks!)

**Comment by methane** [comment]
namespace package is very advanced topic.
I don't think tutorial should mention it.
Putting \_\_init__.py always in normal package is highly recommended.
Otherwise, many tools can't distinguish normal directory and python package.

2017/03/04 午前6:26 "James O" \<report@bugs.python.org\>:

New submission from James O:

PEP-420 says "Allowing implicit namespace packages means that the
requirement to provide an \_\_init__.py file can be dropped completely..."
(as described here:  http://stackoverflow.com/questions/37139786/is-init-py-
not-required-for-packages-in-python-3)

The documentation for modules \<https://docs.python.org/3/
tutorial/modules.html\> doesn't seem to reflect this change.

My "enhancement suggestion" is that a sentence (and perhaps an example) be
added that explicitly states or shows an import from another directory.

(P.S. This is my first Python bug submission, so if it's silly, let me
know. Thanks!)

\----------
assignee: docs@python
components: Documentation
messages: 288932
nosy: James O, docs@python
priority: normal
severity: normal
status: open
title: Python 3 Module doc still sounds like \_\_init__.py is required
type: enhancement
versions: Python 3.3, Python 3.4, Python 3.5, Python 3.6, Python 3.7

_______________________________________
Python tracker \<report@bugs.python.org\>
\<http://bugs.python.org/issue29716\>
_______________________________________
_______________________________________________
docs mailing list
docs@python.org
https://mail.python.org/mailman/listinfo/docs

**Comment by 8e3a9b64-4338-4df6-8ead-c4463e72931d** [comment]
Ah, I didn't realize some tools depended on it. Should I set the status to closed? (like I said, I'm new to this)

**Comment by methane** [comment]
I think so.
namespace package is topic for packaging ecosystem developers, like
setuptools and pip.
Normal python programmer shouldn't omit \_\_init__.py.
Python tutorial is for people who want to be normal python programmer.

2017/03/04 午後1:53 "James O" \<report@bugs.python.org\>:

>
> James O added the comment:
>
> Ah, I didn't realize some tools depended on it. Should I set the status to
> closed? (like I said, I'm new to this)
>
> \----------
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<http://bugs.python.org/issue29716\>
> _______________________________________
>

**Comment by brettcannon** [comment]
I've gone ahead and closed this. Thanks for taking the time to check in on this, James!
