### ISSUE TITLE
Enum._missing_ not called for __getitem__ failures

### ISSUE THREAD

**Issue by ethanfurman** [python/cpython#73938]
BPO | [29752](https://bugs.python.org/issue29752)
--- | :---
Nosy | @warsaw, @ethanfurman, @MojoVampire

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ethanfurman'
closed_at = <Date 2018-01-22.07:47:09.377>
created_at = <Date 2017-03-07.22:29:52.101>
labels = ['type-bug', '3.7']
title = 'Enum._missing_ not called for __getitem__ failures'
updated_at = <Date 2018-01-22.07:47:09.375>
user = 'https://github.com/ethanfurman'
```

bugs.python.org fields:
```python
activity = <Date 2018-01-22.07:47:09.375>
actor = 'ethan.furman'
assignee = 'ethan.furman'
closed = True
closed_date = <Date 2018-01-22.07:47:09.377>
closer = 'ethan.furman'
components = []
creation = <Date 2017-03-07.22:29:52.101>
creator = 'ethan.furman'
dependencies = []
files = []
hgrepos = []
issue_num = 29752
keywords = []
message_count = 6.0
messages = ['289191', '289241', '289306', '289331', '310253', '310401']
nosy_count = 4.0
nosy_names = ['barry', 'eli.bendersky', 'ethan.furman', 'josh.r']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29752'
versions = ['Python 3.7']
```

</p></details>

**Comment by ethanfurman** [comment]
```py
class Label(Enum):

    RedApple = 1
    GreenApple = 2

    @classmethod
    def _missing_(cls, name):
        for member in cls:
            if member.name.lower() == name.lower():
                return member
```


Currently, \_missing_ is only called when using the functional API. In words:

```py
Label('redapple')  # works
Label.redapple     # does not
```

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
Could that perhaps be intentional? Attribute access seems like something where the developer would be explicitly naming a single, hard coded, canonical name for the type, while string construction seems like something where you're getting a string from "somewhere" (user input, which is always terrible) and you'd want to have a way to handle invalid input.

The documentation is so sparse as to be useless for determining intent:

\_missing_ – a lookup function used when a value is not found; may be overridden

I wouldn't view Label.redapple as an attempt to "find" anything, it's just simple attribute access.

**Comment by ethanfurman** [comment]
Thank you, Josh, that's a very good point.

One can be expected to have the correct spelling when using attribute access.

So the two accesses that make sense for a \_missing_ call would then be:

- by-value lookup (e.g. Label(1))

- by-name lookup (e.g. Label['redapple'])

Sound reasonable?

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
Yeah, that sounds fine.
