### ISSUE TITLE
test_ctypes test_pass_by_value fails on arm64 (aarch64) architecture

### ISSUE THREAD

**Issue by e19bb02b-4d86-4b52-b95f-8ba3ba41da14** [python/cpython#73990]
BPO | [29804](https://bugs.python.org/issue29804)
--- | :---
Nosy | @vsajip, @vstinner, @ned-deily, @yan12125, @stratakis, @irushchyshyn
PRs | <li>python/cpython#1559</li>
Files | <li>[Python3.6.1rc1_build_log.txt](https://bugs.python.org/file46724/Python3.6.1rc1_build_log.txt "Uploaded as text/plain at 2017-03-13.13:48:44 by @irushchyshyn")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-03-11.22:20:58.714>
created_at = <Date 2017-03-13.13:50:54.061>
labels = ['ctypes', '3.7', 'tests']
title = 'test_ctypes test_pass_by_value fails on arm64 (aarch64) architecture'
updated_at = <Date 2018-08-02.14:49:59.565>
user = 'https://github.com/irushchyshyn'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-02.14:49:59.565>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-03-11.22:20:58.714>
closer = 'ned.deily'
components = ['Tests', 'ctypes']
creation = <Date 2017-03-13.13:50:54.061>
creator = 'ishcherb'
dependencies = []
files = ['46724']
hgrepos = []
issue_num = 29804
keywords = []
message_count = 15.0
messages = ['289539', '289589', '289595', '289669', '289670', '289674', '290065', '312200', '312963', '312964', '312982', '313625', '322956', '322964', '322966']
nosy_count = 6.0
nosy_names = ['vinay.sajip', 'vstinner', 'ned.deily', 'yan12125', 'cstratak', 'ishcherb']
pr_nums = ['1559']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29804'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by e19bb02b-4d86-4b52-b95f-8ba3ba41da14** [comment]
I am trying to build Python 3.6.1rc1 on Fedora, and have the following test failing on arm64 (aarch64) architecture:

\======================================================================
FAIL: test_pass_by_value (ctypes.test.test_structures.StructureTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/builddir/build/BUILD/Python-3.6.1rc1/Lib/ctypes/test/test_structures.py", line 413, in test_pass_by_value
    self.assertEqual(s.first, 0xdeadbeef)
AssertionError: 195948557 != 3735928559
```

----------------------------------------------------------------------

The build log is attached.
The test was added in this commit [1] as a fix for bpo-29565.

Any idea what this can be related to?


[1] https://github.com/python/cpython/commit/3cc5817cfaf5663645f4ee447eaed603d2ad290a

**Comment by e19bb02b-4d86-4b52-b95f-8ba3ba41da14** [comment]
Hi Vinay, I have added you to the nosy list as you are the author of the fix for bpo-29565, and would like to ask you for insights or ideas on why the test would fail only on one architecture (arm64)?

**Comment by vsajip** [comment]
The test checks that a structure passed by value is indeed passed by value - something that is architecture-dependent, as calling conventions differ across architectures.

If the test fails, this indicates that the structure isn't being passed by value - a pointer to the structure is probably passed, which is pass-by-reference rather than pass-by-value. This indicates that a change to ctypes or libffi is needed to fix this. See the changes made in [Modules/_ctypes/libffi_msvc/ffi.c](https://github.com/python/cpython/blob/main/Modules/_ctypes/libffi_msvc/ffi.c) for bpo-29565 - probably, analogous changes need to be made to the corresponding code for arm64.

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
Since this newly added assertion [0] fails for aarch64 shouldn't this be considered a regression?

And taking into account the timeframe, a release blocker for 3.6.1?

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
[0] https://github.com/python/cpython/commit/a86339b83fbd0932e0529a3c91935e997a234582#diff-39e8978a35ab16f78e60027c61b810f7R413

**Comment by vsajip** [comment]
I don't think it's a regression. It's catching an error that was there, but wasn't tested for before.

If it should be a release blocker - that should not be for any reversion of the change to the test, but for implementing the pass-by-value functionality correctly.

**Comment by ned-deily** [comment]
Technically speaking, we do not officially support arm64 in our release process as we have no arm64 buildbots nor an identified core developer for the platform; see PEP-11 for the policy details.  So there is no place to test a fix if there was one identified.  That said, it would be good to fix the problem if someone is willing to provide a fix and test it or determine that the issue here is a libffi problem.  It would be even better if we could make arm64 an officially supported platform as outlined.
