### ISSUE TITLE
The traceback compounding of RecursionError fails to work with __get__

### ISSUE THREAD

**Issue by df79943f-4aee-4531-a00d-c6b12816eb70** [python/cpython#74041]
BPO | [29855](https://bugs.python.org/issue29855)
--- | :---
Nosy | @ncoghlan, @Vgr255, @DimitrisJim, @mr-nfamous

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-20.06:41:40.484>
created_at = <Date 2017-03-19.23:37:32.143>
labels = ['interpreter-core', 'invalid', 'type-bug', '3.7']
title = 'The traceback compounding of RecursionError fails to work with __get__'
updated_at = <Date 2017-03-20.06:41:40.482>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-20.06:41:40.482>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-20.06:41:40.484>
closer = 'ncoghlan'
components = ['Interpreter Core']
creation = <Date 2017-03-19.23:37:32.143>
creator = 'bup'
dependencies = []
files = []
hgrepos = []
issue_num = 29855
keywords = []
message_count = 3.0
messages = ['289867', '289871', '289875']
nosy_count = 4.0
nosy_names = ['ncoghlan', 'abarry', 'Jim Fasarakis-Hilliard', 'bup']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29855'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by df79943f-4aee-4531-a00d-c6b12816eb70** [comment]
```py
class Property:
    def __init__(self, getter):
        self.getter = getter

    def __get__(self, instance, cls):
        return self.getter(cls if instance is None else instance)

class MyClass:
    @Property
    def something(cls):
        return cls.something
```


Calling MyClass.something will show all 990+ RecursionError message.

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
I'm pretty sure this is by design; the change introduced in [1] tried to keep things simple by only trimming the output when the lines were identical. More complicated scenarios are trickier to implement.

It should be interesting to see if the core-devs believe a change like this is warranted, though.

[1]: https://bugs.python.org/issue26823

**Comment by ncoghlan** [comment]
Indeed, the traceback abbreviation doesn't try to detect recursive loops, only exactly duplicated lines.

The problem is that the more state management we do in the traceback printing, the higher the chance there is of getting an error while attempt to display the previous errors.

Keeping the immediately preceding entry and doing an exact comparison is straightforward, but pattern matching on up-to-N entries is something we'll leave to external traceback pretty printers.
