### ISSUE TITLE
copy breaks staticmethod

### ISSUE THREAD

**Issue by 249e986b-cd73-4bad-a57a-1540abaf6db9** [python/cpython#74088]
BPO | [29902](https://bugs.python.org/issue29902)
--- | :---
Nosy | @warsaw, @avassalotti, @benjaminp, @serhiy-storchaka
PRs | <li>python/cpython#925</li><li>python/cpython#2823</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/benjaminp'
closed_at = <Date 2017-08-02.08:34:21.017>
created_at = <Date 2017-03-25.13:16:44.729>
labels = ['interpreter-core', 'type-bug', 'library']
title = 'copy breaks staticmethod'
updated_at = <Date 2017-08-02.08:34:21.016>
user = 'https://bugs.python.org/dangyogi'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-02.08:34:21.016>
actor = 'serhiy.storchaka'
assignee = 'benjamin.peterson'
closed = True
closed_date = <Date 2017-08-02.08:34:21.017>
closer = 'serhiy.storchaka'
components = ['Interpreter Core', 'Library (Lib)']
creation = <Date 2017-03-25.13:16:44.729>
creator = 'dangyogi'
dependencies = []
files = []
hgrepos = []
issue_num = 29902
keywords = []
message_count = 12.0
messages = ['290481', '290484', '290905', '291739', '291748', '291752', '298892', '298896', '299607', '299642', '299648', '299649']
nosy_count = 5.0
nosy_names = ['barry', 'alexandre.vassalotti', 'dangyogi', 'benjamin.peterson', 'serhiy.storchaka']
pr_nums = ['925', '2823']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29902'
versions = ['Python 2.7']
```

</p></details>

**Comment by 249e986b-cd73-4bad-a57a-1540abaf6db9** [comment]
Doing a copy on a staticmethod breaks it:

```pycon
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from copy import copy
>>> def foo(): pass
... 
>>> class bar: pass
... 
>>> bar.x = staticmethod(foo)
>>> bar.x.__name__
'foo'
>>> bar.y = copy(staticmethod(foo))
>>> bar.y.__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: uninitialized staticmethod object
```

**Comment by serhiy-storchaka** [comment]
Copying and pickling of staticmethod objects are not supported. Starting from 3.6 this raises an exception (see bpo-22995).

```pycon
>>> bar.y = copy(staticmethod(foo))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/py/cpython3.6/Lib/copy.py", line 96, in copy
    rv = reductor(4)
TypeError: can't pickle staticmethod objects
```

**Comment by serhiy-storchaka** [comment]
This issue was fixed by bpo-22995 in 3.6. But for some reasons the general solution was not applied to 3.5 and 2.7. Proposed patch makes staticmethod, classmethod and property descriptors explicitly non-pickleable (as was made explicitly non-pickleable file-like object) in 3.5. Only tests will be foreported to 3.6 and 3.7.

**Comment by serhiy-storchaka** [comment]
What are your thoughts Barry? staticmethod, classmethod and property objects are incorrectly pickled in 2.7 and 3.5 (they are not pickleable in 3.6+). Making them not pickleable in 2.7 and 3.5 can help to catch programming errors.

But this can break the code that "just works" (actually works incorrectly) if it pickles or deepcopies complex objects containing staticmethod, classmethod or property objects, but never use it. Similar situation happened in bpo-22995 with Cython objects.

Maybe emitting a warning rather than an exception would be safer? But deprecation warnings are ignored by default.

**Comment by warsaw** [comment]
I'd be very hesitant to add anything to 2.7 that changes (even broken) behavior here.  It might make more sense to backport the more strict checks to 3.5.  OTOH, we can save people from all programming errors, and if warnings are basically ignored (plus, adding warnings \*can* break things), then perhaps we should only document the limitations.

There's already some description of copy()'s limitations, so either add another warning there, or in the static method objects description in section 3.2

**Comment by serhiy-storchaka** [comment]
If add just warnings we are free to add any warnings in 2.7 in Py3k compatible mode (option -3).

**Comment by serhiy-storchaka** [comment]
I have decided to not merge these changes in 3.5. They help to avoid programmatic errors, but have a non-zero chance of breaking programs that work by accidence. Since this is the last non-secure bugfix we will not have a chance to rollback these changes.

An alternative to these changes is testing a program with Python 3.6.

**Comment by serhiy-storchaka** [comment]
But I think it is worth to add a check and emit a deprecation warning in Py3k mode in 2.7. 2.7 has longer support term than 3.5. And since it is less compatible with 3.6, it is harder to use 3.6 for testing 2.7 programs.

**Comment by serhiy-storchaka** [comment]
Thank you Benjamin for your review!

But I have a design question. Is DeprecationWarning a correct warning type? DeprecationWarning is used when some feature less or more works in the current version, but will be removed in future releases. But pickling memoryview and staticmethod don't work and never worked correctly. A warning here is a sign that the code can not work as expected. Wouldn't RuntimeWarning be more appropriate warning type?

**Comment by benjaminp** [comment]
I don't think it's too important, though most py3k warnings have been
DeprecationWarning. You can think of it as deprecating a misfeature.

**Comment by serhiy-storchaka** [comment]
New changeset 3dd1ccbb0950b2b83713a495958c35d60b453fa9 by Serhiy Storchaka in branch '2.7':
bpo-29902: Emit a Py3k deprecation warning when pickling or copying (bpo-2823)
https://github.com/python/cpython/commit/3dd1ccbb0950b2b83713a495958c35d60b453fa9

**Comment by serhiy-storchaka** [comment]
Thank you Benjamin.
