### ISSUE TITLE
ipadress compare_networks does not work according to documentation

### ISSUE THREAD

**Issue by 3a37abd6-e522-4049-958c-60aefc9639d0** [python/cpython#74099]
BPO | [29913](https://bugs.python.org/issue29913)
--- | :---
Nosy | @ncoghlan, @zhangyangyu, @s-sanjay
PRs | <li>python/cpython#842</li><li>python/cpython#865</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-30.07:45:06.621>
created_at = <Date 2017-03-27.07:23:35.945>
labels = ['type-bug', '3.7', 'docs']
title = 'ipadress compare_networks does not work according to documentation'
updated_at = <Date 2017-03-30.07:45:06.620>
user = 'https://github.com/s-sanjay'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-30.07:45:06.620>
actor = 'xiang.zhang'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-03-30.07:45:06.621>
closer = 'xiang.zhang'
components = ['Documentation']
creation = <Date 2017-03-27.07:23:35.945>
creator = 'Sanjay'
dependencies = []
files = []
hgrepos = []
issue_num = 29913
keywords = []
message_count = 9.0
messages = ['290566', '290569', '290571', '290572', '290573', '290577', '290579', '290680', '290830']
nosy_count = 5.0
nosy_names = ['ncoghlan', 'pmoody', 'docs@python', 'xiang.zhang', 'Sanjay']
pr_nums = ['842', '865']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29913'
versions = ['Python 3.7']
```

</p></details>

**Comment by 3a37abd6-e522-4049-958c-60aefc9639d0** [comment]
according to the docs compare_networks only checks the network address but the implementation is also taking the mask length into account. It returns '0' only if both the network address and the mask are equal but this can be done with just equality check ( ip1 == ip2 )

```pycon
Example:
>>> ip1=ipaddress.ip_network("1.1.1.0/24")
>>> ip2=ipaddress.ip_network("1.1.1.0/25")
>>> ip1.compare_networks(ip2)
-1
>>> ip1 == ip2
False
>>> ip1.network_address
IPv4Address('1.1.1.0')
>>> ip2.network_address
IPv4Address('1.1.1.0')
>>> 
```


shouldn't we ignore the mask length ? I have tried it here:

https://github.com/s-sanjay/cpython/commit/942073c1ebd29891e047b5e784750c2b6f74494a

**Comment by zhangyangyu** [comment]
In my mind this is the wanted behaviour. `compare_networks` means compare one network to another and a network should count its mask in. Your example would look rather weird if 1.1.1.0/24 == 1.1.1.0/25. Maybe make the doc from 'network addresses' to 'network bits' is easier to understand.

**Comment by 3a37abd6-e522-4049-958c-60aefc9639d0** [comment]
yes but compare_networks is not used to implement equality check. \_\_eq__ correctly returns False when we do 1.1.1.0/24 == 1.1.1.0/25.
If compare_networks works exactly like \_\_eq__ then it seems a bit redundant.

**Comment by ncoghlan** [comment]
Looking into it, this appears to be a holdover from the original ipaddr design where rather than being modelled as separate objects, host interfaces are modelled as denormalised network objects (i.e. a host address with a netmask).

So the stdlib equivalent of the original ipaddr compare_networks() operation would be:

```pycon
    >>> ip_interface('192.0.2.1/31').network == ip_network('192.0.2.0/31')
True
```


As Sanjay noted, compare_networks() itself is fairly redundant given the stricter stdlib data model, since we don't allow the creation of denormalised network definitions in the first place:

```
>>> ip_network('192.0.2.1/31')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/ipaddress.py", line 74, in ip_network
    return IPv4Network(address, strict)
  File "/usr/lib64/python3.5/ipaddress.py", line 1536, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 192.0.2.1/31 has host bits set
```

**Comment by zhangyangyu** [comment]
I still hold my opinion that the current behaviour is correct. You are comparing two networks and you should count the mask in. 

And notice that `neta == netb` is not totally equal to `neta.compare_networks(netb)`. The former can only results True or False but the later could result -1, 0 and 1. For example:

```pycon
>>> IPv4Network('192.0.2.0/25') == IPv4Network('192.0.2.0/25')
True
>>> IPv4Network('192.0.2.0/25').compare_networks(IPv4Network('192.0.2.0/25'))
0
>>> 
```


They can't be used exchangably. `compare_networks` actually does the work of all <, >, ==.

**Comment by ncoghlan** [comment]
Right, I agree compare_networks() is behaving correctly according to its original design. However:

- it was designed for Python 2, where cmp() style idioms were still more common. Those idioms have largely been removed in Python 3 (no cmp() builtin, no \_\_cmp__ magic method, no cmp argument to list.sort() and sorted())

- it was designed for the ipaddr data model, where network equality comparisons are more like ipaddress.ip_interface comparisons than they ipaddress.ip_network comparisons

Since there isn't any real maintenance burden in keeping the code around, I'm flipping this to be purely a documentation issue and suggesting that we:

- mark the method as deprecated in the docs, but \*not* in the code (using the method form is just kind of pointless, not actively harmful)

- update the docs to say that it uses the same ordering and comparison algorithm as "\<", "==", and "\>" (the current confusion stems from the fact that the algorithms were different in ipaddr, but in the stdlib that other algorithm is the one used by interface objects, not network objects)

**Comment by zhangyangyu** [comment]
+1 for the doc change.

**Comment by 3a37abd6-e522-4049-958c-60aefc9639d0** [comment]
ok I will update the doc

**Comment by zhangyangyu** [comment]
New changeset 16f852345bcdec1bbb15e5363fad6b33bf960912 by Xiang Zhang (s-sanjay) in branch 'master':
bpo-29913: deprecate compare_networks() in documentation (GH-865)
https://github.com/python/cpython/commit/16f852345bcdec1bbb15e5363fad6b33bf960912
