### ISSUE TITLE
Document that no characters are allowed to proceed \ in explicit line joining

### ISSUE THREAD

**Issue by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [python/cpython#74154]
BPO | [29968](https://bugs.python.org/issue29968)
--- | :---
Nosy | @bitdancer, @vadmium, @DimitrisJim

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-04.17:44:01.304>
created_at = <Date 2017-04-03.12:49:25.098>
labels = ['docs']
title = 'Document that no characters are allowed to proceed \\ in explicit line joining'
updated_at = <Date 2017-04-04.17:44:01.303>
user = 'https://github.com/DimitrisJim'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-04.17:44:01.303>
actor = 'Jim Fasarakis-Hilliard'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-04-04.17:44:01.304>
closer = 'Jim Fasarakis-Hilliard'
components = ['Documentation']
creation = <Date 2017-04-03.12:49:25.098>
creator = 'Jim Fasarakis-Hilliard'
dependencies = []
files = []
hgrepos = []
issue_num = 29968
keywords = []
message_count = 8.0
messages = ['291067', '291068', '291095', '291096', '291097', '291108', '291123', '291128']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'docs@python', 'martin.panter', 'Jim Fasarakis-Hilliard']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29968'
versions = []
```

</p></details>

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
After looking through the code, the tokenizer only allows a new line character to proceed `\` in explicit line joining [1].

The Devguide section on it [2] actually states many of the limitations of using `\` but not directly that nothing is allowed after it (it does have a remark on comments). 

Would it be a good idea to amend it to state that no characters are allowed after `\`?

[1]: https://github.com/python/cpython/blob/734125938d4653459593ebd28a0aec086efb1f27/Parser/tokenizer.c#L1847
[2]: https://docs.python.org/3/reference/lexical_analysis.html#explicit-line-joining

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Alternatively, stripping all white-space that proceed `\` could be considered if it seems like a good idea.

**Comment by bitdancer** [comment]
I think you meant "the language reference" rather than "the [devguide](https://devguide.python.org)".  The sentence about the comment is redundant with the preceding line that says that the thing that results in a join is a physical line that ends with a backslash ("that is not part of..."), which is a definitive statement that no characters may follow it.

So, I don't see any doc bug here, unless we want to delete that redundant statement about the comment because it is confusing.  But I doubt we want to do that, as some people will think that a comment is "the same as there being nothing" (despite the statement about "physical line") which it is not.

**Comment by bitdancer** [comment]
I also have no idea what your comment about stripping white space is in reference to ;)

**Comment by vadmium** [comment]
I think he means make something like the following legal, where dots (.) indicate space characters:

a.=.\\.
....b

At the moment it is a SyntaxError:

```pycon
>>> a = \ 
  File "<stdin>", line 1
    a = \ 
         ^
SyntaxError: unexpected character after line continuation character
```


I don’t think it is worthwhile changing that.

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Ah, yes, the Ref. Manual, not the [devguide](https://devguide.python.org), silly mistake.

It definitely isn't a documentation bug (the documentation doesn't state something wrong) as much as I think it might be a slight omission. I really wasn't aware of how strict the tokenizer is with any characters after `\`.

**Comment by bitdancer** [comment]
I don't see any omission, myself.  Keep in mind that the language reference is as much or more of a specification as it is a reference, so we tend to try to use the minimum language that precisely describes the expected behavior. Which is why I suggested that if anything the sentence about trailing comments should be dropped :)  

And I would vote -1 on allowing trailing whitespace.  (More than -1, actually :)  If that's what you meant: you said "proceed \\", which doesn't sound like \*trailing* whitespace.

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Gotcha, thanks for the input, David. I'll leave it to you to decide if the sentence on the trailing comments warrants removal.
