### ISSUE TITLE
site.USER_SITE is None for Windows embeddable Python 3.6

### ISSUE THREAD

**Issue by fee97611-e62e-4d55-a266-e3efd07200f4** [python/cpython#74180]
BPO | [29994](https://bugs.python.org/issue29994)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-11.22:38:10.146>
created_at = <Date 2017-04-05.10:36:22.669>
labels = ['type-bug', 'invalid', 'OS-windows']
title = 'site.USER_SITE is None for Windows embeddable Python 3.6'
updated_at = <Date 2017-04-12.17:22:52.666>
user = 'https://bugs.python.org/brechtm'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-12.17:22:52.666>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-11.22:38:10.146>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2017-04-05.10:36:22.669>
creator = 'brechtm'
dependencies = []
files = []
hgrepos = []
issue_num = 29994
keywords = []
message_count = 5.0
messages = ['291174', '291519', '291526', '291564', '291566']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'brechtm', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29994'
versions = ['Python 3.6']
```

</p></details>

**Comment by fee97611-e62e-4d55-a266-e3efd07200f4** [comment]
Previous versions of the embeddable Python:

```pycon
    Python 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)] on win32
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import site
    >>> site.USER_SITE
    'C:\\Users\\Brecht\\AppData\\Roaming\\Python\\Python35\\site-packages'
    >>>
```


Version 3.6.0 and 3.6.1, both win32 and amd64:

```pycon
    Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)] on win32
    >>> import site
    >>> site.USER_SITE
    >>>
```


 This causes problems when importing pip for example.

**Comment by zooba** [comment]
This is by design - the embeddable Python is meant to exclude anything relating to the current user by default.

If you're looking for a lightweight Python install that you can use for things like building or managing packages, you may be interested in the Nuget packages - see https://www.nuget.org/packages?q=publisher%3A%22Python+Software+Foundation%22

**Comment by fee97611-e62e-4d55-a266-e3efd07200f4** [comment]
I see. In that case I think pip should be able to handle the case when site.USER_SITE is None. I have created a ticket here: https://github.com/pypa/pip/issues/4437.

I am using the embeddable Python what's it intended for, to make a self-contained distribution of my application (using pynsist). I'm using pip to install optional resources (fonts).

**Comment by zooba** [comment]
Yes, fixing pip in this case is the right approach.

Since you're going to be including a copy of pip with your application, you can also just patch that yourself to get going while the pip team decides how to go from here. Or you could add a sitecustomize.py file (which will only be imported if you have "import site" in your .\_pth file) that sets site.USER_SITE to something so that pip does not crash.

**Comment by zooba** [comment]
Actually, I suspect you're not importing site on startup at all (which is great for performance), but that means that site.main() is not being run. I'll post more details on the pip bug.
