### ISSUE TITLE
Add __matmul__ to collections.Counter

### ISSUE THREAD

**Issue by 551ca523-30ee-4cb4-a031-faea59451be1** [python/cpython#74382]
BPO | [30196](https://bugs.python.org/issue30196)
--- | :---
Nosy | @rhettinger, @terryjreedy, @ilevkivskyi, @DimitrisJim

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-05-01.03:30:25.270>
created_at = <Date 2017-04-28.10:19:20.533>
labels = ['3.7', 'type-feature', 'library']
title = 'Add __matmul__ to collections.Counter'
updated_at = <Date 2017-05-01.03:30:25.269>
user = 'https://bugs.python.org/JchymBarvnek'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-01.03:30:25.269>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-05-01.03:30:25.270>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-04-28.10:19:20.533>
creator = 'J\xc3\xa1chym Barv\xc3\xadnek'
dependencies = []
files = []
hgrepos = []
issue_num = 30196
keywords = []
message_count = 3.0
messages = ['292522', '292547', '292564']
nosy_count = 5.0
nosy_names = ['rhettinger', 'terry.reedy', 'levkivskyi', 'J\xc3\xa1chym Barv\xc3\xadnek', 'Jim Fasarakis-Hilliard']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30196'
versions = ['Python 3.7']
```

</p></details>

**Comment by 551ca523-30ee-4cb4-a031-faea59451be1** [comment]
The class collections.Counter should semantically contain only numbers, so it makes sense to define dot product od Counters, something like this:

```py
def __matmul__(self, other):
  return sum(self[x] * other[x] for x in self.keys() | other.keys())
```


I find this useful ocassionaly.

**Comment by rhettinger** [comment]
Periodically, I've looked at possibly adding these kind of extensions. 

The argument in favor in that it is easy to do and is an obvious extension with plausible utility.  

The main arguments against is that it represents feature creep far removed from the original intended use cases (the tool is primary about counting and trys not to venture into elementwise arithmetic on sparse vectors.)   

It is tempting to add a new feature that might sometimes be useful, but we should also worry that usability and learnability are impaired if the class becomes less cohesive, less thematic, and less focused on unified design goals.

The other factor against adding the feature is that since the Counter is just a dict subclass, it is easy for users to just manipulate the data directly.  We're not really adding much that a person can't already easily do themselves.

**Comment by terryjreedy** [comment]
The '|' should be '&' to avoid useless summing of 0 products.

I think this should be rejected.  Python's number and collections classes provide basic operations from which users can build application-specific functions.  Or in the case of floats, we provide a separate module of specialized functions.  Or in the case of itertools, a section of recipes that build on the basic iterators in the module.

In this case, it makes little sense to me to provide an 'inner product' of Counters (bags, multisets).

```pycon
>>> a, b, c, d = 'a', 'b', 'c', 'd'
>>> c1 = C([a,a,a,b,b,c])
>>> c2 = C([a, c,c,c, d,d,d])
>>> sum(c1[x]*c2[x] for x in c1.keys() & c2.keys())
6
```


Even if the keys are counts and one thinks of the counters as sparse vectors, they are not really matrices.  Hence @ does not exactly fit.

If one does want sparse vectors implemented as dicts, they do not always have to be Counters.  A function would not require that.

```py
def sparse_inner_prod(v1, v2):
    return sum(v1[x]*v2[x] for x in v1.keys() & v2.keys())
```


This only requires that v1 and v2 both have keys and \_\_getitem__ methods.
