### ISSUE TITLE
Bdb: add docstrings

### ISSUE THREAD

**Issue by csabella** [python/cpython#74397]
BPO | [30211](https://bugs.python.org/issue30211)
--- | :---
Nosy | @terryjreedy, @csabella
PRs | <li>python/cpython#1350</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2017-04-29.19:54:20.829>
labels = ['type-feature', '3.7', 'docs']
title = 'Bdb: add docstrings'
updated_at = <Date 2017-05-17.00:43:10.820>
user = 'https://github.com/csabella'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-17.00:43:10.820>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2017-04-29.19:54:20.829>
creator = 'cheryl.sabella'
dependencies = []
files = []
hgrepos = []
issue_num = 30211
keywords = []
message_count = 8.0
messages = ['292598', '293743', '293744', '293752', '293763', '293782', '293813', '293831']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'docs@python', 'cheryl.sabella']
pr_nums = ['1350']
priority = 'normal'
resolution = None
stage = 'commit review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30211'
versions = ['Python 3.7']
```

</p></details>

**Comment by csabella** [comment]
Add docstrings to Bdb.  See bpo-19417.

**Comment by terryjreedy** [comment]
In the entry at https://docs.python.org/3/library/bdb.html#bdb.Bdb.canonic, 
", stripped of surrounding angle brackets"
is wrong, and should be replaced by
".  'Filenames' with angle brackets, such as "\<stdin\>", generated in interactive mode, are returned unchanged"

```pycon
>>> 1/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
```


(IDLE generates "\<PyShell#n\>", when n is statement number, starting with 0.)

This and any other doc errors we find should be corrected in this issue, but perhaps in a separate PR that can be backported separately.

**Comment by terryjreedy** [comment]
As I just posted to core-mentorship, my attempt to push to the PR failed.  Did you leave the 'allow pushes' box checked when you created the PR?

**Comment by terryjreedy** [comment]
The bdb class or \_\_init__ docstring needs to document the data members with a short explanation.  Some of the args need better explanation.  Some of this I may fill in \*after* reviewing the proposed tests, when I understand the code better.  Reviewing pdb and IDLE's Idb and Debugger (my real interest here) will help.

is_skipped_module is public, by its name, but is not in the doc.

break_here: " If the breakpoint is a temporary one, this method deletes it."  maybe (if flag from effective is True)

The first comment and the code that follows do not seem to match.  IDLE does not set breakpoints for functions, so I cannot test the behavior here with its debugger.

set_break doc says filename should be canonic, but function then calls canonic.  So canonic not needed.  If it is, result is self.fncache[canonic_filename] = self.fncache[canonic_filename].  But I will leave suggestion as is for now.

get_stack: return 'size of the higher part': If higher part does not stop as self.botframe (which might be None?), the size is of the lower part.  I need to review frame and tb objects pin down this docstring.

I just pushed my changes.  Please review for typos and anything you think is a new error.  Otherwise, I think this is about good enough to merge.

**Comment by csabella** [comment]
Thank you.  I had some questions that I put on the commit.

You're right about it saying it must be in canonic form and then it calls canonic.  I figured someone added the call later to prevent an error, but didn't change the warning, but I didn't know if I should change it.

I added a comment about get_stack on github.  I know I'm missing something here, but I had trouble documenting that because it didn't look like it was doing what the doc said.

I'm not at my regular computer this week, so I can't add any changes until Saturday.  I'll do the is_skipped_module doc then.

Thank you for the edits on the other docstrings.  They make a lot more sense now.  Although I still don't like the user_* ones.  I hadn't changed them from the original before, but it feels like they should say something else, like what's expected of them.  The test example within bdb.py helped me understand what can be done with them.

**Comment by terryjreedy** [comment]
I plan to merge when I can.  Possible future improvements for bdb.py.

1. Bdb attributes.
2. Say what user_xyz functions might do.  Anything better than 'Intervene in debugging process.'?
3. Clarify what get_stack does.

Improvement for bdb.rst (optional for this issue).
1. Add is_skipped_module
2. Fix overt errors we are sure of, noted above
* canonic: \<\> not stripped
* break_here: temps \*may* be deleted
* get_stack: length may or may not be what says.

**Comment by terryjreedy** [comment]
New changeset 0774e79b93cc494b3a957d538c7c112e289973c0 by terryjreedy (csabella) in branch 'master':
bpo-30211: bdb: add docstrings (bpo-1350)
https://github.com/python/cpython/commit/0774e79b93cc494b3a957d538c7c112e289973c0

**Comment by terryjreedy** [comment]
I still need to push a News Entry.

**Comment by slateny** [comment]
Taking a look at [bdb.py](https://github.com/python/cpython/blob/main/Lib/bdb.py), the methods have docstrings, and the `__init__` args are documented in the docstrings of the classes, so looks like this is resolved.

**Comment by terryjreedy** [comment]
Thank you. Whether I did or did not add a news entry 5 years ago is irrelevant now.
