### ISSUE TITLE
Remove unnecessary tuples, lists, sets, and dicts from Lib

### ISSUE THREAD

**Issue by d623c433-3e67-4a0a-abb9-feaa556f8894** [python/cpython#74482]
BPO | [30296](https://bugs.python.org/issue30296)
--- | :---
Nosy | @rhettinger, @terryjreedy, @stevendaprano, @serhiy-storchaka, @jdufresne, @miss-islington
PRs | <li>python/cpython#1489</li><li>python/cpython#2624</li><li>python/cpython#5908</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2018-02-26.16:25:24.822>
created_at = <Date 2017-05-07.13:08:04.300>
labels = ['3.7', 'library']
title = 'Remove unnecessary tuples, lists, sets, and dicts from Lib'
updated_at = <Date 2018-02-26.16:25:24.821>
user = 'https://github.com/jdufresne'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-26.16:25:24.821>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2018-02-26.16:25:24.822>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-05-07.13:08:04.300>
creator = 'jdufresne'
dependencies = []
files = []
hgrepos = []
issue_num = 30296
keywords = ['patch']
message_count = 16.0
messages = ['293190', '293193', '293195', '293201', '293571', '293588', '293684', '293923', '293926', '293935', '297906', '297911', '297912', '309022', '312929', '312936']
nosy_count = 6.0
nosy_names = ['rhettinger', 'terry.reedy', 'steven.daprano', 'serhiy.storchaka', 'jdufresne', 'miss-islington']
pr_nums = ['1489', '2624', '5908']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30296'
versions = ['Python 3.7']
```

</p></details>

**Comment by d623c433-3e67-4a0a-abb9-feaa556f8894** [comment]
Lib has some patterns that could be easily discovered and cleaned up. Doing so will reduce the number of unnecessary temporary lists in memory and unnecessary function calls. It will also take advantage of Python's own rich features in a way that better dog foods the language. For example:

* Replace list(\<generator expression\>) with list comprehension
* Replace dict(\<generator expression\>) with dict comprehension
* Replace set(\<generator expression\>) with set comprehension
* Replace builtin func(\<list comprehension\>) with func(\<generator expression\>) when supported (e.g. any(), all(), tuple(), min(), & max())

**Comment by stevendaprano** [comment]
Is this unnecessary code churn?

That's not a rhetorical question. Fixing code that isn't broken is not always a good idea.

``func(<list comprehension>)`` is not always identical to ``func(<generator expression>)``, there are situations where there is a significant performance difference between the two. E.g. str.join() is significantly faster when passed a list than when passed a generator expression. According to my tests:

    ''.join(['abc' for x in range(1000000)])

is about 40% faster than

    ''.join('abc' for x in range(1000000))

**Comment by serhiy-storchaka** [comment]
* Some functions that accept an arbitrary iterable first convert it to temporary list and iterate that list. In these cases there is no significant difference in memory usage between list comprehension and generator, but the variant with list comprehension is slightly faster.

* foo(bar(x) for x in a) can be written also as foo(map(bar, a)). Both expressions are idiomatic, different users have different preferences, the variant with map can be faster for larger loops. The variant with map can even be faster than comprehensions.

* Proposed patch changes some files which should be kept compatible with old Python versions. Old Python versions can not support set and dict comprehensions.

* In general we avoid making changes to many files that doesn't have obvious positive effect. Most changes doesn't have measurable effect, they are just style changes. But different users have different preferences and existing code is not obviously bad.

Assigned to Raymond because it usually opposed to such kind of changes but made very similar changes in bpo-22823.

**Comment by rhettinger** [comment]
Jon, we usually try to avoid sweeping changes across the library and instead preference to focus on one module at a time (Guido calls this "holistic refactoring").  There is a risk of introducing bugs and of destabiliizing code that has sat untouched but working for a long time.

Also, as Serhiy and Steven have pointed out, there are sometimes subtle reasons to prevent the existing code.  For example, I find the original to be clearer in this example:

 - return list(set(item.name for item in self.list))		 +        
 \+ return list({item.name for item in self.list})

and the original to be both clearer and faster in this example:

 - return list(map(_convert, node.elts))
 \+ return [_convert(v) for v in node.elts]

In some cases, using "dict(...)" or "set(...)" is clearer about the intension or more readable because it is parallel to the surrounding code (such as the parallelism of successive line in ast.py).

In some cases such as \_pydecimal we have a aversion to changing code that aspires to be backwards compatible across many versions.

That said, there are a few places where it might be worthwhile for making a change.  Converting to set literals is almost always a win:

 -    interesting = set(("include", "lib", "libpath", "path"))		 
 \+    interesting = {"include", "lib", "libpath", "path"}

As Serhiy noted, in some places using map() would be an improvement, so we should look at doing a few of those (where there is a win in term of speed, space, and readability):

 - version_info = tuple([int(x) for x in version.split(".")])
 \+ version_info = tuple(map(int, version.split(".")))

Overall, I think most of these shouldn't be done, but I will mark a few where some change might be considered an improvement.  Steven or Serhiy are both welcome to veto any one of those.  Likewise, if the original author of the code is still active, they have a veto as well.  The status quo usually wins until we're refactoring a single module and make improvements while thinking about that module.

You picked a difficult first patch because you picked a topic that we usually avoid (wholesale sweeps through the standard library) and an area where deciding "what is best" involves subtleties with respect to clarity, parallelism with surrounding code, speed, clear intention, back compatibility, and how the original author thinks about the code.

**Comment by terryjreedy** [comment]
As I said on review, I want idlelib changes either not made or in a separate patch that can be backported as is.  Partial backport/cherry-picks are a major nuisance.  I don't know if anything else should be treated similarly.

**Comment by rhettinger** [comment]
Yes, please do keep any proposed idlelib changes separate.  Also, I don't any of these to be backported (it is stylistic and not about bugs).

**Comment by rhettinger** [comment]
Serhiy, the latest version of this PR looks okay to me.  Do you care to veto any of the remaining suggested changes?

**Comment by rhettinger** [comment]
New changeset 3972628de3d569c88451a2a176a1c94d8822b8a6 by Raymond Hettinger (Jon Dufresne) in branch 'master':
bpo-30296 Remove unnecessary tuples, lists, sets, and dicts (bpo-1489)
https://github.com/python/cpython/commit/3972628de3d569c88451a2a176a1c94d8822b8a6

**Comment by serhiy-storchaka** [comment]
Oh, the PR was merged while I made a review.

tuple([i for i in a]) is 2 times faster than tuple(i for i in a). Since there is no significant difference in readability I would keep the variant with a list comprehension if it is initial.

**Comment by terryjreedy** [comment]
I made a note of the idlelib.multicall changes for when I review the module to modernize and test.

**Comment by serhiy-storchaka** [comment]
Since some changes looks worse than the old code to me (see my comments on GitHub), I have created [PR 2624](https://github.com/python/cpython/pull/2624) which reverts changes with which I disagree or applies alternate changes.

**Comment by rhettinger** [comment]
Why do you think that adding an unnecessary list comprehension around tuple() call makes them better?

Also, I don't think you should be able to override and revert all the judgments I made when carefully reviewing all the OP's PR.  You are NOT the sole arbiter of what goes into Python.

**Comment by serhiy-storchaka** [comment]
> Why do you think that adding an unnecessary list comprehension around tuple() call makes them better?

I just restore the original code because I don't think the changes make it better.

> Also, I don't think you should be able to override and revert all the judgments I made when carefully reviewing all the OP's PR.  You are NOT the sole arbiter of what goes into Python.

You asked my review and vetoing, and assigned this issue to me. I started reviewing, but when I finished it I found that the PR already is merged.
