### ISSUE TITLE
Pull Requests need more detail

### ISSUE THREAD

**Issue by 3e343a24-9ff1-42e1-854f-3942dc156566** [python/cpython#74521]
BPO | [30336](https://bugs.python.org/issue30336)
--- | :---
Nosy | @brettcannon, @vstinner, @monkeyboy2805
PRs | <li>python/cpython#1539</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-11.17:51:13.457>
created_at = <Date 2017-05-10.18:02:47.090>
labels = ['type-feature']
title = 'Pull Requests need more detail'
updated_at = <Date 2017-05-11.17:51:13.456>
user = 'https://github.com/Monkeyboy2805'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-11.17:51:13.456>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-11.17:51:13.457>
closer = 'brett.cannon'
components = []
creation = <Date 2017-05-10.18:02:47.090>
creator = 'Jensen Taylor'
dependencies = []
files = []
hgrepos = []
issue_num = 30336
keywords = []
message_count = 4.0
messages = ['293447', '293449', '293459', '293513']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'vstinner', 'Jensen Taylor']
pr_nums = ['1539']
priority = 'low'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30336'
versions = []
```

</p></details>

**Comment by 3e343a24-9ff1-42e1-854f-3942dc156566** [comment]
Made a PR for this

**Comment by brettcannon** [comment]
I'm not sure if this is going to be useful enough to force all contributors to deal with. Justification for a change should be on bugs.python.org and that's mentioned in the CONTRIBUTING.md guidelines. As for testing, the Travis/AppVeyor failures should communicate that. And for specifying the issue number, there's a status check for that to help communicate it.

I'll let other core devs comment, but while I appreciate what Jensen is trying to help with, I don't think the template helps enough to justify forcing every contributor to have to deal with it.

You can also bring this up on the core-workflow mailing list, Jensen, if you want to discuss it there.

**Comment by vstinner** [comment]
> What is this pull request for?

I didn't notice so many PR without useful commit message (PR description). Not sure that it's useful.

> Include version updates if necessary.

I don't understand this part.

> Make sure you have signed the CLA agreement before continuing

We have a bot for that and the bot explains how to sign it, no?


> ### Reason to modify

I never saw such template in any other project. I'm not sure that we must require an exact format for new PR.


> ### Tests and reviews
> I have tested the code and it works.

While I run Linux and have Windows and FreeBSD VM, sometimes I'm lazy and rely on the CI. I consider that it's waste to burn CI CPUs sometimes :-) For example, it's not that easy to test a change specific to Windows on Python 2.7, but AppVeyor now runs tests for you!

--

@Jensen: I feel that you have useful hints for new contributors, but I suggest you to enhance the [devguide](https://devguide.python.org) instead of using a template.

**Comment by brettcannon** [comment]
OK, since Victor has verified my thinking wasn't totally off-target, I'm going to close this.

Thanks for the idea and taking the time for the PR, Jensen. If you do want to file issues or PRs against the [devguide](https://devguide.python.org), the repo is at https://github.com/python/devguide.
