### ISSUE TITLE
file opened for updating cannot write after read

### ISSUE THREAD

**Issue by jkloth** [python/cpython#74645]
BPO | [30460](https://bugs.python.org/issue30460)
--- | :---
Nosy | @pfmoore, @tjguk, @jkloth, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-02-25.17:32:06.355>
created_at = <Date 2017-05-24.19:07:32.720>
labels = ['type-bug', 'expert-IO', 'OS-windows']
title = 'file opened for updating cannot write after read'
updated_at = <Date 2021-02-25.17:32:06.355>
user = 'https://github.com/jkloth'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-25.17:32:06.355>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2021-02-25.17:32:06.355>
closer = 'eryksun'
components = ['Windows', 'IO']
creation = <Date 2017-05-24.19:07:32.720>
creator = 'jkloth'
dependencies = []
files = []
hgrepos = []
issue_num = 30460
keywords = []
message_count = 3.0
messages = ['294379', '294414', '294509']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'jkloth', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30460'
versions = ['Python 2.7']
```

</p></details>

**Comment by jkloth** [comment]
Attempting to append to an existing file fails with no error set:

```pycon
>>> import os, tempfile
>>> fd, fn = tempfile.mkstemp()
>>> os.write(fd, 'some text')
9
>>> os.close(fd)
>>> with open(fn, 'r+') as f:
...     f.read()
...     f.write('more text')
...     
'some text'
Traceback (most recent call last):
  File "<interactive input>", line 3, in <module>
IOError: [Errno 0] Error
```


(error 0 is defined as NO_ERROR)

**Comment by eryksun** [comment]
It might be simplest to close this as 3rd party since it's similar to bpo-29817. A workaround is to call f.seek(0, 1) to reset the stream state when switching between reading and writing. 

That said, a switch to writing at EOF should be supported. The problem is that Python 2's file_read function in fileobject.c executes the following code in this case:

```c
        if (bytesread < buffersize && !interrupted) {
            clearerr(f->f_fp);
            break;
        }
```


clearerr() resets the EOF flag on the stream, so the Windows CRT has no way to know that it's allowed to reset the buffer from read-mode to write-mode in the subsequent write. Finally, Python raises a weird 'success' exception because the CRT writes fewer than the number of requested bytes without setting errno. AFAIK, this scenario only occurs on Windows. glibc on Linux appears to be more robust in this case.

A simple way to demonstrate this without involving a debugger is to add a second read() call before the write(). The 2nd read() takes a different path in file_read(), which doesn't clear the stream's EOF flag. 

```py
    import os, tempfile
    fd, fn = tempfile.mkstemp()
    os.write(fd, 'some text')
    os.close(fd)
    f = open(fn, 'r+')
```


```pycon
    >>> f.read()
    'some text'
    >>> f.read()
    ''
    >>> f.write('more text')
    >>> f.close()

    >>> open(fn).read()
    'some textmore text'
```

**Comment by jkloth** [comment]
It seems to me that it is a quite simple fix:

```diff
--- a/Objects/fileobject.c
+++ b/Objects/fileobject.c
@@ -1110,7 +1110,7 @@ file_read(PyFileObject *f, PyObject *args)
-            clearerr(f->f_fp);
+            if (ferror(f->f_fp)) clearerr(f->f_fp);
```


which is exactly what the empty read case does above this.

This fixes my error, and produces no changes to the test suite.

I guess it could be wrapped in an #ifdef MS_WINDOWS, just it case, but that seems unnecessary as the previous code does not.
