### ISSUE TITLE
Add CmdLineTest to standard library

### ISSUE THREAD

**Issue by d7907440-6036-40cf-9696-a1d2549a514a** [python/cpython#74674]
BPO | [30489](https://bugs.python.org/issue30489)
--- | :---
Nosy | @terryjreedy

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-02.22:41:45.097>
created_at = <Date 2017-05-26.18:27:27.048>
labels = ['type-feature', '3.7']
title = 'Add CmdLineTest to standard library'
updated_at = <Date 2017-06-02.22:41:45.094>
user = 'https://bugs.python.org/SantiagoCastro'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-02.22:41:45.094>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-02.22:41:45.097>
closer = 'terry.reedy'
components = []
creation = <Date 2017-05-26.18:27:27.048>
creator = 'Santiago Castro'
dependencies = []
files = []
hgrepos = []
issue_num = 30489
keywords = []
message_count = 2.0
messages = ['294565', '295059']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'Santiago Castro']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30489'
versions = ['Python 3.7']
```

</p></details>

**Comment by d7907440-6036-40cf-9696-a1d2549a514a** [comment]
I see that you use some helpers to test command line utilities (https://hg.python.org/cpython/file/default/Lib/test/test_cmd_line_script.py) that would be useful to Python programmers. Please, consider to add them to the standard library (or somewhere) to reuse them.

**Comment by terryjreedy** [comment]
Santiago, an idea like this (one that requests a reversal of previous decisions) should be discussed first on the python-ideas list.  Such a discussion would need to result in a specific proposal of what to extract from test_cmd_line_script.py and where to put it.  test_cmd_line_script.py itself cannot be moved.  If you get a positive response there, you can re-open this or open a new issue.

The test utilities in test/ are already 'in' the stdlib, in that one can  import and use them.  However, doing so is at one's own risk of API change.  They are declared private and kept in test/ so that we can freely change them as needed for their primary purpose -- testing cpython.
