### ISSUE TITLE
Tutorial section 2.1 has *nix example at 3.7, but Windows at 3.6

### ISSUE THREAD

**Issue by csabella** [python/cpython#74754]
BPO | [30569](https://bugs.python.org/issue30569)
--- | :---
Nosy | @terryjreedy, @zooba, @csabella, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-13.09:52:44.782>
created_at = <Date 2017-06-04.20:52:33.370>
labels = ['3.8', 'type-feature', '3.7', 'docs']
title = 'Tutorial section 2.1 has *nix example at 3.7, but Windows at 3.6'
updated_at = <Date 2022-01-13.09:52:44.782>
user = 'https://github.com/csabella'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-13.09:52:44.782>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = True
closed_date = <Date 2022-01-13.09:52:44.782>
closer = 'iritkatriel'
components = ['Documentation']
creation = <Date 2017-06-04.20:52:33.370>
creator = 'cheryl.sabella'
dependencies = []
files = []
hgrepos = []
issue_num = 30569
keywords = []
message_count = 4.0
messages = ['295142', '295577', '311608', '409783']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'docs@python', 'steve.dower', 'cheryl.sabella', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30569'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by csabella** [comment]
https://docs.python.org/3.7/tutorial/interpreter.html

The first lines for the location/command have been updated for 3.7, but next paragraph for Windows has not been updated.

**Comment by terryjreedy** [comment]
There is a lot more wrong with the Windows part:

 "On Windows machines, the Python installation is usually placed in C:\\Python36," is no longer true.  All-users install is, by default, in Program Files.  Current-user install is, by default, buried somewhere forgettable in the hidden /users/USER/appdata dir.

" you can type the following command into the command prompt in a DOS box:"  It has been a long time since Command Prompt was widely called a 'DOS box'.

set path=%path%

The is not permanent, at least for non-admin user.  One can add the install dir, whatever it is, to path during installation.  Or one can use 'py -3.6'
