### ISSUE TITLE
[doc] mention that os.mkdir() raises FileNotFound if path does not exist

### ISSUE THREAD

**Issue by 9227a725-9431-4123-b168-66f8369da563** [python/cpython#74862]
BPO | [30677](https://bugs.python.org/issue30677)
--- | :---
Nosy | @bitdancer, @miss-islington, @iritkatriel, @slateny
PRs | <li>python/cpython#31548</li><li>python/cpython#31877</li><li>python/cpython#31878</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-03-14.20:53:04.659>
created_at = <Date 2017-06-15.14:08:58.623>
labels = ['easy', '3.9', '3.10', '3.11', 'type-feature', 'docs']
title = '[doc] mention that os.mkdir() raises FileNotFound if path does not exist'
updated_at = <Date 2022-03-14.20:53:04.659>
user = 'https://bugs.python.org/ebianchi'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-14.20:53:04.659>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = True
closed_date = <Date 2022-03-14.20:53:04.659>
closer = 'iritkatriel'
components = ['Documentation']
creation = <Date 2017-06-15.14:08:58.623>
creator = 'ebianchi'
dependencies = []
files = []
hgrepos = []
issue_num = 30677
keywords = ['patch', 'easy']
message_count = 5.0
messages = ['296097', '296107', '415179', '415186', '415187']
nosy_count = 6.0
nosy_names = ['r.david.murray', 'docs@python', 'ebianchi', 'miss-islington', 'iritkatriel', 'slateny']
pr_nums = ['31548', '31877', '31878']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30677'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by 9227a725-9431-4123-b168-66f8369da563** [comment]
Currently, documentation for os.mkdir() (see https://docs.python.org/3.6/library/os.html#os.mkdir ) reports only FileExistsError exception if directory exists. Please, add other exceptions (e.g. FileNotFoundError if directory is created in a non existent path) or report OSError as superclass of exceptions returned from this method

**Comment by bitdancer** [comment]
We don't generally document all exceptions that a method can raise, only those that are relevant to its specific API.  In this case, documenting the exception answers the question, "what happens if the directory already exists?"  This question is relevant to the API since the other reasonable possibility is that it would act as if the mkdir had succeeded.  As for documenting OSError, I'm sure there are ways to get os.mkdir to raise an exception that is not an OSError.

However, there is an argument to be made for documenting FileNotFound: the other reasonable thing the function could do in that case would be to create all intermediate path parts, but it does not do that (you use os.makedirs for that).  Since os.makedirs is documented right after os.mkdir, I'm not sure it is worth adding, but one can make the argument :)
