### ISSUE TITLE
len() and iter() of ChainMap don't work with unhashable keys

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74874]
BPO | [30689](https://bugs.python.org/issue30689)
--- | :---
Nosy | @rhettinger, @bitdancer, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-06-18.04:10:55.957>
created_at = <Date 2017-06-17.12:31:43.700>
labels = ['3.7', 'type-feature', 'library']
title = "len() and iter() of ChainMap don't work with unhashable keys"
updated_at = <Date 2018-11-28.16:00:26.106>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-28.16:00:26.106>
actor = 'ebw'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-06-18.04:10:55.957>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-06-17.12:31:43.700>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30689
keywords = []
message_count = 4.0
messages = ['296236', '296257', '296386', '330606']
nosy_count = 4.0
nosy_names = ['rhettinger', 'r.david.murray', 'serhiy.storchaka', 'ebw']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30689'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
As documented ChainMap supports not just dicts, but mappings. A mapping can be implemented not only as a hash table, and mapping keys can be not hashable. But ChainMap.\_\_len__ and ChainMap.\_\_iter__ work only with hashable keys.

This may be considered just as a documentation issue. But I think it would be nice to add the support of unhashable keys in 3.7.

**Comment by rhettinger** [comment]
No thank you.  It is perfectly reasonable to use set operations to make the implementation simple, fast, reliable, and suitable for most use cases.  Marking this as a rejected feature request.

As for documentation, I don't see any need to accommodate a pedantic reading of "mapping" in the general sense versus collections.Mapping in the formal sense.  Additional text would likely create more confusion than it solves and would likely get in the way of normal users who are just trying to learn how to use ChainMap.

If you truly feel that users need to know about every place that the  adjective "mapping" carries with it a dependency on hashability, then consider a FAQ entry or blog post on the subject.  Otherwise, we going have to replace term "mapping" with the more awkward "dict-like object".

Serhiy, while I admire your devotion to studying all the code in the standard library, it really isn't helpful to have you challenge and second guess every single design decision.  While you may have a ton of spare time to generate enormous numbers of PRs, feature requests, and bug reports, it is eating-up \*all* of my development time.  It is a constant distraction from real work than needs to be done.   In particular, most of the issues seem to be "invented problems" that aren't based on any actual user need or reported problem.  Further, it risks excessive code churn, feature creep, risk of introducing new problems/incompatibilities, and destabilizes published code.  It may be fun to rewrite everything you look at, but it isn't a good practice.

**Comment by bitdancer** [comment]
IMO, it would actually be surprising for ChainMap to support unhashable keys.  In Python, as Raymond indicates, "mapping" is pretty much synonymous with 'dict-like', and it would be where that was \*not* true that we might add extra documentation.
