### ISSUE TITLE
tarfile add uses random order

### ISSUE THREAD

**Issue by 05ed1d68-9f72-4552-af38-41e9d578a41d** [python/cpython#74878]
BPO | [30693](https://bugs.python.org/issue30693)
--- | :---
Nosy | @rhettinger, @gustaebel, @vstinner, @tiran, @ned-deily, @bitdancer, @serhiy-storchaka, @bmwiedemann
PRs | <li>python/cpython#2263</li><li>python/cpython#5557</li><li>python/cpython#5567</li><li>python/cpython#31713</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-02-06.18:38:13.647>
created_at = <Date 2017-06-18.02:03:30.834>
labels = ['3.7', 'type-bug', 'library']
title = 'tarfile add uses random order'
updated_at = <Date 2022-03-06.22:48:55.393>
user = 'https://github.com/bmwiedemann'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-06.22:48:55.393>
actor = 'python-dev'
assignee = 'none'
closed = True
closed_date = <Date 2018-02-06.18:38:13.647>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-06-18.02:03:30.834>
creator = 'bmwiedemann'
dependencies = []
files = []
hgrepos = []
issue_num = 30693
keywords = ['patch']
message_count = 23.0
messages = ['296251', '296280', '296308', '310164', '310166', '310167', '310169', '310170', '310171', '310173', '310205', '310337', '310342', '311318', '311320', '311321', '311324', '311325', '311387', '311605', '311685', '311736', '311738']
nosy_count = 9.0
nosy_names = ['rhettinger', 'lars.gustaebel', 'vstinner', 'christian.heimes', 'ned.deily', 'r.david.murray', 'python-dev', 'serhiy.storchaka', 'bmwiedemann']
pr_nums = ['2263', '5557', '5567', '31713']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30693'
versions = ['Python 3.7']
```

</p></details>

**Comment by 05ed1d68-9f72-4552-af38-41e9d578a41d** [comment]
Filesystems do not give any guarantees about ordering of files returned in directory listings, thus tarfile.add adds files in random order, when using os.listdir in recursion.

See also https://reproducible-builds.org/docs/stable-inputs/ on that topic.

**Comment by serhiy-storchaka** [comment]
The patch for similar issue with the glob module was rejected recently since it is easy to sort the result of glob.glob() (see bpo-30461). This issue looks similar, but there are differences. On one side, the command line tar utility doesn't have the option for sorting file names and seems don't sort them by default (I didn't checked). It is possible to use external sorting with the tarfile module as with the tar utility (generate the list of all files and directories, sort it, and pass every item to TarFile.add with the option recursive=False). But on other side, this is not so easy as for glob.glob(). And the overhead of the sorting is expected to be smaller than for glob.glob(). This may be considered as additional arguments for approving the patch.

If this approach will be approved, it should be applied also to the ZIP archives.

FYI the order of archived files can affect the compression ratio of the compressed tar archive. For example the 7-Zip archiver sorts files by extensions, this increases the chance that files of the same type (text, multimedia, spreadsheet, executables, etc) are grouped together and use the common dictionary for global compression. This isn't directly related to this issue, just a material for possible future enhancement.

**Comment by 05ed1d68-9f72-4552-af38-41e9d578a41d** [comment]
note: recent GNU tar versions (1.28?) added an option --sort=name

and the overhead of sorting (e.g. I measured 4ms for 10000 files) is negligible compared to the other processing done on the files here.
