### ISSUE TITLE
EmailMessage Object Creation

### ISSUE THREAD

**Issue by 44497821-d4b0-4cd4-a41a-c26dcccb626f** [python/cpython#74891]
BPO | [30706](https://bugs.python.org/issue30706)
--- | :---
Nosy | @warsaw, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-26.23:38:54.637>
created_at = <Date 2017-06-19.21:19:46.760>
labels = ['type-bug', 'invalid', 'expert-email']
title = 'EmailMessage Object Creation'
updated_at = <Date 2017-06-26.23:38:54.635>
user = 'https://bugs.python.org/MichaelSalsone'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-26.23:38:54.635>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-26.23:38:54.637>
closer = 'r.david.murray'
components = ['email']
creation = <Date 2017-06-19.21:19:46.760>
creator = 'Michael Salsone'
dependencies = []
files = []
hgrepos = []
issue_num = 30706
keywords = []
message_count = 3.0
messages = ['296378', '296389', '296974']
nosy_count = 3.0
nosy_names = ['barry', 'r.david.murray', 'Michael Salsone']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30706'
versions = ['Python 3.6']
```

</p></details>

**Comment by 44497821-d4b0-4cd4-a41a-c26dcccb626f** [comment]
I am looking to use the get_body() method from email.message.EmailMessage, but I am unable to create an object of this type. I am attempting to create an object of this from message_from_string (as well as some of the other email.parser methods). But it won't allow me to change the class to email.message.EmailMessage. I've read through the source for some this code, but I don't see where you thread the needle here, is it even possible?

Example:
from email.message import EmailMessage
email.message_from_string(self.original_message, \_class=EmailMessage)

**Comment by bitdancer** [comment]
This isn't the place to get help on Python coding, but since this is a relatively new API I'll give you a pointer, and then you can tell me where the docs need improvement :)

If you do message_from_string(yourstring, policy=email.policy.default), you should get back an EmailMessage object.

That said, your example does return an EmailMessage for me, if I put a string in place of your self.original_message, which must be something from your program.  However, that won't \*work* very well, because the policy is set to Compat32, and Compat32 and EmailMessage aren't designed to work together.  A lot of things will work fine, but you'll get some weird errors.  However, I don't think that that is worth a documentation note, since it is a logical consequence of using \_class=EmailMessage without specifying a policy.

**Comment by bitdancer** [comment]
Given that there hasn't been any response that would help us improve the docs on this, I'm going to close the issue.  I hope you've figured out how to do what you want to do!
