### ISSUE TITLE
logging must check exc_info correctly

### ISSUE THREAD

**Issue by edecc627-9a02-4253-9acf-03a7fe08c1c6** [python/cpython#74952]
BPO | [30767](https://bugs.python.org/issue30767)
--- | :---
Nosy | @rhettinger, @vsajip, @serhiy-storchaka, @tb3088
PRs | <li>python/cpython#3792</li><li>python/cpython#3972</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-12.07:57:15.925>
created_at = <Date 2017-06-26.13:23:05.077>
labels = ['invalid', '3.7', 'library']
title = 'logging must check exc_info correctly'
updated_at = <Date 2017-10-13.14:20:06.161>
user = 'https://bugs.python.org/krivushinme'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-13.14:20:06.161>
actor = 'vinay.sajip'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-12.07:57:15.925>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-06-26.13:23:05.077>
creator = 'krivushinme'
dependencies = []
files = []
hgrepos = []
issue_num = 30767
keywords = ['patch']
message_count = 11.0
messages = ['296892', '304208', '304209', '304217', '304233', '304235', '304238', '304265', '304321', '304340', '304341']
nosy_count = 5.0
nosy_names = ['rhettinger', 'vinay.sajip', 'serhiy.storchaka', 'krivushinme', 'mp5023']
pr_nums = ['3792', '3972']
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30767'
versions = ['Python 3.7']
```

</p></details>

**Comment by edecc627-9a02-4253-9acf-03a7fe08c1c6** [comment]
Logging checking \`if exc_info:\` and this maybe incorrect, due exception instance can have \_\_bool__ method and thus can be false. If this is a case, then error that is return false from \_\_bool__ will cause logging to swallow traceback. We need to check exc_info correctly. Will do PR myself.

**Comment by serhiy-storchaka** [comment]
[PR 3792](https://github.com/python/cpython/pull/3792) breaks existing tests, and it seems to me, that it solves different issue, than reported here.

**Comment by vsajip** [comment]
This is not an issue that needs fixing; the current behaviour is by design. The documentation states about exc_info:

"There are two keyword arguments in kwargs which are inspected: exc_info which, if it does not evaluate as false, causes exception information to be added to the logging message. If an exception tuple (in the format returned by sys.exc_info()) is provided, it is used; otherwise, sys.exc_info() is called to get the exception information."

So, an individual exception instance returning false will not affect the truthiness of an exc_info tuple (if provided). I propose to close this issue as "not a bug" and reject the PR because (a) there's no issue to fix and (b) what Serhiy said.

If you still think there's an issue here, please post an example script which uses logging as documented and demonstrates a problem.

**Comment by rhettinger** [comment]
I agree that this should be closed.

**Comment by 960fec17-1053-4554-b311-7eb3d06afa39** [comment]
"exc_info which, if it does not evaluate as false", so we provide '1' or 'True'. The IF passes and immediately the formatter tries to dereference it blindly assuming it's Tuple and throws an Exception.

Either the Formatter needs to guard itself (best) or the caller needs to check the Type before allowing a call to the Formatter to go thru.

Should sys.exc_info() have already been called then the Tuple can have a valid frame reference or it's 3 None's. In this last case the Formatter is emitting a naked, zero context "NoneType None" line into the middle of the stack trace which is just annoying and pointless.

Again, I probably should have written the guard at the formatter to emit nothing when the field is None. It actually checks for the 2nd and 3rd fields, not the first.

**Comment by 960fec17-1053-4554-b311-7eb3d06afa39** [comment]
Additionally (probably should have separate PR) the \_checkLevel was full of holes.
First, it's allowing any Integer which if you're claiming to "check" things is rather silly. At least bounds-check it to GE to NOTSET and LE to CRITICAL (or MAX or something handy in that regard).

Second, why is a string representation of an Integer a problem that needs to force the caller to fix his code? Same with lowercase of a recognized value. "Be liberal in what you accept" would seem to apply here. If it can be trivially reduced to an integer or upcased() to get a match then just do it, and send the corrected value back to the caller.

**Comment by 960fec17-1053-4554-b311-7eb3d06afa39** [comment]
And the reason to stomp on the "Level " is because by not doing so the message that is a single field (regex/awk) has been converted non-deterministically into two. This is very bad behavior. If emitting the string/int as-is looks wrong then "Level(value)" or some other notation that keeps it a single field is how it should print.

**Comment by 960fec17-1053-4554-b311-7eb3d06afa39** [comment]
I believe this diff addresses the failure of formatException() to check it's parameter's datatype. I still maintain this should be re-opened since it's guaranteed to raise an exception when someone sets 'exc_info=TruthyValue' in kwargs. albeit with a more focused PR.


```diff
diff --git a/Lib/logging/__init__.py b/Lib/logging/__init__.py
index 00a022039d..5c61cd56a1 100644
--- a/Lib/logging/__init__.py
+++ b/Lib/logging/__init__.py
@@ -533,6 +533,8 @@ class Formatter(object):
         This default implementation just uses
         traceback.print_exception()
         """
+        if not isinstance(ei, tuple) or ei[0] is None:
+            return ""
         sio = io.StringIO()
         tb = ei[2]
         # See issues python/cpython#53673, python/cpython#43948. Commented out for now.
@@ -584,9 +586,7 @@ class Formatter(object):
         if self.usesTime():
             record.asctime = self.formatTime(record, self.datefmt)
         s = self.formatMessage(record)
-        if (isinstance(record.exc_info, tuple) and record.exc_info[0]):
-            # Intercept 'Boolean' - causes subscript error if passed to formatException,
-            # and empty Tuples which emit 'NoneType None' into message.
+        if record.exc_info:
             # Cache the traceback text to avoid converting it multiple times
             # (it's constant anyway)
             if not record.exc_text:
```

**Comment by vsajip** [comment]
Matthew Patton: you don't appear to have read the documentation correctly. The formatException() method's exc_info positional parameter is expected to be a normal exception tuple, not just any truthy value. This is clearly stated in the documentation for the method.

That is different to the logger.debug() etc. methods, where a truthy value can be provided for the exc_info keyword parameter.

**Comment by 960fec17-1053-4554-b311-7eb3d06afa39** [comment]
I've triggered it which is why I looked for the problem and offered the defensive patch. As API writers you can NEVER assume your parameters are what you think they should be and just blindly proceed.

**Comment by vsajip** [comment]
> I've triggered it which is why I looked for the problem and offered the defensive patch.

That's why I asked for a small example which used logging as documented and demonstrated a problem. You haven't done that.

> As API writers you can NEVER assume your parameters are what you think they should be and just blindly proceed.

I think you'll find that in Python usage in general and the Python stdlib in particular, exhaustive checking of input parameters is not the norm. I'm not saying that no error checking is ever done nor that it should never be done, but your "NEVER" doesn't seem to hold up, as the stdlib contains many counterexamples.
