### ISSUE TITLE
Parsing error on f-string-expressions containing strings with backslash

### ISSUE THREAD

**Issue by 071efd12-0c78-4b11-80ee-a5aa643b8dd1** [python/cpython#74976]
BPO | [30793](https://bugs.python.org/issue30793)
--- | :---
Nosy | @ericvsmith

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericvsmith'
closed_at = <Date 2019-05-06.12:29:10.751>
created_at = <Date 2017-06-28.18:58:13.898>
labels = ['type-bug', '3.7']
title = 'Parsing error on f-string-expressions containing strings with backslash'
updated_at = <Date 2019-05-06.12:29:10.749>
user = 'https://bugs.python.org/AnselmKiefner'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-06.12:29:10.749>
actor = 'eric.smith'
assignee = 'eric.smith'
closed = True
closed_date = <Date 2019-05-06.12:29:10.751>
closer = 'eric.smith'
components = []
creation = <Date 2017-06-28.18:58:13.898>
creator = 'Anselm Kiefner'
dependencies = []
files = []
hgrepos = []
issue_num = 30793
keywords = []
message_count = 7.0
messages = ['297206', '297240', '301541', '301579', '301603', '301604', '341493']
nosy_count = 2.0
nosy_names = ['eric.smith', 'Anselm Kiefner']
pr_nums = []
priority = 'normal'
resolution = 'postponed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30793'
versions = ['Python 3.7']
```

</p></details>

**Comment by 071efd12-0c78-4b11-80ee-a5aa643b8dd1** [comment]
Considering that

```py
x = 3
f"{'hello' if x == 3 else 'goodbye'} world"
```


is a simple, elegant and powerful piece of code that works just as expected by itself, I often find myself stumbling and wondering why
 
f"text {'\\n' if x == 3 else ''} text"

fails horribly just because of the \\ within the extra quoted string that must be worked around with ugly code like

nl = "\\n"
f"text {nl if x==3 else ''} text"

which really doesn't feel like python at all.

I am aware that the specification for f-strings says "no \\ in expressions", but please consider that in this case, the \\ is not really part of the expression but rather part of a string that isn't evaluated as part of the expression, which might just as well be referenced to by a variable.

**Comment by ericvsmith** [comment]
The reason that this was done was to give us flexibility in deciding how the backslashes should be interpreted in the future. I announced it on python-dev here: https://mail.python.org/pipermail/python-dev/2016-August/145979.html. That message contains a link to the python-ideas discussion that precipitated the change.

PEP-536 is one proposal to change how this is handled. I don't entirely agree with it, since I think allowing:
f'Magic wand: { bag['wand'] }'
would be confusing and make life more difficult for simple (regex based) parsers to skip over f-strings.

Notice that in Jupiter (https://github.com/jupyter/notebook/issues/2037#issuecomment-272466046) and in CodeMirror (https://github.com/codemirror/CodeMirror/commit/c45674b11e990fe37abc662b0c507d3bb1f635e7#diff-04f7f1f1bbbab888742c7e849187a79c) they were able to make simple changes to their parsers and "support" f-strings (for some value of "support": mostly not break in the presence of f-strings).

However, I'm not completely opposed to revisiting the issue. Your use case is certainly a compelling one.

**Comment by ericvsmith** [comment]
I'm thinking that instead of supporting backslashes in general inside expressions, I'll just special case strings.

So:
f"{'\\n' if foo else ''}"
would be okay, but not:
f"{a\\
}"

I think that would address the reason why \\ was disallowed, but I'm going to have to go back and review the discussions to make sure.

**Comment by 071efd12-0c78-4b11-80ee-a5aa643b8dd1** [comment]
Hey Eric, just a heads up.

In the latest jupyter notebook, this is valid code:

f"{eval('bool(0)\\
and True\\
')}"

which returns
'False'

I don't know how far you want to go, but if someone REALLY wants to use backspace in f-strings just for the sake of it - however ugly it looks like - they already can.

**Comment by ericvsmith** [comment]
That code is an error in Python 3.6:

```pycon
>>> f"{eval('bool(0)\
... and True\
... ')}"
  File "<stdin>", line 3
SyntaxError: f-string expression part cannot include a backslash
>>> 
```


I'm not sure it's a good idea that jupyter accepts code that's not valid in Python itself.

**Comment by 071efd12-0c78-4b11-80ee-a5aa643b8dd1** [comment]
Heh. I had a hunch it could be jupyter specific, but didn't test it. They had problems with f-strings before, it seems they over-fixed those ..
Maybe you want to check their implementation and see if it's any good for a general solution?
Otherwise I'd volunteer to submit a bug report for their code ;)
