### ISSUE TITLE
Import dotted name as alias breaks with concurrency

### ISSUE THREAD

**Issue by d49f56cf-eb86-4468-8f48-f594a04bf559** [python/cpython#74997]
BPO | [30814](https://bugs.python.org/issue30814)
--- | :---
Nosy | @brettcannon, @ncoghlan, @vstinner, @ned-deily, @ericsnowcurrently, @serhiy-storchaka, @RazerM, @rshk
PRs | <li>python/cpython#2580</li><li>python/cpython#2598</li><li>python/cpython#2645</li><li>python/cpython#2665</li><li>python/cpython#2851</li><li>python/cpython#2912</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-07-27.10:19:01.622>
created_at = <Date 2017-06-30.11:09:48.262>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'Import dotted name as alias breaks with concurrency'
updated_at = <Date 2017-07-27.10:19:01.621>
user = 'https://github.com/rshk'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-27.10:19:01.621>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-07-27.10:19:01.622>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-06-30.11:09:48.262>
creator = 'SamueleSanti'
dependencies = []
files = []
hgrepos = []
issue_num = 30814
keywords = ['3.6regression']
message_count = 18.0
messages = ['297380', '297475', '297482', '297679', '297698', '297704', '297803', '297806', '297966', '298050', '298065', '298951', '298958', '299005', '299018', '299019', '299296', '299302']
nosy_count = 8.0
nosy_names = ['brett.cannon', 'ncoghlan', 'vstinner', 'ned.deily', 'eric.snow', 'serhiy.storchaka', 'RazerM', 'SamueleSanti']
pr_nums = ['2580', '2598', '2645', '2665', '2851', '2912']
priority = 'high'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30814'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by d49f56cf-eb86-4468-8f48-f594a04bf559** [comment]
I noticed this weird behavior in Python 3.6:

Apparently ``import package.module as _alias`` fails in a threaded environment, sometimes raising an ``ImportError``, seemingly at random.

Everything seems to be working perfectly fine:

- On 3.5 and lower
- When *not* defining an alias, eg. ``import package.module``
- When using the ``from package import module as alias`` style


See this repo with code for reproducing the issue:

https://github.com/rshk/python36-import-alias-concurrency-bug


I tested this on the system Python 3.6.1 shipped with Archlinux (both inside and outside of a virtualenv), and in the official docker image for 3.6.

This all started here https://github.com/psycopg/psycopg2/issues/550 as others were experiencing this issue too.

**Comment by serhiy-storchaka** [comment]
See also bpo-23203.

This was fixed in master in bpo-30024. Maybe it is worth to backport that change to maintained versions?

**Comment by serhiy-storchaka** [comment]
On other side, bpo-23203 fixed just a symptom. The issue is reproduced in master when replace "import foobar.submodule as foo" with "import foobar.submodule; foo = foobar.submodule".

The regression may be related to bpo-22557. Either the optimization introduced a bug, or it exposed an existing bug by changing timings.

**Comment by brettcannon** [comment]
My guess is the import of package has completed but package.submodule hasn't (I don't know what state it would be in, but obviously before the module is assigned as an attribute on the package), a context switch occurs, and then the assignment fails due to package.submodule not being set on package yet.

I wonder if package.submodule is in sys.modules when the AttributeError is triggered? I don't remember when the assignment of a submodule to an attriute on a package occurs, but this suggests it's rather late and that's why this is failing. Maybe the assignment is outside of the per-module lock being released and that is what's causing this?

Hey, at least importing in a thread doesn't deadlock anymore like it used to. ;)

**Comment by ncoghlan** [comment]
Documenting explicitly what I believe the expected order of module lock acquisition would be in this case:

    Thread A acquires package.subpackage lock
    Thread B blocks on package.subpackage lock
    Thread A acquires package lock
    Thread A releases package lock
    Thread A releases package.subpackage lock
    Thread B acquires & immediately releases package.subpackage lock

Looking at https://hg.python.org/cpython/rev/64f195790a3a#l4.367 (the commit for bpo-22557), there's a potentially suspect change in the scope of a "\_PyImport_AcquireLock/_PyImport_ReleaseLock" pair inside PyImport_ImportModuleLevelObject

Specifically, I think we may now have a race condition at https://github.com/python/cpython/blob/master/Python/import.c#L1534, where two threads can \*both* end up trying to initialize the same module, since we're no longer holding the global import lock around that "mod = PyDict_GetItem(interp-\>modules, abs_name);" call and the associated state updates where the first thread indicates that it is already initializing that module so the second thread should just wait for it to finish doing so.

**Comment by serhiy-storchaka** [comment]
I have came to the same conclusion.

[PR 2580](https://github.com/python/cpython/pull/2580) adds a double check in \_bootstrap.\_find_and_load() (and also moves the locking into it). It also simplifies the C code by removing the fast path for the case sys.module[name] is None.

**Comment by serhiy-storchaka** [comment]
New changeset b4baacee1adc06edbe30ac7574d17a8cd168e2e0 by Serhiy Storchaka in branch 'master':
bpo-30814: Fixed a race condition when import a submodule from a package. (bpo-2580)
https://github.com/python/cpython/commit/b4baacee1adc06edbe30ac7574d17a8cd168e2e0

**Comment by serhiy-storchaka** [comment]
New changeset 03b0e8374b2ea93adf8fb6a48db2916f3b0388cc by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30814: Fixed a race condition when import a submodule from a package. (GH-2580). (bpo-2598)
https://github.com/python/cpython/commit/03b0e8374b2ea93adf8fb6a48db2916f3b0388cc

**Comment by brettcannon** [comment]
I just wanted to say thanks to everyone who helped to fix this bug. The locking situation in import is probably the trickiest part of it and has also been tweaked the most as of late and so solving these kinds of issues is tricky.

**Comment by vstinner** [comment]
test_concurrency() of test_import fails randomly on Windows: see bpo-30891.

**Comment by serhiy-storchaka** [comment]
It is worth to backport the test to older versions. Just to be sure that this is a 3.6 regression.

**Comment by ned-deily** [comment]
When running tests from installed location, test_import now fails on master and 3.6 with:

\======================================================================
ERROR: test_concurrency (test.test_import.ImportTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/nad/Projects/PyDev/active/dev/3x/root/uxd/lib/python3.7/test/test_import/__init__.py", line 408, in test_concurrency
    raise exc
  File "/Users/nad/Projects/PyDev/active/dev/3x/root/uxd/lib/python3.7/test/test_import/__init__.py", line 393, in run
    import package
ModuleNotFoundError: No module named 'package'
```

**Comment by vstinner** [comment]
> When running tests from installed location, test_import now fails on master and 3.6 with:

Which Git revisions are you testing? On master, do you have my latest commit e72b1359f81d1dd42bd8a5c5cc2b3928b74f8023 ?

**Comment by ned-deily** [comment]
> Which Git revisions are you testing? On master, do you have my latest commit e72b1359f81d1dd42bd8a5c5cc2b3928b74f8023 ?

Yes, this is with current top of trunk of both branches.  Perhaps I wasn't clear about "installed location".  The test does not fail if you run it directly from the build directory like with "make test".  It fails when you do a "make install" and then run the test using the newly installed Python.  Tests need to work both ways.

**Comment by vstinner** [comment]
Serhiy on [PR 2851](https://github.com/python/cpython/pull/2851):
> I forget to include directories with new test files in the list of the library directories. This caused that these test files were not installed.

Oh, too bad that Zach's "x86 Gentoo Installed with X 3.6" buildbot is offline.

**Comment by vstinner** [comment]
I also opened https://github.com/python/devguide/issues/241 : "Document how to add a new file or a new directory". It's not the first time that we make such mistake.

**Comment by serhiy-storchaka** [comment]
New changeset d5ed47dea25e04a3a144eddf99a4ac4a29242dbc by Serhiy Storchaka in branch 'master':
bpo-30814, bpo-30876: Add new import test files to projects. (bpo-2851)
https://github.com/python/cpython/commit/d5ed47dea25e04a3a144eddf99a4ac4a29242dbc

**Comment by serhiy-storchaka** [comment]
New changeset 95b16a9705d6b4d31c016c014e59744fc33d53ea by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30814, bpo-30876: Add new import test files to projects. (GH-2851). (bpo-2912)
https://github.com/python/cpython/commit/95b16a9705d6b4d31c016c014e59744fc33d53ea
