### ISSUE TITLE
A venv created and activated from within a virtualenv uses the outer virtualenv's site-packages rather than its own.

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#74994]
BPO | [30811](https://bugs.python.org/issue30811)
--- | :---
Nosy | @vsajip, @uranusjr, @Kentzo, @cosven

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-06-20.07:50:37.248>
created_at = <Date 2017-06-30.09:02:48.281>
labels = ['invalid', 'library']
title = "A venv created and activated from within a virtualenv uses the outer virtualenv's site-packages rather than its own."
updated_at = <Date 2018-08-15.19:04:01.236>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-15.19:04:01.236>
actor = 'uranusjr'
assignee = 'none'
closed = True
closed_date = <Date 2018-06-20.07:50:37.248>
closer = 'vinay.sajip'
components = ['Library (Lib)']
creation = <Date 2017-06-30.09:02:48.281>
creator = 'Antony.Lee'
dependencies = []
files = []
hgrepos = []
issue_num = 30811
keywords = []
message_count = 17.0
messages = ['297365', '297431', '306677', '306679', '306691', '306697', '306699', '306700', '306702', '306786', '310185', '310232', '313131', '313142', '320034', '323580', '323581']
nosy_count = 5.0
nosy_names = ['vinay.sajip', 'uranusjr', '45757', 'Kentzo', 'cosven']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30811'
versions = ['Python 3.6']
```

</p></details>

**Comment by 379dc349-3a10-424f-b9d2-a0104f092359** [comment]
Python 3.6.1, virtualenv 15.1.0 (Arch Linux, distro packages)

```
export PIP_CONFIG_FILE=/dev/null  # just to be sure
# python -mvirtualenv outer-env  # using /usr/bin/python(3)
python2 -mvirtualenv outer-env  # using /usr/bin/python(3)
source outer-env/bin/activate
python -mvenv inner-env  # using outer-env's python
source inner-env/bin/activate
python -minspect -d pip
```

The last step outputs
```
Target: pip
Origin: /tmp/inner-env/lib/python3.6/site-packages/pip/__init__.py
Cached: /tmp/inner-env/lib/python3.6/site-packages/pip/__pycache__/__init__.cpython-36.pyc
Loader: <_frozen_importlib_external.SourceFileLoader object at 0x7f27c019c710>
Submodule search path: ['/tmp/inner-env/lib/python3.6/site-packages/pip']
```
i.e., the outer environment's pip leaks into the inner environment; the inner environment does not have its own pip installed.  Trying to use that pip from the inner environment (from inner-env, `python -mpip install ...`) results in the package being installed in the outer environment rather than the inner one.

Now this may all seem very academic, but for example Travis uses virtualenvs as toplevel containers for their Python projects, so this bug makes it difficult to test, say, projects that set up venvs as part of their workflow.

**Comment by 379dc349-3a10-424f-b9d2-a0104f092359** [comment]
Sorry, that was a sloppy report.  This is a better repro:

```sh
$ export PIP_CONFIG_FILE=/dev/null  # just to be sure
python -mvirtualenv outer-env  # using /usr/bin/python(3)
source outer-env/bin/activate
python -mvenv inner-env  # using outer-env's python
source inner-env/bin/activate
python -minspect -d pip
```


Using base prefix '/usr'
New python executable in /tmp/outer-env/bin/python
Installing setuptools, pip, wheel...done.
Target: pip
Origin: /tmp/outer-env/lib/python3.6/site-packages/pip/__init__.py
Cached: /tmp/outer-env/lib/python3.6/site-packages/pip/__pycache__/__init__.cpython-36.pyc
Loader: \<_frozen_importlib_external.SourceFileLoader object at 0x7f92e00e03c8\>
Submodule search path: ['/tmp/outer-env/lib/python3.6/site-packages/pip']

**Comment by vsajip** [comment]
Can you explain why virtualenv and venv need to be mixed in this way, other than as an academic exercise? If you use -m venv for both inner and outer venvs, then it seems to work as expected.

I'm planning to close this as "not a bug" unless you can provide a reason why this use case needs to be supported.

**Comment by 379dc349-3a10-424f-b9d2-a0104f092359** [comment]
Travis uses virtualenvs as toplevel containers for running CI.  Some projects need (or would like to) set up venvs as part of their test suites.  On example is https://github.com/airspeed-velocity/asv, which profiles a project's speed across revisions; in order to do so it sets up an environment for each revision to run the test suite.  Currently, it can either set up a virtualenv or a conda env, but it would make sense for it to be able to set up a venv too (https://github.com/airspeed-velocity/asv/pull/526).  But the unability to nest a venv into a virtualenv makes this impossible to test on Travis.

**Comment by vsajip** [comment]
The problem for venv is that it's tied to the running interpreter, which is (in the case you mention) the one from the outer virtualenv. Unlike virtualenv, venv does not provide a mechanism to restart itself with a different Python interpreter.

I don't know how Conda works in detail, but virtualenv makes copies of parts of the stdlib; venv, on the other hand, doesn't, but keeps a reference to its original Python environment. That is, I think, the reason for the difference in behaviour.

Instead of just using 'python' to invoke the command which runs the "-mvenv", you could get the underlying Python and create the venv using that. For example, using this script "upvenv.py":

```py
#!/usr/bin/env python
def make_venv(venvpath):
    import os
    import subprocess
    import sysconfig

    python = os.path.join(sysconfig.get_config_var('BINDIR'), 'python3')
    cmd = [python, '-mvenv', venvpath]
    subprocess.run(cmd)

if __name__ == '__main__':
    import sys
    assert len(sys.argv) == 2
    try:
        rc = make_venv(sys.argv[1])
    except Exception as e:
        print('Failed: %s' % e)
        rc = 1
    sys.exit(rc)
```


I get:

vinay@ubuntu:/tmp$ cd /tmp
vinay@ubuntu:/tmp$ ve15 --version
15.1.0
vinay@ubuntu:/tmp$ ve15 -p python3 outer
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/outer/bin/python3
Also creating executable in /tmp/outer/bin/python
Installing setuptools, pip, wheel...done.
vinay@ubuntu:/tmp$ source outer/bin/activate
(outer)  vinay@ubuntu:/tmp$ python upvenv.py inner
(outer)  vinay@ubuntu:/tmp$ source inner/bin/activate
(inner)  vinay@ubuntu:/tmp$ python -minspect -d pip
Target: pip
Origin: /tmp/inner/lib/python3.5/site-packages/pip/__init__.py
Cached: /tmp/inner/lib/python3.5/site-packages/pip/__pycache__/__init__.cpython-35.pyc
Loader: \<_frozen_importlib_external.SourceFileLoader object at 0x7f6917e9e860\>
Submodule search path: ['/tmp/inner/lib/python3.5/site-packages/pip']

which seems OK.

This approach can't be transplanted into venv because it doesn't have the ability to restart with a different interpreter.

**Comment by 379dc349-3a10-424f-b9d2-a0104f092359** [comment]
> venv, on the other hand, doesn't, but keeps a reference to its original Python environment. That is, I think, the reason for the difference in behaviour.

But for example, using the system Python to create a venv (no nesting), packages installed system-wide (e.g. using a linux package manager) are not visible in the venv.  Or, as you note, nesting a venv into another works fine.  I don't understand why things would be different when nesting?

In any case thanks for the workaround.

**Comment by vsajip** [comment]
> I don't understand why things would be different when nesting?

Specifically because venv keeps "a pointer" to the Python environment it was created from. Usually that's a system Python. If a venv ("inner") is created from a virtualenv's interpreter, the pointer points back to that environment ("outer", in this case).

Also, virtualenv can re-invoke itself with a different interpreter easily - that's business as usual. However, the venv module is part of a specific Python stdlib and doesn't reinvoke itself with a different interpreter.

To find the exact mechanisms which lead to these behaviours, you would need to examine the code of virtualenv and the venv module and perhaps do some stepping through in a debugger!

**Comment by vsajip** [comment]
Is it OK if I close this? It's not really a bug, nor a case that's been designed for (a stdlib module supporting specific external packages is very unusual - pip support via ensurepip is perhaps the one exception I can think of). Given there's a way to create a venv from a virtualenv's Python, as posted above, I'm not sure what more I can do.

If, on the other hand, you look into the details and find something I've missed, I'll certainly look again.

**Comment by 379dc349-3a10-424f-b9d2-a0104f092359** [comment]
I guess it's reasonable, I'll see whether we can use the workaround you proposed.  (Could a fix on virtualenv's side help?)
Thanks for the explanations.

**Comment by vsajip** [comment]
> I guess it's reasonable, I'll see whether we can use the workaround you proposed.

OK, please post your findings here.

> (Could a fix on virtualenv's side help?)

Probably not, as it's not behaving unexpectedly. It might be worth asking the Travis devs for an enhancement to allow the choice of -m venv rather than virtualenv to create venvs for Python \>= 3.3, via an option in .travis.yml.
