### ISSUE TITLE
More details in reference 'Looping through a list in Python and modifying it'

### ISSUE THREAD

**Issue by 3bc837d7-28cf-42ba-8e61-629448b1940c** [python/cpython#75009]
BPO | [30826](https://bugs.python.org/issue30826)
--- | :---
Nosy | @rhettinger, @terryjreedy, @bitdancer
PRs | <li>python/cpython#15407</li><li>python/cpython#15410</li><li>python/cpython#22078</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2019-08-23.06:52:47.410>
created_at = <Date 2017-07-02.04:19:58.934>
labels = ['type-feature', '3.7', 'docs']
title = "More details in reference 'Looping through a list in Python and modifying it'"
updated_at = <Date 2020-09-03.13:45:13.363>
user = 'https://bugs.python.org/thedarklord'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-03.13:45:13.363>
actor = 'python-dev'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2019-08-23.06:52:47.410>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-07-02.04:19:58.934>
creator = 'the_darklord'
dependencies = []
files = []
hgrepos = []
issue_num = 30826
keywords = ['patch']
message_count = 10.0
messages = ['297507', '297509', '297514', '297556', '297925', '298214', '302874', '302884', '350253', '350255']
nosy_count = 6.0
nosy_names = ['rhettinger', 'terry.reedy', 'r.david.murray', 'docs@python', 'python-dev', 'the_darklord']
pr_nums = ['15407', '15410', '22078']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30826'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 3bc837d7-28cf-42ba-8e61-629448b1940c** [comment]
Documentation section: https://docs.python.org/3/reference/compound_stmts.html#for

The documentation does not explain at all why is there an infinite loop when not using a copy of the list.

It leaves the reader in a confused state.

Even there are questions concerning the same on stackoverlflow: https://stackoverflow.com/questions/44633798/loop-through-a-list-in-python-and-modify-it

**Comment by 3bc837d7-28cf-42ba-8e61-629448b1940c** [comment]
Wrong documentaion section linked.

Correct seciton: Section 4.2 on https://docs.python.org/3/tutorial/controlflow.html

The last line needs more explanation.

**Comment by rhettinger** [comment]
The example would be more clear if we replaced the opaque idiom "words[:]" with the more explicit alternative "words.copy()".

**Comment by 3bc837d7-28cf-42ba-8e61-629448b1940c** [comment]
And also a small explanation for why there would be an infinite loop without creating a copy.

**Comment by terryjreedy** [comment]
Are you looking for something like:

Let it = iter(words).  When next(it) returns 'defenestrate', insertion at the beginning moves the original 'defenestrate' over so that next(words) returns 'defenestrate' again.
?

**Comment by bitdancer** [comment]
I don't think that helps.  The issue here is that \*sequences* are iterated over by incrementing an integer index.  If you change the size of the list, you are potentially changing which value any given index points to.  Presumably the tutorial writer thought this was intuitive, and indeed after years of Python programming I find it so.  I can see how a beginner might not, though :)

What if we replaced:

  If you need to modify the sequence you are iterating over while inside the loop (for example to duplicate selected items), it is recommended that you first make a copy. Iterating over a sequence does not implicitly make a copy. The slice notation makes this especially convenient:

With:

  Sequence iteration is preformed by incrementing an implicit integer index until there are no more items in the sequence.  The sequence is \*not* copied before iteration, so if you modify the sequence during iteration the value that is affected by the next iteration of the loop may not be the one you are expecting.  You can avoid this problem by iterating over a copy of the sequence, and the slice notation makes this especially convenient:

However, this section has a deeper problem.  It is introducing the 'for' statement, but explains what the for statement does in terms of sequences, when in fact the for statement now operates on any iterable, not just sequences.  (Many Python programmers probably do not remember the time before the iteration protocol was added to the language :)

Fixing that problem not only requires rewriting the section, but also figuring out the best place to introduce the concept of the iteration protocol (which \*might* be in this section, but it's been so long since I've looked over the tutorial that I can't say).

**Comment by rhettinger** [comment]
After looking at this again, I think the entire example should be removed.  We really don't want to encourage people to code like this (it would never make it through a code review).  The example itself is silly (not fully, just weird and lacking real-world motiviation).  The s.insert(0,x) code is an anti-pattern.  And in general, mutating a data structure while iterating over it is a perilous practice leading to fragile code (many data structures ban the practice outright: databases, deques, dicts).

Mutating while iterating is only safe if a data structure makes explicit guarantees about how it iterates.  In Python, we have only a handful of such guarantees (you can safely mutate dict values while iterating over the keys and lists guarantee that the iterator looks-up consecutive indicies regardless of changes to the underlying list).

I propose to remove the last two paragraphs and the example, replacing them with clear practical advice and patterns that would pass a code review.

Something like this:

    Code that modifies a collection while iterating over
    that same collection can be tricky to get right.  Instead,
    it is usually more straight-forward to loop over a copy
    of the collection or to create a new collection.

```py
    # Strategy:  Iterate over a copy
    for user, status in users.copy():
        if status == 'inactive':
            del users[user]

    # Strategy:  Create a new collection
    active_users = {}
    for user, status in users.items():
        if status == 'active':
            active_users[user] = status
```

**Comment by terryjreedy** [comment]
I agree that the tutorial For section needs be updated to include non-sequences. A dict example will help with that.

I agree that the unrealistic insert mis-directs attention and like Raymond's replacement.  ['users.copy()' should be 'users.copy().items']
