### ISSUE TITLE
Keyword can't be an expression?

### ISSUE THREAD

**Issue by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [python/cpython#75041]
BPO | [30858](https://bugs.python.org/issue30858)
--- | :---
Nosy | @gvanrossum, @rhettinger, @ncoghlan, @bitdancer, @serhiy-storchaka, @vedgar, @lysnikolaou, @pablogsal, @iritkatriel
PRs | <li>python/cpython#23753</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-12-13.16:47:04.074>
created_at = <Date 2017-07-05.17:21:20.397>
labels = []
title = "Keyword can't be an expression?"
updated_at = <Date 2020-12-13.16:47:04.073>
user = 'https://github.com/vedgar'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-13.16:47:04.073>
actor = 'pablogsal'
assignee = 'none'
closed = True
closed_date = <Date 2020-12-13.16:47:04.074>
closer = 'pablogsal'
components = []
creation = <Date 2017-07-05.17:21:20.397>
creator = 'veky'
dependencies = []
files = []
hgrepos = []
issue_num = 30858
keywords = ['patch']
message_count = 13.0
messages = ['297772', '297798', '297800', '297805', '297828', '297899', '324138', '324139', '324168', '382547', '382918', '382933', '382935']
nosy_count = 9.0
nosy_names = ['gvanrossum', 'rhettinger', 'ncoghlan', 'r.david.murray', 'serhiy.storchaka', 'veky', 'lys.nikolaou', 'pablogsal', 'iritkatriel']
pr_nums = ['23753']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30858'
versions = []
```

</p></details>

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
Look at this (from https://www.quora.com/Is-end1-a-keyword-in-Python-3-6-1):

```py
print(end1 + end2 + end3 + end4 + end5 + end6 + end=' ')
         ^
SyntaxError: keyword can't be an expression
```


Wouldn't it be better if the message said "keyword for an argument must be a simple name"? Or something like that. Newbies, when they think of keywords, they think something from keyword.kwlist, not something used to pass arguments to a function in a particular way.

**Comment by bitdancer** [comment]
I think the current error message is more informative than your suggestion, myself.  However, the message could say "keyword argument name" instead of just "keyword", which I think would be quite a bit clearer.

I seem to remember another discussion where I suggested disambiguating "keyword" by using "keyword argument name", but I have no idea how to phrase a search to find that issue :(

**Comment by serhiy-storchaka** [comment]
bpo-29951.

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
I agree it's more \_correct_. But it's also more confusing. As far as I can tell, when writing error messages, we tend to minimize confusion, not maximize correctness.

Of course, it would be great to have both. Your "keyword argument name" seems pretty good.

**Comment by bitdancer** [comment]
If I saw your message, I would think "what is a 'simple name'?".  There's no glossary entry for that, nor is it a concept used elsewhere in the documentation as far as I remember.  One could instead use "single identifier",  but the problem with both of those is that "end" \*is* a simple name/single identifier.  The error isn't that an identifier was not used, the error is that an expression was used.  We unfortunately can't read the mind of the programmer to know that the \*actual* error was using a '+' instead of a ','.

**Comment by rhettinger** [comment]
FWIW, I prefer the current error message and my students don't seem to have issues with it.   

No matter what wording we put in, someone will always find a way to misread it, in part because the "end6 + end=' '" example isn't a simple mistake, it reflects an incorrect mental model that isn't easily fixed by an error message.
