### ISSUE TITLE
PCG random number generator

### ISSUE THREAD

**Issue by 5bdc2844-6f38-4b45-8218-144d190d3165** [python/cpython#75063]
BPO | [30880](https://bugs.python.org/issue30880)
--- | :---
Nosy | @tim-one, @rhettinger, @mdickinson, @evelynmitchell

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-07-09.02:36:35.586>
created_at = <Date 2017-07-08.17:14:16.801>
labels = ['extension-modules', 'type-feature', '3.7']
title = 'PCG random number generator'
updated_at = <Date 2017-07-09.03:19:44.347>
user = 'https://github.com/evelynmitchell'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-09.03:19:44.347>
actor = 'tim.peters'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-07-09.02:36:35.586>
closer = 'rhettinger'
components = ['Extension Modules']
creation = <Date 2017-07-08.17:14:16.801>
creator = 'Evelyn Mitchell'
dependencies = []
files = []
hgrepos = []
issue_num = 30880
keywords = []
message_count = 5.0
messages = ['297961', '297968', '297971', '297977', '297980']
nosy_count = 4.0
nosy_names = ['tim.peters', 'rhettinger', 'mark.dickinson', 'Evelyn Mitchell']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30880'
versions = ['Python 3.7']
```

</p></details>

**Comment by 5bdc2844-6f38-4b45-8218-144d190d3165** [comment]
John Cook tested the quality of the PCG Random Number generator (http://www.pcg-random.org/index.html) and it appears to have good performance. 

His report is at: 
https://www.johndcook.com/blog/2017/07/07/testing-the-pcg-random-number-generator/

This is a suggestion to add a PCG implementation.

**Comment by mdickinson** [comment]
Some previous discussions: "Time for a change of random number generator": https://mail.python.org/pipermail/python-dev/2016-February/143268.html

"Should our default random number generator be secure?": (warning: long) https://mail.python.org/pipermail/python-ideas/2015-September/035820.html

**Comment by 5bdc2844-6f38-4b45-8218-144d190d3165** [comment]
Mark, thanks for the background links.

My suggestion is much more constrained than the territory covered by those links.

**Comment by rhettinger** [comment]
FWIW, the previous discussions on the MersenneTwister have all resulted in a decision to stick with it.

The PCG family of PRNG is relatively new.  IIRC, the paper for it was never accepted for publication and some of its bolder claims haven't been proven.  It is far being standard or widely adopted.  In addition, there is not a single "the PCG RNG".  Instead, it is a collection of ideas and patterns for creating RNGs without recommending a single one that the "here use this one".

Tim reminded us that any issues for the MersenneTwister didn't surface for many years after its initial publication and wide-spread acceptance.  That is a cautionary note for adopting something too soon.

FWIW, I reviewed the PCG work a good while ago and discussed it with Guido.  The decision was to stick with the current safe choice.

That said, if someone wants to add this to PyPi, it is a really easy coding task.  There isn't much to the PCG code and the Python random module was designed to be "pluggable" so that other RNGs can easily be substituted by user.

**Comment by tim-one** [comment]
I agree closing was appropriate at this time.  I quite like PCG, but as Raymond said it's more a template for creating PRNGs than a specific generator.  So even if a compelling case could be made, there's still a long way to having specific code in mind.

In the Python world, the only non-trivial (i.e., not just a pure-Python toy demo program) PCG work I'm aware of is Robert Kern's (numpy's PRNG specialist) experiment with wrapping it:

https://github.com/rkern/pcg-python

But it hasn't been touched since late 2015.  It's also a bit concerning that Prof. O'Neill hasn't posted to her PCG blog in over 2 years:

http://www.pcg-random.org/blog/

I'm not concerned that the paper still hasn't been published - papers can sit a loooong time in review queues, and I'm afraid her paper is far too down-to-earth, readable, entertaining, and long for the TOMS editors' tastes \<0.3 wink\>.
