### ISSUE TITLE
Syntax checking confuses Try: class_instance_name as ... is used before glabal declaration

### ISSUE THREAD

**Issue by 19be915d-e6d6-4af6-a935-849f5286b99a** [python/cpython#75070]
BPO | [30887](https://bugs.python.org/issue30887)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @stevendaprano, @david-thrower

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-10.02:43:37.668>
created_at = <Date 2017-07-10.00:18:29.611>
labels = ['OS-mac', 'interpreter-core', 'build', 'invalid']
title = 'Syntax checking confuses Try: class_instance_name as ... is used before glabal declaration'
updated_at = <Date 2017-07-10.03:23:35.255>
user = 'https://github.com/david-thrower'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-10.03:23:35.255>
actor = 'Davidt'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-10.02:43:37.668>
closer = 'steven.daprano'
components = ['Interpreter Core', 'macOS']
creation = <Date 2017-07-10.00:18:29.611>
creator = 'Davidt'
dependencies = []
files = []
hgrepos = []
issue_num = 30887
keywords = []
message_count = 4.0
messages = ['298012', '298013', '298019', '298020']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'steven.daprano', 'Davidt']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30887'
versions = ['Python 3.6']
```

</p></details>

**Comment by 19be915d-e6d6-4af6-a935-849f5286b99a** [comment]
when I do anything like this:

```py
import flask ...
```




try:
    current_user
except NameError:
    global current_user
    current_user = User(request.form['parameter1'], request.form['parameter2'], '')


I get the error that the_user was 'used' before the global declaration. The try ... except ... is so when the user enters this route / function the first time, a class instance is instantiated, but if they return the second time, the existing class instance is updated in lines of code downstream rather than declared again with the same name, and therefore overwritten.

**Comment by 19be915d-e6d6-4af6-a935-849f5286b99a** [comment]
when I do anything like this:

```py
import flask ...
```


class User......
.
.
.

try:
    current_user
except NameError:
    global current_user
    current_user = User(request.form['parameter1'], request.form['parameter2'], '')


I get the error that current_user_user was 'used' before the global declaration. The try ... except ... is so when the user enters this route / function the first time, a class instance is instantiated, but if they return the second time, the existing class instance is updated in lines of code downstream rather than declared again with the same name, and therefore overwritten.

**Comment by stevendaprano** [comment]
Please copy and paste (don't retype from memory!) the \*exact* error you are getting.

You should be seeing something like:

SyntaxWarning: name 'current_user' is used prior to global declaration

(at least that's the warning I'm getting in Python 3.5), which is correct behaviour. The name is used prior to the global declaration.

The Python interpreter is now discouraging the use of the "global" keyword anywhere except at the top of the function. (It may some day become an error.)

If your code is unindented module-level code, as your code snippet suggests, you don't need the global declaration since current_user is automatically global.

If it is function-level code, then move the global declaration to the top of the function, as the SyntaxWarning suggests.

I don't believe this is a bug, I believe that what you are seeing is expected, so I am closing this bug report. If I have misunderstood what you are experiencing, then please re-open the ticket and give us some more information. Preferably give us some code that we can run that demonstrates the error. (Since the error doesn't have anything to do with flask, the `import flask` line is unnecessary.)

**Comment by 19be915d-e6d6-4af6-a935-849f5286b99a** [comment]
I made the syntax error go away by moving the global current_user above the
try......

I will have to revisit this one when time permits and write a script that
recreates the error. This will probably be later this week.

Thanks for your volunteer service.

David
