### ISSUE TITLE
import class not isinstance of the class

### ISSUE THREAD

**Issue by ghost** [python/cpython#75071]
BPO | [30888](https://bugs.python.org/issue30888)
--- | :---
Nosy | @ronaldoussoren, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-18.01:07:47.140>
created_at = <Date 2017-07-10.02:13:00.876>
labels = ['OS-mac', 'type-bug']
title = 'import class not isinstance of the class'
updated_at = <Date 2017-07-18.01:07:47.126>
user = None
```

bugs.python.org fields:
```python
activity = <Date 2017-07-18.01:07:47.126>
actor = '\xe9\x82\xb1\xe4\xbc\x9f\xe7\x95\xa5'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-18.01:07:47.140>
closer = '\xe9\x82\xb1\xe4\xbc\x9f\xe7\x95\xa5'
components = ['macOS']
creation = <Date 2017-07-10.02:13:00.876>
creator = '\xe9\x82\xb1\xe4\xbc\x9f\xe7\x95\xa5'
dependencies = []
files = []
hgrepos = []
issue_num = 30888
keywords = []
message_count = 3.0
messages = ['298018', '298029', '298568']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'ned.deily', '\xe9\x82\xb1\xe4\xbc\x9f\xe7\x95\xa5']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30888'
versions = ['Python 3.6']
```

</p></details>

**Comment by ghost** [comment]
the working directory is like below:

bug/
    dirc/
        \_\_init__.py
        foo.py
        foo2.py
    \_\_init__.py
    foo1.py
    

in foo.py:
```
class Event(object):
    pass
```

in foo2.py:
```
from a.foo import Event

def fun():
    return Event()
```

in foo1.py:
```
from bug.a.foo import Event
from bug.a.foo2 import fun

assert isinstance(fun(), Event)
```

when i try to execute the code in foo1.py, i got an assertion error.

but if i change foo2.py to:
```
from ..a.foo import Event

def fun():
    return Event()

```

the code in foo1.py can be done well without the assertion error.

i think it's about the import mechanism. 

i have checked PEP-328

I think 
when i do "from a.foo import Event", python import Event by the package name "a.foo.Event", but "from ..a.foo import Event" is going to import Event by "bug.a.foo.Event". and it is totally different in python.

is it kind of bug python should prevent?

**Comment by ronaldoussoren** [comment]
In foo2.py you import "a.foo", which refers to module 'a' that isn't included in the directory structure you describe.  I'm assuming 'dirc' should be 'a' to match the code.

How did you run foo1.py?  

When running with 'python3.6 -m bug.foo1' I get an error about not being able to import 'a' (as expected, the package is 'bug.a').

When you run with "PYTHONPATH=. python3.6 bug/foo1.py" I get the assertion failure you mention, and that's expected behavior.  This gets clearer when you print type(fun()) and Event, the output will be:

  \<class 'a.foo.Event'\>
  \<class 'bug.a.foo.Event'\>

As you can see these refer to two different classes, not the same class.

The reason for this is that  'python3.6 bug/foo1.py' adds the 'bug' directory to the start of sys.path, hence the "import a.foo" in foo2 succeeds. The script foo1.py imports 'bug.a.foo', which is a different name that happens to refer to the same file on the filesystem.

All in all this is expected behavior and not a bug.

**Comment by ghost** [comment]
ok. i see what you mean.
so python mark the class from the import way
