### ISSUE TITLE
speed up comparisons to self for built-in containers

### ISSUE THREAD

**Issue by 64d6bacc-d229-4315-b217-f79274508316** [python/cpython#75090]
BPO | [30907](https://bugs.python.org/issue30907)
--- | :---
Nosy | @tim-one, @rhettinger, @mdickinson, @vstinner, @serhiy-storchaka, @wbolster
PRs | <li>python/cpython#2679</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-07-21.16:54:09.497>
created_at = <Date 2017-07-12.13:15:31.139>
labels = ['interpreter-core', '3.7', 'performance']
title = 'speed up comparisons to self for built-in containers'
updated_at = <Date 2017-07-21.16:54:09.497>
user = 'https://github.com/wbolster'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-21.16:54:09.497>
actor = 'wbolster'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-07-21.16:54:09.497>
closer = 'wbolster'
components = ['Interpreter Core']
creation = <Date 2017-07-12.13:15:31.139>
creator = 'wbolster'
dependencies = []
files = []
hgrepos = []
issue_num = 30907
keywords = []
message_count = 13.0
messages = ['298213', '298257', '298259', '298286', '298315', '298338', '298340', '298357', '298360', '298806', '298808', '298811', '298813']
nosy_count = 6.0
nosy_names = ['tim.peters', 'rhettinger', 'mark.dickinson', 'vstinner', 'serhiy.storchaka', 'wbolster']
pr_nums = ['2679']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30907'
versions = ['Python 3.7']
```

</p></details>

**Comment by 64d6bacc-d229-4315-b217-f79274508316** [comment]
when comparing instances of the built-in container types (dict, list, and others) python assumes that "identity implies equality". this is documented (and assumed) behaviour:


"In enforcing reflexivity of elements, the comparison of collections assumes that for a collection element x, x == x is always true. Based on that assumption, element identity is compared first, and element comparison is performed only for distinct elements."

https://docs.python.org/3/reference/expressions.html#value-comparisons

because of this, various operations such as rich comparison of lists can be sped up by checking for identity first, and only falling back to (possibly) much slower rich comparisons on container elements when two elements are not identical (i.e. id(a) == id(b)).

because identity implies equality, comparing a container instance to itself is guaranteed to be true.

currently, comparing a list to itself takes O(n) time, which can be measured easily:

```pycon
>>> x = list(range(1000))
>>> %timeit x == x
2.95 µs ± 19.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

>>> y = list(range(100000))
>>> %timeit y == y
293 µs ± 3.35 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```


the second example is 100 times as slow.

i will shortly submit a few pull request to make "compare to self" run in O(1) time instead for a few of the built-in containers.

**Comment by rhettinger** [comment]
This seems like it optimizes an irrelevant use case, comparing a container to itself.  

I don't think this is likely to benefit any existing code, so it would be better not to add more code clutter/complexity with another special case code path unless we're pretty sure that special case actually arises in practice.

FWIW, the note about identity-implies-equality is a statement about how containers implement element comparison rather than about how two containers are compared to one another (as implemented in PyObject_RichCompareBool()).  Also, it isn't just an optimization, it is necessary to help us reason about containers (i.e. preserving the invariant: all(x in c for x in c)).

**Comment by tim-one** [comment]
Just noting that every special code path "at the start" doesn't just speed the case it's aiming at, it also \_slows_ every case that doesn't pass the new tests.  It takes time to fail the new tests.  So it usually makes things slower overall, unless the new thing being tested for is in fact common enough to more than make up for marginally slowing everything else.

It's hard to believe that "container1 is container2" happens in container comparison often enough that special-casing it wouldn't be an overall loss.  I'm pretty sure it never occurs in any of my code ;-)

**Comment by 64d6bacc-d229-4315-b217-f79274508316** [comment]
fwiw, "if (PyDict_CheckExact(a) && a == b)" amounts to two pointer comparisons, the overhead of which is too small to measure. (i tried.)

**Comment by tim-one** [comment]
Measuring in isolation (like with, e.g., timeit) isn't really interesting.  Then everything is in L1 cache, branches are 100% predictable (because they take the same branch over & over for the duration of the test), and second-order effects on \_other_ code are invisible.  For example, the 100% branch prediction comes at a hidden cost:  finite hardware branch-prediction tables had to kick out info about \_other_ branches to make room for the branches in the code being tested.  Likewise other code is kicked out of instruction caches to make room for the new tests, and similarly for whatever data the test uses.  Those limited hardware resources are consumed by the new code whether or not it's run in the context of a micro-benchmark.

I'm not claiming the new special cases would slow code down "a lot", or even significantly, or even measurably.  That's not the point.  The point is that we avoid adding special cases unless there's \_clear_ expected actual benefit, because when we multiply hundreds of code paths with "this could theoretically speed things up in some cases!" special tests, slowdowns \_do_ become significant.  They all fight each other, and with expected-case code, for limited hardware acceleration gimmicks.

For a very simple example, we don't special-case integer division by 1.  `n // m`, when m=1, takes time proportional to the number of (internal) digits in `n`, despite that we _could_ simply return a pointer to `n` in constant time.

For the same reasons:  it's rare for code to divide by 1, and checking for anything isn't free (even if a micro-benchmark can't demonstrate it).  However, if someone had a way to divide by \_any_ odd integer 5x faster than what we do now, \_that_ may be worth the extra test.

That's why Raymond and I are looking for a reason to even suspect that special-casing container identity would pay off in \_some_ plausibly realistic use case(s).

**Comment by serhiy-storchaka** [comment]
First, few comments about the code.

1) The condition "a == b" is enough. No need to test "PyDict_CheckExact(a)" and like.

2) This fast path can be used only for Py_EQ and Py_NE. For other operations it can change the behavior.

This is common approach of implementing operator== on C++. Unless comparing objects is trivial the implementation of operator== almost always starts with comparing pointers. In Python the overhead of calling methods and comparing objects is larger than in C++ and I expect that the relative overhead of one additional pointer comparison is smaller.

**Comment by serhiy-storchaka** [comment]
The main drawback of this optimization perhaps is not tiny runtime overhead in common case, but the complication of the code. It adds at least 6 or 8 lines to every rich compare implementation.

On other hand, this optimization already is implemented for integers, strings, bytes and slices.

**Comment by mdickinson** [comment]
> On other hand, this optimization already is implemented for integers, strings, bytes and slices.

Probably for good reasons, though, that don't necessarily apply to general containers / other objects.

I can see the possible value for strings and bytes, where filtering on a particular value might involve a good number of `s == s` comparisons (especially given string interning). Similarly, I could believe that small integer caching means that `0 == 0` or `1 == 1` comparisons happen often enough to make the 'is' optimisation worth it. I'm a bit bemused by the slice case, though.

**Comment by tim-one** [comment]
Ya, prior to now ;-) there's generally been some cost-benefit thought given to these things.  Strings and ints are immutable and some values of each are uniquely interned, so the case of identity is more than just plausible.  It happens often.

I'd guess that the bytes object inherited the identity check when old string code was edited to create the bytes type.  The case there is dubious:  as I recall, the only bytes object that's interned is the empty bytes object.

The `slice` object is a hoot.  They may never be compared outside of unit tests ;-)  The code itself is baffled by what it's doing:

```c
"""
static PyObject *
slice_richcompare(PyObject *v, PyObject *w, int op)
{
    ...
    if (v == w) {
        /* XXX Do we really need this shortcut?
           There's a unit test for it, but is that fair? */
    ...
"""
```


It doesn't really care about speed:  if v != w, the code goes on to allocate two temporary 3-tuples, copy the slices' data into them, call PyObject_RichCompare() to compare the tuples, then free the temporary 3-tuples.  Slow.  Its advantage is that it's "obviously correct".

A related example:  for lists, there's an early special case for EQ and NE when the lengths of the lists differ (if lists aren't the same length, they can't be equal).  However, tuple comparison deliberately omits that special case:  while tuple comparison is quite common in some programs (e.g., lots of programs sort large lists of tuples, or index large mappings by tuples), I never found real code that compared tuples of different lengths.  So long as that's so, checking for that case is a pure waste of code, time, and HW resources.

**Comment by rhettinger** [comment]
Any objections to closing this?

**Comment by serhiy-storchaka** [comment]
I don't have any objections to closing this. The net benefit is contradictory, the maintenance cost is not zero. In many performance important cases (dictionary lookup, searching in sequences) the identity already is checked before calling the comparison method.

Maybe it is worth to remove the fast patch from slice_richcompare() or speed up the general case, but this is a different issue.

**Comment by vstinner** [comment]
I never understood how container comparison works.

```pycon
>>> nan = float("nan")
>>> [nan] == [nan]
True
>>> (nan,) == (nan,)
True
>>> nan == nan
False
>>> nan is nan
True
```


I picked the float NaN because it's one of the weirdest object in Python: it's not equal to itself.

I don't know what is the impact of the proposed change on comparison. Can it break an application? It's unclear to me.

--

It also recalls me an optimization I proposed on string: begin with comparison on the hash, if the two hashs are already known. At the end, we decided that it wasn't worth it.

--

Raymond, Tim and Serhiy don't seem to be convince, so I will follow them and agree to reject this optimization :-)

**Comment by tim-one** [comment]
Victor, this part of the docs explains what you're seeing; scroll down to the

"""
In enforcing reflexivity of elements, the comparison of collections assumes that for a collection element x, x == x is always true ...
"""

part.

https://docs.python.org/3/reference/expressions.html#value-comparisons

In passing, note that dicts indexed by strings (well, indexed by anything) \_do_ compare hashes first.  In that specific case it's a major win - but in that specific case we also know in advance that "EQ or NE?" is the only question needing an answer.
