### ISSUE TITLE
Python not IEEE 754 float compliant for various zero operations

### ISSUE THREAD

**Issue by 3b8d22d7-a74a-4e4d-9598-f78aa6008f26** [python/cpython#75116]
BPO | [30933](https://bugs.python.org/issue30933)
--- | :---
Nosy | @mdickinson, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-14.19:07:41.758>
created_at = <Date 2017-07-14.18:25:23.687>
labels = ['interpreter-core', 'invalid', 'type-bug', '3.7']
title = 'Python not IEEE 754 float compliant for various zero operations'
updated_at = <Date 2017-07-14.19:20:08.096>
user = 'https://bugs.python.org/LloydVonHans'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-14.19:20:08.096>
actor = 'mark.dickinson'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-14.19:07:41.758>
closer = 'r.david.murray'
components = ['Interpreter Core']
creation = <Date 2017-07-14.18:25:23.687>
creator = 'LloydVonHans'
dependencies = []
files = []
hgrepos = []
issue_num = 30933
keywords = []
message_count = 3.0
messages = ['298368', '298370', '298371']
nosy_count = 3.0
nosy_names = ['mark.dickinson', 'r.david.murray', 'LloydVonHans']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30933'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 3b8d22d7-a74a-4e4d-9598-f78aa6008f26** [comment]
```pycon
>>> (-0)**.5
0.0
```


Should return -0.0

"Except that squareRoot(−0) shall be −0", IEEE 754-2008, Section 5.4.1

```pycon
>>> 1/(-0.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: float division by zero

>>> 1/(0.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: float division by zero
```


Should return -inf, and inf respectively.

"For division, when the divisor is zero and the dividend is a finite non-zero number, the sign of the infinity is the exclusive OR of the operands’ signs", IEEE 754-2008, Section 7.3

**Comment by bitdancer** [comment]
If I remember correctly, the exceptions adhere to the standard because it gives the option of "signaling" in those cases (but in any case it is the behavior we want).  

0.5 is a float, so x**.5 is not the square root.

```pycon
   >>> math.sqrt(-0.0)
   -0.0
```


I'm closing this but nosying Mark Dickinson, who will correct me if I got anything wrong :)

**Comment by mdickinson** [comment]
(-0) ** 0.5 is a power operation, not a square root operation. As such, the relevant part of IEEE 754-2008 is section 9.2.1, "Special values", which says:

> pow (±0, y) is +0 for finite y \> 0 and not an odd integer

For the other cases, in general the philosophy is that we should raise exceptions where an FPE would be signalled, in preference to returning infinities and NaNs. So for example `math.sqrt(-1)` raises a ValueError rather than giving a NaN, and 1.0 / 0.0 raises ZeroDivisionError similarly. Unfortunately we don't have complete consistency here: for example 1e300 * 1e300 gives an infinity instead of raising. But that behaviour has been in the language for a looong time, and it's hard to change without breaking existing code.
