### ISSUE TITLE
Docs should say that `x is z or x == z` is used for `x in y` in containers that do not implement `__contains__`

### ISSUE THREAD

**Issue by ff59cd45-ebe3-4b3e-9696-65dc59a38b8c** [python/cpython#75152]
BPO | [30969](https://bugs.python.org/issue30969)
--- | :---
Nosy | @rhettinger, @bitdancer, @ztane, @csabella, @miss-islington
PRs | <li>python/cpython#2761</li><li>python/cpython#13684</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-05-30.20:20:17.613>
created_at = <Date 2017-07-19.11:55:53.603>
labels = ['type-feature', 'docs']
title = 'Docs should say that `x is z or x == z` is used for `x in y` in containers that do not implement `__contains__`'
updated_at = <Date 2019-05-30.20:41:25.965>
user = 'https://github.com/ztane'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-30.20:41:25.965>
actor = 'miss-islington'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-05-30.20:20:17.613>
closer = 'cheryl.sabella'
components = ['Documentation']
creation = <Date 2017-07-19.11:55:53.603>
creator = 'ztane'
dependencies = []
files = []
hgrepos = []
issue_num = 30969
keywords = []
message_count = 4.0
messages = ['298671', '298675', '344000', '344001']
nosy_count = 6.0
nosy_names = ['rhettinger', 'r.david.murray', 'docs@python', 'ztane', 'cheryl.sabella', 'miss-islington']
pr_nums = ['2761', '13684']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30969'
versions = []
```

</p></details>

**Comment by ff59cd45-ebe3-4b3e-9696-65dc59a38b8c** [comment]
The doc reference/expressions.srt says that

> For user-defined classes which do not define \_\_contains__() but do 
> define \_\_iter__(), x in y is True if some value z with x == z is 
> produced while iterating over y. If an exception is raised during the 
> iteration, it is as if in raised that exception.

and

> Lastly, the old-style iteration protocol is tried: if a class defines 
> \_\_getitem__(), x in y is True if and only if there is a non-negative 
> integer index i such that x == y[i], and all lower integer indices do 
> not raise IndexError exception. (If any other exception is raised, it 
> is as if in raised that exception).

The documentation doesn't match the implementation, which clearly does `x is y or x == y` to check if `x` is the element `y` from a container. Both the `__iter__` and the index-iteration method test the elements using `is` first. While the document says that `x is x` means that `x == x` should be true, it is not true for example in the case of `nan`:

**Comment by bitdancer** [comment]
I think you change is appropriate given that the "equivalent to" for the built in iterators contains the 'is' expression.

However, I also think we should drop that second whole paragraph, and in the previous paragraph say "...but are :term:\`iterable\`...".  Because conceptually what we do is iterate whatever we're given if iter doesn't return a TypeError, and it is iter that handles the fallback to the older \_\_getitem__ protocol.  I don't see why we should re-explain the iteration protocol in the docs for 'in'.  (I haven't looked at how this is actually implemented, but the implementation ought to be equivalent to that or we will eventually run into bugs.)  I don't think this would result in any loss of precision or understandability, and in fact I think it would make it easier to understand.

See also bpo-27605, which also wants to edit this section slightly.
