### ISSUE TITLE
Set closing variable in asyncore at close

### ISSUE THREAD

**Issue by 6f420f36-ae52-4100-87bc-98d4be1300b0** [python/cpython#75168]
BPO | [30985](https://bugs.python.org/issue30985)
--- | :---
Nosy | @vstinner, @giampaolo, @serhiy-storchaka, @bjmb
PRs | <li>python/cpython#2804</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-06.14:27:05.356>
created_at = <Date 2017-07-21.16:06:42.438>
labels = ['3.7']
title = 'Set closing variable in asyncore at close'
updated_at = <Date 2018-09-06.14:27:05.355>
user = 'https://github.com/bjmb'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-06.14:27:05.355>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-06.14:27:05.356>
closer = 'vstinner'
components = []
creation = <Date 2017-07-21.16:06:42.438>
creator = 'walkhour'
dependencies = []
files = []
hgrepos = []
issue_num = 30985
keywords = []
message_count = 12.0
messages = ['298815', '299026', '299028', '299032', '299134', '299145', '299147', '299151', '299154', '299165', '299171', '324693']
nosy_count = 5.0
nosy_names = ['vstinner', 'giampaolo.rodola', 'serhiy.storchaka', 'Nir Soffer', 'walkhour']
pr_nums = ['2804']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30985'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a3806f99-9e4c-4c1e-88f5-8972537b5177** [comment]
This is an old issue with asyncore - asyncore has a "closing" attribute,
but it was never used. Every user has to implement the closing once
logic in dispatcher subclasses.

Here is a typical fixes in user code:
- https://github.com/oVirt/vdsm/blob/master/lib/vdsm/storage/asyncevent.py#L497
- https://github.com/oVirt/vdsm/blob/master/lib/vdsm/storage/asyncevent.py#L540

Fixing closing attribute will allow fixing the races during
asyncore.poll() and asyncore.poll2(), see
https://github.com/python/cpython/pull/2764

**Comment by vstinner** [comment]
Proposed change looks more like an enhancement like a bug fix.

I consider that features are not welcome anyone in the asyncore module, since it's now deprecated, replaced with selectors and asyncio.

I would prefer to reject this issue.

Giampaolo, Serhiy, Guido: what do you think?


> Every user has to implement the closing once logic in dispatcher subclasses.

Even if it's painful, I consider that it's an acceptable compromise.

**Comment by a3806f99-9e4c-4c1e-88f5-8972537b5177** [comment]
I agree that this change alone is may not be important enough to fix in asyncore today - but this enables easy detection of closed sockets needed for https://github.com/python/cpython/pull/2764 or the alternative https://github.com/python/cpython/pull/2854. Unless you suggest a better way to detect closed dispatchers.

Introducing new failures modes in asyncore is extremely risky, error handling in asyncore is the weakest point.

**Comment by vstinner** [comment]
"Fixing closing attribute will allow fixing the races during asyncore.poll() and asyncore.poll2(), see https://github.com/python/cpython/pull/2764"

Aha, \*slowly* I understand that asyncore is vulnerable to multiple race conditions, and it seems lile we require to set a new closing attribute to fix it.

**Comment by a3806f99-9e4c-4c1e-88f5-8972537b5177** [comment]
The "new" closing attribute is old as asyncore, it was just unused :-)

**Comment by giampaolo** [comment]
I welcome this change as it avoids tricks like this one: 
https://github.com/giampaolo/pyftpdlib/blob/1268bb185cd63c657d78bc33309041628e62360a/pyftpdlib/handlers.py#L537
Any app using asyncore for anything other than an echo server eventually ends up doing the same.

**Comment by giampaolo** [comment]
On the other hand, due to the poor asyncore API, I think it's safer if we land this in 3.7 only. "closing" attribute was never documented so if there's code out there setting it to True that'll crash their app pretty quickly as sockets won't close.

**Comment by a3806f99-9e4c-4c1e-88f5-8972537b5177** [comment]
Giampaolo, people using only 3.7 should probably use asyncio. Fixing
asyncore is more important to those that can use only 2.7 (e.g.Centos/RHEL)
or have to support both python 3 and 2.

Do you think using \_closed is safer for backport? This can also clash with
existing code.

**Comment by vstinner** [comment]
"Giampaolo, people using only 3.7 should probably use asyncio. Fixing
asyncore is more important to those that can use only 2.7 (e.g.Centos/RHEL) or have to support both python 3 and 2."

IMHO starting to use closing in asyncore \*is* a backward incompatible change. We don't know how applications use this existing attribute. Maybe it's not set to a boolean. Maybe it uses a different policy.

I would be ok to start using closing in Python 3.7, but I'm not confortable with backporting such change.

I would be if would be add a new private attribute, as the proposed "\_closed" name.

Maybe nobody uses closing. Maybe people using closing have a similar usage. The thing is that we don't know, and according to what you wrote Nir, closing \*is* used.

What I dislike in asyncore is that subclassing is not prohibed, it seems wanted by design. Ok, but what if a subclass overrides completely a method and doesn't set "closing/_closed" anymore? That's another reason why I dislike the idea of making any change in asyncore \*especially* in Python 2.7 which is now considered as "very stable".

**Comment by vstinner** [comment]
It seems like the closing attribute is not \*required* to fix bpo-30931, asyncore race condition:
http://bugs.python.org/issue30931#msg299162

Another approach doesn't rely on close() "implementation", but more on close() "expected behaviour" (remove the dispatcher file descriptor from map). IMHO this approach would reduce the risk of backward incompatibility.

--

I'm still in favor of rejecting this feature request, \*but* I would prefer to first wait until we agree how to fix bpo-30931 race condition.

**Comment by giampaolo** [comment]
I would probably feel safer to use "\_\_closed" for all python versions and adopt the same naming convention for any attribute we may want to add in the future. Kinda weird, but asyncore is probably the only case of deprecated module with bad API design which makes it risky to make any change to the class namespace. As such I consider using the ugly "\_\_" prefix justifiable.
