### ISSUE TITLE
IDLE: Add tests for configdialog keys tab

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#75185]
BPO | [31002](https://bugs.python.org/issue31002)
--- | :---
Nosy | @terryjreedy, @csabella
PRs | <li>python/cpython#2996</li><li>python/cpython#3092</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-08-15.01:55:44.277>
created_at = <Date 2017-07-24.07:25:08.138>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'IDLE: Add tests for configdialog keys tab'
updated_at = <Date 2017-08-15.21:50:09.573>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-15.21:50:09.573>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-08-15.01:55:44.277>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-07-24.07:25:08.138>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 31002
keywords = []
message_count = 10.0
messages = ['299624', '299633', '299678', '299723', '300114', '300124', '300274', '300277', '300280', '300311']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'cheryl.sabella']
pr_nums = ['2996', '3092']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31002'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by csabella** [comment]
I'm working on the tests for this.

**Comment by terryjreedy** [comment]
Great.  It is non-trivial, so I don't expect perfection first try.  Please revise docstring with explanation of how page works, like with Font and General pages.  I finished tests using those explanations as a guide.  They are also a guide for review.

**Comment by csabella** [comment]
I'm making good progress on this.  I should be able to open the PR tomorrow.  It's definitely non-trivial, but using your font and general tests as a guide has been invaluable.

**Comment by csabella** [comment]
I tried to minimize the changes to configdialog.  There were more I wanted to make, like reorganizing the order of the functions, but I didn't want to make the diff too crazy.  I changed some variable names because all of them had 'keys' in it and I couldn't keep track of them.  It was almost as descriptive as single letter variables!  ;-)   I think I made the new names inline with what had been done on the font and general tabs.  Again, there were more renaming changes I wanted to make (such as key_set to keyset), but I didn't want every line to be a diff.

Also, I used the name 'keyset' to refer to the section names and the keybindings to refer to the option:value pairs.  Some old vars in configdialog weren't changed to reflect this 100%, but the comment should be correct.

I did not include deactivate_current_config and activate_config__changes since those are not really specific to keys.  There are also invoked from themes and from apply.

I have notes for some of the other coding changes I'd like to make once this is in its own class.

**Comment by terryjreedy** [comment]
I am not sure I agree with all your suggested name changes.  But I am looking as more substantive issues first.

**Comment by terryjreedy** [comment]
I have thought about factoring out common test code into helper functions either within test_configdialog or in a new module.  One example: simulate a click on a listbox, with common before and after code.  Another: Testing the group of selection widgets on both theme and keys pages. (If I were not planning to replace this group, we could factor out a SelectionFrame and put an instance on each page.)

We might do some such refactoring after this, before HighPageTest.  Keep notes on redundancies you notice that might be candidates.

**Comment by terryjreedy** [comment]
New changeset 2f8964634918bdf09107c49a2d5ca62460091e54 by Terry Jan Reedy (Cheryl Sabella) in branch 'master':
bpo-31002: IDLE: Add tests for configdialog keys tab (bpo-2996)
https://github.com/python/cpython/commit/2f8964634918bdf09107c49a2d5ca62460091e54

**Comment by terryjreedy** [comment]
New changeset a31459008c5b3230363d155a2e8616664dc4f0c6 by Terry Jan Reedy in branch '3.6':
[3.6] bpo-31002: IDLE: Add tests for configdialog keys tab (GH-2996) (bpo-3092)
https://github.com/python/cpython/commit/a31459008c5b3230363d155a2e8616664dc4f0c6

**Comment by terryjreedy** [comment]
Great work. Thank you.
Next: bpo-31205, bpo-31001, bpo-31206, then ...

**Comment by terryjreedy** [comment]
Lines not yet covered in keys group, other than deactivate_current_config and activate_config_changes functions:

def save_new_key_set
    if not idleConf.userCfg['keys'].has_section(keyset_name):
\# never false - minor issue

def delete_custom_keys
    if not item_list:
\# never false hence following never executed
    else: self.customlist.SetMenu(item_list, item_list[0])
