### ISSUE TITLE
All Sphinx generated pages could have a new "Edit This Page" link adjacent to the existing "Show Source"

### ISSUE THREAD

**Issue by 7833f0f6-c20d-4af4-b77e-0b4dc7bf941a** [python/cpython#75238]
BPO | [31055](https://bugs.python.org/issue31055)
--- | :---
Nosy | @freddrake, @bitdancer, @Mariatta, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-07-27.12:45:26.092>
labels = ['3.11', 'docs']
title = 'All Sphinx generated pages could have a new "Edit This Page" link adjacent to the existing "Show Source"'
updated_at = <Date 2021-04-25.18:13:44.968>
user = 'https://bugs.python.org/PaulHammant'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-25.18:13:44.968>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2017-07-27.12:45:26.092>
creator = 'Paul Hammant'
dependencies = []
files = []
hgrepos = []
issue_num = 31055
keywords = []
message_count = 7.0
messages = ['299306', '299325', '299336', '299337', '299338', '299343', '391865']
nosy_count = 6.0
nosy_names = ['fdrake', 'r.david.murray', 'docs@python', 'Paul Hammant', 'Mariatta', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue31055'
versions = ['Python 3.11']
```

</p></details>

**Comment by 7833f0f6-c20d-4af4-b77e-0b4dc7bf941a** [comment]
Show Source links to: https://github.com/python/cpython/blob/path/to/resource.rst

Edit This Page would link to
https://github.com/python/cpython/edit/path/to/resource.rst

And yes, GitHub does the right thing if you're not ordinarily permitted to change python/cpython

**Comment by Mariatta** [comment]
I don't think we should add this link.

When we make edits to the docs, even simple typo fixes, it should first be done in the master branch, instead of the maintenance branches (e.g. 2.7, 3.5 or 3.6).

If "Edit This Page" link takes you to edit the documentation in branches other than "master", that's not desirable workflow.

If "Edit This Page" link takes you to edit the master branch, it can be confusing to the contributor since the content on "master" might be different.

**Comment by freddrake** [comment]
On Thu, Jul 27, 2017 at 1:03 PM, Mariatta Wijaya \<report@bugs.python.org\> wrote:
> I don't think we should add this link.
>
> When we make edits to the docs, even simple typo fixes, it should first be done
> in the master branch, instead of the maintenance branches (e.g. 2.7, 3.5 or 3.6).
>
> If "Edit This Page" link takes you to edit the documentation in branches other
> than "master", that's not desirable workflow.
>
> If "Edit This Page" link takes you to edit the master branch, it can be confusing
> to the contributor since the content on "master" might be different.

I wonder if a better solution lies somewhere between the original
suggestion and just
not including such a link.

If the link went to an edit form with the version of the content the
user was reading,
and includes an explanation of the multiple-versions issue, it might
prove reasonable
to try applying the diff between the modified and original text to the
HEADs of each
maintenance branch.  If the diff doesn't apply, the (possibly new)
contributor can be
offered a chance to deal with edits to each version (which might be a bit much).

At any rate, the diff could be used to construct a temporary branch,
b.p.o issue, and
PR. This would allow us to provide the contributor with a way to see
that their suggested
changes are being considered, and we're less likely to lose them in a
wall of email.

There'd be a bit of work to make all this play out, though.

  -Fred

**Comment by freddrake** [comment]
On Thu, Jul 27, 2017 at 3:01 PM, Fred L. Drake, Jr.
\<report@bugs.python.org\> wrote:
> If the link went to an edit form with the version of the content the
> user was reading,
> and includes an explanation of the multiple-versions issue, it might
> prove reasonable

Egads, look at that formatting!

Somedays I miss my VT-100 terminals and sane line handling.

  -Fred

**Comment by 7833f0f6-c20d-4af4-b77e-0b4dc7bf941a** [comment]
Hi folks, I'm not explaining Github's non-commiter contribution process very well.

Click this link everyone - https://github.com/BuildRadiator/BuildRadiator/edit/master/README.md - pretend to make a contribution to one of my projects :)

**Comment by bitdancer** [comment]
No, we understand the process, the problem is that except for the 'dev' docs, the link would be to a branch other than master.  That's the problem that we're discussing.

Maybe instead of an edit link on non-dev docs we could have a message saying that if you want to propose a change you can use the edit link on the 'dev' version of the docs?  Maybe with a link or button that would take them to the dev version of the page?

**Comment by hugovk** [comment]
As described, "Edit this page" doesn't really work due to the different branches.

However, all pages (for example https://docs.python.org/3/library/bz2.html) have a "[Found a bug](https://docs.python.org/bugs.html)?" link in the footer, which has info about how to improve the content.

So let's close this, and thanks for the report.
