### ISSUE TITLE
Make super() work with staticmethod by using __class__ for both arguments to super()

### ISSUE THREAD

**Issue by 343ed643-0780-4999-99b9-d39c2c3e528a** [python/cpython#75301]
BPO | [31118](https://bugs.python.org/issue31118)
--- | :---
Nosy | @rhettinger, @ncoghlan, @ashwch, @denis-ryzhkov

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-20.05:14:08.990>
created_at = <Date 2017-08-04.06:42:55.082>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Make super() work with staticmethod by using __class__ for both arguments to super()'
updated_at = <Date 2018-05-14.16:02:02.425>
user = 'https://github.com/ashwch'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-14.16:02:02.425>
actor = 'denisr'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-20.05:14:08.990>
closer = 'ncoghlan'
components = ['Interpreter Core']
creation = <Date 2017-08-04.06:42:55.082>
creator = 'ashwch'
dependencies = []
files = []
hgrepos = []
issue_num = 31118
keywords = []
message_count = 4.0
messages = ['299733', '300594', '300597', '316527']
nosy_count = 4.0
nosy_names = ['rhettinger', 'ncoghlan', 'ashwch', 'denisr']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31118'
versions = ['Python 3.7']
```

</p></details>

**Comment by 343ed643-0780-4999-99b9-d39c2c3e528a** [comment]
From this question I noticed that super() doesn't work with static methods with no arguments: https://stackoverflow.com/q/45498675/846892

My question is what's the issue with using \_\_class__ for both arguments to super() in case of static method? Or was it just an oversight.

**Comment by rhettinger** [comment]
Do you have a use case?  This seems doesn't seem like it would be helpful at all and would make super a little more confusing than it already is.

**Comment by ncoghlan** [comment]
Thanks for the suggestion, but I'm closing this RFE, as there are two strong arguments against it: one related to implementation feasibility, and one related to the nature of what super() \*does*.

The feasibility argument is that the compiler doesn't even have the necessary information to do this, since it doesn't know what kind of method it's dealing with (it has no idea what decorators actually do, it just compiles them as subexpressions). Instead, the compiler blindly translates "super()" into "super(__class__, \<first positional argument\>)" when inside a function definition that's inside a class definition. As a result, there's no way for the compiler to special case static methods and pass \_\_class__ as the second argument as well.

Even without considering that technical limitation though, using \_\_class__ for both arguments doesn't do anything particularly sensible, since super() is specifically about resolving name lookups using the \*dynamic* method resolution order (MRO) of the class the method was retrieved from (which may be a subclass of the class defining the method).

So in instance methods and class methods, type(self) or cls provides the dynamic MRO to use, while \_\_class__ identifies \*where* along that MRO the currently running method implementation sits.

In a static method, there's no dynamic MRO available for super() to query. This means that if you want access to one, you need to convert the method to a classmethod first so that the interpreter will pass in a reference to the class the method was retrieved from (as opposed to the one where it was defined, which is what \_\_class__ gives you).

If folks actually do want to make a method implementation in a child class depend on a static method in a parent class, there are two ways to do that, but only one of them will work correctly in the face of multiple inheritance:

1. Make the child method a class method. This is the most readable approach, since you can then use zero-argument super() to call the staticmethod in the parent class in the usual way. As long as all child classes overriding the method adhere to this approach, that particular class hierarchy will also reliably respect Python's MRO linearisation rules in the case of multiple inheritance.

2. Make the child method a staticmethod, and then use "super(__class__, \_\_class__)" to access the staticmethod in the parent class. This will work OK in cases where there aren't any diamonds in the inheritance hierarchy, but it completely bypasses the dynamic C3 linearisation algorithm, and hence may do weird things in the presence of such diamonds (i.e. cases where a subclass has multiple inheritance paths back to a given base class - see https://python-history.blogspot.com.au/2010/06/method-resolution-order.html for more detail on this).
