### ISSUE TITLE
PriorityQueue.put() fails with TypeError if priority_number in tuples of (priority_number, data) are the same.

### ISSUE THREAD

**Issue by 089b4fff-0cef-4c33-a0ec-c12718838abb** [python/cpython#75328]
BPO | [31145](https://bugs.python.org/issue31145)
--- | :---
Nosy | @rhettinger, @ncoghlan, @bitdancer, @lisroach
PRs | <li>python/cpython#5153</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2018-01-12.06:07:15.262>
created_at = <Date 2017-08-08.14:09:13.395>
labels = ['3.7', 'type-feature', 'library']
title = 'PriorityQueue.put() fails with TypeError if priority_number in tuples of (priority_number, data) are the same.'
updated_at = <Date 2018-01-12.06:07:15.261>
user = 'https://bugs.python.org/MikoajBabiak'
```

bugs.python.org fields:
```python
activity = <Date 2018-01-12.06:07:15.261>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2018-01-12.06:07:15.262>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-08-08.14:09:13.395>
creator = 'Miko\xc5\x82aj Babiak'
dependencies = []
files = []
hgrepos = []
issue_num = 31145
keywords = ['patch']
message_count = 9.0
messages = ['299922', '299929', '302870', '302902', '302905', '302911', '303093', '307646', '309839']
nosy_count = 5.0
nosy_names = ['rhettinger', 'ncoghlan', 'r.david.murray', 'lisroach', 'Miko\xc5\x82aj Babiak']
pr_nums = ['5153']
priority = 'low'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31145'
versions = ['Python 3.7']
```

</p></details>

**Comment by 089b4fff-0cef-4c33-a0ec-c12718838abb** [comment]
```py
# list of tuples in form of (priority_number, data)
bugged = [
(-25.691, {'feedback': 13, 'sentiment': 0.309, 'support_ticket': 5}), (-25.691, {'feedback': 11, 'sentiment': 0.309, 'support_ticket': 3}), (-25.0, {'feedback': 23, 'sentiment': 0.0, 'support_ticket': 15}),
]

from queue import PriorityQueue

pq = PriorityQueue()

for item in bugged:
   pq.put(item)
```


\# TypeError: '\<' not supported between instances of 'dict' and 'dict'

It seems that if priority_numbers are equal, heapq.heapify() falls back to comparing data element from tuple (priority_number, data).
I belive this is an undesired behaviour.
It is acctually listed as one of implementation challenges on https://docs.python.org/3/library/heapq.html:
"Tuple comparison breaks for (priority, task) pairs if the priorities are equal and the tasks do not have a default comparison order."

In python 2.7 the issue in not present and PriorityQueue.put() works as expected

**Comment by rhettinger** [comment]
I don't see any way to change PriorityQueue to fix this.  The non-comparability of dicts likely won't be restored, nor will the lexicographic comparison order of tuples be likely to change.

One possible way forward is to provide a wrapper with the desired comparison behavior:

```py
    pq = PriorityQueue()
    pq.put(Prioritize(13, task))
    task = pq.get().item
  
where Prioritize is implemented something like this:

import functools

@functools.total_ordering
class Prioritize:

    def __init__(self, priority, item):
        self.priority = priority
        self.item = item

    def __eq__(self, other):
        return self.priority == other.priority

    def __lt__(self, other):
        return self.priority < other.priority

from queue import PriorityQueue, Empty
from contextlib import suppress

bugged = [
(-25.691, {'feedback': 13, 'sentiment': 0.309, 'support_ticket': 5}), (-25.691, {'feedback': 11, 'sentiment': 0.309, 'support_ticket': 3}), (-25.0, {'feedback': 23, 'sentiment': 0.0, 'support_ticket': 15}),
]

pq = PriorityQueue()

for priority, item in bugged:
    pq.put(Prioritize(priority, item))
with suppress(Empty):
    while True:
        item = pq.get_nowait().item
        print(item)
```

**Comment by rhettinger** [comment]
Nick, what do you think about this proposal?

The problem being solved is that decorated tuples no longer work well for controlling ordering (because so many types are now non-comparable).  This provides a wrapper to control which fields are used in comparison.

For implementation and API, there are several ways to do it, (accept separate arguments vs accept an existing sequence, standalone class vs a tuple subclass, pure python and/or c-implementation, etc).

**Comment by ncoghlan** [comment]
The main downside I see to that approach is that it would still require quite a few client code changes to restore compatibility for folks upgrading from 2.7, and even though six could add a "six.Prioritize" backport, it would still be difficult for automated tools to work out \*where* such a wrapper would be appropriate.

So I'm wondering whether it might be worth defining a heapq.compareitem helper that special cases tuples, such that heapq switched to using a slightly modified definition of tuple comparisons:

```py
    def compareitem(lhs, rhs):
        """<= variant that ensures all tuples are orderable"""
        is not isinstance(lhs, tuple) or not isinstance(rhs, tuple):
            return lhs <= rhs
        # Compare tuples up to first unequal pair
        for lhs_item, rhs_item in zip(lhs, rhs):
            if lhs_item != rhs_item:
                try:
                    return lhs_item < rhs_item
                except TypeError:
                    pass
                break
        # All item pairs equal, or unorderable pair found
        return len(lhs) <= len(rhs)
```


The key difference would be that if the heap-centric tuple comparison encounters a non-equal, unorderable pair of items, it would fall back to just comparing the tuple lengths (just as regular tuple comparison does when all item pairs are equal), rather than letting the TypeError propagate the way the default tuple comparison operator does.

The heap invariant would change slightly such that "storage.sort(key=heapq.compareitem)" would reliably preserve the heap invariant without raising an exception, while "storage.sort()" might instead fail with TypeError.

**Comment by rhettinger** [comment]
We already have recommendations in the heapq documentation on how to do a work-around.   I'm looking at the more general problem of how can we make it easy once again to decorate a value with a sort value (not just for heaps but for anyplace where comparisons are made).

I would like our preferred answer to be something better than, "take all your existing functions that use comparisons and make new variants that compute and cache key functions".   Instead, I would rather, "keep your existing functions simple and just wrap your data in something that specifies comparison values that are computed just once". 

The old Schwartzian transform (decorate-compare-undecorate) had broad applicability but was effectively killed when a simple tuple no longer served for decoration.  

FWIW, the DataClass discussion has also ventured into this territory (the field definitions can specify whether or not a field is included in the rich comparison methods).

**Comment by ncoghlan** [comment]
My rationale for asking "What if we just changed heapq back to working closer to the way it used to work?" is that it's a case where arbitrarily ordering unorderable tuples made sense, and reverting it to the old behaviour is reasonably safe:

- some Py3 heapq code that previously raised TypeError would start using an arbitrary ordering instead
- Py2 heapq code would get a \*different* arbitrary ordering in Py3, but it would still get an arbitrary ordering

I don't feel especially strongly about that though, so if you prefer the approach of defining a new more explicit idiom to replace the old "make a tuple" one, I think a new wrapper type is a reasonable way to go, but using "Prioritize" as a name is probably too specific to the PriorityQueue use case.

As a more generic name, "KeyedItem" might work:

```
@functools.total_ordering
class KeyedItem:

    def __init__(self, key, item):
        self.key = key
        self.item = item

    def __eq__(self, other):
        return self.key == other.key

    def __lt__(self, other):
        return self.key < other.key
```

So applying an arbitrary key function would look like:

```py
    decorated = [KeyedItem(key(v), v) for v in values]
```


And if it was a tuple subclass, it would also work with APIs like the dict constructor.

**Comment by lisroach** [comment]
I think it is a good idea to have a simple way to add a value to sort on in general, it could have some interesting use-cases. Also I am with Nick a name change would make the broader scope clearer.

What I am not sure about is making the comparison have to be between two items of the same wrapper type - since right now we are comparing priority to priority attributes. 

It makes sense for PriorityQueues, but if we wanted to use this for something more arbitrary like comparing a string with an int priority to an int we end up having to convert both data types to the new wrapper type:

```py
  str_cmp = KeyedItem(20, 'cat')
  int_cmp  = KeyedItem(30, 30)
  str_cmp < int_cmp
```



I don't like having to convert to the new wrapper unless it's relevant, I'd rather do:

```py
  str_cmp = KeyedItem(20, 'cat')
  str_cmp < 30
```



It could be instead:

```py
 class KeyedItem:
    def __init__(self, key, item):
         self.key = key
         self.item = item
     def __eq__(self, other):
         if not isinstance(other, KeyedItem):
             return self.key == other
         return self.key == other.key
            
     def __lt__(self, other):
	if not isinstance(other, KeyedItem):
            return self.key < other
        return self.key < other.key
     ...
```

**Comment by anthonyKiggundu** [comment]
Hello there, 
I think this issue does not work in some cases because I cannot get around the bug despite following all the above suggestions or I might be doing something wrong. I have the following two classes and I still receive the comparison error when I try to heapify the a list containing heapq requests.

`class Station(object):

    def __init__(self, env, key=lambda x:x):
        self.env = env
        self.servers = [Resource(env), Resource(env)]
        self.request_list = {}

    def customer(self, env, servers):
        request = self.servers[shorter_q].request()
        yield request
        curr_queue_requests = self.servers[shorter_q].queue

    def function_name(self, curr_queue_requests):
        object_heap = HeapRequests(curr_queue_requests)
        object_heap.pop()
...... 
 class HeapRequests(object):
    def __init__(self, req_list=None, key=lambda x:x):
        self.key = key
        self.index = 0
        if req_list:
            self.shorter_queue_reqs = [(key(y), x, y) for x, y in enumerate(req_list)]        
            self.index = len(self.shorter_queue_reqs)
            heapify(self.shorter_queue_reqs)
        else:
            self.shorter_queue_reqs = []

    def __eq__(self, other):
        return self.key == other.key

    def __lt__(self, other):
        return self.key < other.key

    def push(self, item):
        heappush(self.shorter_queue_reqs, (self.key(item), self.index, item))
        self.index += 1

    def pop(self):
        return heappop(self.shorter_queue_reqs)
...........................
`
I do not see anything missing but any help here would be highly appreciated as I am really blocked
