### ISSUE TITLE
lib2to3 requires source files for fixes

### ISSUE THREAD

**Issue by b40b6e41-0162-4214-b8d2-5baa33f3d7ad** [python/cpython#75326]
BPO | [31143](https://bugs.python.org/issue31143)
--- | :---
Nosy | @brettcannon, @bitdancer, @zooba, @vedgar, @twschiller
Superseder | <li>bpo-45544: Close 2to3 issues and list them here</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-10-20.22:50:54.893>
created_at = <Date 2017-08-08.13:43:40.432>
labels = ['type-bug', 'expert-2to3']
title = 'lib2to3 requires source files for fixes'
updated_at = <Date 2021-10-20.22:50:54.893>
user = 'https://github.com/twschiller'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-20.22:50:54.893>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-10-20.22:50:54.893>
closer = 'iritkatriel'
components = ['2to3 (2.x to 3.x conversion tool)']
creation = <Date 2017-08-08.13:43:40.432>
creator = 'tschiller'
dependencies = []
files = []
hgrepos = []
issue_num = 31143
keywords = []
message_count = 9.0
messages = ['299920', '299924', '299926', '299927', '300100', '300112', '300150', '300178', '300187']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'r.david.murray', 'steve.dower', 'veky', 'tschiller']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = '45544'
type = 'behavior'
url = 'https://bugs.python.org/issue31143'
versions = []
```

</p></details>

**Comment by b40b6e41-0162-4214-b8d2-5baa33f3d7ad** [comment]
The lib2to3 library doesn't detect/apply any fixes if the source files aren't included with the distribution. See get_all_fix_names at https://github.com/python/cpython/blob/master/Lib/lib2to3/refactor.py#L30

This affects Azure's official Python site extensions [1], which only include bytecode pyc's for the fixes [2].

This results in bad installs when using setuptools to install packages that leverage the use_2to3 flag during the install [3]

[1] https://github.com/Azure/azure-python-siteextensions
[2] https://github.com/Azure/azure-python-siteextensions/issues/14
[3] https://github.com/pypa/setuptools/issues/1120#issuecomment-320769664

**Comment by bitdancer** [comment]
What are you reporting as the bug here?  2to3 obviously can't work without the source, so based just on what you have written here this sounds like an Azure bug.

**Comment by b40b6e41-0162-4214-b8d2-5baa33f3d7ad** [comment]
I'm reporting that lib2to3 doesn't work without having source .py files for the fixes that are packaged with the lib2to3 library. Perhaps the get_all_fix_names method in lib2to3/refactor.py should check for either .py or .pyc files?

The source files are included with the package that I'm installing (anyjson 0.3.3 in this case).

**Comment by bitdancer** [comment]
Ah, I see.  We don't really support .pyc-only distribution, though we try not to break it.

Do you want to propose a fix?

**Comment by zooba** [comment]
It also breaks .zip file distribution, which I'm fairly sure we do explicitly support by virtue of having "python36.zip" in sys.path by default. And the ".pyc-only in a zip file" distribution is \*totally* busted :) (and also officially released for Windows...)

I'm dragging in an importlib expert to the discussion, probably against his will, since this is really a problem of "how do I programmatically discover what I can import without using os.listdir()". Hopefully Brett can answer that question and we can come up with a patch.

**Comment by brettcannon** [comment]
Simplest way is to do https://docs.python.org/3/library/importlib.html#importlib.util.find_spec and see if a spec can be found for the module in question. That will do the search for the module but it won't load it. This does dictate that you know the name of the module upfront, though. If you want more of a "list all modules since I don't know what I want" then you're out of luck until I develop the API (maybe 3.7?).

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
I'm sorry about entering the discussion without knowing any connection between the original problem and Brett's question, but isn't the latter answered by pkgutil.iter_modules (and pkgutil.walk_packages if needed)?

**Comment by brettcannon** [comment]
You're technically right, Verdan, but pkgutils is kind of a hack as it isn't always using standard APIs to achieve its goals, so I personally never recommend using the module unless absolutely necessary and you know exactly how brittle it can be.

**Comment by zooba** [comment]
Perhaps the more important question is whether 2to3 really needs to dynamically generate a list of fixers or if that should have been stopped due to YAGNI. There are only a few modules in the stdlib, and it doesn't seem to support proper namespace packages, so unless there are plans to suddenly add many more we could just make it a hard coded list.
