### ISSUE TITLE
shutil.rmtree fails when target has an internal directory junction (Windows)

### ISSUE THREAD

**Issue by ac44a45e-8ec1-40da-abbb-5c12aadab6df** [python/cpython#75409]
BPO | [31226](https://bugs.python.org/issue31226)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @vidartf
PRs | <li>python/cpython#5998</li>
Files | <li>[mwe.py](https://bugs.python.org/file47090/mwe.py "Uploaded as text/plain at 2017-08-17.13:58:17 by @vidartf"): Minimal working example</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-09-10.15:25:52.052>
created_at = <Date 2017-08-17.13:58:18.663>
labels = ['type-bug', '3.8', '3.9', '3.7', 'library', 'OS-windows']
title = 'shutil.rmtree fails when target has an internal directory junction (Windows)'
updated_at = <Date 2019-09-10.15:25:52.051>
user = 'https://github.com/vidartf'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-10.15:25:52.051>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2019-09-10.15:25:52.052>
closer = 'steve.dower'
components = ['Library (Lib)', 'Windows']
creation = <Date 2017-08-17.13:58:18.663>
creator = 'vidartf'
dependencies = []
files = ['47090']
hgrepos = []
issue_num = 31226
keywords = ['needs review']
message_count = 10.0
messages = ['300424', '300450', '315245', '339856', '348916', '349149', '349241', '349309', '350112', '351701']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'vidartf']
pr_nums = ['5998']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31226'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by ac44a45e-8ec1-40da-abbb-5c12aadab6df** [comment]
On Windows (Windows 10 in my case), given the following directory structure:
- rootfolder
 - a
 - b
  - junc (directory junction to ../a)

a call to `shutil.rmtree('root')` will fail with an exception `FileNotFoundError: [WinError 3]`, in a call to `os.listdir()` in `_rmtree_unsafe`. See attached minimal working example.

Note that sorting order is important: A link in 'a' pointing to 'b' does not fail. This is because `os.listdir()` raises an exception for 'b/junc' when its target ('a') has already been deleted.

Also, note that this is only for junctions, not directory links (`mklink /J` vs `mklink /D`), because:
 - Directory links flag false in the `stat.S_ISDIR(os.lstat('b/junc').st_mode)` test while junctions do not.
 - `os.islink()` returns false for both junctions, while directory links do not.

Indicated Python versions are those which I have personally tested on, and observed this behavior.

Current use case: Deleting a folder tree generated by an external tool, which creates junction links as part of its normal operation ('lerna' tool for the 'npm' javascript package manager).

**Comment by eryksun** [comment]
Junctions are sometimes used as links (e.g. mklink /j) and sometimes as volume mount points (e.g. mountvol.exe). GetVolumePathName can be called to distinguish these cases. If a junction is a volume mount point, then its absolute path and volume path are the same. This test is already used in ntpath.ismount().

For a junction link, islink() should return true, readlink() should work, and S_ISDIR() should return false for the lstat() st_mode. For a junction mount point, islink() should return false, readlink() should not work, and S_ISDIR() should return true for the lstat() st_mode.

A helper function could be added in fileutils.c to determine whether a reparse point is a link, based on the file path and reparse tag. Then modify _Py_attribute_data_to_stat() to take `BOOL is_link` instead of `ULONG reparse_tag`.
