### ISSUE TITLE
Python fails to parse triple quoted (commented out) code

### ISSUE THREAD

**Issue by 375ce0b6-e357-43a2-b190-2827ed46b6e2** [python/cpython#75436]
BPO | [31253](https://bugs.python.org/issue31253)
--- | :---
Nosy | @bitdancer, @vedgar

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-22.08:24:07.972>
created_at = <Date 2017-08-22.07:26:57.081>
labels = ['interpreter-core', 'build', 'invalid']
title = 'Python fails to parse triple quoted (commented out) code'
updated_at = <Date 2017-08-22.13:19:59.400>
user = 'https://bugs.python.org/quamrana'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-22.13:19:59.400>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-22.08:24:07.972>
closer = 'quamrana'
components = ['Interpreter Core']
creation = <Date 2017-08-22.07:26:57.081>
creator = 'quamrana'
dependencies = []
files = []
hgrepos = []
issue_num = 31253
keywords = []
message_count = 5.0
messages = ['300670', '300674', '300675', '300690', '300691']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'veky', 'quamrana']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31253'
versions = ['Python 3.6']
```

</p></details>

**Comment by 375ce0b6-e357-43a2-b190-2827ed46b6e2** [comment]
Python can parse and run this code:

```py
log = list(r'..\Unknown\*.txt')
```



but not this:

'''
log = list(r'..\\Unknown\\*.txt')
'''

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
That's because it is not commented code, it is a multiline string literal. And it is not raw, so \\Un... is just an error, since n is not a valid hexadecimal digit. In the first code, \\Un... is inside a raw string so it is read literally.

There is nothing to fix here. If you really want to continue confusing string literals and comments, you'll have to use r'''...''' to be a bit more general for this case.

**Comment by 375ce0b6-e357-43a2-b190-2827ed46b6e2** [comment]
My lazy way of programming is to piece together lines of code, going round and round commenting and uncommenting sections until I get something that works.

My new lazy way of commenting out larger chunks of code will be:

    r'''
    ... several lines of code here ...
    '''

**Comment by bitdancer** [comment]
Just FYI, Vedran, almost everyone gets this one wrong :)  I too once thought that triple quoted text used as comments was bad style, but in fact I learned they are an accepted way in Python to do multiline comments.  Accepted by Guido, at least: https://sgillies.net/2017/05/30/python-multi-line-comments-and-triple-quoted-strings.html :)  It is not a common practice, though, in my observation, since most code editors support automatically prefixing and unprefixing a block with '#' characters, and highlight such blocks as comments while they do not highlight strings used as comments as comments.

It is an interesting observation that to use it to comment out a block of code one should use the raw string version.  Hopefully the existence of this issue will make that slightly more discoverable.

**Comment by bitdancer** [comment]
And being "accepted" does not change the fact that one needs to be aware of the fact that syntactically they are string literals and not syntactic comments.  Which was your point.
