### ISSUE TITLE
argparse.RawTextHelpFormatter does not maintain lines separated by more than one newline

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#75511]
BPO | [31330](https://bugs.python.org/issue31330)
--- | :---
Nosy | @bitdancer, @anntzer, @elenaoat
PRs | <li>python/cpython#3272</li><li>python/cpython#3428</li><li>python/cpython#3429</li>
Files | <li>[Screen Shot 2017-09-02 at 10.45.48.png](https://bugs.python.org/file47117/Screen%20Shot%202017-09-02%20at%2010.45.48.png "Uploaded as image/png at 2017-09-02.07:46:15 by @elenaoat")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-07.23:18:33.574>
created_at = <Date 2017-09-02.03:19:37.683>
labels = ['3.7', 'library']
title = 'argparse.RawTextHelpFormatter does not maintain lines separated by more than one newline'
updated_at = <Date 2017-09-07.23:18:33.573>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-07.23:18:33.573>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-07.23:18:33.574>
closer = 'r.david.murray'
components = ['Library (Lib)']
creation = <Date 2017-09-02.03:19:37.683>
creator = 'Antony.Lee'
dependencies = []
files = ['47117']
hgrepos = []
issue_num = 31330
keywords = ['patch']
message_count = 10.0
messages = ['301158', '301161', '301162', '301163', '301164', '301465', '301623', '301624', '301638', '301640']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'paul.j3', 'Antony.Lee', 'Elena.Oat']
pr_nums = ['3272', '3428', '3429']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31330'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 379dc349-3a10-424f-b9d2-a0104f092359** [comment]
The doc for argparse.RawTextHelpFormatter states that it "maintains whitespace for all sorts of help text, including argument descriptions."  But the following example (which outputs "Foo", "Bar", and "Baz", each separated by exactly one empty line) shows that paragraphs separated by more than one empty line will only be separated in the output text by a single empty line.


```py
import argparse
parser = argparse.ArgumentParser(
    prog='PROG',
    formatter_class=argparse.RawTextHelpFormatter,
    description='''\
Foo
```


Bar


Baz''')
parser.print_help()

**Comment by a1c683f7-b296-4095-93bb-30a5158fd67e** [comment]
It maintains \*whitespace*, not the new lines. 
I've tested this using whitespaces and I think it keeps them according to the original description. See the image attached.

**Comment by bitdancer** [comment]
If that is the intended definition of "whitespace" in this context (I have no opinion on that so far), then the docs need amplification, because in general "whitespace" includes newlines.  On the other hand, this might be considered a bug in the code and not the docs.  However, changing it has backward compatibility implications, so we might go for a doc fix regardless.

**Comment by 7a064fe6-c535-4d80-a11f-a04ed39056c5** [comment]
I've seen this before, either in another bug/issue or a Stackoverflow question.

The basic change in RawTextHelpFormatter is to turn off the line wrapping for texts like the description.  Multiple newlines are preserved at this step.

But after assembling all the pieces (usage, description, help, epilog) the formatter strips out duplicate newlines.  This is needed because the process of assembly freely inserts newlines between the pieces, regardless of whether they are blank or not.  It can't, or at least doesn't try to, distinguish between newlines within a block like the description, and newlines between blocks.

If someone could come up with a simple patch, great.  Or a simple change to the doc wording.  But I don't think this issue merits a larger fix.

**Comment by 7a064fe6-c535-4d80-a11f-a04ed39056c5** [comment]
http://bugs.python.org/issue17113
argparse.RawDescriptionHelpFormatter should not delete blank lines

This provides more details on why this is happening.

I suggest using adding a space between newlines, thus: '\\n \\n'.  HelpFormatter.format_help is just looking for '\\n\\n'.

**Comment by a1c683f7-b296-4095-93bb-30a5158fd67e** [comment]
I've created a pull request. Could someone review it please?

**Comment by bitdancer** [comment]
New changeset 397c467c49385023de36411194d381ac993bae1a by R. David Murray (Elena Oat) in branch 'master':
bpo-31330: Clarify that RawTextHelpFormatter collapses repeated newlines. (bpo-3272)
https://github.com/python/cpython/commit/397c467c49385023de36411194d381ac993bae1a

**Comment by bitdancer** [comment]
Thanks, Elena.

**Comment by bitdancer** [comment]
New changeset 82cae7c5be4175e2173e4d342825b5315a9d612a by R. David Murray (Miss Islington (bot)) in branch '2.7':
[2.7] bpo-31330: Clarify that RawTextHelpFormatter collapses repeated newlines. (GH-3272) (GH-3428)
https://github.com/python/cpython/commit/82cae7c5be4175e2173e4d342825b5315a9d612a

**Comment by bitdancer** [comment]
New changeset e89b35dd2b87e85978b91e3e2dbdea1fc76d6be4 by R. David Murray (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31330: Clarify that RawTextHelpFormatter collapses repeated newlines. (GH-3272) (GH-3429)
https://github.com/python/cpython/commit/e89b35dd2b87e85978b91e3e2dbdea1fc76d6be4
