### ISSUE TITLE
Use the enumerate function where appropriate

### ISSUE THREAD

**Issue by 319d7274-4c67-4fda-b01a-e2c8ec72a32a** [python/cpython#75598]
BPO | [31417](https://bugs.python.org/issue31417)
--- | :---
Nosy | @rhettinger, @vstinner, @bitdancer, @serhiy-storchaka, @vedgar, @mbyrnepr2
PRs | <li>python/cpython#3497</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-12.17:27:53.626>
created_at = <Date 2017-09-11.10:43:46.455>
labels = ['invalid', 'type-bug', '3.7']
title = 'Use the enumerate function where appropriate'
updated_at = <Date 2017-09-12.17:27:53.625>
user = 'https://github.com/mbyrnepr2'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-12.17:27:53.625>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-12.17:27:53.626>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-09-11.10:43:46.455>
creator = 'Mark Byrne'
dependencies = []
files = []
hgrepos = []
issue_num = 31417
keywords = ['patch']
message_count = 8.0
messages = ['301871', '301879', '301880', '301894', '301905', '301921', '301934', '301937']
nosy_count = 6.0
nosy_names = ['rhettinger', 'vstinner', 'r.david.murray', 'serhiy.storchaka', 'veky', 'Mark Byrne']
pr_nums = ['3497']
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31417'
versions = ['Python 3.7']
```

</p></details>

**Comment by 319d7274-4c67-4fda-b01a-e2c8ec72a32a** [comment]
To make code explicit and more readable

Use the enumerate function to replace occurrences of the pattern:

```py
for i in range(len(sources)):
    src = sources[i]
```

**Comment by bitdancer** [comment]
Thanks for wanting to improve Python, but we don't usually accept refactoring requests like this.  We "fix" such issues when the code is touched for other reasons.  We'll see what other developers think, though.

**Comment by vstinner** [comment]
> Thanks for wanting to improve Python, but we don't usually accept refactoring requests like this.  We "fix" such issues when the code is touched for other reasons.  We'll see what other developers think, though.

The standard library is used by some developers are the reference style for best practices. So it makes sense to "upgrade" to code to use enumarate(). I read the short change, enumerate() usage is appropriate.

**Comment by bitdancer** [comment]
Anyone who uses stdlib code as examples of best practice doesn't understand the history of stdlib code.

Generally, we consider the danger of introducing bugs to be more significant than the benefit of the "cleanup" changes.  The fact that you are discussing further changes to the code in the PR make this more likely.

**Comment by serhiy-storchaka** [comment]
I concur with David in general. And as you can see there are questions to the concrete patch.

**Comment by 319d7274-4c67-4fda-b01a-e2c8ec72a32a** [comment]
Generally, we consider the danger of introducing bugs to be more significant than the benefit of the "cleanup" changes.  The fact that you are discussing further changes to the code in the PR make this more likely.

I haven't updated the PR with further code changes as suggested in the PR comments because the comments don't strictly relate to the changes put forward in this issue, and I don't want to go beyond the scope of the issue - the requested changes could go in a separate PR as needed.

The motivation is to use enumerate where it is a natural fit.
If you decide not to merge, then that is ok; let me know if I can help with anything.

**Comment by bitdancer** [comment]
Mark: Yeah, I think my comment was directed more to haypo than you :)

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
Sorry, this seems like a classical example of "When all you have is a hammer, everything looks like a nail. Then, when you learn of a screwdriver, you suddenly see half of these nails as screws, completely ignoring there are other tools besides those two."

In fact, enumerate is \_not_ the good choice in most of those cases, as the comments show. One should use zip, another should use ordinary iteration because the index isn't needed at all, and yet another should probably stay as it is, since that way it's more obvious that we're transforming each item in place. [When LHS is consts[i] and right is const, it's not easy to see they refer to the same place.]

Even the fourth I would argue is more readable in the current form, for a similar reason: when you base the decision on words[i], and the decision is to del words[i:], it's obvious you delete "it and everything after". Not so much in the "refactored" code.

Please don't do such things. One of Python's great strengths, especially in stdlib, is code stability. The only reason we're able to get anything done is that we have (or at least used to have) a great policy referred to in https://bugs.python.org/issue31417#msg301879, so we don't lose ourselves in enormous bikeshedding about how to best use the enormous expressivity of Python to write the code that works perfectly fine in some slightly different way.
