### ISSUE TITLE
Bug in argparse - not supporting utf8

### ISSUE THREAD

**Issue by ba593c8e-8d78-4602-8404-cbe53bdd8f43** [python/cpython#75656]
BPO | [31475](https://bugs.python.org/issue31475)
--- | :---
Nosy | @bitdancer, @methane, @MojoVampire, @Ali-Razmjoo
PRs | <li>python/cpython#3577</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-30.13:38:44.987>
created_at = <Date 2017-09-14.17:48:43.467>
labels = ['build']
title = 'Bug in argparse - not supporting utf8'
updated_at = <Date 2017-09-30.13:38:44.987>
user = 'https://github.com/Ali-Razmjoo'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-30.13:38:44.987>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-30.13:38:44.987>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-09-14.17:48:43.467>
creator = 'Ali Razmjoo'
dependencies = []
files = []
hgrepos = []
issue_num = 31475
keywords = []
message_count = 7.0
messages = ['302190', '302191', '302192', '302379', '302910', '302964', '303407']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'methane', 'josh.r', 'Ali Razmjoo']
pr_nums = ['3577']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31475'
versions = []
```

</p></details>

**Comment by ba593c8e-8d78-4602-8404-cbe53bdd8f43** [comment]
Regarding bpo-3468 discussion, there is the same bug was in argparse (and optparse) which fixed in this PR. utf8 is not supported in argprase module

bpo-3478: https://github.com/python/cpython/pull/3577
current pr: https://github.com/python/cpython/pull/3577

Regards.

**Comment by bitdancer** [comment]
As I requested in the PR, please provide a way to reproduce the bug you are reporting.

**Comment by bitdancer** [comment]
Note that as far as I know without a reproducer, it is confusing to me to talk about argparse supporting or not supporting utf8.  It deals only with text strings, which are unicode.  Or is this a 2.7 only bug report?  (Although even there it would be a question of unicode support, not utf8).

**Comment by methane** [comment]
You reported stack trace on Github pull request.
But discussion should be made here, not in pull request.

As far as reading traceback, your problem is solved already in Python 3.6, by PEP-528.

**Comment by methane** [comment]
ping?
May I close this issue and pull request?

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
Based on the OP's patch, it looks like they have a problem where they have non-ASCII text in their output strings (either due to using non-ASCII switches, or using non-ASCII help documentation), but sys.stdout/sys.stderr are configured for some encoding that doesn't support said characters, so they're getting exceptions when the help message is sent to the screen automatically (e.g. by running with --help).

It's only sort of a bug in Python: Fundamentally, the problem is a script that assumes arbitrary Unicode support being run under a locale that doesn't provide it. The solution provided is bad though: It shouldn't be trying to force UTF8 output regardless of locale.

A simple repro, at least on Linux-like systems, would be to run Python with LANG=C (and no other LC variables set), then do:

```py
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('-f', help=chr(233)) # help is 'é'
    parser.print_help()
```


While the patch as given is wrong (with the exception of Windows weirdness, blithely ignoring/second-guessing the locale is a terrible idea), it's not a terrible idea to fix this in some way; if nothing else, it might make sense to have some fallback approach when the exception is raised (e.g. encoding the output with errors='ignore' or the like) so running scriptname.py --help at least provides \*some* output even with incompatible locales, rather than dying with an error in the help message handling code itself.

**Comment by methane** [comment]
We already accept PEP-529 and PEP-538.
And there are bpo-15216 ([PR 2343](https://github.com/python/cpython/pull/2343)).
So I don't think we need more solutions.
