### ISSUE TITLE
IDLE: Tiny font on HiDPI display

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75681]
BPO | [31500](https://bugs.python.org/issue31500)
--- | :---
Nosy | @terryjreedy, @taleinat, @ned-deily, @serhiy-storchaka, @mlouielu, @csabella
PRs | <li>python/cpython#3639</li><li>python/cpython#3664</li><li>python/cpython#3665</li><li>python/cpython#3686</li><li>python/cpython#6585</li><li>python/cpython#10015</li>
Files | <li>[Screenshot_20170917_213616.png](https://bugs.python.org/file47141/Screenshot_20170917_213616.png "Uploaded as image/png at 2017-09-17.18:54:06 by @serhiy-storchaka")</li><li>[configdialogkeys_old.png](https://bugs.python.org/file47148/configdialogkeys_old.png "Uploaded as image/png at 2017-09-18.16:20:49 by @csabella")</li><li>[configdialogkeys_new.png](https://bugs.python.org/file47149/configdialogkeys_new.png "Uploaded as image/png at 2017-09-18.16:22:45 by @csabella")</li><li>[configkey_2.png](https://bugs.python.org/file47155/configkey_2.png "Uploaded as image/png at 2017-09-20.00:32:19 by @csabella")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2018-10-20.23:35:31.284>
created_at = <Date 2017-09-17.18:54:06.429>
labels = ['expert-IDLE', 'type-bug']
title = 'IDLE: Tiny font on HiDPI display'
updated_at = <Date 2018-10-21.09:05:30.847>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-10-21.09:05:30.847>
actor = 'taleinat'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2018-10-20.23:35:31.284>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-09-17.18:54:06.429>
creator = 'serhiy.storchaka'
dependencies = []
files = ['47141', '47148', '47149', '47155']
hgrepos = []
issue_num = 31500
keywords = ['patch']
message_count = 32.0
messages = ['302381', '302417', '302463', '302464', '302471', '302477', '302509', '302563', '302566', '302572', '302573', '302574', '302579', '302580', '302595', '302605', '302607', '302640', '302672', '302695', '313199', '313204', '313206', '315664', '315666', '316455', '316485', '316506', '316574', '328177', '328182', '328200']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'taleinat', 'ned.deily', 'serhiy.storchaka', 'louielu', 'cheryl.sabella']
pr_nums = ['3639', '3664', '3665', '3686', '6585', '10015']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31500'
versions = ['Python 2.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
My new laptop has a HiDPI display (3840x2160). IDLE (as well as other Tk applications) looks ugly on it. The font of menu and dialogs is tiny. The font used in editor and shell looks normal size. I use Linux with X Window.

It seems to me this issue doesn't have solution. Related links:

https://wiki.tcl.tk/41949
https://core.tcl.tk/tk/tktview/0917069c05e9c354a27c8105a7a22264090b9274
https://stackoverflow.com/questions/34132203/scaling-of-tkinter-gui-in-4k-38402160-resolution

**Comment by serhiy-storchaka** [comment]
[PR 3639](https://github.com/python/cpython/pull/3639) adapts the receipt from [1]. I'm not sure that it doesn't add regressions on low-DPI displays.

[1] https://wiki.tcl.tk/8488

**Comment by terryjreedy** [comment]
The TkFixedFont initially used in Shell and editor has its size set to 10 if initially negative. Users can only replace this with a real font, not another of tk's abstract fonts.

On windows, the sizes of the nearly 20 fonts touched by the patch range from 8 to 12.  So no possible regression there.  If the sizes on Linux were in the range -8 to -12, then the effect is to replace the size with numbers around 10 instead of exactly 10 (as IDLE currently does).  But from what you said on the patch, the negative numbers are not exactly the negative of their real size, but are tuned for positioning.

Cheryy, Louie, and Ned: the patch needs to be test on multiple \*nix machines, especially on OSX, to make sure it does not mess up on standard monitors.  A quick 'git [pr 3639](https://github.com/python/cpython/pull/3639)' and 'python -m test.test_idle' would be helpful.

**Comment by csabella** [comment]
Tests run on Ubuntu.  The menubar is bigger now though, so it's default is
different than before.  Maybe that was the only way to fix it, but it's now
about twice as big as the shell font.

**Comment by csabella** [comment]
Attached screen prints of configdialog.  It's messed up.

**Comment by terryjreedy** [comment]
Thank you Cheryl.  That is enough to reject the patch is it is now.

The negative sizes are pixels.  I think it might be better to multiply them by a systems specific factor, but only when needed.

One might wish that the scaling should be handled automatically, in tkinter if not in tk itself.  But it was mentioned in one of the links that displays do not always report their dpi correctly.

One possibility is a tkinter calibration app that displays a 500 or 1000 pixel line (user selects) and asks the user to input the physical length (centimeters or inches).  (Some games do something similar with brightness.)

To check whether a tkinter scaling app could be used, I sized Serhiy's image so that the sample font in the Settings Font tab matched the sample font in a real box.  The system font around it is tiny but readable, especially with a magnifier.

This is a tkinter issue, not only an IDLE issue, but IDLE is a good test app, with realistically complex dialogs. Lacking a Python-wide fix, something could be added to the Font tab -- for instance a dpi multiplier that defaults to one.  It would only be used if not 1.0.

I reread config.IdleConf.GetFont.  Rather than manipulate one of tk's default fonts ('TkFixedFont'), it creates a normal font sized in points.  It uses 'TkFixedFont' as a handy key for finding a system-specific sure-to-exist fixed pitch font: "actualFont = Font.actual(f)", where f is a TkFixedFont instance.  Thus it does not affect the dialogs.

It would be helpful to know if HiDPI screens on Windows have a problem.

bpo-31496 is about test_configdialog failing on the same HiDPI screen.

**Comment by serhiy-storchaka** [comment]
The Keys and General tabs are messed up even more on my computer. Some sections are just not visible. This is because The dialog window uses hardcoded size in pixels, it is too small for all content. After removing the hardcoded size all looks good.

**Comment by terryjreedy** [comment]
Cheryl, what do you get with

```py
import tkinter as tk
root = tk.Tk()
print(float(root.tk.call('tk', 'scaling')))
```


If it is less than 1.2, then Serhiy's revised patch should leave config dialog as it should be.

**Comment by terryjreedy** [comment]
New changeset d6e2f26f3f7c62a4ddbf668027d3ba27cb0e1eca by Terry Jan Reedy in branch 'master':
bpo-31500: Removed fixed size of IDLE config dialog. (bpo-3664)
https://github.com/python/cpython/commit/d6e2f26f3f7c62a4ddbf668027d3ba27cb0e1eca

**Comment by terryjreedy** [comment]
New changeset 97be14996b247b853ead77fb255d7029e3cf3dc9 by Terry Jan Reedy (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31500: Removed fixed size of IDLE config dialog. (GH-3664) (bpo-3665)
https://github.com/python/cpython/commit/97be14996b247b853ead77fb255d7029e3cf3dc9

**Comment by csabella** [comment]
```pycon
>>> import tkinter as tk
>>> root = tk.Tk()
>>> print(float(root.tk.call('tk', 'scaling')))
1.3333333333333333
```

**Comment by csabella** [comment]
configdialog looks better now, but the fonts are still huge.  The configdialog is almost bigger than the shell when it opens.

**Comment by terryjreedy** [comment]
It appears that the cutoff of 1.2 in the patch is too low.  Try raising it to 1.4 and you should see the dialog normal.

**Comment by terryjreedy** [comment]
I mean '  if scaling \>= 1.2:' in run.fix_scaling.  It would also be interesting to instead replace the last line,  "font['size'] = -size" with "font['size'] = 9" (or 8 or 10) and see how close the dialog is to what is was before.

**Comment by serhiy-storchaka** [comment]
If just negate the size the menu and the dialog fonts look like on a display with 72 DPI. But currently monitors rarely have such DPI. Normal displays have about 100 DPI (scaling factor about 1.33). If we want to keep font sizes on such displays we should multiply sizes by 0.75 for converting from pixels to points.

**Comment by terryjreedy** [comment]
My screen is 23.5 x 13.25, making it 109 DPI.  I asked Cheryl to try 9 first because it is 3/4 of 12.

**Comment by csabella** [comment]
The scaling factor of 1.4 worked and the menu and configdialog looked normal.

font['size'] = 9 also worked as did font['size'] = 10.  font['size'] = 12 is when it's too big.

**Comment by serhiy-storchaka** [comment]
The limit 1.4 is not arbitrary. This is a minimal scale for which fonts from 10 to 14 pixels are not decreased when converted to points (with multiplier 0.75 and one rounding). round(14 * 0.75) = round(10.5) = 10; 10 * 1.4 = 14.

**Comment by serhiy-storchaka** [comment]
New changeset a96c96f5dab68d4e611af4b8caefd7268533fd9a by Serhiy Storchaka in branch 'master':
bpo-31500: IDLE: Scale default fonts on HiDPI displays. (bpo-3639)
https://github.com/python/cpython/commit/a96c96f5dab68d4e611af4b8caefd7268533fd9a

**Comment by terryjreedy** [comment]
New changeset 0c4997f1919d8583353b12537a63dcbe7b9d280f by Terry Jan Reedy in branch '3.6':
[3.6] bpo-31500: IDLE: Scale default fonts on HiDPI displays. (GH-3639) (bpo-3686)
https://github.com/python/cpython/commit/0c4997f1919d8583353b12537a63dcbe7b9d280f
