### ISSUE TITLE
There is a problem with the setdefault type conversion in the tuple

### ISSUE THREAD

**Issue by 52c22a23-aae1-4ceb-9e57-a134913dc791** [python/cpython#75695]
BPO | [31514](https://bugs.python.org/issue31514)
--- | :---
Nosy | @pfmoore, @tjguk, @stevendaprano, @zware, @zooba
Files | <li>[demo.py](https://bugs.python.org/file47151/demo.py "Uploaded as text/plain at 2017-09-19.03:11:32 by sk xing")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-19.06:05:32.982>
created_at = <Date 2017-09-19.03:11:33.000>
labels = ['OS-windows']
title = 'There is a problem with the setdefault type conversion in the tuple'
updated_at = <Date 2017-09-19.06:05:32.970>
user = 'https://bugs.python.org/skxing'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-19.06:05:32.970>
actor = 'steven.daprano'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-19.06:05:32.982>
closer = 'steven.daprano'
components = ['Windows']
creation = <Date 2017-09-19.03:11:33.000>
creator = 'sk xing'
dependencies = []
files = ['47151']
hgrepos = []
issue_num = 31514
keywords = []
message_count = 2.0
messages = ['302497', '302504']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'steven.daprano', 'zach.ware', 'steve.dower', 'sk xing']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31514'
versions = ['Python 3.6']
```

</p></details>

**Comment by 52c22a23-aae1-4ceb-9e57-a134913dc791** [comment]
The setdefault method of the tuple allows the introduction of custom data types.At this point, the \_\_repr__ method is implemented so that the returned data type has an error.The type of str is returned, but the int type is written to the tuple.Also, write str without quotation marks.
Look at the demo.py in the attachment

**Comment by stevendaprano** [comment]
The demo code you give seems to be working perfectly correctly. I don't think anything here is a bug.

(1) You are working with a dict, not a tuple.

(2) The potint.\_\_repr__ method does NOT have a bug.

(3) de['four'] is NOT an int, it is a potint object, just as you set. It only looks like an int when you print it because that's what the \_\_repr__ does.

To see what the object really is, call:

```py
type(de['four'])
```


and you will see it is a potint.


And I have no idea what you think is wrong with string without quotation marks, it works correctly in the demo.


I'm going to close this bug report as Works For Me. If you disagree, please re-open it with more information.
