### ISSUE TITLE
Add non-elevated symlink support for dev mode Windows 10

### ISSUE THREAD

**Issue by ac44a45e-8ec1-40da-abbb-5c12aadab6df** [python/cpython#75693]
BPO | [31512](https://bugs.python.org/issue31512)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @vidartf, @izbyshev
PRs | <li>python/cpython#3652</li>
Files | <li>[devsymlink.patch](https://bugs.python.org/file47150/devsymlink.patch "Uploaded as text/plain at 2017-09-18.19:16:30 by @vidartf"): Proof of concept patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-04-09.18:20:25.430>
created_at = <Date 2017-09-18.19:16:30.694>
labels = ['3.8', 'type-feature', 'library', 'OS-windows']
title = 'Add non-elevated symlink support for dev mode Windows 10'
updated_at = <Date 2019-04-09.18:20:25.429>
user = 'https://github.com/vidartf'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-09.18:20:25.429>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2019-04-09.18:20:25.430>
closer = 'steve.dower'
components = ['Library (Lib)', 'Windows']
creation = <Date 2017-09-18.19:16:30.694>
creator = 'vidartf'
dependencies = []
files = ['47150']
hgrepos = []
issue_num = 31512
keywords = ['patch']
message_count = 9.0
messages = ['302482', '302494', '302673', '330307', '330349', '330538', '339696', '339800', '339801']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'vidartf', 'izbyshev']
pr_nums = ['3652']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31512'
versions = ['Python 3.8']
```

</p></details>

**Comment by ac44a45e-8ec1-40da-abbb-5c12aadab6df** [comment]
As explained in this Microsoft blogpost (https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/), it is possible on newer versions of Windows 10 for non-privileged users to create symlinks when the machine is in developer mode. However, to ensure backwards compatibility, this behavior requires a flag to be passed to the CreateSymbolicLink function.

I think this is something that Python can benefit from having. It would go from "symlinks on Windows rarely work" to "symlinks on Windows work in developer mode (and rarely otherwise)".

I've attached a proof of concept patch to enable this behavior (a Windows 10 machine with the 'Creators Update' is required to test it). In summary, it enables the flag by default, and updates enable_symlink to prevent lacking privilege from disabling symlinks on machines in developer mode.

**Comment by eryksun** [comment]
Py_CreateSymbolicLinkW can be removed in 3.5+ because Windows XP is no longer supported and calling enable_symlink() is pointless. 

The Windows API uses some privileges simply to determine which security principals can access a capability. Whether the privilege is currently enabled or disabled in the current access token doesn't matter because functions automatically enable it for the current thread (in an impersonation token). 

In this case, CreateSymbolicLink calls RtlAcquirePrivilege to enable SeCreateSymbolicLinkPrivilege for the current thread; sets the symlink reparse point; and then reverts the current thread via RtlReleasePrivilege. It goes through these same steps whether or not the privilege is already enabled in the process, so there's no chance of a race condition between competing threads.

Also, as a side note, the linked blog makes the following claim, which paints an incomplete picture:

> However, for Windows users, due to Windows Vista’s security 
> requirements, users needed local admin rights and, importantly, 
> had to run mklink in a command-line console elevated as 
> administrator to create/modify symlinks. 

SeCreateSymbolicLinkPrivilege can be added to a standard user account, and it doesn't get filtered out from the user's token. So in general you do not need administrator access. However, the above is describing the case for most developers, who use a administrator account that's subject to UAC restrictions.

**Comment by ac44a45e-8ec1-40da-abbb-5c12aadab6df** [comment]
Thanks for the informative comments. I opened a PR based on this feedback. Would you mind checking if it conforms to what you had in mind?
