### ISSUE TITLE
Links for French documentation PDF is broken: LaTeX issue with non-ASCII characters?

### ISSUE THREAD

**Issue by 40756da2-effb-4379-abff-defe2817f76c** [python/cpython#75770]
BPO | [31589](https://bugs.python.org/issue31589)
--- | :---
Nosy | @vstinner, @benjaminp, @ned-deily, @ezio-melotti, @JulienPalard, @Linkid, @jfbu, @miss-islington
PRs | <li>python/cpython#3940</li><li>python/cpython#4069</li><li>python/cpython#4683</li><li>python/cpython#16636</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-05-07.20:08:39.378>
created_at = <Date 2017-09-26.08:59:09.198>
labels = ['type-bug', 'docs']
title = 'Links for French documentation PDF is broken: LaTeX issue with non-ASCII characters?'
updated_at = <Date 2019-10-08.03:42:55.283>
user = 'https://bugs.python.org/fabrice'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-08.03:42:55.283>
actor = 'miss-islington'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-05-07.20:08:39.378>
closer = 'mdk'
components = ['Documentation']
creation = <Date 2017-09-26.08:59:09.198>
creator = 'fabrice'
dependencies = []
files = []
hgrepos = []
issue_num = 31589
keywords = ['patch']
message_count = 25.0
messages = ['303024', '303028', '303498', '303501', '303502', '303503', '303562', '303586', '303587', '303590', '303592', '304016', '304499', '304717', '307469', '307472', '307490', '307493', '307502', '307506', '307507', '307515', '341810', '341838', '354162']
nosy_count = 10.0
nosy_names = ['vstinner', 'benjamin.peterson', 'ned.deily', 'ezio.melotti', 'docs@python', 'mdk', 'linkid', 'fabrice', 'jfbu', 'miss-islington']
pr_nums = ['3940', '4069', '4683', '16636']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31589'
versions = ['Python 2.7']
```

</p></details>

**Comment by 40756da2-effb-4379-abff-defe2817f76c** [comment]
Hi,

In this page : https://docs.python.org/fr/2/download.html, all the documentation links aren't  available, for example : 

- https://docs.python.org/fr/2/archives/python-2.7.14-docs-pdf-a4.zip
- https://docs.python.org/fr/2/archives/python-2.7.14-docs-pdf-a4.tar.bz2

So, I can't read the documentation in French :)

Regards,
Fabrice

**Comment by JulienPalard** [comment]
Hi Fabrice,

Thanks for reporting.

The whole archives/ directory is completly missing for french and japanese, I'll take a look.

Bug is probably really near https://github.com/python/docsbuild-scripts/blob/master/build_docs.py#L222

**Comment by JulienPalard** [comment]
Problem happen during pdflatex, I tried a local build and got: 

! Package hyperref Error: Wrong DVI mode driver option \`dvipdfmx',
(hyperref)                because pdfTeX or LuaTeX is running in PDF mode.

See the hyperref package documentation for explanation.
Type  H \<return\>  for immediate help.
 ...                                              
                                                  
l.4362 \\ProcessKeyvalOptions{Hyp}
                                 
? 
! Emergency stop.

**Comment by ezio-melotti** [comment]
FWIW most of the errors I met while trying to build the pdfs of the main docs were caused by the presence of non-latin1 characters.  French should be limited to the latin1 range and the error you pasted doesn't seem to be related, however that might explain while the Japanese docs are also missing (unless this issue got fixed in the meanwhile -- I haven't built the pdfs in a while).

**Comment by JulienPalard** [comment]
After an upgrade of my venv, the error is now:

Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'faq.aux'
      'faq.out'
      'faq.toc'
Latexmk: Maximum runs of pdflatex reached without getting stable files
Latexmk: All targets (faq.pdf) are up-to-date
Latexmk: Did not finish processing file 'faq.tex':
   'pdflatex' needed too many passes

**Comment by JulienPalard** [comment]
One difference I see in the logs of sucessfully building the faq.tex and failing to build it is:

   Package hyperref Warning: Token not allowed in a PDF string (Unicode):

Looks like if I remove all non-ascii characters from titles, it builds again.

**Comment by JulienPalard** [comment]
Problem looks like the utf8x package is not friend with tableofcontent:

- https://tex.stackexchange.com/questions/240801/utf8x-character-fails-in-the-table-of-contents-every-second-time-i-compile
- https://tex.stackexchange.com/questions/164458/pleaseinsertintopreamble-in-toc-and-header

**Comment by JulienPalard** [comment]
For the record, I can reproduce the issue with this minimal test file:

mdk@windhowl$ ls -lah
total 108K
drwxr-xr-x  2 mdk  mdk  4.0K Oct  2 21:15 .
drwxrwxrwt 18 root root  96K Oct  2 21:15 ..
-rw-r--r--  1 mdk  mdk   196 Oct  2 21:13 faq.tex

mdk@windhowl$ cat faq.tex 
\\documentclass[a4,10pt,french]{report}

\\usepackage[utf8x]{inputenc}
\\usepackage[T1,T2A]{fontenc}
\\usepackage{babel}

\\begin{document}
\\tableofcontents
\\chapter{FAQ sur Python éh}
\\end{document}

mdk@windhowl$ latexmk faq 2\>&1 | tail -n 15
(/usr/share/texlive/texmf-dist/tex/latex/ucs/data/uni-0.def) [2] (./faq.aux) )
Output written on faq.dvi (2 pages, 608 bytes).
Transcript written on faq.log.
Latexmk: Log file says output to 'faq.dvi'
Rule 'latex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'faq.aux'
      'faq.toc'
Latexmk: Maximum runs of latex reached without getting stable files
Latexmk: Did not finish processing file 'faq':
   'latex' needed too many passes
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Latexmk: applying rule 'latex'...
Latexmk: All targets (faq.dvi) are up-to-date


Also, according to matrixise, it works with xelatex.

**Comment by vstinner** [comment]
Julien: Is there any reason why you want to use utf8x in specific?

https://tex.stackexchange.com/questions/13067/utf8x-vs-utf8-inputenc

"""
utf8x vs. utf8 (inputenc)
(...)
The simple answer is that utf8x is to be avoided if possible. It loads the ucs package, which for a long time was unmaintained (although there is now a new maintainer) and breaks various other things.
"""

**Comment by JulienPalard** [comment]
I personally do not care about using utf8x, it has been introduced in:

  r74549 | benjamin.peterson | 2009-08-24 12:42:36 -0500 (Mon, 24 Aug 2009) | 1 line
  fix pdf building by teaching latex the right encoding package

```py
  # Get LaTeX to handle Unicode correctly
  latex_elements = {'inputenc': r'\usepackage[utf8x]{inputenc}'}
```


I tried with utf8 instead and it yielded a different set of errors, so I did not tried much. But utf8-induced bugs may be easier to fix that utf8x-induced bugs, I don't know.

**Comment by vstinner** [comment]
(Oh sorry, I misunderstand what you wrote. I understood that Python didn't use utf8x yet and you proposed to start using it.)

**Comment by JulienPalard** [comment]
Today I tried without utf8x and an up-to-date version of texlive, errors looked less mystical, so I was able to open a readable / easy to reproduce issue:

https://github.com/sphinx-doc/sphinx/issues/4136

I then followed the idea of trying xetex and I was able to build english and french PDF (still not had time to try japanese).

**Comment by JulienPalard** [comment]
Finally have a combination of latex engines that work for every cases, did a PR on docsbuild-scripts:

https://github.com/python/docsbuild-scripts/pull/34/

I already pulled xelatex on docs.iad1.psf.io via https://github.com/python/psf-salt/commit/989a7715c4a452b5af13baf9a33535bab0af822b#diff-6fb01fe8bbc22a54d234a57ad58e291e

Also opened a few related issue sphinx-doc side to track my thoughts:

- https://github.com/sphinx-doc/sphinx/issues/4150 (Ask if there is a better way to set the latex engine than giving it from docsbuild-scripts)
- https://github.com/sphinx-doc/sphinx/issues/4159 (Choose unicode-enabled default latex engines)
- https://github.com/sphinx-doc/sphinx/issues/4149 (Be more explicit on documentation about how to choose a latex engine)

**Comment by 66e64654-c57d-4f99-8d9a-b2fbbf25f848** [comment]
I have made a PR at https://github.com/python/cpython/pull/4069 which enhances `conf.py` with some pdflatex extra Unicode configuration. I tested it with building PDF English documentation at master (at https://github.com/python/cpython/tree/db60a5bfa5d5f7a6f1538cc1fe76f0fda57b524e) and at 3.6 branch (at https://github.com/python/cpython/tree/1e78ed6825701029aa45a68f9e62dd3bb8d4e928) and also French documentation at 3.6 (at https://github.com/python/python-docs-fr/commit/76b522b79c3caa26658920c714acf8fac0c20eeb). The changes are only for ``pdflatex`` builds: if `latex_engine` is set to `xelatex`, `lualatex`, or `platex` (automatic if language is `ja`), nothing is modified.
