### ISSUE TITLE
Build MSI installer for 3.4 security releases on Windows

### ISSUE THREAD

**Issue by eb193824-a002-4e53-a73b-be75738ef3f2** [python/cpython#75804]
BPO | [31623](https://bugs.python.org/issue31623)
--- | :---
Nosy | @terryjreedy, @pfmoore, @larryhastings, @tjguk, @bitdancer, @zware, @zooba, @native-api
Files | <li>[0001-Support-making-MSI-installer-from-tarball.patch](https://bugs.python.org/file47176/0001-Support-making-MSI-installer-from-tarball.patch "Uploaded as text/plain at 2017-09-29.01:42:19 by @native-api"): patch against 3.4</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-07-09.13:44:30.149>
created_at = <Date 2017-09-29.01:01:16.890>
labels = ['type-feature', 'OS-windows', 'build']
title = 'Build MSI installer for 3.4 security releases on Windows'
updated_at = <Date 2018-07-09.13:44:30.147>
user = 'https://github.com/native-api'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-09.13:44:30.147>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2018-07-09.13:44:30.149>
closer = 'terry.reedy'
components = ['Build', 'Windows']
creation = <Date 2017-09-29.01:01:16.890>
creator = 'Ivan.Pozdeev'
dependencies = []
files = ['47176']
hgrepos = []
issue_num = 31623
keywords = ['patch']
message_count = 9.0
messages = ['303292', '303294', '303295', '303354', '303649', '303708', '303709', '321295', '321317']
nosy_count = 9.0
nosy_names = ['terry.reedy', 'paul.moore', 'larry', 'tim.golden', 'r.david.murray', '__Vano', 'zach.ware', 'steve.dower', 'Ivan.Pozdeev']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31623'
versions = ['Python 3.4']
```

</p></details>

**Comment by eb193824-a002-4e53-a73b-be75738ef3f2** [comment]
Since the last version of 3.4 is only made available as a source tarball, it's imperative to be able to make a distributable package locally from it. [Tools/msi/msi.py](https://github.com/python/cpython/blob/main/Tools/msi/msi.py) only works from an \`hg' checkout.

**Comment by bitdancer** [comment]
Assuming 3.4 is packagable using msi and hg is the only problem, I presume you could use an hg-git adapter to get an hg checkout to build from.

**Comment by eb193824-a002-4e53-a73b-be75738ef3f2** [comment]
With this patch, I managed to make a working installer.

There's nothing in PCBuild/readme.txt about making an installer, and this is the only relevant tool I found in the source. If there's another, feel free to close the ticket, and I'll create another one to fix the readme.

**Comment by cbf13ede-eda8-4246-abee-98732ce73413** [comment]
> Assuming 3.4 is packagable using msi and hg is the only problem, I presume you could use an hg-git adapter to get an hg checkout to build from.
An official source tarball, by definition, should be able to be built 
from itself, and contain tools for that. If I take sources from a Git 
repo instead, I'm not building from a tarball. If I must do some 
undocumented magic on the extracted source to build that tools don't do, 
the tools are broken. The current ticket and the attached patch fix the 
tools.

P.S. I didn't include the patch right away 'cuz I was going to make a 
PR. But GitHub doesn't work for me for some reason lately, so attached 
it here after tried and failed.

**Comment by zware** [comment]
As 3.4 is in security-fix-only mode, it's up to Larry whether this can be merged.  The patch looks fine as far as I can tell, but I can't test it.

Note, though, that you are likely to be the only person on Earth using this installer, since there will be no more binary releases of 3.4, the installer was swapped out for 3.5, and the maintainer of the old installer has been away for several years now.  The new installer (in use since 3.5.0) almost certainly doesn't suffer from this issue.

**Comment by cbf13ede-eda8-4246-abee-98732ce73413** [comment]
> Note, though, that you are likely to be the only person on Earth 
using this installer, since there will be no more binary releases of 3.4

Since this is the last release for XP, probably the ppl who are stuck on 
this OS as well. An installable package is a must for any 
maintainability to speak of. The lack of a binary release is actually 
going to be a boost for its use, here :-)

I also had trouble discovering this script in the first place since it's 
not mentioned in PCBuild/readme.txt .
If build instructions are updated as per bpo-31691 , this would help 
potential users as well.

Beside this patch, bpo-31170 and bpo-31645 are needed for the 3.4 
build to work.

**Comment by zware** [comment]
If you're still on XP, security is obviously not a big concern and you're just as well off to stick with 3.4.4 :)
