### ISSUE TITLE
Socket documentation threading misstep?

### ISSUE THREAD

**Issue by 07b62af2-15b2-42e0-b0e6-3c3ff10b9f25** [python/cpython#75898]
BPO | [31717](https://bugs.python.org/issue31717)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-06.15:53:09.108>
labels = ['3.7', 'docs']
title = 'Socket documentation threading misstep?'
updated_at = <Date 2017-10-06.17:00:05.009>
user = 'https://bugs.python.org/apoplexy'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-06.17:00:05.009>
actor = 'apoplexy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2017-10-06.15:53:09.108>
creator = 'apoplexy'
dependencies = []
files = []
hgrepos = []
issue_num = 31717
keywords = []
message_count = 4.0
messages = ['303831', '303834', '303835', '303838']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'docs@python', 'apoplexy']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue31717'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

### Linked PRs
* gh-125023

**Comment by 07b62af2-15b2-42e0-b0e6-3c3ff10b9f25** [comment]
Very small, but,

https://docs.python.org/2/howto/sockets.html
https://docs.python.org/3/howto/sockets.html

have :
while True:
    \# accept connections from outside
    (clientsocket, address) = serversocket.accept()
    \# now do something with the clientsocket
    \# in this case, we'll pretend this is a threaded server
    ct = client_thread(clientsocket)
    ct.run()

and for some reason I really want it to be ct.start()

**Comment by bitdancer** [comment]
Based on the paragraph following the example, I don't think client_thread is a threading.Thread, and 'run' is meant to be a generic representation of a possible API.  Since Threads do have a 'run' method, this is certainly potentially confusing.  Maybe we should change it to 'start_thread' or something like that?

**Comment by bitdancer** [comment]
Or maybe instead of client_handler/run, it should be something like handle_client_asynchronously(clientsocket).

**Comment by 07b62af2-15b2-42e0-b0e6-3c3ff10b9f25** [comment]
I could definitely understand that. After all, if it's slightly askew (or
strikes some as such) it forces critical thinking, which is good. I didn't
think calling run() was indicative of the three likely pathways to handle
the client socket in the following paragraph.

I'm indifferent, I just saw something so I said something, but ultimately I
think you guys do a tremendous job keeping this documentation good.

Thanks,

**Comment by zuo** [comment]
The issue is tagged with `3.7 (EOL)`, but in fact it is still up do date (it could be tagged with 3.13 or 3.14 as well :)).

And I believe the change proposed by OP *would*, indeed, slightly improve the concerned document – making it consistent with the actual `threading.Thread`'s API (even though there is no explicit reference to that API).

So let's apply this change!
