### ISSUE TITLE
crashes in _elementtree due to unsafe decrefs of Element.text and Element.tail

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75909]
BPO | [31728](https://bugs.python.org/issue31728)
--- | :---
Nosy | @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3924</li><li>python/cpython#3945</li><li>python/cpython#3950</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-11.13:44:11.722>
created_at = <Date 2017-10-08.20:16:27.328>
labels = ['expert-XML', '3.7', 'type-crash']
title = 'crashes in _elementtree due to unsafe decrefs of Element.text and Element.tail'
updated_at = <Date 2017-10-11.13:44:11.720>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-11.13:44:11.720>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-11.13:44:11.722>
closer = 'serhiy.storchaka'
components = ['XML']
creation = <Date 2017-10-08.20:16:27.328>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31728
keywords = ['patch']
message_count = 6.0
messages = ['303917', '304013', '304079', '304087', '304132', '304135']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Oren Milman']
pr_nums = ['3924', '3945', '3950']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31728'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes the interpreter to crash:
import xml.etree.ElementTree
class X:
    def \_\_del__(self):
        elem.clear()
elem = xml.etree.ElementTree.Element('elem')
elem.text = X()
elem.clear()

This is because \_elementtree_Element_clear_impl() decrefs self-\>text in an
unsafe manner.
For the same reason, but for self-\>tail, a crash would happen if we replaced
'elem.text = X()' with 'elem.tail = X()'.


Similarly, the following code also causes the interpreter to crash:
import xml.etree.ElementTree
class X:
    def \_\_del__(self):
        elem.clear()
elem = xml.etree.ElementTree.Element('elem')
elem.text = X()
elem.text = X()

This is because element_text_setter() decrefs self-\>text in an unsafe manner.
element_tail_setter() does the same for self-\>tail, so again, if we replaced
'elem.text = X()' with 'elem.tail = X()', we would also get a crash.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
As serhiy pointed out in a comment in [PR 3924](https://github.com/python/cpython/pull/3924), setting self-\>text or self-\>tail to
NULL might lead to an assertion failure, so we should also prevent the following
assertion failure (and the similar one for tail):
import xml.etree.ElementTree
class X:
    def \_\_del__(self):
        elem.text
        
elem = xml.etree.ElementTree.Element('elem')
elem.text = X()
elem.\_\_setstate__({'tag': None}) # implicitly also set elem.text to None

**Comment by serhiy-storchaka** [comment]
New changeset 39ecb9c71b6e55d8a61a710d0144231bd88f9ada by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31728: Prevent crashes in \_elementtree due to unsafe cleanup of Element.text and Element.tail (bpo-3924)
https://github.com/python/cpython/commit/39ecb9c71b6e55d8a61a710d0144231bd88f9ada

**Comment by serhiy-storchaka** [comment]
New changeset a8ac71d15f2a4aef83a8954a678cc12545ce517c by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31728: Prevent crashes in \_elementtree due to unsafe cleanup of Element.text and Element.tail (GH-3924) (bpo-3945)
https://github.com/python/cpython/commit/a8ac71d15f2a4aef83a8954a678cc12545ce517c

**Comment by serhiy-storchaka** [comment]
New changeset f15058a697de12b0efe6c7ebc38fe61a993bb5d5 by Serhiy Storchaka (Oren Milman) in branch '2.7':
[2.7] bpo-31728: Prevent crashes in \_elementtree due to unsafe cleanup of Element.text and Element.tail (GH-3924) (bpo-3950)
https://github.com/python/cpython/commit/f15058a697de12b0efe6c7ebc38fe61a993bb5d5

**Comment by serhiy-storchaka** [comment]
Thank you Oren!
