### ISSUE TITLE
Documentation incorrectly states how descriptors are invoked

### ISSUE THREAD

**Issue by 0c97e840-ae8b-4fa9-b95e-fe2331d61b5b** [python/cpython#75916]
BPO | [31735](https://bugs.python.org/issue31735)
--- | :---
Nosy | @rhettinger, @Cryvate, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2021-12-04.01:44:12.434>
created_at = <Date 2017-10-09.15:04:44.804>
labels = ['3.11', 'invalid', '3.9', '3.10', 'docs']
title = 'Documentation incorrectly states how descriptors are invoked'
updated_at = <Date 2021-12-04.01:44:12.433>
user = 'https://bugs.python.org/PaulPinterits'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-04.01:44:12.433>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2021-12-04.01:44:12.434>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-10-09.15:04:44.804>
creator = 'Paul Pinterits'
dependencies = []
files = []
hgrepos = []
issue_num = 31735
keywords = []
message_count = 8.0
messages = ['303968', '303978', '303984', '303986', '304021', '304022', '407603', '407623']
nosy_count = 5.0
nosy_names = ['rhettinger', 'docs@python', 'Paul Pinterits', 'cryvate', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31735'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by 0c97e840-ae8b-4fa9-b95e-fe2331d61b5b** [comment]
The [descriptor howto](https://docs.python.org/3/howto/descriptor.html#invoking-descriptors) states:

"For example, obj.d looks up d in the dictionary of obj. If d defines the method \_\_get__(), then d.\_\_get__(obj) is invoked [...]"

This is not true - the descriptor obtained from obj's dictionary is never invoked. If it was, the following two snippets would produce output:


```py
class Class:
    pass

obj = Class()
obj.__dict__['d'] = property(lambda: print('called'))

_ = obj.d  # nothing is printed.


class Obj:
    @property
    def d(self):
        print('called')

_ = Obj.d  # nothing is printed.
```

**Comment by 7c3b9f7a-e616-458a-973e-3db6fe83c3bc** [comment]
You get what you should get: when you print obj.d, Obj.d, you will get:

\<property object at 0xDEADBEEF\>

which is exactly what you expect:
- in the first case, you assigned a property object to the dictionary at obj.\_\_dict__, so that's what you get back when you run obj.d.
- you defined a property on a class called d, and you get it when you run Obj.d

If you run print(Obj().d) you will get a TypeError: your lambda should read:

lambda self: print('called')

Properties should be added to the class not the instance, see https://stackoverflow.com/questions/1325673/how-to-add-property-to-a-class-dynamically and https://eev.ee/blog/2012/05/23/python-faq-descriptors/

**Comment by 0c97e840-ae8b-4fa9-b95e-fe2331d61b5b** [comment]
I'm aware that descriptors have to exist on the class in order to work. The point is that the documentation states "If d defines the method \_\_get__(), then d.\_\_get__(obj) is invoked" (where d is obj.d), which is simply not true.

**Comment by 0c97e840-ae8b-4fa9-b95e-fe2331d61b5b** [comment]
If we take this class:

```py
class Obj:
    @property
    def d(self):
        print('called')
```


And we access Obj.d:

```py
_ = Obj.d
```


According to the docs, the following should happen:

```py
# obj.d looks up d in the dictionary of obj
d = Obj.__dict__['d']

# If d defines the method __get__(),
if hasattr(d, '__get__'):

    # then d.__get__(obj) is invoked
    d.__get__(Obj)
```


We know this doesn't happen because nothing is printed to stdout.

**Comment by 7c3b9f7a-e616-458a-973e-3db6fe83c3bc** [comment]
"We know this doesn't happen because nothing is printed to stdout."

Try running Obj().d, you will get output.

Obj.d does not work because it is on a \*class*, and so it runs, per the docs:

'Obj.\_\_dict__['d'].\_\_get__(None, Obj)'

whereas you consider running it on an instance to get:

```py
b = Obj()
b.d
# equivalent to
type(b).__dict__['d'].__get__(b, type(b))
```


and you will get output twice.

[Note, on python2 you will get an error, I think this is because your class does not inherit from object.]

**Comment by 7c3b9f7a-e616-458a-973e-3db6fe83c3bc** [comment]
I do think though that

"If d defines the method \_\_get__(), then d.\_\_get__(obj) is invoked according to the precedence rules listed below."

seems to contain a mistake in that it should have

d.\_\_get__(obj, type(obj)) instead of d.\_\_get__(obj)
