### ISSUE TITLE
Support for C++ 11 and/or C++ 14 in macOS python.org installer

### ISSUE THREAD

**Issue by 194edc10-7bb3-4daa-aaf1-545c513a8f98** [python/cpython#75932]
BPO | [31751](https://bugs.python.org/issue31751)
--- | :---
Nosy | @gpshead, @ronaldoussoren, @ned-deily, @hardkrash

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-02-10.07:29:09.274>
created_at = <Date 2017-10-10.18:51:16.820>
labels = ['OS-mac', 'build', 'expert-installation', '3.8', 'type-feature', '3.7']
title = 'Support for C++ 11 and/or C++ 14 in macOS python.org installer'
updated_at = <Date 2021-02-10.07:29:09.273>
user = 'https://github.com/hardkrash'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-10.07:29:09.273>
actor = 'gregory.p.smith'
assignee = 'none'
closed = True
closed_date = <Date 2021-02-10.07:29:09.274>
closer = 'gregory.p.smith'
components = ['Build', 'Installation', 'macOS']
creation = <Date 2017-10-10.18:51:16.820>
creator = 'hardkrash'
dependencies = []
files = []
hgrepos = []
issue_num = 31751
keywords = []
message_count = 6.0
messages = ['304068', '304085', '304098', '304130', '386742', '386761']
nosy_count = 4.0
nosy_names = ['gregory.p.smith', 'ronaldoussoren', 'ned.deily', 'hardkrash']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31751'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 194edc10-7bb3-4daa-aaf1-545c513a8f98** [comment]
We are using some compiled cython modules with c++ 11 features.
This prohibits us from instructing users to install python from the python.org download.

Please consider using clang with support for C++ 11 and higher.
This would move the minimum OS X version away from 10.6 but as 10.6 is 8 years old and phased out 6 years ago it should be rare that non technical users would be using this OS version.

**Comment by ned-deily** [comment]
Can you give a test case demonstrating what is not working?  The Python interpreters installed with python.org 10.6+ installers are built to work with all versions of macOS from 10.6 on and should be able to build extension modules with either gcc or clang as provided by the Xcode or Command Line Tools appropriate for the macOS version in use.  And, AFAIK, Python itself has no dependency on C++ at all so there should not be a c++ runtime library conflict due to Python itself.  Although the initial value of the configuration variables are CC=gcc-4.2 and GXX=g++-4.2, when the first compilation of an extension module is attempted, Distutils via [Lib/_osx_support.py](https://github.com/python/cpython/blob/main/Lib/_osx_support.py) will do some work to figure out what compilers are available and modify CC and CXX accordingly.  So, for example, on say a macOS 10.13 system with the default Command Line Tools, it should use gcc and g++ which are both aliases for clang.  And, if necessary, you can always override the default compiler selection by explicitly setting the CC and/or CXX environment variables when invoking python.  At least that's how it's supposed to work!

**Comment by 194edc10-7bb3-4daa-aaf1-545c513a8f98** [comment]
This might be a cython issue then, but I will dig into an example case.  Please be patient.

**Comment by ned-deily** [comment]
No rush!  And I didn't mean to imply that how the macOS installers are built is perfect or updates shouldn't be considered.  But we should understand what the issue here is, independent of potential changes.
