### ISSUE TITLE
Issue in login

### ISSUE THREAD

**Issue by 3b2d58e8-6f21-47f9-8fbc-847e0358c4a5** [python/cpython#75943]
BPO | [31762](https://bugs.python.org/issue31762)
--- | :---
Nosy | @bitdancer, @GREEKYnikhilsharma
Files | <li>[Screenshot_20171011_222848.png](https://bugs.python.org/file47213/Screenshot_20171011_222848.png "Uploaded as image/png at 2017-10-11.17:00:59 by @GREEKYnikhilsharma")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-11.18:49:37.537>
created_at = <Date 2017-10-11.17:00:59.827>
labels = []
title = 'Issue in login'
updated_at = <Date 2017-10-11.18:49:37.536>
user = 'https://github.com/GREEKYnikhilsharma'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-11.18:49:37.536>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-11.18:49:37.537>
closer = 'r.david.murray'
components = []
creation = <Date 2017-10-11.17:00:59.827>
creator = 'Nik101'
dependencies = []
files = ['47213']
hgrepos = []
issue_num = 31762
keywords = []
message_count = 2.0
messages = ['304164', '304170']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'Nik101']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31762'
versions = []
```

</p></details>

**Comment by 3b2d58e8-6f21-47f9-8fbc-847e0358c4a5** [comment]
I have included the screen shot

**Comment by bitdancer** [comment]
This tracker is for reporting bugs in python.  If you want to report a problem with the tracker, please use the 'report tracker problem' link in the left column.  (That said, I thought the error message you show in the screenshot was fixed by the recent tracker upgrade, but then again the screenshot doesn't look like any image of the tracker I've ever seen.  So if you open a tracker error report please provide additional information about your environment and what actions will reproduce the error).
