### ISSUE TITLE
unitest.mock: Using autospec=True conflicts with 'wraps'

### ISSUE THREAD

**Issue by 721fabdf-f286-4c0a-90e3-7326ebe32f66** [python/cpython#75988]
BPO | [31807](https://bugs.python.org/issue31807)
--- | :---
Nosy | @rbtcollins, @ezio-melotti, @voidspace, @Lukas0907, @tirkarthi
Files | <li>[0001-bpo-31807-unittest.mock-Fix-common-use-of-autospec-T.patch](https://bugs.python.org/file47267/0001-bpo-31807-unittest.mock-Fix-common-use-of-autospec-T.patch "Uploaded as text/plain at 2017-11-15.15:29:36 by @Lukas0907")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-18.00:48:15.176>
labels = ['3.7', 'type-bug', 'library']
title = "unitest.mock: Using autospec=True conflicts with 'wraps'"
updated_at = <Date 2019-12-02.08:29:10.129>
user = 'https://bugs.python.org/JohnVillalovos'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-02.08:29:10.129>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-10-18.00:48:15.176>
creator = 'John Villalovos'
dependencies = []
files = ['47267']
hgrepos = []
issue_num = 31807
keywords = ['patch']
message_count = 3.0
messages = ['304549', '306273', '352287']
nosy_count = 6.0
nosy_names = ['rbcollins', 'ezio.melotti', 'michael.foord', 'John Villalovos', 'Lukas Anzinger', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31807'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

### Linked PRs
* gh-115223
* gh-117119
* gh-117124

**Comment by 721fabdf-f286-4c0a-90e3-7326ebe32f66** [comment]
If have autospec=True, then no ValueError is raised. If autospec=False or not defined, then the ValueError is raised.


```py
import sys
from unittest import mock

def wrapped_func(value):
    raise ValueError(value)
```


@mock.patch('\_\_main__.wrapped_func', autospec=True, wraps=wrapped_func)
def main(mock_wrap):

```py
    wrapped_func("testing")

if '__main__' == __name__:
    sys.exit(main())
```

**Comment by 67460b24-f0bd-486d-84ce-822ccfee29db** [comment]
I can reproduce the problem and have analyzed it a bit. My use case is a bit different, I want to use autospec=True and wraps= so that I can mock unbound methods but return the result from the original method (see also https://docs.python.org/3/library/unittest.mock-examples.html#mocking-unbound-methods).

The problem in the mock code is that mock.return_value actually calls \_\_get_return_value() which replaces the actual return value mock.DEFAULT (which is stored in self.\_mock_return_value) with a new child mock. When the mock is then called and \_mock_call() is executed, the wrapped function is not executed because self.\_mock_return_value is not mock.DEFAULT anymore:


```py
    if (self._mock_wraps is not None and
         self._mock_return_value is DEFAULT):
        return self._mock_wraps(*args, **kwargs)
    if ret_val is DEFAULT:
        ret_val = self.return_value
    return ret_val
```



Since self.\_mock_return_value is not DEFAULT anymore it doesn't matter if the mock wraps something and it will instead just return a new mock.

I think that the side effect of the assignment to self.return_value in \_setup_func() is not intentional, i.e. the child mock should actually be created only if there is an outside access to return_value, but not when it is just wrapped in a function. The assignment can be made side effect free by assigning the internal attribute \_mock_return_value (see attached patch). This solves the problem for me.
 
I've attached a patch that fixes the problem and doesn't seem to introduce a regression (all unittest.mock tests pass).

If somebody is interested in getting this merged, I'm happy to provide a regression test and everything else that is needed to get this merged.

Cheers,

Lukas

**Comment by e-gebes** [comment]
I ran into the same issue with methods like @Lukas0907 described it, on Python 3.10.

**Comment by infohash** [comment]
`wraps` is ignored in `create_autospec` as well.

```python
from unittest import mock

import pytest


class MyClass:
    def my_func(self):
        raise ValueError


@pytest.mark.xfail
def test_my_func_with_autospec():
    my_func = mock.create_autospec(spec=MyClass.my_func, wraps=MyClass.my_func)
    with pytest.raises(ValueError):
        assert my_func(MyClass())


def test_my_func_without_autospec():
    my_func = mock.Mock(spec=MyClass.my_func, wraps=MyClass.my_func)
    with pytest.raises(ValueError):
        assert my_func(MyClass())
```
Should be run as is.

**Comment by infohash** [comment]
On investigation, I have discovered 3 issues that are making `autospec` to ignore `wraps`.

# Issue 1: Let's Address The OP's Case First

When OP uses autospec on a function/method, autospec replaces the original function/method with its own hardcoded mock function and mock attributes. This can be seen here and it is intended by design.

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/unittest/mock.py#L2775-L2781

This if condition becomes true when you pass a function or a method to `spec` argument. Why?  This is what `FunctionTypes` is:

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/unittest/mock.py#L2886-L2891

On condition true, `_set_signature` or `_setup_async_mock` will return a hardcoded mock function which replaces the original function/method:

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/unittest/mock.py#L201-L207

Now the question is how this leads to ignoring `wraps`? See the above line 206 `_setup_func`, it is patching the return value of the mock function:

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/unittest/mock.py#L264

`return_value` is a property so assigning a new value to it triggers the `settr` descriptor:

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/unittest/mock.py#L584-L592

At line 588 `self._mock_return_value` is assigned a value replacing the default value `Sentiner.DEFAULT`.  `self._mock_return_value` will come to picture soon.

Now the original function has been replaced with the mock and its return value is patched, when it is called, these are the calls made:

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/unittest/mock.py#L1159-L1164

In the above return statement `self._mock_call(*args, **kwargs)` executes:

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/unittest/mock.py#L1167-L1168

Inside `self._execute_mock_call(*args, **kwargs)`:

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/unittest/mock.py#L1234-L1240

Remember, `self._mock_return_value` was assigned a new mocked return value which replaces the default `Sentiner.DEFAULT` value? Because of that, the line 1234 becomes true and you are returned mocked return value ignoring your `wraps` which is just below this condition and `self._mock_wraps is not None` is a true condition because `wraps` is provided as an argument.

---

# Solution To This

I have just inverted the conditions here so that `self._mock_wraps is not None` is given precedent over `self._mock_return_value is not DEFAULT`:

```python
        if self._mock_wraps is not None:
            return self._mock_wraps(*args, **kwargs)

        if self._mock_return_value is not DEFAULT:
            return self.return_value
```

This will now trigger your original function.

---

# Other Two Issues That Are Fixed By The Above Solution & Also Depend On The Above Solution

## Issue 2

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/unittest/mock.py#L2788-L2790

`kwargs` should be provided here so that `wraps` can be passed down to ensure that instance mock can also pass the call through to the wrapped object. When you don't use `autospec`, the instance mock does pass the call through to the wrapped object.

```python
if is_type and not instance and 'return_value' not in kwargs:
        mock.return_value = create_autospec(spec, spec_set, instance=True,
                                            _name='()', _parent=mock, **kwargs)
```

## Issue 3

Inside this for loop:

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/unittest/mock.py#L2792

https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/Lib/unittest/mock.py#L2811

`kwargs` here is not being updated by the `kwargs` from the argument so `wraps` is ignored for child mocks. It should be like this:

```python
wrap_child_mocks = kwargs.get('wraps')
for entry in dir(spec):

    ...

    kwargs = {'spec': original}
    if wrap_child_mocks:
        kwargs.update(wraps=original)
    if spec_set:
        kwargs = {'spec_set': original}
```

I am raising a PR to fix this, let me know if I am wrong about any of these 3 issues being an issue.

**Comment by infohash** [comment]
@tirkarthi @cjw296 This should be closed as completed.
