### ISSUE TITLE
Make itertools iterators interruptible

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75996]
BPO | [31815](https://bugs.python.org/issue31815)
--- | :---
Nosy | @tim-one, @rhettinger, @ncoghlan, @serhiy-storchaka, @k7hoven
PRs | <li>python/cpython#4038</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2018-06-24.05:54:58.595>
created_at = <Date 2017-10-18.16:43:01.540>
labels = ['extension-modules', 'type-feature', '3.8']
title = 'Make itertools iterators interruptible'
updated_at = <Date 2018-06-24.05:54:58.594>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-24.05:54:58.594>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2018-06-24.05:54:58.595>
closer = 'rhettinger'
components = ['Extension Modules']
creation = <Date 2017-10-18.16:43:01.540>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31815
keywords = ['patch']
message_count = 17.0
messages = ['304588', '304590', '304591', '304592', '304593', '304595', '304600', '304601', '304602', '304607', '304633', '304736', '320230', '320351', '320353', '320354', '320356']
nosy_count = 5.0
nosy_names = ['tim.peters', 'rhettinger', 'ncoghlan', 'serhiy.storchaka', 'koos.zevenhoven']
pr_nums = ['4038']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31815'
versions = ['Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed PR makes tight C loops with itertools iterators interruptible with Ctrl-C. It adds checks for keyboard interrupt in iterators that can produce long sequences without advancing other iterators. For performance checks are performed only for every 0x1000-th item. If for generating new value other iterator should be advanced, the responsibility for checking for keyboard interrupt is attributed to that iterator.

This would solve the problem discussed on Python-ideas:

https://mail.python.org/pipermail/python-ideas/2017-October/047412.html
http://permalink.gmane.org/gmane.comp.python.ideas/47429

Example:

```pycon
>>> import itertools
>>> it = itertools.count()
>>> it in it
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyboardInterrupt
>>>
```

**Comment by rhettinger** [comment]
When I have time, I would like to re-launch a python-dev discussion on this.  It is my feeling that this solves an invented problem.  In my experience, it only ever happens to people who have intentionally trying to create this effect.

Adding this kind of "junk" through-out the code base adds complexity and more internal operations, but won't help \*any* existing, deployed code.  We're making everyone pay for a problem that almost no one has.

Also, if we do care about interruptability, it is unclear whether the responsiblity should like with the consumer or the producer of the iterator.

**Comment by serhiy-storchaka** [comment]
Microbenchmark results:

```sh
$ ./python -m perf timeit --compare-to=../cpython-release/python -s 'from itertools import repeat' 'list(repeat(None, 1000000))'
/home/serhiy/py/cpython-release/python: ..................... 3.79 ms +- 0.09 ms
/home/serhiy/py/cpython-iter/python: ..................... 4.14 ms +- 0.07 ms
```


Mean +- std dev: [/home/serhiy/py/cpython-release/python] 3.79 ms +- 0.09 ms -\> [/home/serhiy/py/cpython-iter/python] 4.14 ms +- 0.07 ms: 1.09x slower (+9%)


```sh
$ ./python -m perf timeit --compare-to=../cpython-release/python -s 'from itertools import cycle, islice' 'list(islice(cycle(range(1000)), 1000000))'
/home/serhiy/py/cpython-release/python: ..................... 6.88 ms +- 0.30 ms
/home/serhiy/py/cpython-iter/python: ..................... 6.87 ms +- 0.26 ms
```


Mean +- std dev: [/home/serhiy/py/cpython-release/python] 6.88 ms +- 0.30 ms -\> [/home/serhiy/py/cpython-iter/python] 6.87 ms +- 0.26 ms: 1.00x faster (-0%)
Not significant!


```sh
$ ./python -m perf timeit --compare-to=../cpython-release/python -s 'from itertools import count, islice' 'list(islice(count(), 1000000))'
/home/serhiy/py/cpython-release/python: ..................... 26.1 ms +- 0.6 ms
/home/serhiy/py/cpython-iter/python: ..................... 26.3 ms +- 0.6 ms
```


Mean +- std dev: [/home/serhiy/py/cpython-release/python] 26.1 ms +- 0.6 ms -\> [/home/serhiy/py/cpython-iter/python] 26.3 ms +- 0.6 ms: 1.01x slower (+1%)
Not significant!


```sh
$ ./python -m perf timeit --compare-to=../cpython-release/python -s 'from itertools import product' 'list(product(range(100), repeat=3))'
/home/serhiy/py/cpython-release/python: ..................... 80.2 ms +- 3.2 ms
/home/serhiy/py/cpython-iter/python: ..................... 80.2 ms +- 1.7 ms
```


Mean +- std dev: [/home/serhiy/py/cpython-release/python] 80.2 ms +- 3.2 ms -\> [/home/serhiy/py/cpython-iter/python] 80.2 ms +- 1.7 ms: 1.00x faster (-0%)
Not significant!


```sh
$ ./python -m perf timeit --compare-to=../cpython-release/python -s 'from itertools import combinations' 'list(combinations(range(23), 10))'
/home/serhiy/py/cpython-release/python: ..................... 177 ms +- 14 ms
/home/serhiy/py/cpython-iter/python: ..................... 169 ms +- 4 ms
```


Mean +- std dev: [/home/serhiy/py/cpython-release/python] 177 ms +- 14 ms -\> [/home/serhiy/py/cpython-iter/python] 169 ms +- 4 ms: 1.05x faster (-4%)


The only significant slowdown is for repeat(). But there is possibility to optimize this one by reusing an existing counter.

**Comment by serhiy-storchaka** [comment]
With optimized repeat():

```sh
$ ./python -m perf timeit --compare-to=../cpython-release/python -s 'from itertools import repeat' 'list(repeat(None, 1000000))'
/home/serhiy/py/cpython-release/python: ..................... 3.77 ms +- 0.06 ms
/home/serhiy/py/cpython-iter/python: ..................... 3.77 ms +- 0.05 ms
```


Mean +- std dev: [/home/serhiy/py/cpython-release/python] 3.77 ms +- 0.06 ms -\> [/home/serhiy/py/cpython-iter/python] 3.77 ms +- 0.05 ms: 1.00x faster (-0%)
Not significant!

**Comment by serhiy-storchaka** [comment]
I concur with Raymond. I cited the same arguments in the discussion on Python-ideas. But the other solution that was suggested in this discussion will add more complexity and can't solve all cases.

**Comment by cb78a0e9-9e36-40b5-8802-5ac829a439b1** [comment]
To repeat one of my points in the linked threads, I'm not convinced that infinite iterators are the most common case for the problem of long uninterruptible loops. A general mechanism that can be easily used in many places with minimal maintenance burden would be nice. It could be used even in third-party extension modules.

**Comment by ncoghlan** [comment]
Defensive coding and the complications it brings is a fact of life when providing a widely used platform.

Sure, we're free to say "We don't care about minor user experience irritations like Ctrl-C not always being reliable, users should just suck it up and cope".

I think "It's your own fault for typing that, just restart your session from scratch" is setting the bar too low for ourselves.

**Comment by ncoghlan** [comment]
To put this another way: I see an uninterruptible infinite loop as a data loss bug on par with a segfault, since there's no graceful way to terminate the process and allow cleanup code to run.

For segfaults, we're willing to tolerate them, but we expect the reproducers to involve arcane coding contortions, not simple expressions like "sum(itertools.count())".

Now, the producer side check that Serhiy posted here only addresses part of the problem - there's also the question of making the consumption loops more robust by having them check for signals, and adding a ThreadExit equivalent to allow the interpreter to request shutdown of non-daemon threads other than the main thread.

But as long as we think it's a-OK for us to hang a user's session, causing them to lose all their unsaved/uncached data, then we're going to resist the extra code complexity required to account for these usability concerns. (And I realise they're not new concerns - they're just longstanding problems that folks have gotten used to tolerating and excusing)

**Comment by rhettinger** [comment]
I respectfully disagree that this just happens to people accidentally -- Every single day, I work with either Python professionals or Python students and never see this situation occur, nor have I had a single report of it from one of my clients, ever.  In my experience, someone has to be trying to produce exactly this effect.  

They have to go out of their way to import a high-performance module, select one of the tools specifically documented to be infinite, specifically reach for one the very few tools like repeat() or count() that don't make any pure python callbacks, and then separately reach for a high-performance consumer that makes no pure python callbacks.  People don't just write ``sum(itertools.count()`` to do something useful, they do it just to see if they can produce exactly this effect.

We have a number of areas where we're comfortable saying "just don't do that" (i.e. the repr of a large number or of a large container, repeated exponentation, bytecode hacks, ill-formed ctypes, etc).

```pycon
I would like to draw a line in the sand for itertools to not go down this path unless we actually see this happening in the wild to people not trying to do it on purpose.  It is much more likely that a user with accidentally types ">>> 'x' * 1000000000" and gets the same effect.
```


On a side note, I have a fear (possibly rational, possibly not) that introducing signal handling into formerly atomic operations will open up new classes of bugs and usability problems (i.e. Issue bpo-14976 showed that when GC gained the ability trigger calls to \_\_del__, it created queue reentrancy deadlock problems that could not be solved with pure python code).

One last thought -- the various core devs seem to be charging in opposite directions.  On the one hand, there seems to be no limit to the coding atrocities being considered to save under a millisecond of startup time and for various other questionable mirco-optimizations.  And on the other hand, there seems to be a great deal of willingness to inject almost-never-needed error checks or signal handling into otherwise tight, high-volume code paths.   One group likes to refactor code to make it clean and easy to maintain and stick with its business purpose, while another group is comfortable garbaging-up code in order to achieve some other benefit that may not be in line with the module designer's intent.

**Comment by ncoghlan** [comment]
I'd personally be happy enough if the infinite iterators implemented \_\_length_hint__() as always raising TypeError so the machine-breaking cases of incremental consumption of ever-increasing amounts of memory were blocked - I was suggesting on python-ideas that enabling pervasive signal checking would be too intrusive for anyone to be willing to implement it.

However, Serhiy's patch showed me that it isn't particularly intrusive at all, and the risk of surprising consumers is low, since \_\_next__() methods can already raise arbitrary exceptions.

**Comment by tim-one** [comment]
Segfaults are different:  they usually expose an error in CPython's implementation.  We don't prioritize them because the user may have to restart their program (who cares? \<0.5 wink\>), but because they demonstrate the language implementation is accessing memory wildly.  That in turn can result in anything, from arbitrarily wrong program results, through file corruption, to massive security holes.  It's far more a "correctness" than a "usability" concern.

If a user provokes a segfault by (ab)using low-level facilities (say, ctypes), we don't care - that's on them.  But most segfaults have pointed to legitimate corner-case errors in CPython itself.

There's no correctness issue in whether iterators are always interruptible - it doesn't merit the same concern.

**Comment by cb78a0e9-9e36-40b5-8802-5ac829a439b1** [comment]
For the interactive user who uses an interactive environment such as the repl or a Jupyter notebook, the situation is a little different from "CPython as programming language runtime".

The docs say a KeyboardInterrupt is "Raised when the user hits the interrupt key (normally Control-C or Delete). During execution, a check for interrupts is made regularly.". I suppose there's some ambiguity in what "regularly" means there ;). 

But regardless of whether anyone bothers to read that part of the docs, Ctrl-C or an interrupt button not working can feel like a correctness issue for someone that's using an interactive Python environment \*as an application* in daily work. Python gives you the impression that you can always interrupt anything if it turns out to take too much time. And I remember that being one of the points that made me move away from matlab, which at that time had problems with interrupting computations.
