### ISSUE TITLE
IDLE: Make font sample editable

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#76041]
BPO | [31860](https://bugs.python.org/issue31860)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka, @csabella
PRs | <li>python/cpython#4106</li><li>python/cpython#4154</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-10-28.01:03:14.390>
created_at = <Date 2017-10-24.13:20:40.688>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'IDLE: Make font sample editable'
updated_at = <Date 2019-01-18.03:01:30.788>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2019-01-18.03:01:30.788>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-10-28.01:03:14.390>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-10-24.13:20:40.688>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31860
keywords = ['patch']
message_count = 9.0
messages = ['304909', '305098', '305128', '305135', '305141', '305143', '305144', '310469', '333935']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'serhiy.storchaka', 'cheryl.sabella']
pr_nums = ['4106', '4154']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31860'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The proposed patch makes the font sample in IDLE font configuration dialog editable. This allows users to test fonts with arbitrary samples.

**Comment by terryjreedy** [comment]
Thanks for the patch.  Adding the feature is somehow easier than I expected.  After moving the sample text to module level, which I considered doing before, saving edits for the duration of an IDLE session turned out to also be easy.  

With 11 point Lucida Console, there is room for 5 more lines, without erasing anything, before anything scrolls off the top.

I expect that saving changes across IDLE sessions would be much harder and likely not worth the effort.  I think that exploring font choices is likely rare enough that there is little need to do so.

**Comment by csabella** [comment]
I don't know if saving the changes would be too difficult.

1.  Create a new config file for the text (I think it would clutter the existing config files, but could also add it there).
2.  Load font_sample_text from the config file.
3.  In apply(), write the text back to the config file.

Issues:
1.  Have a reset button so that the original sample text could be restored at some point?  If so, then need to store the original (current) text somewherem maybe a .def and .cfg version like for the other settings?  A reset button would also require some screen space from the text frame.

**Comment by terryjreedy** [comment]
Cheryl, thanks for explaining, in part, why I don't want to do this ;-).  Using the the current .def, .cfg system would mean that the default sample would be frozen.  I want to be able to change it.

**Comment by csabella** [comment]
Makes sense.  I guess I didn't think of it being frozen because I was thinking of it being more like the Recent Files list, but pre-populated if it were empty.  As you said, probably not worth the effort.  :-)

**Comment by terryjreedy** [comment]
New changeset ed6554c487fb2403bc88be6deee611c7a4171d33 by Terry Jan Reedy (Serhiy Storchaka) in branch 'master':
bpo-31860: Make the font sample in the IDLE font configuration dialog editable. (bpo-4106)
https://github.com/python/cpython/commit/ed6554c487fb2403bc88be6deee611c7a4171d33

**Comment by terryjreedy** [comment]
New changeset 6a2957de08e0c2d73f3124d12874b408cda4633d by Terry Jan Reedy (Miss Islington (bot)) in branch '3.6':
bpo-31860: Make the font sample in the IDLE font configuration dialog editable. (GH-4106) (bpo-4154)
https://github.com/python/cpython/commit/6a2957de08e0c2d73f3124d12874b408cda4633d
