### ISSUE TITLE
Duplicated keys in MIME type_map with different values

### ISSUE THREAD

**Issue by markshannon** [python/cpython#76048]
BPO | [31867](https://bugs.python.org/issue31867)
--- | :---
Nosy | @asvetlov, @markshannon, @Cryvate
PRs | <li>python/cpython#4388</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-17.10:11:03.567>
created_at = <Date 2017-10-25.10:14:00.897>
labels = ['3.7', 'library']
title = 'Duplicated keys in MIME type_map with different values'
updated_at = <Date 2017-11-17.10:11:03.566>
user = 'https://github.com/markshannon'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-17.10:11:03.566>
actor = 'asvetlov'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-17.10:11:03.567>
closer = 'asvetlov'
components = ['Library (Lib)']
creation = <Date 2017-10-25.10:14:00.897>
creator = 'Mark.Shannon'
dependencies = []
files = []
hgrepos = []
issue_num = 31867
keywords = ['patch']
message_count = 5.0
messages = ['304973', '304974', '304979', '306425', '306426']
nosy_count = 3.0
nosy_names = ['asvetlov', 'Mark.Shannon', 'cryvate']
pr_nums = ['4388']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31867'
versions = ['Python 3.7']
```

</p></details>

**Comment by markshannon** [comment]
Here
https://github.com/python/cpython/blob/master/Lib/mimetypes.py#L416
and here
https://github.com/python/cpython/blob/master/Lib/mimetypes.py#L526

I have no idea which is the correct value for either, but the code is misleading at best.

**Comment by markshannon** [comment]
I hadn't noticed the comments on the lines above saying "Duplicates :(", so I'm obviously not the first to notice.

**Comment by 7c3b9f7a-e616-458a-973e-3db6fe83c3bc** [comment]
So for excel, 'application/excel' is not listed at http://www.iana.org/assignments/media-types as suggested by the comment at:
https://github.com/python/cpython/blob/master/Lib/mimetypes.py#L397
whereas 'applicaton/vnd.ms-excel' is listed. See also
https://stackoverflow.com/questions/974079/setting-mime-type-for-excel-document.

For cdf, Wolframalpha is using application/cdf it seems (without it being registered) whereas NetCDF suggests application/x-netcdf so that seems reasonable (and is the current value).

For context, these duplicates were introduced here:
https://github.com/python/cpython/commit/a3689fe78675c89d5979c0c5acdb1c173cc75ed6
and noted first here:
https://github.com/python/cpython/commit/107771a228ee73b4683242cb696e3024f93b74d5

**Comment by asvetlov** [comment]
New changeset f02f5e5c3eb815fff9578dc58de60374c6baaa3d by Andrew Svetlov (Henk-Jaap Wagenaar) in branch 'master':
bpo-31867: Remove duplicates in default mimetypes. (bpo-4388)
https://github.com/python/cpython/commit/f02f5e5c3eb815fff9578dc58de60374c6baaa3d

**Comment by asvetlov** [comment]
Henk-Jaap thanks for contribution!
