### ISSUE TITLE
(list).insert() not working

### ISSUE THREAD

**Issue by c2133a72-14f9-4ed0-957c-d82a18cc2898** [python/cpython#76096]
BPO | [31915](https://bugs.python.org/issue31915)
--- | :---
Nosy | @stevendaprano
Files | <li>[Times Tables.py](https://bugs.python.org/file47250/Times%20Tables.py "Uploaded as text/plain at 2017-11-01.01:30:19 by Chance Parsons")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-01.03:37:48.349>
created_at = <Date 2017-11-01.01:30:20.199>
labels = ['type-bug', 'invalid']
title = '(list).insert() not working'
updated_at = <Date 2017-11-01.03:37:48.348>
user = 'https://bugs.python.org/ChanceParsons'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-01.03:37:48.348>
actor = 'steven.daprano'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-01.03:37:48.349>
closer = 'steven.daprano'
components = []
creation = <Date 2017-11-01.01:30:20.199>
creator = 'Chance Parsons'
dependencies = []
files = ['47250']
hgrepos = []
issue_num = 31915
keywords = []
message_count = 2.0
messages = ['305350', '305355']
nosy_count = 3.0
nosy_names = ['steven.daprano', 'Michael Selik', 'Chance Parsons']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31915'
versions = ['Python 3.6']
```

</p></details>

**Comment by 918fd5bb-b946-4ec7-91c7-095b988657d6** [comment]
What behavior did you expect from your code?
What behavior did you get instead?

It looks like you're not calling the list copy method correctly. Try writing "tables2.copy()" instead of "tables2.copy". It also looks like you have other bugs in your code.

This forum is for reporting bugs in the Python language. If you'd like help with bugs in your own code, try asking on StackOverflow (https://stackoverflow.com/) or on the Python Help mailing list (https://mail.python.org/mailman/listinfo/python-help).

**Comment by stevendaprano** [comment]
Thank you for taking the time to report what you thought was a bug, but your example is way too complicated for a bug report. We shouldn't have to study your entire program to understand what the problem is.

I can see at least one bug in your code:

```py
    tbles = tables2.copy
```


sets the variable "tbles" as an alias to the "tables2.copy" method, and of course methods don't have an insert method themselves. So I'm closing this as "Not a bug". If you disagree, feel free to re-open the ticket with more information.

In future, please always report the SIMPLEST example of the bug that you can write. Tell us what you expected to happen, and COPY AND PASTE (no screenshots) the error message that you get, or other unexpected result.

You might also find it useful to read this page:

http://sscce.org/

It is written in terms of Java, but the principles apply equally to every programming language.

Thank you.
