### ISSUE TITLE
pygettext ignores directories as inputfile argument

### ISSUE THREAD

**Issue by 3e26ea47-9edf-4ff1-9361-f447fe64d25d** [python/cpython#76101]
BPO | [31920](https://bugs.python.org/issue31920)
--- | :---
Nosy | @serhiy-storchaka, @insolite, @miss-islington
PRs | <li>python/cpython#4225</li><li>python/cpython#6259</li><li>python/cpython#6431</li><li>python/cpython#6432</li><li>python/cpython#6436</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-04-10.08:04:26.762>
created_at = <Date 2017-11-02.08:37:20.895>
labels = ['3.8', 'type-bug', '3.7']
title = 'pygettext ignores directories as inputfile argument'
updated_at = <Date 2018-04-10.08:04:26.720>
user = 'https://github.com/insolite'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-10.08:04:26.720>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2018-04-10.08:04:26.762>
closer = 'serhiy.storchaka'
components = ['Demos and Tools']
creation = <Date 2017-11-02.08:37:20.895>
creator = 'Oleg Krasnikov'
dependencies = []
files = []
hgrepos = []
issue_num = 31920
keywords = ['patch']
message_count = 7.0
messages = ['305406', '305479', '305488', '315140', '315143', '315144', '315162']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'Oleg Krasnikov', 'miss-islington']
pr_nums = ['4225', '6259', '6431', '6432', '6436']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31920'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 3e26ea47-9edf-4ff1-9361-f447fe64d25d** [comment]
This happens because pygettext's `getFilesForName` calls `os.walk` as if it was `os.path.walk`. But the `walk` function has changed signature when moved from `os.path` to `os`. So now `_visit_pyfiles` is passed to `walk` as `topdown` argument which is obviously wrong and therefore `_visit_pyfiles` is never called.

**Comment by serhiy-storchaka** [comment]
Thank you for your patch Oleg. 3.4 and 3.5 are in security fixes only mode now.

Good catch, the usage of os.walk() in pygettext.py is incorrect. But your change is not enough. In \_visit_pyfiles() the name 'CVS' is removed from the names list. If names is a list of directories emitted by os.walk(), this would exclude the whole directory CVS from searching. But if it is a new list "dirs + files", this doesn't have any effect. And directories with the ".py" extension shouldn't be added to the list of Python files. Hence \_visit_pyfiles should take two separate lists for directories and files. And since it no longer is a callback, it would be better to inline its code.

There are tests for pygettext in [Lib/test/test_tools/test_i18n.py](https://github.com/python/cpython/blob/main/Lib/test/test_tools/test_i18n.py). It would be nice to add a new test for the fixed feature.

**Comment by 3e26ea47-9edf-4ff1-9361-f447fe64d25d** [comment]
Thanks for quite sensible notes Serhiy. I've fixed all that in recent commit and added a regression test. Still not sure about "testing conventions" here cause this is my first PR to python repository, so please let me know if something is wrong and I'll fix that.
