### ISSUE TITLE
idle_test: failures on x86 Windows7 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76152]
BPO | [31971](https://bugs.python.org/issue31971)
--- | :---
Nosy | @terryjreedy, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#4330</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2018-05-29.21:55:49.447>
created_at = <Date 2017-11-07.15:23:17.270>
labels = ['3.7', 'expert-IDLE', 'type-bug', 'tests']
title = 'idle_test: failures on x86 Windows7 3.x'
updated_at = <Date 2018-05-29.21:55:49.447>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-29.21:55:49.447>
actor = 'vstinner'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2018-05-29.21:55:49.447>
closer = 'vstinner'
components = ['IDLE', 'Tests']
creation = <Date 2017-11-07.15:23:17.270>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31971
keywords = ['patch']
message_count = 7.0
messages = ['305763', '305805', '305806', '305814', '308401', '308422', '318109']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'vstinner', 'serhiy.storchaka']
pr_nums = ['4330']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31971'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/#/builders/58/builds/122

\======================================================================
ERROR: tearDownClass (idlelib.idle_test.test_configdialog.KeysPageTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\idlelib\idle_test\test_configdialog.py", line 701, in tearDownClass
    del page.set_keys_type, page.load_keys_list
AttributeError: set_keys_type
```

======================================================================
FAIL: test_set_keys_type (idlelib.idle_test.test_configdialog.KeysPageTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\idlelib\idle_test\test_configdialog.py", line 859, in test_set_keys_type
    eq(d.custom_keyset_on.state(), ('selected',))
AssertionError: Tuples differ: ('selected', 'hover') != ('selected',)
First tuple contains 1 additional elements.
First extra element 1:
'hover'
- ('selected', 'hover')
?             
```
--------
\+ ('selected',)

**Comment by terryjreedy** [comment]
The failure in tearDownClass is a side-effect of the failure in test_set_keys causing 'p.set_keys_type = Func' being skipped.  That could be prevented with 'try:\<anything that could fail\>finally: p.set_keys_type = Func'.

I am completely puzzled at the sudden failure on one machine.  configdialog and test_configdialog were lasted changed 11 days ago (10/27) by Serhey's patch to make font samples editable.  test_idle passed consistently everywhere, including that machine, until build 121, 16 hours ago, and then suddenly started failing, consistently, on that one machine (as far as I know).  It continues to pass on my Win 10 machine, freshly updated with Python rebuilt.  I also checked the git log for tkinter.\_\_init__ and tkinter.ttk and they have not been changed either.

The failure message is also a surprise.  'custom_keyset_on' is a ttk Radiobutton.
https://docs.python.org/3/library/tkinter.ttk.html#widget-states
does not list 'hover' as a state.  However
https://www.tcl.tk/man/tcl8.6/TkCmd/ttk_widget.htm#M-state
does (so the doc needs fixing): "The mouse cursor is within the widget."

Perhaps 'hover' is a result of previous mouse cursor positioning from event_generates in the font tab test.  (Why the sudden change on one system would still be a puzzle.)  If this is the reason, then I only need to worry about this one state test.

Otherwise, I would have to think about either parking the cursor where it cannot interfere, or about minimizing the dialog when it does not need to be de-iconified for event_generate to work.

Serhiy, any thoughts on this?

**Comment by terryjreedy** [comment]
In build 129, which finished perhaps 3 hours ago, test_idle passed again.  I think we should merge the fix anyway in case 'hover' appears again on some machine.

A similar try:except is needed elsewhere.

**Comment by vstinner** [comment]
> I am completely puzzled at the sudden failure on one machine.

The "x86 Windows7 3.x" buildbot worker is very slow. So this bug is probably a race condition which is hard to trigger on a fast machine.
