### ISSUE TITLE
test_c_locale_coercion fails when the default LC_CTYPE != "C"

### ISSUE THREAD

**Issue by embray** [python/cpython#76183]
BPO | [32002](https://bugs.python.org/issue32002)
--- | :---
Nosy | @ncoghlan, @xdegaye, @embray
PRs | <li>python/cpython#4361</li><li>python/cpython#4369</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-11-10.10:47:52.200>
labels = ['3.7', 'type-bug', 'tests']
title = 'test_c_locale_coercion fails when the default LC_CTYPE != "C"'
updated_at = <Date 2020-06-28.07:34:48.407>
user = 'https://github.com/embray'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-28.07:34:48.407>
actor = 'ncoghlan'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2017-11-10.10:47:52.200>
creator = 'erik.bray'
dependencies = []
files = []
hgrepos = []
issue_num = 32002
keywords = ['patch']
message_count = 11.0
messages = ['306019', '306022', '306023', '306027', '306036', '306078', '306079', '306083', '307785', '308466', '372506']
nosy_count = 3.0
nosy_names = ['ncoghlan', 'xdegaye', 'erik.bray']
pr_nums = ['4361', '4369']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32002'
versions = ['Python 3.7']
```

</p></details>

**Comment by embray** [comment]
Several of the tests in test_c_locale_coercion (particularly LocaleCoercionTests.\_check_c_locale_coercion) tend to assume that the system default locale used when setting setlocale(category, "") and when all the relevant environment variables are empty/blank will be the "C"/"POSIX" locale.

While this is often true POSIX does not require this to be the case.  For example on Cygwin it already defaults to "C.UTF-8", so these tests fail because they assume the legacy coercion will be used, when it isn't (e.g. the LC_CTYPE environment variable does not get forced to "C.UTF-8").  In principle this can affect any platform, however, that chooses a different default.

**Comment by ncoghlan** [comment]
bpo-30672 is potentially related here - some of the test cases are already disabled on Mac OS X and other \*BSD systems since the tests assume that C & POSIX are aliases of each other.

I've also added Xavier to the nosy list, since the current implementation and tests aren't quite right for Android either and it would be good to come up with a unified solution to more robust platform feature detection: https://bugs.python.org/issue28180#msg305850

**Comment by embray** [comment]
Yes, I looked at some of the other issues pertaining to this, but it wasn't immediately apparent how to kill multiple birds with one stone, so here I just focused on this one assumption.

**Comment by ncoghlan** [comment]
OK, I'd been meaning to get back to refactoring those tests anyway, so assigning this to myself.

I'm thinking that the right way to go will be to give the test case a more explicit model of "expected platform behaviour" (initialised in setupModule), rather than having that be implicit in a bunch of conditionals scattered throughout the individual test cases.

Then we'd have at least the following cases:

- default is C, POSIX is an alias for C (most Linux distros)
- default is C, POSIX is a separate locale (*BSD)
- default is C.UTF-8 (Cygwin, potentially Android depending on exactly how we resolve that)

**Comment by embray** [comment]
In my PR there's a behavior test for the default, so we don't have to hard-code that on a per-platform basis at least.  The C != POSIX thing I'm not sure you can easily test for.

**Comment by ncoghlan** [comment]
The essential problem in both this issue and bpo-30672 is that the tests are currently incorporating some Linux-specific assumptions about ways to request the "C" locale.

In https://github.com/python/cpython/pull/4369, I've taken the approach of making the baseline tests only cover "C" and "invalid.ascii", and then explicitly \*opt-in* to testing an empty locale and "POSIX" on Linux machines.

If that's enough to get the test passing on Cygwin, I'm inclined to leave it at that. Dynamically calculated test expectations always make me nervous, since it's all too easy to end up with bugs that impact both the test case and the expectation calculator in the same way, and hence end up with the test passing when it should really fail.

**Comment by ncoghlan** [comment]
Note: I'm not entirely sold on my own argument though, as I believe at least Alpine Linux already interprets the empty locale as C.UTF-8, so it may make more sense to use your dynamic check with both the empty string and "POSIX", and only testing those locales if they get reported back as effectively configuring the "C" locale.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
> Several of the tests in test_c_locale_coercion (particularly LocaleCoercionTests.\_check_c_locale_coercion) tend to assume that the system default locale used when setting setlocale(category, "") and when all the relevant environment variables are empty/blank will be the "C"/"POSIX" locale.
>
> While this is often true POSIX does not require this to be the case.

I think you are right. The section starting with "The values of locale categories shall be determined by a precedence order;" in [1] states:

4. If the LANG environment variable is not set or is set to the empty string, the implementation-defined default locale shall be used.

In the current implementation of [PR 4334](https://github.com/python/cpython/pull/4334) [2] only one change to test_c_locale_coercion is needed to fix the failures of some subtests of test_PYTHONCOERCECLOCALE_set_to_warn when all the locale envt variables are set to the empty string. All the other tests are unchanged and ok because the new \_Py_SetLocaleFromEnv() function [3] causes Android to behave as a plain \*nix platform except when the locale envt variables are unset or set to an empty string.

[1] http://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html
[2] [PR 4334](https://github.com/python/cpython/pull/4334): Fix the implementation of PEP-538 on Android
[3] And because after calling setlocale(category, "C"), setlocale(category) returns "C" on Android (this may not be the case on Cygwin).

**Comment by erlend-aasland** [comment]
Closing, as the OP has not responded after multiple pings on the linked PR.
