### ISSUE TITLE
Doc for comparison of sequences with non-orderable elements

### ISSUE THREAD

**Issue by 7ce1a323-7d55-40f6-b97f-d80c3d15e7dc** [python/cpython#76299]
BPO | [32118](https://bugs.python.org/issue32118)
--- | :---
Nosy | @rhettinger, @terryjreedy, @bitdancer, @dubslow
PRs | <li>python/cpython#4514</li><li>python/cpython#15450</li><li>python/cpython#15466</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2019-08-24.17:53:33.785>
created_at = <Date 2017-11-23.04:27:01.138>
labels = ['type-feature', '3.7', 'docs']
title = 'Doc for comparison of sequences with non-orderable elements'
updated_at = <Date 2019-08-24.17:53:33.785>
user = 'https://github.com/Dubslow'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-24.17:53:33.785>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2019-08-24.17:53:33.785>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-11-23.04:27:01.138>
creator = 'Dubslow'
dependencies = []
files = []
hgrepos = []
issue_num = 32118
keywords = ['patch']
message_count = 8.0
messages = ['306780', '306782', '306827', '306928', '306976', '307107', '350383', '350385']
nosy_count = 5.0
nosy_names = ['rhettinger', 'terry.reedy', 'r.david.murray', 'docs@python', 'Dubslow']
pr_nums = ['4514', '15450', '15466']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32118'
versions = ['Python 3.7']
```

</p></details>

**Comment by 7ce1a323-7d55-40f6-b97f-d80c3d15e7dc** [comment]
In sequence comparisons, the enforcement of reflexivity of elements means that only non-identical elements are actually compared. The docs then note, with example, that non-reflexive elements thus always "compare" equal inside the sequence.
    
    This patch adds a second corollary, that non-orderable singletons (e.g. None) will also not break sequence comparison.
    
    Yes, the consequence is logically derivable from the statement "element identity is compared first, and element comparison is performed only for distinct elements", but the first example is given because "For non-reflexive elements, the result is different than for strict element comparison, and may be surprising", which also holds for the example I add here: different from strict element comparison, which may lead to otherwise surprising results (it sure was surprising to me when I expected a list with Nones to fail to compare, hence why I went trawling through the docs). In the manner of the first example, explicit is better than implicit, and (I believe) it will be helpful for readers to have this second consequence demonstrated.

**Comment by 7ce1a323-7d55-40f6-b97f-d80c3d15e7dc** [comment]
The PR includes an unrelated one word grammar fix in the same file, that can be removed (by me or by someone else, IDC).

This is possibly backportable but I wouldn't know, and leave such decisions for someone who do.

**Comment by bitdancer** [comment]
The surprising thing is the behavior of NaN, which is \*not equal* to itself.

The statement about orderability says "...are ordered the same as their first unequal elements".  This is explicit and unambiguous, there is no difference in this context between the number 1 and the singleton None, or the reflexivity enforced on NaN: all are equal to the corresponding element from the other sequence.  The whole point of the paragraph is that \*no order test is done until the first unequal element is encountered*.

If we want to make this \*more* explicit, I would suggest simply adding the following sentence after the first example in the original paragraph: "This means that reflexive elements that are otherwise unorderable (such as None and NaN) do not trigger a TypeError during a comparison."

**Comment by rhettinger** [comment]
This whole section has become a mess an is now more complex that the underlying code.   Adding more caveats, special cases, and atypical examples will make it worse (rather like the U.S. tax code, another example of bad technical writing).

I recommend the whole section be rewritten, extracting the most general rules and with examples that cover the general rules.

There can then be brief separate paragraphs for language lawyers that cover what makes NaNs and None unusual (none of the comparison logic special cases these value -- their interesting behaviors are intrinsic to the object itself).

**Comment by terryjreedy** [comment]
(Raymond, I wrote this before reading your message, but I believe it provides what you requested.  There is nothing special about None that is relevant to sequence comparison.  Nans just happen to be the only built-in non-reflexive objects (that I know of, thank goodness).)

This issue is about order comparisons \*also* being defined on a single object in a sequence and therefore also possibly giving a different result.  Title revised to be clearer and short enough to all be visible.  Demonstration:

```pycon
>>> a = object()
>>> a == a, a != a  # but a < a, a <= a, a >= a, a > a raise TypeError
(True, False)
>>> la = [a]
>>> la == la, la != la, la < la, la <= la, la >= la, la > la
(True, False, False, True, True, False)
```


Comparison of two sequences infers from identity all 6 rich comparison results on a single object in corresponding positions of the two sequences.

This has nothing to do with the object being a singleton, other than a singleton being a single object.  The enforcement of reflexivity and enforcement of consistent order on single objects are related, but the latter did not have to follow from the first.  The presentation of order, in the patch, by reference to singletons and reflexivity, does not work.  As I said in review, the example is too long and wrongly placed.  I think using a generic object instead of None would also be better.

I would like to rewrite the sequence comparison paragraphs after the first as something like the following.
\---

Sequences compare lexicographically using comparison of corresponding elements.  The two objects are first compared for identity.  If they are distinct, they are compared normally.  If they are the same object, the self comparisons are inferred: '==', '\>=', and '\<=' are true, while '!=', '\>', and '\<' are false.

By design, the inferred self comparisons for sequences sometimes give different results than would strict element comparison.  Instances of an unordered class become ordered with respect to themselves instead of raising a TypeError.

```pycon
>>> a = object()
>>> a < a          # By default, objects are not ordered
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '>=' not supported between instances of 'object' and 'object'
>>> [a] < [a]
False              # Sequence comparison orders an object versus itself
```


Even anti-reflexive not-a-number values, for example, are treated as reflexive (meaning a == a always).

\<insert current nan example\> 
\---

This re-write describes sequence comparison in one paragraph, instead of putting the details in the middle of the next paragraph.  The next paragraph describes the two possible consequences of inferring comparisons from identify: a result instead of a raise, and a different result.

**Comment by 7ce1a323-7d55-40f6-b97f-d80c3d15e7dc** [comment]
I like Terry's suggestion much better. I've closed my GitHub PR in favor of Terry's change.

My only suggested tweak might be throwing in something like "(e.g." None)", perhaps e.g. "Instances of an unordered class (e.g. None) become ordered...", but even as is, is a major improvement over mine. Thanks.
