### ISSUE TITLE
tracemalloc.Traceback.format() should have an option to reverse the traceback

### ISSUE THREAD

**Issue by pitrou** [python/cpython#76302]
BPO | [32121](https://bugs.python.org/issue32121)
--- | :---
Nosy | @pitrou, @vstinner, @serhiy-storchaka, @Jesse-Bakker
PRs | <li>python/cpython#4534</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-29.23:05:52.607>
created_at = <Date 2017-11-23.20:10:20.707>
labels = ['3.7', 'type-feature', 'library']
title = 'tracemalloc.Traceback.format() should have an option to reverse the traceback'
updated_at = <Date 2017-11-29.23:05:52.606>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-29.23:05:52.606>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-29.23:05:52.607>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2017-11-23.20:10:20.707>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 32121
keywords = ['patch']
message_count = 9.0
messages = ['306856', '306859', '306863', '306885', '306886', '306892', '306897', '307272', '307273']
nosy_count = 4.0
nosy_names = ['pitrou', 'vstinner', 'serhiy.storchaka', 'jbakker']
pr_nums = ['4534']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32121'
versions = ['Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
Right now tracemalloc.Traceback.format() returns the frames in "most recent call first" order.  This is not intuitive since ordinary Python tracebacks are displayed in "most recent call last" order.  It would be nice to add a `reverse` argument to change that.

**Comment by vstinner** [comment]
The option seems reasonable. Would you like to work on a pull request?

**Comment by 1378c70a-8509-4884-81bc-de196cbe148b** [comment]
I can work on this if you want. Can have a PR ready in a few minutes.

**Comment by vstinner** [comment]
tracemalloc.Traceback contains "raw" data from the C \_tracemalloc module. But since we are at Python level, we are free to change how data is rendered to user.

Since Antoine Pitrou was surprised by the current frame order in Traceback.format() ("This is not intuitive since ordinary Python tracebacks are displayed in "most recent call last" order"), what do you think of adding a new parameter but also \*\*reverse frames by default**?

Maybe we can go further and even reverse frames in Traceback constructor? This is a backward incompatible change, but I don't think that a lot of code in the wild uses the tracemalloc \*API*.

About the parameter name: I'm ok with "reverse". \*But* if we reverse by default, the "reverse" name can be confusing. Maybe we can use a less confusing name like "most_recent_last=True" (or "most_recent_first=False")?

--

Note: The faulthandler module also dumps starting with the "(most recent call first)", but I don't want to change that. It's for technical reason: faulthandler is called when something really bad happens and so Python internal structures may be corrupted. Moreover, frames is a single chained list, it's hard to iterate over them in the backward order (especially in faulthandler code where heap memory allocations are denied).

**Comment by pitrou** [comment]
> what do you think of adding a new parameter but also \*\*reverse frames by default**?

This would be fine with me.  I didn't want to suggest it because it would break compatibility but obviously I find the current behaviour annoying :-)

**Comment by serhiy-storchaka** [comment]
While we are here, what if make a negative limit truncating from the opposite side, as in the traceback module?

**Comment by vstinner** [comment]
Serhiy:
> While we are here, what if make a negative limit truncating from the opposite side, as in the traceback module?

Why not. I'm not opposed to that :-)

**Comment by vstinner** [comment]
New changeset 706e10b186992e086e661a62d2c8ec9588525b31 by Victor Stinner (Jesse-Bakker) in branch 'master':
bpo-32121: Add most_recent_first parameter to tracemalloc.Traceback.format (bpo-4534)
https://github.com/python/cpython/commit/706e10b186992e086e661a62d2c8ec9588525b31

**Comment by vstinner** [comment]
Jesse Bakker implemented all requested changes, I merged his PR. Well done, Jesse!
