### ISSUE TITLE
Change base class for futures.CancelledError

### ISSUE THREAD

**Issue by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [python/cpython#76709]
BPO | [32528](https://bugs.python.org/issue32528)
--- | :---
Nosy | @gvanrossum, @asvetlov, @cjerdonek, @socketpair, @dimaqq, @1st1, @achimnol, @miss-islington, @bmerry, @JustAnotherArchivist
PRs | <li>python/cpython#13528</li><li>python/cpython#21474</li><li>python/cpython#21475</li><li>python/cpython#21476</li><li>python/cpython#21606</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-05-27.12:45:50.368>
created_at = <Date 2018-01-10.16:31:15.055>
labels = ['3.8', 'type-feature', 'library', 'expert-asyncio']
title = 'Change base class for futures.CancelledError'
updated_at = <Date 2020-07-24.14:19:20.996>
user = 'https://github.com/socketpair'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-24.14:19:20.996>
actor = 'miss-islington'
assignee = 'none'
closed = True
closed_date = <Date 2019-05-27.12:45:50.368>
closer = 'yselivanov'
components = ['Library (Lib)', 'asyncio']
creation = <Date 2018-01-10.16:31:15.055>
creator = 'socketpair'
dependencies = []
files = []
hgrepos = []
issue_num = 32528
keywords = ['patch']
message_count = 21.0
messages = ['309772', '309775', '309776', '309777', '309779', '309796', '309799', '309800', '309894', '317705', '326274', '326275', '337839', '343618', '343619', '373166', '373510', '373511', '373650', '373940', '374185']
nosy_count = 11.0
nosy_names = ['gvanrossum', 'gustavo', 'asvetlov', 'chris.jerdonek', 'socketpair', 'Dima.Tisnek', 'yselivanov', 'achimnol', 'miss-islington', 'bmerry', 'JustAnotherArchivist']
pr_nums = ['13528', '21474', '21475', '21476', '21606']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32528'
versions = ['Python 3.8']
```

</p></details>

**Comment by Cartroo** [comment]
I know this is an old issue, but I just wanted to mention the parallel I note with the same change made for `GeneratorExit`, way back in Python 2.6 — as I recall, the justification then was much the same as the justification now.

Given the pain of these changes, I wonder if it's worth considering a particularly strenuous review process for exceptions added to any standard library modules to try to make the correct decisions of `Exception` vs `BaseException` up front, rather than having to have this debate about fixing them later.
