### ISSUE TITLE
Inconsistent behavior if globals is a dict subclass

### ISSUE THREAD

**Issue by d5fdb119-613c-451d-b1c0-d3c0c3358f9c** [python/cpython#76796]
BPO | [32615](https://bugs.python.org/issue32615)
--- | :---
Nosy | @brettcannon, @terryjreedy, @pfalcon, @vstinner, @methane, @pppery, @pablogsal
Superseder | <li>bpo-1402289: Allow mappings as globals (was: Fix dictionary subclass ...)</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-01-17.12:08:49.569>
created_at = <Date 2018-01-21.23:46:26.117>
labels = ['interpreter-core', 'type-feature', '3.9']
title = 'Inconsistent behavior if globals is a dict subclass'
updated_at = <Date 2020-01-17.20:09:57.927>
user = 'https://github.com/pppery'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-17.20:09:57.927>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2020-01-17.12:08:49.569>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2018-01-21.23:46:26.117>
creator = 'ppperry'
dependencies = []
files = []
hgrepos = []
issue_num = 32615
keywords = ['3.6regression']
message_count = 32.0
messages = ['310388', '310810', '310819', '310822', '359066', '359067', '359068', '359069', '359073', '359075', '359086', '359089', '359091', '360078', '360139', '360140', '360141', '360143', '360144', '360146', '360147', '360149', '360153', '360154', '360155', '360156', '360165', '360167', '360172', '360174', '360177', '360212']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'terry.reedy', 'pfalcon', 'vstinner', 'methane', 'ppperry', 'pablogsal']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = '1402289'
type = 'enhancement'
url = 'https://bugs.python.org/issue32615'
versions = ['Python 3.9']
```

</p></details>

**Comment by jgarvin** [comment]
I just got linked to this issue from discussion [here](https://discuss.python.org/t/why-can-you-change-globals-getitem-but-not-setitem/74097). I just want to add for any maintainers that read in the future: I use this feature and I stumbled on it because of reading the code that does it in [another library](https://github.com/amakelov/mandala/blob/f404c7e6ab7b37e16b382f13b1dd6d6cf7b8bcf3/mandala/deps/tracers/dec_impl.py#L97). So it's in use in the wild. As far as I know this is the only way to monitor global variable access robustly in Python. If there were a sys.monitoring hook instead that could also work but I think the potential perf impact is the same. Since the maintenance implication is "we need 2 versions, one that calls the function that assumes the type and one that doesn't" I don't find the maintenance argument super compelling, but I'm just a user that doesn't want their stuff broken. As is only being able to hook one direction is definitely inconsistent.

**Comment by BolunThompson** [comment]
Another [example of use](https://github.com/illinoisdata/kishu/blob/bdbdf24e00b49f3a9ad50eef974c78a5c1cb151e/kishu/kishu/jupyterint.py#L314). Here, the the tracked namespace is piped through IPython, but it ends up being [passed to exec](https://github.com/ipython/ipython/blob/5a3bf345ed7c78e5fab84faa81285e5fd9dfa3da/IPython/core/interactiveshell.py#L3670).
