### ISSUE TITLE
.pth files cannot contain folders with utf-8 names

### ISSUE THREAD

**Issue by 82b5851c-a8e8-4574-8699-6055d11cf3a6** [python/cpython#77102]
BPO | [32921](https://bugs.python.org/issue32921)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @ezio-melotti, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-02-23.13:03:18.090>
labels = ['type-bug', 'expert-unicode', 'OS-windows']
title = '.pth files cannot contain folders with utf-8 names'
updated_at = <Date 2018-03-05.17:53:23.182>
user = 'https://bugs.python.org/einaren'
```

bugs.python.org fields:
```python
activity = <Date 2018-03-05.17:53:23.182>
actor = 'steve.dower'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Unicode', 'Windows']
creation = <Date 2018-02-23.13:03:18.090>
creator = 'einaren'
dependencies = []
files = []
hgrepos = []
issue_num = 32921
keywords = []
message_count = 2.0
messages = ['312635', '313273']
nosy_count = 7.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'ezio.melotti', 'zach.ware', 'steve.dower', 'einaren']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32921'
versions = ['Python 3.6']
```

</p></details>

### Linked PRs
* gh-117802
* gh-117917
* gh-117918

**Comment by zooba** [comment]
> Is this a valid bug, or is it considered a `wontfix`/not a bug at all?

It's valid, but unfortunately not fixable outside of changing the default encoding for the entire process.

> Considering the [Python uses UTF-8 by default for source files](https://peps.python.org/pep-0686/), and that `.pth` are kind of source files ...

Being able to include code in the files is the weird bit, and is likely to be removed well before the default encoding is changed. If it were meant to be a source file, it'd have a `.py` extension (like `sitecustomize.py` does).

> if at a later stage the users set `PYTHONUTF8` or invoke `python -X utf8`, these files would stop working

Yep, which is why users have to opt-in to these options, and if it breaks then they need to opt-out or fix it themselves. Other tools don't need to be concerned about this scenario - just use the default encoding.

> do you have any advice on how to handle this?

Use a regular `open(path, 'w')` call to write to the file, suppressing a warning if needed.

Unfortunately, it seems it [currently requests locale encoding explicitly](https://github.com/python/cpython/blob/main/Lib/site.py#L175) to read, when it ought to be using the default. If it were the default, everyone would get onto UTF-8 when that default changes, but as it stands it'll be stuck on locale encoding forever. So I guess the advice is to explicitly use locale encoding until we fix that.

**Comment by abravalheri** [comment]
Thank you very much @zooba, I am working on https://github.com/pypa/setuptools/pull/4009 trying to follow this recommendation.

**Comment by methane** [comment]
Sorry for delay. I believe pth file encoding should follow utf-8 mode.

When I implemented https://github.com/python/cpython/commit/4827483f47906fecee6b5d9097df2a69a293a85c, I used "locale" encoding because setuptools used locale encoding.
Now setuptools used locale encoding because of I used locale encoding. This is really sad.

How do you think this, @abravalheri :

* Since Python 3.13, we use only UTF-8 for pth files.
* For Python 3.11/3.12, follow UTF-8 mode. (e.g. `encoding="utf-8" if sys.flags.utf8_mode else "locale"`)

**Comment by vstinner** [comment]
Can we try to decode from UTF-8, and fallback on locale on decode error?

**Comment by methane** [comment]
Yes. pth files are small for most cases.
We can use StringIO instead of TextIOWrapper there.

**Comment by abravalheri** [comment]
> Can we try to decode from UTF-8, and fallback on locale on decode error?

I think this is a good idea, for the following reason: the creation of the `.pth` file is independent of running the `.pth` file (i.e. `setuptools` creates the file and CPython runs it). So it is difficult to "match" the specific version of `setuptools` and CPython and the different levels of support (e.g. old setuptools + new CPython, new setuptools + old CPython).

> * Since Python 3.13, we use only UTF-8 for pth files.
> * For Python 3.11/3.12, follow UTF-8 mode. (e.g. `encoding="utf-8" if sys.flags.utf8_mode else "locale"`)

Assuming that we are talking about editable installations[^1], my feedback on the suggestions is the following:

1. > `Since Python 3.13, we use only UTF-8 for pth files`
    
    That is easy for setuptools to handle.
    We can check for  `sys.version_info >= (3, 13)` as an indicator of the capability of processing UTF-8 `.pth` files.

2. > `For Python 3.11/3.12, follow UTF-8 mode` it

    What would be the suggestion of the capability check? Something like the following?
    ```python
    if (
       sys.version_info >= (3, 11, X) and sys.version_info < (3, 12)
       or sys.version_info >= (3, 12, Y)
    ):
    ```
    This is a bit less trivial to maintain since it requires to keep an eye on the release cadence of CPython.

[^1]: As far as I know that is the only non-deprecated use case that uses `.pth`, but I don't claim to understand 100% of setuptools/distutils 😅. The implication of "editable installations" is that the Python used during the build process is the same Python that will be used for the installation and runtime (as far as I understood from PEP 660).

**Comment by zooba** [comment]
UTF-8 mode is a runtime option rather than a build option, so I don't know that you'd want to use it to create a persistent config file like this. It's not really reasonable to expect UTF-8 mode to be consistently on between install processes and application runtime.

You're probably just as well defaulting to UTF-8 all the time, and offer an obscure environment variable setting to switch back to `'locale'` for those who actually hit problems (telling them to run in UTF-8 mode is also an option, but likely too big an ask if they're that stuck).

Maybe on 3.12 and earlier you could even try encoding to ASCII and print a warning that Python may not be able to load it?

The sooner we make it start reading UTF-8 and then fall back to locale, the better.

**Comment by pfmoore** [comment]
It's worth noting that tools which use the `editables` library will also write `.pth` files for support of editable installations (`editables` returns the file name and content as strings, the calling tool needs to choose the encoding when writing the file). And people can manually write their own. I think the important thing here is to define a standard that tools can work to. Normally I'd suggest it should be a packaging standard, but `.pth` files are a core feature, so that might not work. I don't know where a rule like this, for a core Python feature that needs to be documented across versions, should be published - expecting users to check the 3.11, 3.12 and 3.13+ documentation for `.pth` files and work out the differences themselves seems rather hostile 🙁

From the perspective of a tool (or user) *writing* a `.pth` file, I think the rule should be "use UTF-8 for Python 3.13 or later, and the default locale for Python 3.12 and earlier". It's easy to know what the target Python is, as you're typically writing the file into the site-packages for that installation. It's too late to change the default for 3.12, so this is really the only possible option.

From the perspective of the core reading `.pth` files, I'd try UTF-8 first, and in the case of an encoding error (as @vstinner suggested) fall back to the default encoding. I'd be inclined to leave the fallback in place even in 3.13+ to support users still using older tools - but I could accept 3.13 applying the stricter "only UTF-8" rule.

I don't think we should bring UTF-8 mode into it, as that's a runtime choice (and `.pth` files are static, not affected by runtime settings).

**Comment by methane** [comment]
Locale encoding is also a runtime configuration. When you switch languages on Windows or change environment variables on Linux, it changes. UTF-8 Mode helps ensure that the virtual environment is not destroyed by changes in language or environment variables.

When I proposed PEP 597, I did not have plans to make UTF-8 Mode the default. site.py supported UTF-8 Mode up to Python 3.9, but when we implemented PEP 597, I stopped supporting it.

However, I realized that the feasibility of a migration process using EncodingWarnings is very low. I proposed PEP 686, which is a migration process using the UTF-8 Mode, and it was approved. In UTF-8 Mode, we should use UTF-8 in all places unless there is a special reason not to.

So I think supporting UTF-8 mode again in 3.11/3.12 is good idea. It is compatible to 3.9. It provides reason to opt-in UTF-8 mode before Python 3.15.

Another way to support UTF-8 pth file is https://github.com/python/cpython/pull/117802 . It tries UTF-8 and fallbacks to locale encoding. I'm OK for it too.

Anyway, Python is a glue language, and interoperability with other languages is important. I don't want to force the uv developers to use a huge number of codecs that works 100% same to Python codecs to handle locale encoding. I want to provide a way to use UTF-8 in not only Python 3.13 but also Python 3.11 and 3.12 as well.

**Comment by methane** [comment]
Maybe, #117802 would be better idea for now. setuptools uses locale encoding and uv uses utf-8.
It would be better to support both of utf-8 and locale encoding in one mode.

**Comment by hauntsaninja** [comment]
(possibly dumb question) uv doesn't provide a build backend, so when is it writing pth files?

**Comment by pfmoore** [comment]
`uv venv` writes a `.pth` file, as you noticed, but it's ASCII-only. That's the only time `uv` writes a `.pth` file itself (as far as I know) - any other `.pth` files will come from installing projects, and those projects will have their own build backend (specified in the project's `pyproject.toml` file).

The only difficulty from `.pth` files created in the install process is likely to come from editable mode installs, as has been discussed here. Those files include the absolute path of the project source directory, and that can be non-ASCII (for example, if it's in the user's home directory and the user has a username that includes non-ASCII characters).

There *are* other problem cases:

1. `.pth` files created manually by the user, which can contain anything the user chooses.
2. `.pth` files included in a project, which put subdirectories installed by the project onto `sys.path`. For example, `pywin32` does this. But actually, the only example of this that I know of is `pywin32`, and that has ASCII names, so this might well be a non-issue.

For (1), we need to document the rules properly, and then it's up to the user to follow them - if the user wants to add a site-packages directory (via `$PYTHONPATH`, for instance) that is shared across Python versions, making that work is on them, I guess[^1].

For (2), things are similar, as the same package could be installed in different Python versions. I doubt a project is going to want to publish different wheels for different Python versions, just to handle `.pth` file encodings. But as I said, it's quite possible that there are no packages that have this problem in any case.

[^1]: Supporting locale encoding as a fallback if there are UTF-8 errors until all Python versions that don't allow UTF-8 are out of support would help with this, though.

**Comment by methane** [comment]
> `uv venv` writes a `.pth` file, as you noticed, but it's ASCII-only. That's the only time `uv` writes a `.pth` file itself (as far as I know) - any other `.pth` files will come from installing projects, and those projects will have their own build backend (specified in the project's `pyproject.toml` file).
>
> The only difficulty from .pth files created in the install process is likely to come from editable mode installs, as has been discussed here. Those files include the absolute path of the project source directory, and that can be non-ASCII (for example, if it's in the user's home directory and the user has a username that includes non-ASCII characters).

You are right. I thought pth files are created by `uv pip install -e` but it is created by the Hatch. Hatchling uses UTF-8 when building wheel for editable install:

* https://github.com/pypa/hatch/blob/c935e51cdf4b270cc95f3d1942bdb6a326ff6c41/backend/src/hatchling/builders/wheel.py#L557-L569
* https://github.com/pypa/hatch/blob/c935e51cdf4b270cc95f3d1942bdb6a326ff6c41/backend/src/hatchling/builders/wheel.py#L140-L142

Poetry uses `locale.getpreferredencoding()` that uses UTF-8 in UTF-8 mode.

* https://github.com/python-poetry/poetry/blob/cab9c42a0a09fd7aa22886254258d37c8fb931d3/src/poetry/masonry/builders/editable.py#L127-L129


> For (1), we need to document the rules properly, and then it's up to the user to follow them - if the user wants to add a site-packages directory (via $PYTHONPATH, for instance) that is shared across Python versions, making that work is on them, I guess[1](https://github.com/python/cpython/issues/77102#user-content-fn-1-3711ef8c87e781a597f8f6572cd063ae).

How about this plan?

* Python 3.11~3.13: Use UTF-8 and fallback to locale encoding.
* Python 3.14~3.15: Same to above but show EncodingWarning when fallback is used.
* Python 3.16~: UTF-8 only.

**Comment by abravalheri** [comment]
> How about this plan?
>
> Python 3.11~3.13: Use UTF-8 and fallback to locale encoding.
> Python 3.14~3.15: Same to above but show EncodingWarning when fallback is used.
> Python 3.16~: UTF-8 only.

LGTM.

Would the check `sys.version_info >= (3, 13)` be good enough for libraries producing `.pth` know when they can emit UTF-8?

**Comment by methane** [comment]
> Would the check `sys.version_info >= (3, 13)` be good enough for libraries producing `.pth` to know when they can emit UTF-8? (Ideally there should be a simple and easy to maintain condition that producers can check to see when using UTF-8 is guaranteed to work for the given Python installation).

Yes. UTF-8 support will be backported to 3.11 and 3.12 only for tools already produce UTF-8 `.pth` files.

**Comment by methane** [comment]
3.11 is security fix only mode. I backported this only to 3.12.

**Comment by vstinner** [comment]
Thanks @methane, use UTF-8 or fall back on locale encoding is a nice tradeoff.

**Comment by ncoghlan** [comment]
GH-119503 made a small tweak to ignore UTF-8 BOMs when reading .pth files (this aligns with the way source files are decoded)
