### ISSUE TITLE
Embedded 3.6.4 distribution does not add script parent as sys.path[0]

### ISSUE THREAD

**Issue by 778ba349-e395-41f1-a124-828b2a0e1b9d** [python/cpython#77192]
BPO | [33011](https://bugs.python.org/issue33011)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-03-06.17:25:59.654>
created_at = <Date 2018-03-06.11:12:50.382>
labels = ['type-bug', 'invalid', 'OS-windows']
title = 'Embedded 3.6.4 distribution does not add script parent as sys.path[0]'
updated_at = <Date 2018-03-06.17:25:59.653>
user = 'https://bugs.python.org/CongMonkey'
```

bugs.python.org fields:
```python
activity = <Date 2018-03-06.17:25:59.653>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2018-03-06.17:25:59.654>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2018-03-06.11:12:50.382>
creator = 'Cong Monkey'
dependencies = []
files = []
hgrepos = []
issue_num = 33011
keywords = []
message_count = 2.0
messages = ['313316', '313341']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'Cong Monkey']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33011'
versions = ['Python 3.6']
```

</p></details>

**Comment by dsuch** [comment]
Hello @zooba,

can this be reopened and re-evaluated, please?

I use the embedded Python version (now at 3.10) and I am getting at the same exact point as @ezio-melotti was at 3.6.

Let me start with an assumption that a good part of Windows programs are going to be turned into .exe using PyInstaller or py2exe.

Both of these currently depend on the future package - likely because they have had to maintain strict compatibility with Python 2.7 for a long time.

Trying to install future via "pip install future" - using embedded Python - results in the exception below.

At the end of the day, no one is at fault here, none of the authors of any of these tools, but the end result is that the end user, like myself, cannot combine them in a natural way - an embedded Python version that runs my programs turned into an .exe.

This is a real use case from a real world situation.

Thank you.

```
  Using cached future-0.18.2.tar.gz (829 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\dsuch\AppData\Local\Temp\pip-install-v1b626fl\future_050878e0e7d7463db3471c4baf6a0065\setup.py", line 86, in <module>
          import src.future
      ModuleNotFoundError: No module named 'src'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```

**Comment by zooba** [comment]
Try installing it with a regular Python into the directory where you have your embedded runtime. That's the intended use of this distro:

https://docs.python.org/3/using/windows.html#windows-embeddable
> Third-party packages should be installed by the application installer alongside the embedded distribution. Using pip to manage dependencies as for a regular Python installation is not supported with this distribution, though with some care it may be possible to include and use pip for automatic updates. In general, third-party packages should be treated as part of the application (“vendoring”) so that the developer can ensure compatibility with newer versions before providing updates to users.
