### ISSUE TITLE
[logging] add JSON log formatter

### ISSUE THREAD

**Issue by 9ea95f7c-b37a-46e2-b674-e8b33d4f0864** [python/cpython#77691]
BPO | [33510](https://bugs.python.org/issue33510)
--- | :---
Nosy | @brettcannon, @vsajip

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-05-15.07:48:53.786>
created_at = <Date 2018-05-14.22:20:20.543>
labels = ['3.8', 'type-feature', 'library']
title = '[logging] add JSON log formatter'
updated_at = <Date 2018-05-25.22:07:40.042>
user = 'https://bugs.python.org/steveha'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-25.22:07:40.042>
actor = 'wsanchez'
assignee = 'none'
closed = True
closed_date = <Date 2018-05-15.07:48:53.786>
closer = 'vinay.sajip'
components = ['Library (Lib)']
creation = <Date 2018-05-14.22:20:20.543>
creator = 'steveha'
dependencies = []
files = []
hgrepos = []
issue_num = 33510
keywords = []
message_count = 7.0
messages = ['316597', '316603', '316614', '316631', '316688', '316698', '317720']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'vinay.sajip', 'steveha', 'wsanchez']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue33510'
versions = ['Python 3.8']
```

</p></details>

**Comment by vsajip** [comment]
> most of the 3rd parties are using JSON for logging

Not trying to be difficult, but what's your evidence for "most"?

> could you reconsider this?

Reconsider what? I'm not opposed to JSON logging in any way. The cookbook illustrates how it can be done. I have some questions for you:

1. What is wrong with the [approach suggested in the cookbook](https://docs.python.org/3/howto/logging-cookbook.html#implementing-structured-logging)?
2. If I actually implement it in the stdlib, what guarantees are there that people won't complain that it doesn't meet the particular JSON schema they _want_ to use? You can pretty much guarantee that "one size won't fit all".

**Comment by Saphyel** [comment]
The approach in the cookbook kind of defeats the whole point of having formatters and introduces another _interface_ on top of the logging interface. `extra` already provides similar functionality as the `kwargs` in the StructuredMessage


Most of the companies follow this [approach](https://stackoverflow.com/a/70223539/5100104) or [using modules](https://docs.datadoghq.com/logs/log_collection/python/?tabs=jsonlogformatter)
There's a lot of services that provides log analysis which are primarily using json for the flexibility and to avoid to make more spam to other companies datadog is one of them and make sense... it's easier to parse a json than a syslog

**Comment by vsajip** [comment]
Right, and the cookbook example is just that, an example. So there are multiple solutions for people that want to log JSON, and they are free to use ... perhaps people pick specific ones because they fit their use cases better, and one particular one wouldn't suit them all. At least, I don't see one particular approach that would suit everyone, and that's why there's no implementation in the stdlib ... and by the way, some of the approaches you linked to use formatters ... my point is that there is nothing stopping you from logging to JSON and you're not making a case for why it needs to be in the stdlib. I've already said that I see the value of logging in JSON ... so why keep repeating arguments like "t's easier to parse a json than a syslog"? I'm not disagreeing on that point.
