### ISSUE TITLE
subprocess.Popen on a Windows batch file always acts as if shell=True

### ISSUE THREAD

**Issue by bda35265-33d6-4ce4-921c-c1e0d3bd3e42** [python/cpython#77696]
BPO | [33515](https://bugs.python.org/issue33515)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @AbigailBuccaneer
PRs | <li>python/cpython#8906</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-15.11:01:31.144>
labels = ['type-security', '3.8', '3.9', '3.10', 'library', 'OS-windows', 'docs']
title = 'subprocess.Popen on a Windows batch file always acts as if shell=True'
updated_at = <Date 2021-03-01.15:37:34.641>
user = 'https://github.com/AbigailBuccaneer'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-01.15:37:34.641>
actor = 'eryksun'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)', 'Windows']
creation = <Date 2018-05-15.11:01:31.144>
creator = 'abigail'
dependencies = []
files = []
hgrepos = []
issue_num = 33515
keywords = ['patch', 'security_issue']
message_count = 2.0
messages = ['316638', '316716']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'docs@python', 'zach.ware', 'eryksun', 'steve.dower', 'abigail']
pr_nums = ['8906']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue33515'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by gpshead** [comment]
closing as a duplicate of https://github.com/python/cpython/issues/78670

**Comment by fireattack** [comment]
Apologize for relaying in a closed ticket.

I've read this thread, #78670, #8906 in full, together with [this very helpful article](https://stackoverflow.com/questions/562038/escaping-double-quotes-in-batch-script/31413730#31413730) mentioned by @eryksun .  And I understand that weird behaviors occurs when you start escaping characters around due to various limitations of CMD and/or Windows API, and we have no plan to "fix" such non-issue.

What I still don't understand why a simple string with ampersand does not work when batch file is involved.

Considering the following test.bat file:
```bat
@echo off
echo %*
```

I can do `test.bat "a&b"` or `cmd.exe /c test.bat "a&b"` in command line, and they all print 
```
"a&b"
```
properly.

But it does not work if I use 
```py
import subprocess
subprocess.run(['test.bat', 'a&b'])
```
Which prints
```
a
'b' is not recognized as an internal or external command,
operable program or batch file.
```

According to https://github.com/python/cpython/issues/77696#issuecomment-1093785886:
> CreateProcess thus executes a .bat or .cmd script by prepending "%ComSpec% /c" to the command line.

They should be equivalent, aren't they?

Thanks in advance.

**Comment by zooba** [comment]
Presumably because `subprocess.run` does not add quotes to `a&b`. I suspect that `a & b` will work, and so might `"a&b"`.

Under normal command-line processing rules, there's no need to add quotes around `a&b`. It's a cmd.exe-specific rule, and we don't apply any cmd.exe-specific rules.
