### ISSUE TITLE
HTTP request-line parsing splits on Unicode whitespace

### ISSUE THREAD

**Issue by 20110076-1488-4c6b-a78a-d9f7d85840fe** [python/cpython#78154]
BPO | [33973](https://bugs.python.org/issue33973)
--- | :---
Nosy | @vstinner, @ezio-melotti, @tipabu
PRs | <li>python/cpython#7932</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-06-26.18:39:29.435>
labels = ['type-bug', '3.8', '3.9', '3.7', 'library', 'expert-unicode']
title = 'HTTP request-line parsing splits on Unicode whitespace'
updated_at = <Date 2020-01-25.13:18:38.086>
user = 'https://github.com/tipabu'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-25.13:18:38.086>
actor = 'cheryl.sabella'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Unicode']
creation = <Date 2018-06-26.18:39:29.435>
creator = 'tburke'
dependencies = []
files = []
hgrepos = []
issue_num = 33973
keywords = ['patch']
message_count = 2.0
messages = ['320507', '320529']
nosy_count = 3.0
nosy_names = ['vstinner', 'ezio.melotti', 'tburke']
pr_nums = ['7932']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33973'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by tipabu** [comment]
Note that this is still an issue; tested anew on 3.10.12, 3.11.7, 3.12.1, and a 3.13 alpha.

**Comment by encukou** [comment]
I'm sorry for only getting to this PR now.
IMO, there are three issues to consider:
- Compatibility with the specification
- Compatibility with older versions of Python -- 2.x and 3.x

Since this is about illegal (unquoted) requests, the first point doesn't cone into play much, except that this with this PR, we lose support for alternate ASCII whitespace (HTAB, VT (%x0B), FF (%x0C), or bare CR) which is mentioned in RFC 9112.

Regarding compatibility with earlier 3.x versions: turning `split()` into `split(' ')` means
- runs of more than one whitespace are no longer collapsed
- leading/trailing whitespace is no longer ignored

Both could break software that relies on *those* non-standard quirks.

That leaves compatibility with Python 2. However, in 2024, this point has lost its importance. (Again, sorry for getting to this late.)

I would prefer closing this issue and PR. With Python 2 gone, this would be trading one set of non-standard semantics for another.

Or perhaps we could heed the RFC's warning about lenient parsing, and -- with a deprecation period -- make the parsing strict: reject all unexpected characters, including all non-ASCII ones, misplaced spaces, etc.

**Comment by encukou** [comment]
I plan to close the issue and PR in a month if there are no objections.

**Comment by tipabu** [comment]
We can go ahead and close it. Even if I had the bandwidth to rework the PR to tighten parsing rules and follow through on a deprecate-remove cycle, the software I was working on that caused me to discover the issue still wouldn't be able to make use of the change. At some point, it probably needs to just stop relying on stdlib for HTTP parsing all together.

At least this bug doesn't have any (obvious) security implications; if you have a chance, I'd appreciate some thoughts around https://github.com/python/cpython/issues/81274 / https://github.com/python/cpython/pull/13788
