### ISSUE TITLE
Reproducible pyc: FLAG_REF is not stable.

### ISSUE THREAD

**Issue by methane** [python/cpython#78274]
BPO | [34093](https://bugs.python.org/issue34093)
--- | :---
Nosy | @vstinner, @benjaminp, @methane, @ericsnowcurrently, @serhiy-storchaka, @ctismer, @yan12125
PRs | <li>python/cpython#8226</li><li>python/cpython#8293</li><li>python/cpython#28379</li>
Files | <li>[bm_marshal.py](https://bugs.python.org/file47683/bm_marshal.py "Uploaded as text/plain at 2018-07-11.13:07:26 by @methane")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-07-11.10:36:33.741>
labels = ['interpreter-core', 'type-bug', '3.11']
title = 'Reproducible pyc: FLAG_REF is not stable.'
updated_at = <Date 2021-09-20.15:21:12.255>
user = 'https://github.com/methane'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-20.15:21:12.255>
actor = 'eric.snow'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2018-07-11.10:36:33.741>
creator = 'methane'
dependencies = []
files = ['47683']
hgrepos = []
issue_num = 34093
keywords = ['patch']
message_count = 14.0
messages = ['321435', '321448', '321521', '321523', '321524', '321527', '321528', '321529', '321611', '321622', '347970', '401979', '402236', '402244']
nosy_count = 7.0
nosy_names = ['vstinner', 'benjamin.peterson', 'methane', 'eric.snow', 'serhiy.storchaka', 'Christian.Tismer', 'yan12125']
pr_nums = ['8226', '8293', '28379']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue34093'
versions = ['Python 3.11']
```

</p></details>

**Comment by encukou** [comment]
Since this is no longer needed by CPython, I recommend closing the issue (and PR).
Full disclosure: I helped with a third-party project that implements the second pass: https://github.com/fedora-python/marshalparser
IMO, having a second pass on PyPI is fine.

I'll close next week if there are no objections.

**Comment by vstinner** [comment]
> Since this is no longer needed by CPython, I recommend closing the issue (and PR).

Do you mean that the initial issue was fixed? PYC are now reproducible?

**Comment by encukou** [comment]
No. I mean that they don't need to be reproducible. See Guido's comment: https://github.com/python/cpython/pull/28379#issuecomment-948180606

**Comment by vstinner** [comment]
Ok, but this issue is about making PYC files reproducible to [reproducible builds](https://reproducible-builds.org/).

@methane: What do you think?

**Comment by methane** [comment]
Wheel doesn't contain pyc files. So Python ecosystem around PyPI doesn't need reproducible pyc.

> Full disclosure: I helped with a third-party project that implements the second pass: https://github.com/fedora-python/marshalparser
> IMO, having a second pass on PyPI is fine.

I think its fine too.

**Comment by SomberNight** [comment]
>> Ok, but this issue is about making PYC files reproducible to [reproducible builds](https://reproducible-builds.org/).
>
> Wheel doesn't contain pyc files. So Python ecosystem around PyPI doesn't need reproducible pyc.

Wheels might not use pyc but other downstream build artifacts might want to include pyc files for performance reasons while remaining reproducible themselves.

Specifically, the [python-for-android](https://github.com/kivy/python-for-android/blob/2a4dd96a135c542181bc8c0b9bafc3c8e3835434/pythonforandroid/recipes/python3/__init__.py#L383-L388) project packages pyc files inside `.apk`s instead of source .py files to make applications start up faster when opened on Android. To have the apk itself reproducibly built, the pyc files need to be reproducible.

Another example is .AppImage on desktop linux. If the appimage bundles .pyc files, it makes the program launch faster. It makes sense to do the pyc compilation at build-time and package it inside the binary, instead of doing the pyc compilation on the enduser's machine on every app launch. To have the .AppImage reproducibly built, the pyc files need to be reproducible.

**Comment by methane** [comment]
@SomberNight We know it. What we talked about is 3rd party tool can implement reproducible pyc build. So marshal don't need to implement it.
