### ISSUE TITLE
urllib.parse doesn't round-trip file URI's with multiple leading slashes

### ISSUE THREAD

**Issue by cjerdonek** [python/cpython#78457]
BPO | [34276](https://bugs.python.org/issue34276)
--- | :---
Nosy | @cjerdonek, @vadmium, @tirkarthi, @vladima, @epicfaace
PRs | <li>python/cpython#15297</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-07-30.04:39:03.225>
labels = ['3.7', '3.8', 'type-bug', 'library', '3.9']
title = "urllib.parse doesn't round-trip file URI's with multiple leading slashes"
updated_at = <Date 2019-08-27.01:16:36.907>
user = 'https://github.com/cjerdonek'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-27.01:16:36.907>
actor = 'epicfaace'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-07-30.04:39:03.225>
creator = 'chris.jerdonek'
dependencies = []
files = []
hgrepos = []
issue_num = 34276
keywords = ['patch']
message_count = 9.0
messages = ['322652', '322671', '322674', '322675', '322716', '322722', '322737', '322756', '324718']
nosy_count = 6.0
nosy_names = ['chris.jerdonek', 'martin.panter', 'piotr.dobrogost', 'xtreak', 'v2m', 'epicfaace']
pr_nums = ['15297']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue34276'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-113563

**Comment by serhiy-storchaka** [comment]
Initially the condition was added in f3963b1269a9f4fde99724524a7afe81e974aa62, specially to handle `file:` URLs starting with 4 slashes.

https://github.com/python/cpython/commit/f3963b1269a9f4fde99724524a7afe81e974aa62#diff-c272b33cfc076b56637b73ae6fecd13ca0b999883a0a48b16a5c564b24bdb4c3R115

```py
       if netloc or (scheme in uses_netloc and url[:2] == '//'):
```

But it was wrong for `file:` URLs starting with 3 slashes, so the condition was negated in 7dfb6e295b4e4a8a5554debaf93e260c30725f18 (bpo-591713/gh-36991).

https://github.com/python/cpython/commit/7dfb6e295b4e4a8a5554debaf93e260c30725f18#diff-c272b33cfc076b56637b73ae6fecd13ca0b999883a0a48b16a5c564b24bdb4c3R131

```py
       if netloc or (scheme in uses_netloc and url[:2] != '//'):
```

Since the first change was without tests, its initial purpose was lost.

I believe that the right condition should be
```py
    if netloc or (scheme and scheme in uses_netloc) or url[:2] == '//':
```
Even if `netloc` is empty and `scheme` is empty or not require a netloc, `//` should be added if the path starts with `//`, otherwise the first component of the part will be confused with a netlock when parse.

**Comment by vadmium** [comment]
After seeing that the “mailto:” RFC 6068 says slashes (/) have to be encoded in e.g. mailto:%2F%2Flocal@domain, I agree with adding the extra double-slash (//) regardless of scheme. (Previously I believed mailto://local@domain to be valid for an address of //local@domain, but I take that back.)
