### ISSUE TITLE
Declare sethostname in socketmodule.c for SOLARIS

### ISSUE THREAD

**Issue by 13b30afb-96a7-452c-8b5c-a29fad711cf0** [python/cpython#78469]
BPO | [34288](https://bugs.python.org/issue34288)
--- | :---
Nosy | @r-bit-rry, @johngh

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-07-31.07:32:32.085>
labels = ['build', '3.7']
title = 'Declare sethostname in socketmodule.c for SOLARIS'
updated_at = <Date 2019-05-15.15:53:46.806>
user = 'https://github.com/r-bit-rry'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-15.15:53:46.806>
actor = 'John Harrison'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2018-07-31.07:32:32.085>
creator = 'rbelio'
dependencies = []
files = []
hgrepos = []
issue_num = 34288
keywords = []
message_count = 2.0
messages = ['322742', '342581']
nosy_count = 2.0
nosy_names = ['rbelio', 'John Harrison']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue34288'
versions = ['Python 3.7']
```

</p></details>

### Linked PRs
* gh-109447
* gh-110580
* gh-110581

**Comment by vstinner** [comment]
@kulikjak: In PR #108817 we did the opposite, remove ``gethostname()`` prototype. Is this issue about ``sethostname()`` still relevant in 2023 on Solaris?

**Comment by kulikjak** [comment]
Hi, since this is reported in Solaris 10 (which is before Solaris was first opened, so only Sun/Oracle is affected here), I had to dive into history a little bit.

- `gethostname` is available in Solaris 10 header files (at least in reasonably recent one), so no problem there.
- `sethostname` is indeed missing from Solaris 10 headers (and wasn't even available in Solaris 11 since the beginning https://github.com/illumos/illumos-gate/commit/eec1faa811b20b01f0173edcf9179c3c6ad48243 - though that was fixed 17 years ago so we don't have to worry about that...)

I don't think it's a secret that we don't plan to release any new official Python 3.x package for Solaris 10 (which is in the extended support stage intended for critical fixes only), so this is not relevant to us. But that also means that those still using it might want to build newer Python for it themselves.

What's unfortunate is that simply adding the definition would cause at least redefinition warnings on current Solaris.

**Comment by vstinner** [comment]
Can't you test the Solaris version in the preprocessor (#ifdef)? Feel free to propose a PR.

**Comment by kulikjak** [comment]
Developer Studio compiler provides handy macros like `__SunOS_5_10`, but sadly, GCC doesn't.

I guess I can define something like that via configure with `uname -r`, though. Then it would be simple a `#ifdef`.

**Comment by vstinner** [comment]
> I guess I can define something like that via configure with uname -r, though. Then it would be simple a #ifdef.

Yeah, that should be good enough.

**Comment by erlend-aasland** [comment]
Thanks for the report, @r-bit-rry, and thanks for the fix, @kulikjak, and thanks for the review, @vstinner.

Marking this as resolved; the backports are approved and queued for merging.
