### ISSUE TITLE
"__lltrace__"  seems to be wrong , "__ltrace__" is correct in Misc/SpecialBuilds.txt

### ISSUE THREAD

**Issue by bdf615be-f251-4be8-a209-43c8f55880ba** [python/cpython#78607]
BPO | [34426](https://bugs.python.org/issue34426)
--- | :---
Nosy | @Mariatta, @pablogsal, @miss-islington, @danishprakash
PRs | <li>python/cpython#8822</li><li>python/cpython#8915</li><li>python/cpython#8916</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-08-25.02:08:01.544>
created_at = <Date 2018-08-18.05:35:11.033>
labels = ['3.8', 'type-bug', '3.7', 'docs']
title = '"__lltrace__"  seems to be wrong , "__ltrace__" is correct in Misc/SpecialBuilds.txt'
updated_at = <Date 2018-08-25.02:15:59.350>
user = 'https://bugs.python.org/NojimaTakahide'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-25.02:15:59.350>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2018-08-25.02:08:01.544>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2018-08-18.05:35:11.033>
creator = 'Nojima Takahide'
dependencies = []
files = []
hgrepos = []
issue_num = 34426
keywords = ['patch']
message_count = 8.0
messages = ['323692', '323740', '323759', '323761', '324027', '324028', '324030', '324031']
nosy_count = 6.0
nosy_names = ['docs@python', 'Mariatta', 'pablogsal', 'miss-islington', 'Nojima Takahide', 'danishprakash']
pr_nums = ['8822', '8915', '8916']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue34426'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by sweeneyde** [comment]
I think it may have been that the documentation was correct, but the code had a typo:

The typo was introduced in 2012 in this commit: https://github.com/python/cpython/commit/3c1e48176e077bbbf85183874f432de6d4ac8f88

I think "lltrace" (the variable names in the C code) is a better abbreviation for "low-level trace".

Since this has been around for 10 years, at this point, we could give up and do the low-level tracing if either `__ltrace__` or `__lltrace__` is present in the global namespace.
