### ISSUE TITLE
Avoid master/slave terminology

### ISSUE THREAD

**Issue by vstinner** [python/cpython#78786]
BPO | [34605](https://bugs.python.org/issue34605)
--- | :---
Nosy | @gvanrossum, @rhettinger, @terryjreedy, @pitrou, @vstinner, @larryhastings, @ericvsmith, @giampaolo, @stevendaprano, @berkerpeksag, @serhiy-storchaka, @ammaraskar, @Mariatta, @csabella, @miss-islington, @tirkarthi
PRs | <li>python/cpython#9099</li><li>python/cpython#9100</li><li>python/cpython#9101</li><li>python/cpython#9102</li><li>python/cpython#9195</li><li>python/cpython#10800</li><li>python/cpython#10802</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-11.06:33:15.222>
created_at = <Date 2018-09-07.14:22:00.288>
labels = ['interpreter-core', 'type-feature', '3.8', 'docs']
title = 'Avoid master/slave terminology'
updated_at = <Date 2018-11-29.20:39:08.638>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-29.20:39:08.638>
actor = 'miss-islington'
assignee = 'docs@python'
closed = True
closed_date = <Date 2018-09-11.06:33:15.222>
closer = 'gvanrossum'
components = ['Documentation', 'Interpreter Core']
creation = <Date 2018-09-07.14:22:00.288>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 34605
keywords = ['patch']
message_count = 47.0
messages = ['324739', '324740', '324744', '324747', '324748', '324750', '324752', '324754', '324755', '324756', '324757', '324758', '324759', '324760', '324761', '324762', '324763', '324768', '324773', '324774', '324775', '324776', '324777', '324778', '324780', '324786', '324810', '324816', '324822', '324823', '324825', '324838', '324840', '324841', '324843', '324847', '324849', '324870', '324955', '324995', '325094', '325241', '325247', '325351', '325500', '330721', '330724']
nosy_count = 17.0
nosy_names = ['gvanrossum', 'rhettinger', 'terry.reedy', 'pitrou', 'vstinner', 'larry', 'eric.smith', 'giampaolo.rodola', 'steven.daprano', 'berker.peksag', 'serhiy.storchaka', 'ammar2', 'Mariatta', 'Socob', 'cheryl.sabella', 'miss-islington', 'xtreak']
pr_nums = ['9099', '9100', '9101', '9102', '9195', '10800', '10802']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue34605'
versions = ['Python 3.8']
```

</p></details>

**Comment by metal3d** [comment]
You are saying that "slave" and "master" are racist terms?

So you are saying that there were only ethnically represented people who were slaves...

OK, remove the word "robot" from the entire science and automated system because this word comes from Proto-Indo-European word that means "young slave".

Also, remove all "service" terms because this word reminds that some people were forced to serve others.

Also, remove "mastering" and "managing" because it's negative to force something to work as expected.

Really, you are depressing. Infantilism has nothing to do in Python and globally in computing. Your decision will not change the history, human rights and the human condition. It's only a negative decision to make some words ashamed.
