### ISSUE TITLE
Add documentation explaining __init__.py in packages

### ISSUE THREAD

**Issue by a4ea5241-c779-40e6-aba5-6f0760c28e71** [python/cpython#78949]
BPO | [34768](https://bugs.python.org/issue34768)
--- | :---
Nosy | @merwok

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-09-21.19:26:19.604>
labels = ['docs']
title = 'Add documentation explaining __init__.py in packages'
updated_at = <Date 2018-09-28.17:13:36.181>
user = 'https://bugs.python.org/bkestelman'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-28.17:13:36.181>
actor = 'eric.araujo'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2018-09-21.19:26:19.604>
creator = 'bkestelman'
dependencies = []
files = []
hgrepos = []
issue_num = 34768
keywords = []
message_count = 2.0
messages = ['326020', '326649']
nosy_count = 3.0
nosy_names = ['eric.araujo', 'docs@python', 'bkestelman']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue34768'
versions = []
```

</p></details>

**Comment by zahlman** [comment]
>there is no explanation of __init__.py, its purpose

As @merwok noted, this is covered in the tutorial. There is now a separate issue #81073 open for improving the wording of this part of the tutorial.

>or what I should put in it to get my code to work.

This may not be feasible, because the answer depends on essentially everything else about the project. It can range from "it doesn't even need to exist" to "nothing" to "a few lines of special configuration code" (for example, to exclude parts of the package from a star-import) to "the complete implementation of a module that happens to also have submodules" (see for example `collections` in the standard library).

A key insight here is that Python's packages **are modules** - they're represented by the `module` type, not even a subclass:
```
>>> # N.B. paths and tracebacks elided
>>> import collections
>>> collections
<module 'collections' from '.../collections/__init__.py'>
>>> type(collections)
<class 'module'>
>>> collections.abc # because this is a sub-module, it doesn't exist by default
Traceback (most recent call last):
  ...
AttributeError: module 'collections' has no attribute 'abc'
>>> import collections.abc # importing the sub-module attaches it as an attribute of its parent module-which-is-a-package
>>> collections.abc
<module 'collections.abc' from '.../collections/abc.py'>
>>> type(collections.abc)
<class 'module'>
```
