### ISSUE TITLE
test_ctypes failing on Linux SPARC64

### ISSUE THREAD

**Issue by 57f6141e-6563-452f-a4c3-d07a1f3159c0** [python/cpython#78952]
BPO | [34771](https://bugs.python.org/issue34771)
--- | :---
Nosy | @vadmium, @kelledin

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-09-22.17:56:12.924>
labels = ['ctypes', 'type-bug']
title = 'test_ctypes failing on Linux SPARC64'
updated_at = <Date 2018-09-30.18:22:03.191>
user = 'https://github.com/kelledin'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-30.18:22:03.191>
actor = 'kelledin-3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2018-09-22.17:56:12.924>
creator = 'kelledin-3'
dependencies = []
files = []
hgrepos = []
issue_num = 34771
keywords = []
message_count = 5.0
messages = ['326102', '326504', '326636', '326656', '326740']
nosy_count = 2.0
nosy_names = ['martin.panter', 'kelledin-3']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue34771'
versions = ['Python 3.6']
```

</p></details>

**Comment by kulikjak** [comment]
I just tested this with Solaris 11.4 SPARC, and interestingly, we don't see any issues with `test_ctypes`. I tried running it both with and without your suggested change, and all tests passed in both cases. That said, this bug is pretty old now, and it's possible that things changed since then.

I tested this with Python 3.11 and libffi 3.4.4.

**Comment by encukou** [comment]
SPARC is unsupported per PEP-11. We don't have the means to test this issue. I'd be happy to merge a PR to add something clearly SPARC-specific to that `#if`, if a SPARC mainainer told me it fixes the tests. But, let's not track the issue here.

I'll close the bug and PR.
Like other issues for unsupported platforms, it'll be listed on [the GitHub project](https://github.com/orgs/python/projects/27) for anyone who wants to support the platform unofficially or bring support back.
I encourage such people to add themselves to the [Experts list](https://devguide.python.org/core-developers/experts/#platforms) so we know whom to ping.
