### ISSUE TITLE
Index search in CHM help crashes viewer

### ISSUE THREAD

**Issue by f7a29477-11b6-4add-a132-918438c57010** [python/cpython#79409]
BPO | [35228](https://bugs.python.org/issue35228)
--- | :---
Nosy | @pfmoore, @Cito, @tjguk, @methane, @zware, @zooba, @chrullrich, @animalize
Files | <li>[binary_index.png](https://bugs.python.org/file47967/binary_index.png "Uploaded as image/png at 2018-12-02.05:37:15 by @animalize")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-11-13.11:06:57.832>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.7', 'OS-windows', 'docs']
title = 'Index search in CHM help crashes viewer'
updated_at = <Date 2022-03-14.09:08:41.761>
user = 'https://github.com/chrullrich'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-14.09:08:41.761>
actor = 'methane'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Windows']
creation = <Date 2018-11-13.11:06:57.832>
creator = 'chrullrich'
dependencies = []
files = ['47967']
hgrepos = []
issue_num = 35228
keywords = []
message_count = 18.0
messages = ['329824', '330867', '330871', '332525', '370448', '370581', '370586', '370605', '370919', '371012', '375994', '375997', '376033', '376112', '376405', '408759', '413167', '415123']
nosy_count = 14.0
nosy_names = ['paul.moore', 'cito', 'tim.golden', 'methane', 'Zero', 'docs@python', 'zach.ware', 'steve.dower', 'chrullrich', 'malin', 'V\xc3\xa1clav Dvo\xc5\x99\xc3\xa1k', 'Charles G.', 'Keelung Yang', 'danny1221']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue35228'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by alexquinn** [comment]
**Workaround**

1. Find the shortcut in your Start Menu that was created by the Python installer.  Try Start » Run » "%ALLUSERSPROFILE%\Microsoft\Windows\Start Menu\Programs\" » click your Python version.
2. Right-click _Python 3.▒ Manuals (64-bit)_ » Properties.
3. Shortcut (tab) » Target (field) » Replace "C:\Windows\hh.exe" with "C:\Windows\SysWOW64\hh.exe".

This solved it for me.  Thanks to @mannequin for pointing this out on 2/12/2022.

**Possible fix**

Since the shortcut in the Start Menu is created by the installer, and refers directly to the viewer (hh.exe) path, could it refer to the one that works (C:\Windows\SysWOW64\hh.exe) instead of the one that crashes (C:\Windows\hh.exe)?

**Impact**

CHM is the only official documentation that allows incremental search (e.g., type "rel" to find os.path.relpath).  The Python web site does not.  DevDocs also does this, but that's a third party.

CHM still works fine for Python 2.7, so this could be an impediment for 2.x hold-outs.

Personally, CHM has been the one and only way I've accessed Python documentation for 23 years.

**Comment by zooba** [comment]
We've already dropped the CHM file and now distribute plain HTML files that are viewed in the user's default browser.

This workaround should be sufficient for anyone still relying on older releases.

**Comment by kiwichick888** [comment]
I am having this problem but with a compiled Help file for AutoHotkey using the compile_chm.ahk file here: https://github.com/AutoHotkey/AutoHotkeyDocs. Unfortunately, with this being a Python thread, I don't know how to relate/apply any of the potential fixes to AutoHotkey.

**Comment by kiwichick888** [comment]
> > I don't know how to relate/apply any of the potential fixes to AutoHotkey.
> 
> Our ultimate fix was to stop using CHM and just distribute HTML files. That shouldn't be too hard to apply to AHK, if you want to go that way :)
> 
> Otherwise, the last workaround was a change to the shortcut used to launch the help file. That's from the installer, not from Python, so if you're installing a shortcut then check with your installer toolkit on how to make the change.
> 
> Besides those, we don't have any better options. But none of this is Python-specific. Probably you just need to create a discussion in the AHK repo to work with their team on how to do it.

Thanks for the info. I'm not involved in any of the development/distribution of AutoHotkey or its help file. I'm just an AutoHotkey user. The compile_chm.ahk (and associated docs) is made available for anyone to download and use to compile their own help file. I use it to restore an old-style sidebar so I can get Favorites back.
