### ISSUE TITLE
Function ssl.create_default_context raises exception on Windows 10  when called with  ssl.Purpose.SERVER_AUTH) attribute

### ISSUE THREAD

**Issue by 37d608c5-d6d9-4d4c-8d1c-a41d2973e2cd** [python/cpython#79846]
BPO | [35665](https://bugs.python.org/issue35665)
--- | :---
Nosy | @tiran, @pervlad, @MDM-79, @pukkandan
Files | <li>[cacerts.pem](https://bugs.python.org/file48029/cacerts.pem "Uploaded as text/plain at 2019-01-07.18:44:26 by @pervlad"): pub certs</li><li>[Untitled.png](https://bugs.python.org/file50311/Untitled.png "Uploaded as image/png at 2021-09-28.15:39:56 by @MDM-79"): MUPCA Root - Certificates</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-01-08.09:38:24.479>
created_at = <Date 2019-01-05.12:24:45.346>
labels = ['expert-SSL', 'type-bug', '3.9']
title = 'Function ssl.create_default_context raises exception on Windows 10  when called with  ssl.Purpose.SERVER_AUTH) attribute'
updated_at = <Date 2021-09-28.21:47:58.903>
user = 'https://github.com/pervlad'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-28.21:47:58.903>
actor = 'pukkandan'
assignee = 'none'
closed = True
closed_date = <Date 2019-01-08.09:38:24.479>
closer = 'pervlad'
components = ['SSL']
creation = <Date 2019-01-05.12:24:45.346>
creator = 'pervlad'
dependencies = []
files = ['48029', '50311']
hgrepos = []
issue_num = 35665
keywords = []
message_count = 16.0
messages = ['333054', '333055', '333158', '333159', '333168', '333181', '333183', '333184', '333215', '333224', '360050', '402782', '402792', '402794', '402805', '402809']
nosy_count = 5.0
nosy_names = ['christian.heimes', 'pervlad', 'pedja', 'MDM-1', 'pukkandan']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue35665'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-91740
* gh-122768
* gh-122769

**Comment by levicki** [comment]
@tiran Can you please clarify whether this issue been fixed, and if so in which Python version? I am still encountering it in Miniconda3 which bundles Python 3.9.12 with OpenSSL 1.1.1q.

I understand that the underlying issue stems from OpenSSL throwing an error on invalid DER encoding of integers (in some cases it's the serial number which is harmless), but the end result is that HTTPS connections established using default context in Python code are failing if user has any invalid certificates in their Windows root certificate store.

I'd like to point out that:

1. Error message (stacktrace) shown by Python doesn't help the end user understand the error, much less find the offending certificate
2. Even if it did, regular users trying to run a Python application may not have admin rights to remove those certificates
3. Even if they had admin rights, randomly removing root CA certificates trying to figure out which one is responsible can render their system unusable
4. Even if they had the required knowledge of what they can safely remove, they might need those problematic certificates anyway and will just break some other application or intranet website
5. In 99% of cases those certificates are not needed for HTTPS communication and can be safely skipped

So clearly, the bare minimum that could be done by Python developers is to modify `_load_windows_store_certs` to load certificates one by one and skip the invalid ones:
```
    def _load_windows_store_certs(self, storename, purpose):
        certs = bytearray()
        try:
            for cert, encoding, trust in enum_certificates(storename):
                # CA certs are never PKCS#7 encoded
                if encoding == "x509_asn":
                    if trust is True or purpose.oid in trust:
                        try:
                            self.load_verify_locations(cadata=cert)
                            certs.extend(cert)
                        except SSLError:
                            warnings.warn("Bad certificate in Windows certificate store")
        except PermissionError:
            warnings.warn("unable to enumerate Windows certificate store")
        return certs
```
It would be even better if the `CN` or `friendlyName` of the offending certificate could be displayed instead of just `Bad certificate in Windows certificate store`.

Please advise.

**Comment by serhiy-storchaka** [comment]
Reopened this issue as the original problem have not been solved yet and we continue to receive bug reports.

Has anyone reported the problem to OpenSSL and to the Serbian government as was suggested in https://github.com/python/cpython/issues/79846#issuecomment-1093808509?

We can add a workaround in the Python stdlib (BTW, the code proposed by @levicki looks better than #91740), but it will only solve the part of the problem. And I am not sure that ignoring all errors will not open a security hole.

**Comment by levicki** [comment]
> Has anyone reported the problem to OpenSSL and to the Serbian government as was suggested in [#79846 (comment)](https://github.com/python/cpython/issues/79846#issuecomment-1093808509)?

I have just opened an issue with OpenSSL:
https://github.com/openssl/openssl/issues/25023

I don't think they will be too willing to relax the DER validation though.

As for Serbian Interior Ministry, they certainly won't be reissuing the problematic root which is about to expire in 2030.

> We can add a workaround in the Python stdlib (BTW, the code proposed by @levicki looks better than #91740), but it will only solve the part of the problem. And I am not sure that ignoring all errors will not open a security hole.

If you ignore a malformed certificate (i.e. do not add it from the Windows store into the Python trust store) then there is no security hole &mdash; if the certificate is used for securing HTTPS connection (this particular root isn't), then the communication attempt will fail.

This particular certificate isn't used to secure communication (just as a root for document signing certificates), but others might be used for communication as well so the best option would be to load and trust all certificates if possible even if they are malformed.

My rationale is that they are already in the user / system root store which assumes that the user trusts them and wants them to work.

**Comment by serhiy-storchaka** [comment]
Thank you @levicki for reviving this issue.

**Comment by levicki** [comment]
> Thank you @levicki for reviving this issue.

You're welcome.

**Comment by hugovk** [comment]
@levicki Unfortunately 3.10 and 3.11 are only accepting security fixes, see https://devguide.python.org/versions/ and https://devguide.python.org/developer-workflow/development-cycle/#security-branches.

@serhiy-storchaka The 3.12 and 3.13 backports are pending merge, keeping in mind 3.13 is in the RC phase.

**Comment by levicki** [comment]
@hugovk 
> @levicki Unfortunately 3.10 and 3.11 are only accepting security fixes, see https://devguide.python.org/versions/ and https://devguide.python.org/developer-workflow/development-cycle/#security-branches.

Yes, I am well aware of that.

One can hope though? If you look at this issue creatively basically it's a denial of service which could ultimately lead to degradation of security &mdash; if you have a single malformed certificate in your Windows certificate store none of your Python programs can use HTTPS for communication but they can still use HTTP.
