### ISSUE TITLE
Redirected stderr not reset properly when using logging

### ISSUE THREAD

**Issue by 60a9aba8-f866-4b1d-a38e-831b651a9581** [python/cpython#80374]
BPO | [36193](https://bugs.python.org/issue36193)
--- | :---
Nosy | @vsajip, @tirkarthi, @oerp-odoo

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-03-07.06:13:02.052>
created_at = <Date 2019-03-05.11:17:19.721>
labels = ['invalid', 'type-bug', 'library']
title = 'Redirected stderr not reset properly when using logging'
updated_at = <Date 2019-03-07.08:04:56.489>
user = 'https://github.com/oerp-odoo'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-07.08:04:56.489>
actor = 'andriusl'
assignee = 'none'
closed = True
closed_date = <Date 2019-03-07.06:13:02.052>
closer = 'vinay.sajip'
components = ['Library (Lib)']
creation = <Date 2019-03-05.11:17:19.721>
creator = 'andriusl'
dependencies = []
files = []
hgrepos = []
issue_num = 36193
keywords = []
message_count = 9.0
messages = ['337178', '337183', '337193', '337210', '337213', '337284', '337316', '337361', '337369']
nosy_count = 4.0
nosy_names = ['vinay.sajip', 'peter.otten', 'xtreak', 'andriusl']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36193'
versions = ['Python 3.5']
```

</p></details>

**Comment by shaoqx** [comment]
Sorry for opening this again but I found this error is yet not fully explored.
I found the logging error still exists even if I create different loggers and configure them before the redirection.
This is a simplified version of the case I'm dealing with:
```
import logging, os, sys

class HiddenPrints:
    def __init__(self, redirect=os.devnull):
        self.redirect=redirect

    def __enter__(self):
        self.original_stdout = sys.stdout
        self.original_stderr = sys.stderr
        self.redirect_io_obj = open(self.redirect, 'w')
        sys.stdout = self.redirect_io_obj
        sys.stderr = self.redirect_io_obj

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.redirect_io_obj.close()
        sys.stdout = self.original_stdout
        sys.stderr = self.original_stderr


message = 'dummy test'

_LOGGER_1 = logging.getLogger("1")
handler_1 = logging.StreamHandler()
_LOGGER_1.addHandler(handler_1)

with HiddenPrints("test.log"):
    _LOGGER = logging.getLogger("")
    handler = logging.StreamHandler()
    _LOGGER.addHandler(handler)
    _LOGGER.warning(message)

_LOGGER_1.warning(message)
```
I choose to use a self-written context manager for debugging reasons in this case.
```
The output is:
[user@mutant test]$ python test.py
dummy test
--- Logging error ---
Traceback (most recent call last):
  File "/home/miniconda3/envs/uni_enzyhtp/lib/python3.9/logging/__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
ValueError: I/O operation on closed file.
Call stack:
  File "/home/test.py", line 32, in <module>
    _LOGGER_1.warning(message)
Message: 'dummy test'
Arguments: ()
```

In this case, different loggers are used inside and outside of the redirection. The outside _LOGGER_1 is configured beforehand. The handlers are different for them too. _LOGGER is `[<StreamHandler test.log (NOTSET)>]`, _LOGGER_1 is `[<StreamHandler <stderr> (NOTSET)>]`.

`_LOGGER_1.handlers[0].stream.closed` also gives False.

How should I deal with this problem? Thanks in advance!

**Comment by vsajip** [comment]
Perhaps you haven't quite understood how logging works. When you initialize a `StreamHandler`, it keeps a reference to the stream passed in. Within the context, this is `self.redirect_io_obj`. You close that stream in the `__exit__`, but the handler still refers to it. When you use the handler outside the context (after the stream has been closed) you get the error, as I would expect. And you use the handler outside the context because in the context, you added the handler to the root logger. So, it is asked to handle any events from child loggers, including `_LOGGER_1`. You can avoid the error by e,g, setting `_LOGGER_1.propagate = False`.

Refer to [this logging flow diagram](https://docs.python.org/3/howto/logging.html#logging-flow) for a better understanding.

Rather than here, please ask your questions in a forum such as the [Python Discourse](https://discuss.python.org/c/users/7), [Stack Overflow](https://stackoverflow.com/) or similar, so that some one can spot any errors in your logic. Once it is established that there is a definite problem rather than user error, then it is of course reasonable to raise an issue here.

**Comment by shaoqx** [comment]
Thank you Vinay! This is very clear!
