### ISSUE TITLE
use the right python "make -C Doc/ serve"

### ISSUE THREAD

**Issue by matrixise** [python/cpython#80510]
BPO | [36329](https://bugs.python.org/issue36329)
--- | :---
Nosy | @berkerpeksag, @matrixise, @JulienPalard, @hugovk
PRs | <li>python/cpython#12385</li><li>python/cpython#32354</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-17.18:57:38.556>
labels = ['3.11', 'docs']
title = 'use the right python "make -C Doc/ serve"'
updated_at = <Date 2022-04-06.09:32:26.118>
user = 'https://github.com/matrixise'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-06.09:32:26.118>
actor = 'hugovk'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-03-17.18:57:38.556>
creator = 'matrixise'
dependencies = []
files = []
hgrepos = []
issue_num = 36329
keywords = ['patch']
message_count = 6.0
messages = ['338135', '338195', '341163', '341204', '341211', '416848']
nosy_count = 5.0
nosy_names = ['docs@python', 'berker.peksag', 'matrixise', 'mdk', 'hugovk']
pr_nums = ['12385', '32354']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue36329'
versions = ['Python 3.11']
```

</p></details>

**Comment by gpshead** [comment]
For those seeking the old "serve" ability, after `make -C Doc html` run:

`python -m http.server -b localhost -p HTTP/1.1 -d Doc/build/html/ 8088`

I use that with a default port forwarding on my ssh session (aka `ssh -L 8088:localhost:8088` or equivalent in your .ssh/config) to my development systems.

I rarely have the ability for a development system to run a web browser or automatically tell my desktop browser full of important authentications where to go. In general as risk mitigation, but also in part because I'm happy using remote dev environments and ChromeOS.
