### ISSUE TITLE
asyncio.all_tasks() crashes if asyncio is used in multiple threads

### ISSUE THREAD

**Issue by e4fc0762-b12b-485e-9719-d9d96c514a27** [python/cpython#80788]
BPO | [36607](https://bugs.python.org/issue36607)
--- | :---
Nosy | @asvetlov, @thatch, @ambv, @1st1, @miss-islington, @sdunster
PRs | <li>python/cpython#13971</li><li>python/cpython#13975</li><li>python/cpython#13976</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-04-11.18:12:48.096>
labels = ['3.8', 'type-bug', '3.7', '3.9', 'expert-asyncio']
title = 'asyncio.all_tasks() crashes if asyncio is used in multiple threads'
updated_at = <Date 2019-06-12.17:26:52.568>
user = 'https://bugs.python.org/NickDavies'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-12.17:26:52.568>
actor = 'asvetlov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-04-11.18:12:48.096>
creator = 'Nick Davies'
dependencies = []
files = []
hgrepos = []
issue_num = 36607
keywords = ['patch']
message_count = 11.0
messages = ['339991', '340424', '340425', '340428', '340527', '340544', '345239', '345247', '345266', '345380', '345389']
nosy_count = 7.0
nosy_names = ['asvetlov', 'thatch', 'lukasz.langa', 'yselivanov', 'miss-islington', 'sdunster', 'Nick Davies']
pr_nums = ['13971', '13975', '13976']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36607'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-123388

**Comment by gvanrossum** [comment]
I don't remember why it was done this way. Let me see if @1st1 remembers. I betcha there's a deep reason.

**Comment by jbower-fb** [comment]
I'd be +1 for `all_tasks` being something on loops.

In https://github.com/python/cpython/issues/91887 @bdarnell @bast0006 did some good code archaeology on `all_tasks`, and it sounds like the implementation may have been the way it is to help with debugging "lost" tasks. If this is correct, I would imagine keeping things separate from loop instances made this easier if the loop references were also "lost"/closed at the point of debugging.

Further, it sounds like some of the original API to facilitate this didn't survive, like the ability to get "done" tasks and I hope most of the low-level debugging is now complete. So, perhaps now is a good time to change the implementation to be more intentional.

**Comment by willingc** [comment]
As a next action, this would be a good issue to discuss in detail at the upcoming core dev sprint.

**Comment by kumaraditya303** [comment]
> As a next action, this would be a good issue to discuss in detail at the upcoming core dev sprint.

FYI, this issue is now largely fixed since tasks now use a linked list in C implementation, the pure Python implementation remains to be fixed.

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/123388
