### ISSUE TITLE
pathlib.Path.with_name() handles '.' and '..' inconsistently

### ISSUE THREAD

**Issue by 9ecee83d-078f-484a-b634-20525df1e061** [python/cpython#81311]
BPO | [37130](https://bugs.python.org/issue37130)
--- | :---
Nosy | @brettcannon, @terryjreedy, @jaraco, @pitrou, @websurfer5, @NophKe
PRs | <li>python/cpython#14022</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-02.01:18:12.304>
labels = ['type-bug', 'library', '3.9']
title = "pathlib.Path.with_name() handles '.' and '..' inconsistently"
updated_at = <Date 2020-02-01.00:07:11.555>
user = 'https://github.com/NophKe'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-01.00:07:11.555>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-06-02.01:18:12.304>
creator = 'Nophke'
dependencies = []
files = []
hgrepos = []
issue_num = 37130
keywords = ['patch']
message_count = 16.0
messages = ['344250', '344462', '344640', '344770', '345001', '345129', '345386', '345395', '345406', '345424', '345536', '347391', '347495', '348530', '348534', '361136']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'terry.reedy', 'jaraco', 'pitrou', 'Jeffrey.Kintscher', 'Nophke', 'lucas.steinmann']
pr_nums = ['14022']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37130'
versions = ['Python 3.9']
```

</p></details>

**Comment by barneygale** [comment]
Pathlib treats '..' as just another path token, which is why `PurePath('foo/bar/..').parent gives you `foo/bar`. By design, the _only_ method that properly resolves them is `resolve()`.

Pathlib normalizes paths into a list of 'parts', and filters out any '.' parts or empty parts. Therefore `Path()` and `Path('.//.')` evaluate to the same thing: an *empty* list of parts. The `__str__()` method treats this as a special case and returns `'.'` rather than the empty string.

Personally I think the empty string is a reasonable result for `PurePath().name`. You also get an empty string from `PurePosixPath('/')` and `PureWindowsPath('C:/')`.

**Comment by brettcannon** [comment]
@barneygale as in you should use your new triage powers and close the issue? 😉

**Comment by barneygale** [comment]
Closing per the above.
