### ISSUE TITLE
Minidom does not have to escape quote inside text segments

### ISSUE THREAD

**Issue by 717908ce-bb9c-4e05-b89c-d98143e51333** [python/cpython#81555]
BPO | [37374](https://bugs.python.org/issue37374)
--- | :---
Nosy | @scoder, @mitar, @serhiy-storchaka, @viplezer
PRs | <li>python/cpython#14312</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-22.20:34:20.473>
labels = ['expert-XML', 'type-feature']
title = 'Minidom does not have to escape quote inside text segments'
updated_at = <Date 2021-03-10.10:53:53.152>
user = 'https://github.com/mitar'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-10.10:53:53.152>
actor = 'viplezer'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['XML']
creation = <Date 2019-06-22.20:34:20.473>
creator = 'mitar'
dependencies = []
files = []
hgrepos = []
issue_num = 37374
keywords = ['patch']
message_count = 8.0
messages = ['346296', '346310', '346341', '346350', '346892', '346894', '388423', '388424']
nosy_count = 5.0
nosy_names = ['scoder', 'mitar', 'serhiy.storchaka', 'dhilst', 'viplezer']
pr_nums = ['14312']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue37374'
versions = ['Python 3.6']
```

</p></details>

**Comment by Swarf** [comment]
Any chance we can take action on this? I agree with the concern. XML standard says that escaping quotes in content data is optional. minidom is forcing a change to perfectly valid XML.

**Comment by scoder** [comment]
I read the spec, and this case is actually not explicitly specified. The spec says that `&quot;` may be used in order to support quotes in attribute values, but it does not forbid it otherwise. So, this behaviour is not wrong.

Also, the fact that other libraries behave differently does not mean that minidom must. It's been around for more than 20 years, and the current behaviour is probably just as old and settled.

According to the comments above, there seem to be use cases where this can be an annoyance, apparently, but even there, the result is not wrong, just a bit less readable than it could be.

While only C14N makes guarantees w.r.t. the exact byte serialisation (so neither minidom not ElementTree need to), any change here will break someone's code out there, so there is a downside to changing the output. A deliberate change without need means deliberate breakage without need.

To me, there is no definite reason to change the current behaviour.

As much as I second the preference for clean XML output, I'd rather like to avoid changing the output without a compelling reason.

**Comment by Swarf** [comment]
The spec also doesn't say that a serializer shouldn't turn all. the Zs into Ys, but I'm pretty sure we would all consider that a bug. If user data would be valid XML, why modify it regardless of user intent? 

If the answer is simply "go use a different library which doesn't have an opinion on this", then I will. Just disappointed that this minidom isn't usable at present.

**Comment by scoder** [comment]
Reopening since https://github.com/python/cpython/pull/107947 gives us a reason to change the output, so we can solve this issue along the way.

**Comment by techgeniuswang** [comment]
This unnecessary escaping is really annoying, any chance to change it? 

> Reopening since [#107947](https://github.com/python/cpython/pull/107947) gives us a reason to change the output, so we can solve this issue along the way.
