### ISSUE TITLE
Support .as_integer_ratio() in fractions.Fraction

### ISSUE THREAD

**Issue by jdemeyer** [python/cpython#82017]
BPO | [37836](https://bugs.python.org/issue37836)
--- | :---
Nosy | @rhettinger, @mdickinson, @serhiy-storchaka, @jdemeyer
PRs | <li>python/cpython#15327</li><li>python/cpython#15328</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-08-13.09:41:19.711>
labels = ['library', '3.9']
title = 'Support .as_integer_ratio() in fractions.Fraction'
updated_at = <Date 2022-01-02.22:00:12.998>
user = 'https://github.com/jdemeyer'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-02.22:00:12.998>
actor = 'rhettinger'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-08-13.09:41:19.711>
creator = 'jdemeyer'
dependencies = []
files = []
hgrepos = []
issue_num = 37836
keywords = ['patch']
message_count = 6.0
messages = ['349536', '349933', '349940', '349942', '349945', '409531']
nosy_count = 5.0
nosy_names = ['rhettinger', 'mark.dickinson', 'stutzbach', 'serhiy.storchaka', 'jdemeyer']
pr_nums = ['15327', '15328']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue37836'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-120271

**Comment by serhiy-storchaka** [comment]
Concur with @rhettinger.

**Comment by serhiy-storchaka** [comment]
This proposition was rejected because it used `as_integer_ratio()` in both single- and two-argument forms of the Fraction constructor. But these two forms have different roles. The former converts a number to a Fraction or parses a string representation of fraction. The latter creates a fraction from two rationals (and this is perhaps too much, it could be limited to integers). Conversion from integer supports not only rational numbers, but also `float` and `Decimal`. Supporting `as_integer_ratio()` here would allow to convert `float128` and other non-rational numbers to Fraction.

So I reopen this issue with more limited goal -- supporting `as_integer_ratio()` in a single-argument form of the Fraction constructor.

**Comment by pfmoore** [comment]
Agreed this would be a nice generalisation for the case of converting a user-defined type to a fraction (the user defined type just has to define `as_integer_ratio` and then `Fraction(value)` works as expected). But it should *not* apply to the 2-argument case.
