### ISSUE TITLE
bool(~True) == True

### ISSUE THREAD

**Issue by 243bf073-7a9a-4861-97f6-492d27152381** [python/cpython#82012]
BPO | [37831](https://bugs.python.org/issue37831)
--- | :---
Nosy | @gvanrossum, @tim-one, @rhettinger, @mdickinson, @serhiy-storchaka, @eryksun, @tomerv
Superseder | <li>bpo-12447: ~True is not False</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-08-12.20:25:46.266>
created_at = <Date 2019-08-12.10:48:52.558>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'bool(~True) == True'
updated_at = <Date 2019-08-14.17:45:40.127>
user = 'https://github.com/tomerv'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-14.17:45:40.127>
actor = 'gvanrossum'
assignee = 'none'
closed = True
closed_date = <Date 2019-08-12.20:25:46.266>
closer = 'rhettinger'
components = ['Interpreter Core']
creation = <Date 2019-08-12.10:48:52.558>
creator = 'tomerv'
dependencies = []
files = []
hgrepos = []
issue_num = 37831
keywords = []
message_count = 24.0
messages = ['349452', '349459', '349461', '349477', '349478', '349480', '349482', '349484', '349487', '349488', '349489', '349493', '349494', '349495', '349508', '349509', '349522', '349628', '349656', '349661', '349707', '349709', '349723', '349724']
nosy_count = 7.0
nosy_names = ['gvanrossum', 'tim.peters', 'rhettinger', 'mark.dickinson', 'serhiy.storchaka', 'eryksun', 'tomerv']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '12447'
type = 'enhancement'
url = 'https://bugs.python.org/issue37831'
versions = ['Python 3.7']
```

</p></details>

### Linked PRs
* gh-103487

**Comment by timhoffm** [comment]
I would like to reconsider this topic.

From a user point of view:

- For better or worse, `~` on bool is commonly seen as negation by users because it works like this in numpy
- Python overloads all bitwise operators except for `~` to work on bool as logical operations
- `~` on `bool` behavior is inherited from `int`, but I suppose this inheritance relation is not clear to many users

As a result, chances are high, that users use `~` on `bool` with the incorrect expectation of boolean logic - Not so great. Can we do anything better than the current state?

**Proposal:** Deprecate `~` on `bool` and raise an error in the future.

On the downside, this would still violate Liskov's Principle, but maybe less bad than changing to another result with bool semantics. It may break very few usecases where people have used it intentionally, but they could move from `~val` to the more explicit `~int(val)` if they really mean the bitwise operation on the underlying int representation.
Overall we may consider to bear this breakage to make people aware of the likely incorrect usage.

**Comment by gvanrossum** [comment]
> **Proposal:** Deprecate `~` on `bool` and raise an error in the future.

Yeah, that sounds reasonable. Do you want to submit a PR that does this in 3.12?

**Comment by timhoffm** [comment]
Great! I'm happy to provide a PR, but it will be some days before I get to it.

**Comment by gvanrossum** [comment]
That's fine!

GitHub really needs a feature "ping me on this issue in N days/weeks/months" :-)

**Comment by iritkatriel** [comment]
@timhoffm The deadline for getting this int 3.12 is in about a month.

**Comment by timhoffm** [comment]
Thanks for the reminder. I may get around this next week.

**Comment by timhoffm** [comment]
@iritkatriel the PR #103487 is ready. Can I still help with anything to get this into 3.12?

**Comment by pochmann3** [comment]
> I don't think I understand why anyone would want to use | and & on bools to get another bool, instead of just using `or` and `and`.

I think I've had cases where I wanted a bool and needed both operands evaluated, so `or` and `and`  wouldn't have worked.

**Comment by terryjreedy** [comment]
Futher discussion: https://discuss.python.org/t/bool-deprecation/62232
