### ISSUE TITLE
Email example using imaginary library installation error.

### ISSUE THREAD

**Issue by 22334c5f-0925-406d-887b-9fcfe36832e0** [python/cpython#82530]
BPO | [38349](https://bugs.python.org/issue38349)
--- | :---
Nosy | @warsaw, @terryjreedy, @bitdancer, @maxking

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-10-02.16:10:03.652>
labels = ['3.8', 'docs', '3.7', '3.9', 'performance']
title = 'Email example using imaginary library installation error.'
updated_at = <Date 2019-10-05.16:15:18.636>
user = 'https://bugs.python.org/jackotonye'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-05.16:15:18.636>
actor = 'maxking'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-10-02.16:10:03.652>
creator = 'jackotonye'
dependencies = []
files = []
hgrepos = []
issue_num = 38349
keywords = []
message_count = 9.0
messages = ['353743', '353745', '353755', '353997', '353998', '354015', '354016', '354017', '354018']
nosy_count = 7.0
nosy_names = ['barry', 'terry.reedy', 'r.david.murray', 'SilentGhost', 'docs@python', 'maxking', 'jackotonye']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue38349'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
We could also rename imaginary to imaginary_module and then it won't look like a real module name.

**Comment by terryjreedy** [comment]
The file under consideration was written by R. David Murray in 2014, with little revision since.  The suggestions include: do nothing; rewrite the import comment; change the fake name (in particular, to `imaginary_module`); move the function description up to the import; and turn the function description into a docstring for a def that replaces the import (SilentGhost).  There was no consensus on which to do.

Stanley(slateny)'s PR changes the import name and moves the fake function description up.  After reading it and thinking more, I prefer SilentGhost's idea, except that I would want to raise rather than return an empty string.  One reason is that understanding the function description requires knowing its signature.  I presume that this is why David put the comment where he did, just above the call that shows the intended signature.

So, replace the import and its comment and turn the current multiline function comment into a docstring as follows.
```
def magic_html_parser(html_text, partfiles):
    """Return safety sanitized html linked to partfiles.

   Rewrite the href="cid:...." attributes to point to the filenames in partfiles.
   Though not trivial, this should be possible using html.parser.
    """
    raise NotImplementedError("Add the magic needed")
```
I am giving slateny at least a week to write a new PR if he wishes.
