### ISSUE TITLE
Pickle handle self references in classes

### ISSUE THREAD

**Issue by e35c8b43-ccbd-4dd8-8889-3e8ed7ed1481** [python/cpython#82951]
BPO | [38770](https://bugs.python.org/issue38770)
--- | :---
Nosy | @serhiy-storchaka, @furkanonder

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2019-11-11.21:10:17.849>
labels = ['3.7', 'type-bug', 'library']
title = 'Pickle handle self references in classes'
updated_at = <Date 2020-04-21.23:57:29.528>
user = 'https://bugs.python.org/SaimRaza'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-21.23:57:29.528>
actor = 'furkanonder'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-11-11.21:10:17.849>
creator = 'Saim Raza'
dependencies = []
files = []
hgrepos = []
issue_num = 38770
keywords = []
message_count = 3.0
messages = ['356388', '366951', '366956']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'Saim Raza', 'furkanonder']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38770'
versions = ['Python 2.7', 'Python 3.7']
```

</p></details>

### Linked PRs
* gh-122149
* gh-122264
* gh-122265

**Comment by serhiy-storchaka** [comment]
Pickling unbound methods and nested classes is natively supported in protocol 4. In protocol 3 and lower, only top-level classes and functions (i.e. these that do not have a dot in `__qualname__`) were initially supported. Later support of nested names was implemented via the `getattr()` function (see bpo-23611). `Foo.ref` is now represented as `getattr(Foo, 'ref')`. The problem in your example is that if `Foo.__qualname__` is `'Foo.ref'`, `Foo` is pickled as `getattr(Foo, 'ref')`, that involves infinite recursion.

This problem can be solved by forcing all parent objects to be serialized by name without using the normal dispatch mechanism: represent `Foo.ref` as `getattr(getattr(module, 'Foo'), 'ref')`.

I consider this a bugfix because it matches the behavior in protocols < 4 with the behavior in protocols >= 4 which is used by default since 3.8 (see bpo-23403). I wish I did it from the beginning.
