### ISSUE TITLE
performance degradation creating a mock object (by factor 7-8)

### ISSUE THREAD

**Issue by a2bb6667-2710-4a8e-84db-0f6bf7fe8505** [python/cpython#83076]
BPO | [38895](https://bugs.python.org/issue38895)
--- | :---
Nosy | @cjw296, @voidspace, @lisroach, @mariocj89, @tirkarthi, @julianhille, @marseel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-11-22.15:57:32.933>
labels = ['3.7', '3.8', '3.9', 'performance']
title = 'performance degradation creating a mock object (by factor 7-8)'
updated_at = <Date 2019-11-26.04:51:16.008>
user = 'https://github.com/julianhille'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-26.04:51:16.008>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2019-11-22.15:57:32.933>
creator = 'julianhille'
dependencies = []
files = []
hgrepos = []
issue_num = 38895
keywords = []
message_count = 7.0
messages = ['357297', '357379', '357382', '357431', '357435', '357450', '357481']
nosy_count = 7.0
nosy_names = ['cjw296', 'michael.foord', 'lisroach', 'mariocj89', 'xtreak', 'julianhille', 'marseel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue38895'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-100252

**Comment by iritkatriel** [comment]
> Do you mind if I create PR for it? I would like to start contributing to CPython ;)

@marseel Are you still planning to work on this?

**Comment by carljm** [comment]
The slowness of Mock and AsyncMock creation has caused timeout/slowdown issues in our (very large) test suite that makes heavy use of mock objects. In addition to moving the check for async-function attributes to `_get_child_mock` (as described above) my profiling has shown a couple other opportunities for large improvements:

1) Even though getting the signature of `NonCallableMock.__init__` has been moved to module level so it isn't done every time in `NonCallableMock.__new__`, there's still a significant cost to the `bind_partial` call to match up arguments. This really seems unnecessary, as the only gain from it is that we don't have to duplicate the `__init__` argument list. In my testing, duplicating the argument list (instead of using `*args, **kwargs` in the signature of `__new__`) and removing the `bind_partial` call is an additional 2x improvement in the cost of instantiating a `Mock` object. Duplicating this argument list (only a few lines away, in the same file) seems like a very small price to pay for such a significant speed increase for all users of Mock.

2) A large chunk of the cost of creating an `AsyncMock` is the fact that every `AsyncMock` creation eagerly creates an internal `NonCallableMock(spec_set=CodeType)` for use as its `__code__` attribute, so that the `AsyncMock` can pass `iscoroutinefunction()` checks. There are a couple possible improvements here. The biggest speed improvement (and simplest approach) is to use a real dummy async-func code object for the `__code__` attribute, instead of a specced Mock. The downside here is that it could be backwards incompatible if anyone's test suite is actually relying on the `__code__` attribute of an `AsyncMock` being a mock object itself; this seems quite unlikely but in theory it is possible. A second, fully compatible, approach (which still provides a 3x speed improvement all by itself) is to extract the attribute list and signature of `CodeType` just once at module level and construct the CodeType mock a bit more manually, bypassing a lot of the introspection cost of creating a specced mock.

I will submit a PR that does all three of these things (using the more-compatible version of (2)). Taken together, the PR provides an almost 4x improvement in both `Mock()` and `AsyncMock()` creation.

**Comment by hauntsaninja** [comment]
Closing, since we've clawed a good amount of performance back + it was decided not to backport Carl's PR. Thanks everyone!
