### ISSUE TITLE
xml.etree.ElementTree.Element inconsistent warning for bool

### ISSUE THREAD

**Issue by 6ae14072-3760-4408-a24e-9e2992ccd0a3** [python/cpython#83122]
BPO | [38941](https://bugs.python.org/issue38941)
--- | :---
Nosy | @rhettinger, @scoder, @serhiy-storchaka, @JelleZijlstra, @jacobtylerwalls
PRs | <li>python/cpython#31149</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-11-29.13:21:05.659>
labels = ['expert-XML', 'type-bug', 'library', '3.11']
title = 'xml.etree.ElementTree.Element inconsistent warning for bool'
updated_at = <Date 2022-03-23.03:14:02.864>
user = 'https://bugs.python.org/philiprowlands'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-23.03:14:02.864>
actor = 'JelleZijlstra'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'XML']
creation = <Date 2019-11-29.13:21:05.659>
creator = 'philiprowlands'
dependencies = []
files = []
hgrepos = []
issue_num = 38941
keywords = ['patch']
message_count = 10.0
messages = ['357642', '357644', '357645', '357662', '357680', '357682', '357688', '357737', '357740', '415853']
nosy_count = 7.0
nosy_names = ['effbot', 'rhettinger', 'scoder', 'serhiy.storchaka', 'JelleZijlstra', 'philiprowlands', 'jacobtylerwalls']
pr_nums = ['31149']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38941'
versions = ['Python 3.11']
```

</p></details>

**Comment by gpshead** [comment]
The `FutureWarning` existing only on a single (unused by CPython) codepath and not being a `DeprecationWarning` surprised me. So I'd lean towards @JelleZijlstra 's (1) myself.

I agree that the purpose of FutureWarning even existing is... unclear. A behavior changing in the future should be called a Deprecation.

Before deciding on (1) vs (2) though, an experiment with a warning surfaced loudly to see what potential scale of cleanup required across a pile of projects or in a large codebase like we have at work would be useful data.

**Comment by gvanrossum** [comment]
The docs for FutureWarning state that it's for users of applications, whereas DeprecationWarning is for other Python developers. Not sure that that's a very helpful distinction in practice though.

Note that the PR is stalled: https://github.com/python/cpython/pull/31149

**Comment by gpshead** [comment]
Yeah I don't find FutureWarning super useful, but as documented it effectively means DeprecationWarning is what should've been used. The audience for it is developers, not application end users who should be assumed to know nothing about code and APIs.

**Comment by serhiy-storchaka** [comment]
I find FutureWarning useful, although there are less use cases for it then for DeprecationWarning. The difference between DeprecationWarning and FutureWarning is that the former is used for changes which will cause raising an exception in future, while the latter is used when the future behavior change will be more silent -- just return different result or have different side effects. You can ignore DeprecationWarning for a while, because it is difficult to miss an exception in future versions. You should be more careful with FutureWarning, because a silent change can lead to subtle bugs in future releases. This is why FutureWarning is more visible by default.

Emitting FutureWarning in `__bool__` is appropriate if we want to return a different value in future. Emitting DeprecationWarning in `__bool__` is appropriate if we want to raise an exception in future. Raising an exception in `__bool__` is unexpected, and currently only `NotImplemented.__bool__()` emits a DeprecationWarning (for good reasons). So there are three options:

1. Make `__bool__` emitting FutureWarning in both implementations. In future versions make it returning True.
2. Remove any warnings.
3. Make `__bool__` emitting DeprecationWarning. In future versions make it raising an exception.

There are variants of 1 and 3 which are less destructive for current code which checks that "it is a thing". If elements in your code always have children, you have not need to change it. If they can be childless, your code have a bug in any case (it will be automatically fixed by 1a, and 3a will force you to fix it).

1.
   a. Only emit FutureWarning for childless element.
3.
   a. Only emit DeprecationWarning for childless element. In future versions only raise an exception for childless element.

**Comment by jacobtylerwalls** [comment]
I've updated #31149 to raise DeprecationWarning.

I don't think raising an exception is unexpected; the docs have warned since 2.7 that this is an ambiguous pattern. I also think changing the behavior based on whether the element has children is very surprising. In that case, you might never see the DeprecationWarning while testing, and then get bitten in production when encountering childless elements "in the wild".

**Comment by createyourpersonalaccount** [comment]
This is a bug, and a bad one. There should be documentation in every single function that can be bitten by this bug. Currently, there's a caution here: <https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.remove>.

>Caution: Elements with no subelements will test as False. In a future release of Python, all elements will test as True regardless of whether subelements exist. Instead, prefer explicit len(elem) or elem is not None tests.:

This caution should be in bold in every single place, especially <https://docs.python.org/3/library/xml.etree.elementtree.html#finding-interesting-elements> and <https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.find>.

As if XML isn't bad as it is. With regards to fixing this bug, I would nuke the whole module specifically to get rid of this bug without breaking backwards compat. Call it `xml2` or `xml.etree2`.
