### ISSUE TITLE
better name for re.error Exception class.

### ISSUE THREAD

**Issue by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [python/cpython#83162]
BPO | [38981](https://bugs.python.org/issue38981)
--- | :---
Nosy | @gpshead, @ezio-melotti, @serhiy-storchaka, @Carreau, @sourabh025
PRs | <li>python/cpython#17501</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-12-05.16:56:07.880>
labels = ['expert-regex', 'easy', 'type-feature', '3.9']
title = 'better name for re.error Exception class.'
updated_at = <Date 2020-09-18.07:39:36.123>
user = 'https://github.com/Carreau'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-18.07:39:36.123>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Regular Expressions']
creation = <Date 2019-12-05.16:56:07.880>
creator = 'mbussonn'
dependencies = []
files = []
hgrepos = []
issue_num = 38981
keywords = ['patch', 'easy']
message_count = 11.0
messages = ['357867', '357878', '357882', '357883', '357884', '357886', '357962', '357982', '357986', '358059', '358124']
nosy_count = 6.0
nosy_names = ['gregory.p.smith', 'ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'mbussonn', 'sourabh025']
pr_nums = ['17501']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue38981'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-101676
* gh-101677
* gh-112987
* gh-113013

**Comment by hugovk** [comment]
> aifc, binhex, sunau, uu, xdrlib might be removed with PEP-594

Yes, aifc, sunau, uu and xdrlib made the list and will be deprecated in 3.11 and removed in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

binhex isn't part of the PEP 594 because it was already deprecated in 3.9 and has been removed from 3.11:

https://docs.python.org/3.11/whatsnew/3.11.html?highlight=binhex#removed

**Comment by achhina** [comment]
@Carreau I see that you've closed your PR; would you still like to work on this? It seems that your PR was mostly done, and just required finalizing the actual exception name.

**Comment by achhina** [comment]
I've brought the above patch in line with the current main branch as a draft PR - thanks again @Carreau. However, before I make any changes I'd like to see if we can agree on the new exception name.

Looking at other popular libraries across several languages, there are several variations such as Java's `PatternSyntaxException`, but the ones that appear the most often seem to be `Error`, `SyntaxError`, and `CompileError`. I believe these without prefixes would not be much clearer than the original exception, so they should be prefixed with uppercase `RE` as it's an abbreviation.

This leaves us with `REError`, `RESyntaxError`, and `RECompileError`. Admittedly subjectively, I prefer `RESyntaxError` and `RECompileError` over `REError`, as they seem to read better and as such provide more clarity. 

I imagine users will most likely see this exception due to syntax issues with the expression, and some libraries make the distinction that a compilation error is related to an invalid encoding vs. a syntax error. So with that in mind, plus @barneygale's point that it could be read as recompile error, I'd like to propose using `RESyntaxError`.

cc @serhiy-storchaka, @gpshead as you've participated in these discussions before as well.

**Comment by gpshead** [comment]
I'm not feeling like there is a lot of value in doing this anymore.

If I were choosing a new name my logic would look like:
 * I expect code to always access the exception from the module itself, I'd leave the "RE" prefix off of the exception name. Which suggests a simple `re.Error` to gain the uppercase spelling consistent with exception classes elsewhere.
 * But doing that change now is disruptive to code that unfortunately makes the poor choice to `from re import *` and does so later in life... so Error would then import and overwrite their own Error class. Plausibly breaking existing code. So loop back and put the prefix on it again.
 * We're back to the needlessly repetitive `re.RESomeError` spelling again, which is objectively ugly and unpleasing to type compared to `re.error` or `re.Error`. infinite decision loop.

So I expect many will continue to type `re.error` regardless of the new name...  My gut feeling is just to close this issue as "not planned".  It's a historical oddity of the language from before a consistent style was well realized.

**Comment by achhina** [comment]
I think for me when looking at this issue, the benefit of introducing this would be the additional clarity for beginners, as an error like this
```python
RESyntaxError: nothing to repeat at position 0
```
would be more clear than what we have currently
```python
error: nothing to repeat at position 0
```

> I expect code to always access the exception from the module itself

Currently that would be correct as `from re import error` would seem like a poor choice, however I've quite often seen `from json import JSONDecodeError`, and I'd imagine similarly people can make that decision with `re`.

> which is objectively ugly and unpleasing to type

I can understand that, but as you mentioned for those folks `re.error` will always be available, so this should have a very low impact for them while providing a more informative exception name.

**Comment by barneygale** [comment]
We have `re.Pattern`, why not `re.PatternError`? :)

**Comment by achhina** [comment]
> We have `re.Pattern`, why not `re.PatternError`? :)

I think `PatternError` would work well as well :). Both `SyntaxError`/`PatternError` would be good proxies to imply that there is an issue with the regular expression syntax (the most likely reason to see an error). IIRC when I was looking at other regex libraries in/outside of Python, some form of `SyntaxError` seemed to be more popular. So, that combined with if we're suggesting there's an issue with the regular expression syntax, I leaned towards `SyntaxError`. 

What I do like about `PatternError` is the possibility it adds to not have a prefix of `RE`, which makes it more pleasant to type and read. Although I'm leaning towards keeping the prefix, as I find it adds more clarity and seems to be in line with the popular exception format of `<library><error_type>`.

So what I'm thinking is this:
1. If we want to keep the prefix `RE`, then I'd suggest going with `RESyntaxError`.
2. Otherwise, `PatternError`.

Thoughts?

**Comment by terryjreedy** [comment]
I prefer PatternError over RESyntaxError over RECompileError

**Comment by terryjreedy** [comment]
I merged the near-minimal PR with re.error 'updated' only in idlelib.  I will do adjusted backports of the idlelib changes to keep the main bodies of its files in sync and then close.
