### ISSUE TITLE
Python launcher on Windows does not detect active venv

### ISSUE THREAD

**Issue by 96b0706d-37af-4a15-ab8c-3fcb90c88b9d** [python/cpython#83180]
BPO | [38999](https://bugs.python.org/issue38999)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @RossBoylan

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-12-08.18:49:03.610>
labels = ['type-bug', '3.10', 'OS-windows']
title = 'Python launcher on Windows does not detect active venv'
updated_at = <Date 2021-03-27.04:15:08.040>
user = 'https://bugs.python.org/AlexandrosKarypidis'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-27.04:15:08.040>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2019-12-08.18:49:03.610>
creator = 'Alexandros Karypidis'
dependencies = []
files = []
hgrepos = []
issue_num = 38999
keywords = []
message_count = 12.0
messages = ['358017', '358018', '358020', '358061', '358155', '358186', '358277', '358282', '358312', '358313', '358856', '389588']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'Alexandros Karypidis', 'rossb']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38999'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-108101

**Comment by Baljak** [comment]
This issue is not specific to virtual environments, because according to the Windows Launcher documentation, the first Python executable found in PATH should be used by the launcher instead of the default one:

> The /usr/bin/env form of shebang line has one further special property. Before looking for installed Python interpreters, this form will search the executable PATH for a Python executable matching the name provided as the first argument. This corresponds to the behaviour of the Unix env program, which performs a PATH search. If an executable matching the first argument after the env command cannot be found, but the argument starts with python, it will be handled as described for the other virtual commands. The environment variable PYLAUNCHER_NO_SEARCH_PATH may be set (to any value) to skip this search of PATH.

And in fact, this is perfectly valid when putting the shebang line `#!/usr/bin/env python`, but not with `#!/usr/bin/env python3`, while it clearly should work too in this case.

As a side note, I work on a cross-platform code that heavily relies on Python scripts for its execution and we bundle a specific version of Python with it. Because of this, we also tweak the `PATH` environment variable to ensure that this version is used. Now, the current issue is quite a problem since our scripts are hosted on a Git repository with the `#!/usr/bin/env python3` shebang line, to make them work on Linux, but this requires any Windows user to patch these scripts manually to make them work on their OS, by replacing the shebang line with `#!/usr/bin/env python`. And this is not great way, actually.

**Comment by zooba** [comment]
It's probably easier to copy/rename the `python.exe` to `python3.exe` than to modify the scripts.

What that section of documentation means is that it'll find an executable matching the name (`python` or `python3` in your examples) and treat it as a Python executable. If it doesn't find anything, it falls back to the well-known templates, where `python3` gets treated as `py -3` which overrides the `VIRTUAL_ENV` environment variable.

So that either makes this a request for `python3` to match files name `python.exe` when searching PATH (and the `*w.exe` and `*_d.exe` variations we also may have installed), or a request for `py -3` to prefer `VIRTUAL_ENV` rather than its regular search. Either of these would be technically a breaking change, so we have to make the case for it, but it's possible that we could.

**Comment by Baljak** [comment]
> It's probably easier to copy/rename the `python.exe` to `python3.exe` than to modify the scripts.

Renaming `python.exe` to `python3.exe` does not work with the Launcher provided with Python 3.10.
