### ISSUE TITLE
Uninstalling 3.8.0 fails but it says it succeeds..

### ISSUE THREAD

**Issue by d7c51c7a-88e9-4cce-81b3-415a6ce045cc** [python/cpython#83251]
BPO | [39070](https://bugs.python.org/issue39070)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba
Files | <li>[Python 3.8.0 (32-bit)_20191217003514.log](https://bugs.python.org/file48788/Python%203.8.0%20%2832-bit%29_20191217003514.log "Uploaded as text/plain at 2019-12-18.22:32:44 by tuijatuulia")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-12-16.23:42:54.184>
labels = ['type-bug', '3.8', 'OS-windows']
title = 'Uninstalling 3.8.0 fails but it says it succeeds..'
updated_at = <Date 2019-12-19.21:50:24.920>
user = 'https://bugs.python.org/tuijatuulia'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-19.21:50:24.920>
actor = 'steve.dower'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2019-12-16.23:42:54.184>
creator = 'tuijatuulia'
dependencies = []
files = ['48788']
hgrepos = []
issue_num = 39070
keywords = []
message_count = 6.0
messages = ['358526', '358569', '358628', '358631', '358648', '358691']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'tuijatuulia']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39070'
versions = ['Python 3.8']
```

</p></details>

**Comment by parched** [comment]
I'm having the same problem with any version of python. Most recently I've tried with 3.11.0. It says it uninstalled correctly but everything still there in C:\Users\james.duley\AppData\Local\Programs\Python\Python311 and the registry
![image](https://user-images.githubusercontent.com/5975405/199435370-564b9191-a7b5-4b7d-9690-1248e5d150ff.png)

 I've attached the log, hopefully that helps @zooba 
[Python 3.11.0 (64-bit)_20221102205851.log](https://github.com/python/cpython/files/9917821/Python.3.11.0.64-bit._20221102205851.log)

**Comment by zooba** [comment]
Interesting. It seems to have detected both RC releases:

```
[5314:8918][2022-11-02T20:58:51]i102: Detected related bundle: {70dc31a7-6af1-45de-a4bd-c6c0531d4629}, type: Upgrade, scope: PerUser, version: 3.11.122.0, operation: MajorUpgrade
[5314:8918][2022-11-02T20:58:51]i000: Detected previous version - planning upgrade
...
[5314:8918][2022-11-02T20:58:51]i102: Detected related bundle: {a4b9de24-dc08-4013-a411-9a04c841ed1c}, type: Upgrade, scope: PerUser, version: 3.11.121.0, operation: MajorUpgrade
[5314:8918][2022-11-02T20:58:51]i000: Detected previous version - planning upgrade
...
```

The upgrade appears to have worked, but apparently the older versions are still registered, and because they say they require the same packages they aren't being removed.

I suspect if you've still got the RC installers around, running them should give you a separate "Uninstall" button, and once you do all of them then it'll be properly removed. But this is something I can try to reproduce, so thanks!

**Comment by parched** [comment]
It appears the older patch versions aren't being properly uninstalled when I upgrade. I have just been downloading the newer installer and running it without uninstalling the old version, is that what I'm supposed to do?

![image](https://user-images.githubusercontent.com/5975405/199571417-5c7822c9-d4c5-4cb0-b0f8-cd299ee61f7b.png)

**Comment by zooba** [comment]
Yes, you're doing the right thing. But that's an impressive number of installs that aren't being removed... I don't suppose you have any ideas what may be causing that? Or any older log files from when you installed them?

**Comment by parched** [comment]
I have no clue unfortunately, but happy to investigate some things if you have any ideas. I have a lot of logs, I'm not sure which ones are useful, so I've zipped them
[python-install-logs.zip](https://github.com/python/cpython/files/9923378/python-install-logs.zip)
![image](https:/,/user-images.githubusercontent.com/5975405/199578866-5dc07d75-a4b9-4a94-b635-bb9000d6d5e1.png)

**Comment by zooba** [comment]
Okay, this looks like the relevant problem (from the 3.10.4 install log):

```
[82F0:8090][2022-04-29T11:25:33]i301: Applying execute package: {21b42743-c8f9-49d7-b8b6-b5855317c7ed}, action: Uninstall, path: C:\Users\USERNAME\AppData\Local\Package Cache\{21b42743-c8f9-49d7-b8b6-b5855317c7ed}\python-3.10.0-amd64.exe, arguments: '"C:\Users\USERNAME\AppData\Local\Package Cache\{21b42743-c8f9-49d7-b8b6-b5855317c7ed}\python-3.10.0-amd64.exe" -uninstall -quiet -burn.related.upgrade -burn.ancestors={20ae9c9d-53ff-44e7-973b-efb518e01971} -burn.filehandle.self=1268'
[82F0:8090][2022-04-29T11:25:33]e000: Error 0x800704ec: Failed to create embedded process at path: C:\Users\USERNAME\AppData\Local\Package Cache\{21b42743-c8f9-49d7-b8b6-b5855317c7ed}\python-3.10.0-amd64.exe
[82F0:8090][2022-04-29T11:25:33]e000: Error 0x800704ec: Failed to run bundle as embedded from path: C:\Users\USERNAME\AppData\Local\Package Cache\{21b42743-c8f9-49d7-b8b6-b5855317c7ed}\python-3.10.0-amd64.exe
[82F0:8090][2022-04-29T11:25:33]e000: Error 0x800704ec: Failed to configure per-user EXE package.
[82F0:8090][2022-04-29T11:25:33]w350: Applied non-vital package: {21b42743-c8f9-49d7-b8b6-b5855317c7ed}, encountered error: 0x800704ec. Continuing...
```

Error code 0x800704EC means that the program is blocked by group policy, so there's some additional configuration on your machine that makes us unable to run the previous installer to remove its dependency.[^1] This could also happen if you go in and delete the cache, but that's not the case here.

I have no idea which policy might cause this. You could try going to those paths above and running the uninstallers directly? They _might_ refuse to run because a newer version is installed, but if they run they should clean up their own bits and leave the newer version behind (or remove it, if they're the last one).

[^1] I don't know for sure why it works like this - we just use Wix Toolset for our installer, along with much of the professional Windows software development community. I guess it doesn't know for sure that it's replace all the components, so it needs the original installer to run in case it has to remove something that the new installer doesn't even know about?

**Comment by zooba** [comment]
In terms of what we're going to do about it, probably the best option is to try and detect that error and point users to a helpful page. The `Tools/msi/bundle/bootstrapper` app should get a callback for dealing with "related bundles", and that might include the error. If it doesn't, there's probably nothing we can do, short of replacing the entire install process (which I'm regularly thinking about, but no plans yet)

**Comment by parched** [comment]
I spoke to someone from our IT department and he said they block anything in AppData from running unless it's whitelisted, so he's going to add the Python installer certificate.

**Comment by parched** [comment]
Thanks for the help debugging this @zooba. With the certs added to the whitelist everything uninstalled just using add/remove programs, although it looked like I had to run them in a certain order (newest to oldest, I think).

**Comment by zooba** [comment]
I've had a look at a few options and I don't think there's any change we can make to help avoid this kind of issue in the future (short of rewriting the entire installer, which I'm not super thrilled about doing...). Publishing the MSIX packages with instructions on how to side-load would be a better path forward, though still wouldn't have helped here.

Closing this issue because there's nothing we can do for it.
