### ISSUE TITLE
StreamReader.readexactly() raises GeneratorExit on ProactorEventLoop

### ISSUE THREAD

**Issue by 45bf83a6-23ac-4b3a-83de-214f929d7580** [python/cpython#83297]
BPO | [39116](https://bugs.python.org/issue39116)
--- | :---
Nosy | @asvetlov, @gsalgado, @1st1, @twisteroidambassador, @matthewscholefield
Files | <li>[prettysocks.py](https://bugs.python.org/file49532/prettysocks.py "Uploaded as text/plain at 2020-10-20.17:41:54 by @twisteroidambassador")</li><li>[error_log_on_linux_python38.txt](https://bugs.python.org/file49534/error_log_on_linux_python38.txt "Uploaded as text/plain at 2020-10-21.11:03:27 by @twisteroidambassador")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-12-21.16:04:36.435>
labels = ['type-bug', '3.8', '3.9', 'expert-asyncio']
title = 'StreamReader.readexactly() raises GeneratorExit on ProactorEventLoop'
updated_at = <Date 2020-11-29.00:12:06.904>
user = 'https://github.com/twisteroidambassador'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-29.00:12:06.904>
actor = 'matthew'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-12-21.16:04:36.435>
creator = 'twisteroid ambassador'
dependencies = []
files = ['49532', '49534']
hgrepos = []
issue_num = 39116
keywords = []
message_count = 5.0
messages = ['358774', '378931', '379149', '379205', '382027']
nosy_count = 5.0
nosy_names = ['asvetlov', 'salgado', 'yselivanov', 'twisteroid ambassador', 'matthew']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39116'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment]
First the reproducer is very large, you should try to reduce it. I tried it and wasn't able to reproduce the reported errors. It is possible that is already fixed as this bug is 3 years old.  @twisteroidambassador Can you try it on latest main?

**Comment by gvanrossum** [comment]
I wonder if the problem is solved by GH-96323? There was a task created by `connection_made()` (only when there was a callback for that event) that wasn't kept alive, so a poorly timed GC run would destroy the task.

But the reproducer is definitely too big to definitively declare that this was the root cause.

**Comment by twisteroidambassador** [comment]
Reproducing this bug has always been difficult. It happens maybe once or twice a day for my program that runs all day long. The only thing I can say for certain is that it still exists on Python 3.9.9 + Windows 10.

I see that GH-96323 has been merged and backported to 3.10 and 3.11, but it haven't made into any release yet. I am going to build a 3.10 from git and see whether it still has this bug.

**Comment by twisteroidambassador** [comment]
I just caught this bug in 3.10.7 (official installer).

The traceback is no help at all. It's only one layer deep, like this:

```
Traceback (most recent call last):
  File "***", line ***, in ***
    buf = await ureader.readexactly(2)
GeneratorExit
```

It is happening when a freshly-connected StreamReader is being read for the first time (although the associated StreamWriter has been written to once already), so GH-96323 does sound plausible.

**Comment by gvanrossum** [comment]
Could you post the exact code to reproduce? The traceback by itself is (as you say) not helpful.

**Comment by gvanrossum** [comment]
FWIW that error about task destroyed but pending could mean you have code that calls create_task() but doesn't hold onto the task object until it's completed. (We added a note about this to the docs recently.)

**Comment by gvanrossum** [comment]
[me]
> Could you post the exact code to reproduce? The traceback by itself is (as you say) not helpful.

Never mind, I realize now that you're observing this vry occasionally in a large production app. And that the 3.10.7 you're using there does not have the GH-96323 fix. And that the orphan task being reaped is an internal task (which that PR fixes). Also, as we all know by now from earlier comments, GeneratorExit comes from a coroutine (the result of calling an async function) getting closed. So this basically boils down to "no new info yet".

**Comment by gvanrossum** [comment]
Also, Python 3.10.8 was just released, for an unrelated security fix, but it has the fix. So you can upgrade your production to that (I know, that's probably a pain) and eventually you can report that it's gone... Or not!

**Comment by twisteroidambassador** [comment]
Unfortunately I can't post the code

> FWIW that error about task destroyed but pending could mean you have code that calls create_task() but doesn't hold onto the task object until it's completed. (We added a note about this to the docs recently.)

Thanks for pointing this out! I believe this may be my immediate problem. I do have a task that I start up and forget about around the problematic area.

By having a background thread calling `gc.collect()` on a loop, I was able to trigger a `GeneratorExit` in relatively short time. I have added a strong reference to this task, and will see whether it fixes my issue.

Side note: I'm having a hard time wrapping my head around the "task being gc'd" concept. Say I write a coroutine that does not explicitly refer to its own task (no calling `asyncio.current_task()` or anything similar). I create a Task from the coroutine, and does not keep a strong reference to it. Now the Task has no strong references at all. When might the Task be garbage collected? Does it matter whether the Task is currently being run by the event loop or not?

Say I write another coroutine, which keeps a reference to `asyncio.current_task()`. I create a Task from this new coroutine, but still does not keep a strong reference to it otherwise. Now the Task has a circular reference to itself, so will it be garbage collected by a sufficiently motivated GC?

In the case of GH-96323, the fix is to keep a reference of `<Task _client_connected_cb>` in the `StreamReaderProtocol` instance. This task is called with arguments `(StreamReader, StreamWriter)`, so once the Task starts to run it will hold a circular reference to itself. All of these are in context of a `asyncio.base_events.Server` receiving a new connection, so the Task is started by asyncio machinery, and the programmer only gain access to this Task until it starts running, and only from within the Task itself. 

So, is there a possibility that a) the `StreamReaderProtocol` gets gc'd before `<Task _client_connected_cb>` starts running, or b) `StreamReaderProtocol`, `<Task _client_connected_cb>` and related instances all gets gc'd after the Task started but before it finishes, if the programmer does not explicitly save a strong reference to the Task somewhere?

**Comment by twisteroidambassador** [comment]
I'll try to trace the creation of `<Task _client_connected_cb>` with a SelectorEventLoop:

When an incoming connection is being accepted, the loop calls [`selector_events.BaseSelectorEventLoop._accept_connection`](https://github.com/python/cpython/blob/c39a0c335486fa8eac0f3030930f9e8769118a4f/Lib/asyncio/selector_events.py#L157-L161) which calls [`selector_events.BaseSelectorEventLoop._accept_connection2`](https://github.com/python/cpython/blob/c39a0c335486fa8eac0f3030930f9e8769118a4f/Lib/asyncio/selector_events.py#L203-L207). It [creates an instance of `StreamReaderProtocol` by calling `protocol_factory`](https://github.com/python/cpython/blob/c39a0c335486fa8eac0f3030930f9e8769118a4f/Lib/asyncio/selector_events.py#L211), which is [defined here](https://github.com/python/cpython/blob/c39a0c335486fa8eac0f3030930f9e8769118a4f/Lib/asyncio/streams.py#L78-L82). (`StreamReaderProtocol` [holds a strong reference to `StreamReader` it needs](https://github.com/python/cpython/blob/c39a0c335486fa8eac0f3030930f9e8769118a4f/Lib/asyncio/streams.py#L198-L202).) [Then a Transport is created (I'm only tracing the non-ssl tranport here)](https://github.com/python/cpython/blob/c39a0c335486fa8eac0f3030930f9e8769118a4f/Lib/asyncio/selector_events.py#L220-L222), which [holds a strong reference to the Protocol](https://github.com/python/cpython/blob/0895c2a066c64c84cab0821886dfa66efc1bdc2f/Lib/asyncio/selector_events.py#L775), and [saves a strong reference of the Protocol and itself in the event loop via call_soon](https://github.com/python/cpython/blob/0895c2a066c64c84cab0821886dfa66efc1bdc2f/Lib/asyncio/selector_events.py#L910-L913)).

The loop first runs [`streams.StreamReaderProtocol.connection_made`](https://github.com/python/cpython/blob/c39a0c335486fa8eac0f3030930f9e8769118a4f/Lib/asyncio/streams.py#L224). It creates a StreamWriter (which holds a strong reference to the Transport), then creates a Task with `client_connected_cb`, binding StreamReader and StreamWriter to the Task, and *saves a strong reference of the Task (GH-96323)*. It then removes the Protocol's direct strong reference to StreamReader.

The loop then runs `selector_events._SelectorTransport._add_reader`, binding the Transport to the event loop.

So at this point, the event loop keeps the Transport alive, the Transport keeps the Protocol alive, the Protocol has a strong reference to `<Task _client_connected_cb>` which keeps StreamReader and StreamWriter alive. Sounds good. I believe the event loop should keep the Transport alive until the underlying connection is done?

**Comment by gvanrossum** [comment]
I think that's correct. I've never heard of problems where transports or protocols are GC'ed prematurely -- AFAICT this is only an issue with Tasks. I don't actually know (because it's so hard to trace) what state the coroutine is in when this is happening, but it must be in a state where closing it will send a GeneratorExit exception into the coroutine (have fun with genobject.c if you want to trace this more precisely).

I hope that at some point you can confirm that either updating to 3.10.8 or by adding a hard ref to your own task(s) the problem is gone for you.

One final note, probably a red herring. In your attached error log I notice that one of your traceback lines occurs in concurrent/futures/thread.py -- that's a totally different kind of Future (though it has a similar API). If you're not being careful with threads (I can't tell from the error alone if you are or aren't), some very different caveats apply -- you should never do anything from a different thread than the one where the loop is running, _except_ calling `loop.call_soon_threadsafe()`.

**Comment by twisteroidambassador** [comment]
Since making sure every task created has hard references, I haven't seen a single GeneratorExit in the past month. I think it's safe to declare the problem solved!

**Comment by gvanrossum** [comment]
Thanks for checking!
