### ISSUE TITLE
Sqlite3 row_factory for attribute access: NamedRow

### ISSUE THREAD

**Issue by 521f8815-f67e-48ea-929f-5d9862ff6b15** [python/cpython#83351]
BPO | [39170](https://bugs.python.org/issue39170)
--- | :---
Nosy | @erlend-aasland, @jidn
PRs | <li>python/cpython#17768</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-12-31.06:57:54.312>
labels = ['type-feature', 'library', '3.9']
title = 'Sqlite3 row_factory for attribute access: NamedRow'
updated_at = <Date 2021-06-02.14:17:40.379>
user = 'https://github.com/jidn'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-02.14:17:40.379>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-12-31.06:57:54.312>
creator = 'jidn'
dependencies = []
files = []
hgrepos = []
issue_num = 39170
keywords = ['patch']
message_count = 2.0
messages = ['359104', '394911']
nosy_count = 2.0
nosy_names = ['erlendaasland', 'jidn']
pr_nums = ['17768']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39170'
versions = ['Python 3.9']
```

</p></details>

**Comment by erlend-aasland** [comment]
I'm sorry, but I'm -1 to adding this to the sqlite3 extension module. If we are to add a named row class, I would prefer to go with the approach in gh-57508, because it is magnitudes simpler. _If_ the namedtuple approach was implemented and performance is unacceptable, we could look into improving it by revisiting your PR[^1].

For now, I recommend to close this issue and the linked PR as won't-fix.

Thanks for your interest in improving CPython!

[^1]: After a quick glance, the C code in your PR looks good, AFAICS.
