### ISSUE TITLE
Python shelve __del__ ignored exception

### ISSUE THREAD

**Issue by a67aeeb0-9500-4ee2-934f-422385022e0b** [python/cpython#83383]
BPO | [39202](https://bugs.python.org/issue39202)
--- | :---
Nosy | @libbkmz
Files | <li>[test_python_shelve_issue.py](https://bugs.python.org/file48826/test_python_shelve_issue.py "Uploaded as text/plain at 2020-01-03.16:19:52 by @libbkmz"): python testcases via unittests library to reproduce the issue</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-01-03.16:19:53.484>
labels = ['3.8', 'type-feature', 'library']
title = 'Python shelve __del__ ignored exception'
updated_at = <Date 2020-01-03.16:19:53.484>
user = 'https://github.com/libbkmz'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-03.16:19:53.484>
actor = 'libbkmz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-01-03.16:19:53.484>
creator = 'libbkmz'
dependencies = []
files = ['48826']
hgrepos = []
issue_num = 39202
keywords = []
message_count = 1.0
messages = ['359242']
nosy_count = 1.0
nosy_names = ['libbkmz']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39202'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-114560

**Comment by serhiy-storchaka** [comment]
It is not a bug. If you do not close the database explicitly, it will be implicitly closed in the `__del__()` method. And this happens when the local variable `memoize` is rebound, which happens only after a new database referring to the same files is opened. Opening multiple databases that use the same files is not supported.

But it is good idea to mark the database as unmodified after synchronization or creation and avoid any writing in `__del__()` if there was no modifications since that moment. It helps to save data, even if the use of the database is not perfect.
