### ISSUE TITLE
NamedTemporaryFile could cause double-close on an fd if _TemporaryFileWrapper throws

### ISSUE THREAD

**Issue by 4b4bffee-c0a5-4c36-b1d7-404ef2ef29b0** [python/cpython#83499]
BPO | [39318](https://bugs.python.org/issue39318)
--- | :---
Nosy | @nedbat, @sethtroisi, @albertz, @serhiy-storchaka, @eryksun, @jstasiak, @sanjioh, @joernheissler
PRs | <li>python/cpython#17985</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2020-01-13.04:56:47.144>
labels = ['3.8', 'type-bug', 'library', '3.9', '3.10']
title = 'NamedTemporaryFile could cause double-close on an fd if _TemporaryFileWrapper throws'
updated_at = <Date 2021-03-28.03:37:24.913>
user = 'https://bugs.python.org/nneonneo'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-28.03:37:24.913>
actor = 'eryksun'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-01-13.04:56:47.144>
creator = 'nneonneo'
dependencies = []
files = []
hgrepos = []
issue_num = 39318
keywords = ['patch']
message_count = 10.0
messages = ['359888', '359892', '359935', '359957', '359959', '360040', '360041', '360071', '360084', '360104']
nosy_count = 12.0
nosy_names = ['nneonneo', 'nedbat', 'Seth.Troisi', 'Albert.Zeyer', 'serhiy.storchaka', 'paul_ollis', 'eryksun', 'jstasiak', 'sanjioh', 'joernheissler', 'hitbox', 'rekcartgubnohtyp']
pr_nums = ['17985']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39318'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
See #93874. It was mostly ready (except a NEWS entry and some polishing) more than 2 years ago. Now I do not remember why it was not finished at that time -- either I just put it off until the next morning, but was distracted by other issues and forgot about it, or I found some issues with it, or I found a better way. So please make a careful review.

Maybe it was deferred because there is a very tiny possibility of a file descriptor leak if you interrupt the program between `os.open()` and `return`. It is a part of more general issue and is not solvable at the moment.
