### ISSUE TITLE
Py_Initialize Hangs on Windows 10

### ISSUE THREAD

**Issue by c66cedae-26a6-44fd-a569-d31a302229ef** [python/cpython#83526]
BPO | [39345](https://bugs.python.org/issue39345)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba
Files | <li>[dup-hang.c](https://bugs.python.org/file50099/dup-hang.c "Uploaded as text/x-csrc at 2021-06-09.02:44:42 by duaneg")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-01-15.18:55:56.242>
labels = ['3.7', 'type-bug', 'library', 'OS-windows']
title = 'Py_Initialize Hangs on Windows 10'
updated_at = <Date 2021-06-09.02:44:42.595>
user = 'https://bugs.python.org/dhamilton'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-09.02:44:42.595>
actor = 'duaneg'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2020-01-15.18:55:56.242>
creator = 'dhamilton'
dependencies = []
files = ['50099']
hgrepos = []
issue_num = 39345
keywords = []
message_count = 4.0
messages = ['360070', '375628', '375639', '395377']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'duaneg', 'zach.ware', 'steve.dower', 'dhamilton', 'ph.fieschi']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39345'
versions = ['Python 3.7']
```

</p></details>

**Comment by yqs112358** [comment]
This problem still exists on Python3.10.9, when I use Py_NewInterpreter to create new sub-interpreters for my embedded python. It is the same problem as Py_Initialize because the thread hang at the same place.
See more at https://stackoverflow.com/questions/71892914/python-c-api-py-newinterpreter-freezes-thread-when-creating-new-sys-stdin

The situation is like this: when I call Py_NewInterpreter in another thread different from the main thread of console application, current thread freeze until I input an EOF by Ctrl+Z and press enter. Then the program continues to work properly (the sub-intepreter created successfully), but I cannot input anything into console after this. I believe that either the stdin is hijacked by the new sub-interpreter, or stdin is damaged somehow.
If you need, i can upload a video about the situation with VS stacktrace.

**Comment by yqs112358** [comment]
I tried "_close(0)" to temporarily disable stdin and then call Py_NewInterpreter, but the problem is not solved. The thread still freezes.

**Comment by yqs112358** [comment]
I got a temporary solution: start a new thread to execute Win32 API CancelIoEx on `stdin` before calling Py_NewInterpreter, which looks like this:
```cpp
std::thread([](){
	Sleep(50);
	CancelIoEx(GetStdHandle(STD_INPUT_HANDLE), NULL);
}).detach();
```

But this solution not seems good as we don't know exactly when dup2() happens to block after the execution of Py_NewInterpreter. Also it need to call Win32 APIs, which is not suitable for projects like CPython.
Is there a bette way to temporarily ban stdin before dup2(), and recover it when finishing working?

**Comment by zooba** [comment]
I think @eryksun just pointed this same problem out in #102765, so we may need to factor it into this code path as well.

Though I wonder if in this case we'd be better off with a way to preemptively set up stdio for Python, rather than trying to infer it? That could bypass this code entirely, and generally help embedders provide their own read/write functions.

As a rule, we shouldn't require use of global resources in CPython when embedding. Right now, we're pretty bad about that, but it's the direction we'd want to move in. Allowing host apps to completely handle std streams would fit.

**Comment by yqs112358** [comment]
> I think @eryksun just pointed this same problem out in #102765, so we may need to factor it into this code path as well.
> 
> Though I wonder if in this case we'd be better off with a way to preemptively set up stdio for Python, rather than trying to infer it? That could bypass this code entirely, and generally help embedders provide their own read/write functions.
> 
> As a rule, we shouldn't require use of global resources in CPython when embedding. Right now, we're pretty bad about that, but it's the direction we'd want to move in. Allowing host apps to completely handle std streams would fit.

Thanks for your remind. Hopefully Python can make more improvements for embedding in the future. I know that a number of useful improvements will be made to the sub-interpreter in Python 3.12, including splitting the GIL and so on. I'm sure these efforts will work.

I'm trying to see if I can avoid blocking by modifying stdio beforehand. If there is any success I'll post it here

**Comment by eryksun** [comment]
The implementation of `is_valid_fd()` was made faster and generally safer in Python 3.11:

https://github.com/python/cpython/blob/c834a4c713f2fb55de1658bffd77d8ef070cf2d2/Python/pylifecycle.c#L2202-L2208

`GetFileType()` calls `NtQueryVolumeInformationFile()` to get the file's `FileFsDeviceInformation`. If the file object is a direct, local open, then the I/O manager implements this query without having to call the filesystem driver and synchronize on the file object. On the other hand, it does have to call the driver and synchronize on the file if it's opened on a redirected filesystem (i.e. `FILE_DEVICE_NETWORK_FILE_SYSTEM`). That's only a concern in general for a remote pipe or mailslot. The chances of using a remote pipe for standard I/O are slim to none.

**Comment by eryksun** [comment]
Note that there are still problems with `lseek()` calls. For example, the following hangs Python at startup until the console read in the parent process is completed (i.e. until enter is pressed).

```pycon
>>> import os, subprocess, threading
>>> env = os.environ.copy()
>>> env['PYTHONLEGACYWINDOWSSTDIO'] = '1'
>>> th = threading.Thread(target=input)
>>> th.start(); p = subprocess.Popen('python', env=env); th.join(); p.wait()
```

It's easy to see why using an attached debugger:

```text
0:000> kc 8
Call Site
ntdll!NtQueryInformationFile
KERNELBASE!SetFilePointerEx
ucrtbase!common_lseek_nolock<__int64>
ucrtbase!common_lseek<__int64>
ucrtbase!lseeki64
python311!portable_lseek
python311!_io_FileIO_tell_impl
python311!_io_FileIO_tell
```

The child inherits its console input file from the parent. Since the parent is doing a synchronized read on this file, the `NtQueryInformationFile()` call in the child hangs until it can acquire the file lock.

The I/O manager allows setting the file pointer of a synchronous pipe or console file, but it's meaningless. We could protect `lseek()` calls to either do nothing or fail if the file type isn't `FILE_TYPE_DISK`.

**Comment by zooba** [comment]
So it sounds like this hang is no longer an issue on 3.11? Can anyone suffering from the problem confirm?

**Comment by hugovk** [comment]
> So it sounds like this hang is no longer an issue on 3.11? Can anyone suffering from the problem confirm?

No complaints in seven months: let's assume it's now fine, and we can re-open again if needed.
