### ISSUE TITLE
Enhancement: add `os.getdtablesize(..)` to `os` (`posix`) module

### ISSUE THREAD

**Issue by cd099432-c439-4196-9816-d22314ec360c** [python/cpython#83923]
BPO | [39742](https://bugs.python.org/issue39742)
--- | :---
Nosy | @larryhastings, @ngie-eign

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-24.20:36:13.030>
labels = ['type-feature', 'library', '3.9']
title = 'Enhancement: add `os.getdtablesize(..)` to `os` (`posix`) module'
updated_at = <Date 2020-02-29.00:21:12.093>
user = 'https://github.com/ngie-eign'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-29.00:21:12.093>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-02-24.20:36:13.030>
creator = 'ngie'
dependencies = []
files = []
hgrepos = []
issue_num = 39742
keywords = []
message_count = 1.0
messages = ['362603']
nosy_count = 2.0
nosy_names = ['larry', 'ngie']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39742'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-124411

**Comment by serhiy-storchaka** [comment]
There are already two ways to get the same value: `os.sysconf("SC_OPEN_MAX")` and `resource.getrlimit(resource.RLIMIT_NOFILE)`. They are even more portable, because both functions are in POSIX, unlike `getdtablesize()`.

For now, #124411 changes 8 files, has 15 commits and gathered 26 comments for 8 hours. It is obvious that the cost of this feature is pretty high. It may grow to hundreds of comments if we discuss it on discuss.python.org.

On other hand, the benefit is pretty small, taking into account existing alternatives. I suggest to close this issue.

**Comment by vstinner** [comment]
I don't think that it's worth it to add this function, see https://github.com/python/cpython/pull/124411 for the rationale.

You can use already `resource.getrlimit(resource.RLIMIT_NOFILE)[0]` and `os.sysconf("SC_OPEN_MAX")`.
