### ISSUE TITLE
Non-working error handler when creating a task with assigning a variable

### ISSUE THREAD

**Issue by 05386ae6-1bae-4323-9b4b-50528540db51** [python/cpython#84020]
BPO | [39839](https://bugs.python.org/issue39839)
--- | :---
Nosy | @asvetlov, @cjrh, @cjerdonek, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-03-03.18:24:30.080>
labels = ['3.7', 'expert-asyncio']
title = 'Non-working error handler when creating a task with assigning a variable'
updated_at = <Date 2020-05-19.00:58:36.307>
user = 'https://bugs.python.org/rshakh'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-19.00:58:36.307>
actor = 'chris.jerdonek'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2020-03-03.18:24:30.080>
creator = 'rshakh'
dependencies = []
files = []
hgrepos = []
issue_num = 39839
keywords = []
message_count = 4.0
messages = ['363287', '363290', '364274', '369311']
nosy_count = 5.0
nosy_names = ['asvetlov', 'cjrh', 'chris.jerdonek', 'yselivanov', 'rshakh']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue39839'
versions = ['Python 3.7']
```

</p></details>

**Comment by kumaraditya303** [comment]
The exception handler is only called if the task was garbage collected and is pending. This usually happens when a task was created but there is no reference to it. It is documented at https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task

**Comment by gvanrossum** [comment]
Ironically this "bug" reported in this issue is actually (although the OP never quite comes out and says it) that the task raises an exception but that exception is never reported. Following the advice that we recently added to the docs (basically "hold on to the task") _causes_ the "bug". If you disregard the advice, not assigning the task to a variable, the exception handler is called (unless the task gets GC'ed before it is scheduled to run, which is rare but possible since you didn't hang on to it :-).

Maybe we need to add another piece of advice: await the task in order to get an exception reported. However, the best advice is to use TaskGroup, which propagates exceptions from all tasks (since it awaits all of them). Also use asyncio.run(), which reports exceptions propagated to the main() coroutine.
