### ISSUE TITLE
`pathlib.Path.expanduser()` does not call `os.path.expanduser()`

### ISSUE THREAD

**Issue by 4b0c5ead-8181-475a-af87-9342ce46c4e3** [python/cpython#84080]
BPO | [39899](https://bugs.python.org/issue39899)
--- | :---
Nosy | @serhiy-storchaka, @eryksun, @zooba, @barneygale, @Fidget-Spinner, @akulakov
PRs | <li>python/cpython#18841</li><li>python/cpython#25277</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-04-09.22:03:46.934>
created_at = <Date 2020-03-08.05:06:12.759>
labels = ['library', '3.10']
title = '`pathlib.Path.expanduser()` does not call `os.path.expanduser()`'
updated_at = <Date 2021-09-06.17:52:12.404>
user = 'https://github.com/barneygale'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-06.17:52:12.404>
actor = 'andrei.avk'
assignee = 'none'
closed = True
closed_date = <Date 2021-04-09.22:03:46.934>
closer = 'steve.dower'
components = ['Library (Lib)']
creation = <Date 2020-03-08.05:06:12.759>
creator = 'barneygale'
dependencies = []
files = []
hgrepos = []
issue_num = 39899
keywords = ['patch']
message_count = 19.0
messages = ['363635', '363636', '363637', '363639', '363644', '363647', '363652', '390449', '390452', '390461', '390477', '390494', '390497', '390504', '390507', '390528', '390669', '401167', '401168']
nosy_count = 6.0
nosy_names = ['serhiy.storchaka', 'eryksun', 'steve.dower', 'barneygale', 'kj', 'andrei.avk']
pr_nums = ['18841', '25277']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue39899'
versions = ['Python 3.10']
```

</p></details>

**Comment by zahlman** [comment]
Relatedly: `Path('./~').expanduser()` (or with any number of leading `./` components) will expand, where `os.path.expanduser('./~')` gives back `'./~'`. This is because the `.` components are dropped while creating the `Path` object. (It doesn't matter what the current working directory is; the path isn't being *resolved* here.) Not a bug (at least IMHO), but noteworthy for anyone migrating code who expected to conditionally disable path expansion by supplying a value like that.
