### ISSUE TITLE
Ignore specific errors when closing ssl connections

### ISSUE THREAD

**Issue by 1e3445ee-1357-417d-a204-0863cf864f91** [python/cpython#84132]
BPO | [39951](https://bugs.python.org/issue39951)
--- | :---
Nosy | @tiran, @fantix, @asvetlov, @dimaqq, @1st1, @kumaraditya303

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-03-12.14:03:27.004>
created_at = <Date 2020-03-13.03:40:00.997>
labels = ['expert-SSL', 'type-bug', '3.9', '3.10', '3.11', 'expert-asyncio']
title = 'Ignore specific errors when closing ssl connections'
updated_at = <Date 2022-03-12.14:03:27.004>
user = 'https://github.com/dimaqq'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-12.14:03:27.004>
actor = 'asvetlov'
assignee = 'none'
closed = True
closed_date = <Date 2022-03-12.14:03:27.004>
closer = 'asvetlov'
components = ['asyncio', 'SSL']
creation = <Date 2020-03-13.03:40:00.997>
creator = 'Dima.Tisnek'
dependencies = []
files = []
hgrepos = []
issue_num = 39951
keywords = []
message_count = 13.0
messages = ['364071', '364073', '365293', '365299', '379902', '386513', '386514', '386515', '386516', '386518', '386520', '414794', '414798']
nosy_count = 6.0
nosy_names = ['christian.heimes', 'fantix', 'asvetlov', 'Dima.Tisnek', 'yselivanov', 'kumaraditya']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39951'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by vkruglik-aka** [comment]
Hi @asvetlov and @tiran, for the life of me, I can't figure out whether this issue is fixed and released in 3.10 and in which specific bug fix version of 3.10. A comment says that it "should be fixed ...", but not that it is actually fixed and released in 3.10.x. 

I am not seeing it or its older number bpo-39951 in any of the python 3.10.x Changelogs, so can't tell whether it was fixed but is missing from the 3.10.x changelogs or it just never made it to 3.10.x at all.

The reason I am asking is that we're still seeing APPLICATION_DATA_AFTER_CLOSE_NOTIFY on python 3.10.13.
