### ISSUE TITLE
Autogenerate signature for METH_NOARGS and perhaps METH_O extension functions

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#84805]
BPO | [40625](https://bugs.python.org/issue40625)
--- | :---
Nosy | @anntzer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-14.11:46:04.481>
labels = ['expert-C-API', '3.9']
title = 'Autogenerate signature for METH_NOARGS and perhaps METH_O extension functions'
updated_at = <Date 2020-05-14.11:46:04.481>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-14.11:46:04.481>
actor = 'Antony.Lee'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2020-05-14.11:46:04.481>
creator = 'Antony.Lee'
dependencies = []
files = []
hgrepos = []
issue_num = 40625
keywords = []
message_count = 1.0
messages = ['368830']
nosy_count = 1.0
nosy_names = ['Antony.Lee']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue40625'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-107794

**Comment by serhiy-storchaka** [comment]
It is an interesting idea and I implemented it in #107794.

The one difference with Argument Clinic generated signature is that it names the first implicit argument `$module` in module-level functions and `$self` in unbound methods, while my PR use `$self` in both cases. But it does not matter, because it is always removed in module-level functions. The end user never sees a difference until it looks at `__text_signature__` directly.
