### ISSUE TITLE
json.dumps() should encode float number NaN to null

### ISSUE THREAD

**Issue by 10a1cbf5-763e-4aa8-bb14-e0296ea27213** [python/cpython#84813]
BPO | [40633](https://bugs.python.org/issue40633)
--- | :---
Nosy | @rhettinger, @mdickinson, @ericvsmith, @alucab

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-05-18.08:08:12.857>
created_at = <Date 2020-05-15.13:42:04.329>
labels = ['type-feature', 'library', '3.9']
title = 'json.dumps() should encode float number NaN to null'
updated_at = <Date 2020-12-30.12:06:37.163>
user = 'https://bugs.python.org/HaoyuSUN'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-30.12:06:37.163>
actor = 'mark.dickinson'
assignee = 'none'
closed = True
closed_date = <Date 2020-05-18.08:08:12.857>
closer = 'mark.dickinson'
components = ['Library (Lib)']
creation = <Date 2020-05-15.13:42:04.329>
creator = 'Haoyu SUN'
dependencies = []
files = []
hgrepos = []
issue_num = 40633
keywords = []
message_count = 21.0
messages = ['368942', '368944', '368948', '368950', '368959', '369005', '369006', '369043', '369044', '369172', '369188', '369189', '369190', '369191', '369194', '381481', '381491', '383986', '384055', '384059', '384060']
nosy_count = 6.0
nosy_names = ['rhettinger', 'mark.dickinson', 'eric.smith', 'Haoyu SUN', 'arjanstaring', 'alucab']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40633'
versions = ['Python 3.9']
```

</p></details>

**Comment by Dzeri96** [comment]
Sorry to continue a closed discussion but I think adding an option like `nonfinite_to_null` would solve a lot of headaches. It's clear we're in a situation where some functionality has to be sacrificed either way, but choosing not to break every browser in the market warrants implementation of this flag IMO.

**Comment by mdickinson** [comment]
@Dzeri96 

> Sorry to continue a closed discussion [...]

It may be worth opening a new issue, so that the discussion doesn't get lost / hidden. Or I guess we could repurpose and re-open this one, but that doesn't seem like good issue management. (The request on this issue was for JSON encoding to turn NaNs and infinities to null _by default_. That's not viable, both for backwards compatibility breakage reasons and because the result would _still_ not be compliant with JSON.)

> This https://github.com/python/cpython/pull/13233 seems like it might fix the issue

A general mechanism for overriding the float encoding behaviour (or perhaps just the encoding behaviour for nans and infinities) does seem preferable to another boolean flag. That would then support custom uses like "raise on infinities, but encode nans to null", which might fit a lot of scientific data where missing values (represented by nans) are normal and expected but infinities are not.

**Comment by mdickinson** [comment]
> A general mechanism for overriding the float encoding behaviour

Maybe repurpose `allow_nan` itself, extending it to allow a callable to be passed?

**Comment by Dzeri96** [comment]
> Maybe repurpose `allow_nan` itself, extending it to allow a callable to be passed?

That would be a good solution, tough the name of the argument is somewhat limiting unfortunately.
I'll just create a new issue with some alternatives so we can discuss them properly. This issue will be referenced by the new one.
