### ISSUE TITLE
pl.python.org has expired cert and links to nonexistent django.pl page

### ISSUE THREAD

**Issue by f1c7752f-9b0d-4783-9df2-62dcbfbc032d** [python/cpython#84894]
BPO | [40717](https://bugs.python.org/issue40717)
--- | :---
Nosy | @hannob, @ewdurbin, @amaajemyfren

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-21.18:17:25.856>
labels = ['docs']
title = 'pl.python.org has expired cert and links to nonexistent django.pl page'
updated_at = <Date 2020-05-21.20:32:40.360>
user = 'https://github.com/hannob'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-21.20:32:40.360>
actor = 'EWDurbin'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-05-21.18:17:25.856>
creator = 'hanno'
dependencies = []
files = []
hgrepos = []
issue_num = 40717
keywords = []
message_count = 5.0
messages = ['369531', '369535', '369537', '369538', '369539']
nosy_count = 4.0
nosy_names = ['docs@python', 'hanno', 'EWDurbin', 'amaajemyfren']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue40717'
versions = []
```

</p></details>

**Comment by slateny** [comment]
@AlexWaygood Seems like the cert's good now, so should be fine to close

**Comment by AlexWaygood** [comment]
> @AlexWaygood Seems like the cert's good now, so should be fine to close

Closing the issue as out of date (I haven't manually verified but I trust @slateny)

**Comment by slateny** [comment]
> Closing the issue as out of date (I haven't manually verified but I trust @slateny)

@AlexWaygood 👀 Quite a bit of trust there so let me just note these down for the record:

Cert looks good:

![image](https://user-images.githubusercontent.com/46876382/164883602-f3164b33-d1ed-4fbd-b157-3ff656089a39.png)

But http://django.pl/ is still on the page, and seems like the page is dead

![image](https://user-images.githubusercontent.com/46876382/164883641-b8d995ca-d924-4fed-ae81-f81c738b4634.png)

![image](https://user-images.githubusercontent.com/46876382/164883703-8d3e50f4-dfb9-448b-b937-c0037a7449dd.png)

so I don't know whether it'd be considered an issue since it's not exactly a part of *.python.org, and I think it's unlikely that all links on all delegated pages are monitored for validity, so maybe we can still call the issue resolved
