### ISSUE TITLE
Expose PyFloat_AsDouble at Python level: operator.as_float?

### ISSUE THREAD

**Issue by mdickinson** [python/cpython#84978]
BPO | [40801](https://bugs.python.org/issue40801)
--- | :---
Nosy | @mdickinson, @zware, @serhiy-storchaka
PRs | <li>python/cpython#20481</li><li>python/cpython#26827</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-28.09:23:06.760>
labels = ['type-feature', '3.11']
title = 'Expose PyFloat_AsDouble at Python level: operator.as_float?'
updated_at = <Date 2021-06-21.12:00:00.034>
user = 'https://github.com/mdickinson'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-21.12:00:00.034>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2020-05-28.09:23:06.760>
creator = 'mark.dickinson'
dependencies = []
files = []
hgrepos = []
issue_num = 40801
keywords = ['patch']
message_count = 11.0
messages = ['370181', '370189', '370233', '370244', '370247', '370253', '370255', '370258', '370259', '370286', '396234']
nosy_count = 3.0
nosy_names = ['mark.dickinson', 'zach.ware', 'serhiy.storchaka']
pr_nums = ['20481', '26827']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40801'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-110460

**Comment by skirpichev** [comment]
> 2. Call ``type(obj).__float__(obj)``.  But this has several problems: ``__float__`` can return an instance of a float subclass

Since 3.7 it was deprecated (#71170) and maybe it's time to remove this (#109311).

So, it's not an issue in that part.

> calling dunder methods directly should rarely be the Right Way To Do It.

Then why not export ``obj.__float__()`` as ``operator.as_float``.  Same for ``obj.__complex__()`` (as_complex?) or ``obj.__int__()`` (as_int?) - all should return an appropriate type.

Perhaps, a different constructor could be more discoverable option.  But I don't see why we can't expose mentioned above dunder methods just as for the ``__index__``.  Naming?  (i.e. operator.as_float vs operator.float)

**Comment by skirpichev** [comment]
@serhiy-storchaka, probably this can be closed?
