### ISSUE TITLE
urllib.parse.urlunsplit makes relative path to absolute (http:g -> http:///g)

### ISSUE THREAD

**Issue by ce6eff5c-267f-4cdf-b0b8-c897e123fd9f** [python/cpython#85110]
BPO | [40938](https://bugs.python.org/issue40938)
--- | :---
Nosy | @orsenthil, @openandclose, @jaswdr

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-10.11:18:48.328>
labels = ['3.7', '3.8', 'type-bug', 'library', '3.9']
title = 'urllib.parse.urlunsplit makes relative path to absolute (http:g -> http:///g)'
updated_at = <Date 2021-05-13.14:11:56.189>
user = 'https://github.com/openandclose'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-13.14:11:56.189>
actor = 'op368'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-06-10.11:18:48.328>
creator = 'op368'
dependencies = []
files = []
hgrepos = []
issue_num = 40938
keywords = []
message_count = 7.0
messages = ['371179', '393544', '393574', '393576', '393577', '393578', '393583']
nosy_count = 3.0
nosy_names = ['orsenthil', 'op368', 'jaswdr']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40938'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-123179
* gh-123187
* gh-123188

**Comment by serhiy-storchaka** [comment]
The problem is that `urljoin(base, urlunsplit(urlsplit(relurl)))` is not equivalent to `urljoin(base, relurl)`. I think that the problem cannot be solved without large breaking changes (like #67041), but this particular case can be mitigated. `urlunsplit)` can be made preserving non-empty relative path with non-empty scheme and empty netloc.

An exception for empty path was added to not break an existing test for #104139. All other existing tests are passed with this change.
