### ISSUE TITLE
Executing code in thread or process pools: run_in_executor example

### ISSUE THREAD

**Issue by 085de87a-302d-40a9-81bc-2b61a3155cf3** [python/cpython#85299]
BPO | [41127](https://bugs.python.org/issue41127)
--- | :---
Nosy | @aaraney

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-26.15:24:56.727>
labels = ['3.8', 'docs']
title = 'Executing code in thread or process pools: run_in_executor example'
updated_at = <Date 2020-06-26.15:24:56.727>
user = 'https://github.com/aaraney'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-26.15:24:56.727>
actor = 'aaraney'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-06-26.15:24:56.727>
creator = 'aaraney'
dependencies = []
files = []
hgrepos = []
issue_num = 41127
keywords = []
message_count = 1.0
messages = ['372428']
nosy_count = 2.0
nosy_names = ['docs@python', 'aaraney']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue41127'
versions = ['Python 3.8']
```

</p></details>

**Comment by slateny** [comment]
Not getting errors on my end for python 3.8 and 3.10, could you reconfirm?

**Comment by AlexWaygood** [comment]
@slateny FYI I believe, due to some oddities of the github migration, some "mannequin" users won't necessarily receive notifications on issues unless you actually @ them, even if they show up as having previously participated in the thread. (You can safely assume that non-mannequin users are still subscribed to all the issues they were "nosy" to on BPO.)

**Comment by slateny** [comment]
> Not getting errors on my end for python 3.8 and 3.10, could you reconfirm the error?

@aaraney ^ I know it's been a little while, but if you have time could you take another look?

**Comment by slateny** [comment]
Thanks for the clarification - I tried the code and it seems to run for me without error. Are you running this from another file or is this the only file?

**Comment by aaraney** [comment]
Im running it from a standalone script. So, not from the IDLE.

**Comment by slateny** [comment]
Hmm interesting, I ran it on ubuntu 20 w/ python 3.8 and 3.10 and no errors for me - maybe a version/platform thing?

**Comment by aaraney** [comment]
Yeah, that is pretty strange. I'm AFK, but from memory I reproduced it on 3.8.10 sources from miniconda on OSX. I'll see if I can reproduce it in a container tomorrow and put together a repository and share it here if I can.

**Comment by slateny** [comment]
Hmm, if it's a platform issue then do you think that the docs still need updating? If the file's the only one being run, then `if __name__ == "__main__":` seems equivalent to leaving it out

**Comment by aaraney** [comment]
Yeah I think that is a fair point, @slateny. Ive not seen it stated in python docs that examples are runnable as their own script, but I think that is kind of implicit to an _example_ snippet. I would prefer that `if __name__ == "__main__":` is included where examples are expected to be run in a standalone context.

**Comment by slateny** [comment]
The third example uses `ProcessPoolExecutor`, defined [here](https://github.com/python/cpython/blob/56e9fb3e3b1c51c9c32dda9d51f0379f711bc7d7/Lib/concurrent/futures/process.py#L583), which then seems to get the [start method](https://github.com/python/cpython/blob/56e9fb3e3b1c51c9c32dda9d51f0379f711bc7d7/Lib/concurrent/futures/process.py#L620), which as you mentioned uses `spawn` since 3.8. A bit down below, there is a [warning](https://docs.python.org/3/library/multiprocessing.html#the-spawn-and-forkserver-start-methods) about protecting the program's entry point via `if __name__ == '__main__'` if using the `spawn` method.

Taking all that into account, I think the doc change should be instead to add a note/link to the warning for macOS, advising the entrypoint guard as needed.

**Comment by gvanrossum** [comment]
The problem seems to be with how the OP is running the code, not with the example. Nevertheless it is fine to add a “_main__” check to the example, since that is customary for all main programs. No notes about platforms though.
