### ISSUE TITLE
pipes uses text files and the locale encodig

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#85322]
BPO | [41150](https://bugs.python.org/issue41150)
--- | :---
Nosy | @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-28.16:22:22.781>
labels = ['3.8', 'type-bug', 'library', '3.9', '3.10']
title = 'pipes uses text files and the locale encodig'
updated_at = <Date 2020-06-28.16:22:22.781>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-28.16:22:22.781>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-06-28.16:22:22.781>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 41150
keywords = []
message_count = 1.0
messages = ['372524']
nosy_count = 1.0
nosy_names = ['serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41150'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by vstinner** [comment]
I never used the pipes module. Is it really used in the wild? It's now planned for removal in Python 3.13: https://peps.python.org/pep-0594/

Its docstring mentions converting a GIF file to a PPM image. The GIF format is binary, so using text in the pipes modules sounds like a bug for me.

I suggest to leave the code as it is and waits until the module is simply removed in Python 3.13. IMO it's too late (since Python 3.0) to fix it.
