### ISSUE TITLE
Add support for io_uring to cpython

### ISSUE THREAD

**Issue by 2f3b0058-d572-4436-82d8-062775910f62** [python/cpython#85443]
BPO | [41271](https://bugs.python.org/issue41271)
--- | :---
Nosy | @ronaldoussoren, @giampaolo, @benjaminp, @dimaqq, @ammaraskar, @cooperlees, @corona10

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-07-18.07:55:00.370>
created_at = <Date 2020-07-10.19:54:06.976>
labels = ['type-feature', '3.10', 'expert-IO']
title = 'Add support for io_uring to cpython'
updated_at = <Date 2021-09-27.05:30:30.039>
user = 'https://github.com/cooperlees'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-27.05:30:30.039>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2020-07-18.07:55:00.370>
closer = 'ronaldoussoren'
components = ['IO']
creation = <Date 2020-07-10.19:54:06.976>
creator = 'cooperlees'
dependencies = []
files = []
hgrepos = []
issue_num = 41271
keywords = []
message_count = 8.0
messages = ['373477', '373699', '373703', '373704', '373734', '373868', '373884', '402656']
nosy_count = 7.0
nosy_names = ['ronaldoussoren', 'giampaolo.rodola', 'benjamin.peterson', 'Dima.Tisnek', 'ammar2', 'cooperlees', 'corona10']
pr_nums = []
priority = 'normal'
resolution = 'later'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41271'
versions = ['Python 3.10']
```

</p></details>

**Comment by MrHamel** [comment]
Has progress been made on PyPI or CPython? Been quite a few years since this was closed.

**Comment by arhadthedev** [comment]
> I'm closing this as "later" as the consensus is that this might be a useful binding to have, but io_uring is evolving too fast at the moment.

Three years passed so we can return to this issue after Python 3.12 is released.

**Comment by stalkerg** [comment]
We have all these selectors https://docs.python.org/3/library/selectors.html#selectors.SelectSelector one more, the most efficient for Linux sounds reasonable. And it's not canceled any POC outside of std.

**Comment by GalaxySnail** [comment]
Yes, io_uring is mature enough, but it's still rapidly evolving.

For example, [Linux 6.0](https://kernelnewbies.org/Linux_6.0#Core_.28various.29) got multishot recv and zerocopy send, [Linux 6.1](https://kernelnewbies.org/Linux_6.1#Core_.28various.29) got `IORING_SETUP_DEFER_TASKRUN`, [Linux 6.2](https://kernelnewbies.org/Linux_6.2#Core_.28various.29) got `IORING_SEND_ZC_REPORT_USAGE`, Linux 6.3 got [`IORING_REGISTER_USE_REGISTERED_RING`](https://github.com/axboe/liburing/blob/54efde088cdef59269cf48319cb148dcbf0eb98c/man/io_uring_setup.2#L470-L476) and [`IORING_MSG_RING_FLAGS_PASS`](https://github.com/torvalds/linux/commit/cbeb47a7b5f003429ded32b1fb3a7108ce5c1b54). In the future, [read/write on pipes will no longer require the io-wq thread pool](https://nitter.net/axboe/status/1633305284763607042) (before this patch set, we should poll and read on non-blocking pipes instead of read on blocking pipes).

io_uring is a more complex API than poll or epoll, it's challenging to design a pythonic API for io_uring. Maintaining an optimal and pythonic API design for io_uring may require modifying it to keep up with changes in Linux versions. Therefore, I think it's better to leave io_uring to PyPI rather than include it in the stdlib.

**Comment by GalaxySnail** [comment]
> We have all these selectors https://docs.python.org/3/library/selectors.html#selectors.SelectSelector one more, the most efficient for Linux sounds reasonable. And it's not canceled any POC outside of std.

However selectors are not very useful. For example, trio doesn't use selectors for some reasons: https://trio.readthedocs.io/en/latest/design.html#inside-trio-core. Even worse, io_uring is not a selector style API, it's a proactor stype API, so it's not fit for selectors.

**Comment by kumaraditya303** [comment]
-1 on adding another backend for `asyncio` in stdlib, we don't have enough resources. It is best left to be implemented as a third-party package.

**Comment by arhadthedev** [comment]
Closing the issue back since nobody is ready to support it as a battery shipped with Python.
