### ISSUE TITLE
Provide a limit arguments for __repr__

### ISSUE THREAD

**Issue by 14c6ad77-d8f0-40dc-ae4e-d0224b76f054** [python/cpython#85555]
BPO | [41383](https://bugs.python.org/issue41383)
--- | :---
Nosy | @rhettinger, @ericvsmith, @remilapeyre

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-07-24.14:04:53.420>
labels = ['interpreter-core', '3.10']
title = 'Provide a limit arguments for __repr__'
updated_at = <Date 2020-07-26.17:51:07.402>
user = 'https://bugs.python.org/BernatGabor'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-26.17:51:07.402>
actor = 'rhettinger'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-07-24.14:04:53.420>
creator = 'Bernat Gabor'
dependencies = []
files = []
hgrepos = []
issue_num = 41383
keywords = []
message_count = 4.0
messages = ['374179', '374182', '374191', '374335']
nosy_count = 4.0
nosy_names = ['rhettinger', 'eric.smith', 'remi.lapeyre', 'Bernat Gabor']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue41383'
versions = ['Python 3.10']
```

</p></details>

**Comment by gvanrossum** [comment]
@gaborbernat:

I don't know if this was ever taken to python-ideas, so I'll continue here.

I don't think there is any chance we can override the `__repr__` API to add an optional parameter indicating some limit. For the parameter to be usable it needs to be supported by every `__repr__` implementation, since the debugger presumably has to call `repr(x, limit=N)` which must call `x.__repr__(limit=N)`, and if `x.__repr__` doesn't support the `limit` parameter this will raise `TypeError`. Using introspection to determine whether a particular class' `__repr__` implementation has a `limit` parameter is cumbersome and unreliable, and there's no way to do this for types implemented in C.

Consequently the only way to do this would be to define a *new* API (strawman: `__repr_with_limit__`) that types can optionally implement. This is a really high bar (there are lots of other things we would want if we could add a new repr-like dunder) and would require a really well-written PEP supported by high-ranking core devs.

Alternatively, you could lobby for specific improvements to pprint or reprlib (both of which seem to be halfway there). In particular it would seem that if we make one or the other extensible so that user code can register additional handlers for its own types. This is somewhat similar to defining a new dunder but as a feature request for either pprint or reprlib it is much easier to get this idea approved. I don't know exactly what your use case is, so please look at these two modules carefully and come back with a specific proposal.

**Comment by gaborbernat** [comment]
I think @elizaveta239 would be able to describe better what she had in mind 👍

**Comment by Elizaveta239** [comment]
Hi @gvanrossum! Thank you for your explanation and for the suggestions! Looks like `reprlib` does exactly what we need inside our debugger! I don't know how I missed it, but we really can use it without adding any new API into Python. Thank you very much!
