### ISSUE TITLE
Please use active voice in async docs.

### ISSUE THREAD

**Issue by 232d7ad7-7660-4d4e-a54f-74929b9d96b9** [python/cpython#85747]
BPO | [41575](https://bugs.python.org/issue41575)
--- | :---
Nosy | @gvanrossum, @terryjreedy

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-08-18.09:35:22.015>
labels = ['type-feature', '3.8', '3.9', '3.10', 'docs']
title = 'Please use active voice in async docs.'
updated_at = <Date 2020-08-21.22:26:07.627>
user = 'https://bugs.python.org/denilsonsa'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-21.22:26:07.627>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-08-18.09:35:22.015>
creator = 'denilsonsa'
dependencies = []
files = []
hgrepos = []
issue_num = 41575
keywords = []
message_count = 2.0
messages = ['375603', '375771']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'terry.reedy', 'denilsonsa', 'docs@python', 'Yury.Selivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41575'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-99784
* gh-99980
* gh-99981
* gh-100270
* gh-102005
* gh-102006

**Comment by kumaraditya303** [comment]
cc @python/proofreaders

**Comment by pradyunsg** [comment]
This is a reasonable suggestion, and a change worth making.

Looking at the asyncio docs, the spots where we're using passive voice are all actually a decent candidate for explicit structured API documentation using Sphinx's `:param:` and `:returns:` to describe the arguments and return value.

**Comment by bskinn** [comment]
> decent candidate for explicit structured API documentation using Sphinx's `:param:` and `:returns:` to describe the arguments and return value.

I scanned through a handful of pages of the docs, both asyncio and not, and It looks like `:param:` & co. are only lightly used, if at all. 

Is there a general campaign to try to migrate the docs to use these features, @pradyunsg? If not, would it be better to keep to the approach most commonly used elsewhere? It doesn't look like it would give advantages such as, e.g., adding fragment `id`s or cross-reference targets.

**Comment by CAM-Gerlach** [comment]
I definitely agree with the premise here—reference documentation such as this should be concise, consistent, clear and easily skimmable.

Beyond just changing these various instances to use direct language and active voice, these functions generally seem like great candidates for adopting a more explicit, structured and consistent form of presenting their information, namely using the appropriate Sphinx constructs, as discussed [on Discourse](https://discuss.python.org/t/explicit-parameter-list-in-function-documentation/16090/) and implemented so far in several other stdlib modules' docs, such as `sqlite3` and `logging`.

However, I suggest we just go ahead and make the initial minimal changes suggested above first before proceeding with those larger ones, to avoid holding this up and going out of scope, and splitting those into atomic units of one per function/method (or at least one per group of adjacent functions/methods), following discussion.

> Is there a general campaign to try to migrate the docs to use these features, @pradyunsg? If not, would it be better to keep to the approach most commonly used elsewhere? It doesn't look like it would give advantages such as, e.g., adding fragment ids or cross-reference targets.

There is the beginnings of one, [as discussed on Discourse](https://discuss.python.org/t/explicit-parameter-list-in-function-documentation/16090/), though it is still early stages and proceeding one module at a time, rather than being a large, formal project at this point, and is also been coupled with other Diataxis-inspired improvements.

**Comment by bskinn** [comment]
> However, I suggest we just go ahead and make the initial minimal changes suggested above first before proceeding with those larger ones

Do we know, is it only the [one specific page](https://docs.python.org/3/library/asyncio-eventloop.html) that needs these edits, or should the entirety of the asyncio docs (or the entire docs suite, even) be checked and corrected?

**Comment by gvanrossum** [comment]
Please don't submit a bulk PR. It is likely going to overwhelm reviewers, and unless you are also a subject matter expert, your best intentions will still occasionally change the meaning of certain sentences and make the docs less accurate. I'm speaking from experience here.

Instead, submit small PRs, one at a time, that carefully rewrite one particular section (or several related sections) for legibility.

**Comment by bskinn** [comment]
Oh, absolutely, @gvanrossum! At most one source file per PR; less than one file per PR in the case of a sufficient number of edits to a single file.

**Comment by terryjreedy** [comment]
I am a fan of active voice and will review docstring patches to employ such.

 I don't like the hugh, ugly, mostly empty purple blobs resulting from the new sphinx markup, such as for [sqlite.connect](https://docs.python.org/3/library/sqlite3.html#sqlite3.connect).  I think `Parameters:` should be on a line by itself with the entries below with a *small* indent.  If color is wanted, color the parameter names.  I do like the list for more than 2 or 3 parameters.  No purple blob.  The Returns line seems uselessly redundant, as the return type should be part of the summary sentence.  In this instance, I think `Return an open Connection to an SQLite database.` would be even better than the current summary, which allows for a None return.  (Should I make this comment elsewhere?  Where?)

**Comment by mwichmann** [comment]
I'm sure it should be elsewhere :)   Agree with you on the purple blob. This is a theme question; I actually switched a project I work on to `sphinx_book_theme` for this very reason - it puts the header like `Parameters` on its own line, and then renders the list with a small indent. I'm not proposing CPython switch to that theme as there's tons of history for the current one, just illustrating that it is a theming question we could argue about... somewhere.

**Comment by encukou** [comment]
> somewhere

in https://github.com/python/python-docs-theme/issues

Or look at Lutra: https://pradyunsg-cpython-lutra-testing.readthedocs.io/en/latest/library/sqlite3.html#sqlite3.connect (and discuss in https://github.com/pradyunsg/lutra/discussions/31) – Pradyun intends to propose switching to that theme when it's polished.

**Comment by CAM-Gerlach** [comment]
> Oh, absolutely, @gvanrossum! At most one source file per PR; less than one file per PR in the case of a sufficient number of edits to a single file.

+:100: 

> I don't like the hugh, ugly, mostly empty purple blobs resulting from the new sphinx markup, such as for [sqlite.connect](https://docs.python.org/3/library/sqlite3.html#sqlite3.connect).

I'm not a huge fan of it either; I'd also prefer a style like you suggest and `sphinx_book_theme` uses (which is also similar to what we use in Spyder's and Jupyter's help panes that render docstrings, and general Numpydoc convention). However, adopting a structured syntax in the source allows us to easily change it one place in the theme, rather than having to change it everywhere in the source. Just to be clear, though, that's a separate issue from the initial implementation of this one.

> The Returns line seems uselessly redundant, as the return type should be part of the summary sentence.

Sometimes it is mentioned, but given the summary line's primary goal is the very concisely describe the purpose of the function, its not always practical or prudent to use it to explicitly state the exact return type(s), much less do so precisely and with a cross-reference to the type(s) involved, without gumming up what is a supposed to be a "summary" with specific details. An explicit, structured field for the return type makes it easy for authors to specify it as precisely as desired and without having to manually cross-reference the types, and makes it harder to forget to explicitly mention it, while making it easy for readers to quickly find and unambiguously interpret. This also follows what all the major docstring standards (Sphinxdoc, Numpydoc and Googledoc), and other documentation systems (Doxygen, Javadoc, etc) do. And since its structured data, it allows us to present the return type however we prefer.

**Comment by kumaraditya303** [comment]
All referenced PRs were merged, is there still work to be done or is this completed ?

**Comment by bskinn** [comment]
@kumaraditya303 There is a great deal more work to be done to complete this. The rest of `asyncio-eventloop.rst`, beyond the two linked PRs, and then perhaps the remainder of the asyncio docs pages. I've unfortunately had other things intrude on my ability to initiate more of these PRs.

It's a *significant* undertaking. If it's of continued interest, it might be better to migrate the tracking from this single issue into a GitHub Project or something.

**Comment by gvanrossum** [comment]
I don't feel that such work is of sufficient importance to keep an issue open. Thank you for your work!
