### ISSUE TITLE
Make _SubParsersAction public

### ISSUE THREAD

**Issue by 9d4f24ea-177a-48c4-a17d-fae856bb44b9** [python/cpython#85758]
BPO | [41592](https://bugs.python.org/issue41592)
--- | :---
Nosy | @rhettinger, @sourcedelica, @Fidget-Spinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-10-22.12:28:22.102>
created_at = <Date 2020-08-19.19:21:34.462>
labels = ['type-feature', '3.8', '3.9', 'invalid', '3.7', 'library']
title = 'Make _SubParsersAction public'
updated_at = <Date 2021-10-25.23:51:03.692>
user = 'https://github.com/sourcedelica'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-25.23:51:03.692>
actor = 'paul.j3'
assignee = 'none'
closed = True
closed_date = <Date 2021-10-22.12:28:22.102>
closer = 'kj'
components = ['Library (Lib)']
creation = <Date 2020-08-19.19:21:34.462>
creator = 'sourcedelica'
dependencies = []
files = []
hgrepos = []
issue_num = 41592
keywords = []
message_count = 8.0
messages = ['375670', '404724', '404759', '404769', '404774', '404979', '404982', '405009']
nosy_count = 4.0
nosy_names = ['rhettinger', 'paul.j3', 'sourcedelica', 'kj']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41592'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by ms-lolo** [comment]
I'd love to resurface this issue or, at least, voice my disappointment with the resolution. The `_SubParsersAction` simply has to be a public class if we are expected to handle instances of it and be able to pass them around. The documentation is meant to document the public API but the code is still in charge of what that public API is, and the fact that there is a class with an `add_parser()` method that we should call means it's public.

If the developers don't want us to initialize it, then an abstract class or protocol should be defined and made public so we can import it and use it as a type hint without having access to the concrete class for us to instantiate.

This is not in any way related to pycharm.

Additionally, the `__all__` variable in `arparse.py` doesn't even expose `_SubParsersAction` so there are now two things indivating to use that we should never import this class. The fact that it's not exposed by `__all__`, and the fact that the class name starts with an underscore. The fact that the documentation is promising to keep things stable does not negate the fact that the code is warning us, in two different ways, that what we are doing is very much **not** stable. It's not acceptable to think that when we run into private values in the code, we should go make sure things are actually private in the documentation.

Here's an example of what could be exposed by the library (ignoring any versioning differences):
```python
class SubParser(Protocol):
    @abstractmethod
    def add_parser(self, name, **kwargs):
        pass
```

@paulj3, @Fidget-Spinner: I would really like you to revisit this issue since it causes a large amount of confusion on large projects and teams where this constantly pops up as unstable tech debt because we import private classes and have to explain to folks that the library maintainers are telling us to just not worry about this one case.

**Comment by Fidget-Spinner** [comment]
@ms-lolo reading again, I see what you mean. Thank you for explaining further. I will reopen the issue. This is the most I can do, as I do not maintain the argparse module and I am not comfortable changing anything in there.

I don't know if argparse even has a maintainer, considering it has no maintainers listed in the experts index https://devguide.python.org/core-developers/experts/index.html.

**Comment by Fidget-Spinner** [comment]
Sorry if this isn't the answer you want, and about me closing this issue too hastily in the first place.

**Comment by ms-lolo** [comment]
oh no, this was a great answer thank you @Fidget-Spinner! do you have any idea how we might be able to find someone that could help work on this? otherwise just having this issue open will already provide some benefits for us in internal conversations.

**Comment by gvanrossum** [comment]
@ms-lolo If you are at MS can you contact me on Teams chat? That might be quicker than going back and forth on the issue.

**Comment by ms-lolo** [comment]
@Fidget-Spinner, had a chat with @gvanrossum and it sounds like we have a philosophical disagreement. This is unlikely to be changed so I think you can go ahead and close the issue after all.

For folks running into this issue, creating a protocol for the class and using that in your type hints will at least prevent you from needing to import and ignore warnings for protected classes. The one I've created on my side looks like the one I showed in the comments above. Linters will properly allow you to pass in an instance of `argparse._SubParsersAction` as long as your protocol matches the signature of `argparse._SubParsersAction`. I'm a PyCharm user and can confirm this works fine.
