### ISSUE TITLE
port shebang of tools from python2 to python3

### ISSUE THREAD

**Issue by shihai1991** [python/cpython#85792]
BPO | [41626](https://bugs.python.org/issue41626)
--- | :---
Nosy | @terryjreedy, @tiran, @ned-deily, @merwok, @encukou, @corona10, @shihai1991
PRs | <li>python/cpython#21948</li><li>python/cpython#23581</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-08-24.16:28:45.369>
labels = ['library', '3.10']
title = 'port shebang of tools from python2 to python3'
updated_at = <Date 2020-12-01.11:51:42.061>
user = 'https://github.com/shihai1991'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-01.11:51:42.061>
actor = 'christian.heimes'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Demos and Tools', 'Library (Lib)']
creation = <Date 2020-08-24.16:28:45.369>
creator = 'shihai1991'
dependencies = []
files = []
hgrepos = []
issue_num = 41626
keywords = ['patch']
message_count = 8.0
messages = ['375855', '379244', '379247', '379279', '379969', '379970', '382238', '382241']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'christian.heimes', 'ned.deily', 'eric.araujo', 'petr.viktorin', 'corona10', 'shihai1991']
pr_nums = ['21948', '23581']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue41626'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-108273
* gh-130863

**Comment by terryjreedy** [comment]
As near as I can tell, encodings.rot_13 is currently the only* /Lib module with a shebang line with 'python' rather than 'python3'.  #108273 proposes to modify this one file.  Does this seem appropriate?

* idlelib/idletest/example_noext has the same line (with a harmless bug), but it is a dummy file for testing whether IDLE recognizes an extensionless file with a python shebang line as python source.  I intend to change it for consistency, but as part of a PR making other changes and changing other files and backporting them.

As noted above, idlelib.pyshell has a 'python3' shebang line.  It has not been the official initial startup file for at least a decade.  idlelib.idle does not have such a line, so it seems to be unneeded. I will think about removing that line (and exec bit?) in 3.13.

There seems to be as many /Lib files with "if __name__ == '__main__':" without a shebang line as with.

**Comment by terryjreedy** [comment]
As near as I can tell, encodings.rot_13 is currently the only* /Lib module with a shebang line with 'python' rather than 'python3'.  #108273 proposes to modify this one file.  Does this seem appropriate?

* idlelib/idletest/example_noext has the same line (with a harmless bug), but it is a dummy file for testing whether IDLE recognizes an extensionless file with a python shebang line as python source.  I intend to change it for consistency, but as part of a PR making other changes and changing other files and backporting them.

As noted above, idlelib.pyshell has a 'python3' shebang line.  It has not been the official initial startup file for at least a decade.  idlelib.idle does not have such a line, so it seems to be unneeded. I will think about removing that line (and exec bit?) in 3.13.

There seems to be as many /Lib files with "if __name__ == '__main__':" without a shebang line as with.

**Comment by encukou** [comment]
I think that today, it's best to close this issue without action. python2/python3 confusion should be history now.
I'll close next month if there are no objections.

**Comment by merwok** [comment]
This wasn’t only about 2 vs 3 ‑ there were also notes about stdlib modules having executable bit and shebang needlessly

**Comment by encukou** [comment]
OK, I'll only close the PR for internal tools.

**Comment by sandy-lcq** [comment]
There are still several files using shebang "/usr/bin/env python",  add a pull request to fix them.
