### ISSUE TITLE
Windows install failure "could not set file security"

### ISSUE THREAD

**Issue by zooba** [python/cpython#86127]
BPO | [41961](https://bugs.python.org/issue41961)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-10-06.23:32:04.204>
labels = ['type-bug', '3.9', 'OS-windows']
title = 'Windows install failure "could not set file security"'
updated_at = <Date 2020-10-07.16:23:43.435>
user = 'https://github.com/zooba'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-07.16:23:43.435>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2020-10-06.23:32:04.204>
creator = 'steve.dower'
dependencies = []
files = []
hgrepos = []
issue_num = 41961
keywords = []
message_count = 5.0
messages = ['378141', '378142', '378145', '378163', '378169']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41961'
versions = ['Python 3.9']
```

</p></details>

**Comment by rizopus** [comment]
Just a notice to those who are stuck with the same error. This is not a python's installer bug at least under the following conditions.

The bug happens if you want to install Python for the current user who has no admin rights (not in Administrators group), and the folder %appdata%\Microsoft\Installer has a junction in any of its components. This applies to more or less recent versions of Windows.

A Windows Installer impersonates itself as the current user and elevates back to NT AUTHORITY\SYSTEM when it needs to do priviledged operations. When it creates (or checks existance of) a directory %appdata%\Microsoft\Installer, it also tries to set an owner, groups and DACL of the directory*. This is a priviledged operation, e.g. a non-admin user has no SE_TAKE_OWNERSHIP_NAME priv by default. So, Windows Installer needs to elevate. It does, but if any component of the path %appdata%\Microsoft\Installer has a junction, Installer explicitly disables elevation when calling SetFileSecurityW on that folder.

I don't know why this is done, maybe for security reasons.

\* sddl for the security descriptor is
O:BAG:SYD:PAI(A;OICI;0x1200a9;;;WD)(A;OICI;FA;;;SY)(A;OICI;FA;;;BA)
and can be viewed with powershell command ConvertFrom-SddlString -Sddl

**Comment by zooba** [comment]
Thanks for the additional info. This could well be a Windows bug, but it's not ours, so I'm closing the issue.
