### ISSUE TITLE
[argparse] Bad error message formatting when using custom usage text

### ISSUE THREAD

**Issue by c5a210b0-9bc4-41d4-88b1-57b4b853ea6e** [python/cpython#86463]
BPO | [42297](https://bugs.python.org/issue42297)
--- | :---
Nosy | @rhettinger, @TurboTurtle, @bobblanchett

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-11-09.17:25:59.052>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = '[argparse] Bad error message formatting when using custom usage text'
updated_at = <Date 2021-08-07.02:02:50.295>
user = 'https://github.com/TurboTurtle'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-07.02:02:50.295>
actor = 'bobblanchett'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-11-09.17:25:59.052>
creator = 'TurboTurtle'
dependencies = []
files = []
hgrepos = []
issue_num = 42297
keywords = []
message_count = 7.0
messages = ['380598', '380611', '380612', '380615', '380616', '380619', '380701']
nosy_count = 4.0
nosy_names = ['rhettinger', 'paul.j3', 'TurboTurtle', 'bobblanchett']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42297'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-124532
* gh-125891
* gh-127162

**Comment by serhiy-storchaka** [comment]
```py
        # prog defaults to the usage message of this parser, skipping
        # optional arguments and with no "usage:" prefix
        if kwargs.get('prog') is None:
            formatter = self._get_formatter()
            positionals = self._get_positional_actions()
            groups = self._mutually_exclusive_groups
            formatter.add_usage(self.usage, positionals, groups, '')
            kwargs['prog'] = formatter.format_help().strip()
```
This code only makes sense if the custom usage is None. Then automatically generated message includes prog and names of positional arguments preceding subparsers. `add_parser()` creates prog for the subparser by concatenating that value with the name of the subparser. This is exactly the command used to invoke the subparser (ignoring options).

The custom usage replaces the full usage line. If it is close to the generated usage, it includes options, a set of all subparser names, "..." for subparser arguments. E.g. `PROG [-h] [-v] {a,b,c,d,e} ...`. If we add the name of the concrete parser we will get something very from the command used to invoke the subparser.

I think that using full custom usage instead of specially formatted partial usage string is wrong. What should we use instead? I think that falling back to the generated usage would be wrong too -- there is a reason why the custom usage was specified at first place. Then we can just set _prog_prefix to None and use subparser's name as its prog. It will produce less ugly result.

**Comment by serhiy-storchaka** [comment]
#124532 make `'...'` be used as the default prog prefix if custom usage is used.

**Comment by serhiy-storchaka** [comment]
On other hand, using the generated prog prefix as if the custom usage was not specified looks not bad.

#125891 ignores custom usage when generating the default prog prefix.
