### ISSUE TITLE
Python uses ANSI CP for stdio on Windows console instead of using console or OEM CP

### ISSUE THREAD

**Issue by e55b0afb-c7b3-48b9-aac4-6a95a233fee4** [python/cpython#86873]
BPO | [42707](https://bugs.python.org/issue42707)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @methane, @zware, @eryksun, @zooba, @izbyshev

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-12-21.18:59:31.789>
labels = ['3.10', 'type-bug', '3.8', '3.9', 'OS-windows']
title = 'Python uses ANSI CP for stdio on Windows console instead of using console or OEM CP'
updated_at = <Date 2020-12-23.02:50:45.222>
user = 'https://bugs.python.org/u36959'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-23.02:50:45.222>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2020-12-21.18:59:31.789>
creator = 'u36959'
dependencies = []
files = []
hgrepos = []
issue_num = 42707
keywords = []
message_count = 7.0
messages = ['383550', '383566', '383588', '383623', '383625', '383626', '383630']
nosy_count = 9.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'methane', 'zach.ware', 'eryksun', 'steve.dower', 'izbyshev', 'u36959']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42707'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by snnn** [comment]
(Disclaimer: I'm a Microsoft employee, but I don't know Windows more than you and below is my personal opinion)

First, ideally we should forget the concept of "code page".  This is because some languages only exist in Unicode. 

Second, though in C++ we have [wide streams(std::wcout/std::wcerr/...) and multibyte streams(std::cout/std::cerr)](https://learn.microsoft.com/en-us/cpp/standard-library/iostream?view=msvc-170), you may think the wide streams are just a thin-wrapper around the multibyte streams.  The wide streams do not have the capability to directly talk to Windows APIs through wide char interfaces.  This is because std::cout and std::wcout share the same underlying C FILE stream: stdout. The stream has a "translation mode" attribute which could be:
- (default) _O_TEXT. Also known  as: ansi mode
- _O_WTEXT. 
- _O_U16TEXT. It means _O_WTEXT without BOM.
- _O_U8TEXT
- _O_BINARY
- _O_RAW

For compatibility reasons, by default stdout operates in ANSI mode. You may use `_setmode` function to change it to one of the  Unicode modes, but the old ANSI APIs (like printf) will stop working. 

Another challenge comes from `user code page` vs `system code page`.  There is a system-wide code page setting that only the system's Administrators can change.  Traditionally, Windows has different installation ISO images for different user languages. English users buy and use English Windows,  Chinese users buy and use Chinese Windows. But if you have a smart phone, you will find you can the change phone's UI to a different language without the need to reinstall the OS. Now Windows can support it too. And on the same machine different users can use different languages. Conceptually, we say each user also has a `user code page` .  However, the code page might be incompatible with the system-wide code page. For example, if the user language is Chinese but the system language is English, you cannot encode Chinese characters in an English code page(e.g. cp437).

GetConsoleCP()  always returns the system-wide code page. If it is an English codepage(e.g. cp437), any code that depends on this value would not be able to print out any Chinese. This is why all the standard C/C++ IO APIs would not work as expected. Fundamentally, we should avoid thinking about code pages. 

There is one way to make it work: use `WriteConsole` API instead. The API bypasses the codepaths that need to do encoding conversions. You get what you give. But the API has a drawback that it doesn't support IO redirection. 

When you redirect stdout to a file, what encoding the file should use? If you did not use `_setmode`  to set the stdout stream to a unicode mode, the output file would not have a BOM header. Therefore you cannot use UTF-16(otherwise most text editors would not understand it).  Then we need to go back to the discussion of code pages ...

**Comment by methane** [comment]
@snnn Thank you for your comment.



> There is one way to make it work: use `WriteConsole` API instead. The API bypasses the codepaths that need to do encoding conversions. You get what you give. But the API has a drawback that it doesn't support IO redirection.

Python uses WriteConsole since Python 3.7 (see [PEP 528](https://peps.python.org/pep-0528/)).
So this issue is all about redirected stdio.

We already have PYTHONIOENCODING option, and we will enable PYTHONUTF8 by default at Python 3.15.
I think another backward incompatible change will confuse users. Python and Windows will go to UTF-8, not legacy encoding.

So, I close this issue for now.
