### ISSUE TITLE
python3 -m doctest test.py tests the stdlib "time" module instead

### ISSUE THREAD

**Issue by dadeec36-2bda-4160-b6c3-d0f50211f15e** [python/cpython#87072]
BPO | [42906](https://bugs.python.org/issue42906)
--- | :---
Nosy | @gvanrossum

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-01-12.18:22:19.279>
created_at = <Date 2021-01-12.10:39:42.960>
labels = ['type-bug', '3.8', '3.9', 'invalid', '3.7', 'library']
title = 'python3 -m doctest test.py tests the stdlib "time" module instead'
updated_at = <Date 2021-01-12.18:22:32.627>
user = 'https://bugs.python.org/stijnvandrongelen'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-12.18:22:32.627>
actor = 'gvanrossum'
assignee = 'none'
closed = True
closed_date = <Date 2021-01-12.18:22:19.279>
closer = 'gvanrossum'
components = ['Library (Lib)']
creation = <Date 2021-01-12.10:39:42.960>
creator = 'stijnvandrongelen'
dependencies = []
files = []
hgrepos = []
issue_num = 42906
keywords = []
message_count = 4.0
messages = ['384913', '384914', '384973', '384974']
nosy_count = 2.0
nosy_names = ['gvanrossum', 'stijnvandrongelen']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42906'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by kasparthommen** [comment]
> Sorry, this is not a bug. The builtin time module takes precedence in this case because the current directory is not put at the front of the module search path (sys.path).
> 
> As a workaround you could export PYTHONPATH=.

I think it is a bug after all, because the module is in fact being put at the front of the search path, see [here](https://github.com/python/cpython/blob/3.10/Lib/doctest.py#L2796-L2799).

**Comment by gvanrossum** [comment]
The reason is `sys.meta_path`. The `time` module is built-in (statically linked, see `sys.builtin_module_names`) and hence always imported before `sys.path` is consulted.

**Comment by kasparthommen** [comment]
Thanks @gvanrossum . Is this even fixable without major gymnastics?

**Comment by gvanrossum** [comment]
Since it's not considered a bug there's nothing to fix. If you want a different behavior please open a new ticket and describe the behavior you'd like. But if you want `import time` to load the `time.py` file in the current directory (or anywhere else on `sys.path`) you might as well not bother, because that's never going to happen: when overriding a fundamental built-in module like that, you're at risk of breaking all kinds of other stdlib behavior that you didn't expect to break and would have a hard time debugging. By comparison, not having your code loaded because your filename conflicts with a built-in module is a minor nuisance and something people learn to avoid after the first time they try.
