### ISSUE TITLE
Remove pathlib accessors

### ISSUE THREAD

**Issue by 4b0c5ead-8181-475a-af87-9342ce46c4e3** [python/cpython#87178]
BPO | [43012](https://bugs.python.org/issue43012)
--- | :---
Nosy | @pitrou, @ericvsmith, @merwok, @encukou, @eryksun, @miss-islington, @barneygale
PRs | <li>python/cpython#25701</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-02-02.15:37:05.067>
created_at = <Date 2021-01-23.18:15:55.455>
labels = ['3.11', 'library', 'performance']
title = 'Remove pathlib accessors'
updated_at = <Date 2022-02-02.15:37:05.063>
user = 'https://github.com/barneygale'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-02.15:37:05.063>
actor = 'eric.araujo'
assignee = 'none'
closed = True
closed_date = <Date 2022-02-02.15:37:05.067>
closer = 'eric.araujo'
components = ['Library (Lib)']
creation = <Date 2021-01-23.18:15:55.455>
creator = 'barneygale'
dependencies = []
files = []
hgrepos = []
issue_num = 43012
keywords = ['patch']
message_count = 4.0
messages = ['385556', '410732', '410733', '412353']
nosy_count = 7.0
nosy_names = ['pitrou', 'eric.smith', 'eric.araujo', 'petr.viktorin', 'eryksun', 'miss-islington', 'barneygale']
pr_nums = ['25701']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue43012'
versions = ['Python 3.11']
```

</p></details>

**Comment by ronf** [comment]
This change is actually causing a problem for me. I have a unit test case which mocks out os.path.expanduser() but not the pathlib version. This works in 3.10 and earlier due to the indirection of the accessors, but in 3.11 the code ends up failing, since now the pathlib version of expanduser() is also getting into my mock.

I wonder if there might be other code out there which also might be depending on this behavior, without even realizing it.
