### ISSUE TITLE
Speed up math.isqrt, again

### ISSUE THREAD

**Issue by d53266d1-005f-41a4-9f68-6ba663f9bdf2** [python/cpython#87219]
BPO | [43053](https://bugs.python.org/issue43053)
--- | :---
Nosy | @tim-one, @rhettinger, @mdickinson, @serhiy-storchaka
PRs | <li>python/cpython#24414</li>
Files | <li>[isqrt_2.py](https://bugs.python.org/file49770/isqrt_2.py "Uploaded as text/plain at 2021-01-28.08:03:26 by juraj.sukop")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/mdickinson'
closed_at = <Date 2021-02-02.13:38:53.784>
created_at = <Date 2021-01-28.08:03:26.755>
labels = ['extension-modules', '3.8', 'performance']
title = 'Speed up math.isqrt, again'
updated_at = <Date 2021-02-02.13:38:53.783>
user = 'https://bugs.python.org/jurajsukop'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-02.13:38:53.783>
actor = 'mark.dickinson'
assignee = 'mark.dickinson'
closed = True
closed_date = <Date 2021-02-02.13:38:53.784>
closer = 'mark.dickinson'
components = ['Extension Modules']
creation = <Date 2021-01-28.08:03:26.755>
creator = 'juraj.sukop'
dependencies = []
files = ['49770']
hgrepos = []
issue_num = 43053
keywords = ['patch']
message_count = 11.0
messages = ['385848', '385849', '385856', '385861', '385862', '385863', '385872', '385873', '385985', '386089', '386092']
nosy_count = 6.0
nosy_names = ['tim.peters', 'rhettinger', 'mark.dickinson', 'stutzbach', 'serhiy.storchaka', 'juraj.sukop']
pr_nums = ['24414']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue43053'
versions = ['Python 3.8']
```

</p></details>

**Comment by mdickinson** [comment]
> The branch is here: https://github.com/mdickinson/cpython/tree/isqrt-performance

Here's a better, non-broken link: https://github.com/python/cpython/pull/24414

**Comment by mdickinson** [comment]
It's worth noting that the trade-off is no longer so clear now that CPython has subquadratic division: for an integer `n` of bit length `b`, in the final iteration:

- the current algorithm does a `3b/4`-bit-by-`b/4`-bit division (and does nothing else that contributes to the overall complexity)
- the proposed algorithm improves that to a `b/2`-bit-by-`b/4`-bit division, at the expense of an extra `b/4`-bit-by-`b/4`-bit multiplication.

Prior to CPython 3.12, division was still quadratic time while multiplication was subquadratic, so the division dominated and we could expect a factor of two speedup, asymptotically. For CPython >= 3.12, we'd still expect a constant factor speedup, but that constant factor will be smaller than 2 since the multiplication _will_ now contribute to the asymptotic complexity.

I haven't run actual timings; I'll try to find time to do that at some point.

**Comment by tim-one** [comment]
This was exactly my position too:

> But here's the thing: I don't actually care about the performance for *huge* n - people who care about that sort of thing would be better off using gmpy2. I'm much more interested in the performance implications for *smaller* n: that is, integers of length 64-256 bits, say.

I already use `gmpy2` when slinging giant ints. Native CPython remains faster for "small" ints, though (and very much so under PyPy). So anything that slows operations on small ints is probably a "pessimization" to me :wink:.
