### ISSUE TITLE
Unable to install Python 3.9.1 - Windows 10

### ISSUE THREAD

**Issue by 16c35524-b371-47c3-9b38-20d4a21cf8fd** [python/cpython#87293]
BPO | [43127](https://bugs.python.org/issue43127)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-04.16:53:25.038>
labels = ['expert-installation', '3.9', 'OS-windows']
title = 'Unable to install Python 3.9.1 - Windows 10'
updated_at = <Date 2021-02-09.18:11:52.432>
user = 'https://bugs.python.org/adrianedlloyd'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-09.18:11:52.432>
actor = 'steve.dower'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation', 'Windows']
creation = <Date 2021-02-04.16:53:25.038>
creator = 'adrian.e.d.lloyd'
dependencies = []
files = []
hgrepos = []
issue_num = 43127
keywords = []
message_count = 3.0
messages = ['386485', '386733', '386734']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'adrian.e.d.lloyd']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue43127'
versions = ['Python 3.9']
```

</p></details>

**Comment by zware** [comment]
Nothing for us to do here; closing.

**Comment by spbai** [comment]
I have the same issue when trying to install Python 3.10.4
I tried to install other versions 3.9.12 and the issue persists
Still struggling ... Picture is very dark ... don't see the sunlight yet.
So it probably (just a guess) has to do with windows update failure

p.s.
installation from MS store is different than the installation of Python using an installation file downloaded from python.org
MS manages the whole process. There is no downloaded file that one can run in order to install.

**Comment by edward-ellis** [comment]
It would be really helpful if you could say something more specific than just "system policy".  I have searched the entire codebase on the master and 3.10 branches and it nowhere contains the phrase "system policy" in plain text.  Could someone point out where this error is produced so that I can research the cause?

**Comment by zooba** [comment]
I would love to be able to say more than system policy, but there are many ways for system admins to configure Windows to reject certain installers. It's not anything in Python - it's in the operating system.

**Comment by ZfiXxtyN** [comment]
Go to Control Panel - Administrative Tools - Local Security Policy.
Select Software Restriction Policies.
If the policy is not important, right-click on the "Software Restriction Policy" and select "Create a Software Restriction Search".
Double-click on "Apply" and in the "When limited use of programs is detected" section, select "all users except administrators." Program execution policy

**Comment by jszabo98** [comment]
DisableMSI refers to the group policy "Turn off Windows Installer".  On windows server it defaults to 1, or "non-managed applications only".  I guess the python installer isn't .net.  It works for me in windows 10 anyway, as a regular user, but not in windows virtual desktop.
