### ISSUE TITLE
Python Windows DLL search paths

### ISSUE THREAD

**Issue by 8174b6f2-41a7-4cac-9b1f-2c3eb837ecd0** [python/cpython#87339]
BPO | [43173](https://bugs.python.org/issue43173)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-02-09.18:16:16.800>
created_at = <Date 2021-02-09.02:45:38.738>
labels = ['type-bug', '3.8', '3.9', '3.10', 'invalid', 'OS-windows']
title = 'Python Windows DLL search paths'
updated_at = <Date 2021-02-09.18:26:07.608>
user = 'https://bugs.python.org/jmoguill2'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-09.18:26:07.608>
actor = 'jmoguill2'
assignee = 'none'
closed = True
closed_date = <Date 2021-02-09.18:16:16.800>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2021-02-09.02:45:38.738>
creator = 'jmoguill2'
dependencies = []
files = []
hgrepos = []
issue_num = 43173
keywords = []
message_count = 4.0
messages = ['386688', '386691', '386736', '386738']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'jmoguill2']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43173'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by wangruohui** [comment]
> Using a debugger, you can see the name of the missing DLL or procedure if loader snaps are enabled for the application.

Hello @eryksun,

Could you please suggest some details about the *debugger*? What is that and how to use. 

I have faced such problem several times on Windows. Due to no feedback information of which DLLs are missing, I had to spent long time trying a lot of things but still "doesn't work & don't know why". I used Dependency Walker as an assistant tool to find missing DLLs, but the information is sometimes not accurate. As an example, I included paths in `env:PATH` so that dependency walker could find every dependency but `ctypes.CDLL('xxx')` still failed, until I am aware of `os.add_dll_directory()`. So a debugger would be very helpful.
