### ISSUE TITLE
TURTLE: Default values for basic Turtle commands

### ISSUE THREAD

**Issue by 82987a2a-0745-440f-8ca8-a5f706bdc114** [python/cpython#87348]
BPO | [43182](https://bugs.python.org/issue43182)
--- | :---
Nosy | @terryjreedy, @willingc, @Bruce1979

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-10.00:36:45.654>
labels = ['type-feature', 'library', '3.10']
title = 'TURTLE: Default values for basic Turtle commands'
updated_at = <Date 2021-02-14.23:38:14.204>
user = 'https://github.com/Bruce1979'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-14.23:38:14.204>
actor = 'Bruce1979'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-02-10.00:36:45.654>
creator = 'Bruce1979'
dependencies = []
files = []
hgrepos = []
issue_num = 43182
keywords = []
message_count = 3.0
messages = ['386750', '386894', '386977']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'gregorlingl', 'willingc', 'Bruce1979']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43182'
versions = ['Python 3.10']
```

</p></details>

**Comment by sethwoodworth** [comment]
May I propose removing 3.10 and adding 3.12? (now that 3.11rc2 is released)

**Comment by terryjreedy** [comment]
I have quite adding versions to feature issues, as they are only merged into main, whatever that represents at the time of merging.

**Comment by ggorlen** [comment]
I think this will increase confusion. Turtle methods are already too permissive, accepting variable arguments and types in many cases, and are often overload zero-argument calls for getter purposes. Rather than producing silent behavior using arbitrary magic values that aren't visible to the user, it's better to present the beginning programmer with a clear error message of the contract violation.

Having worked with many beginning programmers, single integer arguments like `forward(50)` has never proven to be a serious blocker, and keeps to the design of Logo. On the other hand, I've had countless cases of beginning programmers confused by the heavy use of overloading in Python, whether it be mixing functional and instance interfaces or passing the wrong arguments to a confusing multi-modal and variable type/parameter method like `color`.

Zen says:
- Explicit is better than implicit.
- In the face of ambiguity, refuse the temptation to guess.
- There should be one-- and preferably only one --obvious way to do it.

...broken extensively by the turtle module, unfortunately

**Comment by terryjreedy** [comment]
I agree with @ggorlen, hence closing.  90 degrees is a plausible default for turning, but there is no plausible default for moving.  I don't like using no-args for getting, but it is there.  We usually use defaults when there is an obvious or necessary null value, not for arbitrary values.

Any further discussion should be done on a post on https://discuss.python.org/c/ideas/6, linked here.  But I do not encourage that.
