### ISSUE TITLE
venv does not install libpython

### ISSUE THREAD

**Issue by 7313add6-0985-4482-ab8a-55b0f2ec30b7** [python/cpython#87500]
BPO | [43334](https://bugs.python.org/issue43334)
--- | :---
Nosy | @vsajip, @tiran, @encukou, @AliyevH, @anuppari

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-07-20.13:26:30.811>
created_at = <Date 2021-02-26.22:40:16.689>
labels = ['library', 'type-bug', 'expert-installation', 'invalid', 'expert-C-API']
title = 'venv does not install libpython'
updated_at = <Date 2021-07-20.13:26:30.811>
user = 'https://github.com/anuppari'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-20.13:26:30.811>
actor = 'petr.viktorin'
assignee = 'none'
closed = True
closed_date = <Date 2021-07-20.13:26:30.811>
closer = 'petr.viktorin'
components = ['Installation', 'Library (Lib)', 'C API']
creation = <Date 2021-02-26.22:40:16.689>
creator = 'anuppari'
dependencies = []
files = []
hgrepos = []
issue_num = 43334
keywords = []
message_count = 9.0
messages = ['387752', '388494', '388552', '388553', '388720', '388724', '388883', '388889', '397870']
nosy_count = 5.0
nosy_names = ['vinay.sajip', 'christian.heimes', 'petr.viktorin', 'AliyevH', 'anuppari']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43334'
versions = []
```

</p></details>

**Comment by arcivanov** [comment]
Anybody who needs `libpython` in virtual environments or user sites, if you build your package with https://github.com/karellen/wheel-axle version with `--require-libpython true` the symlinks to `base_exec_prefix`'s libpython will be created for you automatically upon installation.

**Comment by vsajip** [comment]
But note the wheel-axle disclaimer: "WARNING: THIS IS EXPERIMENTAL BETA SOFTWARE. THERE ARE NO WARRANTIES OF ANY KIND. USE AT YOUR OWN RISK. ADDITIONAL INCLUDED DISCLAIMERS ALSO APPLY." I know that disclaimers of warranty generally apply to OSS software, but this is in addition to what's in the (Apache) license.

**Comment by arcivanov** [comment]
It's not "in addition to what's in the (Apache) license", it's a summary restatement of what's in ASL 2.0 section 7.
"Beta" warning is just an honest disclosure of the state of the software.

**Comment by vsajip** [comment]
What I meant was, it's been especially highlighted even though it's already in the license.

**Comment by arcivanov** [comment]
Yes, because usually people don't read licenses.

**Comment by canada-geek** [comment]
Hi, sorry to ask a question on a (slightly) older topic... I understand what's being said above. As a relative noob when it comes to venv, I'm wondering how I would go about doing the following...

For the projects I work on, I need to run different copies/versions of various tools (e.g gdb). Each such copy ends up having different requirements when it comes to things like python versions (some are newer, some are older and have system requirements that are not compatible with newer python, etc).

Tools like GDB obtain their python linkage via the `libpythonX.so`.

Note how in this scenario, the per-version library is not for development purposes; rather, it's to enable operation of each tool with its stated dependencies and their versions.

1. How would I go about doing this? Would venv (and/or something like it) help here?
2. is there a way to activate venv upon invocation of a tool/application, rather than entering/exiting a directory?

For point (2) I figure I can always have a wrapper script that can activate the environment as needed; but if you have other suggestions I'd love to hear them.

Thanks for your time and attention.
