### ISSUE TITLE
multicorevm: guarantee type multi sub interpreters safe

### ISSUE THREAD

**Issue by 7aa09af7-4256-46da-93fc-f6eef717c259** [python/cpython#87608]
BPO | [43442](https://bugs.python.org/issue43442)
--- | :---
Nosy | @JunyiXie

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-09.06:39:09.180>
labels = []
title = 'multicorevm: guarantee type multi sub interpreters safe'
updated_at = <Date 2021-03-09.06:39:09.180>
user = 'https://github.com/JunyiXie'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-09.06:39:09.180>
actor = 'JunyiXie'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-03-09.06:39:09.180>
creator = 'JunyiXie'
dependencies = []
files = []
hgrepos = []
issue_num = 43442
keywords = []
message_count = 1.0
messages = ['388333']
nosy_count = 1.0
nosy_names = ['JunyiXie']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue43442'
versions = []
```

</p></details>

**Comment by iritkatriel** [comment]
CC @ericsnowcurrently

**Comment by ericsnowcurrently** [comment]
@JunyiXie, sorry for the *very* late reply.  I'm not sure how this slipped through the cracks.

**My brief response:** I'm pretty sure this is a non-issue.  Feel free to clarify if I've misunderstood.

**My long response:**

Interpreters (i.e. their state) are typically highly isolated from one another.  However, with the right config options to `Py_NewInterpreterFromConfig()`[^1] you can create an interpreter that shares a specific set of state with the main interpreter.  For example, an interpreter can use the main interpreter's GIL, meaning only one such interpreter in one thread can hold the GIL at a time and thus be running.

[^1]: With the legacy `Py_NewInterpreter()` you always get an interpreter that shares key state, like the GIL, with the main interpreter.  Before 3.12 (PEP 684), this was the status quo for subinterpreters.

The isolation between interpreters is fairly strict, particularly when it comes to objects.  However, we have made allowances for specific objects, such that they may be shared by all interpreters (for the sake of performance).  This includes the singletons, some commonly used simple immutable objects (e.g. small ints), and all the builtin static types[^2].  All such objects are immortal (PEP 683).  For all such objects, we have carefully made them all safe for sharing.  There really shouldn't be any other objects that get directly shared between interpreters.

[^2]: We did have to make some special accommodations for the builtin static types, since all type objects store interpreter-specific data in `__dict__` and `__subclasses__` (and the list of weakrefs).  We added a mechanism to keep that mutable part of each type object on the corresponding interpreter state, while allowing the type objects to be shared.  We did *not* add a similar mechanism for static types in extension modules, though we may revisit the idea of doing so in the future.

The only[^3] exception is static types in extension modules.  They get shared by all interpreters that import the module.  However, there is a very important caveat: static types are only supported in single-phase init modules (not PEP 489 multi-phase init modules).  Single-phase init modules are restricted; they may only be imported in the main interpreter or in subinterpreters that share the main interpreter's GIL.  Thus static types in extension modules don't need any special accommodation.

[^3]: There are actually a small number of objects from extension modules that do get shared, mostly `PyModuleDef`.  However, they are mostly used internally and not exposed to users.

With all that in mind, I don't think there is anything to be done here at this point.  Again, if I've misunderstood please feel free to clarify.

**Comment by ericsnowcurrently** [comment]
I'm going to close this tomorrow (but we can re-open the issue if needed).
