### ISSUE TITLE
functools.cached_property incorrectly locks the entire descriptor on class instead of per-instance locking

### ISSUE THREAD

**Issue by ff59cd45-ebe3-4b3e-9696-65dc59a38b8c** [python/cpython#87634]
BPO | [43468](https://bugs.python.org/issue43468)
--- | :---
Nosy | @tim-one, @rhettinger, @ncoghlan, @pitrou, @carljm, @jab, @serhiy-storchaka, @ztane, @graingert, @youtux
PRs | <li>python/cpython#27609</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-11.06:37:47.884>
labels = ['3.8', 'library', '3.9', '3.10', 'performance']
title = 'functools.cached_property incorrectly locks the entire descriptor on class instead of per-instance locking'
updated_at = <Date 2021-09-07.16:52:45.061>
user = 'https://github.com/ztane'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-07.16:52:45.061>
actor = 'pitrou'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-03-11.06:37:47.884>
creator = 'ztane'
dependencies = []
files = []
hgrepos = []
issue_num = 43468
keywords = ['patch']
message_count = 11.0
messages = ['388480', '388499', '388592', '398290', '398291', '398680', '398686', '398719', '398837', '398861', '401308']
nosy_count = 11.0
nosy_names = ['tim.peters', 'rhettinger', 'ncoghlan', 'pitrou', 'carljm', 'pydanny', 'jab', 'serhiy.storchaka', 'ztane', 'graingert', 'youtux']
pr_nums = ['27609']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue43468'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-101890

**Comment by carljm** [comment]
Sorry everyone for the bad implementation here. The initial PR (based on the widely used implementations in e.g. Django and Pyramid) didn't have locking; I added locking during review at the request of some commenters in the original issue (based on the implementation in some other less-used third-party package), but I think (even apart from this issue) it was a mistake to add it in the first place.

I agree with @serhiy-storchaka and https://mobile.twitter.com/kristjanvalur/status/1431027975298895883 that the locking is basically out-of-place here: Python data structures (e.g. dict) guarantee only (mostly via the GIL) that they won't get into invalid internal states and segfault the interpreter in the face of concurrency, they don't guarantee an absence of application-level data races. That's up to the application to determine and apply the locking that it needs at a higher level.

I think the best of bad options here is to add either `cached_property_no_lock` (name to-be-bikeshedded) or a `nolock=True` keyword argument, and eventually deprecate and remove the locking behavior. I can put up a PR for this. Any preferences about new name vs kwarg?

**Comment by dholth** [comment]
`fast_cached_property`, `cursed_property`

**Comment by patacca** [comment]
> I think the best of bad options here is to add either cached_property_no_lock (name to-be-bikeshedded) or a nolock=True keyword argument, and eventually deprecate and remove the locking behavior. I can put up a PR for this. Any preferences about new name vs kwarg?

Is there any progress in this direction?

**Comment by AlexWaygood** [comment]
> Any preferences about new name vs kwarg?

Personally I'd vote for the kwarg approach.

**Comment by ryan-williams** [comment]
I think [`cached_property.lock`](https://github.com/python/cpython/blob/v3.10.7/Lib/functools.py#L950) is causing a `PicklingError` when a `cached_property` overrides another `cached_property`:

```python
from functools import cached_property
from joblib import Parallel, delayed

class AAA:
    @cached_property
    def num(self): return 111

class BBB(AAA):
    @cached_property
    def num(self): return 222

def test(arg): return arg

Parallel(n_jobs=2)(delayed(test)(bbb) for bbb in [BBB(), BBB()])
```

<details><summary>Output: <code>TypeError: cannot pickle '_thread.RLock' object</code></summary>

```
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "$PYTHON_HOME/site-packages/joblib/externals/loky/backend/queues.py", line 153, in _feed
    obj_ = dumps(obj, reducers=reducers)
  File "$PYTHON_HOME/site-packages/joblib/externals/loky/backend/reduction.py", line 271, in dumps
    dump(obj, buf, reducers=reducers, protocol=protocol)
  File "$PYTHON_HOME/site-packages/joblib/externals/loky/backend/reduction.py", line 264, in dump
    _LokyPickler(file, reducers=reducers, protocol=protocol).dump(obj)
  File "$PYTHON_HOME/site-packages/joblib/externals/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread.RLock' object
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "$PWD/foo.py", line 16, in <module>
    print(parallel(delayed(test)(bbb) for _ in [1, 2]))
  File "$PYTHON_HOME/site_packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "$PYTHON_HOME/site_packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "$PYTHON_HOME/site_packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "$PYTHON_HOME/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "$PYTHON_HOME/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
_pickle.PicklingError: Could not pickle the task to send it to the workers.
```
</details>

Notes:
- If both `AAA.num` and `BBB.num` are changed to `@property`, the error goes away.
  - If one is a `@property` and the other is a `@cached_property`, the error remains.
- I tried working around it by overriding `__getstate__` to omit any attributes that are `cached_property`s on the class instance, but it didn't help.

**Comment by JelleZijlstra** [comment]
PR #98123 was closed because the proposed deprecation approach is too painful for users. Unfortunately that still leaves us without a good solution.

Here are some alternatives:

1. Just rip out the locking code without a deprecation in code. This would fix the bug and improve performance for most users, but it would break users who rely on the current per-class locking. Do any such users exist? I'm not convinced they do, but our general policy is to assume yes. Perhaps we can justify a BC-breaking change here if we clearly document the behavior change and call it out widely in documentation. Concretely, we could do a docs-only deprecation in 3.12 and 3.13 and then remove the locking code in 3.14.
2. Create a new property that is like cached_property but without locking. But this has most of the same problems as #98123 had, and it's hard to think of a good name.
3. "Fix" the locking code to be per-instance instead of per-class. But as @carljm calls out in https://github.com/python/cpython/pull/98123#issuecomment-1279555898, this isn't without problems either. The locking code would be complex and pickling may be affected. I would add that this change may itself cause a BC break: hypothetical code that relies on the current behavior might well be protecting some global state instead of per-instance state.

I feel (1) is the best solution, though it's sad to have to wait until 3.14.

**Comment by pitrou** [comment]
Why not:

4. Add an optional `lock` argument, but without deprecating the current form.

**Comment by pitrou** [comment]
> 1. Do any such users exist? I'm not convinced they do, but our general policy is to assume yes.

I'm sure they do. Moreover, this will break code in mysterious and random ways that will leave users puzzled. So I'm strongly -1 on this.

**Comment by AlexWaygood** [comment]
I suppose the advantage of adding a new class without the locking behaviour is that users will potentially only have to update one line of code to opt out of the locking:

```diff
-from functools import cached_property
+from functools import cached_property_no_lock as cached_property
```

Adding the new class could maybe be combined with @pitrou's suggestion of adding the optional `lock` argument to the existing class without deprecating the current form. That would mean the new class could just be a very simple wrapper:

```python
class cached_property_no_lock(cached_property):
    def __init__(self, func):
        super().__init__(func, lock=False)
```

**Comment by carljm** [comment]
I'm quite tempted by option (1), because it's clearly what we would do given a time machine, and I haven't yet seen anyone, in any forum, mention a real use case in which they are using `cached_property` and depending on the locking. Whereas I have seen many "significant" users (e.g. the Django project) avoid the stdlib `cached_property` entirely because of this bug, and instead continue maintaining their own external lockless version. That said, I think @pitrou is right that there's a reasonable chance that someone, somewhere, even if unaware, is depending on it, and the behavior change when it goes away could be quite hard to debug, so it's probably not a good option :/

I think the "change only one line to opt out" advantage of `cached_property_no_lock` is significant, and I'm not sure there is any need to provide both `cached_property_no_lock` and `cached_property(lock=False)`. The latter is slightly more verbose, more punctuation, and slightly harder to alias to a shorter name (can't be done in the import.) Also there is inherent hard-to-read complexity in the implementation of decorators with optional arguments. So I think "new name" is better than "optional argument."

I can submit a new PR with `cached_property_no_lock` and no deprecation.

**Comment by ionite34** [comment]
> I think the "change only one line to opt out" advantage of `cached_property_no_lock` is significant

It also seems to create an odd library situation down the road, when new users have to choose between the more version compatible and intuitively named `cached_property` which comes at the cost of an undocumented global thread lock, or a newer `cached_property_no_lock` that should be the default choice.

Seems counterintuitive with the idea of no lock being what most users want, and more importantly, expect.

The concept of the lock, (and as implemented by third party libraries), has always seemed to be intended to be based on instances and not be global, if we can't rationalize a valid use case for this global lock, why should `cached_property` still stay in the stdlib after a theoretical `cached_property_no_lock`?

We will either have new users who don't need a lock accidentally using `cached_propery` when they should be using `cached_propery_no_lock`, or users needing an instance lock accidentally using `cached_property` when they really need an instance-based thread lock, which the stdlib wouldn't offer.

Choices that benefit seemingly nobody to keep a undocumented implementation detail broken for a theoretical user that likely does not exist would be detrimental to `functools`'s coherence as a library and to CPython.

Imo, the current optimistic path is removing the lock from cached_property and documenting this. I wouldn't think it affects backwards compatibility if the lock was an undocumented implementation detail.

> and the behavior change when it goes away could be quite hard to debug

I would argue that the vast majority of users are also experiencing hard to debug thread lock issues due to this undocumented global class thread lock. Already this issue is referenced dozens of times across downstream libraries as a caution *against* switching to `functools.cached_property` and instead to rely on a third party library.

Imo, a change in undocumented implementation behavior should aim to fix bugs for the majority of users. Under the idea that any affected behavior is breaking BC there would theoretically be no bug fix possible for any feature.

**Comment by carljm** [comment]
@eendebakpt made another suggestion over on my closed PR #98123 :

> What about the following variation? Add a kwarg with values False, True and None.

> Value True has the same behaviour as in this PR
> Value False has the same behaviour as in this PR
> Value None has the same behaviour as True, but detects whether the lock is actually used. Only if the lock is used, a deprecation warning is issued. (not sure whether this is technically possible)
> The default value is None for several python releases, after which the default value is changed to False .

> In this way most of the users (who do not use threading, so no use of the locking) will have the old behaviour for a couple of releases, and then switch to the desired implementation. Only users that make use of the locking will get a deprecation warning, but one that is easy to fix (e.g. update to lock=True).

I think the main problem here is what it means to "detect if the lock is used." The only reasonable definition I can think of would be "is the lock ever held by another thread when we try to access it."  I think this is detectable by using a non-blocking call to `acquire`; if it fails, we issue the deprecation warning followed by a blocking call. It is, however, a bit strange to issue a deprecation warning based on a behavior of the system that may be non-deterministic.

**Comment by carljm** [comment]
I haven't submitted the new PR for `cached_property_no_lock` yet, mostly because I'm not very happy with that solution either, for the reasons @ionite34 describes, and I still wonder if "just remove the locking, with several versions' doc warning" isn't practically the best option for the vast majority of Python users.

It seems like we have strong differences of opinion here among core developers; there are tradeoffs with any option we choose, and it seems like a largely subjective matter of weighing the tradeoffs. Would a Discourse thread/poll be a reasonable next step to gather more perspectives? Or even bringing the question to the SC?

**Comment by carljm** [comment]
I started a thread at https://discuss.python.org/t/finding-a-path-forward-for-functools-cached-property/23757

**Comment by carljm** [comment]
Following extensive discussion in https://discuss.python.org/t/finding-a-path-forward-for-functools-cached-property/23757 that did not reach full consensus of core devs, I asked for a Steering Council ruling on how to handle this issue: https://github.com/python/steering-council/issues/172

The Steering Council's decision was that the locking should be removed in Python 3.12, with a note in What's New, as done in https://github.com/python/cpython/pull/101890

Thanks everyone for your contributions to this issue!
