### ISSUE TITLE
Improve the textual representation of IPv4-mapped IPv6 addresses

### ISSUE THREAD

**Issue by c028746c-90ae-4571-80c8-c13d66d649c7** [python/cpython#87799]
BPO | [43633](https://bugs.python.org/issue43633)
--- | :---
Nosy | @opavlyuk, @maxmouchet
PRs | <li>python/cpython#29345</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-26.17:34:40.530>
labels = ['type-feature', 'library']
title = 'Improve the textual representation of IPv4-mapped IPv6 addresses'
updated_at = <Date 2021-11-01.12:05:04.773>
user = 'https://github.com/maxmouchet'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-01.12:05:04.773>
actor = 'opavlyuk'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-03-26.17:34:40.530>
creator = 'maxmouchet'
dependencies = []
files = []
hgrepos = []
issue_num = 43633
keywords = ['patch']
message_count = 2.0
messages = ['389556', '405434']
nosy_count = 2.0
nosy_names = ['opavlyuk', 'maxmouchet']
pr_nums = ['29345']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43633'
versions = []
```

</p></details>

### Linked PRs
* gh-135078
* gh-135079
* gh-135080
* gh-135081

**Comment by asvetlov** [comment]
Done by #29345

**Comment by kellyjonbrazil** [comment]
Are there any tests for the `reverse_pointer` method? I'm seeing strange results with the new behavior:

IP Address: `::FFFF:192.168.1.35`

Results in a reverse_pointer of:

`5.3...1...8.6.1...2.9.1.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa`

instead of the old:

`3.2.1.0.8.a.0.c.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa`

I'm not sure which one is more valid or if a pointer record is even relevant in the context of mapped addresses. The original way *seems* more correct to me if nothing for the fact that there are strange extra dots in the new output.

**Comment by oprypin** [comment]
I'd like to express my concern that this change got backported to all these patch releases of Python. Surely the feature is not so important that everyone needs to get it immediately? Compared to the tradeoff that this is supposed to be bugfixes-only?

As I'm rushing to apply the latest security release, I see that the patch release also changed our code that produces IPv6 addresses to now produce `::ffff:7.8.9.10` instead of `::ffff:708:90a`.
