### ISSUE TITLE
TracebackException or StackSummary.extract with capture_locals=True fail to catch exceptions raised by repr() on value of frame local variable in FrameSummary.__init__.

### ISSUE THREAD

**Issue by 326bfa4a-a113-4719-b506-5436db473ad6** [python/cpython#87822]
BPO | [43656](https://bugs.python.org/issue43656)
--- | :---
Nosy | @rbtcollins, @serhiy-storchaka, @iritkatriel, @moi90, @akulakov
PRs | <li>python/cpython#25062</li><li>python/cpython#29299</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-29.09:36:49.757>
labels = ['invalid', 'type-feature', '3.8', '3.9', '3.10']
title = 'TracebackException or StackSummary.extract with capture_locals=True fail to catch exceptions raised by repr() on value of frame local variable in FrameSummary.__init__.'
updated_at = <Date 2021-11-25.14:52:05.471>
user = 'https://github.com/moi90'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-25.14:52:05.471>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-03-29.09:36:49.757>
creator = 'moi90'
dependencies = []
files = []
hgrepos = []
issue_num = 43656
keywords = ['patch']
message_count = 43.0
messages = ['389679', '389680', '389794', '389815', '389819', '389840', '389842', '393199', '393298', '393519', '404319', '404330', '404392', '404445', '404452', '404456', '404457', '404464', '404468', '404514', '404567', '404603', '404736', '404950', '404988', '404989', '405028', '405033', '405049', '405214', '405238', '405893', '405918', '405935', '405994', '406008', '406012', '406042', '406107', '406997', '406998', '406999', '407001']
nosy_count = 6.0
nosy_names = ['rbcollins', 'serhiy.storchaka', 'iritkatriel', 'moi90', 'andrei.avk', 'jbw']
pr_nums = ['25062', '29299']
priority = 'normal'
resolution = 'not a bug'
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43656'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
While I don't think it's a good idea to teach python learners that swallowing exceptions is a good idea, and it's easy enough to rerun the student's homework with capture_locals=False, the situation may be different in large prod jobs that fail intermittently. In a case like that the problem may not be easily repeatable, and the traceback module should prioritise the original exception over any rendering errors.  While it is a little weird to use capture_locals in a production job, people may want to do it.

Given that we have the _safe_string utility which is used in a few other places for this purpose (for either repr or str), I don't think there is much harm applying it to the locals as well.

@moi90 - Would you like to submit a path with this change, plus some unit tests and doc update? This is a new feature rather than a bugfix so we should not backport it.

--- a/Lib/traceback.py
+++ b/Lib/traceback.py
@@ -279,7 +279,8 @@ def __init__(self, filename, lineno, name, *, lookup_line=True,
         self._line = line
         if lookup_line:
             self.line
-        self.locals = {k: repr(v) for k, v in locals.items()} if locals else None
+        self.locals = {k: _safe_string(v, 'local', func=repr)
+                          for k, v in locals.items()} if locals else None
         self.end_lineno = end_lineno
         self.colno = colno
         self.end_colno = end_colno

**Comment by iritkatriel** [comment]
Yes, I suggested a rewording of the news file. You can click the button to accept it if you're happy with it.
