### ISSUE TITLE
re.match appears to hang with certain combinations of pattern and string

### ISSUE THREAD

**Issue by 84cae046-a27b-4ad9-bf51-e627d9912443** [python/cpython#87852]
BPO | [43686](https://bugs.python.org/issue43686)
--- | :---
Nosy | @gpshead, @sweeneyde
Superseder | <li>bpo-1662581: the re module can perform poorly: O(2**n) versus O(n**2)</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-04-12.01:45:43.099>
created_at = <Date 2021-04-01.03:11:36.212>
labels = ['library', '3.9', 'performance']
title = 're.match appears to hang with certain combinations of pattern and string'
updated_at = <Date 2021-04-12.01:45:43.094>
user = 'https://bugs.python.org/alegrigoriev'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-12.01:45:43.094>
actor = 'gregory.p.smith'
assignee = 'none'
closed = True
closed_date = <Date 2021-04-12.01:45:43.099>
closer = 'gregory.p.smith'
components = ['Library (Lib)']
creation = <Date 2021-04-01.03:11:36.212>
creator = 'alegrigoriev'
dependencies = []
files = []
hgrepos = []
issue_num = 43686
keywords = []
message_count = 3.0
messages = ['389949', '389953', '390809']
nosy_count = 3.0
nosy_names = ['gregory.p.smith', 'Dennis Sweeney', 'alegrigoriev']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '1662581'
type = 'performance'
url = 'https://bugs.python.org/issue43686'
versions = ['Python 3.9']
```

</p></details>

**Comment by albertoperdomo2** [comment]
Hi. I have read the answers stating that this behaviour is expected and somehow "normal" given the circumstances. But I actually got a similar issue and so far, I haven't waited long enough to let the `match` finish (20+ minutes). Is there a way to prevent this? I get that it has to do with the string we are passing rather than the `regexp` object itself, so `compile` doesn't work in this sense, but has anyone come up with something to do the trick?
