### ISSUE TITLE
Unexpected Parsing of Numeric Literals Concatenated with Boolean Operators

### ISSUE THREAD

**Issue by 10e2a1cb-ac93-40f2-a3f7-a6f5753fce04** [python/cpython#87999]
BPO | [43833](https://bugs.python.org/issue43833)
--- | :---
Nosy | @gvanrossum, @rhettinger, @cfbolz, @nedbat, @serhiy-storchaka, @zooba, @gvanrossum, @asottile, @pablogsal, @miss-islington, @sco1, @pxeger, @shreyanavigyan, @alimuldal
PRs | <li>python/cpython#25466</li><li>python/cpython#26614</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-06-09.00:25:00.346>
created_at = <Date 2021-04-13.18:27:19.816>
labels = ['interpreter-core', 'type-bug', '3.10']
title = 'Unexpected Parsing of Numeric Literals Concatenated with Boolean Operators'
updated_at = <Date 2021-11-08.13:52:29.794>
user = 'https://github.com/sco1'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-08.13:52:29.794>
actor = 'pablogsal'
assignee = 'none'
closed = True
closed_date = <Date 2021-06-09.00:25:00.346>
closer = 'pablogsal'
components = ['Interpreter Core']
creation = <Date 2021-04-13.18:27:19.816>
creator = 'sco1'
dependencies = []
files = []
hgrepos = []
issue_num = 43833
keywords = ['patch']
message_count = 27.0
messages = ['390981', '390984', '390988', '390991', '390993', '390995', '390996', '390997', '390998', '390999', '391001', '391002', '391003', '391042', '391050', '391051', '391335', '391336', '391340', '391341', '391351', '391354', '395367', '395368', '396498', '405939', '405949']
nosy_count = 16.0
nosy_names = ['gvanrossum', 'rhettinger', 'Carl.Friedrich.Bolz', 'nedbat', 'Joshua.Landau', 'serhiy.storchaka', 'steve.dower', 'Guido.van.Rossum', 'Anthony Sottile', 'pablogsal', 'miss-islington', 'sco1', 'pxeger', 'shreyanavigyan', 'alimuldal', 'rrauenza']
pr_nums = ['25466', '26614']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43833'
versions = ['Python 3.10']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
It is still DeprecationWarning.

**Comment by rizwan342** [comment]
I tried the code that is the subject of this issue, 
```python
[0x1for x in range(10)]
```
but in the usual IDLE installable from python.org, it doesn't raise anything. It still returns `[31]`. 

Further note to @pxeger: Our code-golf answers are normally posted in a specific python version (such as 2 or 3). When it's omitted, we assume it's Python 3, or the Python version that existed when the answer was posted. Besides an easy fix for this issue will be to specify the latest version of Python that allows this bug to be exploited, i.e. if this bug is fixed in, say Python 3.12, we can simply update our answers to say they work in Python versions before 3.12. Otherwise I don't think this bug being fixed will result in issues in executed code.

**Comment by serhiy-storchaka** [comment]
Please open a new issue for IDLE. Perhaps there is already an open issue for SyntaxWarning in IDLE.

**Comment by rizwan342** [comment]
Where?

**Comment by rizwan342** [comment]
I have opened a new one under BPO 99567.

**Comment by rizwan342** [comment]
@pablogsal this comment on my closed issue says otherwise:

> **In 3.12.0a2+, as of today, this is still just a warning**. Duplicate of #82005. Thanks for the current example.
