### ISSUE TITLE
There is a way to access an underlying mapping in MappingProxyType

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#88004]
BPO | [43838](https://bugs.python.org/issue43838)
--- | :---
Nosy | @gvanrossum, @rhettinger, @ncoghlan, @serhiy-storchaka, @brandtbucher, @domdfcoding
PRs | <li>python/cpython#27300</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-08-07.07:55:34.904>
created_at = <Date 2021-04-14.07:34:28.852>
labels = ['interpreter-core', 'type-bug', '3.8', '3.9', '3.10']
title = 'There is a way to access an underlying mapping in MappingProxyType'
updated_at = <Date 2021-08-07.08:52:38.535>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-07.08:52:38.535>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2021-08-07.07:55:34.904>
closer = 'gvanrossum'
components = ['Interpreter Core']
creation = <Date 2021-04-14.07:34:28.852>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 43838
keywords = ['patch']
message_count = 13.0
messages = ['391039', '397244', '397245', '398023', '398025', '398033', '398045', '398072', '398700', '399022', '399057', '399059', '399171']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'rhettinger', 'ncoghlan', 'serhiy.storchaka', 'brandtbucher', 'domdfcoding']
pr_nums = ['27300']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43838'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by Tcll** [comment]
thanks for not fixing this so I can completely change the functionality of python with this exploit and fix a ton of the broken syntax and false functionality :)

![](https://i.sstatic.net/F00iKHHV.png)

**Comment by ncoghlan** [comment]
There's a reason we didn't consider this a meaningful security concern:

```
$ cat hack_python.py
#!/usr/bin/python3
import sys

def _hacked(*args, **kwds):
  sys.stdout.write("If they can run Python code, you've already lost\n")

import builtins
builtins.print = _hacked

print("This is fine")
$ ./hack_python.py
If they can run Python code, you've already lost
```

**Comment by Tcll** [comment]
Yep I've caught a few other things as well, such as property not being read-only:

```
>>> class A(object):
...     a = property(lambda i: 'you found Guido')
... 
>>> a = A()
>>> a.a
'you found Guido'
>>> A.a.fget = lambda i: 'fakeout'           
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: readonly attribute
>>> A.a.__init__(lambda i: 'you lost Guido') # no it is certainly NOT readonly
>>> a.a
'you lost Guido'
>>> 
```
*should've used `__new__` instead of `__init__` so the result is a new property with the new getter rather than the same property with the new getter- 😏

as well as not private attributes:

```
>>> class A(object):    
...     __slots__ = ('__private')
...     def __new__(cls):
...         a = object.__new__(cls)
...         a.__private = 'this attribute is private'
...         return a
...     showprivate = lambda a: a.__private
... 
>>> a = A()
>>> a.showprivate()
'this attribute is private'
>>> a._A__private = 'no this attribute is NOT private'
>>> a.showprivate()
'no this attribute is NOT private'
>>> 
```
*should've used a hidden member_descriptor instance removed from the class dict storing the private attribute value instead of just renaming the dict entry* 😏

All of these are just as bad of an exploit as each other

The only thing that was even sort of decent for being read-only was the hidden functionality of member_descriptor applied to `slice()` attributes (could've also been used for `property()` attributes)

but I guess now even that's blown out of the water with the mappingproxy exploit :P

**Comment by ncoghlan** [comment]
There are *many* reasons why in process access restrictions in CPython only prevent inadvertent modifications, they don't prevent malicious ones. See https://lwn.net/Articles/574215/ for more of the problems with internal sandboxes (rather than external ones along the lines of Linux containers).

This closed issue isn't the right place to discuss them though, so I'm going to go ahead and lock this.
