### ISSUE TITLE
Can't create generic NamedTuple as of py3.9

### ISSUE THREAD

**Issue by 0a897b36-5d8a-438c-baf4-965d1bb0b78b** [python/cpython#88089]
BPO | [43923](https://bugs.python.org/issue43923)
--- | :---
Nosy | @gvanrossum, @rhettinger, @ericvsmith, @serhiy-storchaka, @graingert, @ilevkivskyi, @dlukes, @JelleZijlstra, @FHTMitchell, @sobolevn, @Fidget-Spinner, @AlexWaygood, @juliusgeo
PRs | <li>python/cpython#31679</li><li>python/cpython#31779</li><li>python/cpython#31781</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-23.16:22:56.566>
labels = ['type-bug', '3.9', '3.10', '3.11']
title = "Can't create generic NamedTuple as of py3.9"
updated_at = <Date 2022-03-10.21:38:13.215>
user = 'https://github.com/FHTMitchell'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-10.21:38:13.215>
actor = 'behackett'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-04-23.16:22:56.566>
creator = 'FHTMitchell'
dependencies = []
files = []
hgrepos = []
issue_num = 43923
keywords = ['patch']
message_count = 25.0
messages = ['391705', '406083', '406124', '414541', '414557', '414558', '414559', '414563', '414567', '414568', '414570', '414584', '414585', '414589', '414592', '414593', '414705', '414709', '414754', '414791', '414792', '414815', '414816', '414817', '414830']
nosy_count = 16.0
nosy_names = ['gvanrossum', 'rhettinger', 'eric.smith', 'python-dev', 'serhiy.storchaka', 'graingert', 'levkivskyi', 'dlukes', 'JelleZijlstra', 'behackett', 'FHTMitchell', 'Steven Silvester', 'sobolevn', 'kj', 'AlexWaygood', 'juliusgeo']
pr_nums = ['31679', '31779', '31781']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43923'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by dendron2000** [comment]
Hi, just saying that I have ran into that issue as well. My use case is packing some arguments for a function call which would look somewhat like this (a much simplified example):
```python
T = TypeVar("T")

class MessageCallArgs(NamedTuple, Generic[T]):
    caller: Actor
    actorAddress: TypedActorAddress[T]
```
so that later a function can be called:
```python
class A:
    @staticmethod
    def foo(caller: Actor, actorAddress: TypedActorAddress["A"], name: str):
        # Remote call here

callArgs = MessageCallArgs(caller, actorAddress)
A.foo(*callArgs , "blah-blah")
```

`@dataclass` is simply not usable in this case as it does not implicitly convert to a tuple and therefore cannot be straightforwardly used for arguments unpacking. `A.foo(*dataclass.astuple(callArgs)... ` looks super-ugly and superfluous.

Using just NamedTuple looses type information which is useful for type-checking.

So far I have reverted to using just tuple[T] but this looses all benefits of NamedTuple, like named fields and a user-defined type.

It seems to be me that the reason to forbid the creation of generic named tuples is purely technical, which is unfortunate. I do not think that this case is rare, contrary to what has been said in this thread.

**Comment by serhiy-storchaka** [comment]
It did not actually worked in 3.8:
```
>>> class Group(NamedTuple, Generic[T]):
...      key: T
...      group: List[T]
... 
>>> Group[int]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
>>> Group.__bases__
(<class 'tuple'>,)
```
A NamedTuple is not generic, it is just that other base classes were silently ignored.

**Comment by serhiy-storchaka** [comment]
There is a problem related to the fact that `tuple` has the `__class_getitem__` method. And if `Generic[T]` follows `NamedTuple`, it is `tuple.__class_getitem__` called when subscript the type.

It is not specific to `NamedTuple`, this problem exists when you inherit from any generic class and Generic:
```
>>> from typing import *
>>> T = TypeVar('T')
>>> class A(tuple, Generic[T]): ...
... 
>>> class B(Generic[T], tuple): ...
... 
>>> A.__bases__
(<class 'tuple'>, <class 'typing.Generic'>)
>>> B.__bases__
(<class 'typing.Generic'>, <class 'tuple'>)
>>> A[int]
__main__.A[int]
>>> B[int]
__main__.B[int]
>>> type(A[int])
<class 'types.GenericAlias'>
>>> type(B[int])
<class 'typing._GenericAlias'>
>>> A[int, str]
__main__.A[int, str]
>>> B[int, str]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/py/cpython/Lib/typing.py", line 332, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/serhiy/py/cpython/Lib/typing.py", line 1767, in __class_getitem__
    _check_generic(cls, params, len(cls.__parameters__))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/serhiy/py/cpython/Lib/typing.py", line 253, in _check_generic
    raise TypeError(f"Too {'many' if alen > elen else 'few'} arguments for {cls};"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Too many arguments for <class '__main__.B'>; actual 2, expected 1
```
And named tuple types are unexpectedly subscribtable without Generic (since they are `tuple` subclasses):
```
>>> class NT(NamedTuple):
...     x: int
... 
>>> NT[str, float]
__main__.NT[str, float]
```
The problem is how to create non-generic (or generic with the specified parameters) subclasses of generic types.

**Comment by serhiy-storchaka** [comment]
Consider the following example:
```
>>> import collections
>>> from typing import *
>>> T = TypeVar('T')
>>> Group = collections.namedtuple('Group', 'key group')[T, list[T]]
```
It looks somewhere like a generic named tuple. But it conflicts with what is proposed here.

**Comment by gvanrossum** [comment]
So that just inherits `__init_subclass__` from tuple. Isn't it the job of the static checker to reject this? Runtime allows all kinds of nonsense, like `list[int,int,int]`. Is this any different?

**Comment by gvanrossum** [comment]
In any case if you want to make a class that isn't indexable but inherits from a class that is (e.g. namedtuple inheriting from tuple) you can just set `__class_getitem__ = None` in the class.

**Comment by AlexWaygood** [comment]
I agree with Guido.

**Comment by serhiy-storchaka** [comment]
> In any case if you want to make a class that isn't indexable but inherits from a class that is (e.g. namedtuple inheriting from tuple) you can just set `__class_getitem__ = None` in the class.

#92106, #92107.

I have also opened a topic on Python-Dev about blessing the `__dunder__ = None` idiom: https://mail.python.org/archives/list/python-dev@python.org/thread/YGAK34DRWJFSIV2VZ4NC2J24XO37GCMM/
