### ISSUE TITLE
TimedRotatingFileHandler overwrite log

### ISSUE THREAD

**Issue by b5bb6929-5ba3-4e7d-96e1-5f5dfe213472** [python/cpython#88352]
BPO | [44186](https://bugs.python.org/issue44186)
--- | :---
Nosy | @vsajip, @Harry-Lees, @aeg
PRs | <li>python/cpython#26553</li>
Files | <li>[log.py](https://bugs.python.org/file50053/log.py "Uploaded as text/plain at 2021-05-20.10:50:45 by @aeg")</li><li>[log_44186.py](https://bugs.python.org/file50194/log_44186.py "Uploaded as text/plain at 2021-08-01.05:53:29 by @vsajip"): Slightly updated Python script</li><li>[test.sh](https://bugs.python.org/file50195/test.sh "Uploaded as application/x-shellscript at 2021-08-01.05:56:54 by @vsajip"): Test shell script</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/vsajip'
closed_at = None
created_at = <Date 2021-05-20.10:21:59.331>
labels = ['type-bug', 'library', '3.9']
title = 'TimedRotatingFileHandler overwrite log'
updated_at = <Date 2021-08-02.07:48:35.356>
user = 'https://github.com/aeg'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-02.07:48:35.356>
actor = 'vinay.sajip'
assignee = 'vinay.sajip'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-05-20.10:21:59.331>
creator = 'aeg'
dependencies = []
files = ['50053', '50194', '50195']
hgrepos = []
issue_num = 44186
keywords = ['patch']
message_count = 5.0
messages = ['394009', '395141', '398683', '398692', '398732']
nosy_count = 3.0
nosy_names = ['vinay.sajip', 'Harry-Lees', 'aeg']
pr_nums = ['26553']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44186'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-116191
* gh-116208
* gh-116209
* gh-116409
* gh-116585
* gh-116586

**Comment by serhiy-storchaka** [comment]
Adding arbitrary suffixes will break algorithm for computing files to delete on roll over, especially the most reliable variant proposed in #115809.

I think that the best alternative is to check if the destination file already exists, and if it does, do not roll over. If it exists, it means that it was already rolled over. In worst case the logging records will be added in the next snapshot, it is better than losing data. But it should be very rare case, and it means that there is an error in determining the roll over time.

**Comment by serhiy-storchaka** [comment]
There are several bugs here, and #116191 fixes some of them.

* Overwriting already rolled over file. In the reported issue it happens when you run the logger at "midnight", but it also happen when you run it at DST change. There is a period of repeated times, and all logs rolled over during this period were overwritten.
* The reported issue happened because the computed rollover time could be equal to the specified time  if `when='MIDNIGHT'`. It should be the time of the _next_ rollover, i.e. always larger that the specified time.
* The calculation of the rollover time for MIDNIGHT type was incorrect during the DST change. There were also errors for Wx types if the rollover time is close to the DST change time.

There are other bugs, but I'll open separate issues for them.
