### ISSUE TITLE
venv activate script would be good to show failure.

### ISSUE THREAD

**Issue by 148e44e1-d1f1-49a9-87cb-86f9e3279341** [python/cpython#88452]
BPO | [44286](https://bugs.python.org/issue44286)
--- | :---
Nosy | @vsajip, @br-kim

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-06-04.13:43:29.519>
created_at = <Date 2021-06-02.14:03:06.187>
labels = ['3.7', 'invalid', 'type-feature', 'library']
title = 'venv activate script would be good to show failure.'
updated_at = <Date 2021-06-04.13:43:29.518>
user = 'https://github.com/br-kim'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-04.13:43:29.518>
actor = 'idle947'
assignee = 'none'
closed = True
closed_date = <Date 2021-06-04.13:43:29.519>
closer = 'idle947'
components = ['Library (Lib)']
creation = <Date 2021-06-02.14:03:06.187>
creator = 'idle947'
dependencies = []
files = []
hgrepos = []
issue_num = 44286
keywords = []
message_count = 5.0
messages = ['394909', '394997', '395002', '395074', '395083']
nosy_count = 2.0
nosy_names = ['vinay.sajip', 'idle947']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44286'
versions = ['Python 3.7']
```

</p></details>

**Comment by LeuschkeTressa** [comment]
I suggest re-opening this issue.

These problems seem common and elusive[1] and the fix is seemingly easy to implement.

# Motivation

If an unknowing user...
1. moves or renames the project directory, and then
2. activates the venv

...then, the **current behaviour** is:
* silently, the venv won't be activated
* no error message or hint about this will be given
* to the contrary, the user will believe everything is OK since the prompt changes
* there will be all kinds of strange and hard-to-troubleshoot behaviour, e.g. the wrong (system) interpreter being used and installing packages will install them globally

(this happened for me; I came here after hours of trouble-shooting)

The **desired behaviour** would be:
* print an error message
* don't activate the venv

@vsajip:
> venvs aren't meant to be portable

Apparently not, which is fine. This would be an argument _for_ this easy fix.

Renaming or moving a source/project dir is common, and some users will expect it to be possible, believing paths are relative, as is most common for tools working on source dirs. If in doubt, it's not unlikely for a user to simply try, and then believe all is well since the venv seemingly activates successfully (the prompt changes). Often, no problems won't show up at first; instead subtle problems appear later, stemming from unknowingly installing to and using global packages.


# Fix

It seems this fix would be easy to implement.

**https://github.com/python/cpython/blob/main/Lib/venv/scripts/common/activate:**

now:
```bash
[...]
# unset irrelevant variables
deactivate nondestructive

VIRTUAL_ENV="__VENV_DIR__"
export VIRTUAL_ENV
[...]
```

change to something like:
```bash
[...]
# unset irrelevant variables
deactivate nondestructive

if [ ! -d "$__VENV_DIR__" ]; then
    echo "Error: virtual environment directory $__VENV_DIR__ doesn't exist."
else
  VIRTUAL_ENV="__VENV_DIR__"
  export VIRTUAL_ENV
  [...] # (rest of file in this else-clause)
fi
```

(The absolute path in `__VENV_DIR__` not existing is not an absolute guarantee that the project dir wasn't moved/renamed, but would probably catch 95% of these cases. Importantly, there won't be any false positives: if no dir exists for the path in `__VENV_DIR__`, there's no chance that activating this path as a venv is successful.)



# [1]: seemingly common and frustrating problem

Some examples of reports of this specific problem below. Most mention being misled by lack of error message and by believing the prompt changing indicated successful activation. There's sometimes a high degree of frustration, and a simple error message seemingly would have helped most of them. Several at first had no indication that the experienced problems were caused by a move/rename of the source dir.
* https://salvicode.com/post/do-not-move-your-python-project-folder/
* https://stackoverflow.com/questions/41524320/virtualenv-uses-wrong-python-even-though-it-is-first-in-path
* https://stackoverflow.com/questions/59302178/python-virtual-environment-does-not-default-python-packages
* https://stackoverflow.com/questions/65390129/venv-activate-doesnt-not-change-my-python-path
* https://stackoverflow.com/questions/63932002/unable-to-clone-python-venv-to-another-pc
* https://stackoverflow.com/questions/49567494/activating-python-virtual-environment-does-not-switch-to-local-versions-of-pip-a
* https://stackoverflow.com/questions/41608432/virtual-environment-is-not-activating-after-re-installation-of-virtualenv

(there are many more)

Some SO question on moving source dirs with venv, and on whether this is possible/problems that follow from it:
* https://stackoverflow.com/questions/32407365/can-i-move-a-virtualenv (130 upvotes)
* https://stackoverflow.com/questions/6628476/renaming-a-virtualenv-folder-without-breaking-it (170 upvotes).

# Notes

For reference, here are some requests to make the venv paths relative, along with explanations for why that would be a lot of work/not viable:
* https://github.com/python/cpython/issues/70020
* https://github.com/python/cpython/issues/83650
* https://github.com/python/cpython/issues/71335

**Comment by vsajip** [comment]
I added a warning about non-portability of venvs to the documentation. I can try and review any PRs with tests that are related to error checking in the activation scripts.

**Comment by LeuschkeTressa** [comment]
Doc update: that's great.

**Activation script error check:**

I'm not the right person to make a PR unfortunately.

I still suggest re-opening this issue so an error check is addd eventually. Not having one has evidently caused a lot of users a lot of trouble and the fix is straight-forward.
