### ISSUE TITLE
fraction.Fraction does not implement __int__.

### ISSUE THREAD

**Issue by 88a86bee-7d35-4c40-b100-45a74efaa744** [python/cpython#88713]
BPO | [44547](https://bugs.python.org/issue44547)
--- | :---
Nosy | @rhettinger, @mdickinson, @mamrhein, @ambv, @serhiy-storchaka, @MojoVampire
PRs | <li>python/cpython#27851</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-10-21.22:10:31.682>
created_at = <Date 2021-07-01.19:52:28.462>
labels = ['type-feature', 'library', '3.11']
title = 'fraction.Fraction does not implement __int__.'
updated_at = <Date 2021-10-21.22:10:31.681>
user = 'https://github.com/mamrhein'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-21.22:10:31.681>
actor = 'lukasz.langa'
assignee = 'none'
closed = True
closed_date = <Date 2021-10-21.22:10:31.682>
closer = 'lukasz.langa'
components = ['Library (Lib)']
creation = <Date 2021-07-01.19:52:28.462>
creator = 'mamrhein'
dependencies = []
files = []
hgrepos = []
issue_num = 44547
keywords = ['patch']
message_count = 15.0
messages = ['396827', '396840', '396847', '396856', '396858', '396861', '396864', '396868', '396876', '397022', '397033', '399958', '400060', '404682', '404683']
nosy_count = 6.0
nosy_names = ['rhettinger', 'mark.dickinson', 'mamrhein', 'lukasz.langa', 'serhiy.storchaka', 'josh.r']
pr_nums = ['27851']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44547'
versions = ['Python 3.11']
```

</p></details>

**Comment by MojoVampire** [comment]
> The background is an implementation of __pow__ for a fixed-point decimal number:
> 
> ```python
> SupportsIntOrFloat = Union[SupportsInt, SupportsFloat]
> 
> def __pow__(self, other: SupportsIntOrFloat, mod: Any = None) -> Complex:
>     if isinstance(other, SupportsInt):
>         exp = int(other)
>         if exp == other:
>             ... handle integer exponent
>     if isinstance(other, SupportsFloat):
>         # fractional exponent => fallback to float
>         return float(self) ** float(other)
>     return NotImplemented
> ```
> 
> I came across SupportsInt and SupportsFloat, because they are used in typeshed as param types for int and float.

I'm going to note, this code is subtly confusing/wrong. Since `float` itself is considered an instance of `SupportsInt` (and I believe has done so for as long as `isinstance` has worked with `typing.SupportsInt`), actual `float`s will be treated as `int` if they happen to have no decimal component (the equality test at least avoids the worst case where they silently lose data), so the *values* of your arguments change the *type* of your result, which is... not great.

In practice, you really want to be testing for `SupportsIndex` (which means something is logically *equivalent* to an integer and can be converted to an `int` losslessly) and using `operator.index(other)` for the conversion (`int(operator.index(other))` if it must produce an *exact* `int`, not a subclass thereof), or, with slightly different semantics (that should never differ on properly implemented integral types, but many types aren't properly implemented), testing `isinstance(other, numbers.Integral)` (at which point it usually doesn't matter if you use `int()` or `operator.index()` since it supports both, and at worst using `index` allows you to get an `int` subclass as a result, where `int()` guarantees a true `int`).
