### ISSUE TITLE
shutil.copy() inefficient implementation in Windows

### ISSUE THREAD

**Issue by d3dec965-07cb-44d1-8e09-8773848748fc** [python/cpython#88745]
BPO | [44579](https://bugs.python.org/issue44579)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-07.12:11:29.301>
labels = ['3.8', 'OS-windows', 'performance']
title = 'shutil.copy() inefficient implementation in Windows'
updated_at = <Date 2021-07-07.14:39:41.523>
user = 'https://bugs.python.org/sfmc'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-07.14:39:41.523>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2021-07-07.12:11:29.301>
creator = 'sfmc'
dependencies = []
files = []
hgrepos = []
issue_num = 44579
keywords = []
message_count = 3.0
messages = ['397076', '397077', '397091']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'sfmc']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue44579'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-105055
* gh-105086

**Comment by zooba** [comment]
I think it's time to do this one. I've assigned it to myself, but if someone else gets an implementation together first (it could use a `CopyFileEx` implementation in `_winapi`) I'm happy to review and merge.

Performance enhancement can be backported to 3.12. The behaviour of `copy2` should be totally unchanged by this, except in obscure edge cases (where they'll likely be more consistent with every other Windows app as a result of the change).

We should also clearly document that `copy2` may be significantly faster on Windows than the other `copy*` functions. Probably also worth looking for optimisations on other platforms as well, particularly if they preserve stat, so that we can say that `copy2` is fastest on _most_ platforms.
