### ISSUE TITLE
Failure to build on OSF1.

### ISSUE THREAD

**Issue by 91fe83eb-60a5-408f-a3ac-67c884621f9e** [python/cpython#88749]
BPO | [44583](https://bugs.python.org/issue44583)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @jaykrell
PRs | <li>python/cpython#27063</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-08.08:04:32.087>
labels = ['interpreter-core', 'build', '3.11']
title = 'Failure to build on OSF1.'
updated_at = <Date 2021-07-12.11:14:37.701>
user = 'https://github.com/jaykrell'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-12.11:14:37.701>
actor = 'jaykrell'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2021-07-08.08:04:32.087>
creator = 'jaykrell'
dependencies = []
files = []
hgrepos = []
issue_num = 44583
keywords = ['patch']
message_count = 7.0
messages = ['397128', '397194', '397212', '397226', '397227', '397295', '397298']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'jaykrell']
pr_nums = ['27063']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue44583'
versions = ['Python 3.11']
```

</p></details>

**Comment by encukou** [comment]
Sorry for the delay.
Are you still interested in this?

I'd like to allow better community support for architectures that aren't on [the list](https://peps.python.org/pep-0011/#support-tiers), as it can make CPython more resilient and portable in general.
For example, nowadays Python *should* build without `CLOCK_MONOTONIC` (falling back to other methods), but due to our test matrix, that's not tested and might be broken.

For more invasive patches, like `Include/pyportosf.h`, you're better off maintaining them on your own.

**Comment by encukou** [comment]
OSF1 is unsupported per PEP-11.

I'll close the bug and PR.
Like other issues for unsupported platforms, it'll be listed on [the GitHub project](https://github.com/orgs/python/projects/27) for anyone who wants to support the platform unofficially or bring support back. (Although in this case, the patch is pretty big; as I said it's better to maintain a fork.)

I encourage people interested in OSF1 to add themselves to the [Experts list](https://devguide.python.org/core-developers/experts/#platforms) so we know whom to ping.
