### ISSUE TITLE
argparse: potential bugs on add_subparser due to allow_abbrev cannot deal with short options

### ISSUE THREAD

**Issue by d4bcb7b1-d967-45e4-b312-45affcde5f15** [python/cpython#88767]
BPO | [44601](https://bugs.python.org/issue44601)
--- | :---
Nosy | @zhongxiang117
Files | <li>[myargparse.py](https://bugs.python.org/file50143/myargparse.py "Uploaded as text/plain at 2021-07-11.23:21:13 by @zhongxiang117"): reproduce and explanations</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-11.23:21:14.214>
labels = ['3.8', 'type-bug', 'library', '3.9']
title = 'argparse: potential bugs on add_subparser due to allow_abbrev cannot deal with short options'
updated_at = <Date 2021-07-11.23:21:14.214>
user = 'https://github.com/zhongxiang117'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-11.23:21:14.214>
actor = 'zhongxiang117'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-07-11.23:21:14.214>
creator = 'zhongxiang117'
dependencies = []
files = ['50143']
hgrepos = []
issue_num = 44601
keywords = []
message_count = 1.0
messages = ['397268']
nosy_count = 1.0
nosy_names = ['zhongxiang117']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44601'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
You used confusing terminology. Short options are options consisting of a dash followed by a single non-dash character. Options starting with a single dash and followed by multiple characters are called single-dash long options. Options starting with a double dash are called double-dash long options. Short options cannot be abbreviated, but they can be grouped.

`allow_abbre=False` is broken for single-dash long options, this is a known bug and it will be fixed by #124340.

Do you have other issues besides `allow_abbre=False` not working for single-dash long options?
