### ISSUE TITLE
Handling interruption in async tasks

### ISSUE THREAD

**Issue by 38cebdae-dd4c-497f-933f-b82ba2fdc26b** [python/cpython#88927]
BPO | [44764](https://bugs.python.org/issue44764)
--- | :---
Nosy | @ilianiliev

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-07-28.16:18:43.408>
labels = ['type-bug']
title = 'Handling interruption in async tasks'
updated_at = <Date 2021-07-28.16:18:54.865>
user = 'https://github.com/ilianiliev'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-28.16:18:54.865>
actor = 'ilian'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-07-28.16:18:43.408>
creator = 'ilian'
dependencies = []
files = []
hgrepos = ['407']
issue_num = 44764
keywords = []
message_count = 1.0
messages = ['398400']
nosy_count = 1.0
nosy_names = ['ilian']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44764'
versions = []
```

</p></details>

**Comment by gvanrossum** [comment]
@IlianIliev

This issue was quite mysterious to me until I followed the link to https://github.com/grpc/grpc/issues/26123. There (towards the end) it is implied that grpc has a feature called "graceful shutdown" which appears to be working by sending a `KeyboardInterrupt` to a Python process (presumably by sending the process a `SIGINT` signal). The complaint then seems to be that if the signal occurs while the Python process is in an asyncio task that is running some time-consuming code (either `time.sleep()` or some long-running computation) it interrupts the asyncio event loop and everything gets stopped.

Do I have that right?

If that is indeed the problem, the solution might be as simple as running the asyncio event loop in a separate thread, while the main thread just waits forever until a signal arrives. It can then catch the `KeyboardInterrupt` exception and in response send some callback to the thread running the asyncio event loop (e.g. using `loop.call_soon_threadsafe()`).

If I didn't understand the problem correctly, could you indicate whether you are still interested in keeping this issue open?

**Comment by IlianIliev** [comment]
Hi @gvanrossum, it was quite a surprise to see a response from the Python creator himself, and then you for spending time to look at this.

You have correctly understood the problem, and what you proposed is probably going to work, another workaround is wrapping each task in a try/except.

What I am trying to understand is why we have this inconsistent behavior between running in async and non-async mode, and whether this is the expected way for the interpreter to behave.

**Comment by gvanrossum** [comment]
Yes, this is how it is supposed to work.

**Comment by IlianIliev** [comment]
I understand, thank you.
