### ISSUE TITLE
os.symlink arg names are bad

### ISSUE THREAD

**Issue by f59624fb-af69-457f-91dd-feb033bea663** [python/cpython#89000]
BPO | [44837](https://bugs.python.org/issue44837)
--- | :---
Nosy | @ericvsmith, @stevendaprano

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-08-05.12:00:31.700>
created_at = <Date 2021-08-05.09:08:14.904>
labels = ['type-feature', 'invalid', '3.9', 'docs']
title = 'os.symlink arg names are bad'
updated_at = <Date 2021-08-05.12:25:12.200>
user = 'https://bugs.python.org/krey'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-05.12:25:12.200>
actor = 'steven.daprano'
assignee = 'docs@python'
closed = True
closed_date = <Date 2021-08-05.12:00:31.700>
closer = 'krey'
components = ['Documentation']
creation = <Date 2021-08-05.09:08:14.904>
creator = 'krey'
dependencies = []
files = []
hgrepos = []
issue_num = 44837
keywords = []
message_count = 11.0
messages = ['398977', '398980', '398981', '398984', '398985', '398990', '398994', '398995', '398998', '399000', '399001']
nosy_count = 4.0
nosy_names = ['eric.smith', 'steven.daprano', 'docs@python', 'krey']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue44837'
versions = ['Python 3.9']
```

</p></details>

**Comment by koo5** [comment]
> I guess you could come up with some way of supporting both sets of parameter names, 

os.symlink could get a new set of keyword parameters, probably that GNU-ish `target, linkname`. Newly written code could use them instead of the current positional arguments, to avoid ambiguity. 

> but I doubt we'd accept that, either.
what do you mean?

> Using "target" is ambiguous, "target" can mean the target of the
symbolic link (where the sym link points, i.e. the original file) or
it can mean the target of the ln command, i.e. where the symlink is
created.

not when it's in explicit contrast to `linkname`, which it would be required to be.
