### ISSUE TITLE
[DOC] typing.get_type_hints() raises for type aliases with forward references

### ISSUE THREAD

**Issue by 1b512604-cdc3-4788-a438-7a11b43873bd** [python/cpython#89089]
BPO | [44926](https://bugs.python.org/issue44926)
--- | :---
Nosy | @gvanrossum, @ambv, @mhils, @miss-islington, @Fidget-Spinner
PRs | <li>python/cpython#27859</li><li>python/cpython#27860</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-10-18.07:55:48.195>
created_at = <Date 2021-08-16.17:15:16.657>
labels = ['3.11', 'type-bug', 'library', '3.10', 'docs']
title = '[DOC] typing.get_type_hints() raises for type aliases with forward references'
updated_at = <Date 2021-10-18.07:55:48.191>
user = 'https://github.com/mhils'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-18.07:55:48.191>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = True
closed_date = <Date 2021-10-18.07:55:48.195>
closer = 'iritkatriel'
components = ['Documentation', 'Library (Lib)']
creation = <Date 2021-08-16.17:15:16.657>
creator = 'mhils'
dependencies = []
files = []
hgrepos = []
issue_num = 44926
keywords = ['patch']
message_count = 13.0
messages = ['399660', '399662', '399664', '399672', '399675', '399677', '399746', '399774', '399829', '399850', '399852', '399974', '400086']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'docs@python', 'lukasz.langa', 'mhils', 'miss-islington', 'kj']
pr_nums = ['27859', '27860']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue44926'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by macdjord** [comment]
I just got bit by this, and on a case where eliminating the forward references isn't possible, even with delayed evaluation:
```python
JsonScalar: TypeAlias = str | int | float | bool | None
JsonArray: TypeAlias = list["JsonValue"]
JsonObject: TypeAlias = dict[str, "JsonValue"]
JsonCollection: TypeAlias = JsonArray | JsonObject
JsonValue: TypeAlias = JsonScalar | JsonCollection
```

I thought of a radical idea for how to fix this: have _string literals_ track the context in which they are defined. So, to use @mhils's example, `get_type_hints()` would know that `func1()`'s 'x' argument is a `foo.Data` and not a `bar.Data` because the string literal which is stored in `foo.FooData` knows that it was defined in the `foo` module at the module level.

Now, the obvious issues are that this would require adding low-level support for a very specific use-case to a very fundamental part of the language, and the potential for performance penalties. For the latter, I note that this extra source information would only need to be tracked for string literals, not all strings, and the number of string literals in any code-base is inherently finite and usually relatively small. 

For the former, well, it just comes down to how much being able to reliably evaluate types at runtime is. I, for one, frequently deal with cases where it would be helpful, such as converting structured data (particularly dataclasses) to and from JSON.
