### ISSUE TITLE
alighment format for nullable values

### ISSUE THREAD

**Issue by 341ce0e2-bdbb-4bd4-99e6-746f11201a3f** [python/cpython#89328]
BPO | [45165](https://bugs.python.org/issue45165)
--- | :---
Nosy | @ericvsmith, @asottile

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-09-10.15:10:56.135>
labels = ['interpreter-core', 'type-feature', '3.11']
title = 'alighment format for nullable values'
updated_at = <Date 2021-09-10.16:45:08.946>
user = 'https://github.com/asottile'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-10.16:45:08.946>
actor = 'Anthony Sottile'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2021-09-10.15:10:56.135>
creator = 'Anthony Sottile'
dependencies = []
files = []
hgrepos = []
issue_num = 45165
keywords = []
message_count = 3.0
messages = ['401582', '401583', '401600']
nosy_count = 2.0
nosy_names = ['eric.smith', 'Anthony Sottile']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue45165'
versions = ['Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
I understand how you came to this. You are formatting the data as a table, but some values appear to be None instead of a string or a number.

But only you know what is the meaning of None in this context and how should it be output in your program. Outputting it as "None" may be good for your program, but other programs output it as "-", "unknown", "n/a", "unlimited". The exception helps because it allows you to notice the problem and fix the output.

I propose to close this issue.
