### ISSUE TITLE
platform() is not able to detect windows 11

### ISSUE THREAD

**Issue by fcaf1740-8866-4efd-93b0-89b0cac42b85** [python/cpython#89545]
BPO | [45382](https://bugs.python.org/issue45382)
--- | :---
Nosy | @malemburg, @pfmoore, @tjguk, @ambv, @zware, @eryksun, @zooba, @miss-islington, @Evernow
PRs | <li>python/cpython#30817</li><li>python/cpython#30890</li><li>python/cpython#30891</li><li>python/cpython#30894</li>
Files | <li>[demo.py](https://bugs.python.org/file50327/demo.py "Uploaded as text/plain at 2021-10-05.19:58:45 by sahsariga111")</li><li>[import subprocess.py](https://bugs.python.org/file50329/import%20subprocess.py "Uploaded as text/plain at 2021-10-07.07:49:14 by sahsariga111")</li><li>[main.py](https://bugs.python.org/file50330/main.py "Uploaded as text/plain at 2021-10-07.10:20:02 by sahsariga111")</li><li>[main.py](https://bugs.python.org/file50331/main.py "Uploaded as text/plain at 2021-10-07.11:05:47 by sahsariga111")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-10-05.19:43:57.181>
labels = ['library', '3.10']
title = 'platform() is not able to detect windows 11'
updated_at = <Date 2022-03-28.07:10:50.170>
user = 'https://bugs.python.org/sahsariga111'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-28.07:10:50.170>
actor = 'tim.golden'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-10-05.19:43:57.181>
creator = 'sahsariga111'
dependencies = []
files = ['50327', '50329', '50330', '50331']
hgrepos = []
issue_num = 45382
keywords = ['patch']
message_count = 38.0
messages = ['403260', '403261', '403262', '403263', '403264', '403265', '403267', '403271', '403272', '403357', '403358', '403379', '403386', '403452', '403459', '403471', '404451', '404591', '411331', '411336', '411474', '411498', '411659', '411661', '411663', '411671', '411694', '411696', '411704', '411711', '411712', '411714', '411762', '411763', '411764', '415333', '416142', '416146']
nosy_count = 10.0
nosy_names = ['lemburg', 'paul.moore', 'tim.golden', 'lukasz.langa', 'zach.ware', 'eryksun', 'steve.dower', 'miss-islington', 'sahsariga111', 'Evernow']
pr_nums = ['30817', '30890', '30891', '30894']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45382'
versions = ['Python 3.10']
```

</p></details>

**Comment by zooba** [comment]
So I just created a `_wmi` module that can do basic queries without shelling out to another process. It's still fairly complicated, as it requires COM (which requires running on a separate thread to avoid interfering with user code), but should be very usable.

I'm not entirely clear on what the best mapping to `platform` module functions is though, as it would almost certainly result in values changing quite significantly (for the better, but still changing). So I'd prefer to leave that to others to think through.

My main concern with adding the module is the security implications - being able to query all of WMI is _very_ useful, but because we don't offer any way to modify things it isn't quite as useful for legitimate purposes. All you can really do is scan the whole system. Having that available on every Python install by default is a bit scary, so I'm considering limiting the API to only run the `"SELECT * FROM Win32_OperatingSystem"` query.

(There's also likely a significant performance impact if we always do a WMI query, so I'd rather it remain very optional. It has to load up a ton of stuff to do its job.)

**Comment by pfmoore** [comment]
Having WMI queries available by default would be potentially pretty useful. What are the security implications you are thinking of? Given that it’s possible to shell out to wmic, I’m not clear how this would be notably worse…

**Comment by zooba** [comment]
> Given that it’s possible to shell out to wmic, I’m not clear how this would be notably worse…

It's pretty straightforward to block or remove `wmic.exe` if you don't want to allow it on your machine. But that's at the level of paranoia where you should also have your own modified CPython that uses audit hooks to block WMI queries.

Did you have anything specific in mind that it might be useful for?

**Comment by pfmoore** [comment]
> Did you have anything specific in mind that it might be useful for?

Not really, no. More just that I don't see any benefit in having the capability in core Python and then hiding it. I was imagining using it for things that would otherwise need a pywin32 dependency - listing free space on mounted drives, for example, or getting running process information (both of which I have done with pywin32 in the past).

**Comment by zooba** [comment]
Those both seem legitimate, and looking through [this doc](https://docs.microsoft.com/en-us/windows/win32/wmisdk/wmi-tasks-for-scripts-and-applications) I see more that aren't terrible. Provided only `select` queries are supported, I don't really see the harm in letting it be more open. (And it's worth checking for `select` in the query in case there's some craftable query that can modify the system...)

I'm still not planning to make it a non-private API, or to make it return anything richer than `Name=Value\0Name=Value\0` etc., but it's also very unlikely to change so I guess if someone sneakily uses it 🤷‍♂️

**Comment by pfmoore** [comment]
lol, fair enough. I'll let the rest of the world persuade you that the UI needs improving because it's a bit user-unfriendly 🙂

**Comment by zooba** [comment]
It's very user-unfriendly, but it's only an internal API for using in the stdlib 😉 

The rest of the world can copy my code and write their own module.

**Comment by zooba** [comment]
PR #96289 is now updated with `platform` module changes. I kind of threw a lot of changes at it without thoroughly making sure they'll be consistent with what the old values where, so if anyone wants to try it out on their more obscure setups please do.

Thanks @eryksun for the version->release tables from earlier - I used those.

I did just have the thought that I should probably update `sys.getwindowsversion()` to use `_wmi` (when it's available), which would mean I could revert a lot of the `platform` changes. But that's for another night

**Comment by zooba** [comment]
The fix for this (not including `getwindowsversion()`) has been merged for 3.12, but should probably be considered for 3.11 and 3.10 as well.

I don't think it's important enough to hold up 3.11.0, so we'd be looking at 3.11.1. And we just missed 3.10.7, so no rush for 3.10.8. But I'll leave this open until the backports are done.

**Comment by vstinner** [comment]
Because of the side effects of the calling the _wmi module, I would prefer to only target Python 3.12. I would prefer to get more feedback to see if everything goes well. It's too late to add new feateures to Python 3.11.

The workaround on older Python versions is to run the ``ver`` command, as done by test.pythoninfo: see collect_windows().

**Comment by zooba** [comment]
Fair enough, consider this closed.

**Comment by vstinner** [comment]
Thanks for fixing this issue, it's good to have an easy way to retrieve the real Windows version ;-)

Maybe _wmi can be used for other purposed later. Maybe we can expose it somehow later.

**Comment by v-python** [comment]
Why shell out or use _wmi rather than the registry   HKLM\software\Microsoft\windows nt\CurrentVersion    ProductName

**Comment by zooba** [comment]
Because the registry key is unsupported and primarily for compatibility reasons.

Also, for example, the value of `ProductName` on my Windows 11 machine is "Windows 10 Enterprise", which is exactly the bug we were trying to fix here.

The `platform` module is intended to get true information, not compatibility shims.
