### ISSUE TITLE
Junction/symbolic folder access error on Windows 11

### ISSUE THREAD

**Issue by 27d2690e-605f-4164-831f-c363d7e2af51** [python/cpython#89873]
BPO | [45710](https://bugs.python.org/issue45710)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @zware, @eryksun, @zooba, @fstorino

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-11-07.16:47:47.052>
created_at = <Date 2021-11-04.10:57:57.548>
labels = ['3.10', 'type-bug', '3.9', 'OS-windows']
title = 'Junction/symbolic folder access error on Windows 11'
updated_at = <Date 2021-11-07.16:47:47.050>
user = 'https://github.com/fstorino'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-07.16:47:47.050>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2021-11-07.16:47:47.052>
closer = 'eryksun'
components = ['Windows']
creation = <Date 2021-11-04.10:57:57.548>
creator = 'fstorino'
dependencies = []
files = []
hgrepos = []
issue_num = 45710
keywords = []
message_count = 6.0
messages = ['405677', '405743', '405838', '405848', '405905', '405909']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'fstorino']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45710'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by Andrej730** [comment]
Met this issue too. 

Just to document if it can help someone.
Met this issue working with Blender installed from MS Store (it has it's own Python instance). I've got a symlink at path `C:\\Users\\xxx\\AppData\\Roaming\\Blender # Foundation\\Blender\\4.3\\extensions\\.local\\lib\\python3.11\\site-packages\\ifcopenshell` leading to a path on a different drive `L:\\ifcopenshell` and `os.stat` for it resulted in `The create operation failed because the name contained at least one mount point which resolves to a volume to which the specified device object is not attached: C:\\Users\\xxx\\AppData\\Roaming\\Blender # Foundation\\Blender\\4.3\\extensions\\.local\\lib\\python3.11\\site-packages\\ifcopenshell'`. 

Redirecting the symlink from `L:\\ifcopenshell` to `C:\\ifcopenshell` helps. If symlink located not in AppData but in just let's say `C:\\Users\\xxx\\ifcopenshell` also helps.

Issue can be easily reproduced using Python from MS Store.

**Comment by zooba** [comment]
Those are the exact steps that I tried, though perhaps you mean something different in this step than I interpreted it as?

> 3\. Symlink them to your `C:\Users\xxxx\Appdata` as `folder_c` and `folder_l` and also to `C:\Users\xxxx\`

> > As a general rule, putting something called `.local` under `Roaming` is probably a bad idea.
> 
> Why?

`Roaming` gets automatically synchronised to any other machine where the user logs in and installs the app. `.local` implies that it shouldn't. Now in this case, it might be right, but it's really intended for settings. I don't remember exactly how much space is allowed per app or what happens when it's full, but for Blender I'd expect a list of addins to be synchronised rather than the addin code itself.

**Comment by Andrej730** [comment]
> Those are the exact steps that I tried, though perhaps you mean something different in this step than I interpreted it as?
> 
> > 3. Symlink them to your `C:\Users\xxxx\Appdata` as `folder_c` and `folder_l` and also to `C:\Users\xxxx\`

I use [Link Shell Extension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html), select `folder_c` -> "Pick Link Source", then go to the folder where I need a symlink, open context menu, "Drop As" -> "Symbolic Link".

Though I've just tried it on a different machine with Windows 10 (I have Windows 11 on mine) and couldn't reproduce on it, so it is somehow environment dependent.

**Comment by zooba** [comment]
I wonder if there's something special about your `L` drive? Maybe it's networked or a non-native filesystem that relies on some other service?

**Comment by Andrej730** [comment]
> I wonder if there's something special about your `L` drive? Maybe it's networked or a non-native filesystem that relies on some other service?

C and L are using different SSDs.
