### ISSUE TITLE
Incorrect "Perhaps you forgot a comma" hint

### ISSUE THREAD

**Issue by f2044c74-2589-491b-aea5-3f64941d4a9c** [python/cpython#89959]
BPO | [45801](https://bugs.python.org/issue45801)
--- | :---
Nosy | @aroberge, @lysnikolaou, @pablogsal

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-11-13.21:09:49.516>
created_at = <Date 2021-11-13.17:00:06.073>
labels = ['interpreter-core', 'invalid', '3.10', '3.11']
title = 'Incorrect "Perhaps you forgot a comma" hint'
updated_at = <Date 2021-11-13.21:09:49.515>
user = 'https://github.com/aroberge'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-13.21:09:49.515>
actor = 'pablogsal'
assignee = 'none'
closed = True
closed_date = <Date 2021-11-13.21:09:49.516>
closer = 'pablogsal'
components = ['Parser']
creation = <Date 2021-11-13.17:00:06.073>
creator = 'aroberge'
dependencies = []
files = []
hgrepos = []
issue_num = 45801
keywords = []
message_count = 4.0
messages = ['406287', '406292', '406295', '406298']
nosy_count = 3.0
nosy_names = ['aroberge', 'lys.nikolaou', 'pablogsal']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue45801'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by diegorego514** [comment]
Hey @pablogsal do you know why i am getting this error?

**Comment by diegorego514** [comment]
File "/home/diegorego/main.py", line 13
    @Bot.message (hello, inp how is your day?)
                         ^^^^^^^^^^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?

**Comment by itamaro** [comment]
hello @diegorego514, please direct question to the Python Help forum here: https://discuss.python.org/c/help/7

this repository is intended for reporting issues in CPython itself, and in any case, adding a tangentially related question to an issue that was closed 3 years ago is unlikely to be effective.
before asking that question though, I suggest trying wrapping the string in quotes so it's treated as a string (I'm assuming that's what expected in the snippet you pasted, based on nothing but intuition, since you didn't provide any context).

**Comment by diegorego514** [comment]
Hello! @itamaro So... i decided to give up because that code isn't mine. 
and if i wanted to code i will have to do everything from the very beginning.
