### ISSUE TITLE
There's no readline module on Windows Python (cmd.Cmd)

### ISSUE THREAD

**Issue by 01ba33e6-314a-47c2-b134-633dff387c63** [python/cpython#90028]
BPO | [45870](https://bugs.python.org/issue45870)
--- | :---
Nosy | @gvanrossum, @rhettinger, @terryjreedy, @eryksun, @zooba, @keeely, @E3V3A
Files | <li>[cmd_shell_example.py](https://bugs.python.org/file50461/cmd_shell_example.py "Uploaded as text/plain at 2021-11-29.10:49:57 by @keeely"): Script to demo use of readline module with cmd</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-22.13:51:22.349>
labels = ['type-bug', 'library', '3.10']
title = "There's no readline module on Windows Python (cmd.Cmd)"
updated_at = <Date 2022-02-02.16:23:35.559>
user = 'https://github.com/keeely'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-02.16:23:35.559>
actor = 'E3V3A'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-11-22.13:51:22.349>
creator = 'keeely'
dependencies = []
files = ['50461']
hgrepos = []
issue_num = 45870
keywords = []
message_count = 16.0
messages = ['406778', '406800', '407118', '407162', '407164', '407168', '407169', '407172', '407174', '407176', '407177', '407178', '407180', '407258', '407261', '412372']
nosy_count = 7.0
nosy_names = ['gvanrossum', 'rhettinger', 'terry.reedy', 'eryksun', 'steve.dower', 'keeely', 'E3V3A']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue45870'
versions = ['Python 3.10']
```

</p></details>

**Comment by keeely** [comment]
It took me a while to try the new pyreadline3 module, because I had settled into using WSL2 on Windows.  However I can now report it ticks all the boxes for me and is viable.

It's a bit of a shame it has to be pyreadline3 and we can't somehow give it the simpler name.  It may also be nice if the Python docs gave an indication that this should be used, saving people a visit to pyreadline github, and figuring out it won't work from the issue tracker there.

One thing I noted is that pyreadline3 is missing the append_history_file() function, giving it something in common with the libedit based readline shipped with Mac, so I needed a minor change to my readline detection code to sort that but it's not a big deal.

From my POV this can be closed.

**Comment by gvanrossum** [comment]
Are you interested in submitting a docs PR to link to pyreadline3?

**Comment by keeely** [comment]
I'm afraid not, see: https://github.com/python/cpython/issues/90028#issuecomment-1093938372
