### ISSUE TITLE
Pdb can't use the commands through -c or .pdbrc files

### ISSUE THREAD

**Issue by c3727ede-57cf-4491-8744-e370cacc0034** [python/cpython#90095]
BPO | [45937](https://bugs.python.org/issue45937)
--- | :---
Nosy | @Zrincet

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-11-30.03:36:50.577>
labels = ['3.8', 'library']
title = "Pdb can't use the commands through -c or .pdbrc files"
updated_at = <Date 2021-11-30.03:36:50.577>
user = 'https://github.com/Zrincet'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-30.03:36:50.577>
actor = 'Zrincet'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-11-30.03:36:50.577>
creator = 'Zrincet'
dependencies = []
files = []
hgrepos = []
issue_num = 45937
keywords = []
message_count = 1.0
messages = ['407350']
nosy_count = 1.0
nosy_names = ['Zrincet']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue45937'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-110496
* gh-116660
* gh-116661
* gh-116834
* gh-116854
* gh-116855

**Comment by dennisvang** [comment]
It looks like the `end` command is not properly handled when reading from `.pdbrc` file.

Here's a test that reproduces the issue. This is an adaptation of [test_readrc_kwarg][2], to be placed in [test_pdb.py][1]:

```python
class PdbTestCase(unittest.TestCase):
    ...

    def test_issue90095(self):
        script = textwrap.dedent("""
            import pdb; pdb.Pdb(readrc=True).set_trace()
            
            print('hello')
        """)

        pdbrc = textwrap.dedent("""
            # set breakpoint
            b 3
            # specify commands to execute at breakpoint
            commands 1
            end
            # continue to first breakpoint
            continue
            # quit pdb
            quit
        """)

        save_home = os.environ.pop('HOME', None)
        try:
            with os_helper.temp_cwd():
                with open('.pdbrc', 'w') as f:
                    f.write(pdbrc)

                with open('main.py', 'w') as f:
                    f.write(script)

                cmd = [sys.executable, 'main.py']
                proc = subprocess.Popen(
                    cmd,
                    stdout=subprocess.PIPE,
                    stdin=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                )
                with proc:
                    stdout, stderr = proc.communicate(b'q\n')
                    self.assertNotIn(
                        b"NameError: name 'end' is not defined",
                        stdout)

        finally:
            if save_home is not None:
                os.environ['HOME'] = save_home

```

[1]: https://github.com/python/cpython/blob/main/Lib/test/test_pdb.py
[2]: https://github.com/python/cpython/blob/5c110d112600b679b4cf41b11d2b73653da60555/Lib/test/test_pdb.py#L1739

**Comment by dennisvang** [comment]
Here's one attempt at fixing (part of) the issue. At least this passes the test defined above.

It probably doesn't cover all use cases, but perhaps it's a start.

```python
class Pdb(bdb.Bdb, cmd.Cmd):
    ...

    def execRcLines(self):
        if not self.rcLines:
            return
        # local copy because of recursion
        rcLines = self.rcLines
        rcLines.reverse()
        # execute every line only once
        self.rcLines = []
        while rcLines:
            line = rcLines.pop().strip()
            if line and line[0] != '#':
+               # START collect commands
+               _commands_terminators = [
+                   'end',
+                   'continue', 'cont', 'c',
+                   'step', 's',
+                   'next', 'n',
+                   'return', 'r',
+                   'jump', 'j',
+                   'quit', 'q',
+               ]
+               if line.startswith('commands'):
+                   com = ''
+                   while com not in _commands_terminators:
+                       com = rcLines.pop().strip()
+                       self.cmdqueue.append(com)
+               # END collect commands
                if self.onecmd(line):
                    # if onecmd returns True, the command wants to exit
                    # from the interaction, save leftover rc lines
                    # to execute before next interaction
                    self.rcLines += reversed(rcLines)
                    return True
```

Not sure if I interpreted the following section from the [docs][1] correctly:

> Specifying any command resuming execution (currently [continue](https://docs.python.org/3/library/pdb.html#pdbcommand-continue), [step](https://docs.python.org/3/library/pdb.html#pdbcommand-step), [next](https://docs.python.org/3/library/pdb.html#pdbcommand-next), [return](https://docs.python.org/3/library/pdb.html#pdbcommand-return), [jump](https://docs.python.org/3/library/pdb.html#pdbcommand-jump), [quit](https://docs.python.org/3/library/pdb.html#pdbcommand-quit) and their abbreviations) terminates the command list (as if that command was immediately followed by end). ...

[1]: https://docs.python.org/3/library/pdb.html#pdbcommand-commands

**Comment by dennisvang** [comment]
The above doesn't quite cut it: commands resuming execution are not executed.

Perhaps something like this would do it:

```python
+ _resume_commands = [
+     'continue', 'cont', 'c', 'step', 's', 'next', 'n', 'return', 'r', 'jump', 'j', 'quit', 'q'
+ ]

...

class Pdb(bdb.Bdb, cmd.Cmd):
    ...

    def execRcLines(self):
        if not self.rcLines:
            return
        # local copy because of recursion
        rcLines = self.rcLines
        rcLines.reverse()
        # execute every line only once
        self.rcLines = []
        while rcLines:
            line = rcLines.pop().strip()
            if line and line[0] != '#':
+               # START collect commands
+               if line.startswith('commands'):
+                   while True:
+                       com = rcLines.pop().strip()
+                       if com == 'end':
+                           break
+                       self.cmdqueue.append(com)
+                       if com in _resume_commands:
+                           break
+               # END collect commands
                if self.onecmd(line):
                    # if onecmd returns True, the command wants to exit
                    # from the interaction, save leftover rc lines
                    # to execute before next interaction
                    self.rcLines += reversed(rcLines)
                    return True

```

**Comment by Delengowski** [comment]
Would I be able to get some clarification if this is even supposed to be possible? I myself had a desire to do this and have performed the necessary setup to make an attempt at making this possible but given the long standing stack overflow post about this, I'm not sure if this is even a bug or not.

https://stackoverflow.com/questions/2013698/commands-for-breakpoints-in-a-pdbrc-file

**Comment by gaogaotiantian** [comment]
This is fixed now, you can define any commands/aliases in `.pdbrc` as you want.

**Comment by Zrincet** [comment]
> This is fixed now, you can define any commands/aliases in `.pdbrc` as you want.

Just wanted to drop a quick thank you for fixing this bug that's been lurking around for ages. Huge relief to see it finally squashed!

**Comment by wbolster** [comment]
👋🏼 hello @gaogaotiantian @iritkatriel,

it seems the change to fix this bug (https://github.com/python/cpython/pull/110496 and its backports) broke `.pdbrc` with comment lines in them, resulting in `SyntaxError` whenever they're encountered.

for example, a `.pdbrc` file like this:

```
# pretty-print often used expressions:
alias pl pp locals()  # ‘print locals’
alias pv pp vars(%*)  # ‘print vars’
```

… works fine on 3.12.2:

```
$ PYENV_VERSION=3.12.2 python -c 'breakpoint()'
--Return--
> <string>(1)<module>()->None
(Pdb) 
```

but the `3.12` branch with the change backported (https://github.com/python/cpython/pull/116661) fails:

```
$ PYENV_VERSION=3.12-dev python -c 'breakpoint()'
--Return--
*** SyntaxError: invalid syntax
*** SyntaxError: invalid syntax
(Pdb) 
```

comment lines in `.pdbrc` files are widely used, and even the stdlib docs include an example using them.

so this is clearly a regression. since this is really recent (unreleased) change, i didn't bother to open a new bug report for it (which would require adding a lot of context)

**Comment by wbolster** [comment]
as for a fix, this seems to do to the trick:

```
diff --git Lib/pdb.py Lib/pdb.py
index fd73f14a7e..7a9be7e5cf 100755
--- Lib/pdb.py
+++ Lib/pdb.py
@@ -297,7 +297,7 @@ def setup(self, f, tb):
         self.curframe_locals = self.curframe.f_locals
 
         if self.rcLines:
-            self.cmdqueue = self.rcLines
+            self.cmdqueue = [line for line in self.rcLines if not line.lstrip().startswith("#")]
             self.rcLines = []
 
     # Override Bdb methods
```

alternatively, actually allowing `# ...` commands (as a no-op) would also work, and would avoid this situation:

```
(Pdb) # test
*** SyntaxError: invalid syntax
```

**Comment by iritkatriel** [comment]
Thanks. I reopened this and marked as blocker so we won't forget to fix it.

**Comment by gaogaotiantian** [comment]
Okay this is my fault. The logic was there but somehow I ignored it.

However, when I took a deeper look at this issue, it's actually more complicated.

The only documentation for `.pdbrc` is this:

> If a file .pdbrc exists in the user’s home directory or in the current directory, it is read with 'utf-8' encoding and executed **as if it had been typed at the debugger prompt.** This is particularly useful for aliases. If both files exist, the one in the home directory is read first and aliases defined there can be overridden by the local file.

So the current behavior is **correct** (in the way that it aligns to the documentation). If you type `# comment` in `pdb` in 3.12, that reports syntax error. Thus if you put comments in `.pdbrc` file, it should report syntax error.

However, this current behavior is not desirable as there are already `.pdbrc` files that contain comments in the world (our documentation even used it). The "bug fix" is actually also a "breaking change". Also it would be useful to have comments in `.pdbrc` file.

Oh, and this is accidentally fixed in 3.13 because we used `codeop.compile_command` to compile instead of raw `compile`, which checks for comments and returns a no-op code object. So it's not an issue for main.

Here are the options for 3.12:
1. Allow comments as pdb commands (we have multiple ways to do it)
2. Keep the original behavior, not allow comments as command, but allow it to exist in `.pdbrc` file
3. (maybe not ideal) Keep the current "correct" behavior and break user code
4. (optional) Document `.pdbrc` correctly in all versions

Comments are actually easier, empty line is a totally different issue - they have meanings in `pdb`. If you type enter directly without any input (empty line), that means "repeat last command". How are we going to deal with that in `.pdbrc` file? Do we ignore it which contradicts our documentation (and deprived the user's ability to use it in `.pdbrc`), or do we respect it which could be unintuitive to many users?

In any case, we should have better documentation for `.pdbrc`.

**Comment by iritkatriel** [comment]
Let's not break 3.11 and 3.12. This is not a bugfix that we would backport (it's not a bug that hurts people, while the fix might).
So either fix or revert.

Doc updates are fine for all versions of course.

**Comment by gaogaotiantian** [comment]
I'll patch 3.11 and 3.12 so the behavior is consistent as before (ignore comments and empty lines in `.pdbrc`). The question is - do we want to do the same in 3.13, or we want a different behavior? If we want this behavior on all versions, I'll fix 3.13 and backport, otherwise I'll patch 3.12 and 3.11 separately.

The actual question left (if we fix docs separately) - how we deal with empty lines in `.pdbrc` in the future. Do we ignore them, or do we consider them as a "repeat". We should document them either way but this is a design decision we need to make. It seems like ignoring might be more intuitive.

**Comment by wbolster** [comment]
good point about the empty lines, didn't think of that. my suggested quick fix can be easily adapted to that of course.

i firmly believe they should be treated as no-op in a pdbrc file, i.e. treat them the same as comments.

it's rather common to collect various snippets (e.g. copy-pasted from stack overflow) in a .pdbrc, and have empty lines between them.

i think this is how it worked before, so let's not break that, similar to comment lines.

**Comment by iritkatriel** [comment]
Maybe change 3.13 too, and update the docs to match behaviour. (Doesn't seem like there's a benefit in changing this.)

**Comment by gaogaotiantian** [comment]
Okay I'll do a PR to keep the consistency of the behavior and update the docs (in a way that can be applied to 3.12 and 3.11 as well because no behavior is changed).

**Comment by gaogaotiantian** [comment]
Okay we restored the behavior for 3.12 and 3.11, and we also updated the docs to clarify the behavior of `.pdbrc`. I'll close this. Let us know if there are more stuff to do for the matter.

**Comment by wbolster** [comment]
wow, that was quick. thanks 🙏🏼
