### ISSUE TITLE
add pathlib.Path.walk method

### ISSUE THREAD

**Issue by 42fc2dd9-6fa5-4dc5-a454-a1f31c5f3007** [python/cpython#90385]
BPO | [46227](https://bugs.python.org/issue46227)
--- | :---
Nosy | @merwok, @barneygale, @ajoino, @Ovsyanka83
PRs | <li>python/cpython#30340</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-02.18:34:12.724>
labels = ['type-feature', 'library', '3.11']
title = 'add pathlib.Path.walk method'
updated_at = <Date 2022-01-08.12:58:28.255>
user = 'https://github.com/Ovsyanka83'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-08.12:58:28.255>
actor = 'Ovsyanka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-01-02.18:34:12.724>
creator = 'Ovsyanka'
dependencies = []
files = []
hgrepos = []
issue_num = 46227
keywords = ['patch']
message_count = 4.0
messages = ['409511', '409514', '409994', '410098']
nosy_count = 4.0
nosy_names = ['eric.araujo', 'barneygale', 'ajoino', 'Ovsyanka']
pr_nums = ['30340']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46227'
versions = ['Python 3.11']
```

</p></details>

**Comment by Ovsyanka83** [comment]
The discussion ended on the following decisions:
* The original solution was based on wrapping os.walk but we have decided that it will be both faster and better in the long term to reimplement it (though I was not able to come up with any implementation that is significantly better than that of os.walk so it's 99% the same)
* The original solution was yielding a tuple[Path, list[Path], list[Path]] but we decided to stay true to the original implementation and yield tuple[Path, list[str], list[str]]. It is both better in terms of optimization and should cause a little less confusion to the users
* The original solution had the same arguments as os.walk but the interface was too convoluted so: we decided to rename arguments to snake-case and I decided to remove topdown argument by splitting walk into two methods. So we get walk() and walk_bottom_up().  I.e. Now we get two methods instead of one but with two modes of operation. The naming of methods is up to discussion because I myself am not very happy with these names but those are the best I found

**Comment by brettcannon** [comment]
The views on the change seem generally positive and the API seems like it makes sense, so I'm inclined to accept the change once the PR passes review.

**Comment by tiran** [comment]
GH-92517 broke tests on wasm32-wasi platform.

```
======================================================================
FAIL: test_walk_symlink_location (test.test_pathlib.WalkTests.test_walk_symlink_location)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Lib/test/test_pathlib.py", line 2626, in test_walk_symlink_location
    self.assertIn("link", files)
AssertionError: 'link' not found in ['tmp3']
----------------------------------------------------------------------
Ran 458 tests in 1.229s
FAILED (failures=1, skipped=182)
test test_pathlib failed
```

**Comment by Ovsyanka83** [comment]
@tiran I apologize for introducing this problem and I am really thankful for resolving it, especially so quickly!

**Comment by merwok** [comment]
No worry!  We all forgot to run the PR through buildbots before merging, so let’s just do that next time.

**Comment by brettcannon** [comment]
It's also partially my fault by forgetting that WASI doesn't support symlinks and thus to have you add the test guard for those sorts of platforms.

**Comment by Ovsyanka83** [comment]
By the way, are we adding this PR into what's new? Or is it only gonna be a part of backlog? Seems big enough for what's new

**Comment by brettcannon** [comment]
@Ovsyanka83 it should end up in What's New. If you would like to write a PR for that I will happily review it. We also go through the changelog before release to make sure everything relevant ends up in there, so we don't have to worry about it being missed.
