### ISSUE TITLE
string.Template should allow inspection of identifiers

### ISSUE THREAD

**Issue by 7a497151-d6e0-489a-9dd8-822e43316bd7** [python/cpython#90465]
BPO | [46307](https://bugs.python.org/issue46307)
--- | :---
Nosy | @warsaw, @serhiy-storchaka, @miss-islington, @benkehoe
PRs | <li>python/cpython#30493</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-12.22:12:21.559>
created_at = <Date 2022-01-08.20:12:29.789>
labels = ['type-feature', 'library', '3.11']
title = 'string.Template should allow inspection of identifiers'
updated_at = <Date 2022-01-12.22:12:21.559>
user = 'https://github.com/benkehoe'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-12.22:12:21.559>
actor = 'AlexWaygood'
assignee = 'none'
closed = True
closed_date = <Date 2022-01-12.22:12:21.559>
closer = 'AlexWaygood'
components = ['Library (Lib)']
creation = <Date 2022-01-08.20:12:29.789>
creator = 'ben11kehoe'
dependencies = []
files = []
hgrepos = []
issue_num = 46307
keywords = ['patch']
message_count = 11.0
messages = ['410112', '410127', '410128', '410129', '410131', '410144', '410148', '410172', '410174', '410175', '410322']
nosy_count = 4.0
nosy_names = ['barry', 'serhiy.storchaka', 'miss-islington', 'ben11kehoe']
pr_nums = ['30493']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46307'
versions = ['Python 3.11']
```

</p></details>

**Comment by jgiacobbi** [comment]
I have a use case that has been made more complicated by the decision not to list identifiers with duplicates. I am substituting identifiers with capture groups to match output strings. Since `re` does not allow repeated named capture groups, I have to use unnamed capture groups and match them to their identifiers after the fact. So that leaves three cases:

1. No repeats, i.e. `len(groups) == len(ids)`
2. Repeats in the template but not the groups, so deduplicating the capture groups matches the template since they are both in order
3. The worst case, repeats in the capture group contents that could fit into more than one identifier and are not actually duplicates.

If the identifiers were listed naively then every case would be case 1.

This is the code I have to work around this problem:
```
    def parse_groups(self, groups: tuple[str]) -> dict[str, str]:
        ids = self.template.get_identifiers()
        if len(ids) == len(groups):
            return dict(zip(ids, groups))

        # fastest way to dedup and preserve order in 3.7+
        unique = list(dict.fromkeys(groups))
        if len(ids) == len(unique):
            return dict(zip(ids, unique))

        known = set()
        matched = {}

        found = iter(groups)

        # ids and groups are in the order found in the string being matched
        # duplicates can be skipped, but sometimes a duplicate isn't a duplicate,
        # ex. (\d{2})/(\d{2}) - 15/15 - hour/minute
        for id in ids:
            try:
                while value := next(found):
                    if re.match(self.patterns[id], value):
                        matched[id] = value
                        known.add(value)
                        break
                    elif value in known:
                        break  # skip duplicates
            except StopIteration:
                break

        if len(ids) == len(matched):
            return matched
```

The pull request to change this behavior is simple and obvious, but I haven't made it because I have questions
1. Am I just wrong? Is there an easy way to do this that I am overlooking?
2. Is there a good reason not to leave it up to the consumer if they want to convert to a set or an ordered set? Doing it for them destroys information.
3. If both use cases are valuable then why not support both?
