### ISSUE TITLE
urllib.parse: Allow more flexibility in schemes and URL resolution behavior

### ISSUE THREAD

**Issue by 820fbe17-d578-407e-9c58-7c9ea4773669** [python/cpython#90495]
BPO | [46337](https://bugs.python.org/issue46337)
--- | :---
Nosy | @orsenthil, @merwok, @karlcow, @ethanfurman, @ambv, @lincolnauster
PRs | <li>python/cpython#30520</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-10.21:50:56.334>
labels = ['type-bug', 'library', '3.11']
title = 'urllib.parse: Allow more flexibility in schemes and URL resolution behavior'
updated_at = <Date 2022-04-04.03:47:32.421>
user = 'https://github.com/lincolnauster'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-04.03:47:32.421>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-01-10.21:50:56.334>
creator = 'lincolnauster'
dependencies = []
files = []
hgrepos = []
issue_num = 46337
keywords = ['patch']
message_count = 11.0
messages = ['410259', '413066', '413084', '413123', '413139', '413314', '416369', '416462', '416463', '416464', '416633']
nosy_count = 6.0
nosy_names = ['orsenthil', 'eric.araujo', 'karlcow', 'ethan.furman', 'lukasz.langa', 'lincolnauster']
pr_nums = ['30520']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46337'
versions = ['Python 3.11']
```

</p></details>

**Comment by lincolnauster** [comment]
@orsenthil any udpates? I'd like to continue with this PR as soon as is convenient :)

**Comment by orsenthil** [comment]
Hi @lincolnauster , I was -1 and was thinking much on introducing a flag with the enum in the parse module.

```
urlparse(url, scheme='', allow_fragments=True, flags=SchemeFlag(0)):
```

This API signature is going to confuse people and will be huge blocker for further adoption and change (even if the default arguments are specified).  I was thinking how best to mitigate that.

1. Did we ever consider not going to flag as as parameter?
2. Any other default for the flag rather than an enum?

I am going to paste this comment on the PR too, and we could continue the discussion there. If design design required, we can bring it to a wider forum too.

**Comment by orsenthil** [comment]
This is closed with wont fix (at least for the implementation suggested in this PR - https://github.com/python/cpython/pull/30520) - A simpler approach if suggested by a new issue can be considered.
