### ISSUE TITLE
multiprocessing's "spawn" doesn't actually use spawn

### ISSUE THREAD

**Issue by 20b13c20-bc9c-43ca-8fb6-9d24ce334500** [python/cpython#90525]
BPO | [46367](https://bugs.python.org/issue46367)
--- | :---
Nosy | @vstinner, @jakirkham

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-13.19:20:59.356>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'multiprocessing\'s "spawn" doesn\'t actually use spawn'
updated_at = <Date 2022-01-15.00:10:58.327>
user = 'https://github.com/jakirkham'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-15.00:10:58.327>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-01-13.19:20:59.356>
creator = 'jakirkham'
dependencies = []
files = []
hgrepos = []
issue_num = 46367
keywords = []
message_count = 2.0
messages = ['410512', '410612']
nosy_count = 2.0
nosy_names = ['vstinner', 'jakirkham']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46367'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by gpshead** [comment]
> Oh, about multiprocessing. Well, someone has to propose a patch! I don't know why multiprocessing uses directly _posixsubprocess.fork_exec() rather than the subprocess module. It's also a complex module with many specific constraints.

History. multiprocessing had to get rid of its original os.fork() based Python code as that is unsafe, so it reached into 3.2's _posixsubprocess to use its posix async signal safe fork+exec implementation (which is often vfork+exec in recent Pythons).

Changing what multiprocessing uses to launch new interepreters for `spawn` and the `forkserver` process will require someone willing to dive into its specific internal needs to see if a posix_spawn codepath could be used.

**Comment by gpshead** [comment]
Closing this as not planned. the multiprocessing start methods are names of techniques, not specific API calls.  "spawn" is merely a verb used to indicate that a new python interpreter is invoked for each process.

We're not going to change the behavior of the multiprocessing API because the name of a term it used doesn't happen to coincedentially match part of the name of one variety of API call available only on a subset of platforms.

A new start method that explicitly used the posix_spawn API could be added (file a new feature request and provide a PR). I don't know why anyone would actually want this.

Documentation could be updated to explicitly mention that "spawn" doesn't indicate the system call being used. But the existing text in https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods seems quite clear to me.
