### ISSUE TITLE
TimedRotatingFileHandler "midnight" misleading when interval > 1

### ISSUE THREAD

**Issue by ee7b86dc-d023-43e2-b2f6-ba38ad409e66** [python/cpython#90535]
BPO | [46377](https://bugs.python.org/issue46377)
--- | :---
Nosy | @vsajip
PRs | <li>python/cpython#30599</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-14.13:50:48.156>
labels = ['type-feature', 'library', '3.11']
title = 'TimedRotatingFileHandler "midnight" misleading when interval > 1'
updated_at = <Date 2022-01-14.18:25:21.751>
user = 'https://bugs.python.org/mschiess'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-14.18:25:21.751>
actor = 'mschiess'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-01-14.13:50:48.156>
creator = 'mschiess'
dependencies = []
files = []
hgrepos = []
issue_num = 46377
keywords = ['patch']
message_count = 5.0
messages = ['410558', '410565', '410567', '410571', '410583']
nosy_count = 3.0
nosy_names = ['vinay.sajip', 'python-dev', 'mschiess']
pr_nums = ['30599']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46377'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-98099
* gh-116220
* gh-116892
* gh-116893

**Comment by serhiy-storchaka** [comment]
I see now that the problem is that `computeRollover()` returns the next nearest "midnight" time, ignoring the `interval` parameter, while `doRollover()` computes the file name by stepping back `interval` days. And there is the same issue with the  weekly rotation.

My fix #116191 perhaps affected this issue and made it worse (if you do not consider it better). Previously, in `doRollover()`, if `computeRollover()` returned the current time, `self.interval` was added, so the next rollover time was set after `interval` days or weeks. But this behavior depended on `atTime` and the time of running the script.

Perhaps the safest way is to implement the correct support of the `interval` parameter for "midnight" and weekly rotation.
