### ISSUE TITLE
RFE: @dataclasses.dataclass(slots=True) doesn't support methods using zero-arg super()

### ISSUE THREAD

**Issue by b656d977-2b3d-484b-b318-8209d3128c21** [python/cpython#90562]
BPO | [46404](https://bugs.python.org/issue46404)
--- | :---
Nosy | @vstinner, @ericvsmith, @encukou, @ericsnowcurrently, @hynek, @Tinche, @frenzymadness, @sweeneyde

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-01-16.22:48:06.738>
labels = ['interpreter-core', 'type-feature', '3.11']
title = "RFE: @dataclasses.dataclass(slots=True) doesn't support methods using closures"
updated_at = <Date 2022-03-28.15:16:37.392>
user = 'https://github.com/Tinche'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-28.15:16:37.392>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2022-01-16.22:48:06.738>
creator = 'tinchester'
dependencies = []
files = []
hgrepos = []
issue_num = 46404
keywords = []
message_count = 8.0
messages = ['410730', '410745', '411462', '415291', '415300', '415303', '416169', '416174']
nosy_count = 8.0
nosy_names = ['vstinner', 'eric.smith', 'petr.viktorin', 'eric.snow', 'hynek', 'tinchester', 'frenzy', 'Dennis Sweeney']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue46404'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-104038
* gh-107391
* gh-111538
* gh-119350
* gh-119351
* gh-124455
* gh-124692

**Comment by wookie184** [comment]
I had a go at implementing this, @ericvsmith @vstinner if you're able to take a look: https://github.com/python/cpython/pull/104038

Apologies if you were still planning on implementing this @frenzymadness, as you may have been still waiting for a go-ahead. Since this had stalled for a bit I figured a PR was the easiest way to try and push this forwards.

**Comment by carljm** [comment]
I updated the issue title to clarify that the problem here is specifically about the `__class__` cell, used by zero-arg `super()`, not about closures in general.

One observation about the proposed fix is that (because it modifies the contents of the cell in place) it "breaks" the original class, in case anyone had a reference to it, e.g. something like this:

```
class Orig:
    def method(self):
        return super().method()

SlotifiedDataclass = dataclass(slots=True)(Orig)
```

With the fix proposed above, `SlotifiedDataclass.method()` will now work, but `Orig.method()` will now be broken (it will have the wrong class in its `__class__` cell.)

Perhaps this is acceptable collateral damage, breaking a rare case in order to fix the more common case? But it could break currently-working code.

Even putting a new cell into the function's closure (rather than updating the cell content in place) wouldn't fix this, since the closure (and the function object itself) are also shared between the original and the new class. The only way to avoid it would be to make a new function object, using the same code object as the original one. But this is quite tricky given that the function object could be wrapped by arbitrary decorators etc.

So perhaps we just have to accept that in order to make the new slotified class fully functional, we have to break the old class.

If so, it still seems unfortunate that we have to go scrabbling through all the methods, hoping that at least one of them is not wrapped in a decorator we don't know how to introspect, so we can update the single cell that we actually need to update, just because Python hides it from us. I wonder if there's any reason the class cell shouldn't be left exposed as `__classcell__` in a class namespace, rather than deleted from the class namespace? Then this fix would be trivial: just get `OldClass.__classcell__` and update its contents.

All in all, this issue mostly makes me think that slots support via class-copying was a mistake. FWIW, there would be another option, also ugly in its own way: you can actually add slots to a class post-creation (in C code), but it's only safe to do so if you know that there aren't any instances of the class yet. This is proxy-detectable via the reference count, since every instance holds a reference to its class. So (via a C helper) we could add slots to the existing class, and error out if you try to make a slotified dataclass out of a class you've already somehow created instances of. This limitation seems arguably better than the more complex limitations arising from this issue.

**Comment by ericvsmith** [comment]
At the core sprint last year we discussed the "add slots if no instances have been created" proposal. I think it would be the preferred way to go, but I'm concerned about the impact on other python implementations.

**Comment by carljm** [comment]
> At the core sprint last year we discussed the "add slots if no instances have been created" proposal. I think it would be the preferred way to go, but I'm concerned about the impact on other python implementations.

I think the more general concept of "mark a class when its first instance is created" is reasonable to expect other implementations to be able to provide in some way? Even in CPython, if we found the refcount-based approach to be too subtle, we could pretty easily do a more explicit marker via type flag (though we may not prefer to spend a type flag on this.)

**Comment by wookie184** [comment]
> One observation about the proposed fix is that (because it modifies the contents of the cell in place) it "breaks" the original class

Since dataclasses normally work by modifying the class, and the new class generation is an (albeit leaked and documented) implementation detail, I think it's expected that using the old class isn't really supported. Either way, it's no more broken than the actual dataclass is currently, which I think is a fair trade in brokenness!

> If so, it still seems unfortunate that we have to go scrabbling through all the methods, hoping that at least one of them is not wrapped in a decorator we don't know how to introspect, so we can update the single cell that we actually need to update, just because Python hides it from us.

Yeah, it's a pretty ugly solution. I think it's an improvement on the status quo, given the cases where it doesn't work should be *fairly* uncommon, and avoidable, but it's certainly not perfect so better options are definitely worth considering.

> I wonder if there's any reason the class cell shouldn't be left exposed as __classcell__ in a class namespace, rather than deleted from the class namespace? Then this fix would be trivial: just get OldClass.__classcell__ and update its contents.

I'd also wondered this, although thought it would be a bit of a shame to have to add a new attribute *just* for this. Maybe it could be useful for other things though.

> FWIW, there would be another option, also ugly in its own way: you can actually add slots to a class post-creation (in C code), but it's only safe to do so if you know that there aren't any instances of the class yet. This is proxy-detectable via the reference count, since every instance holds a reference to its class. So (via a C helper) we could add slots to the existing class, and error out if you try to make a slotified dataclass out of a class you've already somehow created instances of. This limitation seems arguably better than the more complex limitations arising from this issue.

The no-instances constraint doesn't sound like an issue. I can't comment on impact on other implementations, but this does sound like the neatest solution from a user perspective.

**Comment by thejcannon** [comment]
Since it seems like the solutions here would be going into some later version of Python, can the python docs be updated to reflect this issue?

Otherwise, people may not understand why their code goes :boom: (took me a while before I put 2 and 2 together and found this issue).

**Comment by blhsing** [comment]
> One observation about the proposed fix is that (because it modifies the contents of the cell in place) it "breaks" the original class, in case anyone had a reference to it, e.g. something like this:
> 
> ```
> class Orig:
>     def method(self):
>         return super().method()
> 
> SlotifiedDataclass = dataclass(slots=True)(Orig)
> ```
> 
> With the fix proposed above, `SlotifiedDataclass.method()` will now work, but `Orig.method()` will now be broken (it will have the wrong class in its `__class__` cell.)

I've made a suggested fix to this particular issue in PR #111538 by creating a new cell for `__class__` instead of sharing the same cell with the old class. Can you help re-review the fix? Thanks!

**Comment by ericvsmith** [comment]
I have a code fix that I think addresses this. Not sure I can get it into 3.13, but I'll try.

**Comment by blhsing** [comment]
> I have a code fix that I think addresses this. Not sure I can get it into 3.13, but I'll try.

Thanks @ericvsmith. Can you let us know if you have started working on this, and which approach you plan on taking?

@carljm has helpfully reasoned through several options. Among them, adding slots to a class post-creation sounded awesome, until I realized that it's technically impossible to do because memory for member descriptors must be allocated at the time of type creation:
https://github.com/python/cpython/blob/15d48aea02099ffc5bdc5511cc53ced460cb31b9/Objects/typeobject.c#L3870

I therefore think exposing `__classcell__` is the easiest and most viable option. Don't think it can cause any harm either since it's documented that dunders are reserved so there should be no existing code base that uses `__classcell__`. If you haven't started working on this I can give this approach a shot.

**Comment by ericvsmith** [comment]
I have a mostly working version of a fix. I'll try to find it and post it here.

**Comment by loic-simon** [comment]
An issue I think is related: dataclasses cannot be generic (pre- or post-695) when using both `slots=True` and `frozen=True`:

```
>>> @dataclass(frozen=True, slots=True)
... class C[T]:
...     a: T
... 
>>> C[str]
__main__.C[str]
>>> C[str]("foo")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/3.12.1/lib/python3.12/typing.py", line 1142, in __call__
    result.__orig_class__ = self
    ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 5, in __setattr__
TypeError: super(type, obj): obj must be an instance or subtype of type
```

If the dataclass is only frozen or only slotted, no issue:
```
>>> @dataclass(frozen=True)
... class C[T]:
...     a: T
... 
>>> C[str]("foo")
C(a='foo')
```
```
>>> @dataclass(slots=True)
... class C[T]:
...     a: T
... 
>>> C[str]("foo")
C(a='foo')
```

Would this case be covered by your fix @ericvsmith? 🙏

**Comment by ericvsmith** [comment]
I'm not sure, but I'll check. I'm sprinting on it this week and will check this use case.

**Comment by ericvsmith** [comment]
@loic-simon : I can't duplicate this in an unmodified 3.12.3:

```pycon
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from dataclasses import dataclass
>>> @dataclass(frozen=True, slots=True)
... class C[T]:
...  a:T
... 
>>> C[str]
__main__.C[str]
>>> C[str]("foo")
C(a='foo')
```

**Comment by loic-simon** [comment]
Oh, indeed! I just checked in 3.12.2 and 3.12.3, this has apparently been fixed in 3.12.3, possibly by [GH-115165](https://github.com/python/cpython/issues/115165)?

Sorry for the noise anyway!

**Comment by ericvsmith** [comment]
No problem! I'll remove my test case for it.

**Comment by ericvsmith** [comment]
> Thanks @ericvsmith. Can you let us know if you have started working on this, and which approach you plan on taking or have taken?

And to actually answer this question: I'm basically going with the approach in #104038 of fixing up the closure cells. I'm still working through tests and corner cases, and looking at @carljm's comments in https://github.com/python/cpython/issues/90562#issuecomment-1529962640.

I talked to @markshannon at this year's PyCon, and he dissuaded me from the "can modify `__slots__` until an instance is created" approach.
