### ISSUE TITLE
create_autospec() doesn't respect configure_mock style kwargs

### ISSUE THREAD

**Issue by f53f4f3a-69bb-4581-a8a8-edeb4f4abde4** [python/cpython#90848]
BPO | [46690](https://bugs.python.org/issue46690)
--- | :---
Nosy | @cjw296, @voidspace, @lisroach, @mariocj89, @tirkarthi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-02-09.11:54:00.145>
labels = ['3.8', 'type-bug', 'library', '3.9', '3.10']
title = "create_autospec() doesn't respect configure_mock style kwargs"
updated_at = <Date 2022-02-10.13:44:04.417>
user = 'https://bugs.python.org/marchantjm'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-10.13:44:04.417>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-02-09.11:54:00.145>
creator = 'marchant.jm'
dependencies = []
files = []
hgrepos = []
issue_num = 46690
keywords = []
message_count = 2.0
messages = ['412898', '413001']
nosy_count = 6.0
nosy_names = ['cjw296', 'michael.foord', 'lisroach', 'mariocj89', 'xtreak', 'marchant.jm']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue46690'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-118163
* gh-118517

**Comment by infohash** [comment]
>
    if _is_instance_mock(mock):
        mock.configure_mock(**original_kwargs)

@tirkarthi We cannot configure child mock with **original `kwargs`** that were meant for parent mock because you will get attribute error if the attribute passed in **original `kwargs`** does not exist on the child object.

> But as we loop through the attributes and create new child mock for the attributes the original configured mock for the method that raises ValueError is overridden by another object without the configuration info

Yes. This is the line of code which is overriding the child of originally configured mock:
https://github.com/python/cpython/blob/ceb6038b053c403bed3ca3a8bd17b7e3fc9aab7d/Lib/unittest/mock.py#L2838-L2841

The line 2841 above 👆 is the one that is overriding the child. That `entry` already exists in `_mock_children` and we are reassigning a new child mock to it which is not pre-configured with `return_value` & `side_effect`. This is why when OP sets `side_effect` later in the code, it works.
