### ISSUE TITLE
Allow subclassing Any at runtime

### ISSUE THREAD

**Issue by hauntsaninja** [python/cpython#91154]
BPO | [46998](https://bugs.python.org/issue46998)
--- | :---
Nosy | @gvanrossum, @JelleZijlstra, @hauntsaninja, @Fidget-Spinner, @AlexWaygood
PRs | <li>python/cpython#31841</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-04-05.02:35:58.785>
created_at = <Date 2022-03-13.03:06:37.673>
labels = ['library', '3.11']
title = 'Allow subclassing Any at runtime'
updated_at = <Date 2022-04-05.02:35:58.784>
user = 'https://github.com/hauntsaninja'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-05.02:35:58.784>
actor = 'JelleZijlstra'
assignee = 'none'
closed = True
closed_date = <Date 2022-04-05.02:35:58.785>
closer = 'JelleZijlstra'
components = ['Library (Lib)']
creation = <Date 2022-03-13.03:06:37.673>
creator = 'hauntsaninja'
dependencies = []
files = []
hgrepos = []
issue_num = 46998
keywords = ['patch']
message_count = 3.0
messages = ['415023', '416720', '416721']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'JelleZijlstra', 'hauntsaninja', 'kj', 'AlexWaygood']
pr_nums = ['31841']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue46998'
versions = ['Python 3.11']
```

</p></details>

**Comment by superbobry** [comment]
I understand the rationale for this change, but it does complicate the type system in unspecified (and not fully understood ways). For example

* What does it mean to subclass `Any` in a) a generic class b) a protocol c) a `typing.NamedTuple` d) a typing.TypedDict`?
* Are `Any` subclasses plain subtypes of `Any`? Does this question even make sense?
* How do `Any` subclasses interact with `Any`? Are they consistent with `Any`? Are they consistent subtypes of `Any`?
* etc

I know it is too late to revert this in 3.11, but is there a chance we could revisit the decision to make `Any` subclassable and put together a deprecation plan, where this behavior ultimately is going away?

**Comment by JelleZijlstra** [comment]
We can always decide to change our mind and deprecate this feature, but that's putting the cart before the horse. Type checkers must support Any as a base class (it will come up if you inherit from a class in an untyped library), so the concept needs to be part of the type system somehow. Formalizing what subclassing Any means could be useful, but existing type checkers manage without it.

**Comment by superbobry** [comment]
Is there a better forum to continue this discussion? 

I'm not sure I understand why inheriting from `Any` is necessary in the type system. In my mind, inheriting from a class in an untyped library is very different. An untyped class is syntactically known to be a class, i.e. a static type, whereas `Any` is a gradual type.

**Comment by AlexWaygood** [comment]
> Is there a better forum to continue this discussion?

@superbobry I'm a little confused here, because this was a change to runtime behaviour, but your concern seems to be with whether type checkers should allow `Any` to be subclassed or not. Whether it's allowed at runtime or not is pretty tangential to that discussion -- there are lots of things that are allowed at runtime that aren't allowed by some or all type checkers, and that's how it should be. If you want to write a type checker that disallows `Any` from ever being subclassed, it's your right to do so (though it's not one that most type checkers have taken), but the decision we took here to change the runtime behaviour has little bearing on that.

Nonetheless, if you do want to argue that we should standardise the behaviour of _type checkers_ so that they always disallow subclassing `Any`, feel free to open an issue at https://github.com/python/typing or to start a thread on the typing-sig mailing list (https://mail.python.org/archives/list/typing-sig@python.org/).

**Comment by superbobry** [comment]
Thanks for chiming in @AlexWaygood!

My concern is that this change does not *just* affect the runtime behavior as type checkers will now observe `Any` subclasses in the source and will need to decide what to do with them.

I will follow up on typing-sig@.
