### ISSUE TITLE
math.isfinite() can raise exception when called on a number

### ISSUE THREAD

**Issue by d47afb43-3ef9-466e-80a2-bd09de11d97d** [python/cpython#91277]
BPO | [47121](https://bugs.python.org/issue47121)
--- | :---
Nosy | @tim-one, @rhettinger, @mdickinson, @stevendaprano, @serhiy-storchaka, @nathanielmanistaatgoogle

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-03-25.17:28:43.481>
labels = ['3.11', 'type-feature', 'docs']
title = 'math.isfinite() can raise exception when called on a number'
updated_at = <Date 2022-04-08.10:09:13.165>
user = 'https://bugs.python.org/tfish2'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.10:09:13.165>
actor = 'tfish2'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2022-03-25.17:28:43.481>
creator = 'tfish2'
dependencies = []
files = []
hgrepos = []
issue_num = 47121
keywords = []
message_count = 8.0
messages = ['416010', '416011', '416018', '416040', '416840', '416842', '416843', '416969']
nosy_count = 8.0
nosy_names = ['tim.peters', 'rhettinger', 'mark.dickinson', 'steven.daprano', 'docs@python', 'serhiy.storchaka', 'Nathaniel Manista', 'tfish2']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue47121'
versions = ['Python 3.11']
```

</p></details>

**Comment by nathanielmanistaatgoogle** [comment]
> Many tools in the math module are thin wrapper around libmath and we never intended to be universal handlers of all numeric types.

> `isfinite()` et alia were added to supply functions defined by current standards to work on IEEE floating-point values.

I came to this enhancement request wanting to contribute support for it, but these kinds of statements are the obstacle over which I'm currently stumbling. I _want_ it to be the case that given the `int` integer type built into the language and the standard library module named `math` that the two just work smoothly and intuitively together, producing correct results rather than raising a boundary-of-what-was-forecast-to-be-needed-was-reached `OverflowError`. I _want_ it to be the case that where there need to be sharp corners, special cases, caveats, and limits, that users have to deliberately opt into them by "reaching further" for the harder-to-use, less-readily-at-hand sharp-cornered system - `import floatmath` or `import ieee754math` or `from c_standard import mathlib_functions` or something like that. But obviously there's history here of which I hadn't before been aware, and I also can't pretend that `This module provides access to the mathematical functions defined by the C standard.` isn't currently the first sentence of the `math` module's documentation.

> Whoa there. You're venturing into changing what those math functions were all about and the core approach to how they operate.
>
> A zigzag to this new direction would need discussion with all the math folks.

Well, yeah. This issue definitely makes me wonder if that discussion would be worth having, and curious to what extent it may have been had before. (I wonder if you meant "the math folks" or "the `math` folks"? 😛 Assuming for the moment the latter...) That the module is in the standard library and has the unqualified name "math" places it "readily at hand" for all programmers and invites general use for general use cases. Given that, has anyone before asked "Is `This module provides access to the mathematical functions defined by the C standard.` really the right 'mission statement' for the module to continue to have?"?

> People working with floats have reasonable expectations that Python will supply workalikes for industry-stand float functions.

Agreed - but I'd hypothesize that "people working with floats" is likely only a subset of those who would add `import math` to their code. Just from its appearance alone `import math` looks like it can be expected to work for all kinds of math stuff, right? 🙂

> If was had to cater to all possible "numberish" types, we'd never add anything new again :-( Doing that in a principled way requires dedicated new dunder methods, and that's a high bar.

Agreed, and I suspect there's an opportunity here to let the perfect be the enemy of the good, and we oughtn't take advantage of that opportunity. I'd like to advocate that the `int`s built into the language work correctly with the `math` in the standard library, and I believe there's space to campaign for that without also arguing that all numeric types and all mathematical functions in all libraries and in all codebases additionally be made to behave well together.

**Comment by serhiy-storchaka** [comment]
A reasonable expectation is that if `math.isfinite(x)` does not fail, `math.atan(x)` should not fail either. If you make `math.isfinite()` not failing for `10**1000`, you will need to add similar changes in all functions which implicitly convert arguments to `float`. Otherwise you can break user's code.

There are also technical problems. The only general way of supporting arbitrary numbers in `math.isfinite()` is to introduce a special method `__isfinite__`. You will end with adding special methods for all `math` functions: `__sqrt__`, `__sin__`, etc. And *different* set of special methods for `cmath` functions: `__csqrt__`, `__csin__`, etc. It will negatively affect performance, because of additional lookup in dictionary and additional calls.

**Comment by rhettinger** [comment]
I concur with Tim that this is just an abstract purity nit and also with Serhiy that this doesn't make sense in light of how the other functions work.  I'll add that I don't see that any real user issue is being addresses here.  Mostly, this seems to be an "it bugs me" request rather than a "people need this" request.

Thanks for the suggestion, but we will decline.

**Comment by fischbacher** [comment]
Right now, the `math` documentation states:

===
https://docs.python.org/3/library/math.html#math.isfinite

Return True if x is neither an infinity nor a NaN, and False otherwise. (Note that 0.0 is considered finite.)

New in version 3.2.
===

Current behavior does not align with the documentation. This is by definition a bug.

There are multiple options for resolving this, one of them is keeping the current behavior and adjusting the documentation.
But a bug it is.

**Comment by serhiy-storchaka** [comment]
Does it return True for an infinity or a NaN? Does it return False for any x which is neither an infinity nor a NaN?

**Comment by fischbacher** [comment]
Does it show any behavior other than returning True or False on type-wise valid numerical input? Yes.

**Comment by fischbacher** [comment]
Perhaps I need to explain this more slowly.

https://docs.python.org/3/library/math.html#math.isfinite clearly says:
Return True if x is neither an infinity nor a NaN, and False otherwise. (Note that 0.0 is considered finite.)


The opposite of "Responds with True on X" is not "Responds with False on X", but "Fails to respond with True on X".

So, in small steps:

1. We can ignore the redundant. "Note that 0.0 is considered finite" statement.

2. The specification is logically equivalent to:
    "If x is an infinity or NaN, returns False. Otherwise returns True."

3. "Fails to follow this specification" is here *not* logically equivalent to:
    "Returns True if x is an infinity or NaN, OR returns False on other input."
    (as the comment above apparently thinks it would).
    (I feel a bit silly even having to explain this.)
    Rather, "fails to follow this specification" is logically equivalent to:
    "Fails to return True if x is an infinity or NaN, OR fails to return False on other input."

Is 10**1000 a real number? Pretty much so. PEP-484 even thinks this is a "float"(!)
Does math.isfinite() fail to return False on this number? That also holds.

So, does math.isfinite() violate its own documentation?

How can there be even a discussion about that?

There is of course some sort-of open issue around "what is valid input here"?
The very fact that this is not clarified is in itself a problem in the documentation that needs rectifying.
However, note that the beginning of https://docs.python.org/3/library/math.html states:

"These functions cannot be used with complex numbers."

This is a clear case of "exceptio probat regulam in casibus non exceptis" - the "complex numbers" are here mentioned as an exception to the not explicitly stated rule that these functions can process not-complex, i.e. real, input.
