### ISSUE TITLE
pip3.10.4 is configured with locations that require TLS/SSL, however the ssl module in Python is not available

### ISSUE THREAD

**Issue by 65f9a771-661b-45d0-b8c6-8626a8a9a022** [python/cpython#91357]
BPO | [47201](https://bugs.python.org/issue47201)
--- | :---
Nosy | @tiran

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-04-02.15:10:50.216>
labels = ['expert-installation', '3.10']
title = 'pip3.10.4 is configured with locations that require TLS/SSL, however the ssl module in Python is not available'
updated_at = <Date 2022-04-02.19:35:32.607>
user = 'https://bugs.python.org/alessandropioli'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-02.19:35:32.607>
actor = 'christian.heimes'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation']
creation = <Date 2022-04-02.15:10:50.216>
creator = 'alessandro.pioli'
dependencies = []
files = []
hgrepos = []
issue_num = 47201
keywords = []
message_count = 2.0
messages = ['416558', '416580']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'alessandro.pioli']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue47201'
versions = ['Python 3.10']
```

</p></details>

**Comment by jacoblapenna** [comment]
I have this same issue on Raspberry Pi OS. During `sudo make altinstall` I get:

```
Could not build the ssl module!                                                                                                                                                                                   Python requires a OpenSSL 1.1.1 or newer
```

Even though `openssl version` gives `OpenSSL 1.1.1n  15 Mar 2022`.

**Comment by tiran** [comment]
> I have this same issue on Raspberry Pi OS. During `sudo make altinstall` I get:

You are missing the OpenSSL development package. Install ``libssl-dev`` first.

**Comment by tiran** [comment]
Build dependencies are documented in the devguide, https://devguide.python.org/setup/#build-dependencies

**Comment by mkfcga** [comment]
OpenSSL 3.0.0 7 sep 2021 (Library: OpenSSL 3.0.0 7 sep 2021)
python 3.11.4 

WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /simple/pip/
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement pip (from versions: none)
ERROR: No matching distribution found for pip
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

**Comment by csipapicsa** [comment]
Any solution for this?

**Comment by mkfcga** [comment]
first install openssl:

sudo yum -y groupinstall "Development Tools"
wget https://www.openssl.org/source/openssl-3.0.9.tar.gz
tar xvf openssl-3.0.9.tar.gz
cd openssl-3.0.9/
./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl
make -j $(nproc)
sudo make install
sudo ldconfig
sudo tee /etc/profile.d/openssl.sh<<EOF
export PATH=/usr/local/openssl/bin:\$PATH
export LD_LIBRARY_PATH=/usr/local/openssl/lib:\$LD_LIBRARY_PATH
EOF
source /etc/profile.d/openssl.sh

next install python:
wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz
tar xvf Python-3.11.4.tgz
cd Python-3.11*/
LDFLAGS="${LDFLAGS} -Wl,-rpath=/usr/local/openssl/lib" ./configure --with-openssl=/usr/local/openssl 
make
sudo make altinstall


important note: u have to sure about openssl location. so fixed addresses to right location

**Comment by canhbd** [comment]
> first install openssl:
> 
> sudo yum -y groupinstall "Development Tools" wget https://www.openssl.org/source/openssl-3.0.9.tar.gz tar xvf openssl-3.0.9.tar.gz cd openssl-3.0.9/ ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl make -j $(nproc) sudo make install sudo ldconfig sudo tee /etc/profile.d/openssl.sh<<EOF export PATH=/usr/local/openssl/bin:$PATH export LD_LIBRARY_PATH=/usr/local/openssl/lib:$LD_LIBRARY_PATH EOF source /etc/profile.d/openssl.sh
> 
> next install python: wget https://www.python.org/ftp/python/3.11.4/Python-3.11.4.tgz tar xvf Python-3.11.4.tgz cd Python-3.11*/ LDFLAGS="${LDFLAGS} -Wl,-rpath=/usr/local/openssl/lib" ./configure --with-openssl=/usr/local/openssl make sudo make altinstall
> 
> important note: u have to sure about openssl location. so fixed addresses to right location

Worked, thank you!

**Comment by cshaptx4869** [comment]
> CentOS 7 has an unsupported OpenSSL version. You need to build your own OpenSSL or use my work from https://github.com/tiran/cpython_builddep/#note
> 
> sudo yum install -y epel sudo yum install -y openssl11-devel sed -i 's/PKG_CONFIG openssl /PKG_CONFIG openssl11 /g' configure

sudo yum install -y epel-release.noarch
