### ISSUE TITLE
subprocess.Popen() should allow capturing output and sending it to stdout and stderr

### ISSUE THREAD

**Issue by c776c355-3f7d-4476-8bb3-3221fa9f7951** [python/cpython#91378]
BPO | [47222](https://bugs.python.org/issue47222)
--- | :---
Nosy | @gpshead, @pprindeville
PRs | <li>python/cpython#32344</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2022-04-04.22:52:49.296>
labels = ['type-feature', 'library', '3.11']
title = 'subprocess.Popen() should allow capturing output and sending it to stdout and stderr'
updated_at = <Date 2022-04-05.21:08:52.185>
user = 'https://github.com/pprindeville'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-05.21:08:52.185>
actor = 'pprindeville'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2022-04-04.22:52:49.296>
creator = 'pprindeville'
dependencies = []
files = []
hgrepos = []
issue_num = 47222
keywords = ['patch']
message_count = 1.0
messages = ['416703']
nosy_count = 2.0
nosy_names = ['gregory.p.smith', 'pprindeville']
pr_nums = ['32344']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue47222'
versions = ['Python 3.11']
```

</p></details>

**Comment by gerion0** [comment]
I wanted to request the same and had a hard time to find this issue (while this issue/PR is more advanced). I searched for _subprocess_ and _tee_. This word is mentioned in the PR but not here. Therefore I want to leave it here to make searching easier:
"Provide a tee-mode for `subprocess.Popen` with `stdout` or `stderr` set to something other than `None` and `subprocess.run` with `capture_output=True`"

**Comment by lyricaljoke** [comment]
This would be useful to have.  IMO it would be best to support this generically by fully supporting using file-like objects as the `stdout`, `stderr`, arguments.  Developers could then pass in a file-like object which forwards writes to one or more locations (e.g. a string buffer and stdout).  The existing interface _nearly_ supports this by accepting certain types of file-like objects (e.g. io.StringIO, io.BytesIO etc.), but it currently only works if the file-like object actually exposes a file descriptor via the `fileno()` method.  I have observed that this often leads to developers poorly reinventing `Popen.communicate()` in application code.

This limitation was noted long ago in #74175, but that issue only resulted in a fix to documentation.

**Comment by gpshead** [comment]
I don't doubt the utility, it is something some applications want to do (I've done it multiple times over the years as well). But I'm not convinced we want to maintain such an ability _within_ `subprocess` in the standard library itself. It adds complexity and being so abstract, would be a less than ideal implementation in many circumstances that the subprocess API caller may not be the best one to express in the context of a larger application.  (async or not, threads or not, intermediate tee process or not, etc.)

Design philosophy: `subprocess` today straddles the boundary between low level and high level. Providing a mostly platform agnostic way to create and manage a child process.

The reason a file descriptor from `.fileno()` is required on stdin/out/err is because that is what the underlying OSes allow for connecting pipes behind the scenes so that the data flow is handled entirely by the OS without the current process being involved or even needing to exist. To support something otherwise requires us to re-invent the wheel of how to babysit pipes and copy & feed data from one place to another without blocking.

Implementation wise: This ends up requiring threads for the general case. I'd rather not have the `subprocess` module spawn threads of its own for that behind the scenes on POSIX platforms where the existence of threads can have application wide consequences _(it already does spawn threads on Windows internally for `.communicate()` to read pipes due to a lack of event driven IO)_. Supporting connections to arbitrary objects supporting read or write methods would require threads regardless of if there could be more efficient ways for specific users to meet their applications particular needs.
