### ISSUE TITLE
Division result incorrect for certain very large numbers in python 3.8.10

### ISSUE THREAD

**Issue by pierrevz** [python/cpython#91455]
i came across an odd error which may be happening elsewhere, but was encountered when dividing a particular large integer. I have not chased down other cases.

Type this in at the command line:
int(24121129033219822/2) 

Version 3.8.0 and 3.8.10 both return 12060564516609912.

Obviously it should be 12060564516609911.

Similarly 24121129033219822/2 returns 1.2060564516609912e+16.

No doubt this is coming from a conversion to base 2 somewhere deep in the code.

**Comment by tim-one** [comment]
`/` is the floating-point division operator, so is constrained by the number of bits of precision in a float (53 on most platforms). It can lose information to rounding if at least one input has more bits of precision than that. Use the `//` operator instead. That does exact integer floor division regardless of how many bits are needed to represent the inputs or result.

**Comment by brandtbucher** [comment]
Integer division converts both operands to float before performing the actual division. So, what you're actually doing is something like:

```py
>>> float(24121129033219822) / float(2)
1.2060564516609912e+16
```

Calling `int` on the result after-the fact can't make up for the loss due to the floating-point conversion.

If you'd like to perform arbitrary-precision integer division, use the `//` or '>>' operators instead:

```py
>>> 24121129033219822 // 2
12060564516609911
>>> 24121129033219822 >> 1
12060564516609911
```

**Comment by pierrevz** [comment]
Thank you both,
problem fixed!
