### ISSUE TITLE
documentation for function arguments

### ISSUE THREAD

**Issue by vainaixr** [python/cpython#91485]
it is confusing what these mean, is there a page which explains the difference between these, or if not, then could there be a page which explains the difference between these, (and more variations)

```
max(iterable, *[, key, default])
max(arg1, arg2, *args[, key])
iter(object[, sentinal])
input([prompt])
itertools.accumulate(iterable[, func, *, initial=None])
```

### Linked PRs
* gh-101177
* gh-101199
* gh-101200

**Comment by eugenetriguba** [comment]
https://docs.python.org/3/library/functions.html
https://docs.python.org/3/library/itertools.html#itertools.accumulate

I'm assuming these are what you're referring to?

**Comment by vainaijr** [comment]
i meant the meaning of the arguments, like the `*[`, i do not know if there are more variations to that.

**Comment by vainaijr** [comment]
yes, thanks for the explanation

**Comment by hauntsaninja** [comment]
I agree that we should try and stick to using Python syntax where possible.

Grepping Doc/ for `*[` I found a couple uses, however only the one in io has documentable default values https://github.com/python/cpython/pull/101177 . So after that is merged, I will close this issue since there's a larger discussion to be had about how to document those kinds of functions (e.g. maybe use `...` as the default value?). E.g. see https://github.com/python/devguide/issues/1020

**Comment by arhadthedev** [comment]
> max(iterable, *[, key, default])  →  max(iterable, *, key=None, default=None)

Previously I've thought that `*[...]` means "an optional group that can be repeated". For "optional named-only arguments" I would expect `*, [...]`.

In other words, I would parse `max(iterable, *[, key, default])` as:

- `max(iterable)`
- `max(iterable, key, default)`
- `max(iterable, key1, default1, key2, default2)`
- ...
