### ISSUE TITLE
On Windows, ` os.defpath` incorrectly mentions `C:\bin`

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#91537]
According to the documentation:

> os.defpath - The default search path used by exec\*p\* and spawn\*p\* if the environment doesn’t have a 'PATH' key.

However, on Windows is has a hardcoded `C:\bin`. Starting with Windows 2000, it has no sense because only admins can write outside of %USERPROFILE% and %TMP%. Moreover, I couldn't grep any Python machinery that adds this directory to PATH before exec/spawn.

This value appeared [1 Aug 1994](https://github.com/python/cpython/commit/2979b01ff88ac4c5b316d9bf98edbaaaffac8e24#diff-d2e8ad2f4746ac5fb230fa5a7345fd4332c56818489a2246472d38893aa82431L17-R24) when neither standard paths nor access rights existed:

https://github.com/python/cpython/blob/2979b01ff88ac4c5b316d9bf98edbaaaffac8e24/Lib/os.py#L19-L24

**Comment by eryksun** [comment]
The value of `os.defpath` in Windows is useful in `shutil.which()`, if there's no `PATH` environment variable defined. A reasonable default would be the system directory and the Windows directory, evaluated at startup via `GetSystemDirectoryW()` and `GetWindowsDirectoryW()`. 

> os.defpath - The default search path used by exec*p* and spawn*p* if the environment doesn’t have a 'PATH' key.

The `spawn*p*()` functions aren't implemented in Windows since there's no `fork()`. And the `exec*()` functions are all nearly worthless. They spawn a new process and terminate the current process instead of implementing a POSIX `exec*()` that replaces the process image. This creates a mess with console applications, and generally for any code that requires waiting for a child process to exit.

> Starting with Windows 2000, it has no sense because only admins can write outside of %USERPROFILE% and %TMP%.

What requires special access is creating a file in the root directory of the system drive -- not a directory such as "C:\\bin". Only SYSTEM and administrators are allowed to create a file in the root directory. Also, since Vista, the user's security context needs to have at least high mandatory level to be allowed to create a file in the root directory. This is normally the case for SYSTEM and administrator logons. (It's possible to get an administrator security context with only medium mandatory level, but this combination is abnormal and generally dysfunctional.)

Authenticated users ("AU") are allowed to create a directory in the root directory of the system drive. By default, authenticated users are allowed to modify the directory. This includes the right to delete it, set its file attributes, and add and remove files and directories. It does not include the right to change the discretionary access control, mandatory access control, or owner. However, the user that creates the directory owns it. By default the owner of an object is implicitly allowed to change the discretionary access control, so the owner can take full control of the directory. Implicit owner rights can be overridden by setting an "OWNER RIGHTS" entry.
