### ISSUE TITLE
Unexpected behaviour random.shuffle with multidimensional numpy array

### ISSUE THREAD

**Issue by gcorso** [python/cpython#91546]
```
import numpy as np 
import random 

a = np.asarray([[1,2],[2,2],[3,2],[4,2]])
random.shuffle(a)
print(a)
```

prints `array([[1, 2], [1, 2], [3, 2], [4, 2]])`
I'm pretty sure this is an unwanted behaviour.

**Comment by fbrunodr** [comment]
The problem is not in the random.shuffle method, but in numpy arrays being unsafe when doing the swap operation. See this example:
```
a = np.asarray([[1,2],[2,2],[3,2],[4,2]]);
a[0], a[1] = a[1], a[0]
print(a)
```
This prints `array([[2, 2], [2, 2], [3, 2], [4, 2]])`. The random.shuffle method uses these swap operations to shuffle, so no wonder it does not work with numpy arrays.

**Comment by gcorso** [comment]
Thanks, that makes sense, ideally this should be flagged somehow
