### ISSUE TITLE
Two (possible) improvements at dataclasses.rst

### ISSUE THREAD

**Issue by xandrade** [python/cpython#91687]
**Documentation**

Observed two possible improvements at [dataclasses.rst](https://github.com/python/cpython/blob/main/Doc/library/dataclasses.rst) 

1. One of the examples at line 705 is throwing an exception. I would kindly suggest to update ```x: List = []``` by ```x: list = field(default_factory=list)``` to avoid the following exception: ```ValueError: mutable default <class 'list'> for field x is not allowed: use default_factory```
2. Remove trailing whitespace in line 745 to avoid exception with automated Azure PR Validation.

@ericvsmith I would be more than happy to raise a PR for above.

### Linked PRs
* gh-103773
* gh-103774

**Comment by AlexWaygood** [comment]
Hi @xandrade,

This section of the docs explains why you should use `default_factory` for mutable dataclass fields, and why `dataclasses` sometimes raises an exception if you don't. The point of this specific example is to illustrate the kind of code `dataclasses` would generate if you _didn't_ use a `default_factory`, _if dataclasses even allowed you to not use a `default_factory` in this situation_. The whole reason _why_ `dataclasses` raises an exception if you try to use code like this is _because_ it would have unfortunate consequences, and this example is intended to illustrate what those consequences would be, if `dataclasses` _didn't_ raise an exception in this situation. 

The docs indicate that the code in this example _does_ raise an exception with the sentence introducing this example:

> Using dataclasses, _if_ this code was valid:

[Here's the link](https://docs.python.org/3/library/dataclasses.html#mutable-default-values) to the section of the docs with the example.

You're right that there's a missing import of `List` from `typing` in the example (and the easy solution here is just to use `list` instead of `List`, as was pointed out to you by @JelleZijlstra and @ericvsmith in the previous issue/PR that you created). But the example definitely shouldn't be using a field with a `default_factory`, because the example is meant to fail.

**Comment by AlexWaygood** [comment]
> this is twice in two days that someone wanted to change that.

I don't think so. I think @xandrade opened one issue about this topic, closed it, and has now opened another one (this one).

**Comment by ericvsmith** [comment]
Ah. I didn't notice it was the same person. Thanks.

I'd be okay with a comment `# This code raises ValueError`. As long as we're doing that, we should change `List` to `list`.

**Comment by hauntsaninja** [comment]
Thanks all!
