### ISSUE TITLE
argparse: replace `%(default)` with repr in help text

### ISSUE THREAD

**Issue by eggplants** [python/cpython#91770]
**Feature or enhancement**

Currently, `argparse.ArgumentDefaultsHelpFormatter` adds default values with plain string:

https://github.com/python/cpython/blob/25e35742ce247d10abf2f59d9fef1d88e4a46fc3/Lib/argparse.py#L703

But I think it is better to add the result of `repr(default)` instead like this:

```diff
# https://github.com/python/cpython/blob/25e35742ce247d10abf2f59d9fef1d88e4a46fc3/Lib/argparse.py#L697-L704
    def _get_help_string(self, action):
        help = action.help
        if '%(default)' not in action.help:
            if action.default is not SUPPRESS:
                defaulting_nargs = [OPTIONAL, ZERO_OR_MORE]
                if action.option_strings or action.nargs in defaulting_nargs:
+                    help += ' (default: %(default)r)'
        return help
```

**Pitch**

With the current output of `argparse.ArgumentDefaultsHelpFormatter`, the rough type of the default value cannot be determined just by looking at the help.

An extreme example:

```shellsession
$ python --version
Python 3.9.0
$ cat test.py
from argparse import ArgumentParser, ArgumentDefaultsHelpFormatter
p = ArgumentParser(formatter_class=ArgumentDefaultsHelpFormatter)
p.add_argument(
    "-a", help="aaa", type=str, default='10'
)
p.add_argument(
    "-b", help="bbb", type=int, default=10
)
p.add_argument(
    "-c", help="ccc", type=str, default='False'
)
p.add_argument(
    "-d", help="ddd", action='store_true'
)
p.add_argument(
    "-v", "--version", action="version", version="x.x.x"
)
p.parse_args()
$ python test.py -h
usage: test.py [-h] [-a A] [-b B] [-c C] [-d] [-v]

optional arguments:
  -h, --help     show this help message and exit
  -a A           aaa (default: 10)
  -b B           bbb (default: 10)
  -c C           ccc (default: False)
  -d             ddd (default: False)
  -v, --version  show program's version number and exit
```

I would like to be:

```
$ python test.py -h
usage: test.py [-h] [-a A] [-b B] [-c C] [-d] [-v]

optional arguments:
  -h, --help     show this help message and exit
  -a A           aaa (default: '10')
  -b B           bbb (default: 10)
  -c C           ccc (default: 'False')
  -d             ddd (default: False)
  -v, --version  show program's version number and exit
```

**Previous discussion**

Never before

**Comment by hpaulj** [comment]
I don't think the existing `ArgumentDefaultsHelpFormatter` needs to be changed.

You can do the same thing with the default help formatter, and a help line like the following:

     parser.add_argument("-a", default="10", help="aaa (default=%(default)r)")

In other words, insert the `default` formatting yourself, rather than depending on Formatter to do it for you.  Alternatively you could make your own formatter subclass that does this for you.

Keep in mind that string defaults are passed through the `type` function at the end of parsing (if they remain unchanged in the `Namespace`).  Thus with `type=int`, it doesn't matter whether default is `'10'` or `10`.  So the `repr` might just end up confusing your end user.
