### ISSUE TITLE
`keyword` module methods don't have docstrings

### ISSUE THREAD

**Issue by tusharsadhwani** [python/cpython#91791]
`Lib/keyword.py` is auto-generated from the grammar, resulting in this:

```console
$ python -m pydoc keyword.iskeyword
keyword.iskeyword = __contains__(...) method of builtins.frozenset instance
    x.__contains__(y) <==> y in x.
```

```console
$ python -m pydoc keyword.issoftkeyword
keyword.issoftkeyword = __contains__(...) method of builtins.frozenset instance
    x.__contains__(y) <==> y in x.
```

**Comment by rhettinger** [comment]
I don't think this has caused any actual user problems (likely because the functions are well named).  The only was to "fix" this issue is to dispense with the bound method (which is fast and clean) and replace it with a pass-through function (which would be much slower).  It is important that this function be fast (for example it is used in the inner-loop for *namedtuple*).

So, thank you for the suggestion, but I think we're better off leaving this as is.
