### ISSUE TITLE
argparse set_defaults() does not remove the action.required flag

### ISSUE THREAD

**Issue by ltn100** [python/cpython#91828]
The `required` and `default` attributes for arguments are almost always mutually exclusive (I can't think of a reason why you would want to use both for a single argument, or even how you would make use of it).

I am using a 3rd party class that makes use of `ArgumentParser`, and the use case is such that the parser is constructed first, and then default arguments are added later. Some of the arguments are required, unless a default is added at a later time. Would it make sense to clear the respective `action.required` flags whenever `set_defaults()` is called?

Here is a minimal example:
```
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument("--x", required=True)
>>> parser.set_defaults(x=42)  # <-- this should clear the required flag on x
>>> parser.parse_args([])
usage: [-h] --x X
: error: the following arguments are required: --x
```

**Comment by rhettinger** [comment]
I can see why you might want this and why you might think the current behavior doesn't make sense, but this isn't a bug. The *required* parameter controls whether a user is required to supply a flag. The *default* value specifies an alternative to *None* for the value stored when a value is missing (this occurs downstream after the *type* conversion is applied).  The *set_defaults* method is documented to support  the use case of "additional attributes that are determined without any inspection of the command line to be added".  None of these are in conflict.

The proposal is a behavior change that would break some existing APIs operate. It is true that if those APIs specify a default that it would never be used; however, those existing APIs specifically asked for the arguments to be required and it affects how the argument is show in the usage section (i.e. this is publicly visible and enforced). Also, subclassers may legitimately be setting a default back to *None* without intending to reset the *required* flag.

This change probably should not be made because it:
* can break existing APIs
* has the feel of "spooky action at a distance"
* it contradicts an an explicit user request
* it has an easy workaround by explicitly setting *required* to False when setting a *default* in a subclass.

**Comment by ltn100** [comment]
Thanks @rhettinger, and thanks for reclassifying.

Yes, I can see why this would be a potential breaking change, and I hadn't considered the effect that it would have on usage section.

I am already using the workaround you suggest, so will continue with that approach.

**Comment by hpaulj** [comment]
The `required` parameter may also be set automatically - for a `positional` (except for a `nargs='?'`).
