### ISSUE TITLE
`inspect.isabstract` does not recognize abstract classes

### ISSUE THREAD

**Issue by Wooza** [python/cpython#91823]
**Bug report**

The [documentation ](https://docs.python.org/3/library/inspect.html#inspect.isabstract) of `inspect.isabstract` states
> Return True if the object is an abstract base class.

However, if we consider the following minimal example with abstract classes, all invocations of `inspect.isabstract` return False:
```
import abc
import inspect


class Baz(metaclass=abc.ABCMeta):
    pass


class Foo:
    @abc.abstractmethod
    def foo(self):
        """"""


class Bar(abc.ABC):
    pass


print(inspect.isabstract(Baz))
print(inspect.isabstract(Foo))
print(inspect.isabstract(Bar))
print(inspect.isabstract(abc.ABC))
```

**Testing environment**

- CPython versions tested on: 3.10.2, 3.8.12
- Operating system and architecture: Ubuntu 21.10, x86-64

Best regards
Florian

**Comment by zware** [comment]
I am not an expert in `inspect` or `abc`, but as far as I can tell this is intentional: none of your example classes are actually abstract for a couple of different reasons.  `Foo`'s metaclass is not `abc.ABCMeta`, so `abc.abstractmethod(Foo.foo)` is meaningless (as noted in its docstring).  `Baz`, `Bar`, and `abc.ABC` each have no abstract methods, so there's nothing making them actually "abstract": you can freely instantiate any of them.

**Comment by Wooza** [comment]
Thanks for your fast answer, that sounds reasonable. I was not aware that `@abstractmethod` requires `ABCMeta`, or that `ABC` subclasses without methods are not actually abstract.
Changing my example to
```
class Foo(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def foo(self):
        """"""
```
does indeed work as intended. 
I was working on some type inspection stuff and tried to test it with some simple toy examples and was confused that it seemingly did not work. But now I realize that my toy examples were just to simple, so thanks again 😄
