### ISSUE TITLE
Consider changing URLs to https in docs

### ISSUE THREAD

**Issue by jeanas** [python/cpython#91838]
Many URLs in the documentation are using the HTTP protocol:

```
cpython/Doc$ git grep "http://" | wc -l
460
cpython/Doc$ git grep "https://" | wc -l
805
```

A number of these could be converted to HTTPS. If this would be welcome, I am willing to open a PR for that, converting them with a script that checks if the HTTPS equivalent is reachable.

**Comment by serhiy-storchaka** [comment]
AFAIK many URLs were converted to HTTPS several years ago. These that left are URLs which do not work with HTTPS or redirect to HTTP. Things could changed since and more URLs could be now converted to HTTPS, but you should test that it is a canonical representation. Not only that the HTTPS equivalent is reachable, but that it is not a redirection to HTTP.

**Comment by slateny** [comment]
What would be the concern if links converted to https redirects to http?

**Comment by serhiy-storchaka** [comment]
It does not have advantages over keeping the HTTP link, but it would mislead the user.

@Jean-Abou-Samra, if you are willing to open a PR for that, please go ahead, but test also that the replacements are meaningful. Otherwise I'll close this issue.

**Comment by serhiy-storchaka** [comment]
I already started a work for the most harmless changes.
