### ISSUE TITLE
Clarify that bisect(a, x, key=...) does not call key(x)

### ISSUE THREAD

**Issue by sean8223** [python/cpython#91966]
The key functions generated by the functools.cmp_to_key function don't work with bisect.bisect_right or bisect.bisect_left, raising a TypeError with the message "TypeError: other argument must be K instance" when used.

Consider the following example derived from the Sorting HOWTO page (https://docs.python.org/3/howto/sorting.html#the-old-way-using-the-cmp-parameter)

```
Python 3.10.4 (main, Apr 25 2022, 16:19:06) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from functools import cmp_to_key
>>> from bisect import bisect_right, bisect_left
>>> ns=[1,2,3,4,5]
>>> def numeric_compare(x, y):
...     return x - y
... 
>>> bisect_right(ns, 2, key=cmp_to_key(numeric_compare))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: other argument must be K instance
>>> bisect_left(ns, 2, key=cmp_to_key(numeric_compare))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: other argument must be K instance
```

The methods bisect.insort_left and bisect.insort_right functions do seem work correctly with these key functions:

```
Python 3.10.4 (main, Apr 25 2022, 16:19:06) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bisect import insort_right, insort_left
>>> from functools import cmp_to_key
>>> def numeric_compare(x, y):
...     return x - y
... 
>>> ns=[1, 2, 3, 4, 5]
>>> insort_right(ns, 2, key=cmp_to_key(numeric_compare))
>>> ns
[1, 2, 2, 3, 4, 5]
```

**Your environment**

- Python version 3.10.4
- Linux x86

**Comment by sweeneyde** [comment]
`bisect_left`/`bisect_right` functions take in a key with the function already applied; they do not apply the key function to the `x` parameter. IIRC it was decided this way because this is slightly more general (you can apply the function when you need to apply the function, but sometimes you only have a key).

```python
>>> ns=[1,2,3,4,5]
>>> key_func = cmp_to_key(numeric_compare)
>>> bisect_right(ns, key_func(2), key=key_func)
2
```

Maybe this is worth documenting better?

**Comment by sweeneyde** [comment]
`bisect_left`/`bisect_right` functions take in a key with the function already applied; they do not apply the key function to the `x` parameter. IIRC it was decided this way because this is slightly more general (you can apply the function when you need to apply the function, but sometimes you only have a key).

```python
>>> ns=[1,2,3,4,5]
>>> key_func = cmp_to_key(numeric_compare)
>>> bisect_right(ns, key_func(2), key=key_func)
2
```

Maybe this is worth documenting better?

**Comment by sean8223** [comment]
I agree that this can be fixed with documentation on the bisect functions -- I would never have deduced this usage from the error message or the examples. Thanks!

**Comment by rhettinger** [comment]
I'll add another example in the final section showing the motivating use case.  Will also amend the function specification to note that the key function is not called on the input value.

**Comment by wpk-** [comment]
In the motivating use case, since `movies` is a list of movies, I suppose 1960 comes from a new `Movie` record and we're looking to find its insertion point, right? 

The docs clearly state `bisect(a, x)` will "locate the insertion point for `x` in `a` to maintain sorted order." I really expect this to still hold for `bisect(lst, x, key=fn)`. The current implementation breaks with that definition.
