### ISSUE TITLE
IDNA resolving is wrong

### ISSUE THREAD

**Issue by JannesAlthoff** [python/cpython#92025]
I own the Domain `κλαρα-σωλις.ευ`, i tried converting the domain via the encode method of string, it results in a wrong A-Label Form of my Domain.

```py
>>> domain = u"κλαρα-σωλις.ευ"
>>> domain.encode("idna")
b'xn----ylba7abgd9buc7d.xn--qxa6a'
```
My Browser and EURID the EU-Registrar converts `κλαρα-σωλις.ευ` to `xn----ylba7abgd9bnh0e.xn--qxa6a`.

**Comment by dignissimus** [comment]
This happens because the [`nameprep`](https://docs.python.org/3/library/codecs.html#encodings.idna.nameprep) converts 'ς' to 'σ' using [`stringprep.map_table_b2`](https://docs.python.org/3/library/stringprep.html#stringprep.map_table_b2).

https://github.com/python/cpython/blob/ea2f5bcda1a392804487e6883be89fbad38a01a5/Lib/encodings/idna.py#L14-L21

I'm not familiar with the IDNA specification but behaviour seems wrong.

**Comment by dignissimus** [comment]
This document seems relevant here.

https://unicode.org/reports/tr46/#Table_Deviation_Characters

**Comment by DemiMarie** [comment]
This is actually a security vulnerability, as it causes HTTPS requests to use wrong hosts.

**Comment by JannesAlthoff** [comment]
Using only IDNA2008 could be a problem because it breaks Emoji URLs, and a few other URLs, which exists but aren't valid with IDNA2008. Like 📻.fm .

**Comment by JannesAlthoff** [comment]
Similar to [CVE-2016-8625](https://www.cvedetails.com/cve/CVE-2016-8625/)

**Comment by DemiMarie** [comment]
@JannesAlthoff How do browsers handle such URLs?

**Comment by JelleZijlstra** [comment]
Thanks @dignissimus, agree it's a duplicate of #61507.
