### ISSUE TITLE
random.sample: `OverflowError` if the size is 2**63 or larger

### ISSUE THREAD

**Issue by oittaa** [python/cpython#92038]
**Bug report**

Arbitrarily large integers work almost everywhere, except I recently encountered an issue while taking a sample from a large `range()`.

Throws an error `OverflowError: Python int too large to convert to C ssize_t`
```python
import random
random.sample(range(2**63), k=2)
```

With one less it works as expected
```python
import random
random.sample(range(2**63 - 1), k=2)
```

**Your environment**

- CPython versions tested on: 3.10.2
- Operating system and architecture: Macos 12, Apple M1

**Comment by serhiy-storchaka** [comment]
This is a known limitation. See #65643.

**Comment by rhettinger** [comment]
This is due to a known limitation in Cpython where the *len()* function which cannot store large ranges.  Everything in Python that uses *len()* is affected by this limitation, but it doesn't seem to matter in actual practice.

```
>>> len(range(1 << 65))
Traceback (most recent call last):
 ...
OverflowError: Python int too large to convert to C ssize_t
```

For the sampling without replacement example, the workaround is easy.  Use *randrange()* to make selections.  It doesn't overflow because it doesn't have to check the size of a population like sample() does.
```
>>> randrange(1 << 65)
16750681663488381831
```

If people really care about this (I'm not sure they do), there is a possible general solution.  Add an *OverflowError* fallback code path to the builtin *len()* function.  That path can then compute arbitrarily large sizes from objects that have integer *start*, *stop*, and *step* attributes.  

This is a general solution because it fixes every case where a *rangeobject* gets passes to a *len()* function.  Then *choice()* and *sample()* will function as the OP expected.  Also, *randrange()* would simplify to just ``choice(range(start, stop, step))`` and it would no longer need to manually compute widths.

The builtin *len()* could also be built out with a fallback that calls ``__len__`` method directly.  This won't help with builtin types like *rangeobject*, but it would help with user defined types:

```
class A:
    def __len__(self):
        return 1 << 66

>>> a.__len__()
73786976294838206464
```

These two measures would mitigate the limitations imposed by CPython's  system of internal slots like *mp_length* and *sq_length*.  However, I don't think any work should be done until we've ascertained whether we're partially solving a real problem or just addressing a theoretical concern.
