### ISSUE TITLE
Specialization of namedtuple types

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#92107]
`collections.namedtuple()` creates a `tuple` subclass, and as a subclass it inherits all `tuple` methods, including `__class_getitem__`.

The `__new__` method has been overridden in a named tuple class. It no longer accept an iterator of arbitrary length. The named tuple has fixed number of elements, and the constructor accept fixed number of arguments (some may be optional).

But the `__class_getitem__` is inherited from `tuple`. It allows to specialize the named tuple type with arbitrary number of arguments.
```python
Point2D = namedtuple('Point2D', 'x y label')
Point2D[int, int, str]
Point2D[int, str]
Point2D[int, ...]
```
It looks confusing at best. A named tuple is not a general tuple, it cannot have an arbitrary number of items.

There are two options:

1. Forbid subscription of types created by `namedtuple()`. If you want to add type annotations, use `typing.NamedTuple`.
2. Add `__class_getitem__` which checks that the number of types corresponds to the size of the named tuple.

@rhettinger

**Comment by serhiy-storchaka** [comment]
See also #92106 and #88089.

**Comment by AlexWaygood** [comment]
I'm not sure that it is a good idea to forbid parameterisation of `collections.namedtuple` at runtime.

The standard library has quite a few uses of `collections.namedtuple`. For almost all of these, typeshed pretends that they are actually `typing.NamedTuple`s, since using `collections.namedtuple` in a stub gives the type checker very little information to work with.

If #92027 is merged, type checkers will be given the freedom to implement support for generic NamedTuples. If they do implement support, we'll want to make several of these stdlib namedtuple-at-runtime-but-NamedTuple-in-the-stub classes generic. `concurrent.futures.DoneAndNotDoneFutures` is an obvious example of a `collections.namedtuple` that we need to be generic in the stub, but there will be others as well. 

If we forbid parameterisation of `collections.namedtuple` at runtime, it could cause a lot of user pain if a user comes across a class that forbids parameterisation at runtime, but which typeshed says is a generic `typing.NamedTuple`.

**Comment by AlexWaygood** [comment]
There isn't the same issue with `TypedDict`, as there isn't a "pre-typing" version of the class the same way as there is with `typing.NamedTuple`

**Comment by MojoVampire** [comment]
Is there a reason the PR just goes straight for option `#1` (forbidding subscription)? Option `#2` seems like a "better than nothing" solution, and doesn't risk breaking existing code that makes sense (code that subscripted with a mismatched number of types would break, but that code would be, by definition, incorrect).

**Comment by AlexWaygood** [comment]
What about a namedtuple like this (for example):

```python
from collections import namedtuple

Foo = namedtuple("Foo", "dict_field list_field")
```

In typeshed we might want to write a stub for this class like this:

```python
from typing import NamedTuple, Generic, TypeVar

T = TypeVar("T")
U = TypeVar("U")
V = TypeVar("V")

class Foo(NamedTuple, Generic[T, U, V]):
    dict_field: dict[T, U]
    list_field: list[V]
```

This class expects 3 parameters, even though it only has two fields. So Option 2 would also be complicated to get right.

**Comment by JelleZijlstra** [comment]
Agree with @AlexWaygood; it can be useful to subscript collections.namedtuples if they are conceptually generic. We don't need to change anything here.

**Comment by serhiy-storchaka** [comment]
@AlexWaygood, in your example the named tuple is generic. This issue is about non-generic named tuples.

**Comment by AlexWaygood** [comment]
> @AlexWaygood, in your example the named tuple is generic. This issue is about non-generic named tuples.

Indeed, but that was my point. If there's a class that's a non-generic `collections.namedtuple` at runtime, but a generic `typing.NamedTuple` in typeshed, that has potential for causing a large amount of user pain if the type checker expects them to parameterise a class, but the runtime raises an exception when they try to do so.
