### ISSUE TITLE
Unavailable Tcl version when compiling for MacOS 10.6

### ISSUE THREAD

**Issue by lmbelo** [python/cpython#92171]
**Bug report**

MacOS build-installer.py script failing with the --dep-target=10.6 argument. It tries to download an unavailable Tcl version (8.6.12) from the FTP server.

**Error**

urllib.error.URLError: <urlopen error ftp error: URLError("ftp error: error_perm('550 Failed to change directory.')")>

**Your environment**

- CPython versions tested on: 3.10.4
- Operating system and architecture: MacOS M1

**Comment by erlend-aasland** [comment]
Quoting the [Tcl/Tk website](https://tcl.tk/software/tcltk/download.html):

> The main site for Tcl/Tk source distributions is [SourceForge](https://sourceforge.net/projects/tcl/files/Tcl/)

The link they provide for 8.6.12 is https://prdownloads.sourceforge.net/tcl/tcl8.6.12-src.tar.gz

**Comment by lmbelo** [comment]
Well, if we need to setup the current script to directly download from the sourceforge, we should use the 
following link instead: https://sonik.dl.sourceforge.net/project/tcl/Tcl/8.6.12/tcl8.6.12-src.tar.gz

**Comment by erlend-aasland** [comment]
For the record:

```console
$ wget ftp://ftp.tcl.tk/pub/tcl//tcl8_6/tcl8.6.8-src.tar.gz
--2022-05-02 13:02:17--  ftp://ftp.tcl.tk/pub/tcl//tcl8_6/tcl8.6.8-src.tar.gz
           => ‘tcl8.6.8-src.tar.gz.1’
Resolving ftp.tcl.tk (ftp.tcl.tk)... 66.228.49.43
Connecting to ftp.tcl.tk (ftp.tcl.tk)|66.228.49.43|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/tcl//tcl8_6 ... done.
==> SIZE tcl8.6.8-src.tar.gz ... 9793786
==> PASV ... done.    ==> RETR tcl8.6.8-src.tar.gz ... done.
Length: 9793786 (9,3M) (unauthoritative)

tcl8.6.8-src.tar.gz.1                                       100%[=========================================================================================================================================>]   9,34M  5,31MB/s    in 1,8s    

2022-05-02 13:02:20 (5,31 MB/s) - ‘tcl8.6.8-src.tar.gz.1’ saved [9793786]

$ wget ftp://ftp.tcl.tk/pub/tcl//tcl8_6/tcl8.6.12-src.tar.gz
--2022-05-02 13:02:23--  ftp://ftp.tcl.tk/pub/tcl//tcl8_6/tcl8.6.12-src.tar.gz
           => ‘tcl8.6.12-src.tar.gz.1’
Resolving ftp.tcl.tk (ftp.tcl.tk)... 66.228.49.43
Connecting to ftp.tcl.tk (ftp.tcl.tk)|66.228.49.43|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /pub/tcl//tcl8_6 ... done.
==> SIZE tcl8.6.12-src.tar.gz ... done.

==> PASV ... done.    ==> RETR tcl8.6.12-src.tar.gz ... 
No such file ‘tcl8.6.12-src.tar.gz’.

```

**Comment by ronaldoussoren** [comment]
The SourceForge download link is problematic for the build script because it inserts an intermediate page and that breaks the build-installer.py script. 

A somewhat easy fix would be to change the ``downloadURL`` function in that script to use ``curl(1)`` instead of ``urllib`` to download. I checked that ``curl -LO https://prdownloads.sourceforge.net/tcl/tcl8.6.12-src.tar.gz`` will download the source archive.

**Comment by erlend-aasland** [comment]
Good point regarding the redirects. Using curl is a better option.

**Comment by ronaldoussoren** [comment]
Calling out to curl is the easy option, it Is also possible to follow redirects in Python code but that's more work and probably not worth the effort for this script.

**Comment by zware** [comment]
We do keep a copy of the vanilla [tcl](https://github.com/python/cpython-source-deps/releases/tag/tcl-core-8.6.12.0)/[tk](https://github.com/python/cpython-source-deps/releases/tag/tk-8.6.12.0) sources in our own [GitHub repo](https://github.com/python/cpython-source-deps/) for use on Windows, though the link GitHub gives to the archive is also a redirect (`https://github.com/python/cpython-source-deps/archive/refs/tags/tcl-core-8.6.12.0.tar.gz` -> `https://codeload.github.com/python/cpython-source-deps/tar.gz/refs/tags/tcl-core-8.6.12.0`; similar for tk).  We also only use the `tcl-core` package rather than the full-fat `tcl` distribution; we've found that's all we actually need on Windows.
