### ISSUE TITLE
Add contextlib.redirect_stdin context manager

### ISSUE THREAD

**Issue by dignissimus** [python/cpython#92178]
The [`contextlib`](https://docs.python.org/3/library/contextlib.html) library contains [`redirect_stdout`](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout) and [`redirect_stderr`](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stderr) context managers to temporarily redirect standard output and standard error to another stream. However, a `redirect_stdin` context manager does not exist. This would introduce a `redirect_stdin` context manager to temporarily redirect standard input to a specified stream.

Discussion
---
* https://mail.python.org/pipermail/python-ideas/2017-September/047236.html
* https://mail.python.org/archives/list/python-ideas@python.org/thread/OMLVJ5RI3C62PERTFADLAVMEEMOI6PF4/

**Comment by rhettinger** [comment]
We had discussed this when the stdout and stderr variants were added.  It was decided to not go down this path because it is rare, unusual, tricky with debuggers, and hard to work with.  As such, it does not belong in the standard library.

Thanks for the suggestion, but this was intentionally omitted.
