### ISSUE TITLE
Porting use of argclinic lru_cache_new from Cinder.

### ISSUE THREAD

**Issue by zitterbewegung** [python/cpython#92197]
**Enhancement of lru_cache_new to use argument clinic**

In cinder one of the enhancements that is relatively low hanging fruit involves adding argument clinic to lru_cache_new since it would provide more coverage of argument clinic in CPython and possibly increase speed in this hot code path.

**Comment by JelleZijlstra** [comment]
Argument Clinic patches are welcome! Feel free to request my review on any such patches.

**Comment by rhettinger** [comment]
> It would provide more coverage of argument clinic in CPython 

There isn't an arg clinic "coverage" goal.  Mostly, we only use this only use this on public facing APIs that need a signature object or calls the can be given a substantial speed boost.  For internal calls, it is has almost no value.

The public facing part of *lru_cache()* is pure python function.  The *lru_cache_new_()* code path is internal.

> and possibly increase speed in this hot code path.

The *lru_cache_new_()* function isn't a hot path. It is used only one when the cache is created. There is no speed benefit to be had here.

**Comment by serhiy-storchaka** [comment]
I concur with @rhettinger and do not see any benefit.

We did not even replace `PyArg_ParseTupleAndKeywords()` with something more efficient, like `PyTuple_Unpack()`, because the speed does not matter here.

Note that it is not a constructor of `functools.lru_cache`. It is a constructor of internal object `functools._lru_cache_wrapper`.
