### ISSUE TITLE
argparse.BooleanOptionalAction accepts and silently discards choices, metavar, and type arguments

### ISSUE THREAD

**Issue by samwyse** [python/cpython#92248]
This is an elaboration of issue #85039.

    >>> parser = ArgumentParser()
    >>> parser.add_argument('--foo', action=BooleanOptionalAction,
    ...     choices=[1,2], metavar='FOOBAR', type=int)  # doctest: +ELLIPSIS
    BooleanOptionalAction(...)

Note that the store_const, store_true, and store_false actions disallow those keyword arguments.

    >>> parser.add_argument('--bar', action='store_true', choices=[1,2])
    Traceback (most recent call last):
      ...
    TypeError: __init__() got an unexpected keyword argument 'choices'
    >>> parser.add_argument('--bar', action='store_true', metavar='FOOBAR')
    Traceback (most recent call last):
      ...
    TypeError: __init__() got an unexpected keyword argument 'metavar'
    >>> parser.add_argument('--bar', action='store_true', type=int)
    Traceback (most recent call last):
      ...
    TypeError: __init__() got an unexpected keyword argument 'type'
    >>> parser.add_argument('--bar', action='store_true')  # doctest: +ELLIPSIS
    _StoreTrueAction(...)

### Linked PRs
* gh-103678

**Comment by rhettinger** [comment]
The various options have complex relationships and some don't have well-defined interactions in uncommon cases.  From my point-of-view, your examples don't make much sense. The *store_true* action is used to create flags that don't have arguments, so the concept of *choices* or *metavar* doesn't apply and is IMHO reasonably ignored by argparse.

 At some point, we should make a list of the steps, the order they are applied, and which inputs are considered.  It may end-up being a decision table or graph.  I'm not really sure that it would help anyone (because the examples didn't make sense in the first place) but at least it would precisely define the behavior (possibly at the risk of over-specification).
