### ISSUE TITLE
Adding an option to clear the python interpreter shell 

### ISSUE THREAD

**Issue by ghost** [python/cpython#92244]
**Feature or enhancement**

An option to clear the interactive python shell would be quite helpful in case the shell gets clunky

**Pitch**

Since many times we have to use the interactive shell for certain purposes for a long time it is kind of tedious to use
```py
>import os
>os.system("clear")
```
everytime, even with pythonrc it will be tedious to set it everytime when switched to a different workspace , hence it would be really helpful to have this feature builtin to prevent repeating things.

**Comment by MojoVampire** [comment]
Making this portable gets seriously clunky. Sure, in a Windows `cmd.exe` or PowerShell you can use `os.system('cls')`. On *most* Linux terminals you can use `os.system('clear')`. On any shell supporting ANSI escape codes, `print("\033[H\033[J", end="")` works without even launching a subprocess. But then you have all the simulated terminals provided by random IDEs (e.g. IDLE) where that won't work, and there's very little ability to determine what methods (if any) *will* work. I'm not against this if someone finds a magical way to make it fully portable (and ideally without relying on invoking subprocesses, which has all sorts of quirks you don't want in what appears to be a simple API call), but I'm not sure such a solution exists.

**Comment by user-dead** [comment]
How about instead of adding it to every interactivbe shell, we detect if its running in a terminal emulator which supports bash / windows commands , if so then we do the clear/cls command else we can print a message that this terminal emulator cant be cleared with the function call , or another thing which i believe can be done is integrating the idlelib with the clear() function , as most of the time python tty shell is either run in  a terminal emulator that is comaptible with bash/windows commands or idle, because so far havent found any other tty shell for python other than idle integrated with an ide which doesnt supports native os commands, i might be wrong , so feel free to correct me

**Comment by serhiy-storchaka** [comment]
Such idea is proposed maybe once in a year, and rejected for reasons mentioned by @MojoVampire.

**Comment by oda-gitso** [comment]
As mentioned by @MojoVampire, on terminals, `os.system('clear')` should work for Linux and `os.system('cls')` for Windows. 

For Jupyter, one would need `clear_output`: `from IPython.display import clear_output`. 

I don't think a fully portable one is practically feasible.
