### ISSUE TITLE
Restart

### ISSUE THREAD

**Issue by rungrotArunon** [python/cpython#92283]
**Feature or enhancement**

(A clear and concise description of your proposal.)

**Pitch**

(Explain why this feature or enhancement should be implemented and how it would be used.
 Add examples, if applicable.)

**Previous discussion**

**Comment by rungrotArunon** [comment]
Why did I close it?

**Comment by stevendaprano** [comment]
@rungrotArunon if you want to post an enhancement request you have to actually tell us what the enhancement is. We can't read your mind. "Restart" means nothing on its own.

**Comment by rungrotArunon** [comment]
Wisdom when working with others, where is the problem?

**Comment by stevendaprano** [comment]
The problem is that you are wasting our time. Do you have an actual bug to report or a feature enhancement? This isn't social media.

**Comment by rungrotArunon** [comment]
I think you misunderstood, I'm flawed, I admit that there are some, but as I see it, it's against what I'm doing already.

**Comment by rungrotArunon** [comment]
Even if it's about the documents, I'm doing everything right, together with an adult, then submitting it to confirm, where am I wrong?

**Comment by stevendaprano** [comment]
You still haven't told us what you want. You actually have to type a description of what you want, otherwise we don't know. We aren't mind readers.

You need:

1. A clear and concise description of your proposed feature. "Python should have blah blah blah".
2. An explanation of how it relates to the title you gave, "Restart". Restart what? When? Why? How?
3. An explanation for *why* you think Python should have that feature, why it is useful, examples showing how it will be used, and if possible, how you would program that feature.
