### ISSUE TITLE
Python 3.10 IDLE 64-bit doesn't open any files names code (code.py, code.pyw)

### ISSUE THREAD

**Issue by BlaBlak2** [python/cpython#92359]
Any files named code (code.py, code.pyw) wont open in Python 3.10 IDLE 64-bit (That's the only one I tried, might work on other versions)

This happened on Win 10 Home V10.0.19043

**Comment by mrabarnett** [comment]
I have Windows 10 Home Version 10.0.19044 and I cannot reproduce the problem.

**Comment by devdave** [comment]
@BlaBlak2 can you give the steps you are taking to produce this bug?    Are you using the explorer context menu "Edit with Idle" or are you using the IDLE File -> Open -> Select `code.py` file in File open dialog box.   or is there some other mechanism you're trying?

**Comment by BlaBlak2** [comment]
> @BlaBlak2 can you give the steps you are taking to produce this bug? Are you using the explorer context menu "Edit with Idle" or are you using the IDLE File -> Open -> Select `code.py` file in File open dialog box. or is there some other mechanism you're trying?

Edit with Idle

**Comment by devdave** [comment]
I am able to replicate this but it is even worse on Windows 11.   Clicking on the Explorer context "Edit with Idle", nothing happens if I attempt to open another file if there is a file named `code.py` in the same directory.

Steps to replicate:

```commandline
>mkdir issue_92359
>cd issue_92359
>echo print('Hello from testme') > testme.py
>explorer .
```
From there do "Edit with Idle" on testme.py and it will open.  Go back to the console/terminal ->

```commandline
>echo print('Hello from code file') > code.py
```
Returning to the File Explorer window, I am now unable to open either `testme.py` or `code.py` with the "Edit with Idle" context menu command.

One thing I have noticed is that a `__pycache__`  sub directory is made with `code.cpython-310.pyc` inside which suggests to me that something is executing/importing `code.py` when the "Edit with idle" context menu is clicked.


Additionally, this problem also happens with Python 3.9.

**Comment by devdave** [comment]
The source of the problem is this line https://github.com/python/cpython/blob/main/Lib/idlelib/pyshell.py#L26

`from code import InteractiveInterpreter`

I am still learning how Idle works but the Python import path is including the current directory, (ex `issue_92359`) and importing the wrong `code.py` in idlelib/pyshell.py.

**Comment by devdave** [comment]
The "Edit with IDLE" shell registry value is  `"C:\Python310\pythonw.exe" -m idlelib "%L" %*

And to verify this is the issue, I went to `Lib/idlelib/__main__.py` and added 

```python
import sys
import pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent.parent.absolute()))
```

before `idlelib.pyshell` is called and the bug went away.   

I can make a push request with that fix but it just feels like an ugly hack.

**Comment by BlaBlak2** [comment]
From what I understand it's importing code but because the files name is code.py it imports the wrong file. Thanks for your help, your choice on the push request.

**Comment by devdave** [comment]
The problem isn't fixed so I would recommend reopening this.   You can remove yourself from the issue so you don't have to deal with spam.

**Comment by terryjreedy** [comment]
Import shadowing is not a bug, code.py specific, IDLE specific, or Windows specific.  See #67997.

A program that needs to execute IDLE code can avoid it by *temporarily* sys.path at startup, but then it must do *all* its imports before reverting sys.pyth.  I believe IDLE delays a few to avoid fatal circular imports.  I might need to delay more sometime, and I would like to delay more for better startup performance.  So I leave this closed.

In the meanwhile, don't use the name of stdlib files (I am not sure about idlelib file names) for your code.

**Comment by BlaBlak2** [comment]
> Import shadowing is not a bug, code.py specific, IDLE specific, or Windows specific. See #67997.
> 
> A program that needs to execute IDLE code can avoid it by _temporarily_ sys.path at startup, but then it must do _all_ its imports before reverting sys.pyth. I believe IDLE delays a few to avoid fatal circular imports. I might need to delay more sometime, and I would like to delay more for better startup performance. So I leave this closed.
> 
> In the meanwhile, don't use the name of stdlib files (I am not sure about idlelib file names) for your code.

for what im doing i cant but its fine i can deal with it

> The problem isn't fixed so I would recommend reopening this. You can remove yourself from the issue so you don't have to deal with spam.

alr

**Comment by terryjreedy** [comment]
I intentionally left this closed.  If I ever want someone to work on an IDLE workaround, I will first do some research to list the various ways to open IDLE and the resulting  sys.path, on all 3 major systems.  I will then open a new issue starting with those results.
