### ISSUE TITLE
Clarification for queue.SimpleQueue

### ISSUE THREAD

**Issue by jenstroeger** [python/cpython#92516]
**Documentation**

As I read through the [queue.SimpleQueue](https://docs.python.org/3/library/queue.html#queue.SimpleQueue) documentation

> Constructor for an unbounded FIFO queue. Simple queues lack advanced functionality such as task tracking.

I wondered what “unbounded” means exactly. Looking at [the source](https://github.com/python/cpython/blob/859250cc55711f4d62b65922d3f7537826c3801e/Lib/queue.py#L258-L322) the SimpleQueue constructor allocates a [collections.deque()](https://docs.python.org/3/library/collections.html#collections.deque) whose `maxlen` if not specified and therefore allows the deque to

> […] grow to an arbitrary length.

So, it sounds like an “unbounded SimpleQueue” means that that queue grows until it exhausts memory.

I think it might make sense to mention that the queue.SimpleQueue wraps the collections.deque without a max length. That way we learn a little more about the SimpleQueue and “unbounded” can be clarified as well.

**Comment by rhettinger** [comment]
Sorry, this doesn't make sense to me.   The word *unbounded* means the opposite of *bounded*. This is clear from the context. It differentiates *SimpleQueue* from *Queue* which has "maxsize is an integer that sets the upperbound limit on the number of items that can be placed in the queue."

Also, it doesn't make sense to talk about *deque*.  That is an implementation detail that may change.  The docs describe what objects do rather than how they are implemented (there are some exceptions if it affects how a user should use an object).
