### ISSUE TITLE
Issues when Condition.notify() is interrupted

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#92530]
If `threading.Condition.notify()` is interrupted just after it releases the waiter lock, but before remove it from the queue, the following calls of `notify()` will fail with `RuntimeError: cannot release un-acquired lock`. It can block the waiter threads if they do not use timeout.

https://github.com/python/cpython/blob/5bc2390229bbcb4f13359e867fd8a140a1d5496b/Lib/threading.py#L375-L380

The simplest solution would be to silence a RuntimeError in `waiter.release()`. There may be similar issues in other parts of the code.

**Comment by serhiy-storchaka** [comment]
There was a similar issue in #89437, although it is difficult to fix it correctly in that case. @vstinner

**Comment by bensimner** [comment]
In #90882 the discussion led to a solution of adding threading.Thread.acquire_and_release method which would solve #89437, but I don't think a PR for that was ever created. This solution probably doesn't help here.

Simply ignoring the RuntimeError here would mean that in those cases notify(n) would wake up fewer than n threads even if n threads were available to wake.  Possibly that's not an issue since condition vars don't make guarantees about how many threads will be awoken.
