### ISSUE TITLE
Python 3.11 doc links actually point to 3.12 docs

### ISSUE THREAD

**Issue by deeppunster** [python/cpython#92588]
**Documentation** - Documentation links for 3.11 actually point to 3.12 documentation

**Details**

The link on [this page](https://www.python.org/downloads/release/python-3110b1/) for the documentation points to [this link](https://docs.python.org/3.11/), but the documentation actually shown is for Python 3.12.0a0.  Further, if I click on the link labeled "Python 3.11 (in development)" in the left sidebar, it just points back to the page already showing.

If this is not reproducible or you need more info, please let me know.  Also, if this is the wrong repository to report this issue, please let me know the correct repository.
Thanks,
Travis

**Comment by CAM-Gerlach** [comment]
Thanks for reporting. Actually, it seems like this is a bigger issue than just what is mentioned above, as it seems like the real problem is that when Python 3.11 was branched at feature freeze/beta realease, the multi-version deployment configuration was apparently not updated, such that the `main` branch is still deploying to the `3.11` subdir on the docs.python.org site, which is still labeled `dev` (rather than `pre`) and there's no 3.12 `dev` branch shown at all.

I'm not familiar with the specific multi-version tooling being used here (I use Sphinx-Multiversion on the repos I maintain, which makes this easy and self-contained as it is all orchestrated within the Sphinx build process itself without any external infra, and automatically uses the repo's tags/branches matching the configured pattern). After a bit of searching, I can't seem to find where this configuration actually lives on this repo, so it might be either somewhere else I didn't check, or handled externally on the hosting side (RTD/Python.org/PSF infra).

Not 100% sure who to ask about this, but I'm guessing @Mariatta or @ewdurbin would know....?

**Comment by corona10** [comment]
@JulienPalard PTAL

**Comment by JulienPalard** [comment]
Taking a look.

**Comment by JulienPalard** [comment]
Got it! It happened yesterday due to https://github.com/python/cpython/issues/92532 happening **during** the creation of the 3.11 branch, a very unfortunate concurrence of rare events:

- When I killed the stuck build, a new waiting build (a process already loaded in memory) started immediatly with a configuration from **before** the 3.11 branch creation (the process was 10+ days old!).
- It was configured to build 3.11 from the `main` branch as there was no 3.11 branch at the time.
- in the meantime, the main branch switched to 3.12, and we now have a 3.11 branch.
- I updated in due time the docsbuild-scripts in https://github.com/python/docsbuild-scripts/commit/30b98030d78db56b28f8590b877f3c33f79b913d to configure `3.12` to build from `origin/main` and `3.11` to build from `origin/3.11`.
- But as it was an old docsbuilder, it picked `origin/main` (containing `3.12`) to build `3.11`, leading to a `3.12` doc (from main) being visible in the `/3.11/` path.

With no human intervention:
- The correct version of docsbuild scripts were picked on the build server on may 8, a few minutes after my commit).
- A fresh build started with it on may 10 0h00 UTC (9 hours ago at the time of writing).
- It already built 3.9 (en, zh-cn, zh-tw, ja, pl, fr, id, ko, pt-br, and es) and should start to build 3.10 soon, then 3.11 (resolving the issue) then 3.12.
- So the issue should resolve by itself, I'll just keep an eye on it.

What I should have done:
- Kill all waiting builders (with old config) before killing the stuck one, to avoid for an old one to run.

Thanks for reporting @deeppunster! I'll close the issue when it gets resolved. I think it a fix has to be added to the code it's more to check for stuck builds than for branch swaps at build time, as the probability of having a branch swap during a stuck build is pretty low (build got stuck only once).

**Comment by CAM-Gerlach** [comment]
Great. thanks for the detailed writeup @JulienPalard 

> A fresh build started with it on may 10 0h00 UTC (9 hours ago at the time of writing).

Wait, it takes > _9 hours_ (!!!) to build the docs? Is there a reason it takes so incredibly long? On my ancient 10 year old laptop running only a single one process and no optimization I can build the docs from scratch in a couple minutes. I understand there's multiple translations x multiple output formats x multiple versions, but that still seems kind excessive, especially for just updating the standard HTML builder given that's how the overwhelming majority of users are likely to access them. Despite their infra being several times slower and less efficient than my hand-tuned builds running on GHA and Netlify, RTD still manage to build fairly large docs sites with many versions and multiple translations and output formats in a matter of minutes, on very low-cost shared infra rather than a dedicated server. Is there some reason it takes so long?

**Comment by JulienPalard** [comment]
> Wait, it takes > _9 hours_ (!!!) to build the docs? Is there a reason it takes so incredibly long?

PDF builds.

> On my ancient 10 year old laptop running only a single one process and no optimization I can build the docs from scratch in a couple minutes.

HTML only or html+txt+epub+pdf?

**Comment by JulienPalard** [comment]
This is resolved, I'm closing the issue.

The 3.12 is not built yet, so the 3.12 links are currently 404ing, but they should land soon.
