### ISSUE TITLE
addition of error message for invalid statements in pep

### ISSUE THREAD

**Issue by vainaixr** [python/cpython#92672]
current scenario -

let us take PEP-572,

in 
https://peps.python.org/pep-0572/#scope-of-the-target
it has some code like this,
```
[[(j := j) for i in range(5)] for j in range(5)] # INVALID
[i := 0 for i, j in stuff]                       # INVALID
[i+1 for i in (i := stuff)]                      # INVALID
```

but it does not specify what error will be raised for these.

expected scenario -

the error message is also described in the pep.
so, the above would become,
```
[[(j := j) for i in range(5)] for j in range(5)] # INVALID
```
raises,
```
SyntaxError: assignment expression cannot rebind comprehension iteration variable 'j'
```
```
[i := 0 for i, j in stuff]                       # INVALID
```
raises,
```
SyntaxError: assignment expression cannot rebind comprehension iteration variable 'i'
```
```
[i+1 for i in (i := stuff)]                      # INVALID
```
raises,
```
SyntaxError: assignment expression cannot be used in a comprehension iterable expression
```

in case there are multiple statements which raise the same error message, then could use like,
```
statement_1 # INVALID
statement_2 # INVALID
```
both of the above raise,
```
error_type: error_message
```

motivation -

it becomes easier to reverse search, like if I get an error, then I could search for it in the pep, and the associated explanation.

**Comment by AlexWaygood** [comment]
PEPs are generally seen as historical documents, so changing them after they've been accepted is only generally done in exceptional circumstances. Nonetheless, if you have a suggestion regarding a specific PEP, you should raise it over at the PEPs repo rather than the CPython repo: https://github.com/python/peps (the PEPs are not hosted in this repository).

If you'd like to discuss a general change in policy for future PEPs, I recommend you start a discussion over at [discuss.python.org](https://discuss.python.org), probably in the "PEPs" category.
