### ISSUE TITLE
Upgrade bundled pip to 22.1 series

### ISSUE THREAD

**Issue by pradyunsg** [python/cpython#92688]
This is in the same vein as https://github.com/python/cpython/issues/91141. There has been a new pip release, and ensurepip's bundled wheels should be updated to the newer version of pip.

**Comment by pradyunsg** [comment]
Notably, due to https://github.com/pypa/pip/pull/11044, Python 3.11+ have a slightly different behaviour starting with pip 22.1.

**Comment by stefanor** [comment]
FWIW, the 22.1 series doesn't work for ensurepip, yet (pypa/pip#11183)

**Comment by uranusjr** [comment]
There are a lot of layers compounding to the ultimate issue, including

1. `pkg_resources` unconditionally ignores any metadata inside a `sys.path` item with suffix `.whl`. This ignore clause was originally intended for `PKG-INFO` metadata (according to in-code comments), but also got applied to `.dist-info` metadata without careful scrutiny.
2. `importlib.metadata` does not inherit this quirk.
3. `ensurepip` populates pip by running pip inside the wheel, a use case not supported by pip maintainers.
4. pip accidentally relied on the `pkg_resources` quirk to exclude itself from the installed packages, making installation process work.

So there are at least three ways we can fix this. But since running pip inside a wheel is not supported in the first place, I will first raise a PR to change `ensurepip` to extracting the wheel before running pip (matching how `get-pip.py` does this), which should resolve the issue. This also prevents people from getting a wrong idea from the stdlib, that pip actively supports being run inside a wheel.

**Comment by sbidoul** [comment]
22.2 is compatible with ensurepip (https://github.com/pypa/pip/pull/11217).
So I filed #95194 and this issue can be closed.

**Comment by kumaraditya303** [comment]
Superseded by https://github.com/python/cpython/issues/95194
