### ISSUE TITLE
PyUnicode_READ() fails to build on C++: _Py_CAST() used with a constant type (const void*)

### ISSUE THREAD

**Issue by da-woods** [python/cpython#92800]
**Bug report**

The new `_Py_CAST` macro (https://github.com/python/cpython/pull/91959/files, and other commits) designed to reduce C++ warnings adds a fairly significant restriction that wasn't there before

https://github.com/python/cpython/blob/9f68dab3d327335b938046c50b4f09944e993cc8/Include/pyport.h#L25-L26

The PyUnicode_READ macro casts to a const pointer

https://github.com/python/cpython/blob/9f68dab3d327335b938046c50b4f09944e993cc8/Include/cpython/unicodeobject.h#L341-L343

This is currently reported to be breaking Cython (https://github.com/cython/cython/issues/4790).

I'd propose a fix which removes the const requirement:

```
template <typename T>
struct _Py_add_const {
    typedef const T type;
};
#  define _Py_CAST(tp, expr) \
       const_cast<tp>(reinterpret_cast<_Py_add_const<tp>::type>(expr))
```

on C++11 you could use the standard library `std::add_cast` instead, at the cost of an extra include. However it isn't available on c++03.

I realise this adds an extra struct `_Py_add_const` to the namespace. I'm not sure if that's desired, or how it should be named. If that's acceptable I'm happy to submit a PR for this.

@vstinner 

**Your environment**

Current 3.11 branch

**Comment by tacaswell** [comment]
This issue is scattered across a couple of places (which may be my fault) here is an index of the relevant links:

 - original issue to clean up casts: https://github.com/python/cpython/issues/91320
 - first PR changing how casting was done: https://github.com/python/cpython/pull/91959 
 - issue to greenlets that was broken by the above https://github.com/python-greenlet/greenlet/issues/301
 - A PR to greenlets that fixes two issues from the above CPython change https://github.com/python-greenlet/greenlet/pull/302
 - An issue that was opened to track the const related issue https://github.com/python/cpython/issues/92135
 - a PR that fixed one of the greenlet compile issues https://github.com/python/cpython/pull/92138
 - a comment from @serge-sans-paille on how to fix this https://github.com/python/cpython/pull/92138#issuecomment-1116983125
 - the cython issue mentioned above cython/cython#4790

**Comment by vstinner** [comment]
> This is currently reported to be breaking Cython (https://github.com/cython/cython/issues/4790).

The C++ project scipy fails to build with:

```
/home/tcaswell/.pybuild/bleeding/include/python3.11/cpython/unicodeobject.h:409:57: error: duplicate ‘const’
  409 |     PyUnicode_READ(_Py_STATIC_CAST(int, kind), _Py_CAST(const void*, data), \
      |                                                         ^~~~~
```

Oh right, that's my fault, _Py_CAST() cannot be used with a const type. _Py_CAST() comment:

```
// The type argument must not be constant. For example, in C++,
// _Py_CAST(const PyObject*, expr) fails with a compiler error.
```

**Comment by vstinner** [comment]
Would you be able to test if https://github.com/python/cpython/pull/92872 fix scipy?

**Comment by tacaswell** [comment]
I can confirm that scipy (and a large fraction of the pydata stack) build with #92872 .

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/pull/92872 : thanks for the bug report!
