### ISSUE TITLE
TextIOBase: non-pythonic behaviour for tell() and seek()

### ISSUE THREAD

**Issue by mguinhos** [python/cpython#93101]
# **Enhance behaviour of tell() and seek() from TextIOBase**

**They are non-portable, non-pythonic, and can lead to undefined behaviour\***

(These changes should not impact older python scripts)

According to the documentation:
```
...
seek(offset, whence=SEEK_SET, /)
...
SEEK_SET or 0: seek from the start of the stream (the default); offset must either be a number returned by TextIOBase.tell(), or zero. Any other offset value produces undefined behaviour.
...
```
> Any other offset value produces undefined behaviour*
```
...
tell()
Return the current stream position as an opaque number. The number does not usually represent a number of bytes in the underlying binary storage.
...
```
> Return the current stream position as an opaque number

These funcions should not be part of the public API, because of misuse. (their behaviour is non-obvious)

**In the most common use cases we just want to get the current linear and flat index of the stream, not this weird non-pythonic cookie.**

They can be renamed to _tell() and _seek(), and should be replaced to safer version with proper checks, and previsible and flat return values.

**Comment by mguinhos** [comment]
Caused trouble with #93077

**Comment by mguinhos** [comment]
Also related with #93079

**Comment by ronaldoussoren** [comment]
It is not possible to have tell behave the way to like due to having some codecs that have more complex internal state and no 1-1 mapping between bytes read and characters read. The implementation in ``Lib/_pyio.py`` contains a clearer explanation than I could write myself:

```
        # The meaning of a tell() cookie is: seek to position, set the
        # decoder flags to dec_flags, read bytes_to_feed bytes, feed them
        # into the decoder with need_eof as the EOF flag, then skip
        # chars_to_skip characters of the decoded result.  For most simple
        # decoders, tell() will often just give a byte offset in the file.
``` 

BTW. I don't understand why you closed the previous issue about this and opened a new one. This fragments the discussion and makes it harder to follow.

**Comment by mguinhos** [comment]
> It is not possible to have tell behave the way to like due to having some codecs that have more complex internal state and no 1-1 mapping between bytes read and characters read. The implementation in `Lib/_pyio.py` contains a clearer explanation than I could write myself:
> 
> ```
>         # The meaning of a tell() cookie is: seek to position, set the
>         # decoder flags to dec_flags, read bytes_to_feed bytes, feed them
>         # into the decoder with need_eof as the EOF flag, then skip
>         # chars_to_skip characters of the decoded result.  For most simple
>         # decoders, tell() will often just give a byte offset in the file.
> ```
> 
> BTW. I don't understand why you closed the previous issue about this and opened a new one. This fragments the discussion and makes it harder to follow.

My proposal is to provide a safer abstraction to these functions, their old behaviour should be the same under the hood.
their positions and the cookie could be stored internally in a dictionary, 
{index: cookie}
and then, if we want to get back to that position we just seek(index) and it will traslate to that cookie internally...
something like that (this seems a bad approach, but it is just an example)

**Comment by mguinhos** [comment]
And, if we can't change tell() and seek().
We could simulate linear indexing with an wrapper like.

class IOCursour:
     def __init__(self, stream, cache=[], index=0):
         self.index = index
         self.cache = cache
         self.index = index

     def tell(self):
         ...

     def seek(self):
         ...

**Comment by ericvsmith** [comment]
It’s not clear what your proposal actually is. Would you be specifying offsets in bytes or characters? If bytes, what happens if you seek(3) on a UCS-2 file? If chars, how do you find the the correct position with a variable length encoding, like UTF-8?

it seems to me that no matter what you do, you can only get back to a position in the file that you’ve remembered before. That sounds like the existing seek and tell.

**Comment by mguinhos** [comment]
> It’s not clear what your proposal actually is. Would you be specifying offsets in bytes or characters? If bytes, what happens if you seek(3) on a UCS-2 file? If chars, how do you find the the correct position with a variable length encoding, like UTF-8?
> 
> it seems to me that no matter what you do, you can only get back to a position in the file that you’ve remembered before. That sounds like the existing seek and tell. 

This thing of remembering the old positions was just an examples, of how can we abstract this behaviour.

There are other approaches that can be taken to get the same result, without needing to remeber the previous cookie.

**Comment by mguinhos** [comment]
Also...

And the position would be by characters (we are talking about TextIOBase)

**Comment by ericvsmith** [comment]
You still haven’t described your proposal. 

What if you opened a UTF-8 file and immediately seeked to the millionth character. How would that work?

**Comment by mguinhos** [comment]
> You still haven’t described your proposal. 
> 
> What if you opened a UTF-8 file and immediately seeked to the millionth character. How would that work?

Why would this be a problem?

My proposal is to make tell and seek work with flat positions... just that...

Also, i dont know why you keep asking that, doesnt matter if it is UTF-8 or ascii, or whatever.

 My proposal is to provide a safer and simpler abstraction to the behaviour of both of these methods... just that... i am not repeating again

**Comment by mguinhos** [comment]
TextIOWrapper works with characters, period!
Independent of the encoding....

**Comment by mguinhos** [comment]
Again, my proposal is: "get rid of cookies, make tell() and seek() works with plain, flat, and obvious position values"

**Comment by mguinhos** [comment]
Again, my proposal is: "get rid of cookies, make tell() and seek() works with plain, flat, and obvious position values"

Handling files in python, should be as high level as python itself

**Comment by ericvsmith** [comment]
> Why would this be a problem?

Because you’d have to read the first million characters and decode them. Otherwise you wouldn’t know where the millionth character started. That doesn’t sound much like a seek operation to me. 

> Also, i dont know why you keep asking that, doesnt matter if it is UTF-8 or fixed size, or whatever.

it very much matters. You have not told me how you’d seek directly to the millionth character in a variable length encoded file. 

I’m going to close this issue. I suggest you discuss it on the Python-ideas mailing list (or on Discourse) to flush it out. If any proposal emerges, we can re-open this issue.

**Comment by mguinhos** [comment]
This question still doesnt makes sense.

 there is no use-case that needs to skip thousands of variable length characters.
Alo, this is also not possible with the currently seek() and tell(), and if it is, can you show me an working example?

**Comment by mguinhos** [comment]
This question still doesnt makes sense.

 there is no use-case that needs to skip thousands of variable length characters.
Alo, this is also not possible with the currently seek() and tell(), and if it is, can you show me an working example?

(It is not possible to skip to the nth character with a variable length encoding, this is not magic... it is variable length)

**Comment by mguinhos** [comment]
@erlend-aasland please, explanaiton for making as unplanned...

**Comment by erlend-aasland** [comment]
Quoting Eric Smith:

> I’m going to close this issue. I suggest you discuss it on the Python-ideas mailing list (or on Discourse) to flush it out. If any proposal emerges, we can re-open this issue.

**Comment by zware** [comment]
It seems to me that the real complaint here is that the docs mention "undefined behavior" because you can feed garbage to `seek()` and break things.  We could mitigate that by returning something other than a bare integer[^1] from `tell` and deprecating passing a bare integer to `seek`.  I don't know whether that's actually worth the effort to implement, though; the result of this "undefined behavior" is just surprising results from your next `read`, not a crash.

[^1]: probably just some private subclass of `int`, with no actual change in the behavior of `seek` or `tell`

**Comment by ericvsmith** [comment]
I don't think it's worth the hassle of changing. The net result is the same: you can only call `seek` with values returned by `tell`.

And we'll probably find that people pickle or otherwise save the values from `tell` and later call `seek`, then we have a backward compatibility issue.
