### ISSUE TITLE
Counter.__iadd__ can mutate the collection even if it throws

### ISSUE THREAD

**Issue by rotu** [python/cpython#93278]
**Bug report**

When using `Counter.__iadd__`, trying to add a complex number throws a `TypeError` but *still* mutates the collection.
Thereafter, every call to `__iadd__` also throws a `TypeError` because of the presence of this bad value.
Other types like `None` which cannot be added with an `int` don't seem to have this problem

```
from collections import Counter
c=Counter()
print(c) # Counter()
c+={0:0j}
print(c) # Counter({0: 0j})
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/dan/.pyenv/versions/3.10.4/lib/python3.10/collections/__init__.py", line 906, in __iadd__
>     return self._keep_positive()
>   File "/Users/dan/.pyenv/versions/3.10.4/lib/python3.10/collections/__init__.py", line 890, in _keep_positive
>     nonpositive = [elem for elem, count in self.items() if not count > 0]
>   File "/Users/dan/.pyenv/versions/3.10.4/lib/python3.10/collections/__init__.py", line 890, in <listcomp>
>     nonpositive = [elem for elem, count in self.items() if not count > 0]
> TypeError: '>' not supported between instances of 'complex' and 'int'

**Your environment**
Python 3.10.4 (main, May 12 2022, 18:19:00) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
MacOS Monterey, Apple M1

**Comment by rhettinger** [comment]
This may be aggravating, but it isn't a bug. 

Per the docs:

> The multiset methods are designed only for use cases with positive values. The inputs may be negative or zero, but only outputs with positive values are created. There are no type restrictions, but the value type needs to support addition, subtraction, and comparison.

Since complex numbers don't support comparison, a TypeError is appropriate.

MyPy is likewise unhappy with the code you provided:

`tmp.py:4: error: Argument 1 to "__iadd__" of "Counter" has incompatible type "Dict[int, complex]"; expected "Counter[Any]"`

FWIW, it is the norm that collections remain mutated even if the mutating operation ultimately raises an exception:

```
>>> s = set()
>>> s.update([2, 3, [4, 5], 6])
Traceback (most recent call last):
 ...
TypeError: unhashable type: 'list'
>>> s
{2, 3}
```

Mostly, this behavior is unavoidable.  Python collection updates don't have the notion of BEGIN TRANSACTION, ROLLBACK, and COMMIT.  That would be expensive and likely not add any real value.

Note that in your example, the Counter is left in a legal state.  You are allowed to store complex values but will lose the ability to use certain operations.  For non-orderable values, the docs say that you lose _elements()_, _most_common(),_ and the multiset operations.  Meanwhile, other operations are explicitly supported.  This is allowed:

```
>>> c = Counter()
>>> c['a'] += 3+4j
>>> c['a'] += 6+3j
>>> c['a']
(9+7j)

```

**Comment by rotu** [comment]
If it's a legal state to have incomparable entries, then I feel like either (1) the values shouldn't be inserted or (2) `TypeError` should be suppressed in `nonpositive`. It remains that `__iadd__` can mutate the object to a state where `__iadd__` no longer works.

At least with `set`, the TypeError would show up sooner when using `+`/`+=`, since the second operand must be a `set` and thus must have hashable elements by construction.

I understand the argument that this may be designed into a corner, as `Counter` has a bit of an identity crisis, simultaneously serving as a multiset, a linear combination, and an arbitrary mapping.

**Comment by rhettinger** [comment]
Thanks for the suggestion, but I will decline.  Neither suggestion makes sense to me.  The Counter is documented to not support multiset operations on non-comparable objects, so this isn't a bug.

I get that you don't like the way it fails, but it isn't reasonable to rewrite every multiset method to check for comparability prior to updating.  AFAICT this isn't a real and recurring problem in practice. It is rare to use complex numbers with Counter and rarer still to be using multiset operations at the same — as evidenced by Counter being 12 years old and no one having reported this before (possibly because it is documented not to work).

With respect to the "identity crisis", it was a day one decision (above my paygrade) that Counter be a subclass of dict and support arbitrary mappings.  From there, it was just a fact of life that some of the useful helper methods could support every possible input value.

**Comment by rotu** [comment]
Fair enough. Thank you for open-minded consideration! I appreciate your hard work!
