### ISSUE TITLE
IDLE and the interactive interpreter both wrongly reports a SyntaxError if no blank line after function definition.

### ISSUE THREAD

**Issue by stevendaprano** [python/cpython#93307]
See discussion [here](https://discuss.python.org/t/continued-invalid-syntax-for-print-function-please-help/16037). Note that the code sample sent by Ron was correctly formatted in email, but has lost all indentation in the Discuss website.

Rename the attached noblank.txt to noblank.py. (Github will not allow you to upload .py files!)

Run the renamed noblank.py file from the command line, e.g. `python3.10 noblank.py`. Note that it will run correctly from the vanilla Python interpreter. But it fails if copied and pasted into the interactive interpreter or IDLE.

**Steps to reproduce**

1. Launch IDLE, or the CPython interactive interpreter.
2. Copy the contents of noblank.py using your preferred text editor.
3. Paste it at the `>>>` prompt.
4. The interactive interpreter and IDLE both report a syntax error: `SyntaxError: invalid syntax`.

**Expected behaviour**

Preferably, the code should run and print "no blank" as it does in the non-interactive interpreter. If that is not possible, it should report a better error message, such as mentioning an unexpected outdent and suggesting that a blank line should be inserted.

- CPython versions tested on: 3.10 on Linux.

[noblank.txt](https://github.com/python/cpython/files/8790292/noblank.txt)

**Comment by aroberge** [comment]
This seems to be a bug in the `code` module, and not in IDLE per se.
```
>>> import code
>>> code.interact()
Python 3.10.2 ...
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> def noblank():
...     print("no blank")
... noblank()  # No blank line.
  File "<console>", line 3
    noblank()  # No blank line.
    ^^^^^^^
SyntaxError: invalid syntax
```

Tested in 3.6 to 3.11, and always got the same traceback.

**Comment by terryjreedy** [comment]
(Stephen, please don't put 3 line examples in a separate file.  Use a triple-backquoted block like Andre' did.)

In interactive mode, one must enter a *single statement* for each primary prompt.  The example has 2 statements.  Compound statements must be terminated with a blank.  From [Tutorial 3.2](https://docs.python.org/3/tutorial/introduction.html#first-steps-towards-programming):  "When a compound statement is entered interactively, it must be followed by a blank line to indicate completion (since the parser cannot guess when you have typed the last line)."    The error is correct.
