### ISSUE TITLE
Allow use of `python -m logging` to setup a basicConfig logging config

### ISSUE THREAD

**Issue by f0rk** [python/cpython#93557]
**Feature or enhancement**

Add support for `python -m logging`, which will call `basicConfig()`.

**Pitch**

When running code from the command line, it is often useful to see the logging output. If the code being run does not itself perform any logging config or setup any handlers, etc. it is necessary to edit the code to add such logic before it can be run.

**Comment by MayD524** [comment]
@vsajip I'm going to assume they want to capture either output, errors and user input? But that's really my only guess. If OP could give a little more info on that it'd be great.

**Comment by gst** [comment]
I understand it would be used to be able to call scripts/modules like this : 

```
python -m logging [eventual-logging-args] path/to/script.py
# or
python -m logging [eventual-logging-args] -m module_name
```

**Comment by MayD524** [comment]
That's my guess, I'm working on something that'd be easy to apply.

**Comment by vsajip** [comment]
Sorry, and thanks for the suggestion, but I think this is out of scope for `logging` itself to do - it's too opinionated (referring here to the implementation in the PR) to be of general use, which is what it needs to be to live in the stdlib. I suggest that this and the PR be closed. From what I can tell, this doesn't need to be in the stdlib itself  - it could be a separate script that invokes logging and calls a target script.

**Comment by MayD524** [comment]
While I do agree my implementation is opinionated, but it does give a useful base to give ```python -m``` supports to logging and gives a general access to the logging module.

**Comment by vsajip** [comment]
Yes, but my main objection is that I don't believe it belongs in the stdlib. I'll close this issue now, and I've already closed the PR. Thanks for your suggestions and for trying to improve `logging`; I suggest bringing this sort of thing up on [the Python discussion forum](https://discuss.python.org/) in `Ideas` first, before raising an issue / spending time on a PR. If you do this for something relating to logging, feel free to @-mention me so that I get pinged about the initial post.
