### ISSUE TITLE
`dpiawareness` for python windows installer

### ISSUE THREAD

**Issue by NewUserHa** [python/cpython#93706]
**Feature or enhancement**
`dpiawareness` for python windows installer
just found 3.10.5 has no `dpiawareness`.

**Comment by stevendaprano** [comment]
Does it need dpiawareness? Please explain why you think it needs it.

**Comment by NewUserHa** [comment]
because it looks blur on 4k monitors

**Comment by AA-Turner** [comment]
cc: @zooba 

Seems the OP is referring to https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process

(I am not afflicted by having a 4k monitor so can't reproduce -- standard 1080p here!)

A

**Comment by NewUserHa** [comment]
just checked that it seems python uses wixtoolset to build windows installer,
but it seems not support high dpi until wix.4.0 and which is currently in development

**Comment by zooba** [comment]
Yep, that's right, we're on WiX. We do have a custom bootstrapper app, but we aren't overriding the UI toolkit at all so I don't think we can do anything special here. Adding the flag now would just make us be tiny on 4K.

Unfortunately, I suspect the migration to WiX 4 will happen as soon as it possibly can, just because they're the source of many of our security issues (because installation is hard ;) ). But maybe we make more of an effort to get users onto the MSIX install anyway. Windows 11 is far more friendly towards sideloading than Win10 was, so it's more viable to have an even simpler experience.

**Comment by zooba** [comment]
Going to close this for now. I'm sure we'll get to it as part of the eventual WiX 4 migration, so there's nothing gained by keeping an extra issue around. Thanks for bringing it up!
