### ISSUE TITLE
Make `dict.pop` and `dict.get` "default"-argument a keyword argument

### ISSUE THREAD

**Issue by carlbordum** [python/cpython#93753]
**Feature or enhancement**

Make `dict` methods `pop` and `get` "default" a keyword argument.

**Pitch**

Code can be more readable.

```py
d.get(count, 0)

# vs

d.get(count, default=0)
```

**Previous discussion**

This was proposed last week on `python-ideas`:
https://mail.python.org/archives/list/python-ideas@python.org/thread/IFM3QL67EWQCROPIX3DNCR44F4ULMFD3/

If there's consensus, I'm up for implementing it.

**Comment by ericvsmith** [comment]
You’ll need to implement it and benchmark it before anyone would agree to include it in cpython.

**Comment by rhettinger** [comment]
I don't know it it is still true, but positional only APIs were faster than positional and keyword.   The *get()* API is very heavily used, we really don't want to make this even slightly slower.

Also, I question where there is any value to this at all.  These APIs are very old and widely used.  AFAICT, no one has ever asked for this.  I taught thousands for people to use get() and pop() and there was never any question about the meaning of the arguments.  So, we need some motivation for this change; otherwise, it doesn't actually make anything better.

**Comment by serhiy-storchaka** [comment]
Initially, positional only APIs were much faster than positional and keyword, because

1. For every keyword _parameter_ it created a new string object using the utf-8 decoder, calculated its hash, and looked up in the var-keyword dict. And it is for every call.
2. Either all parameters were positional-only, or all parameters were positional-or-keyword or keyword-only. It checked the name of parameter even for positional arguments.
3. `PyArg_Parse*` added an overhead for parsing format string for every call. Manual handling of keyword parameters were so complex, that nobody did it. Manual handling of positional-only parameters were manageable.
4. Calling a function with keyword arguments created a new dict.

Currently, a number of optimization is used:

1. You can now have positional-only parameters together with keyword parameters.
2. Python string objects and their hashes are cached between calls.
3. In most cases keyword arguments are passed not as a dict, but as two (usually short) arrays of names and values.
4. It only looks up for arguments passed as keywords.
5.  Argument and parameter names are interned, so comparison is often as cheap as comparing two pointers.
6. Argument Clinic no longer parses format string at run time. It generates a code as efficient as hand written code.

So I expect that supporting a keyword argument may add very little overhead. If it is true, I do not see an objection against it.

If we do this, we can also consider an idea of making the `key` argument of `OrderedDict.get()` positional-only, to harmonize it with `dict.get()`.

**Comment by rhettinger** [comment]
Aside from performance considerations, there is still question of whether this adds any value at all.  Sometimes keyword arguments improve readability and sometimes they degrade readability.   With ``sorted()`` we preclude ``sorted(iterable=data)`` because it reads better as ``sorted(data)``.  IMO, ``get()`` doesn't have a problem that needs to be solved. It is a heavily used API that has not caused confusion for either beginner or expert.  We really don't need to do this.

**Comment by rhettinger** [comment]
No one has stepped forward to champion this.  Marking as closed for the reason listed in the prior comment.

Thank you for the suggestion, but we'll pass on this one.
