### ISSUE TITLE
python-config.py fails if bindir is too long due to shebang overflow

### ISSUE THREAD

**Issue by ptsneves** [python/cpython#93759]
If python is built with a non standard location interpreter, it is possible the location of this interpreter has a string length which will cause issues on systems with shebang string length limitations. An example is in Linux systems where the maximum (!#) shebang size is defined in include/uapi/linux/binfmts.h and is 128 characters

This issue happens if python-config.py is invoked directly. The script will not even be executed by the operating system.

**Comment by ronaldoussoren** [comment]
The python-config.py script is only used on macOS, because the shell script variant that's used elsewhere won't work on macOS for various reasons.

This isn't easily fixed, something like "#!/usr/bin/env pythonX.Y" is not guaranteed to use the correct installation of Python and the script output matches a particular installation.

Longer term it might be possible to drop the requirement on the python variant of the script on macOS, but that requires some research and design work to do away with the customisation done in ``_osx_support.py`` (and it is not at all sure that this will be possible)

For now: Don't install Python into a deeply nested path (the limit appears to be about 512 bytes for the #! line on macOS).
