### ISSUE TITLE
Bug in Python 3 Name Mangling Mechanism (in Exception message)

### ISSUE THREAD

**Issue by dev1-dev2** [python/cpython#93787]
**Bug report**

**Impossible to get an attribute value by its mangled name with described conditions.**

Exception has wrong mangled name of private field (attribute name started with double-underscore).
```python
import unittest


class A:
    __var = 2


class TestMangledNamesUsage(unittest.TestCase):

    def test_wrong_mangled_name_in_exception_on_attempt_of_direct_access_to_private_var(self):
        # when trying to directly access a private field of an object, an exception is thrown containing
        # an incorrect mangled name of an attribute. Must be '_A__var' or "has no attribute '__var'"
        with self.assertRaises(AttributeError,
                               msg="'A' object has no attribute '_TestMangledNamesUsage__var'") as context:
            a = A().__var
        self.assertTrue("'A' object has no attribute '_TestMangledNamesUsage__var'" in str(context.exception),
                        msg="Wrong message.")

    def test_wrong_mangled_name_not_work(self):
        # the correct exception message is created here. there is no error accessing the private field.
        # this test is needed to show that THE ERROR is ONLY IN the EXCEPTION MESSAGE!
        with self.assertRaises(AttributeError,
                               msg="'A' object has no attribute '_TestMangledNamesUsage__var'") as context:
            a = A()._TestMangledNamesUsage__var
        self.assertTrue("'A' object has no attribute '_TestMangledNamesUsage__var'" in str(context.exception),
                        msg="Wrong message.")
```

**My environment**

macOS Monterey, Version 12.4, Chip Apple M1, 8 GB of memory. Python 3.9.2rc1

**Tested with GitHub Actions**

- CPython versions tested on: ["3.5", "3.6", "3.7", "3.8", "3.9", "3.10", "3.11-dev"]
- Operating system and architecture: [ubuntu-18.04, macOS-latest, windows-latest]

All versions in list are affected.

Full explanation with tests and examples in [my repository](https://github.com/dev1-dev2/python-name-mangling-bug)

**Comment by ericvsmith** [comment]
Are you suggesting that:
```python
class A:
    __var = 2

A().__var
```
Should give a message that `__var` does not exist? I think that would be misleading, too.

**Comment by sweeneyde** [comment]
I think this current behavior is correct:
```
>>> class A:
...     __var = 1
...
>>> class B:
...     A().__var
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in B
AttributeError: 'A' object has no attribute '_B__var'. Did you mean: '_A__var'?
```

See the docs [here](https://docs.python.org/3/reference/expressions.html#atom-identifiers) (emphasis mine)

> When an identifier that ***textually occurs in a class definition*** begins with two or more underscore characters and does not end in two or more underscores, it is considered a private name of ***that class***. Private names are transformed to a longer form before code is generated for them. The transformation inserts the class name, with leading underscores removed and a single underscore inserted, in front of the name. For example, the identifier `__spam` ***occurring in a class named `Ham` will be transformed to `_Ham__spam`***.

In other words, it's the current class definition where the code lives that determines the name mangling, not the type of the object whose attribute you're retrieving.

If that's not the behavior you want, then maybe name-mangled "private" attributes just aren't the right tool for your use-case.

**Comment by vyacheslavlobanov** [comment]
> > When an identifier that _**textually occurs in a class definition**_ begins with two or more underscore characters and does not end in two or more underscores, it is considered a private name of _**that class**_. Private names are transformed to a longer form before code is generated for them. The transformation inserts the class name, with leading underscores removed and a single underscore inserted, in front of the name. For example, the identifier `__spam` _**occurring in a class named `Ham` will be transformed to `_Ham__spam`**_.
> 
@sweeneyde In your example `__spam `is an attribute of `Ham` class/object. Mangled name should be `_Ham__spam`.
In my example it will not work, because while using `Unittest `mangled name will be `__TestMangledNameUsage__spam`.
**It is impossible to get a value by this name.** That's why it is a bug.

**Comment by ericvsmith** [comment]
Ah, I didn't realize that you're saying this problem is specific to unittest. I thought you were just using unittest just as a test runner.

Here's a working example that shows the issue I think you're raising. Let me know if I still misunderstand:
```python
import unittest

class A:
    __var = 2

class TestMangledNamesUsage(unittest.TestCase):
    def test(self):
        a = A().__var

unittest.main()
```
Output:
```
$ python issue-93787.py
E
======================================================================
ERROR: test (__main__.TestMangledNamesUsage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "issue-93787.py", line 8, in test
    a = A().__var
AttributeError: 'A' object has no attribute '_TestMangledNamesUsage__var'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```
Using `A()._A__var` works, as expected. This issue is just the class name used in the AttributeError message, correct?

At first glance, it does seem the AttributeError should say "... no attribute '_A__var'".

**Comment by ericvsmith** [comment]
Note the same behavior exists without instantiating an `A` object. Use `A.__var` instead of `A().__var`.

**Comment by vyacheslavlobanov** [comment]
> Let me know if I still misunderstand:
>
> AttributeError: 'A' object has no attribute '_TestMangledNamesUsage__var'
> 
> Using `A()._A__var` works, as expected. 

These two similar examples shows that it is not a Unittest problem only:

```python

class B:  # Still wrong message. Should be '_A__var', because self.a is an attribute and instance os A, but not B instance
              # or should be Error message with not mangled name.
    a = A()

    def test_1(self):
        a = self.a.__var  # AttributeError: 'A' object has no attribute '_B__var'
        return a

    def test_2(self):
        a = self.a._A__var  # return 2
        return a


class C(A):  # Correct, because of inheritance. As documented.

    def test_1(self):
        a = self.__var  # AttributeError: 'C' object has no attribute '_C__var' 
        return a
```
RESULT: these messages misleading enough.

**Comment by ericvsmith** [comment]
Thanks for the example! That's very helpful.

Here's a simple reproducer:
```python
class A:
    __var = 2

class B:
    @staticmethod
    def test():
        print(A._A__var)
        print(A.__var)

B.test()
```
Output:
```
$ python issue-93787.py
2
Traceback (most recent call last):
  File "issue-93787.py", line 10, in <module>
    B.test()
  File "issue-93787.py", line 8, in test
    print(A.__var)
AttributeError: type object 'A' has no attribute '_B__var'
```
It does seem that the AttributeError should use `_A__var` as the reported attribute name, since accessing that attribute via `_A__var` does in fact work (on the previous line).

**Comment by vyacheslavlobanov** [comment]
@ericvsmith We understand each other better now. Is there anything we can do to bring more benefit with this example?

**Comment by ericvsmith** [comment]
@vyacheslavlobanov Unfortunately I've never used mangled attribute names, and I don't know if this is a deliberate decision, or an accident of how the implementation works. Maybe it would be a good idea to find where in the code this error is being generated, and see if any comments there clarify things.

After that, the next step is to get a broader discussion. Maybe bring it up on discuss.pytyhon.org somewhere? Or the python-dev mailing list.

**Comment by sweeneyde** [comment]
Name mangling occurs [in the compiler](https://github.com/python/cpython/blob/274769c61c5f3f3d2d749824cbed26e15813ce14/Python/compile.c#L1489). Any identifier that begins with two underscores and does not end with two underscores in the body of a class definition is just replaced with a mangled version, statically when the Python code is compiled to bytecode, as if you had just written the mangled name instead, mangled with the name of the current enclosing class.

So
```python
class A:
    def f(x):
        # doesn't matter what the type of x is
        x.__secret = 42

from dis import dis
dis(A.f)
```
shows this bytecode (in py3.11):
```python
  2           0 RESUME                   0

  3           2 LOAD_CONST               1 (42)
              4 LOAD_FAST                0 (x)
              6 STORE_ATTR               0 (_A__secret)  # The code doesn't even think about "__secret"
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE
```

So the bytecode interpreter doesn't even know that it's dealing with a mangled name, it just treats it as any other attribute lookup. So *any* time you use the name `__x` in a class, it gets textually find-and-replaced with `_Classname__x`. Once you know how it works, it's a fairly straightforward rule with a consistent mental model, albeit confusing before you know how it works.

More examples of this in action:
```python
from types import SimpleNamespace
ns = SimpleNamespace(_A__x=1, _A__y=2)
class A:
    print(ns.__x, ns.__y) # exactly the same meaning as print(ns._A__x, ns._A__y)
# prints: 1 2

class B:
    __x = 24
    print(locals())
# prints {'__module__': '__main__', '__qualname__': 'B', '_B__x': 24}
```

Recent (Python 3.10 and 3.11) changes to error messages, independent of any name mangling worries, may have already made things more helpful as well, underlining the problem expression with `^^^` and offering a `Did you mean...`:

```
# tester.py
class A:
    __var = 1

class B:
    def __init__(self, a):
        self.__var = a.__var

a = A()
b = B(a)
```
``` 
Traceback (most recent call last):
  File "C:\Users\sween\Source\Repos\cpython2\cpython\tester.py", line 9, in <module>
    b = B(a)
        ^^^^
  File "C:\Users\sween\Source\Repos\cpython2\cpython\tester.py", line 6, in __init__
    self.__var = a.__var
                 ^^^^^^^
AttributeError: 'A' object has no attribute '_B__var'. Did you mean: '_A__var'?
```

In particular, someone encountering this error message will see that (1) the expression that raised the error was `a.__var`, (2) that expression attempted to lookup the attribute `_B__var` (so some name mangling was going on), and (3) there was a similar-looking name that could have been successfully looked up instead. So I think the current error message does a pretty decent job of summarizing the situation.

How would you like that error message to be different? Even if we wanted to tweak something about this error message only for mangled names, that poses an architectural challenge as the bytecode would then have to know which of its names came from mangling, or add a special bytecode or something, which is too much complexity for only marginal, if any, improvement.

> In my example it will not work, because while using Unittest mangled name will be __TestMangledNameUsage__spam.
It is impossible to get a value by this name.

I'm unsure of what exactly you mean here (what is "this name"?), but you *can* access attributes from one class that have been mangled by another:
```
class A:
    __var = 1

class B:
    print(A._A__var)

# prints: 1
```

You can even access unmangled double-underscore names if you use strings instead of identifiers:

```
# It's ill-advised to use variable names like this,
# but even if you do, that is still *some* way to get at them
__myglobal = 17
class A:
    print(globals()["__myglobal"])
# prints: 17
```

**Comment by sweeneyde** [comment]
Similarly to that last example, but for an object rather than the global namespace:
```
>>> class A:
...     pass
... 
>>> a = A()
>>> a.__var = 42
>>> 
>>> class B:
...     print(a.__dict__['__var'])
... 
42
```

**Comment by vyacheslavlobanov** [comment]
Mangled names should be equal in the code and Exception message.

**Comment by sweeneyde** [comment]
> Mangled names should be equal in the code and Exception message.

I'm assuming you mean that something like `class B: tuple.__foo` should show `type object 'tuple' has no attribute '__foo'` instead of the current message `type object 'tuple' has no attribute '_B__foo'`.

If that's the case, I disagree because that does not reflect the semantics of name-mangling: `class B: a.__foo` doesn't look up the `'__foo'` attribute, it looks up the `'_B__foo'` attribute:

```python
class A:
    def __getattr__(self, attr_name):
        print(f"looking up {attr_name}")
a = A()
class B:
    a.__foo

# prints: looking up _B__foo
```

**Comment by ericvsmith** [comment]
The more I think about this, the more I realize @sweeneyde is correct, and there's nothing to fix here. It's working as expected.

**Comment by iritkatriel** [comment]
Thank you, interesting discussion.
