### ISSUE TITLE
Embeddable Python for Windows doesn't find modules to import like the normal Python

### ISSUE THREAD

**Issue by yasarabio** [python/cpython#93875]
Dear Python team,

while trying to replace a normal Python distribution with the embeddable Python for Windows...
https://docs.python.org/3/using/windows.html#the-embeddable-package
...I noted that 'import' doesn't seem to find user-provided modules.

Built-in modules work fine, e.g.

import os,string

is OK. But if I have two modules 'foo.py' and 'bar.py' in the same folder, and foo.py does

import bar

then the import fails if I run foo.py, it cannot find bar. This works fine with a normal Python installation, since searching the folder that contains the importing module for imported modules seems to be the normal behavior...

Many thanks for your help and insight,
Elmar

**Comment by eryksun** [comment]
The embeddable distribution contains a "._pth" file (e.g. "python310._pth"). The presence of this file enables isolated mode, and its contents sets `sys.path`. See [finding modules](https://docs.python.org/3.10/using/windows.html#finding-modules).

**Comment by eryksun** [comment]
Relative paths in a "._pth" file are resolved against the parent directory of the "._pth" file. Since isolated mode is enabled, the directory of an executed script doesn't get prepended to `sys.path`; the current working directory doesn't get prepended to `sys.path` for the REPL shell or `-c` commands;  and `PYTHONPATH` and registry paths are ignored. Directories outside of the parent directory of the "._pth" file have to be added manually. You could remove the "._pth" file to get the non-isolated `sys.path` of a normal installation, or maybe a [nuget.org package](https://docs.python.org/3/using/windows.html#the-nuget-org-packages) or a [PyInstaller](https://pypi.org/project/pyinstaller/) bundled application is better suited to your needs.

**Comment by t1m013y** [comment]
Adding current working directory to `sys.path` without disabling isolated mode can be done by adding the following code to `Lib\site-packages\sitecustomize\__init__.py` (or any other location where python can find `sitecustomize` module):

```python
import sys
sys.path.insert(0, '.')
```
