### ISSUE TITLE
"Using Python on Mac" page is outdated

### ISSUE THREAD

**Issue by pradyunsg** [python/cpython#93987]
Coming from https://mail.python.org/archives/list/docs@python.org/thread/XEMCNFIXKCFZKIWV5GRLFFJZCWWK3FYQ/

The "Using Python on Mac" documentation page (Doc/using/mac.rst) is significantly out of date and has various issues arising out of this:

- It mentions that macOS comes with Python 2.7 by default, but that [it was removed in 12.3](https://www.macrumors.com/2022/01/28/apple-removing-python-2-in-macos-12-3/)
- It discusses universal binaries (used during the PowerPC -> Intel transition) but not the universal2 binaries (the ongoing Intel -> ARM transition).
- It consistently refers to "MacPython", which seems to be the historical name used? It's likely clearer to say Python on macOS today, so that's likely a worthwhile update.
- It refers to IDLE as "IDE". :)
- It suggests doing `python setup.py install`, something that [the setuptools developers actively discourage and want users to move away from](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html).

**Comment by ezio-melotti** [comment]
See also:
* https://github.com/python/cpython/issues/80086
  * https://github.com/python/devguide/issues/453
    * https://github.com/python/devguide/pull/454
* https://github.com/python/cpython/issues/93658
  * https://github.com/python/devguide/pull/891
* https://github.com/python/cpython/issues/93659
  * https://github.com/python/devguide/pull/893

**Comment by pradyunsg** [comment]
Those all seem to be about the building of CPython on macOS. This is a separate page, intended for “how to use Python on macOS”.

**Comment by ezio-melotti** [comment]
It seems there are at least 3 files related to macOS:
* https://github.com/python/cpython/blob/3.10/Doc/using/mac.rst
* https://github.com/python/cpython/blob/3.10/Mac/README.rst
* https://github.com/python/devguide/blob/main/setup.rst#macos-and-os-x

The third file was recently updated (by some of the issues I linked) with information that might (or might not) be relevant.  One of those issues also suggested to update the second file (python/devguide#453).  This issue is about the first file, but since there might be some overlapping between these files, it would be good to compare and update all of them, possibly in separate issues.

**Comment by hugovk** [comment]
"Using Python on a Mac" (`Doc/using/mac.rst`) was recently updated in https://github.com/python/cpython/pull/115024 and https://github.com/python/cpython/pull/117059.

I think we can close this now.
