### ISSUE TITLE
`__name__ must be set to a string object` when using `unittest.mock.patch()` with `autospec=True`

### ISSUE THREAD

**Issue by criskurtin** [python/cpython#94190]
## Basic information

Python version: `3.7.12`
Caused inside `unittest` library
Occurs when calling this inside an async test function:
```python
with patch("path.to.class.to.mock", autospec=True):
    # do something while the object is patched...
```
  
## Details

When trying to mock an instance of a fairly complex class with autospec, an exception occurs on [this line](https://github.com/python/cpython/blob/8a34afd55258c721e446d6de4a70353c39a24148/Lib/unittest/mock.py#L127) while copying `__name__` property of one of the methods.

upon closer inspection, it seems that string is expected as a value of `__name__` (as one would assume), but at this point, `__name__` attribute is already a MagicMock object.

What is shown in the screenshot below is the current value of `func.__name__` (`func -> special variables -> __name__`)

![image](https://user-images.githubusercontent.com/36190893/175386267-3efb847b-2b6c-4a07-b8e0-559ab432210e.png)

This exception causes a test to fail while autospeccing. Any ideas on why this is happening? Is it the fact that MagicMock does its job too good and too early? :sweat_smile:

**Comment by criskurtin** [comment]
Closing because the problem is not in the `unittest` lib after all.

**Comment by petioptrv** [comment]
For the next person that ends up on this page looking for the answer, in our case, it was due to a mock that we were starting in the `setUp` function and destroying in the `tearDown` function, but the `setUp` function was failing, which meant that the `tearDown` was never called and next time around the `tearDown` was called it tried to patch a patched object.
