### ISSUE TITLE
urllib.request missing `HTTPError` in `__all__` causing type checker to nag

### ISSUE THREAD

**Issue by ewerybody** [python/cpython#94204]
**Bug report**

I'm using `request` from the standard `urllib` like so:
```py
from urllib import request

try:
    data = request.urlopen('http://blaaaa').read()
except request.HTTPError as error:
    raise RuntimeError('Could not get data from address!\n%s' % error) from error
```
And my typechecker tells me:
```
"HTTPError" is not a known member of module
```
Indeed `HTTPError` is explicitly imported here
https://github.com/python/cpython/blob/d435a18c537a62a89a70005885e6e09f58997d8a/Lib/urllib/request.py#L101

but it's missing in the `__all__` statement here:
https://github.com/python/cpython/blob/d435a18c537a62a89a70005885e6e09f58997d8a/Lib/urllib/request.py#L126

Probably also causing `typeshed` to import it [here](https://github.com/python/typeshed/blob/64d91ef41472417cb3bb80384af9cc451d9fe78b/stdlib/urllib/request.pyi#L10) and [not having it in the `__all__` statement](https://github.com/python/typeshed/blob/64d91ef41472417cb3bb80384af9cc451d9fe78b/stdlib/urllib/request.pyi#L36) as well.
... causing my type checker to complain :)

**Suggestion**

As `HTTPError` is **the** exception thrown on typical 404 url-request I'd have it in the list of exposed objects so that code is not complained about.

**Questions**

Is there a reason that it's missing?
Would we need to fix it on `typeshed` as well or is that rather automated?
Is a tiny PR about that welcomed?

**Comment by AlexWaygood** [comment]
> Probably also causing `typeshed` to import it [here](https://github.com/python/typeshed/blob/64d91ef41472417cb3bb80384af9cc451d9fe78b/stdlib/urllib/request.pyi#L10) and [not having it in the `__all__` statement](https://github.com/python/typeshed/blob/64d91ef41472417cb3bb80384af9cc451d9fe78b/stdlib/urllib/request.pyi#L36) as well.

FWIW, we're quite happy to re-export things in the stub over at typeshed if the lack of re-export is causing problems for users. Feel free to open a PR over at typeshed (all that's needed is to change the `from urllib.error import HTTPError` line to `from urllib.error import HTTPError as HTTPError`, and type checkers will understand the symbol as being re-exported from the stub).

It might _also_ be a good idea to add it to `__all__` at runtime (I have no opinion on that). If it is added to `__all__` at runtime, we can add it to `__all__` in the typeshed stub as well :)

**Comment by ewerybody** [comment]
Thanks @AlexWaygood !
True, when making the stub import
```py
from urllib.error import HTTPError as HTTPError
```
the problem already goes away. But `pylint` is nagging about 😄
```
Import alias does not rename original package
pylint(useless-import-alias)
```
But what's meant with "_add it to `__all__` at runtime_"? Somewhat conditionally? Like this one?
https://github.com/python/cpython/blob/d435a18c537a62a89a70005885e6e09f58997d8a/Lib/urllib/request.py#L1395

Might be the `typeshed` change is really the least intrusive solution. 👍 I'll put it together.

**Comment by AlexWaygood** [comment]
> But `pylint` is nagging about 😄
> 
> ```
> Import alias does not rename original package
> pylint(useless-import-alias)
> ```

We don't run pylint in typeshed's CI, so that shouldn't be an issue!

> But what's meant with "_add it to `__all__` at runtime_"?

Runtime = CPython. Stubs = typeshed. Type checkers only know about the stubs, they don't know anything about the runtime. But if you do a check at runtime like `if "HTTPError in urllib.request.__all__`, it's only what exists at runtime that matters, the stub is irrelevant.

In typeshed we try to mimic the runtime as closely as possible, though, so we wouldn't add it to `__all__` in typeshed unless it exists in `__all__` at runtime.

**Comment by ewerybody** [comment]
Ok. gotcha. Since this is not a runtime issue > typeshed 👍

**Comment by hauntsaninja** [comment]
My thoughts (as a typeshed maintainer):

- Is `HTTPError` intended to be part of the API of `urllib.request`?
Probably not. It seemed pretty intentional to break apart functionality into different modules during the Python 2 to Python 3 transition. This is also reflected in the fact that `HTTPError` is not currently in `urllib.request`'s `__all__`.

- Should we add `HTTPError` to `urllib.request.__all__`?
No, because, as above, it's probably not intended to be part of the API of `urllib.request`. I also strongly dislike reexporting symbols from a sibling module. So I'm closing this issue — I don't think CPython should be making changes here.

Okay, so no CPython change, but should we still make the change in typeshed? Usually I'd argue no, but I think this is somewhat an exceptional case, and I'd be fine with doing so.

- Why am I fine with reexporting in typeshed?
It's an implementation detail that `urllib.request` imports `bisect`. Similarly, it's an implementation detail that `urllib.request` imports `HTTPError`. In theory this could change at any time, which is why type checkers complain about reexports. 
BUT this is an exceptional case in that this import happens to be widely depended on (https://grep.app/search?q=urllib.request.HTTPError) — widely enough that CPython would likely not be able to remove its import of `HTTPError` (e.g. by using fully qualified `urllib.error.HTTPError` everywhere) because it would break too many people. typeshed generally tries to avoid false positives and meet users where they use a given module.
