### ISSUE TITLE
Deprecate typing.Hashable/Sized

### ISSUE THREAD

**Issue by Numerlor** [python/cpython#94309]
[`typing.Hashable`](https://docs.python.org/3/library/typing.html#typing.Hashable) and [`typing.Sized`](https://docs.python.org/3/library/typing.html#typing.Sized) are aliases to their equivalents in the [`collections.abc module`](https://docs.python.org/3/library/collections.abc.html#collections.abc.Hashable); [PEP 585](https://peps.python.org/pep-0585/) deprecated all aliases like these while aiming to remove the duplication between the two modules, but the aforementioned two seem to have been left out of that because they're not generic.

If the others are deprecated, I don't think it makes sense to keep them when they're just aliases that provide no additional functionality

### Linked PRs
* gh-112196
* gh-112200

**Comment by Fidget-Spinner** [comment]
I'm +1 for deprecating them too. Before that, I'm interested as to why we have these aliases in typing? Are they just for convenience? Searching commit history, I think @gvanrossum might have an idea.

**Comment by AlexWaygood** [comment]
> Are they just for convenience?

According to PEP 484, yup! For both Sized and Hashable, PEP 484 states that they are "not generic, but present [in the proposed new typing module] for completeness": https://peps.python.org/pep-0484/#the-typing-module

**Comment by MonadChains** [comment]
Hi, I'm new to the Python codebase, and I would like to contribute to it. I have a question about this issue: what is the deprecation procedure for the aliases? According to PEP 585, the deprecated aliases should not trigger any `DeprecationWarning` and only type checkers should warn of their usage. So I'm not sure what are exactly the changes needed.

**Comment by JelleZijlstra** [comment]
I think we should just add a deprecation notice in the docs, similar to that for `typing.Iterable` and similar. We don't need any runtime behavior change.

**Comment by Fidget-Spinner** [comment]
@MonadChains thanks for your interest in contributing. Here's what you have to do after cloning cpython.
1. Go to /Doc/library/typing.rst.
2. Copy one of the `.. deprecated::` notices and paste it under the appropriate sections those types. Edit the text saying to use the type in `collections.abc`
3. Build the documentation with either `make html` or `./Doc/make.bat html`. View the html output in `./Doc/build/`.
4. The file uses reStructuredText for documentation. I suggest reading [this guide](https://devguide.python.org/documenting/) as there may be surprising things to beginners (such as indents using 3 spaces instead of 4!).

**Comment by AlexWaygood** [comment]
Fixed in #94626. Thanks @MonadChains! 🎉

**Comment by AlexWaygood** [comment]
Reopening as per https://github.com/python/cpython/pull/94626#issuecomment-1179779042

**Comment by MonadChains** [comment]
> Reopening as per [#94626 (comment)](https://github.com/python/cpython/pull/94626#issuecomment-1179779042)

I've opened a new pull request to add the missing part.
