### ISSUE TITLE
'last_value' attribute from sys module throws an error while accessing it

### ISSUE THREAD

**Issue by nvdsuman** [python/cpython#94356]
**Bug report**

In the sys module, it clearly shows that it has 'last_value' attributes. But when I am accessing it, it throws an error. And even Error is not consistent.  Sometimes it shows different error messages.

>>> dir(sys)
['__breakpointhook__', '__displayhook__', '__doc__', '__excepthook__', '__interactivehook__', '__loader__', '__name__', '__package__', '__spec__', '__stderr__', '__stdin__', '__stdout__', '__unraisablehook__', '_base_executable', '_clear_type_cache', '_current_frames', '_debugmallocstats', '_framework', '_getframe', '_git', '_home', '_xoptions', 'abiflags', 'addaudithook', 'api_version', 'argv', 'audit', 'base_exec_prefix', 'base_prefix', 'breakpointhook', 'builtin_module_names', 'byteorder', 'call_tracing', 'callstats', 'copyright', 'displayhook', 'dont_write_bytecode', 'exc_info', 'excepthook', 'exec_prefix', 'executable', 'exit', 'flags', 'float_info', 'float_repr_style', 'get_asyncgen_hooks', 'get_coroutine_origin_tracking_depth', 'getallocatedblocks', 'getcheckinterval', 'getdefaultencoding', 'getdlopenflags', 'getfilesystemencodeerrors', 'getfilesystemencoding', 'getprofile', 'getrecursionlimit', 'getrefcount', 'getsizeof', 'getswitchinterval', 'gettrace', 'hash_info', 'hexversion', 'implementation', 'int_info', 'intern', 'is_finalizing', 'last_traceback', 'last_type', '**last_value**', 'maxsize', 'maxunicode', 'meta_path', 'modules', 'path', 'path_hooks', 'path_importer_cache', 'platform', 'prefix', 'ps1', 'ps2', 'pycache_prefix', 'set_asyncgen_hooks', 'set_coroutine_origin_tracking_depth', 'setcheckinterval', 'setdlopenflags', 'setprofile', 'setrecursionlimit', 'setswitchinterval', 'settrace', 'stderr', 'stdin', 'stdout', 'thread_info', 'unraisablehook', 'version', 'version_info', 'warnoptions']

>>> **sys.last_value
ValueError("invalid literal for int() with base 10: 'inf'")**

>>> **sys.last_value
AttributeError("module 'sys' has no attribute 'last_value'")**

**Your environment**

>>> sys.version
'3.8.9 (default, Jul 19 2021, 09:37:32) \n[Clang 13.0.0 (clang-1300.0.27.3)]'
>>>

**Comment by ericvsmith** [comment]
What do you want to use it for? Have you looked at the documentation for it? The docs say it is not always defined.

**Comment by stevendaprano** [comment]
You are misinterpreting what you are seeing.

Accessing `sys.last_value` isn't **raising an exception** (there is no traceback). It is returning the last exception object that has been raised.

```
>>> 1/0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>> x = sys.last_value
>>> print(x, type(x))
division by zero <class 'ZeroDivisionError'>
```

So a fresh interpreter session that has had no exceptions raised will not have `last_value` defined at all. Once an exception has been raised, then it will be defined, but it will change from time to time as new exceptions are raised, because it shows *the last exception value*, although the [docs](https://docs.python.org/3/library/sys.html#sys.last_type) could do a better job of saying so explicitly.

By the way, the program output that you included in your bug report was not a genuine, unedited copy-and-paste. It looks like it is out of order and modified from the real output. That's okay so long as it doesn't change the meaning of the output, but in this case it does.

I think this bug report should be changed to a documentation enhancement. What do you think @ericvsmith ?

**Comment by ericvsmith** [comment]
@stevendaprano : I agree that the documentation could be a little clearer on what the 3 `sys` values `last_type`, `last_value`, and `last_traceback` represent. In addition to pointing back to `exc_info()`, a short description of their meanings would be helpful.

**Comment by iritkatriel** [comment]
Note that exc_info is "legacy" now. sys.exception() is all you really need (the rest of sys.exc_info() is redundant).

**Comment by nvdsuman** [comment]
Thanks, @stevendaprano for the clarification. The output I mentioned in the description is not continuous. I have pasted it to explain why it is giving a different error message at a different time as I was not knowing.
