### ISSUE TITLE
frame.setlineno has serious flaws.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#94438]
The `frame_setlineno` function works in in stages:
* Determine a set of possible bytecode offsets as targets from the line number. 
* Compute the stack state for these targets and the current position
* Determine a best target. That is, the first one that has a compatible stack.
* Pop values form the stack and jump.

The first steps is faulty (I think, I haven't demonstrated this) as it might be possible to jump to an instruction involved in frame creation. This should be easy to fix using the new `_co_firsttraceable` field.

The second step has (at least) three flaws:

- [x] It does not account for `NULL`s on the stack, making it possible to jump from a stack with `NULL`s to one that cannot handle `NULL`s.
- [x] It does not skip over caches, so could produce incorrect stacks by misinterpreting cache entries as normal instructions.
- [x] It is out of date. For example it thinks that `PUSH_EXC_INFO` pushes three values. It only pushes one.

Setting the line number of a frame is only possible in the debugger, so this isn't as terrible as might appear, but it definitely needs fixing.

### Linked PRs
* gh-111237
* gh-111243
* gh-111338
* gh-111341
* gh-111369

**Comment by pablogsal** [comment]
Moving this back to release blocker.

**Comment by iritkatriel** [comment]
> It does not skip over caches, so could produce incorrect stacks by misinterpreting cache entries as normal instructions.

I'm assuming this refers to the mark_stacks loop again, which is where stacks are produced. 

The good news is that it looks like it just happens to work by accident. There is no case in the switch for the CACHE opcode, so it goes to the default case. Since the stack_effect of CACHE is 0, it just copies ``stack[i]`` to ``stack[i+1]`` unchanged. So the stack that is supposed to be on the next instruction will propagate as is until the first non-cache entry. 

We could make it more explicit like this:

```
diff --git a/Objects/frameobject.c b/Objects/frameobject.c
index 34a6c46c6b..ccdf7de990 100644
--- a/Objects/frameobject.c
+++ b/Objects/frameobject.c
@@ -220,6 +220,11 @@ mark_stacks(PyCodeObject *code_obj, int len)
             }
             opcode = _Py_OPCODE(code[i]);
             switch (opcode) {
+                case CACHE:
+                {
+                    stacks[i+1] = stacks[i];
+                    break;
+                }
                 case JUMP_IF_FALSE_OR_POP:
                 case JUMP_IF_TRUE_OR_POP:
                 case POP_JUMP_FORWARD_IF_FALSE:
```
 
thoughts?

**Comment by sweeneyde** [comment]
> There is no case in the switch for the CACHE opcode, so it goes to the default case.

Don't cache entries get populated at specialization time with data that overwrites the CACHE opcode? I don't think we're keeping around 0s in the bytecode that aren't subject to change. If I'm understanding right, the problem comes from misinterpreting that specialized cache data as if it's some bytecode that has a stack effect.

It looks like the dis module looks up `_inline_cache_entries[deop]` to determine how many cache entries to skip over. Would that work here?

**Comment by iritkatriel** [comment]
Ah I see!  Would you like to try? (I'm signing off for the night soon.)

**Comment by sweeneyde** [comment]
I don't think I'm going to have time in the next couple of days to come up with a decent test case and PR and everything, but I am thinking that something vaguely like this could work:

```diff
@@ -213,12 +213,15 @@ mark_stacks(PyCodeObject *code_obj, int len)
     int todo = 1;
     while (todo) {
         todo = 0;
-        for (i = 0; i < len; i++) {
+        int ncaches;
+        for (i = 0; i < len; i += (1 + ncaches)) {
+            ncaches = 0;
             int64_t next_stack = stacks[i];
             if (next_stack == UNINITIALIZED) {
                 continue;
             }
-            opcode = _Py_OPCODE(code[i]);
+            opcode = _PyOpcode_Deopt[_Py_OPCODE(code[i])];
+            ncaches = _PyOpcode_Caches[opcode];
             switch (opcode) {
                 case JUMP_IF_FALSE_OR_POP:
                 case JUMP_IF_TRUE_OR_POP:
```

**Comment by brandtbucher** [comment]
> It does not skip over caches, so could produce incorrect stacks by misinterpreting cache entries as normal instructions

@iritkatriel is correct... nothing needs to be done about this. `mark_stacks` uses `_PyCode_GetCode`, which produces a "deoptimized" byte string equivalent to `.co_code` attribute access. Otherwise, we would need cases in this switch for all of the adaptive forms of these instructions.

So I think this issue can be closed?

**Comment by sweeneyde** [comment]
Ah, my mistake, I missed the `_PyCode_GetCode`.

**Comment by brandtbucher** [comment]
Reopening because extended arguments aren't handled correctly. :(

**Comment by brandtbucher** [comment]
Removing release blocker status since all known crashes are fixed.

I'm still going to leave this open, thoough, since the four "is None" jumps aren't handled yet (which just means that we aren't able to jump to some valid locations).

**Comment by brandtbucher** [comment]
Yep. See my above comment. :)

**Comment by iritkatriel** [comment]
ah yeah :)

**Comment by gvanrossum** [comment]
Shall we nevertheless close this, and open a more specific issue?

**Comment by markshannon** [comment]
Yes.
Most, if not all, of the flaws I listed have been fixed.
