### ISSUE TITLE
list inside list multiply index bug

### ISSUE THREAD

**Issue by TheSharkysNL** [python/cpython#94718]
if you create a list like this `list_inside_list = [[0]*3]*3` and then change a index like so `list_inside_list[0][1] = 1` when you go and print it the output will be `[[0, 1, 0], [0, 1, 0], [0, 1, 0]]` but it should be this `[[0, 1, 0], [0, 0, 0], [0, 0, 0]]`

- CPython versions tested on: 3.10
- Operating system and architecture: Windows 10 x64

**Comment by JelleZijlstra** [comment]
The list multiplication copies the elements in the list by identity, so you end up with three references to the same list. This is explicitly documented under footnote 2 at https://docs.python.org/3.10/library/stdtypes.html#sequence-types-list-tuple-range.

**Comment by stevendaprano** [comment]
List "multiplication" is called **repetition** in [the documentation](https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range), because it *repeats* the objects, it does not copy them. So this feature is working as designed, even if it is sometimes surprising.

@JelleZijlstra I don't know what you mean by "copies by identity". The point here is that the objects **aren't** copied. The link you reference explicitly says "Note that items in the sequence s are not copied".
