### ISSUE TITLE
Replacing %-formatting and string concatenation with f-strings in platform module

### ISSUE THREAD

**Issue by Nougat-Waffle** [python/cpython#94713]
A simple rewriting of some of the code to be more modern. Replacing %-formatting and string concatenation with f-strings and replacing `while 1` with `while True`.

**Comment by stevendaprano** [comment]
We don't make a habit of re-writing working code just for the sake of re-writing it. %-formatting works, and is usually faster than "more modern" formatting, so that would be code churn that makes the code worse rather than better.

Since this is just a cosmetic change that will probably hurt performance, I'm going to close this. If you benchmark the changes and find that they are significantly faster, feel free to reopen.
