### ISSUE TITLE
Potential Bug in Counters

### ISSUE THREAD

**Issue by RicoSchumann** [python/cpython#94746]
Should the behaviour in Counter of an "Add" function remove values if they are negative?
<img width="892" alt="image" src="https://user-images.githubusercontent.com/102901119/178263070-d77d1267-55ff-45a6-8e8e-2c43be407a53.png">

If you add two dicts to one another, in my opinion, it is wrong to remove or ignore a negative number assignment. You add two dicts and only because one member's value is negative, it get's thrown away, although his key is still member of the dict. This is not plausible.

**Comment by rhettinger** [comment]
This is the expected, documented, and tested behavior.  All of the multiset operations eliminate negatives — this is necessary so that they get the same results as sets when the multiplicity is one, also because multisets aren't defined for negative values.

To get "regular" addition that supports positive and negative values, use the *update()* method.
