### ISSUE TITLE
set and dict constructors should re-use hashes of elements in  KeysView objects

### ISSUE THREAD

**Issue by Numerlor** [python/cpython#94776]
Even though a `KeysView` object is set-like and already knows the hashes of its elements through its dict, the `set` constructor and `dict.fromkeys` treat it as a plain iterable and unnecessarily re-hash all of its elements

```py
In [15]: class A:
    ...:     def __hash__(self):
    ...:         print("hashing")
    ...:         return 0
    
In [16]: keys = {A(): 0}.keys()
hashing

In [17]: set(keys)
hashing
Out[17]: {<__main__.A at 0x1ac17497820>}

In [18]: dict.fromkeys(a)
Out[18]: hashing
{<__main__.A at 0x1ac17497e80>: None}
```
This can be avoided by special casing them in the functions like dicts themselves already are

**Comment by eendebakpt** [comment]
Creating a `set` directly from the `dict` does not result in any hasing, neither does updating a dictionary. Creating a new dict does result in hashing:
```
class A(object):
    def __hash__(self):
        print("--> hashing")
        return super().__hash__()
    
a=A()    
d={A(): 0}
```
```
In [27]: set(d)
Out[27]: {<__main__.A at 0x1f552302a40>}

In [28]: dict(d)
--> hashing
Out[28]: {<__main__.A at 0x1f552302a40>: 0}

In [29]: {}.update(d)

In [30]: 
```

Constructing directly from the dict is faster:
```
In [43]: %timeit set(d.keys())
447 ns ± 39.7 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)

In [44]: %timeit set(d)
108 ns ± 1.16 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```

Since one can construct a set directly, I am not sure it is worthwhile to special case for the construction from a `KeysView`. But perhaps there are cases where it is worthwhile.

**Comment by rhettinger** [comment]
Sorry, I think this would have almost zero payoff.  Building sets or dict from KeysView objects isn't common at all.
