### ISSUE TITLE
test_sys_settrace leaked [6604, 6602, 6604] on main branch 

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#94979]
Commit tested: a25a803c4c

```console
@kumaraditya303 ➜ /workspaces/cpython (main) $ ./python -m test -R 3:3 test_sys_settrace
0:00:00 load avg: 31.03 Run tests sequentially
0:00:00 load avg: 31.03 [1/1] test_sys_settrace
beginning 6 repetitions
123456
......
test_sys_settrace leaked [6604, 6602, 6604] references, sum=19810
test_sys_settrace leaked [1835, 1860, 1856] memory blocks, sum=5551
test_sys_settrace failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_sys_settrace

Total duration: 1.2 sec
Tests result: FAILURE
```

**Comment by kumaraditya303** [comment]
cc @markshannon @pablogsal

**Comment by kumaraditya303** [comment]
Git bisect points to 2f8bff6879c5d76d143068e8bc867196a7d28afc as first bad commit:

```console
commit 2f8bff6879c5d76d143068e8bc867196a7d28afc (HEAD)
Author: Mark Shannon <mark@hotpy.org>
Date:   Mon Jul 18 16:06:42 2022 +0100

    GH-94739: Mark stacks of exception handling blocks for setting frame.f_lineno in the debugger. (GH-94958)

```

**Comment by mdboom** [comment]
`frame.setlineno` strikes again.

**Comment by brandtbucher** [comment]
The following three tests are leaking:
- `test_jump_from_except_to_finally`
- `test_jump_out_of_bare_except_block`
- `test_jump_out_of_qualified_except_block`

The issue is when we jump *out* of an exception handler into a non-exception-handler. We skip over `POP_EXCEPT`, which is supposed to clear `tstate->exc_info->exc_value`, the currently active exception. This exception references thousands of objects through its traceback frames.

I'm not sure what a good solution is. Perhaps clearing the thread's exception state if we can detect that we're jumping out of an exception handler?
