### ISSUE TITLE
Error 0x80070661 when installing python.

### ISSUE THREAD

**Issue by Dy-tech** [python/cpython#95163]
# Bug report

I tried to install python pre-release version 3.11.0b4 but it came up with the error "0x80070661" when I  was installing it.

# Your environment

- CPython versions tested on: 
  Edition	Windows 10 Pro
  Version	21H2
  Installed on	‎22/‎12/‎2020
  OS build	19044.1766
  Experience	Windows Feature Experience Pack 120.2212.4180.0
  Processor	Intel(R) Core(TM) M-5Y10c CPU @ 0.80GHz   998 MHz
  Installed RAM	4.00 GB
  Device ID	C6B85AF5-AB11-4FD7-A5D9-6EA16E98B3F3
  Product ID	00330-54911-25256-AAOEM
  System type	64-bit operating system, x64-based processor
  Pen and touch	Pen and touch support with 10 touch points

- Operating system and architecture:
  Windows 10 Pro
  x64

**Comment by eryksun** [comment]
0x80070661 is a Windows system error (i.e. 0x8007) with the specific error code `ERROR_INSTALL_PLATFORM_UNSUPPORTED` (1633, i.e. 0x0661). Maybe you tried to install [python-3.11.0b4-arm64.exe](https://www.python.org/ftp/python/3.11.0/python-3.11.0b4-arm64.exe) (ARM) instead of [python-3.11.0b4-amd64.exe](https://www.python.org/ftp/python/3.11.0/python-3.11.0b4-amd64.exe) (AMD64 / x64).

**Comment by Dy-tech** [comment]
Yes, I did run the ARM installer because I like testing out new
pre-releases and experimental versions.

**Comment by zware** [comment]
You're running on amd64 (x64) rather than ARM, though.  The ARM binaries will not work on your system; use the amd64 installer (second link in @eryksun's post) instead.
