### ISSUE TITLE
dict.setdefault() makes class arguments persistent

### ISSUE THREAD

**Issue by BnGx** [python/cpython#95248]
# Bug report

The _dict.setdefault()_ function makes dictionary arguments persistent across all instances of the class.
Arguments of different instances have the same ID and therefore also the same values.

# Environment

- CPython versions tested on: 3.10.4
- Operating system and architecture: Linux - amd64

# PoC

```python
class Test:

    def __init__(self, a, b={}):
        b.setdefault('key', a)
        print('id:', id(b), '-', 'value:', b)

Test(1)    # Print 1
Test(2)    # Print 1
```

**Comment by JelleZijlstra** [comment]
This is nothing to do with `setdefault`; it's a well-known behavior of default values. Default values are created when the function is created, so every time you call it, the default value of `b` is shared. See PEP-671 for discussion and a suggested workaround.

**Comment by AlexWaygood** [comment]
This has little to do with `dict.setdefault()`, and everything to do with the fact that defaults for function default  parameters in Python are always bound at _function definition_ time, rather than when the function is called.

This is not a bug. For a full explanation, please see this article by Fredrik Lundh: https://web.archive.org/web/20200221224620id_/http://effbot.org/zone/default-values.htm

And this StackOverflow question/answer: https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument
