### ISSUE TITLE
CarRacing v1 & v2 bug

### ISSUE THREAD

**Issue by marho13** [python/cpython#95402]
Hi, 
The bug relates to running Reinforcement Learning agents in a synchronous training loop.
When running the training without multiprocessing, all the code functions properly, but when running it with multiprocessing, we get the error shown below in the picture.

# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.
When I run my code without Multiprocessing, everything works properly. I meant to run multiple agents and tried to use ray but found a bug, so I tried multiprocessing, which caused the same bug. This is likely due to ray using multiprocessing under the hood.

A photo of the output is found below
![Multiprocessing_bug_report](https://user-images.githubusercontent.com/19758684/181632549-cc06403e-deee-467a-9d10-81370f27e6f2.PNG)

# Your environment
https://github.com/openai/gym/tree/master/gym/envs/box2d - CarRacing Environment used, tested for both CarRacing-v1 and v2

- CPython versions tested on: 3.10.4
- Operating system and architecture: Ubuntu 22.04 LTS

Code used for reproducing it: https://pastebin.com/MWiNxcTF
Pip list:
Box2D                  2.3.2
box2d-py               2.3.5
ceph                   1.0.0
cephfs                 2.0.0
cloud-init             22.2
cloudpickle            1.6.0
gym                    0.24.1
gym-notices            0.0.7
numpy                  1.23.0
Pillow                 9.2.0
pip                    22.0.2
protobuf               3.20.1
psutil                 5.9.1
ptyprocess             0.7.0
pyglet                 1.5.0
PyOpenGL               3.1.6
pyOpenSSL              21.0.0
python-apt             2.3.0+ubuntu2
python-debian          0.1.43ubuntu1
pytz                   2022.1
PyYAML                 5.4.1
scipy                  1.8.1
torch                  1.12.0
torchfile              0.1.0
virtualenv             20.15.1
visdom                 0.1.8.9
wandb                  0.12.20

**Comment by JelleZijlstra** [comment]
This bug tracker is only for CPython, the language interpreter. Your issue is in some third-party library, not the language itself.

**Comment by marho13** [comment]
Sorry, I thought the multiprocessing library was considered under here, which is what I had the problem with.

**Comment by zware** [comment]
`multiprocessing` is part of the standard library, but your reproducer includes far too much code to be able to tell whether `multiprocessing` is actually at fault here.  You'll need to distill the problem down to an example that uses only the standard library and as little of your own code as possible to make it an issue we can handle here.

**Comment by stevendaprano** [comment]
Further to @zware 's comment about distilling the problem down to a small example, please read https://stackoverflow.com/help/minimal-reproducible-example and http://sscce.org/ and then follow them to reduce the reproducer to the minimal code and data needed. Your pastebin contains extraneous code handling command line arguments, dead code that has been commented out, graphics, and at least six third-party libraries on top of multiprocesssing. We don't know whether or not multiprocessing is even supported by those libraries for this task.

We are in no position to spend hours or days or weeks learning enough about those libraries to even *begin* spending the time needed to debug your code for you, to identify which library the bug is in. And we have no access to your data, so we couldn't run your code even if we wanted to.

Also, when posting error tracebacks don't use screenshots or photos, copy and paste the text of the traceback so they can be searched, copied and pasted, and so as to not discriminate against visually impaired and blind programmers who otherwise might be able to help. Screenreaders and braille output devices don't work with text turned into images.

**Comment by marho13** [comment]
Sorry about that; here is a minimal reproducible example with the output:
https://pastebin.com/LNAMbrW2
![Multiprocessing_bug_report](https://user-images.githubusercontent.com/19758684/181642990-e4dc5587-1b7c-4939-b212-076135d4a0b7.PNG)

**Comment by zware** [comment]
Closer, but not quite :).  You still have `gym` and `numpy` in the code, either of which could be causing problems.

My guess is that when you rework the example to remove `gym`, the problem will go away; I suspect that whatever `gym.make` gives you does not correctly support being pickled.

**Comment by marho13** [comment]
@zware you seem to be right, I saw that the gym environments were supposed to be serializable (https://github.com/rlworkgroup/garage/issues/292).
So I found that to be the issue, thank you so much :)
