### ISSUE TITLE
Adding an element during the last iteration of an OrderedDict doesn't throw an exception 

### ISSUE THREAD

**Issue by daveraja** [python/cpython#95422]
# Bug report

When iterating over an `OrderedDict` it is possible to add a new item without error when you are iterating on the last element of the dictionary. For a "normal" dictionary object this will generated a runtime error "dictionary changed during iteration".

```
    from collections import OrderedDict
    foo = [(1,1),(2,2)]

    # Succeeds
    odict = OrderedDict(foo)
    for n, v in enumerate(odict.items(), 1):
        if n == len(odict):
            odict[3] = 3

    # Fails
    ndict = dict(foo)
    for n, v in enumerate(ndict.items(), 1):
        if n == len(ndict):
            ndict[3] = 3
```
As an aside, if you modify a non-last element of the OrderedDict it generates a "mutated during iteration" runtime error rather than the more specific "dictionary changed during iteration" (like the normal dictionary). 

# Your environment

- CPython versions tested on: v3.10.2
- Operating system and architecture: Ubuntu 20.04 x86_64

**Comment by rhettinger** [comment]
We're fine with this.  It is not guaranteed that all mutations raise an exception.  We put in some simple and cheap protections to guard against common mistakes, but consciously decided to not make more extensive and expensive efforts to detect all mutations.  For the most part, this has proved sufficient. 

Even regular dicts only detect size changes (they do so in iter_next which is written in C so that check is inexpensive), but we don't guard against all mutations.  For example, this succeeds:

```
foo = [(1,1),(2,2)]
ndict = dict(foo)
for n, v in enumerate(ndict.items(), 1):
    if n == len(ndict):
        ndict[1] = 9
print(ndict)
```

BTW, thanks for the clear and well written bug report.  As an API matter, this isn't worth pursuing; however, if you can generate a segfault, the importance would rise and we would pay a cost to make the code correct.

**Comment by daveraja** [comment]
Thanks for the quick response and the insight into the cost vs correctness trade-off that you have to make.
