### ISSUE TITLE
Make sure all sqlite3 doc examples work

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#95432]
Use Sphinx doctest features to ensure that all examples in the sqlite3 docs work as expected.

See also: https://diataxis.fr/tutorials/#ensure-that-the-tutorial-works-reliably

**Comment by erlend-aasland** [comment]
PR for the tutorial is up. I'll create a new PR for the rest later.

@CAM-Gerlach, @hugovk: does Sphinx support doctesting included files?

**Comment by CAM-Gerlach** [comment]
I actually know fairly little about docttests since I don't use them much myself (I primarily maintain docs for the Spyder-family GUI projects, where doctests aren't really relevant or practical), and most of what I know on Sphinx's support for them comes from reading [the Sphinx documentation](https://www.sphinx-doc.org/en/master/usage/extensions/doctest.html), which doesn't seem to mention this.

**Comment by erlend-aasland** [comment]
The literal includes are not tested. This is unfortunate. For sqlite3, I suggest inlining them; most of the snippets are very short. We can exploit this opportunity to make them even more succinct.

**Comment by erlend-aasland** [comment]
Fixed by:

- #96193 
- #96200 
- #96201 
- #96225 
- #96378 
- #96379
