### ISSUE TITLE
Slow first execution of platform.system on windows

### ISSUE THREAD

**Issue by eendebakpt** [python/cpython#95531]
# Bug report

Many python packages make calls to `platform.system()`  or `platform.machine()`  during the import. These functions call the generic `platform.uname()` . The result of `platform.uname()` is cached, but the first invocation is slow on windows (>100ms), adding 100ms import time to these packages. The slow part on windows is `def _syscmd_ver` which starts an external process.

Can we replace `_syscmd_ver` with a faster version (e.g. calling the windows api directly instead of using a external process)? Or refactor the `platform.system()`  and `platform.machine()` functions to only retrieve the information required and not the general `uname`?

# Your environment

- CPython versions tested on: 3.11
- Operating system and architecture: Windows

**Comment by eryksun** [comment]
> Can we replace _syscmd_ver with a faster version (e.g. calling the windows api directly instead of using a external process)?

There is no public API to get the true system version if compatibility mode is enabled. That's the only reason that the CMD shell's `VER` command is used here. An extension module could be developed to use WMI instead of spawning a shell process, but WMI is also relatively slow.

Getting `system`, `machine`, and `processor` should be practically free in Windows, considering `sys.platform` and the environment variables "PROCESSOR_ARCHITECTURE" and "PROCESSOR_IDENTIFIER" are used. It's only held back by a design that's based on POSIX `uname()`.

**Comment by zeha** [comment]
A  common solution is to use the FileVersion from Kernel32.dll.

**Comment by eryksun** [comment]
> A common solution is to use the FileVersion from Kernel32.dll.

That's how [`sys.getwindowsversion().platform_version`](https://docs.python.org/3/library/sys.html#sys.getwindowsversion) is implemented, but it's no longer guaranteed in Windows 10+.  The version of system DLLs may differ from the current Windows build. This is not just a theoretical difference. It happened in practice, which is why the platform module had to switch to querying the shell's `VER` command.

**Comment by AaronMargosis** [comment]
If the compiled Python exe has all the correct supportedOS compatibility GUIDs in its application manifest, the version-lie shims shouldn't come into effect at all. If someone has explicitly applied a compat layer to a Python executable, shouldn't that be on them? Also, what precisely is the purpose for Python to acquire this information? If it's about ensuring that OS features are supported/available, the "IsWindows*" functions in VersionHelpers.h (which ultimately invoke VerifyVersionInfoW) are not subject to those version-lie compat layers.

I work for a company that depends heavily on Python, and we see TONS of excess "Cmd.exe /c ver" instances spinning up, which has significant performance impact as well as customer complaints.

**Comment by zooba** [comment]
`platform` is intended to get information about your system for reporting, and as of a few releases ago uses WMI to retrieve the version (which may have its own performance issues, but usually only if it can't access WMI). If you find libraries using it to determine feature availability, feel free to report bugs against them and tell them they're wrong.

For our own OS version checks, we use the correct helpers. Hopefully people writing code for Windows rely on our built-in checks rather than writing their own, but if they do use their own they'll have no choice but to compare against versions.

**Comment by AaronMargosis** [comment]
Neither invoking WMI nor spawning cmd.exe is necessary to get the OS major/minor/build. Just make sure the exe has all the right compatibility GUIDs in its application manifest, and call the GetVersionEx API. As I said, if someone has explicitly applied a compat layer to a Python executable, that should be on them. The resource and auditing cost of spinning up a new cmd.exe instance (and a new conhost.exe instance with it) is significant, unnecessary, and sadly unavoidable in the current Python implementation.

**Comment by zooba** [comment]
The purpose of the API in question is to get the most accurate information about the OS, regardless of compatibility options. We can't avoid the extra work here (and yes, we have people report legitimate bugs when it returns the wrong information). I know you know full well that we can't apply all the compatibility GUIDs for the 5ish year lifetime of each version of Python - at best we can add them in maintenance updates, but by policy we set our OS compatibility at our `3.x.0` release. We _want_ the compatibility behaviour on new OS releases that weren't around during initial development.

The real question is why are the "many Python packages" mentioned in the original post querying this information. _They_ are the ones who shouldn't need it. Alas, no information about who they are was provided, so we can't figure out what they ought to be doing instead.

Plenty of other people do use the `platform` module correctly to capture information about the machine they're running on, and there's no need to penalise them with incorrect behaviour just because some people use the API badly.

This issue isn't adding anything useful right now, so I'm closing it until we get some more information about why libraries are having to use `platform` on initial import rather than one of the more appropriate APIs.
