### ISSUE TITLE
doctest unexpectedly imports local module named signal.py

### ISSUE THREAD

**Issue by kevinsikes** [python/cpython#95540]
# Bug report

If a module named signal.py is located in the current directory, it is unexpectedly imported when importing doctest, which can introduce unwanted behavior.
```
echo 'print("Importing local signal.py")' > signal.py
python3 -c "import doctest"
```
Output:
`Importing local signal.py`

Workaround:
If feasible, an affected user should name the local file something other than signal.py

# Your environment

- CPython versions tested on: 3.8.10, 3.10.4
- Operating system and architecture: Windows 10 (Python 3.8), Ubuntu 22.04 (Python 3.10), both x86-64

**Comment by stevendaprano** [comment]
This is because doctest imports pdb, which imports signal, which is [a standard library module](https://docs.python.org/3/library/signal.html).

So the problem here is that the user's local module "signal.py" shadows the stdlib module, which is the user's bug, not a doctest bug. The same would occur if the user had a local module called "re.py", "traceback.py", "inspect.py", etc.

I acknowledge that it is difficult for the user to know what module names are used by the stdlib, but ultimately that is their responsibility. You have already worked out the solution: the user must rename the shadowing module to something else.

**Comment by itsfarseen** [comment]
This doesn't happen on 3.11. What changed?
