### ISSUE TITLE
The ValueError for converting an all-whitespace string to a float misleadingly displays it as the empty string

### ISSUE THREAD

**Issue by Zeturic** [python/cpython#95605]
# Bug report

Actual behavior:

```py
>>> float('\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: could not convert string to float: ''
```

Expected behavior:

```py
>>> float('\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: could not convert string to float: '\n'
```

As long as the string isn't completely whitespace, it does display properly. For example:

```py
>>> float('\nn')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: could not convert string to float: '\nn'
```

In addition to newlines, the same thing can be observed with tabs and carriage returns, or any combination of the three. I didn't test any additional whitespace characters, though they would likely behave the same way.

# Your environment

- CPython versions tested on: 3.10.5
- Operating system and architecture: Windows 10 (64-bit)

**Comment by mdickinson** [comment]
Thanks for the report. This is caused by an unfortunate interaction between [`float_from_string_inner`](https://github.com/python/cpython/blob/bdbadb905ae638b67a6c9a6767be396e18839dd6/Objects/floatobject.c#L177-L183) and [`PyOS_string_to_double`](https://github.com/python/cpython/blob/bdbadb905ae638b67a6c9a6767be396e18839dd6/Python/pystrtod.c#L337). (The `PyOS_string_to_double` API leaves something to be desired, with its multi-channel reporting of errors, but it's part of the limited API so we can't change it.)

Specifically, after the `PyOS_string_to_double` call, if `end == last` in `float_from_string_inner`, then _either_ the parse was successful, or the string being parsed was empty; conversely, if the parse was successful then `end = last`. So when we raise on `end != last`, we catch only parse failures on _nonempty_ strings. The parse failure on an empty string just propagates the `ValueError` already raised in `PyOS_string_to_double`, which has an inferior error message.

#95665 should fix this.
