### ISSUE TITLE
CVE-2020-10735: Prevent DoS by large int<->str conversions

### ISSUE THREAD

**Issue by gpshead** [python/cpython#95778]
## Problem

A Denial Of Service (DoS) issue was identified in CPython because we use binary bignum’s for our `int` implementation. A huge integer will always consume a near-quadratic amount of CPU time in conversion to or from a base 10 (decimal) string with a large number of digits. No efficient algorithm exists to do otherwise.

It is quite common for Python code implementing network protocols and data serialization to do `int(untrusted_string_or_bytes_value)` on input to get a numeric value, without having limited the input length or to do `log("processing thing id %s", unknowingly_huge_integer)` or any similar concept to convert an `int` to a string without first checking its magnitude. (`http`, `json`, `xmlrpc`, `logging`, loading large values into integer via linear-time conversions such as hexadecimal stored in `yaml`, or anything computing larger values based on user controlled inputs… which then wind up attempting to output as decimal later on). All of these can suffer a CPU consuming DoS in the face of untrusted data.

Everyone auditing all existing code for this, adding length guards, and maintaining that practice everywhere is not feasible nor is it what we deem the vast majority of our users want to do.

This issue has been reported to the Python Security Response Team multiple times by a few different people since early 2020, most recently a few weeks ago while I was in the middle of polishing up the PR so it’d be ready before 3.11.0rc2.

## Mitigation
After discussion on the Python Security Response Team mailing list the conclusion was that we needed to limit the size of integer to string conversions for non-linear time conversions (anything not a power-of-2 base) by default. And offer the ability to configure or disable this limit.

The Python Steering Council is aware of this change and accepts it as necessary.

### Linked PRs
* gh-100627
* gh-100628
* gh-101065
* gh-101066
* gh-101630
* gh-101631

**Comment by mgorny** [comment]
Thanks a lot for doing this, and especially for the backports to older versions. It's really nice I don't have to figure them all out myself ;-).

**Comment by mdickinson** [comment]
As commented on the PR, the current code in main doesn't prevent the potential DOS for the `int` to `str` direction: the size check is only performed _after_ the quadratic-time algorithm has run. For example:

```python
Python 3.12.0a0 (heads/main-dirty:ac4ddab405, Sep  3 2022, 16:35:07) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> n = 10**(10**7)  # takes a few seconds to run 
>>> s = str(n)  # expect instant ValueError, but takes many minutes
```

One possible fix would be to keep the existing post-loop check (so that we get the benefit of knowing exactly what the threshold is), but also adding a cruder pre-check that would catch the majority of bad cases before the loop is entered.

I think we want _something_ like the following as a pre-check

```python
    if (size_a >= 10 * _PY_LONG_MAX_STR_DIGITS_THRESHOLD / (3 * PyLong_SHIFT) + 2) {
        PyInterpreterState *interp = _PyInterpreterState_GET();
        int max_str_digits = interp->int_max_str_digits;
        d = 10 * max_str_digits / (3 * PyLong_SHIFT) + 2;
        if ((max_str_digits > 0) && (size_a > 10 * max_str_digits / (3 * PyLong_SHIFT) + 2)) {
            <do error raising here>
        }
    }
```

Here `10 * _PY_LONG_MAX_STR_DIGITS_THRESHOLD / (3 * PyLong_SHIFT) + 2` is a constant, so in normal use we get an extra predictable(?) never-taken branch.

For the logic used in computing the constant: 10/3 is an upper bound for log10(2), so

- if `size_a >= 10 * _PY_LONG_MAX_STR_DIGITS_THRESHOLD / (3 * PyLong_SHIFT) + 2`
- then `(size_a - 1) * (3 * PyLong_SHIFT) >= 10 * _PY_LONG_MAX_STR_DIGITS_THRESHOLD`
- so `(size_a - 1) * PyLong_SHIFT >= log10(2) * _PY_LONG_MAX_STR_DIGITS_THRESHOLD`
- so `abs(a) >= PyLong_BASE ** (size_a - 1) >= 10**_PY_LONG_MAX_STR_DIGITS_THRESHOLD`

and similar logic applies for the `size_a > 10 * max_str_digits / (3 * PyLong_SHIFT) + 2)` expression within the loop.

One complication: we can no longer produce an error message that says exactly how many decimal digits there were, but I think that's going to be true no matter how we fix this.

**Comment by mdickinson** [comment]
I'll see if I can turn the above into a PR.

**Comment by mdickinson** [comment]
BTW, did the PR authors consider using type `Py_ssize_t` instead of `int` for the new `int_max_str_digits` field? The max value for `int` could potentially be as low as `32767`, which could be quite limiting. Either `Py_ssize_t` or a fixed-size type like `int32_t` or `int64_t` might work better.

**Comment by merwok** [comment]
-X options and envvars are documented in 4 or 5 spots, I think a couple were missed by the PR.
I’ll make a PR to fix this little issue.

**Comment by gpshead** [comment]
> BTW, did the PR authors consider using type `Py_ssize_t` instead of `int` for the new `int_max_str_digits` field? The max value for `int` could potentially be as low as `32767`, which could be quite limiting. Either `Py_ssize_t` or a fixed-size type like `int32_t` or `int64_t` might work better.

I did consider `Py_ssize_t` instead of `int`, but I'm unaware of any platform supported by CPython with a 16-bit int.

**Comment by mdickinson** [comment]
> I did consider `Py_ssize_t` instead of `int`, but I'm unaware of any platform supported by CPython with a 16-bit int.

Okay. The rest of `longobject.c` tries hard not to make any assumptions about sizes of platform integers (beyond those guaranteed by the C standard), and it's possible that future platforms that we care about _could_ have a 16-bit int. If we want to go the way of requiring that int has at least 32 bits, I think that should be a configure-time check, and should be clearly documented. (But it would be much less effort to use a different type instead of `int` here.)

**Comment by gpshead** [comment]
>  it's possible that future platforms that we care about could have a 16-bit int.

No platform that wants to run real world existing C code would ever make such a decision.

The limit still works even if constrained to 32767 digits by a wacky 1980s worthy platform. Though some unit tests may assume higher limits are possible there is no point in changing those in any way until someone is actually offering up such a platform with a buildbot and credible desire for support.

**Comment by mdickinson** [comment]
Okay. I still think `int` is the wrong type here - is there any really good reason _not_ to use `Py_ssize_t`? It's the obvious type for something that represents a count (of digits, bits, limbs, ...).

**Comment by gpshead** [comment]
The computation for a billion digit conversion would never complete so a full Py_ssize_t isn't needed. Regardless, `int32_t` is pedantically correct so I've added switching to that as a `main` cleanup to do in #96512.

**Comment by mdickinson** [comment]
Yep, that works. That then makes it possible to tighten the check so that there are fewer false negatives - we can make `10 * int_max_str_digits` safe from overflow by casting one of the multiplicands to `int64_t` first. (We couldn't do that with plain old `int` because of problems in the _other_ direction: `int` could potentially be 64 bits.)

**Comment by mdickinson** [comment]
> The computation for a billion digit conversion would never complete so a full `Py_ssize_t` isn't needed.

With current algorithms, that's true. But if some version of Tim's suggestions in https://github.com/python/cpython/issues/90716 went in, billion digit conversions might become feasible. :-)  But at that point, maybe we'd be able to drop these limits entirely?

**Comment by mdickinson** [comment]
> That then makes it possible to tighten the check [...]

To be clear, I can look at this later, for 3.12 only.

**Comment by adamant-pwn** [comment]
Are you aware that there is an algorithm to do conversions faster than quadratic time? For example, one may use divide and conquer + FFT to achieve something around $O(n \log^2 n)$ in complexity. Not as great as linear, but certainly much better than quadratic.

**Comment by gpshead** [comment]
Yes, using a better algorithm is covered over in https://github.com/python/cpython/issues/90716.

**Comment by gpshead** [comment]
> But if some version of Tim's suggestions in https://github.com/python/cpython/issues/90716 went in, billion digit conversions might become feasible. :-) But at that point, maybe we'd be able to drop these limits entirely?

Removing the limit _might not be feasible_ as after this feature some code could come to depend on its existence indirectly to protect other things in whole systems from large values, knowingly or not. That doesn't mean we couldn't, just that it'd need consideration.

We also need to consider the worst case performance of any fancier algorithm before removing the ability to limit it. Untrusted data seeking a DoS would target that. Ex: If a faster conversion algorithm is typically $O(n * log_2(n))$ but devolves into $O(n^2)$ on some values, we need to handle the worst case unexpected computation.

A notebook could even be designed to avoid half the problem by having their REPL repr and storage code auto-switch to hex for large values.

**Comment by imachug** [comment]
This is appalling.

Situation: people pass untrusted data to slow built-in functions. Reasonable solution: a) patch vulnerable programs, b) optimize said functions. CPython's solution: just limit stuff.

Your rationale is founded on the fact that developers constantly add bugs and fixing them is not an option. Fixing bugs is like, more than half of what developers normally do.

When ReDoS was discovered, did we limit the number of iterations of the matching algorithm? No. Then why should we do the same here? There are dangerous tools, but they are often much more useful due to lack of artificial limits. When did we drop "Special cases aren't special enough to break the rules."

To add insult to injury, people seem to be talking about limiting `repr` too. How many bugs that will cause, I can't tell: I saw people use `repr(...)` to generate non-Python code as a universal solution that works with both integers and strings, and I foresee problems when it starts generating non-digit strings.

You're limiting integer to string conversions. How soon are you going to limit `repr(list)` because of the billion laughs attack?

Why is `_PY_LONG_MAX_STR_DIGITS_THRESHOLD` even a constant? No one's going to recompile Python, and if people actually start using this security "feature", chances are it'll be enabled everywhere, and then programs that use big arithmetic and parse numbers from the user input will silently stop working. It's not even *big* arithmetic, really: the discussed limit to `repr` seems to be only 512 bit, which is much less than thousands-of-bits numbers used in cryptography *right now, in Python*. In fact, the problem doesn't go away if it's variable: the problem is that it's global, affecting the whole application rather than the user-facing part. When did we drop "Explicit is better than implicit?"

And then, has anyone actually researched how much trusted code parses integers from untrusted sources directly? To me it seems that even ReDoS should be more popular than this. I think people seldom call `int` on user input directly: they either use parsing libraries like `json` and `yaml`, or (hear me out) use (web) frameworks that parse the data themselves. Either way, there's a finite number of places where checks should be added, and even if it's tens of places, it's so much better than limiting *every single program*, including those that don't even face the outer world, because it'll be actually configurable.

I don't think I even understand why a limit is added in the first place. If Python used a quadratic algorithm for multiplication instead of FFT, that would not be considered a vulnerability but an inefficiency. There are much faster algorithms than the one used by CPython, I literally found one by googling "subquadratic base conversion". There: [*Richard P. Brent and Paul Zimmermann*, Modern Computer Arithmetic](https://members.loria.fr/PZimmermann/mca/mca-cup-0.5.9.pdf). #90716, the issue that was tracking this, was dropped because what, developers tried to invent stuff themselves instead of comparing with state of art, and just chose the simplest option after an inevitable failure?

**Comment by gpshead** [comment]
As a reminder to everybody [Python Community Code Of Conduct](https://www.python.org/psf/conduct/) applies here.

Closing. This is fixed. We'll open new issues for any follow up work necessary.

**Comment by stevendaprano** [comment]
> Everyone auditing all existing code for this, adding length guards, and maintaining that practice everywhere is not feasible nor is it what we deem the vast majority of our users want to do.

If applications don't validate their data before running str <-> int conversions, I'm not entirely sure that having an exploit that allows attackers to crash the application with an unexpected ValueError instead of merely slowing it down for a few seconds is a great improvement.

I'm only a naive developer but this kinda feels like the fix is worse than the problem its solving. What I am missing?

**Comment by gpshead** [comment]
Please redirect further discussion to discuss.python.org.

**Comment by gpshead** [comment]
# Further Discussion

... is taking place in [discuss.python.org threads](https://discuss.python.org/t/int-str-conversions-broken-in-latest-python-bugfix-releases/18889)

**Comment by vstinner** [comment]
There is a minor bug when parsing the -X option: https://github.com/python/cpython/issues/96848

**Comment by vstinner** [comment]
I propose PR #96874 to mention sys.set_int_max_str_digits() in the error message.

**Comment by merwok** [comment]
Follow-up PR for a couple spots missed for documentation: https://github.com/python/cpython/pull/100627
