### ISSUE TITLE
New version alternative for package.version

### ISSUE THREAD

**Issue by mrquokka** [python/cpython#95852]
# Documentation

When i use **packaging.version.parse** it will raise warning
/hdd/work/envs/main/lib/python3.10/site-packages/packaging/version.py:111: DeprecationWarning: Creating a LegacyVersion has been deprecated **and will be removed in the next major release**

For resolve it, i trited **distutils.version.StrictVersion** and get
DeprecationWarning: The distutils **package is deprecated and slated for removal in Python 3.12.** Use setuptools or check PEP 632 for potential alternatives

on this pep alternative of this - use **packaging.version**

How to resolve this logical loop?

**Comment by zware** [comment]
As far as I can tell, the suggestion is to use `packaging.version.Version` rather than `packaging.version.LegacyVersion`, not anything from `distutils`.  `packaging` is not part of the standard library anyway; any issues with it should be raised on [its own issue tracker](https://github.com/pypa/packaging/issues/).  See especially the [pinned issue](https://github.com/pypa/packaging/issues/514) on that tracker.
