### ISSUE TITLE
Unexpected behavior - generator capturing by name rather than by value/reference

### ISSUE THREAD

**Issue by wjablonski-work** [python/cpython#96583]
# Bug report

It seems like generator is capturing variables by name rather than by reference. I'm not sure whether it's considered a bug or implementation detail, but it was extremely unexpected and I don't believe anyone would ever want it to behave this way.

```
a = 1
b = ((i, a) for i in range(1))
a = b
print(list(a))

# stdout:
# [(0, <generator object <genexpr> at 0x000014cff75581b0>)]
```

# Your environment

```
$ python --version
 Python 3.8.7
```

OS:
```Linux (...) 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by gpshead** [comment]
This is expected behavior. Your generator has not executed yet - "a" is merely a name lookup in the scope the generator refers to. You rebound "a" in that scope, thus what it yields reflects that.

The exact same thing that happens if you define a function that returns or yields "a" from an outer scope. A generator is effectively just a tiny function with a yield.

**Comment by wjablonski-work** [comment]
I see how it's self-consistent. Explains the behavior in some way.
