### ISSUE TITLE
Improved replacement functionality for deprecated crypt module

### ISSUE THREAD

**Issue by gstein** [python/cpython#96747]
# Documentation

The `crypt` module is deprecated for 3.11. At the top of the doc page (https://docs.python.org/3/library/crypt.html), it suggests that maybe `hashlib` can provide a replacement, or PEP 594. Neither of these were very helpful.

What I **did** find is `passlib` has a functional replacement. Please see: https://passlib.readthedocs.io/en/stable/lib/passlib.hash.md5_crypt.html

I think this package/module should be recommended in the `crypt` module documentation.

Note that `passlib` will use the OS `crypt()` function *if available*, and will default to a pure-python solution based on the (guaranteed) presence of the MD5 hashing library.

### Linked PRs
* gh-106660
* gh-106697

**Comment by hugovk** [comment]
@gstein Sounds good, please could you create a PR to update the docs?

**Comment by gpshead** [comment]
The 3.11 & 3.12 docs point to `passlib` as a possibility now.  Several of us poked around passlib - it isn't _perfect_.  It's maintainer hasn't been active since October 2020 (anywhere on PyPI) and it has a sole maintainer.  If any of this ever proves to be a practical problem we'll remove the link from our docs.  My own searching didn't obviously turn up other good replacement candidates though.

For the rare users who need old `crypt` functionality, it looks like it'll work for now.  Another alternative would be for anyone to put a fork of 3.12's crypt module up on PyPI as its own package.

For many of these old rarely used in anything modern algorithms even someone offering up a pure python implementation would work just fine for people's intended purpose.
