### ISSUE TITLE
Non-existing class in importlib

### ISSUE THREAD

**Issue by pchanial** [python/cpython#96845]
# Documentation

The documentation for 3.9 and 3.10 about the importlib package mentions the class importlib.resources.abc.Traversable, which only exists since 3.11. Instead, the importlib.abc.Traversable should be mentionned.

**Comment by jaraco** [comment]
My intention was always for this class to be in the `resources` namespace, but that didn't happen until #90276. My preference, for maximum compatibility, would be to expose the class in `importlib.resources.abc` even for old Pythons, to honor the documented location, but I realize now that's not readily achievable because `importlib.resources` is a simple module prior to Python 3.11 and thus doesn't support submodules. In https://github.com/python/cpython/issues/93610#issuecomment-1153911900, I indicated that I meant for the location of `Traversable` to be an implementation detail prior to 3.11.

**Comment by jaraco** [comment]
Docs have been updated to reflect the reality of the situation.
