### ISSUE TITLE
issubclass raising error when argument 1 is a typing._GenericAlias

### ISSUE THREAD

**Issue by nickeldan** [python/cpython#96871]
This seems related to [issue #89489](https://github.com/python/cpython/issues/89489) but I'm not sure if it's the same problem.

I have a metaclass that examines the `__annotations__` of its instances.  At one point, I check whether the type of an annotated field is a subclass of `int` (e.g., an `enum.IntEnum` subclass) by `issubclass(field_type, int)`.  It works fine unless the type is a `typing._GenericAlias` such as `typing.Optional[bytes]` in which case it raises an error:

```python
TypeError: issubclass() arg 1 must be a class
```

Could `issubclass` just return `False` in this case?

This is on Python 3.8.10.

**Comment by sobolevn** [comment]
Well, there are several things to it:
1. `python3.8` is quite old now, we can only add new feature to 3.12 at the moment
2. Typing API specifically states that you cannot use `isinstance` / `issubclass` with generic aliases. Otherwise, people would ask: why can't you use `isinstance([1, 2], list[int])`? I don't think this is going to change anytime soon
3. You can actually work around it by catching `TypeError` and return `False` in your own code

**Comment by JelleZijlstra** [comment]
Yes, this is documented and intentional behavior. The recommendation is to call `isinstance(field_type, type)` before trying to use `issubclass()`.
