### ISSUE TITLE
Deadlock when using fork whilst multiprocessing.resource_tracker._resource_tracker._lock is held

### ISSUE THREAD

**Issue by TheMinefighter** [python/cpython#96971]
# Bug report

Given the following situation: You have a Process "a" with two threads ("aa", "ab"). aa is currently creating a shared memory segment and is holding `multiprocessing.resource_tracker._resource_tracker._lock` for that reason. Note that that lock is not acquired by user code, but deep inside the SharedMemory constructor. 

ab now wants to create a second process using the `fork` method. Process b is created with one thread: bb. As per `man fork` the thread aa is not duplicated in process b. 

 If aa now finishes creating its SharedMemory it releases `multiprocessing.resource_tracker._resource_tracker._lock`. But that lock is only a `threading.Lock`, which means it is released only in process a. In process b it will not be released. If b now wants to create a SharedMemory object and therefore tries to acquire `multiprocessing.resource_tracker._resource_tracker._lock` this will take forever, as it will never be free in process b. `man fork` explicitly mentions that such situations are a potential source of issues.

As this is a race condition there is no minimal, reproducible example I can give.

# Possible solutions
One could replace this `threading.Lock` with a `multiprocessing.Lock`. Alternatively one could replace that lock with a new one in the child process after a fork. Im not sure about the intended behavior of the resource tracker in such situations.

# Your environment

- CPython versions tested on: 3.9, 3.10
- Operating system and architecture: Unix (Arch, Kernel 5.19.7-1)

**Comment by knwng** [comment]
IMHO, forking a process with multiple threads is unsafe by nature. You may try to fork before creating threads.

**Comment by arhadthedev** [comment]
This is a known multiprocessing issue; see gh-84559 for details.

**Comment by TheMinefighter** [comment]
Ok, I believe that there are valid use-cases for forking after thread creation, e.g. when you want to be able to read parts of the heap in the extra process that are only written after thread creation.
If you really decide that this is a non-intended use, please add that to the applicable documentation.

**Comment by arhadthedev** [comment]
> Ok, I believe that there are valid use-cases for forking after thread creation, e.g. when you want to be able to read parts of the heap in the extra process that are only written after thread creation.

@pitrou @gpshead

**Comment by gpshead** [comment]
It is unsafe to continue using the CPython interpreter after fork() per POSIX when threads exist in an application. This is by definition and is not a solvable problem. It is a fundamental core definition of the POSIX platforms. Threads and fork do not mix.

If you want low level C POSIX async-signal-safe code to execute after fork() in a threaded process, you need to write that in C and do the fork() from C via an extension module. It is unsafe to reenter the CPython interpreter from the forked process as CPython is not and never will be an async signal safe.

https://pubs.opengroup.org/onlinepubs/009696799/functions/fork.html - "the child process may only execute async-signal-safe operations"

---

While you may get somewhere by attempting to register the resource tracker lock with various atfork mechanisms so that it is acquired and held across the fork via [`os.register_at_fork()`](https://docs.python.org/3/library/os.html#os.register_at_fork), trying to get those setup and correct for all possible locks in a manner in which they won't deadlock is ultimately a game of whack a mole and generally impossible. In an attempt to allow you to fork from a threaded application and do things from CPython that fundamentally are not guaranteed to work and will break in other ways you haven't happened to experience yet...
