### ISSUE TITLE
Clearing all inputs also erases standard outputs in the same line

### ISSUE THREAD

**Issue by minkyu97** [python/cpython#97563]
# Bug report
``` python3
import readline
print('Hello,\nWorld', end='')
input()
```
When execute above code, If you type some text and erase all the inputs, the expected result is below.
``` shell
Hello,
World
```
But, in my case, the actual result was
``` shell
Hello,

```

# Your environment

- CPython versions tested on: 3.6.9
- Operating system and architecture: Ubuntu 18.04.1 LTS (GNU/Linux 5.4.0-1081-aws x86_64)

**Comment by eryksun** [comment]
This appears to be an issue in GNU Readline. For example, try the following from the command line in a Unix shell: `echo -ne 'Hello,\nWorld'; read -e -p ""`. Now try it with a non-empty prompt such as a single space: `echo -ne 'Hello,\nWorld'; read -e -p " "`. In the first case, "World" can be erased, but in the second case the non-empty prompt acts as a barrier that can't be erased. In Python, GNU Readline behaves the same way if `input(" ")` is used instead of `input()`.

**Comment by eryksun** [comment]
Note that on Windows without `pyreadline` installed, `input()` depends on the console's builtin line editor. The console remembers the initial cursor position when `ReadConsoleW()` is called, and it only erases up to that position. So there's no problem here for a vanilla Windows install.
