### ISSUE TITLE
Setting state of an exception object with a  dic crashes Python 3.8.14 

### ISSUE THREAD

**Issue by xiaxinmeng** [python/cpython#97591]
# Crash report

The following  programs defined a class C. In C, we perform dic clear() operation. When we set state of exception object with the dic, it  causes segmentation fault on main branch (https://github.com/python/cpython/commit/68c46ae68b6e0c36a12e37285fff9ce0782ed01e) and latest stable Python 3.8.14. But it does not trigger any crashing on Python-3.11.0rc2 and Python 3.9.0.

```
class C(str):
    def __hash__(self):
        d.clear()
        return 0

d = {}
d[C()] = C()

e = Exception()
e.__setstate__(d)
```

# Error messages
Segmentation Fault (Core dumped)

# Your environment

- CPython versions tested on: Python 3.8.14 and  main branch (https://github.com/python/cpython/commit/68c46ae68b6e0c36a12e37285fff9ce0782ed01e)
- Operating system and architecture: [GCC 7.5.0] on linux

**Comment by gvanrossum** [comment]
I ran this in main under the debugger and it looks like the crash actually occurs during final cleanup, in ClearWeakRefs called from free_keys_object. Not sure if I have the guts to continue debugging.

**Comment by ofey404** [comment]
Reproduce this in python 3.10.2, and latest main ([83a3de4](https://github.com/python/cpython/commit/83a3de4e0632d90e0d1d5a9b8859a94c9ac25f65))

I would try to dig a little deeper but can't guarantee there will be any output.

**Comment by ofey404** [comment]
I debugged with following code and found:

- The cause is the `d.clear()` in `Key.__hash__()`.
- Any value type will trigger the segfault, except the builtin type (I tested using `str` and `dict` directly.)

```python
import gc

class Key(str):
    def __hash__(self):
        d.clear()
        return 0

class Value(str):
    pass

d = {}
d[Key()] = Value()

e = Exception()
e.__setstate__(d)

gc.collect() # Sigfault happens here
```

According the stacktrace, it dies in `deduce_unreachable` in GC module.

https://github.com/python/cpython/blob/ff54dd96cbe589635ed95c8b5b26bc768166b07d/Modules/gcmodule.c#L1095-L1103

And finally `if (Py_TYPE(v)->tp_repr == NULL)` triggered the segfault.

https://github.com/python/cpython/blob/ff54dd96cbe589635ed95c8b5b26bc768166b07d/Objects/object.c#L409-L411

**Comment by ofey404** [comment]
What confused me is that, if I comment out the `e.__setstate__` line, nothing happens during garbage collection.

Does the `__setstate__` call put the dict into an inconsistent state?

**Comment by ofey404** [comment]
The problem lies on the value's refcount: it becomes -2459565876494606881。

<img width="985" alt="image" src="https://user-images.githubusercontent.com/35857538/193280416-8bb30a6f-7602-4521-9426-e39a5ed6d4d4.png">

**Comment by ofey404** [comment]
Find the cause of wrongly set refcount:

https://github.com/python/cpython/blob/9f2f1dd131b912e224cd0269adde8879799686c4/Objects/typeobject.c#L4017-L4032

The `hash = PyObject_Hash(name);` is exactly the line which touch the refcount.

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/35857538/193294614-aed79de6-0b33-4c52-b232-16e12dabddf2.png">

----

So the problem is in `_PyType_Lookup` at `_PyObject_GenericSetAttrWithDict`. Finally it will call `__hash__` method again, and the refcount of value would be wrongly toggled.

https://github.com/python/cpython/blob/ff54dd96cbe589635ed95c8b5b26bc768166b07d/Objects/object.c#L1370-L1390

<details>
  <summary>Full stack trace</summary>
  
libc.so.6!__memset_avx2_unaligned_erms (Unknown Source:0)
_PyMem_DebugRawFree(void * ctx, void * p) (\home\ofey\Code\cpython-source-reading\cpython\Objects\obmalloc.c:2575)
_PyMem_DebugFree(void * ctx, void * ptr) (\home\ofey\Code\cpython-source-reading\cpython\Objects\obmalloc.c:2709)
PyObject_Free(void * ptr) (\home\ofey\Code\cpython-source-reading\cpython\Objects\obmalloc.c:742)
PyObject_GC_Del(void * op) (\home\ofey\Code\cpython-source-reading\cpython\Modules\gcmodule.c:2366)
unicode_dealloc(PyObject * unicode) (\home\ofey\Code\cpython-source-reading\cpython\Objects\unicodeobject.c:1557)
subtype_dealloc(PyObject * self) (\home\ofey\Code\cpython-source-reading\cpython\Objects\typeobject.c:1573)
_Py_Dealloc(PyObject * op) (\home\ofey\Code\cpython-source-reading\cpython\Objects\object.c:2383)
Py_DECREF(PyObject * op, int lineno, const char * filename) (\home\ofey\Code\cpython-source-reading\cpython\Include\object.h:549)
Py_XDECREF(PyObject * op) (\home\ofey\Code\cpython-source-reading\cpython\Include\object.h:625)
free_keys_object(PyDictKeysObject * keys) (\home\ofey\Code\cpython-source-reading\cpython\Objects\dictobject.c:672)
dictkeys_decref(PyDictKeysObject * dk) (\home\ofey\Code\cpython-source-reading\cpython\Objects\dictobject.c:324)
PyDict_Clear(PyObject * op) (\home\ofey\Code\cpython-source-reading\cpython\Objects\dictobject.c:2070)
dict_clear(PyDictObject * mp, PyObject * _unused_ignored) (\home\ofey\Code\cpython-source-reading\cpython\Objects\dictobject.c:3379)
method_vectorcall_NOARGS(PyObject * func, PyObject * const * args, size_t nargsf, PyObject * kwnames) (\home\ofey\Code\cpython-source-reading\cpython\Objects\descrobject.c:454)
_PyObject_VectorcallTstate(PyThreadState * tstate, PyObject * callable, PyObject * const * args, size_t nargsf, PyObject * kwnames) (\home\ofey\Code\cpython-source-reading\cpython\Include\internal\pycore_call.h:92)
PyObject_Vectorcall(PyObject * callable, PyObject * const * args, size_t nargsf, PyObject * kwnames) (\home\ofey\Code\cpython-source-reading\cpython\Objects\call.c:300)
_PyEval_EvalFrameDefault(PyThreadState * tstate, _PyInterpreterFrame * frame, int throwflag) (\home\ofey\Code\cpython-source-reading\cpython\Python\ceval.c:4173)
_PyEval_EvalFrame(int throwflag, struct _PyInterpreterFrame * frame, PyThreadState * tstate) (\home\ofey\Code\cpython-source-reading\cpython\Include\internal\pycore_ceval.h:95)
_PyEval_Vector(PyThreadState * tstate, PyFunctionObject * func, PyObject * locals, PyObject * const * args, size_t argcount, PyObject * kwnames) (\home\ofey\Code\cpython-source-reading\cpython\Python\ceval.c:5791)
_PyFunction_Vectorcall(PyObject * func, PyObject * const * stack, size_t nargsf, PyObject * kwnames) (\home\ofey\Code\cpython-source-reading\cpython\Objects\call.c:396)
_PyObject_VectorcallTstate(PyObject * kwnames, size_t nargsf, PyObject * const * args, PyObject * callable, PyThreadState * tstate) (\home\ofey\Code\cpython-source-reading\cpython\Include\internal\pycore_call.h:92)
PyObject_CallOneArg(PyObject * func, PyObject * arg) (\home\ofey\Code\cpython-source-reading\cpython\Objects\call.c:378)
call_unbound_noarg(int unbound, PyObject * func, PyObject * self) (\home\ofey\Code\cpython-source-reading\cpython\Objects\typeobject.c:1759)
slot_tp_hash(PyObject * self) (\home\ofey\Code\cpython-source-reading\cpython\Objects\typeobject.c:8044)
PyObject_Hash(PyObject * v) (\home\ofey\Code\cpython-source-reading\cpython\Objects\object.c:769)
find_name_in_mro(PyTypeObject * type, PyObject * name, int * error) (\home\ofey\Code\cpython-source-reading\cpython\Objects\typeobject.c:4027)
_PyType_Lookup(PyTypeObject * type, PyObject * name) (\home\ofey\Code\cpython-source-reading\cpython\Objects\typeobject.c:4097)
_PyObject_GenericSetAttrWithDict(PyObject * obj, PyObject * name, PyObject * value, PyObject * dict) (\home\ofey\Code\cpython-source-reading\cpython\Objects\object.c:1390)
PyObject_GenericSetAttr(PyObject * obj, PyObject * name, PyObject * value) (\home\ofey\Code\cpython-source-reading\cpython\Objects\object.c:1463)
PyObject_SetAttr(PyObject * v, PyObject * name, PyObject * value) (\home\ofey\Code\cpython-source-reading\cpython\Objects\object.c:1022)
BaseException_setstate(PyObject * self, PyObject * state) (\home\ofey\Code\cpython-source-reading\cpython\Objects\exceptions.c:170)
method_vectorcall_O(PyObject * func, PyObject * const * args, size_t nargsf, PyObject * kwnames) (\home\ofey\Code\cpython-source-reading\cpython\Objects\descrobject.c:482)
_PyObject_VectorcallTstate(PyThreadState * tstate, PyObject * callable, PyObject * const * args, size_t nargsf, PyObject * kwnames) (\home\ofey\Code\cpython-source-reading\cpython\Include\internal\pycore_call.h:92)
PyObject_Vectorcall(PyObject * callable, PyObject * const * args, size_t nargsf, PyObject * kwnames) (\home\ofey\Code\cpython-source-reading\cpython\Objects\call.c:300)
_PyEval_EvalFrameDefault(PyThreadState * tstate, _PyInterpreterFrame * frame, int throwflag) (\home\ofey\Code\cpython-source-reading\cpython\Python\ceval.c:4173)
_PyEval_EvalFrame(int throwflag, struct _PyInterpreterFrame * frame, PyThreadState * tstate) (\home\ofey\Code\cpython-source-reading\cpython\Include\internal\pycore_ceval.h:95)
_PyEval_Vector(PyThreadState * tstate, PyFunctionObject * func, PyObject * locals, PyObject * const * args, size_t argcount, PyObject * kwnames) (\home\ofey\Code\cpython-source-reading\cpython\Python\ceval.c:5791)
PyEval_EvalCode(PyObject * co, PyObject * globals, PyObject * locals) (\home\ofey\Code\cpython-source-reading\cpython\Python\ceval.c:591)
run_eval_code_obj(PyThreadState * tstate, PyCodeObject * co, PyObject * globals, PyObject * locals) (\home\ofey\Code\cpython-source-reading\cpython\Python\pythonrun.c:1713)
run_mod(mod_ty mod, PyObject * filename, PyObject * globals, PyObject * locals, PyCompilerFlags * flags, PyArena * arena) (\home\ofey\Code\cpython-source-reading\cpython\Python\pythonrun.c:1734)
pyrun_file(FILE * fp, PyObject * filename, int start, PyObject * globals, PyObject * locals, int closeit, PyCompilerFlags * flags) (\home\ofey\Code\cpython-source-reading\cpython\Python\pythonrun.c:1629)
_PyRun_SimpleFileObject(FILE * fp, PyObject * filename, int closeit, PyCompilerFlags * flags) (\home\ofey\Code\cpython-source-reading\cpython\Python\pythonrun.c:439)
_PyRun_AnyFileObject(FILE * fp, PyObject * filename, int closeit, PyCompilerFlags * flags) (\home\ofey\Code\cpython-source-reading\cpython\Python\pythonrun.c:78)
pymain_run_file_obj(PyObject * program_name, PyObject * filename, int skip_source_first_line) (\home\ofey\Code\cpython-source-reading\cpython\Modules\main.c:360)
pymain_run_file(const PyConfig * config) (\home\ofey\Code\cpython-source-reading\cpython\Modules\main.c:379)
pymain_run_python(int * exitcode) (\home\ofey\Code\cpython-source-reading\cpython\Modules\main.c:610)
Py_RunMain() (\home\ofey\Code\cpython-source-reading\cpython\Modules\main.c:689)
pymain_main(_PyArgv * args) (\home\ofey\Code\cpython-source-reading\cpython\Modules\main.c:719)
Py_BytesMain(int argc, char ** argv) (\home\ofey\Code\cpython-source-reading\cpython\Modules\main.c:743)
main(int argc, char ** argv) (\home\ofey\Code\cpython-source-reading\cpython\Programs\python.c:15)
</details>

**Comment by ofey404** [comment]
So... What should we do with it?

I think I need some guidance/reference now, about what `_PyType_Lookup` does, and what's the MRO.

**Comment by gvanrossum** [comment]
Thanks for the deep research!

I think the root cause is something that happens in `BaseException_setstate()`, in Python/exceptions.c. In particular these four lines:
```cc
        while (PyDict_Next(state, &i, &d_key, &d_value)) {
            if (PyObject_SetAttr(self, d_key, d_value) < 0)
                return NULL;
        }
```
are likely to end up missing an INCREF when the dict is cleared by the hash call. I suspect it's happening in the `PyObject_SetAttr()` call, since `PyDict_Next()` has no need for the hash.

Looking at the code for `PyObject_SetAttr()`, it does an `INCREF(name)` / `DECREF(name)` around the important bits, but it doesn't do the same for the value. Possibly it should -- or in this case the caller should?

**Comment by ofey404** [comment]
I tried to play around, adding `INCREF(value) / DECREF(value)` pair around some suspicious place, but the Makefile crushed before I can run and debug what's happending inside.

I wonder how could I build and inspect `INCREF` and `DECREF` behavior correctly, and I would post this question in the Core-Mentorship list.

```bash
make -s -j
# make: *** [Makefile:1306: Python/deepfreeze/deepfreeze.c] Segmentation fault (core dumped)
```

**Comment by kumaraditya303** [comment]
It is indeed missing an incref before calling `tp_hash` slot in `PyObject_SetAttr`.  See similar issue https://github.com/python/cpython/issues/92930

The following patch fixes it:
```diff
diff --git a/Objects/exceptions.c b/Objects/exceptions.c
index 3703fdcda4..3680c6068b 100644
--- a/Objects/exceptions.c
+++ b/Objects/exceptions.c
@@ -167,8 +167,14 @@ BaseException_setstate(PyObject *self, PyObject *state)
             return NULL;
         }
         while (PyDict_Next(state, &i, &d_key, &d_value)) {
-            if (PyObject_SetAttr(self, d_key, d_value) < 0)
+            Py_INCREF(d_key);
+            Py_INCREF(d_value);
+            int res = PyObject_SetAttr(self, d_key, d_value);
+            Py_DECREF(d_key);
+            Py_DECREF(d_value);
+            if (res < 0) {
                 return NULL;
+            }
         }
     }
     Py_RETURN_NONE;

```

**Comment by ofey404** [comment]
Wow, I'll check the issue. With this patch, the bug disappeared. Should I make a PR for the patch? @kumaraditya303 

----

I guess it's fixed before, but the patch is reversed for some reason. I would look into the line history.

In the latest main, the inc/dec ref pair is still missing:

https://github.com/python/cpython/blob/273a819ed2c927ed205ff334ea997cb62b1d20af/Objects/exceptions.c#L158-L175

**Comment by kumaraditya303** [comment]
> Wow, I'll check the issue. With this patch, the bug disappeared. Should I make a PR for the patch?

Feel free to create a PR with tests.

**Comment by ofey404** [comment]
I check the line history but didn't find many useful options. These lines seems to be unchanged since the cpython repo migrated from SVN in 2006? [This is the commit.](https://github.com/python/cpython/commit/4d70c3d9dded0f0fa7a73c67217a71111d05df4d)

```bash
git log -L '/PyObject_SetAttr(self, d_key, d_value)/,+5:Objects/exceptions.c'

  commit 4d70c3d9dded0f0fa7a73c67217a71111d05df4d
  Author: Thomas Wouters <thomas@python.org>
  Date:   Thu Jun 8 14:42:34 2006 +0000

....

  diff --git a/Objects/exceptions.c b/Objects/exceptions.c
  --- a/Objects/exceptions.c
  +++ b/Objects/exceptions.c
  @@ -167,0 +170,5 @@
  +            if (PyObject_SetAttr(self, d_key, d_value) < 0)
  +                return NULL;
  +        }
  +    }
  +    Py_RETURN_NONE;
```

**Comment by ofey404** [comment]
> Feel free to create a PR with tests.

I would create a test triggering this behavior ;)

**Comment by ofey404** [comment]
PR is created.

`Lib/test/test_baseexception.py` is a better place for this test to go, since:

https://github.com/python/cpython/blob/273a819ed2c927ed205ff334ea997cb62b1d20af/Lib/test/test_baseexception.py#L7-L10

**Comment by gvanrossum** [comment]
Thanks for your investigation and patch!
