### ISSUE TITLE
Lack of a blank line after `.. impl-detail::`

### ISSUE THREAD

**Issue by StevenHsuYL** [python/cpython#97607]
# Documentation

This issue is made for translation work of documentation.

The issue is that if a blank line was absent after `.. impl-detail::`, the Sphinx would not build the paragraph after this line during HTML file generation for zh-tw translation.
I found this issue in three .rst files:

[Doc/library/queue.rst](https://github.com/python/cpython/blob/main/Doc/library/queue.rst)
[Doc/library/readline.rst](https://github.com/python/cpython/blob/main/Doc/library/readline.rst)
[Doc/howto/isolating-extensions.rst](https://github.com/python/cpython/blob/main/Doc/howto/isolating-extensions.rst)

A blank line after `.. impl-detail::` is suggested in those places for a complete building of corresponding translation pages.
Thanks!

### Linked PRs
* gh-97652

**Comment by CAM-Gerlach** [comment]
To make a long story short, after a lot of digging and investigation, I've uncovered, tested and implemented in #97652 a fix to the problem here—the [custom `impl-detail` directive](https://github.com/python/cpython/blob/4652093e1b816b78e9a585d671a807ce66427417/Doc/tools/extensions/pyspecific.py#L100) is configured to consume text in the same paragraph (either with no or one line break after the directive start `::`) as an optional argument, rather than just taking no arguments and simply treating it as first content paragraph by default, as the built-in Docutils/Sphinx directives that behave similarly (e.g. the various `admonition`s) do. This results in it missing the evidently key metadata (e.g. raw source, file and line number) in the parsed doctree nodes, that in turn breaks the translation code that requires this metadata.

Implementing the latter ensures translations work correctly for all three cases (0, 1 or 2 line breaks before directive content) anywhere the directive is used, now and in the future, makes the behavior consistent with the builtin directives, and substantially simplifies the directive code and logic, while not modifying the non-translated HTML output. See #97652 for the fix.
