### ISSUE TITLE
Update activate(.bat) for a dynamic VIRTUAL_ENV

### ISSUE THREAD

**Issue by kxrob** [python/cpython#97647]
# Feature or enhancement

Update venv `Scripts/activate.bat`  and `activate `(sh) for a dynamic VIRTUAL_ENV so we can move / rename the tree 
(`Activate.ps1` already does this)

# Pitch

After moving a venv in the filesystem, it failed and required manual edit of the activate(.bat) scripts.

**Comment by vsajip** [comment]
Just updating `activate.bat` won't fully solve the problem. Any scripts installed in the venv will contain the absolute path to the venv's interpreter in their shebangs, so after moving the venv, those scripts will fail. So, making this change might imply that you can just move/rename venvs, but that won't be the case.

**Comment by vsajip** [comment]
That's not the launcher that's used for installing scripts, as far as I know. The launchers used by `pip` are those provided by [`distlib`](https://github.com/pypa/pip/tree/main/src/pip/_vendor/distlib), and they _do_ use a shebang (somewhere inside the `.exe`) to locate the interpreter to use.

**Comment by vsajip** [comment]
Note that venvs are meant to be disposable, and easy to re-create using e.g. `pip install -r requirements.txt`. There's no real reason to move them from A to B when you can just recreate at B.

**Comment by zooba** [comment]
Also, the reason Activate.ps1 changed style was so that we can code sign it once and have it remain valid. If we modified it, we'd break the signature and some systems would refuse to run it.

**Comment by kxrob** [comment]
> The launchers used by `pip` are those provided by [`distlib`](https://github.com/pypa/pip/tree/main/src/pip/_vendor/distlib)

So it would require changes there too. ->Linked FR.
Which may be reasonable independently - its affects the home python relocatability.
Otherwise python seems to work well in a no-install / rel path way overall, and is obviously designed so.

(For a test I HEX-edited the path in a sample stub exe to non-abs `#!python.exe` + spaces, and then it used the moved venv's  python - which by chance comes first in venv PATH. More robust would perhaps be to use the nearby python explicitely in the distlib `launcher.c` - and an archived abs path optionally on failure perhaps.)

> venvs are meant to be disposable, and easy to re-create

Not generally. Movable would be much better and would just require these 2 rather simple steps.
Venvs often are also are very big and / or not settled yet.
In a world of no-install, virtual folders, net / mount / link points etc. some use cases are not possible with abs path pinning.
And for example in the case where I needed that change (which finally triggered this issue) I use a rather permanent mini-venv (git, checkout paths not absolute) for activating a source tree execution environment: https://github.com/kxrob/pywin32/commit/cbb5e331


> Also, the reason Activate.ps1 changed style was so that we can code sign it once

Various needs enforce the more universal solution...

**Comment by vsajip** [comment]
As the comments by @pfmoore on the pip FR indicate, it's not a very simple problem to solve as you seem to be implying (i.e. with respect to backward compatibility guarantees), and I still see no strong case why a venv can't just be recreated at a new path. You could write a tool for your own use which relocates everything in your venvs and that would solve your problem, and yet not burden volunteer maintainers with reviewing or implementing functionality that seems to be a niche use case, which most people won't need, and may cause compatibility issues, and will need to be supported forever after.

**Comment by sf-kkelly** [comment]
> I still see no strong case why a venv can't just be recreated at a new path.

Your inability to see it doesn't mean it doesn't exist.

Creating a venv from scratch requires other system-level dependencies (compiler/linker toolchains, development libraries, ODBC, etc) to be installed, which is not an easy or technically tractable approach for many enterprise-grade CI pipeline runners or strictly-IT-managed workstations.  It's also a very fragile/unreliable approach because it can be very easily broken by a wide variety of machine-specific environmental/configuration problems.   That doesn't work for the reliability needs of large-scale organizations.

Also, doing all of the same identical version resolution, artifact fetching over the wire, compilation, linking, installation, etc, on every endpoint machine, just to yield a result that's identical other than stupidly-embedded hard-coded paths, is redundant (and thus wasteful) work.  It needlessly and inefficiently consumes network bandwidth and CPU/disk resources that ought not be consumed, and at enterprise scales, that adds up fast.

Overall, the Python community's inability to think through, and resistance to believing or even considering the needs of enterprise-scale corporate use cases, is a fantastically heinous annoyance.  It means desperately-needed features get shot done, and stupidly-bad coding practices (such as hard-coding absolute paths into everything) are used like some kind of wild-west free-for-all.

Please expand your thinking and accept the high-level ask as an important feature request.  Python itself -- on all platforms -- should be portable (i.e. runnable out of any folder, without being "installed"), and in the same vein, virtual environments should be relocatable.  Period.

**Comment by AlexWaygood** [comment]
@sf-kkelly I'm sorry, that's not an acceptable tone. Please remember to treat other members of the community with respect, assume good faith where possible, and to abide by the [Python code of conduct](https://www.python.org/psf/conduct/) at all times.

Telling open-source volunteers that their "inability to think through, and resistance to even believe or consider [your] needs [...] is a fantastically heinous annoyance" is also fairly unlikely to persuade them to do what you'd like them to.

**Comment by sf-kkelly** [comment]
Tone aside, everything I wrote is entirely accurate.

**Comment by sf-kkelly** [comment]
Don't want frustrated users?  Maybe don't dismiss their clearly and repeatedly explained needs.  Just saying 🤷

**Comment by vsajip** [comment]
And I'll reiterate what I said in an earlier comment:

> You could write a tool for your own use which relocates everything in your venvs and that would solve your problem, and yet not burden volunteer maintainers with reviewing or implementing functionality that seems to be a niche use case, which most people won't need, and may cause compatibility issues, and will need to be supported forever after.

**Comment by brettcannon** [comment]
Simply updating `activate.bat` (or any of the other activation scripts) does not also update `pyvenv.cfg`, for instance, and so it isn't as simple as just updating one activation script unfortunately.

It will also greatly complicate those activation scripts as we will have to update them for every shell we support which is not necessarily an easy thing to manage. And we don't want to promise relocation just on Windows, nor would we want to unofficially support it as the instant people rely on it and we stop supporting it we will get bug reports even if we point out we never declared support

As such, I'm going to reject this feature request and suggest folks come up with their own script or tooling to relocate virtual environments (which are not hard to create from scratch sans activation scripts, so I don't think this is an undue burden to ask the community to support this use case; you could try asking the virtualenv project itself to support this somehow).
