### ISSUE TITLE
list.copy()

### ISSUE THREAD

**Issue by d-jackson-576** [python/cpython#97697]
# Documentation

In [3.10.7 Documentation](https://docs.python.org/3/index.html) » [The Python Tutorial](https://docs.python.org/3/tutorial/index.html) » [5. Data Structures](https://docs.python.org/3/tutorial/datastructures.html)

the documentation states that list.copy() is a shallow copy but when I check it by copying a list and I find they have different ids. I make a change in the original list and it does not change the copy of the list.  If I use list2 = list1, then list2 is a shallow copy of list1 and both have the same id and changes made to the original items in list1 are reflected in list2. None of this happens when I use list2=list1.copy().

**Comment by pochmann** [comment]
Where did you read that shallow copy means what you think it means?

**Comment by sweeneyde** [comment]
Suppose we have

```python
>>> a = [[], [], []]
```

Then `a2 = a` does not make a copy at all, it simply gives the same object a different name:

```python
>>> a = [[], [], []]
>>> a2 = a
>>> a2 is a
True
>>> id(a2) == id(a)
True
>>> a2.append(42)
>>> a
[[], [], [], 42]
```

On the other hand, `b = a.copy()` does create a copy.

```python
>>> a = [[], [], []]
>>> b = a.copy()
>>> b.append(42)
>>> a # no change
[[], [], []]
```

The phrase "shallow copy" refers to the fact that the copy contains references to the same items as the original list does -- it does not make new copies of those items. For example:

```python
>>> a = [[], [], []]
>>> b = a.copy()
>>> b[0] is a[0]
True
>>> b[0].append(42)
>>> a
[[42], [], []]
```

So there are three concepts here:

1. `a2 = a`: alias the list. Don't copy anything, use the same object.
2. `b = a.copy()`: Do a shallow copy. Put the contents in a new list object.
3. `import deepcopy; c = deepcopy.deepcopy(a)`: Do a deep copy. Copy over this list, and recursively make new copies of all the list's contents as well.

The phrase "shallow" refers to the fact that the copy is only one level deep, not recursive. In other words, "shallow" distinguishes between cases 2 and 3, not cases 1 and 2.

**Comment by stevendaprano** [comment]
The documentation is correct, and you misunderstand what a copy is.

When you say `list2 = list1`, that is **not a copy at all**, it is just a second name for the same object. Both names `list1` and `list2` refer to the same object, so they have the same ID.

Is there some other part of the documentation or the tutorial which wrongly says that `list2 = list1` is a copy? If so that should be fixed, otherwise I am afraid that this is just your misunderstanding of what a copy is.

(Note: `list2 = list1[:]` *does* make a copy, as that uses string slicing to make a new list.)

**Comment by d-jackson-576** [comment]
Thank you for correcting me on the list2 = list1 not being a copy.

What about when you can use list2 = list1.copy()? The documentation says
that is a shallow copy but I find they have different id's. Wouldn't they
have the same id if a shallow copy had been made?

**Comment by TeamSpen210** [comment]
No, because IDs are a matter of identity - two objects always have different IDs. If it's a copy, it's a different object, and so it must have a different ID.

**Comment by d-jackson-576** [comment]
So then you can tell it's a shallow copy if you change original items in
the original list, and see that in the copied list the items change as well.

>>> x=[1,2,3]
>>> y = x.copy()
>>> x[0]=5
>>> print(x)
[5, 2, 3]
>>> print(y)
[1, 2, 3]
>>>

I was expecting the y[0] to change to 5 as well since copy() is meant to be
shallow. What am I missing here?

**Comment by stevendaprano** [comment]
You are missing understanding of what it means to be a copy.



If you use a photocopier to make a copy of a page, and then scribble on 

the copy, the drawings don't also appear on the original. Because it is 

a *copy*.



If the drawings were to appear on both pages, they aren't *copies* but 

somehow the same page in two places at once. We can't do that in real 

life with actual paper, but we can do that with objects in Python.



Another analogy is that people can have multiple names, just like Python 

objects. My father's name is John. If I give John a cup of tea, just 

like magic Dad gets a cup of tea too -- because Dad and John are the 

same person, **not copies of each other**.



If I shoved John into a cloning machine and made a copy, then Dad and 

Dad #2 would be different people and if I gave Dad a cup of tea, Dad #2 

would miss out. But if I transfer $50 into Dad's bank account, Dad #2 

can withdraw it because he knows the PIN too.



A shallow copy is like putting the object into a cloning machine, you 

end up with two objects.



A *deep copy* is like putting the object into a cloning machine, **and** 

also making a copy of the bank account, complete with the same amount 

of money but a different PIN, so that Dad and Dad #2 are no longer 

sharing the same bank account.



The bug tracker is really not the right place for this discussion. If 

you are still confused, please move this discussion to a help forum such 

as Reddit's r/learnpython, the community forum [here](https://python-forum.io/), 

[Discuss](https://discuss.python.org/), or the Python 

[tutor mailing list](https://mail.python.org/mailman/listinfo/tutor).



This is not an exhaustive list of communities that can help you.

**Comment by d-jackson-576** [comment]
Hi Stefan and Dennis,

Thank you for helping me to understand what is going on. Here is where I
read what is meant by shallow copy:
https://docs.python.org/3/library/copy.html

Thank you for the examples. I didn't realize there was an alias that could
be used. I always thought a shallow copy means you now have two variables
that point to the same location in memory.

>>> x = [1, 2, 3]
>>> y = x.copy()
>>> print(hex(id(x)))
0x2230df0
>>> print(hex(id(y)))
0x3c098a0
>>>

So the copy function is meant to be a shallow copy but the two lists have
different ids. So is this still a shallow copy? It doesn't seem like it is
to me due to the different addresses.

Thanks again,
Deb
