### ISSUE TITLE
An operator issue '=+'

### ISSUE THREAD

**Issue by Mitchell-kw-Lee** [python/cpython#97895]
# Bug report
An ambigous operator allowed to use. '=+'  which is not '+='

# Your environment
- python-3.10.7
- Windows 11 22H2
- AMD CPU

# Expectation:
Make an error message when weired operators are used as this and to be corrected by user.

# Test code:
_wait_seconds = 0
while _wait_seconds < 8: #
	#print('processing 1', _wait_seconds)
	_wait_seconds =+ 1 # <<---- this makes infinite loop
	#print('processing 2', _wait_seconds)

**Comment by sweeneyde** [comment]
Note that `a =+ b` is parsed as `a = (+b)`, with a unary positive operator. Real-world code might use this, so changing this would break backward compatibility. Example code that works now, and should continue working:

```python
>>> a=+1
>>> b=-2
>>> c=+3
>>> a+b+c
2
```

This seems like a concern well-suited for a linter to flag as suspicious (the whitespace is misleading), but it's not something that the Python interpreter should forbid.

**Comment by Mitchell-kw-Lee** [comment]
Suggesting improvment to warn to insert white space when it uses.
as far as the real world know is that 'a = +b' no meaning that nothing usefull which do nothing oviously(unless a = -b).

**Comment by sweeneyde** [comment]
This is a great opportunity to use a linter. For example, the popular linter `flake8` outputs the following on such statements:

```
.\stuff3.py:3:4: E225 missing whitespace around operator
x =+ y
   ^
```

Using a linter on one's code is usually a pretty good idea. But there is not much precedent for including such warnings in the Python interpreter itself, especially since valid code might include such statements.

While it is true that `+a` is no different from `a` if `a` is a `float` or an `int`, that isn't guaranteed to be the case for all objects. For example, `collections.Counter` and `decimal.Decimal` have nontrivial `__pos__` special methods, so `+my_counter` may not be the same as `my_counter`, and `+my_decimal` may not be the same as `my_decimal`.
