### ISSUE TITLE
tkinter.Text.count(index1, index2) returns None not (0,) when index1 equals index2

### ISSUE THREAD

**Issue by RogerMarsh** [python/cpython#97928]
Surely the Text.count() method should return (0,) in the title code snippet?  Following the example of what happens when more than one option is given.

I suppose the text_count method should do so too, but it was a hack of something that did not exist when written.

Tk8.6 documentation says a list of integers is returned.

Sample code below.
 
```python
import tkinter


def text_count(widget, index1, index2, *options):
    """Hack Text count command. Return integer, or tuple if len(options) > 1.

    Tkinter does not provide a wrapper for the Tk Text widget count command
    at Python 2.7.1

    widget is a Tkinter Text widget.
    index1 and index2 are Indicies as specified in TkCmd documentation.
    options must be a tuple of zero or more option values.  If no options
    are given the Tk default option is used.  If less than two options are
    given an integer is returned.  Otherwise a tuple of integers is returned
    (in the order specified in TkCmd documentation).

    See text manual page in TkCmd documentation for valid option values and
    index specification.

    Example:
    chars, lines = text_count(widget, start, end, '-chars', '-lines')

    """
    return widget.tk.call((widget._w, 'count') + options + (index1, index2))


text = tkinter.Text()

print(text.count("1.0", tkinter.END))                                       # (1,0)
print(text.count("1.0", "1.0"))                                                 # None
print(text_count(text, "1.0", "1.0"))                                        # 0
print(text_count(text, "1.0", tkinter.END))                              # 1
print(text.count("1.0", tkinter.END, "chars"))                         # (1,)
print(text.count("1.0", "1.0", "chars"))                                   # None
print(text_count(text, "1.0", "1.0", "-chars"))                         # 0
print(text_count(text, "1.0", tkinter.END, "-chars"))               # 1
print(text.count(tkinter.END, "1.0", "chars"))                         # (-1,)
print(text_count(text, tkinter.END, "1.0", "-chars"))               # -1
print(text.count("1.0", tkinter.END, "chars", "lines"))             # (1, 1)
print(text.count("1.0", "1.0", "chars", "lines"))                       # (0, 0)
print(text_count(text, "1.0", "1.0", "-chars", "-lines"))            # (0, 0)
print(text_count(text, "1.0", tkinter.END, "-chars", "-lines"))  # (1, 1)
```

### Linked PRs
* gh-98484
* gh-115031

**Comment by serhiy-storchaka** [comment]
There are other issues with `Text.count()`.

* Options starting with `'-'`  are silently ignored. It can lead to bugs: `text.count(begin, end, '-lines'))` returns the the number of "indices" rather than the number of lines. Perhaps the initial intention was to only ignore the `'-'` prefix, so `'-lines'` and `'lines'` would mean the same, but it never worked. It is better to make it an error.
* If `wantobjects` was set to 0, the method returns a string.
* It tries to always return a tuple (except when the result is zero count), but it fails with the `'update'` option (which is undocumented in Tkinter). It returns an integer for `'update', 'ypixels'` and `'update', 'indices'`, but a 1-tuple for `'ypixels'` and `'update'`.

There were no any tests for this method, so all this was unnoticed.

Other issues could be solved in compatible way, but the originally reported issue does not have backward compatible solution. Returning `(0.)` instead of `None` would make the behavior more uniform, but it would break the code `if text.count(begin, end)` which just checks where there is something in the interval.

I think that the decision of returning 1-tuple for a single count (unless it is zero) was a mistake. The Tk code is different for a single count and multiple code -- a single count is returned as an integer instead of a 1-list. The difference is only disappeared if convert it to string.

It would be more convenient for users to get an integer in Python too. But it is a breaking change. Choosing between two breaking changes, returning `(0,)` for an empty count or returning a single count as integer, I prefer the latter.

**Comment by terryjreedy** [comment]
Thanks for the fix.

**Comment by terryjreedy** [comment]
I clicked and read most of that discussion.
