### ISSUE TITLE
open() not supported for `~`

### ISSUE THREAD

**Issue by ghost** [python/cpython#98081]
for UNIX platforms please add support for `open(~/readme)` , that would be better in case of `open(/home/user/readme)`

**Comment by arhadthedev** [comment]
You can expand ~ in a single line:

```python
from pathlib import Path
open(Path.home() / "readme")
```

or

```python
import os
open(os.path.expanduser("~/readme"))
```

The first way is better for hardcoded paths, the second one allows to feed input from a user and configuration files.

The `open` cannot do it by itself without programmer's conscience for security reasons. Otherwise, any server written in Python would happily allow to leak environment variables with tokens and passwords via file access error messages.
