### ISSUE TITLE
change sqlite docs to make it clear many platforms ship with loadable extensions

### ISSUE THREAD

**Issue by abe-winter** [python/cpython#98080]
# Documentation

The docs for the `sqlite3` library make it sound like loadable extensions are generally not available, and the only way to get this feature is to rebuild python. But this *is* available in:
- standard python on my ubuntu laptop
- the python docker image (including `python:slim`)
- my ancient macbook air has the config flag (probably because of homebrew)

Is it worth changing the docs to make it clear this is available by default in some places?

https://github.com/python/cpython/blob/3.10/Doc/library/sqlite3.rst

Current docs:

> The sqlite3 module **is not built with loadable extension support by default**, because some platforms (notably macOS) have SQLite libraries which are compiled without this feature. To get loadable extension support, you must pass the [--enable-loadable-sqlite-extensions](https://docs.python.org/3/using/configure.html#cmdoption-enable-loadable-sqlite-extensions) option to configure.

Is it worth changing this to:

> Loadable extension support is controlled by the `--enable-loadable-sqlite-extensions` build option. Because some platform SQLite libraries are compiled without this feature, this isn't available everywhere. Look at `sysconfig.get_config_var('CONFIG_ARGS')` to make sure.

**Comment by ramvikrams** [comment]
Sir can I do the change

**Comment by erlend-aasland** [comment]
Thanks for your interest in improving the CPython docs.

IMO, the suggested text is more confusing than the current docs.

**Comment by erlend-aasland** [comment]
> My point is that all the distributions I tried _do_ have loadable extension. Therefore this line in the original text is not quite right:
> 
> > To get loadable extension support, you must pass the [--enable-loadable-sqlite-extensions](https://docs.python.org/3/using/configure.html#cmdoption-enable-loadable-sqlite-extensions) option to configure

Some -- _not all_ -- distributions supply SQLite builds that have loadable extension support. Please note that the SQLite docs **actively discourage**[^1][^2] the use of the SQLite C APIs used to implement the `enable_load_extension()` and `load_extension()` _sqlite3 connection_ methods. This is why _many_ distributions, including macOS and various Linux distros, choose to leave these APIs disabled. In order to get loadable extension support in the _sqlite3_ stdlib extension module, the _SQLite_ library linked with it needs to have been configured and built with loadable extension support, _and_ your Python executable needs to have been configured and built with `--enable-loadable-sqlite-extensions`. It is not enough that only SQLite or sqlite3 have this support built in; _both of them needs it enabled_.

> I did not pass this option to configure; in fact I did not rebuild python at all, and I still got loadable extension support.

Not quite correct: your SQLite library may have loadable extension support, but the _sqlite3 extension module_ may not have loadable extension support. In order for the _sqlite3_ stdlib extension module to have loadable extension support, Python will have to be configured using `--enable-loadable-sqlite-extensions` _and_ your SQLite library must have such support.

If your distro chose to build both SQLite and Python's sqlite3 extension module with loadable extension support: good for you, but other systems have other configurations.

 > As a sqlite novice, this made me think I couldn't easily deploy an app with a loadable extension because I would have to manage my own python builds.

You can of course deploy such an app, but it will not work for all Python installs. For instance, it will not work with macOS supplied Python.

[^1]: https://www.sqlite.org/c3ref/enable_load_extension.html -- note the security warning at the end of the page
[^2]: https://www.sqlite.org/c3ref/load_extension.html -- note the security warning at the end of the page

**Comment by abe-winter** [comment]
Fair enough -- you're the expert. Thanks for the attention on this, closing the ticket.
