### ISSUE TITLE
Add the ability to get the first element of the queue without removing

### ISSUE THREAD

**Issue by mascai** [python/cpython#98097]
# Feature or enhancement
In C++ we have a convenient method to get the first element without removing
More details `https://cplusplus.com/reference/queue/queue/front/`

Suggest to apply the same convenient method in python queue library

# Pitch
How can we get the first element without removing in python at this moment

```
from queue import Queue

q = Queue()
q.put("Test")

print(q.queue[0] ) # 'Test'

```
Suggest to replace  ```q.queue[0] ``` with ```q.front()```

Logic of the function: Return the first element if exist
Else return None

**Comment by sweeneyde** [comment]
Can you explain your use-case? The `queue` module is designed with synchronization semantics in mind, so that multiple threads of consumers or producers can share the same queue. If you do not need the extra condition variables, you can use `collections.deque()` directly, where you can `d.append(x)`, `d.popleft()`, and access `d[0]`.

In a multithreaded context, I'd be worried that the existence of a peek/front method would encourage users to write look-before-you-leap code with race conditions.

**Comment by rhettinger** [comment]
Closed for the reasons lists on the PR discussion and for the reasons listed by Dennis.

Thank you for the suggestion, but it is incompatible with guaranteed API. Also, it introduces another method with a builtin race condition which is a step backwards.  And it goes in the opposite directly of earlier efforts to make the API minimal.
