### ISSUE TITLE
make install installs pip etc. with the wrong shebang

### ISSUE THREAD

**Issue by ali-beep** [python/cpython#98183]
When building Python 3.10.7 from source on Linux (I have tried this using Ubuntu focal and CentOS 8 docker images), I do something like this to create a tarball distribution:

```
./configure --prefix=/opt/python3
make
make install DESTDIR=install
tar -C install -cJf python3.10.tar.xz opt/python3
```

When I extract that tarball to `/` the shebang for `pip3`, etc. is `#!/opt/python3/bin/python`, but that link doesn't exist.

Either `make install` needs to install the `python` symlink or the shebang should be `python3` and not `python`.

**Comment by eli-schwartz** [comment]
This is actually a distlib bug by way of pip. distlib is used by pip to handle script creation, and it has code to detect when running from a python build build tree and use the best versioned shebang it can, but the code was broken a while ago.

I submitted a PR to distlib which should fix this, although in order to actually deploy that fix it will need to:
- be tagged in a distlib release
- get distlib updated in pip
- get a pip release
- get pip updated in CPython
- get a CPython release

So that may take a while as there are a lot of moving parts. :)
