### ISSUE TITLE
Multiple files use `tuple()`, `list()` and `dict()`

### ISSUE THREAD

**Issue by Ombucha** [python/cpython#98323]
# Bug report

Multiple files use `tuple()`, `list()` and `dict()`, which can slow down performance.

**Comment by pochmann** [comment]
You also try to change `Exception or Exception` to just `Exception` in `test_bpo_42057`, even though [BPO 42057](https://github.com/python/cpython/issues/86223) makes it look like the duplication is absolutely intentional and essential. Do you understand why it is the way it is? And can you explain why it's not needed? You didn't even mention that change. Looks like [Chesterton's fence](https://en.wikipedia.org/wiki/Wikipedia:Chesterton's_fence).

How much do those `tuple()` etc calls slow down performance? And can you explain why they are the way they are, and why they don't need to be?

**Comment by Infiniticity** [comment]
> You also try to change Exception or Exception to just Exception in test_bpo_42057, even though [BPO 42057](https://github.com/python/cpython/issues/86223) makes it look like the duplication is intentional and essential.

I have reverted this change.

> How much do those tuple() etc calls slow down performance? And can you explain why they are the way they are, and why they don't need to be?

It can be inferred from [this StackOverflow answer](https://stackoverflow.com/a/5790954) that `tuple()` is much slower that just `()`.

**Comment by pochmann** [comment]
I know it's slower. And that answer shows differences of 140 nanoseconds. Is that even measurable in the cases you've changed?

**Comment by Infiniticity** [comment]
I am not sure about that.

**Comment by rhettinger** [comment]
Per the PR discussion, marking as closed.

Also a few other comments might be helpful when thinking about this.  Generally, we try to avoid sweeping through many modules at once because it risks destabilizing code  and it makes it harder to backport actual bugfixes.  Also, it is not wrong to write `dict()`, `list()`, or `tuple()`.  Sometimes that reflects the authors way of thinking about the problem and lets them highlight or call out the type for emphasis.   Most of the edits in the PR were aimed at tests or tools where we really don't care about micro-performance.
