### ISSUE TITLE
return list from `reverse`

### ISSUE THREAD

**Issue by maifeeulasad** [python/cpython#98385]
# Feature or enhancement
Enhancement, I would say.

`list.reverse()` takes no input parameter and returns `None`. We can simply return the list.

# Pitch
Now:
```
>>> fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
>>> fruits.reverse()
>>> fruits
['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']
```
After (If it gets implemented):
```
>>> fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
>>> fruits.reverse()
['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']
```

**_I'm open to implementing this. Thanks._**

# Previous discussion

**Comment by ronaldoussoren** [comment]
The current behaviour is intentional.  Methods on builtin sequences that modify the sequence don't return self. 

[This FAQ](https://docs.python.org/3/faq/design.html#why-doesn-t-list-sort-return-the-sorted-list) explains that better than I could do here. The FAQ is for ``list.sorted``, but the same reasoning applies here.
