### ISSUE TITLE
[CVE-2022-37454] Buffer overflow in the _sha3 module in python versions <= 3.10

### ISSUE THREAD

**Issue by botovq** [python/cpython#98517]
[CVE-2022-37454](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-37454) affects Python versions prior to 3.11. The fix discussed in [XKCP's advisory](https://github.com/XKCP/XKCP/security/advisories/GHSA-6w4m-2xhg-2658) can be adapted to these versions. The [discoverer's writeup](https://mouha.be/sha-3-buffer-overflow/) contains code that might be turned into regression tests.

Python 3.11 and later switched to using tiny_sha3 in GH-32060, so they should not be affected.

### Linked PRs
* gh-98519
* gh-98526
* gh-98527
* gh-98528

**Comment by gpshead** [comment]
Scope: When Python is linked against OpenSSL 1.1.1 or later, which is true on many modern systems, the OpenSSL provided `sha3` implementation will be used instead of the bundled `_sha3` XKCP module code.

You can tell if your Python 3.10 or earlier is vulnerable by doing the following:

A vulnerable Python looks like this:

```python
>>> import hashlib
>>> hashlib.sha3_224
<class '_sha3.sha3_224'>
```

A non-vulnerable looks like this:

```python
>>> import hashlib
>>> hashlib.sha3_224
<built-in function openssl_sha3_224>
```

**Comment by hroncok** [comment]
> Scope: When Python is linked against OpenSSL 1.1.1 or later, which is true on many modern systems, the OpenSSL provided `sha3` implementation will be used instead of the vulnerable bundled `_sha3` XKCP module code.

As far as I can see on Fedora, only Python 3.9+ reports `<built-in function openssl_sha3_224>`. Older Python versions, despite being linked against OpenSSL 1.1.1 or later are still vulnerable.

**Comment by mcepl** [comment]
> Scope: When Python is linked against OpenSSL 1.1.1 or later, which is true on many modern systems, the OpenSSL provided `sha3` implementation will be used instead of the vulnerable bundled `_sha3` XKCP module code.
> 
> You can tell if your Python 3.10 or earlier is vulnerable by doing the following:

I don’t think it is correct (at least for the enterprise maintainers dealing with archaeological excavations):

```python

stitny~$ python3.6
Python 3.6.15 (default, Sep 15 2021, 11:41:54) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>> import hashlib
>>> h = hashlib.sha3_224()
>>> hashlib.sha3_224
<class '_sha3.sha3_224'>
>>> h.update(b"\x00" * 1)
>>> h.update(b"\x00" * 4294967295)
fish: Job 1, 'python3.6' terminated by signal SIGSEGV (Address boundary error)
stitny~$ 
```

**Comment by msmeissn** [comment]
openssl sha3 delegation was added in commit d5b3f6b7f9f, which is 3.9 and later python I think.

**Comment by gpshead** [comment]
Our 3.7 and 3.8 branches will get the patch merged, see the PRs above. 3.6 is EOL but it is trivial to apply the change to older `_sha3` supporting releases for distributors with a need to do so on their own.

**Comment by vstinner** [comment]
I created https://python-security.readthedocs.io/vuln/sha3-buffer-overflow.html to track this vulnerability.

**Comment by gpshead** [comment]
Everything was merged. Closing. If you don't see this fix backported into your favorite OS distro that ships their own Python packages, reach out to that distro's security reporting process. Otherwise these will be part of the next planned regular patch releases of all impacted Python versions. https://peps.python.org/pep-0619/ for example. (there's a similar PEP for each version)
