### ISSUE TITLE
Issue #97562 was closed incorrectly.

### ISSUE THREAD

**Issue by aroberge** [python/cpython#98619]
In issue #97562, I gave an example showing that `code.interact()` was giving a `SyntaxError` whereas the normal Python interpreter was giving a `SyntaxWarning`. That issue was closed, indicating that a previous commit had essentially fixed it.  I cannot reopen a closed issue, but I did add a comment showing that the problem remains. Here's a copy:
```
> python
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> def test():
...    [1, 2, 3]()
...
<stdin>:2: SyntaxWarning: 'list' object is not callable; perhaps you missed a comma?
>>> test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in test
TypeError: 'list' object is not callable
>>> import code
>>> code.interact()
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> def test():
...    [1, 2, 3]()
  File "<console>", line 2
SyntaxError: 'list' object is not callable; perhaps you missed a comma?
```

**Comment by sweeneyde** [comment]
If I'm reading the discussion right, the [3.11](https://github.com/python/cpython/commits/3.11) git branch received the fix, commit https://github.com/python/cpython/commit/a386d1341c29b093ba496373934a4a58eb5dd342, but since we were already in the release candidate phase, in the interest of stability, most changes were not cherry-picked to apply to [v3.11.0](https://github.com/python/cpython/commits/v3.11.0), and instead will show up in the first bugfix release, 3.11.1.

**Comment by aroberge** [comment]
Ok, I wasn't aware of this. I'll monitor changes for 3.11.1, and I'll close this as irrelevant.
