### ISSUE TITLE
Use the same address in the example codes of "Using a remote manager"

### ISSUE THREAD

**Issue by saito828koki** [python/cpython#98638]
# Documentation

In the example codes of [Using a remote manager](https://github.com/python/cpython/blob/main/Doc/library/multiprocessing.rst#using-a-remote-manager), the client address is different from the server address. To make the example work correctly, the line
`m = QueueManager(address=('foo.bar.org', 50000), authkey=b'abracadabra')` 
should be changed to 
`m = QueueManager(address=('', 50000), authkey=b'abracadabra')`

**Comment by Jason-Y-Z** [comment]
Thanks for pointing this out. If I understand the docs correctly, it works as follows.
When we instantiate the `QueueManager` on our server, we **don't** need to specify the address because we are on the server already. 
When we instantiate `QueueManager` on our remote client, we **do** need to provide the address so that the client knows which address to "connect" to. We can contrast this against the local process example, where we **don't** need to provide the address since we are already at the same address.

**Comment by saito828koki** [comment]
@Jason-Y-Z Thanks for your quick response and clear explanation. Now I see what the docs say. I’ll close this issue.
