### ISSUE TITLE
list `__iadd__` casts string to list instead of throwing error

### ISSUE THREAD

**Issue by elliott-king** [python/cpython#98668]
# Bug report
I would expect the following to throw an error, but instead it casts the string to an array & concatenates it:

```python 
>>> a = []
>>> a += "hello"
>>> a
['h', 'e', 'l', 'l', 'o']
```

Directly calling the iadd function (example taken from [another issue](https://github.com/python/cpython/issues/90770#issuecomment-1093943911)) also does not throw an error:
```python
>>> a = []
>>> type(a).__iadd__(a, "hello")
['h', 'e', 'l', 'l', 'o']
```

## Expected behavior

```python
>>> a = []
>>> a = [] + "hello"
TypeError: can only concatenate list (not "str") to list
```

# Your environment

- MacOS 11.6.5 Big Sur
- `Python 3.10.4 (main, May 24 2022, 15:45:15) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin`

I also tried on various online Python editors, like w3schools & jupyter.

**Comment by ronaldoussoren** [comment]
The root cause for this is that ``a_list += value`` is an different way of spelling ``a_list.extend(value)`` and that method accepts an arbitrary iterable or iterator for value, including strings (which will then be interpreted as a sequence of characters).

List addition (``a_list + value``) does require that the other value is a list. 

IMHO the current behaviour is too entrenched to change at this point in time due to backward compatibility concerns.
