### ISSUE TITLE
Python 3.11 `re.compile` raises SRE code error for valid regex.

### ISSUE THREAD

**Issue by Waszker** [python/cpython#98740]
# Bug report

Following regex causes `re.compile()` to raise `RuntimeError: invalid SRE code`:
```python
   re.compile(
        r"(?P<h>^([01][0-9]|2[0-3]))"
        r"((?P<m>([0-5][0-9]))?"
        r"(?(5)(?P<s>([0-5][0-9]|60))?)"
        r"(?(7)(\.(?P<ms>([0-9]{1,6})?))?))$"
    )
```

# Your environment

Python 3.11

- CPython versions tested on: 3.11
- Operating system and architecture: Linux (docker image as well as virtualenv)

I've checked and this hasn't been an issue in all previous Python interpreter versions, starting from 3.6 (the oldest I've checked).
What's more the regex is correctly recognized and does not cause any issues in other regexp implementations, e.g. the online tool https://regex101.com/

I've already asked about this on [mailing list](https://mail.python.org/archives/list/python-dev@python.org/thread/NWXOPK5C4KTIHNVXVHSNHVFADTJCIE6N/) and confirmed that this is a bug.

@serhiy-storchaka has confirmed that the case for this bug has already been found.

* PR: gh-99045

* PR: gh-99046

**Comment by hroncok** [comment]
I've bisected this to f703c96cf08a0d65e718e7acfb043cbc49812a22

**Comment by serhiy-storchaka** [comment]
The simplified example is:
```python
re.compile('()()()()()()()(?(1)()?)')
```
It is caused by the fundamental flaw in the RE validation code which checks whether the last word in the "then" branch of the conditional expression matches opcode JUMP which was 16 in 3.10 and below and becomes 15 in 3.11. Unfortunately it matches the value of the *argument* of other opcode ("MARK 15") which means the end of the 8th capturing group.

The bug is not new. Even simpler example for 3.10 is:
```python
re.compile(r'()(?(1)\x10?)')
```
and for 3.10 and below:
```python
re.compile(r'()(?(1)\x0f?)')
```
No matter what is the value of the JUMP opcode, there is always an example which fails.

The solution of this issue will not be easy and may require changing semantic of some opcodes.
