### ISSUE TITLE
Mocking import_module() function causes all subsequent mocks to fail silently

### ISSUE THREAD

**Issue by miguelgrinberg** [python/cpython#98771]
# Bug report

This is a 3.11 regression. Here is the simplest example I could come up with to demonstrate the issue:

```python
from unittest import mock

def f():
    return 'not mocked'

with mock.patch('importlib.import_module') as import_module:
    with mock.patch('__main__.f', return_value='mocked'):
        print(f())
```

Here is the output under several Python versions:

```bash
$ python3.8 mocktest.py
mocked
$ python3.9 mocktest.py
mocked
$ python3.10 mocktest.py
mocked
$ python3.11 mocktest.py
not mocked
```

In case it helps, I've been looking through the commit list for mock.py and found that https://github.com/python/cpython/commit/ab7fcc8fbdc11091370deeb000a787fb02f9b13d is the first change that shows the broken behavior.

# Your environment

I'm using CPython 3.11.0 on Intel Mac.

```python
$ python3.11
Python 3.11.0 (main, Oct 26 2022, 10:08:00) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by ronaldoussoren** [comment]
I'm not sure if this is a bug, you're mocking ``importlib.import_module`` and then do something where a modern implementation would (and as of 3.11 does) use that function to find the module where name resolution should start. The code prints "not mocked" because ``mock.patch`` indirectly uses ``importlib.import_module`` and hence calls the mock object instead of the real implementation.

This worked in older versions of Python because those used a custom implementation of this functionality instead of relying on a public API for this.

**Comment by brettcannon** [comment]
I agree this isn't a bug for the reasons Ronald outlined.

Thanks for at least reporting this, @miguelgrinberg !
