### ISSUE TITLE
`int.from_bytes` crashes if `byteorder` is a string subclass

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#98783]
Here's a minimal reproduction:

```
» ./python.exe
Python 3.12.0a1+ (heads/main:bded5edd9a, Oct 27 2022, 23:29:21) [Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class SubStr(str): ...
... 
>>> int.from_bytes(b"0", SubStr("big"))
Assertion failed: (PyUnicode_CheckExact(str1)), function _PyUnicode_Equal, file Objects/unicodeobject.c, line 10447.
[1]    18466 abort      ./python.exe
```

I think this happes because of these lines: https://github.com/python/cpython/blob/bded5edd9abf7ae6b2874916d70ec29ad209217c/Objects/unicodeobject.c#L10444-L10453

`_PyUnicode_Equal` uses `assert(PyUnicode_CheckExact(...))`, while many function (including `int_from_bytes_impl`) use `PyUnicode_Check()` or just parse `str` objects from args.

https://github.com/python/cpython/blob/bded5edd9abf7ae6b2874916d70ec29ad209217c/Objects/longobject.c#L6167-L6170

Probably other functions that use `_PyUnicode_Equal` are also affected.

I would like to raise a question: shouldn't it be `assert(PyUnicode_Check(...))` in `_PyUnicode_Equal`?

I would like to send a PR with the fix!

**Comment by sobolevn** [comment]
CC @sweeneyde as blame owner

**Comment by sweeneyde** [comment]
> I would like to raise a question: shouldn't it be assert(PyUnicode_Check(...)) in _PyUnicode_Equal?

`_PyUnicode_Equal` was originally added as a part of https://github.com/python/cpython/commit/03768c4d139df46212a091ed931aad03bec18b57, for use in `COMPARE_OP_STR_JUMP` opcode, where it would have had the incorrect behavior for string subclasses, which could have `__eq__` overridden.

So it looks like that made [the switch from `_PyUnicode_EqualToASCIIId` to `_PyUnicode_Equal`](https://github.com/python/cpython/commit/81c72044a181dbbfbf689d7a977d0d99090f26a8#diff-1a6e70e2beeecad88840c67284ac4d54a36998029244771fcc820e801390726a) not an exact replacement.

Replacing the assertion seems reasonable to me, since `COMPARE_OP_STR_JUMP` checks exact types already, but I would want to double-check that that is equivalent to `_PyUnicode_EqualToASCIIId`.

**Comment by sweeneyde** [comment]
Related: https://github.com/faster-cpython/ideas/issues/486 would add back in a hash check for these cases, which would restore the hash check that was in `_PyUnicode_EqualToASCIIId`.

**Comment by sweeneyde** [comment]
There also seems to be a discrepancy between whether or not `_PyUnicode_Equal` can give an error. I don't think it ever can now, and it seems the lines you mention assume it doesn't, but there's this comment:

https://github.com/python/cpython/blob/3e07f827b359617664ad0880f218f17ae4483299/Include/cpython/unicodeobject.h#L948-L949

and this error check:

https://github.com/python/cpython/blob/3e07f827b359617664ad0880f218f17ae4483299/Python/ceval.c#L3422-L3425

At the time it was added, error checks were needed because PyUnicode_READY could fail. But since https://github.com/python/cpython/commit/f9c9354a7a173eaca2aa19e667b5cf12167b7fed, `PyUnicode_READY` is no longer necessary, and the check cannot fail.

I think it should be safe to delete the "Returns -1 on failure" comment and remove the NULL check in ceval.c.

**Comment by sobolevn** [comment]
Other places that crash because of this:
- `int.to_bytes`: the same as OP
- `type_repr`:

```
» ./python.exe       
Python 3.12.0a1+ (heads/main:bded5edd9a, Oct 27 2022, 23:29:21) [Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class A: ...
... 
>>> class SubStr(str): ...
... 
>>> A.__module__ = SubStr('ex')
>>> A
Assertion failed: (PyUnicode_CheckExact(str1)), function _PyUnicode_Equal, file Objects/unicodeobject.c, line 10447.
[1]    21783 abort      ./python.exe
```

- `type_new_visit_slots` and `type_new_copy_slots`

```
>>> class SubStr(str): ...
... 
>>> class A:
...    __slots__ = (SubStr('a'),)
... 
Assertion failed: (PyUnicode_CheckExact(str1)), function _PyUnicode_Equal, file Objects/unicodeobject.c, line 10447.
[1]    21853 abort      ./python.exe
```

- `super_getattro`
- Probably `write_unraisable_exc_file`, but I cannot reproduce it
- `print_exception_message`

**Comment by sweeneyde** [comment]
Thanks for finding and fixing this!

I went ahead and opened https://github.com/python/cpython/issues/98879 about the error handling.
