### ISSUE TITLE
What is formal definition of "Future-like"? (_asyncio_future_blocking)

### ISSUE THREAD

**Issue by dlech** [python/cpython#98935]
# Documentation

https://docs.python.org/3/library/asyncio-future.html#asyncio.isfuture

The link above describes:

> a Future-like object with a _asyncio_future_blocking attribute.

However, it doesn't say exactly what constitutes "Future-like".

Since `asyncio.Task` and `asyncio.Future` both fit this test, I'm assuming it is the set (or a subset?) of the methods shared by both of these classes.

| method | Future | Task |
| - | - | - |
| result | ✅ | ✅  |
| set_result | ✅  | |
| set_exception | ✅ | |
| done | ✅ | ✅  |
| cancelled | ✅ | ✅  |
| add_done_callback | ✅ | ✅  |
| remove_done_callback | ✅ | ✅  |
| cancel | ✅  | ✅  |
| exception | ✅ | ✅  |
| get_loop | ✅ | | 
| get_stack | | ✅ |
| get_name| | ✅ |
| set_name| | ✅ |
| get_stack | | ✅ |
| uncancel| | ✅ |
| cancelling| | ✅ |

Asking because I have a custom awaitable object that was being passed to `asyncio.wait()` that worked in the past but broke in Python 3.11 because is is missing a `add_done_callback()` method.

So...

1. Can we get a formal definition in the docs?
2. Taking it one step farther, should there be a `typing.Protocol` for "Future-like"?

**Comment by dlech** [comment]
After more experimenting, it looks like `get_loop()` is also a required method in addition to the methods shared by both Future and Task.

**Comment by kumaraditya303** [comment]
> However, it doesn't say exactly what constitutes "Future-like".

Future-like means duck type of `asyncio.Future`, it should have all the methods but doesn't need to subclass `asyncio.Future`.

> Taking it one step farther, should there be a typing.Protocol for "Future-like"?

That's a question for the typing folks. @AlexWaygood @gvanrossum?

**Comment by gvanrossum** [comment]
I'm guessing that the OP's concern is that duck typing is often imperfectly defined. As another example, we often used to state (maybe we still do in some places) that some API expects a "file-like" object without specifying which methods were actually needed -- often all that was used was `write()` or `readline()`, and occasionally there were similar disappointments when a newer implementation of the API started using an additional method (e.g. `read()`).

The term Future-like is definitely meant to refer to a duck type for `asyncio.Future`, and I think it's unsafe to expect any of the current methods to be optional. In particular, `add_done_callback()` is a pretty fundamental method for Futures, so the OP was always skating on thin ice. I'm unsure where the OP got the data for their table -- e.g. they list `get_loop()` as missing from `Task`, but when I try it (in 3.10) that method is present. Same for `set_result()` and `set_exception()`, although you probably shouldn't call them, since these are supposed to be set implicitly by the task machinery based on when the coroutine running in the task exits.

As to whether we will add a "Future-like" protocol to typeshed, I don't think that that would purely backwards compatible, and it would certainly be a big effort (everything that is currently declared to take a Future would have to be changed to take a Future-like instead) and could well be disruptive due to the subtle differences between classes and protocols. (For similar reasons we don't dare upgrade Sequence or Mapping to protocols.)

Sorry there isn't better news. Hopefully this answers your questions, @dlech. Feel free to close this issue.

**Comment by dlech** [comment]
> I'm unsure where the OP got the data for their table

From [the official Python docs](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task). It does mention that Task is Future-like but doesn't explicitly list all of the methods.

> Same for `set_result()` and `set_exception()`, although you probably shouldn't call them

Which explains why they are omitted from the Task docs.

Thanks both for the feedback. I also found a few useful comments in the Python source code to help understand what is expected as well. Making a Future-like without using asyncio.Future as a base is a rare thing, so adding something to the docs about it would probably just make things more confusing for those that don't need to worry about it, so I'll go ahead and close the issue.

(For the curious, I've been working on Python bindings for the Windows WinRT APIs which have an IAsyncOperation which is analogous to a Python asyncio.Future)

**Comment by gvanrossum** [comment]
Looking forward to that WinRT library!

**Comment by dlech** [comment]
> Looking forward to that WinRT library!

https://pypi.org/project/winsdk/
