### ISSUE TITLE
Removing element from list while operating cause inconsistency on iteration

### ISSUE THREAD

**Issue by andreamisu** [python/cpython#98983]
# Bug report

Removing elements from a list while iterating using in operator will results in skipping the element after the removed one. 

# Your environment

- CPython versions tested on: 3.10, 3.11
- Operating system and architecture: Linux, x86_64

Reproducer: 
```
x = list(range(0,10))
for i in x:
    print(i)
    if i == 5:
        x.remove(i)
```

will generate
```
0
1
2
3
4
5
7
8
9
```

Expected code should include number 6 in results.

**Comment by eryksun** [comment]
This is the expected behavior. A list is iterated by index. Calling `remove(5)` shifts the index range of the subsequent items (i.e. integers 6 to 9) to index values 5 to 8, but the next index in the iteration is still 6 (i.e. integer 7). The workaround is to iterate a shallow copy such as `x[:]`. Then you're free to modify the contents of the source list `x`.

**Comment by pochmann** [comment]
This issue tracker is for *Python's* bugs. This is *your* bug.
