### ISSUE TITLE
Weird graphical bug with Tk

### ISSUE THREAD

**Issue by Skilowi** [python/cpython#99131]
- CPython versions tested on: 3.8.10
- Operating system and architecture: Linux Mint 20.3 x86_64

Thonny IDE is using Tk, and i am having weird graphical bugs, and he sent me here, cause that bug i also had in IDLE
https://github.com/thonny/thonny/issues/2507#issuecomment-1283485759

Here is my neofetch, may be useful

![196231497-7f4e9fd8-f5d7-4a2d-9626-8a84279ba3fc](https://user-images.githubusercontent.com/76708049/200124723-8ad27086-b6e3-416f-92bc-2401cbbcf656.png)

Link to video with that bug:

https://streamable.com/x230jn

sadly - this time i couldnt reproduce it in IDLE, so Thonny footage only :/

**Comment by serhiy-storchaka** [comment]
Could you please describe your problem in words?

**Comment by chrstphrchvz** [comment]
My guess is that the screen recording is trying to show how tooltip windows appearing and disappearing causes various flashing/flickering artifacts to appear and persist, impairing usability.

Because Compiz is active (as reported by neofetch, and from the effects seen when closing a window), I wonder if this issue is still present when a different window manager is used. But this looks like an issue which neither Tkinter nor Tcl/Tk could do something about, even if the same issue has not been observed in other X11 programs. It looks more like an issue either in Compiz or something else in the graphics stack (e.g. mesa, X11, hardware driver, or hardware itself), however I am not knowledgeable on how such an issue should be investigated further.

**Comment by serhiy-storchaka** [comment]
Thank you @chrstphrchvz. Then this issue has nothing to do with Python.
