### ISSUE TITLE
Elide uninformative traceback indicators in `return` and simple assignment statements

### ISSUE THREAD

**Issue by Zac-HD** [python/cpython#99180]
The new traceback indicators can be *really* nice, though at times also quite verbose.  #93883/#93994 by @belm0 improved this situation by skipping the indicators for lines where the *entire* line was indicated, which helps substantially.  I'd like to propose that we take this a small step further:

- Skip indicators for lines with a `return` statement, where every part execpt the `return` keyword is indicated; e.g. `return foo()`
- Skip indicators for lines with a simple assignment statement, where the entire rhs is indicated and the lhs consists of a simple name; e.g. `name = some.more(complicated, call=here)`

These heuristics are slightly more complicated than "don't indicate the entire line", but I argue that in each of these cases the indicators add little to no information, while compressing the traceback makes it easier to navigate and draws attention to the remaining more-specific indicators.

My motivating example is the traceback reported in https://github.com/pytest-dev/pytest/issues/10466, where I count seven already-elided indicator lines, twelve that would be elided by the return heuristic, seven by the simple-assignment heuristic, and four other lines where the indicators would not be affected by this proposal.  I'd even argue that dropping uninformative indicators from a majority (19/30) of traceback lines could be considered a bugfix - indicating on 4/30 lines is quite different to 23/30!

### Linked PRs
* gh-112670
* gh-119554
* gh-119556

**Comment by iritkatriel** [comment]
CC @pablogsal

**Comment by pablogsal** [comment]
Thanks a lot for raising these @Zac-HD! I think both of this make sense.

I am a bit wary of complicating the already-complex machinery to detect and deal with the ranges even more because the code is becoming a bit complex to maintain but I can give it a go to see how it looks. Also, we have a bunch of in-flight PRs for this area already so we need to land them before attempting anything here.

I have been thinking about all of this and I think the long term solution may be to use colors if possible instead of underlining the ranges with extra characters. This way we save lines and reduce clutter. If colors would be used in the situations you highlight would this have been acceptable?

**Comment by Zac-HD** [comment]
I think colors would be overridden by the pytest error machinery, as well as much of our logging infra at work, so that would be equivalent to disabling range indicators entirely.  That would certainly solve the problem of uninformative indicators, but at the cost of losing useful information too!

**Comment by pablogsal** [comment]
In any case I created https://github.com/python/cpython/pull/112670 in case other core devs think otherwise.

@isidentical @lysnikolaou opinions?

**Comment by lysnikolaou** [comment]
@pablogsal Would it be feasible to only skip the highlights if the highlighted section spans the entire `return` statement (or the entire `rhs`) and *only one highlighting character is used*? This might be a good compromise since it'd still display helpful info when needed (two chars), but the motivating example would still get some benefit from it.

**Comment by pablogsal** [comment]
> @pablogsal Would it be feasible to only skip the highlights if the highlighted section spans the entire `return` statement (or the entire `rhs`) and _only one highlighting character is used_? This might be a good compromise since it'd still display helpful info when needed (two chars), but the motivating example would still get some benefit from it.

Yes, but this still will not cover the OP cases because now we use two characters in many places, including calls. For example:

```
return baz(1)
       ~~~^^^
```

**Comment by lysnikolaou** [comment]
Hmm, I'm +1 for keeping it as is then. Requiring the user to deduct that the last call of the line is the one failing, if no carets are there, sounds like bad experience.

**Comment by pablogsal** [comment]
Another thing to do is explore the entire AST and do this ONLY if there is a single call where the callable is a simple name

**Comment by lysnikolaou** [comment]
> Another thing to do is explore the entire AST and do this ONLY if there is a single call where the callable is a simple name.

Oh yes, that achieves what I was trying to achieve above.

> But this is more computation at error time which I am not super happy about.

This is true, but it isn't *much* more computation, and we've always been happy to sacrifice a bit of time for better errors UX, right? Although it's up to you to decide whether it's too much.
