### ISSUE TITLE
Debug c++ extension initiated from a Python venv

### ISSUE THREAD

**Issue by axelande** [python/cpython#99501]
Before Python3.8 it was possible to create a `venv` and debug c++ extensions with Visual Studio.

To test the issue follow the [Microsoft tutorial on creating c++ python extensions](https://learn.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2022) this works when you run e.g. Python3.10 from its installed path (as described in the tutorial). This was also possible with from a `venv` created with Python3.7, but not with Python3.8 and forward.

Discussed in the end of: https://github.com/MicrosoftDocs/visualstudio-docs/issues/8621
Posted a question here: https://stackoverflow.com/questions/74421151/debug-a-c-python-3-10-extension-venvlauncher-pdb-missing

- CPython versions tested on and operating system and architecture:
Windows 10, Python3.8-64, Python3.9-64 and Python 3.10-64

**Comment by zooba** [comment]
I haven't tried it myself, but you may need to enable attaching to child processes? I thought that was the default in Visual Studio, but I guess it could have changed.

A possible workaround for you could be to create your venv with `--symlinks`, which will require symlinks to be enabled, but since you've probably got Developer Mode enabled then they probably are.

**Comment by axelande** [comment]
Thanks for the suggestion! It works to debug native c++ extensions with `--symlinks` from a `venv` in Python3.10!
