### ISSUE TITLE
Alias for chain.from_iterable

### ISSUE THREAD

**Issue by ShivKJ** [python/cpython#99715]
# Feature or enhancement

```python
from itertools import chain

data = [[1, 2],[3, 4]]
print(list(chain.from_iterable(data))) # prints [1, 2, 3, 4]
```

It will be good to have an alias `flatten` in module `itertools` for `chain.from_iterable` as it is more readable. Term `flatten` also fits well.

So equivalent code with `flatten` will be,

```python
from itertools import flatten

data = [[1, 2],[3, 4]]
print(list(flatten(data))) # prints [1, 2, 3, 4]
```
# Pitch

The alias `flatten` is more intuitive term than `chain.from_itertools`

# How to do this

By adding, `flatten = chain.from_iterable` in `itertools` module.

**Comment by stevendaprano** [comment]
I disagree that this would be an enhancement, or that "flatten" is a good description for what `chain.from_iterable` does. This would just use up the name "flatten" and prevent us from using that name for a proper `flatten` function. For some definition of "flatten" -- the problem is that there are many varieties of flatten.

See, for example:

https://code.activestate.com/recipes/578948-flattening-an-arbitrarily-nested-list-in-python/
https://code.activestate.com/recipes/578092-flattening-an-arbitrarily-deep-list-or-any-iterato/

**Comment by rhettinger** [comment]
Thanks for the suggestion but we will decline.
