### ISSUE TITLE
Threading target bug cause .start() not return

### ISSUE THREAD

**Issue by billwyy** [python/cpython#99711]
import threading
import time
def test():
  while True:
    print('test1')
    time.sleep(1)
  return
t1 = threading.Thread(target=test(), args=())
t1.start()
print('test2')

This program will print 'test1' every second while never print 'test2'.
I spend hours to find the mistake. There is no any warning or mistake from Pycharm
with python version 3.9.
If possible to fix this bug in future and give some warning?
People always made mistake:-(

**Comment by billwyy** [comment]
I tried again and I should blame Pycharm also, because when I copy paste code from internet and delete target name and try input my name then Pycharm will auto fill and add () if I press "enter" on keyboard:-(

**Comment by ericvsmith** [comment]
This tracker is for reporting bugs in Python. This isn't the correct place to ask for help. You should ask this question on https://discuss.python.org/c/users/7

**Comment by billwyy** [comment]
It's a bug really, and I am not asking for help. I am requesting for improvement.
python should give warning.

**Comment by stevendaprano** [comment]
This is not a bug in Python, this is user error: it is a bug in *your* code, not the language or the threading library. There's nothing we can do about this.

Your mistake was that you called the `test` function, instead of passing the function as an argument. So the interpreter does **exactly what you told it to do:** it calls the function, which enters an infinite loop and never returns.

It is impossible for Python to solve your bug. There is no way for the interpreter to know that you meant to pass `test` but accidentally passed `test()`, it cannot read your mind, and it cannot know that the function is an infinite loop (google on "Halting Problem" to see why) or that the function doesn't eventually return a valid target.

As @ericvsmith says, this is not the right place for asking for help with fixing your code. Please take any additional questions to the Python Discuss, or one of the mailing lists.
