### ISSUE TITLE
Handle no arguments when using sub-commands in argparse

### ISSUE THREAD

**Issue by ppaez** [python/cpython#99735]
# Documentation

The example that shows the use of sub-commands and set_defaults to dispatch a function for each sub-command, fails when there are no command line arguments:

`AttributeError: 'Namespace' object has no attribute 'func'`

A pull request is provided that adds one line to handle that case and  an explanation in the documentation.

### Linked PRs
* gh-99736
* gh-100927
* gh-102036
* gh-102037

**Comment by hpaulj** [comment]
Originally `subparsers` were required, so this issue did not come up.  Because of a patching oversight, they are now optional, and we had to add the `required` parameter.  I think this example would be better handled with a

     subparsers = parser.add_subparsers(required=True)

Then we wouldn't have to define a `func` for the no-subparser case.  Your patch works, but I think it adds too much to the text and example, detracting from the essence of what `set_defaults` adds.

Whether we use `set_defaults` or not, the Namespace will have different attributes depending on what subparser (or none) the user invokes.  The post parsing code has to handle that issue in one way or the other.

**Comment by ppaez** [comment]
I hadn't used the ``required=True`` parameter before. It is mentioned in the reference, but I didn't consider it.  I also was not aware of those changes ([bpo-9253](https://github.com/python/cpython/issues/53499) and [bpo-26510](https://github.com/python/cpython/issues/70697)), thanks for explaining them.

PR #100927  has been created with only that change.

**Comment by erlend-aasland** [comment]
Can we close this issue?

**Comment by hauntsaninja** [comment]
Yes we can! The backports had a hiccup, but they're all done now
