### ISSUE TITLE
Parse expressions containing `'`/`"` inside f-strings correctly

### ISSUE THREAD

**Issue by Timwi** [python/cpython#99746]
# Bug report

The code

```py
f'{'foo'}'
```

does not parse correctly. The following error occurs:

```
    f'{'foo'}'
        ^
SyntaxError: f-string: expecting '}'
```

Another, more realistic example:

```py
f'List of people: {', '.join(f'{p.name} ({p.age})' for p in people)}'
```

Error produced:

```
    f'List of people: {', '.join(f'{p.name} ({p.age})' for p in people)}'
                        ^
SyntaxError: f-string: expecting '}'
```

Expected behavior is for the nested expression to be parsed correctly. The parser should correctly translate the above example to code that is equivalent to

```py
'List of people: {}'.format(', '.join(f'{p.name} ({p.age})' for p in people))
```

**Comment by ericvsmith** [comment]
This is a known and deliberate limitation due to the simplistic nature of the current f-string parser. There is a proposal to change the parser to use the PEG parser, at which point we can consider removing this restriction. For some details, see https://pyfound.blogspot.com/2022/05/the-2022-python-language-summit-f.html?m=1

I can't find any documentation on this restriction. It should either be added or made more obvious if it already exists.

Since this is being developed and tracked elsewhere, I'm going to close this issue. Maybe @pablogsal can point to where it's being developed.

**Comment by pablogsal** [comment]
We are finishing drafting a pep so details will be posted soon :)
