### ISSUE TITLE
`python -m venv ...` on windows hardcodes the virtual_env path in `activate.bat`

### ISSUE THREAD

**Issue by Pomax** [python/cpython#99758]
# Bug report

When creating virtual environments using `python -m venv some_name` on Windows, the `Scripts\activate.bat` that gets created hard-codes the virtual environment directory path rather than using the command line syntax, which means that the project will break if:

- your drive letter ever changes, or
- you ever rename or move your project dir, or
- you ever push it to source control with dependencies (plenty of legitimate reasons for that) and someone checks out the code to the same dir but in a different parent dir, or
- you do anything, really, that may change the absolute project path.

# How to fix it

Rather than hard-coding the virtual env path:

```bat
set VIRTUAL_ENV=the absolute path when "python -m venv" was invoked
```

generate the following code instead:

```bat
set VIRTUAL_ENV=%~dp0\..
```

This uses the [Batch parameter](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/call#batch-parameters) for "whatever the dir is that this .bat file lives in", and then takes us up one dir to the virtual environment's root, thus solving a whole bunch of problems related to "the venv dir no longer lives where it did when it was created and now python can't even run this code" =)

(Note that the `activate.ps1` script already does this using PS-specific syntax, so no fixes are required for Powershell users)

# Your environment

The only relevant environment aspect here is that this is specific to using the command liner (`cmd`) on the Windows operating system.

**Comment by ericvsmith** [comment]
Virtual environments are not relocatable. See the warning box at https://docs.python.org/3/library/venv.html#how-venvs-work.

**Comment by Pomax** [comment]
Except they are, _when you do this_

**Comment by ericvsmith** [comment]
If you believe that this covers all cases of both activated and non-activated environments, I suggest you write the tests to demonstrate that it works, and it would probably be accepted. You should bring it up on https://discuss.python.org/c/ideas/6 first, in order to get some feedback.

**Comment by Pomax** [comment]
that would require me knowing C, and it doesn't even have to cover all cases: it just needs to do "the same that activate.ps1 does" because if you want me to rename this as "bug: activate.bat doesn't do what activate.ps1 does", then I'll do that if it means this can get fixed by someone with a spare few minutes and a knowledge of the codebase.

**Comment by ericvsmith** [comment]
Personally, I don't think we should change this, because we don't want to have to support this use case in the future. That is, we don't want to constrain ourselves to changes that continue to support this limited relocation case. But that's just me. If some core dev wants to take it on, I of course won't stop them.

**Comment by Pomax** [comment]
In that case bad news: like I mentioned, activate.ps1 _already does this_ so either `activate.bat` and the bash `activate` are updated to behave better, or `activate.ps1` gets made worse. Either way, they're not doing the same thing right now.

Also note that the idea that "we don't want to support this use case" is literally already covered by the documentation you pointed out, so if you don't want to update it, just keep those docs saying that venvs can't be reliably moved, update the activation scripts so that they don't actively break moving a venv at least, and then Stackoverflow deal with it when users move their venv, but they hit an edge case. Most folks won't. For most folks, fixing this will solve a problem that doesn't need to exist.

**Comment by brettcannon** [comment]
While I understand the desire for relocatable virtual environments, they are simply not designed for this. For instance, paths are hard-coded in `pyvenv.cfg`, so this goes beyond the activation scripts. This is all on purpose to keep the design simple.

And the only reason `Activate.ps1` doesn't hard-code the paths is because we sign that PowerShell script so you don't have to elevate to the more permissive level to run it (you can actually be one level lower in permissions). If PowerShell's security mechanism didn't make things harder we then would (still) generate the `.ps1` file with the paths hard-coded for simplicity.

As such, I'm unfortunately going to be rejecting this feature request.

**Comment by Pomax** [comment]
To be fair: that might have made sense in the past, but I've seen so many SO questions about this topic by now that it feels like it might be time to get one or two folks to actually finally fix this. A virtual env should be relocatable in 2023 =(
