### ISSUE TITLE
Speed-up list.sort()

### ISSUE THREAD

**Issue by alantudyk** [python/cpython#99763]
I implemented for Ruby radix_sort inside Array#sort (https://github.com/ruby/ruby/pull/6796), perhaps similar thing could be implemented in Python.

@tim-one ?

**Comment by StephDC** [comment]
How do you think radix sort would work for arbitrary data (objects of any type) type with user-defined comparison function that may not necessarily map stuff to integers?

I believe those who need faster sort speed and are sorting a given limited data type is already going NumPy instead of here. This list.sort may really have to be comparison-based instead of radix sort or even counting sort for the sole purpose of supporting user-defined object and user-defined comparison function.

**Comment by tim-one** [comment]
Python sorts lists of objects. There is no protocol mapping objects to/from bitstrings to which a radix sort could be applied. The only method objects have to supply to be sortable is `__lt()__`.

You usually could, with more or less effort, craft such a mapping for a specific kind of object, but there's no general approach.

So, no, this is unpromising for Python. As @StephDC  said, some popular extension modules do implement different sorting routines for very specific, limited kinds of objects (like `numpy` vectors containing IEEE-754 double precision floats). CPython won't be competing with them 😉.
