### ISSUE TITLE
I tried "import cPickle as Pickle" and "import pickle" on IDLE and  it didn't work, can I get some help?

### ISSUE THREAD

**Issue by Brykon0423** [python/cpython#99857]
So this is part of my file:

#### Imports
import pickle<----This is where I'm having problems
import os.path

#### Constants
SAVE_FILE_NAME = "address_book.pickle"
INSTRUCTIONS = """Address Book Application
(Python For Kids For Dummies Proj. 9)
Press:
a to add an entry
d to display a list of all entries in summary form
i to print these instructions again
q to quit
"""

and import pickle isn't working. I've tried multiple times and the restart window look like this:

======== RESTART: C:\Users\Brysen\AppData\Local\Programs\Python\Python310\AddressBook.py ===============

**Comment by terryjreedy** [comment]
IDLE is only relevant if the behavior of your code is different than it is when you run the exact same code directly with python instead of through IDLE (which also executes your code with python).

Try `import pickle` in both IDLE Shell and interactive Python.  If there is an error, post the entire traceback between triple backtick lines (\`\`\`).   Or run `py C:\Users\Brysen\AppData\Local\Programs\Python\Python310\AddressBook.py` on a command line.

**Comment by Brykon0423** [comment]
Thank You, I'll try it!

**Comment by Brykon0423** [comment]
> 

It didn't work.

**Comment by terryjreedy** [comment]
What did not work?  Please reread what I wrote.

**Comment by Brykon0423** [comment]
How do I do the last one: py C:\Users\Brysen\AppData\Local\Programs\Python\Python310\AddressBook.py? I'm having trouble with it.

**Comment by zware** [comment]
Please use the [Python Discourse](https://discuss.python.org/c/help/7) to get help with usage and learning.

At a guess, did you name one of your own files `pickle.py`?  It looks like you may have saved your `AddressBook.py` in your Python install location rather than somewhere in your own documents, and if you created your own `pickle.py` in the wrong place that could be causing your issue (though it's hard to say without seeing what error you are actually getting).  But please continue on Discourse (linked above) rather than here :)
