### ISSUE TITLE
bug report 

### ISSUE THREAD

**Issue by oque111** [python/cpython#99921]
ydev debugger: CRITICAL WARNING: This version of python seems to be incorrectly compiled (internal generated filenames are not absolute)
pydev debugger: The debugger may still function, but it will work slower and may miss breakpoints.
pydev debugger: Related bug: http://bugs.python.org/issue1666807

**Comment by hugovk** [comment]
Please can you give us more information about what you did, what you expected to happen, and what actually happened, together with what you used?

Here's the instructions from the template:

---

  If you're new to Python and you're not sure whether what you're experiencing is a bug, the CPython issue tracker is not
  the right place to seek help. Consider the following options instead:

  - reading the Python tutorial: https://docs.python.org/3/tutorial/
  - posting in the "Users" category on discuss.python.org: https://discuss.python.org/c/users/7
  - emailing the Python-list mailing list: https://mail.python.org/mailman/listinfo/python-list
  - searching our issue tracker (https://github.com/python/cpython/issues) to see if
    your problem has already been reported

# Bug report

A clear and concise description of what the bug is.
Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

Include as many relevant details as possible about the environment you experienced the bug in -

- CPython versions tested on:
- Operating system and architecture:


You can freely edit this text. Remove any lines you believe are unnecessary.

**Comment by oque111** [comment]
I’m using windows 10 pro
Using python 3.11
My idle is py charm community edition
The issue is the version of python  “This version of python seems to be incorrectly compiled (internal generated filenames are not absolute)
pydev debugger: The debugger may still function, but it will work slower and may miss breakpoints.
pydev debugger: Related bug: http://bugs.python.org/issue1666807”
-------------------------------------------------------------------------------
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
