### ISSUE TITLE
ctypes.util.find_library support on WASM platforms

### ISSUE THREAD

**Issue by ryanking13** [python/cpython#99948]
# Bug report

`ctypes.util.find_library` doesn't work on WASM platforms like emscripten, wasi.
There is no condition that handles `sys.platform in ('emscripten', 'wasi')`, and it always returns None since the subprocess module is not available in WASM platforms.

# Your environment

- CPython versions tested on: 3.11.0 Emscripten build from: https://github.com/tiran/cpython-wasm-test
- Operating system and architecture: Chrome 108.0.5359.71

### Linked PRs
* gh-99950
* gh-138519
* gh-139022

**Comment by brettcannon** [comment]
I actually think this is the right outcome. You can't find an appropriate library that will work with ctypes under WASI since nothing will work (dynamic loading isn't supported), so always returning `None` makes sense to me. As such, I'm closing this. If you think I'm missing something, though, I can reopen to discuss it further.

**Comment by ryanking13** [comment]
@brettcannon Thank you for remembering this issue. I opened this issue with more of an Emscripten use in mind than WASI, but I agree that Emscripten is currently an unsupported platform anyway, and would be difficult to add until it becomes a tier 3 platform again.

FYI, Pyodide is [patching ctypes.util.find_library](https://github.com/pyodide/pyodide/blob/0.27.0a2/cpython/patches/0002-Add-emscripten-platform-support-to-ctypes.util.find_.patch) to support a few packages.
